### PR TITLE
Fix external ABI type name for contracts

### LINKED ISSUE #6435: Incorrect topic[0] hash for Library events that use a contract's name instead of address type
Probably related to #6001 

## Description
When hashing for the topic[0] of an event, solidity uses the name of the contract rather than `address`

## Environment
Compiler version: 0.5.7 stable
Framework/IDE: Truffle
Steps to Reproduce
Given:
```
pragma experimental ABIEncoderV2;
import { AnotherContract } from "./AnotherContract.sol";
library LibName {
    event Loggy(uint256 aNumber, AnotherContract anAddress);
    ...
        AnotherContract contractInstance = AnotherContract(someGivenAddress);
        emit Loggy(0, contractInstance);
    ...
}
```
`Loggy` has a `topic[0]` of: `keccak256("Loggy(uint256,AnotherContract)")`
but it should be: `keccak256("Loggy(uint256,address)")`

**The abi seems to contain the correct hash**, but the actual bytecode seems to be wrong

### PR DESCRIPTION
**Pull request by Marenz**
I hope this is the right way to fix this ..

fixes #6435

### CODE REVIEW

**Comment by chriseth** [comment]
Hm, I'm not sure this is the correct fix. `ContractType::interfaceType` correctly returns address in the non-library case. Perhaps the flag for that function is not set correctly when it is called?

**Comment by Marenz** [comment]
As far as I understood the code, the name is generated from https://github.com/ethereum/solidity/blob/develop/libsolidity/ast/Types.cpp#L3148
I don't see where the function `ContractType::interfaceType` is used for this

**Comment by ekpyron** [comment]
@Marenz To see where ``ContractType::interfaceType`` is used: In the line you're linking ``_t`` stems from ``parameterTypes`` which is the parameter types of the ``interfaceFunctionType()`` of the function type, which is the ``ìnterfaceType``s of the function's paramter... however ``interfaceFunctionType()`` doesn't get the local ``inLibrary`` in ``externalSignature`` passed down, so it calls ``interfaceType(true)`` instead of ``interfaceType(false)``... does that help?

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -3139,13 +3139,13 @@ string FunctionType::externalSignature() const
...
 	bool const inLibrary = kind() != Kind::Event && dynamic_cast<ContractDefinition const&>(*m_declaration->scope()).isLibrary();
-	FunctionTypePointer external = interfaceFunctionType();
-	solAssert(!!external, "External function type requested.");
-	auto parameterTypes = external->parameterTypes();
-	auto typeStrings = parameterTypes | boost::adaptors::transformed([&](TypePointer _t) -> string
+	auto typeStrings = m_parameterTypes | boost::adaptors::transformed([&](TypePointer _t) -> string
 	{
-		solAssert(_t, "Parameter should have external type.");
-		string typeName = _t->signatureInExternalFunction(inLibrary);
+		auto const& _it = _t->interfaceType(inLibrary);
```
Comment (ekpyron) [inline libsolidity/ast/Types.cpp]:
```suggestion
		auto const& it = _t->interfaceType(inLibrary);
```

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -3139,13 +3139,13 @@ string FunctionType::externalSignature() const
...
+		solAssert(_it.get(), "Parameter should have external type.");
```
Comment (ekpyron) [inline libsolidity/ast/Types.cpp]:
```suggestion
		solAssert(!!it, "Parameter should have external type.");
```
(not sure about the ``!!`` myself, but it's used a lot...)

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -3139,13 +3139,13 @@ string FunctionType::externalSignature() const
...
+
+		string typeName = _it.get()->signatureInExternalFunction(inLibrary);
```
Comment (ekpyron) [inline libsolidity/ast/Types.cpp]:
```suggestion
		string typeName = it->signatureInExternalFunction(inLibrary);
```

**Review by ekpyron — COMMENTED** [review]
Some style remarks.
And I wonder whether we should add a comment to ``interfaceFunctionType()`` where the parameters are transformed using ``interfaceType`` stating that if one edit's that one likely has to edit ``externalSignature`` as well, just to be sure.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (Marenz) [reply libsolidity/ast/Types.cpp]: that doesn't actually compile. I'd need to use `!!it.get()`

**Comment by ekpyron** [comment]
Thinking about it: maybe we should extract the transformation of the parameter types via ``interfaceType(...)`` into a function (like ``interfaceParameterTypes(bool)``) that can be used from ``externalSignature`` and from ``interfaceFunctionType`` alike? That'd ensure that nobody changes one without the other...

**Comment by Marenz** [comment]
Sounds good to me

**Comment by Marenz** [comment]
Updated according to suggestions

**Comment by Marenz** [comment]
Note: I used `std::move()` first, but had to remove it again because

```
/root/project/libsolidity/ast/Types.cpp:162:9: error: moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
        return std::move(transformed);
               ^
/root/project/libsolidity/ast/Types.cpp:162:9: note: remove std::move call here
        return std::move(transformed);
```

File: libsolidity/ast/Types.cpp [hunk 4]
```diff
@@ -147,6 +147,21 @@ bool fitsIntoBits(bigint const& _value, unsigned _bits, bool _signed)
 	));
 }
 
+TypePointers transformParametersToExternal(TypePointers const& _parameters, bool _inLibrary)
+{
+	TypePointers transformed;
+
+	for (auto type: _parameters)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]:
```suggestion
	for (auto const& type: _parameters)
```

File: libsolidity/ast/Types.cpp [hunk 5]
```diff
@@ -147,6 +147,21 @@ bool fitsIntoBits(bigint const& _value, unsigned _bits, bool _signed)
...
+	{
+		if (auto ext = type->interfaceType(_inLibrary).get())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]:
```suggestion
		if (TypePointer ext = type->interfaceType(_inLibrary).get())
```

otherwise, the `.get()` looks like the `.get` function on shared_ptr and thus it might seem like `ext` is a raw pointer.

File: libsolidity/ast/Types.cpp [hunk 6]
```diff
@@ -147,6 +147,21 @@ bool fitsIntoBits(bigint const& _value, unsigned _bits, bool _signed)
...
+			transformed.push_back(ext);
+		else
+			return {};
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Callers of this function cannot easily distinguish between an error case and an invocation on the empty vector. Why not use a `Result<TypePointers>` and also hand over the error message from the `interfaceType` call?

File: libsolidity/ast/Types.cpp [hunk 7]
```diff
@@ -2906,23 +2921,18 @@ FunctionTypePointer FunctionType::interfaceFunctionType() const
 	solAssert(m_declaration, "Declaration needed to determine interface function type.");
 	bool isLibraryFunction = dynamic_cast<ContractDefinition const&>(*m_declaration->scope()).isLibrary();
 
-	TypePointers paramTypes;
-	TypePointers retParamTypes;
+	TypePointers paramTypes =
+		transformParametersToExternal(m_parameterTypes, isLibraryFunction);;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Double `;`

**Comment by Marenz** [comment]
Update to fix comments

**Comment by chriseth** [comment]
Needs a changelog entry.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 8]
```diff
@@ -15607,6 +15607,38 @@ BOOST_AUTO_TEST_CASE(contract_name)
...
+				emit Deposit(a, _id, msg.value);
+			}
+		}
+		contract Test {
+			function f() public {
+				ClientReceipt.deposit("123");
+			}
+		}
+	)";
+	compileAndRun(sourceCode, 0, "Another");
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp]: Why do you need to compile this?

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 9]
```diff
@@ -15607,6 +15607,38 @@ BOOST_AUTO_TEST_CASE(contract_name)
...
+	compileAndRun(sourceCode, 0, "ClientReceipt", bytes(), map<string, Address>{{"Another", m_contractAddress}});
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp]: `Another` is not a library, so you do not need to provide linking information here.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 10]
```diff
@@ -15607,6 +15607,38 @@ BOOST_AUTO_TEST_CASE(contract_name)
...
+{
+	char const* sourceCode = R"(
+		contract Another {
+			uint xx;
+			function abc() public {}
+		}
+		library ClientReceipt {
+			event Deposit(Another indexed _from, bytes32 indexed _id, uint _value);
+			function deposit(bytes32 _id) public {
+				Another a;
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp]: You could just re-use `Test` here.

File: test/libsolidity/SolidityEndToEndTest.cpp (hunk 8 above)
Comment (Marenz) [reply test/libsolidity/SolidityEndToEndTest.cpp]: I tried to copy the pattern I saw in the other tests

File: libsolidity/ast/Types.cpp [hunk 11]
```diff
@@ -3139,13 +3149,15 @@ string FunctionType::externalSignature() const
 
 	// "inLibrary" is only relevant if this is not an event.
 	bool const inLibrary = kind() != Kind::Event && dynamic_cast<ContractDefinition const&>(*m_declaration->scope()).isLibrary();
-	FunctionTypePointer external = interfaceFunctionType();
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:3142]: If `interfaceFunctionType` is not called anymore, we ignore the return parameters. Is that intended?

Comment (chriseth) [reply libsolidity/ast/Types.cpp:3142]: Perhaps we should also change the implementation of  `interfaceFunctionType` to include the special case about events in the line above.

Comment (Marenz) [reply libsolidity/ast/Types.cpp:3142]: Originally, the return value of `interfaceFunctionType()` was only used to get the `parameterTypes()`, so we basically did extra work for something we didn't even use eventually..

Regarding the special case: That was my original approach in this PR, @ekpyron suggested a different approach here: https://github.com/ethereum/solidity/pull/6473#issuecomment-480871065

Our fear was that it might have unforeseen effects on other functions using `interfaceFunctionType()`

**Comment by Marenz** [comment]
Updated

**Comment by chriseth** [comment]
I think we should still change `interfaceFunctionType` to make it consistent. Also: Please add a buglist entry.

**Comment by chriseth** [comment]
I just checked - changing `interfaceFunctionType` should not have unwanted effects.

**Comment by Marenz** [comment]
Updated

File: docs/bugs.json [hunk 12]
```diff
@@ -1,4 +1,12 @@
 [
+    {
+        "name": "IncorrectEventABIInLibraries",
+        "summary": "Contract types used in events in libraries cause an incorrect hash in the ABI",
+        "description": "Instead of using the type 'address' for hashing, the actual contract name was used, leading to a wrong hash in the ABI.",
+        "introduced": "0.3.0",
+        "fixed": "0.5.8",
+        "severity": "low"
```
Comment (chriseth) [inline docs/bugs.json]: I would say it is "very low".

File: docs/bugs.json [hunk 13]
```diff
@@ -1,4 +1,12 @@
 [
+    {
+        "name": "IncorrectEventABIInLibraries",
+        "summary": "Contract types used in events in libraries cause an incorrect hash in the ABI",
```
Comment (chriseth) [inline docs/bugs.json]:
```suggestion
        "summary": "Contract types used in events in libraries cause an incorrect event signature hash",
```

File: docs/bugs.json [hunk 14]
```diff
@@ -1,4 +1,12 @@
...
+        "description": "Instead of using the type 'address' for hashing, the actual contract name was used, leading to a wrong hash in the ABI.",
```
Comment (chriseth) [inline docs/bugs.json]:
```suggestion
        "description": "Instead of using the type `address` in the hashed signature, the actual contract name was used, leading to a wrong hash in the logs.",
```

File: Changelog.md [hunk 15]
```diff
@@ -24,6 +24,7 @@ Compiler Features:
 Bugfixes:
  * SMTChecker: Implement Boolean short-circuiting.
  * SMTChecker: SSA control-flow did not take into account state variables that were modified inside inlined functions that were called inside branches.
+ * Type System: Use correct type name for contracts in event parameters
```
Comment (chriseth) [inline Changelog.md]: ... used in libaries.

Perhaps also add: This affected code generation.

**Comment by Marenz** [comment]
Fixed comments

File: docs/bugs.json [hunk 16]
```diff
@@ -1,4 +1,12 @@
 [
+    {
+        "name": "IncorrectEventABIInLibraries",
```
Comment (chriseth) [inline docs/bugs.json]: Ah actually this also used "ABI" which I don't think is very relevant here. Perhaps `IncorrectEventSignatureInLibraries`?

**Comment by Marenz** [comment]
Renamed bug

**Comment by chriseth** [comment]
I think you have to update the bug list, at least that is what the mac test fails on.

**Comment by chriseth** [comment]
Perhaps it also just ran on outdated code...

**Comment by Marenz** [comment]
the problem was, that I modified the end-of-file newline and the script reverted that change and thus the file was not considered up-to-date. Fixed it now

**Review by chriseth — APPROVED** [review]
