### PR TITLE
Detect Fedora properly in install_deps.sh

### LINKED ISSUE #5512: Fedora is not recognized by the `install_deps.sh` script
## Description

Fedora is not recognized by the `install_deps.sh` script.

## Environment

- Operating system: Fedora 29

## Steps to Reproduce

On a Fedora 29 install, run the following code from the terminal:
```
./scripts/install_deps.sh
```

Output should be:
```
Installing solidity dependencies on Fedora.
...
```

Output is:
```
ERROR - Unsupported or unidentified Linux distro.
See http://solidity.readthedocs.io/en/latest/installing-solidity.html for manual instructions.
If you would like to get your distro working, that would be fantastic.
Drop us a message at https://gitter.im/ethereum/solidity-dev.
```

### PR DESCRIPTION
**Pull request by corollari**
### Description

Make the double quotes around the distro name optional so it matches properly in Fedora (`NAME=Fedora`)

Fixes https://github.com/ethereum/solidity/issues/5512

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by corollari** [comment]
It seems the Travis test is failing because it's trying to run the script in a docker image, would it be possible to know which docker image it's pulling? I've looked at the test directory and can't find it there.

File: scripts/install_deps.sh [hunk 1]
```diff
@@ -55,7 +55,7 @@ detect_linux_distro() {
         DISTRO=$(lsb_release -is)
     elif [ -f /etc/os-release ]; then
         # extract 'foo' from NAME=foo, only on the line with NAME=foo
-        DISTRO=$(sed -n -e 's/^NAME="\(.*\)\"/\1/p' /etc/os-release)
+        DISTRO=$(sed -n -e 's/^NAME="\?\(.*\)\"\?/\1/p' /etc/os-release)
```
Comment (chriseth) [inline scripts/install_deps.sh]: I would not have expected the `\` in front of the `?` or is it required by sed?

**Comment by chriseth** [comment]
The docker image is `docker pull trzeci/emscripten:sdk-tag-1.37.21-64bit` - but how would that be relevant?

File: scripts/install_deps.sh (hunk 1 above)
Comment (corollari) [reply scripts/install_deps.sh]: It is required by grep, actually it is required by POSIX because of historical reasons.
The first versions of POSIX utilities which used regular expressions didn't support `?` so when they added support for it they decided to require the `\` in front to keep backwards compatibility. That's also the reason why there's backslashes before the parentheses in that same expression.

**Comment by corollari** [comment]
> The docker image is `docker pull trzeci/emscripten:sdk-tag-1.37.21-64bit` - but how would that be relevant?

Given that the Travis CI is not a required test maybe it's not needed but I thought I'd have to fix the issues that made the travis test fail before merging

File: scripts/install_deps.sh (hunk 1 above)
Comment (chriseth) [reply scripts/install_deps.sh]: I checked, and it returns `Debian GNU/Linux"` for me. It seems the `.` is not greedy enough.

My suggestion:
```suggestion
        DISTRO=$(sed -n -e 's/^NAME="\?\(.*\)\("\|$\)/\1/p' /etc/os-release)
```

Comment (corollari) [reply scripts/install_deps.sh]: You're right, committed your suggestion.

**Comment by chriseth** [comment]
Thanks!
Waiting for travis to run and will squash and merge afterwards.

**Comment by chriseth** [comment]
Sorry, it was still not working, had to change it again. Fingers crossed!

**Review by chriseth — APPROVED** [review]
