### PR TITLE
Detect circular references for library and free functions

### LINKED ISSUE #9565: Contract dependencies are not properly calculated when library-internal functions are used
The following code leads to an internal error because we have a circular dependency between `D` and `C` but the compiler does not detect it in the analysis phase:
```
library L{
    function f() internal {
        new C();
    }
}

contract D {
    function f() public {
        L.f();
    }
}
contract C {
    constructor() { new D(); }
}
```
The same behaviour can be observed if `L.f` is replaced by a free function.

### LINKED ISSUE #10457: [codegen] ICE due to compiled contract not found
## Description

```
function f() {
        new D();
}
contract D {
        constructor() {
                f;
        }
}
```

throws

https://github.com/ethereum/solidity/blob/8279d90ba26576ece14fee9d32471fa20172a701/libsolidity/codegen/CompilerContext.cpp#L257

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

### LINKED ISSUE #11128: [Sol->Yul] Invalid code generated while compiling code with circular reference
## Description

```
function f() { new D(); }
contract D {
  receive() external payable { f; }
}
```

generates the following invalid Yul code (`solc --ir test.sol`)

```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ir/IRGenerator.cpp(107): Throw in function pair<std::string, std::string> solidity::frontend::IRGenerator::run(const solidity::frontend::ContractDefinition &, const map<const solidity::frontend::ContractDefinition *, const std::string_view> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
object "D_16" {
    code {
        mstore(64, 128)
        if callvalue() { revert(0, 0) }

        constructor_D_16()

        codecopy(0, dataoffset("D_16_deployed"), datasize("D_16_deployed"))

        return(0, datasize("D_16_deployed"))

        function constructor_D_16() {

        }

    }
    object "D_16_deployed" {
        code {
            mstore(64, 128)

            if iszero(lt(calldatasize(), 4))
            {
                let selector := shift_right_224_unsigned(calldataload(0))
                switch selector

                default {}
            }
            if iszero(calldatasize()) { fun__15() stop() }
            revert(0, 0)

            function abi_encode_tuple__to__fromStack(headStart ) -> tail {
                tail := add(headStart, 0)

            }

            function allocate_unbounded() -> memPtr {
                memPtr := mload(64)
            }

            function dispatch_internal_in_0_out_0(fun)  {
                switch fun

                case 9
                {
                    fun_f_9()
                }

                default { panic_error_0x51() }
            }

            function fun__15() {

                let expr_12_functionIdentifier := 9

            }

            function fun_f_9() {

                let _1 := allocate_unbounded()
                let _2 := add(_1, datasize("D_16"))
                if or(gt(_2, 0xffffffffffffffff), lt(_2, _1)) { panic_error_0x41() }
                datacopy(_1, dataoffset("D_16"), datasize("D_16"))
                _2 := abi_encode_tuple__to__fromStack(_2)

                let expr_6_address := create(0, _1, sub(_2, _1))

                if iszero(expr_6_address) { revert_forward_1() }

            }

            function panic_error_0x41() {
                mstore(0, 35408467139433450592217433187231851964531694900788300625387963629091585785856)
                mstore(4, 0x41)
                revert(0, 0x24)
            }

            function panic_error_0x51() {
                mstore(0, 35408467139433450592217433187231851964531694900788300625387963629091585785856)
                mstore(4, 0x51)
                revert(0, 0x24)
            }

            function revert_forward_1() {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }

            function shift_right_224_unsigned(value) -> newValue {
                newValue :=

                shr(224, value)

            }

        }

    }

}



Invalid IR generated:
Warning: "switch" statement with only a default case.

Error: Unknown data object "D_16".

Error: Unknown data object "D_16".

Error: Unknown data object "D_16".
```

## Environment

- Compiler version: 6e1d61a23

## Steps to Reproduce

```
$ solc --ir test.sol
```

### PR DESCRIPTION
**Pull request by Marenz**
Fixes #9565
Fixes #10457
Fixes #11128

### CODE REVIEW

File: libsolidity/ast/ASTAnnotations.h [hunk 1]
```diff
@@ -148,16 +148,21 @@ struct StructDeclarationAnnotation: TypeDeclarationAnnotation
 	std::optional<bool> containsNestedMapping;
 };
 
-struct ContractDefinitionAnnotation: TypeDeclarationAnnotation, StructurallyDocumentedAnnotation
+struct SharedContractDependenciesAnnotation
+{
+	/// List of contracts this contract or function creates, i.e. which need to be compiled first.
+	/// For ContractDefinitions: Also includes all contracts from linearizedBaseContracts.
+	/// Only set for contracts or free functions
```
Comment (chriseth) [inline libsolidity/ast/ASTAnnotations.h]: Why not internal library functions?

File: libsolidity/ast/AST.cpp [hunk 2]
```diff
@@ -247,6 +247,21 @@ FunctionDefinition const* ContractDefinition::nextConstructor(ContractDefinition
 	return nullptr;
 }
 
+bool ContractDefinition::dependenciesAreCyclic(
+	std::set<ContractDefinition const*> const& _seenContracts
```
Comment (chriseth) [inline libsolidity/ast/AST.cpp]: Can you remove this parameter and use the breadth first search utility funciton instead?

File: test/libsolidity/syntaxTests/freeFunctions/circular_reference.sol [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+	function f() public {
+		l();
+	}
+}
+contract C {
+	constructor() { new D(); }
+}
+function l() {
+	new C();
+}
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/freeFunctions/circular_reference.sol]: What about
```suggestion
function l() {
    s();
}
function s() {
	new C();
}
```

File: libsolidity/ast/ASTAnnotations.h (hunk 1 above)
Comment (Marenz) [reply libsolidity/ast/ASTAnnotations.h]: it is in fact also set for library functions. I kind of counted those as contracts. I'll make the comment more explicit

File: Changelog.md [hunk 4]
```diff
@@ -20,6 +20,7 @@ Bugfixes:
  * SMTChecker: Fix internal error in the BMC engine when inherited contract from a different source unit has private state variables.
  * SMTChecker: Fix internal error when ``array.push()`` is used as the LHS of an assignment.
  * Code generator: Fix missing creation dependency tracking for abstract contracts.
+ * References Resolver: Detect circular references for libraries and free functions
```
Comment (hrkrshnn) [inline Changelog.md]: Needs a rebase and moving this to 0.7.6

File: libsolidity/ast/ASTAnnotations.h [hunk 5]
```diff
@@ -148,16 +148,21 @@ struct StructDeclarationAnnotation: TypeDeclarationAnnotation
 	std::optional<bool> containsNestedMapping;
 };
 
-struct ContractDefinitionAnnotation: TypeDeclarationAnnotation, StructurallyDocumentedAnnotation
+struct SharedContractDependenciesAnnotation
+{
+	/// List of contracts this contract or function creates, i.e. which need to be compiled first.
```
Comment (hrkrshnn) [inline libsolidity/ast/ASTAnnotations.h]:
```suggestion
	/// List of contracts that this contract or function creates, i.e., contracts which need to be compiled first.
```

File: libsolidity/ast/ASTAnnotations.h (hunk 1 above)
Comment (hrkrshnn) [inline libsolidity/ast/ASTAnnotations.h]:
```suggestion
	/// Only relevant for contracts or free functions
```
set was a bit confusing

File: libsolidity/ast/AST.cpp (hunk 2 above)
Comment (hrkrshnn) [reply libsolidity/ast/AST.cpp]: Agree

**Review by hrkrshnn — COMMENTED** [review]
Looks good.  Some minor comments.

File: libsolidity/analysis/TypeChecker.cpp [hunk 6]
```diff
@@ -48,6 +48,16 @@ using namespace solidity::util;
 using namespace solidity::langutil;
 using namespace solidity::frontend;
 
+namespace {
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
namespace
{
```

File: libsolidity/ast/AST.cpp (hunk 2 above)
Comment (cameel) [inline libsolidity/ast/AST.cpp]:
```suggestion
	set<ContractDefinition const*> const& _seenContracts
```

File: libsolidity/ast/AST.h [hunk 7]
```diff
@@ -546,6 +546,10 @@ class ContractDefinition: public Declaration, public StructurallyDocumented, pub
 	/// @returns the next constructor in the inheritance hierarchy.
 	FunctionDefinition const* nextConstructor(ContractDefinition const& _mostDerivedContract) const;
 
+	bool dependenciesAreCyclic(
+		std::set<ContractDefinition const*> const& _seenContracts = std::set<ContractDefinition const*>()
+	) const;
+
```
Comment (cameel) [inline libsolidity/ast/AST.h]: I think this would be better as a standalone utility function rather than a member. The AST definitions are already pretty big.

File: libsolidity/analysis/TypeChecker.h [hunk 8]
```diff
@@ -178,8 +174,19 @@ class TypeChecker: private ASTConstVisitor
 			return m_currentSourceUnit;
 	}
 
+	SharedContractDependenciesAnnotation* currentContractDependencies()
+	{
+		if (m_currentFreeFunction)
+			return &m_currentFreeFunction->annotation();
+		else if (m_currentContract)
+			return &m_currentContract->annotation();
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.h]: I think there should be an assert that they are not both true at the same time.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 9]
```diff
@@ -363,6 +363,70 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
 	/// Flag indicating whether we are currently inside a StructDefinition.
 	int m_insideStruct = 0;
 };
+
+struct FreeFunctionDependencies: public PostTypeChecker::Checker
+{
+	FreeFunctionDependencies(ErrorReporter& _errorReporter):
+		Checker(_errorReporter)
+	{}
+	bool visit(ContractDefinition const& _contract) override
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: This could use a bit more whitespace:

```suggestion
	FreeFunctionDependencies(ErrorReporter& _errorReporter):
		Checker(_errorReporter)
	{}
	
	bool visit(ContractDefinition const& _contract) override
```

Same for other definitions in this struct.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 10]
```diff
@@ -363,6 +363,70 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+	bool visit(Identifier const& _identifier) override
+	{
+		if (auto const* functionDef = dynamic_cast<FunctionDefinition const*>(_identifier.annotation().referencedDeclaration))
+			if ((m_currentContract || m_currentFreeFunction) && functionDef->isFree())
+			{
+				SharedContractDependenciesAnnotation* annotationDeps = nullptr;
+				if (m_currentContract != nullptr)
+					annotationDeps = &m_currentContract->annotation();
+				else
+					annotationDeps = &m_currentFreeFunction->annotation();
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I'd assert that both are not non-null at the same time.

File: libsolidity/analysis/TypeChecker.cpp [hunk 11]
```diff
@@ -48,6 +48,16 @@ using namespace solidity::util;
...
+
+bool addContractDependency(SharedContractDependenciesAnnotation& _annotation, ContractDefinition const* _dependency)
+{
+	_annotation.contractDependencies.insert(_dependency);
+	return !_dependency->dependenciesAreCyclic();
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Doing a graph search every time we encounter a new dependency seems pretty heavy. Could it be done once after a pass through the whole AST?

File: libsolidity/analysis/TypeChecker.cpp [hunk 12]
```diff
@@ -2825,21 +2856,11 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
...
-					m_errorReporter.typeError(
-						4224_error,
-						_memberAccess.location(),
-						"Circular reference for contract code access."
-					);
-			}
+			if (
+				(m_currentContract || m_currentFreeFunction) &&
+				!addContractDependency(*currentContractDependencies(), &accessedContractType.contractDefinition())
+			)
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: I think this code would be more readable without the `addContractDependency()` helper, i.e. if the side-effect of adding a new dependency was not hidden inside the condition.

File: test/libsolidity/syntaxTests/library_function_circular_reference.sol [hunk 13]
```diff
@@ -0,0 +1,17 @@
+library L{
```
Comment (cameel) [inline test/libsolidity/syntaxTests/library_function_circular_reference.sol]:
```suggestion
library L {
```

**Review by cameel — COMMENTED** [review]
Mostly style issues.

And yeah, now I see how it won't work without the call graph. It does not cover transitive dependencies where a function calls a function.

File: libsolidity/analysis/TypeChecker.cpp (hunk 11 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: Yes, the call graph PR will solve that.

**Comment by cameel** [comment]
Function call graph (#10973) has been merged so I guess we can now revive this PR. @Marenz, will you be working it do you want someone else to take over?

**Comment by Marenz** [comment]
I can do it, looking forward to using the call graph!

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 14]
```diff
@@ -379,17 +379,22 @@ void NameAndTypeResolver::linearizeBaseContracts(ContractDefinition& _contract)
...
 		input.back().push_front(base);
+		_contract.annotation().contractDependencies.emplace(base, baseSpecifier.get());
+
 		vector<ContractDefinition const*> const& basesBases = base->annotation().linearizedBaseContracts;
 		if (basesBases.empty())
 			m_errorReporter.fatalTypeError(2449_error, baseName.location(), "Definition of base has to precede definition of derived contract");
 		input.push_front(list<ContractDefinition const*>(basesBases.begin(), basesBases.end()));
+
+		auto const& basesDependencies = base->annotation().contractDependencies;
+		_contract.annotation().contractDependencies.insert(basesDependencies.begin(), basesDependencies.end());
```
Comment (hrkrshnn) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: This could be replaced by `+=` from `CommonData.h`.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 15]
```diff
@@ -362,6 +375,66 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+	{}
+
+	bool visit(ContractDefinition const& _contract) override
+	{
+		auto joined = boost::join(
+			_contract.annotation().creationCallGraph->get()->createdContracts,
+			_contract.annotation().deployedCallGraph->get()->createdContracts
+		);
+
+		for (auto const& [contract, referencee]: joined)
```
Comment (hrkrshnn) [inline libsolidity/analysis/PostTypeChecker.cpp]: I'm slightly confused here. What are `contract` and `referencee` here? I thought `joined` would be just a set?

**Comment by cameel** [comment]
Is this actually up for review now? I think @Marenz said yesterday that he's still working on something here so I decided to wait and watch and in the meantime I started reviewing keccak instead :)

**Comment by leonardoalt** [comment]
@cameel ah ok, not sure, I based the requests on `Marenz marked this pull request as ready for review 18 hours ago` above

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 15 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: I changed `createdContracts` to be a map, the value being the ast node that references the contract

**Comment by Marenz** [comment]
> Is this actually up for review now?

No, this is ready now

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 14 above)
Comment (Marenz) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: There does not seem to be a suitable overload for maps

Comment (hrkrshnn) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: Sorry, didn't realize that `contractDepencies` was a map. Was still thinking that it was a set :)

File: libsolidity/ast/AST.cpp (hunk 2 above)
Comment (Marenz) [reply libsolidity/ast/AST.cpp]: Turns out we have an actual CycleDetector class which I used in place now.

File: Changelog.md [hunk 16]
```diff
@@ -4,6 +4,7 @@ Language Features:
 
 
 Compiler Features:
+ * References Resolver: Detect circular references for libraries and free functions
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * References Resolver: Detect circular references to other contracts across libraries and free functions
```

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 17]
```diff
@@ -379,17 +379,21 @@ void NameAndTypeResolver::linearizeBaseContracts(ContractDefinition& _contract)
 		// "push_front" has the effect that bases mentioned later can overwrite members of bases
 		// mentioned earlier
 		input.back().push_front(base);
+		_contract.annotation().contractDependencies.emplace(base, baseSpecifier.get());
```
Comment (chriseth) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: Do we actually still need this, or are the dependencies from the call graph enough?

Comment (chriseth) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: If we have
```
contract A { function f() public { new B(); } }
contract B is A {}
```
this will be caught through the call graph.
A special case that changes is if the base function is not executed when the derived is the "most derived":
```
contract A { function f() public virtual { new B(); } }
contract B is A {
 function f() public override {  }
}
```
But in that case, it is actually possible for `A` to create `B`.

File: libsolidity/ast/CallGraph.h [hunk 18]
```diff
@@ -62,7 +62,7 @@ struct CallGraph
 	std::map<Node, std::set<Node, CompareByID>, CompareByID> edges;
 
 	/// Contracts that may get created with `new` by functions present in the graph.
-	std::set<ContractDefinition const*, ASTNode::CompareByID> createdContracts;
+	std::map<ContractDefinition const*, ASTNode const*, ASTNode::CompareByID> createdContracts;
```
Comment (cameel) [inline libsolidity/ast/CallGraph.h]: I'd make it more specific and use `NewExpression` unless we know that it can indeed be an arbitrary node.

Also, there can be multiple places where a contract is created.

```suggestion
	std::map<ContractDefinition const*, std::set<NewExpression const*>, ASTNode::CompareByID> createdContracts;
```

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 17 above)
Comment (cameel) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: `contractDependencies` looks like it only stores information about the base contracts that the derived contract inherits from. The call graph does not have that info. At least not full info. The creation call graph does have edges from `Entry` to base constructors but only if these constructors are explicitly defined.

I also see that it contains contracts used in member access expressions. The call graph tracks function calls but completely ignores contracts used in such expressions.

And the annotation is used not only for detecting cycles. For example `CompilerStack::compileContract()` uses it to determine which contracts to compile.

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 14 above)
Comment (cameel) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: It would be clearer if the line above used full type rather than `auto`. I see that the type is a bit long though so maybe `auto` is still less bad than the alternative...

Comment (cameel) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: BTW, there's `map::merge()` in C++17 but I think it destroys the original container so `insert()` looks like the best option here.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 19]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+			if (contract != &_contract)
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: Is this actually possible? I don't think a contract can create its own instance? Maybe this should be an assert?

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 20]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+	CircularContractDependencies(ErrorReporter& _errorReporter):
+		Checker(_errorReporter)
+	{}
+
+	bool visit(ContractDefinition const& _contract) override
+	{
+		auto joined = boost::join(
+			_contract.annotation().creationCallGraph->get()->createdContracts,
+			_contract.annotation().deployedCallGraph->get()->createdContracts
+		);
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: What happens when the same contract is on both lists? I think we're losing one of the `NewExpression` instances in that case.

Same when some of the contracts are already present in `contractDependencies`.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 21]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+	map<ContractDefinition const*, ASTNode const*, ASTNode::CompareByID> m_foundCycles;
+
+
+	pair<ContractDefinition const*, ASTNode const*> dependenciesAreCyclic(
+		ContractDefinition const& _currentContract
+	) const
+	{
+		auto visitor = [&](ContractDefinition const& _contract, util::CycleDetector<ContractDefinition>& _cycleDetector, size_t _depth)
+		{
+			if (_depth >= 256)
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: Where does 256 come from? Is it arbitrary?

I think we should have a global constant for this.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 22]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+				m_errorReporter.fatalTypeError(7864_error, _contract.location(), "Contract dependencies exhausting cyclic dependency validator");
+
+			for (auto& [contract, referencee]: _contract.annotation().contractDependencies)
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I'd differentiate these names a bit. When I notice `_contract` and `contract` used next to each other I always have to go back and check what each of them meant.

```suggestion
			for (auto& [dependencyContract, referencee]: _contract.annotation().contractDependencies)
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 23]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+
+		if (contract)
+			m_foundCycles.emplace(contract, referencee);
+	}
+
+	void finalize() override
+	{
+		for (auto const& [cycle, referencee]: m_foundCycles)
+		{
+			SecondarySourceLocation ssl{};
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I think more descriptive names are better, even if they're only used in a small piece of code.
```suggestion
			SecondarySourceLocation secondaryLocation{};
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 24]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+				"Circular reference found."
+			);
+		}
+	}
+
+private:
+	map<ContractDefinition const*, ASTNode const*, ASTNode::CompareByID> m_foundCycles;
+
+
+	pair<ContractDefinition const*, ASTNode const*> dependenciesAreCyclic(
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I think that the current name no longer fits if the function does not return a boolean value:
```suggestion
	pair<ContractDefinition const*, ASTNode const*> findDependencyCycle(
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 25]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+		if (contract)
+			m_foundCycles.emplace(contract, referencee);
+	}
+
+	void finalize() override
+	{
+		for (auto const& [cycle, referencee]: m_foundCycles)
+		{
+			SecondarySourceLocation ssl{};
+			ssl.append(string{"Referenced contract"}, cycle->location());
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]:
```suggestion
			ssl.append("Referenced contract"s, cycle->location());
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 26]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+
+			m_errorReporter.typeError(
+				7813_error,
+				referencee->location(),
+				ssl,
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I see that `SecondarySourceLocation` is just a plain struct so this should work:

```suggestion
				{{"Referenced contract"s, cycle->location()}},
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 27]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+		for (auto const& [contract, referencee]: joined)
+			if (contract != &_contract)
+				_contract.annotation().contractDependencies.emplace(contract, referencee);
+
+		return true;
+	}
+
+	void endVisit(ContractDefinition const& _contract) override
+	{
+		auto const& [contract, referencee] = dependenciesAreCyclic(_contract);
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: This will visit the whole graph for each contract which is O(n^2). I think that it should be possible to detect all cycles with just O(n).

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 28]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+	bool visit(ContractDefinition const& _contract) override
+	{
+		auto joined = boost::join(
+			_contract.annotation().creationCallGraph->get()->createdContracts,
+			_contract.annotation().deployedCallGraph->get()->createdContracts
+		);
+
+		for (auto const& [contract, referencee]: joined)
+			if (contract != &_contract)
+				_contract.annotation().contractDependencies.emplace(contract, referencee);
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I think that modifying `contractDependencies` in the same run through the graph that runs cycle checker is not a good idea. It does work here but only because `endVisit()` runs the cycle checker on every contract in the graph so even if `contractDependencies` is incomplete at some point, it will be complete when we visit the last contract that's part of a cycle. This will stop working if we switch to something more optimal though.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 29]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+
+		return true;
+	}
+
+	void endVisit(ContractDefinition const& _contract) override
+	{
+		auto const& [contract, referencee] = dependenciesAreCyclic(_contract);
+
+		if (contract)
+			m_foundCycles.emplace(contract, referencee);
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: What is `contract` here actually? I know it's the thing that `CycleDetector` returns but which node is that? Is that specifically one of the contracts that create/inherit from `_contract` or just random node inside the cycle?

```suggestion
		auto const& [dependentContract, referencee] = dependenciesAreCyclic(_contract);

		if (dependentContract)
			m_foundCycles.emplace(dependentContract, referencee);
```

Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: Is the intention here to report a separate error for every contract that's a part of a cycle? If so, then I think this does not work as designed because it's not `_contract` that is the key. Instead you're using the element returned by `CycleDetector` which could be the same for different `_contract`s.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 30]
```diff
@@ -362,6 +365,77 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
...
+				if (_cycleDetector.run(*contract))
+					return;
+		};
+
+		ContractDefinition const* loop = util::CycleDetector<ContractDefinition>(visitor).run(_currentContract);
+
+		if (loop)
+			return {loop, _currentContract.annotation().contractDependencies[loop]};
+
+		return {nullptr, nullptr};
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: I think there's no point in returning both the contract and the AST Node that references it if it's just the one from `contractDependencies`. The caller can just look it up on his own.

File: libsolidity/analysis/TypeChecker.h [hunk 31]
```diff
@@ -180,8 +176,21 @@ class TypeChecker: private ASTConstVisitor
 			return m_currentSourceUnit;
 	}
 
+	SharedContractDependenciesAnnotation* currentContractDependencies()
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.h]: I think this name is a bit too misleading. I had to jump here to see what it actually does :) This doesn't really return dependencies. Just the annotation. And not necessarily of the contract.

File: libsolidity/analysis/TypeChecker.cpp [hunk 32]
```diff
@@ -2627,22 +2642,14 @@ void TypeChecker::endVisit(NewExpression const& _newExpression)
 		if (contract->abstract())
 			m_errorReporter.typeError(4614_error, _newExpression.location(), "Cannot instantiate an abstract contract.");
 
-		if (m_currentContract)
+		if (m_currentContract || m_currentFreeFunction)
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Is it actually possible to create a new contract with `new` outside of a contract/library or a free function?

And if it is, shouldn't we include that in dependencies too?

File: libsolidity/analysis/TypeChecker.cpp [hunk 33]
```diff
@@ -2627,22 +2642,14 @@ void TypeChecker::endVisit(NewExpression const& _newExpression)
...
 				"Linearized base contracts not yet available."
 			);
-			if (contractDependenciesAreCyclic(*m_currentContract))
-				m_errorReporter.typeError(
-					4579_error,
-					_newExpression.location(),
-					"Circular reference for contract creation (cannot create instance of derived or same contract)."
-				);
+
+			currentContractDependencies()->contractDependencies.emplace(contract, &_newExpression);
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Is this actually necessary? It seems redundant because the call graph will find it.

On the other hand the call graph does not visit internal/free functions that are not called from anywhere so maybe it is after all?

File: libsolidity/analysis/TypeChecker.cpp [hunk 34]
```diff
@@ -2950,6 +2945,11 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 				"\"chainid\" is not supported by the VM version."
 			);
 	}
+	else if (m_currentContract || m_currentFreeFunction)
+		if (auto typeType = dynamic_cast<TypeType const*>(exprType))
+			if (auto contractType = dynamic_cast<ContractType const*>(typeType->actualType()))
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
		if (auto const* typeType = dynamic_cast<TypeType const*>(exprType))
			if (auto const* contractType = dynamic_cast<ContractType const*>(typeType->actualType()))
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 35]
```diff
@@ -2950,6 +2945,11 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
...
+				if (&contractType->contractDefinition() != m_currentContract)
+					currentContractDependencies()->contractDependencies.emplace(&contractType->contractDefinition(), &_memberAccess);
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: I think that doing this will result in a cycle being reported here:

```solidity
contract C {
    bytes4 s = B.f.selector;

    function f() public {}
}

contract B {
    bytes4 s = C.f.selector;

    function f() public {}
}
```

This is currently allowed and works fine.

File: test/libsolidity/syntaxTests/cyclic_dep_exhaustion.sol [hunk 36]
```diff
@@ -0,0 +1,773 @@
+contract D {
+	function f() public {
+		new C();
+	}
+}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/cyclic_dep_exhaustion.sol]: This part is using tabs, the rest of the file is using spaces:
```suggestion
contract D {
    function f() public {
        new C();
    }
}
```

File: test/libsolidity/syntaxTests/cyclic_dep_exhaustion.sol [hunk 37]
```diff
@@ -0,0 +1,773 @@
...
+    constructor() { new C253(); }
+}
+contract C253 {
+    constructor() { new C254(); }
+}
+contract C254 {
+    constructor() { new C255(); }
+}
+contract C255 {
+	constructor() { new C(); }
```
Comment (cameel) [inline test/libsolidity/syntaxTests/cyclic_dep_exhaustion.sol]:
```suggestion
    constructor() { new C(); }
```

File: test/libsolidity/syntaxTests/freeFunctions/circular_reference.sol [hunk 38]
```diff
@@ -0,0 +1,17 @@
+contract D {
+	function f() public {
+		l();
+	}
+}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/freeFunctions/circular_reference.sol]: Our style guide for Solidity recommends 4 space indents so I think we should be using that style ourselves too :)
Most of the .sol files in this PR have tabs (though some have a mix of tabs and spaces).

File: test/libsolidity/syntaxTests/freeFunctions/circular_reference1.sol [hunk 39]
```diff
@@ -0,0 +1,17 @@
...
+	function f() public {
+		l();
+	}
+}
+contract C {
+	constructor() { new D(); }
+}
+// ----
+// TypeError 7813: (131-136): Circular reference found.
+// TypeError 7813: (42-47): Circular reference found.
```
Comment (cameel) [inline test/libsolidity/syntaxTests/freeFunctions/circular_reference1.sol]: Is this the same thing as `circular_reference.sol`, just with a different order or definitions?

If so, I'd rename them to make that more apparent. E.g. `circular_reference_contracts_first.sol` and `circular_reference_functions_first.sol`. And a comment explaining that might be a good idea because someone modifying these tests later might not notice that the order matters (usually it does not).

File: test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol [hunk 40]
```diff
@@ -16,7 +16,4 @@ contract Test is Base {
     }
 }
 // ----
-// TypeError 4224: (165-188): Circular reference for contract code access.
-// TypeError 4224: (271-293): Circular reference for contract code access.
-// TypeError 4224: (381-404): Circular reference for contract code access.
-// TypeError 4224: (491-513): Circular reference for contract code access.
+// TypeError 7813: (165-188): Circular reference found.
```
Comment (cameel) [inline test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol]: I think this test should be refactored so that each function is in a separate contract. Otherwise it's not clear if all of these cases still report an error or just some.

File: test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol [hunk 41]
```diff
@@ -2,4 +2,6 @@ contract A { function f() public { new B(); } }
 contract B { function f() public { new C(); } }
```
Comment (cameel) [inline test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol:2]: Some more test ideas:
- [ ] Multiple creation cycles sharing one node (to test the case I mentioned in one of the comments where the error is reported only for that shared node and not separately for each contract).
- [x] Creating the contract with `new` in its own constructor (I think we only have that for an ordinary function).
- [x] A situation where two contracts just reference each other's names without doing anything (i.e. `f() public { C; }`). Currently this is allowed.
- [x] Same but with `type(C)`.
- [x] Two contracts calling each other without creating an actual dependency cycle (we might already have a test for this):
    ```solidity
    contract C { function foo(D _d) public { _d.foo(this); } }
    contract D { function foo(C _c) public { _c.foo(this); } }
    ```
    Currently this works.
- [x] Same for libraries
    ```solidity
    library L1 { function foo() internal { L2.foo(); } }
    library L2 { function foo() internal { L1.foo(); } }
    ```
    Currently this works.
- [x] Creation cycles involving both `new` and inheritance. For example:
    - `C is D`, `E is D`, `E` does `new C`
    - `C` does `new A`, `A` does `new D`, `D is C`.
- [x] Creation cycle caused by unused internal functions (which are ignored by the call graph):
    ```solidity
    contract C { function foo() internal { new D(); } }
    contract D { function foo() internal { new C(); } }
    ```
    Currently this is an error.

File: libsolidity/ast/ASTAnnotations.h [hunk 42]
```diff
@@ -152,16 +152,21 @@ struct StructDeclarationAnnotation: TypeDeclarationAnnotation
 	std::optional<bool> containsNestedMapping;
 };
 
-struct ContractDefinitionAnnotation: TypeDeclarationAnnotation, StructurallyDocumentedAnnotation
+struct SharedContractDependenciesAnnotation
+{
+	/// List of contracts that this contract or function creates, i.e. contracts which need to be compiled first.
+	/// For ContractDefinitions: Also includes all contracts from linearizedBaseContracts.
+	/// Only relevant for contracts or free functions
+	std::map<ContractDefinition const*, ASTNode const*> contractDependencies;
```
Comment (cameel) [inline libsolidity/ast/ASTAnnotations.h]: I think the docstring should explain what the `ASTNode` is here for.

Comment (cameel) [inline libsolidity/ast/ASTAnnotations.h]: Can we be more specific than `ASTNode`? I think it can only be `NewExpression` or `InheritanceSpecifier`. Using a `variant` here might save us some assertions.

File: libsolidity/ast/ASTJsonConverter.cpp [hunk 43]
```diff
@@ -269,7 +270,10 @@ bool ASTJsonConverter::visit(ContractDefinition const& _node)
 		make_pair("contractKind", contractKind(_node.contractKind())),
 		make_pair("abstract", _node.abstract()),
 		make_pair("baseContracts", toJson(_node.baseContracts())),
-		make_pair("contractDependencies", getContainerIds(_node.annotation().contractDependencies, true)),
+		make_pair("contractDependencies", getContainerIds(
+			_node.annotation().contractDependencies | boost::adaptors::map_keys,
```
Comment (cameel) [inline libsolidity/ast/ASTJsonConverter.cpp]: You could use ranges v3 here:
```suggestion
			_node.annotation().contractDependencies | views::keys,
```

This would also require these at the top:
```c++
#include <range/v3/view/map.hpp>
using namespace ranges;
```

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 17 above)
Comment (cameel) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: But I think there are some cases where adding stuff to `contractDependencies` is now redundant. For example https://github.com/ethereum/solidity/pull/10228#discussion_r587791629.

Though maybe not. The call graph does not take into account stuff that is unreachable. For example if there's a creation cycle caused by unused internal functions, it won't be detected.
```solidity
contract C { function foo() internal { new D(); } }
contract D { function foo() internal { new C(); } }
```
Currently it causes an error:
```
Error: Circular reference for contract creation (cannot create instance of derived or same contract).
```
But the graph won't report `C` and `D` in `createdContracts`.

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 19 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: Hmm are you sure that's not possible? Why wouldn't it?

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 20 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: Yeah, we would lose it, but is that really a problem? It's only used for error reporting and if several expressions reference a contract within the same contract fixing one cycle would very likely also fix the other, and if not it will just show the error once you fixed the first one..

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 21 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: It is used in the same file a few lines up to break a cycle detection loop for const variable dependency cycles, I just copied it from there. 

But you're right, it's a magic number that can be avoided

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 17 above)
Comment (chriseth) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: What do you mean by "used in member access expressions"?
The reason CompilerStack::compileContract uses `contractDependencies` is because `new C` needs to have `C` available, and that's the only reason.

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 26 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: Aah, I was wondering how to do that best.

Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: Hmm unfortunately that doesn't work

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 29 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: `contract` here is the dependency that causes a cycle, referenced/required by `referencee`. So.. I guess in your words, it is a random node inside the cycle, yes.

Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: I think it works anyway though as `m_foundCycles` is only reset and processed once we processed all contracts..

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 30 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: That's a fair point.

File: libsolidity/analysis/TypeChecker.h (hunk 31 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.h]: Renamed to `currentDependencyAnnotation`

File: libsolidity/analysis/TypeChecker.cpp (hunk 32 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: I can't think of any other contexts where you can create contracts?

File: libsolidity/analysis/TypeChecker.cpp (hunk 35 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: That's true. I think I added the `selector` check due to a request from @chriseth. Chris, maybe you can clear up the desired behavior here? :)

File: test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol (hunk 40 above)
Comment (Marenz) [reply test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol]: Well, `creationBase()` and `runtimeBase()` don't create an error anymore here. However, even when in different contracts, this results in only one error, even though both `Test` calls would cause one

Comment (Marenz) [reply test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol]: I am at this point not sure if that's okay

**Comment by Marenz** [comment]
I pushed an update for this PR that takes care of ~80% of the feedback here. Still a WIP though. Everything marked as resolved should be fine though.

File: libsolidity/analysis/TypeChecker.cpp (hunk 35 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: I don't really understand the question here. There is no contract creation involved in the example, so there should be no cycle, not even an edge.

File: libsolidity/analysis/TypeChecker.cpp [hunk 44]
```diff
@@ -2918,21 +2925,9 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
...
 
-				m_currentContract->annotation().contractDependencies.insert(&accessedContractType.contractDefinition());
-				if (contractDependenciesAreCyclic(*m_currentContract))
-					m_errorReporter.typeError(
-						4224_error,
-						_memberAccess.location(),
-						"Circular reference for contract code access."
-					);
-			}
+			if (m_currentContract || m_currentFreeFunction)
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: This has to be moved inside the call graph analysis.

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: Accessing another contract's code is the same as using `new OtherContract`.

File: libsolidity/analysis/TypeChecker.cpp (hunk 35 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: But it's accessing attributes of a different contract, that is a dependency, right?

File: test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol (hunk 41 above)
Comment (Marenz) [reply test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol:2]: I am wondering if the libraries case _should_ work. In this new PR it is an error.

Comment (Marenz) [reply test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol:2]: * `C is D`, `E is D`, `E` does `new C` — This is currently no error. Should it be? 
* `C` does `new A`, `A` does `new D`, `D is C`. — This does produce an error.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `601402148c5c02e34733f315c6a4a4719d3b846a`:
```
Coding style error:
libsolutil/Common.h:77:const size_t MAX_RECURSION_DEPTH = 256;

```
Please check that your changes are working as intended.

File: libsolidity/analysis/TypeChecker.cpp (hunk 44 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: so adding this to the `_memberAccess` visitor and removing the part here should be enough?

```
	TypePointer exprType = _memberAccess.expression().annotation().type;
	ASTString const& memberName = _memberAccess.memberName();

	if (auto magicType = dynamic_cast<MagicType const*>(exprType))
		if (magicType->kind() == MagicType::Kind::MetaType && (
			memberName == "creationCode" || memberName == "runtimeCode"
		))
		{
			ContractType const& accessedContractType = dynamic_cast<ContractType const&>(*magicType->typeArgument());
			m_graph.createdContracts.emplace(&accessedContractType, &_memberAccess);
		}
```

Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: @cameel and here we already have the case where it's more than just a new expression..

File: libsolidity/analysis/FunctionCallGraph.cpp [hunk 45]
```diff
@@ -212,7 +212,7 @@ bool FunctionCallGraphBuilder::visit(ModifierInvocation const& _modifierInvocati
 bool FunctionCallGraphBuilder::visit(NewExpression const& _newExpression)
 {
 	if (ContractType const* contractType = dynamic_cast<ContractType const*>(_newExpression.typeName().annotation().type))
-		m_graph.createdContracts.emplace(&contractType->contractDefinition());
+		m_graph.createdContracts.emplace(&contractType->contractDefinition(), &_newExpression);
```
Comment (chriseth) [inline libsolidity/analysis/FunctionCallGraph.cpp]: Maybe rename this now from `createdContracts` to something like `bytecodeDependency`?

File: libsolutil/Common.h [hunk 46]
```diff
@@ -73,6 +73,9 @@ using StringMap = std::map<std::string, std::string>;
 // String types.
 using strings = std::vector<std::string>;
 
+/// Max depth a recursion should go before erroring out
+const size_t MAX_RECURSION_DEPTH = 256;
```
Comment (chriseth) [inline libsolutil/Common.h]: We have other numbers in other places (for example ParserBase::increaseRecursionDepth)

File: libsolutil/Algorithms.h [hunk 47]
```diff
@@ -68,6 +68,14 @@ class CycleDetector
 		return m_firstCycleVertex;
 	}
 
+	void reset()
```
Comment (chriseth) [inline libsolutil/Algorithms.h]: I would prefer assigning a newly created copy instead. Reset functions always have to make sure that they don't accidentally forget one of the members.

File: libsolutil/Common.h (hunk 46 above)
Comment (Marenz) [reply libsolutil/Common.h]: I did this as a reaction to @cameel's feedback.. I can remove it again if you think we don't need it..

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 48]
```diff
@@ -362,6 +364,58 @@ struct NoVariablesInInterfaceChecker: public PostTypeChecker::Checker
 	/// Flag indicating whether we are currently inside a StructDefinition.
 	int m_insideStruct = 0;
 };
+
+struct CircularContractDependencies: public PostTypeChecker::Checker
```
Comment (chriseth) [inline libsolidity/analysis/PostTypeChecker.cpp]: I'm not sure if the post type checker is the right place for this. You do not really need to traverse ASTs here - all you need is iterate over all contracts. We already do that in the CompilerStack. Maybe it's better to put it there and move it into a function together with the loop that assigns the call graphs to the annotation?

File: libsolidity/analysis/TypeChecker.cpp (hunk 32 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: This code can be removed completely can't it? We do all this in the call graph.

File: libsolidity/ast/ASTAnnotations.h [hunk 49]
```diff
@@ -177,7 +183,7 @@ struct CallableDeclarationAnnotation: DeclarationAnnotation
 	std::set<CallableDeclaration const*> baseFunctions;
 };
 
-struct FunctionDefinitionAnnotation: CallableDeclarationAnnotation, StructurallyDocumentedAnnotation
+struct FunctionDefinitionAnnotation: CallableDeclarationAnnotation, StructurallyDocumentedAnnotation, SharedContractDependenciesAnnotation
```
Comment (chriseth) [inline libsolidity/ast/ASTAnnotations.h]: I don't think this is needed. The call graph should take care about it.

File: libsolidity/analysis/TypeChecker.cpp (hunk 32 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: Except for unreachable internal functions, I think those are not covered by the graph.

File: libsolutil/Common.h (hunk 46 above)
Comment (Marenz) [reply libsolutil/Common.h]: Oh, you mean that that number should also be replaced by this one?

Comment (Marenz) [reply libsolutil/Common.h]: At the very least the comment is wrong I guess

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `fcc951fb72f06631ea8599c73d67d0b0d82bc205`:
```
Coding style error:
libsolutil/Common.h:77:const size_t MaxCycleDetectionRecursionDepth = 256;

```
Please check that your changes are working as intended.

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 19 above)
Comment (cameel) [reply libsolidity/analysis/PostTypeChecker.cpp]: Doesn't `new C` syntax require the bytecode of `C` to be embedded in the bytecode of the contract that wants to create it? And we're still compiling `C`.

If I try to make `C` create its own instance I get and error that says:

```
Error: Circular reference for contract creation (cannot create instance of derived or same contract).
```

This is from:
``` solidity
contract C {
    function foo() public {
        new C();
    }
}
```

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 20 above)
Comment (cameel) [reply libsolidity/analysis/PostTypeChecker.cpp]: Well, I spotted this at the beginning of the review and after going though it all, I think losing it is not such big a deal. The bigger problem for me is that there's no clear rule about which expression should eventually end up associated with the contract. I'm not even sure it's completely deterministic. `contractDependencies` gets updated in many places during the analysis and they are very loosely coupled.

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 26 above)
Comment (cameel) [reply libsolidity/analysis/PostTypeChecker.cpp]: Oh. Weird. Maybe it requires the name of the type to be given explicitly?

Anyway, I guess it's just a small detail not worth digging into too much so I'll just mark it as resolved :)

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 29 above)
Comment (cameel) [reply libsolidity/analysis/PostTypeChecker.cpp]: Yeah, it's not broken in that it will never just find zero cycles if some exist but I think it may also not find all cycles. Or rather it will find all of them but entries in `m_foundCycles` can get overwritten. That's because the same contract can be part of multiple cycles.

File: libsolidity/analysis/TypeChecker.cpp (hunk 35 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: > I don't really understand the question here. There is no contract creation involved in the example, so there should be no cycle, not even an edge.

I agree there should be no cycle. I think that the piece of code I commented on would result in it being interpreted as a cycle so we have to remove or at least adjust it.

> But it's accessing attributes of a different contract, that is a dependency, right?

`selector` has special rules in that regard. For example you can access selectors of functions from a contract you do not inherit from. It's allowed because you don't have to compile that whole contract before yours to calculate the selector.

`C.f.selector` does result in `f` being added to internal dispatch but I don't think it counts as a dependency because you then just compile this function as a part of your contract. And you could make `s` in my example `constant` which would not even add it to the dispatch.

This case came up recently in #11015 and #11014.

File: test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol (hunk 40 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol]: > However, even when in different contracts, this results in only one error, even though both `Test` calls would cause one

I think this might actually be an example of https://github.com/ethereum/solidity/pull/10228#discussion_r587774557. I suspect that for both cycles the node added to `m_foundCycles` is `Base` and the second one overwrites the first.

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 20 above)
Comment (Marenz) [reply libsolidity/analysis/PostTypeChecker.cpp]: I am pretty sure it's deterministic as I had undeterministic problems before which no longer happen now..

File: test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol (hunk 40 above)
Comment (Marenz) [reply test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol]: I'll investigate that

File: test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol (hunk 41 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/nameAndTypeResolution/236_cyclic_binary_dependency.sol:2]: > I am wondering if the libraries case _should_ work. In this new PR it is an error.

I think it should because you do not need to compile one first to be able to compile the other. Both libraries have their own copies of both functions compiled into them.

> * `C is D`, `E is D`, `E` does `new C` — This is currently no error. Should it be? 

Right, I think it's fine that it compiles because if we compile `C` first, `E` can use its bytecode just fine.

I'd still add it as a test case but the situation I had in mind is actually this: `C is D`, `E is D`, `C` does `new E`

> * `C` does `new A`, `A` does `new D`, `D is C`. — This does produce an error.

Great. This is what I would expect.

File: libsolidity/analysis/TypeChecker.cpp (hunk 44 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: Well, I'd personally just use a variant. It's not really that much more intrusive than `ASTNode *` because with it you just trade `get<T>` for `dynamic_cast<T>`. But that's just my preference. `ASTNode *` is still a valid choice so if you think it's better suited here I'm fine that that too. I'll just probably be suggesting extra assertions because of that :)

File: libsolutil/Common.h (hunk 46 above)
Comment (cameel) [reply libsolutil/Common.h]: I think that @chriseth meant that `increaseRecursionDepth()` uses a different value. It's 1200 there.

If there's no special reason behind 256 other than it being a round number, we could use the same number in both places.

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 17 above)
Comment (cameel) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: I meant that the `TypeChecker` was adding contracts used in member access expressions to `contractDependencies` and function call graph does not add them to `createdContracts` so it could not be used as a replacement.

But well, I see your point now. It should be possible to generalize `createdContracts` to just store info about dependencies rather than just about `new` expressions.

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 50]
```diff
@@ -19,13 +19,15 @@
 #include <libsolidity/analysis/PostTypeChecker.h>
 
 #include <libsolidity/ast/AST.h>
+#include <libsolidity/ast/CallGraph.h>
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: This seems unused now.

File: libsolidity/ast/ASTJsonConverter.cpp [hunk 51]
```diff
@@ -35,13 +35,16 @@
 
 #include <boost/algorithm/string/join.hpp>
 #include <boost/range/algorithm/sort.hpp>
+#include <boost/range/adaptors.hpp>
```
Comment (cameel) [inline libsolidity/ast/ASTJsonConverter.cpp]: This seems unused now.

File: libsolidity/ast/ASTAnnotations.h (hunk 49 above)
Comment (cameel) [reply libsolidity/ast/ASTAnnotations.h]: We'll need to make the graph keep track of inherited contracts.

File: libsolidity/analysis/TypeChecker.cpp [hunk 52]
```diff
@@ -2950,6 +2942,11 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 				"\"chainid\" is not supported by the VM version."
 			);
 	}
+	else if (m_currentContract || m_currentFreeFunction)
+		if (auto const* typeType = dynamic_cast<TypeType const*>(exprType))
+			if (auto const* contractType = dynamic_cast<ContractType const*>(typeType->actualType()))
+				if (&contractType->contractDefinition() != m_currentContract)
+					currentDependencyAnnotation()->contractDependencies.emplace(&contractType->contractDefinition(), &_memberAccess);
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: So, according to https://github.com/ethereum/solidity/pull/10228#discussion_r591582547, I think this should be moved into the graph.

Or maybe just removed? I think that the special case for `creationCode` and `runtimeCode` you already added to the graph covers all member expressions that can result in a bytecode dependency.

File: libsolidity/interface/CompilerStack.cpp [hunk 53]
```diff
@@ -70,11 +70,14 @@
...
 #include <libsolutil/IpfsHash.h>
 #include <libsolutil/JSON.h>
+#include <libsolutil/Algorithms.h>
 
 #include <json/json.h>
 
 #include <boost/algorithm/string/replace.hpp>
 #include <utility>
+#include <map>
+#include <range/v3/view/concat.hpp>
```
Comment (cameel) [inline libsolidity/interface/CompilerStack.cpp]: We usually put `boost` and `ranges` in a group separate from stdlib.

File: libsolidity/interface/CompilerStack.cpp [hunk 54]
```diff
@@ -399,27 +428,44 @@ bool CompilerStack::analyze()
...
-									*contractDefinition
-								)
-							);
-							contractState.contract->annotation().deployedCallGraph = make_unique<CallGraph>(
-								FunctionCallGraphBuilder::buildDeployedGraph(
-									*contractDefinition,
-									**contractState.contract->annotation().creationCallGraph
-								)
-							);
+							createAndAssignCallGraphs(*contractDefinition);
```
Comment (cameel) [inline libsolidity/interface/CompilerStack.cpp]: I think you should do this in a separate loop, first, and only then in another one run the cycle detector. Otherwise the detector can visit some nodes before `createAndAssignCallGraphs()` updates their `contractDependencies`.

File: libsolidity/interface/CompilerStack.cpp [hunk 55]
```diff
@@ -399,27 +428,44 @@ bool CompilerStack::analyze()
...
+				SecondarySourceLocation secondaryLocation{};
+				secondaryLocation.append("Referenced contract"s, cycle->location());
+
+				m_errorReporter.typeError(
+					7813_error,
+					referencee->location(),
+					secondaryLocation,
+					"Circular reference found."
+				);
+			}
```
Comment (cameel) [inline libsolidity/interface/CompilerStack.cpp]: I'd extract more of this code into separate functions to keep `analyze()` leaner.

File: libsolidity/ast/ASTAnnotations.h (hunk 49 above)
Comment (chriseth) [reply libsolidity/ast/ASTAnnotations.h]: No, I think we need to remove inheritance from the dependencies.

Comment (cameel) [reply libsolidity/ast/ASTAnnotations.h]: I think it creates a dependency. Here is how I understand it: if `C is D` then you cannot really compile `D` without being able to finish the compilation of `C` first, even though `D` does not need to access the bytecode of `C` (it has its own "copy"). If we do not detect this, we won't notice that this is a dependency cycle:
- `C` does `new A`
- `A` does `new D`
- `D is C`

Comment (chriseth) [reply libsolidity/ast/ASTAnnotations.h]: I don't think this is a problem. All the dependencies that are created are recorded in the call graph. The `new A` inside `C` will be part of `D`'s call graph if it is reachable. If `D` overrides the function in `C` that contains `new A`, then there will be no creation cycle.

Comment (cameel) [reply libsolidity/ast/ASTAnnotations.h]: Oh, you're right. I did not consider that all the stuff from `C` is inherited so it actually becomes a direct cycle between `A` and `D`.

File: libsolidity/interface/CompilerStack.cpp (hunk 53 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: even if the ranges are part of the stdlib?

File: libsolidity/analysis/TypeChecker.cpp (hunk 52 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: I actually just stumbled about a case where the graph didn't catch an occurance (test case `codeAccess.sol`)

File: libsolidity/interface/CompilerStack.cpp (hunk 53 above)
Comment (cameel) [reply libsolidity/interface/CompilerStack.cpp]: I mostly meant boost. Good point about ranges though. Maybe we should start grouping them with stdlib.

File: libsolidity/interface/CompilerStack.cpp (hunk 54 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: Yep, I just noticed this, too. Good eye!

File: libsolidity/interface/CompilerStack.cpp (hunk 53 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: To my defernce, that boost include was there before I touched that part :P I'll move it down to it's own block.

File: libsolidity/ast/ASTAnnotations.h (hunk 49 above)
Comment (Marenz) [reply libsolidity/ast/ASTAnnotations.h]: Wait, are we talking about `SharedContractDependencyAnnotation` as in, the `contractDependencies` field for `FunctionDefinitionAnnotation` (and not for the `ContractAnnotation`) or is the idea to completely remove `contractDependencies` from all annotations?

Comment (chriseth) [reply libsolidity/ast/ASTAnnotations.h]: I don't think we need a field in the function definition annotation. contractDependencies should be computed only from the call graph, though.

Comment (Marenz) [reply libsolidity/ast/ASTAnnotations.h]: At the moment, if we don't fill that field from the `TypeChecker`, test cases like this will fail:

```
  Contract:
    contract C { function foo() internal { new D(); } }
    contract D { function foo() internal { new C(); } }

  Expected result:
    TypeError 7813: (91-96): Circular reference found.
  Obtained result:
    Success

```

I guess because neither function is currently reachable.

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 17 above)
Comment (Marenz) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: I ran a test and if we don't add them here, our tests all still work, EXCEPT the astjson tests who know are missing their contract dependency information for their field `contractDependencies`. I'll look into the callgraph and check if we can make it do that somehow..

**Comment by Marenz** [comment]
Updated, but still WIP, some things are still missing.

File: test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol (hunk 40 above)
Comment (Marenz) [reply test/libsolidity/syntaxTests/metaTypes/codeAccessBase.sol]: I reversed the contract <-> referencee now but this contract still only gets one error, no matter in how many contracts it is split... I didn't investigate further yet.

File: Changelog.md [hunk 56]
```diff
@@ -6,6 +6,7 @@ Language Features:
 Compiler Features:
  * Command Line Interface: Drop experimental support for ``--machine evm15``.
  * Optimizer: Try to move ``and`` with constant inside ``or`` to improve storage writes of small types.
+ * References Resolver: Detect circular references to other contracts across libraries and free functions
```
Comment (chriseth) [inline Changelog.md]: Has to be moved.

File: libsolidity/ast/ASTAnnotations.h [hunk 57]
```diff
@@ -159,16 +160,17 @@ struct ContractDefinitionAnnotation: TypeDeclarationAnnotation, StructurallyDocu
...
-	std::set<ContractDefinition const*> contractDependencies;
 	/// Mapping containing the nodes that define the arguments for base constructors.
 	/// These can either be inheritance specifiers or modifier invocations.
 	std::map<FunctionDefinition const*, ASTNode const*> baseConstructorArguments;
 	/// A graph with edges representing calls between functions that may happen during contract construction.
 	SetOnce<std::shared_ptr<CallGraph const>> creationCallGraph;
 	/// A graph with edges representing calls between functions that may happen in a deployed contract.
 	SetOnce<std::shared_ptr<CallGraph const>> deployedCallGraph;
+
+	/// List of contracts that this contract uses or creates, i.e. contracts which need to be compiled first.
```
Comment (chriseth) [inline libsolidity/ast/ASTAnnotations.h]: List of contracts whose bytecode is referenced by this contract, e.g. through "new".

File: libsolidity/ast/ASTJsonConverter.cpp [hunk 58]
```diff
@@ -269,7 +271,10 @@ bool ASTJsonConverter::visit(ContractDefinition const& _node)
 		make_pair("contractKind", contractKind(_node.contractKind())),
 		make_pair("abstract", _node.abstract()),
 		make_pair("baseContracts", toJson(_node.baseContracts())),
-		make_pair("contractDependencies", getContainerIds(_node.annotation().contractDependencies, true)),
+		make_pair("contractDependencies", getContainerIds(
+			_node.annotation().contractDependencies | views::keys,
+			true
```
Comment (chriseth) [inline libsolidity/ast/ASTJsonConverter.cpp]: Aren't they already sorted by ID?

File: libsolidity/interface/CompilerStack.cpp [hunk 59]
```diff
@@ -103,6 +107,98 @@ CompilerStack::~CompilerStack()
...
 }
 
+void CompilerStack::createAndAssignCallGraphs()
+{
+	for (Source const* source: m_sourceOrder)
+		if (source->ast)
+			for (ASTPointer<ASTNode> const& node: source->ast->nodes())
+				if (auto const* contract = dynamic_cast<ContractDefinition*>(node.get()))
+				{
+					Contract& contractState = m_contracts.at(contract->fullyQualifiedName());
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Can you somehow reduce the indentation level here?

Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp]: You can use `ASTNode::filteredeNodes<ContractDefinitoin>` or something like that

File: libsolidity/interface/CompilerStack.cpp [hunk 60]
```diff
@@ -103,6 +107,98 @@ CompilerStack::~CompilerStack()
...
+
+					contractState.contract->annotation().creationCallGraph = make_unique<CallGraph>(
+						FunctionCallGraphBuilder::buildCreationGraph(
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Why split the line here? The previous line is much longer.

File: libsolidity/interface/CompilerStack.cpp [hunk 61]
```diff
@@ -103,6 +107,98 @@ CompilerStack::~CompilerStack()
...
+						)
+					);
+					contractState.contract->annotation().deployedCallGraph = make_unique<CallGraph>(
+						FunctionCallGraphBuilder::buildDeployedGraph(
+							*contract,
+							**contractState.contract->annotation().creationCallGraph
+						)
+					);
+
+					auto contractDeps = ranges::views::concat(
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: This should just read 
```
contractState.contract->annotation().contractDependencies = contract->annotation().creationCallGraph->get()->bytecodeDependency + contract->annotation().deployedCallGraph->get()->bytecodeDependency;
```
If not, please adjust the types.

Also can you *please* introduce a local variable for the annotation? You are using it five times...

File: libsolidity/interface/CompilerStack.cpp [hunk 62]
```diff
@@ -103,6 +107,98 @@ CompilerStack::~CompilerStack()
...
+		if (source->ast)
+			for (ASTPointer<ASTNode> const& node: source->ast->nodes())
+				if (auto const* contractDefinition = dynamic_cast<ContractDefinition*>(node.get()))
+				{
+					ContractDefinition const* cycle = cycleDetector.run(*contractDefinition);
+
+					if (cycle)
+					{
+						solAssert(cycleDetector.m_cycleReferencee, "");
+						foundCycles.emplace(cycleDetector.m_cycleReferencee, cycle);
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Why don't you report it right here?

Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp]: You can use a simple set to track what you already reported, but you don't need to store the other information.

File: libsolidity/interface/CompilerStack.cpp [hunk 63]
```diff
@@ -103,6 +107,98 @@ CompilerStack::~CompilerStack()
...
+
+					for (auto const& [dependencyContract, referencee]: contractDeps)
+					{
+						solAssert(dependencyContract != nullptr, "");
+						contractState.contract->annotation().contractDependencies.emplace(dependencyContract, referencee);
+					}
+				}
+}
+
+void CompilerStack::findAndReportCyclicContractDependencies()
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp:143]: Why does this look so much more complicated than ConstStateVarCircularReferenceChecker ?

File: test/libsolidity/ASTJSON/override.sol [hunk 64]
```diff
@@ -1,13 +1,13 @@
 contract A {
```
Comment (chriseth) [inline test/libsolidity/ASTJSON/override.sol:1]: Why did you change this test?

File: libsolidity/ast/ASTJsonConverter.cpp (hunk 58 above)
Comment (Marenz) [reply libsolidity/ast/ASTJsonConverter.cpp]: The change here is not due to sorting but due to the type change to a map of `contractDependencies`

File: test/libsolidity/ASTJSON/override.sol (hunk 64 above)
Comment (Marenz) [reply test/libsolidity/ASTJSON/override.sol:1]: It was made of invalid code that for some reason still successfully exported ast json. However it was no longer successful after the contractDependencies change..

File: libsolidity/ast/ASTJsonConverter.cpp (hunk 58 above)
Comment (chriseth) [reply libsolidity/ast/ASTJsonConverter.cpp]: I know, but you can remove the `true` now, can't you?

File: test/libsolidity/ASTJSON/override.sol (hunk 64 above)
Comment (chriseth) [reply test/libsolidity/ASTJSON/override.sol:1]: I don't see why the dependencies change makes it invalid.

Comment (Marenz) [reply test/libsolidity/ASTJSON/override.sol:1]: Indeed, it seems and I was wrong. Those changes aren't really required, but having valid compilable code in a test still seems like a good idea to me.

File: libsolidity/interface/CompilerStack.cpp (hunk 63 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp:143]: One of the factors that makes this more complicated is this: For the const variables, we only have the declaration and the identifier that causes a cycling dependency.
For contracts, we start with the contract and find a dependency cycle. But then we also want to know which ASTNode (expression) caused the dependency and that information is also in the map `contractDependencies` but it might not be in the originating contract but instead in a dependent contract. 
So to find the ast node that made the reference, I either have to go through all dependencies (and their dependencies) again, finding the contract -> ast node mapping or I remember it and save it when I find the cycle. The later thing is what I am trying to do, but it is very difficult to do this cleanly. I tried to avoid modifying or extending the CycleDetector directly, but that leaves me only limited options, e.g. using the `RememberingCycleDetector` and when I investigated some parts here yesterday, I started to suspect that it's not even done right at the moment so I might have to find another solution to do this. Maybe I have to extend it directly...

File: libsolidity/interface/CompilerStack.cpp [hunk 65]
```diff
@@ -103,6 +107,98 @@ CompilerStack::~CompilerStack()
...
+{
+	// Cycles we found, used to avoid duplicate reports for the same reference
+	map<ASTNode const*, ContractDefinition const*, ASTNode::CompareByID> foundCycles;
+
+	// Use an extra struct to remember the reference for the found cycle
+	struct RememberingCycleDetector : public util::CycleDetector<ContractDefinition>
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: There is absolutely no need to create a subclass here. You are working with a lambda function that captures. Why don't you just use a local variable to store the reference?

File: libsolidity/interface/CompilerStack.cpp [hunk 66]
```diff
@@ -399,33 +495,17 @@ bool CompilerStack::analyze()
...
-						}
+			createAndAssignCallGraphs();
+			findAndReportCyclicContractDependencies();
 		}
 
-		if (noErrors)
-		{
-			// Checks that can only be done when all types of all AST nodes are known.
-			PostTypeChecker postTypeChecker(m_errorReporter);
+	if (noErrors)
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Why is this indented differently?

File: libsolidity/interface/CompilerStack.cpp (hunk 65 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: I tried many variations here and it seemed cleaner to me to have it in a subclass, but it seems I have to change this again because it's still not working as it should

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 17 above)
Comment (Marenz) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: Alright, I misinterpreted a previous error wrongly and it seems this does indeed break tests involving libraries like this one:

```
library L {
    function f() internal {
        new C();
    }
}

contract D {
    function f() public {
        L.f();
    }
}
contract C {
    constructor() { new D(); }
}
```

The problem is that we never detect the `new C();` in `L.f()` and never fill the dependency `C` for `L`..

Comment (chriseth) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: So the call graph does not properly handle internal library functions? I think there should not be a dependency from L to C but rather from D to C, because the code of L.f is included directly in D.

Comment (Marenz) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: That would also explain the problem I am seeing. I'll see if I can fix my problem with that information..

File: libsolidity/interface/CompilerStack.cpp (hunk 61 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: We don't have an `operator+()` for maps....

File: libsolidity/interface/CompilerStack.cpp (hunk 66 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: That was a mistake.

File: libsolidity/interface/CompilerStack.cpp (hunk 65 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: Turned out I don't need any of that. After carefully analysing the problem I found that my solution was very wrong..

File: libsolidity/ast/ASTJsonConverter.cpp (hunk 58 above)
Comment (Marenz) [reply libsolidity/ast/ASTJsonConverter.cpp]: Ah, right. I didn't see that the function also does ordering (not obvious from the name)

File: Changelog.md [hunk 67]
```diff
@@ -29,6 +29,7 @@ Compiler Features:
 
 Bugfixes:
  * AST Import: For constructors, a public visibility is ignored during importing.
+ * References Resolver: Detect circular references to other contracts across libraries and free functions
```
Comment (chriseth) [inline Changelog.md]: needs to be moved

File: libsolidity/analysis/FunctionCallGraph.cpp [hunk 68]
```diff
@@ -199,6 +199,7 @@ bool FunctionCallGraphBuilder::visit(MemberAccess const& _memberAccess)
 		solAssert(*_memberAccess.annotation().requiredLookup == VirtualLookup::Static, "");
 
 	functionReferenced(*functionDef, _memberAccess.annotation().calledDirectly);
+
```
Comment (chriseth) [inline libsolidity/analysis/FunctionCallGraph.cpp]: Is this a leftover or on purpose?

File: Changelog.md (hunk 67 above)
Comment (Marenz) [reply Changelog.md]: due to rebasing I didn't see the new release entry and thought you meant it should be moved to bugfixes (previously new features).

File: libsolidity/analysis/FunctionCallGraph.cpp (hunk 68 above)
Comment (Marenz) [reply libsolidity/analysis/FunctionCallGraph.cpp]: Well.. kind of both? visually I think it's better, but it only is in the PR because I touched & reverted things in that file...

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 69]
```diff
@@ -379,17 +379,18 @@ void NameAndTypeResolver::linearizeBaseContracts(ContractDefinition& _contract)
 		// "push_front" has the effect that bases mentioned later can overwrite members of bases
 		// mentioned earlier
 		input.back().push_front(base);
+
```
Comment (chriseth) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: Same here.

File: libsolutil/Common.h [hunk 70]
```diff
@@ -73,6 +73,9 @@ using StringMap = std::map<std::string, std::string>;
 // String types.
 using strings = std::vector<std::string>;
 
+/// Max depth a cycle detection recursion should go before erroring out
```
Comment (chriseth) [inline libsolutil/Common.h]: I don't think solutil is the right place for this, it is a setting for the analyzer. I mean we could also just use literals in both places, not sure if they really need names or need to have the same value.

File: libsolidity/ast/ASTAnnotations.h [hunk 71]
```diff
@@ -158,16 +158,17 @@ struct ContractDefinitionAnnotation: TypeDeclarationAnnotation, StructurallyDocu
...
 	/// Mapping containing the nodes that define the arguments for base constructors.
 	/// These can either be inheritance specifiers or modifier invocations.
 	std::map<FunctionDefinition const*, ASTNode const*> baseConstructorArguments;
 	/// A graph with edges representing calls between functions that may happen during contract construction.
 	SetOnce<std::shared_ptr<CallGraph const>> creationCallGraph;
 	/// A graph with edges representing calls between functions that may happen in a deployed contract.
 	SetOnce<std::shared_ptr<CallGraph const>> deployedCallGraph;
+
+	/// List of contracts whose bytecode is referenced by this contract, e.g. through "new".
+	/// The Value represents the ast node that referenced the contract
```
Comment (chriseth) [inline libsolidity/ast/ASTAnnotations.h]:
```suggestion
	/// The value represents the ast node that referenced the contract.
```

File: libsolidity/ast/ASTForward.cpp [hunk 72]
```diff
@@ -0,0 +1,42 @@
+/*
```
Comment (chriseth) [inline libsolidity/ast/ASTForward.cpp]: leftover?

Comment (Marenz) [reply libsolidity/ast/ASTForward.cpp]: it's from the "fix macos" commit which is temporary. will be properly integrated now

File: libsolidity/ast/ASTForward.h [hunk 73]
```diff
@@ -99,6 +99,25 @@ class StructuredDocumentation;
 
 class VariableScope;
 
+template <class T>
```
Comment (chriseth) [inline libsolidity/ast/ASTForward.h:103]: Just defining it for ASTNode does not work because of the implicit conversion?

File: libsolidity/interface/CompilerStack.cpp [hunk 74]
```diff
@@ -103,6 +107,101 @@ CompilerStack::~CompilerStack()
...
 
+void CompilerStack::createAndAssignCallGraphs()
+{
+	for (Source const* source: m_sourceOrder)
+	{
+		if (!source->ast)
+			continue;
+
+		for (ContractDefinition const* contract: ASTNode::filteredNodes<ContractDefinition>(source->ast->nodes()))
+
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]:
```suggestion
```

File: libsolidity/interface/CompilerStack.cpp [hunk 75]
```diff
@@ -103,6 +107,101 @@ CompilerStack::~CompilerStack()
...
+		{
+			ContractDefinitionAnnotation& annotation =
+				m_contracts.at(contract->fullyQualifiedName()).contract->annotation();
+
+			annotation.creationCallGraph = make_unique<CallGraph>(
+				FunctionCallGraphBuilder::buildCreationGraph(
+					*contract
+				)
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]:
```suggestion
				FunctionCallGraphBuilder::buildCreationGraph(*contract)
```

File: libsolidity/interface/CompilerStack.cpp [hunk 76]
```diff
@@ -103,6 +107,101 @@ CompilerStack::~CompilerStack()
...
+}
+
+void CompilerStack::findAndReportCyclicContractDependencies()
+{
+	// Cycles we found, used to avoid duplicate reports for the same reference
+	set<ASTNode const*, ASTNode::CompareByID> foundCycles;
+
+	for (Source const* source: m_sourceOrder)
+	{
+		if (!source->ast)
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp:150]: Can this happen at this stage?

File: libsolidity/interface/CompilerStack.cpp [hunk 77]
```diff
@@ -103,6 +107,101 @@ CompilerStack::~CompilerStack()
...
+			continue;
+
+		for (ContractDefinition const* contractDefinition: ASTNode::filteredNodes<ContractDefinition>(source->ast->nodes()))
+		{
+			// Ignore libraries as they are tested as part of the
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: I don't think we can do that, libraries can also be deployed in isolation.

File: libsolidity/interface/CompilerStack.cpp [hunk 78]
```diff
@@ -103,6 +107,101 @@ CompilerStack::~CompilerStack()
...
+					if (_cycleDetector.run(*dependencyContract))
+						return;
+			}};
+
+			ContractDefinition const* cycle = cycleDetector.run(*contractDefinition);
+
+			if (!cycle)
+				continue;
+
+			ASTNode const* referencee = contractDefinition->annotation().contractDependencies.at(cycle);
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp:179]: What if we have a cycle of the form
`a -> b -> c -> d -> c`?
Then the return vaule of the `cycleDetector` will be `c`, which is not a dependency of `a`

File: libsolidity/interface/CompilerStack.cpp (hunk 76 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp:150]: I haven't checked it, but every single iteration in `analyze()` does it that way so it felt safer to keep it..

File: libsolidity/interface/CompilerStack.cpp (hunk 77 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: In that case we have to change the function call graph to handle internal functions as well when it's a library, even if they are not called...

I would suggest to do that in an extra PR and leave it like this in this one.

File: test/libsolidity/ASTJSON/override.sol (hunk 64 above)
Comment (chriseth) [reply test/libsolidity/ASTJSON/override.sol:1]: Can you extract it into its own PR?

**Comment by chriseth** [comment]
Can you add a semantic test that shows that having a "fake cyclic dependency" through a function in a base contract that is never called actually works?

File: libsolidity/interface/CompilerStack.cpp (hunk 78 above)
Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp:179]: This is okay (I also tested your example just now) as the cycle Detector returns only and always the vertex that has a distance of 1 (depth = 1) to the originating vertex

File: libsolidity/ast/ASTForward.h (hunk 73 above)
Comment (Marenz) [reply libsolidity/ast/ASTForward.h:103]: It works for everything except the mac osx build

**Comment by Marenz** [comment]
> Can you add a semantic test that shows that having a "fake cyclic dependency" through a function in a base contract that is never called actually works?

You mean an `internal` function correct?

File: libsolidity/interface/CompilerStack.cpp (hunk 77 above)
Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp]: Internal library functions that are not called will be ignored, but there are also public library functions.

**Comment by chriseth** [comment]
Yes, we discussed such examples in the context of whether or not the base contract should be automatically added to the dependencies or not.

**Comment by Marenz** [comment]
Added requested test case: 
```
contract C
{
	// Internal uncalled function should not cause an cyclic dep. error
	function foo() internal { new D(); }
}

contract D is C
{
}
```

**Comment by chriseth** [comment]
I think we should also add a more complicated case:
There is another public function in `C` that calls `foo`, but it is overwritten in `D` by an empty function.

**Comment by Marenz** [comment]
That would still cause an error though if C is not abstract, that is.

**Comment by chriseth** [comment]
Needs rebase.

File: Changelog.md [hunk 79]
```diff
@@ -9,6 +9,7 @@ Compiler Features:
  * SMTChecker: Report out of bounds index access for arrays and fixed bytes.
  * Standard JSON: Model checker option ``settings.modelChecker.targets`` also accepts ``outOfBounds``.
  * Yul Optimizer: Added a new step FunctionSpecializer, that specializes a function with its literal arguments.
+ * References Resolver: Detect circular references to other contracts across libraries and free functions
```
Comment (chriseth) [inline Changelog.md]: It is not really the references resolver. Cannot think of a better word now. We can just call it "Analysis" if we do not find a better word.

Also please use "code references". References is too general.

File: libsolidity/interface/CompilerStack.cpp (hunk 78 above)
Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp:179]: Interesting, this is not how CycleDetector should work. I will double-check, because I thought it works correctly with constants.

Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp:179]: Yeah, the code in line 64 of Algorithms.h does that. Ok, let's just leave it like that.

File: libsolidity/interface/CompilerStack.cpp (hunk 77 above)
Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp]: The call graph is working perfectly fine. I'll just remove this condition here. Also added some more tests.

**Review by chriseth — DISMISSED** [review]
