### PR TITLE
Disallow function access in inline assembly

### LINKED ISSUE #8386: ICE in ContractCompiler::visit(InlineAssembly &)
## Description

This contract:
```solidity
contract C {
    function f() public pure {}
    constructor() public {
        assembly {
            let x := f
        }
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/codegen/ContractCompiler.cpp(667): Throw in function auto solidity::frontend::ContractCompiler::visit(const solidity::frontend::InlineAssembly &)::(anonymous class)::operator()(const yul::Identifier &, yul::IdentifierContext, yul::AbstractAssembly &) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

## Environment

- Compiler version:  0.6.3-develop.2020.2.10+commit.e8eb1f2d.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by aarlt**
Fix #8386.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -739,8 +739,7 @@ bool TypeChecker::visit(InlineAssembly const& _inlineAssembly)
 		{
 			solAssert(!!declaration->type(), "Type of declaration required but not yet determined.");
 			if (dynamic_cast<FunctionDefinition const*>(declaration))
-			{
-			}
+				m_errorReporter.declarationError(_identifier.location, "Access to functions not allowed in inline assembly.");
```
Comment (leonardoalt) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
				m_errorReporter.declarationError(_identifier.location, "Access to functions is not allowed in inline assembly.");
```

File: libyul/AsmAnalysis.cpp [hunk 2]
```diff
@@ -135,7 +135,7 @@ vector<YulString> AsmAnalyzer::operator()(Identifier const& _identifier)
 		{
 			bool insideFunction = m_currentScope->insideFunction();
 			size_t stackSize = m_resolver(_identifier, yul::IdentifierContext::RValue, insideFunction);
-			if (stackSize != size_t(-1))
+			if (!m_errorReporter.hasErrors() && stackSize != size_t(-1))
```
Comment (leonardoalt) [inline libyul/AsmAnalysis.cpp]: What happens without this?

**Review by leonardoalt — CHANGES_REQUESTED** [review]
I think this needs a Changelog entry.

File: libyul/AsmAnalysis.cpp (hunk 2 above)
Comment (aarlt) [reply libyul/AsmAnalysis.cpp]: without this `found` will be set to `true` and finally not setting `m_success` to `false`. probably this can be cleaned up a bit.

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: and return `size_t(-1)`.

File: libyul/AsmAnalysis.cpp (hunk 2 above)
Comment (chriseth) [reply libyul/AsmAnalysis.cpp]: Please see above.

Comment (aarlt) [reply libyul/AsmAnalysis.cpp]: Ah, nice!

**Comment by chriseth** [comment]
Please do not use issue numbers in commit descriptions and please create branches directly on the main repository instead of your own fork.

**Review by chriseth — APPROVED** [review]

**Review by ekpyron — APPROVED** [review]
