### PR TITLE
Separate control flow from error reporting in command line parser

### LINKED ISSUE #11731: [CLI] Separate control flow from error reporting in `CommandLineParser`
This is a continuation of the CLI refactor from #11518. Getting rid of `exit()` was suggested in the review.

Currently [`CommandLineParser`](https://github.com/ethereum/solidity/blob/develop/solc/CommandLineParser.h) uses the mechanism inherited from `CommandLineInterface` to report errors - it prints a message to the error stream and returns `false`.

- This is too inflexible in some situations - for example it can't return a value that will make the application exit without reporting an error so when it wants ro do so, it just calls `exit()` which terminates the application.
- Sometimes errors are returned in nested calls and the return value has to be bubbled up, which is error prone (see for example https://github.com/ethereum/solidity/pull/11544#discussion_r669767594).
- It also makes the code overly verbose - returning an error takes several lines of code (braces, printing to `serr()`, returning). Throwing exceptions would be more concise.

Here's my proposal on how to refactor this:

1) Modify `CommandLineInterface` so that the return value from the parser only indicates whether it should continue processing (`true`) or immediately exit without error (`false`).
    - Modify the functions that print version and license info in `CommandLineParser` to make them not use `exit()`.
    - Consider moving all of the printing logic to `CommandLineInterface`. The parser should only signal that printing was requested on the command line, not perform the action. This would be more in line with the purpose of the class and would let us get rid of the `sout()` stream form it.
2) Define an exception type that represents a command line validation error.
    - Replace all the code that prints to `serr()` and returns `false` with throwing that exception.
        - Remember to use `BOOST_THROW_EXCEPTION` macro.
    - Remove the `serr()` stream from the parser.
    - Consider defining a whole exception hierarchy and moving message formatting to specific exception classes. The parser could then be leaner and simply pass in the raw info needed to construct the message (file names, option names, option values, etc).
3) Catch the validation error in `CommandLineInterface` and handle it by printing the message to stderr and exiting with an error code.
    - Move the existing handler for `boost::program_options::error` from `CommandLineParser::parse()` to `CommandLineInterface` too. They're the same kind of error and should really be handled the same way.

### PR DESCRIPTION
**Pull request by neelriyer**
Partially Resolves #11731

I did the following:
- Modified the functions that print version and license info in `CommandLineParser` to make them not use `exit()`.
- Replaced all the code that prints to `serr()` and returns `false` with an exception (uses the `BOOST_THROW_EXCEPTION` macro)

Doesn't change too much. This is my first commit to this repository. Let me know what you think.

EDIT by cameel:
- ~Depends on #12125.~ Merged.
- ~Depends on #12118.~ Merged.

It's not based on these two PRs to avoid github closing it when they're merged. Instead it contains commits from these PRs. I'll rebase it to remove them when those PRs are merged.

### CODE REVIEW

File: liblangutil/Exceptions.h [hunk 1]
```diff
@@ -44,6 +44,7 @@ struct InternalCompilerError: virtual util::Exception {};
 struct FatalError: virtual util::Exception {};
 struct UnimplementedFeatureError: virtual util::Exception {};
 struct InvalidAstError: virtual util::Exception {};
+struct CommandLineValidationError: virtual util::Exception {};
```
Comment (cameel) [inline liblangutil/Exceptions.h]: I'd create a new `Exceptions.h` file in `solc/` and put the exception there. `liblangutil/` is for much more generic stuff and this exception will only be used by classes inside the `solc/` directory.

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -387,14 +387,12 @@ bool CommandLineInterface::readInputFiles()
 	{
 		if (!boost::filesystem::exists(m_fileReader.basePath()))
 		{
-			serr() << "Base path does not exist: " << m_fileReader.basePath() << endl;
-			return false;
+			BOOST_THROW_EXCEPTION(CommandLineValidationError() << errinfo_comment("Base path does not exist: "));
 		}
```
Comment (cameel) [inline solc/CommandLineInterface.cpp]: These braces are no longer needed. Please remove them here and in other places. Making the code less verbose is one of the goals of this change after all.

File: solc/CommandLineInterface.cpp [hunk 3]
```diff
@@ -387,14 +387,12 @@ bool CommandLineInterface::readInputFiles()
 	{
 		if (!boost::filesystem::exists(m_fileReader.basePath()))
 		{
-			serr() << "Base path does not exist: " << m_fileReader.basePath() << endl;
-			return false;
+			BOOST_THROW_EXCEPTION(CommandLineValidationError() << errinfo_comment("Base path does not exist: "));
```
Comment (cameel) [inline solc/CommandLineInterface.cpp]: The new message no longer contains `m_fileReader.basePath()`.

Same below and some other places. Please make sure that the exceptions still contain all the information that used to be printed to stderr.

File: solc/CommandLineInterface.cpp [hunk 4]
```diff
@@ -505,15 +501,15 @@ void CommandLineInterface::createFile(string const& _fileName, string const& _da
 	string pathName = (m_options.output.dir / _fileName).string();
 	if (fs::exists(pathName) && !m_options.output.overwriteFiles)
 	{
-		serr() << "Refusing to overwrite existing file \"" << pathName << "\" (use --overwrite to force)." << endl;
+		BOOST_THROW_EXCEPTION(CommandLineValidationError() << errinfo_comment("Refusing to overwrite existing file \"" << pathName << "\" (use --overwrite to force).");
```
Comment (cameel) [inline solc/CommandLineInterface.cpp]: I don't think this will work. You're using the `<<` operator on a string.

File: solc/CommandLineInterface.cpp [hunk 5]
```diff
@@ -649,32 +644,20 @@ bool CommandLineInterface::compile()
 	}
 	catch (InternalCompilerError const& _exception)
 	{
-		serr() <<
-			"Internal compiler error during compilation:" <<
-			endl <<
-			boost::diagnostic_information(_exception);
-		return false;
+		BOOST_THROW_EXCEPTION(CommandLineValidationError() << errinfo_comment("Internal compiler error during compilation:" << boost::diagnostic_information(_exception));
 	}
```
Comment (cameel) [inline solc/CommandLineInterface.cpp]: I just noticed that you're modifying `CommandLineInterface`. We should refactor it eventually too but we really need to have #11732 first - otherwise nothing is catching these exceptions. That's why this issue is only about `CommandLineParser` for now. Please remove changes from this file and start with `CommandLineParser` instead. The only changes here should be in `CommandLineInterface::parseArguments()` - that's where the exceptions should be caught.

File: solc/CommandLineParser.cpp [hunk 6]
```diff
@@ -189,15 +189,13 @@ void CommandLineParser::printVersionAndExit()
 		"Version: " <<
 		solidity::frontend::VersionString <<
 		endl;
-	exit(EXIT_SUCCESS);
```
Comment (cameel) [inline solc/CommandLineParser.cpp]: It's not as simple as just removing the `exit()` :) The compiler must still exit after printing this info, just not like this. You should instead make `CommandLineParser::parse()` return `false` after it runs one of these functions. But now returning `false` means that there was an error - which is why you first need to ensure that returning with an error is only done by raising an exception.

**Review by cameel — DISMISSED** [review]
This needs more work :) The biggest problem is that you're modifying the wrong file - the issue is about `CommandLineParser` and there are only small adjustments needed in `CommandLineInterface`.

Let me know if you need some more hints on how to continue.

**Comment by s0sharma** [comment]
I'll make the changes.

**Comment by neelriyer** [comment]
Thanks @cameel. I'm kind of embarrassed to have submitted this now :). I'll try to work on this and get back to you. Thanks for your help!

**Comment by cameel** [comment]
@spiyer99 Are you working on this? Do you need help?

We have a ton of pending PRs right now and we'd like trim that number down a bit. If you don't have time for it, I can take over and finish it.

**Comment by cameel** [comment]
This is almost finished. The one remaining thing is to update docstrings in `CommandLineInterface` and `CommandLineParser`.

Also #12125 and #12118 need to be merged first so I'm keeping it as a draft for now.

**Comment by cameel** [comment]
This is now ready but still waiting for #12118 to be merged.

**Comment by cameel** [comment]
In https://github.com/ethereum/solidity/pull/12125#issuecomment-942121559 @chriseth said it's ok to slightly change the control flow so that output errors cause an immediate failure (instead of just setting a flag and failing later after the output stage). I added a commit that changes it.

**Comment by neelriyer** [comment]
> @spiyer99 Are you working on this? Do you need help?
> 
> We have a ton of pending PRs right now and we'd like trim that number down a bit. If you don't have time for it, I can take over and finish it.

Hey @cameel sorry for the late reply. I actually forgot about this, but good to see that you got this done in my absence 😊.

**Comment by cameel** [comment]
All dependencies have been merged so this is now reviewable.

File: test/solc/CommandLineParser.cpp [hunk 7]
```diff
@@ -75,12 +73,9 @@ BOOST_AUTO_TEST_CASE(no_options)
 	expectedOptions.modelChecker.initialize = true;
 	expectedOptions.modelChecker.settings = {};
 
-	stringstream serr;
-	optional<CommandLineOptions> parsedOptions = parseCommandLine(commandLine, serr);
+	CommandLineOptions parsedOptions = parseCommandLine(commandLine);
 
-	BOOST_TEST(serr.str() == "");
-	BOOST_REQUIRE(parsedOptions.has_value());
-	BOOST_TEST(parsedOptions.value() == expectedOptions);
```
Comment (chriseth) [inline test/solc/CommandLineParser.cpp:83]: Not relevant here, but you can actually compare `optional<T>` with `T` directly, so this and the previous line would be equivalent to
`BOOST_TEST(parsedOptions == expectedOptions);`

File: solc/CommandLineInterface.cpp [hunk 8]
```diff
@@ -1003,6 +1002,8 @@ bool CommandLineInterface::assemble(yul::AssemblyStack::Language _language, yul:
 {
 	solAssert(m_options.input.mode == InputMode::Assembler, "");
 
+	serr() << "Warning: Yul is still experimental. Please use the output with care." << endl;
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp:988]: Are you sure this is the right place?

Comment (chriseth) [reply solc/CommandLineInterface.cpp:988]: Yes, it seems it is.

**Review by chriseth — APPROVED** [review]

File: test/solc/CommandLineParser.cpp (hunk 7 above)
Comment (cameel) [reply test/solc/CommandLineParser.cpp:83]: I think that it won't work with this macro though because boost requires both types to be printable so I'd have to define `<<` also for the optional version. Well, maybe a generic `<<` for printing `optional<T>` you had in one of your PRs would work for that.
