### PR TITLE
Fix invalid Yul escapes generated from literals in assembly blocks

### LINKED ISSUE #11524: [Sol->Yul] Invalid IR code generated when compiling code with hex string
```
contract S{
  function f() public{
    assembly { let b := hex"08" }
  }
}
```

throws

```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/ir/IRGenerator.cpp(104): Throw in function pair<std::string, std::string> solidity::frontend::IRGenerator::run(const solidity::frontend::ContractDefinition &, const map<const solidity::frontend::ContractDefinition *, const std::string_view> &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
object "S_6" {
    code {
        mstore(64, 128)
        if callvalue() { revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() }

        constructor_S_6()

        let _1 := allocate_unbounded()
        codecopy(_1, dataoffset("S_6_deployed"), datasize("S_6_deployed"))

        return(_1, datasize("S_6_deployed"))

        function allocate_unbounded() -> memPtr {
            memPtr := mload(64)
        }

        function constructor_S_6() {

        }

        function revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() {
            revert(0, 0)
        }

    }
    object "S_6_deployed" {
        code {
            mstore(64, 128)

            if iszero(lt(calldatasize(), 4))
            {
                let selector := shift_right_224_unsigned(calldataload(0))
                switch selector

                case 0x26121ff0
                {
                    // f()

                    if callvalue() { revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() }
                    abi_decode_tuple_(4, calldatasize())
                    fun_f_5()
                    let memPos := allocate_unbounded()
                    let memEnd := abi_encode_tuple__to__fromStack(memPos  )
                    return(memPos, sub(memEnd, memPos))
                }

                default {}
            }
            if iszero(calldatasize()) {  }
            revert_error_42b3090547df1d2001c96683413b8cf91c1b902ef5e3cb8d9f6f304cf7446f74()

            function abi_decode_tuple_(headStart, dataEnd)   {
                if slt(sub(dataEnd, headStart), 0) { revert_error_dbdddcbe895c83990c08b3492a0e83918d802a52331272ac6fdb6a7c4aea3b1b() }

            }

            function abi_encode_tuple__to__fromStack(headStart ) -> tail {
                tail := add(headStart, 0)

            }

            function allocate_unbounded() -> memPtr {
                memPtr := mload(64)
            }

            function fun_f_5() {

                { let usr$b := "\b" }

            }

            function revert_error_42b3090547df1d2001c96683413b8cf91c1b902ef5e3cb8d9f6f304cf7446f74() {
                revert(0, 0)
            }

            function revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() {
                revert(0, 0)
            }

            function revert_error_dbdddcbe895c83990c08b3492a0e83918d802a52331272ac6fdb6a7c4aea3b1b() {
                revert(0, 0)
            }

            function shift_right_224_unsigned(value) -> newValue {
                newValue :=

                shr(224, value)

            }

        }

    }

}



Invalid IR generated:
Error: Illegal token: Invalid escape sequence.

Error: Expected keyword "data" or "object" or "}".



[solidity::util::tag_comment*] = 
object "S_6" {
    code {
        mstore(64, 128)
        if callvalue() { revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() }

        constructor_S_6()

        let _1 := allocate_unbounded()
        codecopy(_1, dataoffset("S_6_deployed"), datasize("S_6_deployed"))

        return(_1, datasize("S_6_deployed"))

        function allocate_unbounded() -> memPtr {
            memPtr := mload(64)
        }

        function constructor_S_6() {

        }

        function revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() {
            revert(0, 0)
        }

    }
    object "S_6_deployed" {
        code {
            mstore(64, 128)

            if iszero(lt(calldatasize(), 4))
            {
                let selector := shift_right_224_unsigned(calldataload(0))
                switch selector

                case 0x26121ff0
                {
                    // f()

                    if callvalue() { revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() }
                    abi_decode_tuple_(4, calldatasize())
                    fun_f_5()
                    let memPos := allocate_unbounded()
                    let memEnd := abi_encode_tuple__to__fromStack(memPos  )
                    return(memPos, sub(memEnd, memPos))
                }

                default {}
            }
            if iszero(calldatasize()) {  }
            revert_error_42b3090547df1d2001c96683413b8cf91c1b902ef5e3cb8d9f6f304cf7446f74()

            function abi_decode_tuple_(headStart, dataEnd)   {
                if slt(sub(dataEnd, headStart), 0) { revert_error_dbdddcbe895c83990c08b3492a0e83918d802a52331272ac6fdb6a7c4aea3b1b() }

            }

            function abi_encode_tuple__to__fromStack(headStart ) -> tail {
                tail := add(headStart, 0)

            }

            function allocate_unbounded() -> memPtr {
                memPtr := mload(64)
            }

            function fun_f_5() {

                { let usr$b := "\b" }

            }

            function revert_error_42b3090547df1d2001c96683413b8cf91c1b902ef5e3cb8d9f6f304cf7446f74() {
                revert(0, 0)
            }

            function revert_error_ca66f745a3ce8ff40e2ccaf1ad45db7774001b90d25810abd9040049be7bf4bb() {
                revert(0, 0)
            }

            function revert_error_dbdddcbe895c83990c08b3492a0e83918d802a52331272ac6fdb6a7c4aea3b1b() {
                revert(0, 0)
            }

            function shift_right_224_unsigned(value) -> newValue {
                newValue :=

                shr(224, value)

            }

        }

    }

}



Invalid IR generated:
Error: Illegal token: Invalid escape sequence.

Error: Expected keyword "data" or "object" or "}".
```

Repro

```
$ solc --experimental-via-ir test.sol
```

### PR DESCRIPTION
**Pull request by cameel**
Fixes #11524.

### CODE REVIEW

File: libsolutil/CommonData.h [hunk 1]
```diff
@@ -554,7 +554,7 @@ std::string formatAsStringOrNumber(std::string const& _value);
 
 /// @returns a string with the usual backslash-escapes for non-ASCII
 /// characters and surrounded by '"'-characters.
-std::string escapeAndQuoteString(std::string const& _input);
+std::string escapeAndQuoteYulString(std::string const& _input);
```
Comment (cameel) [inline libsolutil/CommonData.h:557]: This function is currently only used for Yul strings so I just renamed it instead of adding a parameter for selecting between languages.

If you think we should instead make this function handle both languages, see the first commit without the fixup. I can drop the fixup if that's better.

File: test/libyul/yulSyntaxTests/hex_string_literal_non_printable_characters.yul [hunk 2]
```diff
@@ -0,0 +1,6 @@
+{
+    let name := hex"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
+}
```
Comment (cameel) [inline test/libyul/yulSyntaxTests/hex_string_literal_non_printable_characters.yul:3]: This was not failing (only assembly blocks were affected) but we did not have this case covered so I'm adding a test.

**Comment by cameel** [comment]
No changelog entry. We still do not add them for the IR codegen, right?

**Comment by chriseth** [comment]
Looks good! Please squash.

**Comment by cameel** [comment]
Squashed.

**Review by chriseth — APPROVED** [review]

File: libsolutil/CommonData.h (hunk 1 above)
Comment (axic) [reply libsolutil/CommonData.h:557]: But it has nothing to do with Yul though.

Comment (cameel) [reply libsolutil/CommonData.h:557]: It didn't but now it does because sets of escapes supported by Soldity and Yul are different. `escapeAndQuoteYulString()` as it is now only uses escapes allowed in Yul.
