### PR TITLE
Disallow the exponent to be a signed integer literal

### LINKED ISSUE #9548: [solc] ICE because of signed exponent
## Description

```
contract C {
  function h() public {
    int x;
    ((x**-3));
  }
}
```

throws

https://github.com/ethereum/solidity/blob/cd2ce28317f87798a85cde000c7aa53e240969f5/libsolidity/codegen/ExpressionCompiler.cpp#L2186

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
libsolidity/codegen/ExpressionCompiler.cpp(2186): Throw in function void solidity::frontend::ExpressionCompiler::appendExpOperatorCode(const solidity::frontend::Type &, const solidity::frontend::Type &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

### PR DESCRIPTION
**Pull request by hrkrshnn**
Closes https://github.com/ethereum/solidity/issues/9548

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -712,6 +712,8 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
 				return TypeResult::err("Exponent is fractional.");
 			if (!rationalNumberType->integerType())
 				return TypeResult::err("Exponent too large.");
+			if (rationalNumberType->isNegative())
+				return TypeResult::err("Exponentiation power is not allowed to be a signed integer literal.");
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]:
```suggestion
				return TypeResult::err("Exponentiation power is not allowed to be a negative integer literal.");
```

**Review by chriseth — APPROVED** [review]
