### PR TITLE
Show proper error when trying to emit a non-event

### LINKED ISSUE #3973: Remix: Emitting a non-existing event creates an "unexpected error during compilation"
Source code to spawn this error in remix:

```
pragma solidity ^0.4.21;

contract Bug{
    uint256 Test;

    function TestFunc(){
        emit Test();
    }
}
```
    
Emitting non-event types spawns this "unexpected error" which makes this harder to debug.

I have not checked if this is a general solidity compiler bug, but it happens in remix.

### PR DESCRIPTION
**Pull request by axic**
Fixes #3973.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1067,6 +1067,8 @@ void TypeChecker::endVisit(EmitStatement const& _emit)
 {
 	if (
 		_emit.eventCall().annotation().kind != FunctionCallKind::FunctionCall ||
+		!type(_emit.eventCall().expression()) ||
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: The `type` function already has an assert that in never returns a null pointer.

**Review by chriseth — CHANGES_REQUESTED** [review]

**Comment by chriseth** [comment]
Will fix it and merge.

**Review by chriseth — APPROVED** [review]

**Review by chriseth — APPROVED** [review]
