### PR TITLE
Fix test expectation update

### LINKED ISSUE #8885: isoltest: Wrong update of test expectations
In `semanticTests/constants/constant_string.sol`, set compileViaYul to false, or remove the line.

When running `isoltest --enforce-via-yul` on that test, after saying that test can pass via yul auto update feature updates test expectations like this:
from 
```
// f() -> 0x20, 3, "\x03\x01\x02"
// g() -> 0x20, 3, "\x03\x01\x02"
// h() -> 0x20, 5, "hello"
```
to
```
// f() -> 0x20, 3, ""
// g() -> 0x20, 3, ""
// h() -> 0x20, 5, "hello"
```

### PR DESCRIPTION
**Pull request by a3d4**
Fixes #8885. I have no idea though if it breaks expectation update somewhere else.

### CODE REVIEW

**Comment by mijovic** [comment]
I have restarted timed out tests

File: test/libsolidity/util/TestFunctionCall.cpp [hunk 1]
```diff
@@ -300,7 +300,11 @@ string TestFunctionCall::formatRawParameters(
 		{
 			if (param.format.newline)
 				os << endl << _linePrefix << "// ";
-			os << param.rawString;
+			for (auto const c: param.rawString)
+				if (c >= ' ')
+					os << c;
+				else
+					os << "\\x" << solidity::util::toHex(static_cast<uint8_t>(c));
```
Comment (mijovic) [inline test/libsolidity/util/TestFunctionCall.cpp]: Maybe something like:
```suggestion
			for (auto const c: param.rawString)
				os << (c >= ' ' ? string(1, c) : "\\x" + solidity::util::toHex(static_cast<uint8_t>(c)));
```

**Review by chriseth — APPROVED** [review]

**Review by mijovic — APPROVED** [review]
