### PR TITLE
Print a warning about function parameter names being used instead of values in SMTChecker

### LINKED ISSUE #14751: Invalid string values in smtchecker counterexample for a failed assertion
In `smtCheckerTests/types/string_1.sol` the counterexample is invalid.

```
contract C
{
	function f(string memory s1, string memory s2) public pure {
		assert(bytes(s1).length == bytes(s2).length);
	}
}
```
running the smtchecker produces the following warning:
```
Warning 6328: (77-121): CHC: Assertion violation happens here.\nCounterexample:\n\n\nTransaction trace:\nC.constructor()\nC.f(s1, s2)
```

There are no literal string values in the counterexample.
Even when `s1` and `s2` were interpreted as literals, the values do not fail the assertion.

### PR DESCRIPTION
**Pull request by pgebal**
Closes https://github.com/ethereum/solidity/issues/14751

### CODE REVIEW

File: test/libsolidity/SMTCheckerTest.h [hunk 1]
```diff
@@ -62,7 +62,8 @@ class SMTCheckerTest: public SyntaxTest
 
 	ModelCheckerSettings m_modelCheckerSettings;
 
-	bool m_ignoreCex = false;
+	// we ignore counterexamples by default
+	bool m_ignoreCex = true;
```
Comment (blishko) [inline test/libsolidity/SMTCheckerTest.h]: Do we actually need to change this?
It does not really belong to this PR, no?

File: Changelog.md [hunk 2]
```diff
@@ -23,6 +23,7 @@ Language Features:
 Compiler Features:
  * EVM: Support for the EVM Version "Cancun".
  * SMTChecker: Support `bytes.concat` except when string literals are passed as arguments.
+ * SMTChecker: Print a message that function parameter name was used instead of a concrete value when counterexample generated by a solver is too long.
```
Comment (blishko) [inline Changelog.md]:
```suggestion
 * SMTChecker: Print a message that function parameter name was used instead of a concrete value in a counterexample when the concrete value found by the solver is too long to print.
```

**Review by blishko — COMMENTED** [review]
Looks good!
Left a suggestion.

File: test/libsolidity/SMTCheckerTest.h (hunk 1 above)
Comment (pgebal) [reply test/libsolidity/SMTCheckerTest.h]: I think so. I fell it's misleading that we set it here to false and then use `yes` value as default when reading the settings.

Comment (blishko) [reply test/libsolidity/SMTCheckerTest.h]: I don't quite agree, because the constructor decides what is the default.
I would at least not put the comment here, because what if we decide to switch the default in the constructor, then this again becomes outdated.

Also, we have similar situation for other settings. For example `showUnsupported` in `ModelCheckerSettings` has initial value `false`, but in the constructor of `SMTCheckerTest` the default is `yes` which sets the field to `true`.

I agree that it is somewhat misleading. Not sure what the best solution is, but I don't think that the initialization at the declaration should be marked as the source of the truth, when we actually decide the default value in the body of the constructor.

Comment (pgebal) [reply test/libsolidity/SMTCheckerTest.h]: ok, I'll leave it, like it was before.

**Review by blishko — APPROVED** [review]
LGTM!
