### PR TITLE
Fixes wrong source location when reporting pragma solidity version conflicts

### LINKED ISSUE #6329: Error is reported on wrong line
On input
```
pragma solidity ^0.4.21;
```
The compiler reports:
```
> solc /tmp/x.sol 
/tmp/x.sol:2:1: Error: Source file requires different compiler version (current compiler is 0.5.7+commit.937c5f5b.mod.Linux.g++ - note that nightly builds are considered to be strictly less than the released version

^
```

### PR DESCRIPTION
**Pull request by christianparpart**
Fixes #6329.

Which now looks like this:
image

### CODE REVIEW

**Comment by erak** [comment]
This might need a Changelog entry :)

File: libsolidity/parsing/Parser.cpp [hunk 1]
```diff
@@ -108,14 +110,14 @@ ASTPointer<SourceUnit> Parser::parse(shared_ptr<Scanner> const& _scanner)
...
+void Parser::parsePragmaVersion(SourceLocation const& _location, vector<Token> const& _tokens, vector<string> const& _literals)
 {
-	SemVerMatchExpressionParser parser(tokens, literals);
+	SemVerMatchExpressionParser parser(_tokens, _literals);
 	auto matchExpression = parser.parse();
 	static SemVerVersion const currentVersion{string(VersionString)};
 	// FIXME: only match for major version incompatibility
 	if (!matchExpression.matches(currentVersion))
-		fatalParserError(
+		m_errorReporter.fatalParserError(_location,
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: newline

File: libsolidity/parsing/Parser.cpp [hunk 2]
```diff
@@ -65,6 +65,8 @@ class Parser::ASTNodeFactory
 		return make_shared<NodeType>(m_location, std::forward<Args>(_args)...);
 	}
 
+	SourceLocation const& location() const noexcept { return m_location; }
```
Comment (erak) [inline libsolidity/parsing/Parser.cpp:68]: Oh, did we agree on using `noexcept` when applicable?

Comment (christianparpart) [reply libsolidity/parsing/Parser.cpp:68]: I agreed with myself to be in line with the CppCoreGuidelines. Please Overwrite my configuration in case of violation 🔢

Comment (erak) [reply libsolidity/parsing/Parser.cpp:68]: Don't get me wrong. I agree with this modernization :)

**Review by erak — COMMENTED** [review]
I'd still vote for adding a Changelog entry to the list of bugfixes.

**Review by erak — APPROVED** [review]
