### PR TITLE
Avoid output messages size blow-up using huge bignums literals

### LINKED ISSUE #3328: SOL-009 Output messages size blow-up using huge bignums literals
**Description**

The Solidity compiler accepts numeric literals of arbitrary precision. When a literal is assigned to a variable of shorter size, an error will be written to stderr containing the expanded representation of the literal.

For example, the following code, generates an error output of approximate size 600 KBytes:

```
contract BIGNUMTEST {
function bignum() {
uint c;
c=1E600000;
}
}
```

The huge error line is:
filename.sol:4:5: Error: Type int_const 100000000000000000…..…..000000000
is not implicitly convertible to expected type uint256.

Since computing the 1E600000 integer takes approximately 30 seconds, the same output blow-up can be obtained by forcing multiple conversion errors.

The following example generates a 6 Mbyte output in only 6 seconds:

contract BIGNUMTEST {
function bignum() {
uint c;
c=1E10000;c=1E10000;c=1E10000;
c=1E10000;c=1E10000;c=1E10000;
c=1E10000;c=1E10000;c=1E10000;
...last line repeated 200 times …
}
}

**Recommendations**

● Shorten literal constants by replacing intermediate digits by “...” when printing errors to
stderr (e.g. 1000...000)
● Reduce the number of warnings/errors written to stderr

### PR DESCRIPTION
**Pull request by federicobond**
Fixes #3328 

Example output:
```
test.sol:4:5: Error: Operator + not compatible with types int_const 1000...(93 digits omitted)...0000 and literal_string "foo"
    1e100 + "foo";
    ^-----------^
```

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -949,11 +949,22 @@ bool RationalNumberType::operator==(Type const& _other) const
...
+	string str = num.str();
+	if (str.size() > 32)
+	{
+		int omitted = str.size() - 8;
+		return str.substr(0, 4) + "...(" + to_string(omitted) + " digits omitted)..." + str.substr(str.size() - 4, 4);
+	}
+	return str;
+}
+
 string RationalNumberType::toString(bool) const
```
Comment (axic) [inline libsolidity/ast/Types.cpp:963]: Are you sure `toString` is not used anywhere else but error messages? I think it may be used in `ASTJsonConverter`.

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -949,11 +949,22 @@ bool RationalNumberType::operator==(Type const& _other) const
 	return m_value == other.m_value;
 }
 
+string numberToString(dev::bigint num)
```
Comment (axic) [inline libsolidity/ast/Types.cpp]: This should be in the anonymous namespace or be a static member of the class.

Comment (axic) [reply libsolidity/ast/Types.cpp]: I also think the `dev` namespace is imported.

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -949,11 +949,22 @@ bool RationalNumberType::operator==(Type const& _other) const
...
+{
+	string str = num.str();
+	if (str.size() > 32)
```
Comment (axic) [inline libsolidity/ast/Types.cpp]: Should we support 256 bit values unaltered? That would be 78 (?) digits.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: The name of this should also reflect that it is truncating, perhaps a parameter for the max length would be useful?

Comment (federicobond) [reply libsolidity/ast/Types.cpp]: Yes, that's better, what is the convention for these utility functions?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (federicobond) [reply libsolidity/ast/Types.cpp:963]: You are right, I missed those usages. Are these type strings documented somewhere? Perhaps we can take a moment and describe them in more detail.

File: libsolidity/ast/Types.cpp (hunk 3 above)
Comment (federicobond) [reply libsolidity/ast/Types.cpp]: Unless you are copy-pasting them, you are probably only verifying the first/last digits. I think long numbers just add noise to the error message.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (federicobond) [reply libsolidity/ast/Types.cpp]: ping @axic

Comment (axic) [reply libsolidity/ast/Types.cpp]: There's no strict convention. For the moment I think you could keep this as a private static method of `RationalNumberType` just name it something like `bingintTruncatedToString` (or if you find something better).

File: libsolidity/ast/Types.cpp (hunk 3 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: I think I'm in favour on your argument now.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Please change this to `dev::bigint const&`.

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp:963]: the bool parameter indicates whether it is for human or machine consumption, I think.

Comment (chriseth) [reply libsolidity/ast/Types.cpp:963]: For some use-cases it is important that if two types compare unequal, the `toString` output has to be different.

Comment (federicobond) [reply libsolidity/ast/Types.cpp:963]: bool parameters are THE worst :grimacing:

**Comment by axic** [comment]
@chriseth should be ready, please review again

**Comment by federicobond** [comment]
@axic I have the bool parameter changes ready. Let me build and push again.

**Comment by axic** [comment]
@federicobond please fetch first as I've pushed some updates.

**Comment by axic** [comment]
Ok those changes were lost, will recreate it :)

**Comment by federicobond** [comment]
Oops, sorry! Missed those changes. I will happily rebase if you push them again.

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/ast/Types.cpp:963]: Based on this `true` stands for machine use?

```
        virtual std::string toString(bool _short) const = 0;
        std::string toString() const { return toString(false); }
        /// @returns the canonical name of this type for use in library function signatures.
        virtual std::string canonicalName() const { return toString(true); }
```

**Comment by axic** [comment]
Pushed some of the changes again.

**Comment by axic** [comment]
Test failure:
```
C:/projects/solidity/test/libsolidity/SolidityNameAndTypeResolution.cpp(1755): error: in "SolidityNameAndTypeResolution/overflow_caused_by_ether_units": Unexpected error: TypeError: Type int_const 115792089237316195423570985008687907853269984665640564039458000000000000000000 is not implicitly convertible to expected type uint256.
```

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp:963]: The documentation is in the base class.

**Comment by chriseth** [comment]
OK, I'm sorry  - `toString()` is used only used for error messages. Because of that, I will just update the expectation.

**Comment by chriseth** [comment]
Sorry, meant to say: Because of that, we can always shorten.

**Comment by chriseth** [comment]
I took the liberty to insert spaces around the `/` for readability.

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/ast/Types.cpp:963]: This is from the base class.

**Review by axic — APPROVED** [review]
