### PR TITLE
Fix ICE related to mapping types in abstract contract constructor

### LINKED ISSUE #11356: ICE: Throw in function virtual bool solidity::frontend::TypeChecker::visit(const solidity::frontend::VariableDeclaration &)
## Environment

- Compiler version: Version: 0.8.5-develop.2021.5.7+commit.518629a8.Linux.clang
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system: Linux 5.4.0-66-generic x86_64 GNU/Linux

#### Test program: small.sol
```solidity
abstract contract A {
constructor ( mapping ( uint => uint ) [ ] storage ) { }
}
```
#### Compiler Command
```bash
solc-trunk-asan_ubsan  small.sol
```
#### Output
```
Internal compiler error during compilation:
/solidity/libsolidity/analysis/TypeChecker.cpp(595): Throw in function virtual bool solidity::frontend::TypeChecker::visit(const solidity::frontend::VariableDeclaration &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

### PR DESCRIPTION
**Pull request by hrkrshnn**
Closes https://github.com/ethereum/solidity/issues/11356

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -588,7 +588,18 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
...
 			bool isLibraryStorageParameter = (_variable.isLibraryFunctionParameter() && referenceType->location() == DataLocation::Storage);
-			bool callDataCheckRequired = ((_variable.isConstructorParameter() || _variable.isPublicCallableParameter()) && !isLibraryStorageParameter);
+			auto isVariableInAbstractContract = [&]()
+			{
+				if (ContractDefinition const* contract = _variable.annotation().contract)
+					return contract->abstract();
+				return false;
+			};
+			// We skip the calldata check for abstract contract constructors.
+			bool isAbstractConstructorParam = _variable.isConstructorParameter() && isVariableInAbstractContract();
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
			bool isAbstractConstructorParam = _variable.isConstructorParameter() && m_currentContract && m_currentContract->abstract();
```

Comment (hrkrshnn) [reply libsolidity/analysis/TypeChecker.cpp]: Fixed.

**Review by chriseth — APPROVED** [review]
