### PR TITLE
[BREAKING] permanently set errorTypeForLoose from Warning to SyntaxError

### LINKED ISSUE #2916: Undescriptive exception is thrown when stack underflows during --assemble
I was writting standalone assembly and had a bug in my code, with a minimal reproduction being:
```
{
    0x1
    jumpi my_tag
    my_tag:
    stop
}
```
which should be
```
{
    0x1
    my_tag
    jumpi
    my_tag:
    stop
}

```
instead.
Solc then threw out an error without any explanation:
```
Pretty printed source:
{
    0x1
    jumpi
    my_tag
    my_tag:
    stop
}
Exception while assembling: D:\Libraries\Documents\Praca\solidity\libevmasm\Assembly.cpp(323): Throw in function const class dev::eth::AssemblyItem &__cdecl dev::eth::Assembly::append(const class dev::eth::AssemblyItem &)
Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::eth::AssemblyException>
std::exception::what:
[struct dev::tag_comment * __ptr64] =
```

Assembly.cpp calculates the stack depth constantly, and on underflow throws an undescriptive exception   in [Assembly.cpp:323](https://github.com/ethereum/solidity/blob/develop/libevmasm/Assembly.cpp#L323)

I would expect the error to be ignored (I'm doing raw jumps, safety is up-to me), or a warning issued.

While we're here I believe that stack depth calculations shouldn't be enforced and be more-or-less optional (so you can use `:=` variables). That's because if I'm writing raw manual assembly, the flow and stack-depth might really not follow the expectations of blocks and empty stacks after each one and I might be jumping around the control flow.

Additional info:
Solidity commit hash which I used:
```a0d171722a211720773aae0ded8a80991d44ba9d```

### LINKED ISSUE #3936: Labels in assembly show two (overlapping) warnings
```
multi-errors.sol:4:7: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
      jump(end)
      ^-------^
multi-errors.sol:6:7: Warning: The use of labels is deprecated. Please use "if", "switch", "for" or function calls instead.
      end:
      ^-^
multi-errors.sol:6:7: Warning: Jump instructions and labels are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch", "if" or "for" statements instead.
      end:
      ^-^
```

### LINKED ISSUE #3937: Jumps are considered modifying the state according to ViewPureChecker
```
RLP.sol:389:18: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
                 jumpi(end, eq(i, words))
                 ^----------------------^
RLP.sol:395:18: Warning: Function declared as view, but this expression (potentially) modifies the state and thus requires non-payable (the default) or payable.
                 jump(tag_loop)
                 ^------------^
```

I am not sure whether this is good or bad. It is true it could jump to locations in the contract which have non-pure instructions, but that is really hard to control.

### LINKED ISSUE #3938: Improve suggestin in warning about loose assembly in inline assembly
```
commut.solc:4:7: Warning: Top-level expressions are not supposed to return values (this expression returns 1 value). Use ``pop()`` or assign them.
      1
      ^
commut.solc:5:7: Warning: Top-level expressions are not supposed to return values (this expression returns 1 value). Use ``pop()`` or assign them.
      2
      ^
commut.solc:6:7: Warning: The use of non-functional instructions is deprecated. Please use functional notation instead.
      swap1
      ^---^
commut.solc:7:7: Warning: The use of non-functional instructions is deprecated. Please use functional notation instead.
      mul
      ^-^
commut.solc:8:7: Warning: The use of stack assignment is deprecated. Please use assignment in functional notation instead.
      =: out
      ^----^
```

I don't think we want to support loose assembly anyway, so the step forward here is to extend the first warning to mention "consider using functional notation".

### PR DESCRIPTION
**Pull request by christianparpart**
Closes #2916. Closes #3936. Closes #3937. Closes #3938.

Depends on #4545.

It seems that we do not have a test for it, at least there was nothing
that needed adaption.

### TODO:

- [x] EndToEndTests adaptions
- [x] documentation changes
- [x] adapting compilation tests

### CODE REVIEW

**Comment by chriseth** [comment]
Please add a test.

**Comment by christianparpart** [comment]
@chriseth so it turns out, that our v0.5.0 checklist (#4401) contains the errorTypeForLoose twice, and the first one is just a no-op, as `ReferenceResolver::visit(InlineAssembly const&)`'s invokation of `AsmAnalyzer` is not reporting anything (but only used to resolve references).

At the later stage (in TypeChecker), the change actually takes affect, and for that we have tests of course already.

I've adapted the tests accordingly.

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 1]
```diff
@@ -277,7 +277,7 @@ bool ReferencesResolver::visit(InlineAssembly const& _inlineAssembly)
 	// Will be re-generated later with correct information
 	// We use the latest EVM version because we will re-run it anyway.
 	assembly::AsmAnalysisInfo analysisInfo;
-	boost::optional<Error::Type> errorTypeForLoose = m_experimental050Mode ? Error::Type::SyntaxError : Error::Type::Warning;
+	boost::optional<Error::Type> errorTypeForLoose = Error::Type::SyntaxError;
```
Comment (axic) [inline libsolidity/analysis/ReferencesResolver.cpp:280]: Either keep this here and in `TypeChecker` or merge into the `AsmAnalyzer` line in both cases. While first I was going to suggest not to keep the variable, at least it helps documenting the code.

Well, actually, as a second PR the parameter to `AsmAnalyzer` could be removed entirely.

Comment (chriseth) [reply libsolidity/analysis/ReferencesResolver.cpp:280]: @axic I thought we still might want to keep loose style for the `solc --assemble` mode, but we can also fully remove it.

Comment (christianparpart) [reply libsolidity/analysis/ReferencesResolver.cpp:280]: @axic I'd even go that far in removing that ctor param alltogether (no need for a seperate PR, IMHO), what do you think? /cc @chriseth

Comment (axic) [reply libsolidity/analysis/ReferencesResolver.cpp:280]: > @axic I thought we still might want to keep loose style for the solc --assemble mode, but we can also fully remove it.

Oh right, for that reason I would not change it too much in this PR then. If we decode to remove that, should be in a separate PR.

File: docs/assembly.rst [hunk 2]
```diff
@@ -416,57 +414,7 @@ changes during the call, and thus references to local variables will be wrong.
...
-            // from top to bottom.
-            // Accessing the stack variable x here will lead to errors.
-            x := 9
-            jump(three)
-        two:
-            7 // push something onto the stack
-            jump(one)
-        three:
-    }
+Support for labels have been removed.  Please use functions, loops, if or switch statements instead.
```
Comment (axic) [inline docs/assembly.rst]: Perhaps state that it was removed with 0.5.0?

File: test/compilationTests/milestonetracker/RLP.sol [hunk 3]
```diff
@@ -381,19 +381,16 @@ library RLP {
      // we can write entire words, and just overwrite any excess.
      assembly {
          {
-                 let i := 0 // Start at arr + 0x20
                  let words := div(add(btsLen, 31), 32)
                  let rOffset := btsPtr
                  let wOffset := add(tgt, 0x20)
-             tag_loop:
-                 jumpi(end, eq(i, words))
+
```
Comment (chriseth) [inline test/compilationTests/milestonetracker/RLP.sol:387]: Could you try to merge that into https://github.com/androlo/standard-contracts/blob/master/contracts/src/codec/RLP.sol ?

Comment (christianparpart) [reply test/compilationTests/milestonetracker/RLP.sol:387]: shure, I'd love to.

Comment (christianparpart) [reply test/compilationTests/milestonetracker/RLP.sol:387]: for reference: https://github.com/androlo/standard-contracts/pull/8

File: test/compilationTests/stringutils/strings.sol [hunk 4]
```diff
@@ -506,15 +519,34 @@ library strings {
...
-                    jumpi(ret, eq(and(mload(ptr), mask), needledata))
-                    ptr := sub(ptr, 1)
-                    jumpi(loop, gt(add(ptr, 1), selfptr))
-                    ptr := selfptr
-                    jump(exit)
-                    ret:
-                    ptr := add(ptr, needlelen)
-                    exit:
+
+                    if iszero(eq(and(mload(ptr), mask), needledata)) {
```
Comment (ekpyron) [inline test/compilationTests/stringutils/strings.sol]: For the record: I think we need to have a close look at this one - I'm not sure whether the current code does what it should.

Comment (christianparpart) [reply test/compilationTests/stringutils/strings.sol]: yeah, I am aware of that and will look into this too. I'd highly appreciate others looking into it, too. :-)

File: Changelog.md [hunk 5]
```diff
@@ -49,6 +49,7 @@ Breaking Changes:
  * Type Checker: Fallback function must be external. This was already the case in the experimental 0.5.0 mode.
  * Type Checker: Interface functions must be declared external. This was already the case in the experimental 0.5.0 mode.
  * Type Checker: Address members are not included in contract types anymore. An explicit conversion is now required before invoking an ``address`` member from a contract.
+ * Type Checker: Inline-assembly's loose error type raised from ``Warning`` to ``SyntaxError``.
```
Comment (axic) [inline Changelog.md]: I think this is not clear for users to understand. Something like `Disallow "loose assembly" syntax entirely. This means that jump, jump labels and non-functional instructions cannot be used anymore.`

File: docs/assembly.rst [hunk 6]
```diff
@@ -416,57 +414,7 @@ changes during the call, and thus references to local variables will be wrong.
...
-            // from top to bottom.
-            // Accessing the stack variable x here will lead to errors.
-            x := 9
-            jump(three)
-        two:
-            7 // push something onto the stack
-            jump(one)
-        three:
-    }
+Support for labels has been removed. Please use functions, loops, if or switch statements instead.
```
Comment (axic) [inline docs/assembly.rst]: Should state it was removed in 0.5.0.

**Comment by axic** [comment]
@christianparpart can you please split the peephole optimiser changes into a separate PR?

**Comment by axic** [comment]
Rebased.

File: test/libsolidity/syntaxTests/viewPureChecker/assembly_jump_view_fail.sol [hunk 7]
```diff
@@ -4,5 +4,4 @@ contract C {
     }
```
Comment (axic) [inline test/libsolidity/syntaxTests/viewPureChecker/assembly_jump_view_fail.sol]: I think these two jump tests in `viewPureChecker` are not needed anymore.

File: test/libsolidity/SolidityNameAndTypeResolution.cpp [hunk 8]
```diff
@@ -390,11 +390,11 @@ BOOST_AUTO_TEST_CASE(unsatisfied_version)
...
 {
 	char const* text = R"(
-		contract c { function f() public { uint returndatasize; assembly { returndatasize }}}
+		contract C { function f() public pure { uint returndatasize; assembly { returndatasize() }}}
 	)";
 	vector<pair<Error::Type, std::string>> expectations(vector<pair<Error::Type, std::string>>{
 		{Error::Type::Warning, "Variable is shadowed in inline assembly by an instruction of the same name"},
-		{Error::Type::Warning, "The use of non-functional instructions is deprecated."},
+		{Error::Type::SyntaxError, "Top-level expressions are not supposed to return values"},
 		{Error::Type::DeclarationError, "Unbalanced stack"}
```
Comment (axic) [inline test/libsolidity/SolidityNameAndTypeResolution.cpp]: Probably `pop(returndatasize())` would be better to avoid these two errors.

File: test/libsolidity/SolidityNameAndTypeResolution.cpp [hunk 9]
```diff
@@ -413,7 +413,7 @@ BOOST_AUTO_TEST_CASE(create2_as_variable)
 		{Error::Type::Warning, "Variable is shadowed in inline assembly by an instruction of the same name"},
 		{Error::Type::Warning, "The \"create2\" instruction is not supported by the VM version"},
 		{Error::Type::DeclarationError, "Unbalanced stack"},
-		{Error::Type::Warning, "not supposed to return values"}
+		{Error::Type::SyntaxError, "Top-level expressions are not supposed to return values (this expression returns 1 value). Use ``pop()`` or assign them."}
```
Comment (axic) [inline test/libsolidity/SolidityNameAndTypeResolution.cpp]: Same here with `pop(create2(...))`.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 10]
```diff
@@ -11255,21 +11209,6 @@ BOOST_AUTO_TEST_CASE(recursive_structs)
 	ABI_CHECK(callContractFunction("f()"), encodeArgs(u256(1)));
 }
 
-BOOST_AUTO_TEST_CASE(invalid_instruction)
-{
-	char const* sourceCode = R"(
-		contract C {
-			function f() public {
-				assembly {
-					invalid
```
Comment (axic) [inline test/libsolidity/SolidityEndToEndTest.cpp]: This can be changed into `invalid()` and kept.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 11]
```diff
@@ -8910,52 +8910,6 @@ BOOST_AUTO_TEST_CASE(inline_assembly_storage_access_via_pointer)
...
-{
-	char const* sourceCode = R"(
-		contract C {
-			uint public x;
-			function g(uint y) public { x = 2 * y; assembly { stop } }
-			function f(uint _x) public {
-				assembly {
-					_x
-					jump(g)
-					pop
```
Comment (axic) [inline test/libsolidity/SolidityEndToEndTest.cpp:8949]: This should be added to the pure assembly tests (`test/InlineAssembly`).

File: test/libsolidity/SolidityNameAndTypeResolution.cpp (hunk 8 above)
Comment (christianparpart) [reply test/libsolidity/SolidityNameAndTypeResolution.cpp]: I agree, however, since the error was there before already I didn't feel quite sure of whether to `pop` it or not. Thanks for clarifying.

File: test/libsolidity/SolidityEndToEndTest.cpp (hunk 11 above)
Comment (christianparpart) [reply test/libsolidity/SolidityEndToEndTest.cpp:8949]: @axic I removed those two tests because it is not possible anymore to do jumps or function calls to an outside function. What could I move to `test/InlineAssembly`, or, what exactly should I test for?

Thanks,
Christian.

Comment (axic) [reply test/libsolidity/SolidityEndToEndTest.cpp:8949]: It is not possible within inline assembly, but still possible with the pure assembler, IIRC.

Comment (axic) [reply test/libsolidity/SolidityEndToEndTest.cpp:8949]: Sorry you are right, didn't notice for a second that `f` is a Solidity function.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 12]
```diff
@@ -11255,21 +11224,6 @@ BOOST_AUTO_TEST_CASE(recursive_structs)
 	ABI_CHECK(callContractFunction("f()"), encodeArgs(u256(1)));
 }
 
-BOOST_AUTO_TEST_CASE(invalid_instruction)
```
Comment (axic) [inline test/libsolidity/SolidityEndToEndTest.cpp]: Can you keep this at the original location in the file?

**Review by axic — APPROVED** [review]
