### PR TITLE
Return TypeError is fixed point encoding is attempted.

### LINKED ISSUE #4715: Crash when converting fixed point type using ABIEncoderV2
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
Compiler crashes on the assembly code generation when using `pragma experimental ABIEncoderv2` to encode a fixed point type.

## Error in file
Not yet implemented - FixedPointType.
`libsolidity/codegen/ABIFunctions.cpp(291)`

## Displayed message
Unimplemented feature.
`Throw in function dev::solidity::ABIFunctions::conversionFunction(const dev::solidity::Type&, const dev::solidity::Type&)::<lambda()>`

## Example code

```solidity
pragma solidity ^0.4.24;
pragma experimental ABIEncoderV2;
contract C {
   function f1() public pure returns (bytes) {
       return abi.encode(0.1, 1);
   }
}
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #4715.

This PR returns a `TypeError` if fixed point encoding is attempted (with or without `ABIEncoderV2`), by checking if the argument type is rational and fractional.
Another option would be to make `Type::fullEncodingType` virtual and return `nullptr` in the `RationalNumberType` implementation.

### CODE REVIEW

**Comment by axic** [comment]
Can you add tests?

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1482,7 +1482,16 @@ void TypeChecker::typeCheckABIEncodeFunctions(
 
 		if (argType->category() == Type::Category::RationalNumber)
 		{
-			if (!argType->mobileType())
+			auto const& rationalType = dynamic_cast<RationalNumberType const&>(*argType);
+			if (rationalType.isFractional())
+			{
+				m_errorReporter.typeError(
+					arguments[i]->location(),
+					"Fixed point numbers cannot yet be encoded."
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Perhaps just mention "fractional"? The fact that the number is implicitly converted to a fixed point number might not be obivous to the user.

Comment (leonardoalt) [reply libsolidity/analysis/TypeChecker.cpp]: Done

File: test/libsolidity/syntaxTests/types/encoding_packed_fractional.sol [hunk 2]
```diff
@@ -0,0 +1,8 @@
+contract C {
+   function f1() public pure returns (bytes memory) {
+       return abi.encodePacked(0.1, 1);
+   }
+}
+// ----
+// TypeError: (98-101): Fractional numbers cannot yet be encoded.
+// TypeError: (103-104): Cannot perform packed encoding for a literal. Please convert it to an explicit type first.
```
Comment (axic) [inline test/libsolidity/syntaxTests/types/encoding_packed_fractional.sol:8]: Hm, this kind of worries me that we have such different codepaths. Also this message is a bit confusing for the above case.

Comment (chriseth) [reply test/libsolidity/syntaxTests/types/encoding_packed_fractional.sol:8]: Not sure what you mean. This message is about the `1`, not the `0.1`.

Comment (leonardoalt) [reply test/libsolidity/syntaxTests/types/encoding_packed_fractional.sol:8]: Yep it's about the `1`.

Comment (axic) [reply test/libsolidity/syntaxTests/types/encoding_packed_fractional.sol:8]: Ah ok, it is not an issue if the source location is nicely formatted. Just in the tests :)

**Review by chriseth — APPROVED** [review]
