### PR TITLE
Bug that ignored return tag when no other devdoc tags were present

### LINKED ISSUE #8905: Return annotation is missing from natspec
```
contract C {
  /// @notice Some function.
  /// @return ret Some value is returned.
  function f() public view returns (uint ret) {
  }
}
```

```
Developer Documentation
{
  "methods": {}
}

User Documentation
{
  "methods":
  {
    "f()":
    {
      "notice": "Some function."
    }
  }
}
```

However it does complain if I use `/// @return Some value` without the variable name, so the tag is processed.

### PR DESCRIPTION
**Pull request by hrkrshnn**
Closes https://github.com/ethereum/solidity/issues/8905

### CODE REVIEW

**Comment by axic** [comment]
Can you add a test case?

File: libsolidity/interface/Natspec.cpp [hunk 1]
```diff
@@ -99,16 +99,14 @@ Json::Value Natspec::devDocumentation(ContractDefinition const& _contractDef)
...
-			{
-				// add the function, only if we have any documentation to add
-				Json::Value jsonReturn = extractReturnParameterDocs(fun->annotation().docTags, *fun);
+			// add the function, only if we have any documentation to add
+			Json::Value jsonReturn = extractReturnParameterDocs(fun->annotation().docTags, *fun);
 
-				if (!jsonReturn.empty())
-					method["returns"] = jsonReturn;
+			if (!jsonReturn.empty())
+				method["returns"] = jsonReturn;
```
Comment (axic) [inline libsolidity/interface/Natspec.cpp:106]: So here, if `method` is empty, this line adds a new member.

And since either it was never empty or because of the return statement it is no longer empty, the next condition will be true.

Is that how the logic should go?

File: test/libsolidity/SolidityNatspecJSON.cpp [hunk 2]
```diff
@@ -355,6 +355,27 @@ BOOST_AUTO_TEST_CASE(dev_multiple_functions)
 	checkNatspec(sourceCode, "test", natspec, false);
 }
 
+BOOST_AUTO_TEST_CASE(dev_return_basic)
```
Comment (axic) [inline test/libsolidity/SolidityNatspecJSON.cpp]: Can you name this `dev_return_no_params`?

File: libsolidity/interface/Natspec.cpp (hunk 1 above)
Comment (hrkrshnn) [reply libsolidity/interface/Natspec.cpp:106]: `empty()` does the following "Return true if empty array, empty object, or null; otherwise, false."

In our case method is an empty object. We want the final `if(!method.empty())` so that we don't have a function signature member when no devdoc was specified. @axic

File: Changelog.md [hunk 3]
```diff
@@ -17,7 +17,7 @@ Bugfixes:
  * ABI: Skip ``private`` or ``internal`` constructors.
  * Type Checker: Disallow accessing ``runtimeCode`` for contract types that contain immutable state variables.
  * Fixed an "Assembly Exception in Bytecode" error where requested functions were generated twice.
-
+ * Natspec: fixed a bug that ignored ``@return`` tag when no other developer-documentation tags were present.
```
Comment (axic) [inline Changelog.md]: Nitpick: start with uppercase `F`.

**Review by axic — DISMISSED** [review]
Looks good apart the nitpick.

**Review by axic — APPROVED** [review]
