### PR TITLE
Fix ICE by avoiding copyForLocation() on ArraySliceType

### LINKED ISSUE #8265: ArraySliceType::copyForLocation assertion failure
## Description

This contract:
```solidity
contract C {
    function f( bytes calldata x,bool cond) external pure {
        bytes1 a = x[cond - 1 : 2]. a;
	if (0==1)
	    if (0<1)
		continue;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.h(797): Throw in function virtual std::unique_ptr<ReferenceType> solidity::frontend::ArraySliceType::copyForLocation(solidity::frontend::DataLocation, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled.

On master, using AFL fuzzing.  This was found with a new approach, that inlines a generic C-like source code mutation tool as a high-probability AFL havoc mutator.

## Environment

- Compiler version:  0.6.3-develop.2020.2.5+commit.f44188ab.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Save this contract in `shrink.sol` (or whatever filename)

```solidity
contract C {
    function f( bytes calldata x,bool cond) external pure {
        bytes1 a = x[cond - 1 : 2]. a;
	if (0==1)
	    if (0<1)
		continue;
    }
}
```

produces:

```
> solc shrink.sol 
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.h(797): Throw in function virtual std::unique_ptr<ReferenceType> solidity::frontend::ArraySliceType::copyForLocation(solidity::frontend::DataLocation, bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

### PR DESCRIPTION
**Pull request by Marenz**
fixes #8265

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2555,7 +2555,7 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 
 	if (possibleMembers.empty())
 	{
-		if (initialMemberCount == 0)
+		if (initialMemberCount == 0 && !dynamic_cast<ArraySliceType const*>(exprType))
```
Comment (Marenz) [inline libsolidity/analysis/TypeChecker.cpp:2558]: This solution is very specific to the issue that this fixes. I am open to suggestions to make this more generic to work with all types that would fail for a `withLocation()` call

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:2558]: It's not pretty, but this code will be gone with 0.7.0, so I would say it's fine.

**Review by chriseth — APPROVED** [review]
