### PR TITLE
formal: ignore pragmas during Why3 code generation

### LINKED ISSUE #1177: Why3: pragma not supported
```
Untitled:1:1: Error: Code not supported for formal verification.
pragma solidity ^0.4.0;
^---------------------^
```

### PR DESCRIPTION
**Pull request by pirapira**
Fixes #1177

### CODE REVIEW

**Comment by pirapira** [comment]
The `appveyor/branch` failure seems to be a mining timeout.

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
Can you add a test for this so it is not forgotten? Or better leave it to #1180?

File: libsolidity/formal/Why3Translator.cpp [hunk 1]
```diff
@@ -757,6 +757,11 @@ bool Why3Translator::visit(Literal const& _literal)
 	return false;
 }
 
+bool Why3Translator::visit(PragmaDirective const&)
+{
+	return false;
```
Comment (chriseth) [inline libsolidity/formal/Why3Translator.cpp:771]: Since we might be adding new pragmas in the future which could change the semantics of the language, please only ignore the "version" pragma.

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/formal/Why3Translator.cpp (hunk 1 above)
Comment (pirapira) [reply libsolidity/formal/Why3Translator.cpp:771]: I changed the code to use the SemVerParser to detect a version.  However, the parse accepts too many strings.  Currently most malformed pragmas are parsed as version pragmas; see #1192.

Comment (pirapira) [reply libsolidity/formal/Why3Translator.cpp:771]: @chriseth I have a question.  In the future, can there be a pragma that starts with `pragma solidity` but is not a version pragma?  Or, can I assume that whenever a pragma starts with `pragma solidity` it is a version pragma?

Comment (chriseth) [reply libsolidity/formal/Why3Translator.cpp:771]: The idea is that pragma statements are identified by their first identifier, so `pragma solidity` should always be a version pragma.

File: libsolidity/ast/AST.h [hunk 2]
```diff
@@ -195,6 +196,8 @@ class PragmaDirective: public ASTNode
 	std::vector<Token::Value> const& tokens() const { return m_tokens; }
 	std::vector<ASTString> const& literals() const { return m_literals; }
 
+	SemVerMatchExpression parseSemVer() const;
```
Comment (chriseth) [inline libsolidity/ast/AST.h]: It is quite dangerous to expose this as a public function because the internal use is preceded by some checks against the length of `tokens()`

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 3]
```diff
@@ -2884,10 +2884,12 @@ BOOST_AUTO_TEST_CASE(keccak256_multiple_arguments)
 	compileAndRun(sourceCode);
 
 	BOOST_CHECK(callContractFunction("foo(uint256,uint256,uint256)", 10, 12, 13) == encodeArgs(
-					dev::sha3(
-						toBigEndian(u256(10)) +
-						toBigEndian(u256(12)) +
-						toBigEndian(u256(13)))));
+		dev::keccak256(
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp:2887]: Please rebase.

File: libsolidity/formal/Why3Translator.cpp [hunk 4]
```diff
@@ -757,6 +757,15 @@ bool Why3Translator::visit(Literal const& _literal)
 	return false;
 }
 
+bool Why3Translator::visit(PragmaDirective const& _pragma)
+{
+	auto semVerMatch = _pragma.parseSemVer();
```
Comment (chriseth) [inline libsolidity/formal/Why3Translator.cpp]: As per the comments above, it is probably fine to check only the first identifier. You could add a helper function to `PragmaDirective` that returns the first identifier as a string.

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/formal/Why3Translator.cpp (hunk 4 above)
Comment (pirapira) [reply libsolidity/formal/Why3Translator.cpp]: I chose a primitive way.

File: test/libsolidity/SolidityEndToEndTest.cpp (hunk 3 above)
Comment (pirapira) [reply test/libsolidity/SolidityEndToEndTest.cpp:2887]: Done.

File: libsolidity/formal/Why3Translator.cpp (hunk 1 above)
Comment (pirapira) [reply libsolidity/formal/Why3Translator.cpp:771]: Thank you.

File: libsolidity/ast/AST.h (hunk 2 above)
Comment (pirapira) [reply libsolidity/ast/AST.h]: I removed this function.

**Comment by pirapira** [comment]
@axic adding the test requires another separate "figuring out" process.

**Review by chriseth — APPROVED** [review]
