### PR TITLE
Guard encoding crashes with assertions.

### LINKED ISSUE #332: sha() crashes on structs
```
contract test {

    struct TestStruct {
        uint a;
    }

    function test() {
        TestStruct memory testing = TestStruct({a: 1});
        sha3(testing);
    }
}
```

### LINKED ISSUE #978: sha3() crashes on tuples
```
contract Test {
    function tuple () returns (bool one, bool two) {
    }

    function crash () {
        sha3(tuple());
    }
}
```

```
$ solc/solc sha.sol
Segmentation fault: 11
```

```
* thread #1: tid = 0x1eade8e, 0x00000001003460a1 libsolidity.dylib`dev::solidity::CompilerUtils::encodeToMemory(std::__1::vector<std::__1::shared_ptr<dev::solidity::Type const>, std::__1::allocator<std::__1::shared_ptr<dev::solidity::Type const> > > const&, std::__1::vector<std::__1::shared_ptr<dev::solidity::Type const>, std::__1::allocator<std::__1::shared_ptr<dev::solidity::Type const> > > const&, bool, bool, bool) + 1089, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001003460a1 libsolidity.dylib`dev::solidity::CompilerUtils::encodeToMemory(std::__1::vector<std::__1::shared_ptr<dev::solidity::Type const>, std::__1::allocator<std::__1::shared_ptr<dev::solidity::Type const> > > const&, std::__1::vector<std::__1::shared_ptr<dev::solidity::Type const>, std::__1::allocator<std::__1::shared_ptr<dev::solidity::Type const> > > const&, bool, bool, bool) + 1089
libsolidity.dylib`dev::solidity::CompilerUtils::encodeToMemory:
->  0x1003460a1 <+1089>: movq   (%rax), %rcx
    0x1003460a4 <+1092>: movq   0xb0(%rcx), %rcx
    0x1003460ab <+1099>: leaq   -0x110(%rbp), %rdi
    0x1003460b2 <+1106>: movq   %rax, %rsi
```

### LINKED ISSUE #981: sha3() crashes on invalid symbols
```
contract A {
    function a() {
        sha3(a);
    }
}
```

or 

```
contract A {
    function a() {
        sha3(A);
    }
}
```

Will result in a crash similar to #978 and #332

### PR DESCRIPTION
**Pull request by chriseth**
This only fixes the crash for now, implementing the missing functionality is https://github.com/ethereum/solidity/issues/980

Fixes https://github.com/ethereum/solidity/issues/981
Fixes https://github.com/ethereum/solidity/issues/332
Fixes https://github.com/ethereum/solidity/issues/978

### CODE REVIEW

**Comment by pirapira** [comment]
@chriseth is this still "in progress" or ready to be merged.

**Comment by chriseth** [comment]
@pirapira  if it has "needs review" then it is "ready for review"

**Comment by pirapira** [comment]
Sorry @pipermerriam you and I share some prefix in the username.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 1]
```diff
@@ -160,7 +160,15 @@ void CompilerUtils::encodeToMemory(
 	TypePointers targetTypes = _targetTypes.empty() ? _givenTypes : _targetTypes;
 	solAssert(targetTypes.size() == _givenTypes.size(), "");
 	for (TypePointer& t: targetTypes)
+	{
+		solAssert(
+			t->mobileType() &&
+			t->mobileType()->interfaceType(_encodeAsLibraryTypes) &&
+			t->mobileType()->interfaceType(_encodeAsLibraryTypes)->encodingType(),
+			"Encoding type " + t->toString() + " not yet implemented."
```
Comment (pirapira) [inline libsolidity/codegen/CompilerUtils.cpp]: I suggest something like `"Encoding type [" + t->toString() + "] not yet implemented."` for better readability.

**Comment by pirapira** [comment]
4134834 looks good to merge (the suggestion to add "[  ]" can be deferred).  This fixes the three issues that are mentioned.

**Comment by pirapira** [comment]
Now I'm waiting for "in progress" to disappear before merging this, but if the commit hash changes, it's back to "need review".

**Comment by chriseth** [comment]
@pirapira "in progress" is a tag managed by waffle, it is automatically removed after the PR is merged.

**Comment by pirapira** [comment]
@chriseth I need to learn how the state transition works there...
