### PR TITLE
[SMTChecker] Fix CHC encoding

### LINKED ISSUE #9667: [SMTChecker] std::out_of_range exception because key not found in map
## Description

The following multi source test

```
==== Source: A.sol ====
contract A { function f() public {} }
==== Source:====
import "A.sol";
pragma experimental SMTChecker;
contract C is A {}
```

throws the said exception from here:

https://github.com/ethereum/solidity/blob/29b6c1724621e01924c55febab9a9c55807e9ad7/libsolidity/formal/CHC.cpp#L936

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ cp test.sol test/libsolidity/syntaxTests/multiSource/import_smt.sol
$ isoltest -t syntaxTests/multiSource/import_smt
syntaxTests/multiSource/import_smt.sol: Exception during test: map::at
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/9667

This PR fix some issues with the CHC encoding:
- The `genesis` predicate is actually not needed anymore since we started using nonlinear Horn clauses
- The `interface` and `nondet_interface` predicates for contracts were applied to the wrong contract
- The block counter wasn't reset
- The CHC solver wasn't reset

### CODE REVIEW

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -43,53 +43,31 @@ using namespace solidity::frontend;
 CHC::CHC(
 	smt::EncodingContext& _context,
 	ErrorReporter& _errorReporter,
-	map<util::h256, string> const& _smtlib2Responses,
-	ReadCallback::Callback const& _smtCallback,
+	[[maybe_unused]] map<util::h256, string> const& _smtlib2Responses,
+	[[maybe_unused]] ReadCallback::Callback const& _smtCallback,
 	[[maybe_unused]] smtutil::SMTSolverChoice _enabledSolvers
```
Comment (mijovic) [inline libsolidity/formal/CHC.cpp]: I think this one is always used now, so you can remove `[[maybe_unused]]`
```suggestion
	smtutil::SMTSolverChoice _enabledSolvers
```

Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: True

File: libsolidity/formal/CHC.cpp [hunk 2]
```diff
@@ -43,53 +43,31 @@ using namespace solidity::frontend;
...
-#endif
-	if (!usesZ3)
-	{
-		auto smtlib2Interface = dynamic_cast<smtutil::CHCSmtLib2Interface const*>(m_interface.get());
-		solAssert(smtlib2Interface, "");
-		m_context.setSolver(smtlib2Interface->smtlib2Interface());
-	}
-	m_context.clear();
-	m_context.setAssertionAccumulation(false);
-
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:84]: @mijovic This block was moved into `resetSources` so that the z3 interface gets reset.

File: libsolidity/formal/CHC.cpp [hunk 3]
```diff
@@ -915,10 +911,10 @@ void CHC::defineInterfacesAndSummaries(SourceUnit const& _source)
 							applyMap(function->parameters(), [this](auto _var) { return valueAtIndex(*_var, 1); }) +
 							applyMap(function->returnParameters(), [this](auto _var) { return valueAtIndex(*_var, 1); });
 
-						connectBlocks(nondetPre, nondetPost, (*m_summaries.at(base).at(function))(args));
+						connectBlocks(nondetPre, nondetPost, (*m_summaries.at(contract).at(function))(args));
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:914]: These replacements `base` -> `contract` were simply wrong.

File: libsolidity/formal/CHC.cpp [hunk 4]
```diff
@@ -1210,6 +1206,16 @@ void CHC::addVerificationTarget(
...
 {
+	solAssert(m_currentContract || m_currentFunction, "");
+	SourceUnit const* source = nullptr;
+	if (m_currentContract)
+		source = sourceUnitContaining(*m_currentContract);
+	else
+		source = sourceUnitContaining(*m_currentFunction);
+	solAssert(source, "");
+	if (!source->annotation().experimentalFeatures.count(ExperimentalFeature::SMTChecker))
+		return;
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:1217]: These were added so that verification targets created for imported code do not get checked if that SourceUnit doesn't have the pragma too.

File: libsolidity/formal/CHC.cpp [hunk 5]
```diff
@@ -1459,7 +1465,11 @@ optional<string> CHC::generateCounterexample(CHCSolverInterface::CexGraph const&
 		/// Recurse on the next interface node which represents the previous transaction
 		/// or stop.
 		if (interfaceId)
+		{
+			Predicate const* interfacePredicate = Predicate::predicate(_graph.nodes.at(*interfaceId).first);
+			solAssert(interfacePredicate && interfacePredicate->isInterface(), "");
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:1470]: Just an additional safety check

File: libsolidity/formal/CHC.cpp [hunk 6]
```diff
@@ -861,27 +863,23 @@ void CHC::defineInterfacesAndSummaries(SourceUnit const& _source)
...
 		if (auto const* contract = dynamic_cast<ContractDefinition const*>(node.get()))
-			for (auto const* base: contract->annotation().linearizedBaseContracts)
-			{
-				for (auto const* var: SMTEncoder::stateVariablesIncludingInheritedAndPrivate(*base))
-					if (!m_context.knownVariable(*var))
-						createVariable(*var);
+		{
+			string suffix = contract->name() + "_" + to_string(contract->id());
+			m_interfaces[contract] = createSymbolicBlock(interfaceSort(*contract), "interface_" + suffix);
+			m_nondetInterfaces[contract] = createSymbolicBlock(nondetInterfaceSort(*contract), "nondet_interface_" + suffix);
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:869]: These were moved out of the loop because they should be done for `contract` and not `base`, so they must be done only once.

File: libsolidity/formal/CHC.cpp [hunk 7]
```diff
@@ -900,13 +898,11 @@ void CHC::defineInterfacesAndSummaries(SourceUnit const& _source)
...
-						auto state2 = stateVariablesAtIndex(2, *base);
+						auto state1 = stateVariablesAtIndex(1, *contract);
+						auto state2 = stateVariablesAtIndex(2, *contract);
 
-						auto const* iface = m_nondetInterfaces.at(base);
-						auto state0 = stateVariablesAtIndex(0, *base);
-						auto nondetPre = (*iface)(state0 + state1);
-						auto nondetPost = (*iface)(state0 + state2);
+						auto nondetPre = iface(state0 + state1);
+						auto nondetPost = iface(state0 + state2);
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:905]: Code is the same, in this diff block, the first 2 lines were just moved outside the loop.

File: libsolidity/formal/CHC.cpp (hunk 3 above)
Comment (mijovic) [reply libsolidity/formal/CHC.cpp:914]: I was wondering about these

File: libsolidity/formal/CHC.cpp [hunk 8]
```diff
@@ -43,53 +43,31 @@ using namespace solidity::frontend;
...
-
 	resetSourceAnalysis();
 
-	m_genesisPredicate = createSymbolicBlock(arity0FunctionSort(), "genesis");
-	addRule(genesis(), "genesis");
-
 	set<SourceUnit const*, IdCompare> sources;
 	sources.insert(&_source);
-	for (auto const& source: _source.referencedSourceUnits(true))
+	for (auto const& source: _source.referencedSourceUnits())
```
Comment (mijovic) [inline libsolidity/formal/CHC.cpp]: It should not add sources recursively because later they are visited via third loop?

Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: Hm maybe they should be added recursively though

Comment (mijovic) [reply libsolidity/formal/CHC.cpp]: Can this be tested somehow?

Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: the added tests
`test/libsolidity/smtCheckerTests/imports/imported_fail_1.sol`
and
`test/libsolidity/smtCheckerTests/imports/imported_fail_2.sol`
have 3 sources where one imports the next, and this worked fine. Not sure which case would brake it. I changed it back to `recursive = true` to be safe.

Comment (mijovic) [reply libsolidity/formal/CHC.cpp]: I am fine with leaving true

**Review by mijovic — DISMISSED** [review]
Code and tests are looking fine.

**Comment by leonardoalt** [comment]
@mijovic I think I found the problematic test. Can you reapprove?

**Review by mijovic — APPROVED** [review]

**Comment by mijovic** [comment]
> @mijovic I think I found the problematic test. Can you reapprove?

Btw, do you have any viable explanation why the test was problematic?

**Comment by leonardoalt** [comment]
I don't, but I got it to fail 100% of the time even locally on my laptop.

File: Changelog.md [hunk 9]
```diff
@@ -44,6 +44,7 @@ Bugfixes:
  * SMTChecker: Fix internal error on lvalue unary operators with tuples.
  * SMTChecker: Fix internal error on tuple assignment.
  * SMTChecker: Fix internal error on tuples of one element that have tuple type.
+ * SMTChecker: Fix internal error when using imported code.
```
Comment (chriseth) [inline Changelog.md:47]: Wrong section of the changelog.
