### PR TITLE
Decide better in storing string literals as data

### LINKED ISSUE #4774: Optimisation: store (large) string literals as auxiliary data and codecopy them
Currently all strings are broken up into 32 byte items, `PUSH`d and `MSTORE`d.

The helper function [`CompilerUtils::storeStringData`](https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/CompilerUtils.cpp#L1181-L1201) is doing this, however it has a fixed rule for only doing it for >128 characters.

It should be exposed to the optimiser (or user) to decide based on cost.

### PR DESCRIPTION
**Pull request by axic**
Fixes #4774.

```
contract C {
  function f() pure public {
    require(false, "This is a short text.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
    require(true, "This is a very long text likely to exceed the limit of 32 bytes per push. And more. Really this should exceed it now, finally.");
  }
}
```

Before:
```
Gas estimation:
construction:
   831 + 793800 = 794631
external:
   f():	269
```

After:
```
Gas estimation:
construction:
   399 + 361400 = 361799
external:
   f():	269
```

One must add that storing string literal as data means it can be deduplicated, which is not the case with pushes.

### CODE REVIEW

File: libevmasm/ConstantOptimiser.cpp [hunk 1]
```diff
@@ -93,15 +93,8 @@ bigint ConstantOptimisationMethod::simpleRunGas(AssemblyItems const& _items)
 
 bigint ConstantOptimisationMethod::dataGas(bytes const& _data) const
 {
-	if (m_params.isCreation)
```
Comment (chriseth) [inline libevmasm/ConstantOptimiser.cpp]: Why did you remove this?

Comment (axic) [reply libevmasm/ConstantOptimiser.cpp]: It has been moved into another function, actually those 2 commits don't need to be part of this PR as it doesn't need to use `dataGas` at all.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 2]
```diff
@@ -1180,9 +1181,32 @@ void CompilerUtils::computeHashStatic()
...
-	if (_data.size() <= 128)
+	bool storeAsData = false;
+	if (_data.size() > 32)
+	{
+		unsigned numWords = (_data.size() + 31) / 32;
+		// @todo this does take the constant optimiser into account,
+		// which could reduce the costs of individual PUSHes
+		// NOTE: assumes the C++ compiler will optimise these statements
+		unsigned pushCost =
+			(eth::GasCosts::tier2Gas * numWords) + // PUSH value
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]: Please use the gas meter in conjunction with a sequence of assembly items.

File: libevmasm/GasMeter.cpp [hunk 3]
```diff
@@ -258,4 +258,15 @@ unsigned GasMeter::runGas(Instruction _instruction)
 	return 0;
 }
 
-
+u256 GasMeter::dataGas(bytes const& _data, bool _inCreation)
+{
+	if (_inCreation)
```
Comment (nventuro) [inline libevmasm/GasMeter.cpp]: This may look wrong to a newcomer: consider adding a comment explaining that creation data is only sent as tx data and not stored, whereas non-creation code will be sent to storage (and pay the confusingly-named `createDataGas` cost).

File: libsolidity/codegen/CompilerUtils.cpp (hunk 2 above)
Comment (axic) [reply libsolidity/codegen/CompilerUtils.cpp]: Looked into this now, it seems to be an overkill. `GasMeter` doesn't offer support for an item list and `PathGasMeter` seems to be heavy.

Did yoy mean using `PathGasMeter`?

**Comment by axic** [comment]
@chriseth updated to use `PathGasMeter`. It changes a bunch of things, but please review the logic in CompilerUtils first.

**Comment by chriseth** [comment]
Let's delay that to 0.5.1

**Comment by axic** [comment]
Split off the helper changes into new PRs, those are tiny and prefer to have them merged. This one though fine to be delayed as it should be tested better.

File: libevmasm/GasMeter.cpp (hunk 3 above)
Comment (axic) [reply libevmasm/GasMeter.cpp]: Added that in #5089.

**Comment by axic** [comment]
Needs a test.

**Comment by axic** [comment]
Another example:
```
contract C{
  function f() public {
    string memory a = "hello world";
    string memory b = "hello worldhello worldhello worldhello worldhello worldhello worldhello worldhello world";
    string memory c = "hello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello world";
  }
}
```

**Comment by axic** [comment]
@chriseth this should be done, just need to come up with a new metric for the "duplicate contract" test case.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 4]
```diff
@@ -1202,9 +1206,38 @@ void CompilerUtils::computeHashStatic()
...
+		auto copyCost = eth::PathGasMeter::estimateMax(eth::AssemblyItems{
+			u256(_data.size()), // length
+			u256(4096), // memory offset, assume memory is this big
+			u256(4096), // code offset, assume code is this big
+			Instruction::CODECOPY
+		}, m_context.evmVersion(), 0, make_shared<eth::KnownState>());
+
+		std::cout << "storeStringData: dataSize=" << _data.size() << " pushCost=" << pushCost << " copyCost=" << copyCost << std::endl;
+
+		if (copyCost < pushCost)
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]: This should also use the optimizer tradeoff parameter.

Comment (axic) [reply libsolidity/codegen/CompilerUtils.cpp]: I'm not sure I fully agree.  Using `PUSH` after the threshold will always be more expensive, because: it is more bytecode.

**Comment by axic** [comment]
Add changelog, remove debugging, fix test.

**Comment by chriseth** [comment]
Needs an actual test.

**Comment by chriseth** [comment]
I think we can ignore duplication for now. It is an issue if someone uses a `constant` string, though.

**Comment by chriseth** [comment]
This is tricky to get right and probably not worth it for now.

**Comment by chriseth** [comment]
Ok, let's at least go with the easy route.

File: test/libsolidity/GasCosts.cpp [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+	You should have received a copy of the GNU General Public License
+	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
+*/
+/**
+ * Tests that check that the cost of certain operations stay within range.
+ */
+
+#include <test/libsolidity/SolidityExecutionFramework.h>
+
+#include <math.h>
```
Comment (leonardoalt) [inline test/libsolidity/GasCosts.cpp]:
```suggestion
#include <cmath>
```

**Comment by chriseth** [comment]
Ah, just found a local file I forgot to check in....

**Comment by chriseth** [comment]
Updated and added a test.

**Comment by chriseth** [comment]
Should be ready.

**Review by leonardoalt — APPROVED** [review]
