### PR TITLE
Fix source location of builtin function calls.

### LINKED ISSUE #11068: Error in Yul source map (missing values in first instruction)
## Description

I've found a problem where I get an incorrect constructor source map when compiling Yul.  I haven't really tried different things here to determine what conditions cause this; I'm just going to report this as I found it.  The contract I tried compiling can be found below in the reproduction steps.

On compiling it I got the following constructor source map: `:::-:0;136:4:0;;110:1;101:40;156:4;153:1;146:15;59:106`.  This is mostly correct, but the beginning has a problem.  The very first instruction is `:::-:0`.  This has no start, no length, and no file index.  Now we can interpret these missing values as zero, but the result is still wrong.  The actual first instruction of the constructor bytecode is a `PUSH1 0x0a`, which corresponds to the `datasize("runtime")` call in `let size := datasize("runtime")`.  The source map ought to have that call as the first instruction.  Instead it has... nothing?

The deployed source map by contrast seems fine.

Anyway, sorry for not doing more testing to try to figure out what conditions cause this, but I don't really have the time at the moment, so I figured I'd just report this as it is.  This should be easily reproducible so hopefully it's not too hard to figure out what's going on here.

(Remark: If there were an AST, which of course there isn't at the moment (#11043), this error in the source map would keep Truffle Debugger from being able to inspect the `size` variable.  Of course as it is it can't do that anyway because there's no AST.)

## Environment

- Compiler version: 0.8.2
- Target EVM version (as per compiler settings): default

## Steps to Reproduce

Compile as Yul:

```yul
//SPDX-License-Identifier: MIT

object "YulTest2" {
  code {
    let size := datasize("runtime")
    datacopy(0, dataoffset("runtime"), size)
    return(0, size)
  }
  object "runtime" {
    code {
      mstore(0, 1)
      return(0, 0x20)
    }
  }
}
```

Observe the source map for the constructor bytecode.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/11068

### CODE REVIEW

File: libyul/backends/evm/EVMCodeTransform.cpp [hunk 1]
```diff
@@ -237,16 +237,14 @@ void CodeTransform::operator()(FunctionCall const& _call)
 {
 	yulAssert(m_scope, "");
 
+	m_assembly.setSourceLocation(extractSourceLocationFromDebugData(_call.debugData));
```
Comment (chriseth) [inline libyul/backends/evm/EVMCodeTransform.cpp:240]: This is the actual fix.

File: test/cmdlineTests/optimizer_inliner_dynamic_reference/output [hunk 2]
```diff
@@ -194,7 +194,7 @@ sub_0: assembly {
         /* "#utility.yul":406:415   */
       add
       swap1
-        /* "#utility.yul":244:421   */
+        /* "#utility.yul":196:421   */
```
Comment (chriseth) [inline test/cmdlineTests/optimizer_inliner_dynamic_reference/output:197]: This now references the full function instead of the last block (or even statement?)

**Review by Marenz — DISMISSED** [review]

**Comment by chriseth** [comment]
Fixed the 'objectCompiler' test expectations.

File: libyul/backends/evm/EVMCodeTransform.cpp (hunk 1 above)
Comment (ekpyron) [reply libyul/backends/evm/EVMCodeTransform.cpp:240]: Curious - I actually thought that ``builtin->generateCode`` did set the source location, but apparently it doesn't.
Ah, it actually does, but only after the arguments. And that doesn't affect non-builtin calls anyways, so nevermind anyways.

Comment (ekpyron) [reply libyul/backends/evm/EVMCodeTransform.cpp:240]: Or actually... doing it in ``builtin->generateCode`` before visiting the arguments as well would also fix it. Generally I'd like to change the ``generateCode`` thing and remove the callback in it and instead have the caller make sure that the arguments are on stack. But anyways, the fix is good for now.

**Review by ekpyron — DISMISSED** [review]

File: libyul/backends/evm/EVMCodeTransform.cpp (hunk 1 above)
Comment (chriseth) [reply libyul/backends/evm/EVMCodeTransform.cpp:240]: actually you are right, the instruction itself might have a different source location. let me fix it in some more places :)

**Comment by chriseth** [comment]
Added some more 'setSourceLocation' but it changes only few tests.

**Review by ekpyron — APPROVED** [review]
Did adding those ``setSourceLocation``s to the generator functions of the builtins make a difference? If so I'm not quite sure how and why - the builtins in question don't visit arguments... anyways, it doesn't hurt to set them there as well either way, so I'm approving.

**Comment by ekpyron** [comment]
Ah right - looking at the force-push I see it was the ``verbatim`` one for which it made a difference - that makes sense.
