### PR TITLE
[SMTChecker] Fix calls to virtual/overriden functions

### LINKED ISSUE #10671: [SMTChecker] Incorrect analysis of virtual function call
False negative in the following example:
```
pragma experimental SMTChecker;
contract A {
    int x = 0;

    function f() virtual internal view {
        assert(x == 0);
    }

    function proxy() public view {
        f();
    }
}

contract C is A {

    function f() internal view override {
        assert(x == 1);
    }
}
```

SMTChecker (CHC engine) does not report any problem.
However, the call to `C.proxy()`calls `C.f()` (using the virtual function call mechanism) where the assertion is violated, so an assertion violation should be reported.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/10671

### CODE REVIEW

**Comment by leonardoalt** [comment]
@blishko since you worked on a similar thing for modifiers recently, can you review this? I think the only difference to the modifiers implementation is that this can also be `super`

**Comment by blishko** [comment]
Sure, will check it.

**Comment by leonardoalt** [comment]
Thanks! I'm a bit annoyed about adding `m_currentContract` to all these helpers. Not super convinced, but also don't know another way.

**Review by blishko — COMMENTED** [review]
So far it looks good, but I would also try to see if we cannot get rid of the additional argument in the helper functions.

Also, I think it would be good to add a test using `super` keyword.

**Comment by leonardoalt** [comment]
Some of the helper functions are static, so we can't use `m_currentContract`. I'll check whether `m_currentContract` is consistent in all the non static ones.

Re `super` I added a test which caused a bug, so checking that now

File: libsolidity/formal/BMC.cpp [hunk 1]
```diff
@@ -473,8 +473,8 @@ void BMC::visitAddMulMod(FunctionCall const& _funCall)
 
 void BMC::inlineFunctionCall(FunctionCall const& _funCall)
 {
-	solAssert(shouldInlineFunctionCall(_funCall), "");
-	FunctionDefinition const* funDef = functionCallToDefinition(_funCall);
+	solAssert(shouldInlineFunctionCall(_funCall, m_currentContract), "");
+	auto [funDef, contextContract] = functionCallToDefinition(_funCall, m_currentContract);
```
Comment (leonardoalt) [inline libsolidity/formal/BMC.cpp:477]: We need the fully resolved function definition here.

File: libsolidity/formal/BMC.cpp [hunk 2]
```diff
@@ -100,9 +100,9 @@ void BMC::analyze(SourceUnit const& _source, map<ASTNode const*, set<Verificatio
 	m_errorReporter.clear();
 }
 
-bool BMC::shouldInlineFunctionCall(FunctionCall const& _funCall)
+bool BMC::shouldInlineFunctionCall(FunctionCall const& _funCall, ContractDefinition const* _contract)
 {
-	FunctionDefinition const* funDef = functionCallToDefinition(_funCall);
+	auto [funDef, contextContract] = functionCallToDefinition(_funCall, _contract);
```
Comment (leonardoalt) [inline libsolidity/formal/BMC.cpp:105]: We don't necessarily need the fully resolved function definition here, but might as well be precise.

File: libsolidity/formal/CHC.cpp [hunk 3]
```diff
@@ -580,18 +581,17 @@ void CHC::internalFunctionCall(FunctionCall const& _funCall)
 {
 	solAssert(m_currentContract, "");
 
-	auto const* function = functionCallToDefinition(_funCall);
+	auto [function, contract] = functionCallToDefinition(_funCall, m_currentContract);
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:584]: We need the fully resolved function definition here.

File: libsolidity/formal/SMTEncoder.cpp [hunk 4]
```diff
@@ -744,6 +744,7 @@ void SMTEncoder::initContract(ContractDefinition const& _contract)
 	m_context.pushSolver();
 	createStateVariables(_contract);
 	clearIndices(m_currentContract, nullptr);
+	m_variableUsage.setCurrentContract(_contract);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:747]: We need to pass this information to `VariableUsage` so it knows which function to inline properly in the BMC case

File: libsolidity/formal/SMTEncoder.cpp [hunk 5]
```diff
@@ -2798,9 +2816,9 @@ set<FunctionCall const*> SMTEncoder::collectABICalls(ASTNode const* _node)
 	return ABIFunctions(_node).abiCalls;
 }
 
-void SMTEncoder::createReturnedExpressions(FunctionCall const& _funCall)
+void SMTEncoder::createReturnedExpressions(FunctionCall const& _funCall, ContractDefinition const* _contract)
 {
-	FunctionDefinition const* funDef = functionCallToDefinition(_funCall);
+	auto [funDef, contextContract] = functionCallToDefinition(_funCall, _contract);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2821]: We need the fully resolved function definition here otherwise the return variables might be different

File: libsolidity/formal/SMTEncoder.cpp [hunk 6]
```diff
@@ -2826,18 +2844,18 @@ void SMTEncoder::createReturnedExpressions(FunctionCall const& _funCall)
 		defineExpr(_funCall, currentValue(*returnParams.front()));
 }
 
-vector<smtutil::Expression> SMTEncoder::symbolicArguments(FunctionCall const& _funCall)
+vector<smtutil::Expression> SMTEncoder::symbolicArguments(FunctionCall const& _funCall, ContractDefinition const* _contract)
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2847]: @blishko We actually need the FunctionDefinition here to know exactly how many and what types it expects. If we only use the FunctionType from the FunctionCall, it gives the wrong numbers if the function is bound.

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2847]: Yes, I agree. It would only be possible if `SMTEncoder::expr` would not require `targetType` for proper encoding...

**Comment by mijovic** [comment]
This passing of `m_currentContract` everywhere is annoying. Does it make sense to change some helpers to be non-static and just use `m_currentContract` instead of having additional parameter?

**Comment by leonardoalt** [comment]
It is annoying, but I would prefer to keep those helpers static, especially for the upcoming free functions stuff.

**Comment by leonardoalt** [comment]
@mijovic approve or should I change anything?

**Review by mijovic — APPROVED** [review]
Looks good to me!
