### PR TITLE
OverrideSpecifier: Check for null before dereferencing

### LINKED ISSUE #10874: [PostTypeChecker] Null deref because declaration referenced in the override specifier has unset type
## Description

```
contract A {
  function f() public virtual {}
}
contract B {
  function g() public {}
}
contract C is A,B {
  function f() public override (g) {}
}
```

references a nullptr here

https://github.com/ethereum/solidity/blob/dde6353c5d490009a8ec13978462190e4f7a1528/libsolidity/analysis/PostTypeChecker.cpp#L234

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by Marenz**
fixes #10874

### CODE REVIEW

**Comment by Marenz** [comment]
Ah, missing test...

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 1]
```diff
@@ -225,13 +225,19 @@ struct OverrideSpecifierChecker: public PostTypeChecker::Checker
 			if (dynamic_cast<ContractDefinition const*>(decl))
 				continue;
 
-			TypeType const* actualTypeType = dynamic_cast<TypeType const*>(decl->type());
+			auto const typeString = [&]()
+			{
+				if (TypeType const* actualTypeType = dynamic_cast<TypeType const*>(decl->type()))
```
Comment (hrkrshnn) [inline libsolidity/analysis/PostTypeChecker.cpp]:
```suggestion
				if (auto actualTypeType = dynamic_cast<TypeType const*>(decl->type()))
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 2]
```diff
@@ -225,13 +225,19 @@ struct OverrideSpecifierChecker: public PostTypeChecker::Checker
...
+				else
+					return decl->type()->toString(true);
+			};
 
 			m_errorReporter.typeError(
 				9301_error,
 				override->location(),
 				"Expected contract but got " +
-				actualTypeType->actualType()->toString(true) +
+				typeString() +
```
Comment (hrkrshnn) [inline libsolidity/analysis/PostTypeChecker.cpp]:
```suggestion
				decl->type()->toString(true) +
```
Why not this?

Comment (ekpyron) [reply libsolidity/analysis/PostTypeChecker.cpp]: Or ``(actualType ? actualType->actualType() : decl->type())->toString(true)`` with the old definition of ``actualType``? Not that I don't like lambdas, but maybe slight overkill for this :-).
``decl->type()->toString(true)`` actually would also really be fine - in case of a ``TypeType`` it'll just be ``type(<type>)`` instead of ``<type>``, which wouldn't bother at least me.

**Review by ekpyron — DISMISSED** [review]
Already approving despite the comments, because the fix is fine and the comments are purely cosmetic.

**Comment by ekpyron** [comment]
Should this get a Changelog entry, though? We do that for ICEs at times at least...

**Review by ekpyron — APPROVED** [review]

**Review by hrkrshnn — APPROVED** [review]
