### PR TITLE
Check availability of data objects already in analysis phase.

### LINKED ISSUE #6879: [yul] Exception due to syntax error in object access builtin function
## Description

Syntax errors such as these should not throw an exception

```
{codecopy(datasize(6),5,5)}
```

but they do

```
$ echo "{codecopy(datasize(6),5,5)}" | solc --strict-assembly -
Warning: Yul and its optimizer are still experimental. Please use the output with care.

======= <stdin> (EVM) =======

Pretty printed source:
object "object" {
    code { codecopy(datasize(6), 5, 5) }
}

Exception while assembling: /home/bhargava/work/github/solidity/libyul/backends/evm/EVMDialect.cpp(130): Throw in function {anonymous}::createBuiltins(langutil::EVMVersion, bool)::<lambda(const yul::FunctionCall&, yul::AbstractAssembly&, yul::BuiltinContext&, std::function<void()>)>
Dynamic exception type: boost::exception_detail::clone_impl<yul::YulException>
std::exception::what: Could not find assembly object <6>.
[dev::tag_comment*] = Could not find assembly object <6>.
```

## Environment

- Compiler version: latest develop

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/6879

### CODE REVIEW

**Comment by leonardoalt** [comment]
What happens now if you run the buggy test from the issue?
`{codecopy(datasize(6),5,5)}`

**Comment by leonardoalt** [comment]
Can you add some tests that trigger the new error?

File: libyul/AssemblyStack.cpp [hunk 1]
```diff
@@ -113,7 +113,20 @@ bool AssemblyStack::analyzeParsed(Object& _object)
 {
 	solAssert(_object.code, "");
 	_object.analysisInfo = make_shared<AsmAnalysisInfo>();
-	AsmAnalyzer analyzer(*_object.analysisInfo, m_errorReporter, boost::none, languageToDialect(m_language, m_evmVersion));
+
+	set<YulString> objectNames;
+	objectNames.insert(_object.name);
+	for (auto const& subObject: _object.subIndexByName)
+		objectNames.insert(subObject.first);
```
Comment (leonardoalt) [inline libyul/AssemblyStack.cpp]: Would this have more nested levels? (sub of sub)

Comment (chriseth) [reply libyul/AssemblyStack.cpp]: Yes, but that is not yet implemented in the code generator either.

**Comment by chriseth** [comment]
Looks like this needs some more changes...

**Comment by chriseth** [comment]
Updated.

**Comment by leonardoalt** [comment]
Windows build error

**Comment by chriseth** [comment]
Updated.

File: libyul/optimiser/StackCompressor.h [hunk 2]
```diff
@@ -27,13 +27,15 @@ namespace yul
...
 struct Dialect;
-struct Block;
+struct Object;
 struct FunctionDefinition;
 
 /**
  * Optimisation stage that aggressively rematerializes certain variables in a function to free
  * space on the stack until it is compilable.
  *
+ * Only runs on the code of the object itself, does not descend into sub-objects.
```
Comment (leonardoalt) [inline libyul/optimiser/StackCompressor.h:37]: Is this behavior different from what was there before?

Comment (leonardoalt) [reply libyul/optimiser/StackCompressor.h:37]: It doesn't look like it, was the comment added just to be more explicit?

File: libsolidity/codegen/CompilerContext.cpp [hunk 3]
```diff
@@ -423,23 +424,19 @@ void CompilerContext::appendInlineAssembly(
...
 			dialect,
 			&meter,
-			*parserResult,
-			analysisInfo,
+			obj,
 			_optimiserSettings.optimizeStackAllocation,
 			externallyUsedIdentifiers
 		);
-		analysisInfo = yul::AsmAnalysisInfo{};
-		if (!yul::AsmAnalyzer(
```
Comment (leonardoalt) [inline libsolidity/codegen/CompilerContext.cpp:435]: Was this call moved somewhere else?

File: libyul/optimiser/StackCompressor.h (hunk 2 above)
Comment (chriseth) [reply libyul/optimiser/StackCompressor.h:37]: The behaviour is the same, but we are now passing a full object containing multiple ASTs instead of just a single AST. Because of that, I added the explanation that in only considers the main ast inside the object.

File: libsolidity/codegen/CompilerContext.cpp (hunk 3 above)
Comment (chriseth) [reply libsolidity/codegen/CompilerContext.cpp:435]: The optimizer suite already updates the analysis info inside `obj` and thus this is not necessary anymore.

**Review by leonardoalt — APPROVED** [review]
