### PR TITLE
Fix wording of non-function override error messages.

### LINKED ISSUE #8691: Typo in error message for modifiers
## Description
There is a typo in the (secondary) error message for overriding modifiers.

## Environment
Current develop.

## Steps to Reproduce

```solidity
contract A { modifier mod() virtual { _; } }
contract B is A { modifier mod() { _; } }
```

The output is:
```
Error: Overriding modifier is missing "override" specifier.
 --> /tmp/abstract.sol:2:19:
  |
2 | contract B is A { modifier mod() { _; } }
  |                   ^^^^^^^^^^^^^^^^^^^^^
Note: Overridden function is here:
 --> /tmp/abstract.sol:1:14:
  |
1 | contract A { modifier mod() virtual { _; } }
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

"Note: Overridden **function** is here:"  should be changed to **modifier**

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/8691

### CODE REVIEW

**Comment by axic** [comment]
Does the test format does not record secondary locations or there are no tests for these?

**Comment by chriseth** [comment]
isoltest ignores secondary locations and messages.

**Review by axic — APPROVED** [review]

File: libsolidity/analysis/OverrideChecker.cpp [hunk 1]
```diff
@@ -536,7 +542,13 @@ void OverrideChecker::checkOverride(OverrideProxy const& _overriding, OverridePr
 	if (_overriding.isVariable())
 	{
 		if (_super.visibility() != Visibility::External)
-			overrideError(_overriding, _super, 5225_error, "Public state variables can only override functions with external visibility.");
+			overrideError(
+				_overriding,
+				_super,
+				5225_error,
+				"Public state variables can only override functions with external visibility.",
+				"Overridden function is here:"
```
Comment (axic) [inline libsolidity/analysis/OverrideChecker.cpp:550]: Checked the header and it seems to be defaulting to this very text in the first place. Perhaps remove the default or remove this line?
