### PR TITLE
Fix variable clearing in DataFlowAnalyzer being affected by variable names

### LINKED ISSUE #14494: (v0.8.21) Contract code changes with additional files in compilation
Here I am again with another issue with extra files in compilation causing trouble 🫡 

By extra files I mean files that the target contract does not depend on.

## Recap 
First a recap on previous issues similarly on extra files in compilation:
1. https://github.com/ethereum/solidity/issues/12281 
This was an older issue that seems to affect the AST IDs in `0.6.12` and `0.7.0`. We also encountered this and handled in Sourcify's case https://github.com/ethereum/sourcify/issues/618
2. https://github.com/ethereum/solidity/issues/14250 
I've encountered this in a `0.8.19` contract and got fixed in `0.8.21` with https://github.com/ethereum/solidity/pull/14311.

## Current Issue
I've encountered the current issue in https://github.com/ethereum/sourcify/issues/1065. 

My initial suspicion was that it's an instance of the 2. case because the contract was a `0.8.19` contract. Unfortunately, I was able to reproduce the case in `0.8.21`.

Although the 1. case should have been resolved, I suspect it still can be related because **the metadata hashes are identical** but the bytecodes differ. 

### To reproduce
I named inputs as "hardhat" and "sourcify". "Sourcify" uses the minimum number of source files, because it is based on the ones listed in the contract metadata. "Hardhat" uses extra because by default Hardhat inputs everything to the compiler. Sourcify has two different inputs `0.8.19` and `0.8.21` because it includes the `evmVersion` inside the input i.e. `paris` vs `shanghai`.

[N2MERC721-hardhat-input.json.txt](https://github.com/ethereum/solidity/files/12345384/N2MERC721-hardhat-input.json.txt)
[N2MERC721-sourcify-input-0.8.21.json.txt](https://github.com/ethereum/solidity/files/12345386/N2MERC721-sourcify-input.json.txt)
[N2MERC721-sourcify-input-0.8.19.json.txt](https://github.com/ethereum/solidity/files/12345498/N2MERC721-sourcify-input-0.8.19.json.txt)

You can see the two inputs differ only in some extra files + some of the compiler settings 
<details>
<summary> These are the extra files in Hardhat input </summary>

```js
[
  '@nfts2me/contracts/interfaces/IN2MBeaconFactory.sol',
  '@openzeppelin/contracts-upgradeable/token/ERC1155/ERC1155Upgradeable.sol',
  '@openzeppelin/contracts-upgradeable/token/ERC1155/extensions/ERC1155SupplyUpgradeable.sol',
  '@openzeppelin/contracts-upgradeable/token/ERC1155/extensions/IERC1155MetadataURIUpgradeable.sol',
  '@openzeppelin/contracts-upgradeable/token/ERC1155/IERC1155ReceiverUpgradeable.sol',
  '@openzeppelin/contracts-upgradeable/token/ERC1155/IERC1155Upgradeable.sol',
  '@openzeppelin/contracts/governance/utils/IVotes.sol',
  '@openzeppelin/contracts/proxy/Proxy.sol',
  '@openzeppelin/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol',
  '@openzeppelin/contracts/token/ERC1155/IERC1155.sol',
  '@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol',
  '@openzeppelin/contracts/token/ERC721/IERC721.sol',
  '@openzeppelin/contracts/utils/introspection/IERC165.sol',
  'contracts/beacon/N2MERC1155Upgradeable.sol',
  'contracts/beacon/N2MERC721Upgradeable.sol',
  'contracts/beacon/N2MUpgradeable.sol',
  'contracts/interfaces/IN2M_ERCBase.sol',
  'contracts/interfaces/IN2M_ERCCommon.sol',
  'contracts/interfaces/IN2M_ERCLibrary.sol',
  'contracts/interfaces/IN2M_ERCStorage.sol',
  'contracts/interfaces/IN2MBeaconFactory.sol',
  'contracts/interfaces/IN2MCrossFactory.sol',
  'contracts/interfaces/IN2MERC1155.sol',
  'contracts/interfaces/IN2MERC721.sol',
  'contracts/interfaces/IOperatorFilterRegistry.sol',
  'contracts/interfaces/IReverseRegistrar.sol',
  'contracts/N2MERC1155.sol',
  'contracts/ownable/NFTOwnableUpgradeable.sol',
  'contracts/TextUtils.sol'
]
```

</details>

<details>
<summary> Also leaving the JS script I used to check the differences of the keys of `.sources` in the JSON inputs </summary>

Usage:
`node checkFileKeysDifferences.js solcInput-1.json solcInput-2.json`

```js
const fs = require("fs");

function findKeyDifferences(file1, file2) {
  const json1 = JSON.parse(fs.readFileSync(file1, "utf8"));
  const json2 = JSON.parse(fs.readFileSync(file2, "utf8"));

  const sources1 = new Set(Object.keys(json1.sources) || []);
  const sources2 = new Set(Object.keys(json2.sources) || []);

  const keysOnlyInFile1 = Array.from(sources1).filter(
    (key) => !sources2.has(key)
  );
  const keysOnlyInFile2 = Array.from(sources2).filter(
    (key) => !sources1.has(key)
  );

  return {
    keysOnlyInFile1,
    keysOnlyInFile2,
  };
}

// Retrieve file paths from command-line arguments
const [file1Path, file2Path] = process.argv.slice(2);

if (!file1Path || !file2Path) {
  console.log("Please provide two file paths as command-line arguments.");
  process.exit(1);
}

const { keysOnlyInFile1, keysOnlyInFile2 } = findKeyDifferences(
  file1Path,
  file2Path
);

console.log("Keys only in file 1:", keysOnlyInFile1);
console.log("Keys only in file 2:", keysOnlyInFile2);
```

</details>

To extract the runtime bytecode:
```
cat N2MERC721-sourcify-input-0.8.19.json | solc --standard-json | jq '.contracts."contracts/N2MERC721.sol".N2MERC721.evm.deployedBytecode.object' > N2MERC721-0.8.19-sourcify-runtime-bytecode-from-solc.txt
```

### My Bytecode outputs
[N2MERC721-0.8.21-sourcify-runtime-bytecode.txt](https://github.com/ethereum/solidity/files/12345499/N2MERC721-0.8.21-sourcify-runtime-bytecode.txt)
[N2MERC721-0.8.21-hardhat-runtime-bytecode.txt](https://github.com/ethereum/solidity/files/12345501/N2MERC721-0.8.21-hardhat-runtime-bytecode.txt)
[N2MERC721-0.8.19-sourcify-runtime-bytecode.txt](https://github.com/ethereum/solidity/files/12345502/N2MERC721-0.8.19-sourcify-runtime-bytecode.txt)
[N2MERC721-0.8.19-hardhat-runtime-bytecode.txt](https://github.com/ethereum/solidity/files/12345503/N2MERC721-0.8.19-hardhat-runtime-bytecode.txt)

To check the diff:
```
git diff --word-diff --word-diff-regex=. N2MERC721-0.8.19-hardhat-runtime-bytecode.txt N2MERC721-0.8.19-sourcify-runtime-bytecode.txt
```

Will give you a diff like this:
image

## Environment

- Compiler version: `0.8.19` and `0.8.21` (both Emscripten and Darwin.appleclang)  
- Target EVM version (as per compiler settings): `paris` and `shanghai`
- Framework/IDE (e.g. Truffle or Remix): none
- EVM execution environment / backend / blockchain client:
- Operating system: MacOS

Again, one particular thing that got my attention was that the metadata hashes were identical in all cases. This leaves me thinking if this is similar to the 1. case I mentioned.

### PR DESCRIPTION
**Pull request by cameel**
Fixes #14494.
~Depends on #14585.~ Merged.

### CODE REVIEW

File: libyul/optimiser/DataFlowAnalyzer.cpp [hunk 1]
```diff
@@ -351,13 +351,14 @@ void DataFlowAnalyzer::clearValues(std::set<YulString> _variables)
 	});
 
 	// Also clear variables that reference variables to be cleared.
+	std::set<YulString> referencingVariables;
 	for (auto const& variableToClear: _variables)
 		for (auto const& [ref, names]: m_state.references)
 			if (names.count(variableToClear))
-				_variables.emplace(ref);
+				referencingVariables.emplace(ref);
```
Comment (nikola-matic) [inline libyul/optimiser/DataFlowAnalyzer.cpp:358]: That'll do it.

File: test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul [hunk 2]
```diff
@@ -0,0 +1,30 @@
+object "C" {
```
Comment (nikola-matic) [inline test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul:1]: Did you check if this yields a failure without the above fix? (I'm sure you did, buy I have to ask).

**Review by nikola-matic — DISMISSED** [review]

File: test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul (hunk 2 above)
Comment (r0qs) [reply test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul:1]: If not, I double-checked it now, and it does generate a different assembly code using solidity version `0.8.21`. This PR indeed fixes that.

```diff
16d15
<                     let mid := var
19c18
<                     default { sstore(a, mid) }
---
>                     default { sstore(a, var) }
48,49c47
<       dup1
<       dup4
---
>       dup3
53d50
<       pop
59,62c56
<       swap3
<       pop
<       dup3
<       swap1
---
>       swap2
63a58
>       dup2
```

**Review by r0qs — DISMISSED** [review]

File: test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul (hunk 2 above)
Comment (cameel) [reply test/cmdlineTests/~name_dependent_cse_bug/cse_bug.yul:1]: Yeah I did. But you have a point - it's not very easy to tell without running the code. And the cause is so finicky that it's hard to be sure that this will continue to be a true repro for this issue as optimizer keeps changing.

Hard do to anything about it though. The best I could come up with is to add an optimizer test that shows the generated IR. I just pushed the change. You can check in the diff of the second commit how the fix affects the output.

File: test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_1.yul [hunk 3]
```diff
@@ -35,10 +35,9 @@
 //         {
 //             let _1 := add(a, a)
 //             let var := add(_1, _1)
-//             let mid := var
 //             switch a
 //             case 0 { a := var }
-//             default { sstore(0, mid) }
+//             default { sstore(0, var) }
```
Comment (cameel) [inline test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_1.yul]: This is what the fix does.

Comment (r0qs) [reply test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_1.yul]: Nice :D

However, the test suite seems to be adding an extra `let a_1 := 0`, I suspected that it is the use of `fullSuite` there that may have a different optimization steps than the one used by `--optimize` flag?. Compiling the example using the CLI results in the exact test case you added.

```
object "object" {
    code {
        {
            let a := 0
            for { } a { }
            {
                let _1 := add(a, a)
                let var := add(_1, _1)
                switch a
                case 0 { a := var }
                default { sstore(0, var) }
            }
        }
    }
}
```

Comment (cameel) [reply test/libyul/yulOptimizerTests/fullSuite/name_dependent_cse_bug_part_1.yul]: It seems to be a difference between EVM versions. It gets added on pre-`shanghai` EVMs, while my version is from `shanghai`. Not entirely sure why exactly but some steps do have output dependent on EVM version so this does not seem to be a bug.


I split this test into two versions to account for this and now CI should pass.

**Review by r0qs — DISMISSED** [review]

File: Changelog.md [hunk 4]
```diff
@@ -13,6 +13,7 @@ Compiler Features:
 Bugfixes:
  * AST: Fix wrong initial ID for Yul nodes in the AST.
  * Code Generator: Fix output from via-IR code generator being dependent on which files were discovered by import callback. In some cases, a different AST ID assignment would alter the order of functions in internal dispatch, resulting in superficially different but semantically equivalent bytecode.
+ * Common Subexpression Eliminator: Fix replacement decisions being affected by Yul variable names generated by the compiler, resulting in different (but equivalent) bytecode in some situations.
```
Comment (ekpyron) [inline Changelog.md]: ``Common Subexpression Eliminator`` is ambiguous actually (between libyul and libevmasm) :-).
I'd make it ``Yul Optimizer`` as category and then just e.g. ``replacement decisions during CSE`` or something.

Comment (cameel) [reply Changelog.md]: Good point. Changed.

**Review by ekpyron — APPROVED** [review]
Did you properly think through the comment stating that the clearing doesn't need to be recursive here :-)? I mean, if that's wrong, we have larger problems here than non-determinism, so I'm assuming it's correct for now and am approving this, but I haven't double-checked it again now.

**Comment by cameel** [comment]
> Did you properly think through the comment stating that the clearing doesn't need to be recursive here :-)?

Yeah, there's a docstring explaining the reasoning a few lines above:

```c++
	// All variables that reference variables to be cleared also have to be
	// cleared, but not recursively, since only the value of the original
	// variables changes. Example:
	// let a := 1
	// let b := a
	// let c := b
	// a := 2
	// add(b, c)
	// In the last line, we can replace c by b, but not b by a.
```

Which sounds reasonable. If you have a chain `e -> d -> c -> b -> a -> 1`, changing `a` only breaks the link to `a` and the `e -> d -> c -> b` part is still valid because none of those variables were directly changed and the links are (I assume) symbolic.

Before the PR the code was always clearing at least the variables and direct references. Only the second and higher layers of references were cleared inconsistently. That seems like it should not affect correctness. I.e. we may at most clear them unnecessarily and miss out on a valid optimization.
