### PR TITLE
Fix issue with pop on storage array.

### LINKED ISSUE #10870: [codegen] bad cast during pop of storage array
## Description

```
contract C {
  int[] data;
  function f() public { (data.pop)(); }
}
```

throws

https://github.com/ethereum/solidity/blob/c7dfd78e57c5ad7abd485dc1cc13d8f0ab09d431/libsolidity/codegen/ExpressionCompiler.cpp#L1020

I suspect something is wrong with parsing `data.pop` (minus the parentheses)

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by aarlt**
Fixes #10870.

### CODE REVIEW

**Comment by aarlt** [comment]
I fixed this differently when discussed. I use now the `TypeChecker` to retrieve the needed array type information and store the result in a `FunctionCallAnnotation`. Is it ok to use the `TypeChecker` to do this?

 I also tried to add this information directly to the `FunctionType`, but I was not able to do this, somehow I was only able to retrieve `const FunctionType`'s. So I could not add the information there. But probably I missed something.

**Comment by chriseth** [comment]
I don't think this is the solution. Does it work on the following:
```
contract C {
  uint[] x;
  function f() internal returns (uint[] storage) { return x; }
  function g() internal {
    f().pop();
  }
}
```

**Comment by chriseth** [comment]
Ah, I think it does - what about the following:
```
contract C {
  uint[] x;
  function g() internal {
    (([x])[0]).pop();
  }
}
```

**Comment by aarlt** [comment]
> Ah, I think it does - what about the following:
> 
> ```
> contract C {
>   uint[] x;
>   function g() internal {
>     (([x])[0]).pop();
>   }
> }
> ```

```
Error: Member "pop" is not available in uint256[] memory outside of storage.
 --> /tmp/contract3.sol:4:5:
  |
4 |     (([x])[0]).pop();
  |     ^^^^^^^^^^^^^^


Process finished with exit code 1
```

**Comment by chriseth** [comment]
I think you can create the function type using
```
	FunctionType(
		TypePointers{arrayType},
		TypePointers{},
		strings(),
		strings(),
		FunctionType::Kind::ArrayPop,
		false,
		StateMutability::NonPayable,
		nullptr,
		false,
		false,
		false,
		true
	):
```

**Comment by chriseth** [comment]
Ah, more easily:
```
	FunctionType(
		TypePointers{arrayType},
		TypePointers{},
		strings(),
		strings(),
		FunctionType::Kind::ArrayPop,
	).asBoundFunction();
```

File: libsolidity/analysis/TypeChecker.h [hunk 1]
```diff
@@ -180,6 +180,8 @@ class TypeChecker: private ASTConstVisitor
 			return m_currentSourceUnit;
 	}
 
+	ArrayType const* m_arrayType = nullptr;
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.h]: TypeChecker should have as little state as possible, especially about things that are not syntax but expression related.

**Comment by aarlt** [comment]
I rewrote now the PR so that it uses `FunctionType`. But somehow there seem to be some additional behaviour involved, especially with regards to yul. So the yul related tests will fail for now.

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 2]
```diff
@@ -1014,13 +1014,10 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 		case FunctionType::Kind::ArrayPop:
 		{
 			_functionCall.expression().accept(*this);
-			solAssert(function.parameterTypes().empty(), "");
-
-			ArrayType const& arrayType = dynamic_cast<ArrayType const&>(
-				*dynamic_cast<MemberAccess const&>(_functionCall.expression()).expression().annotation().type
-			);
+//			solAssert(function.bound(), "");
```
Comment (aarlt) [inline libsolidity/codegen/ExpressionCompiler.cpp]: Not sure why it is not bound here.

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -2039,6 +2039,9 @@ void TypeChecker::typeCheckFunctionGeneralChecks(
 	solAssert(!!_functionType, "");
 	solAssert(_functionType->kind() != FunctionType::Kind::ABIDecode, "");
 
+	if (_functionType->kind() == FunctionType::Kind::ArrayPop)
```
Comment (aarlt) [inline libsolidity/analysis/TypeChecker.cpp]: I guess something like this would be also needed for yul. Not sure whether it should be done differently.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 4]
```diff
@@ -1286,8 +1286,9 @@ void IRGeneratorForStatements::endVisit(FunctionCall const& _functionCall)
 	}
 	case FunctionType::Kind::ArrayPop:
 	{
-		auto const& memberAccessExpression = dynamic_cast<MemberAccess const&>(_functionCall.expression()).expression();
-		ArrayType const& arrayType = dynamic_cast<ArrayType const&>(*memberAccessExpression.annotation().type);
+//		solAssert(functionType->bound(), "");
```
Comment (aarlt) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Also here

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 2 above)
Comment (hrkrshnn) [reply libsolidity/codegen/ExpressionCompiler.cpp]: Why should it be bound?

File: libsolidity/analysis/TypeChecker.cpp (hunk 3 above)
Comment (hrkrshnn) [reply libsolidity/analysis/TypeChecker.cpp]: Not sure if returning early is the way to proceed here. What goes wrong here?

**Comment by aarlt** [comment]
@chriseth I'm not sure whether the usage of `FunctionType` to solve this is a good solution. The usage seem to implicate some additional behaviour within the type-checker & codegen. That means, if we use `FunctionType` we need to have special cases in the behaviour, if we see a function type kind of `FunctionType::Kind::ArrayPop`. 

If the `FunctionType` is setup so that the array-type is saved in the return-type - we got a problem with the stack-height. If we use the parameter-type we will need to change the type-checker to ignore the checks that detect that  there was no parameter provided for `pop()`. Also the yul generator seem to generate code where pop will have one additional parameter needed (this is right now the reason for the failing tests).

@chriseth did you meant the usage of `FunctionType` like this?

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 2 above)
Comment (aarlt) [reply libsolidity/codegen/ExpressionCompiler.cpp]: I understand it like that the `function` here is basically exactly the `FunctionType` object that I created in `bool TypeChecker::visit(FunctionCall const& _functionCall)`, where I set `bound` explicitly to `true`. But it looks like that I missed something here.

File: libsolidity/analysis/TypeChecker.cpp (hunk 3 above)
Comment (aarlt) [reply libsolidity/analysis/TypeChecker.cpp]: The problem is that, because I used the `FunctionType` to store the actual array type within the parameters, that the type-checker wants to check for the supplied arguments. Thats why I just "ignore" the check here, if `FunctionType::Kind::ArrayPop` is used. But I'm not sure whether we want to do it like this. Seem to be not a very nice solution.

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 2 above)
Comment (aarlt) [reply libsolidity/codegen/ExpressionCompiler.cpp]: @christeth because this is not `bound` here, it is not the exact same `FunctionType` object I created before, right? I think I missed something here. Maybe you can give a hint?

**Comment by chriseth** [comment]
Did you try returning a bound function type inside `ArrayType::nativeMembers`?

File: libsolidity/formal/SMTEncoder.cpp [hunk 5]
```diff
@@ -1656,8 +1655,6 @@ void SMTEncoder::arrayPushPopAssign(Expression const& _expr, smtutil::Expression
 	else if (auto const* funCall = dynamic_cast<FunctionCall const*>(expr))
 	{
 		FunctionType const& funType = dynamic_cast<FunctionType const&>(*funCall->expression().annotation().type);
-		// Push cannot occur on an expression that is itself a ByteArrayPush, i.e., bytes.push().push() is not possible.
-		solAssert(funType.kind() != FunctionType::Kind::ByteArrayPush, "");
 		if (funType.kind() == FunctionType::Kind::ArrayPush)
 		{
 			auto memberAccess = dynamic_cast<MemberAccess const*>(&funCall->expression());
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp:1660]: This cast fails for the given test case. @leonardoalt

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 6]
```diff
@@ -585,7 +585,12 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 		FunctionType const& function = *functionType;
 		if (function.bound())
 			// Only delegatecall and internal functions can be bound, this might be lifted later.
```
Comment (mijovic) [inline libsolidity/codegen/ExpressionCompiler.cpp]: Maybe update comment here as well?

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 7]
```diff
@@ -1014,14 +1015,10 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 		case FunctionType::Kind::ArrayPop:
 		{
 			_functionCall.expression().accept(*this);
-			solAssert(function.parameterTypes().empty(), "");
```
Comment (mijovic) [inline libsolidity/codegen/ExpressionCompiler.cpp:1017]: Can we add equivalent to this check?

File: test/libsolidity/semanticTests/array/pop/parenthesized.sol [hunk 8]
```diff
@@ -0,0 +1,12 @@
+contract C {
+  int[] data;
+  function f() public returns (uint) {
+    data.push(1);
+    (data.pop)();
```
Comment (mijovic) [inline test/libsolidity/semanticTests/array/pop/parenthesized.sol:5]: maybe adding `(data.push)()` with and without parameters as well? In combination with some assertions maybe

**Review by mijovic — COMMENTED** [review]
Nice to remove redundant function type. Few small suggestions

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 6 above)
Comment (mijovic) [reply libsolidity/codegen/ExpressionCompiler.cpp]: Or remove this comment, not sure if it makes too much sense...

**Comment by chriseth** [comment]
Removed the comment.

**Comment by mijovic** [comment]
> Nice to remove redundant function type. Few small suggestions

What about https://github.com/ethereum/solidity/pull/10896#discussion_r574624314
and https://github.com/ethereum/solidity/pull/10896#discussion_r574622173

File: libsolidity/ast/Types.cpp [hunk 9]
```diff
@@ -1802,27 +1802,28 @@ MemberList::MemberMap ArrayType::nativeMembers(ASTNode const*) const
...
-				TypePointers{baseType()},
+				TypePointers{thisAsPointer, baseType()},
 				TypePointers{},
-				strings{string()},
+				strings{string(),string()},
 				strings{},
-				isByteArray() ? FunctionType::Kind::ByteArrayPush : FunctionType::Kind::ArrayPush
-			));
+				FunctionType::Kind::ArrayPush
+			)->asBoundFunction());
```
Comment (hrkrshnn) [inline libsolidity/ast/Types.cpp:1823]: Do they really have to be `asBoundFunction()`? Not sure if the name "bound" is appropriate for array members.

If we decide to go for this, then the documentation should be updated in `Types.h`.

```
	/// @returns a copy of this function type with the `bound` flag set to true.
	/// Should only be called on library functions.
	FunctionTypePointer asBoundFunction() const;
```

The rich identifier for `bound` currently is
```
	if (bound())
		id += "bound_to" + identifierList(selfType());
```
Does the name "bound" make sense in this context?

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 10]
```diff
@@ -945,20 +949,18 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
...
 			if (function.parameterTypes().size() == 0)
 			{
 				auto paramType = function.returnParameterTypes().at(0);
 				solAssert(paramType, "");
 
-				ArrayType const* arrayType =
-					function.kind() == FunctionType::Kind::ArrayPush ?
-					TypeProvider::array(DataLocation::Storage, paramType) :
-					TypeProvider::bytesStorage();
+				ArrayType const* arrayType = dynamic_cast<ArrayType const*>(function.selfType());
```
Comment (hrkrshnn) [inline libsolidity/codegen/ExpressionCompiler.cpp:962]:
```suggestion
				auto arrayType = dynamic_cast<ArrayType const*>(function.selfType());
```
Same type twice. Also, at other places in the same file. Changing is optional :)

File: libsolidity/ast/Types.cpp [hunk 11]
```diff
@@ -1802,27 +1802,28 @@ MemberList::MemberMap ArrayType::nativeMembers(ASTNode const*) const
...
-			));
+				strings{string()},
+				FunctionType::Kind::ArrayPush
+			)->asBoundFunction());
 			members.emplace_back("push", TypeProvider::function(
-				TypePointers{baseType()},
+				TypePointers{thisAsPointer, baseType()},
 				TypePointers{},
-				strings{string()},
+				strings{string(),string()},
```
Comment (hrkrshnn) [inline libsolidity/ast/Types.cpp:1820]:
```suggestion
				strings{string(), string()},
```
We could also consider replacing `string()` by `""` or `string{}`. I was slightly confused if `ArrayType` had a member named `string()`.

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 7 above)
Comment (hrkrshnn) [reply libsolidity/codegen/ExpressionCompiler.cpp:1017]: Actually the same assert should work here.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 12]
```diff
@@ -1276,30 +1276,31 @@ void IRGeneratorForStatements::endVisit(FunctionCall const& _functionCall)
 	}
 	case FunctionType::Kind::ArrayPop:
 	{
-		auto const& memberAccessExpression = dynamic_cast<MemberAccess const&>(_functionCall.expression()).expression();
-		ArrayType const& arrayType = dynamic_cast<ArrayType const&>(*memberAccessExpression.annotation().type);
+		solAssert(functionType->bound(), "");
+		solAssert(functionType->parameterTypes().size() == 0, "");
```
Comment (hrkrshnn) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]:
```suggestion
		solAssert(functionType->parameterTypes().empty(), "");
```

File: libsolidity/ast/Types.cpp [hunk 13]
```diff
@@ -3077,8 +3077,8 @@ vector<tuple<string, TypePointer>> FunctionType::makeStackItems() const
 		break;
 	case Kind::ArrayPush:
 	case Kind::ArrayPop:
-	case Kind::ByteArrayPush:
-		slots = {make_tuple("slot", TypeProvider::uint256())};
+		solAssert(bound(), "");
+		slots = {};
```
Comment (hrkrshnn) [inline libsolidity/ast/Types.cpp:3087]:
```suggestion
```

File: libsolidity/ast/Types.cpp (hunk 9 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp:1823]: For now, we only used bound functions for `using A for B`, but in my opinion, it is exactly the right construct: The first argument to the function is the object the function is invoked on / a member of.

File: Changelog.md [hunk 14]
```diff
@@ -17,6 +17,7 @@ Bugfixes:
 AST Changes:
  * Support field `documentation` to hold NatSpec comments above each statement.
  * Adds `nameLocation` to declarations to represent the exact location of the symbolic name.
+ * Removed the redundant function type "bytearraypush" - replaced by "arraypush".
```
Comment (bshastry) [inline Changelog.md:21]: Isn't this a bug fix as well?

File: libsolidity/ast/Types.cpp (hunk 13 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp:3087]: I think it's better to be explicit.

File: test/libsolidity/semanticTests/array/pop/parenthesized.sol (hunk 8 above)
Comment (chriseth) [reply test/libsolidity/semanticTests/array/pop/parenthesized.sol:5]: It does not work for `.push` because it is overloaded

File: Changelog.md (hunk 14 above)
Comment (chriseth) [reply Changelog.md:21]: It is a rather obscure bug, but if you want, I can add an entry.

File: libsolidity/ast/Types.cpp (hunk 13 above)
Comment (hrkrshnn) [reply libsolidity/ast/Types.cpp:3087]: Okay. I found it a bit confusing, since the actual member is added in line 3100. This assignment makes it seem that `slots` is `{}` for push and pop. I'm fine with keeping this.

**Review by hrkrshnn — APPROVED** [review]

**Review by mijovic — APPROVED** [review]

File: libsolidity/ast/Types.cpp (hunk 11 above)
Comment (hrkrshnn) [reply libsolidity/ast/Types.cpp:1820]: This still remains. But only a cosmetic fix.

File: Changelog.md (hunk 14 above)
Comment (bshastry) [reply Changelog.md:21]: I am fine without but just wanted to bring it up in case it has been overlooked.
