### PR TITLE
[SMTChecker] Support all type casts

### LINKED ISSUE #5795: [SMTChecker] Support typecast fully (truncation + padding)

### LINKED ISSUE #9789: [SMTChecker] Support type conversion of literals (i.e. address(0))
Type conversions are not fully implemented and it may take a while until they are fully supported, but the above special case is so common and it should be easy to support, I'd suggest we make an exception here.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/9789
Fixes https://github.com/ethereum/solidity/issues/5795
Replaces https://github.com/ethereum/solidity/pull/9808

The implementation is a bit verbose but it's clear and explicit in the typecast behavior.
It will be simplified a lot in 0.8.0 when oversized/not fitting casts are disallowed.

Missing:
- [x] FixedBytes downcast

### CODE REVIEW

**Comment by leonardoalt** [comment]
This is ready for review.

File: libsolidity/formal/SymbolicTypes.cpp [hunk 1]
```diff
@@ -458,6 +494,30 @@ smtutil::Expression zeroValue(frontend::TypePointer const& _type)
 	return 0;
 }
 
+bool isSigned(TypePointer const& _type)
```
Comment (mijovic) [inline libsolidity/formal/SymbolicTypes.cpp:497]: Can this be somehow moved to `Type`, at least as a static method?

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:497]: I'm not sure the semantics align. Solidity moved away from considering `address/contract` the same as numbers, but the SMTChecker still does consider that. For me it'd be no problem moving it there, but I'd like to get other opinions. @chriseth?

Comment (chriseth) [reply libsolidity/formal/SymbolicTypes.cpp:497]: I would be fine with the folloing:
Call `_type->mobileType()` here. After that, everything except InteregType and FixedPointType should return false.
Then introduce `ArithmeticType` as base class of those two and add a `isSigned()` function there.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:497]: The semantics are slightly different though. My function also returns true for negative RationalNumberTypes. But I can also do that separately.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:497]: Also `IntegerType` and `FixedPointType` already have `isSigned`. So I'd rather keep this function here using `mobileType` which already simplifies it a lot.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:497]: Maybe I misunderstood it, but what's the point in calling `mobileType()`? It would actually only simplify one case, `RationalNumberType`. The other cases would still need to be there.

Comment (chriseth) [reply libsolidity/formal/SymbolicTypes.cpp:497]: `mobileType` is defined on all types and for Integer and FixedPointType it just returns `this`.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:497]: Exactly, for all the types in that function except for `RationalNumberType`. So the function wouldn't actually change by using `mobileType`.

Comment (mijovic) [reply libsolidity/formal/SymbolicTypes.cpp:497]: If you introduce ArithmeticType as base type, and implement isSigned there it would simplify this. 
I am fine leaving as is, and implement ArithmeticType in a separate PR.

**Comment by mijovic** [comment]
Please revase and solve conflicts

File: libsolidity/formal/SymbolicTypes.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:497]: That's what I'm not sure of. If `ArithmeticType` is implemented as base for `IntegerType` and `FixedPointType` this function could be simplified to:
```
  bool isSigned(TypePointer const& type)
  {
      auto _type = type->mobileType();
      solAssert(smt::isNumber(*_type), "");
      bool isSigned = false;
    if (auto const* aType = dynamic_cast<ArithmeticType const*>(_type))
          isSigned |= aType->isSigned();
    else if (dynamic_cast<AddressType const*>(_type))
          return false;
    else if (dynamic_cast<ContractType const*>(_type))
          return false;
    else if (dynamic_cast<EnumType const*>(_type))
          return false;
    else if (dynamic_cast<FixedBytesType const*>(_type))
          return false;
    else
          solAssert(false, "");
  
      return isSigned;
  }
```
`RationalNumberType` is handled by `mobileType()`. I still need to take care of the other types, so this function would still be there, and I'm not sure the AST changes would be worth it.

**Comment by leonardoalt** [comment]
Rebased

**Review by mijovic — APPROVED** [review]

File: libsolidity/formal/SymbolicTypes.cpp [hunk 2]
```diff
@@ -458,6 +494,29 @@ smtutil::Expression zeroValue(frontend::TypePointer const& _type)
...
+{
+	solAssert(smt::isNumber(*_type), "");
+	bool isSigned = false;
+	if (auto const* numberType = dynamic_cast<RationalNumberType const*>(_type))
+		isSigned |= numberType->isNegative();
```
Comment (axic) [inline libsolidity/formal/SymbolicTypes.cpp:502]: What was the point of doing this and not just `return numberType->isNegative();`?

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:502]: Not sure, will check and potentially open another PR.
