### PR TITLE
Fix trailing spaces

### LINKED ISSUE #7373: Trailing spaces in JSON output
Came up in https://github.com/ethereum/solidity/pull/7372.

Our JSON AST output (and potentially other json output) has trailing spaces, which required a workaround in our check_style script for the recovery_ast_constructor commandline test and for all ASTJSON tests.

The whitespace is needlessly generated by json-cpp, so we need to postprocess its output.

The task is to adjust ``ASTJsonConverter`` to remove all trailing whitespace generated by json-cpp before printing.
A possible approach would be to change ``ASTJsonConverter::print`` to write to a temporary ``std::stringstream`` first. Then the contents of that can be read back line by line, stripped of whitespace and written to the desired ``std::ostream``.

### PR DESCRIPTION
**Pull request by chriseth**
Clone of https://github.com/ethereum/solidity/pull/7507 to develop.

Closes #7373

### CODE REVIEW

**Review by erak — APPROVED** [review]

File: libsolidity/ast/ASTJsonConverter.cpp [hunk 1]
```diff
@@ -189,7 +190,7 @@ Json::Value ASTJsonConverter::inlineAssemblyIdentifierToJson(pair<yul::Identifie
 
 void ASTJsonConverter::print(ostream& _stream, ASTNode const& _node)
 {
-	_stream << toJson(_node);
+	_stream << jsonPrettyPrint(toJson(_node));
```
Comment (axic) [inline libsolidity/ast/ASTJsonConverter.cpp:193]: A bit late but why is this `PrettyPrint` and not `CompactPrint`?
