### PR TITLE
[Sol -> Yul] Fix ForLoops and implement WhileLoops

### LINKED ISSUE #6691: [Sol -> Yul] Implement while statement

### PR DESCRIPTION
**Pull request by Marenz**
Fixes #6691

### CODE REVIEW

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -150,28 +150,63 @@ bool IRGeneratorForStatements::visit(TupleExpression const& _tuple)
...
+		_forStatement.condition(),
+		&_forStatement.body()
+	);
+	return false;
+}
+
+void IRGeneratorForStatements::generateLoop(
+	Statement const*  _initExpression,
+	ExpressionStatement const* _loopExpression,
+	Expression const* _conditionExpression,
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Condition and body can be references because they should never be null.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 2]
```diff
@@ -150,28 +150,63 @@ bool IRGeneratorForStatements::visit(TupleExpression const& _tuple)
...
+	generateLoop(
+		_forStatement.initializationExpression(),
+		_forStatement.loopExpression(),
+		_forStatement.condition(),
+		&_forStatement.body()
+	);
+	return false;
+}
+
+void IRGeneratorForStatements::generateLoop(
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Please use the same order of functions in the cpp file as in the header.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 3]
```diff
@@ -150,28 +150,63 @@ bool IRGeneratorForStatements::visit(TupleExpression const& _tuple)
...
 	m_code << "} return_flag {\n";
-	if (_for.loopExpression())
-		_for.loopExpression()->accept(*this);
+	if (_loopExpression)
+		_loopExpression->accept(*this);
 	m_code << "}\n";
-	if (_for.condition())
+	m_code << "{\n";
+
+	if (_isDoWhile)
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I think this might have the same problem as Solidity's initial implementation of do-while loops: `continue` should jump to the condition, and not to the next execution of the while loop.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 1 above)
Comment (Marenz) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Hmm for this, the condition is null though
```
        for(;;) {}
```

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Ah right!

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 3 above)
Comment (Marenz) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: True. I added a test to check for this and rewrote the logic

**Comment by Marenz** [comment]
fixed order in cpp
changed logic for doWhile

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 4]
```diff
@@ -503,6 +504,53 @@ void IRGeneratorForStatements::setLValue(Expression const& _expression, unique_p
...
+	Statement const& _body,
+	Expression const* _conditionExpression,
+	Statement const*  _initExpression,
+	ExpressionStatement const* _loopExpression,
+	bool _isDoWhile
+)
+{
+	string first_run;
+
+	if (_isDoWhile && _conditionExpression)
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I think you can assert `_conditionExpression` if `_isDoWhile`.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 5]
```diff
@@ -503,6 +504,53 @@ void IRGeneratorForStatements::setLValue(Expression const& _expression, unique_p
...
+	{
+		first_run = m_context.newYulVariable();
+		m_code << "let " << first_run << " := 1\n";
+	}
+
+	m_code << "for {\n";
+	if (_initExpression)
+		_initExpression->accept(*this);
+	m_code << "} return_flag {\n";
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:820]: I'm wondering whether we could just use 1 here...

**Comment by chriseth** [comment]
Please squash!

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 5 above)
Comment (leonardoalt) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: It looks like it, since `return_flag` is not modified

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 6]
```diff
@@ -503,6 +504,53 @@ void IRGeneratorForStatements::setLValue(Expression const& _expression, unique_p
...
 
+void IRGeneratorForStatements::generateLoop(
+	Statement const& _body,
+	Expression const* _conditionExpression,
+	Statement const*  _initExpression,
+	ExpressionStatement const* _loopExpression,
+	bool _isDoWhile
+)
+{
+	string first_run;
```
Comment (leonardoalt) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]:
```suggestion
	string firstRun;
```

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 5 above)
Comment (leonardoalt) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:820]: What about early returns?

**Comment by Marenz** [comment]
renamed `first_run` -> `firstRun`
asserting for conditionalExpression with doWhile
squashed

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 5 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:820]: They will always use an explicit `break`

**Review by chriseth — APPROVED** [review]
