### PR TITLE
Fix internal compiler error for arrays of recursive structs.

### LINKED ISSUE #7448: Internal Compiler Error with fixed size array of recursive struct
## Description

Below I describe a fully reproducible internal compiler error in solidity version 0.5.11. This bug looks like a regression since I can't recreate it using 0.5.10.

Compiling the test file below leads to:

```
Internal compiler error during compilation:
/tmp/solidity-20190917-49278-19sfpot/solidity_0.5.11/libsolidity/ast/Types.cpp(2053): Throw in function virtual bool dev::solidity::StructType::isDynamicallyEncoded() const
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what:
[dev::tag_comment*] =
```

In order to verify its reproducibility, I checked that the below code also leads to an InternalCompilerError in remix.

## Environment

- Compiler version: 0.5.11+commit.22be8592.Darwin.appleclang
- Target EVM version (as per compiler settings): 0.5.11
- Framework/IDE (e.g. Truffle or Remix): None (solc command line directly)
- EVM execution environment / backend / blockchain client: N/A (internal compiler error)
- Operating system: Mac

## Steps to Reproduce

Just run with `solc Test.sol`

```solidity
pragma solidity 0.5.11;


contract Test {
    struct RecursiveStruct {
        RecursiveStruct[] vals;
    }

    function func() private pure {
        RecursiveStruct[1] memory  val;  
    }
}
```

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #7448

### CODE REVIEW

**Review by chriseth — DISMISSED** [review]

**Review by chriseth — APPROVED** [review]

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -2050,6 +2050,8 @@ unsigned StructType::calldataOffsetOfMember(std::string const& _member) const
 
 bool StructType::isDynamicallyEncoded() const
 {
+	if (recursive())
+		return true;
```
Comment (Marenz) [inline libsolidity/ast/Types.cpp:2054]: A lovely easy fix :)

Comment (ekpyron) [reply libsolidity/ast/Types.cpp:2054]: Well, but not the best one and not a permanent one given https://github.com/ethereum/solidity/issues/7498 ;-).
