### PR TITLE
 Check base contracts for abi encoder compatibility

### LINKED ISSUE #5659: UnimplementedFeatureError when using public structs with ABIEncoderV2 and derived contracts
I upgraded from 0.4.25 to 0.5 and run into a new UnimplementedFeatureError:

> Unimplemented feature:
> /solidity/libsolidity/codegen/CompilerUtils.cpp(347): Throw in function void dev::solidity::CompilerUtils::encodeToMemory(const TypePointers&, const TypePointers&, bool, bool, bool)
> Dynamic exception type: boost::exception_detail::clone_impl<langutil::UnimplementedFeatureError>
> std::exception::what: Encoding type "struct Test.TestStruct memory" not yet implemented.
> [dev::tag_comment*] = Encoding type "struct Test.TestStruct memory" not yet implemented.

This issue can be resolved by adding "pragma experimental ABIEncoderV2" to all derived contracts. 
Minimal Example:

```
--- test1.sol
// pragma solidity 0.4.25;
pragma solidity 0.5.1;

pragma experimental ABIEncoderV2;

contract Test {
    struct TestStruct 
    {
        uint a;
    }

    // Compiles fine in 0.4.25, 
    // 0.5.1 makes all derived contracts fail, unless ABIEncoderV2 is in every one of them
    // Making this non-public makes it pass in 0.5.1

    function giveMe() public returns(TestStruct memory){
    }
} 
```
```
--- test-derived.sol
// pragma solidity 0.4.25;
pragma solidity 0.5.1;

// pragma experimental ABIEncoderV2;
// ^ Compiles fine without this line in 0.4.25 
//   Fails in 0.5.1

import "./test1.sol";
contract TestDerived is Test {

}
```
```
--- test-derived2.sol
// pragma solidity 0.4.25;
pragma solidity 0.5.1;

// pragma experimental ABIEncoderV2;
// ^ Compiles fine without this line in 0.4.25 
//   Fails in 0.5.1

import "./test-derived.sol";


contract TestDerived2 is TestDerived {

}
```

Trying to compile any of the derived contracts, yields the error in 0.5.1. Adding the extra ABIEncoderV2 lines to all derived contracts makes it compile again.

### PR DESCRIPTION
**Pull request by Marenz**
Fixes #5659

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -94,6 +94,63 @@ bool TypeChecker::visit(ContractDefinition const& _contract)
 	for (auto const& n: _contract.subNodes())
 		n->accept(*this);
 
+	// Check base contracts for abi encoder compatibility
+	if (!_contract.sourceUnit().annotation().experimentalFeatures.count(ExperimentalFeature::ABIEncoderV2))
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: I think this can (and perhaps should) move to `ContractLevelChecker`.

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -94,6 +94,63 @@ bool TypeChecker::visit(ContractDefinition const& _contract)
...
+		for (auto const& base: _contract.annotation().linearizedBaseContracts)
+		{
+			SecondarySourceLocation errors;
+
+			if (base == &_contract)
+				continue;
+
+			solAssert(base, "Base contract not available.");
+
+			if (base->sourceUnit().annotation().experimentalFeatures.count(ExperimentalFeature::ABIEncoderV2))
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Can you use `continue` for the negated case and thus reduce the nesting here?

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -94,6 +94,63 @@ bool TypeChecker::visit(ContractDefinition const& _contract)
...
+			{
+				for (auto const& func: base->definedFunctions())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Can you just loop once over `_contract.interfaceFunctionList()`? This would reduce code duplication and would also not require looping over the bases.

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: You can still get the secondary source location using `f->declaration()`.

File: test/libsolidity/Imports.cpp [hunk 4]
```diff
@@ -320,6 +320,154 @@ BOOST_AUTO_TEST_CASE(shadowing_builtins_with_alias)
...
+	pragma solidity >=0.0;
+	pragma experimental ABIEncoderV2;
+
+	contract A
+	{
+		struct S { uint a; }
+		S public s;
+		function f(S memory _s) returns (S memory,S memory) { }
+	}
+)");
```
Comment (chriseth) [inline test/libsolidity/Imports.cpp]: Should be indented once (and everything above up to, but not including `c.addSource`).

File: libsolidity/analysis/TypeChecker.cpp [hunk 5]
```diff
@@ -94,6 +94,63 @@ bool TypeChecker::visit(ContractDefinition const& _contract)
...
+			}
+
+			if (!errors.infos.empty())
+			{
+				m_errorReporter.typeError(
+					_contract.location(),
+					errors,
+					std::string("Contract \"") +
+					_contract.name()
+					+ "\" doesn't use the new experimental ABI encoder but wants to inherit from contract \"" +
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
					+ "\" does not use the new experimental ABI encoder but wants to inherit from contract \"" +
```

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `409ae425d5c0cc3408c16153a59f5717456e7d1b`:
```
Coding style error:
 libsolidity/analysis/ContractLevelChecker.cpp:484: )

```
Please check that your changes are working as intended.

**Comment by Marenz** [comment]
Ready for review

File: liblangutil/ErrorReporter.cpp [hunk 6]
```diff
@@ -207,6 +213,14 @@ void ErrorReporter::typeError(SourceLocation const& _location, string const& _de
 	);
 }
 
+void ErrorReporter::fatalTypeError(SourceLocation const& _location, SecondarySourceLocation const& _secondaryLocation, string const& _description)
+{
+	fatalError(Error::Type::TypeError,
```
Comment (chriseth) [inline liblangutil/ErrorReporter.cpp]:
```suggestion
	fatalError(
    	Error::Type::TypeError,
```

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 7]
```diff
@@ -460,3 +462,55 @@ void ContractLevelChecker::checkLibraryRequirements(ContractDefinition const& _c
...
+		solAssert(func.second->hasDeclaration(), "Function has no declaration?!");
+
+		if (!func.second->declaration().sourceUnit().annotation().experimentalFeatures.count(ExperimentalFeature::ABIEncoderV2))
+			continue;
+
+		bool nextFunction = false;
+
+		auto const& currentLoc = func.second->declaration().location();
+
+		for (auto const& paramType: func.second->parameterTypes())
```
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]: Please use an explicit type. I would like to know if it is a shared pointer or not.

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 8]
```diff
@@ -460,3 +462,55 @@ void ContractLevelChecker::checkLibraryRequirements(ContractDefinition const& _c
...
+			if (!typeSupportedByOldABIEncoder(*paramType, false))
```
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]: Please assert that this is not a library.

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 7 above)
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]:
```suggestion
		for (auto const& paramType: func.second->parameterTypes() + func.second->returnParameterTypes())
```

Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp]: (this allows you to get rid of the second loop and the `nextFunction` flag)

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 9]
```diff
@@ -460,3 +462,55 @@ void ContractLevelChecker::checkLibraryRequirements(ContractDefinition const& _c
...
+		for (auto const& paramType: func.second->returnParameterTypes())
+			if (!typeSupportedByOldABIEncoder(*paramType, false))
+			{
+				errors.append("Return parameter type only supported by the new experimental ABI encoder", currentLoc);
+				break;
+			}
+	}
+
+	if (!errors.infos.empty())
+	{
```
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]:
```suggestion
```

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 10]
```diff
@@ -460,3 +462,55 @@ void ContractLevelChecker::checkLibraryRequirements(ContractDefinition const& _c
...
+		m_errorReporter.fatalTypeError(
+			_contract.location(),
+			errors,
+			std::string("Contract \"") +
+			_contract.name()
```
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]:
```suggestion
			_contract.name() +
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 11]
```diff
@@ -45,9 +45,10 @@ using namespace dev;
 using namespace langutil;
 using namespace dev::solidity;
 
-namespace
+namespace dev
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: We usually don't use scoping namespaces in cpp files

File: libsolidity/analysis/TypeChecker.h [hunk 12]
```diff
@@ -39,6 +39,8 @@ namespace dev
 namespace solidity
 {
 
+bool typeSupportedByOldABIEncoder(Type const& _type, bool _isLibraryCall);
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.h]: Perhaps make this a static function in the TypeChecker?

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 8 above)
Comment (Marenz) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Can't you inherit from a library?

File: libsolidity/analysis/TypeChecker.cpp (hunk 11 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: It wouldn't compile otherwise, something about ambiguous call/definition. Using static will resolve this though.

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 8 above)
Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp]: No - but we might change that in the future. The reason I would like the assert is because you are using `false` here, which means "not a library function" and this should be asserted.

Comment (Marenz) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Should I assert all base contracts or just the current one?

Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp]: I guess the current one is fine.

Comment (Marenz) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Hmm the assert fails. While there is already an error added for when it is a library, it is not a fatal error, so execution continues. I could add the condition that errors must be added, too?

Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Perhaps check that there are at least two contracts in the linearized base class list?

**Comment by Marenz** [comment]
Updated

File: liblangutil/ErrorReporter.h [hunk 13]
```diff
@@ -107,6 +108,11 @@ class ErrorReporter
 		SecondarySourceLocation const& _secondaryLocation,
 		std::string const& _description = std::string());
 
+	void fatalError(Error::Type _type,
```
Comment (chriseth) [inline liblangutil/ErrorReporter.h]: wrong indentation / newlines.

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 14]
```diff
@@ -460,3 +462,50 @@ void ContractLevelChecker::checkLibraryRequirements(ContractDefinition const& _c
...
+
+		if (!func.second->declaration().sourceUnit().annotation().experimentalFeatures.count(ExperimentalFeature::ABIEncoderV2))
+			continue;
+
+		auto const& currentLoc = func.second->declaration().location();
+
+		for (TypePointer const& paramType: func.second->parameterTypes() + func.second->parameterTypes())
+			if (!TypeChecker::typeSupportedByOldABIEncoder(*paramType, false))
+			{
+				errors.append("Type only supported by the new experimental ABI encoder", currentLoc);
```
Comment (axic) [inline libsolidity/analysis/ContractLevelChecker.cpp:495]: I think this should use `m_errorReporter.typeError`.

Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp:495]: The code first fills all the secondary locations (`errors` is just secondary locations).

File: liblangutil/ErrorReporter.h (hunk 13 above)
Comment (Marenz) [reply liblangutil/ErrorReporter.h]: I used the same style as the functions above and below this one. 
I'll fix those as well then.

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 14 above)
Comment (Marenz) [reply libsolidity/analysis/ContractLevelChecker.cpp:495]: Indeed. And after the loop it does one single `typeError` for all found

**Comment by Marenz** [comment]
Updated: Fixed indent errors

File: test/libsolidity/Imports.cpp [hunk 15]
```diff
@@ -320,6 +320,153 @@ BOOST_AUTO_TEST_CASE(shadowing_builtins_with_alias)
 	}
 }
 
+BOOST_AUTO_TEST_CASE(inheritance_abi_encoder_mismatch_1)
```
Comment (leonardoalt) [inline test/libsolidity/Imports.cpp:323]: Can't these be syntax tests?

Comment (chriseth) [reply test/libsolidity/Imports.cpp:323]: syntax tests do not support includes.

**Review by chriseth — CHANGES_REQUESTED** [review]
Please squash the last commit and add a changelog entry.

**Comment by Marenz** [comment]
why squash? It is a change to code that was not added by this PR.

**Comment by chriseth** [comment]
Ah sorry, didn't notice that. But please add a changelog entry.

**Comment by Marenz** [comment]
Added change log

**Review by chriseth — APPROVED** [review]
