### PR TITLE
Code generators needed fixing of the cleanup process during typecasting of bytes and integers

### LINKED ISSUE #12535: [Logging] Indexed log topic differs between legacy and IR if explicitly downcast
```
contract C {
  event ev0(bytes1 indexed);
  constructor() {
    emit ev0(bytes1(bytes16(0x31313131313131313131313131313131)));
  }
}
// ====
// compileViaYul: also
// ----
// constructor() ->
// ~ emit ev0(bytes1): #"1"
```

Legacy truncates indexed log topic, while IR leaves it untruncated. This would lead to a divergence of blockchain state depending on which backend is used.

To reproduce

```
$ cp test.sol test/libsolidity/semanticTests
$ isoltest -t semanticTests/test
  Running via Yul:
  Expected result:
  // constructor() ->
  // ~ emit ev0(bytes1): #"1"

  Obtained result:
  // constructor() ->
  // ~ emit ev0(bytes1): #"1111111111111111"
  
  Attention: Updates on the test will apply the detected format displayed.
  
  Note that the test passed without Yul. 
```

Note that the divergence is maintained with/without optimizer so I would guess this may be a bug related to truncation (or lack thereof) in Sol->Yul.

### PR DESCRIPTION
**Pull request by nishant-sachdeva**
Refactored the conversion and Cleanup Steps of the New Code Generators for the emit functionality

Closes #12535

### CODE REVIEW

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -2727,28 +2727,41 @@ void IRGeneratorForStatements::assignInternalFunctionIDIfNotCalledDirectly(
...
+IRVariable IRGeneratorForStatements::convert(IRVariable const& _from, Type const& _to)
 {
-	if (_from.type() == _to && !_forceCleanup)
+	if (_from.type() == _to)
 		return _from;
 	else
 	{
 		IRVariable converted(m_context.newYulVariable(), _to);
+		bool _forceCleanup = true;
 		define(converted, _from, _forceCleanup);
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Maybe we can also have `defineAndClean`?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 2]
```diff
@@ -2727,28 +2727,41 @@ void IRGeneratorForStatements::assignInternalFunctionIDIfNotCalledDirectly(
...
+		return m_utils.conversionFunction(from.type(), _to) + "(" + from.commaSeparatedList() + ")";
+}
+
+std::string IRGeneratorForStatements::expressionAsCleanedType(Expression const& _expression, Type const& _to)
+{
+	IRVariable from(_expression);
+	if (from.type() == _to)
+		return m_utils.cleanupFunction(_to) + "(" + from.commaSeparatedList() + ")";
 	else
 		return m_utils.conversionFunction(from.type(), _to) + "(" + from.commaSeparatedList() + ")";
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: It would be nice if we could re-use `expressionAsType` in this function.
Maybe
```suggestion
	IRVariable from(_expression);
	if (from.type() == _to)
		return m_utils.cleanupFunction(_to) + "(" + expressionAsType(_expression, _to) + ")";
	else
		return expressionAsType(_expression, _to) ;
```

File: libsolidity/codegen/ir/IRGeneratorForStatements.h [hunk 3]
```diff
@@ -86,10 +86,19 @@ class IRGeneratorForStatements: public IRGeneratorForStatementsBase
...
+		declareAssign(_var, _value, _declare);
+	}
+
+	/// Defines @a _var using the value of @a _value while performing type conversions, if required.
+	/// It also cleans the value of the variable after the conversion.
+	void defineAndCleanup(IRVariable const& _var, IRVariable const& _value)
+	{
+		bool _forceCleanup = true;
+		bool _declare = true;
+		declareAssign(_var, _value, _declare, _forceCleanup);
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.h:101]: As far as I'm concerned we could also have kept these inlined here, but declaring the variables doesn't hurt I guess.

File: libsolidity/codegen/ir/IRGeneratorForStatements.h [hunk 4]
```diff
@@ -86,10 +86,19 @@ class IRGeneratorForStatements: public IRGeneratorForStatementsBase
...
-	void define(IRVariable const& _var, IRVariable const& _value, bool _forceCleanup = false)
+	void define(IRVariable const& _var, IRVariable const& _value)
 	{
-		declareAssign(_var, _value, true, _forceCleanup);
+		bool _declare = true;
+		declareAssign(_var, _value, _declare);
+	}
+
+	/// Defines @a _var using the value of @a _value while performing type conversions, if required.
+	/// It also cleans the value of the variable after the conversion.
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.h]: Is "cleaning up after the conversion" really what happens here? In a sense it is... but I'd rather say, it performs a cleanup, even if ``@a _var`` and ``@a _value`` have the same type. Similarly for ``convertAndCleanup``

**Review by ekpyron — DISMISSED** [review]
LGTM

**Review by ekpyron — APPROVED** [review]

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Failures are also on develop.
