### PR TITLE
Mark function selectors accessed via declaration as pure.

### LINKED ISSUE #8262: Add mechanism for static/const/immutable selector.
## Abstract
There should be a way to reference a function selector from an interface or contract without having to construct it by hand (error prone/complicated) and such that it can be used in constants.

## Specification
Simplest implementation (from a usability standpoint) would be to allow someone to reference an interface function definition with `.selector` in order to get a constant for the byte4.  Caveat here is that overloads become problematic.

Another option would be to provide a syntax for getting the selector from a string, though this is a bit more error prone I suspect.
```
interface Banana {
    function transfer(address,uint256) external returns(bool);
}

contract Apple {
    // simplest UX
    bytes4 constant bananaTransfer1 = Banana.transfer.selector;

    // a bit more complicated to write, but deals with overloads
    bytes4 constant bananaTransfer2 = Banana.transfer(address,uint256).selector;

    // if transfer signature changes on Banana, this will be incorrect with no compiler error
    bytes4 constant bananaTransfer3 = selector(transfer(address,uint256));
}
```

## Backwards Compatibility
The last option would introduce a new keyword that may be problematic.

### PR DESCRIPTION
**Pull request by ekpyron**
Closes https://github.com/ethereum/solidity/issues/8262

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2535,6 +2535,9 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 	if (auto tt = dynamic_cast<TypeType const*>(exprType))
 		if (tt->actualType()->category() == Type::Category::Enum)
 			annotation.isPure = true;
+	if (auto functionType = dynamic_cast<FunctionType const*>(exprType))
+		if (functionType->kind() == FunctionType::Kind::Declaration && memberName == "selector")
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp]: Actually... which member accesses to ``.selector`` are **not** pure? Can we extend this to more of them?

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: If the expression itself is pure, then all of them should.

**Comment by chriseth** [comment]
One thing you could also fix here is the following:
```
interface Banana {
    function transfer(address,uint256) external returns(bool);
}

contract Apple {
    function f() public {
        Banana.transfer;
    }
}
```

It results in an internal error with "unsupported member function" in ExpressionCompiler.

**Comment by ekpyron** [comment]
Fixed that one as well here. Do you think this needs a changelog entry?

File: test/libsolidity/syntaxTests/types/contractTypeType/members/base_contract.sol [hunk 2]
```diff
@@ -3,9 +3,9 @@ contract B {
     function g() public {}
 }
 contract C is B {
-    function h() public {
-        B.f.selector;
-        B.g.selector;
+    function h() public returns (bytes4 fs, bytes4 gs) {
+        fs = B.f.selector;
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/types/contractTypeType/members/base_contract.sol:7]: FYI: this is to avoid "Statement has no effect" warnings.

**Comment by chriseth** [comment]
Does this close https://github.com/ethereum/solidity/issues/8262 ?

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -2533,8 +2533,15 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 	// TODO some members might be pure, but for example `address(0x123).balance` is not pure
 	// although every subexpression is, so leaving this limited for now.
 	if (auto tt = dynamic_cast<TypeType const*>(exprType))
+	{
 		if (tt->actualType()->category() == Type::Category::Enum)
 			annotation.isPure = true;
+		if (auto const* functionType = dynamic_cast<FunctionType const*>(annotation.type))
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Just looking at the diff here, I cannot easily see the relation between `exprType` and `anntation.type` - can you please clarify that?

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: Actually, is `annotation.type` the resulting type? If possible, please avoid making any conclusions about the behaviour of an expression from the type it will result in.

File: libsolidity/analysis/ViewPureChecker.cpp [hunk 4]
```diff
@@ -317,7 +317,8 @@ bool ViewPureChecker::visit(MemberAccess const& _memberAccess)
 	// Catch the special case of `this.f.selector` which is a pure expression.
 	ASTString const& member = _memberAccess.memberName();
 	if (
-		_memberAccess.expression().annotation().type->category() == Type::Category::Function &&
+		auto const * functionType = dynamic_cast<FunctionType const*>(_memberAccess.expression().annotation().type);
```
Comment (chriseth) [inline libsolidity/analysis/ViewPureChecker.cpp]: style

Comment (chriseth) [reply libsolidity/analysis/ViewPureChecker.cpp]: Actually I think the previous way was easier to understand.

**Comment by ekpyron** [comment]
Yeah... I think this makes more sense now.
I was wondering whether there's any functions accessed via contract name that *shouldn't* be pure, but even base functions should be fine - function calls to them should still derive their pureness from their mutability, which should be fine...

**Review by chriseth — DISMISSED** [review]

File: libsolidity/analysis/TypeChecker.cpp [hunk 5]
```diff
@@ -2533,8 +2533,15 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 	// TODO some members might be pure, but for example `address(0x123).balance` is not pure
 	// although every subexpression is, so leaving this limited for now.
 	if (auto tt = dynamic_cast<TypeType const*>(exprType))
+	{
 		if (tt->actualType()->category() == Type::Category::Enum)
 			annotation.isPure = true;
+		if (tt->actualType()->category() == Type::Category::Contract)
+			if (annotation.type->category() == Type::Category::Function)
+				annotation.isPure = true;
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: I think I could sleep better with
```suggestion
				annotation.isPure = _memberAccess.expression().annotation().isPure;
```

Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp]: Changed it.

**Comment by chriseth** [comment]
It would be great if we could take some time and see if we can use `using x for y` to trick this mechanism. We should also check if something like `super.f` or `C.f` where `f` is a state variable of function type could be used here.

And finally, `f.selector` where `f` is a local variable of function type.

**Comment by ekpyron** [comment]
You're right, state variables in base contracts can in fact sneak around the current mechanism, I'll try to fix.

**Comment by ekpyron** [comment]
I wonder whether this can generally be done in a better way... I think the latest version kind of works, but it still won't allow ``(this).f.selector`` without reason... let alone ``(true ? this : this).f.selector``...

File: test/libsolidity/syntaxTests/types/function_types/selector/local_variable_selector_not_pure.sol [hunk 6]
```diff
@@ -0,0 +1,6 @@
+contract C {
+    function f() public pure returns (bytes4) {
+        function() external g;
+        g.selector;
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/types/function_types/selector/local_variable_selector_not_pure.sol:6]: Note the absence of a ``Statement has no effect`` warning.

File: libsolidity/analysis/TypeChecker.cpp [hunk 7]
```diff
@@ -2527,14 +2527,36 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
...
 		if (tt->actualType()->category() == Type::Category::Enum)
 			annotation.isPure = true;
+	if (
+		auto const* functionType = dynamic_cast<FunctionType const*>(exprType);
+		functionType &&
+		functionType->hasDeclaration() &&
+		dynamic_cast<FunctionDefinition const*>(&functionType->declaration()) &&
+		memberName == "selector"
+	)
+		if (auto const* parentAccess = dynamic_cast<MemberAccess const*>(&_memberAccess.expression()))
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp:2553]: We need to look at the parent member access, since in general the function itself won't be considered pure inside base contracts or ``this``, since it would "contain" the current address - but that doesn't hurt the pureness of the selector...

File: test/libsolidity/syntaxTests/types/function_types/selector/local_variable_selector_not_pure.sol (hunk 6 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/types/function_types/selector/local_variable_selector_not_pure.sol:6]: Can you add a comment?

**Review by chriseth — DISMISSED** [review]

File: test/libsolidity/syntaxTests/types/function_types/selector/local_variable_selector_not_pure.sol (hunk 6 above)
Comment (ekpyron) [reply test/libsolidity/syntaxTests/types/function_types/selector/local_variable_selector_not_pure.sol:6]: Added a comment.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Argh, this is also missing a changelog entry :(

**Comment by ekpyron** [comment]
I'll also add a changelog entry.

**Comment by ekpyron** [comment]
Damn, too late :-).
