### PR TITLE
Natspec: Fix internal error when different return name was inherited

### LINKED ISSUE #9947: Exception for overridden function when return name is different and documented
## Description

If I document the return value of a function and then override and rename the return value an exception occurs.

```solidity 
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.0;

contract A {
    /// @return y value
    function g(int x) public pure virtual returns (int y) { return x; }
}

contract B is A {
    function g(int x) public pure override returns (int z) { return x; }
}
```

```console
$ solc test.sol 
Internal compiler error during compilation:
/Users/dejan/workspace/solidity/libsolidity/interface/Natspec.cpp(187): Throw in function static Json::Value solidity::frontend::Natspec::extractReturnParameterDocs(const std::multimap<std::string, DocTag> &, const solidity::frontend::FunctionDefinition &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: No return param name given: z
[solidity::util::tag_comment*] = No return param name given: z
```

## Environment

- Compiler version: 0.7.2
- Operating system: Mac & Remix

### PR DESCRIPTION
**Pull request by Marenz**
fixes #9947

### CODE REVIEW

File: test/libsolidity/SolidityNatspecJSON.cpp [hunk 1]
```diff
@@ -2022,6 +2023,49 @@ BOOST_AUTO_TEST_CASE(dev_explicit_inehrit_complex)
...
+	})ABCDEF";
+
+	char const *natspec2 = R"ABCDEF({
+		"methods":
+		{
+			"g(int256)":
+			{
+				"returns":
+				{
+					"_0": "y value"
```
Comment (hrkrshnn) [inline test/libsolidity/SolidityNatspecJSON.cpp]: Is this how we want to do it? Maybe we shouldn't inherit the `returns` tag in such cases. If we do, then it would make sense to replace "y" by the name of the current return value.

File: libsolidity/interface/Natspec.cpp [hunk 2]
```diff
@@ -178,12 +178,15 @@ Json::Value Natspec::extractReturnParameterDocs(std::multimap<std::string, DocTa
 			string paramName = _functionDef.returnParameters().at(n)->name();
 			string content = i->second.content;
 
-			if (paramName.empty())
+			auto nameEndPos = content.find_first_of(" \t");
```
Comment (hrkrshnn) [inline libsolidity/interface/Natspec.cpp]: Question: can you give an example of the string content?

Comment (Marenz) [reply libsolidity/interface/Natspec.cpp]: the content could be `y value`, basically the part after `@return ` and it has to start with the name of the parameter

File: test/libsolidity/SolidityNatspecJSON.cpp (hunk 1 above)
Comment (Marenz) [reply test/libsolidity/SolidityNatspecJSON.cpp]: well, that would be the default behavior if there is no name given, it made sense to me to default to that if there is a conflict in the parameter names..
Replacing was also an idea I had, but that's not as easy as it maybe sounds with how the code is currently structured.

Comment (Marenz) [reply test/libsolidity/SolidityNatspecJSON.cpp]: Oh, I see what you mean. Maybe a better alternative would be to complete skip it then.

Comment (hrkrshnn) [reply test/libsolidity/SolidityNatspecJSON.cpp]: > Replacing was also an idea I had, but that's not as easy as it maybe sounds with how the code is currently structured.

I agree. The current Natspec code needs an overhaul.

Comment (chriseth) [reply test/libsolidity/SolidityNatspecJSON.cpp]: I think this line should say
```suggestion
					"z": "value"
```

**Comment by chriseth** [comment]
Can you check if we have the same problem with parameters?

File: test/libsolidity/SolidityNatspecJSON.cpp (hunk 1 above)
Comment (Marenz) [reply test/libsolidity/SolidityNatspecJSON.cpp]: If we only have one parameter, correcting it can be done, but if we have several, how should we proceed? Use the order of the parameters to see which one should be which? Skip the whole thing?

Comment (chriseth) [reply test/libsolidity/SolidityNatspecJSON.cpp]: There should be a proper correspondence between the parameters, isn't there?

Comment (Marenz) [reply test/libsolidity/SolidityNatspecJSON.cpp]: if we use the order, yes..

**Comment by Marenz** [comment]
> Can you check if we have the same problem with parameters?

I checked and they don't have the same problem

**Comment by Marenz** [comment]
For normal parameters it seems they are only inherited if they match exactly.

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 3]
```diff
@@ -48,9 +48,37 @@ void copyMissingTags(StructurallyDocumentedAnnotation& _target, set<CallableDecl
 	for (auto const& iterator: _target.docTags)
 		existingTags.insert(iterator.first);
 
-	for (auto const& [tag, content]: sourceDoc.docTags)
-		if (tag != "inheritdoc" && !existingTags.count(tag))
-			_target.docTags.emplace(tag, content);
```
Comment (hrkrshnn) [inline libsolidity/analysis/DocStringAnalyser.cpp:53]: Do you think it's possible to just do a regex_replace on the content here?

Also not sure why a multimap was chosen for this. Probably a vector of tags would be a better choice here. Tag can be a variant of structs notice, dev, param and return. The return struct can be strings name and description. The number of tags is very small (<20, probably like 5 in actual contracts). Do you think it's worth changing this now?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 4]
```diff
@@ -36,7 +36,7 @@ using namespace solidity::frontend;
 namespace
 {
 
-void copyMissingTags(StructurallyDocumentedAnnotation& _target, set<CallableDeclaration const*> const& _baseFunctions)
+void copyMissingTags(set<CallableDeclaration const*> const& _baseFunctions, StructurallyDocumentedAnnotation& _target, CallableDeclaration const* _callable = nullptr)
```
Comment (hrkrshnn) [inline libsolidity/analysis/DocStringAnalyser.cpp]: Would it make sense to change the first argument from a set to just `CallableDeclaration const* _baseFunction`?

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 3 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:53]: Tags can exist multiple times, like several `@param` tags and such. That's why it's a multimap. If we do such a change I would do it in another PR and not here.. generally I am not opposed to a restructuring of the tags.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 4 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp]: From the perspective of the function yes. From the perspective of the caller no, because in 50% of calls I have that parameter only as `set` and would need to do the size check before the call. This way I do the size check only once in the function.

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 5]
```diff
@@ -48,9 +48,37 @@ void copyMissingTags(StructurallyDocumentedAnnotation& _target, set<CallableDecl
...
+				if (docParameterName != _callable->returnParameters().at(n)->name())
+				{
+					bool baseHasNoName = (*_baseFunctions.begin())->returnParameters().at(n)->name().empty();
+					newContent.content =
+						_callable->returnParameters().at(n)->name() + (
+							string::npos == docParaNameEndPos || baseHasNoName ?
+							" " + newContent.content :
+							newContent.content.substr(docParaNameEndPos)
+						);
+				}
```
Comment (hrkrshnn) [inline libsolidity/analysis/DocStringAnalyser.cpp]: Maybe we can replace this by

```cpp
regex_replace(
     it->second.content,
     regex{"[^\\s\\t]"},
     _callable->returnParameters().at(n)->name(),
     regex_constants::format_first_only
)
```

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 4 above)
Comment (hrkrshnn) [reply libsolidity/analysis/DocStringAnalyser.cpp]: True. So maybe not worth the change.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 3 above)
Comment (hrkrshnn) [reply libsolidity/analysis/DocStringAnalyser.cpp:53]: I'll link https://github.com/ethereum/solidity/issues/8247 for future reference.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 5 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp]: Hmm generally I try to avoid the complexity of regex when I don't really need it.

File: test/libsolidity/smtCheckerTests/operators/slice_default_end.sol [hunk 6]
```diff
@@ -8,13 +8,12 @@ contract C {
 		assert(bytes(b[10:]).length == 20);
 		assert(bytes(b[10:])[0] == 0xff);
 		assert(bytes(b[10:])[5] == 0xff);
-		assert(bytes(b[10:])[19] == 0xaa);
+		// Removed because of Spacer nondeterminism
+//		assert(bytes(b[10:])[19] == 0xaa);
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/operators/slice_default_end.sol]: Can you change this to
```suggestion
		//assert(bytes(b[10:])[19] == 0xaa);
```
I grep for `//assert` to find which ones I should try again when there's a new version

Comment (Marenz) [reply test/libsolidity/smtCheckerTests/operators/slice_default_end.sol]: Done

**Comment by axic** [comment]
What is blocking this?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 7]
```diff
@@ -48,9 +48,37 @@ void copyMissingTags(StructurallyDocumentedAnnotation& _target, set<CallableDecl
 	for (auto const& iterator: _target.docTags)
 		existingTags.insert(iterator.first);
 
-	for (auto const& [tag, content]: sourceDoc.docTags)
-		if (tag != "inheritdoc" && !existingTags.count(tag))
-			_target.docTags.emplace(tag, content);
+	for (auto it = sourceDoc.docTags.begin(); it != sourceDoc.docTags.end();)
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:47]: Please either add a comment to explain what this does or extract it into a function which is then self-explanatory through its name.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 4 above)
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp]: Can you find a better name than `_callable`?

File: test/libsolidity/SolidityNatspecJSON.cpp [hunk 8]
```diff
@@ -2022,6 +2023,187 @@ BOOST_AUTO_TEST_CASE(dev_explicit_inehrit_complex)
...
+{
+	char const *sourceCode = R"(
+		contract A {
+			/// @return value A
+			/// @return b value B
+			function g(int x) public pure virtual returns (int, int b) { return (1, 2); }
+		}
+
+		contract B is A {
+			function g(int x) public pure override returns (int z, int y) { return (1, 2); }
```
Comment (chriseth) [inline test/libsolidity/SolidityNatspecJSON.cpp]: Can you change this to remove `y`?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 9]
```diff
@@ -36,21 +36,51 @@ using namespace solidity::frontend;
 namespace
 {
 
-void copyMissingTags(StructurallyDocumentedAnnotation& _target, set<CallableDeclaration const*> const& _baseFunctions)
+void copyMissingTags(set<CallableDeclaration const*> const& _baseFunctions, StructurallyDocumentedAnnotation& _target, CallableDeclaration const* _declaration = nullptr)
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:39]: I still don't understand the purpose of the third parameter.

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 10]
```diff
@@ -36,21 +36,51 @@ using namespace solidity::frontend;
...
 {
 	if (_baseFunctions.size() != 1)
 		return;
 
 	auto& sourceDoc = dynamic_cast<StructurallyDocumentedAnnotation const&>((*_baseFunctions.begin())->annotation());
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:45]: Are you only using the first element of a pointer-based set? Can this cause nondeterminism?

**Review by chriseth — COMMENTED** [review]
I'm sorry, but I have a hard time reviewing this. Is it possible to do this without the use of iterators (or at least without using such descriptive names as `it->first` and `it->second`? :) )

Also, where did `existingTags` go or why is it not needed anymore?

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 10 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:45]: I am, but it's a set of the size() == 1 as you can see in line 41. 
I am mainly passing a set to avoid at least 4 lines of casting and extracting `_baseFunctions.begin()` before calling the function. I figured I need to do that several times, I might as well do it in the function.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 7 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:47]: it's used to get information about the return parameters and their names so they can be adjusted when copied in case of functions.

**Comment by Marenz** [comment]
`existingTags` was no longer needed when I changed to use iterators with the `upper_bound()` function.

Before we had one loop over a multimap. `return` tags for example could have multiple values. `existingTags` was there to make sure we don't copy the already existing ones and we couldn't just check the target map if the tag already exists because due to the multi map we need to add the same tag with different values (e.g. multiple `return`s)

I rewrote it a bit to not use `it->first` and `it->second` much.. I could rewrite it without iterators I suppose but then I'd need to use `equal_range()` at the very least and it will also be not be much easier I fear..

File: libsolidity/ast/ASTAnnotations.h [hunk 11]
```diff
@@ -66,6 +66,7 @@ struct DocTag
 {
 	std::string content;	///< The text content of the tag.
 	std::string paramName;	///< Only used for @param, stores the parameter name.
+	bool inherited = false; ///< True if this tag was inherited
```
Comment (chriseth) [inline libsolidity/ast/ASTAnnotations.h]: How is this used?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 12]
```diff
@@ -36,21 +36,53 @@ using namespace solidity::frontend;
 namespace
 {
 
-void copyMissingTags(StructurallyDocumentedAnnotation& _target, set<CallableDeclaration const*> const& _baseFunctions)
+void copyMissingTags(set<CallableDeclaration const*> const& _baseFunctions, StructurallyDocumentedAnnotation& _target, CallableDeclaration const* _declaration = nullptr)
 {
 	if (_baseFunctions.size() != 1)
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:42]: Please add a comment: Only copy if there is exactly one direct base function.

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 13]
```diff
@@ -36,21 +36,53 @@ using namespace solidity::frontend;
...
+
+		size_t n = 0;
+		// Iterate over all values of the current tag (it's a multimap)
+		for (auto next = sourceDoc.docTags.upper_bound(tag); it != next; it++, n++)
+		{
+			DocTag const& content = it->second;
+			DocTag newContent = content;
+			newContent.inherited = true;
+
+			// Update the parameter name for @return tags
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:63]: What about `@param`?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 14]
```diff
@@ -36,21 +36,53 @@ using namespace solidity::frontend;
...
+			{
+				size_t docParaNameEndPos = content.content.find_first_of(" \t");
+				string const docParameterName = content.content.substr(0, docParaNameEndPos);
+
+				if (docParameterName != _declaration->returnParameters().at(n)->name())
+				{
+					bool baseHasNoName = (*_baseFunctions.begin())->returnParameters().at(n)->name().empty();
+					string const paramName = _declaration->returnParameters().at(n)->name();
+					newContent.content =
+						(paramName.empty() ? "" : std::move(paramName) + " ") + (
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:74]: moving from a const string?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 15]
```diff
@@ -36,21 +36,53 @@ using namespace solidity::frontend;
...
+							string::npos == docParaNameEndPos || baseHasNoName ?
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp:75]: What if we have `@returns x` (without description)?

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 16]
```diff
@@ -36,21 +36,53 @@ using namespace solidity::frontend;
...
+							newContent.content :
+							newContent.content.substr(docParaNameEndPos+1)
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp]:
```suggestion
							newContent.content.substr(docParaNameEndPos + 1)
```

File: libsolidity/analysis/DocStringAnalyser.cpp [hunk 17]
```diff
@@ -36,21 +36,53 @@ using namespace solidity::frontend;
...
+		{
+			it++;
+			continue;
+		}
+
+		size_t n = 0;
+		// Iterate over all values of the current tag (it's a multimap)
+		for (auto next = sourceDoc.docTags.upper_bound(tag); it != next; it++, n++)
+		{
+			DocTag const& content = it->second;
```
Comment (chriseth) [inline libsolidity/analysis/DocStringAnalyser.cpp]: Do you really still need the old copy?

Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp]: Yes, that's the documentation for the base function

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 13 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:63]: well, this issue was about `@return`. As far as I know, `@param` can't be unnamed so they don't have the same problem.
Of course the name can change and in that case nothing will be inherited.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 15 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:75]: in that case it is assumed that `x` is the description and the position is used to identify which return parameter it is referring to.

Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:75]: in terms of code, `returns` is not part of `content`, so the `docParaNameEndPos` would be `npos` as it couldn't find any whitespace or `\t`.

Comment (chriseth) [reply libsolidity/analysis/DocStringAnalyser.cpp:75]: Indeed, but then it would not substitute the name even though it should, right?

Comment (Marenz) [reply libsolidity/analysis/DocStringAnalyser.cpp:75]: It wouldn't and I don't think it should either as it isn't detected as "name" but as "description" instead.. either way it wouldn't have much use to have a name without a description OR a description that is just the name...

File: libsolidity/ast/ASTAnnotations.h (hunk 11 above)
Comment (Marenz) [reply libsolidity/ast/ASTAnnotations.h]: Ah, I think that was from a different attempt and was kept. Will remove.

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 17 above)
Comment (chriseth) [reply libsolidity/analysis/DocStringAnalyser.cpp]: I mean why don't you use `DocTag newContent = content` and replace all mentions of `content` below by `newContent`? (or call everything just `content')

File: libsolidity/analysis/DocStringAnalyser.cpp (hunk 15 above)
Comment (chriseth) [reply libsolidity/analysis/DocStringAnalyser.cpp:75]: Can you add a test for this case?

**Review by chriseth — APPROVED** [review]
