### PR TITLE
Fix revert with reason coming from a string variable

### LINKED ISSUE #4051: InternalCompilerError when using `revert` with constant string variable reason
Repro:
```
pragma solidity ^0.4.23;

contract TestRevert {
    string constant ERR = "Error";
    
    function revertWithErr() public {
        revert(ERR);
    }
}
```

When compiling, I get an error `InternalCompilerError: I sense a disturbance in the stack: 2 vs 1`. When passing in the actual string rather than the variable, everything compiles just fine.

### PR DESCRIPTION
**Pull request by axic**
Fixes #4051.

### CODE REVIEW

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 1]
```diff
@@ -692,6 +692,7 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 				solAssert(function.parameterTypes().size() == 1, "");
 				arguments.front()->accept(*this);
 				utils().revertWithStringData(*arguments.front()->annotation().type);
+				utils().popStackElement(*arguments.front()->annotation().type);
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: We do not need an explicit pop, since this happens after `revert`, so we only need to tell the compiler how the stack should be adjusted in the following control flow. This should actually be done already in `CompilerUtils::revertWithStringData` with `m_context.adjustStackOffset(_argumentType.sizeOnStack())`.

Because of that, I fear there is another bug lurking below.

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/codegen/ExpressionCompiler.cpp]: I was wondering about the same, but since in the `require` case you do the same, I've figured (without looking too much into) that this is how you intended it.

See https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/ExpressionCompiler.cpp#L941

Comment (chriseth) [reply libsolidity/codegen/ExpressionCompiler.cpp]: For require it is different, since it is a conditional jump, so in the success case, we actually have to remove stuff from the stack.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
It turned out that adjusting the stack height after the revert was the wrong thing to do in the first place, since the revert (or rather the memory encoder) actually properly consumed the argument. Only in the conditional branch, the height had to be adjusted.
