### PR TITLE
[Sol->Yul] Fixing array clearing when copying from storage to storage.

### LINKED ISSUE #10412: Array clearing failure during copying in the IR
```
semanticTests/array/copying/array_copy_storage_storage_static_static.sol: FAIL
  Contract:
    contract c {
        uint256[40] data1;
        uint256[20] data2;
    
        function test() public returns (uint256 x, uint256 y) {
            data1[30] = 4;
            data1[2] = 7;
            data1[3] = 9;
            data2[3] = 8;
            data1 = data2;
            x = data1[3];
            y = data1[30]; // should be cleared
        }
    }
    

  Running via Yul:
  Expected result:
  // test() -> 8, 0

  Obtained result:
  // test() -> 8, 4
```

```
semanticTests/array/copying/array_copy_target_leftover.sol: FAIL
  Contract:
    contract c {
        byte[10] data1;
        bytes2[32] data2;
        function test() public returns (uint check, uint res1, uint res2) {
            uint i;
            for (i = 0; i < data2.length; ++i)
                data2[i] = 0xffff;
            check = uint(uint16(data2[31])) * 0x10000 | uint(uint16(data2[14]));
            for (i = 0; i < data1.length; ++i)
                data1[i] = byte(uint8(1 + i));
            data2 = data1;
            for (i = 0; i < 16; ++i)
                res1 |= uint(uint16(data2[i])) * 0x10000**i;
            for (i = 0; i < 16; ++i)
                res2 |= uint(uint16(data2[16 + i])) * 0x10000**i;
        }
    }

  Running via Yul:
  Expected result:
  // test() -> 0xffffffff, 0x0000000000000000000000000a00090008000700060005000400030002000100, 0x0000000000000000000000000000000000000000000000000000000000000000

  Obtained result:
  // test() -> 0xffffffff, 0x0a090807060504030201, -1
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: Type or size of parameter(s) does not match.
  Warning: The call to "test()" returned 
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,ff,ff,ff,ff]
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,a,9,8,7,6,5,4,3,2,1]
  [ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff,ff]
```

```
semanticTests/array/copying/array_copy_different_packing.sol: FAIL
  Contract:
    contract c {
        bytes8[] data1; // 4 per slot
        bytes10[] data2; // 3 per slot
    
        function test()
            public
            returns (bytes10 a, bytes10 b, bytes10 c, bytes10 d, bytes10 e)
        {
            data1 = new bytes8[](9);
            for (uint256 i = 0; i < data1.length; ++i) data1[i] = bytes8(uint64(i));
            data2 = data1;
            a = data2[1];
            b = data2[2];
            c = data2[3];
            d = data2[4];
            e = data2[5];
        }
    }
    

  Running via Yul:
  Expected result:
  // test() -> 0x01000000000000000000000000000000000000000000000000, 0x02000000000000000000000000000000000000000000000000, 0x03000000000000000000000000000000000000000000000000, 0x04000000000000000000000000000000000000000000000000, 0x05000000000000000000000000000000000000000000000000

  Obtained result:
  // test() -> 0x0200000000000000000000000000000000000000000000000000000000, 0x030000000000000000000000000000000000000000000000000000, 0x05000000000000000400000000000000000000000000000000000000000000, 0x0600000000000000000000000000000000000000000000000000000000, 0x070000000000000000000000000000000000000000000000000000
  Warning: The call to "test()" returned 
```

```
semanticTests/array/copying/array_copy_target_simple.sol: FAIL
  Contract:
    contract c {
        bytes8[9] data1; // 4 per slot
        bytes17[10] data2; // 1 per slot, no offset counter
    
        function test()
            public
            returns (bytes17 a, bytes17 b, bytes17 c, bytes17 d, bytes17 e)
        {
            for (uint256 i = 0; i < data1.length; ++i) data1[i] = bytes8(uint64(i));
            data2[8] = data2[9] = bytes8(uint64(2));
            data2 = data1;
            a = data2[1];
            b = data2[2];
            c = data2[3];
            d = data2[4];
            e = data2[9];
        }
    }
    

  Running via Yul:
  Expected result:
  // test() -> 0x01000000000000000000000000000000000000000000000000, 0x02000000000000000000000000000000000000000000000000, 0x03000000000000000000000000000000000000000000000000, 0x04000000000000000000000000000000000000000000000000, 0x0

  Obtained result:
  // test() -> 0x0600000000000000050000000000000004000000000000000000000000000000, 0x08000000000000000000000000000000, 0x0200000000000000010000000000000000000000000000000000000000000000, 0x0600000000000000050000000000000004000000000000000000000000000000, 0x02000000000000000000000000000000000000000000000000
  Warning: The call to "test()" returned 
```

```
semanticTests/array/copying/array_copy_target_leftover2.sol: FAIL
  Contract:
    // since the copy always copies whole slots, we have to make sure that the source size maxes
    // out a whole slot and at the same time there are still elements left in the target at that point
    contract c {
        bytes8[4] data1; // fits into one slot
        bytes10[6] data2; // 4 elements need two slots
    
        function test() public returns (bytes10 r1, bytes10 r2, bytes10 r3) {
            data1[0] = bytes8(uint64(1));
            data1[1] = bytes8(uint64(2));
            data1[2] = bytes8(uint64(3));
            data1[3] = bytes8(uint64(4));
            for (uint256 i = 0; i < data2.length; ++i)
                data2[i] = bytes10(uint80(0xffff00 | (1 + i)));
            data2 = data1;
            r1 = data2[3];
            r2 = data2[4];
            r3 = data2[5];
        }
    }
    

  Running via Yul:
  Expected result:
  // test() -> 0x04000000000000000000000000000000000000000000000000, 0x0, 0x0

  Obtained result:
  // test() -> 0x02000000000000000100000000000000000000000000000000000000000000, 0x0, 0x0
```

### PR DESCRIPTION
**Pull request by mijovic**
Fixes #10412

### CODE REVIEW

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 1]
```diff
@@ -1707,19 +1708,64 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+									<srcAlignLeft>(and(srcSlotValue, <srcMask>)))
+								<!leftAligned>
+									and(srcSlotValue, <srcMask>))
+								</leftAligned>
+							dstSlotValue := or(
+								dstSlotValue,
+								<?leftAligned>
+									<shiftRightDyn>(sub(256, mul(add(j, 1), mul(<dstStride>, 8))), itemValue)
+								<!leftAligned>
+									<shiftLeftDyn>(mul(j, mul(<dstStride>, 8)), itemValue)
```
Comment (mijovic) [inline libsolidity/codegen/YulUtilFunctions.cpp]: I think I can get rid of dynamic shifts here, and will try that now

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: It is not as easy as I was thinking. There is going to be at least one dynamic shift call per source slot...
So, not sure what will be the difference in gas costs, is it worth optimizing this one?

**Comment by chriseth** [comment]
Does this bug also affect non-value array copying?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 2]
```diff
@@ -1707,19 +1708,60 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
-				for { } lt(i, fullSlots) { i := add(i, 1) } {
-					sstore(add(dstPtr, i), <maskFull>(sload(add(srcPtr, i))))
-				}
-				let spill := sub(length, mul(i, <itemsPerSlot>))
-				if gt(spill, 0) {
-					sstore(add(dstPtr, i), <maskBytes>(sload(add(srcPtr, i)), mul(spill, <bytesPerItem>)))
-				}
+				let spill := sub(length, mul(fullSlots, <itemsPerSlot>))
+
+				<?sameStride>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: This ignores the potential implicit conversion. Do we have some assurance that nothing is done during the conversion?

**Comment by mijovic** [comment]
> Does this bug also affect non-value array copying?

Non-value array copying wasn't affected. This was only the case with arrays of value types smaller than 32 bytes (with different base types). But, speaking of which I am not sure if we have tests with nested arrays with such types, so should be added here in any case...

so for example:
```
byte[][] a;
bytes2[][] b;

...

b = a;
```

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 2 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I would need to check if these conversions are allowed at all in type checker, but will add more tests to cover these cases. Either syntax tests or semantic in case if these conversions are allowed.
If not allowed, I need to add assertions here as well...

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 3]
```diff
@@ -1695,7 +1695,8 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
 	solAssert(_fromType.dataStoredIn(DataLocation::Storage) && _toType.baseType()->isValueType(), "");
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Can you add some more assertions, for example that the from base type is a value type?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Oh wait a second, in line 1690 we actually assert that from and to are more or less equal. How does this not fail in the tests?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Let's do that in the optimizer.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 4]
```diff
@@ -1707,19 +1708,60 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+					let totalSlots := fullSlots
+					if gt(spill, 0) {
+						totalSlots := add(totalSlots, 1)
+					}
+					for { let i := 0 } lt(i, totalSlots) { i := add(i, 1) } {
+						let dstSlotValue := 0
+						let itemsInSlot := <itemsPerSlot>
+						if eq(i, fullSlots) { itemsInSlot := spill }
+						for { let j := 0 } lt(j, itemsInSlot) { j := add(j, 1) } {
+							let itemValue := and(srcSlotValue, <srcMask>)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Instead of using all these custom operations, why not just use the helper functions that are also used when generating the code for the solidity expression `dst[i] = src[i]`?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Oh wow, looks like this assert is pointless
It ends up in `operator==` of `ReferenceType` which is quite simple:
```
bool operator==(ReferenceType const& _other) const
{
	return location() == _other.location() && isPointer() == _other.isPointer();
}
```
I'll remove this assertion and add more specific once.

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I added check that both base types are value types, plus that `_fromType.baseType()` is implicitely convertible to `_toType.baseType()`

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: but isn't that operator virtual and overridden by both struct and array?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: If not we have to change it.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 4 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Fixed

**Comment by mijovic** [comment]
I updated with fixes. I did it in different commits for easier review.

Left to be done is to add more tests.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: It was `dynamic_cast`ed to `ReferenceType`, that is why it was doing the one from `ReferenceType`...
But still , `operator==` from `ArrayType` will not work here as base types are not the same. I have changed assertions completely.

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I don't understand - it is still virtual - it should always call the most derived, shouldn't it?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 5]
```diff
@@ -1687,15 +1687,16 @@ string YulUtilFunctions::copyByteArrayToStorageFunction(ArrayType const& _fromTy
...
 {
-	solAssert(
-		*_fromType.copyForLocation(_toType.location(), _toType.isPointer()) == dynamic_cast<ReferenceType const&>(_toType),
-		""
-	);
+	solAssert(_fromType.baseType()->isValueType(), "");
+	solAssert(_toType.baseType()->isValueType(), "");
+	solAssert(_fromType.baseType()->isImplicitlyConvertibleTo(*_toType.baseType()), "");
+
 	solAssert(!_fromType.isByteArray(), "");
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:1806]: Please assert that to type is not byte array.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: An example where conversion would be needed: copy int8[] to int16[]

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: ah, but that's not the same stride!

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Maybe instead of making this optimization, we should rather unroll the loop over the elements in the slot?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 6]
```diff
@@ -1707,19 +1708,52 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+				<?sameStride>
+					let i := 0
+					for { } lt(i, fullSlots) { i := add(i, 1) } {
+						sstore(add(dstSlot, i), <maskFull>(sload(add(srcSlot, i))))
+					}
+					if gt(spill, 0) {
+						sstore(add(dstSlot, i), <maskBytes>(sload(add(srcSlot, i)), mul(spill, <dstStride>)))
+					}
+				<!sameStride>
+					let srcSlotValue := sload(srcSlot)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Can't this move inside the loop?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 7]
```diff
@@ -1707,19 +1708,52 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+					if gt(spill, 0) {
+						totalSlots := add(totalSlots, 1)
+					}
+					for { let i := 0 } lt(i, totalSlots) { i := add(i, 1) } {
+						let dstSlotValue := 0
+						let itemsInSlot := <itemsPerSlot>
+						if eq(i, fullSlots) { itemsInSlot := spill }
+						for { let j := 0 } lt(j, itemsInSlot) { j := add(j, 1) } {
+							let itemValue := <extractFromSlot>(srcSlotValue, mul(<srcStride>, srcItemIndexInSlot))
+							<?+alignRight>itemValue := <alignRight>(itemValue)</+alignRight>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Why not use `prepareStoreFunction`?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 8]
```diff
@@ -1707,19 +1708,52 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+					let totalSlots := fullSlots
+					if gt(spill, 0) {
+						totalSlots := add(totalSlots, 1)
+					}
+					for { let i := 0 } lt(i, totalSlots) { i := add(i, 1) } {
+						let dstSlotValue := 0
+						let itemsInSlot := <itemsPerSlot>
+						if eq(i, fullSlots) { itemsInSlot := spill }
+						for { let j := 0 } lt(j, itemsInSlot) { j := add(j, 1) } {
+							let itemValue := <extractFromSlot>(srcSlotValue, mul(<srcStride>, srcItemIndexInSlot))
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Maybe call conversion function?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: it wouldn't pass `operator==` in ArrayType, or it has a bug :)
Let me check in debugger what happens with that assertion. Anyway `operator==` for `ArrayType` checks that base types are equal as well. Only way it can work is that for example `byte` and `bytes2` are equal.
Let me check and get back

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: It was calling the one from `ReferenceType` (virtual doesn't work in this case)
```
solAssert(
	*_fromType.copyForLocation(_toType.location(), _toType.isPointer()) == dynamic_cast<ReferenceType const&>(_toType),
	""
);
```

Putting it this way 
```
solAssert(
	_fromType.copyForLocation(_toType.location(), _toType.isPointer()) == &_toType,
	""
);

```
fails, as this one call the one from `ArrayType`

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 5 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1806]: Added now

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 7 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: True that, thanks :)

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 8 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Called. Wasn't sure if it makes a difference. In any case, for safe side it is better to call it.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 2 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I have removed this part of function. So hope that optimizer will be able to unroll the loop. That was your suggestion?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 6 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Loop is done over slots in dst. So it lives independently of the loop. This is important for cases when copying, for example `bytes8[]` to `bytes10`. So the counters are not reset at the same time...

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I was suggesting to "manually" unroll it, if that is possible. Another option would be to add a special case not about "sameStride" but about "exactly the same type".

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I tried splitting the loop to two cases, one is same type, other different type.
For types that have same stride (because of possible need to call conversion) I need to read element by element

I don't think this piece of code can be optimized more now.

**Comment by chriseth** [comment]
is this activating all the remaining tests in test/libsolidity/semanticTests/array/copying ?

**Comment by mijovic** [comment]
> is this activating all the remaining tests in test/libsolidity/semanticTests/array/copying ?

There is only one left:
`array/copying/storage_memory_nested_bytes`(this needs #10560, and probably something else)  and `storage_memory_nested_struct` which is implemented by #10552

Once I am done with these PRs will probably fast activate the last one.

Just to mention, there are test working viaYul only in that directory :-)

**Comment by mijovic** [comment]
Rebased

**Comment by mijovic** [comment]
Rebased

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 9]
```diff
@@ -1799,15 +1799,17 @@ string YulUtilFunctions::copyByteArrayToStorageFunction(ArrayType const& _fromTy
...
-		*_fromType.copyForLocation(_toType.location(), _toType.isPointer()) == dynamic_cast<ReferenceType const&>(_toType),
-		""
-	);
+	solAssert(_fromType.baseType()->isValueType(), "");
+	solAssert(_toType.baseType()->isValueType(), "");
+	solAssert(_fromType.baseType()->isImplicitlyConvertibleTo(*_toType.baseType()), "");
+
 	solAssert(!_fromType.isByteArray(), "");
+	solAssert(!_toType.isByteArray(), "");
 	solAssert(_fromType.dataStoredIn(DataLocation::Storage) && _toType.baseType()->isValueType(), "");
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: second part is redundant

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 10]
```diff
@@ -1819,18 +1821,54 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+					totalSlots := add(totalSlots, 1)
+				}
+
+				let srcSlotValue := sload(srcSlot)
+				<?srcReadMultiPerSlot>let srcItemIndexInSlot := 0</srcReadMultiPerSlot>
+
+				for { let i := 0 } lt(i, totalSlots) { i := add(i, 1) } {
+					let dstSlotValue := 0
+					<?sameType>
+						switch lt(i, fullSlots)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Wouldn't it be better to move the last (i.e. the non-full) slot to after the loop?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 11]
```diff
@@ -1819,18 +1821,54 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
-					sstore(add(dstPtr, i), <maskBytes>(sload(add(srcPtr, i)), mul(spill, <bytesPerItem>)))
+					totalSlots := add(totalSlots, 1)
+				}
+
+				let srcSlotValue := sload(srcSlot)
+				<?srcReadMultiPerSlot>let srcItemIndexInSlot := 0</srcReadMultiPerSlot>
+
+				for { let i := 0 } lt(i, totalSlots) { i := add(i, 1) } {
+					let dstSlotValue := 0
+					<?sameType>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:1833]: Maybe instead of distinguishing the "sameType" case, we should rather distinguish the case "srcStride" and "dstStride" are both at least 17 - i.e. we have one item per slot.

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1833]: I would stay with same type, as if types is not the same we need a call to conversion function

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:1833]: Ah wait a second - the "sameType" case also works with multiple items per slot? Then it should certainly have its own case.

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:1833]: Still, the "only one item per slot" could also be its own case - I don't think loop unrolling is coming any time soon...

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:1833]: Although maybe it should...

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 12]
```diff
@@ -1819,19 +1821,60 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+
+				let srcSlotValue := sload(srcSlot)
+				let srcItemIndexInSlot := 0
+				for { let i := 0 } lt(i, fullSlots) { i := add(i, 1) } {
+					let dstSlotValue := 0
+					<?sameType>
+						dstSlotValue := <maskFull>(srcSlotValue)
+						<updateSrcSlotValue>
+					<!sameType>
+						<?multipleItemsPerSlotDst>for { let j := 0 } lt(j, <itemsPerSlot>) { j := add(j, 1) } </multipleItemsPerSlotDst>
```
Comment (mijovic) [inline libsolidity/codegen/YulUtilFunctions.cpp:1837]: In case that we do not have multiple items per slot in destination, there is no loop. Maybe representation is ugly, but the body of the loop is almost the same so didn't want to put whole loop under condition...

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 13]
```diff
@@ -1819,19 +1821,60 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+							</multipleItemsPerSlotDst>
+
+							<updateSrcSlotValue>
+						}
+					</sameType>
+
+					sstore(add(dstSlot, i), dstSlotValue)
 				}
+
+				<?multipleItemsPerSlotDst>
```
Comment (mijovic) [inline libsolidity/codegen/YulUtilFunctions.cpp:1857]: There is spill only in case we have multiple items per slot

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 11 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1833]: Updated. Also there are cases when types are not the same, src base type is less then 17 bytes and dst base type is more then 16 bytes and all the cases are optimized as much as possible now (and covered with tests).

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 12 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:1837]: ah ok!

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 14]
```diff
@@ -1842,11 +1885,43 @@ string YulUtilFunctions::copyValueArrayStorageToStorageFunction(ArrayType const&
...
+		else
+		{
+			templ("dstStride", to_string(_toType.storageStride()));
+			templ("extractFromSlot", extractFromStorageValueDynamic(*_fromType.baseType()));
+			templ("updateByteSlice", updateByteSliceFunctionDynamic(_toType.storageStride()));
+			templ("convert", conversionFunction(*_fromType.baseType(), *_toType.baseType()));
+			templ("prepareStore", prepareStoreFunction(*_toType.baseType()));
+		}
+		templ("updateSrcSlotValue", Whiskers(R"(
+			<?srcReadMultiPerSlot>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:1908]: Can this be merged into the main template?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:1908]: Oh it's used multiple times!

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1908]: I use it in three different places. I can merge, but would have duplication

**Review by chriseth — APPROVED** [review]
