### PR TITLE
Disallow non-hex zero literals and fix 32-byte hex literals in `bytes.concat()`

### LINKED ISSUE #11588: Disallow zero literals as arguments to `bytes.concat()`
Related to #11580 and #11582.

## Description
Currently `bytes.concat()` accepts zero literals because they're implicitly convertible to fixed bytes. After my fix in #11580 they're treated as `bytes1` but user might just as well expect `bytes32` or any other width. This introduces ambiguity and I don't see much use for zero literals in practice so we should disallow this.

As far as I can tell zero is the only exception. Other integers are not implicitly convertible and thus not accepted.

## Backwards-compatibility
Normally this would be a breaking change but this use case was broken and only fixed in 0.8.6 (#11580) so as long as we do it in the same release it can't break any valid code.

### PR DESCRIPTION
**Pull request by cameel**
Fixes #11588.
~Depends on #11591 (fix for tests on `develop`).~ Merged.

- ~Disallows `0` but still allows `0x0000000000000000000000000000000000000000000000000000000000000000`.~ Disallows all numeric zero literals.
- Fixes ICE when using `bytes.concat()` with 32-byte hex literals.
    - By disallowing them.

### CODE REVIEW

File: libsolidity/ast/Types.h [hunk 1]
```diff
@@ -593,7 +594,7 @@ class RationalNumberType: public Type
 private:
 	rational m_value;
 
-	/// Bytes type to which the rational can be explicitly converted.
+	/// Bytes type to which the rational can be implicitly converted.
 	/// Empty for all rationals that are not directly parsed from hex literals.
 	Type const* m_compatibleBytesType;
```
Comment (cameel) [inline libsolidity/ast/Types.h:598]: I think this is an error because this field is actually used in `RationalNumberType::isImplicitlyConvertibleTo()` when deciding if a conversion to fixed bytes is possible.

File: test/libsolidity/syntaxTests/array/concat/bytes_concat_wrong_type_zero_literal.sol [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+            0.0,
+            -0.0,
+            0e10,
+            -0e10,
+            0e-10,
+            -0e-10,
+            (0),
+            0x00,
+            -0x00,
+            -0x0000000000000000000000000000000000000000000000000000000000000000
```
Comment (cameel) [inline test/libsolidity/syntaxTests/array/concat/bytes_concat_wrong_type_zero_literal.sol]: It's interesting that `-0x0000000000000000000000000000000000000000000000000000000000000000` is not convertible to `bytes32` while `0x0000000000000000000000000000000000000000000000000000000000000000` is but makes sense for consistency with other negative hex numbers.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 3]
```diff
@@ -2476,11 +2476,8 @@ string YulUtilFunctions::bytesConcatFunction(vector<Type const*> const& _argumen
 			literalType && literalType->value().size() <= 32
 		)
 			targetTypes.emplace_back(TypeProvider::fixedBytes(static_cast<unsigned>(literalType->value().size())));
-		else if (auto const* literalType = dynamic_cast<RationalNumberType const*>(argumentType))
-		{
-			solAssert(literalType->value() == 0, "");
-			targetTypes.emplace_back(TypeProvider::fixedBytes(1));
-		}
+		else if (argumentType->isImplicitlyConvertibleTo(*TypeProvider::fixedBytes(32)))
+			targetTypes.emplace_back(TypeProvider::fixedBytes(32));
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Wait are we always using `bytes32`? Was it like that before? Is it consistent with `abi.encodePacked()`?

File: libsolidity/analysis/TypeChecker.cpp [hunk 4]
```diff
@@ -2033,18 +2033,29 @@ void TypeChecker::typeCheckBytesConcatFunction(
 	typeCheckFunctionGeneralChecks(_functionCall, _functionType);
 
 	for (shared_ptr<Expression const> const& argument: _functionCall.arguments())
-		if (
-			Type const* argumentType = type(*argument);
+	{
+		Type const* argumentType = type(*argument);
+		bool notConvertibleToBytes = argumentType &&
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Can it be null?

File: libsolidity/analysis/TypeChecker.cpp [hunk 5]
```diff
@@ -2033,18 +2033,29 @@ void TypeChecker::typeCheckBytesConcatFunction(
...
 			!argumentType->isImplicitlyConvertibleTo(*TypeProvider::fixedBytes(32)) &&
-			!argumentType->isImplicitlyConvertibleTo(*TypeProvider::bytesMemory())
-		)
+			!argumentType->isImplicitlyConvertibleTo(*TypeProvider::bytesMemory());
+
+		// Only literals with all 32 bytes specified are allowed. For others the number of bytes is
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Can we still use `"123"` and `0x124567` and `hex"aabbcc"`? (not sure if we should for all of them)

Also would the following condition also work:
 - if it is a rational number type, it has to be implicitly convertible to bytes32 but not to bytes31

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Only for literals. Well, I think I should add a check that it's actually `RationalNumberType` here to make it 100% clear but currently that's the only possibility anyway. At this point all fixed bytes types and string literals have already been handled by `if` branches above and `bytes` is not implicitly convertible to fixed `bytes32` so it will skip this one.

File: libsolidity/analysis/TypeChecker.cpp (hunk 4 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: Good point. I think it can't. I'll change that.

File: libsolidity/analysis/TypeChecker.cpp (hunk 5 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: - `"123"` and hex"aabbcc" - yes. All string literals are supported because they're implicitly convertible to `bytes` or fixed bytes.
- `0x124567` - no, because it's only convertible to `bytes4` and only literals convertible to `bytes32` are accepted.

> Also would the following condition also work:

Yes. It would accept only 32-byte-long hex literals and exclude the one with 32 zeros.

Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: > Yes. It would accept only 32-byte-long hex literals and exclude the one with 32 zeros.

Wait. No, it would not work because I think we do not want to exclude `0x0000000000000000000000000000000000000000000000000000000000000000`, only `0`. We need a condition that would differentiate between the two forms of zero and `isImplicitlyConvertibleTo()` behaves the same way for both.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I added a stronger check now with an assertion that shows that it only happens for literals that are compatible with `bytes32`.

> Was it like that before?

Literals were not considered here at all before. They were falling into the `else` branch that handles `bytes` and failing the assertion there.

> Is it consistent with `abi.encodePacked()`?

It is unless `abi.encodePacked()` handles 32-byte hex literals as something else than `bytes32`. Not sure what it does with zero. I'll check that.

File: libsolidity/analysis/TypeChecker.cpp (hunk 4 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: Done.

I thought that this check was here before but I just misinterpreted the `if` with variable initialization in it - the initialization does not automatically check if the variable does not evaluate to `false`. I really do not like this `if` syntax. I just keep reading it wrong.

File: libsolidity/analysis/TypeChecker.cpp (hunk 5 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: I added all of your examples to test cases.

**Comment by chriseth** [comment]
I think we should implement this with a bit more foresight and change the condition to the following:

If the type is a reference type and convertible to bytes memory, it is accepted.
If the type is a bytesNN, it is accepted.
Otherwise:
 - check for all possible bytesNN types and for bytes memory if conversion is possible.
 - reject if conversion is possible for more than one bytesNN type
 - accept if conversion is possible for at least one of the types (bytesNN / bytes memory)

**Comment by cameel** [comment]
Sounds good. Just one detail:

> check for all possible bytesNN types and for bytes memory if conversion is possible.

Should I just iterate over `bytes1`..`bytes32` or is there a smarter way to do it?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I checked `abi.encodePacked()` and it does not allow 32-byte hex literals at all:
```
Error: Cannot perform packed encoding for a literal. Please convert it to an explicit type first.
  --> test.sol:53:13:
   |
53 |             0x00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff,
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Does not allow plain zero either. Only allows various flavors of string literals (`hex"aabbcc"`, `unicode"abc"`, `"abc"`).

But it also allows some of the literals not supported by `bytes.concat()`:
- Boolean literals (`false`, `true`).
- Address literals (`0x1111222233334444555566667777888899990000`).
- Array literals (`[0]`).
- Expressions that yield integers (`[0][0]`).
- Enum members (`E.A`).

**Comment by chriseth** [comment]
I don't know a better way than iterating.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Then let's just disallow literal numbers. I think it's fair to require explicit conversion to a bytes type for all the examples above.

Comment (cameel) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Done.

**Comment by cameel** [comment]
Solution changed to disallowing all numeric literals in `bytes.concat()`. Ready for another review.

**Review by chriseth — APPROVED** [review]
