### PR TITLE
AssemblyItem gets an optional instruction

### LINKED ISSUE #15933: Cannot build solidity with gcc-15.0.1 -O3 but builds just fine with -O2
## Description

I'm trying to build solidity with GCC 15.0.1 with O3 (default) and with 02 (default in Fedora Linux) on x86_64. The latter builds just fine, but the former halts with the following error

## Environment

- Compiler version: gcc 15.0.1
- Compilation pipeline (legacy, IR, EOF): n/a (compile-time issue)
- Target EVM version (as per compiler settings): n/a (compile-time issue)
- Framework/IDE (e.g. Foundry, Hardhat, Remix): n/a (compile-time issue)
- EVM execution environment / backend / blockchain client: n/a (compile-time issue)
- Operating system: Fedora Linux 43

## Steps to Reproduce

```
CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
LT_SYS_LIBRARY_PATH=/usr/lib64:
CC=gcc
CXX=g++
/usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_FULL_SBINDIR:PATH=/usr/bin -DCMAKE_INSTALL_SBINDIR:PATH=bin -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DBUILD_SHARED_LIBS:BOOL=ON -DIGNORE_VENDORED_DEPENDENCIES:BOOL=ON -DBoost_USE_STATIC_LIBS:BOOL=OFF -DSTRICT_Z3_VERSION:BOOL=OFF -DTESTS:BOOL=OFF
...
[ 20%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/SimplificationRules.cpp.o
cd /builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/redhat-linux-build/libevmasm && /usr/bin/g++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DFMT_HEADER_ONLY=1 -I/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/redhat-linux-build/include -I/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O3 -DNDEBUG -std=c++20 -fstack-protector-strong -Wimplicit-fallthrough -fmacro-prefix-map=/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29=/solidity -Wpessimizing-move -Wredundant-move -Wall -Wextra -Werror -pedantic -Wmissing-declarations -Wno-unknown-pragmas -Wsign-conversion -Wconversion -Wextra-semi -Wno-dangling-reference -Wduplicated-cond -Wlogical-op -fdiagnostics-color -MD -MT libevmasm/CMakeFiles/evmasm.dir/SimplificationRules.cpp.o -MF CMakeFiles/evmasm.dir/SimplificationRules.cpp.o.d -o CMakeFiles/evmasm.dir/SimplificationRules.cpp.o -c /builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/SimplificationRules.cpp
In file included from /builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/Assembly.h:23,
                 from /builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/Inliner.h:25,
                 from /builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/Inliner.cpp:23:
In member function ‘solidity::evmasm::AssemblyItem::AssemblyItem(solidity::evmasm::AssemblyItem const&)’,
    inlined from ‘std::_Construct<solidity::evmasm::AssemblyItem, solidity::evmasm::AssemblyItem const&>(solidity::evmasm::AssemblyItem*, solidity::evmasm::AssemblyItem const&)void’ at /usr/include/c++/15/bits/stl_construct.h:133:7,
    inlined from ‘std::__do_uninit_copy<solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem*>(solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem*)solidity::evmasm::AssemblyItem*’ at /usr/include/c++/15/bits/stl_uninitialized.h:145:17,
    inlined from ‘std::uninitialized_copy<solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem*>(solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem*)solidity::evmasm::AssemblyItem*’ at /usr/include/c++/15/bits/stl_uninitialized.h:260:30,
    inlined from ‘std::__uninitialized_copy_a<solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem*, solidity::evmasm::AssemblyItem>(solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem*, std::allocator<solidity::evmasm::AssemblyItem>&)solidity::evmasm::AssemblyItem*’ at /usr/include/c++/15/bits/stl_uninitialized.h:617:32,
    inlined from ‘std::vector<solidity::evmasm::AssemblyItem, std::allocator<solidity::evmasm::AssemblyItem> >::_M_range_initialize<solidity::evmasm::AssemblyItem const*>(solidity::evmasm::AssemblyItem const*, solidity::evmasm::AssemblyItem const*, std::forward_iterator_tag)void’ at /usr/include/c++/15/bits/stl_vector.h:1890:6,
    inlined from ‘std::vector<solidity::evmasm::AssemblyItem, std::allocator<solidity::evmasm::AssemblyItem> >::vector(std::initializer_list<solidity::evmasm::AssemblyItem>, std::allocator<solidity::evmasm::AssemblyItem> const&)’ at /usr/include/c++/15/bits/stl_vector.h:709:21,
    inlined from ‘solidity::evmasm::Inliner::shouldInlineFullFunctionBody(unsigned long, ranges::span<solidity::evmasm::AssemblyItem const, -1l>, unsigned long) const’ at /builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/Inliner.cpp:159:2:
/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/AssemblyItem.h:163:9: error: ‘MEM[(const struct AssemblyItem &)&D.578956].m_instruction’ may be used uninitialized [-Werror=maybe-uninitialized]
  163 |         AssemblyItem(AssemblyItem const&) = default;
      |         ^~~~~~~~~~~~
/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/Inliner.cpp: In member function ‘solidity::evmasm::Inliner::shouldInlineFullFunctionBody(unsigned long, ranges::span<solidity::evmasm::AssemblyItem const, -1l>, unsigned long) const’:
/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/libevmasm/Inliner.cpp:159:9: note: ‘<anonymous>’ declared here
  159 |         };
      |         ^
cc1plus: all warnings being treated as errors
gmake[2]: *** [libevmasm/CMakeFiles/evmasm.dir/build.make:236: libevmasm/CMakeFiles/evmasm.dir/Inliner.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/redhat-linux-build'
gmake[1]: Leaving directory '/builddir/build/BUILD/solidity-0.8.29-build/solidity-0.8.29/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:453: libevmasm/CMakeFiles/evmasm.dir/all] Error 2
gmake: *** [Makefile:139: all] Error 2
```

### PR DESCRIPTION
**Pull request by clonker**
I have also sharpened the `hasInstruction` function to check if there is actually something inside of `m_instruction`. Previously it could happen that it returns `true` while the instruction was still undefined / null:

https://github.com/ethereum/solidity/blob/340ae32d5c27c87ce51ca0b484f7566f1951c4a0/libevmasm/AssemblyItem.h#L89-L97

Setting the `AssemblyItemType` to, e.g., `SwapN` leaves `m_instruction` undefined but still yields `hasInstruction() -> true`. This is why I think an optional better and more reliably reflects the intended behavior than default-initializing the class member.

Fixes #15933.

### CODE REVIEW

**Comment by lemenkov** [comment]
I've just checked - this indeed fixes #15933.

**Review by aarlt — DISMISSED** [review]

File: libevmasm/AssemblyItem.h [hunk 1]
```diff
@@ -196,22 +195,25 @@ class AssemblyItem
...
+				m_type == EOFCreate ||
+				m_type == ReturnContract ||
+				m_type == RelativeJump ||
+				m_type == ConditionalRelativeJump ||
+				m_type == CallF ||
+				m_type == JumpF ||
+				m_type == RetF ||
+				m_type == SwapN ||
+				m_type == DupN
+			);
```
Comment (cameel) [inline libevmasm/AssemblyItem.h]: This actually changes behavior, because it lets you use some of these assembly items without an instruction. They are by design meant to always have one.

The added part should be an assert instead.

Comment (clonker) [reply libevmasm/AssemblyItem.h]: Also for `verbatimBytecode`? The `m_instruction` used to be defaulted in that case (ie `STOP`), but I guess in reality it should signify some sort of null state, as in it's not used. I have now asserted that the `m_instruction` is set iff `hasInstruction` yields `true`. Also happy to change it to always assert `m_instruction.has_value()` in that function, although then the purpose of `hasInstruction` is a bit unclear to me, too :)

File: libevmasm/AssemblyItem.h [hunk 2]
```diff
@@ -323,7 +324,7 @@ class AssemblyItem
 	size_t opcodeCount() const noexcept;
 
 	AssemblyItemType m_type;
-	Instruction m_instruction; ///< Only valid if m_type == Operation
+	std::optional<Instruction> m_instruction; ///< Only valid if m_type == Operation
```
Comment (cameel) [inline libevmasm/AssemblyItem.h]:
```suggestion
	std::optional<Instruction> m_instruction; ///< Only valid for item types that represent a specific opcode
```

**Review by cameel — DISMISSED** [review]
Looks good, but the docstring should be updated.

File: libevmasm/AssemblyItem.h (hunk 1 above)
Comment (cameel) [reply libevmasm/AssemblyItem.h]: > Also for `verbatimBytecode`?

Yes, it should not be used for verbatim. Verbatim carries a piece of bytecode in `data` instead.

> I have now asserted that the `m_instruction` is set iff `hasInstruction` yields `true`. 

Good. That's the intention. There are items that are associated with a single opcode and others that aren't. There's no in-between. We could clarify that in the docstring.

The instruction was originally used only with `Operation` but with EOF there are more items like this. Some of the existing ones could actually have an instruction too (e.g. the various push variants or `AuxDataLoadN`). We should refactor this at some point.

**Comment by cameel** [comment]
Hmm... what's up with the "Hangup" (`SIGHUP`?) in [`b_archlinux`](https://app.circleci.com/pipelines/github/ethereum/solidity/38900/workflows/25a54e40-4da8-4828-a088-5cdeaf02feb3/jobs/1797999)?

```
[ 12%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/SimplificationRules.cpp.o
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/build.make:317: libevmasm/CMakeFiles/evmasm.dir/PeepholeOptimiser.cpp.o] Hangup
make[1]: *** [CMakeFiles/Makefile2:660: libevmasm/CMakeFiles/evmasm.dir/all] Hangup
make: *** [Makefile:136: all] Hangup
```

Looks like a fluke, but it persists when I rerun.

**Comment by clonker** [comment]
Probably a compiler issue in combination with O3 in the peephole optimizer. `AssemblyItem` is used heavily inside it so the added assert might have worsened the situation there. I suspect it is the same as in #15936. Plus I experienced it when upgrading to c++20 in (i think it was) the alpine docker image. Perhaps a good time to move to `O2` :) after benchmarking it, of course.

File: libevmasm/AssemblyItem.h (hunk 2 above)
Comment (clonker) [reply libevmasm/AssemblyItem.h]: Good point, done

**Review by cameel — APPROVED** [review]

**Comment by cameel** [comment]
Right. If we can't get CI to pass here, we'll even have to do that before we merge this because we can't risk this spreading to `develop`.
