### PR TITLE
[Yul] Output an error of a switch case which contains string literals…

### LINKED ISSUE #6510: [yul] Asm analyzer fails assertion (string literal too long) for string literals with more than 32 characters
## Description

(Found by ossfuzz: issue 13929)

```
{
  let x
  switch x
    case "012345678901234567890123456789012" {}
}
```

fails this assertion

https://github.com/ethereum/solidity/blob/bf653b004eb1168ac84a7c0532ba9ea66c415d0b/libyul/Utilities.cpp#L45

can be reproduced like so
```
$ echo "{let x switch x case \"012345678901234567890123456789012\"{}}" | ./solc/solc --strict-assembly  -
Warning: Yul and its optimizer are still experimental. Please use the output with care.
Exception in assembler: /home/bhargava/work/github/solidity/libyul/Utilities.cpp(45): Throw in function dev::u256 yul::valueOfStringLiteral(const yul::Literal&)
Dynamic exception type: boost::exception_detail::clone_impl<yul::YulException>
std::exception::what: Literal string too long!
[dev::tag_comment*] = Literal string too long!
```

Perhaps, we should output a warning instead for inline asm containing string literals longer than 32 chars.

### PR DESCRIPTION
**Pull request by hydai**
### Description

Fix #6510 

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `4b1ca8120fe9e483d6a675c1f6a1f585e9fbe6df`:
```
Coding style error:
 libyul/AsmAnalysis.cpp:448: if (!(*this)(*_case.value)) {

```
Please check that your changes are working as intended.

File: libyul/AsmAnalysis.cpp [hunk 1]
```diff
@@ -442,15 +442,20 @@ bool AsmAnalyzer::operator()(Switch const& _switch)
...
 			// Statement and would be converted to a Statement otherwise.
 			if (!(*this)(*_case.value))
+			{
+				isCaseValueValid = false;
 				success = false;
+			}
 			expectDeposit(1, initialStackHeight, _case.value->location);
 			m_stackHeight--;
 
+			// If the case value is not valid, we should not insert it into cases.
```
Comment (chriseth) [inline libyul/AsmAnalysis.cpp:456]: Please add an assertion like `yulAssert(isCaseValueValid || m_errorReporter.hasErrors()`, just in case.

Also please add a test case in `test/libyul/Parser.cpp`.

Comment (hydai) [reply libyul/AsmAnalysis.cpp:456]: Fixed. And also add a test case for this PR.

**Review by chriseth — APPROVED** [review]
