### PR TITLE
AsmParser: parse source comment using scanner instead of regex

### LINKED ISSUE #13496: Segmentation fault compiling a contract with huge data and via-IR enabled
## Description
Investigating issue [#13494](https://github.com/ethereum/solidity/issues/13494) I ended up in a segmentation fault error when compiling the contract below with via-IR. The contract only assigns to a variable a huge payload.

## Environment

- Compiler version: Version: 0.8.17-develop.2022.9.5+commit.51929652.Linux.g++ (also tested on 0.8.16 release)
- Target EVM version (as per compiler settings): `via-ir`
- Framework/IDE (e.g. Truffle or Remix): tested with solc and foundry
- Operating system: Linux

## Steps to Reproduce

1. Create a file `Test.sol` with the following code and the data payload from this example [here](https://github.com/bug-reproduction/solidity-assembly-variable-reset/blob/main/test/data/index.ts#L2)
```solidity
pragma solidity >=0.8.16;

contract Test {
	function test() external {
		bytes memory data = hex"615870600E600039..."; // replace with a huge data
	}
}
```

2. Compile the code to get the segmentation fault error
```
solc --via-ir ./Test.sol
```

Running using GDB returns the following stack trace on `solidity::yul::Parser::parseSrcComment`:
```
ar const*, std::__cxx11::match_results<char const*, std::allocator<std::__cxx11::sub_match<char const*> > >&, std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> > const&, std::regex_constants::match_flag_type, std::__detail::_RegexExecutorPolicy, bool) ()
#80516 0x0000555555c4c3f4 in solidity::yul::Parser::parseSrcComment(std::basic_string_view<char, std::char_traits<char> >, solidity::langutil::SourceLocation const&) ()
#80517 0x0000555555c4d63a in solidity::yul::Parser::fetchDebugDataFromComment() ()
#80518 0x0000555555c4d91c in solidity::yul::Parser::advance() ()
#80519 0x0000555555c50e09 in solidity::yul::Parser::parseBlock() ()
#80520 0x0000555555c516e8 in solidity::yul::Parser::parseFunctionDefinition() ()
#80521 0x0000555555c4ff88 in solidity::yul::Parser::parseStatement() ()
#80522 0x0000555555c50e66 in solidity::yul::Parser::parseBlock() ()
#80523 0x0000555555c51a83 in solidity::yul::Parser::parseInline(std::shared_ptr<solidity::langutil::Scanner> const&) ()
#80524 0x0000555555c6e801 in solidity::yul::ObjectParser::parseBlock(std::optional<std::map<unsigned int, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> > > > >) ()
#80525 0x0000555555c6ecaf in solidity::yul::ObjectParser::parseCode(std::optional<std::map<unsigned int, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> > > > >) ()
#80526 0x0000555555c715e1 in solidity::yul::ObjectParser::parseObject(solidity::yul::Object*) ()
#80527 0x0000555555c71985 in solidity::yul::ObjectParser::parseObject(solidity::yul::Object*) ()
#80528 0x0000555555c71ba9 in solidity::yul::ObjectParser::parse(std::shared_ptr<solidity::langutil::Scanner> const&, bool) ()
#80529 0x0000555555c5ec20 in solidity::yul::YulStack::parseAndAnalyze(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#80530 0x0000555555aa0e24 in solidity::frontend::IRGenerator::run[abi:cxx11](solidity::frontend::ContractDefinition const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::map<solidity::frontend::ContractDefinition const*, std::basic_string_view<char, std::char_traits<char> > const, std::less<solidity::frontend::ContractDefinition const*>, std::allocator<std::pair<solidity::frontend::ContractDefinition const* const, std::basic_string_view<char, std::char_traits<char> > const> > > const&) ()
#80531 0x00005555558048d1 in solidity::frontend::CompilerStack::generateIR(solidity::frontend::ContractDefinition const&) ()
#80532 0x000055555580929b in solidity::frontend::CompilerStack::compile(solidity::frontend::CompilerStack::State) ()
#80533 0x0000555555735c26 in solidity::frontend::CommandLineInterface::compile() ()
#80534 0x000055555573b015 in solidity::frontend::CommandLineInterface::processInput() ()
#80535 0x000055555573b40c in solidity::frontend::CommandLineInterface::run(int, char const* const*) ()
#80536 0x0000555555706e6c in main ()
```

### LINKED ISSUE #15207: Segfault in AsmParser for debug-compiled solc
## Description

Calling `solc --standard-json out.json` for [out.json](https://github.com/user-attachments/files/15888227/out.json) (corresponding to [initcode_too_large_paris](https://github.com/ethereum/solidity/blob/develop/test/libsolidity/syntaxTests/sizeLimits/initcode_too_large_paris.sol) syntax test) leads to a segfault in the `std::regex` module [here](https://github.com/ethereum/solidity/blob/develop/libyul/AsmParser.cpp#L201) when `solc` was compiled under GCC with a debug configuration.

## Environment

- Compiler version: GCC 14.1.1
- Operating system: arch linux

### PR DESCRIPTION
**Pull request by clonker**
Fixes #15207
Fixes #13496

### CODE REVIEW

File: libyul/AsmParser.cpp [hunk 1]
```diff
@@ -192,13 +196,67 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+
+	int sourceIndex { -1 };
+	int start { -1 };
+	int end { -1 };
+	bool indexOutOfRange { false };
+	std::optional<std::string_view> snippet { std::nullopt };
+	std::string_view tail { _arguments.substr(_arguments.size()) };
+	auto const parseIndex = [](Scanner& _scanner) -> std::tuple<std::optional<int>, bool>
+	{
+		int sgn = 1;
```
Comment (matheusaaguiar) [inline libyul/AsmParser.cpp]:
```suggestion
		int sign = 1;
```
Just one more letter :)

File: libyul/AsmParser.cpp [hunk 2]
```diff
@@ -192,13 +196,67 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+		if (_scanner.currentToken() == Token::Sub)
+		{
+			sgn = -1;
+			_scanner.next();
+		}
+		if (_scanner.currentToken() != Token::Number)
+			return std::make_tuple(std::nullopt, false);
+		try
+		{
+			return std::make_tuple(sgn * std::stoi(_scanner.currentLiteral()), false);
```
Comment (matheusaaguiar) [inline libyul/AsmParser.cpp]: I read [here](https://en.cppreference.com/w/cpp/string/basic_string/stol) that `std::stoi` can handle a minus (or plus) sign. Or is that implementation dependent?
Maybe we could simplify to:
```suggestion
			return std::make_tuple(std::stoi(_scanner.currentLiteral()), false);
```

File: libyul/AsmParser.cpp [hunk 3]
```diff
@@ -224,30 +303,25 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
 		return {{tail, SourceLocation{}}};
 	}
 
-	std::optional<int> const sourceIndex = toInt(match[1].str());
-	std::optional<int> const start = toInt(match[2].str());
-	std::optional<int> const end = toInt(match[3].str());
-
-	if (!sourceIndex.has_value() || !start.has_value() || !end.has_value())
+	if (indexOutOfRange || (sourceIndex < 0 && sourceIndex != -1) || (start < 0 && start != -1) || (end < 0 && end != -1))
```
Comment (matheusaaguiar) [inline libyul/AsmParser.cpp]:
```suggestion
	if (indexOutOfRange || sourceIndex < -1 || start < -1 || end < -1)
```
This is equivalent, no?

File: libyul/AsmParser.cpp [hunk 4]
```diff
@@ -192,13 +196,67 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
-		R"~~(("(?:[^"\\]|\\.)*"?)?)~~",                // optional code snippet, e.g.: "string memory s = \"abc\";..."
-		std::regex_constants::ECMAScript | std::regex_constants::optimize
-	);
-	std::match_results<std::string_view::const_iterator> match;
-	if (!regex_search(_arguments.cbegin(), _arguments.cend(), match, argsRegex))
+	std::string const s_args (_arguments);
+	CharStream argumentStream (s_args, "");
+	Scanner scanner (argumentStream);
+
+	int sourceIndex { -1 };
```
Comment (matheusaaguiar) [inline libyul/AsmParser.cpp]: This is more a nitpick, but I think overall in the code we usually don't have spaces before/after "constructor braces".
```suggestion
	int sourceIndex {-1};
```

**Review by matheusaaguiar — COMMENTED** [review]
Just some nitpicks and small suggestions.

**Comment by matheusaaguiar** [comment]
Also, just to confirm/point to, I see that we have some tests in `test/libyul/Parser.cpp` which seems to cover parsing. Not sure if we need or would benefit from adding something more there.

File: libyul/AsmParser.cpp (hunk 4 above)
Comment (cameel) [reply libyul/AsmParser.cpp]: Yeah, this style makes things look so confusing. I see code blocks everywhere :P
```suggestion
	int sourceIndex = -1;
```

File: libyul/AsmParser.cpp [hunk 5]
```diff
@@ -208,13 +266,34 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+		tail = _arguments.substr(static_cast<size_t>(scanner.currentLocation().end));
 
-	if (match[4].matched && (
-		!boost::algorithm::ends_with(match[4].str(), "\"") ||
-		boost::algorithm::ends_with(match[4].str(), "\\\"")
-	))
+	if (snippet && (
+			!boost::algorithm::ends_with(*snippet, "\"") ||
+			boost::algorithm::ends_with(*snippet, "\\\"")
+				))
```
Comment (cameel) [inline libyul/AsmParser.cpp]: The scanner will report `ScannerError::IllegalStringEndQuote` for an unterminated string, so you shouldn't have to check this manually. Check `currentError()` instead.

File: libyul/AsmParser.cpp [hunk 6]
```diff
@@ -208,13 +266,34 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+			auto const endOfLine = _arguments.find_first_of('\n', static_cast<size_t>(scanner.currentLocation().end));
+			snippet = _arguments.substr(static_cast<size_t>(scanner.currentLocation().start), endOfLine);
+			while (!snippet->empty() && isNonBreakingWhitespace(snippet->back()))
+				snippet->remove_suffix(1);
+			if (endOfLine != std::string::npos)
+				tail = _arguments.substr(endOfLine);
+		}
+		else
+			tail = _arguments.substr(static_cast<size_t>(scanner.currentLocation().start));
+	}
```
Comment (cameel) [inline libyul/AsmParser.cpp]: I don't think you need to distinguish newlines from other kind of whitespace. The old regex had no such distinction because `\s` does include newline as well. For example something like this would be parsed just fine:
```yul
    ///
    /// @src
    ///
    /// 1:1:2
    ///
    /// "
    ///
    /// abc
    ///
    /// "
    ///
```
You can check by removing the final `"` - it will complain that the snippet is not terminated.

File: libyul/AsmParser.cpp [hunk 7]
```diff
@@ -208,13 +266,34 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
 		return std::nullopt;
 	}
 
-	solAssert(match.size() == 5, "");
-	std::string_view tail = _arguments.substr(static_cast<size_t>(match.position() + match.length()));
+	if (scanner.peekNextToken() == Token::StringLiteral &&
+		isNonBreakingWhitespace(_arguments[static_cast<size_t>(scanner.currentLocation().end)]))
```
Comment (cameel) [inline libyul/AsmParser.cpp]: I don't think any whitespace is required after the snippet. Something like `@src 1:1:1 "a"c` would be recognized as having a proper snippet with `c` being the tail, so you can drop that part of the `if`.

File: libyul/AsmParser.cpp [hunk 8]
```diff
@@ -192,13 +196,67 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+		scanner.next();
+		std::tie(parsed, exception) = parseIndex(scanner);
+		indexOutOfRange |= exception;
+		if (!parsed)
+			return false;
+		end = *parsed;
+
+		size_t const endIndex = static_cast<size_t>(scanner.currentLocation().end);
+		return scanner.peekNextToken() == Token::EOS || langutil::isWhiteSpace(_arguments[endIndex]);
+	}();
```
Comment (cameel) [inline libyul/AsmParser.cpp]: I think it would be simpler to not convert the number here right away. Instead store the string values in these variables and restore the bit below that converted them using `toInt()`.

You wouldn't need the exception handler (it's already in `toInt()`) and two separate flags (you could drop `indexOutOfRange`).

If you also moved `scanner.next()` into `parseIndex()`, you could reduce this whole bit to more or less this:
```c++
std::optional<std::string> rawSourceIndex = parseIndex(scanner);
std::optional<std::string> rawStart = parseIndex(scanner);
std::optional<std::string> rawEnd = parseIndex(scanner);
```

Comment (cameel) [reply libyul/AsmParser.cpp]: By the way, catching only the specific exception type (i.e. `std::out_of_range`) from `stoi()` is still a good idea though. I'd change that in `toInt()`.

Also, the out of range check really should have been based on some type with well-defined size, e.g. `int64_t` and not something platform-dependent like `int`. I wouldn't necessarily change it here (we can consider it out of scope for this PR), but it does bother me a bit now that I go back to this code :) We do this a lot around the codebase unfortunately, so many validations are (unintentionally) platform-dependent.

Comment (cameel) [inline libyul/AsmParser.cpp]: The old code would not accept whitespace between numbers (or between the sign and the number), yours does. Which is fine, but it is technically a user-visible change so perhaps we should mention that in the changelog.

File: libyul/AsmParser.cpp [hunk 9]
```diff
@@ -192,13 +196,67 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
 {
-	static std::regex const argsRegex = std::regex(
-		R"~~(^(-1|\d+):(-1|\d+):(-1|\d+)(?:\s+|$))~~"  // index and location, e.g.: 1:234:-1
-		R"~~(("(?:[^"\\]|\\.)*"?)?)~~",                // optional code snippet, e.g.: "string memory s = \"abc\";..."
-		std::regex_constants::ECMAScript | std::regex_constants::optimize
-	);
-	std::match_results<std::string_view::const_iterator> match;
-	if (!regex_search(_arguments.cbegin(), _arguments.cend(), match, argsRegex))
+	std::string const s_args (_arguments);
+	CharStream argumentStream (s_args, "");
```
Comment (cameel) [inline libyul/AsmParser.cpp]: This looks like some random leftovers. Was `s_args` meant to be static?

```suggestion
	CharStream argumentStream (std::string(_arguments), "");
```

**Review by cameel — COMMENTED** [review]
This needs a changelog entry for the bugfix.

Also note that github is a bit picky about the `fixes`/`closes` annotation. `fixes issue #15207` did not work, The PR is not connected to the issue and won't close it automatically. You need `Fixes #15207`, i.e. without anything in between the word and the issue number. 

> Also, just to confirm/point to, I see that we have some tests in `test/libyul/Parser.cpp` which seems to cover parsing. Not sure if we need or would benefit from adding something more there.

The repro is a bit large and otherwise trivial, so I think it's ok to skip it.

I think we're missing some coverage for whitespace and newline handling behavior, because the PR passes all tests even though the way it handles whitespace seems to have changed.

File: libyul/AsmParser.cpp (hunk 2 above)
Comment (cameel) [reply libyul/AsmParser.cpp]: It wouldn't work this way because once we call `next()`, the sign is gone and `currentLiteral()` only has the number. We need to combine the strings but then we can just as well combine them as numbers, using multiplication.

File: libyul/AsmParser.cpp (hunk 8 above)
Comment (cameel) [reply libyul/AsmParser.cpp]: Actually, there are probably even more differences. For example Solidity strings can use single quotes too, so those will now be accepted here. I'd just make sure that we don't accept any fancy string syntax like `@src 1:2:3 unicode"..."` or `@src 1:2:3 hex"..."`.

I also noticed one case of unterminated string that would not be recognized as a snippet by the regex: `@src 1:2:3 "`, i.e. just the opening `"` immediately followed by a newline. I think your code will report that as an error. Which is technically breaking, but it's such an obscure corner case that we're probably fine ignoring that fact.

File: libyul/AsmParser.cpp [hunk 10]
```diff
@@ -192,13 +196,67 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+		}
+		catch(std::out_of_range const&)
+		{
+			return std::make_tuple(std::nullopt, true);
+		}
+	};
+	bool success = [&]()
+	{
+		auto [parsed, exception] = parseIndex(scanner);
+		indexOutOfRange |= exception;
```
Comment (nikola-matic) [inline libyul/AsmParser.cpp]: `indexOutOfRange` is just `exception`, no?

Comment (clonker) [reply libyul/AsmParser.cpp]: no, it is called multiple times, if i dont "or" it, i might lose the exception on the way :) like `true -> false -> false` would lead to false when in reality i want to handle the case that any exception occurred for the three blocks

File: libyul/AsmParser.cpp (hunk 4 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: haha ok ok, i see you're not fond of this style, i'll change it

File: libyul/AsmParser.cpp (hunk 5 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: there are cases in which string literals are not detected as such by the scanner, unfortunately:

```js
let y := /** @src 1:96:165  "function f() internal { \"\/** @src 0:6:7 *\/\"; }" */ 128
```

as i am creating a new scanner instance on the comment's content,  the escaping reports back as illegal. I guess I could update the scanner and introduce a new `Kind`, but I thought this was easier for the time being.

File: libyul/AsmParser.cpp (hunk 8 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: ~~it is a small change, might as well do it here~~ nevermind, it does have a bit of a tail to it with the depending data structures :P

File: libyul/AsmParser.cpp (hunk 5 above)
Comment (nikola-matic) [reply libyul/AsmParser.cpp]: The indents here are off by the way.

File: libyul/AsmParser.cpp (hunk 8 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: You are right it will report a syntax error b/c of not terminated quote. I have added an error for hex and unicode strings.

File: libyul/AsmParser.cpp (hunk 5 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: Well I have added a new scanner mode after all, imo becomes much cleaner that way :)

File: Changelog.md [hunk 11]
```diff
@@ -12,6 +12,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * AsmParser: Source location comments no longer rely no regex to be parsed. Whitespaces between the indices as well as single-quoted code snippets are now allowed.
```
Comment (cameel) [inline Changelog.md]:
```suggestion
 * AsmParser: Parsing rules for source location comments have been relaxed: Whitespace between the indices as well as single-quoted code snippets are now allowed.
```

I'd say that the fact that we used a regex is an implementation detail. What's important to the user is that the parsing rules have changed.

File: liblangutil/Scanner.cpp [hunk 12]
```diff
@@ -1023,6 +1036,8 @@ std::tuple<Token, unsigned, unsigned> Scanner::scanIdentifierOrKeyword()
 	auto const token = TokenTraits::fromIdentifierOrKeyword(m_tokens[NextNext].literal);
 	switch (m_kind)
 	{
+	case ScannerKind::SourceLocationComment:
+		[[fallthrough]];
 	case ScannerKind::Solidity:
```
Comment (cameel) [inline liblangutil/Scanner.cpp]: I think `[[fallthrough]]` is only necessary the case has some code in it.

```suggestion
	case ScannerKind::SourceLocationComment:
	case ScannerKind::Solidity:
```

File: libyul/AsmParser.cpp [hunk 13]
```diff
@@ -192,13 +191,40 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+		if (expectTrailingColon)
+			_scanner.next();
+		return decimal;
+	};
+	std::optional<std::string> rawSourceIndex = parseIndex(scanner, true);
+	std::optional<std::string> rawStart = parseIndex(scanner, true);
+	std::optional<std::string> rawEnd = parseIndex(scanner, false);
+
+	bool const successfullyScannedIndices = rawSourceIndex && rawStart && rawEnd;
+	size_t const startIndex = static_cast<size_t>(scanner.currentLocation().start);
```
Comment (cameel) [inline libyul/AsmParser.cpp]: In the context of the scanner we call these "positions" rather than "indices". This is especially important in this function since it can easily be confused with `sourceIndex` which represents some number assigned to the source file, so a completely different thing.

That said, I think the more important bit of information here is "what is it the start of?":

```suggestion
	size_t const snippetStart = static_cast<size_t>(scanner.currentLocation().start);
```

Comment (cameel) [reply libyul/AsmParser.cpp]: I'd also rename `successfullyScannedIndices` to something like `locationScannedSuccessfully`. The part it is scanning is the source location. Source index is only the first component of that. The other two are positions in the source.

Similarly, `parseIndex()` would more accurately be called `parseLocationComponent()`.

File: libyul/AsmParser.cpp [hunk 14]
```diff
@@ -192,13 +191,40 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+	bool success = successfullyScannedIndices && (scanner.peekNextToken() == Token::EOS || (startIndex > 0 && langutil::isWhiteSpace(_arguments[startIndex - 1])));
+
+	if (!success)
```
Comment (cameel) [inline libyul/AsmParser.cpp]: How about this?
```suggestion
	bool locationIsWhitespaceSeparated =
		scanner.peekNextToken() == Token::EOS ||
		(snippetStart > 0 && langutil::isWhiteSpace(_arguments[snippetStart - 1]));

	if (!locationScannedSuccessfully || !locationIsWhitespaceSeparated)
```

File: libyul/AsmParser.cpp [hunk 15]
```diff
@@ -208,13 +234,22 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+
+	if (scanner.currentToken() == Token::HexStringLiteral || scanner.currentToken() == Token::UnicodeStringLiteral)
+	{
+		m_errorReporter.syntaxError(
+			1543_error,
+			_commentLocation,
+			"Invalid code snippet in source location mapping. Hex and unicode strings not allowed."
+		);
+		return {{tail, SourceLocation{}}};
+	}
```
Comment (cameel) [inline libyul/AsmParser.cpp]: This is technically a breaking change. A comment like `/// @src 1:1:1 hex"abc"` would compile fine before and now will result in a compilation error.

We should keep doing what the regex was - assume that if it does not start with `"`, it's not a snippet string but just some random trailing text and ignore it.

File: libyul/AsmParser.cpp [hunk 16]
```diff
@@ -224,30 +259,45 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+	bool const successfullyInterpretedIndices = [&]()
+	{
+		if (successfullyScannedIndices)
+		{
+			auto const indexPairs = { std::tie(rawSourceIndex, sourceIndex), std::tie(rawStart, start), std::tie(rawEnd, end) };
+			for (auto& [rawIndex, interpretedIndex] : indexPairs)
+			{
+				auto const interpreted = toInt(*rawIndex);
+				if (interpreted)
+					interpretedIndex = *interpreted;
```
Comment (cameel) [inline libyul/AsmParser.cpp]: This kind of naming is one of my pet peeves :P Good names for similar (but not identical) things should really focus on what distinguishes them so that you can tell it without too much thinking. Something like this would be much clearer IMO:

```suggestion
				auto const indexOrNull = toInt(*rawIndex);
				if (indexOrNull)
					index = *indexOrNull;
```
This is similar to the `val` vs `value` situation.

Comment (cameel) [reply libyul/AsmParser.cpp]: Also, I think that the whole conversion code here would really be better off if it was much less clever :)

```c++
std::optional<int> const sourceIndex = toInt(*rawSourceIndex);
std::optional<int> const start = toInt(*startIndex);
std::optional<int> const end = toInt(*endIndex);

if (
	!sourceIndex.has_value() || *sourceIndex < -1 ||
	!start.has_value() || *start < -1 ||
	!end.has_value() || *end < -1
)
```

This is more repetitive but also IMO much easier to understand quickly. Especially modifying values through local references makes code more confusing for me. There's too much indirection.

By the way, note that you don't have to check `successfullyScannedIndices` because you already made sure above that it is true.

File: libyul/AsmParser.cpp [hunk 17]
```diff
@@ -224,30 +259,45 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+	else if (!(sourceIndex >= 0 && m_sourceNames->count(static_cast<unsigned>(sourceIndex))))
 		m_errorReporter.syntaxError(
 			2674_error,
 			_commentLocation,
 			"Invalid source mapping. Source index not defined via @use-src."
 		);
 	else
 	{
-		std::shared_ptr<std::string const> sourceName = m_sourceNames->at(static_cast<unsigned>(sourceIndex.value()));
-		solAssert(sourceName, "");
```
Comment (cameel) [inline libyul/AsmParser.cpp:250]: Why remove the assert?

File: liblangutil/Scanner.cpp (hunk 12 above)
Comment (cameel) [reply liblangutil/Scanner.cpp]: But also, might make more sense to have no keywords in this mode rather than just randomly choose the same keywords as in `Solidity` mode :) This would probably solve the problem with `hex`/`unicode` string literals as those would no longer be recognized.

File: liblangutil/Scanner.h [hunk 18]
```diff
@@ -62,15 +62,12 @@
...
-class AstValueFactory;
-class ParserRecorder;
-
 enum class ScannerKind
 {
 	Solidity,
 	Yul,
-	ExperimentalSolidity
+	ExperimentalSolidity,
+	SourceLocationComment
```
Comment (cameel) [inline liblangutil/Scanner.h]:
```suggestion
	SpecialComment,
```

Maybe this would be a better name? I think we'll in the future reuse this mode when reimplementing regexes with scanner, so a more general name would make more sense. Most of those cases are generally in comments and inside quoted strings I think (anything that's proper syntax gets parsed in other modes).

File: libyul/AsmParser.cpp (hunk 5 above)
Comment (cameel) [reply libyul/AsmParser.cpp]: Yeah, a new mode is probably a better idea.

File: liblangutil/Scanner.cpp (hunk 12 above)
Comment (clonker) [reply liblangutil/Scanner.cpp]: `[[fallthrough]]` is never _really_ necessary I guess; no keywords absolutely makes sense to me, I'm changing that :)

File: libyul/AsmParser.cpp (hunk 14 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: yes much better!

File: libyul/AsmParser.cpp (hunk 15 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: Right - I have updated the scanner to not recognize any tokens which indeed fixed this problem. For ex
```
@src 0:111:222 hex"abc"@src 1:333:444 "abc"
```
leads to a tail `hex"abc"@src 1:333:444 "abc"`

File: libyul/AsmParser.cpp (hunk 16 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: Yeah you are right, this reads much better. Guess I was trying to be too clever at the expense of readability :)

File: libyul/AsmParser.cpp (hunk 17 above)
Comment (clonker) [reply libyul/AsmParser.cpp:250]: oops, good question - I don't think it was deliberate

File: libyul/AsmParser.cpp (hunk 8 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: since the scanner in its special comment mode no longer recognizes hex/unicode strings as strings, such fragments immediately go into the tail

**Comment by aarlt** [comment]
I guess you could now also remove the `rm ./*_bytecode_too_large_*.sol ./*_combined_too_large_*.sol` in `.circleci/parallel_bytecode_report.sh` - if I remember correctly, the crashes where mainly happening because of the regexp stuff.

**Comment by cameel** [comment]
> I guess you could now also remove the `rm ./*_bytecode_too_large_*.sol ./*_combined_too_large_*.sol` in `.circleci/parallel_bytecode_report.sh` - if I remember correctly, the crashes where mainly happening because of the regexp stuff.

Looks like it worked. Which is actually odd, because this PR doesn't fix #13496, does it? I mean, if it does then great, maybe we should close it too, but it's also possible that it got somehow fixed on `develop` and we didn't realize :)

File: liblangutil/Scanner.cpp (hunk 12 above)
Comment (cameel) [reply liblangutil/Scanner.cpp]: But I suppose it would generate a warning at least? If so, then for us it is actually necessary, because we treat warnings as errors :)

But yeah, it's of course not wrong to have it, I pointed it out mostly because we never do it in such cases. And I think that's better because it makes the obvious case less verbose.

**Comment by clonker** [comment]
> > I guess you could now also remove the `rm ./*_bytecode_too_large_*.sol ./*_combined_too_large_*.sol` in `.circleci/parallel_bytecode_report.sh` - if I remember correctly, the crashes where mainly happening because of the regexp stuff.
> 
> Looks like it worked. Which is actually odd, because this PR doesn't fix #13496, does it? I mean, if it does then great, maybe we should close it too, but it's also possible that it got somehow fixed on `develop` and we didn't realize :)

It does segfault for me in the issue you linked above on develop and not on this branch when, e.g., invoking `solc --via-ir --asm test.sol`. I assume it is because of the debug comments:

image

Invoking the same with `--debug-info none` does not segfault on develop, either.

**Comment by aarlt** [comment]
> > > I guess you could now also remove the `rm ./*_bytecode_too_large_*.sol ./*_combined_too_large_*.sol` in `.circleci/parallel_bytecode_report.sh` - if I remember correctly, the crashes where mainly happening because of the regexp stuff.
> > 
> > 
> > Looks like it worked. Which is actually odd, because this PR doesn't fix #13496, does it? I mean, if it does then great, maybe we should close it too, but it's also possible that it got somehow fixed on `develop` and we didn't realize :)
> 
> It does segfault for me in the issue you linked above on develop and not on this branch when, e.g., invoking `solc --via-ir --asm test.sol`. I assume it is because of the debug comments:
> 
> image
> 
> Invoking the same with `--debug-info none` does not segfault on develop, either.

yep exactly! its because of the debug comments. I ran into this when I was working on [the debug attribute parsing stuff](https://github.com/ethereum/solidity/pull/14857). I would say we should merge this soon so I can rework my PR.

**Comment by aarlt** [comment]
In general it is a bug in `std::regexp` in some GCC versions that created that segfault.

File: Changelog.md [hunk 19]
```diff
@@ -13,6 +13,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * AsmParser: Parsing rules for source location comments have been relaxed: Whitespace between the indices as well as single-quoted code snippets are now allowed.
```
Comment (aarlt) [inline Changelog.md]: I guess we should also mention that it fixes that regexp segfault: https://github.com/ethereum/solidity/issues/13496.

File: liblangutil/Scanner.cpp [hunk 20]
```diff
@@ -826,31 +826,44 @@ Token Scanner::scanString(bool const _isUnicode)
...
 		char c = m_char;
 		advance();
-		if (c == '\\')
+
+		if (m_kind == ScannerKind::SpecialComment)
 		{
-			if (isSourcePastEndOfInput() || !scanEscape())
-				return setError(ScannerError::IllegalEscapeSequence);
+			if (c == '\\')
+				scanEscape();
```
Comment (cameel) [inline liblangutil/Scanner.cpp]: If I understand this code correctly, this does not quite match the behavior of the original regex. The code here will just skip invalid escape sequences and stray `\` at the end of input. If we want to match the original regex, we'd have to instead:
- not interpret unrecognized escapes, just keep them as is,
- report an unterminated string if we reach `\` at the end of input (well, I guess reporting an illegal escape instead would be fine too, as long as it's still an error).

File: libyul/AsmParser.cpp [hunk 21]
```diff
@@ -192,13 +191,42 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
-		R"~~(("(?:[^"\\]|\\.)*"?)?)~~",                // optional code snippet, e.g.: "string memory s = \"abc\";..."
-		std::regex_constants::ECMAScript | std::regex_constants::optimize
-	);
-	std::match_results<std::string_view::const_iterator> match;
-	if (!regex_search(_arguments.cbegin(), _arguments.cend(), match, argsRegex))
+	CharStream argumentStream (std::string(_arguments), "");
+	Scanner scanner (argumentStream);
+	scanner.setScannerMode(ScannerKind::SpecialComment);
+
+	std::string_view tail { _arguments.substr(_arguments.size()) };
```
Comment (cameel) [inline libyul/AsmParser.cpp]:
```suggestion
	CharStream argumentStream(std::string(_arguments), "");
	Scanner scanner(argumentStream);
	scanner.setScannerMode(ScannerKind::SpecialComment);

	std::string_view tail{_arguments.substr(_arguments.size())};
```

File: libyul/AsmParser.cpp [hunk 22]
```diff
@@ -208,13 +236,12 @@ std::optional<std::pair<std::string_view, SourceLocation>> Parser::parseSrcComme
...
+	if (scanner.currentToken() == Token::StringLiteral || (scanner.currentToken() == Token::Illegal && scanner.currentError() == ScannerError::IllegalStringEndQuote))
+		tail = _arguments.substr(static_cast<size_t>(scanner.currentLocation().end));
+	else
+		tail = _arguments.substr(static_cast<size_t>(scanner.currentLocation().start));
 
-	if (match[4].matched && (
-		!boost::algorithm::ends_with(match[4].str(), "\"") ||
-		boost::algorithm::ends_with(match[4].str(), "\\\"")
-	))
+	if (scanner.currentToken() == Token::Illegal && scanner.currentError() == ScannerError::IllegalStringEndQuote)
```
Comment (cameel) [inline libyul/AsmParser.cpp]: Are errors other than `IllegalStringEndQuote` possible here? If not, I think it would be better to assert that to make that clearer (and then you'd only need a check for illegal token). If they are, then perhaps they should be handed explicitly (or at least acknowledged in a comment).

File: test/libyul/Parser.cpp
Comment (cameel) [inline test/libyul/Parser.cpp:1]: I'd add some tests to cover escape parsing in the new scanner mode (may be be combined into one case if possible):
- Invalid escape sequence in the snippet.
- Valid escape sequence in the snippet (other than `\"`).
- In complete escape at the end of the snippet (`\`).

Comment (cameel) [reply test/libyul/Parser.cpp:1]: We should also have a test with single quotes and whitespace between source location components.

**Review by cameel — COMMENTED** [review]
I think we still need some some adjustments in the scanner and a few more tests. Other than that it looks pretty good now.

File: test/libyul/Parser.cpp
Comment (cameel) [reply test/libyul/Parser.cpp:1]: Oh, and a test for the case you mentioned in https://github.com/ethereum/solidity/pull/15209#discussion_r1648479822 might be a good idea too.

**Comment by cameel** [comment]
> It does segfault for me in the issue you linked above on develop and not on this branch when, e.g., invoking `solc --via-ir --asm test.sol`. I assume it is because of the debug comments:

Ah, right. I focused on parsing the long hex string (which should not be affected by this PR) but overlooked the fact that such a string will also end up in a snippet as a part of debug info. In that case, yeah, this PR does fix it.

File: Changelog.md (hunk 19 above)
Comment (cameel) [reply Changelog.md]: I see you appended it at the end. I think it should have its own entry. It's a proper bugfix.

Also, the original entry about relaxed debug comment parsing should really go under `Language Features:`, with a `Yul: ` prefix. I think we can consider these comments a part of Yul syntax. At least we're parsing them along with the rest of Yul code.

File: liblangutil/Scanner.cpp (hunk 20 above)
Comment (clonker) [reply liblangutil/Scanner.cpp]: Yeah it's true, it wasn't reflecting the RegEx behavior - although snippets are really just skipped during parsing, the important bit is the correct detection of the tail. That being said, it absolutely makes sense to interpret the 'special comment' literal string sensibly. Now everything that is escaped and interpretable is being interpreted as such and the rest is appended verbatim. I have added a couple tests to the scanner for that.

File: test/libyul/Parser.cpp
Comment (clonker) [reply test/libyul/Parser.cpp:1]: added tests except for the comment one, that already existed :)

File: libyul/AsmParser.cpp (hunk 22 above)
Comment (clonker) [reply libyul/AsmParser.cpp]: Yeah they're possible if I have something like `@src 0:111:222 /** something something`; this would pop up as an unterminated comment. But at least in this context here it'll be ignored and put towards the tail s.t. the outer loop over tail ends takes care of it and extracts potential subsequent tags

File: Changelog.md [hunk 23]
```diff
@@ -3,6 +3,7 @@
 Language Features:
  * Accept declarations of state variables with ``transient`` data location (parser support only, no code generation yet).
  * Make ``require(bool, Error)`` available when using the legacy pipeline.
+ * Yul: Parsing rules for source location comments have been relaxed: Whitespace between the indices as well as single-quoted code snippets are now allowed.
```
Comment (cameel) [inline Changelog.md]:
```suggestion
 * Yul: Parsing rules for source location comments have been relaxed: Whitespace between the location components as well as single-quoted code snippets are now allowed.
```

File: Changelog.md [hunk 24]
```diff
@@ -13,6 +14,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * AsmParser: Alleviates risk of encountering a segfault for very long comments.
```
Comment (cameel) [inline Changelog.md]:
```suggestion
 * Yul Parser: Fix segfault when parsing very long location comments.
```

File: test/libyul/Parser.cpp [hunk 25]
```diff
@@ -767,6 +769,106 @@ BOOST_AUTO_TEST_CASE(customSourceLocations_two_locations_with_snippets_untermina
...
+	ErrorReporter reporter(errorList);
+	auto const sourceText = R"(
+		/// @src 0:111:222 "\n\\x\x\w\uö\xy\z\y\fq"
+		{}
+	)";
+	EVMDialectTyped const& dialect = EVMDialectTyped::instance(EVMVersion{});
+	std::shared_ptr<Block> result = parse(sourceText, dialect, reporter);
+	BOOST_REQUIRE(!!result && errorList.size() == 0);
+	// the second source location is not parsed as such, as the hex string isn't interpreted as snippet but
+	// as the beginning of the tail in AsmParser
```
Comment (cameel) [inline test/libyul/Parser.cpp]: Looks like this comment was duplicated, even in tests that do not include the second source location at all :) It should probably have stayed only in the one test where it was relevant?

File: liblangutil/Scanner.cpp [hunk 26]
```diff
@@ -764,7 +764,7 @@ bool Scanner::scanEscape()
 	char c = m_char;
 
 	// Skip escaped newlines.
```
Comment (cameel) [inline liblangutil/Scanner.cpp]: Outdated comment.
```suggestion
	// Normally we ignore the slash just before a newline since it's meaningless.
	// In the "special comment" mode, we preserve it though, like all invalid escapes.
```

File: liblangutil/Scanner.cpp [hunk 27]
```diff
@@ -826,31 +851,44 @@ Token Scanner::scanString(bool const _isUnicode)
...
 		char c = m_char;
 		advance();
-		if (c == '\\')
+
+		if (m_kind == ScannerKind::SpecialComment)
 		{
-			if (isSourcePastEndOfInput() || !scanEscape())
-				return setError(ScannerError::IllegalEscapeSequence);
+			if (c == '\\')
+				scanEscape();
```
Comment (cameel) [inline liblangutil/Scanner.cpp]: It would be more consistent with the other branch to treat unterminated `\` as `IllegalEscapeSequence`. Currently you continue, run `scanEscape()` and then error with `IllegalStringEndQuote` right after the loop.

It does work, but it's still weird to let `scanEscape()` run when we're at the end of input and `m_char` is `0`, which I guess is assumed to never actually be read. The function will actually take that `0` and put into the literal and that literal is still accessible via `currentLiteral()` even when we error out.

Also, you should either handle the return value from `scanEscape()` or assert that it's not supposed to fail:

```suggestion
			if (c == '\\')
			{
				if (isSourcePastEndOfInput())
					return setError(ScannerError::IllegalEscapeSequence);
				bool validEscape = scanEscape();
				solAssert(validEscape);
			}
```

File: liblangutil/Scanner.cpp (hunk 26 above)
Comment (cameel) [reply liblangutil/Scanner.cpp]: Also, one way to make this code more self-explanatory would be to add a meaningfully named parameter (e.g. `_preserveInvalidEscapes` or `_rejectInvalidEscapes` with the opposite meaning) instead of special-casing the `SpecialComment` mode here. It would make it clearer here why we're doing something different in this mode.

Then, at the point of call that would also make it more obvious that the function will behave differently:

```c++
		if (m_kind == ScannerKind::SpecialComment)
		{
			if (c == '\\')
				scanEscape(true /* _preserveInvalidEscapes */);
```

**Review by cameel — DISMISSED** [review]
This generally looks good so I'm approving already.

I still have some final suggestions, mostly regarding wording and comments. The only bigger one would to change how unterminated escapes are handled, though that's not incorrect, just leaves some unexpected artifacts in the (invalid) literal.

File: liblangutil/Scanner.cpp (hunk 20 above)
Comment (cameel) [reply liblangutil/Scanner.cpp]: By the way, the most sensible behavior for such escapes would actually be to report an error, but that's breaking. They should never happen in Yul coming from the codegen and are only possible in user-supplied Yul, so maybe it's acceptable, buy I wouldn't do it in this PR. Maybe this is something that we should consider later though. Really, neither skipping them, nor keeping them "as is" is ideal.

File: libyul/AsmParser.cpp (hunk 22 above)
Comment (cameel) [reply libyul/AsmParser.cpp]: Ah, ok then. Good to have the comment though, it wasn't clear to me that this was the case.

File: liblangutil/Scanner.cpp (hunk 26 above)
Comment (clonker) [reply liblangutil/Scanner.cpp]: True, I have opted for `_rejectInvalidEscapes` since then it's no negations thereof in the implementation (or I would've had to reorganize the if statements).

File: liblangutil/Scanner.cpp (hunk 27 above)
Comment (clonker) [reply liblangutil/Scanner.cpp]: Right! Done that, tests now reflect a case where there's a dangling backslash `R"("test\)"` and a missing string end quote `R"("test)"`.

File: liblangutil/Scanner.cpp [hunk 28]
```diff
@@ -826,31 +852,50 @@ Token Scanner::scanString(bool const _isUnicode)
...
+
+		if (m_kind == ScannerKind::SpecialComment)
 		{
-			if (isSourcePastEndOfInput() || !scanEscape())
-				return setError(ScannerError::IllegalEscapeSequence);
+			if (c == '\\')
+			{
+				if (isSourcePastEndOfInput())
+					return setError(ScannerError::IllegalEscapeSequence);
+				bool const validEscape = scanEscape(false /* _rejectInvalidEscapes */);
```
Comment (ekpyron) [inline liblangutil/Scanner.cpp]: So just that I understand correctly: the only thing you need to do here is to check for escaped quotes, right? Couldn't you do that here directly instead of the entire refactoring of ``scanEscape``? We don't actually do anything with the source quote in the snippets other than discarding them, so not sure why we'd go out of our way to deal with all sorts of escape sequences here...

Comment (clonker) [reply liblangutil/Scanner.cpp]: The change was based off of [this comment](https://github.com/ethereum/solidity/pull/15209#discussion_r1657457198). I am completely fine with just checking for escaped quotes as well - all depends on the intended use of the scanner mode beyond this pr I guess.

Comment (ekpyron) [reply liblangutil/Scanner.cpp]: ``scanEscape(false)`` is generally rather weird, though, isn't it? Either you *want* to properly handle all kinds of escape sequences or you don't, but handling *some* properly and ignoring others is strange, isn't it :-)?
I think the simpler solution to just *only* handle escaped quotes here matches more directly what we need now, and keeps the PR simpler - and if we ever want to use this for anything else we can revisit this then...

Comment (clonker) [reply liblangutil/Scanner.cpp]: We don't even need to check for escaped quotes, this should be enough for the purpose of just skipping over it

```cpp
if (c == '\\')
{
	if (isSourcePastEndOfInput())
		return setError(ScannerError::IllegalEscapeSequence);
	advance();
}
```

Comment (ekpyron) [reply liblangutil/Scanner.cpp]: Yeah, and that's exactly what the regex did, right? Let's just do that then.

Comment (ekpyron) [reply liblangutil/Scanner.cpp]: *Was* a code snippet runinng to EOF here actually even an error before the change :-)?

Comment (clonker) [reply liblangutil/Scanner.cpp]: It would have reported an error because of missing end quote (eg `"literal\` - the `\` is no longer part of the match so the regex would have found `"literal`). Or did you mean in the current develop implementation? [There as well](https://github.com/ethereum/solidity/blob/f3f77208ae3224e89f2b380e6e63796a0e1522eb/liblangutil/Scanner.cpp#L833-L837)

Comment (ekpyron) [reply liblangutil/Scanner.cpp]: Well, when scanning string literals hitting EOF is an error. But I meant, whether it was an error if a source snippet of a comment in Yul, parsed with the regex, it was an error if the quote didn't terminate :-).
Technically, it it *wasn't* an error then, making it an error now is breaking.
There is error 1544_error even before this PR, but will this ever be hit in this case, i.e. will the regex even match that? Ah, the terminating quote there is ``"?`` right? So we do get that error in that case also on develop? Then it's fine.

Comment (ekpyron) [reply liblangutil/Scanner.cpp]: Yeah, the previous condition for error 1544 is rather convoluted, but looks like that's what it did.

File: test/libyul/Parser.cpp [hunk 29]
```diff
@@ -767,6 +769,102 @@ BOOST_AUTO_TEST_CASE(customSourceLocations_two_locations_with_snippets_untermina
...
+BOOST_AUTO_TEST_CASE(customSourceLocations_multi_line_source_loc)
+{
+	ErrorList errorList;
+	ErrorReporter reporter(errorList);
+	auto const sourceText = R"(
+		/// @src 1	: 111:
+		/// 222 "
+		/// abc\"def
+		///
+		/// " @src 0:333:444
```
Comment (ekpyron) [inline test/libyul/Parser.cpp:859]: Where and how does this actually happen now - and how does it prevent
```
/// @src 1:1:1 "
let x := 42
/// "
```
from swallowing the non-comment?

Comment (clonker) [reply test/libyul/Parser.cpp:859]: in the example it'll just skip all escaped stuff, so the snippet amounts to `abcdef`. the non-comment is not swallowed because it will never reach that part of the asmparser, there's an outer loop taking care of that, so only `1:1:1 "` would arrive in `parseSrcComment` and error out with unterminated quote

Comment (clonker) [reply test/libyul/Parser.cpp:859]: so more precisely the input to `parseSrcComment` in the test you referenced up there is (with escapes)

`1\t: 111:\n222 "\nabc\"def\n\n" @src 0:333:444`

for which `(1,111,222)` is identified as components and `abcdef` as snippet (the rest is now skipped by scanner as discussed); everything else goes into the `tail` (being `@src 0:333:444`) which is returned to an outer loop.

The outer loop will match it as source location comment and `parseSrcComment` is called again, this time with `0:333:444` as input.

Comment (ekpyron) [reply test/libyul/Parser.cpp:859]: Ah, the point is that ``Scanner::scanSingleLineDocComment()`` just merges the contents of all consecutive lines starting with ``///`` (but not more than that) - alright!

**Review by ekpyron — APPROVED** [review]
I'd say I'm reasonably convinced by this now and Kamil approved it earlier, so I'm fine with merging after squashing the commits a bit!

**Comment by aarlt** [comment]
Just to leave it here: the segmentation fault was related to a bug in GCC's `std::regex` implementation. This bug is at least reproducible with GCC 9, 10, 11, 12, 13 & 14.
