### PR TITLE
NatSpec newline bugfix 

### LINKED ISSUE #8789: Empty NatSpec comments cause compile error
## Description

A contract with multiple lines of empty NatSpec comments causes a parser error, with a rather misleading error message.

## Environment

- Compiler version: `v0.6.6+commit.6c089d02`, but also with `v0.5.17+commit.d19bba13`
- Target EVM version (as per compiler settings): _compiler default_
- Framework/IDE (e.g. Truffle or Remix): _Remix_

## Steps to Reproduce

```solidity
pragma solidity >=0.6.0;

contract C {
    int x;

    ///
    ///
    function f() public {
        x++;
    }

}
```

Result:
```
browser/C.sol:9:10: ParserError: Expected identifier but got '++'
        x++;
         ^^
```

However, if there is only a single line of empty `///` comment, it successfully compiles.

### LINKED ISSUE #8794: NatSpec comments doesn't finish the block after newline
## Description
The value of `StructuredDocumentation` for the following code should be just ` @author y` instead of `@author x\n @author y`

```solidity
contract C{
/// @author x

/// @author y
function f() public{
}
}
```

### LINKED ISSUE #8820: Inconsistent NatSpec userdoc output
## Description

The userdoc produced by the following code is not consistent:

```solidity
contract test {
	///
	///
	/// @notice hello world
	function f() public {
	}

	/// @notice hello world
	function g() public {
	}

	/**
	 * @notice hello world
	 */
	function k() public {
	}

	/**
	 *
	 *
	 *
	 * @notice hello world
	 */
	function l() public {
	}
}

```

## Environment

- Compiler version: develop

## Steps to Reproduce
`./solc --userdoc <file.sol>`

```json
User Documentation
{
  "methods":
  {
    "f()":
    {
      "notice": " hello world"
    },
    "g()":
    {
      "notice": "hello world"
    },
    "k()":
    {
      "notice": "hello world"
    },
    "l()":
    {
      "notice": "*hello world"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by hrkrshnn**
Fixes https://github.com/ethereum/solidity/issues/8794, Fixes https://github.com/ethereum/solidity/issues/8789, Fixes https://github.com/ethereum/solidity/issues/8820
### Change
For singleline and multiline docstring comments, empty comment strings (except the first one) does not add `\n` character to the structured documentation text. This is because `DocStringParser::parse()` replaces every `\n` character (except the first one) with a space which shows up in the parsed tag.

### CODE REVIEW

File: liblangutil/Scanner.cpp [hunk 1]
```diff
@@ -321,16 +324,18 @@ int Scanner::scanSingleLineDocComment()
 		{
 			// Check if next line is also a single-line comment.
 			// If any whitespaces were skipped, use source position before.
-			if (!skipWhitespace())
+			if (!skipWhitespaceExceptUnicodeLinebreak())
```
Comment (hrkrshnn) [inline liblangutil/Scanner.cpp:327]: This fixes the issue where a line break between two natspec comments will mean end of block for the first one. For e.g., the following is two seperate natspec comments.

```
\\\ hello

\\\ world
```

File: liblangutil/Scanner.cpp [hunk 2]
```diff
@@ -389,9 +394,11 @@ Token Scanner::scanMultiLineDocComment()
 			}
 			else if (!m_source->isPastEndOfInput(1) && m_source->get(0) == '*' && m_source->get(1) != '/')
 			{ // skip first '*' in subsequent lines
+				m_char = m_source->advanceAndGet(1);
```
Comment (hrkrshnn) [inline liblangutil/Scanner.cpp:397]: `m_source->advanceAndGet(1)` instead of `m_source->advanceAndGet(2)` becuase the older one assumes that `*` has to be followed by a space. This cause two problems:
1. Reading past `\n` if `*` is followed by just EOL.
2. Problem with parsing `*@notice`.

Doing so also makes singleline and multiline docstringcomments consistent.

File: test/libsolidity/SolidityScanner.cpp [hunk 3]
```diff
@@ -361,7 +361,7 @@ BOOST_AUTO_TEST_CASE(multiline_documentation_comments_parsed)
 	BOOST_CHECK_EQUAL(scanner.next(), Token::Identifier);
 	BOOST_CHECK_EQUAL(scanner.next(), Token::Identifier);
 	BOOST_CHECK_EQUAL(scanner.next(), Token::EOS);
-	BOOST_CHECK_EQUAL(scanner.currentCommentLiteral(), "Send $(value / 1000) chocolates to the user");
+	BOOST_CHECK_EQUAL(scanner.currentCommentLiteral(), " Send $(value / 1000) chocolates to the user");
```
Comment (hrkrshnn) [inline test/libsolidity/SolidityScanner.cpp:364]: The additional space makes the behavior between singleline and multiline docstring comments consistent. For example, the above code would be similar to 
```
///
/// Send $(value / 1000) chocolates to the user
```

The singleline docstring will parse the space after the second `///`

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Will rebase.

**Comment by axic** [comment]
Why is this breaking?

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
@axic I would say mainly because it changes the behaviour of unicode newlines in `///`-comments. Previously, they were not terminating the comment, if I see that correctly.

**Comment by hrkrshnn** [comment]
@axic The issue https://github.com/ethereum/solidity/issues/8794 was considered as breaking. I think this can also go to develop because it only fixes edge cases that are unlikely to be used, but breaking is a safe option.

**Comment by axic** [comment]
I asked the question because IIRC a somewhat similar issue, #4885, was merged as a non-breaking change (due to the being a security risk).

**Review by chriseth — APPROVED** [review]
