### PR TITLE
Interface inheritance

### LINKED ISSUE #3419: Interfaces can't inherit
The following fails to compile. I make a case here that it should.

```solidity
pragma solidity ^0.5;

interface I1 {
    function a() external;
}

// ✅ Test 1 -- should pass 
interface I2 is I1 {
    function b() external;
}

// ✅ Test 2 -- should pass 
interface I3 is I1 {
    function a() external override(A);
}
```

# Why?

Best practice now is for ERCs to publish a Solidity interface. This defines a standard for compliant contracts to implement.

Examples: [ERC-721](https://eips.ethereum.org/EIPS/eip-721), [ERC-777](https://eips.ethereum.org/EIPS/eip-777), [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155), [ERC-875 (DRAFT)](https://eips.ethereum.org/EIPS/eip-875). (This is every Final and Last Call ERC since 721.)

Very often (most of the above examples) the standards author will specify that implementing a standard requires implementing another standard as a prerequisite. For example to implement ERC-721 it is specified that you must implement ERC-165. To implement the ERC-721 Metadata Extension it is specified that you must first implement ERC-721.

Currently, authors are expressing this in code like:

```solidity
/// @title ERC-721 Non-Fungible Token Standard
/// @dev See https://eips.ethereum.org/EIPS/eip-721
///  Note: the ERC-165 identifier for this interface is 0x80ac58cd.
interface ERC721 /* is ERC165 */ {
    // ...
}
```

This can be adopted formatting in the language.

# Related

- https://github.com/ethereum/solidity/issues/7856

### PR DESCRIPTION
**Pull request by randomnetcat**
Permit interface inheritance. Disallows interfaces overriding functions in parent interfaces.

Fixes #3419.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

File: libsolidity/analysis/OverrideChecker.cpp [hunk 1]
```diff
@@ -781,6 +781,14 @@ void OverrideChecker::checkOverrideList(OverrideProxy _item, OverrideProxyBySign
 			_item.astNodeNameCapitalized() + " has override specified but does not override anything."
 		);
 
+	if (_item.contract().isInterface() && !expectedContracts.empty())
+		overrideListError(
+			_item,
+			expectedContracts,
+			"An interface cannot override function in ",
```
Comment (leonardoalt) [inline libsolidity/analysis/OverrideChecker.cpp]:
```suggestion
			"An interface cannot override function from ",
```
The printed one is the source of the overridden function, isn't it?

File: test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+interface SuperB {
+    function test() external returns (uint256);
+    function testB() external returns (int256);
+}
+
+interface Sub is SuperA, SuperB {
+}
+
+// ----
+// TypeError: (236-271): Derived contract must override function "test". Two or more base classes define function with same name and parameter types.
```
Comment (leonardoalt) [inline test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:15]: This error is kind of correct, but misleading, since once you do override those functions you'll get the error `interfaces can't override`

File: libsolidity/analysis/OverrideChecker.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/analysis/OverrideChecker.cpp]: Also, it then says `from contract...`. It'd be more precise if it says `from interface...`

File: test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol (hunk 2 above)
Comment (randomnetcat) [reply test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:15]: Yeah, I figured this would have to be changed.

File: libsolidity/analysis/OverrideChecker.cpp (hunk 1 above)
Comment (randomnetcat) [reply libsolidity/analysis/OverrideChecker.cpp]: Having it say "contract" was the path of least resistance since that's what `overrideListError` already says. I'll try to find a clean way to change this.

**Comment by randomnetcat** [comment]
Waiting for more precise specification in #3419.

**Comment by randomnetcat** [comment]
Updated per https://github.com/ethereum/solidity/issues/3419#issuecomment-574605621 (which nicely made the code a bit simpler).

Also rebased.

File: test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol (hunk 2 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:15]: Can this now be fixed without errors or not?

**Comment by chriseth** [comment]
Please squash, add a changelog entry, update the documentation and add a semantics test :)

File: test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol (hunk 2 above)
Comment (randomnetcat) [reply test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:15]: Done.

**Comment by randomnetcat** [comment]
Squashed and updated changelog and docs.

**Comment by chriseth** [comment]
Commandline tests failing.

File: docs/contracts/interfaces.rst [hunk 3]
```diff
@@ -8,7 +8,7 @@ Interfaces
 
 Interfaces are similar to abstract contracts, but they cannot have any functions implemented. There are further restrictions:
 
-- They cannot inherit other contracts or interfaces.
+- They cannot inherit other contracts.
```
Comment (chriseth) [inline docs/contracts/interfaces.rst]:
```suggestion
- They cannot inherit from contracts, but they can inherit from other interfaces.
```

File: Changelog.md [hunk 4]
```diff
@@ -3,6 +3,7 @@
 Language Features:
  * Allow accessing external functions via contract and interface names to obtain their selector.
  * Inline Assembly: Support literals ``true`` and ``false``.
+ * Allow interface inheritance.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Allow interfaces to inherit from other interfaces.
```

File: libsolidity/analysis/OverrideChecker.cpp [hunk 5]
```diff
@@ -649,14 +649,19 @@ void OverrideChecker::checkAmbiguousOverrides(ContractDefinition const& _contrac
...
+			checkAmbiguousOverridesInternal(std::move(baseModifiers), _contract.contractKind(), _contract.location());
 		}
 
 	}
 }
 
-void OverrideChecker::checkAmbiguousOverridesInternal(set<OverrideProxy> _baseCallables, SourceLocation const& _location) const
+void OverrideChecker::checkAmbiguousOverridesInternal(set<OverrideProxy> _baseCallables, ContractKind _contractKind, SourceLocation const& _location) const
 {
+	// Ambiguous overrides are acceptable within interfaces because the most-derived contract must eventually deal
```
Comment (chriseth) [inline libsolidity/analysis/OverrideChecker.cpp]: I don't think this will work like expected, because when doing the other checks, we sometimes rely on the fact that all other contracts have been checked already. What happens if you remove this check?

File: test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+    function testA() external returns (int128);
+}
+
+interface SuperB {
+    function test() external returns (uint256);
+    function testB() external returns (int256);
+}
+
+interface Sub is SuperA, SuperB {
+}
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:12]: We should require an override here. This is to explicitly state that the functions inherited from the different interfaces are in fact compatible.

Comment (randomnetcat) [reply test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:12]: Oh, I thought having no error here was what you were asking for at https://github.com/ethereum/solidity/pull/8091#discussion_r368502360. I'll revert that change.

Comment (chriseth) [reply test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:12]: Ah sorry, what I meant was if the smart contract can be changed so that the error disappears :)

File: libsolidity/analysis/OverrideChecker.cpp (hunk 5 above)
Comment (randomnetcat) [reply libsolidity/analysis/OverrideChecker.cpp]: Fixed.

File: test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol (hunk 6 above)
Comment (randomnetcat) [reply test/libsolidity/syntaxTests/inheritance/interface/multiple_parents.sol:12]: It can be, but that's tested elsewhere in `overrides_multiple.sol`, function `test5`.

File: docs/contracts/interfaces.rst [hunk 7]
```diff
@@ -37,10 +37,32 @@ they can be overridden. This does not automatically mean that an overriding func
 can be overridden again - this is only possible if the overriding
 function is marked ``virtual``.
 
+Interfaces can inherit from other interfaces. This, in general, has the same rules as
+for normal contracts, except that an interface does not need to override a function
+that is inherited from two of its parents:
+
+::
+
+    pragma solidity >=0.6.2 <0.7.0;
```
Comment (chriseth) [inline docs/contracts/interfaces.rst]: This is causing a failure, since we have not reached 0.6.2 yet. You can use `>0.6.1`.

File: docs/contracts/interfaces.rst [hunk 8]
```diff
@@ -37,10 +37,32 @@ they can be overridden. This does not automatically mean that an overriding func
 can be overridden again - this is only possible if the overriding
 function is marked ``virtual``.
 
+Interfaces can inherit from other interfaces. This, in general, has the same rules as
+for normal contracts, except that an interface does not need to override a function
```
Comment (chriseth) [inline docs/contracts/interfaces.rst]: This exception has been removed, has it?

File: docs/contracts/interfaces.rst [hunk 9]
```diff
@@ -37,10 +37,32 @@ they can be overridden. This does not automatically mean that an overriding func
...
+        function test() external returns (uint256);
+    }
+
+    interface ParentB {
+        function test() external returns (uint256);
+    }
+
+    interface SubInterface is ParentA, ParentB {
+        // Must redefine test in order to assert that the parent
+        // signatures are compatible.
```
Comment (chriseth) [inline docs/contracts/interfaces.rst]: Not the signatures, the meaning of the function.

File: docs/contracts/interfaces.rst (hunk 7 above)
Comment (randomnetcat) [reply docs/contracts/interfaces.rst]: Fixed.

File: docs/contracts/interfaces.rst (hunk 9 above)
Comment (randomnetcat) [reply docs/contracts/interfaces.rst]: Fixed.

File: docs/contracts/interfaces.rst (hunk 8 above)
Comment (randomnetcat) [reply docs/contracts/interfaces.rst]: Yes, yes it has. Gah, documentation is hard :stuck_out_tongue:.

**Comment by chriseth** [comment]
Nice! Can you squash the commits a little?

**Comment by randomnetcat** [comment]
Squashed.

**Review by chriseth — APPROVED** [review]

**Comment by fulldecent** [comment]
Awesome, thank you for your help on this!

**Comment by kamescg** [comment]
Did this get pushed to production?

What Solidity version is required to implement interface inheritance?

**Comment by chriseth** [comment]
0.6.2
