### PR TITLE
[WIP] Fixes issue where computing storage size for a number would take too long (or even cause a crash).

### LINKED ISSUE #4673: Unexpected hangs on some crafted sol files
Our fuzzer detected that `solc` may hang on some crafted sol files.

The root cause seems to lie at the call to `ReferencesResolver::endVisit` where it eventually calls `dev::bytesRequired<boost::multiprecision::number>`. At https://github.com/ethereum/solidity/blob/bf3682108048fd8646c0388f12ac0647df3099a3/libdevcore/CommonData.h#L184

it would take too long to break out the loop (I'm not familiar with `boost::multiprecision::number`, from multiple runs of the loop, I actually cannot see changes as to the value of `_i`). Boost library version is 1.65.1.0ubuntu1 (Ubuntu 18.04 packaged deb).

Here are some inputs and gdb result (also available [here](https://github.com/ntu-sec/pocs/tree/master/solidity-009a55c8/hangs)):

```solidity
// t1.sol
contract F {
  uint8[12222222222202**-22*-21111111111121][1-22*-21111111111121] i;
}
```

```solidity
contract V {
    uint8[-222222/2.1222E222] i;
}
```

```solidity
contract I {
    uint8[-222222/2.1222E222+-222222222226222222/22/12E222/+22220] i;
}
```

```
contract T {
    int c = int(2* -.1**215);
}
```

```
gdb$ info breakpoints
Num     Type           Disp Enb Address            What
17      breakpoint     keep y   <MULTIPLE>
        breakpoint already hit 3 times
17.1                        y     0x0000000000c09a04 in dev::bytesRequired<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1> >(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
17.2                        y     0x0000000000c0cbbf in dev::bytesRequired<unsigned long>(unsigned long) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
17.3                        y     0x0000000000fb582e in dev::bytesRequired<unsigned int>(unsigned int) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
17.4                        y     0x0000000000fb75f4 in dev::bytesRequired<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> >(boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0>) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
gdb$ r
Starting program: /home/hongxu/FOT/solidity-clang/solc/solc /home/hongxu/FOT/ALL/solidity-009a55c8/hangs/t2.sol
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Breakpoint 17, dev::bytesRequired<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1> > (_i=...) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
184             for (; _i != 0; ++i, _i >>= 8) {}
gdb$ p _i
$36 = {m_backend = {<boost::multiprecision::backends::cpp_int_base<0, 4294967295, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, std::allocator<unsigned long long>, false>> = {<std::allocator<unsigned long long>> = {<__gnu_cxx::new_allocator<unsigned long long>> = {<No data fields>}, <No data fields>}, static limb_bits = 0x40, static max_limb_value = 0xffffffffffffffff, static sign_bit_mask = 0x8000000000000000, static internal_limb_count = 0x2, static variable = 0x1, m_data = {ld = {capacity = 0x2, data = 0x6060000027f0}, la = {0x2, 0x6060000027f0}, first = 0x2, double_first = 0x6060000027f00000000000000002}, m_limbs = 0x1, m_sign = 0x1, m_internal = 0x1}, <No data fields>}}
gdb$ c 1000
Will ignore next 4095 crossings of breakpoint 17.  Continuing.
Breakpoint 17, dev::bytesRequired<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1> > (_i=...) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
184             for (; _i != 0; ++i, _i >>= 8) {}
gdb$ p _i
$37 = {m_backend = {<boost::multiprecision::backends::cpp_int_base<0, 4294967295, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, std::allocator<unsigned long long>, false>> = {<std::allocator<unsigned long long>> = {<__gnu_cxx::new_allocator<unsigned long long>> = {<No data fields>}, <No data fields>}, static limb_bits = 0x40, static max_limb_value = 0xffffffffffffffff, static sign_bit_mask = 0x8000000000000000, static internal_limb_count = 0x2, static variable = 0x1, m_data = {ld = {capacity = 0x1, data = 0x6060000027f0}, la = {0x1, 0x6060000027f0}, first = 0x1, double_first = 0x6060000027f00000000000000001}, m_limbs = 0x1, m_sign = 0x1, m_internal = 0x1}, <No data fields>}}
gdb$ bt
#0  dev::bytesRequired<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1> > (_i=...) at /home/hongxu/FOT/solidity-clang/libdevcore/CommonData.h:184
#1  0x0000000000bdf1ba in dev::solidity::RationalNumberType::fixedPointType (this=0x60e000000590) at /home/hongxu/FOT/solidity-clang/libsolidity/ast/Types.cpp:1261
#2  0x0000000000be39f1 in dev::solidity::RationalNumberType::mobileType (this=0x60e000000590) at /home/hongxu/FOT/solidity-clang/libsolidity/ast/Types.cpp:1215
#3  0x0000000000dcffd2 in dev::solidity::ReferencesResolver::endVisit (this=0x7fffffffa6d8, _typeName=...) at /home/hongxu/FOT/solidity-clang/libsolidity/analysis/ReferencesResolver.cpp:222
#4  0x0000000000e2e008 in dev::solidity::ArrayTypeName::accept (this=0x608000004d30, _visitor=...) at /home/hongxu/FOT/solidity-clang/libsolidity/ast/AST_accept.h:381
#5  0x0000000000e2d6ac in dev::solidity::VariableDeclaration::accept (this=0x60d000000120, _visitor=...) at /home/hongxu/FOT/solidity-clang/libsolidity/ast/AST_accept.h:235
#6  0x0000000000dcdb7b in dev::solidity::ReferencesResolver::resolve (this=0x7fffffffa6d8, _root=...) at /home/hongxu/FOT/solidity-clang/libsolidity/analysis/ReferencesResolver.cpp:42
#7  0x0000000000db5001 in dev::solidity::NameAndTypeResolver::resolveNamesAndTypesInternal (this=0x7fffffffb1d0, _node=..., _resolveInsideCode=0x0) at /home/hongxu/FOT/solidity-clang/libsolidity/analysis/NameAndTypeResolver.cpp:325
#8  0x0000000000db478d in dev::solidity::NameAndTypeResolver::resolveNamesAndTypes (this=0x7fffffffb1d0, _node=..., _resolveInsideCode=0x0) at /home/hongxu/FOT/solidity-clang/libsolidity/analysis/NameAndTypeResolver.cpp:130
#9  0x0000000000db4e1b in dev::solidity::NameAndTypeResolver::resolveNamesAndTypesInternal (this=0x7fffffffb1d0, _node=..., _resolveInsideCode=0x1) at /home/hongxu/FOT/solidity-clang/libsolidity/analysis/NameAndTypeResolver.cpp:297
#10 0x0000000000db478d in dev::solidity::NameAndTypeResolver::resolveNamesAndTypes (this=0x7fffffffb1d0, _node=..., _resolveInsideCode=0x1) at /home/hongxu/FOT/solidity-clang/libsolidity/analysis/NameAndTypeResolver.cpp:130
#11 0x0000000000c8da22 in dev::solidity::CompilerStack::analyze (this=0x614000000240) at /home/hongxu/FOT/solidity-clang/libsolidity/interface/CompilerStack.cpp:203
#12 0x0000000000c8ea86 in dev::solidity::CompilerStack::parseAndAnalyze (this=0x614000000240) at /home/hongxu/FOT/solidity-clang/libsolidity/interface/CompilerStack.cpp:297
#13 0x0000000000c8ec50 in dev::solidity::CompilerStack::compile (this=0x614000000240) at /home/hongxu/FOT/solidity-clang/libsolidity/interface/CompilerStack.cpp:311
#14 0x0000000000b5fde1 in dev::solidity::CommandLineInterface::processInput (this=0x7fffffffbc18) at /home/hongxu/FOT/solidity-clang/solc/CommandLineInterface.cpp:837
#15 0x0000000000ba392a in main (argc=0x2, argv=0x7fffffffbe58) at /home/hongxu/FOT/solidity-clang/solc/main.cpp:59
```

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.25-develop.2018.8.3+commit.009a55c8.Linux.g++
```

### LINKED ISSUE #4717: High CPU usage on conversion between numeric literal and others
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
Use of numeric literal values increases compile time and CPU usage, with a higher delay when bigger, being `0e2147399999` the highest possible. Compiling may take up to several days and more.

## Example codes

```solidity
pragma solidity ^0.4.24;                                                                                                                                                                                                                                             
contract VerySlowContract {                                                                                                                                
  function test() public returns (uint256) {                                                                                                   
    return 0e2147399999;                                                                                                                       
  }                                                                                                                                            
}
```

```solidity
pragma solidity ^0.4.24;
contract VerySlowContract {
   function f() public pure {
       fixed a = 0.E2578125;
   }
}
```


```solidity
pragma solidity ^0.4.24;
contract VerySlowContract {
   uint public a = 0x42 >> 0e100000000;
}
```

This following case only hangs when using a previously defined variable.

```solidity
pragma solidity ^0.4.24;
contract VerySlowContract {
    function f() public {
        fixed256x76 e = -0.9332233548164222222222222222222222222222222222222222222222222222222222222222222222222222222222%2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222/222222222222222222222222222222222222222222222222222222222222222222222222888888888888880079984927635411395646;
        fixed256x76 e = -0.92222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222%2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222%=...*.../....&...=....222222222;
    }
}
```

### PR DESCRIPTION
**Pull request by christianparpart**
Fixes #4673.

### TODO
* [x] create a test case for `fixed8x80 a = -1 / (1e9 ** 10);`
* [x] check if it could also fix #4717.

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -1267,7 +1267,11 @@ shared_ptr<FixedPointType const> RationalNumberType::fixedPointType() const
 	if (v > u256(-1))
 		return shared_ptr<FixedPointType const>();
 
-	unsigned totalBits = max(bytesRequired(v), 1u) * 8;
+	boost::optional<unsigned> requiredBytes = bytesRequired(v, 4096);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I think the issue here might rather be that `bytesRequired` does not handle negative numbers.

**Comment by axic** [comment]
Does this fix #4717 too?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I don't think this is the proper fix. Numbers that are too large should be caught by the `if (v > u256(-1))` check above.

Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: ~~Compare with ``integerType()`` -~~ five lines above in the ``if (negative)`` case ~~the sign should be flipped, but isn't.~~ care has to be taken if ``v`` is zero (might happen due to rounding).

Comment (chriseth) [reply libsolidity/ast/Types.cpp]: I'm pretty sure now that the problem is that in line 1265, we end up with `v==0` and `negativ == true`. In this case, I think the fix would be to change `if (negative)` to `if (negative && v != 0)`, but please provide specific example values first, I would like to know how exactly this situation can happen.

Comment (christianparpart) [reply libsolidity/ast/Types.cpp]: The scenario can be reproduced with `fixed n = 12222222222202 ** -22 * -21111111111121;`.

Comment (christianparpart) [reply libsolidity/ast/Types.cpp]: ah, forgot to mention @chriseth: adding `&& v != 0` in the `if (negative)` fixes it and sets `totalBits` to `8`, which feels right.

File: solc/main.cpp [hunk 2]
```diff
@@ -50,8 +50,16 @@ static void setDefaultOrCLocale()
 #endif
 }
 
+struct T {
+	~T() {
+		cout << "Hit <ENTER> to BREXIT\n";
```
Comment (chriseth) [inline solc/main.cpp]: I guess this is not supposed to be here ;)

File: test/libsolidity/syntaxTests/types/too_large_numbers.sol [hunk 3]
```diff
@@ -0,0 +1,11 @@
+contract C {
+  uint8[-21111111111121 * 12222222222202 ** -22] a;
+  uint8[12222222222202 ** -22 * -21111111111121] b;
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/types/too_large_numbers.sol]: Can you find a minimal example, please? I would assume something like `1e-100` would work.

Comment (chriseth) [reply test/libsolidity/syntaxTests/types/too_large_numbers.sol]: Oh and please rename the test so that it is clear that this is about array sizes.

File: solc/main.cpp (hunk 2 above)
Comment (christianparpart) [reply solc/main.cpp]: irks, I'll squash it away upon next push.

File: test/libsolidity/syntaxTests/types/too_large_numbers.sol (hunk 3 above)
Comment (christianparpart) [reply test/libsolidity/syntaxTests/types/too_large_numbers.sol]: I'm working on getting it as minimal as possible, although, I *think* arrays are just the carrier, as I was able to reproduce the solc-hanging also with simple `fixed a = 12222222222202 ** -22 * -21111111111121;` too. But I'll digg into it again tomorrow.

Comment (christianparpart) [reply test/libsolidity/syntaxTests/types/too_large_numbers.sol]: @chriseth the smallest test case I have found so far to trigger this hang is

`fixed8x80 a = -1 / (1e9 ** 10);`

File: test/libsolidity/syntaxTests/types/too_small_negative_numbers.sol [hunk 4]
```diff
@@ -0,0 +1,4 @@
+contract C {
+  fixed8x80 a = -1 / (1e9 ** 10);
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/types/too_small_negative_numbers.sol]: `fixed8x80 a = -1e-100`; should also work.

Comment (christianparpart) [reply test/libsolidity/syntaxTests/types/too_small_negative_numbers.sol]: Your's is more minimal (and working), so I've changed the test.

**Comment by chriseth** [comment]
Please add a changelog entry.

**Comment by ekpyron** [comment]
Just to make sure: we *do* want ``fractionalDigits`` to be ``80`` for these "infinitesimal" values, although the actual value ends up being zero anyways, which does not require any fractional digits? Probably it does make sense like this.

**Comment by chriseth** [comment]
I wonder about this, too. The comment says "least precision loss", which hints at using `80` digits.

**Comment by ekpyron** [comment]
``@returns the smallest fixed type that can  hold the value or incurs the least precision loss.``
The "smallest fixed type that can hold the value" zero is ``fixed8x0``.
How would one define the "precision loss"? Probably using some error measure like ``abs(value - actual_value)`` or some scaled version of that (like ``abs((value - actual_value) / actual_value)``, if ``actual_value > 0`` - that would be some notion of "relative error"). But that would be the same for any ``fixed8xY`` type, if ``value`` is zero.
So that would hint at ``fixed8x0``.
Independently, an argument for ``fixed8x0`` would be that it may be more obvious that the "actual" fractional part is lost. But I'm not really sure - it still feels like ``fixed8x80`` might makes sense, but I wouldn't know how to actually justify it.

**Comment by chriseth** [comment]
There is no type that can hold the value, `fixed8x0` can only hold the truncated value. If we use `fixed8x80` it at least shows that something was truncated. It also shows that the final value has a distance of at most `1e-80` from the actual value.

Perhaps put differently: If we have to truncate, then the number of digits is as large as possible (so long as the integer part still fits).

**Comment by ekpyron** [comment]
Fair enough, that makes sense. We may want to adjust the comment, though.

**Review by ekpyron — APPROVED** [review]
I'm fine with merging this, so I approve, but I think we should improve the comment explaining the behaviour of ``RationalNumberType::fixedPointType()`` and this PR would be a fitting place to do that as well.

**Review by ekpyron — DISMISSED** [review]
Sorry, forgot that this still has no Changelog entry.

**Review by chriseth — APPROVED** [review]
