### PR TITLE
Produce compiler error for compound division and mod zero operations

### LINKED ISSUE #14702: Division and Modulo by Zero does not produce Compiler Error when using shorthand notation /= and %=
## Description

When performing a Division or Modulo by Zero using the long notation, the compiler reports the 'Division by Zero' or 'Modulo zero' error. When performing the same operations using the shorthand '/=' or '%=' operators, the compiler does not raise any errors, and instead the operation will cause a revert at runtime.
As the shorthand notation is semantically equivalent to the longer syntax, both should produce the same behaviour.

## Environment

- Compiler version: 0.8.23
- Target EVM version (as per compiler settings): Shanghai
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client: Remix VM
- Operating system: macOS 14.1

## Steps to Reproduce

The following two contracts will produce an error on compilation:

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract DivisionByZero {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num = num / 0;
        return num;
    }
}
```
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract ModuloByZero {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num = num % 0;
        return num;
    }
}
```

The following two contracts will compile successfully, and instead revert when calling the function `test()`
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract DivisionByZeroShorthand {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num /= 0;
        return num;
    }
}
```

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.23;
contract ModuloByZeroShorthand {
    function test() public pure returns (uint8) {
        uint8 num = 1;
        num %= 0;
        return num;
    }
}
```

### PR DESCRIPTION
**Pull request by clonker**
Fixes #14702 

As a side-effect, this will change the place in which an error for expressions of the form `a = a / 0` is raised:
- in terms of types, such expressions yield an `IntegerType` on the left-hand side, so no explicit value is associated with it as well
- pretending the lhs to be `0` lets me reuse some of the functionality but it also doesn't 100%ly capture the nature of the problem ("unary `f: x->x/0` is bad")
- without this change, an error for `a=a/0` will be raised in static analyzer. Static analyzer states in its docs, that it has to be possible to write equivalent code that does not generate the warning, so perhaps it was not the right place for raising it to begin with?

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -740,6 +740,18 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
...
 
+	if (auto const* other = dynamic_cast<RationalNumberType const*>(_other); other)
+	{
+		if (_operator == langutil::Token::Mod || _operator == langutil::Token::Div)
+		{
+			std::optional<rational> value = ConstantEvaluator::evaluateBinaryOperator(_operator, {0}, other->value());
+			if (!value)
+			{
+				return nullptr;
+			}
```
Comment (r0qs) [inline libsolidity/ast/Types.cpp]: Maybe we could already do:
```suggestion
			if (std::optional<rational> value = ConstantEvaluator::evaluateBinaryOperator(_operator, {0}, other->value()); !value)
				return nullptr;
```
And then you would remove the curly brackets from all ifs, i.e.:
```c++
	if (auto const* other = dynamic_cast<RationalNumberType const*>(_other); other)
		if (_operator == langutil::Token::Mod || _operator == langutil::Token::Div)
			if(std::optional<rational> value = ConstantEvaluator::evaluateBinaryOperator(_operator, {0}, other->value()); !value)
				return nullptr;
```

We usually don't use them for if-Statements that have only one statement in their body :)

File: test/libsolidity/syntaxTests/literalOperations/mod_zero_compound.sol [hunk 2]
```diff
@@ -0,0 +1,6 @@
+contract A {
+    uint a;
+    constructor() { a = 5; a %= 0; }
+}
+// ----
+// TypeError 7366: (52-58): Operator %= not compatible with types uint256 and int_const 0.
```
Comment (r0qs) [inline test/libsolidity/syntaxTests/literalOperations/mod_zero_compound.sol]: I would expect this to be `TypeError: Modulo zero` and not the error above. This test will succeed if you do `a %= uint(0)`, and it should fail.
```
contract A {
    uint a = 5;
    constructor() { a %= uint(0); }
}
```

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -740,6 +740,18 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
 		return this;
 	}
 
+	if (auto const* other = dynamic_cast<RationalNumberType const*>(_other); other)
+	{
+		if (_operator == langutil::Token::Mod || _operator == langutil::Token::Div)
```
Comment (r0qs) [inline libsolidity/ast/Types.cpp]: I would make this the outermost if, since `other` is not used in this condition but in the one below. Also, the `langutil` namespace is not needed, just use `Token::Mod `

**Review by r0qs — COMMENTED** [review]
Hey @clonker thanks a lot for your contribution. I have some initial comments :)

File: libsolidity/ast/Types.cpp [hunk 4]
```diff
@@ -740,6 +740,18 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
...
+		{
+			std::optional<rational> value = ConstantEvaluator::evaluateBinaryOperator(_operator, {0}, other->value());
```
Comment (r0qs) [inline libsolidity/ast/Types.cpp]: Why not just check `if(other->value().denominator() == 0)`?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (clonker) [reply libsolidity/ast/Types.cpp]: Ah, habits got the better of me :) thanks for the hint!

File: libsolidity/ast/Types.cpp (hunk 4 above)
Comment (clonker) [reply libsolidity/ast/Types.cpp]: yeah that's fair :D good catch

File: test/libsolidity/syntaxTests/literalOperations/mod_zero_compound.sol (hunk 2 above)
Comment (clonker) [reply test/libsolidity/syntaxTests/literalOperations/mod_zero_compound.sol]: Agree, I have updated the constant evaluator to try interpret these elementary type name expressions as well as check compound assignments in the static analyzer. previously also expressions of the form `a = 5 / uint(0)` were not raising any flags.

That being said, I am still unsure whether the static analyzer is the right place to begin with, as there is no "equivalent code" for a division by zero that would be valid :-D
As for the error above, I can see what you mean. The modulo zero stems from static analysis and the one above stems from simply checking types (ie you can't mod uint256 space with {0}). In the implementation right now you would get the type operator error for `a = a % 0` and the type: modulo zero error for `a = a % uint(0)`. It's not ideal!

File: libsolidity/analysis/ConstantEvaluator.cpp [hunk 5]
```diff
@@ -393,3 +393,17 @@ void ConstantEvaluator::endVisit(TupleExpression const& _tuple)
...
+	// try to interpret elementary type name expressions like uint(5)
+	if (auto const* expr = dynamic_cast<ElementaryTypeNameExpression const*>(&_functionCall.expression()))
+		if (auto const* type = expr->annotation().type)
+			if (auto const* typeType = dynamic_cast<TypeType const*>(type); typeType && typeType->actualType())
+			{
+				auto const args = _functionCall.arguments();
+				if (args.size() == 1)
+					if (auto const& val = evaluate(*args.front()))
+						m_values[&_functionCall] = convertType(val, *typeType->actualType());
+			}
```
Comment (nikola-matic) [inline libsolidity/analysis/ConstantEvaluator.cpp]:
```suggestion
	if (auto const* typeType = dynamic_cast<TypeType const*>(expr->annotation().type); typeType->actualType())
	{
		auto const args = _functionCall.arguments();
		if (args.size() == 1)
			if (auto const& val = evaluate(*args.front()))
				m_values[&_functionCall] = convertType(val, *typeType->actualType());
	}
```

Comment (ekpyron) [reply libsolidity/analysis/ConstantEvaluator.cpp]: @nikola-matic We'll remove this part anyways, but the additional ``typeType &&`` part is non-optional here :-).

Comment (nikola-matic) [reply libsolidity/analysis/ConstantEvaluator.cpp]: Won't it short circuit if the typeType is nullptr at assignment?

Comment (ekpyron) [reply libsolidity/analysis/ConstantEvaluator.cpp]: That's not a thing for ``if(init; cond)`` - also couldn't really be, ``init`` is not even required to be convertible to ``bool``.

File: test/libsolidity/syntaxTests/literalOperations/mod_zero_compound.sol (hunk 2 above)
Comment (clonker) [reply test/libsolidity/syntaxTests/literalOperations/mod_zero_compound.sol]: as per discussion, `a %= uint(0)` shall not (statically) raise :)

File: libsolidity/ast/Types.cpp [hunk 6]
```diff
@@ -739,6 +739,10 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
 		}
 		return this;
 	}
+	else if (_operator == Token::Mod || _operator == Token::Div)
+		if (_other->category() == Type::Category::RationalNumber)
+			if (dynamic_cast<RationalNumberType const*>(_other)->value().numerator() == 0)
+				return nullptr;
```
Comment (ekpyron) [inline libsolidity/ast/Types.cpp]: Did you actually in your call earlier conclude that this is the better option :-)? I'd have expected us to just add an analog case to the existing ``Division by/Modulo zero`` errors (with those as error messages) in the ``Assignment`` visitor of the ``StaticAnalyzer`` (but I'm mainly being curious here - for this change I'd need to check, if it actually affects anything else and am surprised that it doesn't e.g. also change the error message for existing ``/ 0`` cases and such)

Comment (cameel) [reply libsolidity/ast/Types.cpp]: We mainly concluded that doing it here produces the same error and in the same cases as the `%` and `/` case, so it should be fine.

Now that you mention it, I haven't actually looked at the place where `%` and `/` are handled currently. But I don't think this is done in `StaticAnalyzer`. Or is it? Will have to check in the final review.

Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: https://github.com/ethereum/solidity/blob/ae79d13a083edcefa2b22e8d4267edcfc5da10f4/libsolidity/analysis/StaticAnalyzer.cpp#L308

I actually also now realized why this change doesn't change the error message in the test for this error: in the test case it's actually an expression on literals there (or well, constants - which are treated as literals).

Anyways - since I also now read in the PR description:
> Static analyzer states in its docs, that it has to be possible to write equivalent code that does not generate the warning, so perhaps it was not the right place for raising it to begin with?

The equivalent code in these cases is ``revert();`` - since that's what a division by zero does :-).

But yeah, none of this matters too much, this was just a random issue to get started anyways.

Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: However, that also explains why we have this weird error in the first place: it wasn't ever meant to apply for runtime divisions, but only for compile-time divisions (and divisions of constants, which are compile-time divisions).

So given that, actually, the better fix here, is in fact (as @cameel, you suggested earlier today in chat) to do the opposite and allow this for runtime division.

Which should be doable by just adding
```
*_operation.leftExpression().annotation().isPure &&
ConstantEvaluator::evaluate(m_errorReporter, _operation.leftExpression())) &&
```
to the condition in https://github.com/ethereum/solidity/blob/ae79d13a083edcefa2b22e8d4267edcfc5da10f4/libsolidity/analysis/StaticAnalyzer.cpp#L300

That should still catch divisions by zero on compile-time evaluated constants - but leave ``uint x; x / 0;`` in peace - and we also solved the inconsistency, since ``/= 0`` is impossible for compile-time constants.

So I'd suggest we just do that instead - but yeah, this was actually a rather weird issue that I picked at random here :-D. The lesson to be learned is: never blindly do exactly what people ask ;-).

Comment (clonker) [reply libsolidity/ast/Types.cpp]: While it's a different issue in a sense, I feel like having a _warning_ regarding div / mod zero (also for compounds) isn't such a bad thing and wouldnt introduce inconsistencies. But yeah, a bit weird :-D

File: Changelog.md [hunk 7]
```diff
@@ -13,6 +13,7 @@ Bugfixes:
  * SMTChecker: Fix internal error when using an empty tuple in a conditional operator.
  * SMTChecker: Fix internal error when using bitwise operators with an array element as argument.
  * Standard JSON Interface: Fix ICE when the optimizer is disabled and an empty/blank string is used for ``optimizerSteps`` sequence.
+ * StaticAnalyzer: Only raise compiler error for div/mod zero when it's between literals.
```
Comment (nikola-matic) [inline Changelog.md]:
```suggestion
 * StaticAnalyzer: Only raise a compile time error for division and modulo by zero when it's between literals.
```

**Review by nikola-matic — DISMISSED** [review]

File: Changelog.md [hunk 8]
```diff
@@ -13,6 +13,7 @@ Bugfixes:
  * SMTChecker: Fix internal error when using an empty tuple in a conditional operator.
  * SMTChecker: Fix internal error when using bitwise operators with an array element as argument.
  * Standard JSON Interface: Fix ICE when the optimizer is disabled and an empty/blank string is used for ``optimizerSteps`` sequence.
+ * StaticAnalyzer: Only raise a compile time error for division and modulo by zero when it's between literals.
```
Comment (r0qs) [inline Changelog.md:16]: Shouldn't we mention that the previous behavior was unintended? I mean, just to make people aware that the compiler will not raise a compile time error anymore for non-literals but only runtime errors.

Maybe something like:

```txt
Previously, compile-time errors were unintentionally raised for division and modulo by zero even when not involving literals.
Moving forward, the compiler will no longer raise compile-time errors for non-literals, only runtime errors.
```

Or we can maybe leave this to be posted in the release blog post?

**Review by r0qs — APPROVED** [review]

File: Changelog.md (hunk 8 above)
Comment (r0qs) [reply Changelog.md:16]: Rethinking about it, maybe that is too big for a changelog entry, so I guess we can just mention it in the release blog post. So I approved the PR ;)

File: libsolidity/ast/Types.cpp (hunk 6 above)
Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: > While it's a different issue in a sense, I feel like having a _warning_ regarding div / mod zero (also for compounds) isn't such a bad thing and wouldn't introduce inconsistencies. But yeah, a bit weird :-D

In principle: yes.
The problem is, that we can't do it well anyways - we don't have full compile-time-constant expression evaluation.
So you'd get a warning for
```
uint x; x / 0;
```
but not for
```
uint x = 1; uint y = 1; uint z;
z / (x - y);
```
So in the end just for the boring and obvious cases - which is arguably worse than not at all...
Conversely, proper compile-time-constant expression evaluation would be nice of course, but also quite a bit of effort, especially since it'd need to match EVM semantics completely accurately.
