### PR TITLE
ViewPureChecker::reportMutability: don't check visibility on constructors.

### LINKED ISSUE #9629: ICE in virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const [assert]
## Description

This contract:
```solidity
contract C {
    constructor() {
		assert(tx.gasprice == msg.value);
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/AST.cpp(294): Throw in function virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.8.7+commit.241a564f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by aarlt**
Fix #9629.

### CODE REVIEW

File: libsolidity/analysis/ViewPureChecker.cpp [hunk 1]
```diff
@@ -274,8 +276,8 @@ void ViewPureChecker::reportMutability(
 				m_errorReporter.typeError(
 					5887_error,
 					_location,
-					"\"msg.value\" and \"callvalue()\" can only be used in payable public functions. Make the function "
-					"\"payable\" or use an internal function to avoid this error."
+					"\"msg.value\" and \"callvalue()\" can only be used in " + mutability + " " + kind + "s. Make the " + kind + " " +
+					"\"payable\"" +  (m_currentFunction->isConstructor() ? "." : " or use an internal " + kind + " to avoid this error.")
```
Comment (hrkrshnn) [inline libsolidity/analysis/ViewPureChecker.cpp]: I think it's just easier to have two error messages.

**Comment by chriseth** [comment]
Please add a changelog entry.

File: libsolidity/analysis/ViewPureChecker.cpp (hunk 1 above)
Comment (aarlt) [reply libsolidity/analysis/ViewPureChecker.cpp]: thats true :)

**Review by hrkrshnn — APPROVED** [review]
