### PR TITLE
Do not push code for `L` in `L.Foo`, an enum Foo defined in a library L

### LINKED ISSUE #1116: Internal Compiler error when trying to access enum value of library.
After much gnashing of teeth I have un-earthed the source of the compiler stack error I've been encountering.

```
library Arst {
    enum Foo {
        Things,
        Stuff
    }
}


contract Tsra {
    Arst.Foo it;

    function thisFails() public returns (bool) {
        if (it == Arst.Foo.Things) {
            return true;
        }
    }

    function thisWorks() public returns (bool) {
        if (uint(it) == 1) {
            return true;
        }
    }
}
```

This produces this error

``` shell
/tmp/solidity-20160908-68021-y1p8zd/solidity-0.3.6/libsolidity/codegen/ContractCompiler.cpp(45): Throw in function void StackHeightChecker::check()
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = I sense a disturbance in the stack.
```

It seems to have to do with trying to access the actual enum values on the `Foo` enum from the library.

### PR DESCRIPTION
**Pull request by pirapira**
Fixes #1116 

Before this pull-request, when a library `L` defines an enum `Foo`, an expression `L.Foo` caused the code generation to visit `L` as well as `Foo`.  This left one more element on the stack than expected.  This pull-request prevents the code generation from visiting `L` in `L.Foo`.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 1]
```diff
@@ -883,6 +884,8 @@ bool ExpressionCompiler::visit(MemberAccess const& _memberAccess)
 					m_context << m_context.functionEntryLabel(*function).pushTag();
 				}
 			}
+			else if (dynamic_cast<TypeType const*>(_memberAccess.annotation().type.get()))
+				; // no-op
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: Style: We usually use

```
{
}
```

for these cases.

Comment (pirapira) [reply libsolidity/codegen/ExpressionCompiler.cpp]: I've changed this.
