### PR TITLE
Fix reversed conditions in `ObjectOptimizer::calculateCacheKey()`

### LINKED ISSUE #15871: Building 0.8.28 on Arch Linux with `CMAKE_BUILD_TYPE=None` hits an assert in `std::optional`: `Assertion 'this->_M_is_engaged()' failed`
I get a lot of these error when running the tests, `./build/test/soltest -p true -- --testpath ./test/`.

```sh
/usr/src/debug/solidity/solidity_0.8.28/test/soltest.cpp(120): error: in "semanticTests/viaYul/return_storage_pointers": Exception during extracted test: /usr/src/debug/solidity/solidity_0.8.28/libsolidity/interface/CompilerStack.cpp(119): Throw in function solidity::frontend::CompilerStack::CompilerStack(solidity::frontend::ReadCallback::Callback)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: You shall not have another CompilerStack aside me.
[solidity::util::tag_comment*] = You shall not have another CompilerStack aside me.
```

It only happens when installing via `makepkg` on Arch Linux but not when executing the same commands on a cloned repository manually. Additional information, I do not have installed z3 or cvc5.

The build script can be inspected [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=solidity).

The issue has to be introduced with version 0.8.27 or 0.8.28 because 0.8.26 worked. I have only tested 0.8.28 now which does not work.

### PR DESCRIPTION
**Pull request by cameel**
Fixes #15871.

The cache key calculation was using reversed values for boolean flags. This was unintended, but wasn't really breaking anything on its own since they can't be read back and it only matters that they are unique. Actual problems started in #15467, where a new entry was based on the incorrect condition, putting code dereferencing an `optional` in the wrong branch.

This started failing a debug assertion in STL, but fortunately does not seem like it could lead to broken output. If the value that ends up getting stored is zero, it will result in EOF and non-EOF compilation getting the same cache key, but it's currently not possible to mix them. If the value is some random garbage from memory, it will lead to identical objects getting different keys, bypassing the cache, but we haven't observed this kind of degradation in benchmarks so far.

### CODE REVIEW

File: libyul/ObjectOptimizer.cpp [hunk 1]
```diff
@@ -154,12 +154,12 @@ std::optional<h256> ObjectOptimizer::calculateCacheKey(
 	rawKey += keccak256(asmPrinter(_ast)).asBytes();
 	rawKey += keccak256(_debugData.formatUseSrcComment()).asBytes();
 	rawKey += h256(u256(_settings.language)).asBytes();
-	rawKey += FixedHash<1>(uint8_t(_settings.optimizeStackAllocation ? 0 : 1)).asBytes();
+	rawKey += FixedHash<1>(uint8_t(_settings.optimizeStackAllocation ? 1 : 0)).asBytes();
```
Comment (clonker) [inline libyul/ObjectOptimizer.cpp]: It's fine now (and also doesn't matter in the sense of clashing hashes) but I do think a static cast to uint8 would have been better than the ternary.

**Review by clonker — DISMISSED** [review]

**Review by clonker — DISMISSED** [review]

File: libyul/ObjectOptimizer.cpp (hunk 1 above)
Comment (cameel) [reply libyul/ObjectOptimizer.cpp]: I wanted to answer that `bool` can have values other than `0` and `1` (even if no one *should* ever do that in practice) so the cast is technically incorrect. But then I found out that I was wrong. I did not expect that, but it makes perfect sense given that it's `static_cast<>` and not `reinterpret_cast<>`:

```c++
static_assert(static_cast<uint8_t>(static_cast<bool>(2)) == 1);
```

TIL.

And just another reason why it's better to avoid the C-style casts. Not sure why I even used one here, it should have been a static cast from the beginning :)

**Review by clonker — APPROVED** [review]

File: libyul/ObjectOptimizer.cpp (hunk 1 above)
Comment (clonker) [reply libyul/ObjectOptimizer.cpp]: Yup - I was confused at first why you kept the ternaries but thought oh well, ternaries plus static cast is still better than c-style cast. :)

Comment (clonker) [reply libyul/ObjectOptimizer.cpp]: And actually I think bool being (on a binary level) something else than the binary representation of `true` and `false` leads to UB
