### PR TITLE
Fix wildcard as output selector in standard JSON

### LINKED ISSUE #6066: Standard-compiler: File-wildcard does not trigger "binariesRequested"
Input:
```
{
	"language": "Solidity",
	"sources":
	{
		"A":
		{
			"content": "pragma solidity >=0.0; contract C { function f() public pure {} }"
		}
	},
	"settings":
	{
		"outputSelection":
		{
			"*": { "C": ["evm.bytecode"] }
		}
	}
}
```

This does not trigger bytecode generation because of the `"*"`-match. The bytecode is part of the output, but empty.

### PR DESCRIPTION
**Pull request by erak**
Fixes https://github.com/ethereum/solidity/issues/6066.

This PR allows to specify sources to be selected for the output via the wildcard `*`:
```
{
	"language": "Solidity",
	"sources":
	{
		"A":
		{
			"content": "pragma solidity >=0.0; contract C { function f() public pure {} }"
		}
	},
	"settings":
	{
		"outputSelection":
		{
			"*": { "C": ["evm.bytecode"] }
		}
	}
}
```

### CODE REVIEW

File: libsolidity/interface/CompilerStack.cpp [hunk 1]
```diff
@@ -397,7 +397,8 @@ bool CompilerStack::isRequestedContract(ContractDefinition const& _contract) con
 	return
 		m_requestedContractNames.empty() ||
 		m_requestedContractNames.count(_contract.fullyQualifiedName()) ||
-		m_requestedContractNames.count(_contract.name());
+		m_requestedContractNames.count(_contract.name()) ||
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp:397]: Just from the context here, I don't understand why this change has the desired effect. Can you explain it?

Comment (erak) [reply libsolidity/interface/CompilerStack.cpp:397]: Oh, I just saw your comment. Of course: if a wildcard for the source name is given, `StandardCompiler::requestedContractNames()` will add the contract with the identifier `:C` instead of `A:C` (if source is `A`). This change adds an additional check for the contract name with the seperator prefix `:`. Another solution would have been to have the wildcard reflected properly instead of implicitly accepting a whitespace, such as `_:A` or something like that.

Comment (leonardoalt) [reply libsolidity/interface/CompilerStack.cpp:397]: Is a name collision possible in that case?

Comment (erak) [reply libsolidity/interface/CompilerStack.cpp:397]: I don't think so, but I'm not 100% sure if I considered all use cases. Say, you would have 2 sources with the same contract, then the wildcard would result in both contracts being selected and compiled. Does that make sense to you?

**Comment by leonardoalt** [comment]
Tests failing. Do the expectations need to be updated?
Also, could you check what we talked about yesterday, if a source is named `:A` and similar cases?

File: libsolidity/interface/CompilerStack.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp:397]: Ok, I see, you have to read that together with StandardCompiler.cpp:113

**Comment by erak** [comment]
@leonardoalt Something is weird here. After rebasing onto develop, the tests are failing again locally. I'll need to look into it.

**Comment by erak** [comment]
@leonardoalt Updated. I've also added some more tests.

**Review by leonardoalt — APPROVED** [review]

**Review by chriseth — APPROVED** [review]
