### PR TITLE
[SMTChecker] Show local variables in cex

### LINKED ISSUE #10786: [SMTChecker] CHC Show local variables in counterexample
Currently only state variables are shown in the counterexample, because we use the summary predicate of the function that caused the target fail which doesn't have local variables.
To show the local variables that cause the target fail, we need to traverse the subgraph of the last transaction and find the first summary (1) that has error > 0.
We also need to add a new rule for each function: currently the error condition adds the rule `function_block(...) && local_constraints => function_summary(error, ...)`. Here we won't have access to the last values of local variables that were assigned in `local_constraints`, so we need to change this to
```
function_block(local_vars, state_vars ...) && local_constraints => function_error(error, local_vars, state_vars ...)`
function_error(error,  local_vars, state_vars ...) => function_summary(error, state_vars ...)
```
So after finding (1) (explained above), it should have one child `function_error` where we can collect the local variables.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/10786

### CODE REVIEW

**Comment by leonardoalt** [comment]
So far this PR adds the extra predicate and rules, but does not output local variables yet.

**Review by blishko — DISMISSED** [review]
LGTM.  I also tried to check the tests and did not find any problem.

I have somewhat philosophical question: It seems to me that by "local variable" we mean any variable local to some scope within a function. This sometimes leads to out-of-scope variables appearing in the output. This can be seen in some of the tests, but is best illustrated  on this example:
```
pragma experimental SMTChecker;
contract C {
	function g(int y) public pure {
		if (y > 0) {
			int x = 1;
			assert(x == 0);
		}
		else {
			int x = 2;
			assert(x == 0);
		}
	}
}
```

This produces the following output:
```
Warning: CHC: Assertion violation happens here.
Counterexample:

y = 1
x = 1
x = 0

Transaction trace:
C.constructor()
C.g(1)
 --> test.sol:6:4:
  |
6 | 			assert(x == 0);
  | 			^^^^^^^^^^^^^^

Warning: CHC: Assertion violation happens here.
Counterexample:

y = 0
x = 0
x = 2

Transaction trace:
C.constructor()
C.g(0)
  --> test.sol:10:3:
   |
10 | 		assert(x == 0);
   | 		^^^^^^^^^^^^^^
```

Both versions of variable `x` appear in the output and this is quite confusing in my opinion.
Would it be possible to limit the local variables on the output to only those that are still in-scope at the moment of the error?

**Comment by leonardoalt** [comment]
Good example!
I think that should be possible, although not so easy. Expressions are not scopable in the AST afaik, so I'm not sure how we can collect only the VariableDeclarations in the same scope as the verification target.
@chriseth any idea?

**Comment by chriseth** [comment]
As far as I know, the scopes only exist during the "reference resolution" step. It might be good to keep them alive for longer, I wanted to have that feature for other use-cases, too.

**Comment by leonardoalt** [comment]
@chriseth wouldn't it work simply by making `Expression: Scopable` and relying on `Scoper`?

**Comment by chriseth** [comment]
Oh wait, right! Expressions are not Scopable, but the declarations of the variables are. Just store the current scope (whenever you visit something that derives from Scope) and check if the annotation().scope of the declaration of the variable is in the stack of current scopes.

**Comment by leonardoalt** [comment]
Ah, right! That works

**Comment by leonardoalt** [comment]
Added the fix: keep track of a stack of scopes, by pushing every ScopeOpener node, and when a Predicate is created, copy the current scope stack. During cex generation, only report local variables whose scope is in the stack.

In the latest commit you can see that many of those were fixed from the first commit, including try/catch clauses, branches, modifiers, etc, so I didn't add new tests.

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -382,6 +406,8 @@ bool CHC::visit(WhileStatement const& _while)
 
 bool CHC::visit(ForStatement const& _for)
 {
+	m_scopes.push_back(&_for);
```
Comment (blishko) [inline libsolidity/formal/CHC.cpp:411]: I am not sure I understand why you need to explicitly do this for the `ForStatement` but not for the `WhileStatement` or the `IfStatement`. Can you explain? The other cases are covered by remembering `Block` scope, right? Why not also this one?

Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp:411]: Yes, `while` and `if` are not ScopeOpeners, rather their `Block`s are. `ForStatement` is also a `ScopeOpener` because its initialization part may declare new variables that are not inside the block, but neither outside of the `ForStatement`.

Comment (blishko) [reply libsolidity/formal/CHC.cpp:411]: Makes sense, thanks.

File: libsolidity/formal/Predicate.cpp [hunk 2]
```diff
@@ -334,8 +337,25 @@ vector<optional<string>> Predicate::localVariableValues(vector<smtutil::Expressi
 	auto first = _args.end() - static_cast<int>(localVars.size());
 	vector<smtutil::Expression> outValues(first, _args.end());
 
-	auto outTypes = applyMap(localVars, [](auto _var) { return _var->type(); });
-	return formatExpressions(outValues, outTypes);
+	auto inScope = [this](auto _var) -> bool {
+		for (auto _scope: m_scopeStack)
+		{
+			auto scope = dynamic_cast<ScopeOpener const*>(_var->scope());
+			solAssert(scope, "");
```
Comment (blishko) [inline libsolidity/formal/Predicate.cpp]: The definition of `scope` can be moved outside the for loop.
Actually, this whole lambda could be replace by `std::find` for `_var->scope` and `m_scopeStack`. Not sure if there is any util functions here that would avoid the iterators in this case.

**Review by blishko — COMMENTED** [review]
I have checked only the latest commit now, but it looks good and according to the tests, it works nicely. Left just one comment.

File: libsolidity/formal/Predicate.cpp (hunk 2 above)
Comment (leonardoalt) [reply libsolidity/formal/Predicate.cpp]: Fixed

File: libsolidity/formal/CHC.cpp [hunk 3]
```diff
@@ -1584,6 +1638,32 @@ optional<string> CHC::generateCounterexample(CHCSolverInterface::CexGraph const&
 				auto const& outParams = calledFun->returnParameters();
 				if (auto outStr = formatVariableModel(outParams, outValues, "\n"); !outStr.empty())
 					localState += outStr + "\n";
+
+				optional<unsigned> localErrorId;
+				solidity::util::BreadthFirstSearch<unsigned> bfs{{summaryId}};
+				bfs.run([&](auto _nodeId, auto&& _addChild) {
+					auto const& edges = _graph.edges.at(_nodeId);
```
Comment (mijovic) [inline libsolidity/formal/CHC.cpp]: Maybe better name would be `children`?

File: libsolidity/formal/CHC.cpp [hunk 4]
```diff
@@ -1584,6 +1638,32 @@ optional<string> CHC::generateCounterexample(CHCSolverInterface::CexGraph const&
...
+					if (edges.size() == 1)
+					{
+						auto const* child = nodePred(edges.front());
+						if (child->isFunctionErrorBlock())
```
Comment (mijovic) [inline libsolidity/formal/CHC.cpp]:
```suggestion
						if (nodePred(edges.front())->isFunctionErrorBlock())
```

File: libsolidity/formal/CHC.cpp [hunk 5]
```diff
@@ -1584,6 +1638,32 @@ optional<string> CHC::generateCounterexample(CHCSolverInterface::CexGraph const&
...
+						{
+							localErrorId = edges.front();
+							bfs.abort();
+						}
+					}
+					for (auto c: edges)
+						_addChild(c);
```
Comment (mijovic) [inline libsolidity/formal/CHC.cpp]: Is it better using something like `std::for_each` in such cases?

File: libsolidity/formal/CHC.cpp [hunk 6]
```diff
@@ -1584,6 +1638,32 @@ optional<string> CHC::generateCounterexample(CHCSolverInterface::CexGraph const&
...
+				});
+
+				if (localErrorId.has_value())
+				{
+					auto const* localError = nodePred(*localErrorId);
+					solAssert(localError && localError->isFunctionErrorBlock(), "");
+					auto [localValues, localVars] = localError->localVariableValues(nodeArgs(*localErrorId));
```
Comment (mijovic) [inline libsolidity/formal/CHC.cpp]:
```suggestion
					auto const& [localValues, localVars] = localError->localVariableValues(nodeArgs(*localErrorId));
```

File: libsolidity/formal/Predicate.cpp [hunk 7]
```diff
@@ -50,20 +51,22 @@ Predicate const* Predicate::create(
 	return &m_predicates.emplace(
 		std::piecewise_construct,
 		std::forward_as_tuple(functorName),
-		std::forward_as_tuple(move(predicate), _type, _node, _contractContext)
+		std::forward_as_tuple(move(predicate), _type, _node, _contractContext, move(_scopeStack))
```
Comment (mijovic) [inline libsolidity/formal/Predicate.cpp:54]: You can't get rid of `std::` here?

File: libsolidity/formal/Predicate.cpp [hunk 8]
```diff
@@ -308,6 +326,31 @@ vector<optional<string>> Predicate::summaryPostOutputValues(vector<smtutil::Expr
 	return formatExpressions(outValues, outTypes);
 }
 
+pair<vector<optional<string>>, vector<VariableDeclaration const*>> Predicate::localVariableValues(vector<smtutil::Expression> const& _args) const
+{
+	/// The signature of a local block predicate is: block(error, this, abiFunctions, cryptoFunctions, txData, preBlockchainState, preStateVars, preInputVars, postBlockchainState, postStateVars, postInputVars, outputVars, localVars).
```
Comment (mijovic) [inline libsolidity/formal/Predicate.cpp]: I think we should split to two lines here, in order to increase readability
```suggestion
	/// The signature of a local block predicate is: 
	/// block(error, this, abiFunctions, cryptoFunctions, txData, preBlockchainState, preStateVars, preInputVars, postBlockchainState, postStateVars, postInputVars, outputVars, localVars).
```

**Review by mijovic — COMMENTED** [review]
Just a few small comments, other than that looks good

File: libsolidity/formal/CHC.cpp (hunk 5 above)
Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: I don't like `std::for_each` because it takes iterators instead of the container. But I replaced it by `ranges::for_each` which takes the container

File: libsolidity/formal/CHC.cpp (hunk 6 above)
Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: The values are moved out of the function, so not much use it making it a `ref`, but I made it `const`.

File: libsolidity/formal/Predicate.cpp (hunk 7 above)
Comment (leonardoalt) [reply libsolidity/formal/Predicate.cpp:54]: we could, but in this case I'd prefer to have it explicit

File: libsolidity/formal/Predicate.cpp (hunk 8 above)
Comment (leonardoalt) [reply libsolidity/formal/Predicate.cpp]: Done

**Comment by leonardoalt** [comment]
Updated & rebased

**Review by mijovic — DISMISSED** [review]

**Comment by mijovic** [comment]
Ah, the tests are failing

**Comment by leonardoalt** [comment]
Fixed

**Comment by leonardoalt** [comment]
And squashed

**Review by mijovic — DISMISSED** [review]

File: Changelog.md [hunk 9]
```diff
@@ -6,8 +6,7 @@ Language Features:
 Compiler Features:
  * Commandline Interface: Model checker option ``--model-checker-targets`` also accepts ``outOfBounds``.
  * Low-Level Inliner: Inline ordinary jumps to small blocks and jumps to small blocks that terminate.
- * SMTChecker: Report out of bounds index access for arrays and fixed bytes.
- * Standard JSON: Model checker option ``settings.modelChecker.targets`` also accepts ``outOfBounds``.
```
Comment (blishko) [inline Changelog.md:10]: Why are you removing the changelog entries from your last PR?

Comment (leonardoalt) [reply Changelog.md:10]: I don't know

Comment (leonardoalt) [reply Changelog.md:10]: Fixed :grimacing:

**Comment by leonardoalt** [comment]
@mijovic can you reapprove?

**Review by mijovic — APPROVED** [review]
