### PR TITLE
 Fix CompilerStack::loadMissingSources()

### LINKED ISSUE #8102: The first 256 errors should be shown when aborting with "too many errors".
Reported by @MicahZoltu.
In case there are more than 256 errors, we abort with an exception - but we should at least show the first 256 errors in the exception message.

Reported for 0.5.15.
I haven't confirmed it myself yet.

EDIT: reported for solc-js using standard-json, but I haven't been able to reproduce with our test file, so waiting for more input.

### PR DESCRIPTION
**Pull request by aarlt**
An exception was not caught within `CompilerStack::loadMissingSources()`, if more than 256 errors where detected. 

The main problem related to #8102 was that the used standard-json tried to import a lot of additional `*.sol` files that where not present. These errors exceeded the 256 error count limit and finally ended up with an `FatalError` exception. I added an additional test `test/libsolidity/syntaxTests/more_than_256_importerrors.sol` to cover those kind of errors.

### CODE REVIEW

**Comment by aarlt** [comment]
Looks like that there is a caching issue on CircleCI.

File: liblangutil/ErrorReporter.cpp [hunk 1]
```diff
@@ -39,6 +39,9 @@ ErrorReporter& ErrorReporter::operator=(ErrorReporter const& _errorReporter)
 
 void ErrorReporter::warning(string const& _description)
 {
+	if (_description == "This is a pre-release compiler version, please do not use it in production.")
```
Comment (chriseth) [inline liblangutil/ErrorReporter.cpp]: What is the purpose of this line?

File: liblangutil/ErrorReporter.h [hunk 2]
```diff
@@ -147,6 +147,10 @@ class ErrorReporter
 	unsigned m_errorCount = 0;
 	unsigned m_warningCount = 0;
 
+	// currently only used within checkForExcessiveErrors(..)
```
Comment (chriseth) [inline liblangutil/ErrorReporter.h]: I don't think it is a clean strategy to treat that warning specially.

File: liblangutil/ErrorReporter.cpp [hunk 3]
```diff
@@ -97,27 +100,29 @@ bool ErrorReporter::checkForExcessiveErrors(Error::Type _type)
...
 	else
 	{
 		m_errorCount++;
 
-		if (m_errorCount > c_maxErrorsAllowed)
+		if (m_errorCount == c_maxErrorsAllowed + 1)
 		{
 			auto err = make_shared<Error>(Error::Type::Warning);
-			*err << util::errinfo_comment("There are more than 256 errors. Aborting.");
+			*err << util::errinfo_comment("There are more than 256 errors. Ignoring the rest.");
```
Comment (chriseth) [inline liblangutil/ErrorReporter.cpp]: I think we should really abort instead of just ignoring.

**Comment by chriseth** [comment]
Warnings were treated differently than errors because we continue after 256 warnings. For errors we really abort. The difference is that compilation can still work with just warnings, but it failed already with at least one error. Please try to see if the fatal error exception is just not caught properly.

File: liblangutil/ErrorReporter.cpp (hunk 1 above)
Comment (aarlt) [reply liblangutil/ErrorReporter.cpp]: On CircleCI a release version is build. So on CircleCI where will be always one warning less than in on a developers machine using a pre-release build.

File: liblangutil/ErrorReporter.cpp (hunk 3 above)
Comment (aarlt) [reply liblangutil/ErrorReporter.cpp]: And why?

File: liblangutil/ErrorReporter.h (hunk 2 above)
Comment (aarlt) [reply liblangutil/ErrorReporter.h]: Yeah I was also not very sure how to deal with this. At least for now this is the simplest solution that  I have found so far.

File: liblangutil/ErrorReporter.cpp (hunk 3 above)
Comment (chriseth) [reply liblangutil/ErrorReporter.cpp]: The idea behind this was that continuing the compilation just eats resources needlessly.

File: liblangutil/ErrorReporter.cpp (hunk 1 above)
Comment (chriseth) [reply liblangutil/ErrorReporter.cpp]: It actually builds both versions on CircleCI. Maybe the syntax test framework is no the right place to test this, then.

**Comment by aarlt** [comment]
Ok I will look into how we can do the abort.

**Comment by chriseth** [comment]
@aarlt what is the status here?

**Comment by aarlt** [comment]
@chriseth I think its ready.

**Comment by aarlt** [comment]
@chriseth hmm.. looked at the code again.. I think its better to move that catch to the parse function

File: libsolidity/interface/CompilerStack.cpp [hunk 4]
```diff
@@ -243,26 +243,34 @@ bool CompilerStack::parse()
...
+					string const& newContents = newSource.second;
+					m_sources[newPath].scanner = make_shared<Scanner>(CharStream(newContents, newPath));
+					sourcesToParse.push_back(newPath);
+				}
 			}
 		}
 	}
+	catch(FatalError const&)
+	{
+		// no-op
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: The yunciton `Parser::parse` correctly catches fatal errors, but `loadMissingSources` does not. Maybe it would be more consistent to catch the fatal error there.

Comment (aarlt) [reply libsolidity/interface/CompilerStack.cpp]: thats true..

File: libsolidity/interface/CompilerStack.cpp [hunk 5]
```diff
@@ -906,35 +906,42 @@ StringMap CompilerStack::loadMissingSources(SourceUnit const& _ast, std::string
...
+						string("Source \"" + importPath + "\" not found: " + result.responseOrErrorMessage)
+					);
+					continue;
+				}
 			}
-		}
+	}
+	catch(FatalError const&)
+	{
+		// no-op
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Please add an assertion that the error reporter has an error.

File: libsolidity/interface/CompilerStack.cpp [hunk 6]
```diff
@@ -906,35 +906,42 @@ StringMap CompilerStack::loadMissingSources(SourceUnit const& _ast, std::string
...
+					m_errorReporter.parserError(
+						import->location(),
+						string("Source \"" + importPath + "\" not found: " + result.responseOrErrorMessage)
+					);
+					continue;
+				}
 			}
-		}
+	}
+	catch(FatalError const&)
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]:
```suggestion
	catch (FatalError const&)
```

File: libsolidity/interface/CompilerStack.cpp [hunk 7]
```diff
@@ -906,35 +906,42 @@ StringMap CompilerStack::loadMissingSources(SourceUnit const& _ast, std::string
...
+						string("Source \"" + importPath + "\" not found: " + result.responseOrErrorMessage)
+					);
+					continue;
+				}
 			}
-		}
+	}
+	catch (FatalError const&)
+	{
+		assert(m_errorReporter.hasErrors());
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]:
```suggestion
		solAssert(m_errorReporter.hasErrors(), "");
```

**Comment by chriseth** [comment]
Please squash.

**Review by chriseth — APPROVED** [review]
