### PR TITLE
`b_alpine_docker` CI run

### LINKED ISSUE #14816: Fix release docker build (alpine) and add a nightly CI run
During 0.8.24 release we discovered that [`docker_deploy_manual.sh`](https://github.com/ethereum/solidity/blob/develop/scripts/docker_deploy_manual.sh) fails to build due to a missing include. A trivial problem that should have been discovered in CI, but apparently none of our other jobs build in an environment where it is detected as an error.

This is very problematic if it happens during release, because after the code is tagged, we can no longer build it in that environment and still claim it was built from the same source. In the end we had to fix it by hacking the normal static linux build into the image.

First, we need to fix the problem so that the image can be built. I'd also suggest to add a flag in `docker_deploy_manual.sh` that allows building locally without necessarily immediately deploying the image to dockerhub.

Second, we should really have a CI run that builds this image. We don't need it on every PR, but we should at least include in the nightly run.

### PR DESCRIPTION
**Pull request by cameel**
Fixes #14816.

The PR makes it possible to run `docker_deploy_manual.sh` without getting a new checkout of the repo or pushing the resulting image. With that we can run the build in CI and avoid breakage suddenly appearing during releases.

I'm also removing support for the `release` branch, which we no longer use.

Still a draft, because I made it run in PRs to test it. When it succeeds, I'm going to remove the commit that enables it and make it reviewable.

### CODE REVIEW

**Comment by cameel** [comment]
Note that this job us using a remote Docker container, which is where the docker build and execution happens. This means that we're actually paying for two containers running at the same time. This is a medium-sized Linux container though and those are relatively cheap so it does not make that much difference. And the job is going to only run nightly which makes it a complete non-issue.

Pricing details:
- [CircleCI pricing > Linux VM / (x86) Remote Docker](https://circleci.com/pricing/price-list/#linux)
- [Changes to Remote Docker Reporting & Pricing](https://discuss.circleci.com/t/changes-to-remote-docker-reporting-pricing/47759)

**Comment by cameel** [comment]
Looks like it builds and passes my smoke test: https://app.circleci.com/pipelines/github/ethereum/solidity/35754/workflows/48ffdd06-d6cc-41e2-81d9-81629af74447/jobs/1627821/steps

File: scripts/docker_deploy_manual.sh [hunk 1]
```diff
@@ -2,26 +2,43 @@
...
+else
+    repo_url=https://github.com/ethereum/solidity.git
+fi
+
+if (( $# >= 3 )); then
+    [[ $3 == --no-push ]] || fail "Invalid flag: $3. Expected --no-push."
+    publish=false
+else
+    publish=true
+fi
```
Comment (r0qs) [inline scripts/docker_deploy_manual.sh]: I guess we could rewrite this part to something like:
```suggestion

if (( $# < 1 || $# > 3 )); then
    fail "Usage: $0 <tag/branch> [repo URL] [--no-push]"
fi

branch="$1"
repo_url="${2:-https://github.com/ethereum/solidity.git}"
if (( $# == 3 )); then
    [[ $3 == --no-push ]] || fail "Invalid flag: $3. Expected --no-push."
    publish=false
else
    publish=true
fi
```

**Review by r0qs — COMMENTED** [review]
LGTM besides the unrelated test failing in the CI. But I have one comment about the script :)

File: scripts/docker_deploy_manual.sh (hunk 1 above)
Comment (cameel) [reply scripts/docker_deploy_manual.sh]: True, that's better.

Done.

**Review by r0qs — APPROVED** [review]
