### PR TITLE
Checking experimental pragmas in the right source unit when compiling modifiers and inherited functions

### LINKED ISSUE #9969: ICE in loadFromMemoryHelper() when ABIEncoderV1 code uses a modifier or inherits a function that calls ABIEncoderV2 code
Extracted from https://github.com/ethereum/solidity/issues/8379#issuecomment-704342651

## Steps to Reproduce
`a.sol`:
```solidity
pragma experimental ABIEncoderV2;

struct Data {
    bool flag;
}

contract A {
    function get() public view returns (Data memory) {}
}
```
`b.sol`:
```solidity
pragma experimental ABIEncoderV2;

import "./a.sol";

contract B {
    modifier validate() {
        A(0x00).get();
        _;
    }
}
```
`c.sol`:
```solidity
import "./b.sol";

contract C is B {
    function foo()
        public
        validate()
    {}
}
```
Run it with:
```bash
solc c.sol
```
Output:
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/CompilerUtils.cpp(1440): Throw in function unsigned int solidity::frontend::CompilerUtils::loadFromMemoryHelper(const solidity::frontend::Type&, bool, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

## Environment
- Compiler version: 0.7.2+commit.51b20bc0.Linux.g++

### PR DESCRIPTION
**Pull request by cameel**
Fixes #9969.

~Needs more tests. I haven't really tested it with experimental pragmas other than `ABIEncoderV2`.~
- Done. This does not really affect the SMTChecker pragma because it's not used in the codegen. And those two are the only experimental pragmas we have now (not counting those test pragmas prefixed with `_`).

### CODE REVIEW

**Comment by cameel** [comment]
The PR is ready for review now.

All the included test cases are things that cause an ICE without this fix, except for `v1_modifier_overriding_v2_modifier.sol` which preempts ABIEncoderV2 by overriding the modifier.

File: libsolidity/codegen/ContractCompiler.cpp [hunk 1]
```diff
@@ -1321,14 +1323,22 @@ void ContractCompiler::appendModifierOrFunctionCode()
...
 			codeBlock = &modifier.body();
+			experimentalFeaturesInside = modifier.sourceUnit().annotation().experimentalFeatures;
 		}
 	}
 
 	if (codeBlock)
 	{
+		std::set<ExperimentalFeature> experimentalFeaturesOutside = m_context.experimentalFeaturesActive();
+		solAssert(experimentalFeaturesInside.has_value(), "experimentalFeaturesInside not initialized");
+		m_context.setExperimentalFeatures(experimentalFeaturesInside.value());
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]: Wouldn't this also work?
```suggestion
		m_context.setExperimentalFeatures(codeBlock->sourceUnit().annotation().experimentalFeatures);
```

Comment (cameel) [reply libsolidity/codegen/ContractCompiler.cpp]: Probably :) I didn't realize I could just check the source unit of a block :)

Comment (cameel) [reply libsolidity/codegen/ContractCompiler.cpp]: Done.

I also removed the assert that checks that the experimental feature status does not change inside because I noticed that `accept()` on an AST node cannot really modify the context.

**Review by chriseth — APPROVED** [review]
