### PR TITLE
[YUL] Remove unused function parameters

### LINKED ISSUE #6449: [Yul] Optimizer: Remove unused function parameters
If a parameter is not used in a function, it can be removed. The same is true for return variables.

Call sites have to be modified accordingly, which will be much simpler if the code is in SSA form prior to this step. Note that we cannot assume SSA form for one specific edge case: If the function is used as the condition of a for loop. If the function's return variable turns out to be unused, we can _almost_ replace the function by the constant zero. The only problem are non-movable function arguments. They would have to be copied to right before the loop and to the end of the post part. Perhaps it is better to fail in this case...

### PR DESCRIPTION
**Pull request by hrkrshnn**
Closes https://github.com/ethereum/solidity/issues/6449

### CODE REVIEW

File: libyul/optimiser/UnusedFunctionArgumentPruner.h [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+	solidity is distributed in the hope that it will be useful,
+	but WITHOUT ANY WARRANTY; without even the implied warranty of
+	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+	GNU General Public License for more details.
+
+	You should have received a copy of the GNU General Public License
+	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
+*/
+/**
+ * UnusedFunctionArgumentPruner: Optimiser step that removes unused-parameters in a function.
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.h]: Why not `UnusedFunctionParameterPruner`?
Also please move this comment right above the struct instead of the top of the file.

File: libyul/optimiser/UnusedFunctionArgumentPruner.h [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+ *
+ * If a parameter is unused, like in, `function f(a,b,c) -> x { x := div(a,b) }`
+ *
+ * We remove the parameter and create a new "linking" function as follows:
+ *
+ * `function f(a,b) -> x { x := div(a,b) }`
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.h]: By the way, we can do the same with unused return variables, right? I think it would be fine to do it in the same component.

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+
+/**
+ * First step of UnusedFunctionArgumentPruner: Find functions with whose parameters are not used in
+ * its body.
+ */
+struct FindFunctionsWithUnusedParameters
+{
+	void operator()(FunctionDefinition const& _function)
+	{
+		auto namesFound = ReferencesCounter::countReferences(_function.body);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
		map<YulString, size_t> namesFound = ReferencesCounter::countReferences(_function.body);
```

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+				reducedParameters.push_back(parameter);
+
+		if (reducedParameters.size() < _function.parameters.size())
+		{
+			functions.insert(_function.name);
+			prunedTypeNames[_function.name] = move(reducedParameters);
+		}
+	}
+
+	set<YulString> functions;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: Is this needed? (keys of prunedTypeNames should suffice)

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+	map<YulString, TypedNameList> prunedTypeNames;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
    /// List of parameters pruned of (?) the unused parameters, by function to be modified.
	map<YulString, TypedNameList> prunedParameters;
```

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 6]
```diff
@@ -0,0 +1,191 @@
...
+ * like : `function f_1(x) -> y { y := 1 }`  and all references to `f` by `f_1`.
+ */
+struct ReplaceFunctionName: public NameDisplacer
+{
+	explicit ReplaceFunctionName(
+		NameDispenser& _dispenser,
+		std::set<YulString> const& _namesToFree
+	): NameDisplacer(_dispenser, _namesToFree) {}
+
+	std::map<YulString, YulString>& translations() { return m_translations; }
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: Maybe it would be better to rather add this function to NameDisplacer. If we ever modify the behaviour of NameDisplacer we will better notice.

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 7]
```diff
@@ -0,0 +1,191 @@
...
+};
+
+/**
+ * Third step of UnusedFunctionArgumentPruner: introduce a new function in the block with body of
+ * the old one. Replace the body of the old one with a function call to the new one.
+ *
+ * For example: introduce a new function `f` with the same the body as `f_1`, but with reduced
+ * parameters, i.e., `function f() -> y { y: = 1 }`. Now replace the body of `f_1` with a call to
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
 * parameters, i.e., `function f() -> y { y := 1 }`. Now replace the body of `f_1` with a call to
```

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 8]
```diff
@@ -0,0 +1,191 @@
...
+	explicit ReplaceFunctionName(
+		NameDispenser& _dispenser,
+		std::set<YulString> const& _namesToFree
+	): NameDisplacer(_dispenser, _namesToFree) {}
+
+	std::map<YulString, YulString>& translations() { return m_translations; }
+};
+
+/**
+ * Third step of UnusedFunctionArgumentPruner: introduce a new function in the block with body of
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: After the renaming of the functions, `new` and `old` can be misleading.

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 9]
```diff
@@ -0,0 +1,191 @@
...
+ * the old one. Replace the body of the old one with a function call to the new one.
+ *
+ * For example: introduce a new function `f` with the same the body as `f_1`, but with reduced
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: The first sentence above does not talk about reduced parameters.

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 10]
```diff
@@ -0,0 +1,191 @@
...
+	explicit AddPrunedFunction(
+		set<YulString> const& _functions,
+		map<YulString, TypedNameList> const& _prunedTypeNames,
+		map<YulString, YulString> const&  _translations
+	):
+		m_functions(_functions),
+		m_prunedTypeNames(_prunedTypeNames),
+		m_translations(_translations)
+	{
+		for (auto const& _f: m_functions)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: `invertMap` in `CommonData.h`

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 11]
```diff
@@ -0,0 +1,191 @@
...
+			m_inverseTranslations[m_translations.at(_f)] = _f;
+	}
+
+	void operator()(Block& _block)
+	{
+		iterateReplacing(_block.statements, [&](Statement& _s) -> optional<vector<Statement>>
+		{
+			if (holds_alternative<FunctionDefinition>(_s))
+			{
+				FunctionDefinition& _old = get<FunctionDefinition>(_s);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
				FunctionDefinition& old = get<FunctionDefinition>(_s);
```

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 12]
```diff
@@ -0,0 +1,191 @@
...
+	map<YulString, YulString> const& m_translations;
+	map<YulString, YulString> m_inverseTranslations;
+};
+
+vector<Statement> AddPrunedFunction::addFunction(FunctionDefinition& _old)
+{
+	SourceLocation loc = _old.location;
+	auto newName = m_inverseTranslations.at(_old.name);
+
+	FunctionDefinition _new{
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
	FunctionDefinition newFunction{
```
?

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 13]
```diff
@@ -0,0 +1,191 @@
...
+	{
+		auto namesFound = ReferencesCounter::countReferences(_function.body);
+
+		TypedNameList reducedParameters;
+
+		for (auto const& parameter: _function.parameters)
+			if (namesFound.count(parameter.name))
+				reducedParameters.push_back(parameter);
+
+		if (reducedParameters.size() < _function.parameters.size())
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: If we run this step again without the function being inlined, we will add more and more functions, so maybe add an exception here:
Do not apply the step to the function if
 - the body is empty or
 - it only consists of a single ExpressionStatement with a single function call
 - it only consists of a single assignment with a single function call

Maybe we could also just reduce it to: do not apply if the number of statements in the body is at most 1.

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 14]
```diff
@@ -0,0 +1,191 @@
...
+		assignment.value = make_unique<Expression>(move(call));
+
+		_old.body.statements.emplace_back(move(assignment));
+	}
+
+	vector<Statement> statements;
+	statements.emplace_back(move(_new));
+	statements.emplace_back(move(_old));
+
+	return statements;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
	return make_vector<Statement>(move(_new), move(_old));
```

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 15]
```diff
@@ -0,0 +1,191 @@
...
+}
+
+} // anonymous namespace
+
+void UnusedFunctionArgumentPruner::run(OptimiserStepContext& _context, Block& _block)
+{
+	FindFunctionsWithUnusedParameters _find;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]:
```suggestion
	FindFunctionsWithUnusedParameters find;
```

File: libyul/optimiser/UnusedFunctionArgumentPruner.cpp [hunk 16]
```diff
@@ -0,0 +1,191 @@
...
+	for (auto const& statement: _block.statements)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionArgumentPruner.cpp]: Does `_find(_block)` not work?

**Review by chriseth — CHANGES_REQUESTED** [review]
Nice! This looks really good!

Can you add it to the `fullSuite` and add tests that show that it works as intended in connection to inlining in the full suite?

File: test/libsolidity/gasTests/abiv2_optimised.sol [hunk 17]
```diff
@@ -17,9 +17,9 @@ contract C {
 // optimize-yul: true
 // ----
 // creation:
-//   codeDepositCost: 603000
-//   executionCost: 638
-//   totalCost: 603638
+//   codeDepositCost: 600400
+//   executionCost: 632
+//   totalCost: 601032
```
Comment (hrkrshnn) [inline test/libsolidity/gasTests/abiv2_optimised.sol]: https://gist.github.com/hrkrshnn/e622364b543d6e26a70266e25e88a48a

A diff of the changes.

Comment (chriseth) [reply test/libsolidity/gasTests/abiv2_optimised.sol]: This looks good!

File: libsolidity/interface/OptimiserSettings.h [hunk 18]
```diff
@@ -40,7 +40,7 @@ struct OptimiserSettings
 
 			// should have good "compilability" property here.
 
-			"eul"                      // Run functional expression inliner
+			"Feul"                     // Run functional expression inliner
```
Comment (chriseth) [inline libsolidity/interface/OptimiserSettings.h]: Shouldn't we rather run it before the full inliner instead of the expresison inliner?

Comment (chriseth) [reply libsolidity/interface/OptimiserSettings.h]: Ah, you are saying that if the function only returns a single variable, then the expression inliner can also do it. But maybe better to run it before both the functional inliner and the full inliner?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 19]
```diff
@@ -0,0 +1,202 @@
...
+ * First step of UnusedFunctionParameterPruner: Find functions with whose parameters are not used in
+ * its body.
+ */
+struct FindFunctionsWithUnusedParameters
+{
+	void operator()(FunctionDefinition const& _function)
+	{
+		map<YulString, size_t> namesFound = ReferencesCounter::countReferences(_function.body);
+
+		// We skip if the function body
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
		// We skip if the function body if it
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 20]
```diff
@@ -0,0 +1,202 @@
...
+		// 1. is empty
+		// 2. is a single statement, that is an assignment statement with RHS being a function call
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
		// 2. is a single statement, that is an assignment statement with RHS being a function call, or
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 21]
```diff
@@ -0,0 +1,202 @@
...
+		// 3. is a single expression-statement, that is a function call
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
		// 3. is a single expression-statement, that is a function call
		// This allows this optimizer step to run again on its output without making things worse.
```

Comment (chriseth) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Or maybe something like: The above cases are simple enough such that the inliner alone can remove the parameters.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `c0f4440040fe8331c4da8f49d50dbf6426d9b784`:
```
Coding style error:
 libyul/optimiser/UnusedFunctionParameterPruner.cpp:87: private:

```
Please check that your changes are working as intended.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 22]
```diff
@@ -0,0 +1,370 @@
...
+		m_references(_references)
+
+	{
+		(*this)(_block);
+	}
+	using ASTWalker::operator();
+	void operator()(VariableDeclaration const& _v) override;
+
+	map<YulString, vector<bool>> m_returns;
+ private:
```
Comment (stackenbotten) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp:87]: Coding style error

File: libsolidity/interface/OptimiserSettings.h [hunk 23]
```diff
@@ -43,7 +43,7 @@ struct OptimiserSettings
 			"eul"                      // Run functional expression inliner
 			"xarulrul"                 // Prune a bit more in SSA
 			"xarrcL"                   // Turn into SSA again and simplify
-			"gvif"                     // Run full inliner
+			"gvFif"                    // Run full inliner
```
Comment (hrkrshnn) [inline libsolidity/interface/OptimiserSettings.h]: Not sure about where to place `F`. ~~Also, `F` will cause duplication in names (arguments and return parameters)~~

TODO: need better tests for full suite, especially recursive functions.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `55cf29877dac5fbd6b78da144674d08618523081`:
```
Coding style error:
 libyul/optimiser/UnusedFunctionParameterPruner.cpp:87: private:

```
Please check that your changes are working as intended.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 22 above)
Comment (stackenbotten) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp:87]: Coding style error

File: test/libsolidity/gasTests/abiv2_optimised.sol [hunk 24]
```diff
@@ -17,9 +17,9 @@ contract C {
 // optimize-yul: true
 // ----
 // creation:
-//   codeDepositCost: 603000
-//   executionCost: 638
-//   totalCost: 603638
+//   codeDepositCost: 631600
+//   executionCost: 664
+//   totalCost: 632264
```
Comment (hrkrshnn) [inline test/libsolidity/gasTests/abiv2_optimised.sol]: Weird that the gas costs increased by a lot, even though the optimised code looks better (?)

Here is a diff comparing removing-unused-returns + removing-unused-function-parameters v/s only removing-unused-function-arguments
https://gist.github.com/hrkrshnn/7c14cfa1794271792fbf5f36e0d6cfda

@chriseth What do you think lead to the increase?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 25]
```diff
@@ -0,0 +1,370 @@
...
+	solidity is distributed in the hope that it will be useful,
+	but WITHOUT ANY WARRANTY; without even the implied warranty of
+	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+	GNU General Public License for more details.
+
+	You should have received a copy of the GNU General Public License
+	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
+*/
+/**
+ * UnusedFunctionParameterPruner: Optimiser step that removes unused-parameters function.
```
Comment (axic) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
 * UnusedFunctionParameterPruner: Optimiser step that removes unused parameters from function definition.
```

File: libyul/optimiser/Suite.cpp [hunk 26]
```diff
@@ -220,6 +222,7 @@ map<string, char> const& OptimiserSuite::stepNameToAbbreviationMap()
 		{SSAReverser::name,                   'V'},
 		{SSATransform::name,                  'a'},
 		{StructuralSimplifier::name,          't'},
+		{UnusedFunctionParameterPruner::name, 'F'},
```
Comment (chriseth) [inline libyul/optimiser/Suite.cpp]: Wouldn't `p` (for parameter) be more fitting?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 27]
```diff
@@ -0,0 +1,370 @@
...
+	using ASTWalker::operator();
+	void operator()(VariableDeclaration const& _v) override;
+
+	map<YulString, vector<bool>> m_returns;
+ private:
+	Dialect const& m_dialect;
+	map<YulString, size_t> const& m_references;
+};
+
+// Find functions whose return parameters are unused. Assuming that the code is in SSA form and that
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Ah, so this is more like removing return parameters that are ignored by the caller?

Do you also remove return parameters that are never assigned in the function?

Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: > Do you also remove return parameters that are never assigned in the function?

This is done in Step 1B.

An important case that we are missing is `pop(f())`. A problem with this case is that ExpressionSplitter converts it into

```
let x := f()
pop(x)
```
So we can't infer from `ReferencesCounter` if return value of `f` used. That `pop(x)` is a vacuous statement.

Do you think we should change ExpressionSplitter so that it can `pop(f())` is converted into just `let x := f()`?

File: test/libyul/YulOptimizerTest.cpp [hunk 28]
```diff
@@ -235,6 +236,17 @@ TestCase::TestResult YulOptimizerTest::run(ostream& _stream, string const& _line
...
+	else if (m_optimizerStep == "unusedFunctionParameterPruner")
+	{
+		disambiguate();
+		// prerequisite for SSATransform
+		ForLoopInitRewriter::run(*m_context, *m_ast);
+		SSATransform::run(*m_context, *m_ast);
+		FunctionHoister::run(*m_context, *m_ast);
+		ForLoopConditionIntoBody::run(*m_context, *m_ast);
+		ExpressionSplitter::run(*m_context, *m_ast);
+		UnusedFunctionParameterPruner::run(*m_context, *m_ast);
```
Comment (hrkrshnn) [inline test/libyul/YulOptimizerTest.cpp]: I think it's a good idea to reverse `ExpressionSplitter` and `SSATransform` at the end, so tests are more readable.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 27 above)
Comment (chriseth) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: The `UnusedPruner` should remove `pop(x)`. In general, UnusedPruner should be run before (or at least close to) this step, shouldn't it?

Comment (chriseth) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: This step is getting rather complicated - I didn't review the full thing yet, but is it beneficial to do both things in the same step, or should we rather have one step that only modifies the function definitions (and splits them into two) and another step that modifies the call sites?

Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: They can be split up. They both share the same final step, where the functions get renamed, so doing it together makes sense. If we split it up, the `FullInliner` will have to inline two functions, instead of just one.

Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: > The UnusedPruner should remove pop(x)

`UnusedPruner` seems to be doing the opposite: converting `let x := f(1)` to `pop(f(1))`. So running `UnusedPruner` means such functions cannot be rewritten.

File: libsolidity/interface/OptimiserSettings.h [hunk 29]
```diff
@@ -41,7 +41,7 @@ struct OptimiserSettings
 
 			// should have good "compilability" property here.
 
-			"eul"                      // Run functional expression inliner
+			"peul"                     // Run functional expression inliner
```
Comment (chriseth) [inline libsolidity/interface/OptimiserSettings.h]: Is the expression inliner powerful enough to complete the p step?

Comment (hrkrshnn) [reply libsolidity/interface/OptimiserSettings.h]: Not generally. But this sequence is giving better results than putting it before FullInliner (`i`) Don't know why exactly.

File: test/libyul/yulOptimizerTests/unusedFunctionParameterPruner/multiple_return.yul [hunk 30]
```diff
@@ -0,0 +1,24 @@
+{
+    let a, b, c := f(sload(0))
```
Comment (chriseth) [inline test/libyul/yulOptimizerTests/unusedFunctionParameterPruner/multiple_return.yul:2]: Can you add such a test to the fullSuite so that we see that unused return variables are properly removed at the calling site?

File: libyul/optimiser/UnusedFunctionParameterPruner.h [hunk 31]
```diff
@@ -0,0 +1,48 @@
...
+
+#include <libyul/optimiser/OptimiserStep.h>
+
+namespace solidity::yul
+{
+
+/**
+ * UnusedFunctionParameterPruner: Optimiser step that removes unused parameters in a function.
+ *
+ * If a parameter is unused, like in, `function f(a,b,c) -> x { x := div(a,b) }`
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.h]:
```suggestion
 * If a parameter is unused, like `c` in `function f(a,b,c) -> x { x := div(a,b) }`
```

Comment (chriseth) [reply libyul/optimiser/UnusedFunctionParameterPruner.h]: Please also add an unused return variable

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 32]
```diff
@@ -0,0 +1,324 @@
...
+namespace
+{
+
+bool anyFalse(vector<bool> const& _mask)
+{
+	return any_of(_mask.begin(), _mask.end(), [](bool b){ return !b; });
+}
+
+template<typename T>
+vector<T> applyBooleanMask(vector<T> const& _vec, vector<bool> const& _mask)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: From the name I would have thought it just computes an `&` and does not change the size of the vector. Maybe something like `cutOut`? But then the mask would have to be inverted...

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 33]
```diff
@@ -0,0 +1,324 @@
...
+ * Find functions whose parameters (both arguments and return-parameters) are not used in its body.
+ */
+class FindFunctionsWithUnusedParameters
+{
+public:
+	explicit FindFunctionsWithUnusedParameters(
+		Dialect const& _dialect,
+		Block const& _block,
+		map<YulString, size_t> const& _references
+	) :
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
	):
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 34]
```diff
@@ -0,0 +1,324 @@
...
+		m_references(_references),
+		m_dialect(_dialect)
+	{
+		for (auto const& statement: _block.statements)
+			if (holds_alternative<FunctionDefinition>(statement))
+				(*this)(std::get<FunctionDefinition>(statement));
+	}
+
+	void operator()(FunctionDefinition const& _f);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Maybe better to give this function a proper name?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 35]
```diff
@@ -0,0 +1,324 @@
...
+
+	/// Function name and a boolean mask, where `false` at index `i` indicates that the function
+	/// argument at index `i` in `FuntionDefinition::parameters` is unused.
+	map<YulString, vector<bool>> argumentMasks;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
	map<YulString, vector<bool>> unusedParameters;
```
?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 36]
```diff
@@ -0,0 +1,324 @@
...
+	{
+		for (auto const& statement: _block.statements)
+			if (holds_alternative<FunctionDefinition>(statement))
+				(*this)(std::get<FunctionDefinition>(statement));
+	}
+
+	void operator()(FunctionDefinition const& _f);
+
+	/// Function name and a boolean mask, where `false` at index `i` indicates that the function
+	/// argument at index `i` in `FuntionDefinition::parameters` is unused.
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
	/// argument at index `i` in `FunctionDefinition::parameters` is unused.
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 37]
```diff
@@ -0,0 +1,324 @@
...
+
+private:
+	/// A heuristic to determine if a function was already rewritten by UnusedFunctionParameterPruner
+	bool wasPruned(FunctionDefinition const& _f);
+
+	map<YulString, size_t> const& m_references;
+	Dialect const& m_dialect;
+};
+
+// Find functions whose arguments are not used in its body. Also, find functions whose body
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
/// Find functions whose arguments are not used in its body. Also, find functions whose body
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 38]
```diff
@@ -0,0 +1,324 @@
...
+	/// A set of functions that could potentially be already pruned by
+	/// UnusedFunctionParameterPruner, and therefore should be skipped when applying the
+	/// transformation.
+	set<YulString> alreadyPruned;
+
+private:
+	/// A heuristic to determine if a function was already rewritten by UnusedFunctionParameterPruner
+	bool wasPruned(FunctionDefinition const& _f);
+
+	map<YulString, size_t> const& m_references;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Please document

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 39]
```diff
@@ -0,0 +1,324 @@
...
+// satisfies a heuristic about pruning.
+void FindFunctionsWithUnusedParameters::operator()(FunctionDefinition const& _f)
+{
+	if (wasPruned(_f))
+	{
+		alreadyPruned.insert(_f.name);
+		return;
+	}
+
+	auto contains = [&](auto v) -> bool { return m_references.count(v.name); };
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
	auto used = [&](auto v) -> bool { return m_references.count(v.name); };
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 40]
```diff
@@ -0,0 +1,324 @@
...
+
+} // anonymous namespace
+
+void UnusedFunctionParameterPruner::run(OptimiserStepContext& _context, Block& _block)
+{
+	map<YulString, size_t> references =  ReferencesCounter::countReferences(_block);
+	FindFunctionsWithUnusedParameters find{_context.dialect, _block, references};
+
+	auto first = [](auto const& p) { return p.first; };
+	set<YulString> functionsWithUnusedArguments
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: This is just the set of keys of the map, right? I think we should have a specific helper function for that.

File: libsolidity/interface/OptimiserSettings.h (hunk 29 above)
Comment (chriseth) [reply libsolidity/interface/OptimiserSettings.h]: Ok! I guess it doesn't matter much, the full inliner will do its job eventually.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 41]
```diff
@@ -0,0 +1,324 @@
...
+
+	return ret;
+}
+
+/**
+ * Step 1 of UnusedFunctionParameterPruner:
+ *
+ * Find functions whose parameters (both arguments and return-parameters) are not used in its body.
+ */
+class FindFunctionsWithUnusedParameters
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: I'm wondering whether we really need this to be a stateful class instead of just a function that is called on a FunctionDefinition

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 32 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: The name comes from Python datascience libraries: https://www.tensorflow.org/api_docs/python/tf/boolean_mask

Perhaps the name `booleanMask` can be confusing inside solidity. Would `filter` be a better choice?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 40 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Yes. I wasn't able to find any helper for it. Maybe I'll just add it to `utils::`

File: libsolidity/interface/OptimiserSettings.h [hunk 42]
```diff
@@ -41,7 +41,7 @@ struct OptimiserSettings
 
 			// should have good "compilability" property here.
 
-			"eul"                      // Run functional expression inliner
+			"Tpeul"                    // Run functional expression inliner
```
Comment (hrkrshnn) [inline libsolidity/interface/OptimiserSettings.h:44]: Added LiteralRematerialiser (T) before UnusedFunctionParamterPruner (p) because of https://github.com/ethereum/solidity/issues/9653

**Comment by chriseth** [comment]
Can you add a fullSuite test for something like
```
function f(a) -> x {
  a := calldataload(0)
  mstore(a, x)
}
```
This should be optimized to
```
function f() {
  mstore(calldataload(0), 0)
}
```
Maybe we could even use `a` in a loop (where it cannot be replaced by an SSA variable) but write to `a` before it is read from. 

It might be that the optimizer will have a problem with the loop case, but at least regular write before read should be optimized.

File: libyul/optimiser/NameDisplacer.h [hunk 43]
```diff
@@ -60,6 +60,8 @@ class NameDisplacer: public ASTModifier
 	void operator()(FunctionCall& _funCall) override;
 	void operator()(Block& _block) override;
 
+	std::map<YulString, YulString> const& translations() { return m_translations; }
```
Comment (chriseth) [inline libyul/optimiser/NameDisplacer.h]:
```suggestion
	std::map<YulString, YulString> const& translations() const { return m_translations; }
```

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `d20b2eb0ce9402b58a603f93d643caaa381d9258`:
```
Coding style error:
 libyul/optimiser/UnusedFunctionsCommon.h:20:#include "libyul/optimiser/NameDispenser.h"

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `a44d6d87dafdc8f642b7758c1024d75a44f783ca`:
```
Coding style error:
 libyul/optimiser/UnusedFunctionsCommon.h:20:#include "libyul/optimiser/NameDispenser.h"

```
Please check that your changes are working as intended.

File: test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul [hunk 44]
```diff
@@ -0,0 +1,33 @@
...
+//         sstore(0, 1)
+//     }
+//     function f()
+//     {
+//         let b := 10
+//         let _1 := 0
+//         let a := calldataload(_1)
+//         for { } iszero(b) { b := add(b, not(0)) }
+//         { mstore(a, _1) }
+//     }
```
Comment (hrkrshnn) [inline test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul:32]: I'm a bit surprised by how it was able to infer `a` was unused.

Comment (hrkrshnn) [reply test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul:32]: Don't think it is a bug, since this is how the same test runs for `UnusedFunctionParameterPruner`.
```solidity
{
    sstore(f(1), 1)
    sstore(f(2), 1)
    sstore(f(3), 1)
    function f(a) -> x {
        let b := 10
        for {} iszero(b) { b := sub(b, 1) }
        {
            a := calldataload(0)
            mstore(a, x)
        }
    }
}
// ----
// step: unusedFunctionParameterPruner
//
// {
//     sstore(f_1(1), 1)
//     sstore(f_1(2), 1)
//     sstore(f_1(3), 1)
//     function f(a)
//     {
//         let b := 10
//         for { } iszero(b) { b := sub(b, 1) }
//         {
//             a := calldataload(0)
//             mstore(a, 0)
//         }
//     }
//     function f_1(a_2) -> x_3
//     { f(a_2) }
// }
```

Comment (hrkrshnn) [reply test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul:32]: I think what happens is SSATransform (a) + UnusedPruner (u) + RedundantAssignEliminator (r) is able to remove `a` from the function. And VarNameCleaner cleans up some `a_n` back to `a`. To "verify" the claim, we can replace the parameter name `a` by `a_5`. And still get the same result.

File: libyul/optimiser/UnusedFunctionParameterPruner.h [hunk 45]
```diff
@@ -0,0 +1,52 @@
...
+ *
+ * and replace all references to `f` by `f2`.
+ *
+ * Prerequisites: Disambiguator, FunctionHoister, LiteralRematerialiser
+ *
+ * The step LiteralRematerialiser is not required for correctness. It helps deal with cases such as:
+ * `function f(x) -> y { revert(y, y} }` where the literal `y` will be replaced by its value `0`,
+ * allowing us to rewrite the function.
+ *
+ * The inliner should be run afterwards to make sure that all references to `f2` are replaced by
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.h]: Can you move this above "Prerequisites"?

File: test/cmdlineTests/yul_stack_opt/output [hunk 46]
```diff
@@ -5,11 +5,11 @@ Pretty printed source:
 object "object" {
     code {
         {
-            let a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1 := fun()
```
Comment (chriseth) [inline test/cmdlineTests/yul_stack_opt/output:8]: This is not really fulfulling the objective of the test anymore :(
The idea was to generate many local variables that are unused right after assignment.

File: test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul [hunk 47]
```diff
@@ -0,0 +1,33 @@
...
+        }
+    }
+}
+// ----
+// step: fullSuite
+//
+// {
+//     {
+//         f()
+//         sstore(0, 1)
```
Comment (chriseth) [inline test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul:19]: Does it  infer the result of `f` to be always zero from the 'unused return value pruning'? But this pruning is not part of the pull request yet, is it?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 48]
```diff
@@ -0,0 +1,124 @@
...
+			FunctionDefinition const& f = std::get<FunctionDefinition>(statement);
+
+			if (wasPruned(f, _context.dialect))
+				continue;
+
+			vector<bool> parameters = applyMap(f.parameters, used);
+			vector<bool> returnVariables = applyMap(f.returnVariables, used);
+
+			if (anyFalse(parameters))
+				unusedParameters[f.name] = move(parameters);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Shouldn't this be `usedParameters`?

Comment (chriseth) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Maybe invert the boolean?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 49]
```diff
@@ -0,0 +1,124 @@
...
+
+	set<YulString> namesToFree = util::keys(unusedParameters) + util::keys(unusedReturnVariables);
+
+	// Step 2 of UnusedFunctionParameterPruner: Replace all references of the function, say `f`, by
+	// a new name, say `f_1`.
+	NameDisplacer replace{_context.dispenser, namesToFree};
+	replace(_block);
+	// Inverse-Map of the above translations. In the above example, this will store an element with
+	// key `f_1` and value `f`.
+	std::map<YulString, YulString> inverseTranslations = invertMap(replace.translations());
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: `newToOriginalNames`?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 50]
```diff
@@ -0,0 +1,171 @@
...
+			ret.push_back(_vec[i]);
+
+	return ret;
+}
+
+/// Find functions whose arguments are not used in its body. Also, find functions whose body
+/// satisfies a heuristic about pruning.
+bool wasPruned(FunctionDefinition const& _f, Dialect const& _dialect)
+{
+	// We skip the function body if it
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: I'm wondering if these conditions are also checked by the inliner at some point. If yes, we should combine them.

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 51]
```diff
@@ -0,0 +1,171 @@
...
+				if (!_dialect.builtin(c.functionName.name))
+					return true;
+			}
+	}
+	return false;
+}
+
+FunctionDefinition createReplacement(
+	FunctionDefinition& _old,
+	std::map<YulString, std::vector<bool>> const& _unusedParameters,
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Do you need to pass the full map?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 52]
```diff
@@ -0,0 +1,171 @@
...
+	std::map<YulString, std::vector<bool>> const& _unusedReturnVariables,
+	NameDispenser& _nameDispenser,
+	std::map<YulString, YulString> _inverseTranslations
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Same here, we only need old and new name, right?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 53]
```diff
@@ -0,0 +1,171 @@
...
+
+	FunctionDefinition newFunction{
+		loc,
+		std::move(newName),
+		std::move(functionArguments),
+		std::move(returnVariables),
+		{loc, {}} // body
+	};
+
+	std::swap(newFunction.body, _old.body);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: I'm wondering if it would be simpler to modify the parameter list of the original function instead

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 51 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: Yes, because we know yet, if we have to modify the parameters or the return variables.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 52 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: This can be avoided. This should be a `const` reference. I'll fix that.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 53 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: What do you mean?

File: test/cmdlineTests/yul_stack_opt/output (hunk 46 above)
Comment (hrkrshnn) [reply test/cmdlineTests/yul_stack_opt/output:8]: I'll fix it by making it run a sequence without `p`. Not sure if there is another way around it. I can check if assigning values of `a3, ..., p3` will still make `stack_opt` work.

File: test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul (hunk 47 above)
Comment (hrkrshnn) [reply test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul:19]: We haven't used 'callsite' optimization yet. The value is `0` because of the inlining.

File: test/libyul/yulOptimizerTests/unusedFunctionParameterPruner/multiple_return.yul (hunk 30 above)
Comment (hrkrshnn) [reply test/libyul/yulOptimizerTests/unusedFunctionParameterPruner/multiple_return.yul:2]: test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_return.yul is a testcase for it.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 50 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: The dialect part is a bit specific for this step. But let me have a look.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 51 above)
Comment (chriseth) [reply libyul/optimiser/UnusedFunctionsCommon.h]: But wouldn't `_unusedParameters[_old]` (or new) be enough? Of course, the key does not have to exist, but I think in that case, a `std::optional<std::vector<bool>>` would be better. Or something like "if the vector is empty, it is not considered".

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 53 above)
Comment (chriseth) [reply libyul/optimiser/UnusedFunctionsCommon.h]: Instead of creating a new function and swapping the body, keep the old function, change its name and prune its parameters. Then add a new function that calls the old.

File: test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul (hunk 47 above)
Comment (chriseth) [reply test/libyul/yulOptimizerTests/fullSuite/unusedFunctionParameterPruner_loop.yul:19]: Oh, because `x` is only read from and not written to?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 48 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: I changed it to `usedParameters`.

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 54]
```diff
@@ -0,0 +1,172 @@
...
+	for (size_t i = 0; i < _mask.size(); ++i)
+		if (_mask[i])
+			ret.push_back(_vec[i]);
+
+	return ret;
+}
+
+/// Find functions whose arguments are not used in its body. Also, find functions whose body
+/// satisfies a heuristic about pruning.
+bool wasPruned(FunctionDefinition const& _f, Dialect const& _dialect)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: `tooSimpleToBePruned`?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 55]
```diff
@@ -0,0 +1,172 @@
...
+	std::vector<T> ret;
+
+	for (size_t i = 0; i < _mask.size(); ++i)
+		if (_mask[i])
+			ret.push_back(_vec[i]);
+
+	return ret;
+}
+
+/// Find functions whose arguments are not used in its body. Also, find functions whose body
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Returns true if applying unused parameter pruning would not be helpful because the linking function is already as complicated as the original function.

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 56]
```diff
@@ -0,0 +1,172 @@
...
+/// satisfies a heuristic about pruning.
+bool wasPruned(FunctionDefinition const& _f, Dialect const& _dialect)
+{
+	// We skip the function body if it
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: The function is too simple if its body

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 57]
```diff
@@ -0,0 +1,172 @@
...
+	// 1. is empty, or
+	// 2. is a single statement that is an assignment statement whose value is a non-builtin
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Does it actually make a big difference whether it is a builtin function call or not?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 58]
```diff
@@ -0,0 +1,172 @@
...
+	//    function call, or
+	// 3. is a single expression-statement that is a non-builtin function call.
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Same here

File: test/libsolidity/StandardCompiler.cpp [hunk 59]
```diff
@@ -1235,9 +1235,27 @@ BOOST_AUTO_TEST_CASE(use_stack_optimization)
 	BOOST_REQUIRE(contract["evm"]["bytecode"]["object"].isString());
 	BOOST_CHECK(contract["evm"]["bytecode"]["object"].asString().length() > 20);
 
-	// Now disable stack optimizations
+	// Now disable stack optimizations and UnusedFunctionParameterPruner
 	// results in "stack too deep"
 	parsedInput["settings"]["optimizer"]["details"]["yulDetails"]["stackAllocation"] = false;
+		parsedInput["settings"]["optimizer"]["details"]["yulDetails"]["optimizerSteps"] =
```
Comment (chriseth) [inline test/libsolidity/StandardCompiler.cpp]: I don't think copying this is a good idea. Can you instead look up the letter of the step in the list of steps and remove it from the string?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 60]
```diff
@@ -0,0 +1,136 @@
...
+
+	return nullopt;
+}
+
+
+} // anonymous namespace
+
+void UnusedFunctionParameterPruner::run(OptimiserStepContext& _context, Block& _block)
+{
+
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 61]
```diff
@@ -0,0 +1,136 @@
...
+			vector<bool> parameters = applyMap(f.parameters, used);
+			vector<bool> returnVariables = applyMap(f.returnVariables, used);
+
+			if (anyFalse(parameters))
+				usedParameters[f.name] = move(parameters);
+			if (anyFalse(returnVariables))
+				usedReturnVariables[f.name] = move(returnVariables);
+		}
+
+	set<YulString> namesToFree = util::keys(usedParameters) + util::keys(usedReturnVariables);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
	set<YulString> functionNamesToFree = util::keys(usedParameters) + util::keys(usedReturnVariables);
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 62]
```diff
@@ -0,0 +1,136 @@
...
+	if (it != _map.end())
+		return it->second;
+
+	return nullopt;
+}
+
+
+} // anonymous namespace
+
+void UnusedFunctionParameterPruner::run(OptimiserStepContext& _context, Block& _block)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
void UnusedFunctionParameterPruner::run(OptimiserStepContext& _context, Block& _ast)
```
(because it is not meant to be just "some" block)

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 63]
```diff
@@ -0,0 +1,136 @@
...
+	replace(_block);
+	// Inverse-Map of the above translations. In the above example, this will store an element with
+	// key `f_1` and value `f`.
+	std::map<YulString, YulString> newToOriginalNames = invertMap(replace.translations());
+
+	// Step 3 of UnusedFunctionParameterPruner: introduce a new function in the block with body of
+	// the old one. Replace the body of the old one with a function call to the new one with reduced
+	// parameters.
+	//
+  	// For example: introduce a new function `f` with the same the body as `f_1`, but with reduced
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
  // For example: introduce a new function `f` with the same the body as `f_1`, but with reduced
```

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 64]
```diff
@@ -0,0 +1,136 @@
...
+			if (anyFalse(parameters))
+				usedParameters[f.name] = move(parameters);
+			if (anyFalse(returnVariables))
+				usedReturnVariables[f.name] = move(returnVariables);
+		}
+
+	set<YulString> namesToFree = util::keys(usedParameters) + util::keys(usedReturnVariables);
+
+	// Step 2 of UnusedFunctionParameterPruner: Replace all references of the function, say `f`, by
+	// a new name, say `f_1`.
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: This also renames the function itself, right?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 65]
```diff
@@ -0,0 +1,136 @@
...
+	// parameters.
+	//
+  	// For example: introduce a new function `f` with the same the body as `f_1`, but with reduced
+	// parameters, i.e., `function f() -> y { y := 1 }`. Now replace the body of `f_1` with a call to
+	// `f`, i.e., `f_1(x) -> y { y := f() }`.
+	iterateReplacing(_block.statements, [&](Statement& _s) -> optional<vector<Statement>>
+	{
+		if (holds_alternative<FunctionDefinition>(_s))
+		{
+			FunctionDefinition& old = get<FunctionDefinition>(_s);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Will `old` or `replacement` be the linking function?

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 66]
```diff
@@ -0,0 +1,136 @@
...
+
+void UnusedFunctionParameterPruner::run(OptimiserStepContext& _context, Block& _block)
+{
+
+	map<YulString, size_t> references = ReferencesCounter::countReferences(_block);
+	auto used = [&](auto v) -> bool { return references.count(v.name); };
+
+	// Function name and a boolean mask, where `false` at index `i` indicates that the function
+	// argument at index `i` in `FunctionDefinition::parameters` is unused inside the function body.
+	map<YulString, vector<bool>> usedParameters;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]: If you change this to a `map<YulString, vector<bool>[2]>` and include both the parameters and the return variables - would this simplify the code? I would say that you won't need `optionalFind` below and the if statements in https://github.com/ethereum/solidity/pull/9397/files#diff-b67936fa269149fe7e133f276f7cab60R107 can be removed (i.e. only the "true" case will be left).

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 67]
```diff
@@ -0,0 +1,172 @@
...
+	}
+	return false;
+}
+
+FunctionDefinition createReplacement(
+	FunctionDefinition& _old,
+	std::optional<std::vector<bool>> const& _usedParameters,
+	std::optional<std::vector<bool>> const& _usedReturnVariables,
+	NameDispenser& _nameDispenser,
+	YulString const& _newName)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]:
```suggestion
	YulString const& _newFunctionName
)
```

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 68]
```diff
@@ -0,0 +1,172 @@
...
+				FunctionCall c = std::get<FunctionCall>(std::get<ExpressionStatement>(e).expression);
+				if (!_dialect.builtin(c.functionName.name))
+					return true;
+			}
+	}
+	return false;
+}
+
+FunctionDefinition createReplacement(
+	FunctionDefinition& _old,
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Maybe `original` instead of old?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 69]
```diff
@@ -0,0 +1,172 @@
...
+		renamedParameters,
+		reducedRenamedParameters,
+		{loc, {}} // body
+	};
+
+	_old.name = _newName;
+	_old.parameters = std::move(functionParameters);
+	_old.returnVariables = std::move(returnVariables);
+
+	std::swap(newFunction.parameters, renamedParameters);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Why do you swap here? Shouldn't one be a copy of the other?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 70]
```diff
@@ -0,0 +1,172 @@
...
+	TypedNameList returnVariables;
+	TypedNameList renamedParameters = util::applyMap(_old.parameters, generateName);
+	TypedNameList reducedRenamedParameters;
+	TypedNameList renamedReturnVariables = util::applyMap(_old.returnVariables, generateName);
+	TypedNameList reducedRenamedReturnVariables;
+
+	if (_usedParameters)
+	{
+		std::vector<bool> const& mask = _usedParameters.value();
+		functionParameters = applyBooleanMask(_old.parameters, mask);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: So shouldn't this be named `reducedFunctionParameters`?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 71]
```diff
@@ -0,0 +1,172 @@
...
+	{
+		return TypedName{
+			t.location,
+			_nameDispenser.newName(t.name),
+			t.type
+		};
+	};
+
+	langutil::SourceLocation loc = _old.location;
+	TypedNameList functionParameters;
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Can't some of these be avoided by accessing them as members of `newFunction`?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 72]
```diff
@@ -0,0 +1,172 @@
...
+
+	// Replace the body of `f_1` by an assignment which calls `f`, i.e.,
+	// `return_parameters = f(reduced_parameters)`
+	if (!_old.returnVariables.empty())
+	{
+		Assignment assignment;
+		assignment.location = loc;
+
+		// The LHS of the assignment.
+		for (auto const& r: reducedRenamedReturnVariables)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Is the following correct?
```suggestion
		for (auto const& r: _old.returnVariables)
```

Comment (chriseth) [reply libyul/optimiser/UnusedFunctionsCommon.h]: Ah no, it should be `newFunction.returnVariables` right?

Comment (chriseth) [reply libyul/optimiser/UnusedFunctionsCommon.h]: No, `old` should be correct, because `new` is the linking function and has the full set of return variables.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 57 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: I'm not sure about the impact. If the inliner can handle them, then we don't have to compare with the dialect. However, the inliner won't be able to handle, e.g., `function f(a) -> y { y :=  mload(f(1)) }` because it is recursive.

We could replace this simply by `return _f.body.statements().size() <= 1`

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 70 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: In this `if` branch, yes, that would be a better name. But a generic name was used because `_usedParameters` doesn't have to be `nullopt`.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 69 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: Yes. This is redundant. Sorry about that, after multiple changes, this is not so cohesive. I'll try to avoid this problem in the future.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 57 above)
Comment (chriseth) [reply libyul/optimiser/UnusedFunctionsCommon.h]: What about `_f.body.statements().size() <= 1 && CodeSize::codeSize(_f.body) <= 1`? The second part is the condition in the full inliner.

File: libyul/optimiser/UnusedFunctionsCommon.h (hunk 70 above)
Comment (chriseth) [reply libyul/optimiser/UnusedFunctionsCommon.h]: I think they can still be called reduced even if they are sometimes reduced by 0.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 64 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: Yes. I'll include it in the comment.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 66 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: I changed it to a pair of vectors.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 65 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp]: I changed the name of `old` to `originalFunctionWithNewName` and the function `createReplacement` to `createLinkingFunction`.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 73]
```diff
@@ -0,0 +1,136 @@
...
+				hasUnused = true;
+			}
+			if (anyFalse(returnVariables))
+			{
+				parametersAndReturnVariables.second = move(returnVariables);
+				hasUnused = true;
+			}
+
+			if (hasUnused)
+				usedParametersAndReturnVariables[f.name] = move(parametersAndReturnVariables);
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp]:
```suggestion
			if (tooSimpleToBePruned(f) || boost::algorithm::all_of(f.parameters + f.returnVariables, used))
				continue;

			usedParametersAndReturnVariables[f.name] = {
				applyMap(f.parameters, used),
				applyMap(f.returnVariables, used)
			};
```
This evaluates `used` twice, so you could also introduce local variables, but I don't think we should be shy of using a concatenation of vectors of variables or even better bools...

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp [hunk 74]
```diff
@@ -0,0 +1,119 @@
...
+			FunctionDefinition& originalFunctionWithNewName = get<FunctionDefinition>(_s);
+			if (newToOriginalNames.count(originalFunctionWithNewName.name))
+			{
+				YulString originalName = newToOriginalNames.at(originalFunctionWithNewName.name);
+
+				// After this, the name of `originalFunctionWithNewName` will be changed back to
+				// original, i.e., `f_1 -> f`. Its parameters (both arguments and return-variables)
+				// will be pruned. The function returned will have the new name, i.e., `f_1`, and
+				// becomes the 'linking' function.
+				FunctionDefinition linkingFunction = createLinkingFunction(
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionParameterPruner.cpp:107]: I would find it more natural if `createLinkingFunction` did not modify the original function and really would just create the linking function. As far as I can see, the modifications on the original function would just be three lines of code that can easily be pulled out - is that correct?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 75]
```diff
@@ -0,0 +1,123 @@
...
+}
+
+FunctionDefinition createLinkingFunction(
+	FunctionDefinition& _original,
+	std::pair<std::vector<bool>, std::vector<bool>> const& _usedParametersAndReturns,
+	NameDispenser& _nameDispenser,
+	YulString const& _newFunctionName
+)
+{
+	auto generateName = [&](TypedName t)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]:
```suggestion
	auto generateTypedName = [&](TypedName t)
```

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 76]
```diff
@@ -0,0 +1,123 @@
...
+	return ret;
+}
+
+bool anyFalse(std::vector<bool> const& _mask)
+{
+	return any_of(_mask.begin(), _mask.end(), [](bool b){ return !b; });
+}
+
+/// Find functions whose body satisfies a heuristic about pruning. Returns true if applying
+/// UnusedFunctionParameterPruner is not helpful or redundant because the inliner will be able to
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Does it still make sense to formulate it in such a complicated way?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 77]
```diff
@@ -0,0 +1,123 @@
...
+	std::vector<T> ret;
+
+	for (size_t i = 0; i < _mask.size(); ++i)
+		if (_mask[i])
+			ret.push_back(_vec[i]);
+
+	return ret;
+}
+
+bool anyFalse(std::vector<bool> const& _mask)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Not used anymore.

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 78]
```diff
@@ -0,0 +1,123 @@
...
+
+#include <libsolutil/CommonData.h>
+
+#include <variant>
+
+namespace solidity::yul::unusedFunctionsCommon
+{
+
+template<typename T>
+std::vector<T> applyBooleanMask(std::vector<T> const& _vec, std::vector<bool> const& _mask)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: Did we consider calling this `filter`?

Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionsCommon.h]: I changed the name to `filter`, perhaps more appropriate for c++.

File: libyul/optimiser/UnusedFunctionParameterPruner.cpp (hunk 74 above)
Comment (hrkrshnn) [reply libyul/optimiser/UnusedFunctionParameterPruner.cpp:107]: I moved the modifications for the original function to be outside now.

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 79]
```diff
@@ -0,0 +1,114 @@
...
+bool tooSimpleToBePruned(FunctionDefinition const& _f)
+{
+	return _f.body.statements.size() <= 1 && CodeSize::codeSize(_f.body) <= 1;
+}
+
+FunctionDefinition createLinkingFunction(
+	FunctionDefinition const& _original,
+	std::pair<std::vector<bool>, std::vector<bool>> const& _usedParametersAndReturns,
+	YulString const& _originalFunctionName,
+	YulString const& _newFunctionName,
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]: linkingFunctionName?

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 80]
```diff
@@ -0,0 +1,114 @@
...
+	TypedNameList renamedReturnVariables = util::applyMap(_original.returnVariables, generateTypedName);
+	TypedNameList reducedRenamedReturnVariables = filter(renamedReturnVariables, _usedParametersAndReturns.second);
+
+	FunctionDefinition newFunction{
+		loc,
+		_newFunctionName,
+		renamedParameters,
+		renamedReturnVariables,
+		{loc, {}} // body
+	};
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]:
```suggestion
	FunctionDefinition linkingFunction{
		loc,
		_linkingFunctionName,
		util::applyMap(_original.parameters, generateTypedName),
		util::applyMap(_original.returnVariables, generateTypedName),
		{loc, {}} // body
	};
```

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 81]
```diff
@@ -0,0 +1,114 @@
...
+
+	FunctionCall call{loc, Identifier{loc, _originalFunctionName}, {}};
+	for (auto const& p: reducedRenamedParameters)
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]:
```suggestion
	for (auto const& p: filter(linkingFunction.parameters, _usedParametersAndReturns.first))
```

File: libyul/optimiser/UnusedFunctionsCommon.h [hunk 82]
```diff
@@ -0,0 +1,114 @@
...
+		// The LHS of the assignment.
+		for (auto const& r: reducedRenamedReturnVariables)
+			assignment.variableNames.emplace_back(Identifier{loc, r.name});
+
+		assignment.value = std::make_unique<Expression>(std::move(call));
+
+		newFunction.body.statements.emplace_back(std::move(assignment));
+	}
+	else
+		newFunction.body.statements.emplace_back(ExpressionStatement{loc, std::move(call)});
```
Comment (chriseth) [inline libyul/optimiser/UnusedFunctionsCommon.h]:
```suggestion
	Assignment assignment;
	assignment.location = loc;

	// The LHS of the assignment.
	for (auto const& r: filter(linkingFunction.returnVariables, _usedParametersAndReturns.second))
		assignment.variableNames.emplace_back(Identifier{loc, r.name});

	assignment.value = std::make_unique<Expression>(std::move(call));

	if (assignment.variableNames.empty())
		// no assignment if there are no variables left
		newFunction.body.statements.emplace_back(ExpressionStatement{loc, std::move(call)});
	else
		newFunction.body.statements.emplace_back(std::move(assignment));
```

**Review by chriseth — APPROVED** [review]
