### PR TITLE
[SMTChecker] Fix analysis of push to a string casted to bytes

### LINKED ISSUE #10914: [SMTChecker] Bad cast in arrayPushPopAssign
## Description

```
contract C{string x;function s()public{bytes(x).push();}}
```

throws std::bad_cast here

https://github.com/ethereum/solidity/blob/ec62d12319b1b9731da5822155c428d651ab0a0a/libsolidity/formal/SMTEncoder.cpp#L1658

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by blishko**
Fixes #10914.
This PR consists of two changes:
First change fixes the crash because of an invalid cast in case `push` is called on `string` casted to `bytes`.
The second change (introducing the `cleanExpression` method) ensures that the push is registered on the correct symbolic array.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -2608,6 +2610,32 @@ Expression const* SMTEncoder::innermostTuple(Expression const& _expr)
...
 
+Expression const* SMTEncoder::cleanExpression(Expression const& _expr)
+{
+	auto const* expr = &_expr;
+	if (auto const* tuple = dynamic_cast<TupleExpression const*>(expr))
+		return cleanExpression(*innermostTuple(*tuple));
+	if (auto const* functionCall = dynamic_cast<FunctionCall const*>(expr))
+		if (
+			auto typeType = dynamic_cast<TypeType const*>(functionCall->expression().annotation().type);
+			typeType && *functionCall->annotation().kind == FunctionCallKind::TypeConversion
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]: Do we really need to check `typeType` if we know it's a TypeConversion?

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -2608,6 +2610,32 @@ Expression const* SMTEncoder::innermostTuple(Expression const& _expr)
 	return expr;
 }
 
+Expression const* SMTEncoder::cleanExpression(Expression const& _expr)
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2613]: Nice! There are probably several places in the code we could cleanup by extending and using this function, but can be done in another  PR.

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: I was hoping this whole check could be simplified somehow. Maybe it is not necessary to check the result of the cast, but the cast itself is necessary, to extract the actual type.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Right. How about only use the TypeConversion part here, and if that's true, assert that `typeType` is non null?

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: That should work, I have updated the code according to this suggestion.

**Review by leonardoalt — APPROVED** [review]
