### PR TITLE
[CLI] Improve error handling of missing/unwriteable files

### LINKED ISSUE #6643: [CommonIO] readFile and issues management
The File Reading Operation have 2 possible failure reasons

1) File does not exist 

https://github.com/ethereum/solidity/blob/develop/libdevcore/CommonIO.cpp#L49

2) File is empty 

https://github.com/ethereum/solidity/blob/develop/libdevcore/CommonIO.cpp#L55

both are managed just returning an empty (or better, default constructed return type) but would not it be better to raise an exception ? 

Maybe, it could be possible to build an immutable type moving the IO operation (and the related exceptions) in its constructor 

Alternatively, if exceptions are not an option it could be possible to rely on a Maybe Monad ( or Boost Optional in C++ terms :) ) for the return value to discriminate between valid and non valid values in a formal way (without relying on implicit semantic )

### PR DESCRIPTION
**Pull request by axic**
Fixes #6643.

### CODE REVIEW

File: solc/CommandLineInterface.cpp [hunk 1]
```diff
@@ -738,7 +743,11 @@ void CommandLineInterface::createFile(string const& _fileName, string const& _da
 	ofstream outFile(pathName);
 	outFile << _data;
 	if (!outFile)
-		BOOST_THROW_EXCEPTION(FileError() << errinfo_comment("Could not write to file: " + pathName));
+	{
+		serr() << "Could not write to file \"" << pathName << "\"." << endl;
```
Comment (axic) [inline solc/CommandLineInterface.cpp:747]: It is not possible to test for this with the current testing infra.

However, before:
```
Exception during output generation: /Users/alex/Projects/solidity/solc/CommandLineInterface.cpp(748): Throw in function void solidity::frontend::CommandLineInterface::createFile(const std::__1::string &, const std::__1::string &)
Dynamic exception type: boost::wrapexcept<FileError>
std::exception::what: FileError
[solidity::util::tag_comment*] = Could not write to file: outdir/C.bin
```

After:
```
Could not write to file "outdir/C.bin".
```

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -643,6 +644,10 @@ bool CommandLineInterface::parseLibraryOption(string const& _input)
 	{
 		// Thrown e.g. if path is too long.
 	}
+	catch (FileNotFound const&)
+	{
+		// Should not happen if `fs::is_regular_file` is correct.
```
Comment (leonardoalt) [inline solc/CommandLineInterface.cpp:649]: Shouldn't `assert(false)` here then?

Comment (axic) [reply solc/CommandLineInterface.cpp:649]: Sounds like a good idea. Or couldn't just not catch the exception and leave a comment as in other places.

However, shouldn't we abort with an error in case of the `PathTooLong` case?

Comment (leonardoalt) [reply solc/CommandLineInterface.cpp:649]: Yea think so too

Comment (leonardoalt) [reply solc/CommandLineInterface.cpp:649]: Not sure if this should be done here or in a new PR

**Review by leonardoalt — APPROVED** [review]
