### PR TITLE
[SMTChecker] Add static array length constraint

### LINKED ISSUE #11679: [SMTChecker] Length of static array not taken into account in type constraints
```
contract C {
	function f(address[2] memory a) public pure {
		assert(a.length == 2);
	}
}
```
This assertion should hold but it fails.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/11679

### CODE REVIEW

File: libsolidity/formal/SymbolicTypes.cpp [hunk 1]
```diff
@@ -551,6 +551,11 @@ smtutil::Expression symbolicUnknownConstraints(smtutil::Expression _expr, fronte
 	solAssert(_type, "");
 	if (isEnum(*_type) || isInteger(*_type) || isAddress(*_type) || isFixedBytes(*_type))
 		return _expr >= minValue(_type) && _expr <= maxValue(_type);
+	else if (
+		auto arrayType = dynamic_cast<ArrayType const*>(_type);
+		arrayType && !arrayType->isDynamicallySized()
+	)
+		return smtutil::Expression::tuple_get(_expr, 1) == arrayType->length();
```
Comment (axic) [inline libsolidity/formal/SymbolicTypes.cpp:558]: Hm, wouldn't it be useful adding `&& (arrayType->length() >= 0)` (as below) here too?

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:558]: but that would just be redundant, here we're already assigning the exact value

Comment (axic) [reply libsolidity/formal/SymbolicTypes.cpp:558]: Ah `->length()` is the actual Solidity type, not a symbolic variable as the function name suggests.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicTypes.cpp:558]: since `arrayType->length()` is not symbolic, but rather a concrete value at this point

File: test/libsolidity/smtCheckerTests/types/array_static_aliasing_memory_5.sol [hunk 2]
```diff
@@ -1,9 +1,6 @@
 contract C
 {
 	function f(uint[2] memory a, uint[2] memory b, uint[2] memory c) public pure {
-		require(a.length > 0);
-		require(b.length > 0);
-		require(c.length > 0);
```
Comment (axic) [inline test/libsolidity/smtCheckerTests/types/array_static_aliasing_memory_5.sol:6]: Why remove these? To ensure this case tests aliasing only?

File: test/libsolidity/smtCheckerTests/types/static_array_length_2.sol [hunk 3]
```diff
@@ -0,0 +1,10 @@
+contract C {
+	function f() public pure returns (address[2] memory a) {
+		assert(a.length == 2); // should hold
+		assert(a.length < 2); // should fail
```
Comment (axic) [inline test/libsolidity/smtCheckerTests/types/static_array_length_2.sol:4]: Could also add `a.length > 2` for fail.

File: test/libsolidity/smtCheckerTests/types/array_static_aliasing_memory_5.sol (hunk 2 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/types/array_static_aliasing_memory_5.sol:6]: They're redundant since the type ensures that length == 2

File: test/libsolidity/smtCheckerTests/types/static_array_length_2.sol (hunk 3 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/types/static_array_length_2.sol:4]: Added

**Comment by leonardoalt** [comment]
@axic was that approval? :grimacing:

**Review by axic — APPROVED** [review]
