### PR TITLE
SMTChecker: Fix analysis for selected contracts

### LINKED ISSUE #14275: [SMTChecker] Option `--model-checker-contract` does not work as expected
Consider the following two contracts:
```
contract D {
    function dec(uint v) public pure returns (uint) {
        --v;
        return v;
    }
}

contract C {
    function f() public pure returns (uint) {
        uint ret = d.dec(0);
        return ret;
    }
}
```

We would like to check that SMTChecker detects the underflow in `D.dec` when `C.f` is called.
However, with default settings, it will much more likely detect the underflow when `D.dec` is called directly.

We should have an option to restrict the analysis to consider only contract C as the entry point.
There exists an option, `--model-checker-contract` , that should allow us to restrict the analysis, but currently it does not work as expected.
At the moment, SMTChecker analyzes all contracts in the source unit specified with this option, disregarding the actual contract specified.

In my opinion, the option should restrict the possible entry point to the contracts specified, but we still need to analyze other contracts if their functions are called from the analyzed contract and we are in the trusted mode.

If we manage to resolve this issue, we should add the test above to SMTChecker's test suite for trusted external calls.

### LINKED ISSUE #15836: [SMTChecker] Option --model-checker-contract in combination with trusted external calls causes unsound CHC analysis
CHC analysis does not work correctly if a contract calls another contract that is defined in a different file and external calls are trusted (`--model-checker-ext-calls=trusted` and only the first contract is selected for analysis (with `--model-checker-contracts`).

File `A.sol`
```solidity
contract A { function a() pure public { } }
```

File `B.sol`
```solidity
import "A.sol";
contract B { function b(A a) pure public { a.a(); assert(false); } }
```

Command-line arguments: `--model-checker-engine chc B.sol --model-checker-ext-calls trusted --model-checker-contracts B.sol:B`
**Expected outcome**: Reported assertion violation in `B.b`
**Incorrect actual outcome**: CHC engine reports the assertion as safe.

NOTE: The analysis works as expected if the two contracts live in the same file.

### PR DESCRIPTION
**Pull request by blishko**
Previously, when a contract was selected for analysis, the analysis was incorrect.
There were two issues. First, the contracts in the same file were considered as entry points even though they were not selected for analysis.
Second, the contracts in a different file were mostly ignored, resulting in unsoundness when an external call was made to such a contract in trusted mode.

The solution to the above problems is to always create representation of all contracts (in case they are called from the selected contract), but create verification targets only for the selected contracts.

Fixes #15836.
Fixes #14275.

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `b3c21f10f09963b2819842f82afca783fbaff6a1`:
```
Error: Trailing whitespace found:
Changelog.md:19: * SMTChecker: Fix incorrect analysis when only a subset of contracts is selected with `--model-checker-contracts`. 

```
Please check that your changes are working as intended.

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -1098,13 +1098,18 @@ bool SMTEncoder::shouldAnalyze(SourceUnit const& _source) const
 		m_settings.contracts.has(*_source.annotation().path);
 }
 
+bool SMTEncoder::skipContract(ContractDefinition const& _contract) const
```
Comment (cameel) [inline libsolidity/formal/SMTEncoder.cpp]: You should put this above `SMTEncoder::shouldAnalyze()`. It's easier to find stuff when it's in the same order as in the header. And especially putting it between two overloads is confusing. At first I missed the fact that there's even two of them overload because I did not expect that :)

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -1098,13 +1098,18 @@ bool SMTEncoder::shouldAnalyze(SourceUnit const& _source) const
...
+{
+	return !_contract.canBeDeployed();
+}
+
 bool SMTEncoder::shouldAnalyze(ContractDefinition const& _contract) const
 {
-	if (!_contract.canBeDeployed())
+	if (skipContract(_contract))
```
Comment (cameel) [inline libsolidity/formal/SMTEncoder.cpp]: I think this would be clearer not wrapped in a helper. `!_contract.canBeDeployed()` is short enough and immediately tells me what it's about. With `skipContract()` I had to go to the definition to understand how it's different from just `!shouldAnalyze()`.

File: libsolidity/formal/CHC.cpp [hunk 3]
```diff
@@ -239,14 +239,15 @@ void CHC::endVisit(ContractDefinition const& _contract)
 	setCurrentBlock(*m_constructorSummaries.at(&_contract));
 
 	solAssert(&_contract == m_currentContract, "");
-	if (shouldAnalyze(_contract))
+	if (!skipContract(_contract))
```
Comment (cameel) [inline libsolidity/formal/CHC.cpp]: Shouldn't this be an assert? It has already been checked at the beginning of the function.

Comment (cameel) [reply libsolidity/formal/CHC.cpp]: And the `skipContract()` checks in `CHC::endVisit(ContractDefinition)` `CHC::endVisit(FunctionDefinition)` seem like they should be asserts as well, because the one in `CHC::visit(ContractDefinition)` will not let us reach those places for such contracts.

File: test/libsolidity/SMTCheckerTest.cpp [hunk 4]
```diff
@@ -32,8 +32,13 @@ SMTCheckerTest::SMTCheckerTest(std::string const& _filename):
...
 {
 	auto contract = m_reader.stringSetting("SMTContract", "");
-	if (!contract.empty())
+	auto maybeContracts = ModelCheckerContracts::fromString(contract);
+	if (maybeContracts)
+		m_modelCheckerSettings.contracts = *maybeContracts;
+	else if (!contract.empty())
 		m_modelCheckerSettings.contracts.contracts[""] = {contract};
+	else
+		BOOST_THROW_EXCEPTION(std::runtime_error("Invalid contract specified."));
```
Comment (cameel) [inline test/libsolidity/SMTCheckerTest.cpp]: I'm not sure why `fromString()` is even defined as returning `optional`, because it never returns `nullopt`. You can just assert that, or better, remove the optional and the error.

Comment (cameel) [reply test/libsolidity/SMTCheckerTest.cpp]: BTW if you do end up keeping the error for some reason, I'd at least mention the setting name. These exceptions do not point at a specific place in the test that's wrong so it may be confusing otherwise.

File: test/libsolidity/smtCheckerTests/imports/selected_contract_2.sol
Comment (cameel) [inline test/libsolidity/smtCheckerTests/imports/selected_contract_2.sol:1]: Please put more detail in test names. If you need to put a number in there to make it unique it's a clear sign that some important detail is missing :) Vague test names are really annoying because the name is often the only hint you get about what it's meant to do without digging through history/PRs (and even then it's often unclear).

- `selected_contract.sol` -> `target_in_imported_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol`
- `selected_contract_2.sol` -> `target_in_imported_contract_analyzed_when_called_from_selection_with_trusted_calls.sol`

File: test/libsolidity/smtCheckerTests/imports/selected_contract.sol [hunk 5]
```diff
@@ -0,0 +1,10 @@
+==== Source: A.sol ====
+contract A { function a() pure public { assert(false); } }
+==== Source: B.sol ====
+import "A.sol";
+contract B { function b() pure public { assert(false); } }
+// ====
+// SMTContract: B.sol:B
+// SMTEngine: chc
+// ----
+// Warning 6328: (B.sol:56-69): CHC: Assertion violation happens here.\nCounterexample:\n\n\nTransaction trace:\nB.constructor()\nB.b()
```
Comment (cameel) [inline test/libsolidity/smtCheckerTests/imports/selected_contract.sol]: IMO the purpose of this test would be clearer without the assert in `B.b()`. We'd then immediately see that no warning is generated instead of having to check where it's generated and whether that's expected or not.

File: test/cmdlineTests/model_checker_contracts_inexistent_contract/err
Comment (cameel) [inline test/cmdlineTests/model_checker_contracts_inexistent_contract/err:1]: The name is a bit confusing, but from `args` I assume it was meant to be `nonexistent_contract`, rather than a typo of `in_existent_contract`?

Same for the Standard JSON version of the test.

**Review by cameel — DISMISSED** [review]
I'm going to approve since everything seems correct, but there some minor things that would be good to clean up before we merge.

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: Fixed the location of the function definition. Also renamed the methods, more on that in the comment below.

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: I think the helper is useful, but you are right that the names were confusing.
I renamed the methods to hopefully better reflect their purpose.
The helper should exactly give the high-level idea what is being checked, instead of giving the exact way how the condition is checked. Especially since it may happen that the condition would need to be updated in the future. (The problem that the wrong thing was checked in the wrong place is exactly what this PR is trying to fix.)

File: libsolidity/formal/CHC.cpp (hunk 3 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: Yes, here it should be an assert, updated.
In the other places, I believe the condition should not be converted into an assert.
For example, `CHC::endVisit(ContractDefinition)` will be called even when `CHC::visit(ContractDefinition)` returns `false`.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (blishko) [reply test/libsolidity/SMTCheckerTest.cpp]: `fromString` has a path when it returns an empty optional. I have made that explicit with `std::nullopt`. Previously, `{}` was used.

File: test/libsolidity/smtCheckerTests/imports/selected_contract_2.sol
Comment (blishko) [reply test/libsolidity/smtCheckerTests/imports/selected_contract_2.sol:1]: I'll keep this in mind.
The names have been updated according to the suggestions.

File: test/libsolidity/smtCheckerTests/imports/selected_contract.sol (hunk 5 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/imports/selected_contract.sol]: I agree. Updated.

File: test/cmdlineTests/model_checker_contracts_inexistent_contract/err
Comment (blishko) [reply test/cmdlineTests/model_checker_contracts_inexistent_contract/err:1]: This is true.
The name was there before.
I am thinking of updating the name in a separate PR.

File: libsolidity/formal/SMTEncoder.h [hunk 6]
```diff
@@ -238,11 +238,12 @@ class SMTEncoder: public ASTConstVisitor
...
-	/// @returns true if @param _contract is set for analysis in the settings
-	/// and it is not abstract.
-	bool shouldAnalyze(ContractDefinition const& _contract) const;
-	/// @returns true if @param _source is set for analysis in the settings.
-	bool shouldAnalyze(SourceUnit const& _source) const;
+	/// @returns true if symbolic representation of @param _contract is required for verification
+	bool shouldEncode(ContractDefinition const& _contract) const;
+	/// @returns true if the verification targets of @param _contract are actually selected for verification
+	bool shouldAnalyzeVerificationTargetsFor(ContractDefinition const& _contract) const;
+	/// @returns true if the contracts in @param _source should be verified
```
Comment (cameel) [inline libsolidity/formal/SMTEncoder.h]: Would be good to clarify that this is not simply equivalent to checking whether this is true for any of the contracts. It seems possible for this to return `true` even though there are no contracts we should verify.

Maybe like this?
```suggestion
	/// @returns true if we should descend into @param _source to look for contracts that should be verified
```

File: test/libsolidity/smtCheckerTests/verification_target/target_in_constructor_of_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol [hunk 7]
```diff
@@ -0,0 +1,13 @@
+contract B {
+   constructor() { fail(); }
+
+   function fail() pure internal { assert(false); }
```
Comment (cameel) [inline test/libsolidity/smtCheckerTests/verification_target/target_in_constructor_of_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol]:
```suggestion
    constructor() { fail(); }

    function fail() pure internal { assert(false); }
```

`target_in_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol` has that too.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (cameel) [reply test/libsolidity/SMTCheckerTest.cpp]: Ah, right. I missed that. This logic still seems a bit off to me though. Especially the fact that an exception sounds like it should be thrown on invalid names but actually only happens when the entire setting is left empty.

For example, I think that something like this will fail the first check and enter the second branch:
```solidity
// SMTContract: a.sol:A, B, c.sol:C
```
which means that we'll try to use `a.sol:A, B, c.sol:C` as a contract name, without reporting an error. A more robust way to do it would be to check whether the string contains `:`, `,` or whitespace and report the error when it does, not just when it's empty.

File: libsolidity/formal/CHC.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/formal/CHC.cpp]: You're right. I assumed `endVisit()` would be skipped, but it won't.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (cameel) [reply test/libsolidity/SMTCheckerTest.cpp]: BTW, note that an empty source name is actually something that can happen. You can't do this on the CLI, but in Standard JSON source names can be arbitrary strings, including empty ones. There are some quirks around their behavior (#15747) and I think we'd be better off disallowing them, but for the time being they're technically valid.

And they can contain `:` and `,` even on the CLI (as long as the file system allows this). Only contract names are guaranteed to be identifiers.

This does not matter all that much for testing, but AFAIK `fromString()` is also used for parsing the value of the option in normal operation, so it means that SMTChecker probably can't process contracts in some weirdly named files.

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (cameel) [reply libsolidity/formal/SMTEncoder.cpp]: Well, sometimes I find it better not to abstract things too much when the code is straightforward and not likely to change. This condition seemed to me like such a case.

But ok, the new names are much better so if you expect that it may have to change or just  prefer it that way, that's fine with me.

File: test/libsolidity/smtCheckerTests/verification_target/target_in_constructor_of_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol (hunk 7 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/verification_target/target_in_constructor_of_same_source_contract_not_analyzed_when_not_selected_and_not_called_from_selection.sol]: Fixed.

File: libsolidity/formal/SMTEncoder.h (hunk 6 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.h]: I used your wording.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (blishko) [reply test/libsolidity/SMTCheckerTest.cpp]: I'll have to double-check this, but you are probably right.
I'll see if I can make the parsing more robust without too much effort.

> This does not matter all that much for testing, but AFAIK fromString() is also used for parsing the value of the option in normal operation, so it means that SMTChecker probably can't process contracts in some weirdly named files.

I would prefer to ignore weirdly named files for now, unless someone complains.

Comment (cameel) [reply test/libsolidity/SMTCheckerTest.cpp]: > I would prefer to ignore weirdly named files for now, unless someone complains.

I really think we should be consistent about it. If the rest of the compiler works like this, the SMTChecker should too.

Though of course it's a very low priority thing. From my point of view it's a bug, but it's perfectly fine to just file it and only get to it when there's nothing more important to work on.

I'd also like to make the path situation saner in one of the breaking releases so not jumping right at it is actually good, but I can't say when that will happen, and some of these things will still be problematic (e.g. I don't see us really disallowing commas or colons in paths).

File: Changelog.md [hunk 8]
```diff
@@ -7,6 +7,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * SMTChecker: Fix incorrect analysis when only a subset of contracts is selected with `--model-checker-contracts`.
```
Comment (cameel) [inline Changelog.md]: One last thing. We have this weird inconsistency where some Markdown files use double backticks and some use single ones. Some lists also have this weird one space indent before bullet points. We stuck to it for the sake of consistencym, but it has always been annoying, because people are often confused which one to use where. I'd like to switch to a saner style for the `CHANGELOG` from this release on (https://github.com/ethereum/solidity/pull/15930#discussion_r1994417204).

```suggestion
* SMTChecker: Fix incorrect analysis when only a subset of contracts is selected with `--model-checker-contracts`.
```

Your entry is the first one, and hopefully ones added later will just follow this new style.

Comment (blishko) [reply Changelog.md]: OK, so, single backticks and no space at the beginning.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (blishko) [reply test/libsolidity/SMTCheckerTest.cpp]: I have created https://github.com/ethereum/solidity/issues/15945 to keep track of this issue.

I think this was the last issue regarding this PR?

Comment (cameel) [reply test/libsolidity/SMTCheckerTest.cpp]: Yes. Still does not seem resolved though. I expected you'd replace the check for empty with one for strings containing `:`, `,` or whitespace.

I mean, I'm not going to block the PR because of that, but it seems straightforward to address. To be clear I'm not talking about a fix for #15945, just adjusting this one place that parses the test setting.

**Review by cameel — DISMISSED** [review]
Approving so that you can merge already if you really want to, since nearly everything has been addressed and the fix is correct. Would be nice if we could still do https://github.com/ethereum/solidity/pull/15880#discussion_r1997640323 though.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (blishko) [reply test/libsolidity/SMTCheckerTest.cpp]: Sorry, I missed that objection.
I guess I don't quite understand what you would like to see there.
This is about our test setup.
Previously, any value for `SMTContract` was accepted, unless it was an empty string, in which case it was silently ignored.
I am adding an option to refer to a specific contract in a specific file in a multi-file scenario and I also wanted to turn the empty string case into error.
It would make sense to check if the string is a valid contract name, but that seems more general than what you suggested, no?

Comment (blishko) [reply test/libsolidity/SMTCheckerTest.cpp]: After thinking about it more, I added a stronger check for a valid contract name.
Is that what you had in mind, @cameel?

File: test/libsolidity/SMTCheckerTest.cpp [hunk 9]
```diff
@@ -32,8 +32,17 @@ SMTCheckerTest::SMTCheckerTest(std::string const& _filename):
 	universalCallback(nullptr, smtCommand)
 {
 	auto contract = m_reader.stringSetting("SMTContract", "");
-	if (!contract.empty())
+	auto maybeContracts = ModelCheckerContracts::fromString(contract);
+	auto isValidContractName = [](std::string const& name)
```
Comment (cameel) [inline test/libsolidity/SMTCheckerTest.cpp]:
```suggestion
	auto isValidContractName = [](std::string const& _name)
```

**Review by cameel — DISMISSED** [review]

File: test/libsolidity/SMTCheckerTest.cpp (hunk 9 above)
Comment (blishko) [reply test/libsolidity/SMTCheckerTest.cpp]: Fixed.

File: test/libsolidity/SMTCheckerTest.cpp (hunk 4 above)
Comment (cameel) [reply test/libsolidity/SMTCheckerTest.cpp]: > Previously, any value for `SMTContract` was accepted, unless it was an empty string, in which case it was silently ignored.

True, the old code would accept pretty weird things in this field without error, so I guess you have a point - it's not your PR that introduced this. But when it was just supposed to be an identifier, not having a validation here was acceptable, even if not great. Now, with added syntax, you can easily make mistakes like `a.sol:A, B, c.sol:C` and I really think they should not be silently ignored when we can easily validate against them.

> Is that what you had in mind, @cameel?

Yes, looks good now.

**Review by cameel — APPROVED** [review]
