### PR TITLE
[SMTChecker] Fix internal error when array.push() is used as = LHS

### LINKED ISSUE #9743: [SMTChecker] ICE in SMTEncoder::assignment
## Description

```
pragma experimental SMTChecker;
contract C {
  int[][] array2d;
  function s() internal returns (int[] storage) {
    array2d.push() = array2d.push();
    return array2d[2];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/f964966090f7e3571e20144fd4aa0b6391aea26e/libsolidity/formal/SMTEncoder.cpp#L1497

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

### LINKED ISSUE #9744: [SMTChecker] ICE in unaryoperator end visit
## Description

```
pragma experimental SMTChecker;
contract C {
  int[][] array2d;
  function s() internal returns (int[] storage) {
    delete array2d.push();
    return array2d[2];
  }
}
```

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

### LINKED ISSUE #10058: [SMTChecker] ICE in void solidity::frontend::SMTEncoder::assignment(const solidity::frontend::Expression &, const smtutil::Expression &, const solidity::frontend::TypePointer &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
	struct S {
		int[] b;
	}
	S s;
	struct T {
		S s;
	}
	T t;
	function f() public {
		s.b.push()=
		t.s.b.push();
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1783): Throw in function void solidity::frontend::SMTEncoder::assignment(const solidity::frontend::Expression &, const smtutil::Expression &, const solidity::frontend::TypePointer &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

We've seen ICEs in this code before (#9901 is notably similar, but I just checked and it is still fixed), probably just another corner case of this general pattern.

## Environment

- Compiler version:  0.7.4-develop.2020.10.16+commit.eedd12ad.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/9743
Fixes https://github.com/ethereum/solidity/issues/9744
Fixes https://github.com/ethereum/solidity/issues/10058

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -348,13 +348,46 @@ void SMTEncoder::endVisit(VariableDeclarationStatement const& _varDecl)
 
 }
 
+bool SMTEncoder::visit(Assignment const& _assignment)
+{
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:352]: I had this block of code in `endVisit(Assignment)`, but it doesn't work for `a.push() = a.push()` because of the visit order, so had to move it here. Still not 100% sure, but couldn't come up with anything better so far

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -348,13 +348,46 @@ void SMTEncoder::endVisit(VariableDeclarationStatement const& _varDecl)
...
+	auto const& left = _assignment.leftHandSide();
+	auto const& right = _assignment.rightHandSide();
+
+	if (auto const* memberAccess = isEmptyPush(left))
+	{
+		right.accept(*this);
+		left.accept(*this);
+
+		auto const& memberExpr = memberAccess->expression();
+		auto& symbArray = dynamic_cast<smt::SymbolicArrayVariable&>(*m_context.expression(memberExpr));
```
Comment (mijovic) [inline libsolidity/formal/SMTEncoder.cpp:362]: Can we add const here? I think only `.elements` and `.length` are used, which are marked as `const`
```suggestion
		auto const& symbArray = dynamic_cast<smt::SymbolicArrayVariable&>(*m_context.expression(memberExpr));
```

File: test/libsolidity/smtCheckerTests/array_members/push_as_lhs_3d.sol [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+		// Fails
+		assert(c[length1 - 1][length2 - 1][length3 - 1] == 200);
+	}
+}
+// ----
+// Warning 6328: (431-450): CHC: Assertion violation might happen here.
+// Warning 6328: (454-474): CHC: Assertion violation might happen here.
+// Warning 6328: (478-498): CHC: Assertion violation might happen here.
+// Warning 6328: (502-555): CHC: Assertion violation might happen here.
+// Warning 6328: (570-625): CHC: Assertion violation might happen here.
```
Comment (mijovic) [inline test/libsolidity/smtCheckerTests/array_members/push_as_lhs_3d.sol]: Why CHC reports that violation might happen?

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/array_members/push_as_lhs_3d.sol]: Both engines report `might happen` when they're not able to solve a query.

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/array_members/push_as_lhs_3d.sol]: Maybe we should actually change that message to something more precise

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (mijovic) [reply libsolidity/formal/SMTEncoder.cpp:352]: If there is no better way, let's leave it as is

File: libsolidity/formal/SMTEncoder.cpp [hunk 4]
```diff
@@ -348,13 +348,46 @@ void SMTEncoder::endVisit(VariableDeclarationStatement const& _varDecl)
...
+		smtutil::Expression oldElements = symbArray.elements();
+		smtutil::Expression oldLength = symbArray.length();
+		symbArray.increaseIndex();
+		m_context.addAssertion(symbArray.elements() == smtutil::Expression::store(
+			oldElements,
+			oldLength - 1,
+			expr(right)
+		));
```
Comment (mijovic) [inline libsolidity/formal/SMTEncoder.cpp]: Can you explain me here, why `oldLength -1`, I am not exactly sure about it?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Because the actual `push` was already handled inside `left.accept`, so the length was already increased. Here we only assign the right hand side to the newly created last position. Maybe the name `oldLength` is misleading, since the length doesn't change here.

File: test/libsolidity/smtCheckerTests/array_members/push_as_lhs_3d.sol (hunk 3 above)
Comment (mijovic) [reply test/libsolidity/smtCheckerTests/array_members/push_as_lhs_3d.sol]: We should consider changing that message probably. We should open issue for that and do it sometime in future.

File: libsolidity/formal/SMTEncoder.cpp (hunk 4 above)
Comment (mijovic) [reply libsolidity/formal/SMTEncoder.cpp]: I was thinking that it is because it length was already increased. Can you, please, than change the name of `oldLength` to `lenght` or something similar?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Yep, will change

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:362]: We can't because of `increaseIndex` below

**Comment by leonardoalt** [comment]
Updated & rebased

**Review by mijovic — APPROVED** [review]
