### PR TITLE
[SMTChecker] Check for under/overflow in the end of the function

### LINKED ISSUE #3871: SMT: Only fail if control flow does not revert
The snippet
```
uint y = x + 1;
require(y > x) ;
```
should not report overflow failure.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #3871 #5302

The underflow and overflow checks are stored and only computed at the end of the function while using the function body constraints.
Also, arithmetic operations use mod to mimic the EVM behavior.

### CODE REVIEW

**Comment by leonardoalt** [comment]
New tests missing.

File: libsolidity/formal/SMTChecker.cpp [hunk 1]
```diff
@@ -376,8 +414,13 @@ void SMTChecker::endVisit(UnaryOperation const& _op)
 	case Token::Sub: // -
 	{
 		defineExpr(_op, 0 - expr(_op.subExpression()));
-		if (auto intType = dynamic_cast<IntegerType const*>(_op.annotation().type.get()))
-			checkUnderOverflow(expr(_op), *intType, _op.location());
+		if (dynamic_cast<IntegerType const*>(_op.annotation().type.get()))
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp:417]: Personally I like ``op.annotation().type->category() == Type::Category::Integer`` better, if the pointer isn't used afterwards. In theory it can even be faster (but probably mainly in complex multiple inheritance settings). But it doesn't really matter, so I'd be fine with keeping it.

File: libsolidity/formal/SMTChecker.cpp [hunk 2]
```diff
@@ -853,9 +896,41 @@ void SMTChecker::arithmeticOperation(BinaryOperation const& _op)
...
+		addOverflowTarget(
+			OverflowTarget::Type::All,
+			_op.annotation().commonType,
+			value,
+			_op.location()
+		);
 
 		defineExpr(_op, value);
+
+		smt::Expression powerOf2 = (0 - minValue(intType)) + maxValue(intType) + 1;
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp]: I would call this ``intValueRange`` or sth like that - it'd work just as well, if it wasn't a power of two. But again: doesn't matter too much.

File: libsolidity/formal/SMTChecker.cpp [hunk 3]
```diff
@@ -853,9 +896,41 @@ void SMTChecker::arithmeticOperation(BinaryOperation const& _op)
...
+					expr(_op) - powerOf2,
+					expr(_op)
+				));
+			}
+		}
+		else if (op == Token::Sub)
+		{
+			defineExpr(_op, smt::Expression::ite(
+				value < minValue(intType),
+				value % powerOf2,
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp]: So for ``value = -129``... this is ``-129 % 256``... is this always ``127``?
Can you instead do ``value + powerOf2`` to avoid negative modulos?
I need to have another look at this in general...

File: libsolidity/formal/SMTChecker.cpp [hunk 4]
```diff
@@ -853,9 +896,41 @@ void SMTChecker::arithmeticOperation(BinaryOperation const& _op)
...
+			OverflowTarget::Type::All,
+			_op.annotation().commonType,
+			value,
+			_op.location()
+		);
 
 		defineExpr(_op, value);
+
+		smt::Expression powerOf2 = (0 - minValue(intType)) + maxValue(intType) + 1;
+		if (op == Token::Add || op == Token::Mul)
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp]: Does this work for positive and negative operands alike?

**Review by ekpyron — COMMENTED** [review]
Some comments - need to have another look later.

File: libsolidity/formal/SMTChecker.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTChecker.cpp:417]: Yes I agree with that. I'll write another PR replacing them throughout the code.

File: libsolidity/formal/SMTChecker.cpp (hunk 3 above)
Comment (ekpyron) [reply libsolidity/formal/SMTChecker.cpp]: This can probably be ignored - nobody will use negative representatives for remainders.

**Comment by leonardoalt** [comment]
@ekpyron Updated and added the tests you mentioned

File: libsolidity/formal/SMTChecker.cpp [hunk 5]
```diff
@@ -853,9 +896,30 @@ void SMTChecker::arithmeticOperation(BinaryOperation const& _op)
...
+		);
 
 		defineExpr(_op, value);
+
+		smt::Expression intValueRange = (0 - minValue(intType)) + maxValue(intType) + 1;
+		defineExpr(_op, smt::Expression::ite(
+			value > maxValue(intType) || value < minValue(intType),
+			value % intValueRange,
+			value
+		));
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp:911]: Ok, this catches all over- and underflows and after this we will always be positive in the range ``0..intValueRange``.

File: libsolidity/formal/SMTChecker.cpp [hunk 6]
```diff
@@ -853,9 +896,30 @@ void SMTChecker::arithmeticOperation(BinaryOperation const& _op)
...
+		if (intType.isSigned())
+		{
+			defineExpr(_op, smt::Expression::ite(
+				expr(_op) > maxValue(intType),
+				expr(_op) - intValueRange,
+				expr(_op)
+			));
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp:918]: And in the signed case if we should be negative this should correct that. Should be fine!

File: libsolidity/formal/SMTChecker.cpp [hunk 7]
```diff
@@ -853,9 +896,30 @@ void SMTChecker::arithmeticOperation(BinaryOperation const& _op)
...
 
-		checkUnderOverflow(value, intType, _op.location());
+		addOverflowTarget(
+			OverflowTarget::Type::All,
+			_op.annotation().commonType,
+			value,
+			_op.location()
+		);
 
 		defineExpr(_op, value);
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp]: Do we actually need this now, if it's re-defined two lines down anyways?

**Review by ekpyron — DISMISSED** [review]
Looks good now, although I'm not sure whether the one line I mentioned can be removed.

File: libsolidity/formal/SMTChecker.cpp (hunk 7 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTChecker.cpp]: Yes, for the `else` case (no underflow/overflow).

Comment (leonardoalt) [reply libsolidity/formal/SMTChecker.cpp]: Ah no, you're right, there's no guards now. Will remove.

File: libsolidity/formal/SMTChecker.cpp [hunk 8]
```diff
@@ -316,21 +319,56 @@ void SMTChecker::endVisit(TupleExpression const& _tuple)
...
+void SMTChecker::addOverflowTarget(
+	OverflowTarget::Type _type,
+	TypePointer _intType,
+	smt::Expression _value,
+	SourceLocation const& _location
+)
 {
+	m_overflowTargets.emplace_back(
+		_type,
+		_intType,
```
Comment (chriseth) [inline libsolidity/formal/SMTChecker.cpp]: could move

File: test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol [hunk 9]
```diff
@@ -16,3 +16,5 @@ contract C {
 // ----
 // Warning: (115-121): Unused local variable.
 // Warning: (356-370): Assertion violation happens here
+// Warning: (285-290): Underflow (resulting value less than 0) happens here
```
Comment (chriseth) [inline test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol:19]: Which expression triggered the overflow check here?

**Review by chriseth — CHANGES_REQUESTED** [review]
Please add a changelog entry and a small test that actually contains the classic overflow guard to show no smt warning.

File: test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol (hunk 9 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol:19]: These are caused by `x = 2` (overflow is checked at assignments) since all knowledge regarding variables that are touched inside the loop are erase.

**Comment by leonardoalt** [comment]
Rebased and added SafeMath tests. Forgot to delay division check, doing that now.

File: test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol (hunk 9 above)
Comment (chriseth) [reply test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol:19]: But how can `x=2` cause an underflow?

**Comment by chriseth** [comment]
Still missing changelog.

File: test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol (hunk 9 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol:19]: I'm assuming that since all information regarding `x` is erased it chooses any value for the expression, including negative ones. I'll check further.

File: Changelog.md [hunk 10]
```diff
@@ -4,6 +4,7 @@ Language Features:
 
 
 Compiler Features:
+ * SMTChecker: Reduce the number of underflow/overflow false positives.
```
Comment (chriseth) [inline Changelog.md]: Shouldn't this be more specific?

**Comment by Trazarw** [comment]
the matf is off for the buffer

File: Changelog.md (hunk 10 above)
Comment (leonardoalt) [reply Changelog.md]: Updated

File: test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol [hunk 11]
```diff
@@ -0,0 +1,15 @@
...
+		if (a == 0) {
+			return 0;
+		}
+		uint256 c = a * b;
+		require(c / a == b);
+		return c;
+	}
+}
+// ----
+// Warning: (180-185): Division by zero happens here
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol:15]: This false positive happens because the SMTChecker does not see the code after the `if` as an else, which it should due to the early return.

Comment (axic) [reply test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol:15]: Can we design an internal representation where instead of adding certain conditions (such as early return) we can simplify the AST? In this example wrap the other side into an else block.

Would such an option be worse complexity wise?

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol:15]: We actually wanted to do that to simplify some operations, for example compound assignments. Including that is a good idea.

File: test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol (hunk 9 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol:19]: Yes, the reason is that even though `x = 2` is added to the solver at that point, all the information created inside the loop body is popped from the solver after. So in the end when underflow/overflow are actually checked, this information is not there. What happens then is that the expression is a variable without constraints and the solver can give it values that cause underflow/overflow. This is all caused by assignments also triggering underflow/overflow checks. We could also remove that and always check on the right hand side only.

Comment (chriseth) [reply test/libsolidity/smtCheckerTests/loops/for_loop_trivial_condition_3.sol:19]: I'm just a little confused because assignment involving the same types should never cause an *erflow.

File: test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol (hunk 11 above)
Comment (chriseth) [reply test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol:15]: I agree that we should do that for certain cases, but, here I would actually say that a reachability analysis should be done instead, because we should do it anyway. Think of, for example
```
if (a == 0) {
  if (anotherComplicatedCondition()) return 0;
}
```
If we can prove that `anotherComplicatedCondition` always results in true, AST rewriting will not help, but reachability analysis will, and we should already have all the facts needed for reachability analysis, it's just the path constraints.

Currently, we check dead code by checking the condition of an if, perhaps we should instead check the combined path conditions after the if.

**Review by chriseth — APPROVED** [review]

File: test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol (hunk 11 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/overflow/safe_mul_2.sol:15]: What does "after the if" mean? We currently check the conjunction of path conditions with the if condition.
