### PR TITLE
[SMTChecker] Fix static virtual resolution

### LINKED ISSUE #10796: [SMTChecker] Unknown exception during compilation: map::at
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract BaseBase {
    function init(uint a, uint b) public virtual {
    }
}
contract Base is BaseBase {
    function init(uint a, uint b) public override {
    }
}
contract Child is Base {
    function bInit(uint c, uint d) public {
	BaseBase.init(c, d);
    }
}
```

produces:

```
Unknown exception during compilation: map::at
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.1-develop.2021.1.15+commit.726c5ff6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/10796

### CODE REVIEW

**Review by mijovic — DISMISSED** [review]
Looks good

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -2643,16 +2643,23 @@ pair<FunctionDefinition const*, ContractDefinition const*> SMTEncoder::functionC
...
 		{
 			auto super = _contract->superContract(*_contract);
 			solAssert(super, "Super contract not available.");
 			funDef = &funDef->resolveVirtual(*_contract, super);
 			contextContract = super;
 		}
+		else if (lookup == VirtualLookup::Static)
+			contextContract = funDef->annotation().contract;
+		else
+			solAssert(false, "");
```
Comment (bshastry) [inline libsolidity/formal/SMTEncoder.cpp]: Since `lookup` is of type `VirtualLookup` which is an enum class of three elements `Virtual`, `Super`, and `Static`, this assertion is redundant since all elements are covered. Could also be changed to a switch case, so the c++ compiler errors on unhandled cases if any.

File: test/libsolidity/smtCheckerTests/inheritance/overriden_function_static_call_parent.sol [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+contract Child is Base {
+	function bInit(uint c, uint d) public {
+		BaseBase.init(c, d);
+		assert(x == c);
+		assert(x == d); // should fail
+	}
+}
+// ----
+// Warning 5667: (84-90): Unused function parameter. Remove or comment out the variable name to silence this warning.
+// Warning 6328: (314-328): CHC: Assertion violation happens here.\nCounterexample:\nx = 0\nc = 0\nd = 1\n\nTransaction trace:\nChild.constructor()\nState: x = 0\nChild.bInit(0, 1)\n    BaseBase.init(0, 1) -- internal call
```
Comment (bshastry) [inline test/libsolidity/smtCheckerTests/inheritance/overriden_function_static_call_parent.sol:21]: Perhaps another test case where there is no inheritance?

```
pragma experimental SMTChecker;
contract C { function f() public {} }
contract D {
  function f() public {
    C c;
    c.f();
  }
}
```

**Review by bshastry — COMMENTED** [review]
Minor comments

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Done

File: test/libsolidity/smtCheckerTests/inheritance/overriden_function_static_call_parent.sol (hunk 2 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/inheritance/overriden_function_static_call_parent.sol:21]: @bshastry we already have tests like this one, the problem with the added test is exactly inheritance.

**Review by bshastry — APPROVED** [review]
