### PR TITLE
[SMTChecker] Carry error information across external calls

### LINKED ISSUE #10576: [SMTChecker] CHC does not report failing assertion
```
pragma experimental SMTChecker;

interface D { function e() external; }
   
contract C {
    bool locked = true;

    function call(address target) public {
        locked = false;
        D(target).e();
        locked = true;
    }

    function broken() public view {
        assert(locked);
    }
}   
```

The assertion is false if called by `D`, but CHC doesn't catch it because the `nondeterministic` predicates only model state changes, but not error conditions.

### PR DESCRIPTION
**Pull request by blishko**
Fixes #10576.

### CODE REVIEW

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -642,10 +642,18 @@ void CHC::externalFunctionCall(FunctionCall const& _funCall)
...
 	// TODO this could instead add the summary of the called function, where that summary
 	// basically has the nondet interface of this summary as a constraint.
 	m_context.addAssertion(nondet);
+	solAssert(m_errorDest, "");
+	connectBlocks(m_currentBlock, predicate(*m_errorDest), errorFlag().currentValue() > 0);
+	solAssert(m_currentContract && m_currentFunction, "");
+	for (auto const* base: m_currentContract->annotation().linearizedBaseContracts)
+		for (auto const* defined_function: base->definedFunctions())
+			if (!defined_function->isConstructor() && defined_function->isPublic())
+				m_callGraph[m_currentFunction].insert(defined_function);
```
Comment (blishko) [inline libsolidity/formal/CHC.cpp]: Probably add a comment that here we record that all external methods of the contract could be called from the external call made by us.

File: test/libsolidity/smtCheckerTests/blockchain_state/transfer.sol [hunk 2]
```diff
@@ -10,4 +10,4 @@ contract C {
 	}
 }
 // ----
-// Warning 6328: (199-234): CHC: Assertion violation happens here.\nCounterexample:\n\na = 21238\n\n\nTransaction trace:\nconstructor()\nf(21238)
+// Warning 6328: (199-234): CHC: Assertion violation happens here.\nCounterexample:\n\na = 2437\n\n\nTransaction trace:\nconstructor()\nf(2437)
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/blockchain_state/transfer.sol:13]: Maybe disable CEX here?

File: test/libsolidity/smtCheckerTests/external_calls/external.sol [hunk 3]
```diff
@@ -17,4 +17,4 @@ contract C {
 	}
 }
 // ----
-// Warning 6328: (200-214): CHC: Assertion violation happens here.\nCounterexample:\nx = 10, d = 0\n\n\n\nTransaction trace:\nconstructor()\nState: x = 0, d = 0\nf()\nState: x = 1, d = 0\nf()\nState: x = 2, d = 0\ng()
+// Warning 6328: (200-214): CHC: Assertion violation happens here.
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/external_calls/external.sol:20]: Check why we lost CEX here.

File: test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol [hunk 4]
```diff
@@ -34,4 +34,4 @@ contract C {
 	}
 }
 // ----
-// Warning 6328: (528-565): CHC: Assertion violation happens here.\nCounterexample:\nowner = 1, y = 0, z = 0, s = 0\n\n\n\nTransaction trace:\nconstructor()\nState: owner = 1, y = 0, z = 0, s = 0\ninv()
+// Warning 6328: (528-565): CHC: Assertion violation happens here.\nCounterexample:\nowner = 1, y = 0, z = 0, s = 0\n\n\n\nTransaction trace:\nconstructor()\nState: owner = 1, y = 0, z = 0, s = 0\nf()
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol]: This is a little weird. Can the call to `s.f()` be trusted? Do we know that that source code will be executed, or we cannot know that?

File: test/libsolidity/smtCheckerTests/external_calls/external_inc.sol [hunk 5]
```diff
@@ -21,5 +21,6 @@ contract C {
 // SMTIgnoreCex: yes
 // ----
 // Warning 4984: (146-149): CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
+// Warning 4984: (146-149): CHC: Overflow (resulting value larger than 2**256 - 1) might happen here.
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/external_calls/external_inc.sol:24]: We get the possible violation twice now. The original one is from calling `inc` directly. The new one is from calling `f` which calls external method, which can call `inc` and potentially cause overflow.

File: test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_1.sol [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+		D(target).e();
+		locked = true;
+	}
+
+	function broken() public view {
+		assert(locked);
+	}
+}  
+// ----
+// Warning 6328: (239-253): CHC: Assertion violation happens here.\nCounterexample:\nlocked = false\ntarget = 0\n\n\nTransaction trace:\nconstructor()\nState: locked = true\ncall(0)
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_1.sol:19]: This is the example from #10576

File: test/libsolidity/smtCheckerTests/functions/functions_external_2.sol [hunk 7]
```diff
@@ -17,5 +17,3 @@ contract C
 	}
 }
 // ----
-// Warning 6328: (297-321): CHC: Assertion violation might happen here.
-// Warning 4661: (297-321): BMC: Assertion violation happens here.
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/functions/functions_external_2.sol:21]: CHC can now prove the last assert. Should we change this example to allow changes to the `map`?

File: test/libsolidity/smtCheckerTests/operators/conditional_assignment_5.sol [hunk 8]
```diff
@@ -24,4 +24,4 @@ contract C {
 }
 // ----
 // Warning 2072: (282-288): Unused local variable.
-// Warning 6328: (304-328): CHC: Assertion violation happens here.\nCounterexample:\na = false, x = 3, d = 0\n\n\n\nTransaction trace:\nconstructor()\nState: a = false, x = 0, d = 0\nf()
+// Warning 6328: (304-328): CHC: Assertion violation happens here.\nCounterexample:\na = false, x = 3, d = 0\n\n = 0\n\nTransaction trace:\nconstructor()\nState: a = false, x = 0, d = 0\ng()
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/operators/conditional_assignment_5.sol:27]: I think the CEX has now changed from calling `f` directly to calling `g` and then `f` through the external `d.d()`.
But we need full trace report to judge the correctness of the CEX.

File: test/libsolidity/smtCheckerTests/types/array_branch_1d.sol [hunk 9]
```diff
@@ -11,4 +11,4 @@ contract C
 }
 // ----
 // Warning 2018: (47-148): Function state mutability can be restricted to pure
-// Warning 6328: (128-144): CHC: Assertion violation happens here.\nCounterexample:\n\nb = false\nc = [0, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 18, 14, 14, 21, 14, 14, 23, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14]\n\n\nTransaction trace:\nconstructor()\nf(false, [7719, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 18, 14, 14, 21, 14, 14, 23, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14])
+// Warning 6328: (128-144): CHC: Assertion violation happens here.\nCounterexample:\n\nb = false\nc = [0, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14]\n\n\nTransaction trace:\nconstructor()\nf(false, [151, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14])
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/types/array_branch_1d.sol]: Could we add something like `require(c.lenght() < 2)` to reduce the space of possible CEXs? (Just to reduce the possibility of models changing often).

**Review by blishko — COMMENTED** [review]
First attempt to discuss.

File: test/libsolidity/smtCheckerTests/external_calls/external.sol (hunk 3 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/external_calls/external.sol:20]: Happens sometimes.

File: test/libsolidity/smtCheckerTests/blockchain_state/transfer.sol (hunk 2 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/blockchain_state/transfer.sol:13]: We can see if CI complains.

File: test/libsolidity/smtCheckerTests/types/array_branch_1d.sol (hunk 9 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/types/array_branch_1d.sol]: Sure, sounds good

File: libsolidity/formal/CHC.cpp [hunk 10]
```diff
@@ -642,10 +642,18 @@ void CHC::externalFunctionCall(FunctionCall const& _funCall)
...
+	auto error = errorFlag().increaseIndex();
+	auto nondet = (*m_nondetInterfaces.at(m_currentContract))(preCallState + postCallState + vector<smtutil::Expression>{error, state().thisAddress()});
 	// TODO this could instead add the summary of the called function, where that summary
 	// basically has the nondet interface of this summary as a constraint.
 	m_context.addAssertion(nondet);
+	solAssert(m_errorDest, "");
+	connectBlocks(m_currentBlock, predicate(*m_errorDest), errorFlag().currentValue() > 0);
+	solAssert(m_currentContract && m_currentFunction, "");
+	for (auto const* base: m_currentContract->annotation().linearizedBaseContracts)
+		for (auto const* defined_function: base->definedFunctions())
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp]:
```suggestion
		for (auto const* function: base->definedFunctions())
```

Comment (blishko) [reply libsolidity/formal/CHC.cpp]: This would cause a name clash, there already is a local variable `function`. Is that OK, or should that local variable be renamed?

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: Comment added.

File: libsolidity/formal/CHC.cpp [hunk 11]
```diff
@@ -642,10 +642,20 @@ void CHC::externalFunctionCall(FunctionCall const& _funCall)
 	}
 
 	auto postCallState = vector<smtutil::Expression>{state().state()} + currentStateVariables();
-	auto nondet = (*m_nondetInterfaces.at(m_currentContract))(preCallState + postCallState);
+	auto error = errorFlag().increaseIndex();
+	auto nondet = (*m_nondetInterfaces.at(m_currentContract))(preCallState + postCallState + vector<smtutil::Expression>{error, state().thisAddress()});
 	// TODO this could instead add the summary of the called function, where that summary
 	// basically has the nondet interface of this summary as a constraint.
```
Comment (blishko) [inline libsolidity/formal/CHC.cpp:649]: Does this TODO still make sense?
It seems outdated.

Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp:649]: I think I wrote that thinking about the counterexamples containing `nondet_interface`. Currently, since we add `nondet_interface` directly, that's all we see in the counterexample graph, and can't really synthesize what the external function did, in case we have more than one being called inside the same analyzed function. If we'd do that indirectly we might get more information.
Example:

```
contract C {
    uint x;
    function inc() public { require(x < 1000); ++x; }
    function f(D d) public {
        x = 50;
        d.g();
        d.h();
        assert(x <= 60);
    }
}
```

Of course a silly example, but: the assertion fails. For that, `d.g()` and `d.h()`, combined, would have to call (direct or indirectly) `inc()` at least 10 times. Since both calls just add `nondet_interface` constraints, we don't know which called what (inc) how many times. This is not important for this case, but it might in some other cases.
If we create summaries for `summary_D_g_untrusted` and `summary_D_h_untrusted` which use `nondet_interface`, we might be able to retrieve the information of which of those called what.

Comment (blishko) [reply libsolidity/formal/CHC.cpp:649]: I think that information should be present in the CEX already. Maybe we should discuss this in a call.

File: libsolidity/formal/CHC.cpp (hunk 10 above)
Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: Please just rename it to `definedFunction` then (style)

Comment (blishko) [reply libsolidity/formal/CHC.cpp]: Ah, I was completely blind to the style difference...
Fixed.

File: libsolidity/formal/CHC.cpp [hunk 12]
```diff
@@ -642,10 +642,20 @@ void CHC::externalFunctionCall(FunctionCall const& _funCall)
...
 	m_context.addAssertion(nondet);
+	solAssert(m_errorDest, "");
+	connectBlocks(m_currentBlock, predicate(*m_errorDest), errorFlag().currentValue() > 0);
+	// To capture the possibility of a reentrant call, we record in the call graph that the  current function
+	// can call any of the external methods of the current contract.
+	solAssert(m_currentContract && m_currentFunction, "");
+	for (auto const* base: m_currentContract->annotation().linearizedBaseContracts)
+		for (auto const* definedFunction: base->definedFunctions())
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp]: We might actually have to do virtual resolution here (similar to `SMTEncoder`) otherwise it thinks it can run a function that it actually can't.

File: libsolidity/formal/PredicateSort.cpp [hunk 13]
```diff
@@ -41,7 +41,7 @@ SortPointer nondetInterfaceSort(ContractDefinition const& _contract, SymbolicSta
 	auto varSorts = stateSorts(_contract);
 	vector<SortPointer> stateSort{_state.stateSort()};
 	return make_shared<FunctionSort>(
-		stateSort + varSorts + stateSort + varSorts,
+		stateSort + varSorts + stateSort + varSorts + vector<SortPointer>{_state.errorFlagSort(), _state.thisAddressSort()},
```
Comment (leonardoalt) [inline libsolidity/formal/PredicateSort.cpp]: Can you also change the spec in `PredicateSort.h`?

File: test/libsolidity/smtCheckerTests/functions/functions_external_2.sol (hunk 7 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/functions/functions_external_2.sol:21]: Yea, I think so. Maybe allow changes only for `map[0]` and `map[1]`

File: test/libsolidity/smtCheckerTests/external_calls/external_inc.sol (hunk 5 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/external_calls/external_inc.sol:24]: We can maybe add a check that the target hasn't been solved yet in CHC itself, before trying to solve it.

File: test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol (hunk 4 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol]: We cannot know that, I guess the comment is misleading.

File: libsolidity/formal/CHC.cpp (hunk 11 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp:649]: The result of the discussion is now documented in https://github.com/ethereum/solidity/issues/9393
The TODO still makes sense.

File: test/libsolidity/smtCheckerTests/types/array_branch_1d.sol (hunk 9 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/types/array_branch_1d.sol]: Done.

File: libsolidity/formal/PredicateSort.cpp (hunk 13 above)
Comment (blishko) [reply libsolidity/formal/PredicateSort.cpp]: Updated.

File: test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol (hunk 4 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol]: Does this example makes sense then? What should we do about it?

File: test/libsolidity/smtCheckerTests/external_calls/external_inc.sol (hunk 5 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/external_calls/external_inc.sol:24]: I am not sure we can do that. It could be that the same assertion in the code is safe when transaction starts in one function, but unsafe when it starts from another, no? In such case we don't want the same version preventing the finding of the unsafe version.

Ah, but we could do that for the targets that has been proven *unsafe* already. Separate PR, probably?

File: test/libsolidity/smtCheckerTests/functions/functions_external_2.sol (hunk 7 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/functions/functions_external_2.sol:21]: Updated.

File: libsolidity/formal/PredicateSort.h [hunk 14]
```diff
@@ -37,7 +37,7 @@ namespace solidity::frontend::smt
  *
  * 2. Nondet interface
  * The nondeterminism behavior of a contract. Signature:
- * nondet_interface(blockchainState, stateVariables, blockchainState', stateVariables').
+ * nondet_interface(blockchainState, stateVariables, blockchainState', stateVariables', error, this).
```
Comment (leonardoalt) [inline libsolidity/formal/PredicateSort.h]: Why do we need `this` but not `txData`, `crypto` etc?

File: test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol (hunk 4 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol]: I think the idea here was to make `s` trusted by `C`, maybe by adding `s = new State();` to `C`'s constructor. In that case the comment makes sense.

File: test/libsolidity/smtCheckerTests/external_calls/external_inc.sol (hunk 5 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/external_calls/external_inc.sol:24]: Yea, that should work

File: libsolidity/formal/PredicateSort.h (hunk 14 above)
Comment (blishko) [reply libsolidity/formal/PredicateSort.h]: We probably *do* need this, but we don't have examples for that yet.
This is the minimal change for the known benchmarks to work correctly.
Also, for the `transaction data` we need to be careful, since the external call creates a new transaction, right?

Comment (blishko) [reply libsolidity/formal/PredicateSort.h]: I have added `crypto` and `abi` to the `nondet_interace` and added a test to check `crypto` across external calls.
As discussed, `txData` should not be part of `nondet_interface`, similarly to the `interface`.

File: libsolidity/formal/PredicateInstance.cpp [hunk 15]
```diff
@@ -36,14 +36,23 @@ smtutil::Expression interfacePre(Predicate const& _pred, ContractDefinition cons
...
 	return _pred(stateExprs + currentStateVariables(_contract, _context));
 }
 
-smtutil::Expression nondetInterface(Predicate const& _pred, ContractDefinition const& _contract, EncodingContext& _context, unsigned _preIdx, unsigned _postIdx)
-{
+smtutil::Expression nondetInterface(
+	Predicate const& _pred,
+	ContractDefinition const& _contract,
+	EncodingContext& _context,
+	smtutil::Expression const& _error,
```
Comment (leonardoalt) [inline libsolidity/formal/PredicateInstance.cpp]: Why is `error` a function parameter? You can get it from `state.error()`

File: test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol [hunk 16]
```diff
@@ -0,0 +1,26 @@
...
+
+	bytes32 kec;
+
+	constructor(bytes memory _data) {
+		data = _data;
+
+		kec = keccak256(data);
+	}
+
+	function f() public view {
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol]: Can you add a new test (or change this) so that `f` takes a parameter `bytes memory _data` and add a failing `assert(_kec == keccak256(_data))`?

File: libsolidity/formal/PredicateInstance.cpp (hunk 15 above)
Comment (blishko) [reply libsolidity/formal/PredicateInstance.cpp]: I wanted an option to pass something else.
Basically, I believe we need to start the `nondet_interface`s with `error == 0`.
So now, I am adding a unit clauses like `(nondet_interface_C_54_0  0  this_0 abi_0 crypto_0 state_0  state_0)`.
For that I need this additional parameter.
I guess this could be changed to something like
```
(=>
  error_0 == 0
  (nondet_interface_C_54_0  error_0  this_0 abi_0 crypto_0 state_0  state_0)
)
```
and than I can get rid of the extra parameter in `PredicateInstance::nondetInterface`.
Would that be preferable?

Comment (leonardoalt) [reply libsolidity/formal/PredicateInstance.cpp]: Right. I personally would prefer that, but don't have a strong opinion. Also fine if you prefer the current way.

Comment (blishko) [reply libsolidity/formal/PredicateInstance.cpp]: I'll check how big a change this would be.

File: test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol (hunk 16 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol]: Failing assert added to this test.

File: libsolidity/formal/PredicateInstance.cpp (hunk 15 above)
Comment (blishko) [reply libsolidity/formal/PredicateInstance.cpp]: I have updated the code so that the extra parameter is not needed anymore and the encoding now looks like the latter example above.

File: libsolidity/formal/CHC.cpp [hunk 17]
```diff
@@ -907,18 +917,20 @@ void CHC::defineInterfacesAndSummaries(SourceUnit const& _source)
...
+					vector<smtutil::Expression> args{errorPost, state().thisAddress(), state().abi(), state().crypto(), state().tx(), state().state(1)};
 					args += state1 +
 						applyMap(function->parameters(), [this](auto _var) { return valueAtIndex(*_var, 0); }) +
 						vector<smtutil::Expression>{state().state(2)} +
 						state2 +
 						applyMap(function->parameters(), [this](auto _var) { return valueAtIndex(*_var, 1); }) +
 						applyMap(function->returnParameters(), [this](auto _var) { return valueAtIndex(*_var, 1); });
 
-					connectBlocks(nondetPre, nondetPost, (*m_summaries.at(contract).at(function))(args));
+					connectBlocks(nondetPre, nondetPost, errorPre == 0 && (*m_summaries.at(contract).at(function))(args));
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:933]: To confirm, this rule then looks like
`nondet_interface(0, abi, crypto, stateVars, stateVars') && f_summary(error, abi, crypto, stateVars', stateVars'') => nondet_interface(error, abi, crypto, stateVars, stateVars''`
correct?

File: test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol [hunk 18]
```diff
@@ -34,4 +34,4 @@ contract C {
 	}
 }
 // ----
-// Warning 6328: (528-565): CHC: Assertion violation happens here.\nCounterexample:\nowner = 1, y = 0, z = 0, s = 0\n\n\n\nTransaction trace:\nconstructor()\nState: owner = 1, y = 0, z = 0, s = 0\ninv()
+// Warning 6328: (528-565): CHC: Assertion violation happens here.\nCounterexample:\nowner = (- 1), y = 0, z = 0, s = 0\n\n\n\nTransaction trace:\nconstructor()\nState: owner = (- 1), y = 0, z = 0, s = 0\nf()
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/external_calls/external_hash_known_code_state.sol:37]: This is weird. Looks like tx vars are not being type constrained

File: test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol [hunk 19]
```diff
@@ -0,0 +1,33 @@
...
+
+	function ext(D d) public {
+		d.d();
+	}
+}
+// ----
+// Warning 1218: (335-366): CHC: Error trying to invoke SMT solver.
+// Warning 6328: (335-366): CHC: Assertion violation might happen here.
+// Warning 1218: (335-366): CHC: Error trying to invoke SMT solver.
+// Warning 6328: (335-366): CHC: Assertion violation might happen here.
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol:32]: Looks like CHC is running the assertion twice?

File: libsolidity/formal/CHC.cpp (hunk 17 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp:933]: To be precise, it looks like `nondet_interface(error, abi, crypto, stateVars, stateVars') && error == 0 && f_summary(error', abi, crypto, stateVars', stateVars'') => nondet_interface(error', abi, crypto, stateVars, stateVars''`

Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp:933]: Ok, yes. I wanted to be sure that the function error was the one being propagated. Looks good.

File: test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol (hunk 19 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol:32]: @blishko Is this because the assertion can be violated both via `ext` and `check`?

Comment (blishko) [reply test/libsolidity/smtCheckerTests/external_calls/external_reentrancy_crypto.sol:32]: Yes, I believe that's the reason.

**Review by leonardoalt — APPROVED** [review]
