### PR TITLE
Yul interpreter: Smaller execution timeout for tests and additional testcases

### LINKED ISSUE #7943: yulInterpreter crashes on infinite recursion
Found by ossfuzz (13647 and 13811)

```
{
    function f() {
      f()
    }
    f()
}
```

The problem manifests in `Interpreter::openScope` in `test/tools/yulInterpreter/Interpreter.h`.

### PR DESCRIPTION
**Pull request by bshastry**
Fixes #7943 

Adds a couple of tests for checking how interpreter behaves when interpreter steps are bounded and input program contains infinite recursion.

### CODE REVIEW

**Comment by axic** [comment]
"Solves" #7943?

Actually is there any other change to take from #9483 ?

**Comment by bshastry** [comment]
Thanks for making the connection to #7943 @axic ! Indeed, this fixes that issue.

> Actually is there any other change to take from #9483 ?

Turns out there was something I hadn't factored in! Ready for review again

File: test/libyul/YulInterpreterTest.cpp [hunk 1]
```diff
@@ -87,8 +87,8 @@ bool YulInterpreterTest::parse(ostream& _stream, string const& _linePrefix, bool
 string YulInterpreterTest::interpret()
 {
 	InterpreterState state;
-	state.maxTraceSize = 10000;
-	state.maxSteps = 10000;
+	state.maxTraceSize = 10;
+	state.maxSteps = 150;
```
Comment (axic) [inline test/libyul/YulInterpreterTest.cpp]: Can we increase these?

I'd suggest something like `maxTraceSize = 32` and `maxSteps = 512`.

Comment (bshastry) [reply test/libyul/YulInterpreterTest.cpp]: Done

Comment (axic) [reply test/libyul/YulInterpreterTest.cpp]: Did you push?

Comment (bshastry) [reply test/libyul/YulInterpreterTest.cpp]: Ah sorry, just pushed!

**Review by axic — DISMISSED** [review]

**Comment by bshastry** [comment]
Fixed the failing test.

File: test/libyul/yulInterpreterTests/infinite_recursion.yul [hunk 2]
```diff
@@ -0,0 +1,11 @@
+{
+  function f() {
+    f()
+  }
+  f()
```
Comment (hrkrshnn) [inline test/libyul/yulInterpreterTests/infinite_recursion.yul:5]: What about including a positive test?

```
{
    function f(x) {
        if lt(x, 512) {
            f(add(x, 1))
        }
    }
    f(0)
}
```

Comment (bshastry) [reply test/libyul/yulInterpreterTests/infinite_recursion.yul:5]: Added a positive test but I'm afraid it didn't turn out exactly like above mainly because of how we count an execution "step" (yul statement).

More details here: https://github.com/ethereum/solidity/blob/3cd0b252206550f8aa1158eb3e78665ff77c5b54/test/tools/yulInterpreter/Interpreter.cpp#L193-L195

**Review by hrkrshnn — APPROVED** [review]
