### PR TITLE
Fix crash when declaring the same var twice in the same scope

### LINKED ISSUE #4414: Internal compiler error on multiple variable declaration.
The following code:
```
pragma solidity >0.0.0;
contract C {
    function f() {
        int a;
        int a;
    }
}
```

With 0.4.24:

```
test.sol:5:3: Error: Identifier already declared.
		int a;
		^---^
test.sol:4:3: The previous declaration is here:
		int a;
		^---^
```
With current develop:

```
Internal compiler error during compilation:
/home/daniel/dev/solidity/libsolidity/analysis/DeclarationContainer.cpp(93): Throw in function void dev::solidity::DeclarationContainer::activateVariable(const ASTString&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Tried to activate a non-inactive variable or multiple inactive variables with the same name.
[dev::tag_comment*] = Tried to activate a non-inactive variable or multiple inactive variables with the same name.

```

A bit troubling that this was not caught by any test (there's tests for state variables, but not for locals).

I suspect this might be connected to scoping @leonardoalt? Do you want to look into it? Otherwise I can take it.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #4414 

In #4414 an assertion fails because there is an assumption that the declarations are ok. The error is reached before that, but since it's not fatal the component goes on. My suggestion is to turn the error into fatal.

### CODE REVIEW

**Comment by ekpyron** [comment]
Arguably, it might be nicer to remove the assertion on the other end (in DeclarationContainer.cpp) and instead try to deal with these cases gracefully, since we want to reduce the amount of fatal errors... but maybe it's easier here to just make it fatal.

In any case, there should still be test cases for this.

**Comment by leonardoalt** [comment]
I don't think we should remove the assertion. The code where the assertion is shouldn't be reached in the first place if the variables are not properly declared. I also don't think we should simply check it again at that point, that would just duplicate code.
But if fatal errors are undesired I'll think of something else, it should be possible ;)

**Comment by ekpyron** [comment]
Well, I think the general policy is supposed to be as few fatal errors as possible and where ever it's possible to continue processing from the most reasonable "sane" state, so that later errors are not swallowed... but not at all cost, of course - in this case I'm not sure, so at least I would say: if you see a straightforward way for making it non-fatal, then do it, otherwise just leave it fatal - in any case: tests ;-).

**Comment by leonardoalt** [comment]
Removed the fatal error and added syntax tests.

**Review by ekpyron — DISMISSED** [review]
Yes, this looks much better now!
And I guess we don't necessarily need a Changelog entry for this one, so to me it looks fine!

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 1]
```diff
@@ -156,7 +156,8 @@ bool NameAndTypeResolver::updateDeclaration(Declaration const& _declaration)
 void NameAndTypeResolver::activateVariable(string const& _name)
 {
 	solAssert(m_currentScope, "");
-	m_currentScope->activateVariable(_name);
+	if (m_currentScope->isInvisible(_name))
```
Comment (chriseth) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: Please add a comment.

**Comment by leonardoalt** [comment]
Added review suggestion comment and rebased.

**Review by ekpyron — APPROVED** [review]
