### PR TITLE
[SMTChecker] Support try-catch statements

### LINKED ISSUE #10110: [SMTChecker] Support try/catch properly

### LINKED ISSUE #10600: [SMTChecker] ICE in void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function g(bool b) public pure returns (uint, uint) {
    }
    function f(bool b) public returns (uint x, uint y, bytes memory txt) {
	if (0==1)
            try this.g(b) returns (uint a, uint b) {} catch (bytes memory s) {
		txt = s;
            }
    }
}
```

produces:

```
Internal compiler error during compilation:
/solidity/libsolidity/formal/SMTEncoder.cpp(2266): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.12.14+commit.e21be30d.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### LINKED ISSUE #10666: [SMTChecker] ICE in function smtutil::Expression solidity::frontend::smt::EncodingContext::newValue(const frontend::VariableDeclaration &) (different contract structure)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function f() public returns (uint, uint) {
	while(1==1)
	    try this.f() returns (uint a, uint b) {
		    b = 2;
		} catch {
	    }
    }
}
```

produces:

```
Internal compiler error during compilation:
/solidity/libsolidity/formal/EncodingContext.cpp(108): Throw in function smtutil::Expression solidity::frontend::smt::EncodingContext::newValue(const frontend::VariableDeclaration &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.1-develop.2020.12.20+commit.67712d50.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by blishko**
This PR adds full support for analyzing try-catch statement in the SMTChecker.

Fixes #10600.
Fixes #10666.

Current state:
- [x] CHC engine
	- [x] External calls
	- [x] Contract creation 
- [x] BMC engine

Resolves #10110

### CODE REVIEW

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -541,6 +541,79 @@ void CHC::endVisit(Return const& _return)
...
+	// fine-grained control over how the external call is visited
+	// cannot use "_tryStatement.externalCall().accept(*this);"
+	auto const* call = dynamic_cast<FunctionCall const*>(&_tryStatement.externalCall());
+	solAssert(call, "");
+	call->expression().accept(*this);
+	ASTNode::listAccept(call->arguments(), *this);
+	connectBlocks(m_currentBlock, predicate(*tryAfterCallFailBlock));
+	endVisit(*call);
+	if (_tryStatement.successClause()->parameters())
+	{
```
Comment (blishko) [inline libsolidity/formal/CHC.cpp]: This whole block is very similar to what `SMTEncoder::createReturnedExpressions` is doing, but there are small differences.
The whole purpose is to connect the values returned from the external call with the return parameters declared in the `Try` statement.

It would be nice to find some way to do this more elegantly.

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -2688,7 +2688,28 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
 
 vector<VariableDeclaration const*> SMTEncoder::localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _contract)
 {
-	return _function.localVariables() + modifiersVariables(_function, _contract);
+	return _function.localVariables() + tryCatchVariables(_function) + modifiersVariables(_function, _contract);
+}
+
+vector<VariableDeclaration const*> SMTEncoder::tryCatchVariables(FunctionDefinition const& _function)
```
Comment (blishko) [inline libsolidity/formal/SMTEncoder.cpp:2700]: Parameters from the try-catch clauses are currently not added to the local variables of `FunctionDefinition`s, since they are not `VariableDeclarationStatement`. See `DeclarationRegistrationHelper::endVisit(VariableDeclarationStatement& _variableDeclarationStatement)`.

Maybe this could be changed?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:2700]: Yea we can suggest that

File: libsolidity/formal/SMTEncoder.cpp [hunk 3]
```diff
@@ -2688,7 +2688,28 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
...
+{
+	struct TryCatchVarsVisitor : public ASTConstVisitor{
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]:
```suggestion
	struct TryCatchVarsVisitor : public ASTConstVisitor
	{
```

File: libsolidity/formal/SMTEncoder.cpp [hunk 4]
```diff
@@ -2688,7 +2688,28 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
...
+		vector<VariableDeclaration const*> m_vars;
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]: Please move this to after the function.

File: libsolidity/formal/SMTEncoder.cpp [hunk 5]
```diff
@@ -2688,7 +2688,28 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
...
+
+		bool visit(TryCatchClause const& _catchClause) override
+		{
+			if (_catchClause.parameters())
+			{
+				auto const& params = _catchClause.parameters()->parameters();
+				for (auto param: params)
+					m_vars.push_back(param.get());
+			}
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2711]: Are the return parameters also included here?

File: libsolidity/formal/SMTEncoder.cpp (hunk 4 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Also since it's not public please rename it to `vars`.

File: libsolidity/formal/CHC.cpp [hunk 6]
```diff
@@ -541,6 +541,79 @@ void CHC::endVisit(Return const& _return)
...
+	auto tryHeaderBlock = createBlock(&_tryStatement, PredicateType::FunctionBlock, "try_header_");
+	auto tryAfterCallSuccessBlock = createBlock(&_tryStatement, PredicateType::FunctionBlock, "try_after_call_success_");
+	auto tryAfterCallFailBlock = createBlock(&_tryStatement, PredicateType::FunctionBlock, "try_after_call_fail_");
+	auto afterTryBlock = createBlock(&functionBody, PredicateType::FunctionBlock);
+
+	connectBlocks(m_currentBlock, predicate(*tryHeaderBlock));
+	setCurrentBlock(*tryHeaderBlock);
+	// fine-grained control over how the external call is visited
+	// cannot use "_tryStatement.externalCall().accept(*this);"
+	auto const* call = dynamic_cast<FunctionCall const*>(&_tryStatement.externalCall());
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp]: Isn't this the same as `externalCall` declared at the beginning?

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: Yea, this block is pretty much the same as `createReturnedExpressions` without the 3 first lines of that function. I guess you could extract a function with the block below which can also be used by `createReturnedExpressions`.

File: libsolidity/formal/CHC.cpp [hunk 7]
```diff
@@ -541,6 +541,79 @@ void CHC::endVisit(Return const& _return)
...
+		connectBlocks(m_currentBlock, predicate(*clauseBlocks[i]));
+
+	for (size_t i = 0; i < clauses.size(); ++i)
+	{
+		setCurrentBlock(*clauseBlocks[i]);
+		clauses[i]->accept(*this);
+		connectBlocks(m_currentBlock, predicate(*afterTryBlock));
+	}
+	setCurrentBlock(*afterTryBlock);
+
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:582]: Nice!

File: test/libsolidity/smtCheckerTests/try_catch/try_1.sol [hunk 8]
```diff
@@ -0,0 +1,22 @@
...
+
+	function f() public {
+		x = 0;
+		bool success = false;
+		try this.g() {
+			success = true;
+		} catch (bytes memory s) {
+			assert(x == 0); // should hold
+		}
+		assert(success); // fails for now, since external call is over-approximated (both success and fail are considered possible) for now even for known code
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/try_catch/try_1.sol:17]: If we use `CHC::externalFunctionCall` shouldn't it call the trustedExternalCall code?

File: test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values.sol [hunk 9]
```diff
@@ -0,0 +1,27 @@
...
+
+contract C {
+
+	int x;
+	D d;
+
+	function f() public {
+		x = 0;
+		try d.d() returns (uint x, bool c) {
+			assert(x == 0); // should fail, x is the local variable shadowing the state variable
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values.sol:15]: Oh wow, didn't know that this shadowing was allowed

File: test/libsolidity/smtCheckerTests/try_catch/try_4.sol [hunk 10]
```diff
@@ -0,0 +1,28 @@
...
+	D d;
+
+	function set(int n) public {
+		x = n;
+	}
+
+	function f() public {
+		x = 0;
+		try d.d() {
+			assert(x == 0); // should fail, x can be anything here
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/try_catch/try_4.sol:19]: Can you also add a test similar to this, where
- function `set` has a `require(n < 100);` before the assignment
- the assert here is `assert(x < 100);` which should hold

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: I wanted to do that, but then I notice a small problem, in `createReturnedExpressions` the last line is `defineExpr(_funCall, currentValue(*returnParams.front()));` which assigns the returned values to a *new* version of the expression. However, what I need is the opposite, I need to assign the *current* version of that expression to a variable that I am providing.

I am now thinking more in terms of an assignment, if I can re-use that code somehow.
Because basically `try d.d() returns (uint x, bool b)` is doing the same thing as `(uint x, bool b) = d.d()` (in the success case).

File: libsolidity/formal/SMTEncoder.cpp (hunk 4 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: Actually, I made it public (using `struct`, not `class`), since I did not saw the point of writing a getter, as this class is local to the method and thus not visible anywhere else.

File: libsolidity/formal/SMTEncoder.cpp (hunk 5 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2711]: If by return parameters you mean the `x` and `b` in `try d.d() returns (uint x, bool b) ...`, then yes. They are stored as the parameters of the success clause in the AST representation.

File: libsolidity/formal/CHC.cpp (hunk 6 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: Yes, it is, I completely missed that :)

File: test/libsolidity/smtCheckerTests/try_catch/try_1.sol (hunk 8 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/try_catch/try_1.sol:17]: It does. What I mean by this comment that when analyzing the control flow, we still add the edges to all catch blocks, although maybe some of the edges cannot be taken?

This is related to a question I had. Can an external call like this one, or an external call to public getter fail? My intuition is that it still can fail, no?

File: test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values.sol (hunk 9 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values.sol:15]: The compiler warns about it, but it is allowed.

File: libsolidity/formal/SMTEncoder.cpp (hunk 5 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:2711]: Ok!

File: test/libsolidity/smtCheckerTests/try_catch/try_1.sol (hunk 8 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/try_catch/try_1.sol:17]: Right, I think it can. For example for an array getter, if you give an index out of bounds

File: test/libsolidity/smtCheckerTests/try_catch/try_new.sol [hunk 11]
```diff
@@ -0,0 +1,34 @@
...
+            txt = "success";
+        } catch Error(string memory s) {
+            txt = s;
+        }
+    }
+}
+// ----
+// Warning 4588: (264-278): Assertion checker does not yet implement this type of function call.
+// Warning 4588: (525-540): Assertion checker does not yet implement this type of function call.
+// Warning 4588: (264-278): Assertion checker does not yet implement this type of function call.
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/try_catch/try_new.sol:33]: This warning seems to be duplicated as it comes from both CHC and BMC engine.

File: test/libsolidity/smtCheckerTests/try_catch/try_inside_if.sol [hunk 12]
```diff
@@ -0,0 +1,14 @@
...
+    if (0==1)
+      try this.g(b) {}
+      catch (bytes memory s) {
+        txt = s;
+      }
+  }
+}
+
+// ----
+// Warning 6838: (141-145): BMC: Condition is always false.
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/try_catch/try_inside_if.sol:14]: This is the simplified example from #10600 (was crashing before).

File: test/libsolidity/smtCheckerTests/try_catch/try_new.sol (hunk 11 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/try_catch/try_new.sol:33]: Yea that's normal since we added the options to use each engine separately

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: @blishko any ideas regarding this block? I still think we should move it. We can also have a call about it.

File: libsolidity/formal/SMTEncoder.cpp [hunk 13]
```diff
@@ -2688,7 +2674,29 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
...
+
+			return false;
+		}
+
+		vector<VariableDeclaration const*> m_vars;
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]: I still think this should be called `vars` :p
We usually add `m_` for class private members only. I know you said this ends up being private, but the way it's accessed is still public (`tryCatchVarsVisitor.m_vars`).

File: libsolidity/formal/BMC.cpp [hunk 14]
```diff
@@ -345,6 +345,37 @@ bool BMC::visit(ForStatement const& _node)
...
+	{
+		clausesVisitResults.push_back(visitBranch(clauses[i].get(), clauseId == i));
+		touchedVars += touchedVariables(*clauses[i]);
+	}
+
+	// merge the information from all clauses
+	smtutil::Expression pathCondition = clausesVisitResults.front().second;
+	for (size_t i = 1; i < clauses.size(); ++i)
+	{
+		mergeVariables(touchedVars, clauseId == (i - 1), clausesVisitResults[i-1].first, clausesVisitResults[i].first);
```
Comment (leonardoalt) [inline libsolidity/formal/BMC.cpp]:
```suggestion
		mergeVariables(touchedVars, clauseId == (i - 1), clausesVisitResults[i - 1].first, clausesVisitResults[i].first);
```

File: test/libsolidity/smtCheckerTests/try_catch/try_4.sol (hunk 10 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/try_catch/try_4.sol:19]: Added.

File: libsolidity/formal/BMC.cpp (hunk 14 above)
Comment (blishko) [reply libsolidity/formal/BMC.cpp]: Fixed.

File: libsolidity/formal/SMTEncoder.cpp (hunk 13 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: Fixed.

File: libsolidity/formal/BMC.cpp [hunk 15]
```diff
@@ -345,6 +345,43 @@ bool BMC::visit(ForStatement const& _node)
...
+bool BMC::visit(TryStatement const& _tryStatement)
+{
+	FunctionCall const* externalCall = dynamic_cast<FunctionCall const*>(&_tryStatement.externalCall());
+	solAssert(externalCall && externalCall->annotation().tryCall, "");
+
+	externalCall->accept(*this);
+	auto callExpr = expr(*externalCall);
+	if (_tryStatement.successClause()->parameters())
+		tryCatchAssignment(
+			_tryStatement.successClause()->parameters()->parameters(), *m_context.expression(*externalCall));
```
Comment (leonardoalt) [inline libsolidity/formal/BMC.cpp]:
```suggestion
			_tryStatement.successClause()->parameters()->parameters(), *m_context.expression(*externalCall)
		);
```

File: libsolidity/formal/CHC.cpp [hunk 16]
```diff
@@ -541,6 +541,57 @@ void CHC::endVisit(Return const& _return)
...
+	// cannot use "_tryStatement.externalCall().accept(*this);" since we need to insert the "connectBlocks"
+	// visit(*externalCall); currently there is nothing to do here, so it's commented out
+	externalCall->expression().accept(*this);
+	ASTNode::listAccept(externalCall->arguments(), *this);
+	connectBlocks(m_currentBlock, predicate(*tryAfterCallFailBlock));
+	endVisit(*externalCall);
+
+	if (_tryStatement.successClause()->parameters())
+		tryCatchAssignment(
+			_tryStatement.successClause()->parameters()->parameters(), *m_context.expression(*externalCall));
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp]:
```suggestion
			_tryStatement.successClause()->parameters()->parameters(), *m_context.expression(*externalCall)
		);
```

File: test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values_with_tuple.sol [hunk 17]
```diff
@@ -0,0 +1,26 @@
...
+	}
+
+	function f() public view {
+		bool success = false;
+		try this.g() returns (bool b, S memory s) {
+			success = true;
+			assert(b && s.x == 42 && s.y == -1);
+		} catch {
+		}
+		assert(success); // fails, not guaranteed that there will be no error
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values_with_tuple.sol:22]: Can you also add an assertion over `s` that holds?

File: libsolidity/formal/CHC.cpp [hunk 18]
```diff
@@ -541,6 +541,57 @@ void CHC::endVisit(Return const& _return)
...
+	auto tryAfterCallFailBlock = createBlock(&_tryStatement, PredicateType::FunctionBlock, "try_after_call_fail_");
+	auto afterTryBlock = createBlock(&m_currentFunction->body(), PredicateType::FunctionBlock);
+
+	connectBlocks(m_currentBlock, predicate(*tryHeaderBlock));
+	setCurrentBlock(*tryHeaderBlock);
+	// fine-grained control over how the external call is visited
+	// cannot use "_tryStatement.externalCall().accept(*this);" since we need to insert the "connectBlocks"
+	// visit(*externalCall); currently there is nothing to do here, so it's commented out
+	externalCall->expression().accept(*this);
+	ASTNode::listAccept(externalCall->arguments(), *this);
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp]: As @ekpyron suggested, the code below this comment could be simplified by removing blocks `tryAfterCallSuccessBlock` and `tryAfterCallFailBlock`, and linking directly `m_currentBlock` to each clauseBlocks[i]`, where
```
endVisit(*externalCall);
tryCatchAssignment
```
should be added for `i == 0`.

File: test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values_with_tuple.sol (hunk 17 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/try_catch/try_multiple_returned_values_with_tuple.sol:22]: There already is an assertion on `s` that holds in the success clause and `s` is not visible outside that block, so I am not sure what you mean.

File: libsolidity/formal/BMC.cpp (hunk 15 above)
Comment (blishko) [reply libsolidity/formal/BMC.cpp]: Fixed.

File: libsolidity/formal/CHC.cpp (hunk 16 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: Fixed.

File: libsolidity/formal/CHC.cpp (hunk 18 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: I agree that they are redundant. I have removed them and updated the code and the comments.

File: libsolidity/formal/CHC.cpp [hunk 19]
```diff
@@ -541,6 +541,48 @@ void CHC::endVisit(Return const& _return)
...
+	// Branch directly to all catch clauses, since in these cases, any effects of the external call are reverted.
+	for (size_t i = 1; i < clauseBlocks.size(); ++i)
+		connectBlocks(m_currentBlock, predicate(*clauseBlocks[i]));
+	// Only now visit the actual call to record its effects and connect to the success clause.
+	endVisit(*externalCall);
+	if (_tryStatement.successClause()->parameters())
+		tryCatchAssignment(
+			_tryStatement.successClause()->parameters()->parameters(), *m_context.expression(*externalCall)
+		);
+	connectBlocks(m_currentBlock, predicate(*clauseBlocks[0]));
```
Comment (ekpyron) [inline libsolidity/formal/CHC.cpp:573]: Just as a note: We could probably still simplify this further by just directly using
``clauses[0]->accept(*this); connectBlocks(m_currentBlock, predicate(*afterTryBlock));`` here and starting the loop below at ``1`` instead (respectively in the end generating one clause block less)...

But maybe it's simpler and the predicates are easier to read later, if we keep it like this, so fine with me either way.

**Review by ekpyron — COMMENTED** [review]
I only looked at ``CHC``, since @leonardoalt said he has BMC covered already - and CHC looks good, only one optional comment, but also fine as it is!

File: libsolidity/formal/CHC.cpp (hunk 19 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp:573]: I see, I agree that it should be possible.

The disadvantage is that we lose symmetry: catch clauses would have a dedicated predicate, but the success clause would not have one. And the success case might be harder to follow in the encoding.

The advantage is that we do less work and there is one less predicate in the encoding, which might be better for the solver.
On the other hand, having the predicate might make extracting and interpreting a counterexample easier.

I am currently slightly in favour of the current version, with the explicit success block.

**Review by leonardoalt — APPROVED** [review]
