### PR TITLE
[SMTChecker] Fix internal error on bytes.push on the LHS of an assignment

### LINKED ISSUE #10525: [SMTChecker] ICE in void solidity::frontend::SMTEncoder::assignment(const solidity::frontend::Expression &, const smtutil::Expression &, const solidity::frontend::TypePointer &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
	bytes array;
	function g(uint x) public {
		for (uint i = 0; i < x; ++i)
			array.push() = bytes1(uint8(i));
	}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1842): Throw in function void solidity::frontend::SMTEncoder::assignment(const solidity::frontend::Expression &, const smtutil::Expression &, const solidity::frontend::TypePointer &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer,  a bit indirectly:  I took every test in my corpus I use to start fuzzing, and add the SMT checker pragma to any that lacked it, then ran triage and minimized the tests (so they aren't exactly the corpus tests + SMT checker pragma).

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by blishko**
Fixes #10525.

Extends #10120 to handle also `bytes.push()` properly on the LHS of an assignment, as `bytes` are special kind of `arrays`.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -2499,7 +2500,7 @@ MemberAccess const* SMTEncoder::isEmptyPush(Expression const& _expr) const
 	)
 	{
 		auto const& funType = dynamic_cast<FunctionType const&>(*funCall->expression().annotation().type);
-		if (funType.kind() == FunctionType::Kind::ArrayPush)
+		if (funType.kind() == FunctionType::Kind::ArrayPush || funType.kind() == FunctionType::Kind::ByteArrayPush)
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2505]: I think we also need to add this in `arrayPushPopAssign`

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2505]: I have checked it and I don't think that can happen. If I have an expression `e.push()` then `e` cannot be a `ByteArrayPush` because that returns `byte` so another `push` on that is not possible.
`ByteArrayPush` can only be the *innermost* push in a sequence of nested pushes.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:2505]: Ok. Can you then add an assert and a comment related to that at the location I suggested?

**Review by leonardoalt — DISMISSED** [review]

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -1572,6 +1573,8 @@ void SMTEncoder::arrayPushPopAssign(Expression const& _expr, smtutil::Expression
 	else if (auto const* funCall = dynamic_cast<FunctionCall const*>(expr))
 	{
 		FunctionType const& funType = dynamic_cast<FunctionType const&>(*funCall->expression().annotation().type);
+		// Push cannot occur on an expression that is itself a ByteArrayPush, i.e., bytes.push().push() is not possible.
```
Comment (bshastry) [inline libsolidity/formal/SMTEncoder.cpp:1576]: How does the assertion guarantee that the expression here is a bytesarraypush?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1576]: Not sure what you mean. It shouldn't be that

**Comment by blishko** [comment]
Added the required test case, for double push on `bytes[]`.

**Review by leonardoalt — APPROVED** [review]
