### PR TITLE
Raise error when using unimplemented internal library functions.

### LINKED ISSUE #1769: Problem with internal passing of structs
I managed to create minimum reproducible build of this error involving internal passing of structs. 

Note the below code:

```
pragma solidity >=0.0.0;

library Model {

    struct DataMap {
        mapping(bytes32 => DataElement) rows;
        bytes32[] keys;
        uint size;
    }

    struct DataElement {
        bool exists;
        uint keyIdx;
        Data data;
    }

    struct Data {
        bytes32 id;
        uint uintValue;
        bytes32 bytes32Value;
        address addressValue;
        bool boolValue;
    }
}

library Api {
   function get(Model.DataMap storage _map, bytes32 _id) internal returns (Model.Data);
}

contract Process {

    using Api for Model.DataMap;

    Model.DataMap processData;

    function getDataAsAddress(bytes32 _id) constant returns (address) {
        Model.Data memory data = processData.get(_id);
        return data.addressValue;
    }

}
```

This does not compile currently although it probably should based on our current documentation (unless I'm missing something). This produces the following error:

```
Internal compiler error during compilation:
/Users/vor0220/solidity/libsolidity/codegen/ContractCompiler.cpp(843): Throw in function void dev::solidity::ContractCompiler::appendModifierOrFunctionCode()
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] =
```

The error can be turned off at the cost of not being able to publicly retrieve the variable in getDataAsAddress by making the return an internal return. How might one go about alleviating this? Either way we need to come up with a better error if indeed this is intended functionality.

### PR DESCRIPTION
**Pull request by axic**
Fixes #1769.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1410,6 +1410,21 @@ bool TypeChecker::visit(FunctionCall const& _functionCall)
...
+		functionType->kind() == FunctionType::Kind::Internal &&
+		functionType->hasDeclaration() &&
+		dynamic_cast<FunctionDefinition const*>(&functionType->declaration())
+	)
+	{
+		FunctionDefinition const* function = dynamic_cast<FunctionDefinition const*>(&functionType->declaration());
+		bool isLibraryFunction =
+			dynamic_cast<ContractDefinition const*>(function->scope()) &&
+			dynamic_cast<ContractDefinition const*>(function->scope())->isLibrary();
+		if (!function->isImplemented() && isLibraryFunction)
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Do we really need the check for a library function? Unimplemented functions that are called internally should always be an error.

**Comment by axic** [comment]
This also catches:
```
library L {
  function f() internal;
  fucntion g() { f(); }
}
```

but that is fine since libraries can inherit other libraries so no way to implement it.

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/analysis/TypeChecker.cpp]: I think it should fine since it can be implemented in a derived class.

For `private` functions it should reject them though.

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: Ah, now I see the test case. Perhaps we  should rather check whether the current contract is implemented instead of whether the called function is a library function?

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: What about:
```
library L { function f() internal; }
contract c {
function g() {
  var x =L.f;
  x();
}
} 
```

Comment (axic) [reply libsolidity/analysis/TypeChecker.cpp]: Another question is, the below currently allowed and compiles, but not sure we should allow it:
```
library L {
  function f() internal;
  function g() {}
}
```

And so does (as long as noone of the functions are referenced by a contract):
```
library L {
  function f() internal;
  function g() { f(); }
}
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -1410,6 +1410,21 @@ bool TypeChecker::visit(FunctionCall const& _functionCall)
...
+			m_errorReporter.typeError(_functionCall.location(), "Inlined library function is lacking implementation.");
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Not sure if we should use the word "inlined" here. Isn't that an implementation detail of internal library functions?

**Comment by axic** [comment]
Will disable unimplemented internal library functions in `FunctionDefinition`, but also need to come up with a more comprehensive list of tests for that.

**Comment by axic** [comment]
@chriseth this should be ready

File: test/libsolidity/SolidityNameAndTypeResolution.cpp [hunk 3]
```diff
@@ -6536,6 +6536,28 @@ BOOST_AUTO_TEST_CASE(constructor_without_implementation)
 	CHECK_ERROR(text, TypeError, "Constructor must be implemented if declared.");
 }
 
+BOOST_AUTO_TEST_CASE(library_function_without_implementation)
+{
+	char const* text = R"(
+		library L {
+			function f();
```
Comment (axic) [inline test/libsolidity/SolidityNameAndTypeResolution.cpp:6543]: I can see a point of keeping this, since at link time an address can be supplied which has it implemented. Also disallowing this would be a breaking change.

**Review by chriseth — APPROVED** [review]
