### PR TITLE
[SMTChecker] Support fixed bytes index access

### LINKED ISSUE #7663: [SMTChecker] Support FixedBytes IndexAccess
Currently expressions of type `FixedBytes` are encoded as SMT integers, but in Solidity their indices can be accessed individually, returning a `byte`.
One way to support it might be to create an SMT prelude that fills an array of size 32 with the powers of 2.
Then access to index `i` of FixedBytes `b` can be encoded as `(b / 2^(len(b) - i) % 256`.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/7663

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -970,13 +970,25 @@ void SMTEncoder::endVisit(IndexAccess const& _indexAccess)
...
-		);
+		smtutil::Expression base = expr(_indexAccess.baseExpression());
+
+		if (type->numBytes() == 1)
+			defineExpr(_indexAccess, base);
+		else
+		{
+			auto [bvSize, isSigned] = smt::typeBvSizeAndSignedness(_indexAccess.baseExpression().annotation().type);
+			solAssert(!isSigned, "");
+
```
Comment (axic) [inline libsolidity/formal/SMTEncoder.cpp:985]: Maybe add another assert for `bvSize > 0`.

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -970,13 +970,25 @@ void SMTEncoder::endVisit(IndexAccess const& _indexAccess)
...
+			smtutil::Expression idx = expr(*_indexAccess.indexExpression());
+
+			auto bvBase = smtutil::Expression::int2bv(base, bvSize);
+			auto bvShl = smtutil::Expression::int2bv(idx * 8, bvSize);
+			auto bvShr = smtutil::Expression::int2bv(bvSize - 8, bvSize);
+			auto result = (bvBase << bvShl) >> bvShr;
```
Comment (axic) [inline libsolidity/formal/SMTEncoder.cpp:991]: Will this work if it shifts outside the value range? e.g. indexing out of bounds.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:991]: What should it answer? It mostly answers that the result is 0, but for
```
    function f(uint i) public pure {
        bytes4 x = 0x01020304;
        require(i > 3);
        assert(x[i] == 0x00);
    }
```
it says
```
Warning: Assertion violation happens here.
 --> ../test/libsolidity/smtCheckerTests/types/fixed_bytes_access_7.sol:7:3:
  |
7 | 		assert(x[i] == 0x00);
  | 		^^^^^^^^^^^^^^^^^^^^
Note: 
Counterexample:

i = 536870913


Transaction trace:
f(536870913)
```

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:991]: Maybe we can just answer 0 for now and soon add checks for bounds, because that's what's in runtime anyway.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:991]: So I updated the code to return an `unknown` value for out of bound access, I think it's the safest option for now.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `14c6b625d41eeb2296302174b46eb1df49d9a05f`:
```
Coding style error:
 libsolidity/formal/SMTEncoder.cpp:19:#include "libsmtutil/SolverInterface.h"

```
Please check that your changes are working as intended.

File: libsolidity/formal/SMTEncoder.cpp [hunk 3]
```diff
@@ -16,6 +16,7 @@
 */
 // SPDX-License-Identifier: GPL-3.0
 
+#include "libsmtutil/SolverInterface.h"
```
Comment (stackenbotten) [inline libsolidity/formal/SMTEncoder.cpp]: Coding style error

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (axic) [reply libsolidity/formal/SMTEncoder.cpp:991]: Sounds good, the question was whether it will crash or misbehave.

File: libsolidity/formal/SMTEncoder.cpp [hunk 4]
```diff
@@ -970,13 +970,36 @@ void SMTEncoder::endVisit(IndexAccess const& _indexAccess)
...
+			smtutil::Expression idx = expr(*_indexAccess.indexExpression());
+
+			auto bvBase = smtutil::Expression::int2bv(base, bvSize);
+			auto bvShl = smtutil::Expression::int2bv(idx * 8, bvSize);
+			auto bvShr = smtutil::Expression::int2bv(bvSize - 8, bvSize);
+			auto result = (bvBase << bvShl) >> bvShr;
+
+			auto anyValue = expr(_indexAccess);
+			m_context.expression(_indexAccess)->increaseIndex();
+			unsigned numBytes = bvSize / 8;
```
Comment (axic) [inline libsolidity/formal/SMTEncoder.cpp:995]: ~~Why not make this a shortcut? We are generated all these expressions for nothing :)~~

Ah okay, the entire thing can be symbolic so we can't omit it.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:995]: Yep

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:991]: Ok!

**Review by axic — APPROVED** [review]
