### PR TITLE
Fix ownership.

### LINKED ISSUE #8555: Utility methods: broken ownership
Take the following template in `libsolutil/CommonData.h` as an example:
```cpp
/// Concatenate the contents of a container onto a vector, move variant.
template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U&& _b)
{
	std::move(_b.begin(), _b.end(), std::back_inserter(_a));
	return _a;
}
```

The intent here appears to be able to move out of temporary ranges.

There are some issues with this:

First, `U&&` can deduce to (for instance) `std::vector<T>&` because `U&&` is a forwarding reference. This would result in moving out of elements in an lvalue range, which is not desirable. This can be fixed by constraining on `is_rvalue_reference_v<U&&>`.

However, the deeper issue is that the lifetime of a range does not necessarily correspond to the lifetime of its elements. Consider (using C++20's `span`):
```cpp
std::vector<T> vec = /* somehow initialize */;
std::vector<T> other = /* somehow initialize */;

std::span<T> s = vec;
other += std::move(s); // BUG - calls rvalue reference overload, moves out of elements owned by vec, although they will continue living past this line
```

This is harder to fix - it requires knowledge of the meanings of types.

### PR DESCRIPTION
**Pull request by aarlt**
Fixes #8555.

## Example of problem

```cpp
bytes solidity::util::ipfsHash(string _data)
{
	...
	protobufEncodedData += bytes{0x12};
	protobufEncodedData += lengthAsVarint; // move append, after this lengthAsVarint is not valid anymore, because all items where moved out of the container
	...
	protobufEncodedData += bytes{0x18} + lengthAsVarint; // here lengthAsVarint is not valid anymore
	...
}
```

I think I understood now what was happening here, this is my interpretation:

We defined the following functions:
```
/// Concatenate the contents of a container onto a vector
template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U const& _b)

/// Concatenate the contents of a container onto a vector, move variant.
template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U&& _b);
```

The lvalue reference implementation was only used, if `_b` was of constant type. In all other cases the "rvalue reference" implementation was used. In our case it is not always necessarily a rvalue reference. Because of the template parameter, the actual type will be deduced and can bind rvalues and non-constant lvalues. This is quite similar to Scott Meyers "universal references".

So our implementation of the "move variant" was basically an implementation that was able to bind lvalues and rvalues with the exception of constant lvalue references. So the "move variant" function was also called if non-constant lvalues where used. 

By removing `const` from the lvalue reference implementation, we ensure that the rvalue reference implementation can only bind rvalue references and the lvalue reference implementation will only bind to lvalue references.

### CODE REVIEW

File: libsolutil/CommonData.h [hunk 1]
```diff
@@ -57,10 +60,13 @@ template <class U, class... T> std::multiset<T...>& operator+=(std::multiset<T..
...
 }
 /// Concatenate the contents of a container onto a multiset, move variant.
-template <class U, class... T> std::multiset<T...>& operator+=(std::multiset<T...>& _a, U&& _b)
+template <class U, class... T,
+	class = typename std::enable_if<!std::is_lvalue_reference<U>::value>::type>
+std::multiset<T...>& operator+=(std::multiset<T...>& _a, U&& _b)
 {
 	for (auto&& x: _b)
 		_a.insert(std::move(x));
+	_b.clear();
```
Comment (chriseth) [inline libsolutil/CommonData.h]: Is this really needed? "If you move from an object, it is left in a consistent but undefined state."

Comment (aarlt) [reply libsolutil/CommonData.h]: it is not really needed, I just thought it may be more save

Comment (aarlt) [reply libsolutil/CommonData.h]: I will remove the clears now, because it is not really needed ;)

**Comment by ekpyron** [comment]
Can we instead just change
``template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U const& _b)`` to
``template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U& _b)``? Not sure, but might have the same effect, but I'd need to check what has precedence myself in this case.

**Comment by randomnetcat** [comment]
Since solidity is using C++17, you can use `std::enable_if_t<...>` instead of `typename std::enable_if<...>::type` and `std::is_lvalue_reference_v<...>` instead of `std::is_lvalue_reference<...>::value`.

**Comment by ekpyron** [comment]
I just checked - removing the ``const`` from the lvalue ref version and leaving the rvalue version as is should do the trick.
It'll correctly choose the lvalue version for `const&` and `&` (deducing ``U`` as ``const`` or not respectively) and the rvalue version for rvalue references.
If we want an additional safeguard we can add
``
static_assert(!std::is_lvalue_reference_v<U>, "")
``
to the rvalue version.

**Comment by aarlt** [comment]
@random-internet-cat @ekpyron thx for the feedback :)

I use now the c++17 stuff and remove `const` from the lvalue ref version.

File: libsolutil/CommonData.h [hunk 2]
```diff
@@ -38,39 +38,45 @@
...
+template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U& _b)
 {
 	for (auto const& i: _b)
 		_a.push_back(i);
 	return _a;
 }
 /// Concatenate the contents of a container onto a vector, move variant.
-template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U&& _b)
+template <class T, class U,
+	class = std::enable_if_t<!std::is_lvalue_reference_v<U>>>
```
Comment (ekpyron) [inline libsolutil/CommonData.h]: Just to be clear: With the change above you really don't need this change anymore now :-).
If you want, you can just move the condition into a static assertion in the body - but lvalues will always choose the version above now, so changing nothing in this version would actually be fine now.
(and of course the same holds for the other cases)

File: libsolutil/CommonData.h [hunk 3]
```diff
@@ -38,39 +38,45 @@
...
+std::vector<T>& operator+=(std::vector<T>& _a, U&& _b)
 {
 	std::move(_b.begin(), _b.end(), std::back_inserter(_a));
```
Comment (ekpyron) [inline libsolutil/CommonData.h]: Or in other words (if I'm right):
```suggestion
template <class T, class U> std::vector<T>& operator+=(std::vector<T>& _a, U&& _b)
{
	static_assert(!std::is_lvalue_reference_v<U>, "You should not be able to make this fail, because the U& version takes precedence!");
	std::move(_b.begin(), _b.end(), std::back_inserter(_a));
```

File: libsolutil/CommonData.h (hunk 2 above)
Comment (aarlt) [reply libsolutil/CommonData.h]: ah really? will check that.. compiling on my machine takes sooooo looong :/

File: libsolutil/CommonData.h (hunk 3 above)
Comment (aarlt) [reply libsolutil/CommonData.h]: It looks like that this is not working. It looks like that `U&&` version takes precedence.

Comment (aarlt) [reply libsolutil/CommonData.h]: Ah no! You're right!

**Comment by aarlt** [comment]
@ekpyron thank you soo much for your feedback! It took me a while to fully understand what was happening here, I hope that my interpretation is correct.

**Comment by ekpyron** [comment]
Yeah, this is higher C++ dark-magic :-).

**Review by chriseth — APPROVED** [review]

**Comment by ekpyron** [comment]
I would actually have added the static assertion to the other one to make sure...

**Comment by ekpyron** [comment]
Also: what about the other cases in ``CommonData``? We do need to do the same for the set's, etc., don't we?

**Comment by ekpyron** [comment]
So @aarlt Can you open a new PR with the rest :-)?
