### PR TITLE
Fix SMT Checker crash due to missing type information

### LINKED ISSUE #6057: SMTchecker crash with unsupported array in struct
Found by ossfuzz (13237)

```
contract C {
  struct S{
    int[6*1] x;
  }
}
```

results in
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3878:17: runtime error: reference binding to null pointer of type 'std::__1::shared_ptr<const dev::solidity::Type>::element_type' (aka 'const dev::solidity::Type')
/Users/alex/Projects/solidity/libsolidity/formal/SMTChecker.cpp:700:21: runtime error: reference binding to null pointer of type 'const dev::solidity::Type'
```

### PR DESCRIPTION
**Pull request by Marenz**
Fixes #6057

### CODE REVIEW

File: libsolidity/analysis/ConstantEvaluator.cpp [hunk 1]
```diff
@@ -53,18 +53,19 @@ void ConstantEvaluator::endVisit(BinaryOperation const& _operation)
...
-		setType(
-			_operation,
+		commonType =
 			TokenTraits::isCompareOp(_operation.getOperator()) ?
 			make_shared<BoolType>() :
-			commonType
-		);
+			commonType;
+		setType(_operation, commonType);
+		_operation.annotation().commonType = commonType;
```
Comment (chriseth) [inline libsolidity/analysis/ConstantEvaluator.cpp]: Actually the common type is always the one the operation is performed in, so even for comparison operators, it is the common type of its parameters, not bool.

Also, shouldn't the type checker actually set the annotations?

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/analysis/ConstantEvaluator.cpp (hunk 1 above)
Comment (Marenz) [reply libsolidity/analysis/ConstantEvaluator.cpp]: I haven't figured out exactly yet which part should do the types, I mean we also set the type in the references resolver: https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/ReferencesResolver.cpp#L249

Comment (chriseth) [reply libsolidity/analysis/ConstantEvaluator.cpp]: Yes, but only inside typenames.

**Comment by Marenz** [comment]
Pushed a fix in TypeChecker. This is inccidently exactly what I did initially for the previous fix: https://github.com/ethereum/solidity/commit/1aca60783380eddc8559b46efcb7efc3f9c14366 which chris didn't like though

**Comment by Marenz** [comment]
Ready for review.

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -504,12 +504,18 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
...
 		if (auto arrayType = dynamic_cast<ArrayType const*>(varType.get()))
+		{
 			if (
 				((arrayType->location() == DataLocation::Memory) ||
 				(arrayType->location() == DataLocation::CallData)) &&
 				!arrayType->validForCalldata()
 			)
 				m_errorReporter.typeError(_variable.location(), "Array is too large to be encoded.");
+
+			if (auto arrayTypeName = dynamic_cast<ArrayTypeName*>(_variable.typeName()))
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Would it suffice to just call `_variable.typeName()->accept(*this)`?

This could also just be done at the beginning of the function.

**Comment by Marenz** [comment]
Pushed with Chris' suggestion

**Review by chriseth — APPROVED** [review]

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -448,6 +448,9 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
 	)
 		m_errorReporter.typeError(_variable.location(), "Variables cannot be declared in interfaces.");
 
+	if (_variable.typeName())
+		_variable.typeName()->accept(*this);
```
Comment (axic) [inline libsolidity/analysis/TypeChecker.cpp]: Does this mean we're doing smtchecker traversal before the type checker? Or we do not resolve these in the type checker?
