### PR TITLE
Fix member lookup for constructor in library.

### LINKED ISSUE #9557: ICE in virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const
## Description

This contract:
```solidity
library L {
    function x() internal returns (uint256) {
    }
    constructor() {
	x = L.x;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/AST.cpp(294): Throw in function virtual solidity::frontend::Visibility solidity::frontend::FunctionDefinition::defaultVisibility() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.1-develop.2020.7.31+commit.f2fa5b5f.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/9557

### CODE REVIEW

**Review by ekpyron — COMMENTED** [review]
Test needs expectations - otherwise looks good!

**Review by leonardoalt — APPROVED** [review]

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -451,7 +451,7 @@ MemberList::MemberMap Type::boundFunctions(Type const& _type, ASTNode const& _sc
 		);
 		for (FunctionDefinition const* function: library.definedFunctions())
 		{
-			if (!function->isVisibleAsLibraryMember() || seenFunctions.count(function))
+			if (!function->isOrdinary() || !function->isVisibleAsLibraryMember() || seenFunctions.count(function))
```
Comment (axic) [inline libsolidity/ast/Types.cpp:454]: This line is the actual fix, right?

Comment (chriseth) [reply libsolidity/ast/Types.cpp:454]: This and the emptyness check belo.
