### PR TITLE
Relax type equality requirement of function types during conversion in code generation.

### LINKED ISSUE #5279: Internal compiler error: function type conversion view to non-view
## Description

The following solidity contract produces the error: `Invalid error: "InternalCompilerError"`

```
contract C {
    function h() pure external {
    }
    function f() view external returns (bytes4) {
        function ()  external g = this.h;
        return g.selector;
    }
}
// ----
```

## Environment

- Compiler version: latest develop commit
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 16.04

## Steps to Reproduce

```
$ ./solfuzzer < <sol_contract_above>
```

Found by libFuzzer

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #5279.

### CODE REVIEW

File: libsolidity/codegen/CompilerUtils.cpp [hunk 1]
```diff
@@ -1014,6 +1014,8 @@ void CompilerUtils::convertType(
 			// stack: <address> <function_id>
 			m_context << Instruction::POP;
 		}
+		else if (stackTypeCategory == Type::Category::Function && targetTypeCategory == Type::Category::Function)
+			solAssert(_typeOnStack.isImplicitlyConvertibleTo(_targetType), "Invalid function type conversion requested.");
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]: This looks a little dangerous to me. Please add asserts that we only allow internal -> internal or external -> external conversions - there are so many different function types.

Comment (chriseth) [reply libsolidity/codegen/CompilerUtils.cpp]: Oh and please also add an assert that the stack size is equal.

Comment (chriseth) [reply libsolidity/codegen/CompilerUtils.cpp]: And what about the code that would have been generated otherwise in line 1023 - is the condition always false in this case?

Comment (ekpyron) [reply libsolidity/codegen/CompilerUtils.cpp]: Updated.

**Review by chriseth — APPROVED** [review]
