### PR TITLE
Warn on JUMP/JUMPI in inline assembly

### LINKED ISSUE #2365: Variable locations are wrongly calculated in Julia assembler
```
{
  let x := 1

  jump(label)

  let y := 2
  
label:
  let z := x
}
```

The location of `x` is calculated wrongly, because the other declarations between the jump and label are also taken into account.

`z` should be `dup1`, but is generated as `dup2`. If `let y` is removed it results in `dup1`.

### PR DESCRIPTION
**Pull request by axic**
Fixes #2365.

### CODE REVIEW

File: libsolidity/inlineasm/AsmAnalysis.cpp [hunk 1]
```diff
@@ -486,4 +486,11 @@ void AsmAnalyzer::warnOnFutureInstruction(solidity::Instruction _instr, SourceLo
 			+ "\" instruction is only available after " +
 			"the Metropolis hard fork. Before that it acts as an invalid instruction."
 		);
+
+	if (_instr == solidity::Instruction::JUMP || _instr == solidity::Instruction::JUMPI)
+		m_errorReporter.warning(
+			_location,
+			"Using jumps requires stack adjustments when working with variables. "
```
Comment (chriseth) [inline libsolidity/inlineasm/AsmAnalysis.cpp]: "requires" sounds too strong, jumpi can be used without stack adjustments.
Perhaps we should phase the whole thing in a different way and also warn on labels. Something like `labels and jump instructions are low-level EVM features that can lead to incorrect stack access. Because of that, they are discouraged, please consider using "switch" or "for" statements."

**Review by chriseth — CHANGES_REQUESTED** [review]
Did you check that this does not cause warnings for the internal assembly routines we use?

**Review by chriseth — APPROVED** [review]
