### PR TITLE
Common input file processing for CLI and Standard JSON

### LINKED ISSUE #11552: Crash with --standard-json when the JSON path is a directory
`solc` crashes in Standard JSON mode when the specified path exists but is not a regular file:

```bash
solc --standard-json /tmp/
```

```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
Aborted (core dumped)
```

## Environment

- Compiler version: 0.8.5
- Operating system: Arch Linux

### PR DESCRIPTION
**Pull request by cameel**
Fixes #11552.
~Depends on #11520. Draft until that one is merged.~ Merged.

The main purpose of this refactor is to group input file processing and `FileReader` initialization in `CommandLineInterface` into an independent phase (`readInputFiles()`), separate from actually running the compiler. This way its results can be easily tested. So far almost all of this was already grouped into `readInputFilesAndConfigureFileReader()` except for stuff related to Standard JSON. This PR unifies the logic for Standard JSON with that for other modes.

As a side effect this improves the behavior with `--standard-input`:
- Fixes the crash from #11552.
-  An explicit request to read from standard input (the `-` option) now works in that mode too.
-  Technically, `--ignore-missing` now works as well but it's useless because in Standard JSON you cannot specify more than one file.
- If you try to specify remappings on the command line you get an error explicitly telling you to put them in JSON instead of one saying that there are too many input fiies.

### CODE REVIEW

File: solc/CommandLineInterface.cpp [hunk 1]
```diff
@@ -377,8 +377,18 @@ void CommandLineInterface::handleGasEstimation(string const& _contract)
 	}
 }
 
-bool CommandLineInterface::readInputFilesAndConfigureFileReader()
+bool CommandLineInterface::readInputFiles()
 {
+	solAssert(!m_standardJsonInput.has_value(), "");
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp:382]:
```suggestion
	solAssert(!m_standardJsonInput, "");
```

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -411,16 +421,33 @@ bool CommandLineInterface::readInputFilesAndConfigureFileReader()
 		}
 
 		// NOTE: we ignore the FileNotFound exception as we manually check above
-		m_fileReader.setSource(infile, readFileAsString(infile.string()));
-		m_fileReader.allowDirectory(boost::filesystem::path(boost::filesystem::canonical(infile).string()).remove_filename());
+		string fileContent = readFileAsString(infile.string());
+		if (m_options.input.mode == InputMode::StandardJson)
+		{
+			solAssert(!m_standardJsonInput.has_value(), "");
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp:427]:
```suggestion
			solAssert(!m_standardJsonInput, "");
```

File: solc/CommandLineInterface.cpp [hunk 3]
```diff
@@ -411,16 +421,33 @@ bool CommandLineInterface::readInputFilesAndConfigureFileReader()
 		}
 
 		// NOTE: we ignore the FileNotFound exception as we manually check above
-		m_fileReader.setSource(infile, readFileAsString(infile.string()));
-		m_fileReader.allowDirectory(boost::filesystem::path(boost::filesystem::canonical(infile).string()).remove_filename());
+		string fileContent = readFileAsString(infile.string());
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp:424]: it's called "read**File**AsString", maybe it should expect a filesystem::path then? So you don't have to pass `infile.string()` but only `infile`. (just a code cleanup idea).

File: solc/CommandLineInterface.cpp [hunk 4]
```diff
@@ -411,16 +421,33 @@ bool CommandLineInterface::readInputFilesAndConfigureFileReader()
...
+		if (m_options.input.mode == InputMode::StandardJson)
+		{
+			solAssert(!m_standardJsonInput.has_value(), "");
+			m_standardJsonInput = move(fileContent);
+		}
+		else
+		{
+			m_fileReader.setSource(infile, move(fileContent));
+			m_fileReader.allowDirectory(boost::filesystem::path(boost::filesystem::canonical(infile).string()).remove_filename());
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp]:
```suggestion
			m_fileReader.allowDirectory(boost::filesystem::path(boost::filesystem::canonical(infile)).remove_filename());
```
This should work, too, isn't it?

File: solc/CommandLineInterface.cpp [hunk 5]
```diff
@@ -411,16 +421,33 @@ bool CommandLineInterface::readInputFilesAndConfigureFileReader()
...
+		}
 	}
 
 	if (m_options.input.addStdin)
-		m_fileReader.setSource(g_stdinFileName, readUntilEnd(m_sin));
+	{
+		if (m_options.input.mode == InputMode::StandardJson)
+		{
+			solAssert(!m_standardJsonInput.has_value(), "");
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp:441]:
```suggestion
			solAssert(!m_standardJsonInput, "");
```

File: solc/CommandLineInterface.cpp [hunk 6]
```diff
@@ -411,16 +421,33 @@ bool CommandLineInterface::readInputFilesAndConfigureFileReader()
...
+			m_standardJsonInput = readUntilEnd(m_sin);
+		}
+		else
+			m_fileReader.setSource(g_stdinFileName, readUntilEnd(m_sin));
+	}
 
-	if (m_fileReader.sourceCodes().size() == 0)
+	if (m_fileReader.sourceCodes().size() == 0 && !m_standardJsonInput.has_value())
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp]:
```suggestion
	if (m_fileReader.sourceCodes().empty() && !m_standardJsonInput)
```

File: solc/CommandLineParser.cpp [hunk 7]
```diff
@@ -899,10 +915,8 @@ General Information)").c_str(),
 		m_options.output.evmVersion = *versionOption;
 	}
 
-	if (m_args.count(g_strAssemble) || m_args.count(g_strStrictAssembly) || m_args.count(g_strYul))
+	if (m_options.input.mode == InputMode::Assembler)
```
Comment (christianparpart) [inline solc/CommandLineParser.cpp:934]: You chain the `if`-statements to iterate through each `InputMode` enum class' value.
If you use a switch statement here, the compiler would tell you if you accidentally missed handling one case. I also think it would be cleaner, but that might be subjective. :)

File: test/solc/CommandLineInterface.cpp [hunk 8]
```diff
@@ -0,0 +1,294 @@
...
+	string stdoutContent;
+	string stderrContent;
+};
+
+OptionsReaderAndMessages parseCommandLineAndReadInputFiles(vector<string> const& commandLine)
+{
+	size_t argc = commandLine.size();
+	vector<char const*> argv(commandLine.size() + 1);
+
+	// argv[argc] typically contains NULL
```
Comment (christianparpart) [inline test/solc/CommandLineInterface.cpp]: not just typically. isn't it always?

File: test/solc/CommandLineInterface.cpp [hunk 9]
```diff
@@ -0,0 +1,294 @@
...
+	argv[argc] = nullptr;
+
+	for (size_t i = 0; i < argc; ++i)
```
Comment (christianparpart) [inline test/solc/CommandLineInterface.cpp]:
```suggestion
	for (size_t const i: views::iota(argc))
```
Just a suggestion (I try to avoid mutating variables that don't have any special purpose) :)
This comes from `<ranges/views/iota.hpp>`.

File: test/solc/CommandLineInterface.cpp [hunk 10]
```diff
@@ -0,0 +1,294 @@
...
+		"Import remappings are not accepted on the command line in Standard JSON mode.\n"
+		"Please put them under 'settings.remappings' in the JSON input.\n";
+
+	vector<string> commandLine = {"solc", "--standard-json", "a=b"};
+	OptionsReaderAndMessages result = parseCommandLineAndReadInputFiles(commandLine);
+	BOOST_TEST(!result.success);
+	BOOST_TEST(result.stderrContent == expectedMessage);
+}
+
+BOOST_AUTO_TEST_SUITE_END()
```
Comment (christianparpart) [inline test/solc/CommandLineInterface.cpp:344]: I really like the testability of the CLI arguments! :+1:

File: test/solc/CommandLineParser.cpp [hunk 11]
```diff
@@ -388,10 +388,10 @@ BOOST_AUTO_TEST_CASE(standard_json_mode_options)
 
 	CommandLineOptions expectedOptions;
 	expectedOptions.input.mode = InputMode::StandardJson;
-	expectedOptions.input.paths = {};
-	expectedOptions.input.standardJsonFile = "input.json";
+	expectedOptions.input.paths = {"input.json"};
 	expectedOptions.input.basePath = "/home/user/";
 	expectedOptions.input.allowedDirectories = {"/tmp", "/home", "project", "../contracts"};
+	expectedOptions.input.ignoreMissingFiles = true;
 	expectedOptions.output.dir = "/tmp/out";
```
Comment (christianparpart) [inline test/solc/CommandLineParser.cpp:392]: It was already there, but it should never be hardcoded to `/tmp`. Is this used and written to somewhere? (if not, ignore this message). :)

**Review by christianparpart — CHANGES_REQUESTED** [review]

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:382]: I find `!x.has_value()` much more readable than `!x`. The latter often does not really read like a condition. And it makes `x` look like a pointer. I'd prefer to keep this as is.

File: solc/CommandLineInterface.cpp (hunk 3 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:424]: Right, this should be a path. It's unrelated to this PR though so I have submitted a separate one: #11650.

The downside is that now `CommonIO.h` includes the boost path header but I guess we can live with that.

File: solc/CommandLineInterface.cpp (hunk 4 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp]: Yeah. Also the explicit `boost::filesystem::path` conversion is unnecessary.

File: solc/CommandLineInterface.cpp (hunk 6 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp]: Changed `size() == 0` to `empty()`.

File: solc/CommandLineParser.cpp (hunk 7 above)
Comment (cameel) [reply solc/CommandLineParser.cpp:934]: Right. I guess it's time to start applying the refactors requested in the CLI PR :)
Done.

File: test/solc/CommandLineInterface.cpp (hunk 8 above)
Comment (cameel) [reply test/solc/CommandLineInterface.cpp]: Oh. Looks like it's the language standard that mandates this. I though it was just a convention.
Comment fixed.

File: test/solc/CommandLineInterface.cpp (hunk 9 above)
Comment (cameel) [reply test/solc/CommandLineInterface.cpp]: I get the idea but in this case I'd rather keep the loop as is. The current form is the bog standard idiomatic one that everyone recognizes at a glance. The one with `iota` is still simple but it would still give me a pause because it's not very common :)

File: test/solc/CommandLineParser.cpp (hunk 11 above)
Comment (cameel) [reply test/solc/CommandLineParser.cpp:392]: `CommandLineParser` is not meant to read anything from disk so it's fine. Note that all the actual file reading and checks for path existence are in `CommandLineInterface`. This is for example the reason why both have separate conditions to check if there were any input files - even if `CommandLineParser` checks it and sees that there's at least one path, `CommandLineInterface` with `--ignore-missing` could still see zero files because they do not actually exist.

I decided to use these paths like this because dealing with absolute paths when you need to ensure they exist overcomplicates tests a lot. See for example tests like `cli_paths_to_source_unit_names_relative_base_path` from `test/solc/CommandLineInterface.cpp` in #11545. These tests would be much simpler if I could just write paths like this but there I can't.

**Comment by cameel** [comment]
This is now ready for another round.

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (christianparpart) [reply solc/CommandLineInterface.cpp:382]: I am not sure if we should come up with something as a rule-of-thumb to this question, because I see it written in both ways, and I am getting corrected into at least one way (using `operator!` and `operator bool()`). I'm fine with either way.

File: solc/CommandLineInterface.cpp [hunk 12]
```diff
@@ -377,8 +377,18 @@ void CommandLineInterface::handleGasEstimation(string const& _contract)
...
-bool CommandLineInterface::readInputFilesAndConfigureFileReader()
+bool CommandLineInterface::readInputFiles()
 {
+	solAssert(!m_standardJsonInput.has_value(), "");
+
+	m_fileReader.setBasePath(m_options.input.basePath);
+
+	if (m_options.input.basePath != "" && !boost::filesystem::is_directory(m_options.input.basePath))
+	{
+		serr() << "Base path must be a directory: \"" << m_options.input.basePath << "\"\n";
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp]: maybe quote `basePath` here in the output to avoid accidentally misleading output? - Or don't quote at all.

File: solc/CommandLineInterface.cpp [hunk 13]
```diff
@@ -411,16 +421,33 @@ bool CommandLineInterface::readInputFilesAndConfigureFileReader()
...
+		}
+		else
+			m_fileReader.setSource(g_stdinFileName, readUntilEnd(m_sin));
+	}
 
-	if (m_fileReader.sourceCodes().size() == 0)
+	if (m_fileReader.sourceCodes().empty() && !m_standardJsonInput.has_value())
 	{
-		serr() << "No input files given. If you wish to use the standard input please specify \"-\" explicitly." << endl;
+		serr() << "All specified input files either do not exist or are not regular files." << endl;
```
Comment (christianparpart) [inline solc/CommandLineInterface.cpp:450]: Why actually `endl` and not `\n`? Not that we care about performance at that stage (`endl` is flushing, `\n` is not necessarily), but `\n` works on all platforms, and is shorter to write than always this concatenation style for creating a newline.

**Review by christianparpart — DISMISSED** [review]
LGTM (apart from the minors which seem subjective anyways :)

File: solc/CommandLineInterface.cpp (hunk 12 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp]: OK. I tried to be consistent about quoting but looks like existing messages are themselves not consistent :) True, the ones in this part do not quote stuff.

We should really do #7578 some day :)

File: solc/CommandLineInterface.cpp (hunk 13 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:450]: Mostly because it's the prevalent style used in this file and I don't think the difference matters for us here. As for readability, I slightly prefer `endl` because `\n` looks like noise to me :) but I don't feel too strongly about either.

If we want to change this, we should go over the whole file (and maybe more files) so I'd rather not do it in this PR.
It might actually be a `good first issue` for someone so maybe create an issue for it?

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:382]: Yeah, one of these things where we'd need to agree on common style. Until then you probably will get corrected either way :)

BTW, I saw @ekpyron using `has_value()` in his PR so it's not just me :)

File: solc/CommandLineInterface.cpp (hunk 13 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:450]: Oh, I just noticed that I used `\n` in the base path message (and it's the only one like that in the file). Changed that to `endl` now for consistency.

File: solc/CommandLineInterface.cpp (hunk 12 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp]: Quotes removed.

I actually also changed `m_options.input.basePath` to `m_fileReader.basePath()` because that's what we should be checking.

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (ekpyron) [reply solc/CommandLineInterface.cpp:382]: Although I mainly use it, because people are telling me it's nicer and I don't really mind either way myself :-). Unfortunately though, as a consequence, I don't think I do it consistently either way myself these days :-).

Comment (cameel) [reply solc/CommandLineInterface.cpp:382]: > because people are telling me it's nicer

Well, they're right :P

I'm not really sure why people are not bothered more by using non-boolean values in conditions but for me it just makes them harder to read so it's not worth saving a few keystrokes.

File: solc/CommandLineParser.cpp [hunk 14]
```diff
@@ -846,42 +872,32 @@ General Information)").c_str(),
 			m_options.output.stopAfter = CompilerStack::State::Parsed;
 	}
 
-	vector<string> const exclusiveModes = {
+	checkMutuallyExclusive({
```
Comment (aarlt) [inline solc/CommandLineParser.cpp]: I guess the return value was supposed to be used here.

File: test/solc/CommandLineParser.cpp (hunk 11 above)
Comment (aarlt) [inline test/solc/CommandLineParser.cpp:392]: I'm not entirely sure, but wouldn't it be good to also add some tests here that test command line parameters that are usually used in different platforms, e.g. windows. Just to verify that the `CommandLineParser` parses e.g. windows specific paths correctly.

**Comment by aarlt** [comment]
Looks good to me, at least for now I only found one small thing. 

However, I was wondering whether we should reduce the line numbers used in `bool CommandLineParser::parse(...)`. I think this function is a bit too long (ca. 700 lines).

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (ekpyron) [reply solc/CommandLineInterface.cpp:382]: I mainly use non-boolean values on conditions in branches, like ``if (auto someOptional = someFunction())``.
You could write ``if (auto someOptional = someFunction(); someOptional.has_value())`` for those, but in that case it seems like a pretty weird thing to do :-). In all other cases I could get used to using ``.has_value()``. But what do you propose for checking a pointer being not-``nullptr``? That's also a non-boolean value... we do have cases of ``!!ptr`` for that, but IMHO that doesn't really improve anything :-). And ``ptr != nullptr`` seems overly verbose.

Comment (ekpyron) [reply solc/CommandLineInterface.cpp:382]: And if it's fine for a pointer to just implicitly have it convert to `bool`, I'm not sure why it should be wrong for an `optional`...

File: solc/CommandLineParser.cpp (hunk 14 above)
Comment (cameel) [reply solc/CommandLineParser.cpp]: Right. Great catch! I'm actually surprised it's not covered by tests. I'll add one.

File: test/solc/CommandLineParser.cpp (hunk 11 above)
Comment (cameel) [reply test/solc/CommandLineParser.cpp:392]: True and I actually do have such tests but only for `CommandLineInterface` (in #11545). `CommandLineInterface` actually reads files and uses these paths. `CommandLineParser` only puts paths in the options struct so I think there's not much gain from repeating these tests for it. Especially given that these tests are pretty bulky and often need ifdefs for other platforms.

Actually, I could move the first commit from #11545 that contains them here but I'm not sure if this makes sense now that it's been reviewed. Originally I wanted it to be a separate PR but I already have too many PRs that depend on each other and I decided to avoid creating more.

**Comment by cameel** [comment]
> However, I was wondering whether we should reduce the line numbers used in `bool CommandLineParser::parse(...)`. I think this function is a bit too long (ca. 700 lines).

I totally agree. This is not a new thing though. The functions in `CommandLineInterface` were already pretty big and I just did not split them to keep the diff smaller. I'm going to do some more refactors, but step by step, over time because this is not a priority right now. The main point of my refactor was only to make the CLI somewhat testable, not to rewrite it all :)

File: solc/CommandLineParser.cpp (hunk 14 above)
Comment (cameel) [reply solc/CommandLineParser.cpp]: Done.

**Comment by cameel** [comment]
Fixes applied, comments answered. This is ready for another round.

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:382]: I don't see anything wrong with `ptr != nullptr`. It reads like a full condition (if ptr is not null). `ptr` as a condition is just weird and I only use it because it's prevalent style in our code already. Otherwise I'd never do that.

I don't think it's wrong. I just think it's not as readable. This style is really common in Python and I really hate it.

> You could write `if (auto someOptional = someFunction(); someOptional.has_value())` for those, but in that case it seems like a pretty weird thing to do :-).

Agreed. I mean, I'd prefer to have has_value()` there but a preference for not having the second part in the `if` is much stronger :) It's too easy to overlook that part when skimming over code.

Comment (ekpyron) [reply solc/CommandLineInterface.cpp:382]: Actually, e.g. in ``assert(ptr != nullptr)`` or even ``if(ptr != nullptr)`` I'd even be ok with it - I'm just extremely used to implicit pointer-to-bool conversions, so I'd probably have to be constantly reminded until I'm used to it :-D. But even more prevalent in the code is again the ``if (auto ptr = ...sth...)`` case, especially with the RTTI ``dynamic_cast`` cases... and there ``if (auto ptr = ...; ptr != nullptr)`` has the same problem as the optional case... but yeah, not sure. Maybe we should more broadly collect opinions. *Sometimes* using ``assert(!!ptr)``, *sometimes* ``assert(ptr)``, *sometimes* ``assert(someOptional)`` and *sometimes* ``assert(someOptional.has_value())`` randomly for sure isn't the nicest thing to do.

**Review by Marenz — DISMISSED** [review]

**Comment by cameel** [comment]
@Marenz Can you reapprove? I only squashed fixups.

**Comment by cameel** [comment]
I'm adding some refactors from work on #11688. All of this basically only touches the test utilities and should not require re-reviewing the whole PR. Since this PR has not been merged yet, I think it makes more sense to change this stuff here instead of having to immediately refactor it in later PRs. Everything that has been added is in fixup commits:
- Added `test/solc/Common.h` and moved helpers from `CommandLineInterface`/`CommandLineParser` tests there.
    - Made `parseCommandLineAndReadInputFiles()` a bit more generic.
- Operators for printing sources, allowed paths and remappings if a test fails.
- `createEmptyFilesWithParentDirs()` is now `createFilesWithParentDirs()` and you can specify file content.
- `TEST_CASE_NAME` (see #11686).

**Review by christianparpart — DISMISSED** [review]
LGTM (again, actually) :)

**Comment by cameel** [comment]
Great. In that case I've squashed the fixups and rebased on develop so that it's ready to merge.

**Comment by cameel** [comment]
Conflict resolved. It was just a change from #11639 that added the formatting parameter to `StandardCompiler`. I just adjusted the constructor invocation in `CommandLineInterface.cpp`.

**Review by christianparpart — APPROVED** [review]
re-approved after fixes.
