### PR TITLE
Fix segmentation fault with constant function parameters

### LINKED ISSUE #2403: Segmentation fault with constant array parameter
Source code:

```
contract test {
  function f(uint[] constant x) {
    x[0] = 1;
  }
}
```

AFAIK, the constant qualifier should be forbidden inside parameter lists.

### PR DESCRIPTION
**Pull request by federicobond**
Closes #2403

### CODE REVIEW

**Comment by chriseth** [comment]
A segmentation fault is a very serious error. Usually, we have assertion guards, so that segmentation faults cannot happen in one component, even if another component fails. Could you try to spot down the bug, introduce a corresponding assert and only then add the "not implemented" assertion?

**Comment by federicobond** [comment]
Yes, that makes sense. I already tracked the bug. I will add the assertion guard there too.

**Comment by federicobond** [comment]
SIGSEGV happens [here](https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/ExpressionCompiler.cpp#L1788) because variable is declared as constant but value() is nullptr.

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 1]
```diff
@@ -1785,6 +1785,7 @@ void ExpressionCompiler::appendVariable(VariableDeclaration const& _variable, Ex
 		setLValueFromDeclaration(_variable, _expression);
 	else
 	{
+		solUnimplementedAssert(_variable.value(), "Not implemented for constant parameters.");
```
Comment (axic) [inline libsolidity/codegen/ExpressionCompiler.cpp]: I think this should just be a regular `solAssert(_variable.value(), "");`?

**Comment by chriseth** [comment]
Hm, this should actually be called by TypeChecker.cpp:507 - It might be that the type checker for FunctionDeclaration does not visit the parameters.

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 1 above)
Comment (federicobond) [reply libsolidity/codegen/ExpressionCompiler.cpp]: I was just copying the style I saw 10 lines above since @chriseth mentioned this was not implemented.

**Comment by federicobond** [comment]
@chriseth indeed, that seems to be the case. Testing a solution right now.

**Comment by federicobond** [comment]
That was a great find! I started visiting VariableDeclaration nodes for each parameter and now I get this cascade of errors we weren't triggering before:

```
test1.sol:2:16: Error: Illegal use of "constant" specifier.
  function foo(uint[] constant a) {
               ^---------------^
test1.sol:2:16: Error: Constants of non-value type not yet implemented.
  function foo(uint[] constant a) {
               ^---------------^
test1.sol:2:16: Error: Uninitialized "constant" variable.
  function foo(uint[] constant a) {
               ^---------------^
```

**Comment by federicobond** [comment]
Will definitely add tests for this.

**Comment by chriseth** [comment]
@federicobond do you still want to add tests or can this be merged?

Please add an entry to the changelog file!

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -487,7 +489,10 @@ bool TypeChecker::visit(FunctionDefinition const& _function)
 
 bool TypeChecker::visit(VariableDeclaration const& _variable)
 {
-	if (m_scope->contractKind() == ContractDefinition::ContractKind::Interface)
+	if (
+		m_scope->contractKind() == ContractDefinition::ContractKind::Interface
+		&& !_variable.isCallableParameter()
```
Comment (axic) [inline libsolidity/analysis/TypeChecker.cpp]: ~~Can you add a test for this?~~

Ah, it is the "returns (bool)" test.

**Comment by federicobond** [comment]
@chriseth I added a new test case and expanded another one, so I think it's fine to merge as it is.

I also just added the changelog entry.

File: libsolidity/analysis/TypeChecker.cpp (hunk 2 above)
Comment (axic) [reply libsolidity/analysis/TypeChecker.cpp]: Actually can you add a comment here to explain what is this for? (As a good practice, because the `isCallableParameter` doesn't seem very meaningful in this context)

Comment (federicobond) [reply libsolidity/analysis/TypeChecker.cpp]: Good idea. Done.

Comment (axic) [reply libsolidity/analysis/TypeChecker.cpp]: The description actually reminded to add a test with input parameter :)

File: test/libsolidity/SolidityNameAndTypeResolution.cpp [hunk 3]
```diff
@@ -5611,7 +5621,7 @@ BOOST_AUTO_TEST_CASE(using_interface_complex)
 	char const* text = R"(
 		interface I {
 			event A();
-			function f();
+			function f() returns(bool);
```
Comment (axic) [inline test/libsolidity/SolidityNameAndTypeResolution.cpp]: Can't comment on the right spot, but this test should fail. The interace defines a return parameter, while the implementation is omitting it.

Comment (federicobond) [reply test/libsolidity/SolidityNameAndTypeResolution.cpp]: Indeed, but I would venture to say it falls a bit out of the scope of this PR. ~~This happens because `TypeChecker::checkContractIllegalOverrides` relies in `_contract.annotation().linearizedBaseContracts` which probably does not include the implemented interfaces.~~

**Edit:** it's definitely not that, because when compiling the same example outside tests it rejects it. May be something specific to the test setup.

Should I leave the test highlighting the broken functionality and submit another PR with the fix?

Comment (axic) [reply test/libsolidity/SolidityNameAndTypeResolution.cpp]: I would say create a new PR and remove this change here as it is covered by `interface_function_parameters`.
