### PR TITLE
[SMTChecker] Shortcut RationalNumber expressions

### LINKED ISSUE #6095: Number constant too large assertion in SMTChecker
Found by ossfuzz (12969).

```
pragma experimental SMTChecker;
contract c {
  function f() public {
    8e130%9;
  }
}
```

```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/ast/Types.cpp(1287): Throw in function virtual dev::u256 dev::solidity::RationalNumberType::literalValue(const dev::solidity::Literal *) const
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Number constant too large.
[dev::tag_comment*] = Number constant too large.
```

It is not the same issue as #5056 as it works if SMT is disabled.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #6095 

When visiting a `UnaryExpression` or `BinaryExpression`, if the type is `RationalNumber`, we can shortcut and add the constant literal as the symbolic expression and ignore the `endVisit` of those node types.

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
I think this is fine!

File: libsolidity/formal/SMTChecker.cpp [hunk 1]
```diff
@@ -374,6 +374,9 @@ void SMTChecker::checkOverflow(OverflowTarget& _target)
 
 void SMTChecker::endVisit(UnaryOperation const& _op)
 {
+	if (_op.annotation().type->category() == Type::Category::RationalNumber)
```
Comment (chriseth) [inline libsolidity/formal/SMTChecker.cpp]: Why do you need this?
