### PR TITLE
[Sol->Yul] Implementing getter for struct with bytes member

### LINKED ISSUE #10115: [Sol->Yul] Strings in public storage variables
Originally reported as a bug in #10100. IR generator is still experimental so it looks more like a missing feature though.

Currently using `string` storage variables with `public` visibility crashes the IR generator. As a consequence, wasm generation for such code does not work either.

This applies to `string` and `bytes` storage variables as well as mappings, structs and arrays that contain them.

## Steps to Reproduce
```solidity
contract C {
    string public s;
}
```

```bash
solc --ir test.sol
```
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/YulUtilFunctions.cpp(1968): Throw in function std::string solidity::frontend::YulUtilFunctions::readFromStorageDynamic(const solidity::frontend::Type&, bool)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

## Environment
- Compiler version: 0.7.4+commit.3f05b770.Linux.g++

### LINKED ISSUE #10118: [Sol->Yul] Initializing string storage variables
Originally reported as a bug in #10100. IR generator is still experimental so it looks more like a missing feature though.

An attempt to initialize a `string` or `bytes` storage variable crashes the IR generator. As a consequence, wasm generation for such code does not work either.

This looks similar to #10115 but the crash happens in a different function and affects non-public storage variables too.

## Steps to Reproduce
```solidity
contract C {
    string s = "abcd";
    bytes b = "abcd";
}
```

```bash
solc --ir test.sol
```
```
Internal compiler error during compilation:
/solidity/libsolidity/codegen/YulUtilFunctions.cpp(2121): Throw in function solidity::frontend::YulUtilFunctions::updateStorageValueFunction(const solidity::frontend::Type&, const solidity::frontend::Type&, const std::optional<unsigned int>&)::<lambda()>
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

## Environment
- Compiler version: 0.7.4+commit.3f05b770.Linux.g++

### PR DESCRIPTION
**Pull request by mijovic**
Part of #9714

Fixes #10115 
Fixes #10118

### CODE REVIEW

File: libsolidity/codegen/ir/IRGenerator.cpp [hunk 1]
```diff
@@ -382,34 +382,53 @@ string IRGenerator::generateGetter(VariableDeclaration const& _varDecl)
...
 				code += Whiskers(R"(
 					<ret> := <readStorage>(add(slot, <slotOffset>))
 				)")
 				("ret", joinHumanReadable(retVars))
-				("readStorage", m_utils.readFromStorage(*returnTypes[i], offsets.second, true))
+				(
+					"readStorage",
+					arrayType ?
+						m_utils.copyArrayFromStorageToMemoryFunction(
+							dynamic_cast<ArrayType const&>(*arrayType->copyForLocation(DataLocation::Storage, arrayType->isPointer())),
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGenerator.cpp]: Can you set the pointer arguments to true/false? Does it matter?

Comment (mijovic) [reply libsolidity/codegen/ir/IRGenerator.cpp]: It doesn't meter and shouldn't make any difference in this case.
Also second one shouldn't be used with `copyForLocation` as it should already be correct type (it comes from `returnTypes`)

Will change this at both occurrences now

File: libsolidity/codegen/ir/IRGenerator.cpp [hunk 2]
```diff
@@ -382,34 +382,53 @@ string IRGenerator::generateGetter(VariableDeclaration const& _varDecl)
 			{
 				if (returnTypes[i]->category() == Type::Category::Mapping)
 					continue;
-				if (auto arrayType = dynamic_cast<ArrayType const*>(returnTypes[i]))
+				auto const* arrayType = dynamic_cast<ArrayType const*>(returnTypes[i]);
+				if (arrayType)
 					if (!arrayType->isByteArray())
 						continue;
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGenerator.cpp]:
```suggestion
				if (arrayType && !arrayType->isByteArray())
					continue;
```

File: libsolidity/codegen/ir/IRGenerator.cpp [hunk 3]
```diff
@@ -382,34 +382,53 @@ string IRGenerator::generateGetter(VariableDeclaration const& _varDecl)
...
 		else
 		{
 			solAssert(returnTypes.size() == 1, "");
+			auto const* arrayType = dynamic_cast<ArrayType const*>(returnTypes.front());
+			if (arrayType)
+				solAssert(arrayType->isByteArray(), "");
 			vector<string> retVars = IRVariable("ret", *returnTypes.front()).stackSlots();
 			returnVariables += retVars;
-			// TODO conversion from storage byte arrays is not yet implemented.
 			code += Whiskers(R"(
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGenerator.cpp:540]: Maybe it would be better to use different templates for arrays and non-arrays?

Comment (mijovic) [reply libsolidity/codegen/ir/IRGenerator.cpp:540]: Or maybe calling it from `readFromStorageReferenceType`, so we do not add anything here.
That way it activates more tests as well, and implements more features we are missing

File: test/libsolidity/semanticTests/array/copying/storage_memory_nested_struct.sol [hunk 4]
```diff
@@ -2,25 +2,23 @@ contract C {
...
         a[1][2].y = 22;
         a[1][2].z.push(4);
-        a[1][2].z.push(5);
-        a[1][2].z.push(6);
         T[3][] memory m = a;
         return (
-            m[0][1].x, m[0][1].y, m[0][1].z[0], m[0][1].z[1], m[0][1].z[2],
-            m[1][2].x, m[1][2].y, m[1][2].z[0], m[1][2].z[1], m[1][2].z[2]
+            m[0][1].x, m[0][1].y, m[0][1].z[0],
+            m[1][2].x, m[1][2].y, m[1][2].z[0]
```
Comment (mijovic) [inline test/libsolidity/semanticTests/array/copying/storage_memory_nested_struct.sol:21]: It was generating Stack too deep error, I needed to simplify test a bit in order to make it work via yul

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 5]
```diff
@@ -2167,8 +2167,26 @@ string YulUtilFunctions::readFromStorage(Type const& _type, size_t _offset, bool
...
 string YulUtilFunctions::readFromStorageDynamic(Type const& _type, bool _splitFunctionTypes)
 {
-	solAssert(_type.isValueType(), "");
-	return readFromStorageValueType(_type, {}, _splitFunctionTypes);
+	if (_type.isValueType())
+		return readFromStorageValueType(_type, {}, _splitFunctionTypes);
+	string functionName =
+		"read_from_storage__dynamic_" +
+		string(_splitFunctionTypes ? "split" : "") +
+		"_" +
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
		string(_splitFunctionTypes ? "split_" : "") +
```

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 6]
```diff
@@ -2211,7 +2229,12 @@ string YulUtilFunctions::readFromStorageValueType(Type const& _type, optional<si
 
 string YulUtilFunctions::readFromStorageReferenceType(Type const& _type)
 {
-	solUnimplementedAssert(_type.category() == Type::Category::Struct, "");
+	if (auto const* arrayType = dynamic_cast<ArrayType const*>(&_type))
+		return copyArrayFromStorageToMemoryFunction(
+			dynamic_cast<ArrayType const&>(*arrayType->copyForLocation(DataLocation::Storage, false)),
+			*arrayType
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:2340]: Why do you know that arrayType is in memory? Shouldn't it rather be in storage?

File: libsolidity/codegen/ir/IRGenerator.cpp (hunk 3 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGenerator.cpp:540]: Sounds good!

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 7]
```diff
@@ -2167,8 +2167,26 @@ string YulUtilFunctions::readFromStorage(Type const& _type, size_t _offset, bool
 
 string YulUtilFunctions::readFromStorageDynamic(Type const& _type, bool _splitFunctionTypes)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:2272]: I'm a bit worried that this might lead to unnecessary copies from storage to memory. Can you check that it is always used properly?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2272]: I saw some code in the form of
```
			structMembers[i].type->isValueType() ?
				readFromStorageDynamic(*structMembers[i].type, true) :
				readFromStorage(*structMembers[i].type, memberStorageOffset, true)
```
Can this now be simplified?

**Review by chriseth — CHANGES_REQUESTED** [review]

**Comment by chriseth** [comment]
I think the worry in https://github.com/ethereum/solidity/pull/10552#discussion_r540188354 is ungrounded.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 7 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:2272]: It can be simplified, yes. Will do it

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 6 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:2340]: This should be type to what we are trying to read, which is a bit misleading. I should:
1. rename function to have better name, as this is basically copying from storage to memory for reference types
2. add additional argument to have `_fromType` and `_toType`

Sounds fine?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2340]: If it works then it's fine.

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2340]: But maybe add an assertion here to make it explicit? I know there is an assertion in the called function, but still.

**Comment by mijovic** [comment]
> I think the worry in [#10552 (comment)](https://github.com/ethereum/solidity/pull/10552#discussion_r540188354) is ungrounded.

I was thinking about this before I started adding this copy. I think it is not going to happen in current use. But, if someone calls function in some other place, it can happen that he doesn't expect copy to happen... But I guess we will be careful with that.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 6 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:2340]: Added additional assertion

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 7 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:2272]: Can be simpler, but point was that in dynamic we have additional check (if offset is 0 it will call panic()). So, In simpler version it look nicer, but it will have this check which probably optimizer can remove.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 8]
```diff
@@ -2222,24 +2247,20 @@ string YulUtilFunctions::readFromStorageReferenceType(Type const& _type)
 	for (size_t i = 0; i < structMembers.size(); ++i)
 	{
 		auto const& [memberSlotDiff, memberStorageOffset] = structType.storageOffsetsOfMember(structMembers[i].name);
+		solAssert(structMembers[i].type->isValueType() || memberStorageOffset == 0, "");
```
Comment (mijovic) [inline libsolidity/codegen/YulUtilFunctions.cpp:2354]: Added assertion, to have it here as well. Probably it is done in many other places, but it was missing here

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 9]
```diff
@@ -2222,24 +2247,20 @@ string YulUtilFunctions::readFromStorageReferenceType(Type const& _type)
...
 
 		memberSetValues[i]["setMember"] = Whiskers(R"(
 			{
-				let <memberValues> := <readFromStorage>(add(slot, <memberSlotDiff>)<?hasOffset>, <memberStorageOffset></hasOffset>)
+				let <memberValues> := <readFromStorage>(add(slot, <memberSlotDiff>), <memberStorageOffset>)
 				<writeToMemory>(add(value, <memberMemoryOffset>), <memberValues>)
```
Comment (mijovic) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Thinking about this. 
What happens is that `readFromStorage` copies from storage to memory in newly allocated space.
Than `writeToMemory` copies it to another location in memory.

Instead of doing this, I think it will be better to do direct copy to the desired location in memory to remove unnecessary copies.

I can do it in a separate PR, as this wasn't really scope of this one.

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Not true. For value types it is fine, and for reference it will just store reference, so we can ignore my concern here :-)

**Comment by mijovic** [comment]
Rebased and activated 2 more tests via yul. Should be ready for review again.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 10]
```diff
@@ -2326,24 +2351,20 @@ string YulUtilFunctions::readFromStorageReferenceType(Type const& _type)
...
 		("memberValues", suffixedVariableNameList("memberValue_", 0, structMembers[i].type->stackItems().size()))
 		("memberMemoryOffset", structType.memoryOffsetOfMember(structMembers[i].name).str())
 		("memberSlotDiff",  memberSlotDiff.str())
 		("memberStorageOffset", to_string(memberStorageOffset))
-		("readFromStorage",
-			structMembers[i].type->isValueType() ?
-				readFromStorageDynamic(*structMembers[i].type, true) :
-				readFromStorage(*structMembers[i].type, memberStorageOffset, true)
-		)
+		("readFromStorage", readFromStorageDynamic(*structMembers[i].type, true))
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Shouldn't we keep the static read?

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 10 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Added back static read

**Review by chriseth — DISMISSED** [review]

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 11]
```diff
@@ -2337,10 +2363,11 @@ string YulUtilFunctions::readFromStorageReferenceType(Type const& _type)
 		("memberMemoryOffset", structType.memoryOffsetOfMember(structMembers[i].name).str())
 		("memberSlotDiff",  memberSlotDiff.str())
 		("memberStorageOffset", to_string(memberStorageOffset))
-		("readFromStorage",
+		(
+			"readFromStorage",
 			structMembers[i].type->isValueType() ?
-				readFromStorageDynamic(*structMembers[i].type, true) :
-				readFromStorage(*structMembers[i].type, memberStorageOffset, true)
+			readFromStorageDynamic(*structMembers[i].type, true) :
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Actually I realized that it's the other way round: We can profit from the static read only for value types, since offset is zero for non-value types anyway. So Could you change this such that it directly calls `YulUtilFunctions::readFromStorageValueType` with a static offset?

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: True that. If I just call `readFromStorage` in both cases, it should call `readFromStorageValueType` for value types. So I think it is better now.

**Review by chriseth — APPROVED** [review]
