### PR TITLE
[SMTChecker] Refactor VariableUsage

### LINKED ISSUE #5903: SMTCheck throw exception
## Description

I ran solc with Z3 and CVC4 installed on some contracts including the rubixi contract(in myth_solidity_examples ), 

    solc rubixi.sol 
returns:

    Internal compiler error during compilation:
    solidity/libsolidity/formal/SMTChecker.cpp(1240): Throw in function void dev::solidity::SMTChecker::mergeVariables(const std::vector<const dev::solidity::VariableDeclaration*>&, const dev::solidity::smt::Expression&, const VariableIndices&, const VariableIndices&)
    Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
    std::exception::what:
    [dev::tag_comment*] =

## Environment

- Compiler version:Version: 0.5.4-develop.2019.1.26+commit.628d6654.mod.Linux.g++ 
- Target EVM version (as per compiler settings):default 
- Framework/IDE (e.g. Truffle or Remix): command line solc 
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 18.04.1 LTS 

## Steps to Reproduce

1. Download contracts from 
https://github.com/ConsenSys/mythril-classic/tree/develop/solidity_examples 
2. change the first line to "pragma solidity ^0.5.0;", append 
"pragma experimental SMTChecker; " before the first line.
3. run solc rubixi.sol or solc BECToken.sol or solc weak_random.sol

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #5903 

The previous `VariableUsage` class pre-processed the AST in its constructor to keep only paths to nodes that touched variables. When adding support to modifier inlining, it got too complicated to keep the state and know what's happening when a `PlaceholderStatement` is visited.
This PR refactors `VariableUsage` as a simple visitor that inlines function calls and modifiers following the same rules as the SMTChecker. It is of course slower than the previous `VariableUsage`, but less complicated to deal with (in my opinion).

The added tests were leading to ICEs due to the latest PR on `VariableUsage` that added function call inlining. This PR also fixes that. The tests were simplified versions of `rubixi.sol` from #5903.

Maybe a future refactor can be done where the class `SMTChecker` derives from `VariableUsage` and we can use shared visitor functions.

### CODE REVIEW

File: libsolidity/formal/VariableUsage.cpp [hunk 1]
```diff
@@ -42,6 +42,15 @@ VariableUsage::VariableUsage(ASTNode const& _node)
...
 				m_children[&n].push_back(funDef);
 		}
+		else if (auto modifierInv = dynamic_cast<ModifierInvocation const*>(&n))
+		{
+			// TODO Calls to constructors of base classes also go in here.
+			auto modifierDef = dynamic_cast<ModifierDefinition const*>(
+				modifierInv->name()->annotation().referencedDeclaration
+			);
+			if (modifierDef)
+				m_children[&n].push_back(modifierDef);
```
Comment (chriseth) [inline libsolidity/formal/VariableUsage.cpp]: "else: not supported"?

Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.cpp]: will add on the SMTChecker side

Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.cpp]: Actually, the SMTChecker already says that constructors are not supported, which would be reached in that case.

Comment (chriseth) [reply libsolidity/formal/VariableUsage.cpp]: Ok!

**Comment by chriseth** [comment]
Is this ready for review or still work in progress?

**Comment by leonardoalt** [comment]
In progress.

**Comment by leonardoalt** [comment]
@chriseth ready for review. Please re-read the first comment.

File: libsolidity/formal/SMTChecker.cpp [hunk 2]
```diff
@@ -1497,7 +1491,7 @@ void SMTChecker::resetStorageReferences()
 	resetVariables([&](VariableDeclaration const& _variable) { return _variable.hasReferenceOrMappingType(); });
 }
 
-void SMTChecker::resetVariables(vector<VariableDeclaration const*> _variables)
+void SMTChecker::resetVariables(set<VariableDeclaration const*> _variables)
```
Comment (ekpyron) [inline libsolidity/formal/SMTChecker.cpp]:
```suggestion
void SMTChecker::resetVariables(set<VariableDeclaration const*> const& _variables)
```

**Review by ekpyron — CHANGES_REQUESTED** [review]
Haven't reviewed everything yet, but at least one change:

File: libsolidity/formal/SMTChecker.cpp (hunk 2 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTChecker.cpp]: Updated

File: libsolidity/formal/SMTChecker.cpp [hunk 3]
```diff
@@ -272,17 +270,13 @@ bool SMTChecker::visit(ForStatement const& _node)
...
 	// Do not reset the init expression part.
-	auto touchedVariables =
-		m_variableUsage->touchedVariables(_node.body());
+	auto touchedVars = touchedVariables(_node.body());
 	if (_node.condition())
-		touchedVariables += m_variableUsage->touchedVariables(*_node.condition());
+		touchedVars += touchedVariables(*_node.condition());
 	if (_node.loopExpression())
-		touchedVariables += m_variableUsage->touchedVariables(*_node.loopExpression());
-	// Remove duplicates
```
Comment (leonardoalt) [inline libsolidity/formal/SMTChecker.cpp:281]: `touchedVars` is a `set` now instead of a `vector`

File: libsolidity/formal/VariableUsage.cpp [hunk 4]
```diff
@@ -19,72 +19,61 @@
...
+			m_touchedVariables.insert(varDecl);
 }
 
-vector<VariableDeclaration const*> VariableUsage::touchedVariables(ASTNode const& _node) const
+void VariableUsage::endVisit(FunctionCall const& _funCall)
 {
-	if (!m_children.count(&_node) && !m_touchedVariable.count(&_node))
-		return {};
+	if (auto const& funDef = SMTChecker::inlinedFunctionCallToDefinition(_funCall))
+		if (find(m_functionPath.begin(), m_functionPath.end(), funDef) == m_functionPath.end())
```
Comment (ekpyron) [inline libsolidity/formal/VariableUsage.cpp:40]: This ensures that this terminates if e.g. ``f`` calls ``g`` and ``g`` calls ``f`` back, right?

**Review by ekpyron — DISMISSED** [review]
I *think* this is fine!

File: libsolidity/formal/SMTChecker.cpp (hunk 3 above)
Comment (ekpyron) [reply libsolidity/formal/SMTChecker.cpp:281]: Yep - first time I felt with @chriseth complaining about ``auto`` :-)

File: libsolidity/formal/VariableUsage.cpp (hunk 4 above)
Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.cpp:40]: Yep, that's the idea

Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.cpp:40]: Hmmmm but maybe we should pass the entire call stack from the SMTChecker to VariableUsage to have the exact same behavior

Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.cpp]: Ok done

Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.cpp:40]: Ok done

File: libsolidity/formal/VariableUsage.h [hunk 5]
```diff
@@ -17,33 +17,35 @@
...
+ * This class computes information about which variables are modified in a certain subtree.
  */
-class VariableUsage
+class VariableUsage: private ASTConstVisitor
 {
 public:
-	explicit VariableUsage(ASTNode const& _node);
-
-	std::vector<VariableDeclaration const*> touchedVariables(ASTNode const& _node) const;
+	/// @param _outerFunction the function where the current control-flow is in.
```
Comment (ekpyron) [inline libsolidity/formal/VariableUsage.h]:
```suggestion
	/// @param _outerFunction the function which contains the current control-flow.
```
:-D - but nevermind that :-D.

So do I understand this correctly in that it would have worked and terminated before, but now it possibly does sooner, since roughly speaking I pass along half of a possibly round-trip that I'd otherwise have had to walk again? If so, I still think this is fine and better now, yeah!

**Review by ekpyron — DISMISSED** [review]

**Review by ekpyron — DISMISSED** [review]

File: libsolidity/formal/VariableUsage.h (hunk 5 above)
Comment (leonardoalt) [reply libsolidity/formal/VariableUsage.h]: Fixed

**Comment by leonardoalt** [comment]
@ekpyron added test

**Review by ekpyron — APPROVED** [review]
