### PR TITLE
Do not run SMTChecker when file level functions/constants are present.

### LINKED ISSUE #10461: [SMTChecker] ICE in solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
	function f() view {}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(722): Throw in function void solidity::frontend::SMTEncoder::initFunction(const solidity::frontend::FunctionDefinition &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

This is similar to some older initFunction crashes that required more complex inputs.  Must be some newly introduced issue that lacks a detecting test for this simple a variant.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### LINKED ISSUE #10502: 2 Compiler Errors in solc 0.7.5 version, triggered by three contracts
## Description

Hello to everyone, I found 2 unique crashes, triggered by four solidity contracts in solc compiler version 0.7.5 that Superion, AFL and Mopt could not found .

1. Internal Compiler error in :

https://github.com/ethereum/solidity/blob/afe500e399e76ce88c9dadfd04b616bd5df47c37/libsolidity/formal/SMTEncoder.cpp#L722

"Triggered" by contracts (a), (b), (c) :

(a)
pragma experimental SMTChecker;	function f()pure {
		ufixed a = uint64(1) + ufixed(2);
}

(b)
pragma experimental SMTChecker;

contract K {}
	function f() pure {
		(abi.encode, "");
}

(c)

pragma experimental SMTChecker;
contract C {
	function f(bytes calldata x, uint y) external pure {
		x[8][0];
		x[8][5*y];
	}
}

2. Internal Compiler Error :
Unknown exception during compilation: stoul, out of range.

"Triggered" by contract :

pragma experimental SMTChecker;
contract C {
	function f(bytes calldata x, uint y) external pure {
		x[8][0];
		x[8][5*y];
	}
}

## Environment

- Compiler version: 0.7.5
- Target EVM version (as per compiler settings): 0.7.5+commit.eb77ed08
- Framework/IDE (e.g. Truffle or Remix): Remix
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 16.04 Xenial

## Steps to Reproduce

solc <contract_number>

### LINKED ISSUE #10521: [SMTChecker] ICE in const solidity::frontend::VariableDeclaration *solidity::frontend::SMTEncoder::identifierToVariable(const solidity::frontend::Expression &) const
## Description

This contract:
```solidity
pragma experimental SMTChecker;
uint256 constant x = 56;
enum ActionChoices {GoLeft, GoRight, GoStraight, Sit}
ActionChoices constant choices = ActionChoices.GoRight;
bytes32 constant st = "abc\x00\xff__";
contract C {
    function i() public returns (uint, ActionChoices, bytes32) {
	return (x, choices, st);
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(2386): Throw in function const solidity::frontend::VariableDeclaration *solidity::frontend::SMTEncoder::identifierToVariable(const solidity::frontend::Expression &) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

```

when compiled with solc.

On master, using AFL fuzzing.  **Another discovery using https://github.com/agroce/afl-compiler-fuzzer,  a bit indirectly:  I took every test in my corpus I use to start fuzzing, and add the SMT checker pragma to any that lacked it, then ran triage and minimized the tests (so they aren't exactly the corpus tests + SMT checker pragma).  I think I have quite a few bugs to report here, and it might be a good idea to add something to automatically do this to tests!**

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### LINKED ISSUE #10526: [SMTChecker] Segmentation fault for solc and solfuzzer in solidity::frontend::CHC::internalFunctionCall
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    uint[] data;
    function f(uint x, uint[] calldata input) public returns (uint, uint) {
        (uint a, uint[] calldata b) = fun(input, data);
    }
}
function fun(uint[] calldata _x, uint[] storage _y) view  returns (uint, uint[] calldata) {
	return (_y[0], _x);
}
```

produces:

```
Segmentation fault
```

gdb claims it's here:
```
Program received signal SIGSEGV, Segmentation fault.
solidity::frontend::CHC::internalFunctionCall (this=0x7ffe15cd9be0, _funCall=...) at /home/user/solidity/libsolidity/formal/CHC.cpp:561
561			if (contract->isLibrary())
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.  Again, indirectly via adding SMTChecker pragmas to existing tests, then triaging/reducing.

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/10502
Fixes https://github.com/ethereum/solidity/issues/10526
Fixes https://github.com/ethereum/solidity/issues/10461
Fixes https://github.com/ethereum/solidity/issues/10521

This does not support free functions/constants, but fails with a warning instead of exception/crash.
I added all the tests mentioned in the issues above.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -40,6 +40,38 @@ SMTEncoder::SMTEncoder(smt::EncodingContext& _context):
...
+	for (auto const& source: _source.referencedSourceUnits(true))
+		sources.insert(source);
+
+	bool analysis = true;
+	for (auto source: sources)
+		for (auto node: source->nodes())
+			if (auto function = dynamic_pointer_cast<FunctionDefinition>(node))
+			{
+				m_errorReporter.warning(
+					6660_error,
```
Comment (axic) [inline libsolidity/formal/SMTEncoder.cpp:56]: Woot.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:56]: Even looks like I did it manually ;)

**Review by axic — DISMISSED** [review]
Looks good to me, is there any other issue/test case we missed?

**Review by bshastry — DISMISSED** [review]
LGTM too.

**Comment by leonardoalt** [comment]
> Looks good to me, is there any other issue/test case we missed?

I went through the SMTChecker project, issue list, and referenced issues, so hopefully not.

**Comment by leonardoalt** [comment]
Wait there are a bunch of tests missing

**Comment by leonardoalt** [comment]
Forgot to push some other tests, just pushed them

**Comment by leonardoalt** [comment]
@axic @bshastry can you approve again?

**Review by bshastry — APPROVED** [review]
