### PR TITLE
[SMTChecker] Fix ICEs with tuples

### LINKED ISSUE #8405: [SMTChecker] SMTEncoder throws ICE when m_context.knownExpression(*tComponent) is nullptr
## Description

```
pragma experimental SMTChecker;

contract K{function f()public{(abi.encode,(""));}}
```

throws

https://github.com/ethereum/solidity/blob/b65a165da19f150fbff39eac08729da72e4216c3/libsolidity/formal/SMTEncoder.cpp#L422

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): NA

## Steps to Reproduce

With solc linked against z3,

```
$ solc <input.sol>
Internal compiler error during compilation:
/home/bhargava/work/github/solidity/libsolidity/formal/SMTEncoder.cpp(422): Throw in function virtual void solidity::frontend::SMTEncoder::endVisit(const solidity::frontend::TupleExpression &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

### LINKED ISSUE #8407: [SMTChecker] ICE in SMTEncoder because "symbComponents.size() == _tuple.components().size()" fails
## Description

```
pragma experimental SMTChecker;
contract C {
  function f() public {
    (("",""));
  }
}
```

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): NA

## Steps to Reproduce

With solc linked against z3,

```
$ solc <input.sol>
Internal compiler error during compilation:
/home/bhargava/work/github/solidity/libsolidity/formal/SMTEncoder.cpp(411): Throw in function virtual void solidity::frontend::SMTEncoder::endVisit(const solidity::frontend::TupleExpression &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/8405
Fixes https://github.com/ethereum/solidity/issues/8407

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -407,19 +407,25 @@ void SMTEncoder::endVisit(TupleExpression const& _tuple)
 		auto const& symbTuple = dynamic_pointer_cast<smt::SymbolicTupleVariable>(m_context.expression(_tuple));
 		solAssert(symbTuple, "");
 		auto const& symbComponents = symbTuple->components();
-		auto const& tupleComponents = _tuple.components();
-		solAssert(symbComponents.size() == _tuple.components().size(), "");
+		auto const* tupleComponents = &_tuple.components();
+		while (tupleComponents->size() == 1)
+		{
+			auto singleTuple = dynamic_pointer_cast<TupleExpression>(tupleComponents->front());
```
Comment (ekpyron) [inline libsolidity/formal/SMTEncoder.cpp]: What if the single tuple element is not itself a tuple? Should this rather e.g. be
```suggestion
			if (auto const* singleTuple = dynamic_cast<TupleExpression const*>(tupleComponents->front().get()))
				tupleComponents = &singleTuple->components();
			else
				break;
```
or something like that?

Do you have a test case like
```
pragma experimental SMTChecker;

contract C {
	function f() public pure {
		(2);
	}
}
```
and won't that throw in the next line, since ``singleTuple`` will be ``nullptr``?

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: In that case the type of the tuple is actually the type of the inner expression, so it still works. Added an assertion and the test.

**Review by ekpyron — APPROVED** [review]
