### PR TITLE
Silence implicit fallthrough warning

### LINKED ISSUE #2344: Implicit fallthrough warning on GCC 7.x
Which version of Solidity you are using
> HEAD of develop branch (commit b4ae188a)

What was the source code (if applicable)
> solidity/libsolidity/codegen/CompilerUtils.cpp:784

```cpp
case Type::Category::Function:
	{
		if (targetTypeCategory == Type::Category::Integer)
		{
			IntegerType const& targetType = dynamic_cast<IntegerType const&>(_targetType);
			solAssert(targetType.isAddress(), "Function type can only be converted to address.");
			FunctionType const& typeOnStack = dynamic_cast<FunctionType const&>(_typeOnStack);
			solAssert(typeOnStack.kind() == FunctionType::Kind::External, "Only external function type can be converted.");

			// stack: <address> <function_id>
			m_context << Instruction::POP;
			break;
		}
	}
	default:
             ...
```

Which platform are you running on
> Arch Linux (Kernel 4.10.11-1), g++ (GCC) 7.1.1 20170516, cmake version 3.8.0

How to reproduce the issue
> `git submodule update --init && ./scripts/install_deps.sh && ./scripts/build.sh`
> On my arch linux, the script `./scripts/install_deps.sh` can't work, so I install dependencies manually.

What was the result of the issue
> 
```
[ 39%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/CompilerUtils.cpp.o
/home/wangwangwar/code/Compiler/solidity/libsolidity/codegen/CompilerUtils.cpp: 在成员函数‘void dev::solidity::CompilerUtils::convertType(const dev::solidity::Type&, const dev::solidity::Type&, bool, bool)’中:
/home/wangwangwar/code/Compiler/solidity/libsolidity/codegen/CompilerUtils.cpp:784:3: 错误：this statement may fall through [-Werror=implicit-fallthrough=]
   }
   ^
/home/wangwangwar/code/Compiler/solidity/libsolidity/codegen/CompilerUtils.cpp:786:2: 附注：here
  default:
  ^~~~~~~
cc1plus：所有的警告都被当作是错误
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/build.make:543：libsolidity/CMakeFiles/solidity.dir/codegen/CompilerUtils.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:275：libsolidity/CMakeFiles/solidity.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
```

What the expected behaviour is
> Compile successfully.

### PR DESCRIPTION
**Pull request by LefterisJP**
Fixes #2344.

In my system I have gcc 7.1.1 and there I get a lot of warnings which
fail the build due to implicit fallthroughs in switch statements.

Some examples can be seen here:
https://gist.github.com/LefterisJP/388c3ba5ad356f92a3b44e7efed89f9f

This PR proposes a simple solution, which is to ignore the warning for
both gcc and clang since implici fallthrough is actively used in the codebase and don;t know of a way to locally ignore it on a case by case basis.

### CODE REVIEW

**Review by chriseth — CHANGES_REQUESTED** [review]
I'm not in favour of disabling warnings. How many of them are there? I think there are portable ways to decorate intentional fall-throughs.

**Comment by LefterisJP** [comment]
@chriseth 

I am also not in favour of disabling them but this is the easiest solution that I used locally (to have solc again) temporarily until I bring the matter to your attention.

>  How many of them are there? 

There were quite a few cases.

There is no standard way to disable them locally. According to [this](https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/) we can use the following non-standard ways:

```c++
switch (cond)
 {
 case 1:
   bar (1);
   __attribute__ ((fallthrough)); // C and C++03
 case 2:
   bar (2);
   [[gnu::fallthrough]]; // C++11 and C++14
 case 3:
   bar (3);
   [[fallthrough]]; // C++17 and above
 /* ... */
 }
```

You can also tweak the level of fallthrough ranging from `-Wimplicit-fallthrough=0` to `-Wimplicit-fallthrough=3`.

I am not sure what you guys think is the best for the codebase as it stands now but I suggest having a look at the aforementioned article and taking a decision depending on the seriousness (or lack of) of the places where the warning hits.

**Comment by LefterisJP** [comment]
@chriseth I opted for the C++03 way as per our discussion. Let's hope all the tests pass.

**Comment by chriseth** [comment]
It seems the compilers do not accept it. I read in some non-standard documents that this is part of C++03, but perhaps that is wrong?

**Comment by axic** [comment]
Since we only have two such cases, would it make sense reordering the code so that it is not falling through?

**Comment by chriseth** [comment]
If there are only two, then yes, indeed.

**Comment by axic** [comment]
@LefterisJP would you be able to do the change above?

**Comment by chriseth** [comment]
Refactored the code.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 1]
```diff
@@ -769,9 +769,9 @@ void CompilerUtils::convertType(Type const& _typeOnStack, Type const& _targetTyp
 		if (_cleanupNeeded)
 			m_context << Instruction::ISZERO << Instruction::ISZERO;
 		break;
-	case Type::Category::Function:
+	default:
 	{
-		if (targetTypeCategory == Type::Category::Integer)
+		if (stackTypeCategory == Type::Category::Function)
```
Comment (axic) [inline libsolidity/codegen/CompilerUtils.cpp]: I think this should be `stackTypeCategory == Type::Category::Function && targetTypeCategory == Type::Category::Integer` as it checks for function type to address conversion.

Well with the new version it will raise `Function type can only be converted to address` if assigning to int, while other the more vague `Invalid type conversion requested`.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 2]
```diff
@@ -780,10 +780,8 @@ void CompilerUtils::convertType(Type const& _typeOnStack, Type const& _targetTyp
 
 			// stack: <address> <function_id>
 			m_context << Instruction::POP;
-			break;
+			// "fall-through"
```
Comment (axic) [inline libsolidity/codegen/CompilerUtils.cpp]: This should not fall through if conversion succeeded.

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 3]
```diff
@@ -1008,61 +1008,65 @@ bool ExpressionCompiler::visit(MemberAccess const& _memberAccess)
...
-		else if ((set<string>{"send", "transfer", "call", "callcode", "delegatecall"}).count(member))
-			utils().convertType(
-				*_memberAccess.expression().annotation().type,
-				IntegerType(0, IntegerType::Modifier::Address),
-				true
-			);
-		else
-			BOOST_THROW_EXCEPTION(InternalCompilerError() << errinfo_comment("Invalid member access to integer."));
-		break;
+	switch (_memberAccess.expression().annotation().type->category())
```
Comment (axic) [inline libsolidity/codegen/ExpressionCompiler.cpp]: This could also use `expressionTypeCategory` from above or is that to the deteriment of readability?

**Comment by chriseth** [comment]
@axic these changes really look dangerous. I think we should just disable the warning until we have  gcc7 as part of our CI.

**Comment by LefterisJP** [comment]
I tend to agree. I would do the following:

1. Disable the warning with this PR.
2. Create a new issue as a followup detailing that these particular code points need to be refactored and the warning re-enabled.

**Comment by chriseth** [comment]
@LefterisJP if you could do that, this would be wonderful!

**Review by chriseth — APPROVED** [review]
