### PR TITLE
Fix exponentiation bug

### LINKED ISSUE #8297: ICE in solidity::u256 solidity::frontend::RationalNumberType::literalValue
## Description

This contract:
```solidity
contract c {
    function f() public pure {
        int a;
             a** 1E1233;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.cpp(1177): Throw in function virtual solidity::u256 solidity::frontend::RationalNumberType::literalValue(const solidity::frontend::Literal *) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Number constant too large.
[solidity::util::tag_comment*] = Number constant too large.
```

when run with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer

## Environment

- Compiler version:  0.6.3-develop.2020.2.10+commit.e8eb1f2d.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### LINKED ISSUE #8929: [solc] ICE because exponent too large
## Description

```
contract C {
  int x = type(int).min ** 3e635;
}
```

throws

https://github.com/ethereum/solidity/blob/b2122d479fc0554a9506f4e393fe95aa52f503d3/libsolidity/ast/Types.cpp#L1196

Fixed by https://github.com/ethereum/solidity/pull/8903

## Environment

- Compiler version: latest develop

## Steps to reproduce

```
$ solc <input.sol>
```

### PR DESCRIPTION
**Pull request by hrkrshnn**
Closes https://github.com/ethereum/solidity/issues/8297
Closes https://github.com/ethereum/solidity/issues/8929

Issues an error saying literal too large if the exponent in the `**` operation is too big for the result type.

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `622d0b7c78d2b6cdeb1a8f05ba3050c337497710`:
```
Coding style error:
 libsolidity/analysis/TypeChecker.cpp:1600: if(

```
Please check that your changes are working as intended.

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1596,6 +1596,32 @@ void TypeChecker::endVisit(BinaryOperation const& _operation)
 					"might overflow. Silence this warning by converting the literal to the "
 					"expected type."
 				);
+
+		if(
```
Comment (stackenbotten) [inline libsolidity/analysis/TypeChecker.cpp:1600]: Coding style error

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -1596,6 +1596,32 @@ void TypeChecker::endVisit(BinaryOperation const& _operation)
 					"might overflow. Silence this warning by converting the literal to the "
 					"expected type."
 				);
+
+		if (
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Can this move to `IntegerType::binaryOperatorResult`?

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -613,6 +613,19 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
 		}
 		else if (dynamic_cast<FixedPointType const*>(_other))
 			return nullptr;
+		else if (
+			auto rationalNumberType = dynamic_cast<RationalNumberType const*>(_other);
+			rationalNumberType
+		)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]:
```suggestion
		else if (auto rationalNumberType = dynamic_cast<RationalNumberType const*>(_other))
```

File: libsolidity/ast/Types.cpp [hunk 4]
```diff
@@ -613,6 +613,19 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
...
+		{
+			IntegerType const* integerType = rationalNumberType->integerType();
+			if (
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Does this not fit a line?

File: libsolidity/ast/Types.cpp [hunk 5]
```diff
@@ -613,6 +613,19 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
...
+				!integerType ||
+				integerType->numBits() >
+				numBits()
+			)
+				return TypeResult::err("The exponent is too large.");
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]:
```suggestion
				return TypeResult::err("Exponent too large.");
```

File: libsolidity/ast/Types.cpp [hunk 6]
```diff
@@ -613,6 +613,19 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
...
 			return nullptr;
+		else if (
+			auto rationalNumberType = dynamic_cast<RationalNumberType const*>(_other);
+			rationalNumberType
+		)
+		{
+			IntegerType const* integerType = rationalNumberType->integerType();
+			if (
+				!integerType ||
+				integerType->numBits() >
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I think the first condition is enough, at least the second condition is not grounded on anything. For non-literals, we make no restrictions on the number of bits, for example.

Comment (hrkrshnn) [reply libsolidity/ast/Types.cpp]: @chriseth Don't you think code like this should be dissallowed?
```solidity
contract C {
	function f(uint8 x) public pure {
		x = x ** 1E5;
	}
}
```

Comment (chriseth) [reply libsolidity/ast/Types.cpp]: I'm just saying we should be consistent.

File: libsolidity/ast/Types.cpp [hunk 7]
```diff
@@ -613,6 +613,9 @@ TypeResult IntegerType::binaryOperatorResult(Token _operator, Type const* _other
 		}
 		else if (dynamic_cast<FixedPointType const*>(_other))
 			return nullptr;
+		else if (auto rationalNumberType = dynamic_cast<RationalNumberType const*>(_other))
+			if (!rationalNumberType->integerType())
+				return TypeResult::err("Exponent too large.");
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:621]: Sorry to bother you again, but I think another reason for `integerType()` to return nullptr could be that the exponent is fractional: `x**(1/2)` - can you check, please?

Comment (hrkrshnn) [reply libsolidity/ast/Types.cpp:621]: Good point. `integerType()` would throw if fractional. I'll add a check and an error before.

File: Changelog.md [hunk 8]
```diff
@@ -19,6 +19,7 @@ Bugfixes:
  * Fixed an "Assembly Exception in Bytecode" error where requested functions were generated twice.
  * Natspec: Fixed a bug that ignored ``@return`` tag when no other developer-documentation tags were present.
  * Yul assembler: Fix source location of variable declarations without value.
+ * Type checker: Checks if the exponent in the ``**`` operation is too large or fractional.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Type checker: Checks if a literal exponent in the ``**`` operation is too large or fractional.
```

**Comment by chriseth** [comment]
Please squash!

**Comment by bshastry** [comment]
The fuzzer found a failing test case that this PR fixes :-) (see #8929 )

**Review by chriseth — APPROVED** [review]
