### PR TITLE
Prevent NameSimplifier and VarNameCleaner from producing Yul identifiers with leading and trailing dots

### LINKED ISSUE #11496: NameSimplifier sometimes produces invalid Yul code by leaving a trailing dot at the end of an identifier
```
{
  function f() -> u,Q {
    let j, r._ := f()
  }
  {
    let d, g := f()
  }
}
```

throws

https://github.com/ethereum/solidity/blob/7d8a4e63d84f548dbb3409f761fb2e92936c9057/libyul/AsmAnalysis.cpp#L93

To reproduce

```
$ solc --strict-assembly --optimize test.yul
```

### PR DESCRIPTION
**Pull request by clonker**
Fixes #11496

### CODE REVIEW

File: libyul/optimiser/OptimizerUtilities.cpp [hunk 1]
```diff
@@ -36,6 +36,16 @@ using namespace solidity::langutil;
 using namespace solidity::util;
 using namespace solidity::yul;
 
+namespace
+{
+
+bool hasLeadingOrTrailingDot(std::string_view const _s)
+{
+	return !_s.empty() && (_s.at(0) == '.' || _s.at(_s.size()-1) == '.');
```
Comment (nikola-matic) [inline libyul/optimiser/OptimizerUtilities.cpp]:
```suggestion
	return !_s.empty() && (_s.front() == '.' || _s.back() == '.');
```

Also, *technically*, `isRestrictedIdentifier` already checks for said empty identifier and short circuits in such a case, so I would go even further to reduce this and omit the empty check completely, and rather replace it with an assert.

```suggestion
	solAssert(!_s.empty());
	return _s.front() == '.' || _s.back() == '.';
```

File: test/cmdlineTests/yul_leading_or_trailing_dot_in_name/args
Comment (nikola-matic) [inline test/cmdlineTests/yul_leading_or_trailing_dot_in_name/args:1]: No need for a commandline test here, you can move it to `test/libyul/yulSyntaxTests`.

File: test/cmdlineTests/yul_leading_or_trailing_dot_in_name/input.yul [hunk 2]
```diff
@@ -0,0 +1,8 @@
+{
+  function f() -> u,Q {
+    let j, r._ := f()
```
Comment (nikola-matic) [inline test/cmdlineTests/yul_leading_or_trailing_dot_in_name/input.yul]: Should add a leading dot in the test case as well.

File: test/cmdlineTests/yul_leading_or_trailing_dot_in_name/args [hunk 3]
```diff
@@ -0,0 +1 @@
+--strict-assembly --optimize
```
Comment (cameel) [inline test/cmdlineTests/yul_leading_or_trailing_dot_in_name/args]: You could `--debug-info none` to remove the unnecessary debug comments from the output.

```suggestion
--strict-assembly --optimize --debug-info none
```

But I agree with @nikola-matic, a Yul syntax test is enough if you can repr

Also, the original issue says that `--optimize` is not necessary to trigger this. I suspect this is simply due to #13972, i.e. we run some minimal optimizations even when the optimizer is technically disabled. So it probably still makes sense to have it here to make it more explicit.

File: test/cmdlineTests/yul_leading_or_trailing_dot_in_name/input.yul (hunk 2 above)
Comment (cameel) [reply test/cmdlineTests/yul_leading_or_trailing_dot_in_name/input.yul]: I would just add the second repro: https://github.com/ethereum/solidity/issues/11496#issuecomment-1537917593.

File: test/cmdlineTests/yul_leading_or_trailing_dot_in_name/input.yul [hunk 4]
```diff
@@ -0,0 +1,8 @@
...
+  }
+  {
+    let d, g := f()
+  }
+}
```
Comment (cameel) [inline test/cmdlineTests/yul_leading_or_trailing_dot_in_name/input.yul]: It's best to clean up the repro a bit before adding it, as long as it does not interfere with the bug reproduction. Especially the repros from fuzzing are usually quite messy and don't follow our style.

```suggestion
{
    function f() -> u, q {
        let j, r._ := f()
    }
    let d, g := f()
}
```

I'd also remove any bits that are not relevant to reproduction, though this one looks fine in that regard.

**Review by cameel — COMMENTED** [review]
Also some general remarks:
- The PR is missing a changelog entry.
- When a PR fixes everything in the original issue you should use the github feature that will fix the issue automatically when the PR is merged. I.e. just add `Fixes #11496` in the PR description.
- I saw that the issue was moved to the 'In progress' column on the triage board. That column actually means that triage is progress :) It was added so that multiple people don't waste time triaging the same issue at the same time. The issues are only really meant to spent a short time there - triage never really takes all that long.

**Comment by cameel** [comment]
> - When a PR fixes everything in the original issue you should use the github feature that will fix the issue automatically when the PR is merged. I.e. just add `Fixes #11496` in the PR description.

Just noticed that you do have this but it's in the commit message. I'd recommend against it since this adds a lot of noise to the issue you mention this way - the commit appears there again and again each time you rebase the branch. It works much better when used in the PR instead.

File: test/cmdlineTests/yul_leading_or_trailing_dot_in_name/args (hunk 3 above)
Comment (clonker) [reply test/cmdlineTests/yul_leading_or_trailing_dot_in_name/args]: I could reproduce with a yul objectCompiler test, interestingly syntax test was not enough

File: test/libyul/objectCompiler/leading_and_trailing_dots.yul [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+//     /* "source":4:34   */
+// tag_1:
+//     /* "source":28:29   */
+//   0x00
+//     /* "source":26:30   */
+//   tag_1
+//   jump	// in
+// Bytecode: 60025b5f600256
+// Opcodes: PUSH1 0x2 JUMPDEST PUSH0 PUSH1 0x2 JUMP
+// SourceMappings: 39:1:0:-:0;4:30;28:1;26:4;:::i
```
Comment (nikola-matic) [inline test/libyul/objectCompiler/leading_and_trailing_dots.yul]: Newline

**Comment by clonker** [comment]
> Also some general remarks:
> 
> * The PR is missing a changelog entry.
> * When a PR fixes everything in the original issue you should use the github feature that will fix the issue automatically when the PR is merged. I.e. just add `Fixes #11496` in the PR description.
> * I saw that the issue was moved to the 'In progress' column on the triage board. That column actually means that triage is progress :) It was added so that multiple people don't waste time triaging the same issue at the same time. The issues are only really meant to spent a short time there - triage never really takes all that long.

Ahh I have misunderstood the "in progress" :) thanks for pointing that out!

File: test/libyul/objectCompiler/leading_and_trailing_dots.yul [hunk 6]
```diff
@@ -0,0 +1,20 @@
+{
+  function e(_._) {
+    e(0)
+  }
+  e(2)
```
Comment (cameel) [inline test/libyul/objectCompiler/leading_and_trailing_dots.yul]:
```suggestion
    function e(_._) {
        e(0)
    }
    e(2)
```

File: Changelog.md [hunk 7]
```diff
@@ -7,6 +7,7 @@ Compiler Features:
 
 
 Bugfixes:
+* Yul: NameSimplifier and VarNameCleaner steps could lead to forbidden identifiers with a leading and/or trailing dot, e.g., `let x._ := f()` would get simplified to `x.`.
```
Comment (cameel) [inline Changelog.md]: One odd quirk to be aware of is that for some odd reason we're using the RST double backticks instead of single ones in the changelog.

Also, `f()` does not seem relevant here so I'd remove it. We don't usually add examples in the changelog to keep it more concise. This one is short so I guess it's fine though.

Finally, is it both `NameSimplifier` and `VarNameCleaner` or just one of them? I put both in the PR name, because it touches a function used by both, but from the issue I got an impression that only `NameSimplifier` was affected. Maybe it would be best just not to mention the step by name. It's not even technically a step, just a part of the optimization process.

```suggestion
* Yul Optimizer: Name simplification could lead to forbidden identifiers with a leading and/or trailing dot, e.g., ``x._`` would get simplified into ``x.``.
```

**Review by nikola-matic — DISMISSED** [review]

File: Changelog.md (hunk 7 above)
Comment (clonker) [reply Changelog.md]: Yeah makes sense, this captures it better.

**Review by cameel — DISMISSED** [review]
If it passes CI, it's good to go.

**Comment by clonker** [comment]
Whelp, forgot to update the test outcome after updating indentations, care to re-approve @cameel ?:)

**Review by nikola-matic — APPROVED** [review]

**Review by cameel — APPROVED** [review]
