### PR TITLE
[SMTChecker] Fix ICE on external calls from constructor

### LINKED ISSUE #11341: [SMTChecker] ICE in void solidity::frontend::CHC::externalFunctionCall(const solidity::frontend::FunctionCall &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract State {
    function f() public view returns (uint) {
    }
}
contract C {
    State s;
    uint z = s.f();
}
```

produces:

```
Internal compiler error during compilation:
/solidity/libsolidity/formal/CHC.cpp(762): Throw in function void solidity::frontend::CHC::externalFunctionCall(const solidity::frontend::FunctionCall &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

## Environment

- Compiler version:  0.8.5-develop.2021.5.3+commit.fe4822a1.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/11341
Depends on https://github.com/ethereum/solidity/pull/11465

### CODE REVIEW

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -788,7 +788,6 @@ void CHC::externalFunctionCallToTrustedCode(FunctionCall const& _funCall)
 	auto kind = funType.kind();
 	solAssert(kind == FunctionType::Kind::External || kind == FunctionType::Kind::BareStaticCall, "");
 
-	solAssert(m_currentContract, "");
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:791]: Removed cus the same check is present 5 lives above

**Review by ekpyron — APPROVED** [review]
