### PR TITLE
Forbid implicit conversion from a contract to super

### LINKED ISSUE #9596: [solc] ICE because "cannot convert magic variable super"
## Description

```
contract C {
  C c;
  function h() public {
    super != c;
  }
}
```

throws

https://github.com/ethereum/solidity/blob/05901f5bc9607a6c3f0e4dd83954ebff17834eab/libsolidity/codegen/CompilerUtils.cpp#L754

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by cameel**
Fixes #9596.

At some point in the future #7744 will make such conversion impossible anyway so I think forbidding it should not be controversial. All the tests still pass after doing so.

I tried to come up in some other situations where this conversion could happen but the only one I found so far are operators.

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -1569,12 +1569,15 @@ BoolResult ContractType::isImplicitlyConvertibleTo(Type const& _convertTo) const
 		return true;
 	if (_convertTo.category() == Category::Contract)
 	{
-		auto const& bases = contractDefinition().annotation().linearizedBaseContracts;
-		if (m_super && bases.size() <= 1)
+		auto const& targetContractType = dynamic_cast<ContractType const&>(_convertTo);
+		if (targetContractType.isSuper())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:1573]: I think we should also disallow conversions from super.

**Review by chriseth — CHANGES_REQUESTED** [review]
Please add a changelog entry.

File: test/libsolidity/syntaxTests/conversion/implicit_conversion_of_super_in_comparison.sol [hunk 2]
```diff
@@ -0,0 +1,24 @@
+contract D {}
+
+contract C {
```
Comment (axic) [inline test/libsolidity/syntaxTests/conversion/implicit_conversion_of_super_in_comparison.sol:3]: Should this be `contract C is D`?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (cameel) [reply libsolidity/ast/Types.cpp:1573]: It's already disallowed. The function has this at the beginning:
```c++
	if (isSuper())
		return nullptr;
```

File: test/libsolidity/syntaxTests/conversion/implicit_conversion_of_super_in_comparison.sol (hunk 2 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/conversion/implicit_conversion_of_super_in_comparison.sol:3]: No. For completeness I wanted the test to include both a comparison that was causing and ICE and one that was not. Both should result in the same compiler error.

I added comments in the file to make it clearer that `D` is meant to be an unrelated contract on purpose.

**Comment by cameel** [comment]
Changelog added. The PR is ready for another round of review.

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
Ah sorry, needs another rebase. Also I think the changelog entry can be shortened a bit.

**Comment by cameel** [comment]
Rebased and changelog shortened. I hope it's better now.

**Review by chriseth — APPROVED** [review]
