### PR TITLE
Disallow RETURNDATACOPY and RETURNDATASIZE in inline assembly in pure functions

### LINKED ISSUE #12860: RETURNDATACOPY opcode is not disallowed in pure functions
The main feature of a pure function is that it cannot read blockchain state, which includes not only reading storage but also things like accessing external contract code, checking balance, checking remaining gas, etc. There are also cases where this is not so clear cut, e.g. CODECOPY (#12260, #8153) but we tend towards disallowing that as well. Another such case is RETURNDATACOPY. It was recently pointed out that it should not be accessible in pure functions.

The fact that it's allowed should probably be considered a bug. Otherwise it's a breaking change.

## Environment

- Compiler version: 0.8.13

## Steps to reproduce
This code compiles just fine:
```solidity
function foo() pure {
    assembly {
        returndatacopy(0, 32, 64)
    }
}
```

While the same would not work with e.g. EXTCODECOPY:
```solidity
function foo() pure {
    assembly {
        extcodecopy(0, 0, 32, 64)
    }
}
```
```
Error: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
 --> test.sol:3:13:
  |
3 |             extcodecopy(0, 0, 32, 64)
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Extra information
Here's the full list of instructions currently disallowed in `pure` functions
https://github.com/ethereum/solidity/blob/c4909e99c1015233d6937d229058cde52615f246/libevmasm/SemanticInformation.cpp#L465-L520

### PR DESCRIPTION
**Pull request by cameel**
Fixes #12860.

The PR also adds comprehensive test cases for opcodes allowed/disallowed at each visibility level.

### CODE REVIEW

File: libevmasm/SemanticInformation.cpp [hunk 1]
```diff
@@ -479,6 +479,8 @@ bool SemanticInformation::invalidInPureFunctions(Instruction _instruction)
 	case Instruction::EXTCODESIZE:
 	case Instruction::EXTCODECOPY:
 	case Instruction::EXTCODEHASH:
+	case Instruction::RETURNDATASIZE:
+	case Instruction::RETURNDATACOPY:
```
Comment (hrkrshnn) [inline libevmasm/SemanticInformation.cpp:483]: I'm not sure what should or should not be pure. AFAIK, there is no proper definition for what is a pure function in EVM. So this is entirely arbitrary.

The only restriction I can think about is related to compile time constant evaluation. Which we don't properly have yet. If that is indeed the case, there should be more instructions here.

File: Changelog.md [hunk 2]
```diff
@@ -11,6 +11,7 @@ Compiler Features:
 Bugfixes:
 * Assembly-Json: Fix assembly json export to store jump types of operations in `jumpType` field instead of `value`.
 * TypeChecker: Convert parameters of function type to how they would be called for ``abi.encodeCall``.
+* View Pure Checker: Mark ``returndatasize`` and ``returndatacopy`` as view.
```
Comment (hrkrshnn) [inline Changelog.md]: Should be about marking them as not pure!

File: libevmasm/SemanticInformation.cpp (hunk 1 above)
Comment (cameel) [reply libevmasm/SemanticInformation.cpp:483]: Well, we don't even have full agreement if `pure` should refer to stuff that can be evaluated at compilation time or to stuff that does not touch state (#8153). So I think this out of scope of this PR.

This particular change to RETURNDATACOPY was explicitly requested by @chriseth:

> 0age just mentioned it the ethsecurity chat that returndatacopt is not marked as invalid in pure functions - can someone please create an issue about it and potentially even fix?

What I'm not clear about is whether this should really be considered a bug. I'd consider it a breaking change but from that comment it seems to me like @chriseth sees it as a bugfix.

File: Changelog.md (hunk 2 above)
Comment (cameel) [reply Changelog.md]: Well, maybe. I'll reword to clarify but I based this on the entry that we have for `chainid`, which was a similar situation:

> * View Pure Checker: Mark ``chainid`` as view.

Comment (cameel) [reply Changelog.md]: How about now?

Comment (hrkrshnn) [reply Changelog.md]: Looks good!

File: libevmasm/SemanticInformation.cpp (hunk 1 above)
Comment (aarlt) [reply libevmasm/SemanticInformation.cpp:483]: Hmm.. why is this actually needed?

Comment (aarlt) [reply libevmasm/SemanticInformation.cpp:483]: Ahh.. I guess because `pure` is considered as being evaluatable at compile time, right?

Comment (cameel) [reply libevmasm/SemanticInformation.cpp:483]: Not exactly. Currently `pure` is closer to "not reading or writing", though there are discussions about changing/clarifying that. Reading returndata is a bit borderline IMO. I could see it being allowed.

Comment (aarlt) [reply libevmasm/SemanticInformation.cpp:483]: Yeah, seem to depend on how `pure` is exactly defined. I also understood it (now) as you said - not reading or writing from state (after reading the docs again). Isn't it correct to see it like that `RETURNDATACOPY` & `RETURNDATASIZE` is not reading or writing any state? 

Why should `RETURNDATACOPY` & `RETURNDATASIZE` not be `pure`? What is the big advantage to change that? Or isn't it like that `RETURNDATACOPY` & `RETURNDATASIZE`  can basically only be used, if a call was done before? `STATICCALL` is already considered as reading the state - it is already not allowed in pure functions. 

If `RETURNDATACOPY` & `RETURNDATASIZE` is used without a call (e.g. in pure functions) I see it like that `RETURNDATACOPY` will just not do anything. Where `RETURNDATASIZE` will always return `0`.

For all other cases, calls are needed, that are not allowed in `pure` functions.

**Comment by hrkrshnn** [comment]
Notes from the call: allow this. Might need to think about memory operations in the future.

Also, `returndatasize` may be used by gas optimizers instead of `push1 0`. In that sense, this can break some contracts.

File: libevmasm/SemanticInformation.cpp (hunk 1 above)
Comment (aarlt) [reply libevmasm/SemanticInformation.cpp:483]: After having a short discussion with @chriseth  and @hrkrshnn, I finally understand the underlying issue. The problem is basically, that it is possible to do a call before calling a pure function that maybe using `RETURNDATACOPY` and `RETURNDATASIZE`. In this case the values depend on the previous calls.

Thats why it makes totally sense to disallow `RETURNDATACOPY` and `RETURNDATASIZE` in pure functions.

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+            pop(mulmod(0, 1, 2))
+            pop(signextend(0, 1))
+            pop(keccak256(0, 1))
+            pop(0)
+            pop(mload(0))
+            mstore(0, 1)
+            mstore8(0, 1)
+            //pop(sload(0))
+            //sstore(0, 1)
+            //pop(gas())
```
Comment (aarlt) [inline test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: I did not check the actual current behaviour. But wouldn't it be better to not comment those out, so that we can see the error messages later?

Comment (aarlt) [inline test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: I did not check the actual current behaviour. But wouldn't it be better to not comment those out, so that we can see the error messages later?

Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Yeah, that's why I also added `inline_assembly_instructions_disallowed_pure.sol`. It contains only those commented-out opcodes.

I left them commented-out here because otherwise it's not that easy to see which ones are missing from the list.

Also, I want this case to pass without error because then it goes all the way through codegen. The failing one (obviously) stops at the analysis stage.

Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: not uncomment, but let the errors there.. e.g.
```
// ====
// EVMVersion: >=london
// ----
// Warning 5740: (94-1721): Unreachable code.
...
// TypeError 8961: (1759-1774): Function cannot be declared as pure because this expression (potentially) modifies the state.
// TypeError 8961: (1809-1819): Function cannot be declared as pure because this expression (potentially) modifies the state.
...
// TypeError 8961: (1919-1941): Function cannot be declared as pure because this expression (potentially) modifies the state.
```

Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: not uncomment, but let the errors there.. e.g.
```
// ====
// EVMVersion: >=london
// ----
// Warning 5740: (94-1721): Unreachable code.
...
// TypeError 8961: (1759-1774): Function cannot be declared as pure because this expression (potentially) modifies the state.
// TypeError 8961: (1809-1819): Function cannot be declared as pure because this expression (potentially) modifies the state.
...
// TypeError 8961: (1919-1941): Function cannot be declared as pure because this expression (potentially) modifies the state.
```

Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Duplicate comment.

**Comment by cameel** [comment]
> Notes from the call: allow this. Might need to think about memory operations in the future.

Allow what? Allow RETURNDATACOPY in pure functions or allow this PR to be merged?

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol (hunk 3 above)
Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Right now I would prefer having those errors.. but I also find the error messages a bit poor.. I think it would be better to know exactly what expression actually caused it

Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Maybe two versions would make sense.. one where the stuff is commented out, and one that will produce an error?

Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: I don't understand. If you don't uncomment them, how would you get the error messages?

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure.sol [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+            //pop(pc())
+        }
+    }
+}
+// ====
+// EVMVersion: >=london
+// ----
+// Warning 5740: (742-1153): Unreachable code.
+// TypeError 2527: (79-87): Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
+// TypeError 8961: (101-113): Function cannot be declared as pure because this expression (potentially) modifies the state.
```
Comment (aarlt) [inline test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure.sol:51]: Ah sorry! Somehow I missed this.

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol (hunk 3 above)
Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Ah sorry, somehow I did not see the other tests.. so you are already testing both versions, allowed and disallowed.

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure.sol (hunk 4 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure.sol:51]: Yeah. For each visibility level there are two files: one with allowed and one with disallowed opcodes :)

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol (hunk 3 above)
Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: > I don't understand. If you don't uncomment them, how would you get the error messages?

Everything is good! I did not saw that you already did what I meant with the `*disallowed*` tests. That makes totally sense now. Somehow I just missed those. However, I meant the error messages that are shown e.g. in the `*disallowed*` tests.. E.g. `TypeError 2527: (153-162): Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".` I was missing somehow the exact reference in the source code.. I was expecting that the thing is somehow written directly in the message. However, I also noticed now that the reference is shown, if `solc` is used:
```
Error: Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view".
  --> /Users/alex/git/solidity/test/libsolidity/syntaxTests/test2.sol:68:17:
   |
68 |             pop(chainid())
   |                 ^^^^^^^^^
```

Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: If we have e.g. `TypeError 2527: (153-162)`... wouldn't it be nice to extract the corresponding string (eg. string between characters `153-162`).. so we could also read the tests more easily.. e.g. `TypeError 2527: (153-162):  'chainid()' Function declared as pure, but this expression (potentially) reads from the environment or state and thus requires "view"`.

Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Yeah, there were similar ideas in #4620 and #9581. Maybe we should restart the discussion there. @nishant-sachdeva also recently commented on the fact that we don't even have line numbers in tests, which is another similar idea.

The thing is, we don't really have an agreement on what to do so it requires some design discussion.

I think that adding line numbers would probably be uncontroversial, easy to implement and would help a bit so maybe we should create a `good first issue` for that? Not sure if we have enough manpower now to push through a bigger change.

**Comment by aarlt** [comment]
> > Notes from the call: allow this. Might need to think about memory operations in the future.
> 
> Allow what? Allow RETURNDATACOPY in pure functions or allow this PR to be merged?

I think @hrkrshnn meant allow the disallow ;)

**Comment by hrkrshnn** [comment]
I meant to say that allow this change ;)

Just do add one more comment. These opcodes `returndatasize` and `returndatacopy` are indeed used in high level calls. For example:

```solidity
contract C {
    function f() pure external returns (uint) {}
}

contract Test {
    function test() pure external returns (uint ret) {
        ret = C(address(123)).f();
    }
}
```

**Comment by aarlt** [comment]
> I meant to say that allow this change ;)
> 
> Just do add one more comment. These opcodes `returndatasize` and `returndatacopy` are indeed used in high level calls. For example:
> 
> ```solidity
> contract C {
>     function f() pure external returns (uint) {}
> }
> 
> contract Test {
>     function test() pure external returns (uint ret) {
>         ret = C(address(123)).f();
>     }
> }
> ```

@cameel Maybe we should rename this PR (and commit messages) to communicate that this is only disallowing this in inline assembly? 
@hrkrshnn I guess we don't want to allow this for high-level calls, right? Shouldn't be all calls disallowed in pure?

**Comment by hrkrshnn** [comment]
@aarlt About high level calls: I'd argue, yes. In particular, we should make pure to be as close to compile time evaluation as possible. Changing the behaviour for high level calls would definitely be a breaking change. Technically, this one as well, but we're trying to argue that we haven't mentioned the assembly part in the documentation.

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol (hunk 3 above)
Comment (aarlt) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: Sure, having line numbers would make the navigation in files much more easy. But it will not help during reviews, because the user still need to look at numbers. I just created #12890 that adds the location string to the message. I think that increases the readability of such tests.

**Comment by cameel** [comment]
@aarlt
> Maybe we should rename this PR (and commit messages) to communicate that this is only disallowing this in inline assembly?

Good point. Done.

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol (hunk 3 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol:37]: That's a monster PR :)

I think line numbers still help a bit. You can see them in diffs. With them it's much easier than what I do now when reviewing, i.e. counting errors manually.

**Review by ekpyron — APPROVED** [review]
I'm actually still a bit wary about calling this a non-breaking bugfix - especially since occurrences *after* an external call to an external pure function are arguably just fine :-)...
But it's probably fine and the code change and tests look good, so I'm approving!

We could consider mentioning this in the release notes though, or something like that.

**Comment by cameel** [comment]
Personally I think it would be better to treat it as breaking because it's more of an omission than a real bug. But on the other hand we were called out on this which means that people already expect it to work that way...

File: test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed.sol [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+            memoryguard(0)
+            verbatim_1i_1o(hex"600202", 0)
+
+            pop(msize())
+            pop(pc())
+        }
+    }
+}
+// ----
+// SyntaxError 6553: (47-362): The msize instruction cannot be used when the Yul optimizer is activated because it can change its semantics. Either disable the Yul optimizer or do not use the instruction.
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed.sol:19]: How does this actually work :-)? We only run these tests with enabled yul optimizer? I wouldn't have guessed :-).

Comment (cameel) [reply test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed.sol:19]: Apparently. I was surprised too since I usually run `isoltest` without the `--optimize` flag.

**Comment by ekpyron** [comment]
> Personally I think it would be better to treat it as breaking because it's more of an omission than a real bug. But on the other hand we were called out on this which means that people already expect it to work that way...

I'd consider it a proper bug - if these are called before any external call in the pure function itself, then it's definitely contrary to the intended meaning of ``pure`` (under *every* of the different views on what ``pure`` means ;-)) - you can construct pure functions that read state like that after all... (respectively pure functions with different behaviour based on some state that affected the previous external call).
We could of course take drastic measures and do control flow analysis and only flag this in paths, in which there is no pure external call up front - but that's significant effort and in 0.9 we may disallow external calls in pure functions anyways (undecided though)... and it also wouldn't be perfect and would also have false positives... so whatever we do, it's not perfectly nice and maybe disallowing as non-breaking bug-fix is indeed the least harmful way to deal with it.

**Comment by cameel** [comment]
Is returndata really a part of state though? I see it more like some random piece of memory, which is why it seems like a grey area and is just easier to lump together with state than treat as a thing of its own.

**Comment by ekpyron** [comment]
> Is returndata really a part of state though? I see it more like some random piece of memory, which is why it seems like a grey area and is just easier to lump together with state than treat as a thing of its own.

Yeah, I was a bit torn on this when writing that comment myself :-)... I mean - in a lot of cases the returndata of the previous call will literally be lying around somewhere in memory and thereby be accessible via ``mload``... so is ``mload`` also impure :-)?

**Comment by cameel** [comment]
We need to maintain a map of polluted memory slots :P

Anyway, I think the change is good, just not 100% convinced that the case is clear enough that it should be a bugfix.

**Review by chriseth — APPROVED** [review]

**Comment by ekpyron** [comment]
Another argument for considering this breaking after all is
https://github.com/ensdomains/ens-contracts/blob/master/contracts/utils/LowLevelCallUtils.sol

I guess those helper functions were specifically marked ``pure`` because before this change the compiler actively *suggested* to *make* them pure... after which making this an error in a non-breaking release is probably a bit mean...

**Comment by chriseth** [comment]
Yeah, let's make it breaking.
