### PR TITLE
Fix ICE when a variable declaration before a referenced struct

### LINKED ISSUE #12505: [TypeChecker] Failed assertion for forward declared struct constant
```
S constant x;struct S{x y;}
```

throws

https://github.com/ethereum/solidity/blob/eee30b6ead0e2917eb75ab410d571a18b57c24ae/libsolidity/ast/Types.cpp#L2194

### PR DESCRIPTION
**Pull request by Marenz**
fixes #12505

### CODE REVIEW

File: libsolidity/analysis/DeclarationTypeChecker.cpp [hunk 1]
```diff
@@ -437,16 +437,22 @@ void DeclarationTypeChecker::endVisit(VariableDeclaration const& _variable)
...
+			bool allowed = false;
+			if (auto arrayType = dynamic_cast<ArrayType const*>(type))
+				allowed = arrayType->isByteArray();
+			if (!allowed)
+				m_errorReporter.fatalTypeError(9259_error, _variable.location(), "Constants of non-value type not yet implemented.");
+		}
+
+		solAssert(
+			!dynamic_cast<UserDefinedValueType const*>(type) &&
+			type->containsNestedMapping()
```
Comment (ekpyron) [inline libsolidity/analysis/DeclarationTypeChecker.cpp]: This doesn't look right - you meant this negated, right?

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: libsolidity/analysis/DeclarationTypeChecker.cpp (hunk 1 above)
Comment (Marenz) [reply libsolidity/analysis/DeclarationTypeChecker.cpp]: Oh. Haha, yeah. Famous last minute changes. Before it would complain that the error code is in no test, so I figured make it an assert if it can't ever happen anyway.

Comment (ekpyron) [reply libsolidity/analysis/DeclarationTypeChecker.cpp]: Or rather ``solAssert(dynamic_cast<UserDefinedValueType const*>(type) || !type->containsNestedMapping());``?
Not sure we need it at all, though, since we assert that it's a value type above anyways.

File: libsolidity/analysis/DeclarationTypeChecker.cpp [hunk 2]
```diff
@@ -437,16 +437,22 @@ void DeclarationTypeChecker::endVisit(VariableDeclaration const& _variable)
...
-			"The type contains a (nested) mapping and therefore cannot be a constant."
+	if (_variable.isConstant())
+	{
+		if (!type->isValueType())
+		{
+			bool allowed = false;
+			if (auto arrayType = dynamic_cast<ArrayType const*>(type))
+				allowed = arrayType->isByteArray();
+			if (!allowed)
+				m_errorReporter.fatalTypeError(9259_error, _variable.location(), "Constants of non-value type not yet implemented.");
```
Comment (ekpyron) [inline libsolidity/analysis/DeclarationTypeChecker.cpp]: Actually, since we allow byte arrays, the error message is (and has been) wrong :-). But I guess we can keep it.
You can also change it to sth like "Only constants of value types and byte array types are implemented." or so.

**Comment by Marenz** [comment]
Gah, I should update the tests when I modify the error message.,

File: libsolidity/analysis/DeclarationTypeChecker.cpp [hunk 3]
```diff
@@ -437,16 +437,14 @@ void DeclarationTypeChecker::endVisit(VariableDeclaration const& _variable)
...
-			_variable.location(),
-			"The type contains a (nested) mapping and therefore cannot be a constant."
-		);
+	if (_variable.isConstant() && !type->isValueType())
+	{
+		bool allowed = false;
+		if (auto arrayType = dynamic_cast<ArrayType const*>(type))
+			allowed = arrayType->isByteArray();
+		if (!allowed)
+			m_errorReporter.fatalTypeError(9259_error, _variable.location(), "Only constants of value type and byte arrays are implemented.");
```
Comment (ekpyron) [inline libsolidity/analysis/DeclarationTypeChecker.cpp]: If we want to be pedantic this should probably either be
``Only constants of value and byte array type...``, resp. ``Only constants of value type and byte array type...``
or
``Only constants of value type and byte array constants...``

**Review by ekpyron — COMMENTED** [review]
I'd say this is fine, so mainly blocked by the Z3 update.

**Review by ekpyron — APPROVED** [review]
