### PR TITLE
Fix ICE caused by storage parameters with nested mappings in libraries

### LINKED ISSUE #9957: ICE in calldataEncodedSize() when a public library function takes a storage parameter containing a nested maping
## Description

This contract:
```solidity
library Test {
   struct Nested { mapping(uint => uint )[2][] a; } uint y;
    struct X { Nested n; }
    function f(X storage x){}
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.h(224): Throw in function virtual unsigned int solidity::frontend::Type::calldataEncodedSize(bool) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.3-develop.2020.10.2+commit.756e21a8.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by a3d4**
Fixes #9957 .

Alternatively we could wait for PR #9746, it fixes the issue too. (So I was puzzled for some time why I cannot reproduce the error locally :).)

### CODE REVIEW

**Comment by hrkrshnn** [comment]
The "fixes" link seems to be to a PR.

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -599,8 +599,15 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
...
 	{
 		auto result = referenceType->validForLocation(referenceType->location());
-		if (result && (_variable.isConstructorParameter() || _variable.isPublicCallableParameter()))
-			result = referenceType->validForLocation(DataLocation::CallData);
+		if (result)
+		{
+			bool callDataCheckRequired =
+				(_variable.isLibraryFunctionParameter() && referenceType->location() == DataLocation::Storage) ? false :
+				(_variable.isConstructorParameter() || _variable.isPublicCallableParameter()) ? true :
+				false;
```
Comment (hrkrshnn) [inline libsolidity/analysis/TypeChecker.cpp]: I think it's better to refactor this nested ternary operator into ifs

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol [hunk 2]
```diff
@@ -0,0 +1,8 @@
+library Test {
+    struct Nested { mapping(uint => uint )[2][] a; } uint y;
+    struct X { Nested n; }
+    function f(X storage x){}
+}
+// ----
+// SyntaxError 4937: (107-132): No visibility specified. Did you intend to add "public"?
+// TypeError 9957: (68-74): Library cannot have non-constant state variables
```
Comment (hrkrshnn) [inline test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: Why not have a test that doesn't have any errors?

```solidity
  struct Nested { mapping(uint => uint )[2][] a; } 
  struct X { Nested n; }
  library Test {
	  function f(X storage x) public {}
  }  
```

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (hrkrshnn) [reply libsolidity/analysis/TypeChecker.cpp]: Also, the last `true: false;` is redundant.

**Comment by cameel** [comment]
I think it was meant to fix #9957.

EDIT: And I see that when you type a dot after `#9957` github's editor suggests `#9915` and inserts it when you press enter. I wish I could disable this issue autocompletion. It's getting in the way more than it ever helps.

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol (hunk 2 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: Yeah. I'd even say that it's more relevant than the broken example and we could keep just this one.

Initially I did not notice that the `uint y;` part is just a completely separate storage variable declaration (that would be valid in a contract) and not some invalid syntax that breaks the struct declaration. If the error happens on valid code too then the errors are just an extra, unnecessary complication.

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol [hunk 3]
```diff
@@ -0,0 +1,8 @@
+library Test {
```
Comment (cameel) [inline test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: I think that `test/libsolidity/syntaxTests/dataLocations/libraries/` would be better place for this test.

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol [hunk 4]
```diff
@@ -0,0 +1,8 @@
...
+    struct Nested { mapping(uint => uint )[2][] a; } uint y;
+    struct X { Nested n; }
+    function f(X storage x){}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]:
```suggestion
    function f(X storage x) {}
```

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol [hunk 5]
```diff
@@ -0,0 +1,8 @@
+library Test {
+    struct Nested { mapping(uint => uint )[2][] a; } uint y;
```
Comment (cameel) [inline test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]:
```suggestion
    struct Nested { mapping(uint => uint)[2][] a; } uint y;
```

Comment (cameel) [inline test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: This being on a single line initially led me think that the syntax here is much more broken than it really is :)
```suggestion
    struct Nested { mapping(uint => uint )[2][] a; }
    uint y;
```

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol (hunk 2 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: I'd also add tests where it's not a storage parameter and where it's not a library function (unless we already have ones covering this, which is likely).

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: How about this?
```c++
bool isLibraryStorageParameter = (_variable.isLibraryFunctionParameter() && referenceType->location() == DataLocation::Storage);
if ((_variable.isConstructorParameter() || _variable.isPublicCallableParameter()) && !isLibraryStorageParameter)
```
or
```c++
bool libraryParameter = _variable.isLibraryFunctionParameter();
bool storageParameter = referenceType->location() == DataLocation::Storage;
bool constructorParameter = _variable.isConstructorParameter();
bool publicCallableParameter = _variable.isPublicCallableParameter();

if ((constructorParameter || publicCallableParameter) && !(libraryParameter && storageParameter))
```

Comment (a3d4) [reply libsolidity/analysis/TypeChecker.cpp]: > I think it's better to refactor this nested ternary operator into ifs

I started with `if` and refactored to `?:` :). I agree of course that the expression can be simplified. I tried to make things easier to understand, but still reasonably short. OK, let's use @cameel's proposal,

```
bool isLibraryStorageParameter = (_variable.isLibraryFunctionParameter() && referenceType->location() == DataLocation::Storage);
bool callDataCheckRequired = ((_variable.isConstructorParameter() || _variable.isPublicCallableParameter()) && !isLibraryStorageParameter);
```

What we do now might be not that important, because #9746 reworks `callDataCheckRequired` anyway.

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol (hunk 2 above)
Comment (a3d4) [reply test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: > Yeah. I'd even say that it's more relevant than the broken example and we could keep just this one.

There is no guarantee that the simplified test succeeds/fails iff the originally reported issue (with fixes) succeeds/fails. So keeping both tests might be considered.

> I'd also add tests where it's not a storage parameter and where it's not a library function (unless we already have ones covering this, which is likely).

I hope non-storage parameters are covered for libraries and contracts both (see e.g.
**types\mapping\library_nested_mapping.sol**,
**nameAndTypeResolution\043_functions_with_structs_of_non_external_types_in_interface_nested.sol**).

Other tests are added to **syntaxTests/types/mapping**, because it seems to fit to all of them.

**Comment by a3d4** [comment]
> The "fixes" link seems to be to a PR.

> I think it was meant to fix #9957.

Yes, corrected, thanks!

Also, I hope the formatting is OK now, I did not reply to each comment.

File: test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol (hunk 2 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/iceRegressionTests/storage_parameter_in_library.sol]: You can never be sure but I think that in this case the likelihood is very low. You just can't test everything :)

I think I'd personally just skip that test case but I'm not completely opposed to including it in `iceRegressionTests/` if you think it adds some value. More tests is usually a good thing.

File: test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_2.sol [hunk 6]
```diff
@@ -0,0 +1,4 @@
+struct S { mapping(uint => uint)[2] a; }
+library L {
+    function f(S storage s) public {}
+}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_2.sol]: Does this test actually get executed? It's missing the `// ----` and `isoltest` usually fails when I forget it in my tests but your tests seem to be passing.

File: test/libsolidity/syntaxTests/types/mapping/contract_storage_parameter_with_mapping.sol [hunk 7]
```diff
@@ -0,0 +1,6 @@
+struct S { mapping(uint => uint)[2] a; }
+contract L {
```
Comment (cameel) [inline test/libsolidity/syntaxTests/types/mapping/contract_storage_parameter_with_mapping.sol]: Not that it matters that much but when I see `L` in tests I usually expect it to be a library.
```suggestion
contract C {
```

File: test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_1.sol [hunk 8]
```diff
@@ -0,0 +1,6 @@
+library Test {
+    struct Nested { mapping(uint => uint)[2][] a; }
+    struct X { Nested n; }
+    function f(X storage x) public {}
+}
+// ----
```
Comment (cameel) [inline test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_1.sol]: > `library_storage_parameter_with_mapping_1.sol`
> `library_storage_parameter_with_mapping_2.sol`

How about `library_storage_parameter_with_nested_mapping.sol` and `library_storage_parameter_with_mapping`?

**Review by cameel — COMMENTED** [review]
Only very minor corrections needed. I think this will be ready for merge once they're done.

> Also, I hope the formatting is OK now, I did not reply to each comment.

Yeah, it's fine. I resolved all the comments that were addressed (so, basically all of them :).

File: test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_2.sol (hunk 6 above)
Comment (a3d4) [reply test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_2.sol]: My understanding is that `isoltest` keeps the `// ----`, if it is there. For instance, if all errors are gone, `isoltest` updates the `.sol` file, adding the trailing `// ----`.

However if a test has no `// ----` and succeeds, `isoltest` (and `soltest`) are happy.

File: test/libsolidity/syntaxTests/types/mapping/contract_storage_parameter_with_mapping.sol (hunk 7 above)
Comment (a3d4) [reply test/libsolidity/syntaxTests/types/mapping/contract_storage_parameter_with_mapping.sol]: Ah, copy-pasting. It matters ). Good catch, thanks!

File: test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_1.sol (hunk 8 above)
Comment (a3d4) [reply test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_1.sol]: Yes, I like the idea. (I think now it is fine to keep all test together here, without moving anything to `iceRegressionTests/`.)

File: test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_2.sol (hunk 6 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/types/mapping/library_storage_parameter_with_mapping_2.sol]: Looks like it complains only in semantic tests:
```
Exception during test: /solidity/test/libsolidity/SemanticTest.cpp(101): Throw in function solidity::frontend::test::SemanticTest::SemanticTest(const string&, solidity::langutil::EVMVersion, const std::vector<boost::filesystem::path>&, bool)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: No tests specified in /projects/solidity/test/libsolidity/semanticTests/enums/constructing_enums_from_ints.sol
```

OK then, if it passes then I guess it's fine.

**Review by cameel — DISMISSED** [review]
Looks fine now.

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
Needs rebase.

**Review by chriseth — APPROVED** [review]
