### PR TITLE
Fix assignment after tags in inline assembly

### LINKED ISSUE #478: (Inline assembly) assignment using =: fails after tags
```
contract Test {
    function f() {
        uint x;
        assembly{
            tag:
               =: x 
        }
    }
}
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #478.

### CODE REVIEW

File: libsolidity/inlineasm/AsmParser.cpp [hunk 1]
```diff
@@ -95,7 +95,8 @@ assembly::Statement Parser::parseStatement()
 			fatalParserError("Label name / variable name must precede \":\".");
 		assembly::Identifier const& identifier = boost::get<assembly::Identifier>(statement);
 		m_scanner->next();
-		if (m_scanner->currentToken() == Token::Assign)
+		// =: is an assignment, while :=: is invalid
```
Comment (chriseth) [inline libsolidity/inlineasm/AsmParser.cpp]: Please change the comment:
`identifier:=:` should be parsed as `identifier: =:` (i.e. a label) while `identifier:=` (being followed by a non-colon) as `identifier :=` (assignment).

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/inlineasm/AsmParser.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/inlineasm/AsmParser.cpp]: Done

**Review by chriseth — APPROVED** [review]
