### PR TITLE
Fixes bug in byte optimization rule and adds tests.

### LINKED ISSUE #6316: Wrong argument order in optimization rule for byte function leads to incorrect computation
## Description

The following strict assembly code results in `sstore(0,2)` instead of `sstore(0,0)`.

```
{
  let a := foo(2)
  sstore(0, a)
  function foo(x) -> r
  {
    r := byte(x,31)
  }
}
```

The root cause of the bug is the incorrect optimization of the code pattern `byte(x,31)` to `and(x,255)` in the rule below (introduced in 0.5.5)

https://github.com/ethereum/solidity/blob/304ef77b4a5e983ebc0105bd41e00d78607aefdb/libevmasm/RuleList.h#L156

The correct rule is optimizing `byte(31,x)` to `and(x,255)`. Essentially, the ordering of arguments in the optimization rule for the `byte` function is wrong.

## Environment

- Compiler version: latest develop commit
- Target EVM version (as per compiler settings): petersburg
- Framework/IDE (e.g. Truffle or Remix): na
- EVM execution environment / backend / blockchain client: na
- Operating system: Ubuntu 18.04

## Steps to Reproduce

This issue can be reproduced using the expression simplification step (`s`) of the `yulopti` testing tool as follows

```
$ yulopti --input-file <buggy_code>.yul
----------------------                                                            
{                                                                                   
  let a := foo(2)                                                   
  sstore(0, a)                                                           
  function foo(x) -> r
  {
    r := byte(x,31)                        
  }
}

(q)quit/(f)flatten/(c)se/initialize var(d)ecls/(x)plit/(j)oin/(g)rouper/(h)oister/
  (e)xpr inline/(i)nline/(s)implify/varname c(l)eaner/(u)nusedprune/ss(a) transform/
  (r)edundant assign elim./re(m)aterializer/f(o)r-loop-pre-rewriter/
  s(t)ructural simplifier/equi(v)alent function combiner/ssa re(V)erser/?
  stack com(p)ressor?
 s
----------------------
{
    let a := foo(2)
    sstore(0, a)
    function foo(x) -> r
    {
        r := and(x, 255)
    }
}
```

The resulting `and` is subsequently optimized to `sstore(0,2)`.

### PR DESCRIPTION
**Pull request by bshastry**
### Description

(Fixes #6316 )

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by chriseth** [comment]
This needs a buglist entry.

File: test/libevmasm/Optimiser.cpp [hunk 1]
```diff
@@ -268,6 +268,26 @@ BOOST_AUTO_TEST_CASE(cse_double_shift_left_overflow)
 	}
 }
 
+BOOST_AUTO_TEST_CASE(cse_byte_ordering_bug)
+{
+	AssemblyItems input{
+			u256(31),
+			u256(2),
```
Comment (chriseth) [inline test/libevmasm/Optimiser.cpp]: Please use something non-constant like `callvalue` here.

File: test/libevmasm/Optimiser.cpp [hunk 2]
```diff
@@ -268,6 +268,26 @@ BOOST_AUTO_TEST_CASE(cse_double_shift_left_overflow)
...
+			Instruction::BYTE
+	};
+	checkCSE(input, {u256(0)});
+}
+
+BOOST_AUTO_TEST_CASE(cse_byte_ordering_fix)
+{
+	AssemblyItems input{
+			u256(2),
```
Comment (chriseth) [inline test/libevmasm/Optimiser.cpp]: Same here.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 3]
```diff
@@ -10495,6 +10495,25 @@ BOOST_AUTO_TEST_CASE(fixed_bytes_length_access)
 	ABI_CHECK(callContractFunction("f(bytes32)", "789"), encodeArgs(u256(32), u256(16), u256(8)));
 }
 
+BOOST_AUTO_TEST_CASE(byte_optimization_bug)
+{
+char const* sourceCode = R"(
+		contract C {
+			assembly {
+	                        function byte_wrong_order(uint a) public returns (uint c) {
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp]: uses spaces for indentation.

File: docs/bugs.json [hunk 4]
```diff
@@ -1,4 +1,15 @@
 [
+    {
+        "name": "ByteOptimizationBug",
```
Comment (chriseth) [inline docs/bugs.json]: We never explicitly added the word "Bug". What about `ByteInstructionOptimization'?

File: docs/bugs.json [hunk 5]
```diff
@@ -1,4 +1,15 @@
...
+        "summary": "Byte expressions that contain the constant 31 as the second argument can result in unexpected values.",
```
Comment (chriseth) [inline docs/bugs.json]: The optimizer incorrectly handles `byte` opcodes that use the constant 31 as second argument. This can happen when performing index access on `bytesNN` types with a compile-time constant value (not index) of 31 or when using the `byte` opcode in inline assembly.

File: docs/bugs.json [hunk 6]
```diff
@@ -1,4 +1,15 @@
...
+        "description": "Byte operations whose second argument is 31 are incorrectly optimized. This only applies to byte operations of compile-time constant expressions.",
```
Comment (chriseth) [inline docs/bugs.json]: I guess this is more or less equal to summary...

File: test/libevmasm/Optimiser.cpp [hunk 7]
```diff
@@ -268,6 +268,26 @@ BOOST_AUTO_TEST_CASE(cse_double_shift_left_overflow)
 	}
 }
 
+BOOST_AUTO_TEST_CASE(cse_byte_ordering_bug)
+{
+	AssemblyItems input{
+			u256(31),
```
Comment (leonardoalt) [inline test/libevmasm/Optimiser.cpp]:
```suggestion
		u256(31),
```
This only needs one level of indentation (same for the other lines)

File: test/libevmasm/Optimiser.cpp [hunk 8]
```diff
@@ -268,6 +268,26 @@ BOOST_AUTO_TEST_CASE(cse_double_shift_left_overflow)
...
+			Instruction::CALLVALUE,
+			Instruction::BYTE
+	};
+	checkCSE(input, {u256(31), Instruction::CALLVALUE, Instruction::BYTE});
+}
+
+BOOST_AUTO_TEST_CASE(cse_byte_ordering_fix)
+{
+	AssemblyItems input{
+			Instruction::CALLVALUE,
```
Comment (leonardoalt) [inline test/libevmasm/Optimiser.cpp]: Same here

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 9]
```diff
@@ -10495,6 +10495,27 @@ BOOST_AUTO_TEST_CASE(fixed_bytes_length_access)
 	ABI_CHECK(callContractFunction("f(bytes32)", "789"), encodeArgs(u256(32), u256(16), u256(8)));
 }
 
+BOOST_AUTO_TEST_CASE(byte_optimization_bug)
+{
+char const* sourceCode = R"(
```
Comment (leonardoalt) [inline test/libsolidity/SolidityEndToEndTest.cpp]:
```suggestion
	char const* sourceCode = R"(
```

File: Changelog.md [hunk 10]
```diff
@@ -1,5 +1,8 @@
 ### 0.5.7 (unreleased)
 
+Important Bugfixes:
+ * Optimizer: Fix wrong ordering of arguments in byte optimization rule for constants.
```
Comment (Marenz) [inline Changelog.md:4]: should this get a whole own section "Important Bugfixes" instead of being part of the normal "Bugfixes"?

Comment (axic) [reply Changelog.md:4]: It is in `Important Bugfixes`.

Comment (Marenz) [reply Changelog.md:4]: That's what I mean, as in, whether it should be ;) I haven't seen that before.

Comment (chriseth) [reply Changelog.md:4]: Yes, we do that for bugs that go into the bug list.

Comment (bshastry) [reply Changelog.md:4]: From what I can understand, there is an "Important Bugfixes" Changelog section whenever the said release adds a buglist entry. If this logic holds, then  should we retain it in the changelog for legacy reasons?

File: docs/bugs.json [hunk 11]
```diff
@@ -1,4 +1,15 @@
 [
+    {
+        "name": "IncorrectByteInstructionOptimization",
+	"summary": "The optimizer incorrectly handles byte opcodes whose second argument is 31 or a constant expression that evaluates to 31. This can result in unexpected values.",
+        "description": "The optimizer incorrectly handles byte opcodes that use the constant 31 as second argument. This can happen when performing index access on bytesNN types with a compile-time constant value (not index) of 31 or when using the byte opcode in inline assembly.",
```
Comment (axic) [inline docs/bugs.json:5]: @chriseth @holiman are we happy with the summary and description?

**Comment by axic** [comment]
Merging this now, we can review both bug list entries at once.
