### PR TITLE
 Fix error in SMTChecker: Use rich indentifier instead of external identifier to encode member access to functions

### LINKED ISSUE #14181: [SMTChecker] ICE because parameter must have external type
```
pragma experimental SMTChecker;
library L {
function value(function()internal a, uint256 b) internal {}
}
contract C {
using L for function()internal;
function f() public {
    function()internal x;
    x.value(42);
}
}
```

throws

https://github.com/ethereum/solidity/blob/385c48df73030c4526f75029b65ec840e2255b75/libsolidity/ast/Types.cpp#L3617

### PR DESCRIPTION
**Pull request by pgebal**
Closes https://github.com/ethereum/solidity/issues/14181

Cause:
- we use `FunctionType::externalIdentifier` in `SMTEncoder` to encode functions, `externalIdentifier` requires all parameters to have external type. Error happens when function parameter is an internal function

Solution:
- use a hash of rich identifier instead of external identifier when encoding function in `SMTEncoder`

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -1358,7 +1359,10 @@ bool SMTEncoder::visit(MemberAccess const& _memberAccess)
 	{
 		auto const* functionType = dynamic_cast<FunctionType const*>(_memberAccess.annotation().type);
 		if (functionType && functionType->hasDeclaration())
-			defineExpr(_memberAccess, functionType->externalIdentifier());
+			defineExpr(
+				_memberAccess,
+				util::selectorFromSignatureU32(functionType->richIdentifier())
```
Comment (pgebal) [inline libsolidity/formal/SMTEncoder.cpp:1364]: I don't like that the function is called `selectorFromSignatureU32` and I call it on rich identifier. Maybe copying it into a private function in `SMTEncoder` and renaming it is a better idea?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1364]: Isn't something like a 4 byte selector already available in `functionType`?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1364]: Ohh that might be only for external functions, I see

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1364]: I think your approach is fine

File: test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol [hunk 2]
```diff
@@ -0,0 +1,14 @@
+library L {
+	function value(function()internal a, uint256 b) internal {}
+}
+contract C {
+	using L for function()internal;
+
+	function f() public {
+		function()internal x;
+		x.value(42);
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol:9]: What exactly was triggering the assertion before, was it `x.value`?

Comment (pgebal) [reply test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol:9]: yes

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (pgebal) [reply libsolidity/formal/SMTEncoder.cpp:1364]: No. There was only `externalIdentifier` which dosen't work for internal functions.

Comment (pgebal) [reply libsolidity/formal/SMTEncoder.cpp:1364]: I understood to leave it like it is now and use `selectorFromSignatureU32`, or am I mistaken?

File: test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol (hunk 2 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol:9]: I think I still don't fully understand the bug. The `MemberAccess` in the C++ code has function type, right? But it's not the function type of the variable `x`, it's the function type of `x.value`?

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1364]: Yea I'd say that's fine.

File: test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol (hunk 2 above)
Comment (pgebal) [reply test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol:9]: Right. `MemberAccess` is about the `value` function. It's the function type of `value` or `x.value` function from library.

Comment (pgebal) [reply test/libsolidity/smtCheckerTests/functions/functions_library_internal.sol:9]: @leonardoalt I was wrong about that. I updated PR description with hopefully true cause.

File: Changelog.md [hunk 3]
```diff
@@ -20,6 +20,7 @@ Bugfixes:
  * Commandline Interface: It is no longer possible to specify both ``--optimize-yul`` and ``--no-optimize-yul`` at the same time.
  * SMTChecker: Fix encoding of side-effects inside ``if`` and ``ternary conditional``statements in the BMC engine.
  * SMTChecker: Fix false negative when a verification target can be violated only by trusted external call from another public function.
+ * SMTChecker: Fix internal error when verifying code with internal functions.
```
Comment (leonardoalt) [inline Changelog.md]: @pgebal can you also update the bugfix message here with something more precise?

Comment (pgebal) [reply Changelog.md]: @leonardoalt done

**Review by leonardoalt — APPROVED** [review]
