### PR TITLE
Fix handling of scopes in Yul Interpreter.

### LINKED ISSUE #7237: [yul] interpreter fails assertion `m_functions.count(_funCall.functionName.name)`
## Description

```
{
  function foo(x) { foo(1) }
  foo(1)
}
```

fails this assertion

https://github.com/ethereum/solidity/blob/aae1d9872402b4548fc3c1a7497e6cb571507c7b/test/tools/yulInterpreter/Interpreter.cpp#L240

`solc` correctly generates code for it, so I suspect this is a yul interpreter bug.

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg

## Steps to Reproduce

```
$ yulrun --input-file <code.yul>
```

where `code.yul` is the enclosed code.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/7237

### CODE REVIEW

**Comment by chriseth** [comment]
Forgot the test....

File: test/tools/yulInterpreter/Interpreter.cpp [hunk 1]
```diff
@@ -180,25 +180,23 @@ void Interpreter::operator()(Block const& _block)
...
 void Interpreter::closeScope()
 {
-	for (auto const& var: m_scopes.back())
-	{
-		size_t erased = m_variables.erase(var) + m_functions.erase(var);
-		solAssert(erased == 1, "");
-	}
+	for (auto const& [var, funDeclaration]: m_scopes.back())
+		if (!funDeclaration)
+			solAssert(m_variables.erase(var) == 1, "");
```
Comment (bshastry) [inline test/tools/yulInterpreter/Interpreter.cpp:200]: When are functions unregistered?

File: test/tools/yulInterpreter/Interpreter.cpp [hunk 2]
```diff
@@ -164,8 +165,7 @@ void Interpreter::operator()(Block const& _block)
 		if (statement.type() == typeid(FunctionDefinition))
 		{
 			FunctionDefinition const& funDef = boost::get<FunctionDefinition>(statement);
-			m_functions[funDef.name] = &funDef;
-			m_scopes.back().insert(funDef.name);
+			m_scopes.back().emplace(funDef.name, &funDef);
```
Comment (bshastry) [inline test/tools/yulInterpreter/Interpreter.cpp:169]:
```suggestion
			solAssert(!m_scopes.back().count(funDef.name), "");
			m_scopes.back().emplace(funDef.name, &funDef);
```

File: test/tools/yulInterpreter/Interpreter.h [hunk 3]
```diff
@@ -136,17 +136,17 @@ class Interpreter: public ASTWalker
...
 	/// Values of variables.
 	std::map<YulString, dev::u256> m_variables;
-	/// Meanings of functions.
-	std::map<YulString, FunctionDefinition const*> m_functions;
-	/// Scopes of variables and functions, used to clear them at end of blocks.
-	std::vector<std::set<YulString>> m_scopes;
+	/// Scopes of variables and functions. Used for lookup, clearing at end of blocks
+	/// and passing over the visible functions across function calls.
+	/// The pointer is nullptr if and only if the key is a variable.
+	std::vector<std::map<YulString, FunctionDefinition const*>> m_scopes;
```
Comment (bshastry) [inline test/tools/yulInterpreter/Interpreter.h:149]: Wondering if having a separate scope object for variables and functions would make the code more readable. I'm not sure.

File: test/tools/yulInterpreter/Interpreter.h [hunk 4]
```diff
@@ -186,16 +184,19 @@ class ExpressionEvaluator: public ASTWalker
 	/// stores it in m_value.
 	void evaluateArgs(std::vector<Expression> const& _expr);
 
-	/// Extracts functions from the earlier scopes that are visible for the given function
-	std::map<YulString, FunctionDefinition const*> visibleFunctionsFor(YulString const& _name);
+	/// Finds the function called @a _functionName in the current scope stack and returns
+	/// the function's scope stack (with variables removed) and definition.
```
Comment (bshastry) [inline test/tools/yulInterpreter/Interpreter.h:188]: Why are variables removed from the function's scope stack?

**Review by bshastry — COMMENTED** [review]
Code looks good to me, I have some questions regarding function deregistration and handling of nested scope.

File: test/tools/yulInterpreter/Interpreter.cpp (hunk 1 above)
Comment (Marenz) [inline test/tools/yulInterpreter/Interpreter.cpp:200]:
```suggestion
			solAssert(funDeclaration || m_variables.erase(var) == 1, "");
```

Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.cpp:200]: Functions are only "registered" inside `m_scopes`, whose last element is removed at the end of this function. In addition to `m_scopes`, variables are also tracked inside `m_variables`, so they have to be removed from there here.

Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.cpp:200]: I don't think this is needed because of `if (!funDeclaration)` in the line above.

File: test/tools/yulInterpreter/Interpreter.h (hunk 4 above)
Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.h:188]: Because they are not accessible.

File: test/tools/yulInterpreter/Interpreter.cpp (hunk 1 above)
Comment (bshastry) [reply test/tools/yulInterpreter/Interpreter.cpp:200]: Ah I see.

**Review by bshastry — DISMISSED** [review]
