### PR TITLE
Code generators needed fixing of the cleanup process during typecasting

### LINKED ISSUE #12535: [Logging] Indexed log topic differs between legacy and IR if explicitly downcast
```
contract C {
  event ev0(bytes1 indexed);
  constructor() {
    emit ev0(bytes1(bytes16(0x31313131313131313131313131313131)));
  }
}
// ====
// compileViaYul: also
// ----
// constructor() ->
// ~ emit ev0(bytes1): #"1"
```

Legacy truncates indexed log topic, while IR leaves it untruncated. This would lead to a divergence of blockchain state depending on which backend is used.

To reproduce

```
$ cp test.sol test/libsolidity/semanticTests
$ isoltest -t semanticTests/test
  Running via Yul:
  Expected result:
  // constructor() ->
  // ~ emit ev0(bytes1): #"1"

  Obtained result:
  // constructor() ->
  // ~ emit ev0(bytes1): #"1111111111111111"
  
  Attention: Updates on the test will apply the detected format displayed.
  
  Note that the test passed without Yul. 
```

Note that the divergence is maintained with/without optimizer so I would guess this may be a bug related to truncation (or lack thereof) in Sol->Yul.

### PR DESCRIPTION
**Pull request by nishant-sachdeva**
Typecasting process for "bytes" and "integers" has problems in the Old and New Code Generators

1. In the New Code generator, for the bytes type, it was sending the "from" type for cleanup instead of the "to" type.
2. Errors in the old code generator are yet to be identified

Closes #12535

### CODE REVIEW

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 1]
```diff
@@ -3404,7 +3404,7 @@ string YulUtilFunctions::conversionFunction(Type const& _from, Type const& _to)
 				solAssert(toCategory == Type::Category::FixedBytes, "Invalid type conversion requested.");
 				body =
 					Whiskers("converted := <clean>(value)")
-					("clean", cleanupFunction(from))
+					("clean", cleanupFunction(_to))
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: What this should really do is probably to use the cleanup function of the smaller of the types ``from`` and ``_to``.

Can you verify that we have tests for the following and they don't break:
```
ontract C {
    function g() external returns (bytes32 y) {
        bytes1 x;
        assembly { x := sub(0,1) }
        y = x;
    }

}
// ====
// compileViaYul: also
// ----
// g() -> 0xff00000000000000000000000000000000000000000000000000000000000000
```
?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 2]
```diff
@@ -3387,6 +3387,7 @@ string YulUtilFunctions::conversionFunction(Type const& _from, Type const& _to)
 		case Type::Category::FixedBytes:
 		{
 			FixedBytesType const& from = dynamic_cast<FixedBytesType const&>(_from);
+			FixedBytesType const& to = dynamic_cast<FixedBytesType const&>(_to);
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: You can only do this cast after the ``solAssert(toCategory == Type::Category::FixedBytes, "Invalid type conversion requested.");`` below, otherwise it will throw depending on what ``_to`` is.

**Comment by ekpyron** [comment]
The idea was not to generally *always* call the conversion functions at *all* times, but selectively enforce the conversion when emitting events, i.e. in particular in IRGeneratorForStatements.cpp:L1038 only :-).

**Comment by ekpyron** [comment]
Actually, looking at IRGeneratorForStatements.cpp:L1038 a bit more closely - you can probably get away with asserting that ``paramTypes[i]`` has ``sizeOnStack() == 1`` and then use ``expressionAsType(arg, *paramTypes[i], true)`` instead of using ``convert(arg, *paramTypes[i])`` (and thus you can leave ``convert`` and ``declareAssign`` unchanged).

File: test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening.sol [hunk 3]
```diff
@@ -12,6 +12,6 @@ contract C {
 }
 // ====
 // compileToEwasm: also
-// compileViaYul: also
+// compileViaYul: true
```
Comment (ekpyron) [inline test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening.sol]: You can revert this change now and the test will still pass, won't it?

Comment (nishant-sachdeva) [reply test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening.sol]: Nope, the test does not pass if I revert this change.
New Code and OId Code Generators give conflicting outputs

Comment (ekpyron) [reply test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening.sol]: Ah, right, now I see the diff in the expectation correctly.
Then please split this test into two tests, one for old and one for new codegen and adjust the comment in the test case accordingly.

File: test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_newCodeGen.sol [hunk 4]
```diff
@@ -0,0 +1,17 @@
+contract C {
+    function f() public pure returns (bytes32 r) {
+        bytes4 x = 0xffffffff;
+        bytes2 y = bytes2(x);
+        assembly {
+            r := y
+        }
+        // At this point, r stores four bytes and y stores 2 bytes
+        // y is properly cleaned before the equality check
+        require(y == bytes2(0xffff));
```
Comment (ekpyron) [inline test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_newCodeGen.sol]: These three lines can actually be removed - the fact that `y` is already cleaned is apparent in the return value.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 5]
```diff
@@ -3402,9 +3402,10 @@ string YulUtilFunctions::conversionFunction(Type const& _from, Type const& _to)
 			{
 				// clear for conversion to longer bytes
 				solAssert(toCategory == Type::Category::FixedBytes, "Invalid type conversion requested.");
+				FixedBytesType const& to = dynamic_cast<FixedBytesType const&>(_to);
 				body =
 					Whiskers("converted := <clean>(value)")
-					("clean", cleanupFunction(from))
+					("clean", cleanupFunction((to.numBytes() <= from.numBytes())? to : from))
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
					("clean", cleanupFunction((to.numBytes() <= from.numBytes()) ? to : from))
```

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 6]
```diff
@@ -1035,7 +1035,10 @@ void IRGeneratorForStatements::endVisit(FunctionCall const& _functionCall)
 						")\n";
 				}
 				else
-					indexedArgs.emplace_back(convert(arg, *paramTypes[i]));
+				{
+					solAssert((*parameterTypes[i]).sizeOnStack() == 1, "Size of indexed argument is not 1.");
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]:
```suggestion
					solAssert(parameterTypes[i]->sizeOnStack() == 1, "");
```

**Review by ekpyron — COMMENTED** [review]
Apart from some minor style suggestions, this mainly needs a Changelog entry

File: Changelog.md [hunk 7]
```diff
@@ -19,6 +19,7 @@ Bugfixes:
  * IR Generator: Fix IR syntax error when copying storage arrays of structs containing functions.
  * Natspec: Fix ICE when overriding a struct getter with a Natspec-documented return value and the name in the struct is different.
  * TypeChecker: Fix ICE when a constant variable declaration forward references a struct.
+ * Code Generator: Fix differences in variable cleanup procedured of Old and New Code Generators.
```
Comment (ekpyron) [inline Changelog.md]:
```suggestion
 * IR Generator: Add missing cleanup during the conversion of fixed bytes types to smaller fixed bytes types.
 * IR Generator: Add missing cleanup for indexed event arguments of value type.
```

Comment (ekpyron) [reply Changelog.md]: Also note that the Changelog is sorted alphabetically.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 8]
```diff
@@ -3402,9 +3402,10 @@ string YulUtilFunctions::conversionFunction(Type const& _from, Type const& _to)
 			{
 				// clear for conversion to longer bytes
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: This comment also no longer applies - it clears for conversion to longer and shorter bytes types.

File: test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_OldCodeGen.sol [hunk 9]
```diff
@@ -0,0 +1,13 @@
+contract C {
+    function f() public pure returns (bytes32 r) {
+        bytes4 x = 0xffffffff;
+        bytes2 y = bytes2(x);
+        assembly {
+            r := y
+        }
```
Comment (ekpyron) [inline test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_OldCodeGen.sol]: I only meant to remove the
```
        // At this point, r and y both store four bytes, but
        // y is properly cleaned before the equality check
        require(y == bytes2(0xffff));
```
part in the new code gen version. In the test for old code gen we should keep that.

File: test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_newCodeGen.sol [hunk 10]
```diff
@@ -5,13 +5,13 @@ contract C {
         assembly {
             r := y
         }
-        // At this point, r and y both store four bytes, but
+        // At this point, r stores four bytes and y stores 2 bytes
         // y is properly cleaned before the equality check
         require(y == bytes2(0xffff));
```
Comment (ekpyron) [inline test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_newCodeGen.sol]: Haha, sorry for this apparently being confusing :-). But the idea is to keep the *original*, *unmodified* comment and ``require`` in the ``OldCodeGen`` file and *not* have those three linkes in the ``newCodeGen`` file :-).

Comment (ekpyron) [reply test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_newCodeGen.sol]: In the new code gen test, the output of ``r`` already shows that the conversion properly did the cleanup.
In the old code gen test, the output shows that the conversion did *not* do any cleanup. That's why in the *old* codegen file, we want to make sure that the comparison still works as expected.
Clear now :-)?

File: Changelog.md [hunk 11]
```diff
@@ -16,6 +16,8 @@ Bugfixes:
  * Code Generator: Fix ICE when doing an explicit conversion from ``string calldata`` to ``bytes``.
  * Control Flow Graph: Perform proper virtual lookup for modifiers for uninitialized variable and unreachable code analysis.
```
Comment (Aivolt1) [inline Changelog.md:17]: Approved

**Review by Aivolt1 — DISMISSED** [review]

File: libsolidity/codegen/ir/IRGeneratorForStatements.h [hunk 12]
```diff
@@ -86,7 +86,10 @@ class IRGeneratorForStatements: public IRGeneratorForStatementsBase
 	IRVariable evaluateExpression(Expression const& _expression, Type const& _to);
 
 	/// Defines @a _var using the value of @a _value while performing type conversions, if required.
-	void define(IRVariable const& _var, IRVariable const& _value) { declareAssign(_var, _value, true); }
+	void define(IRVariable const& _var, IRVariable const& _value, bool _forceCleanup = false)
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.h]: One last thing ;-). It might be nice to document ``_forceCleanup`` in the comment here (and also for ``convert``), similar to the comment at ``expressionAsType``.

**Review by Aivolt1 — APPROVED** [review]

File: test/libsolidity/semanticTests/userDefinedValueType/erc20.sol [hunk 13]
```diff
@@ -115,7 +115,7 @@ contract ERC20 {
 // ----
 // constructor()
 // ~ emit Transfer(address,address,uint256): #0x00, #0x1212121212121212121212121212120000000012, 0x14
-// gas irOptimized: 442239
+// gas irOptimized: 447831
```
Comment (ekpyron) [inline test/libsolidity/semanticTests/userDefinedValueType/erc20.sol:118]: We should (separately) investigate the increase in gas cost here and check if it can be avoided. But for now I'll approve and merge this PR.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 14]
```diff
@@ -1035,7 +1035,10 @@ void IRGeneratorForStatements::endVisit(FunctionCall const& _functionCall)
 						")\n";
 				}
 				else
-					indexedArgs.emplace_back(convert(arg, *paramTypes[i]));
+				{
+					solAssert(parameterTypes[i]->sizeOnStack() == 1, "");
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1039]: Actually, since we now ended up not using ``expressionAsType``, we don't really need this assertion anymore - so we could remove it again. I'll approve nonetheless.

**Review by ekpyron — APPROVED** [review]
