### PR TITLE
Store compiler version in CBOR metadata

### LINKED ISSUE #2741: Metadata CBOR to contain compiler version
The idea is that it can be figured out easily if a contract uses a broken compiler version and therefore should not be trusted.

One could argue against this though that contracts which don't have their metadata JSON uploaded to Swarm should not be trusted and once it is uploaded the version can be verified within.

Note: libraries already include a version byte (though not as part of the metadata). We could consider replacing that version byte with one in the metadata CBOR or use the same compact form in the metadata CBOR.

### PR DESCRIPTION
**Pull request by axic**
Fixes #2741.

### CODE REVIEW

**Comment by axic** [comment]
The version is 8 bytes long plus the CBOR encoding makes it 14 bytes extra data to be added to each contract. Given the deployed code has it plus the creator code, this results in ~4000 gas extra cost on a regular contract.

Need to evaluate whether it is worth it.

**Comment by axic** [comment]
Decision: if can make this cost around 2500 gas we merge it, otherwise ignore it for now - can leave the issue and invite opinions from the community.

Proposal: change the 64bit version number into 32bit where the top byte contains a flag: 1. bit means it is a non-release.

File: test/libsolidity/Metadata.cpp [hunk 1]
```diff
@@ -81,14 +80,13 @@ BOOST_AUTO_TEST_CASE(metadata_stamp_experimental)
...
 	bytes hash = dev::swarmHash(metadata).asBytes();
 	BOOST_REQUIRE(hash.size() == 32);
-	BOOST_REQUIRE(bytecode.size() >= 2);
-	size_t metadataCBORSize = (size_t(bytecode.end()[-2]) << 8) + size_t(bytecode.end()[-1]);
-	BOOST_REQUIRE(metadataCBORSize < bytecode.size() - 2);
+	bytes cborMetadata = dev::test::onlyMetadata(bytecode);
+	BOOST_REQUIRE(!cborMetadata.empty());
 	bytes expectation =
-		bytes{0xa2, 0x65, 'b', 'z', 'z', 'r', '0', 0x58, 0x20} +
+		bytes{0xa3, 0x65, 'b', 'z', 'z', 'r', '0', 0x58, 0x20} +
```
Comment (axic) [inline test/libsolidity/Metadata.cpp]: In order to fix the tests, need to implement a helper: `parseCBORMetadata(bytes) -> map<string,string>`. This would parse strings into strings, bytes into hex strings and booleans into true/false strings.

The map could be then properly used in the tests.

Comment (axic) [reply test/libsolidity/Metadata.cpp]: Done #6233.

**Comment by axic** [comment]
This should now pass the tests, it is only a matter of agreeing on the acceptable overhead.

File: libsolidity/interface/CompilerStack.cpp [hunk 2]
```diff
@@ -1022,22 +1022,29 @@ string CompilerStack::createMetadata(Contract const& _contract) const
...
+		// CBOR-encoding of the version string (ByteString)
+		((versionBytesSize <= 23) ? bytes{static_cast<unsigned char>(0x40 + versionBytesSize)} : bytes{0x58, static_cast<unsigned char>(versionBytesSize)}) + versionBytes;
 	bytes cborEncodedMetadata;
 	if (_experimentalMode)
 		cborEncodedMetadata =
 			// CBOR-encoding of {"bzzr0": dev::swarmHash(metadata), "experimental": true}
-			bytes{0xa2} +
+			bytes{0xa3} +
 			cborEncodedHash +
 			bytes{0x6c, 'e', 'x', 'p', 'e', 'r', 'i', 'm', 'e', 'n', 't', 'a', 'l', 0xf5};
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: This is rediculous. Let's just add the 10 (?) additional bytes for the version string.

I see that it includes the commit hash. Do we really need that?

**Comment by axic** [comment]
Decision from call:
1) for release version the `solc` key has a `ByteString` value consisting of 3 bytes: major, minor, patch
2) for non-release versions the `solc` key has a `TextString` value consisting of the entire compiler version text

**Comment by axic** [comment]
Since the release case cannot be easily tested, perhaps add a script to the release process which validates it.

**Comment by axic** [comment]
@chriseth this is becoming ever so more complicated. How do you feel about having a tiny class encode CBOR?

```
class MetadataCBOREncoder
{
        void pushBytes(string const& key, bytes const& value);
        void pushString(string const& key, string const& value);
        void pushBool(string const& key, bool value);
        // Prepends fixed-length map key and the 16 bit length at the end.
        bytes finalise();
}
```

It would need to either make an entire copy in `finalise` or keep the values as a map and serialise them on `finalise`.

**Comment by axic** [comment]
@chriseth I'll squash some commits before merge, but it would be ok to review this now.

**Comment by chriseth** [comment]
Tests are failing.

**Comment by axic** [comment]
> Tests are failing.

Haven't updated the expected bytecode in StandardCompiler and the length check in the optimiser ones.

The main test case is `libsolidity/Metadat` which is updated.

File: libsolidity/interface/Version.cpp [hunk 3]
```diff
@@ -44,6 +44,34 @@ string const dev::solidity::VersionStringStrict =
 	(string(SOL_VERSION_PRERELEASE).empty() ? "" : "-" + string(SOL_VERSION_PRERELEASE)) +
 	(string(SOL_VERSION_COMMIT).empty() ? "" : "+" + string(SOL_VERSION_COMMIT));
 
+bytes const dev::solidity::VersionCompactBytes = compactBinaryVersion();
+
+bool const dev::solidity::VersionIsRelease = string(SOL_VERSION_PRERELEASE).empty();
+
+bytes dev::solidity::compactBinaryVersion()
+{
+	bytes ret{};
```
Comment (chriseth) [inline libsolidity/interface/Version.cpp]:
```suggestion
	bytes ret;
```

File: libsolidity/interface/Version.cpp [hunk 4]
```diff
@@ -44,6 +44,34 @@ string const dev::solidity::VersionStringStrict =
...
+	size_t i = 0;
+	auto parseDecimal = [&]()
```
Comment (chriseth) [inline libsolidity/interface/Version.cpp]: Code duplication.

**Comment by chriseth** [comment]
Looks good. We should probably create a pull request with `prerelease.txt` present to check the CI.

File: libsolidity/interface/Version.cpp (hunk 4 above)
Comment (axic) [reply libsolidity/interface/Version.cpp]: Turns out `binaryVersion` is not used anymore in the code base. How about we just change it to return the 3-byte version?

Comment (axic) [reply libsolidity/interface/Version.cpp]: @chriseth what do you think?

Comment (chriseth) [reply libsolidity/interface/Version.cpp]: Sounds good!

**Comment by chriseth** [comment]
Todo:
 - remove duplicate code
 - test with `prerelease.txt`

**Comment by ekpyron** [comment]
After discussing with @chriseth:
We'll replace the cmdline gas tests with isoltest types to be able to update expectations for release and prerelease simultanously. The standard-json test involving gas estimates will have the gas estimate part removed (although we'll need to consider whether it should be tested in some way nonetheless).

File: test/cmdlineTests/standard_binaries_requested/output.json [hunk 5]
```diff
@@ -1 +0,0 @@
-{"contracts":{"A":{"C":{"evm":{"gasEstimates":{"creation":{"codeDepositCost":"19800","executionCost":"75","totalCost":"19875"},"external":{"f()":"122"}}}}}},"sources":{"A":{"id":0}}}
```
Comment (ekpyron) [inline test/cmdlineTests/standard_binaries_requested/output.json:1]: All requests that trigger binary generation will either output the bytecode that will change volatilely for prerelease versions or the gas estimates, which will also change volatilely for prerelease versions, so I don't see a good way to keep this test.

File: libsolidity/interface/Version.cpp [hunk 6]
```diff
@@ -44,36 +44,10 @@ string const dev::solidity::VersionStringStrict =
...
-	solAssert(i + 7 < VersionString.size(), "");
-	bytes commitHash = fromHex(VersionString.substr(i, 8));
-	solAssert(!commitHash.empty(), "");
-	ret += commitHash;
-	solAssert(ret.size() == 1 + 3 + 4, "");
-
-	return ret;
-}
+bytes const dev::solidity::VersionCompactBytes = {
+	ETH_PROJECT_VERSION_MAJOR,
```
Comment (ekpyron) [inline libsolidity/interface/Version.cpp:48]: I don't see a reason for decoding the version string here at runtime instead of passing in the version as numbers at compile time - this is much simpler and has the additional advantage that compilation should fail, if we'd happen to have version numbers >=256.

**Comment by ekpyron** [comment]
I now adjusted this to allow putting the compiler stack in a "fake release" mode for the gas estimate tests - I think the gas costs in "prerelease mode" are too fragile due to the version itself changing in string length and on top of that the build date being encoded into it, which will regularly change in size as well. And this doesn't merely affect bytecode size, but also changes the deployed code size in the ``codecopy`` command in the constructor bytecode, which might now randomly be stored using different numbers of bytes and possibly involving zero bytes; all of that affecting gas costs. I'd argue that it's more important to test release numbers anyways, so I'd say this is fine.

I simplified the new ``GasTest`` class in the test suite accordingly (in the current version of this PR there's no need to treat creation gas costs specially anymore).

@chriseth Do you think this is reasonable or should I look into reliably calculating the difference between release and prerelease gas costs?

File: test/libsolidity/GasCosts.cpp [hunk 7]
```diff
@@ -66,20 +66,21 @@ BOOST_AUTO_TEST_CASE(string_storage)
 			}
 		}
 	)";
+	m_compiler.overwriteReleaseFlag(true);
 	compileAndRun(sourceCode);
 
 	if (Options::get().evmVersion() <= EVMVersion::byzantium())
-		CHECK_GAS(133899, 130591, 100);
```
Comment (chriseth) [inline test/libsolidity/GasCosts.cpp:72]: 2500 gas for the additional field, even in release mode?

File: test/libsolidity/GasTest.cpp [hunk 8]
```diff
@@ -83,42 +67,28 @@ GasTest::GasTest(string const& _filename)
...
+	map<std::string, std::string>* currentKind = nullptr;
+	string line;
 
 	while (getline(_stream, line))
-		if (boost::starts_with(line, "// creation:"))
+		if (!boost::starts_with(line, "// "))
+			BOOST_THROW_EXCEPTION(runtime_error("Invalid expectation: expected \"// \"."));
+		else if (boost::ends_with(line, ":"))
 		{
-			auto it = line.begin() + 12;
```
Comment (chriseth) [inline test/libsolidity/GasTest.cpp:92]: What are these changes?

Comment (ekpyron) [reply test/libsolidity/GasTest.cpp:92]: If we only test in release mode, we don't need to parse the integer value of the creation cost, but we can treat the ``creation`` part exactly like ``internal`` and ``external`` (i.e. just use string comparison). When I wrote this earlier I expected that we would adjust the creation gas cost values depending on the release/prerelease mode, but if we end up not doing that, this can be simplified.

File: test/libsolidity/GasCosts.cpp (hunk 7 above)
Comment (ekpyron) [reply test/libsolidity/GasCosts.cpp:72]: It's 9 additional bytes to be stored on chain costing ```9*200 = 1800``` - that's what our gas estimation tests tell... I'm not sure about the remainder - maybe those 9 bytes have to be sent for the creation transaction costing ```9*68 = 612``` on top of the 1800? Not sure why that'd be missing from our estimation then, though...

**Review by chriseth — DISMISSED** [review]
Please add a changelog entry.

**Comment by ekpyron** [comment]
~~This should probably also be documented - I'll do that as well!~~ Done

File: Changelog.md [hunk 9]
```diff
@@ -8,6 +8,7 @@ Compiler Features:
  * SMTChecker: Support inherited state variables.
  * SMTChecker: Support tuples and function calls with multiple return values.
  * SMTChecker: Support ``delete``.
+ * Metadata: Add another field encoding the compiler version to the CBOR metadata.
```
Comment (chriseth) [inline Changelog.md]: Hm, the metadata is the json whose hash is part of the code - this is something we probably do not have a name for yet...

File: docs/metadata.rst [hunk 10]
```diff
@@ -131,23 +131,28 @@ encoding is not easy to find, its length is added in a two-byte big-endian
 encoding. The current version of the Solidity compiler usually adds the following
 to the end of the deployed bytecode::
 
-    0xa1 0x65 'b' 'z' 'z' 'r' '0' 0x58 0x20 <32 bytes swarm hash> 0x00 0x29
+    0xa2
+    0x65 'b' 'z' 'z' 'r' '0' 0x58 0x20 <32 bytes swarm hash>
+    0x64 's' 'o' 'l' 'c' 0x43 <3 byte version encoding>
```
Comment (chriseth) [inline docs/metadata.rst:136]: I think the version should already be mentioned in the first paragraph.

File: Changelog.md (hunk 9 above)
Comment (chriseth) [reply Changelog.md]: Perhaps "Assembler: encode the compiler version in the deployed bytecode"?

Comment (ekpyron) [reply Changelog.md]: In ``0.4.16`` we have ``Metadata: Store experimental flag in metadata CBOR.`` :-). But I'll change it anyways!

File: docs/metadata.rst (hunk 10 above)
Comment (ekpyron) [reply docs/metadata.rst:136]: Updated.

**Review by chriseth — APPROVED** [review]
