### PR TITLE
Fix the Heisenbug

### LINKED ISSUE #3718: Heisenbug - sigsegv when using --ast
Solidity has had a bug for a long time on MacOS that only occurs in release builds and is related to the move constructor or move-assignment operator of `std::map`. It might be related to some versions of the standard library only and migth also occur only for certain versions of the compiler. This bug report is one instance of it.

----
Original description:

Just about every contract I have tried with the `--ast` option has given sigsegv.
```
$ solc --ast node_modules/zeppelin-solidity/contracts/math/SafeMath.sol 
node_modules/zeppelin-solidity/contracts/math/SafeMath.sol:9:3: Warning: Function state mutability can be restricted to pure
  function mul(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
node_modules/zeppelin-solidity/contracts/math/SafeMath.sol:15:3: Warning: Function state mutability can be restricted to pure
  function div(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
node_modules/zeppelin-solidity/contracts/math/SafeMath.sol:22:3: Warning: Function state mutability can be restricted to pure
  function sub(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
node_modules/zeppelin-solidity/contracts/math/SafeMath.sol:27:3: Warning: Function state mutability can be restricted to pure
  function add(uint256 a, uint256 b) internal constant returns (uint256) {
  ^
Spanning multiple lines.
Segmentation fault: 11
```

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.20+commit.3155dd80.Darwin.appleclang
```

### PR DESCRIPTION
**Pull request by alibabe**
Fixes #3718 

I tried adding customized move assignment operator and copy assignment operator to GasConsumption and ASTNode with no luck. However, I am able to fix the issue by assigning the result of breakToStatementLevel to a local variable, then assign it back to gasCosts.

Let me know if this is enough

### CODE REVIEW

**Comment by chriseth** [comment]
Oh wow! Are you sure this is the only place? We should have many more uses of the move assignment operator for maps, and actually this should not even use the move assignment operator but rather return value optimization.

**Comment by alibabe** [comment]
I tested the change using `--ast`, `--ast-json` and `--ast-compact-json` option. And segmentation faults are gone. Are we looking for solving the problem for just these three options? Or are we trying to fix all the miss uses of map assignment? I probably won't be able to solve the later, since Im not very familiar with the code base.

File: solc/CommandLineInterface.cpp [hunk 1]
```diff
@@ -987,10 +987,13 @@ void CommandLineInterface::handleAst(string const& _argStr)
 		map<ASTNode const*, eth::GasMeter::GasConsumption> gasCosts;
 		// FIXME: shouldn't this be done for every contract?
 		if (m_compiler->runtimeAssemblyItems(m_compiler->lastContractName()))
-			gasCosts = GasEstimator::breakToStatementLevel(
+ 		{
+			auto ret = GasEstimator::breakToStatementLevel(
```
Comment (axic) [inline solc/CommandLineInterface.cpp]: If we go with merging this fix/workaround, please leave an explanatory comment here, otherwise this may be "optimized out" by future changes/people.

**Comment by chriseth** [comment]
The thing is that I don't see the slightest problem with the previous version of the code. If this is a workaround, we should evaluate why it works and what it works around.

What is special about this function is that it is static and uses lambda functions that capture the variable to be returned, but I don't see why this should be a problem.

If you add a comment, we can take this PR as fixing the problem, because it is an improvement at very low cost.

**Comment by alibabe** [comment]
I added some comments. Agree on root causing. I am also wondering why it fixes it too. Thinking if @wjmelements who reports the problem or someone else who is able to reproduce could verify the fix on his end?

**Comment by vs77bb** [comment]
@alibabe @chriseth Is this still in progress? Just checking 👍

**Comment by alibabe** [comment]
@vs77bb I added some comments to the pull request. Let me know if this is enough for this issue.

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -990,10 +990,15 @@ void CommandLineInterface::handleAst(string const& _argStr)
...
 		if (m_compiler->runtimeAssemblyItems(m_compiler->lastContractName()))
-			gasCosts = GasEstimator::breakToStatementLevel(
+		{
+			//NOTE: keep the local variable `ret` to prevent a Heisenbug that could happen on certain mac os platform.
+			//See: https://github.com/ethereum/solidity/issues/3718 for details.
+			auto ret = GasEstimator::breakToStatementLevel(
 				GasEstimator(m_evmVersion).structuralEstimation(*m_compiler->runtimeAssemblyItems(m_compiler->lastContractName()), asts),
 				asts
 			);
+			gasCosts = ret;
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp:1000]: Could you check if the bug is present when we use `gasCosts = std::move(ret);` here?

Comment (alibabe) [reply solc/CommandLineInterface.cpp:1000]: After I added `gasCosts = std::move(ret);` the bug is back.

Comment (chriseth) [reply solc/CommandLineInterface.cpp:1000]: Great, thanks! This confirms that

1. the bug actually is due to the move-assignment operator
2. the workaround adds the complexity of an actual copy operation

The question remains: Do we want to have this workaround? The bug does not seem to be present for recent versions of macos / xcode.

@alibabe could you tell us your version of macos, xcode, boost, etc, so we could perhaps add this workaround only selectively?

Comment (alibabe) [reply solc/CommandLineInterface.cpp:1000]: Mac OS: 
```
El Capitan 10.11.6 (15G21013)
```

Xcode: 
not used

boost:
```sh
>> grep "#define BOOST_VERSION" /usr/local/include/boost/version.hpp
#define BOOST_VERSION_HPP
#define BOOST_VERSION 106600
```

clang: 
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

libc:
```
>> otool -L $(where solc)
/usr/local/bin/solc:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Comment (chriseth) [reply solc/CommandLineInterface.cpp:1000]: Thanks a lot (and also thanks for your patience)!
One important piece of information is also the version of the standard library you link against - is that directly visible from the clang version or the target?

Comment (alibabe) [reply solc/CommandLineInterface.cpp:1000]: updated above

Comment (erak) [reply solc/CommandLineInterface.cpp:1000]: @alibabe @chriseth The bug indeed doesn't seem to be present when linking newer versions of the standard library. I can't reproduce it on my machine with the following setup: 

macOS Sierra 10.12.6
Clang 9.0.0

and ``otool -L solc`` outputs:
```
/usr/local/opt/z3/lib/libz3.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

I think we should try to selectively apply this workaround to older versions of macOS / clang since it can be really annoying to people that don't want or can't update their system.

Comment (erak) [reply solc/CommandLineInterface.cpp:1000]: We could try using ``CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang"`` and ``CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9.0.0`` for that.

Comment (erak) [reply solc/CommandLineInterface.cpp:1000]: @alibabe Could you please check the libc++ version number that is defined through ``_LIBCPP_VERSION`` in ``/Library/Developer/CommandLineTools/usr/include/c++/v1/__config``?

Comment (alibabe) [reply solc/CommandLineInterface.cpp:1000]: @bit-shift I have `#define _LIBCPP_VERSION 3700` on my environment

Comment (erak) [reply solc/CommandLineInterface.cpp:1000]: Great! Thanks. That means we could conditionally compile the workaround using (haven't tested with clang on Linux and Windows though)
```
#if defined(_LIBCPP_VERSION) && (_LIBCPP_VERSION == 3700)
	#define LIBCPP_MOVE_WORKAROUND
#endif
```
@chriseth What do you think? I'm not sure if we should fix it to this one version or also apply it to older ones. Perhaps even ``_LIBCPP_VERSION < 4000``?

Comment (chriseth) [reply solc/CommandLineInterface.cpp:1000]: I would use `_LIBCPP_VERSION < 4000`, because we do not know when it was fixed.

Comment (alibabe) [reply solc/CommandLineInterface.cpp:1000]: @bit-shift How do you know its the libc++ that's causing the issue? 
@chriseth even if we do `_LIBCPP_VERSION < 4000` it's not guaranteed to fix the issue, right? because we don't know when it was fixed

Comment (erak) [reply solc/CommandLineInterface.cpp:1000]: @alibabe As already confirmed, the buggy move-assignment operator triggers the segmentation fault. This is part of the C++ standard library (which is implemented by libc++). I have a newer version of libc++ (307.5.0, ``_LIBCPP_VERSION 4000``) and can't reproduce the segfault, which means that the bug seems be gone with that version.

Comment (alibabe) [reply solc/CommandLineInterface.cpp:1000]: updated PR

File: solc/CommandLineInterface.cpp [hunk 3]
```diff
@@ -990,10 +990,22 @@ void CommandLineInterface::handleAst(string const& _argStr)
 		map<ASTNode const*, eth::GasMeter::GasConsumption> gasCosts;
 		// FIXME: shouldn't this be done for every contract?
 		if (m_compiler->runtimeAssemblyItems(m_compiler->lastContractName()))
+		{
+			//NOTE: keep the local variable `ret` to prevent a Heisenbug that could happen when use move assignment.
+			//See: https://github.com/ethereum/solidity/issues/3718 for details.
+			#if defined(_LIBCPP_VERSION) && (_LIBCPP_VERSION < 4000)
```
Comment (axic) [inline solc/CommandLineInterface.cpp]: I think for clarity I'd just have this copying code used always with a big fat comment explaining the reasoning (libc on macos is broken on certain versions).

The problem with this ifdef is that very likely this branch won't be tested (compiled) on the CI and therefore any missing change applied to there will not be caught.

This isn't a speed/memory critical piece of code since it is the CLI and as a such a copy shouldn't hurt too much.

However we could still figure out the reason this move operator fails, because move operators are used extensively in the code and I wonder if it fails in other places too or the data structure returned here has a particular reason for breaking the broken libc.

Comment (alibabe) [reply solc/CommandLineInterface.cpp]: @bit-shift @chriseth do you have any objections to @axic's suggestion? I can revert the change with more comments. I agree with @axic that if the code is not performance critical just copying is better.

Comment (erak) [reply solc/CommandLineInterface.cpp]: @alibabe I think @axic's objection to the current solution is reasonable. We'd probably need to create another build plan that uses an older version of XCode / clang / libc++ to also build and test a binary containing the workaround. I'm also fine with applying this in general (and accepting the additional copy).

@axic Does it make sense to merge this regardless of any other potential issues with the move-assignment operator in our code base? Right now we don't have a development environment that we could use to investigate this further.

**Comment by chriseth** [comment]
@alibabe ok, please revert, but add comments documenting our findings (the ifdef statement for example would already be enough).

**Comment by axic** [comment]
> However we could still figure out the reason this move operator fails, because move operators are used extensively in the code and I wonder if it fails in other places too or the data structure returned here has a particular reason for breaking the broken libc.

I would also stress part of the comment ^^

Is only this exact `move` operator failing or are there are other cases? If only this one, why? Does it have an unusual construct?

**Comment by alibabe** [comment]
I reverted the latest commit. Will try to spend some time to see if I can answer @axic's question.

**Comment by alibabe** [comment]
So `std::map` is the culprit. See code here: https://gist.github.com/alibabe/cfe2b99a935f9c3f82fd6e71bcb03d58

If I run `testMoveU256 `, no issue.
If I run `testMoveGas`, no issue.
If I run `testMap` or `testMoveU256Map` or `testMoveGasMap` all seg fault at move assignment. 

This could be related to: https://bugs.llvm.org/show_bug.cgi?id=30449

edit: Its the std::map that's having issue, not `u256` @wjmelements

**Comment by wjmelements** [comment]
u256 is boost::multiprecision::number<boost::multiprecision::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>>.

edit:
according to: https://github.com/aionnetwork/aion_fastvm/blob/master/solidity/libdevcore/Common.h#L92

**Comment by chriseth** [comment]
Could you please check if #4473 fixes the heisenbug?

**Comment by alibabe** [comment]
@chriseth tried #4473 with no luck. Still got segmentation fault. 

Given my gist link above, now im pretty convinced that it's the `std::map`'s problem. @wjmelements ru still able to reproduce the issue? Can you help verify?

**Comment by wjmelements** [comment]
From what I can tell this is a Boost problem, and that the fix is to fix the u256 move constructor rather than to ensure we don't use the u256 move constructor anywhere.

**Comment by wjmelements** [comment]
I have verified the current fix.

**Comment by chriseth** [comment]
@wjmelements I agree that we should try to fix the root of the problem but are you sure it is a boost issue instead of a stdlib issue? @alibabe which boost version do you use?

**Comment by alibabe** [comment]
Im using Boost 1.66 
@wjmelements how you know its u256? I tried just move on u256 without seg fault

```
void testMoveU256() {
    u256 a = 1;

    std::cout<< "testMoveU256()" << std::endl;
    u256 b = std::move(a);
    std::cout << b << std::endl;
}
```

**Comment by chriseth** [comment]
I'm pretty sure it is a combination of `std::map` and perhaps `u265`.

**Comment by alibabe** [comment]
@chriseth 
Here is another reproduce where u256 is not used -  [llvm bug report](https://bugs.llvm.org/show_bug.cgi?id=30449). 
```
struct alignas(16) Foo { int val; };
void testMap() {
    std::map<int, Foo> m;
    std::map<int, Foo> n{{1,{1}}};
    std::cout << "GOT HERE" << std::endl;
    m = std::move(n);  //  segfault happens here
    std::cout << "GOT HERE TOO" << std::endl;
}
```

**Comment by chriseth** [comment]
Oh wow, thanks a lot! This might indeed be the root problem. u256 could likely use alignment specifiers.

**Comment by chriseth** [comment]
Ok, we now know where this is coming from, so I think we should just merge it. If it turns out to be a performance killer, we can add a switch.
