### PR TITLE
ossfuzz: Fixes buggy generation of duplicate case literals

### LINKED ISSUE #6538: [ossfuzz] proto generator generates duplicate case literals in switch statements
## Description

A switch statement in yul can have case literals that are decimal, hexadecimal, or string. The yul parser treats more than one case statement with identically valued literals as duplicates.

The proto generator does not respect this logic while generating random yul code, so we could end up with code like this (which is simply rejected by the parser)

```
$ cat code.yul
{
  let x
  switch x
    case 1 {}
    case 1 {}
}
$ solc --strict-assembly code.yul
5:5: Error: Duplicate case defined.
    case 1 {}
    ^-------^
```

Although such unparseable code accounts for about 1% of the total number of randomly generated test cases, it is a bug that needs to ensure the proto generator produces valid yul code only.

### PR DESCRIPTION
**Pull request by bshastry**
(closes #6538)

### CODE REVIEW

File: test/tools/ossfuzz/protoToYul.cpp [hunk 1]
```diff
@@ -50,6 +50,41 @@ string ProtoConverter::createAlphaNum(string const& _strBytes) const
...
+			if (tmp.empty())
+			{
+				isEmptyString = true;
+				tmp = std::to_string(0);
+			}
+			else
+				tmp = "\"" + tmp + "\"";
+			break;
+		case Literal::LITERAL_ONEOF_NOT_SET:
+			tmp = std::to_string(1);
```
Comment (chriseth) [inline test/tools/ossfuzz/protoToYul.cpp:77]: Does that mean that the "default" case has value 1? Does that also mean that the following code will never be generated:
```
switch x
case 1 { ... }
default { ... }
```
?

Comment (chriseth) [reply test/tools/ossfuzz/protoToYul.cpp:77]: Shouldn't you just return `false` here without adding the case value to the set?

Comment (bshastry) [reply test/tools/ossfuzz/protoToYul.cpp:77]: > Does that mean that the "default" case has value 1?

No, the grammar for default statement is "default BLOCK", so it visits a `Block` instead. This special casing for unset literals is needed because we use the `oneof` directive from the protobuf language which means `at most one of`. So it could happen that the protobuf mutator synthesizes a case statement with an unset string literal.

> Shouldn't you just return false here without adding the case value to the set?

If we return `false` here, then it could happen that we generate a syntactically incorrect snippet like so
```
// switch statement has been visited because there is exactly one case statement
switch x
// case statement is not visited because it's literal is unset
```

and then we run into an unparesable switch statement. Note that `default` case is optional in our spec and not required. If it were changed to `required` (which means that every switch stmt should have a default case) then we could return false. I think we should keep `default` to optional because it exercises the edge-case when a default statement is (correctly) missing.

Comment (bshastry) [reply test/tools/ossfuzz/protoToYul.cpp:77]: May be I should clarify. The `oneof { A, B, C}` directive in protobuf leads to the four cases `{A, B, C, None}`. Unset Literals have nothing to do with default case statement i.e., None does not imply default case. Rather, it is referring to a case statement with an unset literal.

**Comment by chriseth** [comment]
Thanks for the explanation! Please rebase.

**Comment by bshastry** [comment]
Rebased.

**Review by chriseth — APPROVED** [review]
