### PR TITLE
Fix source location of yul variable declarations without value.

### LINKED ISSUE #8838: Yul sourcemaps skip let statements with no initializer
## Description

Not sure if this is a *bug* as such, but Yul sourcemaps skip over any `let` statement that has no initializer.

For instance, if you do `let x := 1`, then the resulting `PUSH1 0x01` will sourcemap to the `1`.  Pretty sensible.  But if you do `let x`, without specifying an initial value, the resulting `PUSH1 0x00` will sourcemap to the previous statement, and not to, say, the `let x` as one might expect.

This poses a problem for, say, Truffle Debugger, which relies on the sourcemap as part of how it locates variables on the stack.  (The interface skips over variable declarations when stepping, but internally we very much rely on hitting them!  Or things related to them, at least, like in the `let x := 1` case above.)  Now presently Truffle Debugger doesn't support assembly variables, of course, but [I wrote a PR to make it do so](https://github.com/trufflesuite/truffle/pull/3018), and this is one point where it falls down -- if the variable is declared with no initializer, the debugger won't see it (with one exception, see below).

Note: This doesn't mean things are *impossible* to handle as they are, but presently I haven't come up with a good way.  Regardless, obviously any such way would necessarily be a hack.

In one case I do handle it because I have to -- if such variables are declared at the beginning of a Yul function, the fact that they're not sourcemapped actually messes with our ability to locate on the stack the parameters to and return values from said function.  Fortunately, I've accounted for this, but it would be more convenient if I didn't have to.

Be aware though that changing this would arguably be breaking.  Like, if you did change this, I'd have to turn *off* the above hack I mention for versions of Solidity where this was fixed.

## Environment

- Compiler version: 0.6.6
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle

## Steps to Reproduce

```solidity
pragma solidity ^0.6.6;

contract AssemblyTest {
  function run() public {
    assembly {
      let x := 1 // 1 is hit
      let v //skipped entirely
      function discard(a) {
        let z //skipped, causing difficulty locating a
        pop(a)
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/8838

### CODE REVIEW

File: libyul/backends/evm/EVMCodeTransform.cpp [hunk 1]
```diff
@@ -184,11 +184,13 @@ void CodeTransform::operator()(VariableDeclaration const& _varDecl)
 	}
 	else
 	{
+		m_assembly.setSourceLocation(_varDecl.location);
```
Comment (mijovic) [inline libyul/backends/evm/EVMCodeTransform.cpp:187]: Is this needed, as there is another call after?

Comment (chriseth) [reply libyul/backends/evm/EVMCodeTransform.cpp:187]: It has to be called before the call to `appendConstant`

**Review by leonardoalt — CHANGES_REQUESTED** [review]
Looks like it needs tests updates

**Review by leonardoalt — DISMISSED** [review]
