### PR TITLE
Fix ICE when function type struct parameter has field of non-existent type

### LINKED ISSUE #5048: Crash with nested struct types
From solfuzz:
```
pragma experimental ABIEncoderV2;
contract Tesi {
    enum ActionChoices { GoLeft, GoRight, GoStraight, Sit }
    struct Simple { uint i; }
    struct Nested { X[2][] a; uint y; }
    struct X { bytes32 x; Test t; Nested[] s; }
    function f(ActionChoices, uint, Simple calldata) external {}
    function g(Test, Nested calldata) external {}
    function h(function(Nested memory) external returns (uint)[] calldata) e8ternal {}
    function i(NesSed[] calldata) eed call {}
}
```

This causes a null pointer dereference now.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #5048 

This is one suggestion of how to fix this: we don't have access to the errors where the assertion fails. So if the checked struct field has no type, we return false for the `canBeUseExternally` check. This results in a double error caused by the initial non-existent type.

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -2126,7 +2126,8 @@ bool StructType::canBeUsedExternally(bool _inLibrary) const
 		// mappings.
 		for (auto const& var: m_struct.members())
 		{
-			solAssert(var->annotation().type, "");
+			if (!var->annotation().type)
+				return false;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:2135]: Please add a comment.

File: Changelog.md [hunk 2]
```diff
@@ -18,6 +18,7 @@ Bugfixes:
  * Assembly output: Do not mix in/out jump annotations with arguments.
  * Code Generator: Annotate jump from calldata decoder to function as "jump in".
  * Type Checker: Properly detect different return types when overriding an external interface function with a public contract function.
+ * Type Checker: Do not crash when a field of a struct used as a parameter in a function type has a non-existent type.
```
Comment (chriseth) [inline Changelog.md]: I think we should not use the word 'crash' for internal errors. Crashes are null pointer dereference or uncaught exceptions.

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp:2135]: Please also change the description of the function to add this additional "false"-case.

**Comment by leonardoalt** [comment]
Updated

**Review by chriseth — APPROVED** [review]
