### PR TITLE
Store whether an evmasm Assembly is creation code.

### LINKED ISSUE #11118: Understanding creation context when optimizing Yul subobjects
Currently, we assume that all Yul subobjects are in runtime context: https://github.com/ethereum/solidity/blob/develop/libyul/AssemblyStack.cpp#L177 (the second parameter `false`.)

However, this is not true in general.

Take for example, 

```
  contract C {
	  constructor () {
		  assembly {
			  sstore(0, shl(180, 1))
		  }
		  new D();
	  }
  }
  contract D {
	  constructor() {
		  assembly {
			  sstore(1, shl(180, 1))
		  }
	  }
	  fallback() external {
		assembly {
			sstore(2, shl(180, 1))
		}
	  }
  }
```

From the context of `C`, both `D`'s constructor and `fallback` will have `shl(180, 1)` expanded. In this case, this would lead to more expensive construction code.

-----

One solution is that the context of each sub-object should be stored in the C++ data structure. But this runs into another problem for the following code:

```
  contract C {
	  D d;
	  constructor () {
		  d = new D();
		  d.f();
	  }
	  fallback() external {
		  d.f();
	  }
  }
  contract D {
	  constructor() {
		  assembly {
			  sstore(1, shl(180, 1))
		  }
	  }
	  function f() public {
		  assembly {
			  sstore(2, shl(180, 1))
		  }
	  }
  }
```

In this example, optimizing the sub-object `D.f` with creation context would mean that the calling C's constructor is cheaper, but making the call to fallback more expensive at runtime.  Somehow we have to understand which among the two options would be cheaper overall and optimize according to that. We might require a gas estimator for Yul to properly do this.

### LINKED ISSUE #12738: `creationCode` via IR does not match the compiler's `--bin` output when the contract has a constructor with `bytes` arguments
## Description
In contracts compiled with the `--experimental-via-ir` option, the bytecode returned from `type(C).creationCode` does not match the one the compiler returns from `--bin` when there's a constructor accepting a `bytes` argument.

```solidity
contract C {
    constructor(bytes memory x) {}
}
```
It does not happen if the constructor has a `unit` parameter or no parameters at all.

I discovered this when I re-enabled tests in the `ir-optimize-evm+yul` preset of ElementFi external test (#12736). Note that in that PR I had to disable some tests due to known issues with Hardhat's heuristics not working with the new codegen. The remaning tests pass with the legacy codegen but 15 of them fail via IR. The bug is the cause of some of these failures.

It's the easiest to reproduce with a framework like Hardhat because this way it's possible to compare compiler output directly. We'll need #11424 to be able to compare the bytecode in isoltest (and #12737 could also be an issue).

## Environment

- Compiler version: 0.8.12 and `develop`
- Framework/IDE: Hardhat 2.9.0
- Operating system: Arch Linux

The issue is reproducible as far back as 0.8.2. On 0.8.1 Hardhat crashes. On 0.8.0, 0.7.6 and 0.7.5 the compiler crashes. On 0.7.4 and earlier `viaIR` option was not available.

## Steps to Reproduce

Run this in the shell:
```bash
mkdir test/ contracts/

cat <<EOF > hardhat.config.js
require("@nomiclabs/hardhat-waffle");

module.exports = {
    solidity: {
        compilers: [{
            version: "0.8.12",
            settings: {
                viaIR: true,
                optimizer: { enabled: true },
                metadata: { "bytecodeHash": "none" },
            },
        }]
    }
};
EOF

cat <<EOF > test/CreationCodeTest.js
const { expect } = require("chai");
const { ethers } = require("hardhat");

const targetJSON = require("../artifacts/contracts/CreationCodeTest.sol/Target.json");

it("Bytecode creationCode should match the bytecode in the artifact", async () => {
    const Factory = await ethers.getContractFactory("Factory");
    const factory = await Factory.deploy();

    expect(await factory.targetCreationCode()).to.equal(targetJSON.bytecode);
});
EOF

cat <<EOF > contracts/CreationCodeTest.sol
contract Target {
    constructor(bytes memory x) {}
}

contract Factory {
    bytes public targetCreationCode = type(Target).creationCode;
}
EOF

npm install hardhat @nomiclabs/hardhat-waffle chai
npx hardhat test
```

```
Compiled 1 Solidity file successfully


  1) Bytecode creationCode should match the bytecode in the artifact

  0 passing (635ms)
  1 failing

  1) Bytecode creationCode should match the bytecode in the artifact:

      AssertionError: expected '0x6080604052346100e95761015d803803806…' to equal '0x6080604052346100e85761015b803803806…'
      + expected - actual

      -0x6080604052346100e95761015d8038038061001981610105565b92833981019060209081818403126100e157805167ffffffffffffffff918282116100d7570183601f820112156100c15780519182116100ca575b610066601f8301601f19168401610105565b938285528383830101116100c15781906000905b848383106100a95750501161009b575b505050604051602490816101398239f35b60009201015238808061008a565b8193508281939201015182828801015201829161007a565b50505050600080fd5b6100d26100ee565b610054565b5050505050600080fd5b505050600080fd5b600080fd5b50634e487b7160e01b600052604160045260246000fd5b6040519190601f01601f1916820167ffffffffffffffff81118382101761012b57604052565b6101336100ee565b60405256fe6080604052600080fdfea26c6578706572696d656e74616cf564736f6c634300080c0018
      +0x6080604052346100e85761015b8038038061001981610104565b92833981019060209081818403126100e05780516001600160401b03918282116100d6570183601f820112156100c05780519182116100c9575b610065601f8301601f19168401610104565b938285528383830101116100c05781906000905b848383106100a85750501161009a575b505050604051602490816101378239f35b600092010152388080610089565b81935082819392010151828288010152018291610079565b50505050600080fd5b6100d16100ed565b610053565b5050505050600080fd5b505050600080fd5b600080fd5b50634e487b7160e01b600052604160045260246000fd5b6040519190601f01601f191682016001600160401b0381118382101761012957604052565b6101316100ed565b60405256fe6080604052600080fdfea26c6578706572696d656e74616cf564736f6c634300080c0018

      at Context.<anonymous> (test/CreationCodeTest.js:10:51)
```

The expected value above comes from the `bytecode` field of an artifact produced by Hardhat. This value comes directly from compiler's Standard JSON output, which can be verified by compiling the contract without Hardhat:
```
solc contracts/CreationCodeTest.sol --experimental-via-ir --optimize --metadata-hash none --bin
```
```
======= contracts/CreationCodeTest.sol:Target =======
Binary:
6080604052346100e85761015b8038038061001981610104565b92833981019060209081818403126100e05780516001600160401b03918282116100d6570183601f820112156100c05780519182116100c9575b610065601f8301601f19168401610104565b938285528383830101116100c05781906000905b848383106100a85750501161009a575b505050604051602490816101378239f35b600092010152388080610089565b81935082819392010151828288010152018291610079565b50505050600080fd5b6100d16100ed565b610053565b5050505050600080fd5b505050600080fd5b600080fd5b50634e487b7160e01b600052604160045260246000fd5b6040519190601f01601f191682016001600160401b0381118382101761012957604052565b6101316100ed565b60405256fe6080604052600080fdfea26c6578706572696d656e74616cf564736f6c634300080c0018
```

### PR DESCRIPTION
**Pull request by ekpyron**
Alternative to https://github.com/ethereum/solidity/pull/12744
Fixes https://github.com/ethereum/solidity/issues/12738
Fixes https://github.com/ethereum/solidity/issues/11118

### CODE REVIEW

File: libevmasm/Assembly.cpp [hunk 1]
```diff
@@ -431,13 +431,16 @@ map<u256, u256> const& Assembly::optimiseInternal(
 	if (m_tagReplacements)
 		return *m_tagReplacements;
 
+	assertThrow(_settings.isCreation == m_creation, OptimizerException, "Mismatching creation settings.");
```
Comment (ekpyron) [inline libevmasm/Assembly.cpp]: We could also remove the flag in the settings entirely...

File: test/cmdlineTests/viair_subobject_optimization/input.sol [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// SPDX-License-Identifier: GPL-3.0
+pragma solidity >0.0.0;
+
+contract C {
+  constructor(uint x) {
+    // The constant should be optimized away and occur neither in the bytecode of C
+    // nor embedded in the bytecode of D.
```
Comment (ekpyron) [inline test/cmdlineTests/viair_subobject_optimization/input.sol]: Not sure if we have - or should come up with - a better way to test this...

It might even make sense to compile each and every semantics test contract directly and compare the bytecode with compiling it together with another contract that returns its ``type(...).creationCode``....

File: test/cmdlineTests/viair_subobject_optimization/output [hunk 3]
```diff
@@ -0,0 +1,8 @@
...
+
+======= viair_subobject_optimization/input.sol:D =======
+Binary:
+6080806040523461001657610203908161001d8239f35b50600080fdfe6080806040526004361015610015575b50600080fd5b600090813560e01c6326121ff01461002d575061000f565b3461009657816003193601126100965760ce603f8101601f1916820167ffffffffffffffff81118382101761007f5761007b93506040528082526100f260208301396040519182918261009a565b0390f35b5050634e487b7160e01b8252506041600452602490fd5b5080fd5b919091602080825283519081818401526000945b8286106100db5750508060409394116100ce575b601f01601f1916010190565b60008382840101526100c2565b85810182015184870160400152948101946100ae56fe6080806040523460525760ce80380390601f19601f8301168301918383106001600160401b03841117605857808492602094604052833981010312605257604590516072565b604051604d908160818239f35b50600080fd5b50505050634e487b7160e01b600052604160045260246000fd5b60be600160481b031460525756fe6080604052600080fdfea26c6578706572696d656e74616cf564736f6c63782b302e382e31332d646576656c6f702e323032322e332e372b636f6d6d69742e37633931646430352e6d6f640041a26c6578706572696d656e74616cf564736f6c63782b302e382e31332d646576656c6f702e323032322e332e372b636f6d6d69742e37633931646430352e6d6f640041
```
Comment (ekpyron) [inline test/cmdlineTests/viair_subobject_optimization/output]: Note that on develop this contains ``ffffffffffffffff42``, while the one for ``C`` doesn't.

File: test/cmdlineTests/viair_subobject_optimization/output [hunk 4]
```diff
@@ -0,0 +1,378 @@
...
+          pop
+          pop
+          pop
+          pop
+          mstore(0x00, shl(0xe0, 0x4e487b71))
+          mstore(0x04, 0x41)
+          revert(0x00, 0x24)
+            /* "viair_subobject_optimization/input.sol":76:278  constructor(uint x) {... */
+        tag_1:
+          sub(shl(0x48, 0x01), 0xbe)
```
Comment (ekpyron) [inline test/cmdlineTests/viair_subobject_optimization/output:357]: Note that this is ``0xffffffffffffffff42`` on develop, while it's still constant-optimized in the version above.

File: test/cmdlineTests/yul_optimize_runs/output [hunk 5]
```diff
@@ -5,12 +5,12 @@ Pretty printed source:
...
         {
-            let _1 := datasize("Runtime")
-            datacopy(0, dataoffset("Runtime"), _1)
+            let _1 := datasize("Runtime_deployed")
+            datacopy(0, dataoffset("Runtime_deployed"), _1)
             return(0, _1)
         }
     }
-    object "Runtime" {
+    object "Runtime_deployed" {
```
Comment (ekpyron) [inline test/cmdlineTests/yul_optimize_runs/output:13]: This case now depends on the name of the subobject... which is not really nice...

File: Changelog.md [hunk 6]
```diff
@@ -8,6 +8,7 @@ Compiler Features:
 * JSON-AST: Added selector field for errors and events.
 
 Bugfixes:
+ * Yul Optimizer: Optimize embedded creation code with correct settings. This fixes potential mismatches between the constructor code of a contract compiled in isolation and the bytecode in ``type(C).creationCode``, resp. the bytecode used for ``new C(...)``.
```
Comment (chriseth) [inline Changelog.md]: Shouldn't this also say Yul IR codegen?

File: docs/yul.rst [hunk 7]
```diff
@@ -1124,6 +1124,10 @@ regular strings in native encoding. For code,
 
 Above, ``Block`` refers to ``Block`` in the Yul code grammar explained in the previous chapter.
 
+.. note::
+
+    An object with a name that ends in ``_deployed`` is treated as runtime code by the Yul optimizer.
```
Comment (chriseth) [inline docs/yul.rst]: We should say that the only consequence of this is the tuning of the gas cost heuristic of the optimizer.

File: libevmasm/Assembly.cpp (hunk 1 above)
Comment (chriseth) [reply libevmasm/Assembly.cpp]: Yeah, that actually sounds better.

File: libevmasm/Assembly.h [hunk 8]
```diff
@@ -157,6 +157,8 @@ class Assembly
 	std::vector<size_t> decodeSubPath(size_t _subObjectId) const;
 	size_t encodeSubPath(std::vector<size_t> const& _subPath);
 
+	bool isCreation() const { return m_creation; }
```
Comment (chriseth) [inline libevmasm/Assembly.h:159]: What about changing this to "executedOnce"?

Comment (ekpyron) [reply libevmasm/Assembly.h:159]: The effect in the optimizer is not only adjusting the runs parameter, but also stuff like
``m_params.isCreation ? GasCosts::txDataNonZeroGas(m_params.evmVersion) : GasCosts::createDataGas``
in the constant optimizer calculations...

Comment (chriseth) [reply libevmasm/Assembly.h:159]: Yeah but as I said, for tx data gas, it should be relevant whether it is a top-level object.

Comment (ekpyron) [reply libevmasm/Assembly.h:159]: Yeah, but right now the flag does both, so it's really a "creation mode" flag so far...

If we want to additionally consider whether something is a top-level object, then we run into the same problem again: the compiler would output different bytecode for ``C`` compiled in isolation compared to ``C`` used from another contract ``D``... what we really need is per-contract optimizer settings for this, don't we?

File: libevmasm/Assembly.cpp (hunk 1 above)
Comment (ekpyron) [reply libevmasm/Assembly.cpp]: Done in another commit now.

File: docs/yul.rst [hunk 9]
```diff
@@ -1124,6 +1124,11 @@ regular strings in native encoding. For code,
...
```
Comment (chriseth) [inline docs/yul.rst]:
```suggestion
    An object with a name that ends in ``_deployed`` is treated as deployed code by the Yul optimizer.
```
(creation code is also runtime code)

File: libevmasm/Assembly.h [hunk 10]
```diff
@@ -48,7 +48,7 @@ using AssemblyPointer = std::shared_ptr<Assembly>;
 class Assembly
 {
 public:
-	explicit Assembly(std::string _name = std::string()):m_name(std::move(_name)) { }
+	explicit Assembly(bool _creation, std::string _name): m_creation(_creation), m_name(std::move(_name)) { }
```
Comment (chriseth) [inline libevmasm/Assembly.h]:
```suggestion
	Assembly(bool _creation, std::string _name): m_creation(_creation), m_name(std::move(_name)) { }
```

**Review by chriseth — DISMISSED** [review]

File: libyul/backends/evm/EVMObjectCompiler.cpp [hunk 11]
```diff
@@ -48,7 +50,8 @@ void EVMObjectCompiler::run(Object& _object, bool _optimize)
 	for (auto const& subNode: _object.subObjects)
 		if (auto* subObject = dynamic_cast<Object*>(subNode.get()))
 		{
-			auto subAssemblyAndID = m_assembly.createSubAssembly(subObject->name.str());
+			bool isCreation = !boost::ends_with(subObject->name.str(), "_deployed");
```
Comment (chriseth) [inline libyul/backends/evm/EVMObjectCompiler.cpp:53]: This could actually use a (new) function of IRNames instead of a fixed string, but only if we do that everywhere.

**Review by chriseth — APPROVED** [review]
Using IRNames is probably not viable.
