### PR TITLE
Fix accessing memory reference types in yul codegen and clean up on memory reads.

### LINKED ISSUE #8795: [Sol -> Yul] Cleanup not always done
I think that in the Sol -> Yul translation, cleanup is not always done, at least not before equality comparison. Maybe we should do cleanup for every single type conversion?

Specifically, type conversion does not lead to cleanup when the types are the same. This could lead to problems with regards to inline assembly.

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes https://github.com/ethereum/solidity/issues/8795
~~Depends on https://github.com/ethereum/solidity/pull/8845~~

### CODE REVIEW

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -120,7 +120,7 @@ struct CopyTranslate: public yul::ASTCopier
 
 		return yul::Identifier{
 			_identifier.location,
-			yul::YulString{m_context.localVariable(*varDecl).name()}
+			yul::YulString{m_context.localVariable(*varDecl).commaSeparatedList()}
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: This actually fixes an ICE that occurred in the test, since ``name()`` only works for types with one unnamed stack component, but memory references have one ``mpos`` slot. If you deem it necessary, I assert that it's only one slot here or have a special case for reference types instead.

**Comment by chriseth** [comment]
failures.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `f0a9d2af6821ddc6f535790047addc64aaa5abca`:
```
Coding style error:
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1983: m_utils.splitExternalFunctionIdFunction() <<
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1984: "(mload(" <<
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1985: _memory.address <<
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1986: "))\n";
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1989: "mload(" <<
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1990: _memory.address <<
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1991: ")\n";

```
Please check that your changes are working as intended.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 2]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
-				define(result) <<
-					m_utils.cleanupFunction(_lvalue.type) <<
-					"(mload(" <<
-					_memory.address <<
-					"))\n";
+			if (auto const* functionType = dynamic_cast<FunctionType const*>(&_lvalue.type))
+			{
+				if (functionType->kind() == FunctionType::Kind::External)
+					define(result) <<
+								   m_utils.splitExternalFunctionIdFunction() <<
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1983]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 3]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
+								   "(mload(" <<
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1984]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 4]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
+								   _memory.address <<
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1985]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 5]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
+								   "))\n";
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1986]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 6]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
+				else
+					define(result) <<
+								   "mload(" <<
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1989]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 7]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
+								   _memory.address <<
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1990]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 8]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
...
+								   ")\n";
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1991]: Coding style error

**Comment by ekpyron** [comment]
Should stop failing now...

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 9]
```diff
@@ -1976,18 +1976,30 @@ IRVariable IRGeneratorForStatements::readFromLValue(IRLValue const& _lvalue)
 					")\n";
 		},
 		[&](IRLValue::Memory const& _memory) {
-			if (_memory.byteArrayElement)
-				define(result) <<
-					m_utils.cleanupFunction(_lvalue.type) <<
-					"(mload(" <<
-					_memory.address <<
-					"))\n";
+			if (auto const* functionType = dynamic_cast<FunctionType const*>(&_lvalue.type))
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Should we create a util function for that? There is already something very similar in YulUtilFunctions

Comment (ekpyron) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I'm just looking at the usage - I think I can just make ``readMemory`` always do the cleanup (resp. change ``readFromMemoryOrCalldata`` to cleaning up from memory and validating from calldata) - I think this here is actually the only usage of it. I'll verify.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 10]
```diff
@@ -1764,8 +1764,17 @@ string YulUtilFunctions::cleanupFunction(Type const& _type)
...
 		case Type::Category::Function:
-			solAssert(dynamic_cast<FunctionType const&>(_type).kind() == FunctionType::Kind::External, "");
-			templ("body", "cleaned := " + cleanupFunction(FixedBytesType(24)) + "(value)");
+			switch(dynamic_cast<FunctionType const&>(_type).kind())
+			{
+				case FunctionType::Kind::External:
+					templ("body", "cleaned := " + cleanupFunction(FixedBytesType(24)) + "(value)");
+					break;
+				case FunctionType::Kind::Internal:
+					templ("body", "cleaned := value");
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Any harm in having this?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 9 above)
Comment (ekpyron) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Changed that now instead.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `59934b1693eb1b960b574dc2bcb48203224eb7f4`:
```
Coding style error:
 libsolidity/codegen/YulUtilFunctions.cpp:1767: switch(dynamic_cast<FunctionType const&>(_type).kind())

```
Please check that your changes are working as intended.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 11]
```diff
@@ -1764,8 +1764,17 @@ string YulUtilFunctions::cleanupFunction(Type const& _type)
 			solUnimplemented("Fixed point types not implemented.");
 			break;
 		case Type::Category::Function:
-			solAssert(dynamic_cast<FunctionType const&>(_type).kind() == FunctionType::Kind::External, "");
-			templ("body", "cleaned := " + cleanupFunction(FixedBytesType(24)) + "(value)");
+			switch(dynamic_cast<FunctionType const&>(_type).kind())
```
Comment (stackenbotten) [inline libsolidity/codegen/YulUtilFunctions.cpp:1767]: Coding style error

File: test/libsolidity/semanticTests/viaYul/dirty_memory_read.sol [hunk 12]
```diff
@@ -0,0 +1,14 @@
+contract C {
+	function f() public pure returns (uint8 x, bool a) {
+		uint8[1] memory m;
+		assembly {
+			mstore(m, 257)
+		}
+		x = m[0];
```
Comment (leonardoalt) [inline test/libsolidity/semanticTests/viaYul/dirty_memory_read.sol:7]: Does it make sense to add the weird case `x == 0x0101`? Or does it not relate?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: +1 for assertion

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 10 above)
Comment (leonardoalt) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Wouldn't think so

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 13]
```diff
@@ -2228,18 +2236,23 @@ string YulUtilFunctions::readFromMemoryOrCalldata(Type const& _type, bool _fromC
...
 			}
 		)")
 		("functionName", functionName)
-		("load", _fromCalldata ? "calldataload" : "mload")
-		("needsValidation", _fromCalldata)
-		("validate", _fromCalldata ? validatorFunction(_type) : "")
+		("fromCalldata", _fromCalldata)
+		("validate", validatorFunction(_type))
+		// Apart from reading byte array elements, we primarily clean up anticipating dirty memory writes
+		// form inline assembly. TODO: Rethink that.
```
Comment (leonardoalt) [inline libsolidity/codegen/YulUtilFunctions.cpp]: `Rethink` as in, if this should be done at all, or how to do it?

**Review by leonardoalt — COMMENTED** [review]
Some comments

File: test/libsolidity/semanticTests/viaYul/dirty_memory_read.sol (hunk 12 above)
Comment (ekpyron) [reply test/libsolidity/semanticTests/viaYul/dirty_memory_read.sol:7]: I can add another return value ``b`` and set ``b = (m[0] == 0x0101);`` and expect it to be false?

Comment (leonardoalt) [reply test/libsolidity/semanticTests/viaYul/dirty_memory_read.sol:7]: yep

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 13 above)
Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp]: If it should be done at all - I'll rephrase the comment, though. We'll probably keep doing it, but I'll retain the comment about why.
I wonder how well the optimizer will ever be able to remove the cleanups for these, though...

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 14]
```diff
@@ -2259,18 +2258,23 @@ string YulUtilFunctions::readFromMemoryOrCalldata(Type const& _type, bool _fromC
...
-			function <functionName>(memPtr) -> value {
-				value := <load>(memPtr)
-				<?needsValidation>
+			function <functionName>(ptr) -> value {
+				<?fromCalldata>
+					value := calldataload(ptr)
 					<validate>(value)
-				</needsValidation>
+				<!fromCalldata>
+					value := <cleanup>(mload(ptr))
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:2268]: Do we actually need to do cleanup after memory load now if we do it before operations and before memory store?

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:2268]: The whole cleanup business as it currently stands relies on the optimizer to remove unnecessary cleanups anyways - so given that I'd say better to clean one time too many than not enough...

Actually I'm still looking at the cleanup before the memory store - it kind of looks like there could be a way to circumvent cleaning up there, but I haven't managed to trigger a dirty write yet, so maybe it's fine as is.

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2268]: I think cleanup before memory store is more important than cleanup after memory read because of things like `sha3` and external calls.

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:2268]: Ok, I'll make double-sure there's cleanup there, resp. just add another explicit one to it.
It's a bit unfortunate that the IRVariable mechanism was kind of designed with the idea of things being clean in mind, so they can be assigned to each other all the time without problems, if they are of the same type... given that we change the cleanup policy, maybe we should rethink that...

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:2268]: Actually cleanup is *always* done in ``writeToMemoryFunction``, so this is fine.
And it makes sense to generally not clean up IRVariables, but have the util functions *always* do it.

**Review by chriseth — APPROVED** [review]
