### PR TITLE
Fix infinite loop when accessing circular constants from inline assem…

### LINKED ISSUE #10732: Compilation doesn't terminate for contract
## Description

`solc` doesn't terminate when compiling this small contract (I let it run for ~2 mins then `Ctrl-c`'d):

```solidity
contract C { 
    bytes32 constant x = x;
    function f() public pure returns (uint t) {
        assembly {
            t := x
        }
    }
}
```

Without the assembly block, this contract causes a cyclical dependency in the `x = x` statement. Looks like the cycle detection trips up with a variable use or assignment in the assembly block.

Found on master, part of the fuzzing project https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version: Version: 0.8.1-develop.2021.1.8+commit.d11cf15d.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04.5 LTS

## Steps to Reproduce

This command doesn't terminate:

```bash
cat <<EOF | solc - 
contract C { 
    bytes32 constant x = x;
    function f() public pure returns (uint t) {
        assembly {
            t := x
        }
    }
}
EOF
```

### PR DESCRIPTION
**Pull request by hrkrshnn**
…bly.

Closes https://github.com/ethereum/solidity/issues/10732

The problem is that circular references are only checked after TypeChecker (as part of PostTypeChecker.) However, when these variables are used in inline assembly, TypeChecker will try to find its initial value and get into an infinite loop.

### CODE REVIEW

File: libsolidity/ast/ASTUtils.cpp [hunk 1]
```diff
@@ -19,12 +19,35 @@
 #include <libsolidity/ast/AST.h>
 #include <libsolidity/ast/ASTUtils.h>
 
+#include <libsolutil/Algorithms.h>
+
 namespace solidity::frontend
 {
 
+bool isConstantVariableRecursive(VariableDeclaration const& _varDecl)
```
Comment (ekpyron) [inline libsolidity/ast/ASTUtils.cpp:27]: Do we really have to duplicate the logic? Can't the check from the ``PostTypeChecker`` be moved to an earlier time instead?

Comment (ekpyron) [reply libsolidity/ast/ASTUtils.cpp:27]: ``ContractLevelChecker`` maybe? The check in the ``PostTypeChecker`` only requires the ``DeclarationTypeChecker`` to already have run, right? And one can argue that it's "Contract Level", i.e. for each contract look at its state variables...
But not sure, maybe it's more complicated than that.

Comment (ekpyron) [reply libsolidity/ast/ASTUtils.cpp:27]: Maybe a simpler method would be to make ``rootConstVariableDeclaration`` in ``ASTUtils.cpp`` robust against cycles and return ``nullptr`` in the cycle case... (it'd just need to track which variable declarations it has already seen)

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:27]: > Can't the check from the PostTypeChecker be moved to an earlier time instead?

Maybe. It's not entirely trivial to move it, since that check runs on the entire AST and probably needs to be run after `TypeChecker`.

Anyway having the assert inside `rootConstVariableDeclaration` makes sense, because it's called from `ContractCompiler.cpp` and `IRGeneratorForStatements.cpp`.

Comment (ekpyron) [reply libsolidity/ast/ASTUtils.cpp:27]: Not an assert - that would just ICE in these cases - just returning ``nullptr`` should be fine, though, shouldn't it? That can happen anyways and is consistent (there's not always a root variable declaration and a cycle is one such case)

Comment (ekpyron) [reply libsolidity/ast/ASTUtils.cpp:27]: It'd probably error out with ``Only direct number constants and references to such constants are supported by inline assembly.`` that way, but I'd say that's ok...

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:27]: > return nullptr in the cycle case...

I thought about this, however we'll still have to distinguish between non-direct-constants and cyclic constants (both will return nullptr.) And the error message won't be so useful.

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:27]: > it'd probably error out with Only direct number constants and references to such constants are supported by inline assembly.

But we would miss the error about cyclic constant, since this check is done after TypeChecker and will never be done. I think this would be confusing.

Comment (ekpyron) [reply libsolidity/ast/ASTUtils.cpp:27]: Hm, yeah, not sure... I think it'd be fine - it's true that the cyclic constant doesn't refer to a number in the end :-).
On the other hand making ``rootConstVariableDeclaration`` robust against cycles is not all that different from checking for cycles before calling it in the type checker...

What we'd actually need is a ``PreTypeChecker`` that works like the ``PostTypeChecker``, just before the ``TypeChecker`` (actual type checking is not required for the constant detection in ``PostTypeChecker`` - it only really needs ``DeclarationTypeChecker``...)... but that'd maybe be overkill :-)...

Well, I'd also be fine with just leaving this as is...

Comment (chriseth) [reply libsolidity/ast/ASTUtils.cpp:27]: I think it's a good idea to introduce a new component.

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:27]: @chriseth You mean a component like `PreTypeChecker` that @ekpyron mentioned?

**Comment by chriseth** [comment]
Yes.

File: libsolidity/ast/ASTUtils.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/ast/ASTUtils.cpp:27]: What other steps do you envision in that file? Maybe better to have a dedicated `CircularReferencesChecker` step/file?

Comment (chriseth) [reply libsolidity/ast/ASTUtils.cpp:27]: Just this for now. We may find another crash and then we can move more things there.

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:27]: Doing `ConstStateVarCircularReferenceChecker` before TypeChecking won't work for:

```
    ==== Source: a ====
    import "b";
    uint constant c = d;
    ==== Source: b ====
    import "a" as M;
    uint constant b = M.c;
    uint constant d = b;
    contract C {
        uint constant a = b;
    }
```

The `MemberAccess.annotation().referencedDeclaration()` is set during TypeChecker. So it would miss this test case.

Can `TypeChecker::visit(MemberAccess const& _memberAccess)` be moved further up in the compiler stack, or is there a reason it's done in `TypeChecker`?

Comment (chriseth) [reply libsolidity/ast/ASTUtils.cpp:27]: You are right, then we can only do it in the TypeChecker :(

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -753,6 +753,16 @@ bool TypeChecker::visit(InlineAssembly const& _inlineAssembly)
 			}
 			if (var->isConstant())
 			{
+				if (isConstantVariableRecursive(*var))
+				{
+					m_errorReporter.typeError(
+						3558_error,
+						_identifier.location,
+						"Constant variable is circular."
```
Comment (bshastry) [inline libsolidity/analysis/TypeChecker.cpp:761]: Would `Constant variable references itself.` be easier to understand?

File: test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_err.sol [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+    bytes32 constant x = x;
+    function f() public pure returns (uint t) {
+        assembly {
+            // Reference to a circular member
+            t := x
+        }
+    }
+}
+// ----
+// TypeError 3558: (171-172): Constant variable is circular.
```
Comment (bshastry) [inline test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_err.sol:11]: How are circular references handled elsewhere? Non inline assembly I mean.

Would it make sense to add the test case that came up in an earlier thread

```
    ==== Source: a ====
    import "b";
    uint constant c = d;
    ==== Source: b ====
    import "a" as M;
    uint constant b = M.c;
    uint constant d = b;
    contract C {
        uint constant a = b;
    }
```

Comment (hrkrshnn) [reply test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_err.sol:11]: This already exists in `test/libsolidity/syntaxTests/constants/cross_file_cyclic_modules.sol`

File: libsolidity/analysis/TypeChecker.cpp (hunk 2 above)
Comment (hrkrshnn) [reply libsolidity/analysis/TypeChecker.cpp:761]: Not sure if it would be accurate, for `a` when the relations are `a -> b`, `b -> b`.

Comment (bshastry) [reply libsolidity/analysis/TypeChecker.cpp:761]: Ah right!

File: libsolidity/ast/ASTUtils.cpp [hunk 4]
```diff
@@ -19,12 +19,35 @@
...
+			if (auto referencedVarDecl = dynamic_cast<VariableDeclaration const*>(identifier->annotation().referencedDeclaration))
+				if (referencedVarDecl->isConstant())
+					if (_cycleDetector.run(*referencedVarDecl))
+						return;
+	};
+
+	if (util::CycleDetector<VariableDeclaration>(visitor).run(_varDecl))
+		return true;
+
+	return false;
```
Comment (bshastry) [inline libsolidity/ast/ASTUtils.cpp]: What about `return util::CycleDetector<VariableDeclaration>(visitor).run(_varDecl);` instead of 

```
	if (util::CycleDetector<VariableDeclaration>(visitor).run(_varDecl))
		return true;

	return false;
```

like in 
https://github.com/ethereum/solidity/blob/1df284733eb93e4b887c317b79412fe74fa7f731/libsolidity/analysis/PostTypeChecker.cpp#L204

File: test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_err.sol (hunk 3 above)
Comment (bshastry) [reply test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_err.sol:11]: Perhaps add the following test case if it doesn't exist?

```
==== Source: a ====
bytes32 constant x = x;
==== Source: b ====
import "a";
contract C {
    function f() public pure returns (uint t) {
        assembly {
            // Reference to a circular member
            t := x
        }
    }
}
```

File: libsolidity/ast/ASTUtils.cpp [hunk 5]
```diff
@@ -19,12 +19,32 @@
...
 {
 
+bool isConstantVariableRecursive(VariableDeclaration const& _varDecl)
+{
+	solAssert(_varDecl.isConstant(), "Constant variable expected");
+	auto visitor = [&](VariableDeclaration const& _variable, util::CycleDetector<VariableDeclaration>& _cycleDetector, size_t _depth)
+	{
+		solAssert(_depth < 256, "Recursion depth limit reached");
+
+		if (auto identifier = dynamic_cast<Identifier const*>(_variable.value().get()))
```
Comment (chriseth) [inline libsolidity/ast/ASTUtils.cpp]: If you are only looking for `identifier`, then this cannot catch the circularity as in the example in https://github.com/ethereum/solidity/pull/10783/files#r560848021 does it?

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp]: I added a test for it. https://github.com/ethereum/solidity/pull/10783/files#diff-31b40ad134e36fb598eba9d52a0d3ac9d7f983fbdd03793ade820316a8b4743e 

It doesn't detect the circular part though. Let me see if this function can be improved to deal with that case.

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp]: Fixed this now.

File: libsolidity/ast/ASTUtils.cpp [hunk 6]
```diff
@@ -19,12 +19,41 @@
...
+{
+	solAssert(_varDecl.isConstant(), "Constant variable expected");
+
+	auto referencedDeclaration = [&](Expression const* _e) -> VariableDeclaration const*
+	{
+		if (auto identifier = dynamic_cast<Identifier const*>(_e))
+			return dynamic_cast<VariableDeclaration const*>(identifier->annotation().referencedDeclaration);
+		else if (auto memberAccess = dynamic_cast<MemberAccess const*>(_e))
+			return dynamic_cast<VariableDeclaration const*>(memberAccess->annotation().referencedDeclaration);
+		return nullptr;
```
Comment (bshastry) [inline libsolidity/ast/ASTUtils.cpp:37]: Are these two (via identifier or via member access) the only ways referenced declarations may be cyclic?

**Review by bshastry — COMMENTED** [review]
Minor clarification

File: libsolidity/ast/ASTUtils.cpp (hunk 6 above)
Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:37]: You can compare with `ConstStateVarCircularReferenceChecker`

Comment (hrkrshnn) [reply libsolidity/ast/ASTUtils.cpp:37]: I think the answer is yes.

**Review by bshastry — DISMISSED** [review]
Looks good

File: libsolidity/ast/ASTUtils.cpp [hunk 7]
```diff
@@ -19,12 +19,41 @@
...
+#include <libsolutil/Algorithms.h>
+
 namespace solidity::frontend
 {
 
+bool isConstantVariableRecursive(VariableDeclaration const& _varDecl)
+{
+	solAssert(_varDecl.isConstant(), "Constant variable expected");
+
+	auto referencedDeclaration = [&](Expression const* _e) -> VariableDeclaration const*
```
Comment (chriseth) [inline libsolidity/ast/ASTUtils.cpp:31]: This looks like a generic helper also useful in @christianparpart 's LSP. Let's extract it in a subsequent PR.

**Comment by chriseth** [comment]
Rebased.

**Review by chriseth — APPROVED** [review]
