### PR TITLE
[Sol->Yul] Fixing setLValue for calldata types.

### LINKED ISSUE #10889: [soltoyul] ICE in setLValue because _lvalue.type.dataStoredIn(DataLocation::CallData) is true
## Description

```
contract C{function f(uint[]calldata x,uint[]calldata y)external{x=y;}}
```

throws

https://github.com/ethereum/solidity/blob/8a4e6acdac8d11ee671f084d96d82de63f684812/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L2923

## Steps to Reproduce

```
$ solc --ir test.sol
```

### PR DESCRIPTION
**Pull request by mijovic**
Fixes #10889

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -2918,10 +2918,7 @@ void IRGeneratorForStatements::setLValue(Expression const& _expression, IRLValue
 	solAssert(!m_currentLValue, "");
 
 	if (_expression.annotation().willBeWrittenTo)
-	{
 		m_currentLValue.emplace(std::move(_lvalue));
-		solAssert(!_lvalue.type.dataStoredIn(DataLocation::CallData), "");
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:2923]: Acutally can you replace this by:
If the type is stored in calldata, then the _lvalue.kind is stack?

Comment (mijovic) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:2923]: Added @chriseth 
https://github.com/ethereum/solidity/pull/10912
