### PR TITLE
SMTChecker: Ignore errors that might occur during constant evaluation

### LINKED ISSUE #15600: SMTChecker triggers an ICE by not reporting `Arithmetic error when computing constant value` fatal error caused by constant negation
## Environment

- Compiler version: 0.8.27
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce
```solidity
// SPDX-License-Identifier: MIT
contract BitwiseSolver {
    uint256 constant largeConstant = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;
    event LogResult(uint256 result);
    constructor() {
        executeOperations(99);
    }
    function executeOperations(uint256 input) public {
        uint256 result = (input | largeConstant) & ~largeConstant;
        result = performShift(result + input);
        emit LogResult(result);
    }
    function performShift(uint256 value) internal pure returns (uint256) {
        for (uint8 i = 0; i < 256; i++) {
            value ^= (1 << i);
            if (i == 0) break;   // Ensures loop runs only once
        }
        return value;
    }
}
```
```
solc-0827 b.sol --model-checker-ext-calls trusted --model-checker-timeout 0 --model-checker-engine chc --model-checker-solvers z3   --model-checker-show-unproved 
```
```
Internal compiler error:
/solidity/libsolidity/interface/CompilerStack.cpp(502): Throw in function bool solidity::frontend::CompilerStack::analyze()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Unreported fatal error: std::exception
[solidity::util::tag_comment*] = Unreported fatal error: std::exception
```
However, the program can be successfully compiled into bytecode.

### LINKED ISSUE #15601: SMTChecker triggers an ICE by not reporting `Arithmetic error when computing constant value` fatal error caused by constant addition
## Environment

- Compiler version: 0.8.27
- Target EVM version (as per compiler settings): None
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: Linux

## Steps to Reproduce
```solidity
// SPDX-License-Identifier: MIT
contract BugDetection {
    uint256 public storedValue;
    uint8 constant MAX_UINT8 = 255;
    function storeShiftedValue(uint256 input) public {
        // Inline assembly to manipulate bits directly
        assembly {
            let shifted := shl(2, input) // Shift left by 2, may overflow if input is not managed
            sstore(storedValue.slot, shifted) // Store the shifted value to storedValue
        }
        storedValue = computeHashWithSideEffect(uint8(storedValue % (MAX_UINT8 + 1)));
    }
    function computeHashWithSideEffect(uint8 input) internal returns (uint256) {
        // Function with potential side-effect in the expression
        uint8 interimValue = input;
        bytes32 hash = keccak256(abi.encodePacked(interimValue + modifyState()));
        return uint256(hash);
    }
    function modifyState() internal returns (uint8) {
        storedValue = storedValue + 1; // Intentional side-effect to modify state
        return 1; // Return a small constant value
    }
}
```
```
solc-0827 b.sol --model-checker-ext-calls trusted --model-checker-timeout 0 --model-checker-engine chc --model-checker-solvers z3   --model-checker-show-unproved 
```
```
Internal compiler error:
/solidity/libsolidity/interface/CompilerStack.cpp(502): Throw in function bool solidity::frontend::CompilerStack::analyze()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Unreported fatal error: std::exception
[solidity::util::tag_comment*] = Unreported fatal error: std::exception
```
However, the program can be successfully compiled into bytecode.

### LINKED ISSUE #15722: SMTChecker triggers an ICE by not reporting `Arithmetic error when computing constant value` fatal error caused by constant subtraction
Hello! I encountered an internal compiler error when using the solc compiler version 0.8.27 to compile the following code. My compilation command was: `solc-0.8.27 a.sol --model-checker-solvers smtlib2 --model-checker-engine bmc`.

```solidity
contract Test {

  uint256 public A;
  uint256 public constant B = 1;

  function g() public returns(uint256) {
      A >>= ((B & 0x3f) + B * 64) - 112;
      return 1;
  }
}
```

Output:

```
Internal compiler error:
/solidity/libsolidity/interface/CompilerStack.cpp(502): Throw in function bool solidity::frontend::CompilerStack::analyze()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Unreported fatal error: std::exception
[solidity::util::tag_comment*] = Unreported fatal error: std::exception
```

I compiled a new version of solc (71988f7546063a9d6d63d54ece85839400b46264) for testing, and the error persists.

### PR DESCRIPTION
**Pull request by blishko**
Previously, if a fatal error would occur during constant evaluation in the model checker, it would throw an exception which the model checker would let escape and crash the compiler.

We introduce a new API to `ConstantEvaluator` that swallows any errors use it from the model checker.
This allows model checker to continue, treating any expression where an error would occur simply as not constant.

Fixes #15600 #15601 #15722.

Resolves point 3 of [@cameel 's analysis](https://github.com/ethereum/solidity/issues/15709#issuecomment-2628622966) in #15709.

### CODE REVIEW

File: libsolidity/analysis/ConstantEvaluator.cpp [hunk 1]
```diff
@@ -269,6 +269,20 @@ std::optional<TypedRational> ConstantEvaluator::evaluate(
 	return ConstantEvaluator{_errorReporter}.evaluate(_expr);
 }
 
+std::optional<TypedRational> ConstantEvaluator::tryEvaluate(Expression const& _expr)
+{
+	ErrorList l;
+	ErrorReporter e(l);
```
Comment (cameel) [inline libsolidity/analysis/ConstantEvaluator.cpp]: I see it was copied from `SMTEncoder.cpp`, but if you're touching it, I'd apply our coding style and remove abbreviations:

```suggestion
	ErrorList errorList;
	ErrorReporter errorReporter(errorList);
```

Comment (cameel) [reply libsolidity/analysis/ConstantEvaluator.cpp]: Similarly `t` in `isConstant()` would be much better off named something like `typedRational` since type is obscured by `auto`.

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -3124,12 +3124,7 @@ RationalNumberType const* SMTEncoder::isConstant(Expression const& _expr)
 	if (auto type = dynamic_cast<RationalNumberType const*>(_expr.annotation().type))
 		return type;
 
-	// _expr may not be constant evaluable.
-	// In that case we ignore any warnings emitted by the constant evaluator,
-	// as it will return nullptr in case of failure.
-	ErrorList l;
-	ErrorReporter e(l);
-	if (auto t = ConstantEvaluator::evaluate(e, _expr))
+	if (auto t = ConstantEvaluator::tryEvaluate(_expr))
```
Comment (cameel) [inline libsolidity/formal/SMTEncoder.cpp]: Now that we have the helper, we should use it in `StaticAnalyzer::visit(BinaryOperation)` as well. Though that needs a changelog entry and some tests so maybe it's better off done in a separate PR.

File: Changelog.md [hunk 3]
```diff
@@ -14,6 +14,7 @@ Compiler Features:
 
 Bugfixes:
  * General: Fix internal compiler error when requesting IR AST outputs for interfaces and abstract contracts.
+ * SMTChecker: Fix internal compiler error when analyzing overflowing expressions involving constants.
```
Comment (cameel) [inline Changelog.md]: I think we should explicitly mention that it affected bitwise negation as well.

**Review by cameel — DISMISSED** [review]
I have some suggestions, but nothing critical. Overall looks good.

File: libsolidity/analysis/ConstantEvaluator.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/analysis/ConstantEvaluator.cpp]: Abbreviations have been expanded.

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: Yes, I think this should be done in a separate PR.

File: Changelog.md (hunk 3 above)
Comment (blishko) [reply Changelog.md]: I mention bitwise negation of unsigned types now in the changelog entry.

File: Changelog.md [hunk 4]
```diff
@@ -15,6 +15,7 @@ Compiler Features:
 
 Bugfixes:
  * General: Fix internal compiler error when requesting IR AST outputs for interfaces and abstract contracts.
+ * SMTChecker: Fix internal compiler error when analyzing overflowing expressions or bitwise negatation of unsigned types involving constants.
```
Comment (cameel) [inline Changelog.md]:
```suggestion
 * SMTChecker: Fix internal compiler error when analyzing overflowing expressions or bitwise negation of unsigned types involving constants.
```

**Review by cameel — DISMISSED** [review]

File: Changelog.md (hunk 4 above)
Comment (blishko) [reply Changelog.md]: Fixed. Sorry, you will have to re-approve.

**Review by cameel — APPROVED** [review]
