### PR TITLE
Fix ICE when pop dyn storage array of mapping

### LINKED ISSUE #7378: ICE pop a dynamic storage array of mapping
```
contract C {
    mapping (uint => uint)[] a;
    function f() public {
        a.pop();
    }
}
```

```
libsolidity/codegen/LValue.cpp(401): Throw in function virtual void dev::solidity::StorageItem::setToZero(const langutil::SourceLocation&, bool) const
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what: Clearing of unsupported type requested: mapping(uint256 => uint256)
[dev::tag_comment*] = Clearing of unsupported type requested: mapping(uint256 => uint256)
```

Deleting a `mapping` gives a `TypeError`, which is correct.
Here the `pop` tries to `setToZero` the last mapping which is then caught by codegen.
`a.pop()` should be valid, since popping the array should be fine. But because of the base type being a `mapping` it shouldn't try to `setToZero`.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/7378

### CODE REVIEW

**Comment by leonardoalt** [comment]
`delete a;` worked before because `ArrayUtils::clearStorageLoop` also only acts if the base type is not a mapping.

File: libsolidity/codegen/ArrayUtils.cpp [hunk 1]
```diff
@@ -896,11 +896,16 @@ void ArrayUtils::popStorageArrayElement(ArrayType const& _type) const
 		// Stack: ArrayReference oldLength
 		m_context << u256(1) << Instruction::SWAP1 << Instruction::SUB;
 		// Stack ArrayReference newLength
-		m_context << Instruction::DUP2 << Instruction::DUP2;
-		// Stack ArrayReference newLength ArrayReference newLength;
-		accessIndex(_type, false);
-		// Stack: ArrayReference newLength storage_slot byte_offset
-		StorageItem(m_context, *_type.baseType()).setToZero(SourceLocation(), true);
+
+		if (_type.baseType()->category() != Type::Category::Mapping)
```
Comment (bshastry) [inline libsolidity/codegen/ArrayUtils.cpp:900]: I'm confused. Isn't this supposed to be `==` because the change log refers to array of mappings.

Comment (leonardoalt) [reply libsolidity/codegen/ArrayUtils.cpp:900]: Mappings can't be zeroed, so if the base type is a mapping nothing should happen. If it's not a mapping, the content should be zeroed.

File: test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+		mapping (uint => uint)[] storage b = a[a.length - 1];
+		b.length++;
+	}
+
+	function map(uint key) public view returns (uint) {
+		mapping (uint => uint)[] storage b = a[a.length - 1];
+		return b[b.length - 1][key];
+	}
+
+    function p() public {
```
Comment (bshastry) [inline test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol]: Indentation is off here and below

File: test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol [hunk 3]
```diff
@@ -0,0 +1,39 @@
+contract C {
+    mapping (uint => uint)[][] a;
+
+	function n1(uint key, uint value) public {
+		a.length++;
+		mapping (uint => uint)[] storage b = a[a.length - 1];
+		b.length++;
+		b[b.length - 1][key] = value;
+	}
```
Comment (bshastry) [inline test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol:9]: Note to self: This appends another dimension to the array of mappings and initializes the last dimension's last slot to `key, value`

File: test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+
+	function n2() public {
+		a.length++;
+		mapping (uint => uint)[] storage b = a[a.length - 1];
+		b.length++;
+	}
```
Comment (bshastry) [inline test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol:15]: Note to self: This increases the size of array of mappings by one.

File: test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+
+	function map(uint key) public view returns (uint) {
+		mapping (uint => uint)[] storage b = a[a.length - 1];
+		return b[b.length - 1][key];
+	}
```
Comment (bshastry) [inline test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol:20]: Note to self: This returns the value stored in the array's last dimension's last slot at `key`

File: test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+}
+// ----
+// n1(uint256,uint256): 42, 64 ->
+// map(uint256): 42 -> 64
+// p() ->
+// n2() ->
+// map(uint256): 42 -> 64
+// d() -> 0
+// n2() ->
+// map(uint256): 42 -> 64
```
Comment (leonardoalt) [inline test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol:39]: Note that since mappings can't be zeroed, deleting the entire array in `d()` above does not delete the mapping information. Reallocating the array, that is, reassigning the length, should make the old mapping data accessible.

File: test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol (hunk 4 above)
Comment (bshastry) [reply test/libsolidity/semanticTests/storage/mappings_array2d_pop_delete.sol:15]: a[1][1] becomes a[2][1] after this

**Review by bshastry — DISMISSED** [review]
LGTM apart from indentation being off in test program.

**Comment by leonardoalt** [comment]
Fixed indentation

**Review by chriseth — APPROVED** [review]
