### PR TITLE
Report error on shadowing state variables

### LINKED ISSUE #2563: Shadowing of inherited state variables should be an error (override keyword)
Code like the following should be an error:

```
contract Base {
  uint x;
}
contract Derived is Base {
  uint x;
}
```

Functions defined in `Base` that use the `x` state variable will access `Base.x`, and those defined in `Derived` will silently access the different slot `Derived.x`. This is a common problem for beginners that don't understand inheritance very well, and it could happen accidentally to anyone as well. The compiler should fail to compile it to prevent these errors.

This is different (and I believe more serious) than #973. It is about state variables shadowing other (_inherited_) state variables, possibly defined in different files and so harder to see.

### PR DESCRIPTION
**Pull request by christianparpart**
## Goal:

* [x] State variables shadowing state variables from base contracts must raise an error (Closes #2563.)
* [x] new test added.
* [x] existing tests adapted.
* [x] ChangeLog added
* [x] documentation adapted
* [x] Entry to "0.6.0" change list

## Notes

I still feel it kind of conflicts with the work with @Marenz. So maybe you can have a look too (that's why some tests (of yours) are failing).

Maybe we should clarify here a bit. I see perfect reasoning in the way shadowed variables are reported (in this PR), and I *thought* that the variable override logic were about to override a base function with a state var in the child contract, but apparently some tests fail with some interesting new syntax that I don't understand yet.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -510,6 +510,24 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
 			m_errorReporter.typeError(_variable.location(), "Internal or recursive type is not allowed for public state variables.");
 	}
 
+	if (_variable.isStateVariable())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Please extract to function.

**Comment by chriseth** [comment]
Please add changelog entry, documentation and entry to "0.6.0" change list"

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (christianparpart) [reply libsolidity/analysis/TypeChecker.cpp]: ok, will do ASAP.

p.s.: the above questions have been solved after a short chat with @Marenz - I'll adapt his tests.

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -528,6 +530,27 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
...
+{
+	if (_variable.isStateVariable())
+	{
+		solAssert(m_scope != nullptr, "");
+		SecondarySourceLocation sec{};
+
+		for (auto base = next(begin(m_scope->annotation().linearizedBaseContracts)); base != end(m_scope->annotation().linearizedBaseContracts); ++base)
+			for (VariableDeclaration const* otherVarDecl: (*base)->stateVariables())
+				if (_variable.name() == otherVarDecl->name())
+					sec.append("Also available from here:", otherVarDecl->location());
```
Comment (Marenz) [inline libsolidity/analysis/TypeChecker.cpp]: I would say here "Conflicting variable here:"

**Comment by Marenz** [comment]
I just found this https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/NameAndTypeResolver.cpp#L349
this would probably then be a better place to do this no?

**Comment by leonardoalt** [comment]
Rebased, updated docs, tests and comments

**Review by Marenz — APPROVED** [review]

File: Changelog.md [hunk 3]
```diff
@@ -22,11 +22,13 @@ Breaking changes:
  * Source mappings: Add "modifier depth" as a fifth field in the source mappings.
  * AST: Inline assembly is exported as structured JSON instead of plain string.
  * General: ``private`` cannot be used together with ``virtual``.
+ * Inheritance: State variable shadowing is now disallowed.
 
 Language Features:
  * Allow global enums and structs.
  * Allow underscores as delimiters in hex strings.
  * Allow explicit conversions from ``address`` to ``address payable`` via ``payable(...)``.
+ * Inheritance: Disallow state variables to shadow state variables from base contracts.
```
Comment (ekpyron) [inline Changelog.md]: Isn't one entry enough?

File: docs/060-breaking-changes.rst [hunk 4]
```diff
@@ -38,6 +38,9 @@ This section lists purely syntactic changes that do not affect the behavior of e
   If the name contains a dot, its prefix up to the dot may not conflict with any declaration outside the inline
   assembly block.
 
+* State variable shadowing is now disallowed. That is, if you have a derived contract that has a state variable ``x``
```
Comment (ekpyron) [inline docs/060-breaking-changes.rst]:
```suggestion
* State variable shadowing is now disallowed. A derived contract can only declare a state variable ``x``, if there is no state variable with the same name in any of its bases.
```
?

File: Changelog.md (hunk 3 above)
Comment (leonardoalt) [reply Changelog.md]: Should this one be removed?

File: docs/contracts/inheritance.rst [hunk 5]
```diff
@@ -19,6 +19,10 @@ is compiled into the created contract. This means that all internal calls
 to functions of base contracts also just use internal function calls
 (``super.f(..)`` will use JUMP and not a message call).
 
+State variable shadowing is considered as an error. That is, a derived
```
Comment (ekpyron) [inline docs/contracts/inheritance.rst]: See above.

File: test/libsolidity/syntaxTests/inheritance/override/override.sol [hunk 6]
```diff
@@ -3,9 +3,10 @@ abstract contract A {
 	function test() internal virtual returns (uint256);
 	function test2() internal virtual returns (uint256);
 }
-contract X is A {
+abstract contract X is A {
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/inheritance/override/override.sol]: Why make it abstract? If this is *needed* here, then that's a bug, isn't it?

File: test/libsolidity/syntaxTests/inheritance/override/override_multiple.sol [hunk 7]
```diff
@@ -13,7 +12,7 @@ abstract contract C {
 abstract contract D {
 	function foo() internal virtual returns (uint256);
 }
-contract X is A, B, C, D {
+abstract contract X is A, B, C, D {
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/inheritance/override/override_multiple.sol]: Also shouldn't be abstract.

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: Changelog.md (hunk 3 above)
Comment (ekpyron) [reply Changelog.md]: Yep - it's a breaking change, I'd say that's enough and that's what we did for all others, right (haven't checked)?

File: docs/060-breaking-changes.rst (hunk 4 above)
Comment (leonardoalt) [reply docs/060-breaking-changes.rst]: Well, that's not true. If a base contract has a state variable with same name but `private`, that works.

Comment (leonardoalt) [reply docs/060-breaking-changes.rst]: Shadowing happens when the derived contract actually inherits the base one.

Comment (chriseth) [reply docs/060-breaking-changes.rst]: "...there is no visible state variable with the same..."?

File: test/libsolidity/smtCheckerTests/inheritance/state_variables_2.sol [hunk 8]
```diff
@@ -2,12 +2,10 @@ pragma experimental SMTChecker;
 
 contract Base1 {
 	uint x;
-	uint private t;
 }
 
 contract Base2 is Base1 {
 	uint z;
-	uint private t;
```
Comment (chriseth) [inline test/libsolidity/smtCheckerTests/inheritance/state_variables_2.sol:10]: Why did you remove it? Would it cause an error?

File: test/libsolidity/syntaxTests/inheritance/override/override.sol (hunk 6 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/inheritance/override/override.sol]: I would also like to know the explanation.

**Comment by chriseth** [comment]
Do we have a test that shows a clash between a variable and a function?

File: test/libsolidity/smtCheckerTests/inheritance/state_variables_2.sol (hunk 8 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/inheritance/state_variables_2.sol:10]: It wouldn't but it wasn't being used. Probably copied from some other test and forgot then.

**Review by chriseth — APPROVED** [review]
