### PR TITLE
Array slice syntax (with implementation for dynamic calldata arrays)

### LINKED ISSUE #6012: abi.decode cannot decode `msg.data`
I'm trying to use `abi.decode` to decode abi encoded calls. 

I noticed that this is not possible because `abi.decode` fails to shift out the "msg.sig", the first 4 bytes.

```solidity
pragma solidity >=0.5.0 <0.6.0; 
contract Foo {
    function bar(uint256 _a, address _b) external pure returns (uint256 a, address b) {
        (a,b) = abi.decode(msg.data, (uint256,address));
    }
}
```

This is the result:
```
decoded input | { 	"uint256 _a": "1", 	"address _b": "0xDe4A88ef731cc55450C76E9307A64e94146006f7" }
-- | --
decoded output | { 	"0": "uint256: a 43775121307266258428473763376100980315118985562653986292681922597120504758272", 	"1": "address: b 0x00000000de4a88EF731cc55450C76E9307A64E94" }
```

I noticed that if I remove the 4 bytes from start and it decodes correctly:
```solidity
pragma solidity >=0.5.0 <0.6.0; 
contract Foo {
    function bar(bytes calldata data) external pure returns (uint256 a, address b) {
        (a,b) = abi.decode(data, (uint256,address));
    }
}
```

Using data (with bytes4 msg.sig):
```
decoded input | { 	"bytes data": "0xa55176590000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de4a88ef731cc55450c76e9307a64e94146006f7" }
-- | --
decoded output | { 	"0": "uint256: a 74775551433990177875228592555497145942085465184237639638388956040984682037248", 	"1": "address: b 0x00000000de4a88EF731cc55450C76E9307A64E94" }
```

Cropping out the msg.sig:
```
decoded input | { 	"bytes data": "0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000de4a88ef731cc55450c76e9307a64e94146006f7" }
-- | --
decoded output | { 	"0": "uint256: a 1", 	"1": "address: b 0xDe4A88ef731cc55450C76E9307A64e94146006f7" }
```

I tried ` abi.decode(msg.data, (bytes4,uint256,address));` but then this line reverts.
Maybe we need a `abi.decodePacked`?

### PR DESCRIPTION
**Pull request by ekpyron**
So far ~~``x.slice``~~ ``x[start:end]`` is an error for everything but dynamic calldata arrays and slices of them.
For calldata slices ~~only~~ implicit conversions back to calldata arrays are implemented, which means that they can be passed to ``abi.decode`` and nothing besides that (no other conversions, ~~no index access~~, no members). Index accesses for calldata slices are implemented as well.

So rather incomplete, but already Fixes #6012.

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -1864,6 +1873,45 @@ std::unique_ptr<ReferenceType> ArrayType::copyForLocation(DataLocation _location
...
+bool ArraySliceType::operator==(Type const& _other) const
+{
+	if (auto const* other = dynamic_cast<ArraySliceType const*>(&_other))
+		return m_arrayType == other->m_arrayType;
+	return false;
+}
+
+string ArraySliceType::toString(bool _short) const
+{
+	return m_arrayType.toString(_short) + " slice";
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:1893]: Is it a problem that `slice` might appear after `memory`?

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -1864,6 +1873,45 @@ std::unique_ptr<ReferenceType> ArrayType::copyForLocation(DataLocation _location
...
+}
+
+TypePointer ArraySliceType::encodingType() const
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Does that work?

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 3]
```diff
@@ -920,6 +920,33 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
...
+			ArrayType const& arrayType = dynamic_cast<ArrayType const&>(
+				*dynamic_cast<MemberAccess const&>(_functionCall.expression()).expression().annotation().type
+			);
+			solUnimplementedAssert(arrayType.location() == DataLocation::CallData && arrayType.isDynamicallySized(), "");
+			solAssert(arguments.size() == 2, "");
+
+			arguments[0]->accept(*this);
+			utils().convertType(*arguments[0]->annotation().type, *TypeProvider::uint256());
+
+			arguments[1]->accept(*this);
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: I think we should also support `.slice(start)`

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 4]
```diff
@@ -920,6 +920,33 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
...
+		{
+			_functionCall.expression().accept(*this);
+			ArrayType const& arrayType = dynamic_cast<ArrayType const&>(
+				*dynamic_cast<MemberAccess const&>(_functionCall.expression()).expression().annotation().type
+			);
+			solUnimplementedAssert(arrayType.location() == DataLocation::CallData && arrayType.isDynamicallySized(), "");
+			solAssert(arguments.size() == 2, "");
+
+			arguments[0]->accept(*this);
+			utils().convertType(*arguments[0]->annotation().type, *TypeProvider::uint256());
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: Is there a shortcut for accept + convert?

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 5]
```diff
@@ -920,6 +920,33 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
...
+			arguments[1]->accept(*this);
+			utils().convertType(*arguments[1]->annotation().type, *TypeProvider::uint256());
+
+			m_context.appendInlineAssembly(
+				Whiskers(R"({
+					if sgt(sliceLength, sub(length, sliceStart)) { revert(0, 0) }
+					offset := add(offset, mul(sliceStart, <stride>))
+					length := sliceLength
+				})")("stride", toString(arrayType.calldataStride())).render(),
+				{"offset", "length", "sliceStart", "sliceLength"}
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: JavaScript's `.slice` uses `end` as second parameter, and not length.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: Well, since the array slice type can't be named at the moment, this should never actually be used... but if one ever was to encode or decode them, then at least dynamic calldata array slices can be encoded just like full dynamic calldata arrays at the moment... But maybe better to leave it at the default implementation for now...

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 6]
```diff
@@ -1109,10 +1136,13 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 			else
 				targetTypes = TypePointers{_functionCall.annotation().type};
 			if (
-				*firstArgType == ArrayType(DataLocation::CallData) ||
-				*firstArgType == ArrayType(DataLocation::CallData, true)
+				auto referenceType = dynamic_cast<ReferenceType const*>(firstArgType);
+				referenceType && referenceType->dataStoredIn(DataLocation::CallData)
 			)
+			{
+				utils().convertType(*firstArgType, *TypeProvider::bytesCalldata());
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: I think we should have some more assertions here.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp]: For `abi.encode`, the type does not have to be named.

Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: Yeah, true... that should actually just work like this then - I'll add tests for it.

Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: Hm... it seems like there is more to it - it still won't pass the type checker like this and codegen also has various assertions - I'll remove it and we can implement all this later.

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (ekpyron) [reply libsolidity/ast/Types.cpp:1893]: Isn't e.g. ``bytes calldata slice`` better than ``bytes slice calldata``? We could also use ``slice(bytes calldata)`` or something else entirely... I don't really mind, but I'm myself fine with just appending "slice"...

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `9b7e84711390a395bd85f9e262b4939b993c0a23`:
```
Coding style error:
 libsolidity/analysis/TypeChecker.cpp:2375: else if(!(arrayType = dynamic_cast<ArrayType const*>(exprType)))

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `b8dff65144373026b8ff94cdce6c3e59528f7f1b`:
```
Coding style error:
 libsolidity/analysis/TypeChecker.cpp:2375: else if(!(arrayType = dynamic_cast<ArrayType const*>(exprType)))

```
Please check that your changes are working as intended.

**Comment by ekpyron** [comment]
I did implement the ``[start:end]`` syntax after all now - that requires a bit of fiddling with the index access structure parser, but apart from that it's actually nicer to make it its own AST node and visit it separately in the type checker and during code gen.

We might actually be able to merge this to develop now, though - or is it still breaking in some way?

**Comment by chriseth** [comment]
Nice!

It is breaking in the sense that it introduces a new AST node type. If you have a tool that iterates over the full AST, you might miss some branches because you do not know how the children are called. Let's merge it into 0.6.0 - what would be the harm?

File: libsolidity/analysis/TypeChecker.cpp [hunk 7]
```diff
@@ -2338,6 +2344,47 @@ bool TypeChecker::visit(IndexAccess const& _access)
...
+	if (exprType->category() == Type::Category::TypeType)
+	{
+		m_errorReporter.typeError(_access.location(), "Types cannot be sliced.");
+		_access.annotation().type = exprType;
+		return false;
+	}
+	else if (auto const* arraySlice = dynamic_cast<ArraySliceType const*>(exprType))
+		arrayType = &arraySlice->arrayType();
+	else if (!(arrayType = dynamic_cast<ArrayType const*>(exprType)))
+		m_errorReporter.fatalTypeError(_access.location(), "Index range access is only possible for arrays and array slices.");
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp:2382]: The equivalent in ``IndexAccess`` is a fatal error as well... we could make both of them non-fatal and just assign ``_access.annotation().type = exprType`` here - that might lead to confusing results later, but probably not even too bad ones...

**Comment by ekpyron** [comment]
@leonardoalt To be clear: I was just confused before, the range is actually ``[start,end)`` already.

**Comment by ekpyron** [comment]
Rebased.

File: docs/grammar.txt [hunk 8]
```diff
@@ -123,6 +124,7 @@ FunctionCallArguments = '{' NameValueList? '}'
 NewExpression = 'new' TypeName
 MemberAccess = Expression '.' Identifier
 IndexAccess = Expression '[' Expression? ']'
+IndexRangeAccess = Expression '[' Expression ':' Expression? ']'
```
Comment (chriseth) [inline docs/grammar.txt]:
```suggestion
IndexRangeAccess = Expression '[' Expression? ':' Expression? ']'
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 9]
```diff
@@ -2245,6 +2243,14 @@ bool TypeChecker::visit(IndexAccess const& _access)
 	Expression const* index = _access.indexExpression();
 	switch (baseType->category())
 	{
+	case Type::Category::ArraySlice:
+	{
+		auto const& arrayType = dynamic_cast<ArraySliceType const&>(*baseType).arrayType();
+		if (arrayType.location() != DataLocation::CallData || !arrayType.isDynamicallySized())
+			m_errorReporter.typeError(_access.location(), "Index access is only implemented for slices of dynamic calldata arrays.");
+		baseType = &arrayType;
+		[[fallthrough]];
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:2252]: Does this not result in an error here: https://github.com/ethereum/solidity/pull/7340/files#diff-9f2a45efaa7b75ab7ec620d3177cf01aR2266 ?

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:2252]: Ah sorry, it is a regular index access to an array slice, i.e. `x[:10][2]` - is that right?

Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp:2252]: Yep. By the way so far the start index is non-optional by intention - should it be optional? I don't really mind either way...

File: libsolidity/analysis/TypeChecker.cpp [hunk 10]
```diff
@@ -2341,6 +2347,47 @@ bool TypeChecker::visit(IndexAccess const& _access)
 	return false;
 }
 
+bool TypeChecker::visit(IndexRangeAccess const& _access)
+{
+	_access.baseExpression().accept(*this);
+	TypePointer exprType = type(_access.baseExpression());
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Move these two closer to where they are first used?

File: libsolidity/analysis/TypeChecker.cpp [hunk 11]
```diff
@@ -2341,6 +2347,47 @@ bool TypeChecker::visit(IndexAccess const& _access)
...
+	if (exprType->category() == Type::Category::TypeType)
+	{
+		m_errorReporter.typeError(_access.location(), "Types cannot be sliced.");
+		_access.annotation().type = exprType;
+		return false;
+	}
+	else if (auto const* arraySlice = dynamic_cast<ArraySliceType const*>(exprType))
+		arrayType = &arraySlice->arrayType();
+	else if (!(arrayType = dynamic_cast<ArrayType const*>(exprType)))
+		m_errorReporter.fatalTypeError(_access.location(), "Index range access is only possible for arrays and array slices.");
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:2382]: Should we only use one of the two expressions slice and range? Or are these different concepts for you?

File: libsolidity/analysis/TypeChecker.cpp [hunk 12]
```diff
@@ -2341,6 +2347,47 @@ bool TypeChecker::visit(IndexAccess const& _access)
...
+bool TypeChecker::visit(IndexRangeAccess const& _access)
+{
+	_access.baseExpression().accept(*this);
+	TypePointer exprType = type(_access.baseExpression());
+	ArrayType const* arrayType = nullptr;
+
+	Expression const& start = _access.startExpression();
+	Expression const* end = _access.endExpression();
+
+	bool isLValue = false;
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Do you need these two local variables?

File: libsolidity/ast/ASTJsonConverter.cpp [hunk 13]
```diff
@@ -694,6 +694,18 @@ bool ASTJsonConverter::visit(IndexAccess const& _node)
 	return false;
 }
 
+bool ASTJsonConverter::visit(IndexRangeAccess const& _node)
+{
+	std::vector<pair<string, Json::Value>> attributes = {
+		make_pair("baseExpression", toJson(_node.baseExpression())),
```
Comment (chriseth) [inline libsolidity/ast/ASTJsonConverter.cpp:700]: Do need `..Expression` for the three of these?

File: libsolidity/ast/Types.h [hunk 14]
```diff
@@ -773,6 +773,36 @@ class ArrayType: public ReferenceType
...
+	Category category() const override { return Category::ArraySlice; }
+
+	BoolResult isImplicitlyConvertibleTo(Type const& _other) const override;
+	std::string richIdentifier() const override;
+	bool operator==(Type const& _other) const override;
+	unsigned calldataEncodedSize(bool) const override { solAssert(false, ""); }
+	unsigned calldataEncodedTailSize() const override { return 32; }
+	bool isDynamicallySized() const override { return true; }
+	bool isDynamicallyEncoded() const override { return true; }
+	u256 storageSize() const override { return 1; }
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: Is this meaningful?

File: libsolidity/ast/Types.cpp [hunk 15]
```diff
@@ -1869,6 +1869,30 @@ std::unique_ptr<ReferenceType> ArrayType::copyForLocation(DataLocation _location
...
+BoolResult ArraySliceType::isImplicitlyConvertibleTo(Type const& _other) const
+{
+	if (m_arrayType.location() == DataLocation::CallData && m_arrayType.isDynamicallySized() && m_arrayType == _other)
+		return true;
+	return (*this) == _other;
+}
+
+string ArraySliceType::richIdentifier() const
+{
+	return m_arrayType.richIdentifier() + "slice";
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: No space?

File: libsolidity/ast/Types.cpp [hunk 16]
```diff
@@ -1869,6 +1869,30 @@ std::unique_ptr<ReferenceType> ArrayType::copyForLocation(DataLocation _location
 	return copy;
 }
 
+BoolResult ArraySliceType::isImplicitlyConvertibleTo(Type const& _other) const
+{
+	if (m_arrayType.location() == DataLocation::CallData && m_arrayType.isDynamicallySized() && m_arrayType == _other)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:1874]: Convert to calldata? Where does that happen?

File: libsolidity/analysis/TypeChecker.cpp (hunk 11 above)
Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp:2382]: ``IndexSliceAccess`` or ``SliceAccess`` both sound weird at least... and I'm not sure about ``ArrayRange`` instead of ``ArraySlice`` - to me an ``ArrayRange`` would rather just be a tuple of numbers, whereas the ``ArraySlice`` is the actual subarray given by a range... but the distinction is not too important to me - I'd be fine with changing it to one or the other, if you prefer.

File: libsolidity/ast/ASTJsonConverter.cpp (hunk 13 above)
Comment (ekpyron) [reply libsolidity/ast/ASTJsonConverter.cpp:700]: Nope, but it's consistent with ``IndexAccess`` this way, that's the reason... we could change both, though?

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 17]
```diff
@@ -1503,90 +1507,160 @@ bool ExpressionCompiler::visit(IndexAccess const& _indexAccess)
...
+
+		m_context << Instruction::POP << Instruction::POP;
 	}
-	else if (baseType.category() == Type::Category::TypeType)
+	else
 	{
-		solAssert(baseType.sizeOnStack() == 0, "");
-		solAssert(_indexAccess.annotation().type->sizeOnStack() == 0, "");
-		// no-op - this seems to be a lone array type (`structType[];`)
+		m_context.appendInlineAssembly(
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: Maybe just push the length and use the same code if end expression is missing?

File: libsolidity/ast/ASTJsonConverter.cpp (hunk 13 above)
Comment (chriseth) [reply libsolidity/ast/ASTJsonConverter.cpp:700]: then it's fine!

File: libsolidity/analysis/TypeChecker.cpp (hunk 11 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:2382]: I'm only talking about the error messages for the users

File: libsolidity/ast/Types.cpp (hunk 16 above)
Comment (ekpyron) [reply libsolidity/ast/Types.cpp:1874]: ``abi.decode`` implicitly converts to ``bytes calldata``, if the first argument is in calldata and is implicitly convertible to ``bytes calldata``.
And the conversion itself is just a no-op.

**Comment by chriseth** [comment]
Fine apart from style and the fact that I think the first argument should also be optional.

File: libsolidity/ast/Types.h (hunk 14 above)
Comment (ekpyron) [reply libsolidity/ast/Types.h]: It's what dynamically sized arrays (of any kind) do - that's why it's here, since array slices are basically dynamically sized arrays with a special stack representation...

File: libsolidity/ast/Types.cpp (hunk 15 above)
Comment (ekpyron) [reply libsolidity/ast/Types.cpp]: Maybe an underscore, yeah.

File: libsolidity/analysis/TypeChecker.cpp (hunk 12 above)
Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp]: ``isLValue`` not exactly so far - but I kept it as a reminder that this has to be considered when implementing memory and storage slices... and ``isPure`` is assigned a few times and just way shorter than ``_access.baseExpression().annotation().isPure`` - it's done similarly in ``IndexAccess``

File: libsolidity/ast/Types.h (hunk 14 above)
Comment (chriseth) [reply libsolidity/ast/Types.h]: Not sure we are talking about the same thing - `storageSize` is the number of slots in storage - but this is only implemented for calldata.

**Comment by chriseth** [comment]
Looks good! Please rebase and merge.

File: libsolidity/ast/Types.h (hunk 14 above)
Comment (ekpyron) [reply libsolidity/ast/Types.h]: I removed it in any case - returning 1 is the default implementation anyways...

**Comment by ekpyron** [comment]
Rebased. I'll merge once the tests pass (except the two failing expectedly :-)).
