### PR TITLE
Fixes u256 overflow in logical shift optimization rule and adds tests.

### LINKED ISSUE #6246: u256 overflow in logical shift optimization rule leads to incorrect computation
## Description

(Found by LPM+libFuzzer: Minimized by hand)

The following code should reduce to `mstore(0,0)` instead it reduces to `mstore(0,2)`

```
{
  foo(2)
  function foo(x)
  {
    mstore(0, shl(1,shl(not(0),x)))
  }
}
```

I believe the problem lies in the following logical shift optimization rules

https://github.com/ethereum/solidity/blob/4430fe6a546c05275e72630561737b21d913eaf0/libevmasm/RuleList.h#L348-L353

wherein the following optimization happens
  - SHR(B, SHR(A, X)) -> SHR(min(A+B, 256), X)

However, for the corner cases that trigger a u256 overflow in the addition of `A` and `B` such as `B=1` and `A=not(0)`, `min(A+B, u256(256))` incorrectly reduces to `0`. When there's an overflow in the shift size, we'd want to shift by u256(256) instead.

Subsequently `SHR(0, X)` correctly reduces to `X`.

This bug/reasoning applies for the logical shift left operator as well.

This bug was a bit tricky to minimize because a simpler program such as the following is correctly computed.

```
{mstore(0, shl(1,shl(not(0),2)))}
```

Although I can't pin-point the reason for this, I guess that the optimization steps applied before logical shift optimizations (within the expression simplifier) somehow ensure that the buggy shift optimization rule is not triggered.

Introduction of a function makes it non-trivial enough for the buggy shift optimization rule to kick in.

### Potential fix

In logical shift optimization rule
  - check for u256 overflow after addition of nested shift sizes
  - in case of an overflow, do `std::max(A+B, u256(256))` where `A` and `B` are shift sizes
  - else do `std::min(A+B, u256(256))`

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: n/a

## Steps to Reproduce

The bug may be reproduced using `yulopti` using the `s` option (expression simplifier). The debug output is from the AST printer at the time expression simplifier is called first before and then after the buggy shift optimization rule has been applied.

```
$ ./test/tools/yulopti --input-file <code.yul>
----------------------                                                                          
{                                                                                               
  foo(2)                                                                                        
  function foo(x)                                                                               
  {                                                                                             
    mstore(0, shl(1,shl(not(0),x)))                                                             
  }                                                                                             
}                                                                                               
                                                                                                
(q)quit/(f)flatten/(c)se/initialize var(d)ecls/(x)plit/(j)oin/(g)rouper/(h)oister/              
  (e)xpr inline/(i)nline/(s)implify/varname c(l)eaner/(u)nusedprune/ss(a) transform/            
  (r)edundant assign elim./re(m)aterializer/f(o)r-loop-pre-rewriter/                            
  s(t)ructural simplifier/equi(v)alent function combiner/ssa re(V)erser/?                       
  stack com(p)ressor?
 s
ES AST
{
    foo(2)
    function foo(x)
    {
        mstore(0, shl(1, shl(not(0), x)))
    }
}----------------------
{
    foo(2)
    function foo(x)
    {
        mstore(0, x)
    }
}
```

### PR DESCRIPTION
**Pull request by bshastry**
### Description

(closes #6246 )

This PR fixes incorrect shift optimization due to u256 overflow in the addition of shift sizes.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### CODE REVIEW

File: libevmasm/RuleList.h [hunk 1]
```diff
@@ -46,6 +46,11 @@ template <class S> S modWorkaround(S const& _a, S const& _b)
 	return (S)(bigint(_a) % bigint(_b));
 }
 
+template <class S> S minOfu256Add(S const& _a, S const& _b, S const& _c)
```
Comment (axic) [inline libevmasm/RuleList.h]: Please move to `libdevcore/CommonData.h` after `bigintShiftLeftWorkaround`.

**Review by axic — CHANGES_REQUESTED** [review]
Please add a changelog and a buglist entry.

Also include it in the end to end tests (where the other shift combinations are).

File: libevmasm/RuleList.h (hunk 1 above)
Comment (ekpyron) [reply libevmasm/RuleList.h]: Are you sure that this makes a nice helper function? It's rather cryptic - I don't think it's apparent what it does without looking at the implementation. And it's not like we're working around a bug in boost here or something like that...

Comment (chriseth) [reply libevmasm/RuleList.h]: I also think it should just be inlined.

**Comment by chriseth** [comment]
It's currently not possible to test this in the end to end tests. I will fix that.

**Comment by chriseth** [comment]
Ah sorry, I confused this with the peephole optimizer. Of course it is possible to test these via the execution framework.

File: docs/bugs.json [hunk 2]
```diff
@@ -1,4 +1,15 @@
...
+    {
+        "name": "ShiftSizeOverflow",
+        "summary": "Using the shift left/right builtin functions such that the sum of shift sizes leads to a u256 overflow can result in unexpected values.",
+        "description": "Nested logical shift operations whose total shift size leads to a u256 overflow are incorrectly optimized.",
+	"introduced": "0.5.5",
+        "fixed": "0.5.6",
+        "severity": "medium/high",
+        "conditions": {
+            "optimizer": true
+        }
```
Comment (axic) [inline docs/bugs.json:12]: Should add `"evmVersion": ">=constantinople"`

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 3]
```diff
@@ -15109,11 +15109,21 @@ BOOST_AUTO_TEST_CASE(bitwise_shifting_constantinople_combined)
 					c := shl(0xd0, shl(0x40, a))
 				}
 			}
+			function shl_combined_overflow(uint a) public returns (uint c) {
+				assembly {
+					c := shl(0x01, shl(not(0x00), a))
```
Comment (axic) [inline test/libsolidity/SolidityEndToEndTest.cpp:15114]: I don't think there is a need for these, just supply a large value in `callContractFunction` below.

Comment (chriseth) [reply test/libsolidity/SolidityEndToEndTest.cpp:15114]: I don't understand - it only works for constants. Supply a large value where?

Comment (axic) [reply test/libsolidity/SolidityEndToEndTest.cpp:15114]: I thought it has two inputs, sorry.

File: docs/bugs.json [hunk 4]
```diff
@@ -1,4 +1,16 @@
 [
+    {
+        "name": "DoubleShiftSizeOverflow",
+        "summary": "Double bitwise shifts by large constants whose sum overflows 256 bits can result in unexpected values.",
+        "description": "Nested logical shift operations whose total shift size is 2**256 or more are incorrectly optimized. This only applies to shifts by numbers of bits that are compile-time constant expressions.",
+	    "introduced": "0.5.5",
```
Comment (axic) [inline docs/bugs.json]: Indentation?

File: Changelog.md [hunk 5]
```diff
@@ -20,6 +20,7 @@ Bugfixes:
  * SMTChecker: Fix internal compiler error when contract contains too large rational number.
  * Type system: Detect if a contract's base uses types that require the experimental abi encoder while the contract still uses the old encoder
  * Yul Optimizer: Fix visitation order bug for the structural simplifier.
+ * Yul Optimizer: Fix overflow in shift optimization rule.
```
Comment (chriseth) [inline Changelog.md]: Ah sorry, this is too specific - will change.

File: docs/bugs.json (hunk 4 above)
Comment (chriseth) [reply docs/bugs.json]: Weird, I thought I fixed it...

File: test/libyul/yulOptimizerTests/expressionSimplifier/shift_left_overflow.yul [hunk 6]
```diff
@@ -0,0 +1,14 @@
...
+  }
+}
+// ----
+// expressionSimplifier
+// {
+//     function foo(x)
+//     {
+//         mstore(0, shl(256, x))
+//     }
+// }
```
Comment (bshastry) [inline test/libyul/yulOptimizerTests/expressionSimplifier/shift_left_overflow.yul]: This test may fail because it is picked up by an IPC test involving aleth-homestead.

File: test/libyul/yulOptimizerTests/expressionSimplifier/shift_right_overflow.yul [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+  }
+}
+// ----
+// expressionSimplifier
+// {
+//     function foo(x)
+//     {
+//         mstore(0, shr(256, x))
+//     }
+// }
```
Comment (bshastry) [inline test/libyul/yulOptimizerTests/expressionSimplifier/shift_right_overflow.yul]: This test may also fail for the same reason as above.

**Review by bshastry — COMMENTED** [review]
I think the yulOptimizer tests may fail on homestead

File: test/libyul/yulOptimizerTests/expressionSimplifier/shift_left_overflow.yul (hunk 6 above)
Comment (chriseth) [reply test/libyul/yulOptimizerTests/expressionSimplifier/shift_left_overflow.yul]: Ah right, I forgot to remove them. Thanks!

**Comment by chriseth** [comment]
Changed severity to "low". The situation is comparable to `ConstantOptimizerSubtraction`.

File: libevmasm/RuleList.h [hunk 8]
```diff
@@ -349,14 +349,26 @@ std::vector<SimplificationRule<Pattern>> simplificationRuleListPart7(
 	rules.push_back({
 		// SHL(B, SHL(A, X)) -> SHL(min(A+B, 256), X)
 		{Instruction::SHL, {{B}, {Instruction::SHL, {{A}, {X}}}}},
-		[=]() -> Pattern { return {Instruction::SHL, {std::min(A.d() + B.d(), u256(256)), X}}; },
+		[=]() -> Pattern {
+			bigint sum = bigint(A.d()) + B.d();
+			if (sum >= 256)
+				return 0;
```
Comment (ekpyron) [inline libevmasm/RuleList.h]: In this case, the rule now does remove the non-constant, but it is still indicated that it doesn't by the ``false`` below. This should probably instead still return ``{Instruction::SHL, {u256(256), X}}``. Alternatively, the whole rule could rather look like:

```
[=]() -> Pattern {
  return {Instruction::SHL, {u256(std::min(bigint(A.d()) + bigint(B.d()), bigint(256))), X }};
}
```

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: libevmasm/RuleList.h (hunk 8 above)
Comment (ekpyron) [reply libevmasm/RuleList.h]: The whole thing together with the non-constant can then be conditionally removed with the mechanism in #6160 independently of this rule.

Comment (ekpyron) [reply libevmasm/RuleList.h]: I know that what I'm suggesting was one of the previous versions of this PR and that it was then explicitly changed - but won't e.g. the yul ``ExpressionSimplifier`` remove a non-movable ``X`` in certain cases if we don't change it back? ``pop(shl(1,shl(255,call(...))))`` reducing to ``pop(0)``?

Comment (chriseth) [reply libevmasm/RuleList.h]: Oh dear! Good catch!

I don't understand your last message.

Comment (ekpyron) [reply libevmasm/RuleList.h]: If you agree that this needs to be changed back, nevermind my last comment :-).

**Comment by chriseth** [comment]
Updated.

**Review by ekpyron — APPROVED** [review]
I hope I'm not missing something else, but I think it's fine now :-).
