### PR TITLE
[ewasm] Implement stop() in EVM->Ewasm translator

### LINKED ISSUE #10116: [ewasm] Missing stop() function when generating wasm code for a fallback function
Originally reported in #10100 which has more code examples.

Trying to generate wasm code for a contract that contains a fallback function results in an assertion failing due to the output being incomplete. Apparently the `stop()` function is missing.

## Steps to reproduce
```solidity
contract C {
    fallback() external {}
}
```

```bash
solc --ewasm test.sol
```

```
Exception during compilation: /solidity/libyul/backends/wasm/EVMToEwasmTranslator.cpp(1261): Throw in function solidity::yul::Object solidity::yul::EVMToEwasmTranslator::run(const solidity::yul::Object&)
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what: Invalid code generated after EVM to wasm translation.
Note that the source locations in the errors below will reference the original, not the translated code.
Translated code:
----------------------------------
object "C_5_deployed" {
...
}----------------------------------
:24:17: Warning: "switch" statement with only a default case.
                switch selector
                ^ (Relevant source part starts here and spans across multiple lines).
:30:13: Error: Function not found.
            stop()
            ^--^
```

## Environment
- Compiler version: 0.7.4+commit.3f05b770.Linux.g++

### PR DESCRIPTION
**Pull request by axic**
Fixes #10116.

### CODE REVIEW

**Review by leonardoalt — DISMISSED** [review]

**Comment by axic** [comment]
Realised the reason none of the fallback tests can be forced to work is that the calldata change was still not merged. So either a) we can blindly merge this (it does avoid the compilation error, double checked locally); or b) wait for #9508.

**Comment by leonardoalt** [comment]
I'd say we merge, but maybe let's wait for more opinions.

File: libyul/backends/wasm/BinaryTransform.cpp [hunk 1]
```diff
@@ -356,11 +356,15 @@ bytes BinaryTransform::operator()(BuiltinCall const& _call)
 	if (_call.functionName == "dataoffset")
 	{
 		string name = get<StringLiteral>(_call.arguments.at(0)).value;
+		// TODO: support the case where name refers to the current object
+		yulAssert(m_subModulePosAndSize.count(name), "");
```
Comment (axic) [inline libyul/backends/wasm/BinaryTransform.cpp:360]: Added this unrelated commit for #10117.

**Review by chriseth — APPROVED** [review]
