### PR TITLE
[Sol->Yul] Adding assertion in order to give better error messages for fixed point types

### LINKED ISSUE #10939: [Sol->Yul] ICE due to arithmetic (addition) operation on fixed point variable
## Description

```
contract C{function f()public{fixed x;x+x;}}
```

throws

https://github.com/ethereum/solidity/blob/72c6932bf5a94e097d9ac5e8c4ea0290111b1b2b/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L2718

### LINKED ISSUE #10940: [Sol->Yul] ICE due to shift operation applied on fixed point value
## Description

```
contract C {
        function f() public pure {
                fixed x;
                assert(x >>> 6 == 0);
        }
}
```

throws

https://github.com/ethereum/solidity/blob/72c6932bf5a94e097d9ac5e8c4ea0290111b1b2b/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L2759

### PR DESCRIPTION
**Pull request by mijovic**
After reading discussion in #10949 looks like the only way to do it is to add assertions for both of these issues instead of asserting earlier.

Fixes #10940
Fixes #10939 

Also, fixes issue that aggregates these two #10941

### CODE REVIEW

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -2718,7 +2718,8 @@ string IRGeneratorForStatements::binaryOperation(
 		solAssert(
 			_type.category() == Type::Category::Integer ||
 			_type.category() == Type::Category::FixedBytes,
-		"");
+			""
+		);
```
Comment (mijovic) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:2722]: This was just a random code style issue I found

**Review by Marenz — APPROVED** [review]
