### PR TITLE
Report meaningful error if parsing a version pragma failed

### LINKED ISSUE #10411: Confusing error message for missing `;` in pragma
Compiling the following contract with `solc-0.7.5`:
```
pragma solidity ^0.7.5
pragma experimental ABIEncoderV2;

contract A {
}
```
yields the error message:
```
Error: Source file requires different compiler version (current compiler is 0.7.5+commit.eb77ed08.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> src/hmm.sol:1:1:
  |
1 | pragma solidity ^0.7.5
  | ^ (Relevant source part starts here and spans across multiple lines).
```
But the error is actually a missing semicolon in the first pragma line

### PR DESCRIPTION
**Pull request by axic**
Fixes #10411.

### CODE REVIEW

File: liblangutil/SemVerHandler.cpp [hunk 1]
```diff
@@ -166,6 +166,7 @@ SemVerMatchExpression SemVerMatchExpressionParser::parse()
 	catch (SemVerError const&)
 	{
 		reset();
+		return nullopt;
```
Comment (axic) [inline liblangutil/SemVerHandler.cpp:169]: We could also rethrow the exception, instead of returning an option.

File: test/libsolidity/syntaxTests/pragma/broken_version_1.sol [hunk 2]
```diff
@@ -0,0 +1,3 @@
+pragma solidity ^0^1;
```
Comment (axic) [inline test/libsolidity/syntaxTests/pragma/broken_version_1.sol:1]: Why is this parsed? And into what exactly?

File: test/libsolidity/syntaxTests/pragma/broken_version_2.sol [hunk 3]
```diff
@@ -0,0 +1,3 @@
+pragma solidity pragma;
```
Comment (axic) [inline test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: @ekpyron The grammar file accepts this, while the parser (now) doesn't. Not sure what to do. Perhaps remove this test?

File: libsolidity/parsing/Parser.cpp [hunk 4]
```diff
@@ -140,9 +140,16 @@ void Parser::parsePragmaVersion(SourceLocation const& _location, vector<Token> c
...
 	auto matchExpression = parser.parse();
+	if (!matchExpression.has_value())
+		m_errorReporter.fatalParserError(
+			1684_error,
+			_location,
+			"Found version pragma, but failed to parse it. "
+			"Please ensure there is a trailing semicolon."
+		);
 	static SemVerVersion const currentVersion{string(VersionString)};
 	// FIXME: only match for major version incompatibility
```
Comment (axic) [inline libsolidity/parsing/Parser.cpp:151]: Do we actually want this? I am not proposing to do it in this PR, but we could remove this todo if it actually doesn't make sense.

File: test/libsolidity/syntaxTests/pragma/broken_version_2.sol (hunk 3 above)
Comment (ekpyron) [reply test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: Don't remove the test - if fixing the grammar is not an option, resp. more trouble than it's worth (and here that might be the case), then add the error id to the exclude list in `test/test_antrl*` (whatever the name of the script there)

Comment (axic) [reply test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: Thanks! I think it is more trouble, because the grammar correctly just assumes anything goes (we would need to have a "version pragma" lexer mode). This is a special case I'd say not worth the effort.

File: test/libsolidity/syntaxTests/pragma/broken_version_1.sol (hunk 2 above)
Comment (leonardoalt) [reply test/libsolidity/syntaxTests/pragma/broken_version_1.sol:1]: Dunno

File: liblangutil/SemVerHandler.cpp (hunk 1 above)
Comment (leonardoalt) [reply liblangutil/SemVerHandler.cpp:169]: Fine with option

File: libsolidity/analysis/SyntaxChecker.cpp [hunk 5]
```diff
@@ -160,8 +160,10 @@ bool SyntaxChecker::visit(PragmaDirective const& _pragma)
 		vector<string> literals(_pragma.literals().begin() + 1, _pragma.literals().end());
 		SemVerMatchExpressionParser parser(tokens, literals);
 		auto matchExpression = parser.parse();
+		// An unparsable version pragma is an unrecoverable fatal error in the parser.
```
Comment (leonardoalt) [inline libsolidity/analysis/SyntaxChecker.cpp:163]:
```suggestion
		// An unparseable version pragma is an unrecoverable fatal error in the parser.
```

File: libsolidity/parsing/Parser.cpp [hunk 6]
```diff
@@ -140,9 +140,16 @@ void Parser::parsePragmaVersion(SourceLocation const& _location, vector<Token> c
...
-	if (!matchExpression.matches(currentVersion))
+	if (!matchExpression->matches(currentVersion))
```
Comment (leonardoalt) [inline libsolidity/parsing/Parser.cpp:152]: Won't this throw if `has_value == false`?

File: libsolidity/parsing/Parser.cpp (hunk 4 above)
Comment (leonardoalt) [reply libsolidity/parsing/Parser.cpp:151]: Also not sure. Why match for major incomp. only?

File: libsolidity/analysis/SyntaxChecker.cpp (hunk 5 above)
Comment (axic) [reply libsolidity/analysis/SyntaxChecker.cpp:163]: Spellcheck complained, apparently this is the correct one: https://www.lexico.com/en/definition/unparsable

File: libsolidity/parsing/Parser.cpp (hunk 6 above)
Comment (axic) [reply libsolidity/parsing/Parser.cpp:152]: There's a fatal error above for that.

File: libsolidity/analysis/SyntaxChecker.cpp (hunk 5 above)
Comment (leonardoalt) [reply libsolidity/analysis/SyntaxChecker.cpp:163]: Lol ok

File: libsolidity/parsing/Parser.cpp (hunk 6 above)
Comment (leonardoalt) [reply libsolidity/parsing/Parser.cpp:152]: Ah true, didn't notice it was fatal

File: libsolidity/parsing/Parser.cpp (hunk 4 above)
Comment (axic) [reply libsolidity/parsing/Parser.cpp:151]: I think the idea was that it is reported later nicely, but recoverable parser errors make this more complicated, and I think the reporting (here and in SyntaxChecker) are identical, so it is fine.

File: test/libsolidity/syntaxTests/pragma/broken_version_2.sol (hunk 3 above)
Comment (axic) [reply test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: Disabled. Let's see if anyone complains about the grammar not being super strict enough 😉

Comment (leonardoalt) [reply test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: The grammar isn't precise. What is the point even

Comment (axic) [reply test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: The point of the grammar or the point of the people wanting it to be 100% match?

Comment (leonardoalt) [reply test/libsolidity/syntaxTests/pragma/broken_version_2.sol:1]: The point of the grammar (it was a joke)

File: test/libsolidity/syntaxTests/pragma/broken_version_1.sol (hunk 2 above)
Comment (axic) [reply test/libsolidity/syntaxTests/pragma/broken_version_1.sol:1]: Apparently it only parsed until `^0`, validating that major is 0, and ignored the rest. Fixed.

**Review by leonardoalt — DISMISSED** [review]

**Review by leonardoalt — DISMISSED** [review]

File: liblangutil/SemVerHandler.cpp [hunk 7]
```diff
@@ -227,6 +228,8 @@ SemVerMatchExpression::MatchComponent SemVerMatchExpressionParser::parseMatchCom
 		component.levelsPresent++;
 		if (currentChar() == '.')
 			nextChar();
+		else if ('0' < currentChar() || currentChar() > '9')
```
Comment (axic) [inline liblangutil/SemVerHandler.cpp]: Hmm, maybe need to check for EOF here, one more test needed I guess 😬

File: test/libsolidity/syntaxTests/pragma/broken_version_1.sol (hunk 2 above)
Comment (axic) [reply test/libsolidity/syntaxTests/pragma/broken_version_1.sol:1]: Apparently the tests we have suggest there's some weird support for these. Will split the PR into two.

**Comment by axic** [comment]
External zeppelin tests fail with:
```
Error executing vyper:
/bin/sh: 1: vyper: not found
```

**Comment by axic** [comment]
@leonardoalt can you reapprove?

**Review by leonardoalt — APPROVED** [review]
