### PR TITLE
typeCheckAbiEncodeCallFunction should type check the arguments on functionPointerType->asExternallyCallableFunction instead of the plain function type

### LINKED ISSUE #12718: `abi.encodeCall` does not properly convert the function type to an externally-called function
## Abstract

The following gives an error:

```solidity
pragma solidity 0.8.12;

contract Sender {
    function main(string memory helloworld) external {
        // TypeError: Cannot implicitly convert component at position 0 from "string" to "string".
        abi.encodeCall(IReceiver.methodName, (helloworld));
    }
}

interface IReceiver {
    function methodName(string calldata) external;
}
```

## Motivation

When encoding data for a call, it shouldn't really matter if it's calldata or memory. If the interface has calldata, but if the value that we want to pass is in memory, it triggers the typecheck error abi.encodeCall. 

## Specification

abi.encodeCall should not typecheck data location.

## Backwards Compatibility

This should not have any breakings.

### PR DESCRIPTION
**Pull request by nishant-sachdeva**
Closes #12718

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2190,7 +2190,9 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 	for (size_t i = 0; i < numParameters; i++)
 	{
 		Type const& argType = *type(*callArguments[i]);
-		BoolResult result = argType.isImplicitlyConvertibleTo(*functionPointerType->parameterTypes()[i]);
+		BoolResult result = argType.isImplicitlyConvertibleTo(*functionPointerType->asExternallyCallableFunction(
+								functionPointerType->kind() == FunctionType::Kind::DelegateCall ? true:false
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp]: Why not
```suggestion
								functionPointerType->kind() == FunctionType::Kind::DelegateCall
```
?

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -2190,7 +2190,11 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 	for (size_t i = 0; i < numParameters; i++)
 	{
 		Type const& argType = *type(*callArguments[i]);
-		BoolResult result = argType.isImplicitlyConvertibleTo(*functionPointerType->parameterTypes()[i]);
+		BoolResult result = argType.isImplicitlyConvertibleTo(
+								*functionPointerType->asExternallyCallableFunction(
+									functionPointerType->kind() == FunctionType::Kind::DelegateCall
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp]: Looking at the code above: this is always false, isn't it :-)? ``functionPointerType->kind() == FunctionType::Kind::DelegateCall`` is an error case above that returns early, right?

Comment (nishant-sachdeva) [reply libsolidity/analysis/TypeChecker.cpp]: Yes. You're right. Will change it in the next push.

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -2190,7 +2190,10 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 	for (size_t i = 0; i < numParameters; i++)
 	{
 		Type const& argType = *type(*callArguments[i]);
-		BoolResult result = argType.isImplicitlyConvertibleTo(*functionPointerType->parameterTypes()[i]);
+		// functionPointerType is never equal to DelegateCall ( it would have thrown error above )
+		BoolResult result = argType.isImplicitlyConvertibleTo(
+								*functionPointerType->asExternallyCallableFunction(false)->parameterTypes()[i]
+							);
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Indentation is off here

File: libsolidity/analysis/TypeChecker.cpp [hunk 4]
```diff
@@ -2196,7 +2196,10 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 	for (size_t i = 0; i < numParameters; i++)
 	{
 		Type const& argType = *type(*callArguments[i]);
-		BoolResult result = argType.isImplicitlyConvertibleTo(*functionPointerType->parameterTypes()[i]);
+		// functionPointerType is never equal to DelegateCall ( it would have thrown error above )
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp]: I'd say you can either just drop the comment or if it should be more explicit make it a proper
```suggestion
		solAssert(functionPointerType->kind() != FunctionType::Kind::Declaration);
```

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: See line 2124. I would actually do the conversion to external callable function much closer to where the pointer is defined.

Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp]: Yeah, I was actually wondering whether to suggest that as well!

File: test/libsolidity/semanticTests/abiEncoderV1/bool_out_of_bounds.sol [hunk 5]
```diff
@@ -3,9 +3,10 @@ contract C {
 	function f(bool b) public pure returns (bool) { return b; }
 }
 // ====
+// compileViaYul: false
```
Comment (chriseth) [inline test/libsolidity/semanticTests/abiEncoderV1/bool_out_of_bounds.sol]: Please revert these, there is no `abi.encodeCall` in these tests, so they should not change.

**Comment by chriseth** [comment]
@ekpyron I'm seeing that ExpressionCompiler.cpp just calls `abiEncode` without a target type. Is this actually safe?

**Comment by ekpyron** [comment]
> @ekpyron I'm seeing that ExpressionCompiler.cpp just calls `abiEncode` without a target type. Is this actually safe?

We should at least change it, but let me think if I can come up with an example that breaks.

**Comment by ekpyron** [comment]
``IRGeneratorForStatements.cpp`` also doesn't use the parameter types of the function type, but the encoding types of the argument tuple...

File: test/libsolidity/semanticTests/abiEncoderV1/bool_out_of_bounds.sol (hunk 5 above)
Comment (nishant-sachdeva) [reply test/libsolidity/semanticTests/abiEncoderV1/bool_out_of_bounds.sol]: Reverted the changes in the latest push.

File: Changelog.md [hunk 6]
```diff
@@ -10,6 +10,7 @@ Compiler Features:
 
 Bugfixes:
  * Yul IR Code Generation: Optimize embedded creation code with correct settings. This fixes potential mismatches between the constructor code of a contract compiled in isolation and the bytecode in ``type(C).creationCode``, resp. the bytecode used for ``new C(...)``.
+* TypeChecker: ABIEncodeCallFunction properly converts function type to externally called function.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
* TypeChecker: Use external function parameter types for `abi.encodeCall`.
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 7]
```diff
@@ -2154,7 +2154,10 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 		return;
 	}
 
-	solAssert(!functionPointerType->takesArbitraryParameters(), "Function must have fixed parameters.");
+	solAssert(functionPointerType->kind() != FunctionType::Kind::DelegateCall);
+	auto const externallyCallableFunction = functionPointerType->asExternallyCallableFunction(false);
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: I'd call it `externalFunctionType` since it's still a function type.

Also, we generally avoid `auto` unless the type is obvious from context - as it was at the point of declaration of `functionPointerType` due to `dynamic_cast`. Here it's not. And when we use auto, we at least include the `*` or `&` to make it clear that it's a pointer/reference.

```suggestion
	FunctionType const* externalFunctionType = functionPointerType->asExternallyCallableFunction(false);
```

File: Changelog.md [hunk 8]
```diff
@@ -10,6 +10,7 @@ Compiler Features:
 
 Bugfixes:
  * Yul IR Code Generation: Optimize embedded creation code with correct settings. This fixes potential mismatches between the constructor code of a contract compiled in isolation and the bytecode in ``type(C).creationCode``, resp. the bytecode used for ``new C(...)``.
+* TypeChecker: Use external function parameter types for `abi.encodeCall`.
```
Comment (Marenz) [inline Changelog.md]: I think a better description would be "Use location independent type checking for function parameter types used with `abi.encodeCall`"

File: libsolidity/analysis/TypeChecker.cpp (hunk 7 above)
Comment (Marenz) [inline libsolidity/analysis/TypeChecker.cpp]: Just a though, might it be better to overwrite `functionPointerType` with the result of this call instead? It is not used afterwards but could lead to accidentally be used in the future if one is not careful.

**Review by Marenz — CHANGES_REQUESTED** [review]

File: test/libsolidity/syntaxTests/abiEncoder/passing_memory_to_interface_that_expects_calldata_should_not_throw.sol [hunk 9]
```diff
@@ -0,0 +1,10 @@
+contract Sender {
```
Comment (cameel) [inline test/libsolidity/syntaxTests/abiEncoder/passing_memory_to_interface_that_expects_calldata_should_not_throw.sol]: I think this should be more thoroughly tested. The reporter provided one case but when implementing a fix, please always try to come up with other similar cases and add some of them. For example here:
- I'd test all the 6 combinations (`calldata`/`calldata`, `memory`/`calldata`, `calldata`/`memory`, `memory`/`memory`, `storage`/`calldata`, `storage`/`memory`). `memory`/`memory` is probably already covered by existing tests but please check.
- Are there any other types that could cause a mismatch like this?
    - So far I managed to come up with three (see https://github.com/ethereum/solidity/issues/12718#issuecomment-1064322093). Please add these as test cases here and check if your fix already covers them. Also, please try to see if you can come up with more.
    - For a good measure I'd still add some more types in this case: `bytes`, static and dynamic array, struct.
- A semantic test for the `calldata`/`memory` case would not hurt - so that we're sure that codegen can actually handle it correctly despite the slight difference in types. A function pointer case might also warrant a semantic test since I remember that we did have some asserts failing at some point because they did not expect slightly different pointer types. I'd verify it works at least.

**Review by cameel — CHANGES_REQUESTED** [review]

File: Changelog.md (hunk 8 above)
Comment (cameel) [reply Changelog.md]: It's actually not only about location. You get the same thing with `address` vs `address payable` for example.

But I agree that this changelog entry could be a bit less terse. It's technically correct but as a user I think I'd have trouble figuring out what it really means.

File: libsolidity/analysis/TypeChecker.cpp (hunk 7 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: Not sure about others but personally I prefer choosing names that are distinct enough and keeping the original variable over overwriting the same variable with something slightly different. I actually wish variables were `const` by default, which would somewhat discourage overwriting them. You might still want to access the previous value later or you could move a chunk of code not realizing that at the new location the variable has a new meaning.

**Comment by cameel** [comment]
I just tested the `b_ubu_static` artifact from this PR with the cases I listed in https://github.com/ethereum/solidity/issues/12718#issuecomment-1064322093 and looks like the PR does fix them. I.e. it fixes the first one and the other two are actually expected to error out due to types that are not implicitly convertible.

**Comment by cameel** [comment]
Ah, wait. The case with function pointers is actually valid. This is the same exact function type and it's rejected simply because the function type has a `calldata` argument. For `memory` it does not happen. The PR does not fix that problem.

File: libsolidity/analysis/TypeChecker.cpp (hunk 7 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: If you need to access something later, you can always change it back, in that case it is at least a very conscious decision to do so.
An alternative could be to never declare `functionPointerType` in the function scope but a tiny sub-scope where the only thing it does is assigning to an `externallyCallableFunction` (or however you want to call it) variable in the function scope.
As before, if you DO need to access it at a later time, you can always move it out of the scope.

Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp]: > An alternative could be to never declare `functionPointerType` in the function scope

Yeah, I agree, this would be much better.

**Comment by ekpyron** [comment]
> Ah, wait. The case with function pointers is actually valid. This is the same exact function type and it's rejected simply because the function type has a `calldata` argument. For `memory` it does not happen. The PR does not fix that problem.

That's a separate issue, though, isn't it? That also doesn't work for directly calling a function...
<details>
<pre>
interface I {
      function f(function (string calldata) external) external;
  }
  
  contract C {
      function g(string calldata) external {}
  
      function main() external view {
          I x;
          x.f(this.g);
          abi.encodeCall(I.f, (this.g));
      }
  }
</pre>
fails with both
<pre>
Error: Invalid type for argument in function call. Invalid implicit conversion from function (string memory) external to function (string calldata) external requested.
  --> test.sol:10:6:
   |
10 |    x.f(this.g);
   |        ^^^^^^

Error: Cannot implicitly convert component at position 0 from "function" to "function".
  --> test.sol:11:29:
   |
11 |         abi.encodeCall(I.f, (this.g));
   |                             ^^^^^^^^
</pre>
after this PR

</details>

So that should be fixed in ``asExternallyCallableFunction`` (or whatever it's coming from) instead.

**Comment by cameel** [comment]
> That's a separate issue, though, isn't it?

True. Looks like it's not a problem with `abi.encodeCall()` but a more general one. I'll report a separate issue so that we can focus only on `encodeCall()` here.

**Comment by cameel** [comment]
Reported in #12778.

**Comment by chriseth** [comment]
there is a coding style problem

**Comment by cameel** [comment]
Also, still needs more test cases in my opinion.

File: libsolidity/analysis/TypeChecker.cpp [hunk 10]
```diff
@@ -2111,57 +2111,61 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
...
+				"Expected first argument to be a function pointer, not \"" +
+				type(*arguments.front())->toString() +
+				"\"."
+			);
+			return;
+		}
+
+		externalFunctionType = functionPointerType->asExternallyCallableFunction(
+													functionPointerType->kind() == FunctionType::Kind::DelegateCall
+												);
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
		externalFunctionType = functionPointerType->asExternallyCallableFunction(
			functionPointerType->kind() == FunctionType::Kind::DelegateCall
		);
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 11]
```diff
@@ -2111,57 +2111,61 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
...
-		m_errorReporter.typeError(
-			5511_error,
-			arguments.front()->location(),
-			"Expected first argument to be a function pointer, not \"" +
-			type(*arguments.front())->canonicalName() +
-			"\"."
-		);
-		return;
+		auto const functionPointerType = dynamic_cast<FunctionTypePointer>(type(*arguments.front()));
+		if (!functionPointerType)
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Another way to avoid having this extra variable visible in the whole function, without introducing an artificial block, would be to do this:
```suggestion
		if (auto const functionPointerType = dynamic_cast<FunctionTypePointer>(type(*arguments.front())))
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 12]
```diff
@@ -2111,57 +2111,61 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
...
+				arguments.front()->location(),
+				"Expected first argument to be a function pointer, not \"" +
+				type(*arguments.front())->toString() +
+				"\"."
+			);
+			return;
+		}
+
+		externalFunctionType = functionPointerType->asExternallyCallableFunction(
+													functionPointerType->kind() == FunctionType::Kind::DelegateCall
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Can this actually be a delegatecall in practice? I think you had an assert before and that seemed fine to me.

File: test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol [hunk 13]
```diff
@@ -0,0 +1,30 @@
...
+contract testContract {
+    function g(string calldata) external {}
+    function h(string memory) external {}
+    string s;
+
+    function main() external view {
+        abi.encodeCall(testInterface.A, (address(0)));
+        abi.encodeCall(testInterface.B, (s));
+        abi.encodeCall(testInterface.C, (s));
+        abi.encodeCall(testInterface.D, (s));
```
Comment (cameel) [inline test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol:27]: This covers the `storage`/`calldata` combination. Can you also add others for full coverage, like I mentioned in https://github.com/ethereum/solidity/pull/12750/files#r823996395?
- Encoding a `calldata` value as an input for a `calldata` argument
- Encoding a `calldata` value as an input for a `memory` argument
- Encoding a `memory` value as an input for a `calldata` argument
- Encoding a `storage` value as an input for a `memory` argument

File: test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol [hunk 14]
```diff
@@ -0,0 +1,30 @@
...
+    function D(string calldata) external;
+}
+
+contract testContract {
+    function g(string calldata) external {}
+    function h(string memory) external {}
+    string s;
+
+    function main() external view {
+        abi.encodeCall(testInterface.A, (address(0)));
```
Comment (cameel) [inline test/libsolidity/syntaxTests/abiEncoder/abi_encode_conversions.sol]: Can you also add a test the other way around? I.e. encoding `address payable` as an input for an `address` argument?

File: test/libsolidity/syntaxTests/abiEncoder/passing_memory_to_interface_that_expects_calldata_should_not_throw.sol (hunk 9 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/abiEncoder/passing_memory_to_interface_that_expects_calldata_should_not_throw.sol]: Could you add some of these?

File: libsolidity/analysis/TypeChecker.cpp (hunk 12 above)
Comment (nishant-sachdeva) [reply libsolidity/analysis/TypeChecker.cpp]: I felt this made it much more readable.
Plus there is a check in the code below, that carries an assert that it can't be DelegateCall. 
So, having an assert here as well seemed repetitive.

File: libsolidity/analysis/TypeChecker.cpp [hunk 15]
```diff
@@ -2111,57 +2111,58 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 		return;
 	}
 
-	auto const functionPointerType = dynamic_cast<FunctionTypePointer>(type(*arguments.front()));
-
-	if (!functionPointerType)
+	FunctionType const* externalFunctionType = nullptr;
+	if (auto const functionPointerType = dynamic_cast<FunctionTypePointer>(type(*arguments.front())))
+		externalFunctionType = functionPointerType->asExternallyCallableFunction(
+			functionPointerType->kind() == FunctionType::Kind::DelegateCall
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: This should notbe true - see below.

File: Changelog.md [hunk 16]
```diff
@@ -37,6 +37,7 @@ Bugfixes:
  * General: Fix internal error for locales with unusual capitalization rules. Locale set in the environment is now completely ignored.
  * Type Checker: Fix incorrect type checker errors when importing overloaded functions.
  * Yul IR Code Generation: Optimize embedded creation code with correct settings. This fixes potential mismatches between the constructor code of a contract compiled in isolation and the bytecode in ``type(C).creationCode``, resp. the bytecode used for ``new C(...)``.
+* TypeChecker: Use external function parameter types for `abi.encodeCall`.
```
Comment (chriseth) [inline Changelog.md]: This has to be moved to the new version.

File: libsolidity/analysis/TypeChecker.cpp [hunk 17]
```diff
@@ -2111,57 +2111,59 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
...
 
-	auto const functionPointerType = dynamic_cast<FunctionTypePointer>(type(*arguments.front()));
-
-	if (!functionPointerType)
+	FunctionType const* externalFunctionType = nullptr;
+	if (auto const functionPointerType = dynamic_cast<FunctionTypePointer>(type(*arguments.front())))
+	{
+		// functionPointerType->kind() != FunctionType::Kind::DelegateCall
+		externalFunctionType = functionPointerType->asExternallyCallableFunction(false);
+	}
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
		// this cannot be a library function, that is checked below
		externalFunctionType = functionPointerType->asExternallyCallableFunction(false);
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 18]
```diff
@@ -2111,57 +2111,59 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
...
 			"Expected first argument to be a function pointer, not \"" +
-			type(*arguments.front())->canonicalName() +
+			type(*arguments.front())->toString() +
 			"\"."
 		);
 		return;
 	}
 
 	if (
-		functionPointerType->kind() != FunctionType::Kind::External &&
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:2129]: Please do this check on the original type. Otherwise I think we would introduce a bug.

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:2129]: Ah ok, it currently is the same thing. Then please add an assertion above that the kind is the same for both type pointers.

File: test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol [hunk 19]
```diff
@@ -1,11 +0,0 @@
-interface I {
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol:1]: Why did you delete these tests?

File: Changelog.md (hunk 8 above)
Comment (chriseth) [reply Changelog.md]: What about `Convert parameters of function type to how they would be called for abi.encodeCall.`?

File: test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol (hunk 19 above)
Comment (nishant-sachdeva) [reply test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol:1]: Seemed redundant to have them spread across different files. Now we have them in two files based on whether the code is working correctly or not.

Edit : It's not a perfectly working/not-working split. The idea of the split is to keep the test cases concerning function pointers (something that the this PR does not fix and which will be fixed with #12778) in a separate file and all the other test cases concerning this issue in one file.

Comment (chriseth) [reply test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol:1]: Ah, you just moved them!
I don't see that they are properly split into working / not working, though.

Comment (nishant-sachdeva) [reply test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol:1]: Ah yes, it's not a perfect split. 
The issue #12778 that should be solving the error statements coming in these functions only mentioned functions. So, I didn't move the address pointer test to the other file

Comment (chriseth) [reply test/libsolidity/syntaxTests/abiEncoder/abi_encode_convert_address_to_address_payable.sol:1]: Please do it properly. When we address #12778 we can still change the tests.

File: Changelog.md [hunk 20]
```diff
@@ -8,6 +8,7 @@ Compiler Features:
 
 
 Bugfixes:
+* TypeChecker: Convert parameters of function type to how they would be called for abi.encodeCall.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
* TypeChecker: Convert parameters of function type to how they would be called for ``abi.encodeCall``.
```

File: Changelog.md [hunk 21]
```diff
@@ -38,7 +39,6 @@ Bugfixes:
  * Type Checker: Fix incorrect type checker errors when importing overloaded functions.
  * Yul IR Code Generation: Optimize embedded creation code with correct settings. This fixes potential mismatches between the constructor code of a contract compiled in isolation and the bytecode in ``type(C).creationCode``, resp. the bytecode used for ``new C(...)``.
 
-
```
Comment (chriseth) [inline Changelog.md]: Please undo this.

**Review by chriseth — APPROVED** [review]
