### PR TITLE
[SMTChecker] Fix ICE on unique error reporting

### LINKED ISSUE #11878: [SMTChecker] ICE in UniqueErrorReporter::seen
Create three files named like so

`a.sol`

```
contract A{uint x;}
```

`b.sol`

```
import"a.sol";
contract B is A {
  function g() public { assert(x>x); }
}
```

`c.sol`
```
import "b.sol";
pragma experimental SMTChecker;
contract C is B {
  function h(uint x) public { assert(x<x); }
}
```

```
$ solc a.sol b.sol c.sol
Internal compiler error during compilation:
/solidity/liblangutil/UniqueErrorReporter.h(72): Throw in function bool solidity::langutil::UniqueErrorReporter::seen(solidity::langutil::ErrorId, const solidity::langutil::SourceLocation &, const std::string &) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] =
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/11878

The bug hasn't been released yet, so no need for a Changelog entry.
Thanks for finding it so quickly @bshastry !

### CODE REVIEW

**Review by cameel — DISMISSED** [review]
Are those all errors without location or only some of them? Looks like they are a bigger problem that I thought. Good that we at least have the assert to detect them.

**Comment by cameel** [comment]
Looks like some extracted tests need to have their messages updated.

**Comment by leonardoalt** [comment]
Not only messages, there's a problem I'm not sure how to solve.
`test/SyntaxTest.cpp` assumes the only errors with `location->start == 0` are the SPDX and pragma warnings. But since these changes that this PR does report warnings on `_source.location()`, it goes through the same conditions as the ones above and the things go wrong from there. Still need to figure out what to do there.

**Comment by cameel** [comment]
Maybe there's code that filters it out and assumes that the message contains no location info?

**Comment by leonardoalt** [comment]
@cameel https://github.com/ethereum/solidity/blob/develop/test/libsolidity/SyntaxTest.cpp#L132
This is the code I'm talking about. Not sure if that's what you meant, but yea it assumes that the license and version lines are there, and adjusts the location of every warning with `location = location - (version+license)`. I'll have to change this bit to allow my warnings that start at 0, but it might get a bit hacky

**Comment by leonardoalt** [comment]
This is ready for review now

File: test/cmdlineTests/model_checker_solvers_smtlib2/err [hunk 1]
```diff
@@ -1,7 +1,23 @@
...
+ --> model_checker_solvers_smtlib2/input.sol:2:1:
+  |
+2 | pragma solidity >=0.0;
+  | ^ (Relevant source part starts here and spans across multiple lines).
 
 Warning: BMC analysis was not possible. No SMT solver (Z3 or CVC4) was available. None of the installed solvers was enabled.
+ --> model_checker_solvers_smtlib2/input.sol:2:1:
+  |
+2 | pragma solidity >=0.0;
+  | ^ (Relevant source part starts here and spans across multiple lines).
```
Comment (cameel) [inline test/cmdlineTests/model_checker_solvers_smtlib2/err]: I can see now why these had no location :) Printing this does seem a bit useless. Maybe we could deal with it in a more generic way - by not printing the source if it spans the whole contract and has multiple lines?

Alternatively - maybe the mechanism for cutting out repeated errors should just ignore errors without location?

File: test/libsolidity/SyntaxTest.cpp [hunk 2]
```diff
@@ -132,8 +132,13 @@ void SyntaxTest::filterObtainedErrors()
...
-				locationStart = location->start - preambleSize;
+				if (location->start >= preambleSize)
+					locationStart = location->start - preambleSize;
+				else
+				{
+					solAssert(location->start == 0, "");
+					locationStart = 0;
+				}
 			}
 			if (location->end != -1)
```
Comment (cameel) [inline test/libsolidity/SyntaxTest.cpp]: Not adjusting `end` will result in the error not covering the whole file. This might look a bit weird, but I don't have a good solution other than making the SMTChecker aware of the preamble and that sounds like bad idea.

File: test/libsolidity/SyntaxTest.cpp [hunk 3]
```diff
@@ -132,8 +132,13 @@ void SyntaxTest::filterObtainedErrors()
 			// ignore the version & license pragma inserted by the testing tool when calculating locations.
 			if (location->start != -1)
 			{
-				solAssert(location->start >= preambleSize, "");
-				locationStart = location->start - preambleSize;
+				if (location->start >= preambleSize)
```
Comment (cameel) [inline test/libsolidity/SyntaxTest.cpp]: It would be a good idea to add a comment explaining the weirdness happening here:
```suggestion
				// Preamble is not in the original input so error locations need to be shifted back.
				// Normally this is safe because errors should not happen inside preamble. Errors
				// covering the whole file are a special case because they start at 0, not after the preamble.
				if (location->start >= preambleSize)
```

**Review by cameel — COMMENTED** [review]
Looks ok but the hack is not pretty. The whole preamble thing is a hack though and I it's hard to suggest something clean here.

Maybe ignoring errors without location during duplicate removal would be a better solution to the problem overall?

**Comment by leonardoalt** [comment]
I mean, in the end I felt like this wasn't a hack anymore, just another rule "if the error actually is about position 0, just keep it"

File: test/cmdlineTests/model_checker_solvers_smtlib2/err (hunk 1 above)
Comment (leonardoalt) [reply test/cmdlineTests/model_checker_solvers_smtlib2/err]: Yea I think I prefer the second idea. The first one might touch parts outside the smtchecker that I'm not aware of.

**Comment by leonardoalt** [comment]
I'll fix it on the error duplicate removal layer, so we don't have to touch the tests part hopefully.

**Comment by leonardoalt** [comment]
@cameel fixed it by ignoring the check for errors without SourceLocation

File: liblangutil/UniqueErrorReporter.h [hunk 4]
```diff
@@ -77,7 +77,8 @@ class UniqueErrorReporter
 
 	void markAsSeen(ErrorId _error, SourceLocation const& _location, std::string const& _description)
 	{
-		solAssert(!seen(_error, _location, _description), "");
+		if (_location != SourceLocation{})
+			solAssert(!seen(_error, _location, _description), "");
 		m_seenErrors[{_error, _location}] = _description;
```
Comment (cameel) [inline liblangutil/UniqueErrorReporter.h]: Wouldn't it be better not to mark these errors as seen at all?

Comment (leonardoalt) [reply liblangutil/UniqueErrorReporter.h]: Updated

File: liblangutil/UniqueErrorReporter.h [hunk 5]
```diff
@@ -58,11 +58,7 @@ class UniqueErrorReporter
 
 	void warning(ErrorId _error, std::string const& _description)
 	{
-		if (!seen(_error, {}, _description))
-		{
-			m_errorReporter.warning(_error, _description);
-			markAsSeen(_error, {}, _description);
-		}
+		markAsSeen(_error, {}, _description);
```
Comment (cameel) [inline liblangutil/UniqueErrorReporter.h]: I think you may have left the wrong line here :)
```suggestion
		m_errorReporter.warning(_error, _description);
```

File: test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+==== Source: c.sol ====
+import "b.sol";
+contract C is B {
+	function h(uint x) public pure { assert(x < x); }
+}
+// ====
+// SMTEngine: all
+// ----
+// Warning 6328: (b.sol:62-75): CHC: Assertion violation happens here.\nCounterexample:\nx = 0\n\nTransaction trace:\nB.constructor()\nState: x = 0\nB.g()
+// Warning 6328: (c.sol:68-81): CHC: Assertion violation happens here.\nCounterexample:\nx = 0\nx = 0\n\nTransaction trace:\nC.constructor()\nState: x = 0\nC.h(0)
```
Comment (cameel) [inline test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: Actually, why do these have locations? Wasn't the error triggered by errors with different descriptions and no location?

**Review by cameel — COMMENTED** [review]
Looks much neater overall.

Weirdly, tests are failing due to gas differences. The PR does not touch anything that could trigger that though. Is `develop` broken?

File: liblangutil/UniqueErrorReporter.h (hunk 5 above)
Comment (leonardoalt) [reply liblangutil/UniqueErrorReporter.h]: ah damn true

File: test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol (hunk 6 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: These are triggered by the assertions themselves, that's why they have locations.

**Comment by leonardoalt** [comment]
> Looks much neater overall.
> 
> Weirdly, tests are failing due to gas differences. The PR does not touch anything that could trigger that though. Is `develop` broken?

let me rebase and run it locally

**Comment by cameel** [comment]
I just got these in my PRs. So yeah, `develop` must be broken.

File: test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol (hunk 6 above)
Comment (cameel) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: So there should be more errors here? Perhaps they did not get printed due to the bug in `warning()`?

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: Why should there be more errors? I think this is correct.

Comment (cameel) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: In that case I don't understand why the ICE got triggered in the first place.

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: Good q, let me think

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: Weird, I'm re-running the issue on develop and it doesn't happen anymore.

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/imports/duplicated_errors_1.sol]: Ahh ok it happens only when there are no solvers available

**Comment by leonardoalt** [comment]
@cameel now it all makes much more sense :)

**Review by cameel — DISMISSED** [review]

**Comment by leonardoalt** [comment]
@cameel can you reapprove?

**Review by cameel — APPROVED** [review]
