### PR TITLE
Fix NULL dereference in abi.encodeCall check

### LINKED ISSUE #13266: `abi.encodeCall()` segfaults in a free function when passed an error/event
```
error Error(string);
error Panic(uint);

function panic(uint code)
{
  bytes memory data = abi.encodeCall(Panic, code);
  assembly "evmasm" ("memory-safe") {
    revert(data, mload(data))
  }
}
```

The compiler segfaults...

### PR DESCRIPTION
**Pull request by timweri**
closes #13266

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2213,7 +2213,7 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 				externalFunctionType->declaration().scope() == m_currentContract
 			)
 				msg += " Did you forget to prefix \"this.\"?";
-			else if (util::contains(
+			else if (m_currentContract && util::contains(
 				m_currentContract->annotation().linearizedBaseContracts,
 				externalFunctionType->declaration().scope()
 			) && externalFunctionType->declaration().scope() != m_currentContract)
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
			else if (
				m_currentContract &&
				externalFunctionType->declaration().scope() != m_currentContract &&
				util::contains(
					m_currentContract->annotation().linearizedBaseContracts,
					externalFunctionType->declaration().scope()
				)
			)
```

File: test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_error_free_function.sol [hunk 2]
```diff
@@ -0,0 +1,7 @@
+error E(uint);
+
+function f() {
+    abi.encodeCall(E, (1));
+}
+// ----
+// TypeError 3509: (50-51): Expected regular external function type, or external view on public function. Cannot use special function.
```
Comment (cameel) [inline test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_error_free_function.sol]: I think we should have a separate message for errors and events. Not sure if technically we can classify them as "special functions" or not, but I think saying event/error would be much clearer for users anyway. Looks like it should be easy to change in `TypeChecker.cpp`, just above the change you already made.

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -2213,7 +2213,7 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 				externalFunctionType->declaration().scope() == m_currentContract
 			)
 				msg += " Did you forget to prefix \"this.\"?";
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp:2229]: From the implementation, looks like there should be more affected cases and indeed I found some. Could you add these as tests?

```solidity
function g(uint) {}

function f() {
    abi.encodeCall(g, (1));
}
```

```solidity
library L {
    function f() external {}
}

function f() {
    abi.encodeCall(L.f, (1));
}
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 4]
```diff
@@ -2213,7 +2213,7 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 				externalFunctionType->declaration().scope() == m_currentContract
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp:2227]: Can you check if `scope()` returns `nullptr` for free functions? If it does, we also need a check against `m_currentContract` being null here. When it's a free function, the compiler should not suggest adding `this.`

I think this part does not show up in syntax tests so please also test this by running compiled `solc` locally on one of the test cases. You should see the secondary message that way.

File: test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_error_free_function.sol (hunk 2 above)
Comment (timweri) [reply test/libsolidity/syntaxTests/abiEncoder/abi_encodeCall_error_free_function.sol]: I added separate messages for events and errors. Let me know what you think.

File: libsolidity/analysis/TypeChecker.cpp (hunk 4 above)
Comment (timweri) [reply libsolidity/analysis/TypeChecker.cpp:2227]: I did a `dynamic_cast` check and the `scope()` of a free function is not `nullptr`. It is the `SourceUnit`. Also, from my understanding, free functions would not pass the `visibility()` check above because free functions are not `public`.

File: libsolidity/analysis/TypeChecker.cpp (hunk 3 above)
Comment (timweri) [reply libsolidity/analysis/TypeChecker.cpp:2229]: Confirmed that these cases are also affected. Added tests.

**Review by Marenz — DISMISSED** [review]

File: libsolidity/analysis/TypeChecker.cpp [hunk 5]
```diff
@@ -2195,14 +2195,28 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
...
+				msg += " Cannot use library functions for abi.encodeCall.";
+				break;
+			case FunctionType::Kind::Creation:
+				msg += " Provided creation function.";
+				break;
+			case FunctionType::Kind::Event:
+				msg += " Cannot use event function.";
+				break;
+			case FunctionType::Kind::Error:
+				msg += " Cannot use error function.";
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Still needs a small tweak.
```suggestion
			case FunctionType::Kind::Event:
				msg += " Cannot use events for abi.encodeCall.";
				break;
			case FunctionType::Kind::Error:
				msg += " Cannot use errors for abi.encodeCall.";
```

File: libsolidity/analysis/TypeChecker.cpp (hunk 4 above)
Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp:2227]: True. They'll fail the first check. Good.

**Review by cameel — COMMENTED** [review]
I think the messages should not refer to errors and events as functions. Other than that everything seems fine.

**Comment by timweri** [comment]
Fixed the error messages :)

**Review by cameel — DISMISSED** [review]
You still need to update test output or tests will fail.

But anyway, I'm approving already. As soon as it's fixed, it's good to go.

**Comment by timweri** [comment]
My bad. I updated the tests.

**Review by Marenz — DISMISSED** [review]

**Comment by timweri** [comment]
Seems like the CI is failing for something unrelated to my change. Other PRs are also failing the same test.

**Comment by cameel** [comment]
Yeah, that looks like a false-positive unrelated to the PR. We'll need to disable these tests.

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
Actually this is missing a changelog entry - could you add it please?

**Comment by timweri** [comment]
@chriseth Added changelog

File: Changelog.md [hunk 6]
```diff
@@ -13,6 +13,7 @@ Compiler Features:
 
 Bugfixes:
  * Commandline Interface: Disallow the following options outside of the compiler mode: ``--via-ir``,``--metadata-literal``, ``--metadata-hash``, ``--model-checker-show-unproved``, ``--model-checker-div-mod-no-slacks``, ``--model-checker-engine``, ``--model-checker-invariants``, ``--model-checker-solvers``, ``--model-checker-timeout``, ``--model-checker-contracts``, ``--model-checker-targets``.
+ * TypeChecker: Fix null dereference in `abi.encodeCall` type checking of free function.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Type Checker: Fix null dereference in `abi.encodeCall` type checking of free function.
```
(I know it is written like that above, but this is how it should be :) )

Comment (timweri) [reply Changelog.md]: Fixed :)

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Thanks a lot!
