### PR TITLE
Fix for constant strings.

### LINKED ISSUE #28: "bytes32 constant x" causes disturbance in the stack.
```
contract BytesConstError {
    bytes32 constant x = "test";
    
    function (){
        g(x);
    }
    
    function g(bytes32 arg){}
}
```

```
Internal compiler error: I sense a disturbance in the stack.
```

Tested in latest browser compiler and: `0.1.1-0/Release-Linux/g++/int`. Removing constant fixes, or just using a literal.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #28

### CODE REVIEW

File: libsolidity/AST.cpp [hunk 1]
```diff
@@ -559,9 +560,18 @@ void VariableDeclaration::checkTypeRequirements()
 			BOOST_THROW_EXCEPTION(createTypeError("Illegal use of \"constant\" specifier."));
 		if (!m_value)
 			BOOST_THROW_EXCEPTION(createTypeError("Uninitialized \"constant\" variable."));
-		else if (m_type && !m_type->isValueType())
-			// TODO: const is implemented only for uint, bytesXX and enums types.
-			BOOST_THROW_EXCEPTION(createTypeError("Illegal use of \"constant\" specifier. \"constant\" is not implemented for this type yet."));
+		if (m_type && !m_type->isValueType())
+		{
+			// TODO: const is implemented only for uint, bytesXX, string and enums types.
```
Comment (LianaHus) [inline libsolidity/AST.cpp:565]: there is an exactly same comment in tests(SolidityEndToEndTest.cpp
), could you please add "string" there as well

File: libsolidity/AST.cpp [hunk 2]
```diff
@@ -559,9 +560,18 @@ void VariableDeclaration::checkTypeRequirements()
...
+			bool constImplemented = false;
+			if (auto arrayType = dynamic_cast<ArrayType const*>(m_type.get()))
+				constImplemented = arrayType->isByteArray();
+			if (!constImplemented)
+				BOOST_THROW_EXCEPTION(createTypeError(
+					"Illegal use of \"constant\" specifier. \"constant\" "
+					" is not yet implemented for this type."
```
Comment (LianaHus) [inline libsolidity/AST.cpp]: don't you have 2 spaces here?
