### PR TITLE
yul: Set non movable flag to true in simplification rule for byte of …

### LINKED ISSUE #9558: [yul] ExpressionSimplifier removes non-movable expression
## Description

This test passes but it shouldn't because `call()` may change blockchain state (similarly other opcodes that are potentially state changing) and therefore if a contract previously disabled optimizer but at a later point *only* enabled the expression simplifier (not sure if this is a user-facing setting), the end-result will be different.

Please note that full optimization suite retains the `call` in the example below, so this is only a bug if one were to only enable the expression simplifier.

```
{
  pop(byte(0, shr(0x8, call(0, 0, 0, 0, 0, 0, 0))))
}
// ----
// step: expressionSimplifier
//
// { pop(0) }
```

Rule executed is

https://github.com/ethereum/solidity/blob/08791ab0d4cc0c30bebc4076d141e6b96b0d6412/libevmasm/RuleList.h#L582-L587

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ cp test.yul test/libyul/yulOptimizerTests/expressionSimplifier/byte_shr_call.yul
$ isoltest -t yulOptimizerTests/expressionSimplifier/byte_shr_call
Running tests...

yulOptimizerTests/expressionSimplifier/byte_shr_call.yul: OK

Yul Optimizer Test Summary: 1/438 tests successful (437 tests skipped).


Summary: 1/4128 tests successful (4127 tests skipped).
```

### PR DESCRIPTION
**Pull request by bshastry**
…right-shifted expression

Fixes #9558

### CODE REVIEW

File: libevmasm/RuleList.h [hunk 1]
```diff
@@ -582,7 +582,7 @@ std::vector<SimplificationRule<Pattern>> simplificationRuleListPart7(
 	rules.push_back({
 		Builtins::BYTE(A, Builtins::SHR(B, X)),
 		[=]() -> Pattern { return A.d() < B.d() / 8 ? Word(0) : Builtins::BYTE(A.d() - B.d() / 8, X); },
-		false,
+		true,
```
Comment (ekpyron) [inline libevmasm/RuleList.h:585]: Ah, damn, I should have realized this when this was added...
This is actually an "important bugfix"! (Unless for some reason we're absolutely sure this *really* can't ever happen in practice)

It would probably be nicer to split this rule into two, though - one with ``A.d() < B.d() / 8`` being part of the precondition lambda, generally replacing with ``Word(0)`` and setting this flag to ``true`` and one with ``A.d() >= B.d() / 8`` as part of the precondition, always replacing with ``Builtins::BYTE(A.d() - B.d() / 8, X)`` and leaving this flag as ``false``.

File: libevmasm/RuleList.h [hunk 2]
```diff
@@ -581,9 +581,20 @@ std::vector<SimplificationRule<Pattern>> simplificationRuleListPart7(
 
 	rules.push_back({
 		Builtins::BYTE(A, Builtins::SHR(B, X)),
-		[=]() -> Pattern { return A.d() < B.d() / 8 ? Word(0) : Builtins::BYTE(A.d() - B.d() / 8, X); },
+		[=]() -> Pattern { return Word(0); },
+		true,
+		[=] {
+			return B.d() % 8 == 0 && A.d() < Pattern::WordSize / 8 && B.d() <= Pattern::WordSize && A.d() < B.d() / 8;
```
Comment (chriseth) [inline libevmasm/RuleList.h:587]: In a follow-up pull request, we could actually drop the `%8==0` requirement here.

Comment (ekpyron) [reply libevmasm/RuleList.h:587]: True - then we should drop it from ``test/formal/combine_byte_shr_2.py`` as well, though. Rather unfortunate - I did split up the proofs back then and even thought about suggesting splitting up the rules, but saw no reason for it, since I had already stopped thinking about the flag by then...

**Comment by chriseth** [comment]
Added changelog entry.

**Review by ekpyron — APPROVED** [review]
