### PR TITLE
Unary minus is not implemented for fixed point type

### LINKED ISSUE #10256: [Typechecker] Bad cast during negation of fixed point type variable in contract function
## Description

```
contract C {
        function f() public pure {
                fixed x;
                -x;
        }
}
```

throws a `std::bad_cast` here

https://github.com/ethereum/solidity/blob/141277dadfe4a75e250fd2abfed89d98fb694d4a/libsolidity/codegen/YulUtilFunctions.cpp#L3401

because `fixed` and `integer` types are unrelated by inheritance. Surprisingly, free functions do not demonstrate this bug e.g., `function f() pure { fixed x; -x; }`

## Environment

- Compiler version: latest breaking

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by axic**
Closes #10256.

This only adds the necessary assertion. We could improve the type checker, but not sure it is worth it?

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 1]
```diff
@@ -453,6 +453,10 @@ bool ExpressionCompiler::visit(UnaryOperation const& _unaryOperation)
 		// unary add, so basically no-op
 		break;
 	case Token::Sub: // -
+		solUnimplementedAssert(
```
Comment (axic) [inline libsolidity/codegen/ExpressionCompiler.cpp:456]: This is copied from the `inc/dec` case from above.

**Comment by axic** [comment]
The failure seems to be some smtchecker thing, present on `breaking`.
