### PR TITLE
Fix crash with oversized address literals

### LINKED ISSUE #10257: [TypeChecker] Null dereference during explicit cast of hex literal to address type
## Description

```
function t() pure {
        address(0x11223345567aaaaaaaaaaaaaaaaaaaaaaaaaaaaa0112233445566778899001122);
}
```

dereferences a nullptr here

https://github.com/ethereum/solidity/blob/141277dadfe4a75e250fd2abfed89d98fb694d4a/libsolidity/ast/Types.cpp#L976

in the call to `integerType()->numBits()` because `integerType()` returns a nullptr.

## Environment

- Compiler version: latest breaking

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #10257.

### CODE REVIEW

**Review by hrkrshnn — APPROVED** [review]

**Comment by hrkrshnn** [comment]
The CI job ` t_bytecode_compare` is failing.

**Comment by axic** [comment]
> The CI job t_bytecode_compare is failing.

I see that but it must be unrelated, as this code difference would not produce code at least in one case (pre or post).

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -940,7 +940,7 @@ BoolResult RationalNumberType::isExplicitlyConvertibleTo(Type const& _convertTo)
 	if (category == Category::FixedBytes)
 		return false;
 	else if (category == Category::Address)
-		return !(isNegative() || isFractional() || integerType()->numBits() > 160);
+		return !(isNegative() || isFractional() || !integerType() || integerType()->numBits() > 160);
 	else if (category == Category::Integer)
 		return false;
 	else if (auto enumType = dynamic_cast<EnumType const*>(&_convertTo))
```
Comment (axic) [inline libsolidity/ast/Types.cpp:946]: ~~The enum check uses `m_value` directly, while for address we go through the integer conversion helper. I think we should do the same for enums? This would find any disagreements between what is happening on conversion vs. a direct comparison of rational.~~

Never mind, we don't have a nice way to extract value out of an integer type (just `toString`).

**Comment by chriseth** [comment]
Bytecode comparison is due to a date difference in the version.
