### PR TITLE
SMTChecker: Fix struct constructor where fixed-bytes member is initialized with a string literal

### LINKED ISSUE #11336: [SMTChecker] ICE due to equal expression with different sorts
```
pragma experimental SMTChecker;
contract C {
  struct S {
    int a;
    bytes5 b;
  }
  function f() public {
    [S({a:2, b:""})];
  }
}
```

throws

https://github.com/ethereum/solidity/blob/f1d58c549b1682fb6a863c53fad710381da30748/libsmtutil/SolverInterface.h#L262

### PR DESCRIPTION
**Pull request by blishko**
Fixes #11336.

The crash happened because `SMTEncoder::visitStructConstructorCall` did not take the possible conversion from String literal to fixed-bytes into account.

The added test case simplifies the one from issue a bit (the array is unnecessary, the crash happened also without it) and adds assertions.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -1158,7 +1158,14 @@ void SMTEncoder::visitStructConstructorCall(FunctionCall const& _funCall)
...
 	{
 		auto& structSymbolicVar = dynamic_cast<smt::SymbolicStructVariable&>(*m_context.expression(_funCall));
-		structSymbolicVar.assignAllMembers(applyMap(_funCall.sortedArguments(), [this](auto const& arg) { return expr(*arg); }));
+		auto structType = dynamic_cast<StructType const*>(structSymbolicVar.type());
+		solAssert(structType, "");
+		auto const& structMembers = structType->structDefinition().members();
+		solAssert(structMembers.size() == _funCall.sortedArguments().size(), "");
+		structSymbolicVar.assignAllMembers(applyMap(
+			_funCall.sortedArguments(),
+			[&, i=0u] (auto const& arg) mutable { return expr(*arg, structMembers[i++]->type()); }
```
Comment (blishko) [inline libsolidity/formal/SMTEncoder.cpp]: This would be better with a version of `applyMap` taking two sequences.
Or is there something in `ranges` that could be used here?

Comment (hrkrshnn) [reply libsolidity/formal/SMTEncoder.cpp]: There seems to be zip in ranges. Here is an example: https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/TypeChecker.cpp#L983

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: `zip` seems to work and is more readable, I think. Thanks!
I added it as a separate commit for comparison, I can squash if this gets approved.

**Review by hrkrshnn — DISMISSED** [review]

**Comment by hrkrshnn** [comment]
A rebase should fix the CI issues.

**Comment by blishko** [comment]
Squashed and rebased.

**Review by hrkrshnn — APPROVED** [review]

**Comment by hrkrshnn** [comment]
Thanks for the PR!
