### PR TITLE
Fix location of yul assignment

### LINKED ISSUE #9223: Incorrect source mapping for Yul variable assignment
## Description

The following contract, when compiled with `solc --ast-compact-json`, produces an incorrect source mapping for the `YulVariableAssignment` node:

```
contract A {
    fallback() external {
        assembly
{
  let a, b
  a, b := f()
  function f() -> r1, r2 {}
}
    }
}
```

With unix line endings, solc reports the src of the assignment node to be `74:8:0` which corresponds to `b := f()`. It should probably be `71:11:0`.

## Environment

- Compiler version: `0.6.10+commit.00c0fcaf.Linux.g++`
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/9223

### CODE REVIEW

File: libyul/AsmParser.cpp [hunk 1]
```diff
@@ -175,7 +175,8 @@ Statement Parser::parseStatement()
 	case Token::Comma:
 	case Token::AssemblyAssign:
 	{
-		std::vector<Identifier> variableNames;
+		Assignment assignment;
+		assignment.location = locationOf(elementary);
```
Comment (cameel) [inline libyul/AsmParser.cpp:179]: If I understand the change correctly, location of the assignment used to be set to:
```
abc, def, ghi := xyz
          ^^^
```
and now it will be
```
abc, def, ghi := xyz
^^^
```
is that the intention here? Why not
```
abc, def, ghi := xyz
^^^^^^^^^^^^^
```
or
```
abc, def, ghi := xyz
^^^^^^^^^^^^^^^^^^^^
```
or
```
abc, def, ghi := xyz
              ^^
```

?

Comment (cameel) [inline libyul/AsmParser.cpp:179]: Also, maybe it would be a good idea to add a syntax test for a case where it matters. E.g. a situation where the assignment contains an error and the compiler indicates its location?

Comment (chriseth) [reply libyul/AsmParser.cpp:179]: the source location is the full assignment statement now. I will add a syntax test.

**Comment by chriseth** [comment]
Updated.

**Review by cameel — APPROVED** [review]

File: libyul/AsmParser.cpp (hunk 1 above)
Comment (cameel) [reply libyul/AsmParser.cpp:179]: I marked it as approved since the test clearly confirms that the location is indeed the whole assignment. But I'm still trying to figure out why. `elementary` is just a single `identifier` so `locationOf(elementary)` should be just the location of that identifier, right?

Comment (chriseth) [reply libyul/AsmParser.cpp:179]: Because of this line: https://github.com/ethereum/solidity/pull/9225/files#diff-cfa1a0f58085cfb54feda51c7f9d53fdR214

So before this change, the location was actually
```
abc, def, ghi := xyz
          ^^^^^^^^^^
```

Comment (cameel) [reply libyul/AsmParser.cpp:179]: Right, it overwrites the `end` later. I totally missed that.
