### PR TITLE
Fix crash for too large struct array indicies

### LINKED ISSUE #5056: Invalid number literal causes crash
Found by solfuzzer.

```
contract C {        function f() public returns (string memory) {
        return (["s5D789<B0>12345678890123453789012;^S+78901 34567890123456781012D4567890,234567891<FF><FF><FF><FF>678I01234565890;1234167890123456789012345678901234567890123456$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$678901@O4567890"][901236789012345678915555555555555234567890123453789012345&88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888-888888888888888888888888888888888888888888888888888888888888888^8888888888][901236789012345678915555555555555234567890123453789012345&88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888-888888888888888888888888888888888888888888888888888888888888888^888888888888^8888888888888888888888888888888888888888888888888888888888888888888888888888888888888-888888888888888888888888888888888888888888888888888888888888888^8888888888][901236789012345678915555555555555234567890123453789012345&88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888-888888888888888888888888888888888888888888888888888888888888888^888888888888^8888888885555888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888789012325678955555555555555555555555555555555555555555555555555555555555555555555558888885555888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888789012325678955555555555555555555555555555555555555555555555555555555555555555555558888888888888888888888888888888888888888888888888888888^8888555555555555555555555555555555555555555555588^8888888885555888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888789012325678955555555555555555555555555555555555555555555555555555555155555555555558888888888888888888888888888888888888888888888888888888^88885555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555523453789012345&-891234567890123453789012345&-8901234567890123256789555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555501234&6789012345777777777777777]);
    }
}
```

Error
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/ast/Types.cpp(1285): Throw in function virtual dev::u256 dev::solidity::RationalNumberType::literalValue(const dev::solidity::Literal *) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Integer constant too large.
[dev::tag_comment*] = Integer constant too large.
```

Also uploaded as a file, because it contains unprintable characters.

[id:000167,sig:06,src:010984,op:havoc,rep:2.txt](https://github.com/ethereum/solidity/files/2405910/id.000167.sig.06.src.010984.op.havoc.rep.2.txt)

### PR DESCRIPTION
**Pull request by Marenz**
Fixes #5056

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2198,7 +2198,8 @@ bool TypeChecker::visit(IndexAccess const& _access)
 			resultType = make_shared<TypeType>(make_shared<ArrayType>(DataLocation::Memory, typeType.actualType()));
 		else
 		{
-			expectType(*index, IntegerType::uint256());
+			if (!expectType(*index, IntegerType::uint256()))
+				m_errorReporter.fatalTypeError(_access.location(), "Index expression cannot be represented as an unsigned integer.");
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp]: The source location of the error should probably be ``index->location()``.

File: Changelog.md [hunk 2]
```diff
@@ -3,6 +3,7 @@
 Bugfixes:
  * Code generator: Defensively pad allocation of creationCode and runtimeCode to multiples of 32 bytes.
  * Parser: Disallow empty import statements.
+ * Type Checker: Fix internal error when a struct array index is not an unsigned.
```
Comment (ekpyron) [inline Changelog.md]:
```suggestion
 * Type Checker: Fix internal error when a struct array index is not an unsigned integer.
```

Comment (ekpyron) [reply Changelog.md]: or
```suggestion
 * Type Checker: Fix internal error when a struct array index does not fit into an uint256.
```

**Review by ekpyron — CHANGES_REQUESTED** [review]
The source location should be fixed, otherwise it's fine!

**Comment by axic** [comment]
There are a few other cases in the file where `expectType`'s return value is ignored. Would it be worth having a quick look at them?

File: Changelog.md (hunk 2 above)
Comment (chriseth) [reply Changelog.md]: "a uint" :)

Comment (Marenz) [reply Changelog.md]: Mind you all, I just copied this change log entry from https://github.com/ethereum/solidity/pull/5195/files#diff-9b8fab691c00b9e5380b19ce882f3271R128
and added "struct" :P

**Comment by Marenz** [comment]
> There are a few other cases in the file where `expectType`'s return value is ignored. Would it be worth having a quick look at them?

The other cases either don't directly use the type or check for errors using `hasErrors()` before using it.

Pushed requested changes

File: Changelog.md [hunk 3]
```diff
@@ -3,6 +3,7 @@
 Bugfixes:
  * Code generator: Defensively pad allocation of creationCode and runtimeCode to multiples of 32 bytes.
  * Parser: Disallow empty import statements.
+ * Type Checker: Fix internal error when a struct array index does not fit into an uint256.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Type Checker: Fix internal error when a struct array index does not fit into a uint256.
```

**Comment by Marenz** [comment]
pushed

**Comment by Marenz** [comment]
Fixed failing CI

**Review by ekpyron — DISMISSED** [review]

File: test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+ struct s { uint a; uint b;}
+    function f() pure public returns (byte) {
+        s[75555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555];
+        s[7];
+    }
+}
+
+// ----
+// TypeError: (101-241): Type int_const 7555...(132 digits omitted)...5555 is not implicitly convertible to expected type uint256.
+// TypeError: (101-241): Index expression cannot be represented as an unsigned integer.
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: Actually this is a second error with exactly the same cause. We probably should not just create a new fatal error but handle it in a different way.

**Review by chriseth — CHANGES_REQUESTED** [review]

File: test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol (hunk 4 above)
Comment (ekpyron) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: If it *can* be handled differently without too many problems, then we can turn the fatal errors a few lines down in TypeChecker.cpp line 2210 into a non-fatal error as well.

Comment (Marenz) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: How about this?
```
	case Type::Category::TypeType:
	{
		TypeType const& typeType = dynamic_cast<TypeType const&>(*baseType);
		if (!index)
			resultType = make_shared<TypeType>(make_shared<ArrayType>(DataLocation::Memory, typeType.actualType()));
		else
		{
			u256 length = 0;
			if (expectType(*index, IntegerType::uint256()))
			{
				if (auto indexValue = dynamic_cast<RationalNumberType const*>(type(*index).get()))
					length = indexValue->literalValue(nullptr);
				else
					m_errorReporter.fatalTypeError(index->location(), "Integer constant expected.");
			}

			resultType = make_shared<TypeType>(make_shared<ArrayType>(
				DataLocation::Memory,
				typeType.actualType(),
				length
			));
		}
		break;
	}
```

Comment (chriseth) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: Please update the PR so we can properly see the diff.

**Comment by Marenz** [comment]
I pushed a suggestion how to handle it differently. Tests not yet updated.

File: libsolidity/analysis/TypeChecker.cpp [hunk 5]
```diff
@@ -2205,15 +2205,20 @@ bool TypeChecker::visit(IndexAccess const& _access)
...
-			else
-				m_errorReporter.fatalTypeError(index->location(), "Integer constant expected.");
+			u256 length = 0;
+			if (expectType(*index, IntegerType::uint256()))
+			{
+				if (auto indexValue = dynamic_cast<RationalNumberType const*>(type(*index).get()))
+					length = indexValue->literalValue(nullptr);
+				else
+					m_errorReporter.fatalTypeError(index->location(), "Integer constant expected.");
+			}
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:2215]: Looks good, but please assert here that we have an error in the error list.

**Comment by Marenz** [comment]
Updated.
* Updated test
* changed fallback value to 1 in case 0 causes problems later
* added assert

File: test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol (hunk 4 above)
Comment (ekpyron) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: Maybe we could just proceed without any fatal error by using a RationalNumberType with value zero?

Comment (Marenz) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: Isn't that kind of what I did?

Comment (ekpyron) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: Ah yeah - I hadn't noticed, because you still have the fatal error in the snippet - that can turn into a non-fatal one, if we fall back to just zero.

Comment (Marenz) [reply test/libsolidity/syntaxTests/indexing/struct_array_noninteger_index.sol]: Oh. Yes that is an other fatal error from the code before I changed anything. I figured my change should be as minimal-invasive as possible. I can remove that one too, I suppose.

**Review by chriseth — APPROVED** [review]

File: libsolidity/analysis/TypeChecker.cpp [hunk 6]
```diff
@@ -2205,15 +2205,22 @@ bool TypeChecker::visit(IndexAccess const& _access)
...
-					typeType.actualType(),
-					length->literalValue(nullptr)
-				));
+			u256 length = 1;
+			if (expectType(*index, IntegerType::uint256()))
+			{
+				if (auto indexValue = dynamic_cast<RationalNumberType const*>(type(*index).get()))
+					length = indexValue->literalValue(nullptr);
+				else
+					m_errorReporter.fatalTypeError(index->location(), "Integer constant expected.");
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp:2214]: This could be changed to a non-fatal error as well now - I'd say there's no harm in doing that in this PR as well, but I'm also fine with keeping it.
