### PR TITLE
OSX: Fix readlink & ASTImportTest.sh issues.

### LINKED ISSUE #9711: ASTImportTest.sh silently ignores errors
## Description
`ASTImportTest.sh` (which runs as a part of command line tests) uses the return value from `splitSources.py` to determine if a file is a multi-source one or not. In effect, other errors can go unnoticed (example: #9710).

It also does not use the `set -e` which means that failing commands do not interrupt the script (example: #9712).

The script needs to be adjusted so that we can discern errors from other situations.

## Environment

- Compiler version: 0.7.1-develop.2020.8.31+commit.8c8eca3e.Linux.g++

## Steps to Reproduce
```bash
FILETMP=$(mktemp -d)
cd $FILETMP

/path/to/solidity/scripts/ASTImportTest.sh
```
```
Looking at 2140 .sol files...
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "/projects/solidity/scripts/splitSources.py", line 51, in <module>
    lines = open(filePath, mode='r', encoding='utf8').read().splitlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 36: invalid start byte
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
SUCCESS: 0 syntaxTests passed, 0 failed, 2243 could not be compiled (2200 sources total).
```

### PR DESCRIPTION
**Pull request by aarlt**
Fix #9711 and #9712. Also see #9710. 

This is probably not the cleanest solution. 

- `scripts/splitSources.py` - system exception hook will print message and will result code `3`. This will be treated as a critical error by `scripts/ASTImportTest.sh`.  If an `UnicodeDecodeError` exception occurs, the script will result code `2`, `scripts/ASTImportTest.sh` will ignore this, but will print stdout of the python script. The semantic of result code `0` and `1` are the same as before: `0` means that there was code extracted from a multi-source file and `1` means that the file was not a multi-source file. Also regarding #9710: splitting of multi-source files containing invalid utf-8 sequences is still not implemented.

- `scripts/ASTImportTest.sh` - use of `greadlink` on osx #9712. fix that it silently ignores errors by adding result code handling for `scripts/splitSources.py` #9711. 

- `scripts/test_antlr_grammar.sh` - use of `greadlink` on osx.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

File: scripts/ASTImportTest.sh [hunk 1]
```diff
@@ -1,10 +1,15 @@
...
+set -e
+
 # Bash script to test the ast-import option of the compiler by
 # first exporting a .sol file to JSON, then loading it into the compiler
 # and exporting it again. The second JSON should be identical to the first
-
-REPO_ROOT=$(readlink -f "$(dirname "$0")"/..)
+READLINK=readlink
+if [[ "$OSTYPE" == "darwin"* ]]; then
+    READLINK=greadlink
```
Comment (axic) [inline scripts/ASTImportTest.sh:10]: What packages is this contained in?

Comment (aarlt) [reply scripts/ASTImportTest.sh:10]: @axic `greadlink` is part of `coreutils`, installable via `brew install coreutils`.

Comment (axic) [reply scripts/ASTImportTest.sh:10]: Can that be added to the dependencies list in the documentation? Or well, into the some developer docs which explains how to run all the tests.
