### PR TITLE
Yul: Fix cleanup for left shift of bytes types.

### LINKED ISSUE #11736: [Sol->Yul] Truncation not performed on bytesNN before applying left shift
The semantic test here: https://github.com/ethereum/solidity/blob/ae519c1278c7244bcd81929cdbdd0a11da4c789e/test/libsolidity/semanticTests/operators/shifts/shift_bytes_cleanup.sol#L5-L6

shows that we do not ~~clean up~~truncate before applying left shift in Sol->Yul unlike for right shift where we do.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/11736

### CODE REVIEW

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 1]
```diff
@@ -445,11 +445,16 @@ string YulUtilFunctions::typedShiftLeftFunction(Type const& _type, Type const& _
 			Whiskers(R"(
 			function <functionName>(value, bits) -> result {
 				bits := <cleanAmount>(bits)
-				result := <cleanup>(<shift>(bits, value))
+				<?leftAligned>
+					result := <shift>(bits, <cleanup>(value))
+				<!leftAligned>
+					result := <cleanup>(<shift>(bits, value))
+				</leftAligned>
```
Comment (bshastry) [inline libsolidity/codegen/YulUtilFunctions.cpp]: In `typedShiftRightFunction` we do `cleanup(shift(bits, cleanup(value))` unconditionally. Do you mind briefly explaining what is different between left and right shifts that we need a conditional `<?leftAligned>` here but not in right shift function.

To put it differently, what if we always do `result := <cleanup>(<shift>(bits, <cleanup>(value))`?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I just ran some tests and it turns out that (at least for unsigned numbers), the optimizer is clever enough to remove one of the cleanups, so we can also simplify this to the same case as the right shift.

**Review by bshastry — APPROVED** [review]
LGTM
