### PR TITLE
Fix null dereference in using for directive when operator name is empty

### LINKED ISSUE #14016: [Parser] Null pointer deref while parsing `using for` directive that contains an empty string as operator name
```
using{a as''
```

derefs null ptr here

https://github.com/ethereum/solidity/blob/983407762c3423e9c301d5ae56ac7b6d951655df/libsolidity/parsing/Parser.cpp#L998

### PR DESCRIPTION
**Pull request by matheusaaguiar**
fix #14016 .

### CODE REVIEW

File: libsolidity/parsing/Parser.cpp [hunk 1]
```diff
@@ -994,11 +994,23 @@ ASTPointer<UsingForDirective> Parser::parseUsingDirective()
 				Token operator_ = m_scanner->currentToken();
 				if (!util::contains(userDefinableOperators, operator_))
 				{
+					auto operatorName = [&]() -> string {
+						if (!m_scanner->currentLiteral().empty())
+							return m_scanner->currentLiteral();
+						else if (
+							char const* tokenString = TokenTraits::toString(operator_);
+							tokenString != nullptr
+						)
```
Comment (nikola-matic) [inline libsolidity/parsing/Parser.cpp]:
```suggestion
						else if (char const* tokenString = TokenTraits::toString(operator_))
```

File: libsolidity/parsing/Parser.cpp [hunk 2]
```diff
@@ -994,11 +994,23 @@ ASTPointer<UsingForDirective> Parser::parseUsingDirective()
...
+							return string(tokenString);
+						else
+							return {};
```
Comment (nikola-matic) [inline libsolidity/parsing/Parser.cpp]:
```suggestion
						return {};
```

File: test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol [hunk 3]
```diff
@@ -0,0 +1,3 @@
+using {f as ''} for uint;
```
Comment (nikola-matic) [inline test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: I'd cover additional cases that Kamil [mentioned](https://github.com/ethereum/solidity/issues/14016#issuecomment-1445159819) in the original issue. Also, this error kinda looks a bit weird when an empty string is returned; perhaps we should consider a special case for this scenario (not necessarily in this PR, since I'd assume that a segfault takes precedence).

Comment (matheusaaguiar) [reply test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: Yes, I will add tests for those too.
I had the thought to make a different message for the case of the empty string, but stopped myself until we decide it is really needed. Also, I agree that it is probably better to (eventually) do it in another PR.

**Review by nikola-matic — DISMISSED** [review]
@cameel for final review.

File: libsolidity/parsing/Parser.cpp [hunk 4]
```diff
@@ -994,11 +994,19 @@ ASTPointer<UsingForDirective> Parser::parseUsingDirective()
 				Token operator_ = m_scanner->currentToken();
 				if (!util::contains(userDefinableOperators, operator_))
 				{
+					auto operatorName = [&]() -> string {
+						if (!m_scanner->currentLiteral().empty())
+							return m_scanner->currentLiteral();
+						else if (char const* tokenString = TokenTraits::toString(operator_))
+							return string(tokenString);
+						return {};
+					};
```
Comment (cameel) [inline libsolidity/parsing/Parser.cpp]: This lambda is used exactly once and does not take parameters. It would be simpler to replace it with an intermediate variable.

File: test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol [hunk 5]
```diff
@@ -0,0 +1,7 @@
...
+using {f as ""} for int;
+using {f as hex""} for address;
+// ----
+// ParserError 4403: (12-14): Not a user-definable operator: . Only the following operators can be user-defined: |, &, ^, ~, +, -, *, /, %, ==, !=, <, >, <=, >=
```
Comment (cameel) [inline test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: This message looks as if it was malformed. Maybe it would be better to shorten it to this when we hit this case?
```suggestion
// ParserError 4403: (12-14): Not a user-definable operator. Only the following operators can be user-defined: |, &, ^, ~, +, -, *, /, %, ==, !=, <, >, <=, >=
```

File: test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol
Comment (cameel) [inline test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol:1]: For consistency with existing tests, I'd name this one `operator_parsing_operator_name_empty_string.sol`.

File: libsolidity/parsing/Parser.cpp (hunk 4 above)
Comment (ekpyron) [reply libsolidity/parsing/Parser.cpp]: That's true.

File: test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol (hunk 5 above)
Comment (ekpyron) [reply test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: Stop micro-optimizing error messages for cases that won't ever happen in reality :-).

Comment (nikola-matic) [reply test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: But in typical cases, this will yield an error like `Not a user-definable operator:x`, which is a bit ugly as well. It would be much nicer to have a specific error for this particular case, but then @ekpyron might have a stroke, so I guess I'm more for leaving it as is.

Comment (ekpyron) [reply test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: I mean, honestly, if we want to be nitpicky about this, the parser is not really the place for erroring out on these anyways - what really should happen is to accept anything that's an operator here (the parser should be concerned with grammatic categories, not with individual tokens) and just make this a generic ``Expected: operator`` as far as the parser is concerned - and then syntax check the operator in these things to restrict to supported operators... but none of this is worth spending time on, so just fix the ICE and be fine with the messages :-).

Comment (nikola-matic) [reply test/libsolidity/syntaxTests/operators/userDefined/using_for_empty_operator_name.sol]: 100% agree.

**Comment by matheusaaguiar** [comment]
Addressed all comments and rebased.

**Review by ekpyron — APPROVED** [review]
