### PR TITLE
LLL: move broken parsing of Ethereum subunits to macros

### LINKED ISSUE #1197: LLL: consider moving wei/szabo/finney/ether from parser to builtins
They are defined here: https://github.com/ethereum/solidity/blob/develop/liblll/Parser.cpp#L109 

@zigguratt would this be possible with LLL?

### PR DESCRIPTION
**Pull request by axic**
Fixes #1197.

This is a breaking change. Current parser zealously will replace all `<number> szabo` occurences (even replacing `1 szabounit` with `1000000000000 unit`).

The new syntax with macros is `(* 1 szabo)`.

### CODE REVIEW

File: liblll/CompilerState.cpp [hunk 1]
```diff
@@ -69,6 +69,10 @@ void CompilerState::populateStandard()
 	"(def 'ripemd160 (data datasize) (msg allgas 3 0 data datasize))"
 	"(def 'sha256 (val) { [0]:val (sha256 0 32) })"
 	"(def 'ripemd160 (val) { [0]:val (ripemd160 0 32) })"
+	"(def 'wei 1)"
+	"(def 'szabo 1000000000000)"
+	"(def 'finney 1000000000000000)"
+	"(def 'eth 1000000000000000000)"
```
Comment (axic) [inline liblll/CompilerState.cpp]: Should this be `eth` or `ether`?

It was `ether` in the parser and Solidity uses `ether`.

Comment (zigguratt) [reply liblll/CompilerState.cpp]: I guess to maintain consistency it should be `ether`. Or maybe we could have both.

**Review by zigguratt — CHANGES_REQUESTED** [review]
Change `eth` to `ether` for consistency with both old LLL usage and current Solidity usage.

**Review by zigguratt — APPROVED** [review]

**Comment by zigguratt** [comment]
Damn. Meant to approve only one of the commits. Didn't know it was going to approve both at once.

**Comment by chriseth** [comment]
Please check that this does not break any of the tests in https://github.com/ethereum/tests

**Review by chriseth — CHANGES_REQUESTED** [review]
Might change existing tests in https://github.com/ethereum/tests and https://github.com/ethereum/cpp-ethereum - please check.

**Comment by axic** [comment]
I don't see anywhere LLL is being used in the tests. Do you have any pointers?

**Comment by chriseth** [comment]
One example: https://github.com/ethereum/cpp-ethereum/blob/develop/test/libevm/VMTestsFiller/vmIOandFlowOperationsTestFiller.json#L148

**Comment by axic** [comment]
@chriseth thanks. I did a search on the repos for `wei`, `szabo`, `finney`, `ether` without any results.

**Review by chriseth — APPROVED** [review]
