### PR TITLE
Fixed Type initial PR

### LINKED ISSUE #428: Token::name and Token::toString do not work for fixed
The functions Token::name and Token::toString do not work for the new complex tokens fixed and ufixed, e.g. they return "UFixed" for "ufixed8x8".

### PR DESCRIPTION
**Pull request by VoR0220**
Fixes https://github.com/ethereum/solidity/issues/428

Major changes:
- convert constant integer to rationals (two big ints)
- lay the foundations for the fixed type
- some changes to the operators
- numerous tests added

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -251,17 +260,30 @@ IntegerType::IntegerType(int _bits, IntegerType::Modifier _modifier):
...
+	}
+	else if (_convertTo.category() == Category::Fixed)
+	{
+		FixedType const& convertTo = dynamic_cast<FixedType const&>(_convertTo);
+		if (convertTo.leftBits() < m_bits)
+			return false;
+		else if (isSigned())
+			return convertTo.isSigned();
+		else
+			return !convertTo.isSigned() || convertTo.leftBits() > m_bits;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Why allow the second part?

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -339,29 +361,159 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
 		return MemberList::MemberMap();
 }
 
-bool IntegerConstantType::isValidLiteral(const Literal& _literal)
+FixedType::FixedType(int _Lbits, int _Rbits, FixedType::Modifier _modifier):
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Please use the terms `integer bits` and `fractional bits`.

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -339,29 +361,159 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
 	{
-		bigint x(_literal.value());
+		string literal = _literal.value();
+		auto literalEnd = remove(literal.begin(), literal.end(), '.');
+		bigint x(string(literal.begin(), literalEnd));
 	}
 	catch (...)
 	{
-		return false;
+			return false;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Indentation

File: libsolidity/ast/Types.cpp [hunk 4]
```diff
@@ -339,29 +361,159 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+}
+
+bool ConstantNumberType::isValidLiteral(const Literal& _literal)
 {
 	try
 	{
-		bigint x(_literal.value());
+		string literal = _literal.value();
+		auto literalEnd = remove(literal.begin(), literal.end(), '.');
+		bigint x(string(literal.begin(), literalEnd));
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: What does this check? Please add a comment about which literals are valid.

File: libsolidity/ast/Types.cpp [hunk 5]
```diff
@@ -339,29 +361,159 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+ConstantNumberType::ConstantNumberType(Literal const& _literal)
 {
-	m_value = bigint(_literal.value());
+	string literal = _literal.value();
+	auto radix = find(literal.begin(), literal.end(), '.');
+	if (radix != literal.end())
+	{
+		m_modifier = Modifier::Fixed;
+		auto literalEnd = remove(literal.begin(), literal.end(), '.');
+		m_scalingFactor = distance(radix, literalEnd);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Not sure if we should use decimal or binary here

File: libsolidity/ast/Types.cpp [hunk 6]
```diff
@@ -389,43 +541,100 @@ IntegerConstantType::IntegerConstantType(Literal const& _literal)
...
+		}
+	}
+	else if (_convertTo.category() == Category::Fixed)
+	{
+		auto targetType = dynamic_cast<FixedType const*>(&_convertTo);
+		if (m_value == 0)
 			return true;
-		return false;
+		int forSignBit = (targetType->isSigned() ? 1 : 0);
+		if (isInteger())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: This seems really complicated. What are the exact rules?

File: libsolidity/ast/Types.cpp [hunk 7]
```diff
@@ -451,44 +660,93 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
+			if (modifier == Modifier::Fixed)
+				if(rightOfRadix() != bigint(0) || other.rightOfRadix() != bigint(0))
+					BOOST_THROW_EXCEPTION(InternalCompilerError() << errinfo_comment("Cannot perform bit operations on non integer fixed type."));
 			value = m_value & other.m_value;
 			break;
 		case Token::Add:
-			value = m_value + other.m_value;
+			if (modifier == Modifier::Fixed)
+			{
+				bigint leftSide = leftOfRadix() + other.leftOfRadix();
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: This looks like we actually do not need a special case for fixed point arithmetics.

File: libsolidity/ast/Types.h [hunk 8]
```diff
@@ -132,7 +132,7 @@ class Type: private boost::noncopyable, public std::enable_shared_from_this<Type
 public:
 	enum class Category
 	{
-		Integer, IntegerConstant, StringLiteral, Bool, Real, Array,
+		Integer, NumberConstant, StringLiteral, Bool, Fixed, Array,
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: I think we should call it `FixedPoint`, otherwise it might be mistaken for `FixedBytes`.

File: libsolidity/ast/Types.h [hunk 9]
```diff
@@ -308,20 +308,67 @@ class IntegerType: public Type
 };
 
 /**
- * Integer constants either literals or computed. Example expressions: 2, 2+10, ~10.
+ * A fixed point type number (signed, unsigned).
+ */
+class FixedType: public Type
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: Also here, I think `FixedPointType` would be better.

File: libsolidity/ast/Types.h [hunk 10]
```diff
@@ -308,20 +308,67 @@ class IntegerType: public Type
...
  * There is one distinct type per value.
  */
-class IntegerConstantType: public Type
+class ConstantNumberType: public Type
 {
 public:
-	virtual Category category() const override { return Category::IntegerConstant; }
+	enum class Modifier
+	{
+		Integer, Fixed
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: Do we really need this? I would say `1.0` is an integer, as is the result of `(2.5 * 2)`.

File: libsolidity/ast/Types.h [hunk 11]
```diff
@@ -338,9 +385,26 @@ class IntegerConstantType: public Type
...
+	bigint rightOfRadix() const
+	{
+		return m_value % boost::multiprecision::pow(bigint(10), m_scalingFactor);
+	}
+	short commonScalingFactor(short const& _firstNumber, short const& _secondNumber, Token::Value const& _operator) const;
 
 private:
+
 	bigint m_value;
+	short m_scalingFactor;
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: Please add a comment, especially about what happens if we e.g. compute `1.0 / 3`.

File: libsolidity/formal/Why3Translator.cpp [hunk 12]
```diff
@@ -428,7 +428,7 @@ bool Why3Translator::visit(BinaryOperation const& _binaryOperation)
 	Type const& commonType = *_binaryOperation.annotation().commonType;
 	Token::Value const c_op = _binaryOperation.getOperator();
 
-	if (commonType.category() == Type::Category::IntegerConstant)
+	if (commonType.category() == Type::Category::NumberConstant)
```
Comment (chriseth) [inline libsolidity/formal/Why3Translator.cpp]: Please throw an error if this is not an integer (not sure if this is the correct place).

File: libsolidity/ast/Types.cpp (hunk 5 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Just from the wikipedia page you gave me, apparently binary will be faster, however, decimal will be more accurate and generally easier to code and understand. My vote goes to decimal.

File: libsolidity/ast/Types.cpp (hunk 6 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: This case is for if our current constantNumber is an integer or not, the else is if it's a fixed type. If it's an integer, we only focus on the bits left of the radix. If it's a fixed type, we make sure that the size of the integer bits and the size of the fractional bits for the type we are converting to are greater or equal to what we currently have so that they fit, respectively. We have the sign bit for obvious reasons in there.

File: libsolidity/ast/Types.cpp (hunk 7 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: I think you're right. This special case should be the default case for all ConstantNumbers.

File: libsolidity/ast/Types.h (hunk 8 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: That's fair.

File: libsolidity/ast/Types.h (hunk 9 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: agreed

File: libsolidity/ast/Types.h (hunk 10 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: mmmmmmm....I suppose we could do that for those cases, but I think whenever melding between the two of them it helps in distinguishing them. I could be wrong however. But that's how I see it currently. There's some rules I've baked in that require this distinction.

File: libsolidity/ast/Types.h (hunk 11 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: certainly.

File: libsolidity/formal/Why3Translator.cpp (hunk 12 above)
Comment (VoR0220) [inline libsolidity/formal/Why3Translator.cpp]: will write that in.

File: libsolidity/ast/Types.cpp (hunk 4 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Definitely should have written that in. This checks to see if it is a valid literal or not. The remove function is to make sure that the radix is removed, otherwise there will be an error thrown when trying to convert to a bigint. Essentially what this is checking is that there are no alphabetical characters, and that there are no odd symbols in there that would not be considered part of an integer.

File: libsolidity/formal/Why3Translator.cpp (hunk 12 above)
Comment (VoR0220) [inline libsolidity/formal/Why3Translator.cpp]: I'm actually not certain how to go about this one. I'm leaving it for now...going to focus on the other parts of this.

**Comment by chriseth** [comment]
Please rebase (PR contains merge commits and github has no way to see how potential merge conflicts were resolved).

File: libsolidity/ast/Types.cpp [hunk 13]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
-bool IntegerConstantType::isValidLiteral(const Literal& _literal)
+FixedPointType::FixedPointType(int _integerBits, int _fractionalBits, FixedPointType::Modifier _modifier):
+	m_integerBits(_integerBits), m_fractionalBits(_fractionalBits), m_modifier(_modifier)
+{
+	solAssert(
+		m_integerBits + m_fractionalBits > 0 && 
+		m_integerBits + m_fractionalBits <= 256 && 
+		m_integerBits % 8 == 0 && 
+		m_fractionalBits % 8 == 0,
+		"Invalid bit number(s) for fixed type: " +
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I think we have to add another restriction here: If the fixed point type is signed, the integer part cannot have zero bits, because we need at least one bit for the sign.
An assert should be added here, and Token.cpp should not generate/parse the tokens `fixed0x8`, ..., `fixed0x256` in the first place.

File: libsolidity/ast/Types.cpp [hunk 14]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+{
+	if (_convertTo.category() == category())
+	{
+		FixedPointType const& convertTo = dynamic_cast<FixedPointType const&>(_convertTo);
+		if (convertTo.m_integerBits < m_integerBits || convertTo.m_fractionalBits < m_fractionalBits)
+			return false;
+		else if (isSigned())
+			return convertTo.isSigned();
+		else
+			return !convertTo.isSigned() || (convertTo.m_integerBits > m_integerBits && convertTo.m_fractionalBits > m_fractionalBits);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: We can drop the condition about fractional bits, I think.

File: libsolidity/ast/Types.cpp [hunk 15]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+		return TypePointer();
+	auto commonType = dynamic_pointer_cast<FixedPointType const>(Type::commonType(shared_from_this(), _other));
+
+	if (!commonType)
+		return TypePointer();
+
+	// All fixed types can be compared
+	if (Token::isCompareOp(_operator))
+		return commonType;
+	if (Token::isBooleanOp(_operator))
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I think we should not allow boolean operators for fixed point types.

File: libsolidity/ast/Types.cpp [hunk 16]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+		return TypePointer();
+	return commonType;
+}
+
+bool ConstantNumberType::isValidLiteral(const Literal& _literal)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: `Literal const&`

File: libsolidity/ast/Types.cpp [hunk 17]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
 {
 	try
 	{
-		bigint x(_literal.value());
+		rational numerator;
+		rational denominator = bigint(1);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: `rational denominator(1)` does not work?

File: libsolidity/ast/Types.cpp [hunk 18]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+				bigint(10), 
+				distance(radixPoint + 1, _literal.value().end())
+			);
+			numerator = bigint(string(_literal.value().begin(), radixPoint));
+			rational x = numerator + denominator;
+		}
+		else
+		{
+			numerator = bigint(_literal.value());
+			rational x = numerator;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Is this needed?

File: libsolidity/ast/Types.cpp [hunk 19]
```diff
@@ -340,11 +368,138 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
 {
 	try
 	{
-		bigint x(_literal.value());
+		rational numerator;
+		rational denominator = bigint(1);
+		auto radixPoint = find(_literal.value().begin(), _literal.value().end(), '.');		
+		if (radixPoint != _literal.value().end())
+		{
+			//problem here. If the first digit is a 0 in the string, it won't
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Do we actually need to do something here apart from checking that it is of the format `digit*.digit*`?
It is probably important to check that `1.0x2` is not a valid literal.

File: libsolidity/ast/Types.cpp [hunk 20]
```diff
@@ -353,16 +508,57 @@ bool IntegerConstantType::isValidLiteral(const Literal& _literal)
...
+
+		m_value = numerator + denominator;		
+		//cout << "Original form: " << _literal.value() << endl;
+		//cout << "Actual form: " << to_string(m_value) << endl;
+		//cout << "Float form: " << to_string(boost::rational_cast<long double>(m_value)) << endl;
+		//cout << endl;
+	}
+	else
+	{
+		numerator = bigint(_literal.value());
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: `m_value = bigint(_literal.value())` does not work?

File: libsolidity/ast/Types.cpp [hunk 21]
```diff
@@ -353,16 +508,57 @@ bool IntegerConstantType::isValidLiteral(const Literal& _literal)
...
 	case Literal::SubDenomination::Wei:
 	case Literal::SubDenomination::Second:
-	case Literal::SubDenomination::None:
+	{
+		if (m_value.denominator() != 1)
+		{
+			char const* sub = Token::toString(_literal.token());
+			BOOST_THROW_EXCEPTION(
+				Error(Error::Type::TypeError) << errinfo_comment(
+					"Cannot divide sub denomination " + ((sub) ? string(Token::toString(_literal.token())) : "") + " any further."
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: If we add this check here, we should also forbid things like
`0.000000000000000000000000000001 szabo`. I think it is best not to check it at all.

File: libsolidity/ast/Types.cpp [hunk 22]
```diff
@@ -390,10 +586,11 @@ IntegerConstantType::IntegerConstantType(Literal const& _literal)
 	}
 }
 
-bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) const
+bool ConstantNumberType::isImplicitlyConvertibleTo(Type const& _convertTo) const
 {
-	if (auto targetType = dynamic_cast<IntegerType const*>(&_convertTo))
+	if (_convertTo.category() == Category::Integer)
 	{
+		auto targetType = dynamic_cast<IntegerType const*>(&_convertTo);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Is that needed?

File: libsolidity/ast/Types.cpp [hunk 23]
```diff
@@ -406,28 +603,52 @@ bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) cons
 			return true;
 		return false;
 	}
+	else if (_convertTo.category() == Category::FixedPoint)
+	{
+		auto targetType = dynamic_cast<FixedPointType const*>(&_convertTo);
+		if (m_value == 0)
+			return true;
+		int forSignBit = (targetType->isSigned() ? 1 : 0);
+		if (m_value > 0)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: What about negative values?

File: libsolidity/ast/Types.cpp [hunk 24]
```diff
@@ -406,28 +603,52 @@ bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) cons
...
+		{
+			bool properlyScaledBits = m_scalingFactor <= targetType->fractionalBits() ?
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: It think it should be enough to test whether `m_value * pow(bigint(10), target_type->fractionalBits())` can be converted to the signed/unsigned integer type with `target_type->fractionalBits() + target_type->integerBits()` bits.

File: libsolidity/ast/Types.cpp [hunk 25]
```diff
@@ -485,73 +733,110 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
 }
 
-u256 IntegerConstantType::literalValue(Literal const*) const
+u256 ConstantNumberType::literalValue(Literal const*) const
 {
 	u256 value;
 	// we ignore the literal and hope that the type was correctly determined
-	solAssert(m_value <= u256(-1), "Integer constant too large.");
-	solAssert(m_value >= -(bigint(1) << 255), "Integer constant too small.");
+	solAssert(m_value <= u256(-1), "Number constant too large.");
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I think this should be relaxed here to allow fractional literals.

File: libsolidity/ast/Types.cpp [hunk 26]
```diff
@@ -485,73 +733,110 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
+	auto fixType = fixedPointType();
+	solAssert(!!fixType, "mobileType called with invalid fixed constant " + toString(false));
+	return fixType;
 }
 
-shared_ptr<IntegerType const> IntegerConstantType::integerType() const
+shared_ptr<IntegerType const> ConstantNumberType::integerType() const
 {
-	bigint value = m_value;
+	bigint value = m_value.numerator();
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:752]: Can we assert that the denominator is 1 here?

File: libsolidity/ast/Types.h [hunk 27]
```diff
@@ -338,9 +384,13 @@ class IntegerConstantType: public Type
...
 	std::shared_ptr<IntegerType const> integerType() const;
-
+	/// @returns the smallest fixed type that can hold the value or an empty pointer
+	std::shared_ptr<FixedPointType const> fixedPointType() const;
+	bigint denominator() const { return m_value.denominator(); }
+	
 private:
-	bigint m_value;
+	rational m_value;
+	short m_scalingFactor;
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: I think we should not store the scaling factor, sometimes it does not even apply, for example for `1/3`.

File: libsolidity/formal/Why3Translator.cpp (hunk 12 above)
Comment (chriseth) [inline libsolidity/formal/Why3Translator.cpp]: Check that denominator is 1, otherwise call `error(_identifier, "Fractional numbers not supported.")`.

File: libsolidity/formal/Why3Translator.cpp [hunk 28]
```diff
@@ -589,7 +589,7 @@ bool Why3Translator::visit(Literal const& _literal)
 		else
 			add("true");
 		break;
-	case Type::Category::IntegerConstant:
+	case Type::Category::NumberConstant:
 		add("(of_int " + toString(type->literalValue(&_literal)) + ")");
```
Comment (chriseth) [inline libsolidity/formal/Why3Translator.cpp:600]: Same here

File: libsolidity/parsing/Token.cpp [hunk 29]
```diff
@@ -151,20 +153,19 @@ tuple<Token::Value, unsigned int, unsigned int> Token::fromIdentifierOrKeyword(s
 				positionM < positionX &&
 				positionX < _literal.end() &&
 				*positionX == 'x' &&
-				all_of(positionX + 1, _literal.end(), ::isdigit)
+				all_of(++positionX, _literal.end(), ::isdigit)
```
Comment (chriseth) [inline libsolidity/parsing/Token.cpp]: I made some changes here that are reverted now. Are you sure your changes are correct?

File: libsolidity/ast/Types.cpp (hunk 13 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: fair point

File: libsolidity/ast/Types.cpp (hunk 14 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: why?

File: libsolidity/ast/Types.cpp (hunk 21 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Shouldn't we give some kind of warning for it in some form?

File: libsolidity/ast/Types.cpp (hunk 23 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: good point...this is a bit copy and paste from the integer portion.

File: libsolidity/ast/Types.cpp (hunk 14 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Because `convertTo.m_fractionalBits == m_fractionalBits` is also fine, and we already checked `<` above.

File: libsolidity/ast/Types.cpp (hunk 25 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: what would you put instead?

File: libsolidity/ast/Types.cpp (hunk 21 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Why? `ufixed x = .5 wei` is perfectly fine, you will get an error when you want to convert it to `uint`.

File: libsolidity/ast/Types.h (hunk 27 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: that is what I was worried about. However it is very useful when converting to a fixed point type. I am currently running into problems surrounding this. What would you recommend instead of a scaling factor for a conversion?

File: libsolidity/ast/Types.cpp (hunk 26 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:752]: no, we don't want to do that. We need the conversion to integerType to take into account a case whereby a integer may need to be converted into a fixed point type and vice versa. Perhaps this is a clunky way of going about it, but that should be the case.

File: libsolidity/ast/Types.cpp (hunk 16 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: on it

File: libsolidity/ast/Types.h (hunk 27 above)
Comment (chriseth) [inline libsolidity/ast/Types.h]: So yes, the point where we have a problem is `fixed x = 1/3`, because it will never fit without truncating.
So the question is: What is the "intrinsic fixed point type" for a constant (what is returned by `fixedPointType()`) and which fixed point types do we allow implicit conversion to (explicit conversion is always fine)?

I would say the `canonical` fixed point type is the one with the smallest number of bits such that the number fits without losing information: I.e. we have to count the number of bits that can hold the numerator plus sign bit (should be the same code as in the integer case) and for the fractional bits, we should get that `denominator * 10**bits` is an integer. Then implicit conversions are ok if and only if the canonical fixed point type can be converted.

We should also add that information to the documentation and to https://github.com/ethereum/wiki/wiki/Solidity-Features

File: libsolidity/ast/Types.cpp (hunk 21 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: ahhhhhhhh...okay I see your reasoning now.

File: libsolidity/parsing/Token.cpp (hunk 29 above)
Comment (VoR0220) [inline libsolidity/parsing/Token.cpp]: correct in the sense that they work. See below the reasoning...However....I can change it back to what it was before with little pain, so I think that can be done.

Comment (VoR0220) [inline libsolidity/parsing/Token.cpp]: The changes for m and n needed to be put there, and the issue with UFixedMxN not being considered an identifier are also solved below.

File: libsolidity/ast/Types.cpp (hunk 20 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: good point.

File: libsolidity/ast/Types.cpp (hunk 18 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: no it is not. Good catch.

File: libsolidity/ast/Types.cpp [hunk 30]
```diff
@@ -406,28 +603,52 @@ bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) cons
 			return true;
 		return false;
 	}
+	else if (_convertTo.category() == Category::FixedPoint)
+	{
+		auto targetType = dynamic_cast<FixedPointType const*>(&_convertTo);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: As discussed below, I think we should rather use `fixedPoint() && fixedPoint()->isImplicitlyConvertibleTo(_convertTo)` to avoid code duplication.

File: libsolidity/ast/Types.cpp [hunk 31]
```diff
@@ -406,28 +603,52 @@ bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) cons
...
+bool ConstantNumberType::isExplicitlyConvertibleTo(Type const& _convertTo) const
 {
-	TypePointer intType = integerType();
-	return intType && intType->isExplicitlyConvertibleTo(_convertTo);
+	if (m_value.denominator() == 1)
+	{
+		TypePointer intType = integerType();
+		return intType && intType->isExplicitlyConvertibleTo(_convertTo);
+	}
+	TypePointer fixType = fixedPointType();
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I think we have to do that more manually here, because `1/3` does not have a canonical fixed point type, but `fixed(1/3)` is still a valid explicit conversion.

File: libsolidity/formal/Why3Translator.cpp (hunk 12 above)
Comment (VoR0220) [inline libsolidity/formal/Why3Translator.cpp]: done

File: libsolidity/ast/Types.cpp (hunk 19 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Yes...we do. If the first digits are 0s they cannot be converted into bigints.

File: libsolidity/ast/Types.h (hunk 27 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: Well here's the problem. How does the function know the number of bits that it is converting to?

File: libsolidity/ast/Types.cpp (hunk 13 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: dropped as can add sign bit to fractional side.

File: libsolidity/ast/Types.h (hunk 27 above)
Comment (chriseth) [inline libsolidity/ast/Types.h]: I'm confused, doesn't the description above explain that? `number of fractional bits = min{i | m_value * 2**i is integer and i is multiple of 8 and i <= 256}`

Comment (VoR0220) [inline libsolidity/ast/Types.h]: yes but remember, the NumberConstant and especially the fixedPoint function don't necessarily know that without an input.

Comment (VoR0220) [inline libsolidity/ast/Types.h]: wait a second...I might be wrong. Let me try something.

File: libsolidity/ast/Types.cpp (hunk 13 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: skipping because we can assign sign bit to the fractional side.

File: libsolidity/ast/Types.cpp (hunk 26 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:752]: In fact I realized that the way this is going about it is all wrong. This needs to get rid of whatever remainder is left and truncate it.

File: libsolidity/ast/Types.cpp (hunk 31 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: If only integer types are concerned, we disallowed conversion when the number was too large.
Now that we add rationals, we cannot disallow conversion for rationals that cannot be represented in finite precision.
So the conversion rules are a bit more complicated and we have to check each of them here.

File: libsolidity/ast/Types.cpp (hunk 24 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: thinking about this...this should actually be checking to see whether the whole numbers of the rational can fit in the integer bits and if the remainder can fit in the fractional bits...Otherwise we haven't properly converted, have we?

File: libsolidity/parsing/Token.cpp (hunk 29 above)
Comment (VoR0220) [inline libsolidity/parsing/Token.cpp]: there may be an odd error coming from my change. Investigating.

File: libsolidity/ast/Types.cpp [hunk 32]
```diff
@@ -452,31 +639,57 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
+			if (!thisFixedPointType || !otherFixedPointType)
+				return TypePointer();
+			return thisFixedPointType->binaryOperatorResult(_operator, otherFixedPointType);
+		}		
 	}
 	else
 	{
-		bigint value;
+		rational value;
+		bool fixedPointType = (m_value.denominator() != 1 || other.m_value.denominator() != 1);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: "`fractional`"?

File: libsolidity/ast/Types.cpp [hunk 33]
```diff
@@ -452,31 +639,57 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
 		switch (_operator)
 		{
+		//bit operations will only be enabled for integers and fixed types that resemble integers
 		case Token::BitOr:
-			value = m_value | other.m_value;
+			if (fixedPointType)
+				BOOST_THROW_EXCEPTION(Error(Error::Type::TypeError) << errinfo_comment("Cannot perform bit operations on non integer fixed type."));
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: These should return `TypePointer()`.

File: libsolidity/ast/Types.cpp [hunk 34]
```diff
@@ -486,72 +699,110 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
 			break;
 		case Token::Mod:
 			if (other.m_value == 0)
 				return TypePointer();
-			value = m_value % other.m_value;
-			break;
+			else if (fixedPointType)
+			{
+				value = m_value;
+				if (value > other.m_value)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Is that really what we want? If yes, is there a more efficient way to do it? :-)

File: libsolidity/ast/Types.cpp [hunk 35]
```diff
@@ -486,72 +699,110 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
 			break;
 		case Token::Mul:
 			value = m_value * other.m_value;
-			break;
+			break;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Superfluous whitespace.

File: libsolidity/ast/Types.h [hunk 36]
```diff
@@ -338,9 +384,15 @@ class IntegerConstantType: public Type
 
 	/// @returns the smallest integer type that can hold the value or an empty pointer if not possible.
 	std::shared_ptr<IntegerType const> integerType() const;
+	/// @returns the smallest fixed type that can hold the value or an empty pointer
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: Should be changed to "... hold the value or incurs the least precision loss. If the integer part does not fit, returns an empty pointer."

File: libsolidity/ast/Types.cpp (hunk 34 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Do tell me of the more efficient way to do it :) I've been thinking about it but I can't figure it out.

File: libsolidity/ast/Types.cpp (hunk 35 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: whoops

File: libsolidity/ast/Types.cpp (hunk 32 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Definitely

File: libsolidity/ast/Types.cpp (hunk 33 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Fair enough.

File: libsolidity/ast/Types.h (hunk 36 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: alright. I'll change it to that...and ensure that it actually does that.

File: libsolidity/ast/Types.cpp [hunk 37]
```diff
@@ -561,6 +812,75 @@ shared_ptr<IntegerType const> IntegerConstantType::integerType() const
 		);
 }
 
+shared_ptr<FixedPointType const> RationalNumberType::fixedPointType() const
+{
+	//do calculations up here
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: What about this implementation:

```
    bool negative = (m_value < 0);
    unsigned fractionalBits = 0;
    rational value = m_value;
    rational maxValue = rational(bigint(1) << 256);
    if (!negative)
        maxValue -= 1;
    else
        value = -value;
    while (value * 0x100 <= maxValue && value.denominator() != 1)
    {
        value *= 0x100;
        fractionalBits += 8;
    }

    if (value > maxValue)
        return shared_ptr<FixedPointType const>();
    bigint v = value.denominator() / value.numerator();
    if (negative)
        v = -v;
    // u256(v) is the actual value that will be put on the stack
    // From here on, very similar to integerType()
    if (negative) // convert to positive number of same bit requirements
        value = ((0 - value) - 1) << 1;
    if (value > u256(-1))
        return shared_ptr<FixedPointType const>();
    unsigned integerBits = bytesRequired(value);
    solAssert(integerBits >= fractionalBits, "Invalid bit requirement calculation.");
    //@todo special handling for integerBits == 0 && fractionalBits == 0?
    return make_shared<FixedPointType>(
        integerBits, fractionalBits,
        negative ? FixedPointType::Modifier::Signed : FixedPointType::Modifier::Unsigned
    );
```

File: libsolidity/ast/Types.cpp [hunk 38]
```diff
@@ -390,10 +561,11 @@ IntegerConstantType::IntegerConstantType(Literal const& _literal)
 	}
 }
 
-bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) const
+bool RationalNumberType::isImplicitlyConvertibleTo(Type const& _convertTo) const
 {
-	if (auto targetType = dynamic_cast<IntegerType const*>(&_convertTo))
+	if (_convertTo.category() == Category::Integer)
 	{
+		auto targetType = dynamic_cast<IntegerType const*>(&_convertTo);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:533]: `If (m_value.denominator() != 1) return false;`

File: libsolidity/ast/Types.cpp [hunk 39]
```diff
@@ -406,44 +578,59 @@ bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) cons
 			return true;
 		return false;
 	}
+	else if (_convertTo.category() == Category::FixedPoint)
+	{
+		if (fixedPointType() && fixedPointType()->isImplicitlyConvertibleTo(_convertTo))
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: We cannot use `fixedPointType()` here because we have to return false if the number does not fit into finite precision. Instead, I would propose to do something like

```
rational shifted = (m_value * (bigint(1) << (8 * _convertTo.fractionalBits())));
if (shifted.denominator() != 1) return false;
// here, do the same stuff we do above for integers with _convertTo.integerBits() + _convertTo.fractioalBits() bits.
```

File: libsolidity/ast/Types.cpp [hunk 40]
```diff
@@ -406,44 +578,59 @@ bool IntegerConstantType::isImplicitlyConvertibleTo(Type const& _convertTo) cons
...
+		return false;
+	}
 	else if (_convertTo.category() == Category::FixedBytes)
 	{
 		FixedBytesType const& fixedBytes = dynamic_cast<FixedBytesType const&>(_convertTo);
-		return fixedBytes.numBytes() * 8 >= integerType()->numBits();
+		if (m_value.denominator() == 1)
+			return fixedBytes.numBytes() * 8 >= integerType()->numBits();
+		else
+			return fixedBytes.numBytes() * 8 >= fixedPointType()->numBits();
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I would return false here because there is no obvious way to do the conversion.

File: libsolidity/ast/Types.cpp (hunk 39 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: But it's already checking to see if the number can fit into finite precision, is it not?

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: see fixed point implicit conversion function.

File: libsolidity/ast/Types.cpp (hunk 40 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Yes there is :) we talked about this. We take the fixed point bigint, we convert it over and take it in its pure byte form and pad right.

File: libsolidity/ast/Types.cpp (hunk 37 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Why would we solAssert that integerbits be bigger than fractionalBits? That takes away the ability to have a fixed0x256.

File: libsolidity/ast/Types.cpp (hunk 34 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: `a % b = c <=> 0 <= c < |b| && \exist x \in \int: a = xb+c`
So what about something like `a - ((a/b).numerator() / (a/b).denominator()) * b`?
Concerning the sign of `a%b`, please follow the convention used by the EVM itself.

File: libsolidity/ast/Types.cpp (hunk 37 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: also, getting an error thrown at me with this:

rational maxValue = rational(bigint(1) << 256);

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: got it to run...but it's breaking most of my tests.

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: it's also somehow enabling 272 bit fraction types....

File: libsolidity/ast/Types.cpp (hunk 40 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: That assumes a certain encoding of the fixed number type. Remember that integer -> byte conversion is only explicit.

File: libsolidity/ast/Types.cpp (hunk 37 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I did not say that it is perfect, but at least to me, it looks a lot simpler. I might be missing out on some edge cases, but actually I think I got all of them.

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: one I fixed it up it appears to be working...still gotta figure out why this infinite loop is happening though.

File: libsolidity/ast/Types.cpp (hunk 40 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: ahhhh...crap...yeah you're right.

File: libsolidity/ast/Types.cpp (hunk 37 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: here's my patched up version. For some reason it is effecting my unary operation test with the negative...

```
shared_ptr<FixedPointType const> RationalNumberType::fixedPointType() const
{
    bool negative = (m_value < 0);
    unsigned fractionalBits = 0;
    unsigned integerBits = bytesRequired(wholeNumbers()) * 8;
    rational value = m_value;
    bigint l = bigint(1) << 256;
    rational maxValue = rational(l);
    if (!negative)
        maxValue -= 1;
    else
        value = -value;
    cout << "Max value: " << maxValue << endl;
    while (value * 0x100 <= maxValue && value.denominator() != 1 && fractionalBits < 256 - integerBits)
    {
        value *= 0x100;
        fractionalBits += 8;
    }

    if (value > maxValue)
    {
        cout << "value > max value " << endl;
        return shared_ptr<FixedPointType const>();
    }
    bigint v = value.denominator() / value.numerator();
    if (negative)
        v = -v;
    // u256(v) is the actual value that will be put on the stack
    // From here on, very similar to integerType()
    //if (negative) // convert to positive number of same bit requirements
    //  value = ((0 - value) - 1) << 1;
    if (value > u256(-1))
    {
        cout << "Too large of a number" << endl;
        return shared_ptr<FixedPointType const>();
    }

    //solAssert(integerBits >= fractionalBits, "Invalid bit requirement calculation.");
    //@todo special handling for integerBits == 0 && fractionalBits == 0?
    return make_shared<FixedPointType>(
        integerBits, fractionalBits,
        negative ? FixedPointType::Modifier::Signed : FixedPointType::Modifier::Unsigned
    );
}
```

File: libsolidity/ast/Types.cpp (hunk 38 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:533]: in this case though, there is an implicit conversion, we simply truncate off the fractional bits.

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 41]
```diff
@@ -103,10 +103,11 @@ void ReferencesResolver::endVisit(ArrayTypeName const& _typeName)
 	{
 		if (!length->annotation().type)
 			ConstantEvaluator e(*length);
-
-		auto const* lengthType = dynamic_cast<IntegerConstantType const*>(length->annotation().type.get());
+		auto const* lengthType = dynamic_cast<RationalNumberType const*>(length->annotation().type.get());
 		if (!lengthType)
 			fatalTypeError(length->location(), "Invalid array length.");
+		else if (lengthType->denominator() != 1)
+			fatalTypeError(length->location(), "Invalid input for array length, expected integer.");
```
Comment (chriseth) [inline libsolidity/analysis/ReferencesResolver.cpp]: Please change to `Invalid array length, expected integer literal.` (and please also change above)

File: libsolidity/analysis/TypeChecker.cpp [hunk 42]
```diff
@@ -773,8 +773,8 @@ bool TypeChecker::visit(VariableDeclarationStatement const& _statement)
 			// Infer type from value.
 			solAssert(!var.typeName(), "");
 			if (
-				valueComponentType->category() == Type::Category::IntegerConstant &&
-				!dynamic_pointer_cast<IntegerConstantType const>(valueComponentType)->integerType()
+				valueComponentType->category() == Type::Category::RationalNumber &&
+				!dynamic_pointer_cast<RationalNumberType const>(valueComponentType)->integerType()
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: This should also work for rationals.

File: libsolidity/analysis/TypeChecker.cpp [hunk 43]
```diff
@@ -799,8 +799,8 @@ bool TypeChecker::visit(VariableDeclarationStatement const& _statement)
 
 void TypeChecker::endVisit(ExpressionStatement const& _statement)
 {
-	if (type(_statement.expression())->category() == Type::Category::IntegerConstant)
-		if (!dynamic_pointer_cast<IntegerConstantType const>(type(_statement.expression()))->integerType())
+	if (type(_statement.expression())->category() == Type::Category::RationalNumber)
+		if (!dynamic_pointer_cast<RationalNumberType const>(type(_statement.expression()))->integerType())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Should also work for rationals.

File: libsolidity/analysis/TypeChecker.cpp [hunk 44]
```diff
@@ -1106,7 +1106,7 @@ bool TypeChecker::visit(FunctionCall const& _functionCall)
 			auto const& argType = type(*arguments[i]);
 			if (functionType->takesArbitraryParameters())
 			{
-				if (auto t = dynamic_cast<IntegerConstantType const*>(argType.get()))
+				if (auto t = dynamic_cast<RationalNumberType const*>(argType.get()))
 					if (!t->integerType())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Should also work for rationals.

File: libsolidity/analysis/TypeChecker.cpp [hunk 45]
```diff
@@ -1341,9 +1341,13 @@ bool TypeChecker::visit(IndexAccess const& _access)
 		else
 		{
 			expectType(*index, IntegerType(256));
-			if (auto integerType = dynamic_cast<IntegerConstantType const*>(type(*index).get()))
-				if (!actualType.isDynamicallySized() && actualType.length() <= integerType->literalValue(nullptr))
+			if (auto numberType = dynamic_cast<RationalNumberType const*>(type(*index).get()))
+			{
+				if (numberType->denominator() != 1)
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: You can change that to an assert - we already checked for implicit convertibility to `u256` in line 1343.

File: libsolidity/analysis/TypeChecker.cpp [hunk 46]
```diff
@@ -1368,7 +1372,7 @@ bool TypeChecker::visit(IndexAccess const& _access)
 		else
 		{
 			index->accept(*this);
-			if (auto length = dynamic_cast<IntegerConstantType const*>(type(*index).get()))
+			if (auto length = dynamic_cast<RationalNumberType const*>(type(*index).get()))
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Please check that it is an integer here.

File: libsolidity/analysis/TypeChecker.cpp [hunk 47]
```diff
@@ -1368,7 +1372,7 @@ bool TypeChecker::visit(IndexAccess const& _access)
 		else
 		{
 			index->accept(*this);
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: I think this should actually be `expectType(*index, IntegerType(256));`

File: libsolidity/ast/Types.cpp [hunk 48]
```diff
@@ -251,17 +262,30 @@ IntegerType::IntegerType(int _bits, IntegerType::Modifier _modifier):
...
-	if (isAddress())
-		return convertTo.isAddress();
-	else if (isSigned())
-		return convertTo.isSigned();
+	if (_convertTo.category() == category())
+	{	
+		IntegerType const& convertTo = dynamic_cast<IntegerType const&>(_convertTo);
+		if (convertTo.m_bits < m_bits)
+			return false;
+		if (isAddress())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:267]: This restriction should also be checked when converting to rational

File: libsolidity/ast/Types.cpp [hunk 49]
```diff
@@ -307,7 +331,7 @@ string IntegerType::toString(bool) const
 
 TypePointer IntegerType::binaryOperatorResult(Token::Value _operator, TypePointer const& _other) const
 {
-	if (_other->category() != Category::IntegerConstant && _other->category() != category())
+	if (_other->category() != Category::RationalNumber && _other->category() != category())
 		return TypePointer();
 	auto commonType = dynamic_pointer_cast<IntegerType const>(Type::commonType(shared_from_this(), _other));
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:333]: The conditions below are not 100% correct. It will allow the following:

```
uint8 x = 2;
ufixed y = .5;
x**y
```

Please make a note somewhere to add a test for that once we get to implementing fixed point types themselves.

File: libsolidity/ast/Types.cpp [hunk 50]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
 		return MemberList::MemberMap();
 }
 
-bool IntegerConstantType::isValidLiteral(const Literal& _literal)
+FixedPointType::FixedPointType(int _integerBits, int _fractionalBits, FixedPointType::Modifier _modifier):
+	m_integerBits(_integerBits), m_fractionalBits(_fractionalBits), m_modifier(_modifier)
+{
+	solAssert(
+		m_integerBits + m_fractionalBits > 0 &&
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:368]: Actually I would consider disallowing `fixedMx0` because that is just an alias for `intM` (this is not the place to do that, of course, but rather Token.cpp).

File: libsolidity/ast/Types.cpp [hunk 51]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+			return convertTo.isSigned();
+		else
+			return !convertTo.isSigned() || (convertTo.m_integerBits > m_integerBits);
+	}
+	else if (_convertTo.category() == Category::Integer)
+	{
+		IntegerType const& convertTo = dynamic_cast<IntegerType const&>(_convertTo);
+		if (convertTo.numBits() < m_integerBits)
+			return false;
+		else if (isSigned())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Disallow conversion to address, please.

File: libsolidity/ast/Types.cpp [hunk 52]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+			return convertTo.isSigned();
+		else
+			return !convertTo.isSigned() || (convertTo.m_integerBits > m_integerBits);
+	}
+	else if (_convertTo.category() == Category::Integer)
+	{
+		IntegerType const& convertTo = dynamic_cast<IntegerType const&>(_convertTo);
+		if (convertTo.numBits() < m_integerBits)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Conversion should only be allowed if `m_fractionalBits == 0`, but please see above (remove that case altogether).

File: libsolidity/ast/Types.cpp (hunk 50 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:368]: for me it would seem that it might make type conversion easier for the user.

File: libsolidity/ast/Types.cpp [hunk 53]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+
+string FixedPointType::toString(bool) const
+{
+	string prefix = isSigned() ? "fixed" : "ufixed";
+	return prefix + dev::toString(m_integerBits) + "x" + dev::toString(m_fractionalBits);
+}
+
+TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePointer const& _other) const
+{
+	if (_other->category() != Category::RationalNumber
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]:
```
if (
    _other->category()...
)
```

File: libsolidity/ast/Types.cpp [hunk 54]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+string FixedPointType::toString(bool) const
+{
+	string prefix = isSigned() ? "fixed" : "ufixed";
+	return prefix + dev::toString(m_integerBits) + "x" + dev::toString(m_fractionalBits);
+}
+
+TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePointer const& _other) const
+{
+	if (_other->category() != Category::RationalNumber 
+		&& _other->category() != category()
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Should be `||`

File: libsolidity/ast/Types.cpp [hunk 55]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+
+	if (!commonType)
+		return TypePointer();
+
+	// All fixed types can be compared
+	if (Token::isCompareOp(_operator))
+		return commonType;
+	if (Token::isBooleanOp(_operator))
+		return TypePointer();
+	return commonType;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp:452]: I think we should check all the operators, there might be some we have to disallow.

File: libsolidity/ast/Types.cpp (hunk 49 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:333]: I thought we were allowing that? That we would be able to run exponents of fixed types?

File: libsolidity/ast/Types.cpp [hunk 56]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
 {
 	try
 	{
-		bigint x(_literal.value());
+		rational numerator;
+		rational denominator(1);
+		auto radixPoint = find(_literal.value().begin(), _literal.value().end(), '.');		
+		if (radixPoint != _literal.value().end())
+		{
+			//problem here. If the first digit is a 0 in the string, it won't
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Please change comment: Only decimal notation allowed here, leading zeros would switch to octal.

File: libsolidity/ast/Types.cpp [hunk 57]
```diff
@@ -340,11 +364,133 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+			//turn it into a integer...Using find if not to count the leading 0s.
+			auto leadingZeroes = find_if_not(
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Please also check that the whole number conforms to `[0-9]*.[0-9]*`

File: libsolidity/ast/Types.cpp (hunk 49 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp:333]: Right, I'm backing off :-)
But: be prepared to implement a gigantic mess of assembly for that.

Comment (VoR0220) [inline libsolidity/ast/Types.cpp:333]: YAY!!! :)

File: libsolidity/ast/Types.cpp (hunk 50 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp:368]: Why do you think?

Comment (VoR0220) [inline libsolidity/ast/Types.cpp:368]: just simplicity of the idea and especially for explicit conversion. Be odd if we just out of the blue disallowed them from having a fixed act as an int...but I suppose it could go both ways. Me personally I'd like the flexibility in the understanding of it.

Comment (chriseth) [inline libsolidity/ast/Types.cpp:368]: If we allow `fixedNx0`, then it should be an exact alias for `intN`, which I believe is more work to implement.

File: libsolidity/ast/Types.cpp [hunk 58]
```diff
@@ -353,15 +499,37 @@ bool IntegerConstantType::isValidLiteral(const Literal& _literal)
...
+	{
+		auto leadingZeroes = find_if_not(
+				radixPoint + 1, 
+				_literal.value().end(), 
+				[](char const& a) { return a == '0'; }
+			);
+		auto fractionalBegin = leadingZeroes != _literal.value().end() ?
+			leadingZeroes : radixPoint + 1;
+		//separatly grabbing the numerator, denominator for conversions
+		denominator = bigint(string(fractionalBegin, _literal.value().end()));
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Code duplication with previous function.

File: libsolidity/ast/Types.cpp (hunk 38 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp:533]: We cannot ever destroy information for an implicit conversion, that is one of its two core principles.

File: libsolidity/ast/Types.cpp [hunk 59]
```diff
@@ -486,72 +696,105 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
 			break;
 		case Token::Mul:
 			value = m_value * other.m_value;
-			break;
+			break;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Surplus whitespace.

File: libsolidity/ast/Types.cpp [hunk 60]
```diff
@@ -561,6 +804,55 @@ shared_ptr<IntegerType const> IntegerConstantType::integerType() const
...
+	{
+		value = abs(value);
+		if (wholeNumbers() > 0)
+			transitionValue = ((0 - wholeNumbers()) - 1) << 1;
+		else
+			transitionValue = 0;
+		integerBits = bytesRequired(transitionValue) * 8;
+	}
+
+	while (value * 0x100 <= maxValue && value.denominator() != 1 && fractionalBits < 256 - integerBits)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: I don't really get the meaning of `transitionValue` and I don't see why we need to keep track of `integerBits` here.
I would say this algorithm is much more stable if we first try to convert the number into an integer by shifting (as it is done here) and then define `integerBits = bytesRequired(value) - fractionalBits`.

File: libsolidity/ast/Types.h [hunk 61]
```diff
@@ -338,9 +384,15 @@ class IntegerConstantType: public Type
 
 	/// @returns the smallest integer type that can hold the value or an empty pointer if not possible.
 	std::shared_ptr<IntegerType const> integerType() const;
+	/// @returns the smallest fixed type that can  hold the value or incurs the least precision loss. 
+	/// If the integer part does not fit, returns an empty pointer.
+	std::shared_ptr<FixedPointType const> fixedPointType() const;
+
+	bigint denominator() const { return m_value.denominator(); }
+	bigint wholeNumbers() const { return m_value.numerator() / m_value.denominator(); }
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: What about renaming this to `truncatedIntegerPart`?

File: libsolidity/ast/Types.cpp (hunk 58 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: indeed...should make this its own function.

File: libsolidity/ast/Types.cpp (hunk 57 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: can you elaborate?

File: libsolidity/ast/Types.h (hunk 61 above)
Comment (VoR0220) [inline libsolidity/ast/Types.h]: Bit long of a name don't you think? What about something shorter?

File: libsolidity/ast/Types.cpp (hunk 60 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: hmmmm....that's a pretty clever way to go about it. I think we'll do that.

File: libsolidity/ast/Types.h (hunk 61 above)
Comment (chriseth) [inline libsolidity/ast/Types.h]: integerPart?

Comment (VoR0220) [inline libsolidity/ast/Types.h]: that works

File: libsolidity/ast/Types.cpp (hunk 60 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: transitionValue is there because you cannot run bit operations on a rational type.

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Also I put the integer bits in the while loop to make the loop more efficient. We go until we can't fit anymore and enables more numbers to get into the system that users would like to use. This is why we need it before we get the value.

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: relooking at it, I think we should keep it as is.

File: libsolidity/ast/Types.cpp (hunk 48 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:267]: Rational or fixed point?

File: libsolidity/ast/Types.cpp (hunk 55 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp:452]: Bitop was one I just added.

File: libsolidity/ast/Types.cpp (hunk 48 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp:267]: of course, fixed, conversion to rational is not possible.

File: libsolidity/ast/Types.cpp (hunk 60 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: But then you have to add more comments, I don't get the meaning of `transitionValue`.

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: ahhhhh...it's a temporary big int to hold the value and pop it in the rational. Perhaps `temporaryBigInt` might be better?

File: libsolidity/ast/Types.cpp [hunk 62]
```diff
@@ -340,110 +367,254 @@ MemberList::MemberMap IntegerType::nativeMembers(ContractDefinition const*) cons
...
+				!all_of(_literal.value().begin(), radixPoint, ::isdigit)
+			)
+				throw;
+			//Only decimal notation allowed here, leading zeros would switch to octal.
+			auto leadingZeroes = find_if_not(
+				radixPoint + 1, 
+				_literal.value().end(), 
+				[](char const& a) { return a == '0'; }
+			);
+			auto fractionalBegin = leadingZeroes != _literal.value().end() ?
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: It might be possible to remove this condition without replacement.

File: libsolidity/ast/Types.cpp [hunk 63]
```diff
@@ -490,68 +687,100 @@ TypePointer IntegerConstantType::binaryOperatorResult(Token::Value _operator, Ty
...
+	if (m_value.denominator() == 1)
+		return "int_const " + m_value.numerator().str();
+	return "rational_const " + m_value.numerator().str() + '/' + m_value.denominator().str();
 }
 
-u256 IntegerConstantType::literalValue(Literal const*) const
+u256 RationalNumberType::literalValue(Literal const*) const
 {
 	u256 value;
+	bigint shiftedValue = integerPart();
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: We need `m_value * 2**numFixedBits` here. Also assert that denominator is 1 after multiplication. and then keep the additional asserts below. Oh and convert to 2's complement if negative.

File: libsolidity/ast/Types.cpp (hunk 62 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: It's possible to remove this condition, but I noticed something very odd when I was testing out the var capabilities...only the first rational type registers...everything after that does not register atleast in terms of a isValid literal...it does not hit that function. This should require some investigation or atleast some explanation as to why this might be.

File: libsolidity/ast/Types.cpp (hunk 63 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: how do we gather numFixedBits?

File: libsolidity/ast/Types.cpp (hunk 60 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: just came to a realization...we shouldn't go ahead and loop through again on what is conceivably a larger number than we looped through for the fractional bits. If we only loop through for the integer bits, we're conceivably working with a smaller number of loops...there's considerable overlap with the v value of the same fractional bits that we just processed.

**Comment by innovator256** [comment]
go go go guys....we are waiting :) thank you @VoR0220, thank you @chriseth !!

File: libsolidity/ast/Types.cpp (hunk 63 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: You don't need the actual number, it is fine to just multiply by 8 until the number is an integer.

File: libsolidity/ast/Types.cpp (hunk 60 above)
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: If there is an error in the implementation here, it might very well be that we will never notice.
Please compare "there might be an error we never notice" to "looping 20 or 32 times".

Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: Hmmmm....i suppose when you frame it like that.

File: libsolidity/ast/Types.cpp (hunk 63 above)
Comment (VoR0220) [inline libsolidity/ast/Types.cpp]: if we're asking for the literal value...shouldn't we be getting the LITERAL value of the type? Shouldn't we be multiplying by 10 until denominator != 1?

File: libsolidity/analysis/TypeChecker.cpp [hunk 64]
```diff
@@ -773,35 +773,56 @@ bool TypeChecker::visit(VariableDeclarationStatement const& _statement)
 			// Infer type from value.
 			solAssert(!var.typeName(), "");
 			if (
-				valueComponentType->category() == Type::Category::IntegerConstant &&
-				!dynamic_pointer_cast<IntegerConstantType const>(valueComponentType)->integerType()
+				valueComponentType->category() == Type::Category::RationalNumber &&
+				!dynamic_pointer_cast<RationalNumberType const>(valueComponentType)->integerType() &&
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: The call to `integerType` triggers an assertion if called on a non-integer. I guess the best thing here is to check that `mobileType()` does not return a null shared pointer.

This could be done in a generic way (not only for RationalNumber category) and then tune the error message in the case we have a RationalNumber.

File: libsolidity/analysis/TypeChecker.cpp [hunk 65]
```diff
@@ -773,35 +773,56 @@ bool TypeChecker::visit(VariableDeclarationStatement const& _statement)
...
+				)
+					typeError(
+						_statement.location(),
+						"Type " +
+						valueComponentType->toString() +
+						" is not implicitly convertible to expected type " +
+						var.annotation().type->toString() +
+						". Try converting to type " +
+						valueComponentType->mobileType()->toString() +
+						" or using an explicit conversion."
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Wording: "or use"? Oh and `mobileType()` can return null!
