### PR TITLE
[SMTChecker] Fix ICE when bitwise operator on fixed bytes

### LINKED ISSUE #9087: [SMTUtil] ICE via SMTLogicError due to "_n.sort->kind != Kind::Int"
## Description

```
pragma experimental SMTChecker;
contract C {
  function f() public {
    (byte("") & (""));
  }
}
```

throws

https://github.com/ethereum/solidity/blob/0a71e415013c8ae712de0c519a22aef2cf1c2119/libsmtutil/SolverInterface.h#L203

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/9087 https://github.com/ethereum/solidity/issues/9101

### CODE REVIEW

**Review by chriseth — DISMISSED** [review]

File: libsmtutil/SolverInterface.h [hunk 1]
```diff
@@ -262,23 +262,23 @@ class Expression
 	}
 	friend Expression operator+(Expression _a, Expression _b)
 	{
-		return Expression("+", std::move(_a), std::move(_b), Kind::Int);
+		return Expression("+", {std::move(_a), std::move(_b)}, SortProvider::sintSort);
```
Comment (leonardoalt) [inline libsmtutil/SolverInterface.h]: @chriseth actually these should use `_a`'s sort, as you pointed out at some point

**Review by chriseth — APPROVED** [review]
