### PR TITLE
Fix SMTChecker bug when a public library function is called internally

### LINKED ISSUE #13477: [SMTChecker] CHC engine throws `out_of_range` in a simple example with two libraries and an internal call
```
pragma experimental SMTChecker;
library L1 {}
library L2 {
  function f1() public {}
  function f() internal { f1(); }
}
```

throws

https://github.com/ethereum/solidity/blob/51929652291a833889c2f3132b2ca6f037c02a56/libsolidity/formal/CHC.cpp#L1526

### PR DESCRIPTION
**Pull request by leonardoalt**
Fix https://github.com/ethereum/solidity/issues/13477

### CODE REVIEW

File: test/libsolidity/SMTCheckerTest.cpp [hunk 1]
```diff
@@ -29,6 +29,10 @@ using namespace solidity::frontend::test;
 
 SMTCheckerTest::SMTCheckerTest(string const& _filename): SyntaxTest(_filename, EVMVersion{})
 {
+	auto contract = m_reader.stringSetting("SMTContract", "");
+	if (!contract.empty())
+		m_modelCheckerSettings.contracts.contracts[""] = {contract};
```
Comment (leonardoalt) [inline test/libsolidity/SMTCheckerTest.cpp:34]: Needed to add this option to SMTChecker isoltest otherwise the added tests would only report the assertion failure from L but we wanted to test C which is what caused the bug before.

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -3162,11 +3162,11 @@ void SMTEncoder::collectFreeFunctions(set<SourceUnit const*, ASTNode::CompareByI
 				auto contract = dynamic_cast<ContractDefinition const*>(node.get());
 				contract && contract->isLibrary()
 			)
-			{
 				for (auto function: contract->definedFunctions())
-					if (!function->isPublic())
+					// We need to add public library functions too because they can be called
+					// internally by internal library functions that are considered free functions.
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp:3167]: Why are internal library functions considered free functions?

File: libsolidity/formal/SMTEncoder.cpp [hunk 3]
```diff
@@ -3162,11 +3162,11 @@ void SMTEncoder::collectFreeFunctions(set<SourceUnit const*, ASTNode::CompareByI
...
+					if (!function->isPublic() || function->libraryFunction())
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp]: I think the condition can now be simplified to `true`.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: why?

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:3167]: Because they are called in the context of the caller contract, so for the encoding this has the same effect.

File: libsolidity/formal/SMTEncoder.cpp (hunk 3 above)
Comment (chriseth) [reply libsolidity/formal/SMTEncoder.cpp]: Because all these functions are library functions due to the check in line 3163

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: true, changed

**Review by chriseth — APPROVED** [review]
