### PR TITLE
[SMTChecker] Fix ICE when reporting cex

### LINKED ISSUE #7168: [SMTChecker] Scanner from different source ICE
From https://github.com/ethereum/solidity/issues/7011

Two files:
```
// base.sol 
contract Base {
	uint x;
	address a;
	function g() internal returns (uint) {
		a = address(this);
		return 2;
	}
}
```
```
pragma experimental SMTChecker;

import 'base.sol';

contract Der is Base {
	function f(uint y) public {
		x += g();
	}
}
```
The bug here is that it gets a model for `this` which is an UF, but the scanner has another source (because it's in a different file).

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #7168 

Since `SourceLocation` now also has `CharStream` we don't need a `Scanner` to print the source code.

### CODE REVIEW

**Comment by chriseth** [comment]
Build fails.

File: liblangutil/SourceLocation.h [hunk 1]
```diff
@@ -49,6 +51,14 @@ struct SourceLocation
 
 	bool isEmpty() const { return start == -1 && end == -1; }
 
+	std::string text() const
+	{
+		struct SourceLocationError: virtual dev::Exception {};
```
Comment (chriseth) [inline liblangutil/SourceLocation.h]: What use is an exception class that is not visible?

Comment (leonardoalt) [reply liblangutil/SourceLocation.h]: I was actually thinking whether we actually need a new one. Wouldn't `dev::Exception` suffice here?

Comment (chriseth) [reply liblangutil/SourceLocation.h]: I think it is always good to be more specific.

**Comment by leonardoalt** [comment]
Updated

File: liblangutil/SourceLocation.h [hunk 2]
```diff
@@ -49,6 +52,13 @@ struct SourceLocation
 
 	bool isEmpty() const { return start == -1 && end == -1; }
 
+	std::string text() const
+	{
+		assertThrow(source, SourceLocationError, "Requested text from null source.");
+		assertThrow(!isEmpty(), SourceLocationError, "Requested text from empty source location.");
+		return source->source().substr(start, end - start);
```
Comment (ekpyron) [inline liblangutil/SourceLocation.h:61]: Should we assert that ``start <= end`` and ``end <= source->source().length()`` or is that overly paranoid :-)?

**Review by ekpyron — COMMENTED** [review]
Minor comment - looks fine generally.

File: liblangutil/SourceLocation.h (hunk 2 above)
Comment (erak) [reply liblangutil/SourceLocation.h:61]: It's paranoid, but doesn't hurt ;) What would the message be? Something like `Requested text from an invalid source location.`?

Comment (ekpyron) [reply liblangutil/SourceLocation.h:61]: Or just invalid source location?

Comment (leonardoalt) [reply liblangutil/SourceLocation.h:61]: updated

**Comment by leonardoalt** [comment]
Rebased

File: Changelog.md [hunk 3]
```diff
@@ -27,7 +27,11 @@ Bugfixes:
  * SMTChecker: Fix pointer knowledge erasing in loops.
  * SMTChecker: Fix internal error when using compound bitwise assignment operators inside branches.
  * SMTChecker: Fix internal error when inlining a function that returns a tuple containing an unsupported type inside a branch.
+<<<<<<< HEAD
```
Comment (ekpyron) [inline Changelog.md]: ... :-)

Comment (leonardoalt) [reply Changelog.md]: oh, fixed ;)

**Review by ekpyron — APPROVED** [review]
It might be able to use this simpler method of getting the text of source locations elsewhere as well... in any case: this PR looks good to me now!
