### PR TITLE
Fix weird Optimizer Emscripten Bug

### LINKED ISSUE #4162: Gas estimation regression between solc 0.4.21 and solc 0.4.22
**Which version of Solidity I am using:**
0.4.22, 0.4.23 or 0.4.24.

**What was the source code:**
This contract, coming from [Solidity Read The Doc](https://solidity.readthedocs.io/en/v0.4.24/introduction-to-smart-contracts.html):

```
pragma solidity ^0.4.0;

contract SimpleStorage {
    uint storedData;

    function set(uint x) public {
        storedData = x;
    }

    function get() public view returns (uint) {
        return storedData;
    }
}
```

**Platform:**
Remix IDE.

**How to reproduce the issue:**
Use Remix, copy the above contract code.
Select solc 0.4.22, or solc 0.4.23, or solc 0.4.24 and build.

**Result of the issue:**
These following warning messages are present:
> Gas requirement of function SimpleStorage.get() high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage).

> Gas requirement of function SimpleStorage.set(uint256) high: infinite. If the gas requirement of a function is higher than the block gas limit, it cannot be executed. Please avoid loops in your functions or actions that modify large areas of storage (this includes clearing or copying arrays in storage).

**Expected behaviour:**
No warning message, as with solc 0.4.21.

**Additionnal information:**
This issue is not the same than #3779 (which was already present with socl 0.4.19, and the present issue appears only with solc 0.4.22).

More precisely, this regression appeared between **solc 0.4.22-nightly.2018.4.11** and  **solc 0.4.22-nightly.2018.4.12**

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes: https://github.com/ethereum/solidity/issues/4162

Opening this PR to have circle generate ``soljson.js`` to verify that this change indeed fixes the optimizer emscripten bug reported for Archlinux's ``chromium 67.0.3396.99``.

In any case, this "solution" won't help too much, since we won't be able to tell, when this might happen again after adding more rules or whether it's still happening for other browsers, etc...

It's probably some kind of stack size issue, but we'll have to find out exactly which limitation is violated in which way to properly deal with this.

### CODE REVIEW

**Comment by ekpyron** [comment]
Indeed, the generated ``soljson.js`` works for me in ``chromium 67.0.3396.99``, as well as in ``chrome 69.0.3497.92``.

**Comment by ekpyron** [comment]
I tried a number of different emscripten settings, but none seem to change the behaviour without this change (stack size seems to be irrelevant; stack overflow checking and assertions don't seem to detect this problem; etc.).

**Comment by ekpyron** [comment]
Observation:
I manually "traced" the call leading to the construction of ``static Rules rules;``:

```
StandardCompiler::compileInternal()
CompilerStack::compile()
CompilerStack::compileContract()
Compiler::compileContract()
CompilerContext::optimise()
Assembly::optimise(bool, EVMVersion, bool, size_t)
Assembly::optimise(OptimiserSettings const&)
Assembly::optimiseInternal()
Assembly::optimiseInternal()
CommonSubexpressionEliminator::feedItems()
CommonSubexpressionEliminator::feedItem()
KnownState::feedItem()
KnownState::feedItem() type != Operation
KnownState::feedItem() !_item.pushedValue()
ExpressionClasses::find() Before tryToSimplify
ExpressionClasses::tryToSimplify: Before 'static Rules rules;'
Rules::Rules()
```

Execution never continues from there. However, after that I can see that remix calls ``StandardCompiler::compileInternal()`` again - and in this run the static Rules object is not initialized again, so the rule list remains empty.

EDIT: I'm talking about the case without the change in this PR.

**Comment by ekpyron** [comment]
Another observation:
Defining the ``Rules rules;`` object as a global variable, instead of statically inside a function, I get ``Unknown exception during compilation`` in remix and the following error in the javascript console:

Uncaught RangeError: Maximum call stack size exceeded
    at Object.dlb [as dynCall_viiiiii] (soljson.js:5)
    at invoke_viiiiii (soljson.js:1)
    at Uva (soljson.js:16)
    at Lta (soljson.js:16)
    at func (soljson.js:1)
    at callRuntimeCallbacks (soljson.js:1)
    at ensureInitRuntime (soljson.js:1)
    at doRun (soljson.js:23)
    at run (soljson.js:23)
    at soljson.js:23

**Comment by ekpyron** [comment]
So my conclusion for the moment would be that (1) we should properly refactor ``simplificationRuleList`` with stack size in mind, since that's the cause of this particular problem, and (2) we should investigate why apparently a crashing or stuck or in any case not-properly-returning call of the standard compiler in ``soljson.js`` is not detected and reported e.g. in remix and instead the standard compiler is just called a second time while being in a non-sane state.

**Comment by axic** [comment]
> we should investigate why apparently a crashing or stuck or in any case not-properly-returning call of the standard compiler in soljson.js is not detected and reported e.g. in remix and instead the standard compiler is just called a second time while being in a non-sane state.

So that is not a stack overflow in the C++ code, but the JS optimiser.

I have mentioned last week that apparently Remix/Play did this, catching exceptions and running it again, because that "apparently made it to work".

**Comment by ekpyron** [comment]
Ah, ok - then if remix is changed back to actually expose such exceptions, we could for now just go with a fix like in this PR - if we can detect stuff like this in the future it's probably not too bad...

**Comment by chriseth** [comment]
This is interesting, thanks a lot! So it seems that `soljson` is treated as a fixed binary in memory that is only initialized once - this is also something we should keep in mind all the time.

File: libevmasm/RuleList.h [hunk 1]
```diff
@@ -162,6 +160,25 @@ std::vector<SimplificationRule<Pattern>> simplificationRuleList(
...
+	Pattern C,
+	Pattern X,
+	Pattern Y
+)
+{
+	std::vector<SimplificationRule<Pattern>> rules;
+
+	rules += simplificationRuleListPart1(A, B, C, X, Y);
 
 	// Replace MOD X, <power-of-two> with AND X, <power-of-two> - 1
```
Comment (chriseth) [inline libevmasm/RuleList.h]: Just for clarity, perhaps split out the rest of this function into `..Part2` and then call only `...Part1` and `...Part2` here?

**Review by chriseth — CHANGES_REQUESTED** [review]
Please add an assertion after the point where the static `Rules` variable is (there should be two of them, another one is in the yul part!) to check that the number of rules is large enough, then we should be safe here.

**Comment by chriseth** [comment]
Updated.

**Review by chriseth — DISMISSED** [review]

**Comment by serapath** [comment]
yay - that is the issue i ran into while working on `play` and i was talking with @axic during ETHberlin.
I spend 2 weeks trying to figure out what I'm doing wrong, because this issue did not show up on remix.

But now I know ...it DOES show up on remix and remix-alpha ...since forever :-)
It's just, that the compiler runs once when the page loads and it swallows that initial error.

Here is how you reproduce it:
**[how to reproduce - video](https://files.gitter.im/ethereum/remix-dev/DqNJ/Sep-17-2018-4_33-PM.webm)**



---
For now I will just swallow the error and move on, because that seems to be what works for remix for a long time already, so it's good enough and i can finally stop pulling my hair :-)

But yeah - i guess it would be nice if that was somehow fixed

File: libevmasm/SimplificationRules.cpp [hunk 2]
```diff
@@ -82,6 +85,7 @@ Rules::Rules()
 	Y.setMatchGroup(5, m_matchGroups);
 
 	addRules(simplificationRuleList(A, B, C, X, Y));
+	assertThrow(!m_rules[byte(Instruction::ADD)].empty(), OptimizerException, "Rule list not properly initialized.");
```
Comment (ekpyron) [inline libevmasm/SimplificationRules.cpp]: Yeah, well - these assertions won't help - no "sane" code path will lead here with empty rules and in the error case execution will abort/throw/whatever before ever reaching this... but it doesn't hurt either I gues.

**Review by ekpyron — COMMENTED** [review]
I'm fine with merging the updated version!

File: libevmasm/SimplificationRules.cpp (hunk 2 above)
Comment (ekpyron) [reply libevmasm/SimplificationRules.cpp]: Ah ok - in a potential second run with the same, resp. a failed static initialization, this will still throw. That makes sense.

Comment (chriseth) [reply libevmasm/SimplificationRules.cpp]: I'm still not so sure. Perhaps the test should rather be after the declaration of the static variables. I think I'll add another check just to be sure.

**Comment by chriseth** [comment]
This is reported to work.

File: libevmasm/ExpressionClasses.cpp [hunk 3]
```diff
@@ -184,6 +184,7 @@ string ExpressionClasses::fullDAGToString(ExpressionClasses::Id _id) const
 ExpressionClasses::Id ExpressionClasses::tryToSimplify(Expression const& _expr)
 {
 	static Rules rules;
+	assertThrow(rules.isInitialized(), OptimizerException, "Rule list not properly initialized.");
```
Comment (axic) [inline libevmasm/ExpressionClasses.cpp:187]: Is this really needed if in the `Rules` constructor this is done? Or due to the stack overflow it was ignored? Perhaps we should leave a comment here for the future, to clarify it.

Comment (chriseth) [reply libevmasm/ExpressionClasses.cpp:187]: It shouldn't but better safe than sorry.
