### PR TITLE
[ewasm] Fix infinite loops.

### LINKED ISSUE #9205: [Yul -> Ewasm] Code generator produces infinite loops
## Description
Yul->Wasm translation produces `for` loops that repeat the initialization code in every iteration. The effect is an infinite loop.

From Yul code like this:
```yul
for { <init> } <condition> { <increment> }
{
    <body>
}
```
we get wasm like this:
```wasm
(loop $loop_label
    <init>
    <condition>
    <body>
    <increment>
    (br $loop_label)
)
```
This is wrong because jumping to `loop_label` repeats the `<init>` block in each iteration. 

## Environment
- Compiler version: `develop` (>= 0.6.10)

## Steps to Reproduce
- Check out `evmc-vms-evm-ewasm` branch from #9143 which allows you to execute wasm tests on [hera](https://github.com/ewasm/hera).
- Build `soltest`
- Put this example in `test/libsolidity/semanticTests/tmp/test.sol`
    ```solidity
    contract test {
        function f(uint x) public pure returns(uint r) {
            for (uint i = 0; i < 5; i++)
            {
                for (uint j = 0; j < 5; j++)
                {
                    x++;
                }
            }
            return x;
        }
    }
    // ====
    // compileToEwasm: also
    // compileViaYul: true
    // ----
    // f(uint256): 0 -> 0x19
    ```
- Run `soltest`:
    ```bash
    soltest --run_test=semanticTests/tmp/* -- --vm <path-to-evmone>/libevmone.so --vm <path-to-hera>/libhera.so —evm-version=byzantium --no-smt --show-messages
    ```
- It hangs.

The test hangs.

### PR DESCRIPTION
**Pull request by aarlt**
Fixes #9205.

### CODE REVIEW

File: libyul/backends/wasm/WasmCodeTransform.cpp [hunk 1]
```diff
@@ -265,7 +264,10 @@ wasm::Expression WasmCodeTransform::operator()(ForLoop const& _for)
 	loop.statements += visit(_for.post.statements);
 	loop.statements.emplace_back(wasm::Branch{wasm::Label{loop.labelName}});
 
-	return { wasm::Block{breakLabel, make_vector<wasm::Expression>(move(loop))} };
+	std::vector<wasm::Expression> result;
+	result += visit(_for.pre.statements);
```
Comment (chriseth) [inline libyul/backends/wasm/WasmCodeTransform.cpp]: Can you avoid wrapping it in another expression if pre.statements is empty?

File: libyul/backends/wasm/WasmCodeTransform.cpp [hunk 2]
```diff
@@ -265,7 +264,10 @@ wasm::Expression WasmCodeTransform::operator()(ForLoop const& _for)
...
+	result += make_vector<wasm::Expression>(move(loop));
+	return { wasm::Block{breakLabel, move(result)} };
```
Comment (cameel) [inline libyul/backends/wasm/WasmCodeTransform.cpp]: The brace is not really necessary. `Block` gets implicitly converted to `wasm::Expression` (which is a `variant`).
```suggestion
	return wasm::Block{breakLabel, move(result)};
```

**Comment by axic** [comment]
Mention in the changelog?

**Comment by cameel** [comment]
Isn't wasm support still an experimental feature? I think we don't add changelog entries for these. Or is the policy different in case of bugfixes?

File: libyul/backends/wasm/WasmCodeTransform.cpp [hunk 3]
```diff
@@ -269,7 +268,13 @@ wasm::Expression WasmCodeTransform::operator()(ForLoop const& _for)
...
 	loop.statements.emplace_back(wasm::Branch{wasm::Label{loop.labelName}});
 
-	return { wasm::Block{breakLabel, make_vector<wasm::Expression>(move(loop))} };
+	if (_for.pre.statements.empty())
+		return wasm::Block{breakLabel, make_vector<wasm::Expression>(move(loop))};
+
+	std::vector<wasm::Expression> result;
+	result += visit(_for.pre.statements);
+	result += make_vector<wasm::Expression>(move(loop));
+	return wasm::Block{breakLabel, move(result)};
```
Comment (chriseth) [inline libyul/backends/wasm/WasmCodeTransform.cpp]: Isn't this equivalent to
```suggestion
	return wasm::Block{breakLabel, visit(_for.pre.statements) + make_vector<wasm::Expression>(move(loop))};
```
?

But could you try to move the `visit(_for.pre.statemenst)` to the front again, so that it is visited before the loop? It should not make a difference, but I think it's better to be safe than sorry.

Comment (aarlt) [reply libyul/backends/wasm/WasmCodeTransform.cpp]: Sadly `return wasm::Block{breakLabel, visit(_for.pre.statements) + make_vector<wasm::Expression>(move(loop))};` is not working because `std::variant` doesn't provide a copy constructor. I think then the previous solution was then nicer.

Comment (chriseth) [reply libyul/backends/wasm/WasmCodeTransform.cpp]: Can you please still find a solution that
 - visits the pre statements before everything else
 - reduces code duplication

Comment (aarlt) [reply libyul/backends/wasm/WasmCodeTransform.cpp]: yes, sure

**Review by chriseth — APPROVED** [review]
