### PR TITLE
Fix uncaught exception when using empty string for yul optimization flags

### LINKED ISSUE #14946: Providing an empty string to `--yul-optimizations` without enabling yul optimization triggers uncaught exception
## Description

This is a edge case in command-line arg parsing related to assembly optimization flags: Providing the empty string or a string containing only whitespace to `--yul-optimizations` triggers an uncaught exception. 

## Environment

- Compiler version: 0.8.23 - 0.8.26-develop.2024.3.15+commit.33e33241.mod.Linux.g++
- Target EVM version (as per compiler settings): Default.
- Framework/IDE (e.g. Truffle or Remix): None, triggered on the command-line
- EVM execution environment / backend / blockchain client: None.
- Operating system: Linux

Not present in 0.8.22, most likely due to the change in command-line parsing introduced in #14657.

## Steps to Reproduce

Executing either (example Yul provided below):
```
solc --strict-assembly --yul-optimizations " " simple.yul
```
or
```
solc --strict-assembly --yul-optimizations "" simple.yul
```

Triggers the exception:
```
Uncaught exception:
/solidity/libyul/YulStack.cpp(179): Throw in function solidity::yul::YulStack::optimize(solidity::yul::Object&, bool)::<lambda()>
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what: Yul assertion failed
[solidity::util::tag_comment*] = Yul assertion failed
```

Contrarily:
```
solc --strict-assembly --yul-optimizations ":" simple.yul
```
outputs unoptimized bytecode, as expected:

```
======= simple.yul (EVM) =======

Pretty printed source:
object "object" {
    code {
        {
            sstore(0, f(1, 2))
            return(0, 32)
        }
        function f(a, b) -> c
        { c := add(a, b) }
    }
}


Binary representation:
6009600260016010565b5f5560205ff35b019056

Text representation:
    /* "simple.yul":145:152   */
  tag_2
    /* "simple.yul":150:151   */
  0x02
    /* "simple.yul":147:148   */
  0x01
    /* "simple.yul":145:152   */
  tag_1
  jump	// in
tag_2:
    /* "simple.yul":142:143   */
  0x00
    /* "simple.yul":135:153   */
  sstore
    /* "simple.yul":182:184   */
  0x20
    /* "simple.yul":179:180   */
  0x00
    /* "simple.yul":172:185   */
  return
    /* "simple.yul":35:115   */
tag_1:
    /* "simple.yul":86:95   */
  add
    /* "simple.yul":35:115   */
  swap1
  jump	// out
```

If the `--optimize` flag is added, the behavior is also as expected:
```
solc --strict-assembly --optimize --yul-optimizations "" simple.yul
```
which outputs the optimized bytecode.

Here's the contents of `simple.yul` used above, but this issue should be triggered regardless of input:
```
{
    function f(a, b) -> c {
        c := add(a, b)
    }

    sstore(0, f(1, 2))
    return(0, 32)
}
```

### PR DESCRIPTION
**Pull request by matheusaaguiar**
fix #14946.

### CODE REVIEW

File: libyul/optimiser/Suite.cpp [hunk 1]
```diff
@@ -399,7 +399,7 @@ bool OptimiserSuite::isEmptyOptimizerSequence(std::string const& _sequence)
 		default:
 			return false;
 		}
-	return true;
+	return delimiterCount == 1;
```
Comment (nikola-matic) [inline libyul/optimiser/Suite.cpp]: This is fine, but I remember @ekpyron mentioning that we don't really even need this - i.e. checking for whitespace and newlines, as well as the number of semicolons, but rather to simply check if a semicolon delimiter is present in the sequence, and return true if yes, which should then fail later during validation if the sequence is malformed. [Here's](https://github.com/ethereum/solidity/pull/14657#discussion_r1383233923) the comment. Although even there he says he's fine with leaving it as is, so no biggie.

**Review by nikola-matic — COMMENTED** [review]
Bugfixes need changlog entries :)

File: libyul/optimiser/Suite.cpp (hunk 1 above)
Comment (r0qs) [reply libyul/optimiser/Suite.cpp]: Not sure if I follow, do you mean just this?
```c++
bool OptimiserSuite::isEmptyOptimizerSequence(std::string const& _sequence)
{
	return _sequence.find(':') != std::string::npos;
}
```
Wouldn't this return the wrong result if you have something like: `"u:"`?

Comment (nikola-matic) [reply libyul/optimiser/Suite.cpp]: No, more like what Daniel mentioned in the above comment (I guess we'd still need to check for white space and newlines:
```c++
return !ranges::any_of(_sequence, [](auto _step) { return _step != ':' && _step != ' ' && _step != '\n'; });
```

Comment (matheusaaguiar) [reply libyul/optimiser/Suite.cpp]: AFAIU, when the empty string (or blank spaces only) is input, then the original code (or Daniel's suggested refactor) returns `true`, but the empty string means **no optimizer steps and the default cleanup sequence**. If we want to test if a string is the empty optimizer sequence (both steps and cleanup empty), i.e, `:`, we must ensure that (at least) one colon appears.

**Comment by matheusaaguiar** [comment]
I am wondering whether we should have a better error message for this case. Although the docs explain what should be an empty optimizer sequence, it can be a bit confusing. Or in other words, it is understandable mistake to think that an empty or blank string is the same as the empty sequence.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `d1215b1a946347b3b5bcda3f0f684cb17e093704`:
```
Error: Trailing whitespace found:
Changelog.md:12: 

```
Please check that your changes are working as intended.

**Review by nikola-matic — COMMENTED** [review]
Can you add CLI tests as well?

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `75c147cc70973b7acebe2072480349b442093d6c`:
```
Error: Trailing whitespace found:
Changelog.md:12: 

```
Please check that your changes are working as intended.

File: test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args [hunk 2]
```diff
@@ -0,0 +1,2 @@
+--via-ir --yul-optimizations " "
```
Comment (matheusaaguiar) [inline test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: @nikola-matic, tried to add a CLI test, but can't find a way to input empty/blank string. In this case, it gets the `"` as the value. I've tried to escape with `\"`, but that doesn't work.
Maybe @r0qs knows how to do this?

Comment (nikola-matic) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: Not sure I understand - it looks like it's issuing the appropriate error, no? 
```
Error: --yul-optimizations is invalid with a non-empty sequence if Yul optimizer is disabled.
```

File: libsolidity/interface/StandardCompiler.cpp [hunk 3]
```diff
@@ -463,9 +463,15 @@ std::optional<Json::Value> checkOptimizerDetailSteps(Json::Value const& _details
 	{
 		if (_details[_name].isString())
 		{
-			std::string const fullSequence = _details[_name].asString();
+			std::string fullSequence = _details[_name].asString();
+			boost::trim(fullSequence);
```
Comment (nikola-matic) [inline libsolidity/interface/StandardCompiler.cpp]: ~~You're trimming the string here (removing whitespace), but not doing so in the command line parser, which is why your check for an empty sequence string is failing (when supplying `"  "`)~~. You can trim the string in `OptimiserSuite::isEmptyOptimizerSequence(std::string)` and remove the whitespace check from it. In that case you shouldn't need to check for an empty optimizer sequence (as in `.empty()`), and can just attach the note by to the error message every time.

File: test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args (hunk 2 above)
Comment (nikola-matic) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: Yeah, it's not appending the `Note` portion, which is super weird. When running solc with the same params, it works just fine, and the sequence is fully trimmed and thus empty in the debugger. Not really sure what's going on here.

Comment (nikola-matic) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: Could be a weird bash bug in the cmdline script.

Comment (nikola-matic) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: Yeah, it's `cmdlineTests.sh` - this is what it runs:
```
solc --via-ir --yul-optimizations '"' '"' yul_optimizer_steps_without_optimize_blank_string/input.sol
```
which then obviously causes the optimization sequence to not be empty empty.

Comment (cameel) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: It's not a Bash bug. It's that an `args` file is intentionally interpreted by `cmdlineTests.sh` as a simple list of space-separated arguments. It does not support anything fancy, like quoting. Its content is not executed as a Bash command so things like `>`, `|` or variables will not work either. And I think it's better off like this. Support for values with spaces would be nice, but we don't want to bring in all of those other things.

Just make it a Boost test in `test/solc/CommandLineInterface.cpp`.

Comment (nikola-matic) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: Yeah, CLI boost test will work just as well, although I thought our long term strategy was to move away from boost tests wherever possible.

> It does not support anything fancy, like quoting.

I wouldn't really consider quoting fancy, especially in terms of CLI tests, but I do agree it would be annoying to introduce this into our current cmdline tests.

File: test/solc/CommandLineInterface.cpp [hunk 4]
```diff
@@ -241,6 +241,54 @@ BOOST_AUTO_TEST_CASE(cli_input)
 	BOOST_CHECK_EQUAL(result.reader.allowedDirectories(), expectedAllowedPaths);
 }
 
+BOOST_AUTO_TEST_CASE(cli_optimizer_disabled_yul_optimization_input_blank_spaces)
+{
+	TemporaryDirectory tempDir(TEST_CASE_NAME);
+	createFilesWithParentDirs({tempDir.path() / "input.sol"});
+
+	std::string const expectedMessage =
```
Comment (stackenbotten) [inline test/solc/CommandLineInterface.cpp:249]: Coding style error

File: test/solc/CommandLineInterface.cpp [hunk 5]
```diff
@@ -241,6 +241,54 @@ BOOST_AUTO_TEST_CASE(cli_input)
...
+		[&](auto const& _exception) { BOOST_TEST(_exception.what() == expectedMessage); return true; }
+	);
+}
+
+BOOST_AUTO_TEST_CASE(cli_optimizer_disabled_yul_optimization_input_empty)
+{
+	TemporaryDirectory tempDir(TEST_CASE_NAME);
+	createFilesWithParentDirs({tempDir.path() / "input.sol"});
+
+	std::string const expectedMessage =
```
Comment (stackenbotten) [inline test/solc/CommandLineInterface.cpp:273]: Coding style error

File: libsolidity/interface/StandardCompiler.cpp (hunk 3 above)
Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: I agree with moving the trim inside `OptimiserSuite::isEmptyOptimizerSequence(std::string)`.
However, I think that the `empty()` check is needed still. For example, if the input is `u:`, it is not an empty optimizer sequence and so it should raise the error with the first part of the message, but not with the hint about the empty/blank string.

Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: > I agree with moving the trim inside `OptimiserSuite::isEmptyOptimizerSequence(std::string)`.

Although now I am not sure of that... since I think that we need to check for the empty and blank spaces cases. For this latter case, I used the trim before the `empty()` check, so both cases collapsed to just one.

File: test/solc/CommandLineInterface.cpp [hunk 6]
```diff
@@ -241,6 +241,54 @@ BOOST_AUTO_TEST_CASE(cli_input)
...
+		"--yul-optimizations is invalid with a non-empty sequence if Yul optimizer is disabled."
+		" Note that if an empty or blank string is supplied, the default cleanup sequence is used. The empty sequence is properly denoted by \":\"."
+	;
+	std::string const blankInput = "   ";
+
+	BOOST_CHECK_EXCEPTION(
+		parseCommandLineAndReadInputFiles({
+			"solc",
+			"--strict-assembly",
```
Comment (nikola-matic) [inline test/solc/CommandLineInterface.cpp]:
```suggestion
```

File: test/solc/CommandLineInterface.cpp [hunk 7]
```diff
@@ -241,6 +241,54 @@ BOOST_AUTO_TEST_CASE(cli_input)
...
+	std::string const expectedMessage =
+		"--yul-optimizations is invalid with a non-empty sequence if Yul optimizer is disabled."
+		" Note that if an empty or blank string is supplied, the default cleanup sequence is used. The empty sequence is properly denoted by \":\"."
+	;
+	std::string const emptyInput;
+
+	BOOST_CHECK_EXCEPTION(
+		parseCommandLineAndReadInputFiles({
+			"solc",
+			"--strict-assembly",
```
Comment (nikola-matic) [inline test/solc/CommandLineInterface.cpp]:
```suggestion
```

File: libsolidity/interface/StandardCompiler.cpp [hunk 8]
```diff
@@ -463,9 +463,18 @@ std::optional<Json::Value> checkOptimizerDetailSteps(Json::Value const& _details
...
 			if (!_runYulOptimizer && !OptimiserSuite::isEmptyOptimizerSequence(fullSequence))
-				return formatFatalError(Error::Type::JSONError, "If Yul optimizer is disabled, only an empty optimizerSteps sequence is accepted.");
+			{
+				std::string errorMessage = "If Yul optimizer is disabled, only an empty optimizerSteps sequence is accepted.";
+				if (fullSequence.empty())
+					errorMessage +=
+						" Note that if an empty or blank string is supplied, the default cleanup sequence is used."
+						" The empty sequence is properly denoted by \":\"."
+					;
```
Comment (nikola-matic) [inline libsolidity/interface/StandardCompiler.cpp]: Now that I think about it - this is kinda unnecessary; `isEmptyOptimizerSequence` will return `false` even with whitespace only sequences - so to reduce complexity, it might just make more sense to alter the original message to include `The empty sequence is properly denoted by \":\".`. i.e.
```
If Yul optimizer is disabled, only an empty optimizerSteps sequence is accepted. The empty sequence is properly denoted by \":\".
```

The actual bugfix is basically this `return delimiterCount == 1;`, so no need to over complicate it with the message.

**Review by nikola-matic — COMMENTED** [review]
Also, please add a short line to describe what an empty optimizer sequence is (:) [here](https://github.com/ethereum/solidity/blob/develop/docs/internals/optimizer.rst?plain=1#L49).

File: libsolidity/interface/StandardCompiler.cpp (hunk 8 above)
Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: I don't think this is over-complicated. This is just an additional test to insert a hint in the error message. I usually don't care about these details, but feels like a defeat to just quit this after we spent some time to get it right (mostly the CLI test tbh).
We can rewrite to make more explicit the white spaces part, maybe something like: `Note that if an empty or whitespace only string...`. I thought that "blank string" would convey that meaning.

Comment (nikola-matic) [reply libsolidity/interface/StandardCompiler.cpp]: Also, `Note that if an empty or blank string is supplied, the default cleanup sequence is used.` is technically wrong in this context , since this is part of the error that would be triggered if you were to provide an empty/blank string if the optimizer is disabled, so the default sequence would not be used, since the contract(s) would not compile.

So yeah, maybe better to rephrase it into something like
```
Note that an empty optimizer sequence is is properly denoted by \":\".
```

Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: I see your point. 
What happens is that, when the string is empty, it is assumed that the default cleanup sequence is selected for use, regardless of the optimizer being enabled. The problem fixed by this PR was caused exactly by that.
So maybe, rephrasing to `Note that if an empty or blank string is supplied, the default cleanup sequence is selected/assumed.` would clarify and make it coherent with the context?

Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: But whatever, I think we spent too much time on this already. 
I'll just add the hint by default.

Comment (nikola-matic) [reply libsolidity/interface/StandardCompiler.cpp]: >  What happens is that, when the string is empty, it is assumed that the default cleanup sequence is selected for use, regardless of the optimizer being enabled. The problem fixed by this PR was caused exactly by that.

But this hint will only be shown if the optimizer is disabled right? It's in the 
```
if (!_runYulOptimizer && !OptimiserSuite::isEmptyOptimizerSequence(fullSequence))
```
block.

In any case, don't bother reverting the changes to include the note everywhere, I might be wrong. @cameel can you take a look?

Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: Yes, the error message (and the hint) only shows when the optimizer is disabled.
I think the hint would be helpful because the empty/blank string can be confused with the empty optimizer sequence.
But I am fine with it just being appended even if the input is not the empty/blank string. The check would just make it be more specific to that case.

File: libyul/optimiser/Suite.cpp (hunk 1 above)
Comment (cameel) [reply libyul/optimiser/Suite.cpp]: Yes, we definitely do need to handle the case of zero colons specially, since that's the core part of the fix. But we could still combine this with @nikola-matic's suggestion. Just not using the original one-liner alone. We'd need to add a separate check for the number of colons in the sequence before it.

It would make code a bit nicer, but it's not essential to the fix though. It would also change the error message in the case of more than one colon, which would warrant at least putting it at least in a separate commit, rather than mixing it in with the fix. Now that we shipped that original PR, changing it is a user visible change (though a trivial one that does not need a changelog entry).

File: libsolidity/interface/StandardCompiler.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/interface/StandardCompiler.cpp]: `trim()` should not be necessary here. Everything, including `isEmptyOptimizerSequence()`, validation and the functions executing the sequence can already handle whitespace in the sequence. It will actually affect metadata if you do it here.

I mean, having it trimmed in the metadata might actually be a good thing, but it's unrelated to the fix. I'd suggest submitting a separate PR to give this change more visibility.

If it's just for the purpose of the `empty()` check below, do it on a copy of the value. Or use a more robust check, e.g.:

```c++
if (ranges::all_of(fullSequence, [](char _s) { return _s == ' ' || _s == '\n'; }))
```

File: libsolidity/interface/StandardCompiler.cpp (hunk 8 above)
Comment (cameel) [reply libsolidity/interface/StandardCompiler.cpp]: Well, having the extra hint is nice since I also think most users will be confused by the difference between an empty string and an empty sequence.

But it does add some redundancy - the check yet again has to make some assumptions about the sequence (e.g. which characters count as whitespace). Honestly, this is trivial enough that I don't particularly mind it if you think it makes things better, but consider whether just always including it the default message wouldn't be a good compromise:

```
If Yul optimizer is disabled, only an empty optimizerSteps sequence is accepted.
Note that an empty sequence is properly denoted by ":".
```

In the current message I'm not sure if the difference between "empty" and "blank" is all that clear.

File: test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_no_yul_blank_spaces/input.json [hunk 9]
```diff
@@ -0,0 +1,20 @@
...
+                "
+            }
+    },
+    "settings": {
+        "optimizer": {
+            "details": {
+                "yul": false,
+                    "yulDetails": {
+                        "optimizerSteps": " "
+                    }
```
Comment (cameel) [inline test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_no_yul_blank_spaces/input.json]: This is formatted in a misleading way. There's no nesting here, but at a glance it looks as if there was.
```suggestion
                "yul": false,
                "yulDetails": {
                    "optimizerSteps": " "
                }
```

File: test/solc/CommandLineInterface.cpp (hunk 6 above)
Comment (cameel) [reply test/solc/CommandLineInterface.cpp]: It would actually not hurt to test both as long as it can be done concisely, e.g. by looping over
```c++
{
    ["--strict-assembly", "--yul-optimizations="],
    ["--strict-assembly", "--yul-optimizations=    "],
    ["--yul-optimizations="],
    ["--yul-optimizations=    "],
}
```
which would be used to construct the command. Both assembling and compilation go through the same path in command-line parser now, but it's not guaranteed that it will always be like this and the issue affects both.

I'd say it's optional, but @nikola-matic has a point that currently you're assembling with input file called `input.sol`.

File: test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args (hunk 2 above)
Comment (cameel) [reply test/cmdlineTests/yul_optimizer_steps_without_optimize_blank_string/args]: > Yeah, CLI boost test will work just as well, although I thought our long term strategy was to move away from boost tests wherever possible.

Boost tests are not going anywhere any time soon. CLI tests are too crude for some things and we also can't spend time improving them so for the foreseeable future you're free to choose whichever is appropriate.

> I wouldn't really consider quoting fancy, especially in terms of CLI tests, but I do agree it would be annoying to introduce this into our current cmdline tests.

Full Bash-compatible quoting is pretty complex. And something that looks like Bash quoting but acts differently is dangerous because everyone would just assume it works like Bash.

File: libsolidity/interface/StandardCompiler.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/interface/StandardCompiler.cpp]: By the way, note that the corresponding change in `CommandLineParser` does *not* modify metadata because there you use a fresh variable for the string that gets trimmed.

This inconsistency should have come up in tests so apparently we don't have any covering this. I think we should have a test showing how a sequence with whitespace looks when stored in metadata. Actually two, one for for CLI and one for Standard JSON.

File: test/solc/CommandLineInterface.cpp (hunk 6 above)
Comment (matheusaaguiar) [reply test/solc/CommandLineInterface.cpp]: Actually, this should had been `input.yul`. I was testing using the example from the issue.
I will add the variations.

File: libsolidity/interface/StandardCompiler.cpp (hunk 8 above)
Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: Ok. I had already agreed with the hint by default.
After thinking about it also I think it is better that way because it always clarifies what is the empty optimizer sequence.

File: libsolidity/interface/StandardCompiler.cpp (hunk 3 above)
Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: > It will actually affect metadata if you do it here.

Yes. I had not noticed that `fullSequence` becomes part of the metadata.






> This inconsistency should have come up in tests so apparently we don't have any covering this. I think we should have a test showing how a sequence with whitespace looks when stored in metadata. Actually two, one for for CLI and one for Standard JSON.

I will create an issue for that.

File: test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_no_yul_blank_spaces/input.json (hunk 9 above)
Comment (matheusaaguiar) [reply test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_no_yul_blank_spaces/input.json]: Fixed.

File: libsolidity/interface/StandardCompiler.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/interface/StandardCompiler.cpp]: I mean, I'd rather keep is simple so I'm not sure if creating an issue is necessary. I'd just check if, as a part of this PR, you can fit a simple test for this into whatever test suites we already have. If there's no good place for it, it's fine to skip it. It would be helpful here but it's also not *that* important.

Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: Ok, I'll try that.

File: libyul/optimiser/Suite.cpp (hunk 1 above)
Comment (matheusaaguiar) [reply libyul/optimiser/Suite.cpp]: I refactored the function to include both the check of number of colons and the one-liner suggested on the previous PR.

File: libsolidity/interface/StandardCompiler.cpp (hunk 3 above)
Comment (matheusaaguiar) [reply libsolidity/interface/StandardCompiler.cpp]: I added some new tests and extend a few existing ones.

File: test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_empty_sequence_whitespaces_metada/output.json [hunk 10]
```diff
@@ -0,0 +1,19 @@
+{
+    "contracts":
+    {
+        "A":
+        {
+            "C":
+            {
+                "metadata": "{\"compiler\":{\"version\":\"<VERSION REMOVED>\"},\"language\":\"Solidity\",\"output\":{\"abi\":[],\"devdoc\":{\"kind\":\"dev\",\"methods\":{},\"version\":1},\"userdoc\":{\"kind\":\"user\",\"methods\":{},\"version\":1}},\"settings\":{\"compilationTarget\":{\"A\":\"C\"},\"evmVersion\":\"cancun\",\"libraries\":{},\"metadata\":{\"bytecodeHash\":\"ipfs\"},\"optimizer\":{\"details\":{\"constantOptimizer\":false,\"cse\":false,\"deduplicate\":false,\"inliner\":false,\"jumpdestRemover\":true,\"orderLiterals\":false,\"peephole\":true,\"simpleCounterForLoopUncheckedIncrement\":true,\"yul\":false,\"yulDetails\":{\"optimizerSteps\":\":\"}},\"runs\":200},\"remappings\":[]},\"sources\":{\"A\":{\"keccak256\":\"0xb63d3c030f127aecaa7a1e223e41ef58ce5b4404939d397ccfd9ca0eb11d757b\",\"license\":\"GPL-3.0\",\"urls\":[\"bzz-raw://567242af52de5d6870167f16a7f46d7bf27fb2b101cf99fd9ab48c645dfe7ecd\",\"dweb:/ipfs/QmamT3HqCmEbVvWwQiYSfUZRn5XwHRRkEe29BpbEJadxDT\"]}},\"version\":1}"
```
Comment (matheusaaguiar) [inline test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_empty_sequence_whitespaces_metada/output.json]: I noticed here that the metadata was not preserved. The `optimizerSteps` value is just the colon instead of a whitespace before it and two whitespaces after it.
The cause is 
https://github.com/ethereum/solidity/blob/ae9bcabd954c20e9610a3f3fe64e24cbcf153375/libsolidity/interface/CompilerStack.cpp#L1732
being defined if the sequence is the empty optimizer sequence, although we accept whitespaces and linebreaks.

Comment (matheusaaguiar) [reply test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_empty_sequence_whitespaces_metada/output.json]: I fixed that in https://github.com/ethereum/solidity/pull/14967/commits/a455829160c29c730212d9634568faedc2a9eb13.

Comment (cameel) [reply test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_empty_sequence_whitespaces_metada/output.json]: True. But changing it so that this is preserved also technically changes the metadata so I'd keep it out of this PR.

Like I said in https://github.com/ethereum/solidity/pull/14967#discussion_r1551741993, this is fine to do, but I'd rather do any such changes explicitly, in a separate PR. 

Also, I think that the right way to make it consistent is to be always stripping whitespace from the sequence, means we'd leave this bit as is and instead change the rest to match :)

**Review by cameel — COMMENTED** [review]
The only thing that still needs to be addressed is https://github.com/ethereum/solidity/pull/14967#discussion_r1561798536. Other than that there are no big problems and I pushed some fixups to clean up some of the smaller ones without going through extra review rounds.

File: test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_empty_sequence_whitespaces_metada/output.json (hunk 10 above)
Comment (matheusaaguiar) [reply test/cmdlineTests/standard_optimizer_yulDetails_optimiserSteps_empty_sequence_whitespaces_metada/output.json]: Ok, I will separate this commit apart.

**Comment by matheusaaguiar** [comment]
Rebased and squashed commits.

**Review by cameel — DISMISSED** [review]

**Comment by nikola-matic** [comment]
> Also, please add a short line to describe what an empty optimizer sequence is (:) [here](https://github.com/ethereum/solidity/blob/develop/docs/internals/optimizer.rst?plain=1#L49).

Push docs and I'll re-approve so we can merge.

**Comment by matheusaaguiar** [comment]
> > Also, please add a short line to describe what an empty optimizer sequence is (:) [here](https://github.com/ethereum/solidity/blob/develop/docs/internals/optimizer.rst?plain=1#L49).
> 
> Push docs and I'll re-approve so we can merge.

Sorry, I missed that when checking pending comments. Fixed.

**Review by cameel — DISMISSED** [review]

**Review by cameel — APPROVED** [review]
