### PR TITLE
Fixes invalid function calls to literals inside tuple assignment's LHS.

### LINKED ISSUE #5053: Invalid expression causes assertion
```
contract test {
    function f(uint y) { ((((6(((y ^ 8) & 7) | 6) - 5)=+ 4) , 3) /(2) * 1); }
}
```

Error:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/analysis/TypeChecker.cpp(1447): Throw in function void dev::solidity::TypeChecker::checkExpressionAssignment(const dev::solidity::Type &, const dev::solidity::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```
Introduced by #4671.

### PR DESCRIPTION
**Pull request by christianparpart**
### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### Description

This change fixes #5053. I did not adapt the Changelog as this bug was just recently introduced in the 0.5 branch.

FYI: I was first trying to not get a solution via making the typeError into a fatalTypeError, however, I didn't find a clean solution, as every follow-up-change did look more like a workaround, so I decided to go with promoting this error from non-fatal to fatal. I'd however like to have a post-0.5 discussion on when to go fatal and where we wanna change that (I believe we'd need a change in the AST to easily reflect whether some node is in invalid-state due to internal bug vs already-reported-user-bugs).

### CODE REVIEW

**Comment by chriseth** [comment]
Please add the example that uncovered the bug as a test case.

**Comment by chriseth** [comment]
(or of course, the minimal version you found)

**Comment by chriseth** [comment]
I don't think this is the proper fix. Take a look at the following example:
```
contract C {
    function f(uint y) public {
        //(1(y)) = 2;
        (f(2)) = 2;
    }
}
```
I think the failing assertion is just wrong and should be converted to an error. I assume that we only thought of assignments of the type `(a, b) = (c,d)`. Actually I think we should check whether `f() = (c,d)` works as expected, although I'm not sure if the result of a function call can ever be an lvalue...

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1444,8 +1444,7 @@ void TypeChecker::checkExpressionAssignment(Type const& _type, Expression const&
 		auto const* tupleType = dynamic_cast<TupleType const*>(&_type);
 		auto const& types = tupleType ? tupleType->components() : vector<TypePointer> { _type.shared_from_this() };
 
-		solAssert(tupleExpression->components().size() == types.size(), "");
-		for (size_t i = 0; i < types.size(); i++)
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:1448]: Looks good! Please add an assertion about `m_errorReporter.hasErrors()` for safety.

Comment (christianparpart) [reply libsolidity/analysis/TypeChecker.cpp:1448]: Many thanks @chriseth. That's a good one.

Comment (christianparpart) [reply libsolidity/analysis/TypeChecker.cpp:1448]: @chriseth: done.

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -1444,8 +1444,10 @@ void TypeChecker::checkExpressionAssignment(Type const& _type, Expression const&
...
+		solAssert(tupleExpression->components().size() == types.size() || m_errorReporter.hasErrors(),
+			"The array sizes must match or an error must have been already generated.");
```
Comment (erak) [inline libsolidity/analysis/TypeChecker.cpp]: Perhaps turn it into ``Array sizes don't match or no errors generated.``?

**Review by erak — CHANGES_REQUESTED** [review]
This PR is missing a Changelog entry.

File: libsolidity/analysis/TypeChecker.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: Also style: linebreak directly after `(`, every component on a line of its own and `);` on a line of its own.

**Comment by chriseth** [comment]
@bit-shift no changelog entry because nothing was fixed that was broken at the previous release (at least I think...)

File: libsolidity/analysis/TypeChecker.cpp (hunk 2 above)
Comment (christianparpart) [reply libsolidity/analysis/TypeChecker.cpp]: I preferred my original string message, but I am fine with the latter, too. Style fixed.

**Review by chriseth — APPROVED** [review]
