### PR TITLE
Consider fixed-size arrays when checking for recursive structs.

### LINKED ISSUE #4483: Incorrect struct array processing in sol compiler may cause solc stack overflow
Incorrect struct array processing in sol compiler may cause solc stack overflow leading possible local code exec

[struct_array_mem_corruption.zip](https://github.com/ethereum/solidity/files/2184875/struct_array_mem_corruption.zip)

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #4483.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -607,6 +607,12 @@ bool TypeChecker::visit(StructDefinition const& _struct)
 				auto const& typeName = dynamic_cast<UserDefinedTypeName const&>(*member->typeName());
 				check(&dynamic_cast<StructDefinition const&>(*typeName.annotation().referencedDeclaration), parents);
 			}
+			else if (auto arrayType = dynamic_cast<ArrayType const*>(type(*member).get()))
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Oh this is very interesting! We have some kind of duplication in `StructType::recursive()` which also disallows dynamic arrays because the purpose is different. Because of that I guess it is still better to keep both versions, but perhaps this implementation here could be simplified to use `CycleDetector` class?

Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp]: Looking a bit closer at ``StructType::recursive`` I think I forgot to take care about multi-dimensional arrays as well :). But using ``CycleDetector`` makes sense in any case. I'll update and add tests for the multi-dimensional array case.

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: There is no such thing as multi-dimensional arrays. Are you talking about dynamic arrays? In contrast to `::recursive`, they are fine at this point because here, the issue is that we want to check whether the storage size of the struct is finite, which is the case for dynamically-sized arrays that recursively contain the struct itself.

Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp]: To me ``struct S { S[1][1] s; };`` is a multi-dimensional array and this is bad as well - dynamic arrays are fine as in ``struct S { S[][1] s; };``, ``struct S { S[1][] s; };``, ``struct S { S[][] s; };`` as well as ``struct S { S[] s; };`` are all fine.

Comment (ekpyron) [reply libsolidity/analysis/TypeChecker.cpp]: "Arrays of arrays" is what I meant.

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: OK, then I misunderstood you. Sorry!

**Review by chriseth — APPROVED** [review]

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -593,22 +594,24 @@ bool TypeChecker::visit(StructDefinition const& _struct)
...
-		for (ASTPointer<VariableDeclaration> const& member: _struct->members())
-			if (type(*member)->category() == Type::Category::Struct)
+	auto visitor = [&](StructDefinition const& _struct, CycleDetector<StructDefinition>& _cycleDetector)
+	{
+		for (ASTPointer<VariableDeclaration> const& member: _struct.members())
+		{
+			Type const* memberType = type(*member).get();
+			while (auto arrayType = dynamic_cast<ArrayType const*>(memberType))
 			{
-				auto const& typeName = dynamic_cast<UserDefinedTypeName const&>(*member->typeName());
```
Comment (ekpyron) [inline libsolidity/analysis/TypeChecker.cpp:607]: I suppose it's fine to just cast the type instead of going by the way of the type name and the referenced declaration here? I'm not sure why it was done this way before...

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:607]: Yes, I guess it's fine.
