### PR TITLE
Fix duplicate tag assert throw

### LINKED ISSUE #8656: Unexplained "Assembly exception for bytecode"
## Description

We made a small change to our code and noticed that the non-optimized compilation began failing. In particular, a `require()` (with message) statement seemed to be triggering the new failure. Our codebase is fairly large, but [here](https://github.com/UMAprotocol/protocol/tree/solidity_compilation_example) is a branch where the issue is present. In particular, [this new line](https://github.com/UMAprotocol/protocol/blob/e527ca542479e79a593cc249da6eac5c8b1c86d5/core/contracts/oracle/implementation/VoteTiming.sol#L21) seemed to cause the problem. Even more surprising, the compilation begins to succeed again when we removed the require message. I've reproduced this error in a much more minimal example below.

## Environment

- Compiler version: 0.6.6
- Target EVM version (as per compiler settings): default for compiler
- Framework/IDE (e.g. Truffle or Remix): Truffle, but we were able to reproduce the example below in remix as well.
- EVM execution environment / backend / blockchain client: N/A -- this is a compilation failure
- Operating system: Mac OS X 10.15.3

## Steps to Reproduce

Compile the below example with optimization off.

```solidity
pragma solidity ^0.6.0;

pragma experimental ABIEncoderV2;


contract Ownable {
    address private _owner;

    modifier onlyOwner() {
        require(msg.sender == _owner, "Ownable: caller is not the owner");
        _;
    }

    function renounceOwnership() public onlyOwner {
        _owner = address(0);
    }
}


library VoteTiming {
    function init(uint phaseLength) internal pure {
        require(phaseLength > 0, "Phase length can not be zero");
    }
}


contract Voting is Ownable {
    constructor(uint _phaseLength) public {
        VoteTiming.init(_phaseLength);
    }
}
```

Please note that the code above is somewhat nonsensical. It has the ABIEncoderV2 pragma despite not needing it (the code that originally had the error *did* need/use ABIEncoderV2). It includes a fairly random assortment of functions that don't really have anything to do with one another. These are just artifacts of stripping out the pieces not necessary to reproduce the error.

If you change almost anything about the example, the compilation begins to succeed:
- Removing either `require` message.
- Removing `ABIEncoderV2`.
- Removing the `onlyOwner` modifier from the `renounceOwnership()` method.

Please let me know if there's any other information you need!

### PR DESCRIPTION
**Pull request by Marenz**
fixes #8656

This is only a WIP. Currently missing is a check that the function is run exactly once and fixing/analysing the new test failures caused by this change

### CODE REVIEW

File: libsolidity/codegen/ContractCompiler.cpp [hunk 1]
```diff
@@ -215,6 +213,7 @@ size_t ContractCompiler::deployLibrary(ContractDefinition const& _contract)
 	solAssert(!!m_runtimeCompiler, "");
 	solAssert(_contract.isLibrary(), "Tried to deploy contract as library.");
 
+	appendMissingFunctions();
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp:216]:
```suggestion
	m_runtimeCompiler->appendMissingFunctions();
```

Comment (chriseth) [reply libsolidity/codegen/ContractCompiler.cpp:216]: or maybe try both like in `packIntoContractCreator`

**Comment by chriseth** [comment]
Please add a changelog entry and a mechanism that checks that `m_context.requestedYulFunctions()` is called exactly once on each context.

**Comment by Marenz** [comment]
Oh right. I completely forgot that part. Sorry.

**Comment by Marenz** [comment]
Updated

File: Changelog.md [hunk 2]
```diff
@@ -9,6 +9,8 @@ Compiler Features:
 
 
 Bugfixes:
+ * Fixed an "Assembly Exception in Bytecode" error where requested functions
+   were generated twice.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Fixed an "Assembly Exception in Bytecode" error where requested Yul functions were generated twice.
```

File: libsolidity/codegen/Compiler.cpp [hunk 3]
```diff
@@ -49,6 +49,9 @@ void Compiler::compileContract(
 	m_runtimeSub = creationCompiler.compileConstructor(_contract, _otherCompilers);
 
 	m_context.optimise(m_optimiserSettings);
+
+	solAssert(m_context.requestedYulFunctionsRan(), "requestedYulFunctions() was not called.");
```
Comment (chriseth) [inline libsolidity/codegen/Compiler.cpp:53]: Does that work here? Shouldn't we rather have it in `Compiler::compileContract`?

Comment (Marenz) [reply libsolidity/codegen/Compiler.cpp:53]: As it is currently, that would cause a assert fail because we do `m_runtimeCompiler->appendMissingFunctions()` when we call `compileConstructor()` which adds it to the runtime context.

But this is a bit confusing because only the call to the creation compiler adds the missing functions to the runtime compiler.. maybe we should structure this differently?

**Review by chriseth — APPROVED** [review]
