### PR TITLE
Error and ICE reporting tweaks

### LINKED ISSUE #15740: Stack too deep exception is not being caught
Compile: `solc a.sol --asm --optimize-yul --yul-optimizations ohDEndLjOgiTMsCufeSlcVUr --via-ir`

```solidity
contract Test {
  int256 public z;

  bytes16 public constant e = hex"616263";

  function f(int256 c, bytes1 b, bool d) public returns(bytes1) {
    bytes16 a = e;
    a = bytes16(abi.encodePacked(a[0], a[1], b, a[2], b, a[4], a[5], b, a[6], a[7], b, a[8], a[9], b, a[11], b, a[13], a[14], a[15]));
    bytes16 r = a;
    return r[0];
  }
}
```

Output:

```
/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(110): Throw in function void solidity::yul::EVMObjectCompiler::run(const solidity::yul::Object&, bool)
Dynamic exception type: boost::wrapexcept<solidity::yul::StackTooDeepError>
std::exception::what: Cannot swap Variable value18 with Slot 0x01: too deep in the stack by 4 slots in [ RET value18 value17 value16 value15 value14 value13 value12 value11 value10 pos value8 value7 value6 value5 value4 value3 value2 value1 value0 value9 0x01 ]
memoryguard was present.
[solidity::util::tag_comment*] = Cannot swap Variable value18 with Slot 0x01: too deep in the stack by 4 slots in [ RET value18 value17 value16 value15 value14 value13 value12 value11 value10 pos value8 value7 value6 value5 value4 value3 value2 value1 value0 value9 0x01 ]
memoryguard was present.
[solidity::langutil::tag_sourceLocation*] = a.sol[1389,1730]
```

solc version: `Version: 0.8.29-develop.2025.1.17+commit.26263c63.Linux.g++`

### PR DESCRIPTION
**Pull request by cameel**
This is an assortment of small improvements in error reporting:
- `AsmAnalyzer::analyzeStrictAssertCorrect()` now includes pretty printed source and the error list in the assertion message. This will make it easier to triage cases like [#15889](https://github.com/ethereum/solidity/issues/15889) and is the most important change here.
- `SourceReferenceFormatter` was not printing source locations for files with an empty name. This is a perfectly valid case in Standard JSON. We also use such names for internally generated Yul and in test suites.
- Failed Yul assertions and Yul StackTooDeep errors (not to be confused with completely separate `langutil` StackTooDeep errors; WTF) are now handled properly in Solidity mode: the former as ICE, the latter as a normal error.
    - ICEs in Standard JSON now properly include all the same diagnostic info we provide on the CLI. Until now this was being done only for uncaught exceptions, not failed assertions.
    - StackTooDeep errors on the CLI now show a proper error with location rather than the hairy diagnostic info meant for ICEs. This fixes #15740.
    - Note that this is still a mess in many ways. E.g. we have separate exception handlers for Yul and I did not touch those.
- The assertion that's triggered by invalid IR coming out the generator now shows error codes (and source locations due to the other fix mentioned above).

### CODE REVIEW

File: test/CommonSyntaxTest.cpp [hunk 1]
```diff
@@ -197,15 +197,15 @@ void CommonSyntaxTest::printErrorList(
...
 					{BOLD, SourceReferenceFormatter::errorTextColor(Error::errorSeverity(error.type))}
 				);
-				_stream << _linePrefix << Error::formatErrorType(error.type);
+				formattedStream << _linePrefix << Error::formatErrorType(error.type);
 				if (error.errorId.has_value())
-					_stream << ' ' << error.errorId->error;
-				_stream << ": ";
+					formattedStream << ' ' << error.errorId->error;
+				formattedStream << ": ";
 			}
```
Comment (cameel) [inline test/CommonSyntaxTest.cpp:209]: This one does not actually fix anything but I decided to change it to be less of a head-scratcher.

We usually output to the ANSI stream using `<<`, but here it's just created and we ignore it. I initially thought it was a bug and that coloring must be broken because of it, but it works. Apparently the control codes are issued at construction and destruction time.

File: libyul/Exceptions.h [hunk 2]
```diff
@@ -36,7 +36,7 @@ namespace solidity::yul
 struct YulException: virtual util::Exception {};
 struct OptimizerException: virtual YulException {};
 struct CodegenException: virtual YulException {};
-struct YulAssertion: virtual YulException {};
+struct YulAssertion: virtual util::Exception {};
```
Comment (cameel) [inline libyul/Exceptions.h:39]: We should simplify this one day and make all assert macros throw `InternalCompilerError`. Having different types and even documenting them in [Error types](https://docs.soliditylang.org/en/develop/using-the-compiler.html#error-types) just unnecessarily exposes implementation details to the user. We should only have compilation errors there. It's especially confusing when things like `SMTLogicError` are actually failed assertions.

File: test/cmdlineTests/standard_empty_file_name/output.json [hunk 3]
```diff
@@ -4,6 +4,10 @@
             "component": "general",
             "errorCode": "2904",
             "formattedMessage": "DeclarationError: Declaration \"A\" not found in \"\" (referenced as \".\").
+ --> :2:24:
+  |
+2 | pragma solidity >=0.0; import {A} from \".\";
+  |                        ^^^^^^^^^^^^^^^^^^^^
```
Comment (cameel) [inline test/cmdlineTests/standard_empty_file_name/output.json:10]: Note that this affects also the errors reported by the assert in `CompilerStack::loadGeneratedIR()`.

Instead of this:
```
Invalid IR generated:
Error (6913): Call or assignment expected.

Error (8143): Expected keyword "data" or "object" or "}".
```
we'll now see this:
```
Invalid IR generated:
Error (6913): Call or assignment expected.
 --> :7:9:
  |
7 |         mstore(64, memoryguard(128))
  |         ^^^^^^

Error (8143): Expected keyword "data" or "object" or "}".
 --> :7:9:
  |
7 |         mstore(64, memoryguard(128))
  |         ^^^^^^
```

Another thing it affects are Yul test case variants that use the empty name for the source they parse and don't allow errors in expectations. The formatted errors are instead included in the exception they throw.

File: test/cmdlineTests/stack_too_deep_from_code_transform/err [hunk 4]
```diff
@@ -0,0 +1,6 @@
+Error: Cannot swap Variable value23 with Slot 0x20: too deep in the stack by 9 slots in [ RET value23 value22 value21 value20 value19 value18 value17 value16 value15 value14 value13 value12 value11 value10 value9 value8 value7 value6 value5 value4 value3 value2 value1 value0 pos 0x20 ]
+memoryguard was present.
+ --> stack_too_deep_from_code_transform/input.sol:1:1:
+  |
+1 | contract C {
+  | ^ (Relevant source part starts here and spans across multiple lines).
```
Comment (cameel) [inline test/cmdlineTests/stack_too_deep_from_code_transform/err:6]: This is what it looked like before the change:
```
Uncaught exception:
/solidity/libyul/backends/evm/EVMObjectCompiler.cpp(110): Throw in function void solidity::yul::EVMObjectCompiler::run(const solidity::yul::Object&, bool)
Dynamic exception type:
std::exception::what: Cannot swap Variable value23 with Slot 0x20: too deep in the stack by 9 slots in [ RET value23 value22 value21 value20 value19 value18 value17 value16 value15 value14 value13 value12 value11 value10 value9 value8 value7 value6 value5 value4 value3 value2 value1 value0 pos 0x20 ]
memoryguard was present.
[solidity::util::tag_comment*] = Cannot swap Variable value23 with Slot 0x20: too deep in the stack by 9 slots in [ RET value23 value22 value21 value20 value19 value18 value17 value16 value15 value14 value13 value12 value11 value10 value9 value8 value7 value6 value5 value4 value3 value2 value1 value0 pos 0x20 ]
memoryguard was present.
[solidity::langutil::tag_sourceLocation*] = stack_too_deep_from_code_transform/input.sol[0,206]
```

**Review by matheusaaguiar — APPROVED** [review]
