### PR TITLE
Fix: Allow multiple @return tags on public state variables

### LINKED ISSUE #11381: Cannot NatSpec document a struct return value
# Test case

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.4;
contract Bank {
    struct Coin {
        string obverseGraphicURL;
        string reverseGraphicURL;
    }

    /// @notice Get the n-th coin I own
    /// @return obverseGraphicURL Front pic
    /// @return reverseGraphicURL Back pic
    Coin[] public coinStack;
}
```

# Discussion

Public state variables are allowed to have `@return` as per https://docs.soliditylang.org/en/v0.8.4/natspec-format.html?highlight=natspec#tags

If returning a `struct` from a public state variable, which is common for arrays and mappings, JSON ABI (and Solidity) treat the output as a tuple.

# Expected outcome

This should compile.

Also, we should consider allowing a `@param ???` documentation for the input of this public state variable. Because every external input and output of every published smart contract should be documented.

# Actual outcome

> DocstringParsingError: Documentation tag "@return" is only allowed once on state-variables. --> contracts/3_Ballot.sol:9:5: | 9 | /// @notice Get the n-th coin I own | ^ (Relevant source part starts here and spans across multiple lines).

### PR DESCRIPTION
**Pull request by Marenz**
fixes #11381

I am not completely happy with how I solved the dependency problem in CompilerStack. If you see a nicer way, please comment.

### CODE REVIEW

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 1]
```diff
@@ -199,40 +210,41 @@ void DocStringTagParser::parseDocStrings(
...
 			if (auto const* varDecl = dynamic_cast<VariableDeclaration const*>(&_node))
 			{
 				solAssert(varDecl->isPublic(), "@return is only allowed on public state-variables.");
-				if (returnTagsVisited > 1)
-					m_errorReporter.docstringParsingError(
-						5256_error,
-						_node.documentation()->location(),
-						"Documentation tag \"@" + tagName + "\" is only allowed once on state-variables."
-					);
+				returnParameterNames = FunctionType(*varDecl).returnParameterNames();
```
Comment (Marenz) [inline libsolidity/analysis/DocStringTagParser.cpp]: The `FunctionType()` c'tor requires existing type information which is only available after we ran the DeclarationChecker..

File: Changelog.md [hunk 2]
```diff
@@ -13,6 +13,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * Natspec: Allow multiple @return tags on public state variable documentation.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Natspec: Allow multiple ``@return`` tags on public state variable documentation.
```

Comment (chriseth) [reply Changelog.md]: Also it's not sorted at the right location.

**Comment by chriseth** [comment]
I think the general approach to split it up into two phases is good, but could you change the code so that it does not re-do everything on the second phase? All information retrieved in the first phase should be in the annotations, shouldn't it?

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 3]
```diff
@@ -47,6 +47,14 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
 	return errorWatcher.ok();
 }
 
+bool DocStringTagParser::validateDocStringsUsingTypes(SourceUnit const& _sourceUnit)
+{
+	m_resolverRan = true;
+	auto errorWatcher = m_errorReporter.errorWatcher();
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]:
```suggestion
	ErrorWatcher errorWatcher = m_errorReporter.errorWatcher();
```

File: libsolidity/analysis/DocStringTagParser.h [hunk 4]
```diff
@@ -37,6 +37,8 @@ class DocStringTagParser: private ASTConstVisitor
 public:
 	explicit DocStringTagParser(langutil::ErrorReporter& _errorReporter): m_errorReporter(_errorReporter) {}
 	bool parseDocStrings(SourceUnit const& _sourceUnit);
+	/// Validate the parsed doc strings, requires the resolver to have run
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.h]: You mean this resolver, right?
```suggestion
	/// Validate the parsed doc strings, requires the NameAndTypeResolver to have run
```

File: libsolidity/interface/CompilerStack.cpp [hunk 5]
```diff
@@ -445,6 +446,11 @@ bool CompilerStack::analyze()
 			if (source->ast && !declarationTypeChecker.check(*source->ast))
 				return false;
 
+		// Requires declaration checker to have run
```
Comment (cameel) [inline libsolidity/interface/CompilerStack.cpp]:
```suggestion
		// Requires DeclarationTypeChecker to have run
```

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 6]
```diff
@@ -199,40 +210,41 @@ void DocStringTagParser::parseDocStrings(
...
+			else
+				continue;
+
+			string content = tagValue.content;
+			string firstWord = content.substr(0, content.find_first_of(" \t"));
 
-				if (returnTagsVisited > function->returnParameters().size())
+			if (returnTagsVisited > returnParameterNames.size())
+				m_errorReporter.docstringParsingError(
+					2604_error,
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]: This error is semantically pretty close to the old one. Maybe it would be better to preserve the old error code?
```suggestion
					5256_error,
```

File: libsolidity/analysis/DocStringTagParser.cpp (hunk 1 above)
Comment (cameel) [reply libsolidity/analysis/DocStringTagParser.cpp]: I think it would not hurt to put it in a comment at this point in the code.

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 7]
```diff
@@ -47,6 +47,14 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
 	return errorWatcher.ok();
 }
 
+bool DocStringTagParser::validateDocStringsUsingTypes(SourceUnit const& _sourceUnit)
+{
+	m_resolverRan = true;
+	auto errorWatcher = m_errorReporter.errorWatcher();
+	_sourceUnit.accept(*this);
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]: Doesn't doing this mean that we're running the whole analysis step the second time? Or was it not running on `SourceUnit` before? Even if it wasn't, it surely must have run at least on some parts of the AST.

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 8]
```diff
@@ -169,6 +177,9 @@ void DocStringTagParser::parseDocStrings(
 
 	_annotation.docTags = DocStringParser{*_node.documentation(), m_errorReporter}.parse();
 
+	if (!m_resolverRan)
+		return;
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]: Why not assert? Is there a legitimate situation where we're fine with this analysis step being silently skipped?

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 9]
```diff
@@ -47,6 +47,14 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
 	return errorWatcher.ok();
 }
 
+bool DocStringTagParser::validateDocStringsUsingTypes(SourceUnit const& _sourceUnit)
+{
+	m_resolverRan = true;
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]: Wouldn't it be more appropriate to call it something like `m_validateDocStringsUsingTypesRan`? The class can't really know if the resolver step actually ran before it but the current name makes you think it does.

File: test/libsolidity/SolidityNatspecJSON.cpp [hunk 10]
```diff
@@ -328,6 +328,54 @@ BOOST_AUTO_TEST_CASE(public_state_variable)
...
+	char const* sourceCode = R"(
+		contract Bank {
+			struct Coin {
+				string obverseGraphicURL;
+				string reverseGraphicURL;
+			}
+
+			/// @notice Get the n-th coin I own
+			/// @return obverseGraphicURL Front pic
+			/// @return reverseGraphicURL Back pic
```
Comment (cameel) [inline test/libsolidity/SolidityNatspecJSON.cpp]: Could you also add a test for duplicate `@return` for one parameter while another is missing? I.e.
```
			/// @return obverseGraphicURL Front pic
			/// @return obverseGraphicURL Front pic
```

File: libsolidity/analysis/DocStringTagParser.h (hunk 4 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringTagParser.h]: Well, technically it is the ReferencesResolver which is in turned called by the NameAndTypeResolver

File: libsolidity/analysis/DocStringTagParser.cpp (hunk 6 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringTagParser.cpp]: I did not introduce any new errors nor changed any old ones, there only has been some moving around..

File: libsolidity/analysis/DocStringTagParser.h (hunk 4 above)
Comment (cameel) [reply libsolidity/analysis/DocStringTagParser.h]: Ah, my bad. All the more reason to include its name though :)

File: libsolidity/analysis/DocStringTagParser.cpp (hunk 6 above)
Comment (cameel) [reply libsolidity/analysis/DocStringTagParser.cpp]: Ah, right. The diff is a bit hard to read here and I thought `2604_error` was being replaced by `5856_error` but it's still there. It's only 5256_error` that is being removed.

Comment (Marenz) [reply libsolidity/analysis/DocStringTagParser.cpp:231]: Nope, `5256` is still here, too

File: test/libsolidity/SolidityNatspecJSON.cpp (hunk 10 above)
Comment (Marenz) [reply test/libsolidity/SolidityNatspecJSON.cpp]: sure

File: libsolidity/analysis/DocStringTagParser.cpp (hunk 8 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringTagParser.cpp]: This kind of links with your other question of whether we ran the whole analysis again. This flag prevents the later parts. 
But i changed my approach now a bit so this became obsolete anyway :)

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 11]
```diff
@@ -47,6 +47,65 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
 	return errorWatcher.ok();
 }
 
+bool DocStringTagParser::validateDocStringsUsingTypes(SourceUnit const& _sourceUnit)
+{
+	auto errorWatcher = m_errorReporter.errorWatcher();
+
+	SimpleASTVisitor visitReturns([](ASTNode const&) { return true; }, [&](ASTNode const& _node)
+	{
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]: I'd wrap it this way. This clearly shows that we have two lambdas passed in parameter. The current line looked to me as a weird function declared in the middle of another function at first. 
```suggestion
	SimpleASTVisitor visitReturns(
		[](ASTNode const&) { return true; },
		[&](ASTNode const& _node)
		{
```

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 12]
```diff
@@ -47,6 +47,65 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
...
+								" does not contain the name of its return parameter."
+							);
+					}
+
+				}
+		}
+	});
+
+	_sourceUnit.accept(visitReturns);
+	return errorWatcher.ok();
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp:109]: If the return value is always `ok()` maybe it would be better not to return anything?

File: libsolidity/analysis/DocStringTagParser.h (hunk 4 above)
Comment (cameel) [reply libsolidity/analysis/DocStringTagParser.h]: Also, it probably also requires `parseDocStrings()` to run before it, right? If so I'd mention it in the docstring too.

**Review by cameel — COMMENTED** [review]
Looks good now. I think that all the bigger stuff has been addressed. There are just a few minor/stylistic/docstring issues remaining.

File: libsolidity/analysis/DocStringTagParser.cpp (hunk 12 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringTagParser.cpp:109]: `ok()` doesn't always return `true` ;). The method returns the state of the error watcher

Comment (cameel) [reply libsolidity/analysis/DocStringTagParser.cpp:109]: Oh, good point. It's fine then.

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 13]
```diff
@@ -47,6 +47,69 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
 	return errorWatcher.ok();
 }
 
+bool DocStringTagParser::validateDocStringsUsingTypes(SourceUnit const& _sourceUnit)
+{
+	auto errorWatcher = m_errorReporter.errorWatcher();
+
+	SimpleASTVisitor visitReturns(
```
Comment (chriseth) [inline libsolidity/analysis/DocStringTagParser.cpp:54]: Can you split this into two commits so the changes are visible?

File: libsolidity/interface/CompilerStack.cpp [hunk 14]
```diff
@@ -436,6 +431,12 @@ bool CompilerStack::analyze()
 
 		resolver.warnHomonymDeclarations();
 
+		DocStringTagParser docStringTagParser(m_errorReporter);
+		for (Source const* source: m_sourceOrder)
+			if (source->ast && !docStringTagParser.parseDocStrings(*source->ast))
+				noErrors = false;
+
+		// Requires DocStringTagParser
```
Comment (cameel) [inline libsolidity/interface/CompilerStack.cpp:440]:
```suggestion
		// Requires DocStringTagParser.parseDocStrings()
```

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 15]
```diff
@@ -47,6 +47,69 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
...
+						returnTagsVisited++;
+						vector<string> returnParameterNames;
+
+						if (auto const* varDecl = dynamic_cast<VariableDeclaration const*>(&_node))
+						{
+							if (!varDecl->isPublic())
+								continue;
+
+							// FunctionType() requires the DeclarationTypeChecker
+							// to have run.
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp]:
```suggestion
							// FunctionType() requires the DeclarationTypeChecker to have run.
```

File: libsolidity/analysis/DocStringTagParser.cpp [hunk 16]
```diff
@@ -47,6 +47,69 @@ bool DocStringTagParser::parseDocStrings(SourceUnit const& _sourceUnit)
...
+				for (auto const& [tagName, tagValue]: annotation->docTags)
+					if (tagName == "return")
+					{
+						returnTagsVisited++;
+						vector<string> returnParameterNames;
+
+						if (auto const* varDecl = dynamic_cast<VariableDeclaration const*>(&_node))
+						{
+							if (!varDecl->isPublic())
+								continue;
```
Comment (cameel) [inline libsolidity/analysis/DocStringTagParser.cpp:73]: Is this no longer an assert because in the old place the `!_validTags.count(tagName)` check would catch it?

File: test/libsolidity/SolidityNatspecJSON.cpp [hunk 17]
```diff
@@ -328,6 +328,73 @@ BOOST_AUTO_TEST_CASE(public_state_variable)
...
+
+			/// @notice Get the n-th coin I own
+			/// @return obverseGraphicURL Front pic
+			/// @return obverseGraphicURL Front pic
+			Coin[] public coinStack;
+		}
+	)";
+
+	expectNatspecError(sourceCode);
+}
```
Comment (cameel) [inline test/libsolidity/SolidityNatspecJSON.cpp:396]: Maybe it would be better to move this test to `test/libsolidity/syntaxTests/natspec/`?

**Review by cameel — DISMISSED** [review]
Looks fine to me. I have a few small nitpicks but I think it would be acceptable even if it went in in the current form so I'm already making as approved.

File: test/libsolidity/SolidityNatspecJSON.cpp [hunk 18]
```diff
@@ -328,6 +328,73 @@ BOOST_AUTO_TEST_CASE(public_state_variable)
...
+{
+	char const* sourceCode = R"(
+		contract Bank {
+			struct Coin {
+				string obverseGraphicURL;
+				string reverseGraphicURL;
+			}
+
+			/// @notice Get the n-th coin I own
+			/// @return obverseGraphicURL Front pic
```
Comment (chriseth) [inline test/libsolidity/SolidityNatspecJSON.cpp]: Can you swap this and the next line, so that we can verify that the association is by name and not by position?

File: libsolidity/analysis/DocStringTagParser.cpp (hunk 16 above)
Comment (Marenz) [reply libsolidity/analysis/DocStringTagParser.cpp:73]: Kind of.
Previously the function was called using
```
		if (_variable.isPublic())
			parseDocStrings(_variable, _variable.annotation(), {"dev", "notice", "return", "inheritdoc"}, "public state variables");

```
So it would only see public state variables and as you said, it also has a more limited set of valid tags.

In the new function it is just called from compilerstack directly and goes over all already parsed tags.

File: test/libsolidity/SolidityNatspecJSON.cpp (hunk 18 above)
Comment (Marenz) [reply test/libsolidity/SolidityNatspecJSON.cpp]: They are actually associated by name AND position. If either is wrong, it will fail. That was also the behavior of the previous code which only worked for functions though, not state variables. 

I am currently implementing that the order doesn't matter, but something like _only order_ (e.g. no parameter names) feels unnecessary at this point.. let me know if you disagree

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
Please rebase.

**Review by chriseth — DISMISSED** [review]

**Review by chriseth — APPROVED** [review]
