### PR TITLE
Fix PostTypeChecker retaining state across contracts

### LINKED ISSUE #2108: Internal compiler error: PostTypeChecker.cpp:51
The following code gives `Internal compiler error (/src/libsolidity/analysis/PostTypeChecker.cpp:51): `.

```
pragma solidity ^0.4.10;

contract A {
    uint256 constant x = 1;
    uint256 constant y = 1 + x;
}

contract B {
}
```

### PR DESCRIPTION
**Pull request by federicobond**
Closes #2108

The `m_constVariableDependencies.empty()` solAssert in `visit(ContractDefinition const&)` was failing because the visitor retained constants from previous contracts.

### CODE REVIEW

**Comment by pirapira** [comment]
`scripts/bytecodecompare/storebytecode.sh` is [failing](https://travis-ci.org/ethereum/solidity/jobs/220126698).  Does this mean comparison failure or some other problems?  @chriseth

**Comment by axic** [comment]
@pirapira means that creating the report (e.g. all the test sources compiled and saved to a github repo) failed

**Comment by federicobond** [comment]
Failure appears unrelated. CI outputs "iv undefined", so I looked into the bytecodecompare.sh script and found this [line](https://github.com/ethereum/solidity/blob/develop/scripts/bytecodecompare/storebytecode.sh#L83):
````
openssl aes-256-cbc -K $encrypted_60701c962b9c_key -iv $encrypted_60701c962b9c_iv -in "$REPO_ROOT"/scripts/bytecodecompare/deploy_key.enc -out deploy_key -d
````
Which leads me to think that the `encrypted_60701c962b9c_iv` variable may not be set correctly.

**Comment by chriseth** [comment]
The reason for the failure is that this is an external pull request that does not have access to the private key required for the upload. We could improve that script :-)

**Comment by chriseth** [comment]
Thanks for looking into this bug!

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 1]
```diff
@@ -58,6 +58,9 @@ void PostTypeChecker::endVisit(ContractDefinition const&)
 	for (auto declaration: m_constVariables)
 		if (auto identifier = findCycle(declaration))
 			typeError(declaration->location(), "The value of the constant " + declaration->name() + " has a cyclic dependency via " + identifier->name() + ".");
+
+	m_constVariables.clear();
```
Comment (chriseth) [inline libsolidity/analysis/PostTypeChecker.cpp:62]: I wonder whether it might be better to remove the check in line 51. The reason is that I think it is safer to rather keep the dependencies in. Furthermore, we already plan to allow things like
```js
library X { uint constant x = 0x123; }
contract C {
uint y = X.x;
}
```
and thus we might have cross-contract dependencies soon.

Comment (federicobond) [reply libsolidity/analysis/PostTypeChecker.cpp:62]: My own thinking was that you cannot have cross contract cycles, because you cannot reference down the inheritance chain and libraries cannot reference back contracts.

I remember removing the check without clearing the state and getting some unintended results, like duplicated errors because the cycle would be found in both the child and the parent contract.

**Comment by federicobond** [comment]
We can guard the script with `TRAVIS_SECURE_ENV_VARS != "true"` in the .travis.yml file.

**Comment by chriseth** [comment]
@federicobond can you please investigate the other way to solve it? I think currently, even if you only have a cycle in a single contract, you get multiple reports of that cycle, which is not a bad thing, I would say.

**Comment by federicobond** [comment]
Taking this Solidity code as input:
```
contract Foo {
  uint constant a = b;
  uint constant b = a;
}

contract Bar is Foo {
  uint constant c = b;
}
```

With my current patch:

```
test.sol:4:3: Error: The value of the constant a has a cyclic dependency via b.
  uint constant a = b;
  ^-----------------^
test.sol:5:3: Error: The value of the constant b has a cyclic dependency via a.
  uint constant b = a;
  ^-----------------^
```
But if I don't clean the state and remove the assertion instead, I get this:
```
test.sol:5:3: Error: The value of the constant a has a cyclic dependency via b.
  uint constant a = b;
  ^-----------------^
test.sol:6:3: Error: The value of the constant b has a cyclic dependency via a.
  uint constant b = a;
  ^-----------------^
test.sol:5:3: Error: The value of the constant a has a cyclic dependency via b.
  uint constant a = b;
  ^-----------------^
test.sol:6:3: Error: The value of the constant b has a cyclic dependency via a.
  uint constant b = a;
  ^-----------------^
test.sol:15:3: Error: The value of the constant c has a cyclic dependency via b.
  uint constant c = b;
  ^-----------------^
```

**Comment by chriseth** [comment]
Does that mean that your way to solve it does not even detect the cyclic dependency caused by c? Admittedly, I don't see a way to create a cyclic dependency in Bar by referencing a variable in Foo while Foo does not yet have a cyclic dependency, but this is not true anymore if you can do things like `B.c`.

I guess the way to achieve that would be to just clear `m_constVariables` but not `m_constVariableDependencies`.

Also, `findCycle` could be improved to not just find any cycle, but just a cycle that contains the initial node. I think that there is no case where we have a cycle that does not include at least one of the newly added variables.

**Comment by federicobond** [comment]
But `c` is not "causing" any cyclic dependency in my example, since you can take it out and the cycle will still be there. Another way to put it is that `c` is not inside the cycle of the dependency graph, only `a` and `b` are.

> but this is not true anymore if you can do things like B.c

How does that work?

**Comment by chriseth** [comment]
@federicobond yes, that's what I am saying. I think it is fine to only create an error if you have a cycle that ends up again at the variable you started with. Using `B.c` is not yet supported, but it is not too far away.

**Comment by pirapira** [comment]
@chriseth I'm not seeing a problem in this PR.  Maybe that's because I don't understand what can go wrong with `B.c`.  I'm believing it's totally fine to detect cycles locally in a single contract.

**Comment by chriseth** [comment]
Ok, so let's keep this until we extend the lookup across contracts. Sorry for the hassle, @federicobond :-)
