### PR TITLE
Crash when array index value is too large

### LINKED ISSUE #4716: Crash when array index value is too large
_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
Compiler crashes when a rational type over 78 digits is present as an array index.

## Error in file
Integer constant too large.
`libsolidity/ast/Types.cpp(1144)`

## Displayed message
`Throw in function virtual dev::u256 dev::solidity::RationalNumberType::literalValue(const dev::solidity::Literal*) const`

## Example code

```solidity
pragma solidity ^0.4.24;
contract CrashContract {
    function f() returns (string) {
        return (["zeppelin"][123456789012345678901234567890123456789012345678901234567890123456789012345678]);
    }
}

```

### PR DESCRIPTION
**Pull request by bakaoh**
Fix #4716

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### Description
Add some check to report error instead of crash

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2211,12 +2211,13 @@ bool TypeChecker::visit(IndexAccess const& _access)
...
-			if (auto numberType = dynamic_cast<RationalNumberType const*>(type(*index).get()))
-			{
-				if (!numberType->isFractional()) // error is reported above
-					if (!actualType.isDynamicallySized() && actualType.length() <= numberType->literalValue(nullptr))
-						m_errorReporter.typeError(_access.location(), "Out of bounds array access.");
-			}
+			if (!m_errorReporter.hasErrors())
+				if (auto numberType = dynamic_cast<RationalNumberType const*>(type(*index).get()))
+				{
+					if (!numberType->isFractional()) // error is reported above
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Since you now check for `hasErrors()` this should be changed into `solAssert(!numberType->isFractional(), "")`

File: Changelog.md [hunk 2]
```diff
@@ -111,6 +111,7 @@ Bugfixes:
  * Type Checker: Report error when using structs in events without experimental ABIEncoderV2. This used to crash or log the wrong values.
  * Type Checker: Report error when using indexed structs in events with experimental ABIEncoderV2. This used to log wrong values.
  * Type Checker: Dynamic types as key for public mappings return error instead of assertion fail.
+ * Type Checker: Fix crash when array index value is too large.
```
Comment (chriseth) [inline Changelog.md]: Perhaps better to use the word "internal error" - "crash" always sounds like a segmentation violation to me.

**Review by chriseth — CHANGES_REQUESTED** [review]
Wonderful, I would just request some tiny cosmetic changes.

File: test/libsolidity/syntaxTests/types/array_index_too_large.sol [hunk 3]
```diff
@@ -0,0 +1,7 @@
+contract C {
+    function f() public returns (string memory) {
+        return (["zeppelin"][123456789012345678901234567890123456789012345678901234567890123456789012345678]);
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/types/array_index_too_large.sol]: Ah, perhaps add a comment `// this used to cause an internal error` so that we know why the test is there.

**Comment by bakaoh** [comment]
@chriseth -- i've updated :)

**Review by chriseth — APPROVED** [review]
