### PR TITLE
[SMTChecker] Fix ICE on conditional with tuples of rationals

### LINKED ISSUE #9741: [SMTChecker] ICE in if-then-else evaluation because *_trueValue.sort != *_falseValue.sort
## Description

```
pragma experimental SMTChecker;
contract C {
  function f(bool x) public pure { x ? (1,2) : (3,4); }
}
```

throws

https://github.com/ethereum/solidity/blob/f964966090f7e3571e20144fd4aa0b6391aea26e/libsmtutil/SolverInterface.h#L114

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/9741
Depends on https://github.com/ethereum/solidity/pull/10077

### CODE REVIEW

File: libsolidity/formal/SymbolicVariables.cpp [hunk 1]
```diff
@@ -245,7 +245,24 @@ SymbolicTupleVariable::SymbolicTupleVariable(
...
 
-vector<SortPointer> const& SymbolicTupleVariable::components()
+smtutil::Expression SymbolicTupleVariable::currentValue(frontend::TypePointer const& _targetType) const
+{
+	if (!_targetType || sort() == smtSort(*_targetType))
+		return SymbolicVariable::currentValue();
+
+	auto const& thisTuple = dynamic_cast<TupleSort const&>(*sort());
+	auto const& otherTuple = dynamic_cast<TupleSort const&>(*smtSort(*_targetType));
+	solAssert(thisTuple.components.size() == otherTuple.components.size(), "");
```
Comment (hrkrshnn) [inline libsolidity/formal/SymbolicVariables.cpp]: soltest seems to throw here.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicVariables.cpp]: Yes, but only on Mac OS. No idea why. @chriseth mentioned it's not a new thing

File: test/libsolidity/smtCheckerTests/operators/tuple_rationals_conditional.sol [hunk 2]
```diff
@@ -0,0 +1,9 @@
+pragma experimental SMTChecker;
+
+contract C {
+	function f(bool x) public pure {
+		(uint a, uint b) = x ? (10000000001, 2) : (3, 4);
+		assert(a % 2 == 1);
+		assert(b % 2 == 0);
+	}
```
Comment (axic) [inline test/libsolidity/smtCheckerTests/operators/tuple_rationals_conditional.sol:10]: I'd also assert for `a != 0 && b != 0` to avoid any potential case where the tuple is not considered initialised.

File: libsolidity/formal/SymbolicVariables.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/formal/SymbolicVariables.cpp]: Yeah, I was probably wrong.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicVariables.cpp]: I tried debugging this on CI Mac OS, but:
- I can't use `gdb` there because it requires some signing (???). I did the signing following google stuff but the signing just hangs.
- When I use `lldb` the run hangs. Running `solc` works fine, I get the exception, but when running anything inside `lldb`, even without the SMTChecker, it hangs.
So I open to suggestions...

Comment (hrkrshnn) [reply libsolidity/formal/SymbolicVariables.cpp]: If debuggers don't work, one way around the problem is to add a bunch of `cout` and run it on the CI? Not sure if `soltest` will suppress it though.

Comment (leonardoalt) [reply libsolidity/formal/SymbolicVariables.cpp]: Yea, I'll try that. Hard to know the source of the problem without a stack trace though

File: test/libsolidity/smtCheckerTests/operators/tuple_rationals_conditional.sol (hunk 2 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/operators/tuple_rationals_conditional.sol:10]: Done

File: libsolidity/formal/SymbolicVariables.cpp [hunk 3]
```diff
@@ -245,7 +245,25 @@ SymbolicTupleVariable::SymbolicTupleVariable(
...
 }
 
-vector<SortPointer> const& SymbolicTupleVariable::components()
+smtutil::Expression SymbolicTupleVariable::currentValue(frontend::TypePointer const& _targetType) const
+{
+	if (!_targetType || sort() == smtSort(*_targetType))
+		return SymbolicVariable::currentValue();
+
+	auto thisTuple = dynamic_pointer_cast<TupleSort>(sort());
+	auto otherTuple = dynamic_pointer_cast<TupleSort>(smtSort(*_targetType));
```
Comment (leonardoalt) [inline libsolidity/formal/SymbolicVariables.cpp:254]: @hrkrshnn @chriseth 
This used to be
`auto const& otherTuple = dynamic_cast<TupleSort const&>(*smtSort(*_targetType));`
I guess the OSX libc++ doesn't know how to get references of temporaries (the way the proper libc++ does), it was giving an empty object here, so the assertion on the size failed with 2 vs 0. This seemed to work inside CI.

**Review by hrkrshnn — APPROVED** [review]
LGTM. One more review would be nice before merging.

**Review by mijovic — APPROVED** [review]
