### PR TITLE
Split up rule list generation further.

### LINKED ISSUE #1644: Can't compile in firefox or load older compiler
Hello. 
Currently was using Firefox to work with remix web IDE, but I had to switch to chrome because a few things with the compiler were not working...

First, I just could not compile a simple contract:

screen shot 2018-12-21 at 7 29 13 pm
screen shot 2018-12-21 at 7 29 16 pm

Then, when trying to pick an older compiler, it is stuck on "loading using worker".

I had no problem on Chrome however, but I am a firefox gal.

### LINKED ISSUE #1659: Internal exception in StandardCompiler
I am having problems with my new solidity contracts in Remix.
For example, I get:

"Internal exception in StandardCompiler::compileInternal: /root/project/libevmasm/ExpressionClasses.cpp(187): Throw in function ExpressionClasses::Id dev::eth::ExpressionClasses::tryToSimplify(const dev::eth::ExpressionClasses::Expression &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::OptimizerException>
std::exception::what: Rule list not properly initialized.
[dev::tag_comment*] = Rule list not properly initialized."

for this simple contract:

pragma solidity ^0.5.0;

/* @title Lockable */
contract Lockable  {
  
  // State
  bool public isLocked;
 
  
}

### PR DESCRIPTION
**Pull request by ekpyron**
This (hopefully) fixes https://github.com/ethereum/remix-ide/issues/1659 and fixes https://github.com/ethereum/remix-ide/issues/1644.

But this is a nasty workaround - we still need a more permanent solution, which probably means to move towards wasm.

### CODE REVIEW

File: libevmasm/RuleList.h [hunk 1]
```diff
@@ -163,16 +199,13 @@ std::vector<SimplificationRule<Pattern>> simplificationRuleListPart1(
 }
 
 
-// This part of simplificationRuleList below was split out to prevent
```
Comment (axic) [inline libevmasm/RuleList.h:166]: Maybe move this to the top saying the rules are split due to JS?

Comment (ekpyron) [reply libevmasm/RuleList.h:166]: There was a copy of this at the top already - I just rephrased it slightly now.

**Review by axic — APPROVED** [review]
