### PR TITLE
Fix Via-IR bytecode divergence when compiling multiple files that are already included via imports

### LINKED ISSUE #14541: Via-IR bytecode differences when explicitly requesting a file that would be pulled by an import
Originally reported in https://github.com/ethereum/solidity/issues/14494#issuecomment-1692358415.

## Description
Explicitly requesting compilation of a file that is already included via imports may in certain situations affect the order in which Yul functions are placed in the IR output, which causes bytecode differences. This is apparently due to different AST IDs assigned to those functions.

The problem manifests both with and without optimizer. Only the IR pipeline is affected.

## Environment

- Compiler version: 0.8.21

## Steps to Reproduce
```bash
mkdir @

cat <<=== > a.sol
    import "@/za.sol";
    import "b.sol";

    contract A is B {
        function a() public pure {
            zb();
        }
    }
===

cat <<=== > b.sol
    import "@/zb.sol";
    import "c.sol";

    abstract contract B is C {}
===

cat <<=== > c.sol
    abstract contract C
    {
        function f() public pure {}

        function c() public view returns (uint) {
            try this.f() { return 0; }
            catch {}
        }
    }
===

cat <<=== > @/za.sol
    import "@/zc.sol";
===

cat <<=== > @/zb.sol
    import "@/zc.sol";

    function zb() pure {
        zc();
    }
===

cat <<=== > @/zc.sol
    function zc() pure returns (bytes memory returndata) {
        if (returndata.length == 0) {
            return "";
        }
    }
===

diff --color --unified \
    <(solc a.sol b.sol --bin --via-ir | grep '======= a.sol:A =======' --after-context=2 | fold --width 100) \
    <(solc a.sol       --bin --via-ir | grep '======= a.sol:A =======' --after-context=2 | fold --width 100)

diff --color --unified \
    <(solc a.sol b.sol --ir) \
    <(solc a.sol       --ir)
```

I could not go below 6 files or get rid of a subdirectory, though I suspect this is needed only due to the way it affects the import/compilation order and examples without it should be possible as well.

The import pattern goes like this:

```
a──►za──►zc
│         ▲
▼         │
b──►zb────┘
│
▼
c
```

But the pattern itself is not enough. The `try`/`catch` and all the other calls are necessary and must also be placed in specific files.

### PR DESCRIPTION
**Pull request by r0qs**
Fixes https://github.com/ethereum/solidity/issues/14541.

### CODE REVIEW

File: libsolidity/codegen/ir/IRGenerationContext.h [hunk 1]
```diff
@@ -37,27 +37,16 @@
...
-		// NULLs always first.
-		if (_f1 != nullptr && _f2 != nullptr)
-			return _f1->id() < _f2->id();
-		else
-			return _f1 == nullptr;
-	}
-};
-
-using DispatchSet = std::set<FunctionDefinition const*, AscendingFunctionIDCompare>;
+using DispatchQueue = std::queue<FunctionDefinition const*>;
```
Comment (r0qs) [inline libsolidity/codegen/ir/IRGenerationContext.h]: I used a `queue` here so we can have constant time processing the functions for codegen in FIFO order, and I kept the `set` for logarithmic search in the `m_internalDispatchMap`, but maybe this could also be replace by a queue or a vector, but then we would have linear search.

**Comment by ekpyron** [comment]
Ah, ok - you said that bytecode comparison was failing - I thought you only meant in the new "randomized AST IDs" version, but it looks like it's also failing just due to this change?
I guess that means that we do not *always* add functions to this queue in a deterministic order after all, so we still need to check that.

**Comment by cameel** [comment]
It's probably the fact that `AscendingFunctionIDCompare` was removed from the definition of `DispatchSet` so it now sorts based on pointer addresses.

**Comment by nikola-matic** [comment]
> It's probably the fact that `AscendingFunctionIDCompare` was removed from the definition of `DispatchSet` so it now sorts based on pointer addresses.

This will just default to `std::less`, which should have well defined total ordering, right?

File: libsolidity/codegen/ir/IRGenerationContext.h [hunk 2]
```diff
@@ -37,27 +37,16 @@
...
 
 class YulUtilFunctions;
 class ABIFunctions;
 
-struct AscendingFunctionIDCompare
-{
-	bool operator()(FunctionDefinition const* _f1, FunctionDefinition const* _f2) const
-	{
-		// NULLs always first.
-		if (_f1 != nullptr && _f2 != nullptr)
```
Comment (nikola-matic) [inline libsolidity/codegen/ir/IRGenerationContext.h:53]: The only place where we perform an insertion is 
```
std::string IRGenerationContext::enqueueFunctionForCodeGeneration(FunctionDefinition const& _function)
```
which accepts `FunctionDefinition` by reference, so were these nullptr checks even necessary? Unless we're using `AscendingFunctionIDCompare` elsewhere?

**Comment by cameel** [comment]
> This will just default to `std::less`, which should have well defined total ordering, right?

Ordering is well defined, but it does not help when addresses are different on each run :)

**Comment by nikola-matic** [comment]
> > This will just default to `std::less`, which should have well defined total ordering, right?
> 
> Ordering is well defined, but it does not help when addresses are different on each run :)

Ah, right as always @cameel :)

**Comment by r0qs** [comment]
> It's probably the fact that `AscendingFunctionIDCompare` was removed from the definition of `DispatchSet` so it now sorts based on pointer addresses.

Yes, I thought that it should not interfere in code generation, but I guess I was wrong. The function `IRGenerationContext::initializeInternalDispatch` iterates over the set and calls `enqueueFunctionForCodeGeneration`, so it affects the order as well, as you pointed out. I completely replaced the set by a queue, and this should fix the problem now.

**Comment by cameel** [comment]
It would be best if we could add the repro from the issue as a test. How about adding a custom CLI test in the same vein as e.g. [`~via_ir_equivalence`](https://github.com/ethereum/solidity/blob/develop/test/cmdlineTests/~via_ir_equivalence/test.sh)?

BTW, note that these custom CLI test can be written directly in Python. The current ones are all Bash simply because they used to be a part of `cmdlineTests.sh`.

**Comment by r0qs** [comment]
> It would be best if we could add the repro from the issue as a test. How about adding a custom CLI test in the same vein as e.g. [`~via_ir_equivalence`](https://github.com/ethereum/solidity/blob/develop/test/cmdlineTests/~via_ir_equivalence/test.sh)?
> 
> BTW, note that these custom CLI test can be written directly in Python. The current ones are all Bash simply because they used to be a part of `cmdlineTests.sh`.

Indeed. I did it in another branch to ease the review process. Please let me know if that is what you have in mind https://github.com/ethereum/solidity/pull/14565.

File: libsolidity/codegen/ir/IRGenerationContext.cpp [hunk 3]
```diff
@@ -152,13 +153,13 @@ void IRGenerationContext::addToInternalDispatch(FunctionDefinition const& _funct
...
-		// Note that m_internalDispatchMap[arity] is a set with a custom comparator, which looks at function IDs not definitions
-		solAssert(*m_internalDispatchMap[arity].find(&_function) == &_function, "Different definitions with the same function ID");
-
-	m_internalDispatchMap[arity].insert(&_function);
-	enqueueFunctionForCodeGeneration(_function);
+	auto it = ranges::find(m_internalDispatchMap[arity], &_function);
+	if (it != ranges::end(m_internalDispatchMap[arity]))
+		solAssert(*it == &_function, "Different definitions with the same function ID");
+	else {
+		m_internalDispatchMap[arity].push_back(&_function);
```
Comment (cameel) [inline libsolidity/codegen/ir/IRGenerationContext.cpp]: Do we have a test against duplicates in the dispatch? If not, please add a case like this:
```solidity
contract C {
    function a() internal {}
    function f() public {
        function () ptr1 = a;
        function () ptr2 = a;
    }
}
```

The easiest way to check would probably be to remove the check against duplicates in `IRGenerationContext::addToInternalDispatch()`, run semantic tests and see if any of them fails.

File: libsolidity/codegen/ir/IRGenerationContext.cpp [hunk 4]
```diff
@@ -152,13 +153,13 @@ void IRGenerationContext::addToInternalDispatch(FunctionDefinition const& _funct
...
-
-	if (m_internalDispatchMap.count(arity) != 0 && m_internalDispatchMap[arity].count(&_function) != 0)
-		// Note that m_internalDispatchMap[arity] is a set with a custom comparator, which looks at function IDs not definitions
-		solAssert(*m_internalDispatchMap[arity].find(&_function) == &_function, "Different definitions with the same function ID");
-
-	m_internalDispatchMap[arity].insert(&_function);
-	enqueueFunctionForCodeGeneration(_function);
+	auto it = ranges::find(m_internalDispatchMap[arity], &_function);
+	if (it != ranges::end(m_internalDispatchMap[arity]))
+		solAssert(*it == &_function, "Different definitions with the same function ID");
```
Comment (cameel) [inline libsolidity/codegen/ir/IRGenerationContext.cpp]: This assert is ineffective now. It will never fail:
- if we have the same exact `FunctionDefinition` object, we'll enter `else`.
- if we have a different `FunctionDefinition` that for some wild reason happens to share the ID, the assert will succeed because `find()` will never find that definition (it's no longer a set with a comparator so the comparison is between pointers).

I'd remove it from here and instead add a sanity check in `IRGenerator::generateInternalDispatchFunctions()`. That function used to be able to assume no duplicates because it was receiving a set. Now that it gets a queue, it should assert that items in it have unique IDs.

File: Changelog.md [hunk 5]
```diff
@@ -12,6 +12,7 @@ Compiler Features:
 
 Bugfixes:
  * AST: Fix wrong initial ID for Yul nodes in the AST.
+ * Code Generator: Fix Via-IR bytecode divergence when compiling multiple files that are already included via imports. In some cases, the order in which function definitions were discovered by the IR generator during AST traversal would lead to different bytecodes. This issue affected only the IR pipeline.
```
Comment (cameel) [inline Changelog.md]: How about this?
```suggestion
 * Code Generator: Fix output from via-IR code generator being dependent on which files were discovered by import callback. In some cases, a different AST ID assignment would alter the order of functions in internal dispatch, resulting in superficially different but semantically equivalent bytecode.
```

**Review by cameel — COMMENTED** [review]
Needs some small tweaks, but overall looks like a good solution.

File: libsolidity/codegen/ir/IRGenerationContext.cpp (hunk 3 above)
Comment (r0qs) [reply libsolidity/codegen/ir/IRGenerationContext.cpp]: We do not as far as I could see. I added the test and ran it as you suggested, removing the check against duplicates, and it throws an error as expected:
```
Invalid IR generated:
Error: Duplicate case "1" defined.
```

File: libsolidity/codegen/ir/IRGenerationContext.cpp (hunk 4 above)
Comment (r0qs) [reply libsolidity/codegen/ir/IRGenerationContext.cpp]: Ops, indeed. I added an assertion there to check if a function definition with the same ID is processed more than once.

**Review by cameel — COMMENTED** [review]
In terms of correctness this looks fine.

I added some small tweaks. If you're fine with them, please squash and we can merge it.

**Review by cameel — APPROVED** [review]
