### PR TITLE
Fix implementation of leave.

### LINKED ISSUE #8960: Support for call* functions when compiling to ewasm
When compiling Yul -> ewasm, `call`, `staticcall`, `delegatecall` etc. are not included in the final bytecode, nor in the `.wat` output. No Ethereum Interface imports are added for them to the wasm module.

Example: https://gist.github.com/loredanacirstea/d8da062392b7c165976bbc25a183149e

```
object "TestWasm9" {
    code {
        datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
        return(0, datasize("Runtime"))
    }
    object "Runtime" {
        code {
            let _calldata := 96
            calldatacopy(_calldata, 0, calldatasize())

            let addr := mslice(_calldata, 20)
            let input_ptr := add(_calldata, 20)

            // callStatic
            let success := staticcall(gas(), addr, input_ptr, 4, 0, 0)
            mstore(0, success)
            
            return (0, 32)
            
            function mslice(position, length) -> result {
              if gt(length, 32) { revert(0, 0) }
              result := div(mload(position), exp(2, sub(256, mul(length, 8))))
            }
        }
    }
}

```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/8960

### CODE REVIEW

File: libyul/backends/wasm/WasmCodeTransform.cpp [hunk 1]
```diff
@@ -280,7 +280,7 @@ wasm::Expression WasmCodeTransform::operator()(Continue const&)
 
 wasm::Expression WasmCodeTransform::operator()(Leave const&)
 {
-	return wasm::Return{};
+	return wasm::Branch{wasm::Label{m_functionBodyLabel}};
```
Comment (axic) [inline libyul/backends/wasm/WasmCodeTransform.cpp:284]:
```suggestion
    yulAssert(!m_functionBodyLabel.empty(), "");
	return wasm::Branch{wasm::Label{m_functionBodyLabel}};
```

File: libyul/backends/wasm/WasmCodeTransform.cpp [hunk 2]
```diff
@@ -330,10 +330,15 @@ wasm::FunctionDefinition WasmCodeTransform::translateFunction(yul::FunctionDefin
 	fun.returns = !_fun.returnVariables.empty();
 
 	yulAssert(m_localVariables.empty(), "");
-	fun.body = visit(_fun.body.statements);
+	m_functionBodyLabel = newLabel();
```
Comment (axic) [inline libyul/backends/wasm/WasmCodeTransform.cpp:335]:
```suggestion
    yulAssert(m_functionBodyLabel.empty(), "");
	m_functionBodyLabel = newLabel();
```

**Comment by chriseth** [comment]
This seems to increase the code length quite a lot, but there are still tons of optimizations with regards to wasm binary, so I think it's fine.
