### PR TITLE
[Yul] Require equal types for switch cases and detect duplicates by number value.

### LINKED ISSUE #5792: [Yul] Switch analysis does not detect duplicate cases for distinct number literals with equal value..
```
{
        switch 1
        case 0 { mstore(0, 1) }
        case 0 { mstore(0, 2) }
        case 1 { mstore(0, 3) }
        default { mstore(0, 4) }
}

Error analyzing source.
:4:2: Error: Duplicate case defined
        case 0 { mstore(0, 2) }
```

Whereas

```
{
        switch 1
        case 0 { mstore(0, 1) }
        case 0x0 { mstore(0, 2) }
        case 1 { mstore(0, 3) }
        default { mstore(0, 4) }
}
// no error
```

Came up in #5776 and it will probably make sense to adjust switch case handling in ``SyntacticallyEqual``, if/when this is fixed.

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #5792.
References #2324.

Came up during #5776 and will allow to more reasonably sort switch cases for the syntactic equality comparison there.

EDIT: I'm not sure whether it was a deliberate design decision **not** to require matching types in switch cases so far.
EDIT: Also this is two things at once - let me know if I should split.

### CODE REVIEW

**Comment by ekpyron** [comment]
Damn - emscripten seems to require all ``.cpp`` files to be have distinct names, even if they are in different paths... strange thing to require IMO... Still, to work around renaming ``optimizer/Utilities.cpp`` to ``optimizer/OptimizerUtilities.cpp`` is probably best (I think it still makes sense to split into optimizer specific and general "Utilities")...

EDIT: renamed

File: libyul/Utilities.h [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+/**
+ * Linear order on Yul AST nodes.
+ *
+ * Defines a linear order on Yul AST nodes to be used in maps and sets.
+ * Note: the order is total and deterministic, but independent of the semantics, e.g.
+ * it is not guaranteed that the false Literal is "less" than the true Literal.
+ */
+template<typename T>
+struct Less
```
Comment (ekpyron) [inline libyul/Utilities.h:39]: Maybe this is unneccessarily general - it probably mostly makes sense for literals anyways, so I could just make it ``LiteralLess`` instead...

File: libyul/AsmAnalysis.cpp [hunk 2]
```diff
@@ -390,7 +391,29 @@ bool AsmAnalyzer::operator()(Switch const& _switch)
...
+				else if (caseType != _case.value->type)
+				{
+					mismatchingTypes = true;
+					break;
+				}
+			}
+		if (mismatchingTypes)
+			m_errorReporter.typeError(
+				_switch.location,
+				"Switch cases have non-matching types"
```
Comment (chriseth) [inline libyul/AsmAnalysis.cpp]:
```suggestion
				"Switch cases have non-matching types."
```

File: test/libyul/Parser.cpp [hunk 3]
```diff
@@ -304,6 +304,18 @@ BOOST_AUTO_TEST_CASE(if_statement_invalid)
 	BOOST_CHECK(successParse("{ if 42:u256 { } }"));
 }
 
+BOOST_AUTO_TEST_CASE(switch_case_types)
+{
+	CHECK_ERROR("{ switch 0:u256 case 0:u256 {} case 1:u32 {} }", TypeError, "Switch cases have non-matching types");
+	BOOST_CHECK(successParse("{ switch 0:u256 case 0:u32 {} case 1:u32 {} }"));
```
Comment (chriseth) [inline test/libyul/Parser.cpp:311]: Actually I think the type of the cases should be equal to the type of the expression - but I think we cannot yet determine that. Could you please add a comment to the test?

**Review by chriseth — DISMISSED** [review]

File: test/libyul/Parser.cpp (hunk 3 above)
Comment (ekpyron) [reply test/libyul/Parser.cpp:311]: Yes, for that we'd need to determine types for expressions - I'll add a comment.

File: libyul/AsmAnalysis.cpp (hunk 2 above)
Comment (ekpyron) [reply libyul/AsmAnalysis.cpp]: Ok, then I'll add a dot a few lines down as well, though :).

**Review by chriseth — APPROVED** [review]

**Comment by ekpyron** [comment]
Thinking about it: this might have warranted a changelog entry.

**Comment by axic** [comment]
This should go into the changelog.

Update: ah just seen you commented that :)
