### PR TITLE
Fix segmentation fault when  importing large AST from json file

### LINKED ISSUE #13179: solc: Stack overflow importing large AST from json file
## Description
Importing an AST with `--import-ast` using a large JSON file results in a stack overflow and segmentation fault with certain output options.

A quick run with memcheck shows that it stems from a regex match.

## Environment

- Compiler version: 0.8.16-develop.2022.6.21+commit.c3ea8661.mod.Linux.g++
- Target EVM version (as per compiler settings): london
- Operating system: Linux

## Steps to Reproduce

Create a large AST as JSON. Here is Uniswap V3 as an example (20.2 MB) from the external tests: [uniswap_ast.zip](https://github.com/ethereum/solidity/files/8946583/uniswap_ast.zip)

Try generating IR output - currently segfaults:
```
solc --import-ast ./164dbdb3af44e9eea766cd449cf8864c.json --ir
```

Try generating assembly from IR - currently segfaults:
```
solc --import-ast ./164dbdb3af44e9eea766cd449cf8864c.json --via-ir --asm
```

Regular assembly with the `--asm` flag only works as expected for this file.

### PR DESCRIPTION
**Pull request by matheusaaguiar**
Fixes #13179.

### CODE REVIEW

**Comment by matheusaaguiar** [comment]
Ok, so the solution is not so simple as I expected.

File: libyul/AsmParser.cpp [hunk 1]
```diff
@@ -152,6 +152,19 @@ void Parser::fetchDebugDataFromComment()
 	);
 
 	string_view commentLiteral = m_scanner->currentCommentLiteral();
+
+	// (ugly) workaround to avoid regex seg fault with too large strings
+	auto resizeIfGt = [&commentLiteral](size_t sizeLimit) {
+		if(commentLiteral.size() > sizeLimit)
```
Comment (stackenbotten) [inline libyul/AsmParser.cpp]: Coding style error

File: libyul/AsmParser.cpp [hunk 2]
```diff
@@ -154,6 +154,14 @@ void Parser::fetchDebugDataFromComment()
 	string_view commentLiteral = m_scanner->currentCommentLiteral();
 	match_results<string_view::const_iterator> match;
 
+	// (ugly) workaround to avoid regex seg fault with too large strings
+	size_t sizeLimit = 32 * 1024;
+	if (commentLiteral.size() > sizeLimit)
+	{
+		size_t resizeIndex = commentLiteral.find_first_of('\"');
+		commentLiteral = commentLiteral.substr(0, resizeIndex);
```
Comment (wechman) [inline libyul/AsmParser.cpp]: Can we do that without information lost?

Comment (matheusaaguiar) [reply libyul/AsmParser.cpp]: Apparently, yes. 
Nevertheless, I don't think this should be the final solution. I thought about it a little and I guess it requires an alternative method to handle the special case of large strings that regex_search can't handle.

Comment (wechman) [reply libyul/AsmParser.cpp]: Then, maybe we can just limit the string size in all cases without a need of differentiation between long and short strings?

Comment (matheusaaguiar) [reply libyul/AsmParser.cpp]: The problem is that sometimes you have more info (src location, ast id) after the code snippet and they need to be searched for and parsed. So, I implemented this workaround to only limit the string size if it would cause a seg fault.

File: liblangutil/CharStream.h [hunk 3]
```diff
@@ -138,6 +141,7 @@ class CharStream
 private:
 	std::string m_source;
 	std::string m_name;
+	bool m_imported_from_AST;
```
Comment (Marenz) [inline liblangutil/CharStream.h]: `bool m_imported_from_AST = false;`
or 
`bool m_imported_from_AST{false};`

would be better here (similar to the var below)

File: libyul/AsmPrinter.cpp [hunk 4]
```diff
@@ -278,7 +278,10 @@ string AsmPrinter::formatSourceLocation(
 	{
 		sourceIndex = to_string(_nameToSourceIndex.at(*_location.sourceName));
 
-		if (_debugInfoSelection.snippet && _soliditySourceProvider)
+		if (_debugInfoSelection.snippet &&
```
Comment (Marenz) [inline libyul/AsmPrinter.cpp]:
```suggestion
                if (
                    _debugInfoSelection.snippet &&
```

styling not quite correct

File: liblangutil/CharStream.h [hunk 5]
```diff
@@ -72,10 +72,13 @@ class CharStream
 public:
 	CharStream() = default;
 	CharStream(std::string _source, std::string _name):
-		m_source(std::move(_source)), m_name(std::move(_name)) {}
+		m_source(std::move(_source)), m_name(std::move(_name)), m_imported_from_AST(false) {}
```
Comment (Marenz) [inline liblangutil/CharStream.h]: maybe use line breaks here now, when it is getting so long?

**Review by Marenz — CHANGES_REQUESTED** [review]
lgtm, only minor changes. Please merge the commits as well :)

File: libyul/AsmPrinter.cpp (hunk 4 above)
Comment (Marenz) [reply libyul/AsmPrinter.cpp]: (ignore my fucked up space-based indentations, github makes it hard)

File: liblangutil/CharStream.h [hunk 6]
```diff
@@ -138,6 +144,7 @@ class CharStream
 private:
 	std::string m_source;
 	std::string m_name;
+	bool m_imported_from_AST{false};
```
Comment (Marenz) [inline liblangutil/CharStream.h]: I just realized you used snake-case here instead of camel case. I think we use camel case here (`m_importedFromAST`) (yes the m_ is the exception for member variables)

**Review by Marenz — CHANGES_REQUESTED** [review]
just one minor style thing I noticed then we're good to go

File: liblangutil/CharStream.h (hunk 6 above)
Comment (matheusaaguiar) [reply liblangutil/CharStream.h]: Oh, yes, I sometimes forget that ... I guess old habits die hard lol

**Review by Marenz — APPROVED** [review]
