### PR TITLE
Abstract contracts

### LINKED ISSUE #649: Explicit keyword for abstract contracts
Compiler doesn't produce errors, but returns empty bytecode when child contract does not call inherited constructor.

To reproduce:

```
contract parent {
  function parent(address _someValue) {}
}

contract child is parent {
//  Uncomment to fixes compilation
//  function child(address a) parent(a) {}
}
```

run `sold child.sol --bin`
output:

```

======= child =======
Binary: 


======= parent =======
Binary: 
60606040526040516020806038833981016040528080519060200190919050505b5b50600a80602e6000396000f360606040526008565b00
```

solc version:

```
solc, the solidity compiler commandline interface
Version: 0.3.4-0/RelWithDebInfo-Linux/g++/Interpreter
```

Expected: some error message that child must define constructor

### PR DESCRIPTION
**Pull request by aarlt**
Fixes #649 
Fixes https://github.com/ethereum/solidity/issues/3594

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

File: libsolidity/parsing/Parser.cpp [hunk 1]
```diff
@@ -242,14 +245,21 @@ ASTPointer<ImportDirective> Parser::parseImportDirective()
 	return nodeFactory.createNode<ImportDirective>(path, unitAlias, move(symbolAliases));
 }
 
-ContractDefinition::ContractKind Parser::parseContractKind()
+ContractDefinition::ContractKind Parser::parseContractKind(bool *_isAbstract)
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: Please use parameters only for input and return values for output. You can use an `std::tuple` or `std::pair`.

File: libsolidity/parsing/Parser.cpp [hunk 2]
```diff
@@ -242,14 +245,21 @@ ASTPointer<ImportDirective> Parser::parseImportDirective()
...
 	switch(m_scanner->currentToken())
 	{
 	case Token::Interface:
 		kind = ContractDefinition::ContractKind::Interface;
 		break;
+	case Token::Abstract:
+		*_isAbstract = true;
+		kind = ContractDefinition::ContractKind::Contract;
+		if (Token::Contract != m_scanner->next())
+			fatalParserError(string("Only contracts can be abstract."));
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: This should not be a fatal error. Just assume it is not abstract in the other case.

File: libsolidity/ast/AST.h [hunk 3]
```diff
@@ -435,6 +437,7 @@ class ContractDefinition: public Declaration, public Documented
 	std::vector<ASTPointer<InheritanceSpecifier>> m_baseContracts;
 	std::vector<ASTPointer<ASTNode>> m_subNodes;
 	ContractKind m_contractKind;
+	bool m_isAbstract{false};
```
Comment (chriseth) [inline libsolidity/ast/AST.h]: Needs a function that returns `m_isAbstract`. Also please just use `m_abstract`.

**Comment by chriseth** [comment]
Please also make changes to `ASTJsonConverter`.

**Comment by chriseth** [comment]
Please test that:
 - a contract with unimplemented functions (either directly in that contract or inherited) produces an error: "should be marked abstract" or something like that

File: libsolidity/parsing/Parser.cpp (hunk 2 above)
Comment (aarlt) [reply libsolidity/parsing/Parser.cpp]: Are you sure? From my point of view it will probably confusing if someone wrote `abstract interface` or `abstract library`.

Comment (chriseth) [reply libsolidity/parsing/Parser.cpp]: Of course it should be an error, just not a fatal one. The difference is that parsing continues after non-fatal errors while it stops after fatal errors.

Comment (aarlt) [reply libsolidity/parsing/Parser.cpp]: ah yes :)

**Comment by aarlt** [comment]
@chriseth Hmm.. I just started to fix the tests related to `cmdlineTests.sh`.. the current implementation of the `TypeChecker` creates an error if unimplemented functions where detected in a contract not marked as abstract.. if we use errors, we will need to change the related contracts used by `cmdlineTests.sh`, e.g.
```
Compiling various other contracts and libraries...
 - MultiSigWallet/
 - corion/
 - gnosis/
Unexpected compilation result:
Expected failure: 0 - Expected warning / error output: 1
Was failure: 1

Warning: This declaration shadows an existing declaration.
Note: The shadowed declaration is here:

Error: Contract "Token" should be marked as abstract.

Error: Contract "Oracle" should be marked as abstract.

Error: Contract "Event" should be marked as abstract.

Error: Contract "Market" should be marked as abstract.

Error: Contract "MarketMaker" should be marked as abstract.

Error: Contract "MarketFactory" should be marked as abstract.
```
Should the `TypeChecker` create an error or a warning related to "should be marked as abstract"?

**Comment by aarlt** [comment]
Probably it's better that the `TypeChecker` is only creating a warning for "should be marked as abstract". With this there is no need to actually change any contracts - but I'm not sure whether its better to be more strict here.

File: libsolidity/analysis/TypeChecker.cpp [hunk 4]
```diff
@@ -88,6 +88,14 @@ bool TypeChecker::visit(ContractDefinition const& _contract)
 	for (auto const& n: _contract.subNodes())
 		n->accept(*this);
 
+	if (_contract.contractKind() == ContractDefinition::ContractKind::Contract &&
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Can you move this to the end of `ContractLevelChecker::checkAbstractFunctions`?

Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: Also please format as
```
if (
  A &&
  B &&
  C
)
```

File: libsolidity/parsing/Parser.cpp [hunk 5]
```diff
@@ -242,14 +245,31 @@ ASTPointer<ImportDirective> Parser::parseImportDirective()
...
+		if (Token::Abstract == m_scanner->peekNextToken())
+		{
+			m_scanner->next();
+			fatalParserError(string("Contract expected."));
+		}
+		else
+			if (Token::Contract ==  m_scanner->peekNextToken())
+				abstract = true;
+			else
+				parserError(string("Only contracts can be abstract."));
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: Maybe move this to the ContractLevelChecker instead? Then you could also have a check for parsing the `abstract` keyword in another step before this switch and not modify the switch at all - then you would also not need any peek-calls.

Comment (aarlt) [reply libsolidity/parsing/Parser.cpp]: Hmm.. I'm not sure that I understood this correctly.. do you mean that the part of parsing of the `abstract` keyword should be moved to the `ContractLevelChecker`? So that the `ContractLevelChecker` is responsible for parsing the `abstract` keyword?

Comment (chriseth) [reply libsolidity/parsing/Parser.cpp]: I meant parse `abstract` here and do not check whether the next token is contract/interface, etc and only check that later in the contractlevelchecker

Comment (aarlt) [reply libsolidity/parsing/Parser.cpp]: Ah yes!

File: docs/contracts/abstract-contracts.rst [hunk 6]
```diff
@@ -10,15 +10,15 @@ Contracts are marked as abstract when at least one of their functions lacks an i
```
Comment (aarlt) [inline docs/contracts/abstract-contracts.rst:14]: I guess the documentation should also be modified, right?

File: docs/grammar.txt [hunk 7]
```diff
@@ -7,7 +7,7 @@ ImportDirective = 'import' StringLiteral ('as' Identifier)? ';'
         | 'import' ('*' | Identifier) ('as' Identifier)? 'from' StringLiteral ';'
         | 'import' '{' Identifier ('as' Identifier)? ( ',' Identifier ('as' Identifier)? )* '}' 'from' StringLiteral ';'
 
-ContractDefinition = ( 'contract' | 'library' | 'interface' ) Identifier
+ContractDefinition = 'abstract'* ( 'contract' | 'library' | 'interface' ) Identifier
```
Comment (aarlt) [inline docs/grammar.txt]: Currently the parser is accepting `'abstract'*`. Should this be changed? What level of "abstraction" should be reflected with this `grammar.txt`? Just how the parser is basically implemented, or should this also reflect actual "semantics", e.g. that only contracts can be abstract. Then it would be probably something like

```
ContractDefinition = (('abstract'* 'contract') | 'library' | 'interface' ) Identifier
```

A question is also, whether `'abstract'*` is ok, or the parser should also be changed that only one or zero `abstract` tokens are accepted.

@chriseth

**Comment by aarlt** [comment]
@chriseth I just saw that you referenced https://github.com/ethereum/solidity/issues/3594 .. I was now thinking whether it would be helpful to add the not implemented functions to the "should be marked as abstract" error. Something like "Contract "B" should be marked as abstract, because function supportsInterface(bytes4 interfaceID) external view returns (bool), function bla() and function blaaaa() where not implemented". What do you think?

**Comment by aarlt** [comment]
probably it's nicer to just write the function name and not the full signatures..

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 8]
```diff
@@ -266,6 +266,21 @@ void ContractLevelChecker::checkAbstractFunctions(ContractDefinition const& _con
...
+		_contract.abstract() && _contract.contractKind() != ContractDefinition::ContractKind::Contract
+	)
+		m_errorReporter.typeError(_contract.location(), "Only contracts can be abstract.");
+
+	if (
+		_contract.contractKind() == ContractDefinition::ContractKind::Contract &&
+		!_contract.annotation().unimplementedFunctions.empty() &&
+		!_contract.abstract()
+	)
+		m_errorReporter.typeError(
```
Comment (aarlt) [inline libsolidity/analysis/ContractLevelChecker.cpp:403]: @chriseth what about something like this
```cpp
		std::stringstream stream;
		if ( _contract.annotation().unimplementedFunctions.size() == 1)
			stream << "function";
		else
			stream << "functions";
		for (const auto& function : _contract.annotation().unimplementedFunctions) {
			stream << " " << function->name();
			if (function != *(_contract.annotation().unimplementedFunctions.rbegin()))
				stream << ",";
		}
		if ( _contract.annotation().unimplementedFunctions.size() == 1)
			stream << " was not implemented.";
		else
			stream << " where not implemented.";
		m_errorReporter.typeError(_contract.location(),
		                          "Contract \"" + _contract.annotation().canonicalName
		                              + "\" should be marked as abstract, because the " + stream.str());
```

**Comment by aarlt** [comment]
@chriseth any news on this? for me the question is whether we want to output what functions where not be implemented, i think it may make much sense to add these information to the "should be marked as abstract" error. what do you think?

File: docs/grammar.txt (hunk 7 above)
Comment (aarlt) [reply docs/grammar.txt]: @chriseth is `'abstract'*` ok?

File: libsolidity/parsing/Parser.cpp [hunk 9]
```diff
@@ -91,6 +91,9 @@ ASTPointer<SourceUnit> Parser::parse(shared_ptr<Scanner> const& _scanner)
 			case Token::Import:
 				nodes.push_back(parseImportDirective());
 				break;
+			case Token::Abstract:
+				nodes.push_back(parseContractDefinition());
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: Can be fall-through.

File: libsolidity/parsing/Parser.cpp [hunk 10]
```diff
@@ -244,14 +247,20 @@ ASTPointer<ImportDirective> Parser::parseImportDirective()
...
+	bool abstract = false;
 	switch(m_scanner->currentToken())
 	{
 	case Token::Interface:
 		kind = ContractDefinition::ContractKind::Interface;
 		break;
+	case Token::Abstract:
+		abstract = true;
+		m_scanner->next();
+		kind = parseContractKind().first;
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: Why do you make a recursive call here? Wouldn't it be simpler to just check the token to be abstract or something else, consume it if it is abstract and then enter the switch?

File: docs/contracts/abstract-contracts.rst [hunk 11]
```diff
@@ -6,27 +6,27 @@
 Abstract Contracts
 ******************
 
-Contracts are marked as abstract when at least one of their functions lacks an implementation as in the following example (note that the function declaration header is terminated by ``;``)::
+Contracts need to be marked as abstract when at least one of their functions lacks an implementation as in the following example (note that the function declaration header is terminated by ``;``)::
```
Comment (chriseth) [inline docs/contracts/abstract-contracts.rst]: What about the converse? Can you mark a contract as abstract when all functions have an implementation? Please also explain what "mark as abstract" means specifically.

File: docs/grammar.txt (hunk 7 above)
Comment (chriseth) [reply docs/grammar.txt]: Please only allow `'abstrat'?` both in the grammar and the parser.

File: Changelog.md [hunk 12]
```diff
@@ -10,6 +10,7 @@ Breaking changes:
  * General: New reserved keywords: ``virtual``.
  * Standard JSON Interface: Add option to disable or choose hash method between IPFS and Swarm for the bytecode metadata.
  * Syntax: ``push(element)`` for dynamic storage arrays do not return the new length anymore.
+ * Syntax: abstract contracts need now to be marked explicitly as abstract by using the ``abstract`` keyword.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Syntax: Abstract contracts need to be marked explicitly as abstract by using the ``abstract`` keyword.
```

File: docs/contracts/abstract-contracts.rst [hunk 13]
```diff
@@ -6,27 +6,31 @@
 Abstract Contracts
 ******************
 
-Contracts are marked as abstract when at least one of their functions lacks an implementation as in the following example (note that the function declaration header is terminated by ``;``)::
+Contracts need to be marked as abstract when at least one of their functions was not implemented.
```
Comment (chriseth) [inline docs/contracts/abstract-contracts.rst:9]: Please add: You can also mark contracts as abstract even though all functions are implemented.

File: docs/contracts/abstract-contracts.rst [hunk 14]
```diff
@@ -6,27 +6,31 @@
...
+This can be done by using the ``abstract`` keyword as shown in the following example. Note, that this contract need to be
+defined as abstract, because the function ``utterance()`` was defined, but no implementation was provided (no implementation body ``{ }`` was given).::
```
Comment (chriseth) [inline docs/contracts/abstract-contracts.rst]: Please put the `::` on a line of its own.

File: docs/contracts/abstract-contracts.rst [hunk 15]
```diff
@@ -6,27 +6,31 @@
...
 
     pragma solidity >=0.4.0 <0.7.0;
 
-    contract Feline {
+    abstract contract Feline {
         function utterance() public returns (bytes32);
     }
 
-Such contracts cannot be compiled (even if they contain implemented functions alongside non-implemented functions), but they can be used as base contracts::
+Such abstract contracts can only be used as base contracts. This is also true, if an abstract contract itself does implement
```
Comment (chriseth) [inline docs/contracts/abstract-contracts.rst]: I'm not sure what you mean by "only be used as base contracts". They can also be used to contain function definitions, define types, etc.

The main thing that can not be done with abstract contracts is creating them directly with the `new` operator and requesting their bytecode from the compiler.

File: docs/contracts/abstract-contracts.rst [hunk 16]
```diff
@@ -6,27 +6,31 @@
...
+    abstract contract Feline {
         function utterance() public returns (bytes32);
     }
 
     contract Cat is Feline {
         function utterance() public returns (bytes32) { return "miaow"; }
     }
 
-If a contract inherits from an abstract contract and does not implement all non-implemented functions by overriding, it will itself be abstract.
+If a contract inherits from an abstract contract and does not implement all non-implemented functions by overriding, it need to be marked as abstract as well.
```
Comment (chriseth) [inline docs/contracts/abstract-contracts.rst]:
```suggestion
If a contract inherits from an abstract contract and does not implement all non-implemented functions by overriding, it needs to be marked as abstract as well.
```

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 17]
```diff
@@ -266,6 +266,21 @@ void ContractLevelChecker::checkAbstractFunctions(ContractDefinition const& _con
 				_contract.annotation().unimplementedFunctions.push_back(function);
 				break;
 			}
+
+	if (
```
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]: This really does not fit in a single line?

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 8 above)
Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp:403]: Let's do this as a follow-up PR.

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 18]
```diff
@@ -266,6 +266,21 @@ void ContractLevelChecker::checkAbstractFunctions(ContractDefinition const& _con
...
+		m_errorReporter.typeError(_contract.location(), "Only contracts can be abstract.");
+
+	if (
+		_contract.contractKind() == ContractDefinition::ContractKind::Contract &&
+		!_contract.annotation().unimplementedFunctions.empty() &&
+		!_contract.abstract()
+	)
+		m_errorReporter.typeError(
+			_contract.location(),
+			"Contract \""+_contract.annotation().canonicalName + "\" should be marked as abstract."
```
Comment (chriseth) [inline libsolidity/analysis/ContractLevelChecker.cpp]:
```suggestion
			"Contract \"" + _contract.annotation().canonicalName + "\" should be marked as abstract."
```

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 8 above)
Comment (chriseth) [reply libsolidity/analysis/ContractLevelChecker.cpp:403]: Also, I think the unimplemented functions should be used together with the secondary source location feature.

File: libsolidity/analysis/TypeChecker.cpp [hunk 19]
```diff
@@ -2168,6 +2167,9 @@ void TypeChecker::endVisit(NewExpression const& _newExpression)
 		if (!contract->constructorIsPublic())
 			m_errorReporter.typeError(_newExpression.location(), "Contract with internal constructor cannot be created directly.");
 
+		if (contract->abstract())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: The check above (`unimplementedFunctions.empty()`) can now be removed or turned into an assertion below this check.

File: libsolidity/ast/AST.cpp [hunk 20]
```diff
@@ -151,7 +151,7 @@ bool ContractDefinition::constructorIsPublic() const
 
 bool ContractDefinition::canBeDeployed() const
 {
-	return constructorIsPublic() && annotation().unimplementedFunctions.empty();
+	return constructorIsPublic() && annotation().unimplementedFunctions.empty() && !abstract();
```
Comment (chriseth) [inline libsolidity/ast/AST.cpp:154]:
```suggestion
	return constructorIsPublic() && !abstract();
```

File: libsolidity/ast/AST.h [hunk 21]
```diff
@@ -388,13 +388,14 @@ class ContractDefinition: public Declaration, public Documented
...
-		ContractKind _contractKind = ContractKind::Contract
+		ContractKind _contractKind = ContractKind::Contract,
+		bool _abstract = false
 	):
 		Declaration(_location, _name),
 		Documented(_documentation),
 		m_baseContracts(_baseContracts),
 		m_subNodes(_subNodes),
-		m_contractKind(_contractKind)
+		m_contractKind(_contractKind), m_abstract(_abstract)
```
Comment (chriseth) [inline libsolidity/ast/AST.h]:
```suggestion
		m_contractKind(_contractKind),
		m_abstract(_abstract)
```

File: libsolidity/parsing/Parser.cpp [hunk 22]
```diff
@@ -273,7 +280,8 @@ ASTPointer<ContractDefinition> Parser::parseContractDefinition()
 	ASTPointer<ASTString> docString;
 	vector<ASTPointer<InheritanceSpecifier>> baseContracts;
 	vector<ASTPointer<ASTNode>> subNodes;
-	ContractDefinition::ContractKind contractKind = ContractDefinition::ContractKind::Contract;
+	std::pair<ContractDefinition::ContractKind, bool> contractKind =
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]:
```suggestion
	std::pair<ContractDefinition::ContractKind, bool> contractKind{};
```
should be enough.

File: libsolidity/parsing/Parser.h [hunk 23]
```diff
@@ -85,7 +85,7 @@ class Parser: public langutil::ParserBase
 	void parsePragmaVersion(langutil::SourceLocation const& _location, std::vector<Token> const& _tokens, std::vector<std::string> const& _literals);
 	ASTPointer<PragmaDirective> parsePragmaDirective();
 	ASTPointer<ImportDirective> parseImportDirective();
-	ContractDefinition::ContractKind parseContractKind();
+	std::pair<ContractDefinition::ContractKind, bool> parseContractKind();
```
Comment (chriseth) [inline libsolidity/parsing/Parser.h:90]: Please document the bool.

File: libsolidity/ast/AST.cpp (hunk 20 above)
Comment (aarlt) [reply libsolidity/ast/AST.cpp:154]: Looks like that `annotation().unimplementedFunctions.empty() ` is needed here, if an interface is used.

File: libsolidity/analysis/TypeChecker.cpp (hunk 19 above)
Comment (aarlt) [reply libsolidity/analysis/TypeChecker.cpp]: Ok, I removed the check above, but added `&&  !contract-> annotation().unimplementedFunctions.empty()` here.. so we will have the same error. We will later add the information about what functions where not be implemented.

File: libsolidity/ast/AST.cpp (hunk 20 above)
Comment (aarlt) [reply libsolidity/ast/AST.cpp:154]: The method `abstract()` only returns whether a contract was marked as abstract. So if e.g. an interface was used, there could be still unimplemented functions.

File: docs/contracts/abstract-contracts.rst (hunk 14 above)
Comment (aarlt) [reply docs/contracts/abstract-contracts.rst]: It looks like that it is not possible to just have `::` in one line.

File: libsolidity/ast/AST.cpp (hunk 20 above)
Comment (chriseth) [reply libsolidity/ast/AST.cpp:154]: Sure, but that will be caught by a different error elsewhere.

**Review by chriseth — APPROVED** [review]
