### PR TITLE
Fix handling of carriage return.

### LINKED ISSUE #11041: [yul] File with just a carriage return crashes with std::out_of_range (what():  basic_string_view::substr: __pos (which is 1) > __size (which is 0))
## Description

A yul file with just a carriage return "\r" (e.g., generated by something like this python code):

```
> f = open("cr.yul", 'w')
> f.write("\r")
> f.close()
```

produces a crash

```
> ../build/solc/solc cr.yul --strict-assembly
Warning: Yul is still experimental. Please use the output with care.
Error: Expected keyword "object".
 --> cr.yul:1:2:
  |
1 | terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string_view::substr: __pos (which is 1) > __size (which is 0)
Aborted
```

On master, using AFL fuzzing of yul inputs via '--strict-assembly'.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.3-develop.2021.3.3+commit.ad2ecf16.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04.1 LTS in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/11041

### CODE REVIEW

File: test/cmdlineTests/only_cr/args [hunk 1]
```diff
@@ -0,0 +1 @@
+--strict-assembly
```
Comment (cameel) [inline test/cmdlineTests/only_cr/args]: I'd rename the test to `strict_asm_only_cr` to match the naming of other tests and also to avoid naming conflicts if we ever need such a test for Solidity code.

File: test/cmdlineTests/only_cr/exit [hunk 2]
```diff
@@ -0,0 +1 @@
+0
```
Comment (cameel) [inline test/cmdlineTests/only_cr/exit]: Shouldn't it return non-zero on compilation error?

**Review by bshastry — DISMISSED** [review]
LGTM

File: test/cmdlineTests/only_cr/exit (hunk 2 above)
Comment (bshastry) [inline test/cmdlineTests/only_cr/exit]:
```suggestion
1
```

Comment (bshastry) [reply test/cmdlineTests/only_cr/exit]: Shouldn't parsing errors result in a `1` instead?

File: liblangutil/SourceReferenceExtractor.cpp [hunk 3]
```diff
@@ -106,7 +107,7 @@ SourceReference SourceReferenceExtractor::extract(SourceLocation const* _locatio
 		interest,
 		isMultiline,
 		line,
-		start.column,
-		end.column,
+		min(start.column, static_cast<int>(line.length())),
+		min(end.column, static_cast<int>(line.length()))
```
Comment (cameel) [inline liblangutil/SourceReferenceExtractor.cpp:111]: This does prevent the crash but I'm not sure it actually fixes the underlying issue.

I think that the problem might actually be in `source->lineAtPosition()`. It seems that it strips a single  `\r` character from the line which is the reason why `start` ends up being past the end of the line. For example if the line is `\r\r\r\r`, it returns `\r\r\r`. This is inconsistent with ` source->translatePositionToLineColumn()`, which just ignores `\r` characters completely.

Also, even after the fix the locations shown in error messages seem off. For example for `\rabc` you get this:
```
Warning: Yul is still experimental. Please use the output with care.
Error: Expected keyword "object".
 --> /tmp/cr.yul:1:2:
  |
abc
  |  ^^^
```

Comment (chriseth) [reply liblangutil/SourceReferenceExtractor.cpp:111]: Yes, that is indeed the underlying issue, but I still think that this is the best fix. The problem with `\rabc` is a different one.

Comment (cameel) [reply liblangutil/SourceReferenceExtractor.cpp:111]: Yeah, I think the problem is here:
https://github.com/ethereum/solidity/blob/661d11035b871aa1624bf568e3d476ef1bf25895/liblangutil/CharStream.cpp#L100-L101

It looks like it's meant to handle the `\r` left over after stripping `\n` on Windows. But for this to work correctly `translatePositionToLineColumn()` should also treat that `\r` in the same special way - as a part of the line ending - and it does not.

Comment (cameel) [reply liblangutil/SourceReferenceExtractor.cpp:111]: `translatePositionToLineColumn()` could be causing similar problems in other places that we just haven't detected yet.

File: test/cmdlineTests/only_cr/args (hunk 1 above)
Comment (mijovic) [reply test/cmdlineTests/only_cr/args]: Probably better to rename the test

File: liblangutil/SourceReferenceExtractor.cpp [hunk 4]
```diff
@@ -19,6 +19,7 @@
 #include <liblangutil/CharStream.h>
 #include <liblangutil/Exceptions.h>
 
+#include <algorithm>
```
Comment (mijovic) [inline liblangutil/SourceReferenceExtractor.cpp:22]: Is this include needed?

**Comment by chriseth** [comment]
Updated.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `f8e690e654d5f8305b78edad31bae21efb7aa1f5`:
```
Error: Trailing whitespace found:
test/cmdlineTests/strict_asm_only_cr/err:5:1 | 
test/cmdlineTests/strict_asm_only_cr/input.yul:1:^M

```
Please check that your changes are working as intended.

File: liblangutil/SourceReferenceExtractor.cpp (hunk 3 above)
Comment (chriseth) [reply liblangutil/SourceReferenceExtractor.cpp:111]: I think `translatePositionToLineColumn` is perfectly implemented according to the specification. It is `lineAtPosition` that is questionable.

Comment (chriseth) [reply liblangutil/SourceReferenceExtractor.cpp:111]: We could change `lineAtPosition` to remove all trailing whitespace....

**Comment by chriseth** [comment]
I think this PR is fine as it is. The changed function now returns a structure that is internally consistent.

File: liblangutil/SourceReferenceExtractor.cpp (hunk 3 above)
Comment (cameel) [reply liblangutil/SourceReferenceExtractor.cpp:111]: Just curious, which specification do you mean? Do we have newline handling documented somewhere?

> We could change `lineAtPosition` to remove all trailing whitespace....

Well, maybe. I wouldn't really expect `CharStream` to do such a transformation but on the other hand trailing whitespace is mostly meaningless so maybe it's better off that way anyway. I'd at least adjust the name in that case.

**Review by cameel — APPROVED** [review]
Well, it does fix the crash so we could just as well merge it and sort out the small details separately.

File: liblangutil/SourceReferenceExtractor.cpp (hunk 3 above)
Comment (chriseth) [reply liblangutil/SourceReferenceExtractor.cpp:111]: Ok, no specification, but rather something like "the simplest definition of "line number" that would make sense".
