### PR TITLE
Fix ICE caused by const structs with mappings

### LINKED ISSUE #9951: ICE in nativeMembers() when trying to initialize a constant struct using a hex literal
## Description

This contract:
```solidity
contract C {
    struct S {
        mapping(uint => uint) c;
    }
    S public constant e = 0x1212121212121212121212121212121212121212;
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.cpp(2403): Throw in function virtual MemberList::MemberMap solidity::frontend::StructType::nativeMembers(const solidity::frontend::ASTNode *) const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.3-develop.2020.10.2+commit.756e21a8.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by a3d4**
Fixes #9951.

The issue was introduced in d41eaeba5686828b85279057f3a7da8be0f9a8f9, PR #9146,
https://github.com/ethereum/solidity/pull/9146/files#diff-07335c711d9742b9c53a75648c7ad55cL2295-L2298.

Basically, `if + continue` was replaced with `solAssert`, which crashes with constant structs containing mappings:

```
contract C {
    struct S {
        mapping(uint => uint) c;
    }
    S public constant e;
}
```

The comment in the old code claims that the old behavior was intended. I restored it, but not completely sure if it is the right way to go. Skipping struct members looks suspicious :).

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -2400,7 +2400,10 @@ MemberList::MemberMap StructType::nativeMembers(ASTNode const*) const
 	{
 		TypePointer type = variable->annotation().type;
 		solAssert(type, "");
-		solAssert(!(location() != DataLocation::Storage && type->containsNestedMapping()), "");
+		// If we are not in storage, skip all members that cannot live outside of storage,
```
Comment (hrkrshnn) [inline libsolidity/ast/Types.cpp]: Previously  we allowed structs containing mappings in memory and skipped such members when this function was being called. Then the TypeChecker dissalowed such structs. Do you think you can keep the old code and add a check about constants?

File: test/libsolidity/syntaxTests/iceRegressionTests/const_struct_with_mapping.sol [hunk 2]
```diff
@@ -0,0 +1,10 @@
+contract C {
+    struct S {
+        mapping(uint => uint) c;
+    }
+    S public constant e = 0x1212121212121212121212121212121212121212;
+}
+// ----
+// TypeError 6280: (71-135): Types in storage containing (nested) mappings cannot be assigned to.
```
Comment (hrkrshnn) [inline test/libsolidity/syntaxTests/iceRegressionTests/const_struct_with_mapping.sol]: Perhaps one way to fix this would be to convert this regular type error into a fatal type error.

Comment (a3d4) [reply test/libsolidity/syntaxTests/iceRegressionTests/const_struct_with_mapping.sol]: The crash happens even without assignment, `S public constant e;` is sufficient. And it seems that `solAssert` happens before error reporting. I'll have a closer look, thanks!

File: libsolidity/analysis/ContractLevelChecker.cpp [hunk 3]
```diff
@@ -398,6 +398,13 @@ void ContractLevelChecker::checkExternalTypeClashes(ContractDefinition const& _c
 					);
 			}
 		for (VariableDeclaration const* v: contract->stateVariables())
+		{
+			if (v->isConstant() && v->type()->containsNestedMapping())
```
Comment (hrkrshnn) [inline libsolidity/analysis/ContractLevelChecker.cpp]: Is it possible to move this to type checker? Or is too late?

Comment (hrkrshnn) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Somewhere in here:
https://github.com/ethereum/solidity/blob/a83ad58109604bb4795a246b2ac4844faa2831af/libsolidity/analysis/TypeChecker.cpp#L499

Comment (a3d4) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Unfortunately it seems to be too late indeed. The assertion happens within `ContractLevelChecker`. Here is my stack:

```
solc.exe!solidity::frontend::StructType::nativeMembers(const solidity::frontend::ASTNode * __formal) Line 2406	C++
solc.exe!solidity::frontend::Type::members(const solidity::frontend::ASTNode * _currentScope) Line 355	C++
solc.exe!solidity::frontend::FunctionType::FunctionType(const solidity::frontend::VariableDeclaration & _varDecl) Line 2852	C++
[Inline Frame] solc.exe!std::make_unique(const solidity::frontend::VariableDeclaration &) Line 2539	C++
[Inline Frame] solc.exe!solidity::frontend::TypeProvider::createAndGet(const solidity::frontend::VariableDeclaration &) Line 203	C++
solc.exe!solidity::frontend::TypeProvider::function(const solidity::frontend::VariableDeclaration & _varDecl) Line 426	C++
solc.exe!solidity::frontend::ContractLevelChecker::checkExternalTypeClashes(const solidity::frontend::ContractDefinition & _contract) Line 403	C++
solc.exe!solidity::frontend::ContractLevelChecker::check(const solidity::frontend::ContractDefinition & _contract) Line 92	C++
solc.exe!solidity::frontend::ContractLevelChecker::check(const solidity::frontend::SourceUnit & _sourceUnit) Line 77	C++
solc.exe!solidity::frontend::CompilerStack::analyze() Line 374	C++
solc.exe!solidity::frontend::CompilerStack::compile(solidity::frontend::CompilerStack::State _stopAfter) Line 517	C++
solc.exe!solidity::frontend::CommandLineInterface::processInput() Line 1487	C++
solc.exe!main(int argc, char * * argv) Line 60	C++
```

Comment (hrkrshnn) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Can you add an assert for `v->type()` before this? Not entirely sure if all type resolution is complete at this stage.

**Comment by chriseth** [comment]
Constants can only be value types, so the struct is already an error.

**Comment by a3d4** [comment]
> Constants can only be value types, so the struct is already an error.

It might be a slightly different thing. We report a non-fatal error `"Constants of non-value type not yet implemented."` in `TypeChecker` already. That implies that one day they might work.

Here we have a nested mapping issue. Maybe `"Constants of non-value type not yet implemented. Besides, constants are located in memory and could not contain nested mappings anyway."` ? Sounds funny enough, but I would not mind to have it.

Another point is just moving the existing non-value-constants-not-implemented check from `TypeChecker` to `ContractLevelChecker` does not sound quite right. I think it belongs rather to `TypeChecker`, and it is nice to have it non-fatal.

File: libsolidity/analysis/ContractLevelChecker.cpp (hunk 3 above)
Comment (hrkrshnn) [reply libsolidity/analysis/ContractLevelChecker.cpp]: Perhaps we can skip going into the if condition on line 408 if `v->isConstant` is not a value type? Or maybe if it contains a nested mapping? Then the type checker can handle the error properly. Sounds a bit hacky, so not sure.

**Comment by chriseth** [comment]
@a3d4 type checker does analysis on expression level, the fact that a constant does not have a value type should be detected earlier, probably in the declarationtypechecker.

**Comment by a3d4** [comment]
@chriseth 
> the fact that a constant does not have a value type should be detected earlier, probably in the declarationtypechecker.

I moved the check to `DeclarationTypeChecker`. Was not sure if neighbor checks regarding const initialization should belong to `DeclarationTypeChecker` too, so left them in `TypeChecker` for now.

(There are a few failing builds, ~~but they do not seem to be relevant~~. Investigating.)

**Review by hrkrshnn — COMMENTED** [review]
Looks good. Can be merged if the tests pass.

**Comment by chriseth** [comment]
Looks good, but somehow causes an internal error in a documentation snippet.

**Comment by a3d4** [comment]
The error occurs in `StandardCompiler::compileSolidity(StandardCompiler::InputsAndSettings _inputsAndSettings)` when converting to Json:

```
if (compilerStack.state() >= CompilerStack::State::Parsed && (!compilerStack.hasError() || _inputsAndSettings.parserErrorRecovery))
	
        . . . .

        sourceResult["ast"] = ASTJsonConverter(false, compilerStack.state(), compilerStack.sourceIndices()).toJson(compilerStack.ast(sourceName));
```

due to `solAssert(!(location() != DataLocation::Storage && type->containsNestedMapping()), "");`.

For some reason, `compilerStack.hasError()` returns `false`, although `DeclarationTypeChecker` fails.

3fc486d may fix this.

But there are three more similar `return false;` in `CompilerStack::analyze()` right before the fix (lines 353, 360, 366 (sorry, links do not work)).

Should `m_hasError` be set to `true` always before returning `false` from `CompilerStack::analyze()`?

File: libsolidity/interface/CompilerStack.cpp [hunk 4]
```diff
@@ -368,7 +368,10 @@ bool CompilerStack::analyze()
 		DeclarationTypeChecker declarationTypeChecker(m_errorReporter, m_evmVersion);
 		for (Source const* source: m_sourceOrder)
 			if (source->ast && !declarationTypeChecker.check(*source->ast))
+			{
+				m_hasError = true;
 				return false;
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Can you fix this in a uniform way, by either moving the inner part of the try/catch into a function that returns a bool and the caller of that function sets `m_hasError` appropriately? Then the `if (noErrors)` can be replaced by a return.
 -

Comment (a3d4) [reply libsolidity/interface/CompilerStack.cpp]: I made a few commits to simplify review, should be squashed afterwards.

Minor behavior changes are introduced in daba02b, they cause a few tests to fail (including command line tests). I updated the expectations, please double check if it is OK.

File: test/libsolidity/ASTJSON/assembly/nested_functions.json [hunk 5]
```diff
@@ -94,6 +94,7 @@
               }
             ]
           },
+          "functionSelector": "26121ff0",
```
Comment (hrkrshnn) [inline test/libsolidity/ASTJSON/assembly/nested_functions.json]: Why does this show up now?

File: libsolidity/interface/CompilerStack.cpp [hunk 6]
```diff
@@ -411,73 +408,62 @@ bool CompilerStack::analyzeInternal()
...
+				for (ASTPointer<ASTNode> const& node: source->ast->nodes())
+					if (ContractDefinition* contract = dynamic_cast<ContractDefinition*>(node.get()))
+						ImmutableValidator(m_errorReporter, *contract).analyze();
+
+		// Control flow graph generator and analyzer. It can check for issues such as
+		// variable is used before it is assigned to.
+		CFG cfg(m_errorReporter);
+		for (Source const* source: m_sourceOrder)
+			if (source->ast && !cfg.constructFlow(*source->ast))
+				noErrors = false;
```
Comment (hrkrshnn) [inline libsolidity/interface/CompilerStack.cpp]: Can you replace this line by `return false;`? Would that work?

**Review by hrkrshnn — COMMENTED** [review]
Also missing a changelog

File: libsolidity/interface/CompilerStack.cpp (hunk 6 above)
Comment (a3d4) [reply libsolidity/interface/CompilerStack.cpp]: That would be tempting indeed, but would stop on the first erroneous source instead of analyzing others. I think the idea was to run via all sources and report all errors, and I tried to keep the old behavior.

(And the same for other similar loops.)

Comment (hrkrshnn) [reply libsolidity/interface/CompilerStack.cpp]: Ah, I forgot that we were in a for loop.

File: test/libsolidity/ASTJSON/assembly/nested_functions.json (hunk 5 above)
Comment (a3d4) [reply test/libsolidity/ASTJSON/assembly/nested_functions.json]: I did not make full analysis, but daba02b introduces a minor change, setting `AnalysisPerformed` at the end of `CompilerStack::analyze()` always.

And we have code that might be impacted (`m_stackState > CompilerStack::State::ParsedAndImported`)

```
if (_node.isPartOfExternalInterface() && m_stackState > CompilerStack::State::ParsedAndImported)
    attributes.emplace_back("functionSelector", _node.externalIdentifierHex());
```

File: libsolidity/interface/CompilerStack.cpp [hunk 7]
```diff
@@ -331,6 +331,16 @@ bool CompilerStack::analyze()
 		if (source->ast)
 			Scoper::assignScopes(*source->ast);
 
+	bool ok = analyzeInternal();
+
+	m_stackState = AnalysisPerformed;
```
Comment (hrkrshnn) [inline libsolidity/interface/CompilerStack.cpp]: @chriseth Can you check this line? This leads to some changes in tests https://github.com/ethereum/solidity/pull/9959/files#r528634568

Comment (a3d4) [reply libsolidity/interface/CompilerStack.cpp]: Previously, before daba02b,  in `CompilerStack::analyzeInternal()`, in case of several early `return false;` we did not set the state `m_stackState = AnalysisPerformed`

For instance here, for a *non-fatal error* we just returned `false`:

```
bool CompilerStack::analyzeInternal()
{
    . . . .
        for (Source const* source: m_sourceOrder)
            if (source->ast && !resolver.resolveNamesAndTypes(*source->ast))
                return false;
```

It is somewhat strange, because a *fatal error* in `resolveNamesAndTypes`
would be caught and the state `m_stackState = AnalysisPerformed` would be set:

```
    catch (FatalError const&)
    {
        if (m_errorReporter.errors().empty())
            throw; // Something is weird here, rather throw again.
        noErrors = false;
    }

    m_stackState = AnalysisPerformed;
    if (!noErrors)
        m_hasError = true;

    return !m_hasError;
}
```

I think it has to be consistent, and we should
- either set `m_stackState = AnalysisPerformed` when `CompilerStack::analyze()` *finishes, always*;
- or do it if `CompilerStack::analyze()` *finishes successfully*.

**Comment by a3d4** [comment]
> Also missing a changelog

Yes, I know :). I plan to do it when all other things are completed, to avoid merge conflicts.

File: libsolidity/interface/CompilerStack.cpp (hunk 7 above)
Comment (ekpyron) [reply libsolidity/interface/CompilerStack.cpp]: I think the old behaviour was by design and is inherited from the efforts to error-recovery...
``AnalysisPerformed`` is not meant to imply "Analysis successful"... that's why there's ``m_hasError`` checks in cricital stages that want to move beyond ``AnalysisPerformed``. Not sure how sane any of that really is, though...
EDIT: Also I'm not entirely sure I'm right here :-).

But I guess this change is independent of fixing the ICE by moving the check? Maybe we should split that...

File: libsolidity/analysis/DeclarationTypeChecker.cpp [hunk 8]
```diff
@@ -390,8 +390,16 @@ void DeclarationTypeChecker::endVisit(VariableDeclaration const& _variable)
...
 	}
 
-	_variable.annotation().type = type;
+	if (_variable.isConstant() && !type->isValueType())
+	{
+		bool allowed = false;
+		if (auto arrayType = dynamic_cast<ArrayType const*>(type))
+			allowed = arrayType->isByteArray();
+		if (!allowed)
+			m_errorReporter.declarationError(9259_error, _variable.location(), "Constants of non-value type not yet implemented.");
```
Comment (ekpyron) [inline libsolidity/analysis/DeclarationTypeChecker.cpp]: I think we should split out the part that just fixes the ICE, i.e. the move from ``TypeChecker`` to ``DeclarationTypeChecker``. I'd hope that'd actually be enough... but if not, I guess we can just make this here a fatal error and at least that should do it? The other changes are a bit delicate - maybe it's fine, but I've not worked through them yet.

Comment (a3d4) [reply libsolidity/analysis/DeclarationTypeChecker.cpp]: OK. The error has to be fatal though, otherwise `fuzzer.exe < const_struct_with_mapping.sol` causes ICE.

I think we should fix that ICE still (in another PR).

File: Changelog.md [hunk 9]
```diff
@@ -16,6 +16,7 @@ Bugfixes:
  * SMTChecker: Fix false negatives when analyzing external function calls.
  * SMTChecker: Fix missing type constraints for block variables.
  * SMTChecker: Fix internal error on ``block.chainid``.
+ * Type Checker: Fix ICE caused by const structs with mappings.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Type Checker: Fix internal error caused by constant structs containing mappings.
```

**Comment by chriseth** [comment]
Will rebase and merge.

**Review by chriseth — APPROVED** [review]
