### PR TITLE
Pragma keyword check

### LINKED ISSUE #1192: Malformed pragmas interpreted as version pragmas
In `develop`, a malformed pragma that finishes with a `;` is interpreted as a version pragma.

```
$ cat test.sol 
pragma some sentence;
$ solc/solc test.sol 
test.sol:1:1: Error: Source file requires different compiler version (current compiler is 0.4.3-develop.2016.10.10+commit.aa8832d6.mod.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma some sentence;
^-------------------^
```

### PR DESCRIPTION
**Pull request by pirapira**
This is a one line check that fixes #1192.

### CODE REVIEW

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 1]
```diff
@@ -2884,10 +2884,12 @@ BOOST_AUTO_TEST_CASE(keccak256_multiple_arguments)
 	compileAndRun(sourceCode);
 
 	BOOST_CHECK(callContractFunction("foo(uint256,uint256,uint256)", 10, 12, 13) == encodeArgs(
-					dev::sha3(
-						toBigEndian(u256(10)) +
-						toBigEndian(u256(12)) +
-						toBigEndian(u256(13)))));
+		dev::keccak256(
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp:2887]: Please rebase.

**Review by chriseth — CHANGES_REQUESTED** [review]

**Comment by chriseth** [comment]
The hard science of boolean negation :-)

File: test/libsolidity/SolidityEndToEndTest.cpp (hunk 1 above)
Comment (pirapira) [reply test/libsolidity/SolidityEndToEndTest.cpp:2887]: Done.

**Review by chriseth — APPROVED** [review]
