### PR TITLE
Escape object/data names in Yul serializer

### LINKED ISSUE #16516: Unescaped object/data names in Yul serializer cause crash on reparse
## Description

When running on input file:
```
object'"'{code{}}
```

which is valid Yul, we get:

```
./solc/solc --strict-assembly --optimize-yul crash-9bba37f2d0573d9282916d92152e7d9a23571560
Yul assertion failed:
/solidity/libyul/YulStack.cpp(220): Throw in function void solidity::yul::YulStack::reparse()
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what: object "3"{code{}}e0003" {
    code { { } }
}


Invalid IR generated:
Error: Expected end of source but got identifier
 --> crash-9bba37f2d0573d9282916d92152e7d9a23571560:1:19:
  |
1 | object "3"{code{}}e0003" {
  |                   ^^^^^



[solidity::util::tag_comment*] = object "3"{code{}}e0003" {
    code { { } }
}


Invalid IR generated:
Error: Expected end of source but got identifier
 --> crash-9bba37f2d0573d9282916d92152e7d9a23571560:1:19:
  |
1 | object "3"{code{}}e0003" {
  |                   ^^^^^
```

This is due to `reparse()` failing on line 145 in YulStack.cpp:

```cpp
		m_stackState = Parsed;
		solAssert(m_objectOptimizer);
		m_objectOptimizer->optimize(
			*m_parserResult,
			ObjectOptimizer::Settings{
				m_language,
				m_evmVersion,
				m_eofVersion,
				optimizeStackAllocation,
				yulOptimiserSteps,
				yulOptimiserCleanupSteps,
				m_optimiserSettings.expectedExecutionsPerDeployment
			}
		);

		// Optimizer does not maintain correct native source locations in the AST.
		// We can work around it by regenerating the AST from scratch from optimized IR.
		reparse();
```

During reparsing, the source is:

Image

i.e. 
```
	source = "object \"3\"{code{}}e0003\" {\n code { { } }\n}\n"
```

## Environment

- Compiler version: fab9d5c2bcc1078b7f6b97804a903623af5254ad
- Compilation pipeline (legacy, IR, EOF): ` --strict-assembly --optimize-yul`
- Target EVM version (as per compiler settings): latest
- Framework/IDE (e.g. Foundry, Hardhat, Remix): none, direct solc invocation
- EVM execution environment / backend / blockchain client: we don't get to execute EVM
- Operating system: Linux

## Steps to Reproduce

As per above.

### PR DESCRIPTION
**Pull request by msooseth**
## Fix: Unescaped object/data names in Yul serializer cause crash on reparse

Fixes: https://github.com/argotorg/solidity/issues/16516

### Problem

`Object::toString()` and `Data::toString()` concatenated the `name` field directly into the serialized output:

```cpp
"object \"" + name + "\" {\n"
```

The `name` is stored as the raw unescaped string value from the scanner, so a name containing `"` (e.g. parsed from `object "foo\"bar" { ... }`) would produce malformed Yul like:

```
object "foo"bar" {
```

After optimization, `YulStack::reparse()` serializes the AST via `print()` and re-parses it. The malformed output caused a fatal parser error: *"Expected end of source but got identifier"*.

### Fix

Replace manual quoting with `util::escapeAndQuoteString(name)` in both `Object::toString()` and `Data::toString()`. This escapes `"`, `\`, and non-printable characters before re-serialization, making the output round-trip correctly through the parser.

`formatUseSrcComment()` in the same file already used `escapeAndQuoteString` correctly for source names — this applies the same pattern to object and data names.

## Output on crashing input
```
$ ./solc/solc --strict-assembly --optimize-yul crash-9bba37f2d0573d9282916d92152e7d9a23571560

======= crash-9bba37f2d0573d9282916d92152e7d9a23571560 (EVM) =======

Pretty printed source:
object "3\"{code{}}e0003" {
    code { { } }
}


Binary representation:
00

Text representation:
    /* "crash-9bba37f2d0573d9282916d92152e7d9a23571560":37:44   */
  stop
```

## Disclosures

Code generated by Caude Claude. Reviewed by myself.

### CODE REVIEW

File: libyul/Object.cpp
Comment (cameel) [inline libyul/Object.cpp:1]: Needs a changelog entry and some tests.

Comment (msooseth) [reply libyul/Object.cpp:1]: Good point! Added a tests and added changelog :) Can you maybe re-review?

File: Changelog.md [hunk 1]
```diff
@@ -12,6 +12,7 @@ Compiler Features:
 * Yul EVM Code Transform: Improve stack shuffler performance by fixing a BFS deduplication issue.
 
 Bugfixes:
+* Yul: Fix incorrect serialization of Yul object names containing special characters (e.g. quotes) that were not escaped, producing output that could not be reparsed.
```
Comment (cameel) [inline Changelog.md]: I would make it more concrete:

```suggestion
* Yul: Fix incorrect serialization of Yul object names containing double quotes and escape sequences, producing output that could not be parsed as valid Yul.
```

File: test/libyul/objectCompiler/data_name_with_special_chars.yul [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// Data section name containing a quote must be escaped in serialization
+// to prevent a reparse failure during optimization (exercises Data::toString).
+object "a" {
+    code { {} }
+    data "my\"data" hex"deadbeef"
```
Comment (cameel) [inline test/libyul/objectCompiler/data_name_with_special_chars.yul]: I'd add `datasize("my\"data")` in there to prove that you can successfully refer to such data, not just declare it.

File: test/libyul/objectCompiler/object_name_with_backslash.yul [hunk 3]
```diff
@@ -0,0 +1,13 @@
+// Object name containing a backslash must be escaped in serialization
+// to prevent a reparse failure during optimization.
+object "foo\\bar" {
```
Comment (cameel) [inline test/libyul/objectCompiler/object_name_with_backslash.yul]: Can we just use a name that has all the possible escapes? There's only a handful of them: https://github.com/argotorg/solidity/blob/57d3d689a611ada8c1d957569b310ffd6475a342/libsolutil/CommonData.cpp#L204-L219

And please use `datasize()` here as well.

File: test/libyul/objectCompiler/data_name_with_special_chars.yul
Comment (cameel) [inline test/libyul/objectCompiler/data_name_with_special_chars.yul:1]: I'm not sure seeing assembly outputs adds much to these tests. It shows that they compile, but we only expect issues in the parser anyway. Maybe these would be better off in `test/libyul/yulSyntaxTests/objects/` instead?

Comment (cameel) [reply test/libyul/objectCompiler/data_name_with_special_chars.yul:1]: This would also allow us to add some coverage for invalid cases. For example I think we should have tests covering names that include an unescaped newline, tab, or unicode character. For example something like this should produce an error:

```yul
object "A" {
    code {
        sstore(0, datasize("B\nC"))
    }
    data "B
C" hex"1234"
}
```

Comment (msooseth) [reply test/libyul/objectCompiler/data_name_with_special_chars.yul:1]: Added test `test/libyul/yulSyntaxTests/objects/data_name_with_literal_newline.yul` to address this concern.

I also moved all the files into `test/libyul/yulSyntaxTests/objects/` you are right, it makes a ton more sense. Sorry, I am not very familiar with the testing setup in Solidity :S

File: test/libyul/objectCompiler/object_name_with_backslash.yul (hunk 3 above)
Comment (msooseth) [reply test/libyul/objectCompiler/object_name_with_backslash.yul]: New test case has them all: `test/libyul/yulSyntaxTests/objects/object_name_with_all_special_chars.yul` :) Let me know what you think!

File: test/libyul/objectCompiler/data_name_with_special_chars.yul (hunk 2 above)
Comment (msooseth) [reply test/libyul/objectCompiler/data_name_with_special_chars.yul]: Yes, it seems like we can, I updated the test :) Yay. Let me know what you think!

**Review by clonker — COMMENTED** [review]
Commits need squashing and the branch needs a rebase. We try avoiding merge commits in the history and an up-to-date rebase ensures that the changes integrate well with the current develop as well as keeps the history neat and linear.
Changes and test coverage are good!

**Review by clonker — APPROVED** [review]
