### PR TITLE
[Sol->Yul] Implementing copying of arrays to storage 

### LINKED ISSUE #9037: ICE when trying to assign a calldata struct to storage
## Environment 
Solidity version: 0.6.8
Platform: macOS Catalina / Ubuntu 20.04

## Relevant source:
```
pragma solidity >=0.6.0;
pragma experimental ABIEncoderV2;

contract Test {

  struct Struct {
    bytes32 arr;
  }

  Struct public myStr;

  function test (Struct calldata s) external payable {
    myStr = s;
  }
}
```

## Observed behaviour (compiler output):
```
Internal compiler error during compilation:
/tmp/solidity-20200527-88271-1omoasb/solidity_0.6.8/libsolidity/codegen/LValue.cpp(358): Throw in function virtual void solidity::frontend::StorageItem::storeValue(const solidity::frontend::Type &, const solidity::langutil::SourceLocation &, bool) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Structs in calldata not supported.
[solidity::util::tag_comment*] = Structs in calldata not supported.
```

## Expected behaviour:
The calldata struct should get copied to storage?
https://solidity.readthedocs.io/en/v0.6.8/types.html?highlight=calldata%20storage#data-location-and-assignment-behaviour

## Workaround
Copying to memory and then assigning to storage works fine:
```
pragma solidity >=0.6.0;
pragma experimental ABIEncoderV2;

contract Test {

  struct Struct {
    bytes32 arr;
  }

  Struct public myStr;

  function test (Struct calldata s) external payable {
    Struct memory ss = s;
    myStr = ss;
  }
}
```

Also, marking the contract as abstract makes the error go away:
```
pragma solidity >=0.6.0;
pragma experimental ABIEncoderV2;

abstract contract Test {

  struct Struct {
    bytes32 arr;
  }

  Struct public myStr;

  function test (Struct calldata s) external payable {
    myStr = s;
  }
}
```

### PR DESCRIPTION
**Pull request by mijovic**
Code is ready for review.

TODO:
- [x] Adding more tests with nested arrays, arrays of structs, structs containing arrays,...
- [x] Remove calls to index access functions
- [ ] Optimize number of calls to `sstore` (try writing multiple array members at once if multi members fit one slot) (we agreed this will be a part of other PR, there is an issue for that now #9831)
- [x] Clear storage array with zeros when copying smaller array

Depends on:
- #9843
- #9905

Fixes #9037

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `ffd2c2d2e3eb73ae03b3b522eca56769cc8356d4`:
```
Coding style error:
 libsolidity/codegen/YulUtilFunctions.cpp:1100: for { let i := 0 } lt(i, length) {i := add(i, 1)} {
 libsolidity/codegen/YulUtilFunctions.cpp:1116: }

```
Please check that your changes are working as intended.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 1]
```diff
@@ -1065,6 +1065,87 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
+								let <elementValues> := <readFromCalldataOrMemory>(callDataOrMemoryOffset)
+							</isValueType>
+						</isBytes>
+					<!fromCalldata>
+						let <elementValues> := <readFromCalldataOrMemory>(callDataOrMemoryOffset)
+					</fromCalldata>
+					let elementSlot, elementOffset := <toArrayIndexAccess>(slot, i)
+					let elementValueOrRef := <?isRefTypeInCalldata>callDataOrMemoryOffset<!isRefTypeInCalldata><elementValues></isRefTypeInCalldata>
+					<updateStorageValue>(elementSlot<?hasOffset>, elementOffset</hasOffset>, elementValueOrRef)
+    			}
```
Comment (stackenbotten) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Coding style error

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `70b1e267e760a74b6d38c434e8b2eae6013e801e`:
```
Coding style error:
 libsolidity/codegen/YulUtilFunctions.cpp:1100: for { let i := 0 } lt(i, length) {i := add(i, 1)} {

```
Please check that your changes are working as intended.

File: libsolidity/codegen/LValue.cpp [hunk 2]
```diff
@@ -338,10 +338,30 @@ void StorageItem::storeValue(Type const& _sourceType, SourceLocation const& _loc
...
 			m_context << Instruction::POP; // remove byte offset
-			ArrayUtils(m_context).copyArrayToStorage(
-				dynamic_cast<ArrayType const&>(*m_dataType),
-				dynamic_cast<ArrayType const&>(_sourceType)
-			);
+			auto const& sourceArrayType = dynamic_cast<ArrayType const&>(_sourceType);
+			if (sourceArrayType.baseType()->category() == Type::Category::Struct && sourceArrayType.location() != DataLocation::Storage)
+			{
+				bool fromCalldata = sourceArrayType.location() == DataLocation::CallData;
+				solAssert(_sourceType.sizeOnStack() == (fromCalldata ? 2 : 1), "");
```
Comment (ekpyron) [inline libsolidity/codegen/LValue.cpp]: Only dynamically sized calldata arrays occupy two stack slots - for statically sized calldata arrays there's no length on the stack, so I think the static case is missing here, right?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 3]
```diff
@@ -1065,6 +1065,87 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
+string YulUtilFunctions::copyArrayToStorage(ArrayType const& _fromType, ArrayType const& _toType)
+{
+	solAssert(
+		*_fromType.copyForLocation(_toType.location(), _toType.isPointer()).get() == dynamic_cast<ReferenceType const&>(_toType),
+		""
+	);
+
+	string functionName = "copy_array_to_storage_from_" + _fromType.identifier() + "_to_" + _toType.identifier();
+	return m_functionCollector.createFunction(functionName, [&](){
+		Whiskers templ(R"(
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp:1199]: I think this template has too many case distinctions, we should try to simplify it...

For example, instead of conditionally having ``length`` for dynamic calldata arrays, we could use ``<value>`` and make it a list of ``_fromType.sizeOnStack()``-many variables, and then implement a ``arrayLengthFunction`` for dynamic calldata types as well (i.e. for *all* array types - which would be weird, since it'd be ``function arrayLengthFunction(value, len) -> length { length := len }`` in the dynamic calldata case, but it shouldn't harm, because it'll be inlined by the optimiser and in places like this it would make it easier to do things more generically).

Also I think it might be worth it to treat the ``isBytes`` case separately.

Since after the first suggestion the shared code for determining the length will reduce to one line in all cases, I think also splitting into "array of reference type" and "array of value type" cases could also work without much duplication.

**Review by ekpyron — CHANGES_REQUESTED** [review]
I haven't checked everything for correctness, yet, but I have some suggestions for simplifications.

File: libsolidity/codegen/LValue.cpp (hunk 2 above)
Comment (mijovic) [reply libsolidity/codegen/LValue.cpp]: Yes, only dynamic arrays from calldata have 2 stack slots. Fixing now.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1199]: I simplified length part of template.
I tried to simplify other parts a bit without moving all cases to separate template, as it would have a lot of duplication than.
Does it look better now? @ekpyron

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 4]
```diff
@@ -1065,6 +1065,103 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
+			function <functionName>(slot, <value>) {
+				let length := <arrayLength>(<value>)
+				<?isToDynamic>
+					<storeLength>(slot, length)
+				</isToDynamic>
+
+				for { let i := 0 } lt(i, length) {i := add(i, 1)} {
+					let callDataOrMemoryOffset := <fromArrayIndexAccess>(<value>, i)
+					let elementSlot, elementOffset := <toArrayIndexAccess>(slot, i)
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: I'm wondering... both of these functions are **very** expensive, because they do all kinds of bounds checks and verifications...
All of them could be done only once in advance and then inside the loop it would basically just be incrementing an offset by a stride...

I'd like to think the optimizer to be clever enough to inline these, recognize that the checks hold inductively, if and only if they hold for "i = length - 1", extract this check in front of the loop and remove all checks inside the loop... but that's never going to happen :-)...

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:1199]: I posted another comment about using the index access functions below, that will probably change the situation quite a bit...

I think if we want to do this efficiently, the first distinction will have to be based on whether the to-array will have multiple elements per slot or not. If it has multiple ones, we'll want to loop over slots and not elements, treating the last slot special. (e.g. as long as there's more than two ``uint128``s left, read two of them from calldata, pack them together and write to storage once, and only in the end check if a single one remains that has to be appended).

If it is one element per slot, on the other hand, it's much simpler.

In both cases for the source-side in memory/calldata we first calculate the starting offset before the loop and then just increment by ``calldataStride()`` or ``memoryStride()`` in the loop.

So none of the bounds checks hidden in the index access functions have to be performed inside the loop and for packed storage arrays, we can drastically reduce the storage reads and writes required, if multiple elements are written at once - which is worth the complexity, since storage access is really expensive...

**Comment by ekpyron** [comment]
Also as a general note: I may have been blind and just not seen it, but I think it's missing in the PR:
Storage has to be zeroed out in case the array used to be larger.
I.e. this:
```
contract C {
  uint256[] x;
  function f() public returns(uint256) {
    x.push(42); x.push(42);
    uint256[] memory y = new uint256[](1);
    y[0] = 23;
    x = y;
    assembly { sstore(x.slot, 2) } // overwrite length to 2, s.t. we can easily access the second element that should have been cleared
    return x[1];
  }
}
```
has to return ``0``, not ``42``.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:1199]: So doing all of this manually and most efficiently instead will probably be quite some work and tricky to get right - but I still think we should do it, since savings in storage operations are quite important and the optimizer has little chance here.

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1199]: I completely agree with your comment here. I'll leave this PR now in draft, and will do optimizations.
I'll use this code as a reference and incrementally add optimization and split into possibly more functions for different cases.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 5]
```diff
@@ -1065,6 +1065,103 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
+	return m_functionCollector.createFunction(functionName, [&](){
+		Whiskers templ(R"(
+			function <functionName>(slot, <value>) {
+				let length := <arrayLength>(<value>)
+				<?isToDynamic>
+					<storeLength>(slot, length)
+				</isToDynamic>
+
+				for { let i := 0 } lt(i, length) {i := add(i, 1)} {
+					let callDataOrMemoryOffset := <fromArrayIndexAccess>(<value>, i)
```
Comment (mijovic) [inline libsolidity/codegen/YulUtilFunctions.cpp]: As a reminder. This doesn't work for dynamic nested arrays, as it has length as a return value as well.

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: But, as I am going to change the code anyways, it will be probably solved in a different way.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `3673161a37ee8292308c310bb84b670cf58865c3`:
```
Error: Trailing whitespace found:
 test/libsolidity/semanticTests/array/copying/array_copy_memory_to_storage.sol:2: uint128[13] unused; 
 test/libsolidity/semanticTests/array/copying/array_of_structs_containing_arrays_memory_to_storage.sol:16: m[1].c[0] = 1; 

```
Please check that your changes are working as intended.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:1199]: I'll mark this as resolved now, but just because it's annoying to have the long comment in the sources ;-).

File: Changelog.md [hunk 6]
```diff
@@ -1,7 +1,7 @@
 ### 0.7.2 (unreleased)
 
 Language Features:
-
+ * Code generator: Implementing copying arrays of structs to storage.
```
Comment (mijovic) [inline Changelog.md]: Missing changelog entry for copying nested dynamic arrays from calldata to storage (as that feature is activated for old codegen as well)

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 4 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I removed `fromArrayIndexAccess`, am at half of removing `toArrayIndexAccess`, will update with that hopefully today

**Comment by mijovic** [comment]
> Also as a general note: I may have been blind and just not seen it, but I think it's missing in the PR:
> Storage has to be zeroed out in case the array used to be larger.
> I.e. this:
> 
> ```
> contract C {
>   uint256[] x;
>   function f() public returns(uint256) {
>     x.push(42); x.push(42);
>     uint256[] memory y = new uint256[](1);
>     y[0] = 23;
>     x = y;
>     assembly { sstore(x.slot, 2) } // overwrite length to 2, s.t. we can easily access the second element that should have been cleared
>     return x[1];
>   }
> }
> ```
> 
> has to return `0`, not `42`.

I am adding tests for these. I used `resizeDynamicArrayFunction` to clear unused part of the array and write new length. It works for types greater than 16bytes as it is just clearing whole slot. Now I am fixing it to work with smaller types.

File: libsolidity/codegen/ArrayUtils.cpp [hunk 7]
```diff
@@ -225,7 +226,10 @@ void ArrayUtils::copyArrayToStorage(ArrayType const& _targetType, ArrayType cons
 				else if (sourceBaseType->isValueType())
 					CompilerUtils(_context).loadFromMemoryDynamic(*sourceBaseType, fromCalldata, true, false);
 				else
-					solUnimplemented("Copying of type " + _sourceType.toString(false) + " to storage not yet supported.");
+				{
+					// this should be implemented in a call to yul util function
+					solAssert(false, "");
```
Comment (ekpyron) [inline libsolidity/codegen/ArrayUtils.cpp]: Why not keep it at the old ``solUnimplemented`` with the previous message?

File: libsolidity/codegen/LValue.cpp [hunk 8]
```diff
@@ -338,10 +338,35 @@ void StorageItem::storeValue(Type const& _sourceType, SourceLocation const& _loc
 		if (m_dataType->category() == Type::Category::Array)
 		{
 			m_context << Instruction::POP; // remove byte offset
-			ArrayUtils(m_context).copyArrayToStorage(
-				dynamic_cast<ArrayType const&>(*m_dataType),
-				dynamic_cast<ArrayType const&>(_sourceType)
-			);
+			auto const& sourceArrayType = dynamic_cast<ArrayType const&>(_sourceType);
+			if (
+				(sourceArrayType.baseType()->isDynamicallySized() || dynamic_cast<StructType const*>(sourceArrayType.baseType())) &&
```
Comment (ekpyron) [inline libsolidity/codegen/LValue.cpp]: Should this really be ``baseType()->isDynamicallySized()`` or rather ``baseType()->isDynamicallyEncoded()``?
I.e. what happens if the base type is a statically sized array of dynamically sized arrays?

File: libsolidity/codegen/LValue.cpp [hunk 9]
```diff
@@ -338,10 +338,35 @@ void StorageItem::storeValue(Type const& _sourceType, SourceLocation const& _loc
...
+					sourceArrayType.location() == DataLocation::CallData &&
+					sourceArrayType.isDynamicallySized();
+				solAssert(_sourceType.sizeOnStack() == (isDynamicFromCalldata ? 2 : 1), "");
+				solAssert(m_dataType->sizeOnStack() == 1, "");
+
+				// stack: source_ref [source_length] target_ref
+				if (isDynamicFromCalldata)
+					m_context << Instruction::SWAP2 << Instruction::DUP3;
+				else
+					m_context << Instruction::SWAP1 << Instruction::DUP2;
```
Comment (ekpyron) [inline libsolidity/codegen/LValue.cpp]: So in the dynamic callldata case, this is:
```
// stack: source_ref source_length target_ref
m_context << Instruction::SWAP2;
// stack: target_ref source_ref source_length
m_context << Instruction::DUP3;
// stack: target_ref source_ref source_length target_ref
```
Shouldn't ``source_ref`` and ``source_length`` be reversed?

The arguments to the yul function are ``slot, value, len`` in this case, not ``slot, len, value``...

If I'm right here about this, then it's rather suspicious that this didn't come up in any test ;-).

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 10]
```diff
@@ -809,20 +807,35 @@ std::string YulUtilFunctions::resizeDynamicArrayFunction(ArrayType const& _type)
...
-				// Store new length
-				sstore(array, newLen)
+				<?isBytes>
+					switch lt(newLen, 32)
+					case 0 {
+						sstore(array, add(mul(newLen, 2), 1))
+					}
+					default {
+						sstore(array, mul(newLen, 2))
+					}
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
					sstore(array, or(shl(newLen, 1), iszero(lt(newLen, 32))))
```
or is that too cryptic :-)?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 11]
```diff
@@ -1005,24 +1018,75 @@ string YulUtilFunctions::clearStorageRangeFunction(Type const& _type)
 {
 	string functionName = "clear_storage_range_" + _type.identifier();
 
-	solAssert(_type.storageBytes() >= 32, "Expected smaller value for storage bytes");
-
 	return m_functionCollector.createFunction(functionName, [&]() {
 		return Whiskers(R"(
-			function <functionName>(start, end) {
+			function <functionName>(start, end, firstInactiveInStart) {
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: This is getting quite a weird function...
But this PR is blowing up a bit - what do you think about making "Implement resizing of packed storage arrays." its own PR :-)? Just changing the resize and clear function should work on its own and be testable, shouldn't it?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 12]
```diff
@@ -1005,24 +1018,75 @@ string YulUtilFunctions::clearStorageRangeFunction(Type const& _type)
...
+			_type.storageBytes() < 17 ?
+			(storageSetWholeSlotToZeroFunction(_type) + "(start)") :
+			(storageSetToZeroFunction(_type) + "(start, 0)")
+		)
 		("increment", _type.storageSize().str())
 		.render();
 	});
 }
 
+string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: I think it would probably be best to move this part to another PR as well.
You can implement ``delete`` for storage structs with this, that can again be done independently of the rest and can be tested on its own and then you can just reuse it in this PR.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 13]
```diff
@@ -2657,6 +2992,15 @@ string YulUtilFunctions::storageSetToZeroFunction(Type const& _type)
 			("functionName", functionName)
 			("clearArray", clearStorageArrayFunction(dynamic_cast<ArrayType const&>(_type)))
 			.render();
+		else if (_type.category() == Type::Category::Struct)
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Ah, yes, you already have it here as well. This should now allow stuff like this to pass:
```
contract C {
  struct S { uint256 x; }
  S s;
  function f() public {
    s.x = 42;
    delete s;
    assert(s.x == 0);
  }
}
```
and (as mentioned in the other comment) can be its own PR with its own tests.

**Review by ekpyron — COMMENTED** [review]
Some comments - I think what we should first do is take a few parts of this that can be done on their own and move them to separate smaller PRs first, otherwise this one will become too large :-).

In particular I'm thinking about resizing storage arrays with small base types and ``delete`` for storage structs as candidates for separate PRs.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 13 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: #9843

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 12 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: #9843

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 10 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I decided to move resizing bytes array to its own PR

**Comment by ekpyron** [comment]
What's the state of this - is this still ready to be reviewed given everything that was extracted from it? If so, ping me about it. It asks for a rebase in any case (maybe even better to wait until https://github.com/ethereum/solidity/pull/9985 is merged with it, that'll probably require another rebase).

**Comment by mijovic** [comment]
> What's the state of this - is this still ready to be reviewed given everything that was extracted from it? If so, ping me about it. It asks for a rebase in any case (maybe even better to wait until #9985 is merged with it, that'll probably require another rebase).

I'll do rebase and will need to remove some things from here.
When done, will ping you :-)

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 14]
```diff
@@ -754,7 +754,7 @@ string YulUtilFunctions::arrayLengthFunction(ArrayType const& _type)
 	string functionName = "array_length_" + _type.identifier();
 	return m_functionCollector.createFunction(functionName, [&]() {
 		Whiskers w(R"(
-			function <functionName>(value) -> length {
+			function <functionName>(value<?calldata><?dynamic>, len</dynamic></calldata>) -> length {
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Maybe use a new template (i.e. just a fixed string) for that case?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 15]
```diff
@@ -1065,6 +1129,198 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
 }
 
+string YulUtilFunctions::copyArrayFromMemoryToStorage(ArrayType const& _fromType, ArrayType const& _toType)
+{
+	solAssert(_fromType.location() == DataLocation::Memory, "");
+
+	string functionName = "copy_array_memory_to_storage_from_" + _fromType.identifier() + "_to_" + _toType.identifier();
+	return m_functionCollector.createFunction(functionName, [&](){
+		Whiskers templ(R"(
+			function <functionName>(slot, value) {
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
			function <functionName>(slot, memptr) {
```

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: or `srcArray` or `src`

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 16]
```diff
@@ -1065,6 +1129,198 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
+				let length := <arrayLength>(value)
+				<?isToDynamic>
+					<resizeArray>(slot, length)
+				</isToDynamic>
+
+				let memoryOffset := <dataLocation>(value)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: srcDataLocation and dstDataLocation below?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 17]
```diff
@@ -1065,6 +1129,198 @@ string YulUtilFunctions::clearStorageArrayFunction(ArrayType const& _type)
...
+			("multipleItemsPerSlot", _toType.storageStride() <= 16)
+			("storageStride", to_string(_toType.storageStride()))
+			("storageSize", _toType.baseType()->storageSize().str())
+			.render()
+		);
+		return templ.render();
+	});
+}
+
+string YulUtilFunctions::copyArrayFromCalldataToStorage(ArrayType const& _fromType, ArrayType const& _toType)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: It may be easier to combine copying from calldata and copying from memory than it is to combine regular arrays and byte arrays :)

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: That was my idea as well. Also byte arrays will need #9966 first :)
Starting rebase now

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `ed283151b0bdb283d05a24861e8e37380f6d517d`:
```
Error: Trailing whitespace found:
 Changelog.md:34: 

```
Please check that your changes are working as intended.

**Comment by mijovic** [comment]
I rebased and solved conflicts. Pushed just in case. Will now be fixing PR. Please do not review still :-)

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `a71875ef5e187aada78477993c937c5cf356da6e`:
```
Error: Trailing whitespace found:
 Changelog.md:34: 

```
Please check that your changes are working as intended.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 17 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I went with removing byte array implementation from this PR as it needs #9966 first. It will probably end up in its own function. I left calldata and memory cases separate for now. If you think it should be combined I can merge them.

File: libsolidity/codegen/LValue.cpp (hunk 8 above)
Comment (mijovic) [reply libsolidity/codegen/LValue.cpp]: I left this PR to be only for `sol->yul ` implementation. It would be easier to merge. Than will follow up with things that can be enabled in olcodegen as well

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 18]
```diff
@@ -808,7 +808,7 @@ string YulUtilFunctions::arrayLengthFunction(ArrayType const& _type)
 	string functionName = "array_length_" + _type.identifier();
 	return m_functionCollector.createFunction(functionName, [&]() {
 		Whiskers w(R"(
-			function <functionName>(value) -> length {
+			function <functionName>(value<calldataDynLen>) -> length {
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
			function <functionName>(value<?dynamic><?calldata>, len</calldata></dynamic>) -> length {
```

File: libsolidity/codegen/YulUtilFunctions.h [hunk 19]
```diff
@@ -173,6 +173,10 @@ class YulUtilFunctions
 	/// signature: (slot) ->
 	std::string clearStorageArrayFunction(ArrayType const& _type);
 
+	/// @returns the name of a function that will copy array from calldata or memory to storage
+	/// signature (slot, value) ->
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.h]:
```suggestion
	/// signature (to_slot, from_ptr) ->
```

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 20]
```diff
@@ -1755,23 +1938,39 @@ string YulUtilFunctions::updateStorageValueFunction(
 		else
 		{
 			auto const* toReferenceType = dynamic_cast<ReferenceType const*>(&_toType);
-			auto const* fromReferenceType = dynamic_cast<ReferenceType const*>(&_toType);
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:1758]: Oh wow!

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 21]
```diff
@@ -1755,23 +1938,39 @@ string YulUtilFunctions::updateStorageValueFunction(
...
+			auto const* fromReferenceType = dynamic_cast<ReferenceType const*>(&_fromType);
 			solAssert(fromReferenceType && toReferenceType, "");
 			solAssert(*toReferenceType->copyForLocation(
 				fromReferenceType->location(),
 				fromReferenceType->isPointer()
 			).get() == *fromReferenceType, "");
+			solAssert(fromReferenceType->location() != DataLocation::Storage, "");
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: solUnimplementedAssert?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 22]
```diff
@@ -1185,6 +1186,188 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+				</isToDynamic>
+
+				let memoryOffset := <srcDataLocation>(memptr)
+
+				let elementSlot := <dstDataLocation>(slot)
+				<?isBytes>
+					if lt(length, 32) {
+						elementSlot := slot
+					}
+				</isBytes>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
```

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 23]
```diff
@@ -1185,6 +1186,188 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+				let elementOffset := 0
+
+				for { let i := 0 } lt(i, length) {i := add(i, 1)} {
+					let <elementValues> := <readFromMemory>(memoryOffset)
+					<?isBytes>
+						<updateStorageValue>(elementSlot, sub(31, elementOffset), <elementValues>)
+					<!isBytes>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
```

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 24]
```diff
@@ -1185,6 +1186,188 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+
+				let elementSlot := <dstDataLocation>(slot)
+				<?isBytes>
+					if lt(length, 32) {
+						elementSlot := slot
+					}
+				</isBytes>
+				let elementOffset := 0
+
+				for { let i := 0 } lt(i, length) {i := add(i, 1)} {
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:1216]: We could unroll the loop to "number of items per slot"

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 25]
```diff
@@ -1185,6 +1186,188 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+		if (_fromType.baseType()->isValueType())
+			templ("readFromCalldataOrMemory", readFromCalldata(*_fromType.baseType()));
+		templ("hasOffset", _toType.baseType()->isValueType());
+		templ("elementValues", suffixedVariableNameList(
+				"elementValue_",
+				0,
+				_fromType.baseType()->stackItems().size()
+		));
+		templ("updateStorageValue", updateStorageValueFunction(*_fromType.baseType(), *_toType.baseType()));
+		templ("stride", to_string(_toType.calldataStride()));
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
		templ("stride", to_string(_fromType.calldataStride()));
```

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 21 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: In case of `storage` to `storage` it should just do `slot := value`? I think this is done in other place. In any case I can change this to unimplemented assert

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 24 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1216]: I can do it. If size of type is less than 32 which is only for value types, I can do all operation on whole slot and type u256?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 21 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Please keep it a proper assert if it cannot be triggered - it was just a question.

Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Sorry, it was my bad. It can be triggered, for example in test `array_copy_storage_storage_static_static` where we perform deep copy of array from storage to storage...
So, will leave `solUnimplementedAssert` as it is correct one to have here.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 24 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:1216]: I'll leave this as is now and will do it as a part of #9831, ok?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 26]
```diff
@@ -819,28 +819,29 @@ string YulUtilFunctions::arrayLengthFunction(ArrayType const& _type)
...
+					<?calldata>
+						length := len
+					</calldata>
 				<!dynamic>
 					length := <length>
 				</dynamic>
 			}
 		)");
 		w("functionName", functionName);
+		w("calldataDynLen", _type.isDynamicallySized() && _type.dataStoredIn(DataLocation::CallData) ? ", len" : "");
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]:
```suggestion
```

**Comment by mijovic** [comment]
@chriseth Combined into one function. 
Probably most of this can be used for copying from storage to storage when implementing that part.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 27]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
 	});
 }
 
+string YulUtilFunctions::copyArrayToStorage(ArrayType const& _fromType, ArrayType const& _toType)
+{
+	solAssert(
+		*_fromType.copyForLocation(_toType.location(), _toType.isPointer()).get() == dynamic_cast<ReferenceType const&>(_toType),
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Why `.get()` and `*`?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 28]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+
+				let elementSlot := <dstDataLocation>(slot)
+				let elementOffset := 0
+
+				for { let i := 0 } lt(i, length) {i := add(i, 1)} {
+					<?fromCalldata>
+						<?dynamicallyEncodedBase>
+							let <calldataOffset> := <accessCalldataTail>(value, add(value, mul(i, <stride>)))
+						<!dynamicallyEncodedBase>
+							let <calldataOffset> := add(value, mul(i, <stride>))
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Does it make sense to use a generic `srcPointer` and update it by adding `<stride>` at the end of each iteration as we do when copying from memory?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 29]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+					let memoryOffset := <srcDataLocation>(value)
+				</fromMemory>
+
+				let elementSlot := <dstDataLocation>(slot)
+				let elementOffset := 0
+
+				for { let i := 0 } lt(i, length) {i := add(i, 1)} {
+					<?fromCalldata>
+						<?dynamicallyEncodedBase>
+							let <calldataOffset> := <accessCalldataTail>(value, add(value, mul(i, <stride>)))
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: `let <calldataOffset>` can be pulled out of the conditional

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 30]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+			templ("dynamicallySizedBase", _fromType.baseType()->isDynamicallySized());
+			templ("dynamicallyEncodedBase", _fromType.baseType()->isDynamicallyEncoded());
+			if (_fromType.baseType()->isDynamicallyEncoded())
+				templ("accessCalldataTail", accessCalldataTailFunction(*_fromType.baseType()));
+			templ("calldataOffset", suffixedVariableNameList(
+				"calldataOffset_",
+				0,
+				_fromType.baseType()->stackItems().size()
+			));
+			templ("isRefType", !_fromType.baseType()->isValueType());
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: It looks like we don't need `isRefType`...

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 31]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+							<updateStorageValue>(elementSlot, elementOffset, <elementValues>)
+						</isValueType>
+						<?isRefType>
+							<updateStorageValue>(elementSlot, <calldataOffset>)
+						</isRefType>
+					</fromCalldata>
+
+					<?fromMemory>
+						let <elementValues> := <readFromCalldataOrMemory>(memoryOffset)
+						<updateStorageValue>(elementSlot<?isValueType>, elementOffset</isValueType>, <elementValues>)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: This line can be used for all three cases: value type from calldata, reference type from calldata and from memory

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 32]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+						memoryOffset := add(memoryOffset, <stride>)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: I think you can use `value := add(value, <stride>)` all the same. Maybe even use `value` for `memoryOffset`?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: (or `srcPtr` or something for both)

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 33]
```diff
@@ -1185,6 +1185,117 @@ string YulUtilFunctions::clearStorageStructFunction(StructType const& _type)
...
+			0,
+			_fromType.baseType()->stackItems().size()
+		));
+		templ("updateStorageValue", updateStorageValueFunction(*_fromType.baseType(), *_toType.baseType()));
+		templ("stride", to_string(fromCalldata ? _fromType.calldataStride() : _fromType.memoryStride()));
+
+		templ(
+			"updateSlotAndOffset",
+			Whiskers(R"(
+				<?multipleItemsPerSlot>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Can this be moved into the main template?

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 28 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Makes sense, updated

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 33 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I think yes, moving now

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 31 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: It can be used for all cases I think. Refactored a bit all around, moved the line at the end of the loop, just before updating storage slot and offset

**Comment by mijovic** [comment]
@chriseth updated

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 34]
```diff
@@ -808,7 +808,7 @@ string YulUtilFunctions::arrayLengthFunction(ArrayType const& _type)
 	string functionName = "array_length_" + _type.identifier();
 	return m_functionCollector.createFunction(functionName, [&]() {
 		Whiskers w(R"(
-			function <functionName>(value) -> length {
+			function <functionName>(value<?dynamic><?calldata>, len</calldata></dynamic>) -> length {
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:811]: This change might allow for simplifications elsewhere

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:811]: I'll create a follow-up pr

**Review by chriseth — APPROVED** [review]
