### PR TITLE
SMTChecker: Fix string literal to fixed bytes conversion with user-defined type

### LINKED ISSUE #15888: SMT logic error from incorrect handling of fixed bytes to user defined value type conversion
Hi! Compiling the following Solidity code with `solc a.sol --model-checker-engine all` results in a SMT logic error.

```solidity
type MyBytes is bytes2;

contract C {
  MyBytes b = MyBytes.wrap("ab");
}
```

Output: 

```
SMT logic error:
/solidity/libsmtutil/SolverInterface.h(393): Throw in function solidity::smtutil::Expression solidity::smtutil::operator==(Expression, Expression)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Trying to create an 'equal' expression with different sorts
[solidity::util::tag_comment*] = Trying to create an 'equal' expression with different sorts
```

Both `solc 0.8.29-develop.2025.2.25+commit.eb216716.Linux.g++`, `solc-0.8.27` and `solc-0.8.28` can reproduce this bug.

### PR DESCRIPTION
**Pull request by blishko**
Fixes #15888.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -929,8 +929,10 @@ void SMTEncoder::visitAddMulMod(FunctionCall const& _funCall)
 void SMTEncoder::visitWrapUnwrap(FunctionCall const& _funCall)
 {
 	auto const& args = _funCall.arguments();
-	solAssert(args.size() == 1, "");
-	defineExpr(_funCall, expr(*args.front()));
+	smtAssert(args.size() == 1, "Expected exactly one argument to wrap/unwrap");
+	auto const& funType = dynamic_cast<FunctionType const&>(*_funCall.expression().annotation().type);
+	auto argType = funType.parameterTypes().front();
```
Comment (clonker) [inline libsolidity/formal/SMTEncoder.cpp]:
```suggestion
	auto const* argType = funType.parameterTypes().front();
```

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: Updated!

**Review by clonker — APPROVED** [review]
