### PR TITLE
Fix scientific notation in number literals

### LINKED ISSUE #1671: Parser: scientific notation for numbers
The scanner has support for scientific notation (`1e1`, `1e-1`, `1e+1`, etc.), thought it is not currently working.

Is it something we want to support or should it be removed?

### PR DESCRIPTION
**Pull request by axic**
Fixes #1671.

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -575,11 +575,31 @@ tuple<bool, rational> RationalNumberType::isValidLiteral(Literal const& _literal
...
+		if (expPoint == _literal.value().end())
+			expPoint = find(_literal.value().begin(), _literal.value().end(), 'E');
 		auto radixPoint = find(_literal.value().begin(), _literal.value().end(), '.');
-		if (radixPoint != _literal.value().end())
+
+		if (expPoint != _literal.value().end())
+		{
+			if (
+				!all_of(_literal.value().begin(), expPoint, ::isdigit) ||
+				!all_of(expPoint + 1, _literal.value().end(), ::isdigit)
```
Comment (axic) [inline libsolidity/ast/Types.cpp]: This the reason it fails for `2e-2`.

**Comment by axic** [comment]
Tests fail because this is too greedy and captures hex literals too (which can contain `e`).

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -575,11 +575,39 @@ tuple<bool, rational> RationalNumberType::isValidLiteral(Literal const& _literal
 	rational x;
 	try
 	{
-		rational numerator;
-		rational denominator(1);
-		
+		auto expPoint = find(_literal.value().begin(), _literal.value().end(), 'e');
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: You can use `_literal.value().find_first_of("eE")`

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -575,11 +575,39 @@ tuple<bool, rational> RationalNumberType::isValidLiteral(Literal const& _literal
...
+		if (expPoint == _literal.value().end())
+			expPoint = find(_literal.value().begin(), _literal.value().end(), 'E');
 		auto radixPoint = find(_literal.value().begin(), _literal.value().end(), '.');
-		if (radixPoint != _literal.value().end())
+
+		if (expPoint != _literal.value().end())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: This all got quite complex now. I wonder whether it might make sense to use regular expressions instead.

File: Changelog.md [hunk 4]
```diff
@@ -19,6 +19,7 @@ Bugfixes:
  * Type system: Disallow ``var`` declaration with empty tuple type.
  * Type system: Correctly convert function argument types to pointers for member functions.
  * Type system: Move privateness of constructor into AST itself.
+ * Type system: Support scientific notation in numbers (e.g. ``2e8`` and ``200e-2``).
```
Comment (chriseth) [inline Changelog.md]: The actual code is inside the type checker, but perhaps to the user, this looks more like a parser thing? Oh and is it a bugfix or a feature?

File: test/libsolidity/SolidityParser.cpp [hunk 5]
```diff
@@ -1479,6 +1479,20 @@ BOOST_AUTO_TEST_CASE(function_type_state_variable)
 	BOOST_CHECK(successParse(text));
 }
 
+BOOST_AUTO_TEST_CASE(scientific_notation)
+{
+	char const* text = R"(
+		contract test {
+			uint256 a = 2e10;
```
Comment (chriseth) [inline test/libsolidity/SolidityParser.cpp:1486]: Please add a test here and in endtoend tests with a negative number in scientific notation.

File: libsolidity/ast/Types.cpp [hunk 6]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+}
+
+tuple<bool, rational> RationalNumberType::isValidLiteral(Literal const& _literal)
+{
+	rational x;
+	try
+	{
+		auto expPoint = _literal.value().find_first_of("eE");
+
+		if (starts_with(_literal.value.begin(), _literal.value().end(), "0x"))
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Where does `starts_with` come from? Can you use `starts_with(_literal.value, "0x")`?

File: libsolidity/ast/Types.cpp [hunk 7]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+			// parse the exponent
+			bigint exp = bigint(string(expPoint + 1, _literal.value().end()));
+
+			if (exp > numeric_limits<int32_t>::max())
+				return make_tuple(false, rational(0));
+
+			// parse the base
+			tuple<bool, rational> tmp = parseRational(string(_literal.value().begin(), expPoint));
+			if (get<0>(tmp) == false)
+			{
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: No braces needed.

File: libsolidity/ast/Types.cpp [hunk 8]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+		{
+			// parse the exponent
+			bigint exp = bigint(string(expPoint + 1, _literal.value().end()));
+
+			if (exp > numeric_limits<int32_t>::max())
+				return make_tuple(false, rational(0));
+
+			// parse the base
+			tuple<bool, rational> tmp = parseRational(string(_literal.value().begin(), expPoint));
+			if (get<0>(tmp) == false)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: `if (!get<0>(tmp))`?

File: libsolidity/ast/Types.cpp [hunk 9]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+		else if (expPoint != _literal.value().end())
+		{
+			// parse the exponent
+			bigint exp = bigint(string(expPoint + 1, _literal.value().end()));
+
+			if (exp > numeric_limits<int32_t>::max())
+				return make_tuple(false, rational(0));
+
+			// parse the base
+			tuple<bool, rational> tmp = parseRational(string(_literal.value().begin(), expPoint));
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: If you rename `tmp` to `base`, it is better readable and you might even remove the comment.

File: libsolidity/ast/Types.cpp [hunk 10]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+	}
+	catch (...)
+	{
+		return make_tuple(false, rational(0));
+	}
+}
+
+tuple<bool, rational> RationalNumberType::isValidLiteral(Literal const& _literal)
+{
+	rational x;
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Please try to avoid generic names for variables. What about `value`?

File: libsolidity/ast/Types.cpp [hunk 11]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+		{
+			// process as hex
 			x = bigint(_literal.value());
+		}
+		else if (expPoint != _literal.value().end())
+		{
+			// parse the exponent
+			bigint exp = bigint(string(expPoint + 1, _literal.value().end()));
+
+			if (exp > numeric_limits<int32_t>::max())
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: What if `exp` is negative?

File: libsolidity/ast/Types.cpp [hunk 12]
```diff
@@ -571,39 +571,104 @@ TypePointer FixedPointType::binaryOperatorResult(Token::Value _operator, TypePoi
...
+					bigint(10),
+					exp.convert_to<int32_t>()
+				);
+		}
+		else
+		{
+			// parse as rational number
+			tuple<bool, rational> tmp = parseRational(_literval.value());
+			if (get<0>(tmp) == false)
+			{
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: No braces.

File: libsolidity/ast/Types.h [hunk 13]
```diff
@@ -416,6 +416,8 @@ class RationalNumberType: public Type
 
 private:
 	rational m_value;
+
+	virtual std::tuple<bool, rational> parseRational(std::string const& _value, bool _allowRadixPoint);
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: I think `_allowRadixPoint` is not used in the implementation, is it?
Any reason to declare it virtual?

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/ast/Types.cpp (hunk 10 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: You mean the `x`? That was there originally.

File: libsolidity/ast/Types.cpp (hunk 8 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: This is a copy of a previous place in the file.

File: libsolidity/ast/Types.cpp (hunk 7 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: As above.

File: libsolidity/ast/Types.cpp (hunk 11 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: It is handled below and there are tests for it.

File: test/libsolidity/SolidityParser.cpp (hunk 5 above)
Comment (axic) [reply test/libsolidity/SolidityParser.cpp:1486]: There is one for that.

File: Changelog.md (hunk 4 above)
Comment (axic) [reply Changelog.md]: It is a bugfix in the sense the parser supported it. Not sure if it was ever supported by the type system - assuming it was, this is a bug fix, otherwise it is a feature.

Comment (chriseth) [reply Changelog.md]: If it was neither documented nor working, the feature did not exist, so I would say it is a new feature.

File: test/libsolidity/SolidityParser.cpp (hunk 5 above)
Comment (chriseth) [reply test/libsolidity/SolidityParser.cpp:1486]: Sorry, I cannot find it. I mean a number with negative mantissa, not negative exponent.

File: libsolidity/ast/Types.cpp (hunk 11 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp]: I mean negative with absolute value larger than int32_t max.

File: test/libsolidity/SolidityParser.cpp (hunk 5 above)
Comment (axic) [reply test/libsolidity/SolidityParser.cpp:1486]: Added.

File: Changelog.md (hunk 4 above)
Comment (axic) [reply Changelog.md]: Changed.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 14]
```diff
@@ -9176,6 +9176,39 @@ BOOST_AUTO_TEST_CASE(revert)
...
+			function g() returns (uint) {
+				return 200e-2 wei;
+			}
+			function h() returns (uint) {
+				return 2.5e1;
+			}
+			function i() returns (uint) {
+				return -2e10;
+			}
+			function j() returns (uint) {
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp]: I think this has to be changed to `int` here.

Comment (axic) [reply test/libsolidity/SolidityEndToEndTest.cpp]: Fixed.

File: libsolidity/ast/Types.cpp (hunk 11 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: Added check against int32_t min.

**Review by chriseth — COMMENTED** [review]
Please also add documentation.

**Review by chriseth — APPROVED** [review]
