### PR TITLE
Fix handling of structs of dynamic size as constructor parameters.

### LINKED ISSUE #6754: ABIEncoderV2 + constructor args with struct causes error while deploying
## Description
Contract
```
pragma experimental ABIEncoderV2;

contract A {
    struct Struct {
        string a;
        uint8 b;
        string c;
    }
    
    constructor(Struct memory s) public {}
}
```
reverts while deploying with arg:
```
{
  a: "",
  b: 0,
  c: ""
}
```

## Environment

- Compiler version: 0.5.8
- Target EVM version: petersburg

## Steps to Reproduce

As description.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #6754

Does this deserve an entry in the bug list? The issue is that if all variables are statically sized and at least one is dynamically encoded (but statically sized), not enough data is copied to memory for the decoder.

I think the only types that are statically sized but dynamically encoded are structs or multi-dimensional arrays where the outer arrays is statically-sized.

As far as I know, such types are only supported by ABIV2, so this is not as bad as it sounds.

### CODE REVIEW

**Review by ekpyron — DISMISSED** [review]
I wonder whether we should just always use the ``argumentSize == 0`` codepath... the program size is appended later anyways, ``CODESIZE`` and ``SUB`` are cheap... so is there a difference in cost at all?
Anyways: fine to merge this fix!

**Comment by ekpyron** [comment]
I'd tend to think that this warrants a buglist entry - ABIEncoderV2 is experimental, but if it is used already, then I guess it's most likely used for structs and possibly also in the constructor - so it might be good to emphasize this at least a bit.

**Comment by ekpyron** [comment]
The tests need to be disabled for homestead, though.

**Comment by chriseth** [comment]
You are right, if we always use `codesize` then we get proper range checks.

**Comment by ekpyron** [comment]
The comment before calling abiDecode states ``// stack: <memptr>`` - that's probably wrong - it should be ``<memptr> <length>``... but it currently is ``<memptr> <end>`` isn't it? That'd be wrong too then - but I might have misread it. Anyways: yes: proper range checks would be nice and I think the costs shouldn't differ much for small ``argumentSize`` and should even be cheaper for large ones.

**Comment by ekpyron** [comment]
This still needs:
 - Disabling the new test cases for homestead, since the types are not available there.
 - Investigating the ``store_keccak256`` GasMeterTest and deciding whether we should consider that a problem.
 - ``abiDecode`` in ContractCompiler.cpp:L259, resp. now L244 is still called with a wrong second argument (it's passed the memory end ptr - ``abiDecode`` expects the length, though, and will itself perform a ``offset + length`` addition), which is still preventing correct range checks in the decoder - maybe we should also have a test case for that (i.e. short arguments revert at least with ABIEncoderV2? Not sure what the old decoder does in that case).

**Comment by chriseth** [comment]
Still investigating store_keccak256, the other issues are hopefully fixed.

**Comment by chriseth** [comment]
The `store_keccak256` test failed because no constructor argument was supplied and we did not do any bounds check before for fixed-size constructor parameters.

File: test/libsolidity/GasMeter.cpp [hunk 1]
```diff
@@ -176,8 +176,8 @@ BOOST_AUTO_TEST_CASE(store_keccak256)
 	char const* sourceCode = R"(
 		contract test {
 			bytes32 public shaValue;
-			constructor(uint a) public {
-				shaValue = keccak256(abi.encodePacked(a));
+			constructor() public {
+				shaValue = keccak256(abi.encodePacked(this));
```
Comment (ekpyron) [inline test/libsolidity/GasMeter.cpp:180]: I'm not quite sure why this is needed and why it works, actually...

**Review by ekpyron — APPROVED** [review]
Despite me not understanding the reasoning behind the gas meter test, I would say this is fine now!

File: test/libsolidity/GasMeter.cpp (hunk 1 above)
Comment (chriseth) [reply test/libsolidity/GasMeter.cpp:180]: The test input did not provide the constructor argument. Previously, it worked because something else was used instead... Now we have the check.

The parameter to `keccak256` has to be dynamic, otherwise the optimizer will just replace it by a constant.
