### PR TITLE
[Yul] Disallow function definitions inside for loop init blocks

### LINKED ISSUE #6532: [Yul] interpreter: function call before function definition inside for loop init block leads to an assertion failure because the function is not yet registered
## Description

The following code snippet

```
{
  for{foo() function foo() {}} 0 {}
  {
  }
}
```

fails this assertion

https://github.com/ethereum/solidity/blob/6b12726f51c25840b3ccb231018fc37e994869e7/test/tools/yulInterpreter/Interpreter.cpp#L191

## Environment

- Compiler version: latest develop commit

## Steps to Reproduce

```
$ ./test/tools/yulrun --input-file <file.yul>
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<langutil::InternalCompilerError>'
  what():  
Aborted (core dumped)
```

### LINKED ISSUE #6541: [yul] break-continue statement design
## Description

Is the following yul program supposed to be valid?

```
{
  for {{let x for {} x {} { break }}} 1 {} {}
}
```

The `break` is in the `for` loop body scope which itself is nested within a for loop init block.

### PR DESCRIPTION
**Pull request by sifmelcara**
Probably closes #6541 by adding examples proposed by @bshastry in the issue as tests.

Regarding to error message, I did not fully followed @bshastry 's suggestion in https://github.com/ethereum/solidity/issues/6541#issuecomment-484110149 because I found that we will need extra member variables in Parser class to implement it.

Fixes https://github.com/ethereum/solidity/issues/6532

### CODE REVIEW

File: libyul/AsmParser.cpp [hunk 1]
```diff
@@ -105,28 +106,44 @@ Statement Parser::parseStatement()
...
 			return stmt;
 		}
 		else
 		{
-			m_errorReporter.syntaxError(location(), "Keyword break outside for-loop body is not allowed.");
+			if (
+				m_currentForLoopComponent == ForLoopComponent::ForLoopPre ||
+				m_currentForLoopComponent == ForLoopComponent::ForLoopPost
+			)
+				m_errorReporter.syntaxError(location(), "Keyword break in for-loop init/post block is not allowed.");
```
Comment (bshastry) [inline libyul/AsmParser.cpp]: Could this be split into more specific error message like so?

```
			if (m_currentForLoopComponent == ForLoopComponent::ForLoopPre)
				m_errorReporter.syntaxError(location(), "Keyword break in for-loop init block is not allowed.");
            else if (m_currentForLoopComponent == ForLoopComponent::ForLoopPost)
				m_errorReporter.syntaxError(location(), "Keyword break in for-loop post block is not allowed.");
```

File: libyul/AsmParser.h [hunk 2]
```diff
@@ -29,17 +29,25 @@
...
+
 namespace yul
 {
 
 class Parser: public langutil::ParserBase
 {
 public:
+	enum class ForLoopComponent
+	{
+		ForLoopPre, ForLoopPost, ForLoopBody
```
Comment (chriseth) [inline libyul/AsmParser.h]: Why not add `None` instead of using it together with boost::optional?

File: libyul/AsmParser.cpp [hunk 3]
```diff
@@ -105,28 +106,44 @@ Statement Parser::parseStatement()
...
+		if (m_currentForLoopComponent == ForLoopComponent::ForLoopBody)
 		{
 			auto stmt = Statement{ createWithLocation<Break>() };
 			m_scanner->next();
 			return stmt;
 		}
 		else
 		{
-			m_errorReporter.syntaxError(location(), "Keyword break outside for-loop body is not allowed.");
+			if (
```
Comment (chriseth) [inline libyul/AsmParser.cpp]: Can you extract these lines into a function and use it for both `break` and `continue`?

File: libyul/AsmParser.cpp [hunk 4]
```diff
@@ -105,28 +106,44 @@ Statement Parser::parseStatement()
...
+		if (m_currentForLoopComponent == ForLoopComponent::ForLoopBody)
 		{
 			auto stmt = Statement{ createWithLocation<Continue>() };
 			m_scanner->next();
 			return stmt;
 		}
 		else
 		{
-			m_errorReporter.syntaxError(location(), "Keyword continue outside for-loop body is not allowed.");
+			if (
```
Comment (chriseth) [inline libyul/AsmParser.cpp]: If you use `switch`, then the compiler will tell you if you handled all cases instead of requiring a runtime assert.

**Review by chriseth — CHANGES_REQUESTED** [review]
Looks good in general, but I think the code can be cleaned up up a little further.

File: libyul/AsmParser.cpp [hunk 5]
```diff
@@ -105,28 +106,44 @@ Statement Parser::parseStatement()
...
+				m_currentForLoopComponent == ForLoopComponent::ForLoopPre ||
+				m_currentForLoopComponent == ForLoopComponent::ForLoopPost
+			)
+				m_errorReporter.syntaxError(location(), "Keyword continue in for-loop init/post block is not allowed.");
```
Comment (bshastry) [inline libyul/AsmParser.cpp]: Same comment as for `break` statement

File: test/libyul/Parser.cpp [hunk 6]
```diff
@@ -359,10 +379,26 @@ BOOST_AUTO_TEST_CASE(for_statement_continue_fail_post)
...
+		"Keyword continue in for-loop init/post block is not allowed.",
+		dialect);
+}
+
+BOOST_AUTO_TEST_CASE(for_statement_continue_nested_body_in_init)
+{
+	auto dialect = EVMDialect::strictAssemblyForEVMObjects(EVMVersion::constantinople());
+	BOOST_CHECK(successParse("{ for {let x for {} x {} { continue }} 1 {} {} }", dialect));
+}
+
```
Comment (bshastry) [inline test/libyul/Parser.cpp:420]: For completeness, we can add the following test cases

```
BOOST_AUTO_TEST_CASE(for_statement_break_nested_body_in_init)
{
	auto dialect = EVMDialect::strictAssemblyForEVMObjects(EVMVersion::constantinople());
	BOOST_CHECK(successParse("{ for {let x for {} x {} { break }} 1 {} {} }", dialect));
}

BOOST_AUTO_TEST_CASE(for_statement_continue_nested_body_in_post)
{
	auto dialect = EVMDialect::strictAssemblyForEVMObjects(EVMVersion::constantinople());
	BOOST_CHECK(successParse("{ for {} 1 {let x for {} x {} { continue }} {} }", dialect));
}

BOOST_AUTO_TEST_CASE(for_statement_break_nested_body_in_post)
{
	auto dialect = EVMDialect::strictAssemblyForEVMObjects(EVMVersion::constantinople());
	BOOST_CHECK(successParse("{ for {} 1 {let x for {} x {} { break }} {} }", dialect));
}
```

**Review by bshastry — COMMENTED** [review]
Comment regarding making error message more fine-grained and adding more tests for completeness.

**Comment by chriseth** [comment]
If you don't mind - I'll take this over and also add the "feature" to disallow function declarations in `pre` blocks of for loops.

**Comment by chriseth** [comment]
Please review, @bshastry

File: test/libyul/Parser.cpp (hunk 6 above)
Comment (chriseth) [reply test/libyul/Parser.cpp:420]: Added.

File: Changelog.md [hunk 7]
```diff
@@ -7,6 +7,7 @@ Important Bugfixes:
 Language Features:
  * Code Generation: Implement copying recursive structs from storage to memory.
  * ABIEncoderV2: Implement encoding of calldata arrays and structs.
+ * Yul: Disallow function definitions inside for-loop init blocks.
```
Comment (sifmelcara) [inline Changelog.md:10]: Would it make sense to also disallow function definition inside for-loop post blocks?

File: libyul/AsmParser.cpp [hunk 8]
```diff
@@ -26,6 +26,7 @@
 #include <libdevcore/Common.h>
 
 #include <boost/algorithm/string.hpp>
+#include <boost/optional.hpp>
```
Comment (sifmelcara) [inline libyul/AsmParser.cpp]: Now this line can be deleted

File: libyul/AsmParser.h [hunk 9]
```diff
@@ -29,17 +29,25 @@
 #include <liblangutil/Scanner.h>
 #include <liblangutil/ParserBase.h>
 
+#include <boost/optional.hpp>
```
Comment (sifmelcara) [inline libyul/AsmParser.h]: Also this line

**Review by sifmelcara — COMMENTED** [review]
:+1: Please feel free to take over

File: Changelog.md (hunk 7 above)
Comment (chriseth) [reply Changelog.md:10]: post blocks do not have irregular scoping rules, they are just as any other block.

**Comment by chriseth** [comment]
Updated.

File: docs/yul.rst [hunk 10]
```diff
@@ -167,6 +167,7 @@ The ``continue`` and ``break`` statements can only be used inside loop bodies
 and have to be in the same function as the loop (or both have to be at the
 top level).
 The condition part of the for-loop has to evaluate to exactly one value.
+Functions cannot be defined inside for loop init blocks.
```
Comment (bshastry) [inline docs/yul.rst:170]: Nit: Do we refer to the block as for init or for pre (as in the title)?

File: test/libyul/Parser.cpp [hunk 11]
```diff
@@ -333,8 +357,9 @@ BOOST_AUTO_TEST_CASE(for_statement_nested_break)
 	CHECK_ERROR_DIALECT(
 		"{ for {let i := 0} iszero(eq(i, 10)) {} { function f() { break } } }",
 		SyntaxError,
-		"Keyword break outside for-loop body is not allowed.",
-		dialect);
+		"Keyword \"break\" needs to be inside a for-loop body.",
+		dialect
+	);
```
Comment (bshastry) [inline test/libyul/Parser.cpp:362]: How about adding a symmetric test case for continue?

```
	CHECK_ERROR_DIALECT(
		"{ for {let i := 0} iszero(eq(i, 10)) {} { function f() { continue } } }",
		SyntaxError,
		"Keyword continue outside for-loop body is not allowed.",
		dialect);
		"Keyword \"continue\" needs to be inside a for-loop body.",
		dialect
	);
```

File: test/libyul/Parser.cpp [hunk 12]
```diff
@@ -359,8 +385,57 @@ BOOST_AUTO_TEST_CASE(for_statement_continue_fail_post)
...
+	auto dialect = EVMDialect::strictAssemblyForEVMObjects(EVMVersion{});
+	BOOST_CHECK(successParse("{ for { } 1 { function f() {} } {} }", dialect));
+	BOOST_CHECK(successParse("{ for { } 1 {} { function f() {} } }", dialect));
+	CHECK_ERROR_DIALECT(
+		"{ for { function f() {} } 1 {} {} }",
+		SyntaxError,
+		"Functions cannot be defined inside a for-loop init block.",
+		dialect
+	);
 }
```
Comment (bshastry) [inline test/libyul/Parser.cpp:450]: How about adding a nested test case like so?

### failing_function_def_in_init_nested_by_post

```
{
for {} 1 {for {function foo {}} 1 {} {} } {}
}
```

### passing_function_def_in_post_nested_by_init

```
{
for {for {} 1 {function foo {}} {}} 1 {} {}
}
```

**Review by bshastry — CHANGES_REQUESTED** [review]
LGTM with the minor addition of a few other test cases.

File: docs/yul.rst (hunk 10 above)
Comment (chriseth) [reply docs/yul.rst:170]: This document seems to use "init" consistently.

**Review by bshastry — APPROVED** [review]

**Review by chriseth — APPROVED** [review]
