### PR TITLE
Proper type checking for bound functions

### LINKED ISSUE #561: The `using` keyword causes `unknown exception` if the recipient method is not found
This code causes `Unknown exception during compilation.`:

```
library B {
    function b() {
    }
}

contract A {
    using B for bytes;

    function a() {
        bytes memory x;
        x.b();
    }
}
```

Adding the proper parameter type (i.e. `function b(bytes a) {`) to `B.b()` fixes it.

### PR DESCRIPTION
**Pull request by axic**
Fixes #561 and #1216.

The reason this is becoming increasingly complex is that when a `FunctionType` is bound, `parameterTypes()`, `parameterNames()`, etc. will skip the first argument without validation.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1146,6 +1146,11 @@ bool TypeChecker::visit(FunctionCall const& _functionCall)
 	else
 		_functionCall.annotation().type = make_shared<TupleType>(functionType->returnParameterTypes());
 
+	if (functionType->bound() && !functionType->hasSelfType()) {
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Shouldn't that be an internal compiler error?

File: libsolidity/ast/Types.h [hunk 2]
```diff
@@ -881,6 +881,7 @@ class FunctionType: public Type
 	std::vector<std::string> const returnParameterTypeNames(bool _addDataLocation) const;
 	/// @returns the "self" parameter type for a bound function
 	TypePointer selfType() const;
+	virtual bool hasSelfType() const { return bound() && m_parameterTypes.size() > 0; }
```
Comment (chriseth) [inline libsolidity/ast/Types.h]: I think it should not be possible to construct a function type that is bound but does not have a self type.

**Review by chriseth — CHANGES_REQUESTED** [review]
We should probably talk about this PR personally.

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/analysis/TypeChecker.cpp]: `b.b()` will first cause `MemberAccess` and then `FunctionCall` visits, if the latter is an ICE then the whole thing is an ICE.

File: libsolidity/ast/Types.h (hunk 2 above)
Comment (pirapira) [reply libsolidity/ast/Types.h]: I created #1216 for this.

**Comment by pirapira** [comment]
To me the changes made sense.

File: libsolidity/ast/Types.h (hunk 2 above)
Comment (axic) [reply libsolidity/ast/Types.h]: I think the above code in the typechecker is the place where it should be checked. How can you check during the `using` statement? The contract should be able to have non-bound functions too.

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp]: I think that the member lookup should fail in the first place, or do I have a example case in mind? Could you add a test case for this?

**Review by chriseth — CHANGES_REQUESTED** [review]

**Comment by axic** [comment]
This was updated to refuse creating bound functions without a self type. This feels like the proper fix, with a downside: error reporting is negatively impacted.

**Review by chriseth — APPROVED** [review]
