### PR TITLE
Fix assignment of struct containing array of mappings

### LINKED ISSUE #6783: Struct containing an array of mappings crash
## Description

What happens: compiler crashes.

Expected: user-friendly error, or successful compile.
## Environment

- Compiler version: 0.5.5+commit.47a71e8f.Darwin.appleclang
- Operating system: MacOS 10.12.6

## Steps to Reproduce

```solidity
pragma solidity >=0.5.0;

contract StructsMappingArrays {

  struct A {
    mapping(int=>int)[] m;
  }

  A a1;

  function() external payable {
    A memory ma = A();
    a1.m.length = 3;
    a1 = ma;
    assert(a1.m.length == 3);
  }

}
```

Current output:
```
Internal compiler error during compilation:
/tmp/solidity-20190307-21448-1jpsebx/solidity_0.5.5/libsolidity/ast/Types.cpp(2232): Throw in function u256 dev::solidity::StructType::memoryOffsetOfMember(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Member not found in struct.
[dev::tag_comment*] = Member not found in struct.
```

### PR DESCRIPTION
**Pull request by sifmelcara**
### Description

Closes #6783 

I think we need to add a test, but not sure where is suitable for this test case. `syntaxTests` is not enough because the bug need actual codegen to happen to reproduce; run time tests that need IPC seems like an overkill.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### CODE REVIEW

File: libsolidity/codegen/LValue.cpp [hunk 1]
```diff
@@ -313,9 +314,9 @@ void StorageItem::storeValue(Type const& _sourceType, SourceLocation const& _loc
 			solAssert(sourceType.location() != DataLocation::CallData, "Structs in calldata not supported.");
 			for (auto const& member: structType.members(nullptr))
 			{
-				// assign each member that is not a mapping
+				// assign each member that can live outside of storage
 				TypePointer const& memberType = member.type;
-				if (memberType->category() == Type::Category::Mapping)
+				if (!memberType->canLiveOutsideStorage())
```
Comment (chriseth) [inline libsolidity/codegen/LValue.cpp:319]: Hm, that also excludes copying of arrays of structs that contain mappings, right? I think they should still be copied, because there is still something to copy. On the other hand: What does the type checker say about these?

We plan to disallow such types being used in memory altogether with 0.6.0, so if this is too much work, it is probably not worth it.

Comment (sifmelcara) [reply libsolidity/codegen/LValue.cpp:319]: > Hm, that also excludes copying of arrays of structs that contain mappings, right?

I don't think so

Array's `canLiveOutsideStorage` depends on base type
https://github.com/ethereum/solidity/blob/9a00729ce750997920851a8a18c17d1797e852af/libsolidity/ast/Types.h#L708

Struct's `canLiveOutsideStorage` is always true.
https://github.com/ethereum/solidity/blob/9a00729ce750997920851a8a18c17d1797e852af/libsolidity/ast/Types.h#L836

So `arrayOfStructThatContainMappingsType.canLiveOutsideStorage()` should be true.

PS.
For each member of struct, it will recursively call `storeValue()`
https://github.com/ethereum/solidity/pull/6833/files/15e41ee4954aba6173ca5041bdf3f4f5b1e1ba4e#diff-bba7240285384c9f6e5edd7942acc957L346
That's why struct's `canLiveOutsideStorage()` can always return true.

Comment (chriseth) [reply libsolidity/codegen/LValue.cpp:319]: Ah that1s great! So I think nothing needs to be changed here.

Can you please add a test, though? I don't think semantic tests are overkill here - it is always good to also verify the semantics of code generation.

Please also add a test that uses an array of a struct that only contains a mapping - i'm curious because this more or less generates an empty struct.

Comment (sifmelcara) [reply libsolidity/codegen/LValue.cpp:319]: > On the other hand: What does the type checker say about these?

I didn't see any strange behavior.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Thanks a lot!
