### PR TITLE
abi.encodeCall for declarations.

### LINKED ISSUE #12435: abi.encodeCall of contractName.functionName doesn't work
## Description
The documentation of encodeCall shows:
```solidity
abi.encodeCall(contractName.functionName, (arg1, arg2, arg3)) 
```
https://blog.soliditylang.org/2021/12/20/solidity-0.8.11-release-announcement/

However when trying to make a POC this actually doesn't work.
It only works with a function pointer, which could be deduced from the rest of the documentation.
Note: encodeWithSelector works with both contractName.functionName and a function pointer.
See example below
Suggestion: Update the documentation and/or implement this feature

## Environment
Solidity 0.8.11 in Remix

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity =0.8.11;
import "hardhat/console.sol";  

contract OtherContract {
   function hi(uint n) public  {
     console.log("hi",n);
   }
}

contract Account {
   OtherContract c=new OtherContract();
   
  constructor() {
    (bool success1, bytes memory data1) = address(c).call(abi.encodeWithSelector(OtherContract.hi.selector,1));
    (bool success2, bytes memory data2) = address(c).call(abi.encodeWithSelector(c.hi.selector,2));
    (bool success3, bytes memory data3) = address(c).call(abi.encodeCall(c.hi,(3)));
    //(bool success4, bytes memory data4) = address(c).call(abi.encodeCall(OtherContract.hi,(4))); // TypeError: Function must be public or external
  }
}
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/12435

TODO:
 - [x] changelog entry
 - [x] general tests
 - [x] test to check if this works properly if referencing a base contract function.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2132,6 +2135,11 @@ void TypeChecker::typeCheckABIEncodeCallFunction(FunctionCall const& _functionCa
 			ssl.append("Function is declared here:", functionPointerType->declaration().location());
 			if (functionPointerType->declaration().scope() == m_currentContract)
 				msg += " Did you forget to prefix \"this.\"?";
+			else if (contains(
+				m_currentContract->annotation().linearizedBaseContracts,
+				functionPointerType->declaration().scope()
+			))
+				msg += " Functions from base contracts have to be external.";
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp:2153]: This will make the user think you can't use a function at with `abi.encodeCall()` when it's public. Make we should suggest assigning it to a function pointer or using a contract variable instead?

File: test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+        (success, result) = t.staticcall(abi.encodeCall(Base.a, 100));
+        require(success && result.length == 32);
+        r += abi.decode(result, (uint));
+        require(r == 114);
+
+        (success, result) = t.staticcall(abi.encodeCall(this.a, 1000));
+        require(success && result.length == 32);
+        r += abi.decode(result, (uint));
+        require(r == 1115);
```
Comment (cameel) [inline test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol]: I don't think `+=` and `==` work on `bytes`.

Also, why add to `r` instead of just overwriting it? Would make the logic simpler. It took me a moment to see why you're not expecting 1000 here but I'm still not sure why it's 1115.

File: test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+contract Base {
+    function a(uint x) external pure returns (uint) { return x + 1; }
+}
+
+contract C is Base {
+	function test() public view returns (uint r) {
+        address t = address(this);
+        bool success;
+        bytes memory result;
+        (success, result) = t.staticcall(abi.encodeCall(X.a, 1));
```
Comment (cameel) [inline test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol]: I think it's much easier to read without helper variables, especially when their names are just single letters.
```suggestion
        (success, result) = address(this).staticcall(abi.encodeCall(X.a, 1));
```

File: test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol [hunk 4]
```diff
@@ -0,0 +1,49 @@
+pragma abicoder v2;
```
Comment (cameel) [inline test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol]: This test should be called `abi_encode_call_declaration.sol` to match others in the same directory.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall.sol [hunk 5]
```diff
@@ -2,81 +2,49 @@ interface I {
...
+contract Base {
+	function baseFunctionExternal(uint) external pure {}
+}
 
+contract C is Base {
 	function f(int a) public {}
 	function f2(int a, string memory b) public {}
 	function f3(int a, int b) public {}
 	function f4() public {}
 	function fInternal(uint256 p, string memory t) internal {}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall.sol]: These seem unused now.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_args.sol [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+
+library L {
+	function fExternal(uint256 p, string memory t) external {}
+	function fInternal(uint256 p, string memory t) internal {}
+}
+
+contract Base {
+	function baseFunction(uint) internal pure {}
+	function baseFunctionExternal(uint) external pure {}
+}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_args.sol]: This seems unused.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+	function baseFunctionPublic(uint) public pure {}
+}
+
+contract C is Base {
+	using L for uint256;
+
+	function f(int a) public {}
+	function f2(int a, string memory b) public {}
+	function f3(int a, int b) public {}
+	function f4() public {}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol]: This seems unused.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+	function fInternal(uint) internal pure {}
+}
+
+library L {
+	function fExternal(uint256 p, string memory t) external {}
+	function fInternal(uint256 p, string memory t) internal {}
+}
+
+contract Base {
+	function baseFunction(uint) internal pure {}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol]:
```suggestion
	function baseFunctionInternal(uint) internal pure {}
```

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+	function baseFunctionPublic(uint) public pure {}
+}
+
+contract C is Base {
+	using L for uint256;
+
+	function f(int a) public {}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol]:
```suggestion
	function fPublic(int a) public {}
```

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+	function failLibraryPointerCall() public {
+		abi.encodeCall(L.fInternal, (1, "123"));
+		abi.encodeCall(L.fExternal, (1, "123"));
+	}
+	function failBoundLibraryPointerCall() public returns (bytes memory) {
+		uint256 x = 1;
+		return abi.encodeCall(x.fExternal, (1, "123"));
+	}
+	function viaBaseDeclaration() public pure returns (bytes memory) {
+		return abi.encodeCall(C.f, (2));
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol]: The error here is
```
Function must be "public" or "external". Did you forget to prefix "this."?
```
I think it would be better to get the same one you get when you use a public function from base class because it better explains why this does not work.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+		return abi.encodeCall(localFunctionPointer, (1, "123"));
+	}
+	function failLibraryPointerCall() public {
+		abi.encodeCall(L.fInternal, (1, "123"));
+		abi.encodeCall(L.fExternal, (1, "123"));
+	}
+	function failBoundLibraryPointerCall() public returns (bytes memory) {
+		uint256 x = 1;
+		return abi.encodeCall(x.fExternal, (1, "123"));
+	}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol:49]: All of these give this error currently:
```
Function must be "public" or "external".
```
But two of these are already external. I think that we should have a more specific error message for library functions.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 12]
```diff
@@ -0,0 +1,72 @@
...
+contract Other {
+	function fExternal(uint) external pure {}
+	function fPublic(uint) public pure {}
+	function fInternal(uint) internal pure {}
+}
+
+library L {
+	function fExternal(uint256 p, string memory t) external {}
+	function fInternal(uint256 p, string memory t) internal {}
+}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol:14]: Can you also add a free function to the test?

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 13]
```diff
@@ -0,0 +1,72 @@
...
+	}
+	function failFunctionPtrWrongType() public returns(bytes memory) {
+		return abi.encodeCall(abi.encodeCall, (1, 2, 3, "test"));
+	}
+	function failFunctionInternal() public returns(bytes memory) {
+		return abi.encodeCall(fInternal, (1, "123"));
+	}
+	function failFunctionInternalFromVariable() public returns(bytes memory) {
+		function(uint256, string memory) internal localFunctionPointer = fInternal;
+		return abi.encodeCall(localFunctionPointer, (1, "123"));
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol:40]: The error here is:
```
Error: Function must be "public" or "external". Did you forget to prefix "this."?
```
I think we should not add this part about `this` when it's a pointer stored in a variable.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol [hunk 14]
```diff
@@ -0,0 +1,72 @@
...
+	}
+	function viaBaseDeclaration() public pure returns (bytes memory) {
+		return abi.encodeCall(C.f, (2));
+	}
+	function viaBaseDeclaration() public pure returns (bytes memory) {
+		return bytes.concat(
+			abi.encodeCall(Base.baseFunctionPublic, (1)),
+			abi.encodeCall(Base.baseFunction, (1))
+		);
+	}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol]: Both functions are called `viaBaseDeclaration()`. That's an error (and not one we're supposed to test here :)).

**Review by cameel — CHANGES_REQUESTED** [review]

**Comment by cameel** [comment]
> Fixes #12435

Before we can use that here we also need to change the blog post because that's a part of the issue.

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:2153]: Ok, this is actually true. But if it works if you assign it to an external function pointer, then it should also work without, shouldn't it? Maybe we can perform an implicit conversion or something.

Comment (cameel) [reply libsolidity/analysis/TypeChecker.cpp:2153]: Yeah, that would be even better. I thought about suggesting that but I wasn't sure how complicated it would be.

But I just checked to make sure this workaround would even work - and turns out it does not. We don't have a contract address on a function pointer referenced like that so you can't directly assign it to a function pointer:
```solidity
contract Base {
    function baseFunctionPublic(uint) public pure {}
}

contract C is Base {
    function viaBaseDeclaration() public pure  {
        function(uint) external pure fPtr = Base.baseFunctionPublic;
        abi.encodeCall(fPtr, (1));
    }
}
```
```
Error: Type function (uint256) pure is not implicitly convertible to expected type function (uint256) pure external. Special functions can not be converted to function types.
 --> test.sol:7:9:
  |
7 |         function(uint) external pure fPtr = Base.baseFunctionPublic;
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

**Comment by bshastry** [comment]
Is this legal? Or is it rightly illegal?

```
contract C {
  function f() external { abi.encodeCall(C.f, ()); } // Error: Function must be "public" or "external".
}
```

Edit:

Funnily enough, the following already works. I suppose this is because `this.g` is not referencing the declaration but a pointer to an externally callable function.

```
contract C {
  function g() public { abi.encodeCall(this.g, ()); }
}
```

However, encoding a call to a public function declaration does not work but selector on the said declaration works:

```
contract C {
  function g() public {}
  function h() external { abi.encodeCall(C.g, ()); } // Error: Function must be "public" or "external".
}

contract D {
  function i() external { abi.encodeCall(C.g, ()); } // Error: Function must be "public" or "external".
  function j() external { C.g.selector; } // Works
}
```

**Comment by cameel** [comment]
Oh, we should definitely have this as a test.

I think it should be legal because you don't really have to call the function right away. You could just store it somewhere and call later. Whether such a construct would be actually useful in practice is another matter though :)

File: test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol (hunk 2 above)
Comment (chriseth) [reply test/libsolidity/semanticTests/abiencodedecode/abi_encodecall_declaration.sol]: This is just to catch errors that could cancel each other out, and to detect where something went wrong.
Also note that `r` is `uint` and not `bytes`.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol (hunk 13 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol:40]: Oh interesting that it still has "hasDeclaration" set to true...

Comment (chriseth) [reply test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol:40]: Ah sorry, I think the error you quoted is from line 34, i.e. `abi.encodeCall(abi.encodeCall`

**Comment by chriseth** [comment]
Ok, I think this is as good as it gets WRT error messages.

**Comment by chriseth** [comment]
The example by @bshastry is working now, added a test for it.

File: test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol (hunk 11 above)
Comment (bshastry) [reply test/libsolidity/syntaxTests/specialFunctions/encodeCall_fail_funType.sol:49]: Would just like to add that the following compiles without an error

```
library L0 { function f(uint) public {} }
library L1 { function g() public { abi.encodeWithSelector(L0.f.selector, 1); } }
```

Also

```
library L {
  function f() external {}
  function g() internal { L.f.selector; }
}
```

Both of the above tests error via `abi.encodeCall` so there is an asymmetry to it i.e., users may still make use of the type unsafe `abi.encodeWithSelector` but not yet make use of the type safe `abi.encodeCall` alternative

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (bshastry) [reply libsolidity/analysis/TypeChecker.cpp:2153]: Why are base contract public functions not supported by `abi.encodeCall`?

**Review by Marenz — CHANGES_REQUESTED** [review]
PR looks good to me, though CI is still failing

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:2153]: `BaseContract.functionName` is the way to call the base implementation of a potentially virtual function, so it is an internal access.

**Comment by chriseth** [comment]
Restricted the test to `>=byzantium` - so this hopefully works now.

**Review by Marenz — APPROVED** [review]

**Comment by 134dd3v** [comment]
Any idea when the new version that includes the fix'd be available?

**Comment by cameel** [comment]
Can't give you a firm date on this but we usually release once per 1-2 months (when there's enough new stuff accumulated to be worth a release) - unless there's a security issue or a critical bug. I think you can expect this to be released somewhere in February.
