### PR TITLE
check enum value range during conversion

### LINKED ISSUE #1311: Check enums for overflow during conversion
Solidity should throw an exception for conversions to enum that do not fit the enum.

### LINKED ISSUE #1343: Enum constructor accepts signed int
```
contract C {
    enum ActionChoices { GoLeft, GoRight, GoStraight }
	function getChoice() returns (int d)
	{
	    return int(ActionChoices(-1));
	}
}
```

Returns `-1`, which is invalid enum value.

### LINKED ISSUE #1346: Empty enums are allowed by the compiler
```
contract C {
    enum Empty { }
}
```

This will be a useless construct after #1311 is fixed.

### PR DESCRIPTION
**Pull request by pirapira**
Fixes #1311; fixes #1343 and fixes #1346.

### CODE REVIEW

File: libsolidity/codegen/CompilerUtils.cpp [hunk 1]
```diff
@@ -656,6 +656,15 @@ void CompilerUtils::convertType(Type const& _typeOnStack, Type const& _targetTyp
 		solAssert(_typeOnStack == _targetType, "Invalid type conversion requested.");
 		break;
 	}
+
+	// Check the conversion result fits in a range.
+	if (targetTypeCategory == Type::Category::Enum)
+	{
+		EnumType const* enumType = dynamic_cast<decltype(enumType)>(&_targetType);
+		solAssert(enumType, "targetTypeCategory is wrong.");
+		m_context << u256(enumType->numberOfMembers()) << Instruction::DUP2 << Instruction::LT << Instruction::ISZERO;
```
Comment (axic) [inline libsolidity/codegen/CompilerUtils.cpp]: How about `m_context << u256(enumType->numberOfMembers() - 1) << Instruction::DUP2 << Instruction::GT;`?

File: libsolidity/ast/Types.h [hunk 2]
```diff
@@ -738,6 +738,7 @@ class EnumType: public Type
 	EnumDefinition const& enumDefinition() const { return m_enum; }
 	/// @returns the value that the string has in the Enum
 	unsigned int memberValue(ASTString const& _member) const;
+	size_t numberOfMembers() const;
```
Comment (axic) [inline libsolidity/ast/Types.h:741]: Would it make sense including the body here?

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 3]
```diff
@@ -3314,6 +3314,35 @@ BOOST_AUTO_TEST_CASE(using_enums)
...
+					d = uint256(choices);
+				}
+				ActionChoices choices;
+			}
+	)";
+	compileAndRun(sourceCode);
+	// throws
+	BOOST_CHECK(callContractFunction("getChoiceExp()") == encodeArgs());
+	// also throws
+	BOOST_CHECK(callContractFunction("getChoiceFromEnum()") == encodeArgs());
```
Comment (axic) [inline test/libsolidity/SolidityEndToEndTest.cpp]: Can you add tests for the edge case (value == limit)?

Do we have also have tests for the other success cases?

**Review by axic — CHANGES_REQUESTED** [review]
Document this in the "where exceptions happen" section.

File: libsolidity/codegen/CompilerUtils.cpp (hunk 1 above)
Comment (pirapira) [reply libsolidity/codegen/CompilerUtils.cpp]: I feel uncertain about enums with no members.

File: libsolidity/ast/Types.h (hunk 2 above)
Comment (pirapira) [reply libsolidity/ast/Types.h:741]: At this location, `class EnumDefinition` is only forward-declared, so I cannot look at its contents.

File: test/libsolidity/SolidityEndToEndTest.cpp (hunk 3 above)
Comment (pirapira) [reply test/libsolidity/SolidityEndToEndTest.cpp]: I added success cases.

**Comment by pirapira** [comment]
@axic I added one clause in the list of exceptions.

File: libsolidity/codegen/CompilerUtils.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/codegen/CompilerUtils.cpp]: Are those valid in the first place?

Comment (pirapira) [reply libsolidity/codegen/CompilerUtils.cpp]: Currently I get no error or warning messages for `enum empty {}`.

**Comment by axic** [comment]
Don't forget the changelog 😉

File: libsolidity/codegen/CompilerUtils.cpp (hunk 1 above)
Comment (axic) [reply libsolidity/codegen/CompilerUtils.cpp]: If we fix that condition, the assembly can be simplified. Either we do that in this PR or separately. However, since limiting enum values is a breaking change in some way  (will break code) and that construct is useless after merging this PR we could as well just fix it here.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 4]
```diff
@@ -3314,6 +3314,55 @@ BOOST_AUTO_TEST_CASE(using_enums)
...
+					d = uint256(choice);
+				}
+				function getChoiceFromEnum() returns (uint d)
+				{
+					choice = ActionChoices(Dummy.Dummy3);
+					d = uint256(choice);
+				}
+				function getChoiceFromEnumOk() returns (uint d)
+				{
+					choice = ActionChoices(Dummy.Dummy2);
```
Comment (axic) [inline test/libsolidity/SolidityEndToEndTest.cpp]: Should we allow mixing enum types?

Comment (pirapira) [reply test/libsolidity/SolidityEndToEndTest.cpp]: Probably it's a bad idea to allow this.  I'll change this.

Comment (pirapira) [reply test/libsolidity/SolidityEndToEndTest.cpp]: Now it's a type error, converting an enum to another enum.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 5]
```diff
@@ -656,6 +656,16 @@ void CompilerUtils::convertType(Type const& _typeOnStack, Type const& _targetTyp
 		solAssert(_typeOnStack == _targetType, "Invalid type conversion requested.");
 		break;
 	}
+
+	// Check the conversion result fits in a range.
+	if (targetTypeCategory == Type::Category::Enum)
+	{
+		EnumType const* enumType = dynamic_cast<decltype(enumType)>(&_targetType);
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]: In these cases, I usually do `EnumType const& enumType = dynamic_cast<EnumType const&>(_targetType)` - it will not throw an InternalCompilerError, but the general exception will also be caught.

File: libsolidity/parsing/Parser.cpp [hunk 6]
```diff
@@ -406,6 +406,8 @@ ASTPointer<EnumDefinition> Parser::parseEnumDefinition()
 		if (m_scanner->currentToken() != Token::Identifier)
 			fatalParserError(string("Expected Identifier after ','"));
 	}
+	if (members.size() == 0)
+		fatalParserError({"enum with no members is not allowed."});
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: Parser errors only have to be fatal if parsing cannot continue, which is not the case here, I would say.

Comment (pirapira) [inline libsolidity/parsing/Parser.cpp]: What about non-fatal parse error?

Comment (pirapira) [reply libsolidity/parsing/Parser.cpp]: I replaced this with a `parserError`.

File: libsolidity/codegen/CompilerUtils.cpp (hunk 5 above)
Comment (pirapira) [reply libsolidity/codegen/CompilerUtils.cpp]: OK.  I changed this.

File: Changelog.md [hunk 7]
```diff
@@ -1,5 +1,14 @@
 ### 0.4.5 (unreleased)
 
+Features:
+
+ * Code generator: generates a runtime error when an out-of-range value is converted into an enum type.
+
+Bugfixes:
+
+ * Parser: disallow empty enum definitions.
+ * Type checker: disallow conversion from enum type to another enum type
```
Comment (axic) [inline Changelog.md]: Maybe 'disallow conversion between different enum types` is enough?

Comment (pirapira) [reply Changelog.md]: That sounds better.  I changed the line.

**Review by axic — APPROVED** [review]

File: libsolidity/codegen/CompilerUtils.cpp [hunk 8]
```diff
@@ -656,6 +656,15 @@ void CompilerUtils::convertType(Type const& _typeOnStack, Type const& _targetTyp
 		solAssert(_typeOnStack == _targetType, "Invalid type conversion requested.");
 		break;
 	}
+
+	// Check the conversion result fits in a range.
+	if (targetTypeCategory == Type::Category::Enum)
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]: Isn't it better to put that in the enum cleaning routine which is called for integer -> enum conversion (and potentially also for memory -> enum conversion)?

Comment (pirapira) [reply libsolidity/codegen/CompilerUtils.cpp]: In that case, I would call the cleaning routine at this spot.  This catches anything -> enum conversion.

Comment (chriseth) [reply libsolidity/codegen/CompilerUtils.cpp]: I think having this routine at this spot is generally confusing. We can keep an assert here which checks that only int to enum conversion is possible.

Comment (pirapira) [reply libsolidity/codegen/CompilerUtils.cpp]: It seems I need to familiarize myself with the logic of the code.

Comment (pirapira) [reply libsolidity/codegen/CompilerUtils.cpp]: @chriseth I moved the overflow checking; but I'm not sure if this is what you want.  I did not find an enum cleaning routine.
