### PR TITLE
[CLI] Consolidate exception handlers in CommandLineInterface

### LINKED ISSUE #11732: [CLI] Consolidate exception handlers in `CommandLineInterface`
Related to #10295 and #11731.

Currently there are lots of independent `try`/`catch` statements inside various functions of `CommandLineInterface`. In most (if not all) cases they just print the error message and exit. In some cases this results in exceptions being silenced too eagerly, in others exceptions are not caught at all and can terminate the application without a sensible error message.

There should really be just a single error handler of this kind and it should reside at the very top-level of the hierarchy where printing and exiting is the default action for stuff that was not handled at lower levels. At lower levels the exceptions should be free to escape and interrupt the processing. Most `try`/`catch` blocks should only perform cleanup (if any is necessary at all) and then rethrow the exception so that the top-level handler can deal with it.

The top-level handler should be placed inside `main()` (like in #10295).

### PR DESCRIPTION
**Pull request by s0sharma**
removed some try/catch and placed the catch inside main();

Fixes #11732.
Closes #12109.

### CODE REVIEW

File: solc/CommandLineInterface.cpp [hunk 1]
```diff
@@ -618,11 +618,6 @@ bool CommandLineInterface::compile()
 					astAssert(false, "Analysis of the AST failed");
 				}
 			}
-			catch (Exception const& _exc)
-			{
-				serr() << string("Failed to import AST: ") << _exc.what() << endl;
-				return false;
-			}
```
Comment (cameel) [inline solc/CommandLineInterface.cpp]: You can't just remove the `catch` clause and leave the `try` hanging there :) You need to remove it and leave only the code that was inside it.

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -663,14 +649,6 @@ bool CommandLineInterface::compile()
 			boost::diagnostic_information(_exception);
 		return false;
 	}
-	catch (smtutil::SMTLogicError const& _exception)
```
Comment (cameel) [inline solc/CommandLineInterface.cpp:718]: Please leave `SMTLogicError` here. It's not a generic exception type, it should only happen in `compile()`.

File: solc/main.cpp [hunk 3]
```diff
@@ -53,24 +52,48 @@ static void setDefaultOrCLocale()
...
 		return 1;
-	if (!cli.readInputFiles())
+	}
+	catch (Exception const& _exception)
+	{
+		cerr << "Uncaught exception" << boost::diagnostic_information(_exception) << endl;
 		return 1;
-	if (!cli.processInput())
+	}
+	catch (InternalCompilerError const& _exception)
```
Comment (cameel) [inline solc/main.cpp]: This inherits from `boost::exception` so it must be higher. Otherwise the compiler will never enter here.

File: solc/main.cpp [hunk 4]
```diff
@@ -53,24 +52,48 @@ static void setDefaultOrCLocale()
...
+		setDefaultOrCLocale();
+		solidity::frontend::CommandLineInterface cli(cin, cout, cerr);
+		if (!cli.parseArguments(argc, argv) || !cli.readInputFiles() || !cli.processInput() || !cli.actOnInput())
+			return 1;
+
+		return 0;
+	}
+	catch (boost::exception const& _exception)
+	{
+		cerr << "Uncaught exception" << boost::diagnostic_information(_exception) << endl;
```
Comment (cameel) [inline solc/main.cpp]: There should be some whitespace between the messages:
```suggestion
		cerr << "Uncaught exception: " << boost::diagnostic_information(_exception) << endl;
```
Please run the compiler locally and test that all of these messages are actually printed correctly.

File: solc/main.cpp [hunk 5]
```diff
@@ -53,24 +52,48 @@ static void setDefaultOrCLocale()
...
 	}
-	catch (boost::exception const& _exception)
+	catch (std::exception const& _e)
 	{
-		cerr << "Exception during output generation: " << boost::diagnostic_information(_exception) << endl;
-		success = false;
+		cerr() << "Uncaught exception" << (_e.what() ? ": " + string(_e.what()) : ".") << endl;
+		return 1;
+	}
+	catch (Exception const& _exc)
```
Comment (cameel) [inline solc/main.cpp]: You need to import this exception type to be able to use it. It's defined in [`libsolutil/Exceptions.h`](https://github.com/ethereum/solidity/blob/develop/libsolutil/Exceptions.h).

Also, it inherits from both `std::exception` and `boost::exception` so it must be above them.

File: solc/main.cpp [hunk 6]
```diff
@@ -53,24 +52,48 @@ static void setDefaultOrCLocale()
...
-		success = cli.actOnInput();
+		cerr << "Uncaught exception" << boost::diagnostic_information(_exception) << endl;
+		return 1;
 	}
-	catch (boost::exception const& _exception)
+	catch (std::exception const& _e)
 	{
-		cerr << "Exception during output generation: " << boost::diagnostic_information(_exception) << endl;
-		success = false;
+		cerr() << "Uncaught exception" << (_e.what() ? ": " + string(_e.what()) : ".") << endl;
```
Comment (cameel) [inline solc/main.cpp]: I originally did not do this in #10295 but I think that `boost::diagnostic_information` is usable with `std::exception` too. Could you try it?

File: solc/main.cpp [hunk 7]
```diff
@@ -53,24 +52,48 @@ static void setDefaultOrCLocale()
...
+		return 1;
+	}
+	catch (Exception const& _exc)
+	{
+		cerr() << "Uncaught exception" << _exc.what() << endl;
```
Comment (cameel) [inline solc/main.cpp]: And it's definitely usable with `Exception`.

Also, the whole point of cathing it as a separate type is to use the extra info it stores. It has `lineInfo()` and `comment()`. If `boost::diagnostic_information()` prints that then you don't need this handler at all. If it does not, please print it.

**Review by cameel — DISMISSED** [review]
Thanks for the PR!

It still needs some work. Also, please make sure the code actually compiles. I see that CI is reporting lots of errors.

**Comment by s0sharma** [comment]
I'll make the changes.

**Comment by hrkrshnn** [comment]
This seems to be stalled. Pinging @s0sharma. Would it be possible for you to make the changes from the review comments? Thanks for the PR.

**Comment by s0sharma** [comment]
sorry for the delay. I'm busy right now. It may take a couple of days to work on it.

**Comment by cameel** [comment]
@s0sharma I can take over if you don't have time to finish this. We have a ton of pending PRs right now and we'd like trim that number down a bit :)

File: solc/CommandLineInterface.cpp (hunk 2 above)
Comment (cameel) [reply solc/CommandLineInterface.cpp:718]: Looks like it is a generic exception after all (it's thrown by `smtAssert()`).

**Comment by cameel** [comment]
This is now finished and ready for review.

**Review by chriseth — APPROVED** [review]

**Comment by cameel** [comment]
#12106 should fix the failing `b_osx`. I'd rebase the PR on it but github will probably close it once the base PR is merged since it's an external PR so I'll just wait for that base PR to be merged instead.
