### PR TITLE
Correctly parse ambiguities like `A.B[10] x` and `x.y[10] = 3`.

### LINKED ISSUE #138: Parse error when using type from other library/contract
library Lib {
    struct info {uint f;}
    function doit() constant returns (uint t) {
        return 0; 
    }
}

contract A
{
    Lib s;
    function aa(){
       Lib.info a;
       a.f = s.doit();
    }
}

:13:17: Parser error: Expected token Semicolon
       Lib.info a;
                ^

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #138

### CODE REVIEW

File: libsolidity/Parser.cpp [hunk 1]
```diff
@@ -744,36 +747,43 @@ ASTPointer<Statement> Parser::parseSimpleStatement()
...
 
-	// At this point, we have '(Identifier|ElementaryTypeName) "["'.
-	// We parse '(Identifier|ElementaryTypeName) ( "[" Expression "]" )+' and then decide whether to hand this over
-	// to ExpressionStatement or create a VariableDeclarationStatement out of it.
-	ASTPointer<PrimaryExpression> primary;
+	// At this point, we have 'Identifier "["' or 'Identifier "." Identifier' or 'ElementoryTypeName "["'.
+	// We parse '(Identifier ("." Identifier)* |ElementaryTypeName) ( "[" Expression "]" )+'
+	// until we can decide whether to hand this over to ExpressionStatement or create a
+	// VariableDeclarationStatement out of it.
+
```
Comment (LefterisJP) [inline libsolidity/Parser.cpp:754]: unneeded new line?
