### PR TITLE
ast: super contract type does not contain native members

### LINKED ISSUE #1151: Internal compiler error: super function not found
```
                contract A { function b() returns (uint r) { return 0; } }
                contract B is A { function f() returns (uint r) { return super.f() | 2; } }
                contract C is A { function f() returns (uint r) { return super.f() | 4; } }
                contract D is B, C { uint data; function D() { data = super.f() | 8; } function f() returns (uint r) { return data; } }
```

Found by llvm's libfuzzer.

### PR DESCRIPTION
**Pull request by pirapira**
When members are sought for a contract whose type is super, the result should not contain the members of the derived contract.

Fixes #1151

### CODE REVIEW

**Comment by pirapira** [comment]
Now I think it's better to change `nativeMembers`

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -1288,14 +1288,17 @@ string ContractType::canonicalName(bool) const
...
+MemberList::MemberMap ContractType::nativeMembers(ContractDefinition const* _current) const
 {
 	// All address members and all interface functions
 	MemberList::MemberMap members(IntegerType(120, IntegerType::Modifier::Address).nativeMembers(nullptr));
 	if (m_super)
 	{
 		// add the most derived of all functions which are visible in derived contracts
 		for (ContractDefinition const* base: m_contract.annotation().linearizedBaseContracts)
+		{
+			if (base == _current)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Please change this to start from index 1 and also add a test for this fix.

**Review by chriseth — CHANGES_REQUESTED** [review]

**Comment by pirapira** [comment]
@chriseth I've accommodated your review comments.

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -1295,7 +1295,14 @@ MemberList::MemberMap ContractType::nativeMembers(ContractDefinition const*) con
 	if (m_super)
 	{
 		// add the most derived of all functions which are visible in derived contracts
-		for (ContractDefinition const* base: m_contract.annotation().linearizedBaseContracts)
+		auto bases = m_contract.annotation().linearizedBaseContracts;
+		if (bases.size() < 1)
+			BOOST_THROW_EXCEPTION(
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Perhaps easier to do `solAssert(bases.size() > 1, "linearized...");`

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -1295,7 +1295,14 @@ MemberList::MemberMap ContractType::nativeMembers(ContractDefinition const*) con
...
+				InternalCompilerError() <<
+				errinfo_comment("linearizedBaseContracts should at least contain the most derived contract.")
+			);
+		bases.erase(bases.begin()); // Remove the most derived contract, which should not be searchable from `super`.
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: What about the following:

```
#include <boost/range/adaptor/sliced.hpp>;
...
for (ContractDefinition const* base: bases | sliced(1, bases.size()))
```

**Review by chriseth — CHANGES_REQUESTED** [review]

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (pirapira) [reply libsolidity/ast/Types.cpp]: I will do something similar.

File: libsolidity/ast/Types.cpp (hunk 3 above)
Comment (pirapira) [reply libsolidity/ast/Types.cpp]: This is cheaper computationally.  So I choose this one.

**Comment by pirapira** [comment]
@chriseth I've accommodated all your change requests.

**Comment by chriseth** [comment]
Please add an entry to the changelog.

**Comment by pirapira** [comment]
@chriseth done.
