### PR TITLE
CSE optimization 

### LINKED ISSUE #12406: Large array declaration hangs compiler when optimization enabled
## Description

For private deployment of Ethereum I would like to deploy "larger" contracts than on mainnet.
Here's example of such smart contract: https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160

solc is able to compile this smart contract normally, but hangs when optimization is enabled.

## Environment

- Compiler version: 0.8.10+commit.fc410830.Linux.g++
- Target EVM version (as per compiler settings): Default
- Framework/IDE (e.g. Truffle or Remix): No
- EVM execution environment / backend / blockchain client: Besu
- Operating system:  x86_64 GNU/Linux 5.15.6-arch2 Archlinux

## Steps to Reproduce

Download example source code from [this gist](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160)

Run this command:

```
solc --bin -o build_check --optimize --optimize-runs=200 --no-optimize-yul ./MediumVerifier.sol
```

### Expected result

Code is compiled, same way as without optimization.

### Actual result

Compiler hangs, consuming 100% of single cpu thread.

### Notes

Outcome is the same if `--optimize-runs=1`

### PR DESCRIPTION
**Pull request by wechman**
fixes #12406 

Changes:
1) m_expressions member of ExpressionClasses is now unordered_set. Tests show this change reduces [MediumVerifier.sol](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160) compilation time from 21 to 14 minutes (33% compilation time reduction).

2) CommonSubexpressionEliminator::feedItems is updated to accept items in chunks with max size of 1000. With this change [MediumVerifier.sol](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160) compile time is reduced to 8 seconds.

Proposed limit of 1000 items in a single chunk passed to CSE is not final yet. To shed some light on a chunk size that the compiler is usually dealing with, below statistic has been collected on external tests.

|chunk size|occurrences|chunk size|occurrences|chunk size|occurrences|chunk size|occurrences|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|0|1250131|51|301|102|39|157|1
|1|113354|52|364|103|9|159|2|
|2|258753|53|206|104|24|160|2|
|3|172793|54|402|105|32|162|4|
|4|226723|55|374|106|15|165|7|
|5|159193|56|190|107|23|168|10|
|6|162382|57|404|108|16|169|2|
|7|106297|58|209|109|28|175|1|
|8|97268|59|248|110|18|176|13|
|9|74523|60|232|111|47|177|2|
|10|81716|61|246|112|3|178|4|
|11|38994|62|125|113|18|179|5|
|12|34726|63|183|114|14|181|2|
|13|30574|64|194|116|25|182|7|
|14|20208|65|84|117|7|183|1|
|15|20131|66|153|118|2|184|2|
|16|15046|67|94|119|6|190|18|
|17|14875|68|81|120|40|191|18|
|18|15160|69|191|121|13|192|4|
|19|11616|70|65|122|7|193|2|
|20|9342|71|101|123|16|194|2|
|21|8200|72|129|124|3|198|2|
|22|13707|73|74|125|25|200|2|
|23|10659|74|56|126|2|205|4|
|24|5641|75|152|127|3|215|2|
|25|4758|76|46|128|11|222|6|
|26|10939|77|66|129|7|231|2|
|27|7363|78|130|130|1|239|15|
|28|7063|79|140|131|8|244|4|
|29|3984|80|28|133|6|249|4|
|30|2672|81|25|134|4|250|4|
|31|3157|82|59|135|3|258|4|
|32|4343|83|24|136|4|262|10|
|33|2349|84|17|137|17|290|2|
|34|2126|85|61|138|3|293|16|
|35|1558|86|28|139|75|296|2|
|36|1276|87|38|141|29|309|2|
|37|2291|88|52|142|8|324|16|
|38|1363|89|47|144|9|328|46|
|39|1967|90|63|145|2|341|6|
|40|1305|91|39|146|9|347|7|
|41|1435|92|112|147|2|358|6|
|42|1337|93|57|148|7|371|4|
|43|1218|94|20|149|8|432|10|
|44|1138|95|51|150|3|1485|4|
|45|741|96|54|151|8|1487|1|
|46|803|97|75|152|6|1490|4|
|47|555|98|64|153|5|1492|1|
|48|762|99|20|154|10|1500|6|
|49|502|100|7|155|4|1505|4|
|50|528|101|16|156|2||

Another important thing is to check how limiting the chunk size affects actual projects. Below is a gas benchmark comparison  between develop and PR changes. It is formed with c_ext_benchmarks CI job usage.

_bleeps_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|0|0|
|legacy-optimize-evm+yul|0|0|0|

_colony_
||bytecode_size|
|:---:|:---:|
|ir-no-optimize|0|
|ir-optimize-evm+yul|0|
|ir-optimize-evm-only|0|
|legacy-no-optimize|0|
|legacy-optimize-evm+yul|0|
|legacy-optimize-evm-only|0|

_ens_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|24(+0%)|0|
|legacy-no-optimize|0|||
|legacy-optimize-evm+yul|0|-12(-0%)|0|
|legacy-optimize-evm-only|0|0|0|

_gnosis_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|36(+0%)|-647(-0%)|
|legacy-no-optimize|0|0|224(+0%)|
|legacy-optimize-evm+yul|0|12(+0%)|218(+0%)|
|legacy-optimize-evm-only|0|-12(-0%)|-596(-0%)|

_perpetual-pools_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|legacy-no-optimize|0|-15(-0%)|3222(+0%)|
|legacy-optimize-evm+yul|0|-34(-0%)|-139195(`-0.02%✅`)|
|legacy-optimize-evm-only|0|-60(-0)|0|

_pool-together_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|12(+0%)|6(+0%)|
|legacy-no-optimize|0|-48(-0%)|50(0%)|
|legacy-optimize-evm+yul|0|0|51(+0%)|
|legacy-optimize-evm-only|0|48(+0%)|37(+0%)|

_prb-math_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|-12(-0%)|0|
|legacy-no-optimize|0|-12(-0%)|0|
|legacy-optimize-evm+yul|0|0|0|
|legacy-optimize-evm-only|0|-12(-0%)|0|

_trident_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|36(+0%)|30(+0%)|
|legacy-no-optimize|0|24(+0%)|-159(-0%)|
|legacy-optimize-evm+yul|0|-24(-0%)|42(+0%)|
|legacy-optimize-evm-only|0|12|357|

_uniswap_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|legacy-no-optimize|0|0|-1810(-0%)|
|legacy-optimize-evm+yul|0|-12(0%)|320(0%)|
|legacy-optimize-evm-only|0|12(+0%)|1082(+0%)|

_yield_liquidator_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|0|0|
|legacy-no-optimize|0|12(+0%)|-72(+0%)|
|legacy-optimize-evm+yul|0|-12(-0%)|0|
|legacy-optimize-evm-only|0|-12(-0%)|-108(-0%)|

_zeppelin_
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0|12(+0%)|-42(-0%)|
|legacy-no-optimize|0|48(+0%)|215(+0%)|
|legacy-optimize-evm+yul|0|-60(-0%)|201(+0%)|
|legacy-optimize-evm-only|0|-120(-0%)|4(+0%)|

### CODE REVIEW

File: libevmasm/CommonSubexpressionEliminator.h [hunk 1]
```diff
@@ -179,7 +179,12 @@ AssemblyItemIterator CommonSubexpressionEliminator::feedItems(
...
 	assertThrow(!m_breakingItem, OptimizerException, "Invalid use of CommonSubexpressionEliminator.");
-	for (; _iterator != _end && !SemanticInformation::breaksCSEAnalysisBlock(*_iterator, _msizeImportant); ++_iterator)
+	unsigned const maxChunkSize = 1000;
+	for (
+		unsigned chunkSize = 0;
+		_iterator != _end && !SemanticInformation::breaksCSEAnalysisBlock(*_iterator, _msizeImportant) && chunkSize < maxChunkSize;
+		++_iterator, ++chunkSize
+	)
 		feedItem(*_iterator);
 	if (_iterator != _end)
```
Comment (chriseth) [inline libevmasm/CommonSubexpressionEliminator.h]: I think this should be `_iterator != _end && chunkSize < maxChunkSize`.

**Comment by chriseth** [comment]
So there are only 20 chunks larger than 1000 items - why does it still have such a big impact on gas? Also why does it change some legacy-no-optimize runs?

Finally: What happens if we only use the second commit?

File: libevmasm/CommonSubexpressionEliminator.h (hunk 1 above)
Comment (wechman) [reply libevmasm/CommonSubexpressionEliminator.h]: You are correct. Fixup commit added.

**Comment by wechman** [comment]
> So there are only 20 chunks larger than 1000 items - why does it still have such a big impact on gas? Also why does it change some legacy-no-optimize runs?

Yes, only 20 chunks larger than 1000 items. But, I am not sure if the changes really have a big impact on gas. I compared two consecutive builds on my branch and get similar differences in gas without any code change. I think we cannot fully rely on these benchmark tests.

> Finally: What happens if we only use the second commit?

With reverted first commit I notice [MediumVerifier.sol](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160) compilation time increase of ~6%.

**Comment by leonardoalt** [comment]
Is this PR waiting for reviews?

**Comment by wechman** [comment]
> Is this PR waiting for reviews?

@leonardoalt  Yes, it is. Could you help with that?

**Comment by ekpyron** [comment]
> 
> Yes, only 20 chunks larger than 1000 items. But, I am not sure if the changes really have a big impact on gas. I compared two consecutive builds on my branch and get similar differences in gas without any code change. I think we cannot fully rely on these benchmark tests.
> 

I've been getting small fluctuations of <100 gas a lot in general - it may be random things like zeroes in commit hashes or not entirely deterministic setup in the external tests - I think it's safe to ignore gas changes in those benchmarks below 0.01%...

> > Finally: What happens if we only use the second commit?
> 
> With reverted first commit I notice [MediumVerifier.sol](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160) compilation time increase of ~6%.

What about the opposite effect? ``unordered_set`` yields constant complexity, but it may still be larger than the logarithmic complexity of ``set`` for small sets... i.e. is there any measurable *adverse* effect of switching to a hash set?

**Comment by wechman** [comment]
I think we can use compiler tests to get some numbers on performance:

|test suite|Set|HashSet|
|:---:|:---:|:---:|
|isoltests|2m59s|2m59s|
|soltest|11m38s|12m9s|
|cmdline|7m42s|7m45s|

There is no much difference in the tests' execution time, but this is still an adverse effect of the change. Now, with limited size of a chunk passed to CSE, switching to a hash set is no longer crucial. I guess for most of the user contracts, there will be a marginal difference in compilation time. A significant change can be noticed only for contracts that requires extensive CSE optimization.

**Comment by ekpyron** [comment]
Ok, then I'd say we can stay with the hash set (but I'd also be fine with reverting it).

So I guess the main concern left here is how much effects the chunk size limit has in practice... did you make sure to run the benchmark comparison exactly against the base commit of this branch on develop? Some of the differences e.g. of 12 gas may be spurious, but there are some oddities in some numbers and in the fact that ``legacy-no-optimize`` appears to be affected...

Also: the chunk sizes in https://github.com/ethereum/solidity/issues/12406#issuecomment-1070819072 seem to be getting significantly larger than 1000 - maybe it makes sense to measure more generous limits, e.g. 2000, wrt the compilation time of MediumVerifier and external tests gas changes?

**Comment by wechman** [comment]
I am also finding it hard to say if we should go for HashSet or keep Set. I guess compilation time of real word contracts is prior so maybe HashSet is a way to go. 

About benchmark comparison, I am pretty sure I used the branch and the develop base commit of the branch:) I was not the only one who was surprised to see differences in the results. So that I did  test with two consecutive benchmark runs on exactly the same commit of develop. Even here I get similar gas differences.

The limit of 1000 elements in chunk was the first proposal. Now we can go for 2000 to check the MediumVerifier compilation time. I am all for it. But, I consider gas changes to be spurious in the results we have so far. So I do not expect any news on that part.

**Comment by wechman** [comment]
### [MediumVerifier.sol](https://gist.github.com/citizen-stig/a25be3d125969c64f0f2b94b28a0d160) compilation time:
|ChunkSize|HashSet|Set|
|:---:|:---:|:---:|
|1000|7.723s|8.125s(+5.2%)|
|2000|15.563s|17.242s(+10.8%)|


### Tests' execution time:
|TestSuite|ChunkSize:1000|ChunkSize:2000|
|:---:|:---:|:---:|
|isoltests(HashSet)|2m59s|2m59s|
|isoltests(Set)|2m59s|2m57s|
|soltest(HashSet)|12m9s|11m54s|
|soltest(Set)|11m38s|11m43s|
|cmdline(HashSet)|7m45s|7m48s|
|cmdline(Set)|7m42s|7m43s|

### ChunkSize 1000 vs 2000 (HashSet in use):
bleeps
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|0(0%)|0(0%)|
|legacy-optimize-evm+yul|0(0%)|0(0%)|0(0%)|


colony
||bytecode_size|
|:---:|:---:|
|ir-no-optimize|0(0%)|
|ir-optimize-evm+yul|0(0%)|
|ir-optimize-evm-only|0(0%)|
|legacy-no-optimize|0(0%)|
|legacy-optimize-evm+yul|0(0%)|
|legacy-optimize-evm-only|0(0%)|


elementfi
||bytecode_size|
|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|
|legacy-no-optimize|0(0%)|
|legacy-optimize-evm+yul|0(0%)|
|legacy-optimize-evm-only|0(0%)|


ens
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|36(+0%)|26510(+0.03%❌)|
|legacy-no-optimize|0(0%)|||
|legacy-optimize-evm+yul|0(0%)|72(+0%)|0(0%)|
|legacy-optimize-evm-only|0(0%)|-48(-0%)|0(0%)|


euler
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|legacy-no-optimize|0(0%)|23(+0%)|39310(+0%)|
|legacy-optimize-evm+yul|0(0%)|-12(-0%)|-14632(-0%)|
|legacy-optimize-evm-only|0(0%)|-12(-0%)|21274(+0%)|


gnosis
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|-12(-0%)|39(+0%)|
|legacy-no-optimize|0(0%)|36(+0%)|899(+0%)|
|legacy-optimize-evm+yul|0(0%)|-12(-0%)|186(+0%)|
|legacy-optimize-evm-only|0(0%)|0(0%)|-1138(-0%)|


perpetual-pools
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|legacy-no-optimize|0(0%)|-26(-0%)|90078(+0.01%❌)|
|legacy-optimize-evm+yul|0(0%)|2(+0%)|-717(-0%)|
|legacy-optimize-evm-only|0(0%)|1(+0%)|-2(-0%)|


pool-together
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|-12(-0%)|-28(-0%)|
|legacy-no-optimize|0(0%)|36(+0%)|-25(-0%)|
|legacy-optimize-evm+yul|0(0%)|-24(-0%)|7(+0%)|
|legacy-optimize-evm-only|0(0%)|36(+0%)|-30(-0%)|


prb-math
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|0(0%)|0(0%)|
|legacy-no-optimize|0(0%)|12(+0%)|0(0%)|
|legacy-optimize-evm+yul|0(0%)|-12(-0%)|0(0%)|
|legacy-optimize-evm-only|0(0%)|-12(-0%)|0(0%)|


trident
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|12(+0%)|28(+0%)|
|legacy-no-optimize|0(0%)|-36(-0%)|-540(-0%)|
|legacy-optimize-evm+yul|0(0%)|12(+0%)|320(+0%)|
|legacy-optimize-evm-only|0(0%)|-12(-0%)|49(+0%)|


uniswap
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|legacy-no-optimize|0(0%)|48(+0%)|591(+0%)|
|legacy-optimize-evm+yul|0(0%)|0(0%)|1319(+0%)|
|legacy-optimize-evm-only|0(0%)|0(0%)|679(+0%)|


yield_liquidator
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|60(+0%)|0(0%)|
|legacy-no-optimize|0(0%)|0(0%)|0(0%)|
|legacy-optimize-evm+yul|0(0%)|24(+0%)|0(0%)|
|legacy-optimize-evm-only|0(0%)|-12(-0%)|0(0%)|


zeppelin
||bytecode_size|deployment_gas|method_gas|
|:---:|:---:|:---:|:---:|
|ir-optimize-evm+yul|0(0%)|-12(-0%)|211467(+0.05%❌)|
|legacy-no-optimize|0(0%)|-24(-0%)|137(+0%)|
|legacy-optimize-evm+yul|0(0%)|-84(-0%)|185(+0%)|
|legacy-optimize-evm-only|0(0%)|-24(-0%)|212303(+0.05%❌)|

**Comment by chriseth** [comment]
Can we get this merged?

**Comment by wechman** [comment]
> Can we get this merged?

@ekpyron is there anything else you think I should change or add to this PR?

**Comment by ekpyron** [comment]
> > Can we get this merged?
> 
> @ekpyron is there anything else you think I should change or add to this PR?

Nope (sorry, only seeing this now). We can merge it as far as I'm concerned.

**Review by ekpyron — APPROVED** [review]

**Comment by ekpyron** [comment]
Actually, now that it's merged, I'm wondering :-): maybe we should have given it a changelog entry :-)... can you add one in a followup PR (the unordered_map part does not change behaviour, but the CSE change may affect at least some cases)?
