### PR TITLE
[YulOpt] Implement ForLoopConditionIntoBody

### LINKED ISSUE #6480: [Yul] Optimizer: move loop condition into loop body so we can apply expression splitter
Follow-up of #6449 

Since we now support `break` statement in for-loop, we could move loop condition into loop body for the ease of further optimizations.

For example,
```
for { } lt(i, exponent) { i := add(i, 1:u256) }
{
    result := mul(result, base)
}
```
can be rewrite to
```
for { } true { i := add(i, 1:u256) }
{
    if lt(i, exponent) { break }
    result := mul(result, base)
}
```

At this moment, seems like loop conditions expressions are the only exception of SSA transformation. This can cause trouble when we want to apply optimizations which relies on SSA transformation. (#6449 is an example)

And the control flow graph should be isomorphic(?) before and after the transformation. So it probably should not be harder to optimize if we analyze the control flow correctly.

### PR DESCRIPTION
**Pull request by sifmelcara**
### Description

closes #6480

TODO:

1. ~~Update `libyul/optimizer/README.md`~~ Done
2. Update `Changelog.md`?    <- probably not worth mention because not yet enabled in Suite.cpp

### Checklist
- [x] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### CODE REVIEW

File: test/tools/yulopti.cpp [hunk 1]
```diff
@@ -129,7 +130,7 @@ class YulOpti
 			}
 			cout << "(q)quit/(f)flatten/(c)se/initialize var(d)ecls/(x)plit/(j)oin/(g)rouper/(h)oister/" << endl;
 			cout << "  (e)xpr inline/(i)nline/(s)implify/varname c(l)eaner/(u)nusedprune/ss(a) transform/" << endl;
-			cout << "  (r)edundant assign elim./re(m)aterializer/f(o)r-loop-pre-rewriter/" << endl;
+			cout << "  (r)edundant assign elim./re(m)aterializer/f(o)r-loop-init-rewriter/f(O)r-loop-cond-rewriter/" << endl;
```
Comment (sifmelcara) [inline test/tools/yulopti.cpp]: I think we are out of alphabets to use...

File: libyul/optimiser/ForLoopCondRewriter.cpp [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+				If {
+					{},
+					make_unique<Expression>(
+						FunctionalInstruction {
+							{},
+							eth::Instruction::ISZERO,
+							boost::assign::list_of(*forLoop.condition)
+						}
+					),
+					Block {{}, boost::assign::list_of(Break{{}})}
```
Comment (sifmelcara) [inline libyul/optimiser/ForLoopCondRewriter.cpp]: Cannot use `{Break{{}}}` instead of `boost::assign::list_of(Break{{}})` because some `std::move` issue with initialization-list

**Comment by sifmelcara** [comment]
Oh and I will separate the test case update part into a separate commit later

File: libyul/optimiser/ForLoopCondRewriter.h [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+*/
+#pragma once
+
+#include <libyul/optimiser/ASTWalker.h>
+
+namespace yul
+{
+
+/**
+ * Rewrites ForLoop by moving the cond expression into the ForLoop.
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.h]:
```suggestion
 * Rewrites ForLoop by moving the iteration check into the ForLoop body.
```
(it does not only move the condition expression but also the check)

File: libyul/optimiser/ForLoopCondRewriter.h [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+ * For example, `for {} lt(a, b) {}` becomes `for {} true { if iszero(lt(a, b)) }`
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.h]:
```suggestion
 * For example, `for {} lt(a, b) {}` becomes `for {} true { if iszero(lt(a, b)) { break } }`
```

Comment (chriseth) [reply libyul/optimiser/ForLoopCondRewriter.h]: oh and I think you omitted the post block

File: libyul/optimiser/ForLoopCondRewriter.h [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+ * Requirements:
+ * - The Disambiguator must be run upfront.
+ * - To avoid unnecessary rewrite, it is recommanded to run this rewriter after StructuralSimplifier.
+ */
+class ForLoopCondRewriter: public ASTModifier
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.h]: Since it would be good to also implement the reverse transform, perhaps name it `ForLoopConditionIntoBody`?

File: libyul/optimiser/ForLoopCondRewriter.h (hunk 3 above)
Comment (chriseth) [reply libyul/optimiser/ForLoopCondRewriter.h]: Perhaps also explain why we want to perform this transform

File: libyul/optimiser/Suite.cpp [hunk 6]
```diff
@@ -80,6 +81,7 @@ void OptimiserSuite::run(
 	BlockFlattener{}(ast);
 	ControlFlowSimplifier{}(ast);
 	StructuralSimplifier{*_dialect}(ast);
+	ForLoopCondRewriter{}(ast);
```
Comment (chriseth) [inline libyul/optimiser/Suite.cpp]: I think this should be done after the control flow simplifier.

In fact, it should probably be done only before the steps that benefit from this representation and then it should be undone again.

File: libyul/optimiser/ForLoopCondRewriter.cpp (hunk 2 above)
Comment (chriseth) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: Ah! Learnt of another useful library :)

File: libyul/optimiser/ForLoopCondRewriter.cpp [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+using namespace yul;
+
+void ForLoopCondRewriter::operator()(Block& _block)
+{
+	for (Statement& _stmt: _block.statements)
+	{
+		if (_stmt.type() == typeid(ForLoop))
+		{
+			auto& forLoop = boost::get<ForLoop>(_stmt);
+			(*this)(forLoop.pre);
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.cpp]: Why not call `visit()`?

File: libyul/optimiser/ForLoopCondRewriter.cpp [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+			(*this)(forLoop.body);
+			(*this)(forLoop.post);
+			forLoop.body.statements.insert(
+				forLoop.body.statements.begin(),
+				If {
+					{},
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.cpp]: `locationOf(forLoop.condition)` (also all other locations should be set to this)

File: libyul/optimiser/ForLoopCondRewriter.cpp [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+					make_unique<Expression>(
+						FunctionalInstruction {
+							{},
+							eth::Instruction::ISZERO,
+							boost::assign::list_of(*forLoop.condition)
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.cpp]: Hm, I think you should move from `forLoop.condition`

File: libyul/optimiser/ForLoopCondRewriter.cpp [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+				Literal {
+					{},
+					LiteralKind::Number,
+					"1"_yulstring,
+					{}
+				}
+			);
+		}
+		else
+		{
```
Comment (chriseth) [inline libyul/optimiser/ForLoopCondRewriter.cpp]: We don't use {} for single statements.

File: libyul/optimiser/ForLoopCondRewriter.cpp (hunk 9 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: Is `boost::assign::list_of(std::move(*forLoop.condition))` what you meant?

File: libyul/optimiser/ForLoopCondRewriter.cpp (hunk 7 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: I don't know, I copied it from ForLoopInitRewriter

File: libyul/optimiser/ForLoopCondRewriter.h (hunk 5 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopCondRewriter.h]: What's the reverse transform's expected behavior? To find out all code piece similiar to `for { ... } 1 { ... } { if x { break } ... }` then turn it into `for { ... } iszero(x) { ... } { ... }`?

Should the reverse transform belongs to the scope of this pull request?

File: libyul/optimiser/Suite.cpp (hunk 6 above)
Comment (sifmelcara) [reply libyul/optimiser/Suite.cpp]: Ok so it will looks like
```
ForLoopCondRewriter{}(ast);
ExpressionSplitter{}(ast);
// Actual optimization steps that depend on expression splitter
ExpressionJoiner{}(ast);
ForLoopCondRewriterUndo{}(ast);
```
?

Comment (chriseth) [reply libyul/optimiser/Suite.cpp]: yes, something like that.

File: libyul/optimiser/ForLoopCondRewriter.h (hunk 5 above)
Comment (chriseth) [reply libyul/optimiser/ForLoopCondRewriter.h]: Yes, something along those lines. The reverse transform can be a different pull request (and maybe should), but then you should not activate this transform in the suite.

File: libyul/optimiser/ForLoopCondRewriter.cpp (hunk 9 above)
Comment (chriseth) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: Yep!

Comment (ekpyron) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: That will still copy the expression, though - but we can change it later depending on #6780.

Comment (sifmelcara) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: Great! Will rebase and update these code after #6780 being merged into develop.

File: libyul/optimiser/ForLoopCondRewriter.h (hunk 5 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopCondRewriter.h]: OK

File: libyul/optimiser/ForLoopCondRewriter.cpp (hunk 9 above)
Comment (ekpyron) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: @sifmelcara #6780 is merged now!

Comment (sifmelcara) [reply libyul/optimiser/ForLoopCondRewriter.cpp]: Updated

File: libyul/optimiser/ForLoopConditionIntoBody.cpp [hunk 11]
```diff
@@ -0,0 +1,64 @@
...
+#include <libdevcore/CommonData.h>
+
+using namespace std;
+using namespace dev;
+using namespace yul;
+
+void ForLoopConditionIntoBody::operator()(Block& _block)
+{
+	for (Statement& _stmt: _block.statements)
+	{
```
Comment (chriseth) [inline libyul/optimiser/ForLoopConditionIntoBody.cpp]:
```suggestion
```

File: libyul/optimiser/ForLoopConditionIntoBody.cpp [hunk 12]
```diff
@@ -0,0 +1,64 @@
...
+				Literal {
+					loc,
+					LiteralKind::Number,
+					"1"_yulstring,
+					{}
+				}
+			);
+		}
+		else
+			visit(_stmt);
```
Comment (chriseth) [inline libyul/optimiser/ForLoopConditionIntoBody.cpp]: Can't this be moved to the beginning of the for loop, unconditionally?

File: libyul/optimiser/ForLoopConditionIntoBody.cpp [hunk 13]
```diff
@@ -0,0 +1,64 @@
...
+
+using namespace std;
+using namespace dev;
+using namespace yul;
+
+void ForLoopConditionIntoBody::operator()(Block& _block)
+{
+	for (Statement& _stmt: _block.statements)
+	{
+		if (_stmt.type() == typeid(ForLoop))
```
Comment (chriseth) [inline libyul/optimiser/ForLoopConditionIntoBody.cpp]: Maybe it would make sense to skip this transform if the condition is already a literal constant. Then the transform would be idempotent.

File: libyul/optimiser/ForLoopConditionIntoBody.cpp (hunk 12 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: Oh, I guess yes. And maybe `ForLoopConditionIntoBody::operator()(ForLoop& _floop)` instead of `ForLoopConditionIntoBody::operator()(Block& _block)`

File: libyul/optimiser/ForLoopConditionIntoBody.cpp (hunk 13 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: But then `ForLoopCondMoveOutBody(ForLoopCondIntoBody(forLoop))` won't be identity function anymore?

File: libyul/optimiser/ForLoopConditionIntoBody.cpp (hunk 12 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: Updated

File: libyul/optimiser/ForLoopConditionIntoBody.cpp (hunk 13 above)
Comment (chriseth) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: Why not?

Comment (sifmelcara) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: Assume user inputs:
```
for {} 1 {}
{
  if a { break }
}
```
Then we first apply the skip transform version of ForLoopConditionIntoBody (which does nothing) then apply ForLoopConditionMoveOutBody, it will become
```
for {} iszero(a) {} {}
```

For some reason we may want optimization phases like `(ExpressionSplitter, ExpressionJoiner)`, `(ForLoopConditionIntoBody, ForLoopConditionMoveOutBody)` to be pairs of inverse functions? (ignoring the fact we may get `iszero(iszero(a))` after transformation)

Comment (chriseth) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: But isn't it a good thing that it will result in `for {} iszero(a) {} {}`?

Comment (chriseth) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: It may be better to think of such transforms not of performing a certain fixed transform but instead that the result of the transform satisfies certain syntactic or semantic conditions. And if that is the setting, then I would say transforms should take the "shortest path" towards satisfying that condition.

Comment (sifmelcara) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: That mindset makes sense! Will fix this tomorrow

File: libyul/optimiser/README.md [hunk 14]
```diff
@@ -74,6 +74,22 @@ and F is a list of function definitions such that no function contains a functio
 
 The benefit of this stage is that we always know where the list of function begins.
 
+### For Loop Condition Into Body
+
+This transformation moves the iteration check part of a for-loop into loop body.
```
Comment (bshastry) [inline libyul/optimiser/README.md]: `iteration check condition` instead of `iteration check part`?

**Comment by bshastry** [comment]
This is probably far-fetched but is there an expression that when used as for-loop condition and this optimization step applied bears a different outcome because it is invoked at a later point.

```
for {} gas() {} {}
```

becomes

```
for {} 1 {}
{
  if iszero(gas()) break
}
```

If `gas()` returns `1`, in the transformed case does it still return `1`. I think so, but just wanted to be sure.

Also, what happens if we replace `gas()` in the above example with `pc()`, or say `msize()`?

File: libyul/optimiser/README.md (hunk 14 above)
Comment (chriseth) [reply libyul/optimiser/README.md]: Then I would fully switch to `iteration condition`

**Comment by chriseth** [comment]
`msize` will not be affected, but things like `gas` and `pc` will change with every single optimizer routine and just cannot be relied on, I would say. `gas` and `pc` even change when you transform `add(1,2)` to `3` at any place prior to the `gas` instruction.

Note that this transform does not change the order of instructions, it only changes jumps and jump labels.

File: libyul/optimiser/ForLoopConditionIntoBody.cpp (hunk 13 above)
Comment (sifmelcara) [reply libyul/optimiser/ForLoopConditionIntoBody.cpp]: Updated. Was wondering if we should also skip this transformation if the iteration condition is Variable (which ExpressionSplitter also cannot apply on). But decided to keep it simple.

**Review by chriseth — APPROVED** [review]
