### PR TITLE
Directly restart processing calling functions.

### LINKED ISSUE #11522: "Unreachable code" warning in 0.8.5 but not 0.8.4
## Description

After trying out 0.8.5 on our code, we got a lot of strange warnings about "unreachable code". The warning seems to have to do with library functions marked as `internal`.

## Environment

- Compiler version: 0.8.5
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: No execution, compliation problem
- Operating system: macOS 11.4

## Steps to Reproduce

`A.sol`:
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity =0.8.5;

import './B.sol';

contract Test is Bar {}
```

`B.sol`:
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity =0.8.5;

library Foo {
    // no warning if visibility "public"
    function nop() internal {}
}

contract Bar {
    function example() public returns (uint256) {
        foo();
        return 0;
    }

    function foo() public {
        Foo.nop();
    }
}
```

Compilation output:
```
➜  contracts  hh compile --force
Solidity 0.8.5 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support"

Compiling 2 files with 0.8.5
Warning: Unreachable code.
  --> contracts/B.sol:11:9:
   |
11 |         return 0;
   |         ^^^^^^^^


Compilation finished successfully
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #11522 
Alternative to #11523

### CODE REVIEW

**Comment by chriseth** [comment]
Even better would be to restart at exactly that point, but then we might get problems with the BFS.

**Comment by chriseth** [comment]
It is possible to only restart at the points we left off, but it would require even more local data structures, and I'm not sure if it's worth the hassle.

File: libsolidity/analysis/ControlFlowRevertPruner.cpp [hunk 1]
```diff
@@ -108,14 +113,14 @@ void ControlFlowRevertPruner::findRevertStates()
...
 		if (revertState != RevertState::Unknown)
-			for (auto& nextItem: m_calledBy[item.function])
-				// Ignore different most derived contracts in dependent callees
-				if (
-					item.contract == nullptr ||
-					nextItem.contract == nullptr ||
-					nextItem.contract == item.contract
-				)
+		{
+			std::set<CFG::FunctionContractTuple> toWakeUp = move(wakeUp[item]);
```
Comment (cameel) [inline libsolidity/analysis/ControlFlowRevertPruner.cpp]: Why does `move` without `std::` work in a file without `using namespace std`?

File: libsolidity/analysis/ControlFlowRevertPruner.cpp [hunk 2]
```diff
@@ -108,14 +113,14 @@ void ControlFlowRevertPruner::findRevertStates()
...
+			wakeUp.erase(item);
+			for (auto const& nextItem: toWakeUp)
```
Comment (cameel) [inline libsolidity/analysis/ControlFlowRevertPruner.cpp]:
```suggestion
			for (CFG::FunctionContractTuple const& nextItem: toWakeUp)
```

File: libsolidity/analysis/ControlFlowRevertPruner.cpp [hunk 3]
```diff
@@ -83,14 +83,19 @@ void ControlFlowRevertPruner::findRevertStates()
...
 					{
 						case RevertState::Unknown:
+							wakeUp[calledFunctionTuple].insert(item);
 							foundUnknown = true;
 							return;
 						case RevertState::AllPathsRevert:
 							return;
-						default:
+						case RevertState::HasNonRevertingPath:
 							break;
```
Comment (cameel) [inline libsolidity/analysis/ControlFlowRevertPruner.cpp:104]: I'd add `solAssert(false, "")` in the default case just in case.

File: test/libsolidity/syntaxTests/controlFlow/unreachableCode/library_function_import_bug.sol [hunk 4]
```diff
@@ -0,0 +1,18 @@
+==== Source: a ====
```
Comment (cameel) [inline test/libsolidity/syntaxTests/controlFlow/unreachableCode/library_function_import_bug.sol:1]: Could you also add the alternative test case from https://github.com/ethereum/solidity/pull/11523#discussion_r650172661?

**Review by cameel — COMMENTED** [review]
Looks like it should work too.

I don't see any actual problems, just some minor suggestions.

File: libsolidity/analysis/ControlFlowRevertPruner.cpp (hunk 3 above)
Comment (chriseth) [reply libsolidity/analysis/ControlFlowRevertPruner.cpp:104]: You mean I should add a default case with a failing assertion?

Comment (cameel) [reply libsolidity/analysis/ControlFlowRevertPruner.cpp:104]: Yes. In case something is added to the enum and not handled here. I guess the risk of that here is pretty low but personally I'd add it anyway.

Comment (chriseth) [reply libsolidity/analysis/ControlFlowRevertPruner.cpp:104]: The C++ compiler will create an error in that case.

Comment (chriseth) [reply libsolidity/analysis/ControlFlowRevertPruner.cpp:104]: If we add a default case, it will not create an error and we only notice it at runtime.

File: test/libsolidity/syntaxTests/controlFlow/unreachableCode/library_function_import_bug.sol (hunk 4 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/controlFlow/unreachableCode/library_function_import_bug.sol:1]: Added.

File: libsolidity/analysis/ControlFlowRevertPruner.cpp (hunk 3 above)
Comment (cameel) [reply libsolidity/analysis/ControlFlowRevertPruner.cpp:104]: Oh, looks like it does. That's even better. It's fine then.

**Review by cameel — DISMISSED** [review]

**Comment by chriseth** [comment]
Waiting for @ekpyron to approve as well.

File: libsolidity/analysis/ControlFlowRevertPruner.cpp [hunk 5]
```diff
@@ -57,6 +58,7 @@ void ControlFlowRevertPruner::run()
 void ControlFlowRevertPruner::findRevertStates()
 {
 	std::set<CFG::FunctionContractTuple> pendingFunctions = keys(m_functions);
+	std::map<CFG::FunctionContractTuple, std::set<CFG::FunctionContractTuple>> wakeUp;
```
Comment (ekpyron) [inline libsolidity/analysis/ControlFlowRevertPruner.cpp:64]: This is "tuples to be woken up when the key tuple changes its state from unknown to known", right? Might be worth a small comment for future reference? But also fine without.

**Review by ekpyron — DISMISSED** [review]
I hope there's no other hidden issues here, but so far I couldn't think of any and the issue at hand should indeed be solved by this change.

File: Changelog.md [hunk 6]
```diff
@@ -7,6 +7,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * Control Flow Graph: Fix incorrectly reported unreachable code.
```
Comment (lhoenig) [inline Changelog.md:10]: Do you in principal credit bug discoverers or actually no one? If the former is the case, I'm the discoverer, and wrote the minimal example ;)

Comment (lhoenig) [reply Changelog.md:10]: In any case, I'm amazed what in-depth discussion resulted from my findings. Really cool.

Comment (lhoenig) [reply Changelog.md:10]: I see you don't give any credits in the Changelog. That's okay, we dont want to break your consistency :D

**Comment by lhoenig** [comment]
Nicely done..! I am happy I was able to help improve Solidity a little bit ☺️

File: Changelog.md (hunk 6 above)
Comment (chriseth) [reply Changelog.md:10]: Sorry, we only attribute "critical bugs", i.e. those that make it into the [bug list](https://docs.soliditylang.org/en/latest/bugs.html) and where we write blog posts about. We also don't credit who implemented which feature :)

Comment (lhoenig) [reply Changelog.md:10]: Sure! Thanks for clarifying. I'm happy as it is ☺️
