### PR TITLE
[isoltest] Update improvements (support for missing types)

### LINKED ISSUE #6946: Failed semantic tests have strange "expected result v.s obtained result" formatting
To reproduce this issue, first intentionally modify a semantic test test case's expected output, for example
```
--- a/test/libsolidity/semanticTests/abiEncoderV2/calldata_array_dynamic_index_access.sol
+++ b/test/libsolidity/semanticTests/abiEncoderV2/calldata_array_dynamic_index_access.sol
@@ -23,7 +23,7 @@ contract C {
 // ====
 // EVMVersion: >homestead
 // ----
-// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
+// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 88
 // g(uint256[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
 // g(uint256[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
 // h(uint8[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
```

Then run the tests:
```
./build/test/soltest -p -- --ipcpath /tmp/testeth/geth.ipc --evm-version byzantium --no-smt --testpath ./test
```

it outputs
```
error: in "semanticTests/abiEncoderV2/calldata_array_dynamic_index_access": Test expectation mismatch.
Expected result:
// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 88
// g(uint256[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// g(uint256[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// h(uint8[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// j(bytes): 32, 3, hex"AB11FF" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 0, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 1, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 4, left(0xFF791432)

Obtained result:
// f(uint256[]): 32, 3, 42, 23, 87 -> 32, 160, hex"0000000000000000000000000000000000000000000000000000000000000020"
Warning: Encoding does not match byte range. The call returned 224 bytes, but 224 bytes were expected.
// g(uint256[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// g(uint256[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// h(uint8[]): 32, 3, 42, 23, 87 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 0, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17 -> 32, 160, 32, 3, 42, 23, 87
// i(uint8[][2],uint256): 0x40, 1, 0x40, 0xC0, 3, 42, 23, 87, 4, 11, 13, 17, 27 -> 32, 192, 32, 4, 11, 13, 17, 27
// j(bytes): 32, 3, hex"AB11FF" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 0, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 3, left(0xAB11FF)
// k(bytes[2],uint256): 0x40, 1, 0x40, 0x63, 3, hex"AB11FF", 4, hex"FF791432" -> 32, 96, 32, 4, left(0xFF791432)

Attention: Updates on the test will apply the detected format displayed.

```
I think it does not properly print the actual obtained result?

I guess something went wrong in the following function
https://github.com/ethereum/solidity/blob/a6cc296cd9b9221df9a203cc9e85cb45f0086756/test/libsolidity/util/TestFunctionCall.h#L143-L154

cc author of the file @erak , thanks!

### PR DESCRIPTION
**Pull request by erak**
Fixes https://github.com/ethereum/solidity/issues/6946.

Part of https://github.com/ethereum/solidity/issues/6669.

```
contract C {
    function a() public returns (string memory, uint, string memory) {
        return ("any", 42, "any");
    }
    function b() public returns (uint) {
        return 1;
    }
function 
}
...
// a() -> 0x60, 0x2a, 0xa0, 3, "any", 3, "any"
// a() ->
// a() -> 1, 42, 1, 3, 0x11, 3, "any"
// b() ->
```

This PR cleans up a lot of code needed for https://github.com/ethereum/solidity/issues/6669. These changes include:
  - Fix type retrieval from JSON ABI (and set `ABIType::UnsignedDec` as the fallback parameter type)
    `// a() ->` gets corrected to `// a() -> 0x60, 0x2a, 0xa0, 3, "any", 3, "any"`
  - Simplify deduction of types (from ABI or semantic test expectation based on their size and type) used while formatting a parameter
    `// a() -> 1, 42, 1, 3, 0x11, 3, "any"` gets corrected to `// a() -> 0x60, 42, 0xa0, 3, "any", 3, "any"`
  - Print actual byte output after function call as a warning, such that expectation mismatches can be adjusted manually:
    `// b() -> 1`
    `Warning: The call to "b()" returned`
    `[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]`
    `Warning: Encoding does not match byte range. The call returned 32 bytes, but 0 bytes were expected.`
  - Minor refactoring and addressing requested changes from https://github.com/ethereum/solidity/pull/7048

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `3a4a5157f0e167f58ce9f5edf013bade68586339`:
```
Error: Trailing whitespace found:
 test/libsolidity/semanticTests/smoke_test.sol:85:// constructor(): 3 -> 
 test/libsolidity/semanticTests/smoke_test.sol:88:// e() -> 

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `bc1ca715bde0d39a3e0b9577d45c48b04188e819`:
```
Error: Trailing whitespace found:
 test/libsolidity/semanticTests/smoke_test.sol:85:// constructor(): 3 -> 
 test/libsolidity/semanticTests/smoke_test.sol:88:// e() -> 

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `ad4e478db24977eafc3e3e519e00f6f8ed4d642f`:
```
Error: Trailing whitespace found:
 test/libsolidity/semanticTests/smoke_test.sol:85:// constructor(): 3 -> 
 test/libsolidity/semanticTests/smoke_test.sol:88:// e() -> 

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `b0b5bc2101e6bbf104cfa76785115666e3696842`:
```
Error: Trailing whitespace found:
 test/libsolidity/semanticTests/smoke_test.sol:85:// constructor(): 3 -> 
 test/libsolidity/semanticTests/smoke_test.sol:88:// e() -> 

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `4c64dc91fe976678e462ac253ec44046519c1930`:
```
Error: Trailing whitespace found:
 test/libsolidity/semanticTests/smoke_test.sol:85:// constructor(): 3 -> 
 test/libsolidity/semanticTests/smoke_test.sol:88:// e() -> 

```
Please check that your changes are working as intended.

File: test/libsolidity/util/BytesUtils.cpp [hunk 1]
```diff
@@ -164,35 +201,105 @@ string BytesUtils::formatString(bytes const& _bytes) const
...
+	stringstream os;
+
+	switch (_abiType.type)
+	{
+	case ABIType::UnsignedDec:
+		// Check if the detected type was wrong and if this could
+		// be signed. If an unsigned was detected in the expectations,
+		// but the actual result returned a signed, it would be formatted
+		// incorrectly.
+		if (*_bytes.begin() & 0x80)
```
Comment (erak) [inline test/libsolidity/util/BytesUtils.cpp:244]: @chriseth Fixed https://github.com/ethereum/solidity/pull/7048#discussion_r301513425 here. `formatUnsigned` does not do this "auto-correction" anymore and I moved it here to make it even more clear.

File: test/libsolidity/util/BytesUtils.cpp [hunk 2]
```diff
@@ -82,22 +119,22 @@ bytes BytesUtils::convertString(string const& _literal)
...
-string BytesUtils::formatUnsigned(bytes const& _bytes) const
+string BytesUtils::formatUnsigned(bytes const& _bytes)
 {
 	stringstream os;
 
-	if (*_bytes.begin() & 0x80)
-		os << u2s(fromBigEndian<u256>(_bytes));
-	else
-		os << fromBigEndian<u256>(_bytes);
+	soltestAssert(!_bytes.empty(), "");
```
Comment (erak) [inline test/libsolidity/util/BytesUtils.cpp]: @chriseth Fixed https://github.com/ethereum/solidity/pull/7048#discussion_r301515345 here. Please also see the check below.

File: test/libsolidity/util/BytesUtils.cpp [hunk 3]
```diff
@@ -33,6 +35,41 @@ using namespace dev::solidity::test;
 using namespace std;
 using namespace soltest;
 
+bytes BytesUtils::alignLeft(bytes _bytes)
+{
+	soltestAssert(_bytes.size() <= 32, "");
+	return std::move(_bytes) + bytes(32 - _bytes.size(), 0);
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]: Better safe than sorry: Copy `_bytes.size()` to a local variable.

File: test/libsolidity/util/BytesUtils.cpp [hunk 4]
```diff
@@ -33,6 +35,41 @@ using namespace dev::solidity::test;
...
+	if (_alignment != Parameter::Alignment::None)
+		_abiType.alignDeclared = true;
+
+	switch (_alignment)
+	{
+	case Parameter::Alignment::Left:
+		_abiType.align = ABIType::AlignLeft;
+		return alignLeft(std::move(_bytes));
+	case Parameter::Alignment::Right:
+		_abiType.align = ABIType::AlignRight;
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]: These two lines can be removed

File: test/libsolidity/util/BytesUtils.cpp [hunk 5]
```diff
@@ -82,22 +119,22 @@ bytes BytesUtils::convertString(string const& _literal)
...
+string BytesUtils::formatUnsigned(bytes const& _bytes)
 {
 	stringstream os;
 
-	if (*_bytes.begin() & 0x80)
-		os << u2s(fromBigEndian<u256>(_bytes));
-	else
-		os << fromBigEndian<u256>(_bytes);
+	soltestAssert(!_bytes.empty(), "");
+	os << fromBigEndian<u256>(_bytes);
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]:
```suggestion
	return fromBigEndian<u256>(_bytes).str();
```

File: test/libsolidity/util/BytesUtils.cpp (hunk 2 above)
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]: and at most 32 bytes long

File: test/libsolidity/util/BytesUtils.cpp [hunk 6]
```diff
@@ -82,22 +119,22 @@ bytes BytesUtils::convertString(string const& _literal)
...
 
 	return os.str();
 }
 
-string BytesUtils::formatSigned(bytes const& _bytes) const
+string BytesUtils::formatSigned(bytes const& _bytes)
 {
 	stringstream os;
 
+	soltestAssert(!_bytes.empty(), "");
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]: and at most 32 bytes long

File: test/libsolidity/util/BytesUtils.cpp [hunk 7]
```diff
@@ -164,35 +201,105 @@ string BytesUtils::formatString(bytes const& _bytes) const
...
-bytes BytesUtils::alignLeft(bytes _bytes) const
+string BytesUtils::formatRawBytes(bytes const& _bytes)
 {
-	return std::move(_bytes) + bytes(32 - _bytes.size(), 0);
+	if (!_bytes.empty())
+	{
+		stringstream os;
+		auto it = _bytes.begin();
+		size_t size = 32;
+		for (size_t i = 0; i < _bytes.size() / size; i++)
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]: round up

Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]:
```suggestion
		for (size_t i = 0; i < _bytes.size(); i += 32)
```

File: test/libsolidity/util/BytesUtils.cpp [hunk 8]
```diff
@@ -164,35 +201,105 @@ string BytesUtils::formatString(bytes const& _bytes) const
...
+		{
+			long offset = static_cast<long>(size);
+			auto offsetIter = it + offset;
+			bytes byteRange{it, offsetIter};
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]:
```suggestion
			bytes byteRange{it, it + 32};
```

File: test/libsolidity/util/BytesUtils.cpp [hunk 9]
```diff
@@ -164,35 +201,105 @@ string BytesUtils::formatString(bytes const& _bytes) const
...
+
+			os << "  " << byteRange;
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]:
```suggestion
			os << "  " << toHex(bytes_ref(&_bytes).cropped(i, 32))
```

File: test/libsolidity/util/BytesUtils.cpp [hunk 10]
```diff
@@ -164,35 +201,105 @@ string BytesUtils::formatString(bytes const& _bytes) const
...
-	case Parameter::Alignment::Left:
-		_abiType.align = ABIType::AlignLeft;
-		return alignLeft(std::move(_bytes));
-	case Parameter::Alignment::Right:
-		_abiType.align = ABIType::AlignRight;
-		return alignRight(std::move(_bytes));
-	default:
-		_abiType.align = ABIType::AlignRight;
-		return alignRight(std::move(_bytes));
+		size_t size = parameter.abiType.size;
```
Comment (chriseth) [inline test/libsolidity/util/BytesUtils.cpp]: I think this could be better readable if we would not have the local variables `size` and `offset`. Also please try to avoid the cast.

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 11]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+{
+
+using ParameterList = dev::solidity::test::ParameterList;
+
+auto arraySize(string const& _arrayType) -> size_t
+{
+	auto leftBrack = _arrayType.find("[");
+	auto rightBrack = _arrayType.find("]");
+
+	soltestAssert(leftBrack != string::npos && rightBrack != string::npos, "");
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
	soltestAssert(leftBrack != string::npos && rightBrack != string::npos && leftBrack < rightBrack, "");
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 12]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
 
-dev::solidity::test::ParameterList ContractABIUtils::parametersFromJson(
+namespace
+{
+
+using ParameterList = dev::solidity::test::ParameterList;
+
+auto arraySize(string const& _arrayType) -> size_t
+{
+	auto leftBrack = _arrayType.find("[");
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp:49]:
```suggestion
	auto leftBrack = _arrayType.rfind("[");
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 13]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+	auto rightBrack = _arrayType.find("]");
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
	auto rightBrack = _arrayType.rfind("]");
```

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 11 above)
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: Also assert that `rightBrack` is the last character

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 14]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+
+	soltestAssert(leftBrack != string::npos && rightBrack != string::npos, "");
+
+	string size = _arrayType.substr(leftBrack + 1, rightBrack - leftBrack - 1);
+	return static_cast<size_t>(stoi(size));
+}
+
+auto isBool(string _type) -> bool
+{
+	return regex_match(_type, regex{"(bool)"});
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
	return _type == "bool";
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 15]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+}
+
+auto isUint(string _type) -> bool
+{
+	return regex_match(_type, regex{"(uint\\d*)"});
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: Please check that this does not match on `someuintabc`

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 16]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+}
+
+auto isInt(string _type) -> bool
+{
+	return regex_match(_type, regex{"(int\\d*)"});
+}
+
+auto isBytes(string _type) -> bool
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
auto isFixedBytes(string _type) -> bool
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 17]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+{
+	return regex_match(_type, regex{"(bytes\\d+)"});
+}
+
+auto isDynBytes(string _type) -> bool
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
auto isBytes(string _type) -> bool
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 18]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+	auto leftBrack = _arrayType.find("[");
+	auto rightBrack = _arrayType.find("]");
+
+	soltestAssert(leftBrack != string::npos && rightBrack != string::npos, "");
+
+	string size = _arrayType.substr(leftBrack + 1, rightBrack - leftBrack - 1);
+	return static_cast<size_t>(stoi(size));
+}
+
+auto isBool(string _type) -> bool
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: These should all take `string const&`

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 19]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+
+auto isTupleArray(string _type) -> bool
+{
+	return regex_match(_type, regex{"(tuple)(\\[\\d+\\])"});
+}
+
+auto functionMatchesSignature(Json::Value const& _contractABIFunction, string const& _signature) -> bool
+{
+	string functionName{_signature.substr(0, _signature.find("("))};
+	string functionParameters{_signature.substr(_signature.find("(") + 1, _signature.find(")") - 2)};
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: Maybe use regex?

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 20]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+
+	vector<string> parameterTypes;
+	if (!functionParameters.empty())
+		boost::split(parameterTypes, functionParameters, [](char c){return c == ',';});
+
+	vector<string> abiParameterTypes;
+	for (auto const& input: _contractABIFunction["inputs"])
+		abiParameterTypes.push_back(input["type"].asString());
+
+	return (
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
	return
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 21]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+}
+
+auto isTupleArray(string _type) -> bool
+{
+	return regex_match(_type, regex{"(tuple)(\\[\\d+\\])"});
+}
+
+auto functionMatchesSignature(Json::Value const& _contractABIFunction, string const& _signature) -> bool
+{
+	string functionName{_signature.substr(0, _signature.find("("))};
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: Maybe better to just construct the signature from _contractABIFunction and then check for string equality?

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 22]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+
+	return (
+		_contractABIFunction["name"] == functionName &&
+		parameterTypes == abiParameterTypes
+	);
+}
+
+}
+
+boost::optional<dev::solidity::test::ParameterList> ContractABIUtils::parametersFromJson(
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: `outputsFromJson`?

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 23]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+	{
+		if (functionMatchesSignature(function, _functionSignature))
 			for (auto const& output: function["outputs"])
 			{
-				auto types = fromTypeName(output["type"].asString());
-				for (auto const& type: types)
-					abiParams.push_back(Parameter{bytes(), "", type, FormatInfo{}});
+				string type = output["type"].asString();
+
+				ABITypes addressTypes;
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
				ABITypes tailOffsetTypes;
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 24]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+
+				finalParams += addressTypeParams + valueTypeParams;
+
+				addressTypeParams.clear();
+				valueTypeParams.clear();
 			}
+	}
 
-	return abiParams;
+	return boost::optional<ParameterList>(finalParams + dynamicTypeParams);
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: This should return `boost::none` and the actual return should be in the loop iteration that found the function

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 25]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
 	{
-		abiTypes.push_back(ABIType{ABIType::UnsignedDec, ABIType::AlignRight, 32});
-		abiTypes.push_back(ABIType{ABIType::UnsignedDec, ABIType::AlignRight, 32});
-		abiTypes.push_back(ABIType{ABIType::HexString, ABIType::AlignLeft, 32});
+		for (auto const& component: _functionOutput["components"])
+			appendTypesFromName(component, _addressTypes, _valueTypes, _dynamicTypes, true);
 	}
-	else if (regex_match(_type, s_stringType))
+	else if (isBoolArray(type))
+		fill_n(back_inserter(_valueTypes), arraySize(type), ABIType{ABIType::Boolean});
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
		_valueTypes += vector<ABIType>(arraySize(type), ABIType{ABIType::Boolean});
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 26]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+	else if (isTuple(type))
 	{
-		abiTypes.push_back(ABIType{ABIType::UnsignedDec, ABIType::AlignRight, 32});
-		abiTypes.push_back(ABIType{ABIType::UnsignedDec, ABIType::AlignRight, 32});
-		abiTypes.push_back(ABIType{ABIType::HexString, ABIType::AlignLeft, 32});
+		for (auto const& component: _functionOutput["components"])
+			appendTypesFromName(component, _addressTypes, _valueTypes, _dynamicTypes, true);
 	}
-	else if (regex_match(_type, s_stringType))
+	else if (isBoolArray(type))
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: What about dynamic arrays?

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 27]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
-	else if (regex_match(_type, s_dynBytesType))
+		if (_isCompoundType)
+			_dynamicTypes.push_back(ABIType{ABIType::Hex});
+
+		_dynamicTypes.push_back(ABIType{ABIType::UnsignedDec});
+		_dynamicTypes.push_back(ABIType{ABIType::String, ABIType::AlignLeft});
+	}
+	else if (isTuple(type))
 	{
-		abiTypes.push_back(ABIType{ABIType::UnsignedDec, ABIType::AlignRight, 32});
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp:74]:
```
_addressTypes += <hex>;
vector<ABIType> thisStatic;
vector<ABIType> thisDynamic;
for (component)
  appendTypesFromName(component, thisStatic, thisDynamic);
_dynamicTypes += thisStatec + thisDynamic;
```

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 28]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+	}
 
-	return abiParams;
+	return boost::optional<ParameterList>(finalParams + dynamicTypeParams);
 }
 
-std::vector<ABIType> ContractABIUtils::fromTypeName(string const& _type) const
+bool ContractABIUtils::appendTypesFromName(
+	Json::Value const& _functionOutput,
+	ABITypes& _addressTypes,
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: address and value should be combined.

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 29]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+		if (
+			_a.abiType.size != _b.abiType.size ||
+			_a.abiType.type != _b.abiType.type
+		)
+		{
+			_errorReporter.warning("Type or size of parameter(s) does not match.");
+			_b = _a;
+		}
+	};
+	boost::for_each(_sourceParameters, _targetParameters, boost::bind<void>(overwrite, _1, _2));
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]: Pull in the lambda function

Comment (chriseth) [reply test/libsolidity/util/ContractABIUtils.cpp]: Please check what happens if the two lists do not have the same length.

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 30]
```diff
@@ -33,55 +39,256 @@ using namespace dev::solidity::test;
...
+}
+
+dev::solidity::test::ParameterList ContractABIUtils::preferredParameters(
+	ErrorReporter& _errorReporter,
+	dev::solidity::test::ParameterList const& _targetParameters,
+	dev::solidity::test::ParameterList const& _sourceParameters,
+	bytes _bytes
```
Comment (chriseth) [inline test/libsolidity/util/ContractABIUtils.cpp]:
```suggestion
	bytes const& _bytes
```

File: test/libsolidity/util/SoltestTypes.h [hunk 31]
```diff
@@ -154,12 +169,17 @@ struct Parameter
...
 	/// detected and retained in order to format them later on.
-	ABIType abiType;
+	ABIType abiType = ABIType{ABIType::UnsignedDec, ABIType::AlignRight, 32};
 	/// Format info attached to the parameter. It handles newlines given
 	/// in the declaration of it.
 	FormatInfo format;
 	/// Stores the parsed alignment, which can be either left(...) or right(...).
 	Alignment alignment = Alignment::None;
+	/// Compares _bytes to the bytes stored in this object.
+	bool matchesBytes(bytes _bytes) const
```
Comment (chriseth) [inline test/libsolidity/util/SoltestTypes.h]:
```suggestion
	bool matchesBytes(bytes const& _bytes) const
```

File: test/libsolidity/util/TestFunctionCall.cpp [hunk 32]
```diff
@@ -144,129 +144,49 @@ string TestFunctionCall::formatBytesParameters(
...
-		os << BytesUtils().formatString(_bytes);
-		break;
-	case ABIType::Failure:
-		break;
-	case ABIType::None:
-		break;
+		ParameterList defaultParameters;
+		fill_n(
+			back_inserter(defaultParameters),
+			_bytes.size() / 32,
```
Comment (chriseth) [inline test/libsolidity/util/TestFunctionCall.cpp]: round up

**Comment by chriseth** [comment]
Needs to be rebased.

File: test/libsolidity/util/BytesUtils.cpp (hunk 4 above)
Comment (erak) [reply test/libsolidity/util/BytesUtils.cpp]: Maybe a case for `[[fallthrough]]` (in the future)?

File: test/libsolidity/util/BytesUtils.cpp (hunk 10 above)
Comment (erak) [reply test/libsolidity/util/BytesUtils.cpp]: I removed the local variable but left the cast to `long`, which is needed in order to avoid a warning about the signedness of the result of `it + type.size`, which is a `size_t` being implicitly changed. I don't think that the implicit conversion is dangerous and would be also OK with introducing a new warning.

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 15 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: It does not match `someuintabc`, but I still removed the sub-expressions in order to avoid confusion.

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 17 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: I've also renamed the other array functions.

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 22 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: Went for `parametersFromJsonOutputs` in the end.

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 26 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: They are not supported yet. We would need to read the actual array size returned by the call in order to generate enough ABI types. But here, we are falling back to a decimal representation for the uncovered, but will change it to hex with: https://github.com/ethereum/solidity/pull/7091.

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 21 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: Yes, that's a lot clearer. Done.

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 25 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: Looks less complicated ;)

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 29 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: I added an assertion here, because it's not meant to be called with two vectors being unequally sized. In case the number of parameters given in the test does not match the one returned by the ABI, the ones from the ABI are taken and the function has no effect.

But if the expected and the actual ABI parameters have same the same size, but one of the parameters does not match the one defined by the ABI, the function will have an effect and produce that warning.

File: test/libsolidity/util/BytesUtils.h [hunk 33]
```diff
@@ -32,67 +32,69 @@ namespace test
 class BytesUtils
```
Comment (Marenz) [inline test/libsolidity/util/BytesUtils.h:32]: If all is static you might as well change the class to a namespace (this input was fed to me by @christianparpart )

File: test/libsolidity/util/BytesUtils.cpp [hunk 34]
```diff
@@ -198,3 +198,26 @@ string BytesUtils::formatString(bytes const& _bytes)
 
 	return os.str();
 }
+
+string BytesUtils::formatRawBytes(bytes const& _bytes)
+{
+	if (!_bytes.empty())
```
Comment (Marenz) [inline test/libsolidity/util/BytesUtils.cpp]: if you reverse the `if` conditions/bodies, you saved one indent level, e.g. `if(bytes.empty()) return "[]";`

File: test/libsolidity/util/TestFunctionCall.cpp [hunk 35]
```diff
@@ -208,6 +208,7 @@ string TestFunctionCall::formatBytesParameters(
 					" does not match the one inferred from ABI."
 				);
 			}
+	_errorReporter.warning("The call to \"" + _signature + "\" returned \n" + BytesUtils::formatRawBytes(_bytes));
```
Comment (Marenz) [inline test/libsolidity/util/TestFunctionCall.cpp:167]: forgotten debug output? Or wrong indent?

File: test/libsolidity/util/TestFunctionCall.cpp [hunk 36]
```diff
@@ -279,11 +280,14 @@ string TestFunctionCall::formatRawParameters(
 	stringstream os;
 	for (auto const& param: _params)
 	{
-		if (param.format.newline)
-			os << endl << _linePrefix << "// ";
-		os << param.rawString;
-		if (&param != &_params.back())
-			os << ", ";
+		if (!param.rawString.empty())
```
Comment (Marenz) [inline test/libsolidity/util/TestFunctionCall.cpp:211]: you can remove the {} of the `for`

File: test/libsolidity/util/ContractABIUtils.cpp [hunk 37]
```diff
@@ -33,55 +39,272 @@ using namespace dev::solidity::test;
...
+	ParameterList dynamicTypeParams;
+
+	ParameterList finalParams;
+
+	if (!_contractABI)
+		return boost::none;
+
 	for (auto const& function: _contractABI)
-		if (function["name"] == _functionName)
+	{
```
Comment (Marenz) [inline test/libsolidity/util/ContractABIUtils.cpp]: You can remove the `{}`'s here

File: test/libsolidity/util/TestFunctionCall.cpp (hunk 35 above)
Comment (Marenz) [reply test/libsolidity/util/TestFunctionCall.cpp:167]: Ah, I believe this was added too early in the commit history

**Review by Marenz — CHANGES_REQUESTED** [review]
LGTM, but a few smaller things

File: test/libsolidity/util/TestFunctionCall.cpp (hunk 35 above)
Comment (erak) [reply test/libsolidity/util/TestFunctionCall.cpp:167]: What exactly do you mean? The indentation seems to be correct and it was added with the right commit.

Comment (Marenz) [reply test/libsolidity/util/TestFunctionCall.cpp:167]: Your intention was to add this in commit https://github.com/ethereum/solidity/pull/7052/commits/e72e6964777f0768baa0c22fd476d56e9960db86
"[isoltest] Prints bytes result if expectations mismatch."? If yes, then it's not correctly indented for the
`for (auto const& param: preferredParams)` loop body.

Comment (erak) [reply test/libsolidity/util/TestFunctionCall.cpp:167]: Ah, I see. You're right. It is supposed to be added by that commit. I would squash at least some commits, and this one for sure. So, shall I leave it like that?

Comment (Marenz) [reply test/libsolidity/util/TestFunctionCall.cpp:167]: sgtm :+1:

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 37 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: Ah, I need them back because of the changes coming with the comment on the `return` below ;)

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 29 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp]: It will loop `min(_source.size(), _target.size())` times.

**Comment by leonardoalt** [comment]
Tests are failing

File: test/libsolidity/util/ContractABIUtils.cpp (hunk 27 above)
Comment (erak) [reply test/libsolidity/util/ContractABIUtils.cpp:74]: The issue here is, that `_addressTypes += <hex>` would break the update for
```
contract C {
    struct S {
        uint a;
        uint b;
    }
    function t1() public returns (S memory) {
        return S(23, 42);
    }
}
// ----
// t1() -> 23
```

File: test/libsolidity/semanticTests/smoke_test.sol [hunk 38]
```diff
@@ -1,5 +1,17 @@
+pragma experimental ABIEncoderV2;
+
 contract C {
+    struct S {
```
Comment (chriseth) [inline test/libsolidity/semanticTests/smoke_test.sol:4]: This file is WAY too complicated for a smoke test. Please split.

**Comment by chriseth** [comment]
It's probably better to merge this for now, even if it does not cover all cases yet.

**Review by chriseth — APPROVED** [review]
