### PR TITLE
[yul-phaser] Fix slow tests for classic genetic algorithm

### LINKED ISSUE #9343: Tests for the classic genetic algorithm in yul-phaser are very slow
## Description
Investigate, fix and re-enable tests disabled in #9342.

[My analysis posted on Gitter](https://gitter.im/ethereum/solidity-dev?at=5f0489a9a9378637e8b2215b):
> Looks like it's just 5 tests that take 99% of execution time with `--run_test=Phaser`. And takes more like 70 seconds:
> ```
> /solidity/test/yulPhaser/GeneticAlgorithms.cpp(215): Leaving test case "runNextRound_should_select_individuals_with_probability_proportional_to_fitness"; testing time: 2894241us
> /solidity/test/yulPhaser/GeneticAlgorithms.cpp(256): Leaving test case "runNextRound_should_select_only_individuals_existing_in_the_original_population"; testing time: 7107841us
> /solidity/test/yulPhaser/GeneticAlgorithms.cpp(300): Leaving test case "runNextRound_should_do_mutation"; testing time: 20214808us
> /solidity/test/yulPhaser/GeneticAlgorithms.cpp(329): Leaving test case "runNextRound_should_do_deletion"; testing time: 14013702us
> /solidity/test/yulPhaser/GeneticAlgorithms.cpp(358): Leaving test case "runNextRound_should_do_addition"; testing time: 22049925us
> 
> /solidity/test/yulPhaser/GeneticAlgorithms.cpp(213): Leaving test suite "ClassicGeneticAlgorithmTest"; testing time: 66300487us
> ```
> 
> They're all tests for the classic algorithm that I added at the end.
> 
> It's weird that those tests in particular are so slow. There are many others that repeat stuff thousands of times to check distributions of random values and they still run below 1 second taken all together. At a glance I don't see anything that should be making them that slow. For example `runNextRound_should_do_addition` runs just one round with 1000 identical `"aaaaaaaaaa"` chromosomes with a dummy metric that does not even optimize any program (it just returns chromosome length). It should finish instantly.
> 
> I don't see anything obvious in these tests or in the algorithm code so this will need some profiling. In the meantime, I think I'll just disable them and create an issue to investigate and re-enable them when I'm done with `solc-bin` nightly and release scripts. The code has tons of tests anyway so I don't think it's going to fall into disrepair without those 5 in the meantime :)

## Steps to Reproduce
This should finish instantly:
```bash
soltest --log_level=test_suite --run_test=Phaser
```

### PR DESCRIPTION
**Pull request by cameel**
Fixes #9343 and re-enables the disabled tests.

Turns out that the thing that was slowing tests was my last-minute change to `isFitter()` function to make chromosome comparisons deterministic. The change was a lexicographic comparison if length and fitness of both chromosomes were the same. The worst case scenario for this is a huge population of many long identical chromosomes - and that's exactly the case in the affected tests. The comparison was not very heavy on its own but still much heavier than iterating over a string and it's a very common operation. It involved iterating over the chromosome and looking up every step name in a map.

My fix is a refactor suggested at some point by @chriseth - making `Chromosome` store the string of abbreviations rather than a vector of optimisation step names. This way the string conversion is now basically free.

The re-enabled tests are now back to running in ~1 second (down from ~70 seconds before refactoring).

### CODE REVIEW

File: test/yulPhaser/Chromosome.cpp [hunk 1]
```diff
@@ -47,25 +47,25 @@ using namespace solidity::util;
 namespace solidity::phaser::test
 {
 
+vector<string> const ChrOmOsoMeSteps{
```
Comment (chriseth) [inline test/yulPhaser/Chromosome.cpp:50]: Why the weird capitalization?

Comment (chriseth) [reply test/yulPhaser/Chromosome.cpp:50]: Oh, I see!

Comment (cameel) [reply test/yulPhaser/Chromosome.cpp:50]: Yeah. I could not come up with a better name for it :)

**Review by chriseth — APPROVED** [review]
