### PR TITLE
Turn toCompactHexWithPrefix into a template and support unsigned types

### LINKED ISSUE #11398: Build failure with boost 1.76
## Description

After updating to boost 1.76 solidty v0.1.4-15954-gf58d58738 fails to build with what appears to be a type conversion issue.

## Environment

- Compiler version:
NA
- Target EVM version (as per compiler settings):
NA
- Framework/IDE (e.g. Truffle or Remix):
NA
- EVM execution environment / backend / blockchain client:
NA
- Operating system:
Arch linux.
gcc 10.2
boost 1.76
## Steps to Reproduce
```
    mkdir build
    cd build
    cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DTESTS=OFF \
        ..
    make
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost headers in 
-- Found Boost::filesystem at 
-- Found Boost::unit_test_framework at 
-- Found Boost::program_options at 
-- Found Boost::system at 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test fstack-protector-strong
-- Performing Test fstack-protector-strong - Success
-- Performing Test Wimplicit-fallthrough
-- Performing Test Wimplicit-fallthrough - Success
-- Performing Test fmacro-prefix-map=/build/solidity/src/solidity=/solidity
-- Performing Test fmacro-prefix-map=/build/solidity/src/solidity=/solidity - Success
-- Performing Test Wpessimizing-move
-- Performing Test Wpessimizing-move - Success
-- Performing Test Wredundant-move
-- Performing Test Wredundant-move - Success
-- Performing Test $<$<COMPILE_LANGUAGECXX>-Wextra-semi>
-- Performing Test $<$<COMPILE_LANGUAGECXX>-Wextra-semi> - Success
-- Performing Test Wfinal-dtor-non-final-class
-- Performing Test Wfinal-dtor-non-final-class - Failed
-- Performing Test Wnewline-eof
-- Performing Test Wnewline-eof - Failed
-- Performing Test Wsuggest-destructor-override
-- Performing Test Wsuggest-destructor-override - Failed
-- Performing Test Wduplicated-cond
-- Performing Test Wduplicated-cond - Success
-- Performing Test Wduplicate-enum
-- Performing Test Wduplicate-enum - Failed
-- Performing Test Wlogical-op
-- Performing Test Wlogical-op - Success
-- Performing Test Wno-unknown-attributes
-- Performing Test Wno-unknown-attributes - Failed

------------------------------------------------------------------------
-- Configuring solidity 0.8.5
------------------------------------------------------------------------
--                  CMake Version                            3.20.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
-- COVERAGE         Coverage support                         OFF
------------------------------------------------------------- components
-- TESTS            Build tests                              OFF
------------------------------------------------------------------ flags
-- OSSFUZZ                                                   OFF
------------------------------------------------------------------------

-- Found Z3: /usr/lib64/cmake/z3/Z3Config.cmake (found suitable version "4.8.10.0", minimum required is "4.8.0") 
Z3 SMT solver found. This enables optional SMT checking with Z3.
CVC4 SMT solver found. This enables optional SMT checking with CVC4.
-- Configuring done
-- Generating done
-- Build files have been written to: /build/solidity/src/solidity/build
[  1%] Creating directories for 'jsoncpp-project'
[  1%] Creating directories for 'range-v3-project'
[  1%] Built target solidity_BuildInfo.h
[  1%] Performing download step (download, verify and extract) for 'jsoncpp-project'
[  2%] Performing download step (download, verify and extract) for 'range-v3-project'
-- Downloading...
   dst='/build/solidity/src/solidity/deps/downloads/jsoncpp-1.9.3.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/open-source-parsers/jsoncpp/archive/1.9.3.tar.gz'
-- Downloading...
   dst='/build/solidity/src/solidity/deps/downloads/range-v3-0.11.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/ericniebler/range-v3/archive/0.11.0.tar.gz'
-- [download 100% complete]
-- [download 100% complete]
-- [download 2% complete]
-- [download 5% complete]
-- [download 8% complete]
-- [download 10% complete]
-- [download 13% complete]
-- [download 16% complete]
-- [download 19% complete]
-- [download 22% complete]
-- [download 25% complete]
-- [download 28% complete]
-- [download 31% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 38% complete]
-- [download 41% complete]
-- [download 44% complete]
-- [download 47% complete]
-- [download 49% complete]
-- [download 52% complete]
-- [download 55% complete]
-- [download 58% complete]
-- [download 61% complete]
-- [download 64% complete]
-- [download 67% complete]
-- [download 69% complete]
-- [download 71% complete]
-- [download 74% complete]
-- [download 77% complete]
-- [download 80% complete]
-- [download 83% complete]
-- [download 85% complete]
-- [download 87% complete]
-- [download 89% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 95% complete]
-- [download 98% complete]
-- [download 100% complete]
-- verifying file...
       file='/build/solidity/src/solidity/deps/downloads/range-v3-0.11.0.tar.gz'
-- Downloading... done
-- extracting...
     src='/build/solidity/src/solidity/deps/downloads/range-v3-0.11.0.tar.gz'
     dst='/build/solidity/src/solidity/build/deps/src/range-v3-project'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  2%] No update step for 'range-v3-project'
[  3%] No patch step for 'range-v3-project'
[  3%] Performing configure step for 'range-v3-project'
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- verifying file...
       file='/build/solidity/src/solidity/deps/downloads/jsoncpp-1.9.3.tar.gz'
-- Downloading... done
-- extracting...
     src='/build/solidity/src/solidity/deps/downloads/jsoncpp-1.9.3.tar.gz'
     dst='/build/solidity/src/solidity/build/deps/src/jsoncpp-project'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  4%] No update step for 'jsoncpp-project'
-- Detecting CXX compiler ABI info - done
[  4%] No patch step for 'jsoncpp-project'
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.31.1") 
[  5%] Performing configure step for 'jsoncpp-project'
-- [range-v3]: C++ std=17
-- Performing Test RANGES_HAS_CXXSTD
-- Performing Test RANGES_HAS_CXXSTD - Success
-- Performing Test RANGES_HAS_WALL
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Performing Test RANGES_HAS_WALL - Success
-- Performing Test RANGES_HAS_WEXTRA
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- JsonCpp Version: 1.9.3
-- Looking for C++ include clocale
-- Performing Test RANGES_HAS_WEXTRA - Success
-- Performing Test RANGES_HAS_WERROR
-- Looking for C++ include clocale - found
-- Looking for localeconv
-- Performing Test RANGES_HAS_WERROR - Success
-- Performing Test RANGES_HAS_FDIAGNOSTIC_SHOW_TEMPLATE_TREE
-- Looking for localeconv - found
-- Looking for C++ include sys/types.h
-- Performing Test RANGES_HAS_FDIAGNOSTIC_SHOW_TEMPLATE_TREE - Success
-- Performing Test RANGES_HAS_FTEMPLATE_BACKTRACE_LIMIT
-- Performing Test RANGES_HAS_FTEMPLATE_BACKTRACE_LIMIT - Success
-- Performing Test RANGES_HAS_FMACRO_BACKTRACE_LIMIT
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Performing Test RANGES_HAS_FMACRO_BACKTRACE_LIMIT - Failed
-- Performing Test RANGES_HAS_OMIT_FRAME_POINTER
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Performing Test RANGES_HAS_OMIT_FRAME_POINTER - Success
-- Performing Test RANGES_HAS_OFAST
-- Looking for C++ include stddef.h - found
-- Check size of lconv
-- Performing Test RANGES_HAS_OFAST - Success
-- Performing Test RANGES_HAS_STRICT_ALIASING
-- Performing Test RANGES_HAS_STRICT_ALIASING - Success
-- Performing Test RANGES_HAS_STRICT_VTABLE_POINTERS
-- Check size of lconv - done
-- Performing Test HAVE_DECIMAL_POINT
-- Performing Test RANGES_HAS_STRICT_VTABLE_POINTERS - Failed
-- Performing Test RANGES_HAS_FAST_MATH
-- Performing Test HAVE_DECIMAL_POINT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /build/solidity/src/solidity/build/deps/src/jsoncpp-project-build
-- Performing Test RANGES_HAS_FAST_MATH - Success
-- Performing Test RANGES_HAS_VECTORIZE
[  5%] Performing build step for 'jsoncpp-project'
-- Performing Test RANGES_HAS_VECTORIZE - Failed
-- Performing Test RANGES_HAS_SIZED_DEALLOCATION
[ 25%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_reader.cpp.o
[ 75%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_writer.cpp.o
[ 75%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_value.cpp.o
-- Performing Test RANGES_HAS_SIZED_DEALLOCATION - Success
-- Performing Test RANGES_HAS_MARCH_NATIVE
-- Performing Test RANGES_HAS_MARCH_NATIVE - Success
-- Performing Test RANGES_HAS_MTUNE_NATIVE
-- Performing Test RANGES_HAS_MTUNE_NATIVE - Success
-- Performing Test RANGE_V3_ALIGNED_NEW_PROBE
-- Performing Test RANGE_V3_ALIGNED_NEW_PROBE - Success
-- Performing Test RANGE_V3_HAS_FCONCEPTS
-- Performing Test RANGE_V3_HAS_FCONCEPTS - Success
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


-- Build files have been written to: /build/solidity/src/solidity/build/deps/src/range-v3-project-build
[  6%] Performing build step for 'range-v3-project'
[  6%] Performing install step for 'range-v3-project'
Install the project...
-- Install configuration: "Release"
-- Installing: /build/solidity/src/solidity/build/deps/lib/cmake/range-v3/range-v3-targets.cmake
-- Installing: /build/solidity/src/solidity/build/deps/lib/cmake/range-v3/range-v3-config-version.cmake
-- Installing: /build/solidity/src/solidity/build/deps/lib/cmake/range-v3/range-v3-config.cmake
-- Up-to-date: /build/solidity/src/solidity/build/deps/include
-- Installing: /build/solidity/src/solidity/build/deps/include/std
-- Installing: /build/solidity/src/solidity/build/deps/include/std/iterator
-- Installing: /build/solidity/src/solidity/build/deps/include/std/detail
-- Installing: /build/solidity/src/solidity/build/deps/include/std/detail/associated_types.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/meta
-- Installing: /build/solidity/src/solidity/build/deps/include/meta/meta_fwd.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/meta/meta.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/experimental
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/experimental/view
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/experimental/view/shared.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/experimental/utility
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/experimental/utility/generator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/arithmetic.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/comparisons.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/pipeable.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/identity.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/not_fn.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/indirect.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/overload.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/on.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/bind.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/reference_wrapper.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/compose.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/bind_back.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/invoke.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional/concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range_fwd.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/traits.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/basic_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/unreachable_sentinel.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/access.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/counted_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/stream_iterators.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/diffmax_t.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/insert_iterators.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/reverse_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/default_sentinel.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/operations.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/move_iterators.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/common_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator/concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/functional.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/compare.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/span.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/size.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view_interface.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view_facade.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/data.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/cartesian_product.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/exclusive_scan.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/unique.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/filter.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/drop_exactly.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/for_each.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/sliding.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/slice.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/adaptor.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/take.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/take_exactly.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/drop.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/stride.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/transform.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/span.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/single.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/common.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/adjacent_remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/cycle.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/drop_last.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/set_algorithm.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/subrange.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/sample.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/intersperse.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/view.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/move.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/zip.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/addressof.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/repeat_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/remove.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/chunk.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/c_str.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/join.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/const.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/interface.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/take_last.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/iota.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/group_by.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/delimit.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/repeat.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/replace_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/tail.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/indirect.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/enumerate.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/replace.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/concat.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/linear_distribute.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/split_when.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/getlines.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/map.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/drop_while.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/partial_sum.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/cache1.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/any_view.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/ref.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/trim.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/facade.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/adjacent_filter.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/zip_with.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/all.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/split.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/empty.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/counted.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/generate_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/unbounded.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/istream.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/take_while.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/bounded.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/reverse.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/tokenize.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/generate.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view/indices.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range_for.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/traits.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/conversion.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/dangling.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/access.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/primitives.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/operations.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range/concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/to_container.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/memory.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/get.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/semiregular_box.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/basic_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/semiregular.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/unreachable.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/functional.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/iterator_traits.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/infinity.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/static_const.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/dangling.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/in_place.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/tagged_pair.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/tuple_algorithm.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/move.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/nullptr_v.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/addressof.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/optional.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/common_type.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/counted_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/swap.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/variant.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/scope_exit.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/associated_types.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/any.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/box.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/common_tuple.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/compressed_pair.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/tagged_tuple.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/iterator_concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/polymorphic_cast.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/common_iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/invoke.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/random.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility/concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range_access.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/at.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/view_adaptor.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/back.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/unique.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/partition_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/min_element.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/for_each.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/is_sorted.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/binary_search.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/search_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/remove_copy_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/minmax.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/replace_copy_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/transform.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/partial_sort.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/equal.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/rotate_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/all_of.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/partition.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/swap_ranges.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/is_sorted_until.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/move_backward.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/reverse_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/find_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/adjacent_find.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/adjacent_remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/ends_with.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/copy_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/rotate.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/find_if_not.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/set_algorithm.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/inplace_merge.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/sample.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/shuffle.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/fill_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/move.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/find_first_of.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/max_element.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/mismatch.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/remove.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/is_partitioned.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/count_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/remove_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/stable_sort.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/copy_backward.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/lexicographical_compare.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/find.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/any_of.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/find_end.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/none_of.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/fill.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/partition_point_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/sort_n_with_buffer.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/merge_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/upper_bound_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/merge_n_with_buffer.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/equal_range_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/aux_/lower_bound_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/unstable_remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/copy_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/merge.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/replace_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/stable_partition.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/replace.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/tagspec.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/lower_bound.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/contains.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/heap_algorithm.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/permutation.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/min.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/nth_element.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/partition_point.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/unique_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/for_each_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/search.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/equal_range.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/sort.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/starts_with.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/result_types.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/count.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/generate_n.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/upper_bound.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/replace_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/partial_sort_copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/minmax_element.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/reverse.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/copy.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/max.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/algorithm/generate.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/getlines.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/index.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range_traits.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/action.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/unique.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/insert.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/slice.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/take.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/drop.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/stride.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/transform.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/push_back.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/adjacent_remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/shuffle.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/erase.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/remove.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/join.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/stable_sort.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/unstable_remove_if.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/split_when.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/drop_while.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/push_front.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/split.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/sort.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/take_while.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/reverse.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/action/concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/utility.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/satisfy_boost_range.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/with_braced_init_args.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/variant.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/range_access.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/adl_get.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/config.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/prologue.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/detail/epilogue.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator_range.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/core.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/range_concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/all.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/iterator.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/empty.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/begin_end.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/istream_range.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/distance.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/version.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/front.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric/accumulate.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric/inner_product.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric/iota.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric/adjacent_difference.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/range/v3/numeric/partial_sum.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/concepts
-- Installing: /build/solidity/src/solidity/build/deps/include/concepts/compare.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/concepts/type_traits.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/concepts/swap.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/concepts/concepts.hpp
-- Installing: /build/solidity/src/solidity/build/deps/include/module.modulemap
[  6%] Completed 'range-v3-project'
/build/solidity/src/solidity/build/deps/src/jsoncpp-project/src/lib_json/json_reader.cpp:756:34: warning: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead. [-Wdeprecated-declarations]
  756 | Reader::Char Reader::getNextChar() {
      |                                  ^
In file included from /build/solidity/src/solidity/build/deps/src/jsoncpp-project/src/lib_json/json_reader.cpp:10:
/build/solidity/src/solidity/build/deps/src/jsoncpp-project/src/lib_json/../../include/json/reader.h:37:63: note: declared here
   37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
      |                                                               ^~~~~~
/build/solidity/src/solidity/build/deps/src/jsoncpp-project/src/lib_json/json_reader.cpp:810:21: warning: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead. [-Wdeprecated-declarations]
  810 | std::vector<Reader::StructuredError> Reader::getStructuredErrors() const {
      |                     ^~~~~~~~~~~~~~~
In file included from /build/solidity/src/solidity/build/deps/src/jsoncpp-project/src/lib_json/json_reader.cpp:10:
/build/solidity/src/solidity/build/deps/src/jsoncpp-project/src/lib_json/../../include/json/reader.h:37:63: note: declared here
   37 |     "Use CharReader and CharReaderBuilder instead.") JSON_API Reader {
      |                                                               ^~~~~~
[  6%] Built target range-v3-project
[100%] Linking CXX static library ../../lib/libjsoncpp.a
[100%] Built target jsoncpp_lib
[  6%] Performing install step for 'jsoncpp-project'
Consolidate compiler generated dependencies of target jsoncpp_lib
[100%] Built target jsoncpp_lib
Install the project...
-- Install configuration: "Release"
-- Installing: /build/solidity/src/solidity/build/deps/lib/cmake/jsoncpp/jsoncppConfig.cmake
-- Installing: /build/solidity/src/solidity/build/deps/lib/cmake/jsoncpp/jsoncppConfig-release.cmake
-- Installing: /build/solidity/src/solidity/build/deps/lib/cmake/jsoncpp/jsoncppConfigVersion.cmake
-- Installing: /build/solidity/src/solidity/build/deps/lib/libjsoncpp.a
-- Installing: /build/solidity/src/solidity/build/deps/include/json/allocator.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/assertions.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/config.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/forwards.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/json.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/json_features.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/reader.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/value.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/version.h
-- Installing: /build/solidity/src/solidity/build/deps/include/json/writer.h
[  7%] Completed 'jsoncpp-project'
[  7%] Built target jsoncpp-project
[  8%] Building CXX object libsolutil/CMakeFiles/solutil.dir/Common.cpp.o
[  8%] Building CXX object libsolutil/CMakeFiles/solutil.dir/CommonData.cpp.o
[  8%] Building CXX object libsolutil/CMakeFiles/solutil.dir/IndentedWriter.cpp.o
[  8%] Building CXX object libsolutil/CMakeFiles/solutil.dir/JSON.cpp.o
[  8%] Building CXX object libsolutil/CMakeFiles/solutil.dir/Exceptions.cpp.o
[  9%] Building CXX object libsolutil/CMakeFiles/solutil.dir/CommonIO.cpp.o
[  9%] Building CXX object libsolutil/CMakeFiles/solutil.dir/Keccak256.cpp.o
[  9%] Building CXX object libsolutil/CMakeFiles/solutil.dir/SwarmHash.cpp.o
[ 10%] Building CXX object libsolutil/CMakeFiles/solutil.dir/UTF8.cpp.o
[ 11%] Building CXX object libsolutil/CMakeFiles/solutil.dir/IpfsHash.cpp.o
[ 12%] Building CXX object libsolutil/CMakeFiles/solutil.dir/StringUtils.cpp.o
[ 12%] Building CXX object libsolutil/CMakeFiles/solutil.dir/Whiskers.cpp.o
[ 12%] Linking CXX static library libsolutil.a
[ 12%] Built target solutil
[ 12%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o
[ 12%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/CHCSmtLib2Interface.cpp.o
[ 12%] Building CXX object liblangutil/CMakeFiles/langutil.dir/CharStream.cpp.o
[ 13%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/Sorts.cpp.o
[ 15%] Building CXX object liblangutil/CMakeFiles/langutil.dir/EVMVersion.cpp.o
[ 15%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/SMTLib2Interface.cpp.o
[ 15%] Building CXX object liblangutil/CMakeFiles/langutil.dir/Exceptions.cpp.o
[ 15%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/AssemblyItem.cpp.o
[ 15%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/Z3Interface.cpp.o
[ 15%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/Z3CHCInterface.cpp.o
[ 15%] Building CXX object liblangutil/CMakeFiles/langutil.dir/Scanner.cpp.o
[ 15%] Building CXX object liblangutil/CMakeFiles/langutil.dir/ErrorReporter.cpp.o
[ 15%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/SMTPortfolio.cpp.o
[ 15%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/ExpressionClasses.cpp.o
[ 15%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/ConstantOptimiser.cpp.o
[ 15%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/CommonSubexpressionEliminator.cpp.o
[ 17%] Building CXX object liblangutil/CMakeFiles/langutil.dir/SourceLocation.cpp.o
[ 18%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/BlockDeduplicator.cpp.o
[ 18%] Building CXX object liblangutil/CMakeFiles/langutil.dir/ParserBase.cpp.o
[ 21%] Building CXX object libsmtutil/CMakeFiles/smtutil.dir/CVC4Interface.cpp.o
[ 21%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/Inliner.cpp.o
[ 21%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/ControlFlowGraph.cpp.o
[ 21%] Building CXX object liblangutil/CMakeFiles/langutil.dir/SourceReferenceExtractor.cpp.o
[ 21%] Building CXX object liblangutil/CMakeFiles/langutil.dir/SemVerHandler.cpp.o
[ 21%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/GasMeter.cpp.o
[ 23%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/PathGasMeter.cpp.o
[ 23%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/JumpdestRemover.cpp.o
[ 23%] Building CXX object liblangutil/CMakeFiles/langutil.dir/SourceReferenceFormatter.cpp.o
[ 23%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/Instruction.cpp.o
[ 24%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/LinkerObject.cpp.o
[ 24%] Building CXX object liblangutil/CMakeFiles/langutil.dir/Token.cpp.o
[ 24%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/KnownState.cpp.o
[ 24%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/PeepholeOptimiser.cpp.o
[ 25%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/SemanticInformation.cpp.o
[ 25%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/SimplificationRules.cpp.o
[ 25%] Linking CXX static library liblangutil.a
[ 25%] Built target langutil
[ 25%] Linking CXX static library libsmtutil.a
[ 25%] Built target smtutil
[ 25%] Linking CXX static library libevmasm.a
[ 25%] Built target evmasm
[ 26%] Building CXX object libyul/CMakeFiles/yul.dir/AsmJsonImporter.cpp.o
[ 28%] Building CXX object libyul/CMakeFiles/yul.dir/Dialect.cpp.o
[ 28%] Building CXX object libyul/CMakeFiles/yul.dir/AsmAnalysis.cpp.o
[ 28%] Building CXX object libyul/CMakeFiles/yul.dir/AsmJsonConverter.cpp.o
[ 28%] Building CXX object libyul/CMakeFiles/yul.dir/AsmParser.cpp.o
[ 28%] Building CXX object libyul/CMakeFiles/yul.dir/AsmPrinter.cpp.o
[ 28%] Building CXX object libyul/CMakeFiles/yul.dir/ObjectParser.cpp.o
[ 29%] Building CXX object libyul/CMakeFiles/yul.dir/AssemblyStack.cpp.o
[ 29%] Building CXX object libyul/CMakeFiles/yul.dir/Object.cpp.o
[ 29%] Building CXX object libyul/CMakeFiles/yul.dir/ScopeFiller.cpp.o
[ 30%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/AsmCodeGen.cpp.o
[ 30%] Building CXX object libyul/CMakeFiles/yul.dir/Utilities.cpp.o
[ 30%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/ConstantOptimiser.cpp.o
[ 30%] Building CXX object libyul/CMakeFiles/yul.dir/CompilabilityChecker.cpp.o
[ 31%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/EthAssemblyAdapter.cpp.o
[ 31%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/EVMAssembly.cpp.o
[ 31%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/EVMObjectCompiler.cpp.o
[ 31%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/EVMCodeTransform.cpp.o
[ 32%] Building CXX object libyul/CMakeFiles/yul.dir/Scope.cpp.o
[ 33%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/EVMDialect.cpp.o
[ 33%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/NoOutputAssembly.cpp.o
[ 33%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/VariableReferenceCounter.cpp.o
[ 34%] Building CXX object libyul/CMakeFiles/yul.dir/backends/evm/EVMMetrics.cpp.o
[ 35%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/EVMToEwasmTranslator.cpp.o
[ 35%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/TextTransform.cpp.o
[ 35%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/BinaryTransform.cpp.o
[ 35%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/WasmDialect.cpp.o
[ 36%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/WasmCodeTransform.cpp.o
[ 37%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/WasmObjectCompiler.cpp.o
[ 37%] Building CXX object libyul/CMakeFiles/yul.dir/backends/wasm/WordSizeTransform.cpp.o
[ 37%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ASTCopier.cpp.o
[ 38%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ASTWalker.cpp.o
[ 38%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/BlockFlattener.cpp.o
[ 39%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/BlockHasher.cpp.o
[ 39%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/CallGraphGenerator.cpp.o
[ 39%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/CircularReferencesPruner.cpp.o
[ 40%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/CommonSubexpressionEliminator.cpp.o
[ 40%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ConditionalSimplifier.cpp.o
[ 41%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ConditionalUnsimplifier.cpp.o
[ 41%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ControlFlowSimplifier.cpp.o
[ 41%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/DataFlowAnalyzer.cpp.o
[ 42%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/DeadCodeEliminator.cpp.o
[ 42%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/Disambiguator.cpp.o
[ 42%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/EquivalentFunctionDetector.cpp.o
[ 43%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/EquivalentFunctionCombiner.cpp.o
[ 43%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ExpressionInliner.cpp.o
[ 44%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ExpressionJoiner.cpp.o
[ 44%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ExpressionSimplifier.cpp.o
[ 44%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ExpressionSplitter.cpp.o
[ 45%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ForLoopConditionIntoBody.cpp.o
[ 45%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ForLoopConditionOutOfBody.cpp.o
[ 46%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ForLoopInitRewriter.cpp.o
[ 46%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/FullInliner.cpp.o
[ 46%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/FunctionCallFinder.cpp.o
[ 47%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/FunctionGrouper.cpp.o
[ 47%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/FunctionHoister.cpp.o
[ 48%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/FunctionSpecializer.cpp.o
[ 48%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/InlinableExpressionFunctionFinder.cpp.o
[ 48%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/KnowledgeBase.cpp.o
[ 49%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/LoadResolver.cpp.o
[ 49%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/LoopInvariantCodeMotion.cpp.o
[ 50%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/MainFunction.cpp.o
[ 50%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/Metrics.cpp.o
[ 50%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/NameCollector.cpp.o
[ 51%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/NameDispenser.cpp.o
[ 51%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/NameDisplacer.cpp.o
[ 51%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/NameSimplifier.cpp.o
[ 52%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/OptimizerUtilities.cpp.o
[ 52%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/ReasoningBasedSimplifier.cpp.o
[ 53%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/RedundantAssignEliminator.cpp.o
[ 53%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/Rematerialiser.cpp.o
[ 53%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/SMTSolver.cpp.o
[ 54%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/SSAReverser.cpp.o
[ 54%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/SSATransform.cpp.o
[ 54%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/SSAValueTracker.cpp.o
[ 55%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/Semantics.cpp.o
[ 55%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/SimplificationRules.cpp.o
[ 56%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/StackCompressor.cpp.o
[ 56%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/StackLimitEvader.cpp.o
[ 56%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/StackToMemoryMover.cpp.o
[ 57%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/StructuralSimplifier.cpp.o
[ 57%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/Substitution.cpp.o
[ 58%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/Suite.cpp.o
[ 58%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/SyntacticalEquality.cpp.o
[ 58%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/TypeInfo.cpp.o
[ 59%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/UnusedFunctionParameterPruner.cpp.o
[ 59%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/UnusedFunctionsCommon.cpp.o
[ 60%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/UnusedPruner.cpp.o
[ 60%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/VarDeclInitializer.cpp.o
[ 60%] Building CXX object libyul/CMakeFiles/yul.dir/optimiser/VarNameCleaner.cpp.o
[ 61%] Linking CXX static library libyul.a
[ 61%] Built target yul
[ 63%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/DocStringTagParser.cpp.o
[ 63%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ControlFlowBuilder.cpp.o
[ 63%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ContractLevelChecker.cpp.o
[ 63%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/DeclarationContainer.cpp.o
[ 63%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ControlFlowGraph.cpp.o
[ 65%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/GlobalContext.cpp.o
[ 65%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/DocStringAnalyser.cpp.o
[ 65%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ConstantEvaluator.cpp.o
[ 66%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ControlFlowAnalyzer.cpp.o
[ 67%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/NameAndTypeResolver.cpp.o
[ 67%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/OverrideChecker.cpp.o
[ 65%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/DeclarationTypeChecker.cpp.o
[ 67%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/FunctionCallGraph.cpp.o
[ 67%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ImmutableValidator.cpp.o
[ 67%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/PostTypeChecker.cpp.o
[ 68%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/PostTypeContractLevelChecker.cpp.o
[ 69%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/StaticAnalyzer.cpp.o
[ 69%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/Scoper.cpp.o
[ 69%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/SyntaxChecker.cpp.o
[ 69%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ViewPureChecker.cpp.o
[ 69%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/AST.cpp.o
[ 71%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/ASTAnnotations.cpp.o
[ 71%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/TypeChecker.cpp.o
[ 71%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/ASTJsonConverter.cpp.o
[ 71%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/ASTUtils.cpp.o
[ 71%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ReferencesResolver.cpp.o
[ 72%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/ASTJsonImporter.cpp.o
[ 72%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/CallGraph.cpp.o
[ 73%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/Types.cpp.o
[ 73%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ABIFunctions.cpp.o
[ 73%] Building CXX object libsolidity/CMakeFiles/solidity.dir/ast/TypeProvider.cpp.o
[ 74%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ArrayUtils.cpp.o
[ 74%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/Compiler.cpp.o
[ 75%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/CompilerContext.cpp.o
[ 75%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/CompilerUtils.cpp.o
[ 75%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ContractCompiler.cpp.o
[ 76%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ExpressionCompiler.cpp.o
[ 76%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/LValue.cpp.o
[ 76%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/MultiUseYulFunctionCollector.cpp.o
[ 77%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ReturnInfo.cpp.o
[ 77%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/YulUtilFunctions.cpp.o
[ 78%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ir/Common.cpp.o
[ 78%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ir/IRGenerator.cpp.o
[ 78%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ir/IRGeneratorForStatements.cpp.o
[ 79%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ir/IRGenerationContext.cpp.o
[ 79%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ir/IRVariable.cpp.o
[ 80%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/ArraySlicePredicate.cpp.o
[ 80%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/BMC.cpp.o
[ 80%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o
[ 81%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/EncodingContext.cpp.o
[ 81%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/ModelChecker.cpp.o
[ 82%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/ModelCheckerSettings.cpp.o
[ 82%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/Predicate.cpp.o
[ 82%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/PredicateInstance.cpp.o
[ 83%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/PredicateSort.cpp.o
[ 83%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/SMTEncoder.cpp.o
[ 83%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/SSAVariable.cpp.o
[ 84%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/SymbolicState.cpp.o
[ 84%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/SymbolicTypes.cpp.o
[ 85%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/SymbolicVariables.cpp.o
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp: In member function ‘solidity::frontend::CompilerContext& solidity::frontend::CompilerContext::appendPanic(solidity::util::PanicCode)’:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: error: no matching function for call to ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::number(solidity::util::PanicCode&)’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:317:50: note: candidate: ‘template<class Other, boost::multiprecision::expression_template_option ET> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(boost::multiprecision::number<Other, ET>&&, typename std::enable_if<(std::is_convertible<Other, Backend>::value && (! boost::multiprecision::detail::is_restricted_conversion<Other, Backend>::value))>::type*) [with Other = Other; boost::multiprecision::expression_template_option ET = ET; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  317 |    BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(number<Other, ET>&& val,
      |                                                  ^~~~~~
/usr/include/boost/multiprecision/number.hpp:317:50: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘boost::multiprecision::number<Backend, ExpressionTemplates>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:307:35: note: candidate: ‘constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(boost::multiprecision::number<Backend, ExpressionTemplates>&&) [with Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  307 |    BOOST_MP_FORCEINLINE constexpr number(number&& r)
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:307:51: note:   no known conversion for argument 1 from ‘solidity::util::PanicCode’ to ‘boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >&&’
  307 |    BOOST_MP_FORCEINLINE constexpr number(number&& r)
      |                                          ~~~~~~~~~^
/usr/include/boost/multiprecision/number.hpp:297:38: note: candidate: ‘template<class tag, class Arg1, class Arg2, class Arg3, class Arg4> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>&, typename std::enable_if<((! std::is_convertible<typename boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>::result_type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value) && boost::multiprecision::detail::is_explicitly_convertible<typename boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>::result_type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value)>::type*) [with tag = tag; Arg1 = Arg1; Arg2 = Arg2; Arg3 = Arg3; Arg4 = Arg4; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  297 |    explicit BOOST_MP_CXX14_CONSTEXPR number(const detail::expression<tag, Arg1, Arg2, Arg3, Arg4>& e,
      |                                      ^~~~~~
/usr/include/boost/multiprecision/number.hpp:297:38: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:289:29: note: candidate: ‘template<class tag, class Arg1, class Arg2, class Arg3, class Arg4> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>&, typename std::enable_if<std::is_convertible<typename boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>::result_type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value>::type*) [with tag = tag; Arg1 = Arg1; Arg2 = Arg2; Arg3 = Arg3; Arg4 = Arg4; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  289 |    BOOST_MP_CXX14_CONSTEXPR number(const detail::expression<tag, Arg1, Arg2, Arg3, Arg4>& e, typename std::enable_if<std::is_convertible<typename detail::expression<tag, Arg1, Arg2, Arg3, Arg4>::result_type, self_type>::value>::type* = 0)
      |                             ^~~~~~
/usr/include/boost/multiprecision/number.hpp:289:29: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::detail::expression<tag, Arg1, Arg2, Arg3, Arg4>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:175:50: note: candidate: ‘template<class Other, boost::multiprecision::expression_template_option ET> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Other, ET>&, const boost::multiprecision::number<Other, ET>&, typename std::enable_if<std::is_convertible<Other, Backend>::value>::type*) [with Other = Other; boost::multiprecision::expression_template_option ET = ET; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  175 |    BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const number<Other, ET>& v1, const number<Other, ET>& v2, typename std::enable_if<std::is_convertible<Other, Backend>::value>::type* = 0)
      |                                                  ^~~~~~
/usr/include/boost/multiprecision/number.hpp:175:50: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::number<Backend, ExpressionTemplates>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:170:59: note: candidate: ‘template<class V, class U> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, const U&, unsigned int, typename std::enable_if<((((std::is_constructible<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, V>::value || std::is_convertible<V, std::__cxx11::basic_string<char> >::value) && (std::is_constructible<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, U>::value || std::is_convertible<U, std::__cxx11::basic_string<char> >::value)) && (! std::is_same<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value)) && (!(boost::is_convertible<V, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value && boost::is_convertible<U, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value)))>::type*) [with V = V; U = U; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  170 |    BOOST_MP_FORCEINLINE explicit BOOST_MP_CXX14_CONSTEXPR number(const V& v1, const U& v2, unsigned digits10,
      |                                                           ^~~~~~
/usr/include/boost/multiprecision/number.hpp:170:59: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   candidate expects 4 arguments, 1 provided
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:165:50: note: candidate: ‘template<class V, class U> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, const U&, unsigned int, typename std::enable_if<((std::is_convertible<V, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value && std::is_convertible<U, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value) && (! std::is_same<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value))>::type*) [with V = V; U = U; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  165 |    BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const V& v1, const U& v2, unsigned digits10,
      |                                                  ^~~~~~
/usr/include/boost/multiprecision/number.hpp:165:50: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   candidate expects 4 arguments, 1 provided
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:153:59: note: candidate: ‘template<class Traits> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const std::basic_string_view<char, Traits>&, unsigned int) [with Traits = Traits; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  153 |    explicit BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const std::basic_string_view<char, Traits>& v, unsigned digits10)
      |                                                           ^~~~~~
/usr/include/boost/multiprecision/number.hpp:153:59: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const std::basic_string_view<char, Traits>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:147:45: note: candidate: ‘template<class Traits> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const std::basic_string_view<char, Traits>&, const std::basic_string_view<char, Traits>&) [with Traits = Traits; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  147 |    explicit inline BOOST_MP_CXX14_CONSTEXPR number(const std::basic_string_view<char, Traits>& view_x, const std::basic_string_view<char, Traits>& view_y)
      |                                             ^~~~~~
/usr/include/boost/multiprecision/number.hpp:147:45: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const std::basic_string_view<char, Traits>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:141:45: note: candidate: ‘template<class Traits> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const std::basic_string_view<char, Traits>&) [with Traits = Traits; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  141 |    explicit inline BOOST_MP_CXX14_CONSTEXPR number(const std::basic_string_view<char, Traits>& view)
      |                                             ^~~~~~
/usr/include/boost/multiprecision/number.hpp:141:45: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const std::basic_string_view<char, Traits>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:128:59: note: candidate: ‘template<class V, class U> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, const U&, typename std::enable_if<(((((std::is_constructible<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, V>::value || std::is_convertible<V, std::__cxx11::basic_string<char> >::value) && (std::is_constructible<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, U>::value || std::is_convertible<U, std::__cxx11::basic_string<char> >::value)) && (! std::is_same<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value)) && (! std::is_same<V, boost::multiprecision::number<Backend, ExpressionTemplates> >::value)) && (!(std::is_convertible<V, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value && std::is_convertible<U, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value)))>::type*) [with V = V; U = U; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  128 |    BOOST_MP_FORCEINLINE explicit BOOST_MP_CXX14_CONSTEXPR number(const V& v1, const U& v2,
      |                                                           ^~~~~~
/usr/include/boost/multiprecision/number.hpp:128:59: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   candidate expects 3 arguments, 1 provided
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:120:50: note: candidate: ‘template<class V, class U> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, const U&, typename std::enable_if<((std::is_convertible<V, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value && std::is_convertible<U, typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type>::value) && (! std::is_same<typename boost::multiprecision::component_type<boost::multiprecision::number<Backend, ExpressionTemplates> >::type, boost::multiprecision::number<Backend, ExpressionTemplates> >::value))>::type*) [with V = V; U = U; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  120 |    BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const V& v1, const U& v2,
      |                                                  ^~~~~~
/usr/include/boost/multiprecision/number.hpp:120:50: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   candidate expects 3 arguments, 1 provided
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:115:59: note: candidate: ‘template<class Other, boost::multiprecision::expression_template_option ET> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Other, ET>&, typename std::enable_if<(boost::multiprecision::detail::is_explicitly_convertible<Other, Backend>::value && (boost::multiprecision::detail::is_restricted_conversion<Other, Backend>::value || (! std::is_convertible<Other, Backend>::value)))>::type*) [with Other = Other; boost::multiprecision::expression_template_option ET = ET; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  115 |    explicit BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const number<Other, ET>& val, typename std::enable_if<
      |                                                           ^~~~~~
/usr/include/boost/multiprecision/number.hpp:115:59: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::number<Backend, ExpressionTemplates>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:103:38: note: candidate: ‘template<class Other, boost::multiprecision::expression_template_option ET> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Other, ET>&, typename std::enable_if<(! boost::multiprecision::detail::is_explicitly_convertible<Other, Backend>::value)>::type*) [with Other = Other; boost::multiprecision::expression_template_option ET = ET; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
  103 |    explicit BOOST_MP_CXX14_CONSTEXPR number(const number<Other, ET>& val, typename std::enable_if<
      |                                      ^~~~~~
/usr/include/boost/multiprecision/number.hpp:103:38: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::number<Backend, ExpressionTemplates>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:97:50: note: candidate: ‘template<class Other, boost::multiprecision::expression_template_option ET> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Other, ET>&, typename std::enable_if<(std::is_convertible<Other, Backend>::value && (! boost::multiprecision::detail::is_restricted_conversion<Other, Backend>::value))>::type*) [with Other = Other; boost::multiprecision::expression_template_option ET = ET; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   97 |    BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const number<Other, ET>& val,
      |                                                  ^~~~~~
/usr/include/boost/multiprecision/number.hpp:97:50: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::number<Backend, ExpressionTemplates>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:93:35: note: candidate: ‘template<boost::multiprecision::expression_template_option ET> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Backend, ET>&) [with boost::multiprecision::expression_template_option ET = ET; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   93 |    BOOST_MP_FORCEINLINE constexpr number(const number<Backend, ET>& val)
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:93:35: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   mismatched types ‘const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, ET>’ and ‘solidity::util::PanicCode’
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:89:44: note: candidate: ‘template<class V> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, unsigned int, typename std::enable_if<(((((boost::multiprecision::detail::is_arithmetic<V>::value || std::is_same<std::__cxx11::basic_string<char>, V>::value) || std::is_convertible<V, const char*>::value) && boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value) && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_complex)) && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_rational))>::type*) [with V = V; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   89 |    explicit BOOST_MP_FORCEINLINE constexpr number(const V& v, unsigned digits10, typename std::enable_if<(boost::multiprecision::detail::is_arithmetic<V>::value || std::is_same<std::string, V>::value || std::is_convertible<V, const char*>::value) && detail::is_restricted_conversion<typename detail::canonical<V, Backend>::type, Backend>::value && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_complex) && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_rational)>::type* = 0)
      |                                            ^~~~~~
/usr/include/boost/multiprecision/number.hpp:89:44: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   candidate expects 3 arguments, 1 provided
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:84:44: note: candidate: ‘template<class V> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, typename std::enable_if<(boost::multiprecision::detail::is_explicitly_convertible<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value && (boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value || (! std::is_convertible<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value)))>::type*) [with V = V; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   84 |    explicit BOOST_MP_FORCEINLINE constexpr number(const V& v, typename std::enable_if<
      |                                            ^~~~~~
/usr/include/boost/multiprecision/number.hpp:84:44: note:   template argument deduction/substitution failed:
/usr/include/boost/multiprecision/number.hpp: In substitution of ‘template<class V> constexpr boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::number(const V&, typename std::enable_if<(boost::multiprecision::detail::is_explicitly_convertible<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value && (boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value || (! std::is_convertible<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value))), void>::type*) [with V = solidity::util::PanicCode]’:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26:   required from here
/usr/include/boost/multiprecision/number.hpp:84:44: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:77:59: note: candidate: ‘template<class V> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, typename std::enable_if<((((boost::multiprecision::detail::is_arithmetic<V>::value || std::is_same<std::__cxx11::basic_string<char>, V>::value) || std::is_convertible<V, const char*>::value) && (! boost::multiprecision::detail::is_explicitly_convertible<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value)) && boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value)>::type*) [with V = V; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   77 |    explicit BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const V& v, typename std::enable_if<
      |                                                           ^~~~~~
/usr/include/boost/multiprecision/number.hpp:77:59: note:   template argument deduction/substitution failed:
/usr/include/boost/multiprecision/number.hpp: In substitution of ‘template<class V> constexpr boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::number(const V&, typename std::enable_if<((((boost::multiprecision::detail::is_arithmetic<T>::value || std::is_same<std::__cxx11::basic_string<char>, V>::value) || std::is_convertible<Val, const char*>::value) && (! boost::multiprecision::detail::is_explicitly_convertible<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value)) && boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value), void>::type*) [with V = solidity::util::PanicCode]’:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26:   required from here
/usr/include/boost/multiprecision/number.hpp:77:59: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
/usr/include/boost/multiprecision/number.hpp:73:35: note: candidate: ‘constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Backend, ExpressionTemplates>&, unsigned int) [with Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   73 |    BOOST_MP_FORCEINLINE constexpr number(const number& e, unsigned digits10)
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:73:35: note:   candidate expects 2 arguments, 1 provided
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:66:35: note: candidate: ‘template<class V> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, unsigned int, typename std::enable_if<(((((boost::multiprecision::detail::is_arithmetic<V>::value || std::is_same<std::__cxx11::basic_string<char>, V>::value) || std::is_convertible<V, const char*>::value) && (! boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value)) && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_complex)) && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_rational))>::type*) [with V = V; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   66 |    BOOST_MP_FORCEINLINE constexpr number(const V& v, unsigned digits10, typename std::enable_if<(boost::multiprecision::detail::is_arithmetic<V>::value || std::is_same<std::string, V>::value || std::is_convertible<V, const char*>::value) && !detail::is_restricted_conversion<typename detail::canonical<V, Backend>::type, Backend>::value && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_complex) && (boost::multiprecision::number_category<Backend>::value != boost::multiprecision::number_kind_rational)
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:66:35: note:   template argument deduction/substitution failed:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26: note:   candidate expects 3 arguments, 1 provided
  343 |  templ("code", u256(_code).str());
      |                          ^
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:58:35: note: candidate: ‘template<class V> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, typename std::enable_if<(std::is_convertible<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value && (! boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value))>::type*) [with V = V; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   58 |    BOOST_MP_FORCEINLINE constexpr number(const V& v, typename std::enable_if<
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:58:35: note:   template argument deduction/substitution failed:
/usr/include/boost/multiprecision/number.hpp: In substitution of ‘template<class V> constexpr boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::number(const V&, typename std::enable_if<(std::is_convertible<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value && (! boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value)), void>::type*) [with V = solidity::util::PanicCode]’:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26:   required from here
/usr/include/boost/multiprecision/number.hpp:58:35: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:48:50: note: candidate: ‘template<class V> constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const V&, typename std::enable_if<((((boost::multiprecision::detail::is_arithmetic<V>::value || std::is_same<std::__cxx11::basic_string<char>, V>::value) || std::is_convertible<V, const char*>::value) && (! std::is_convertible<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value)) && (! boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, Backend>::type, Backend>::value))>::type*) [with V = V; Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   48 |    BOOST_MP_FORCEINLINE BOOST_MP_CXX14_CONSTEXPR number(const V& v, typename std::enable_if<
      |                                                  ^~~~~~
/usr/include/boost/multiprecision/number.hpp:48:50: note:   template argument deduction/substitution failed:
/usr/include/boost/multiprecision/number.hpp: In substitution of ‘template<class V> constexpr boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::number(const V&, typename std::enable_if<((((boost::multiprecision::detail::is_arithmetic<T>::value || std::is_same<std::__cxx11::basic_string<char>, V>::value) || std::is_convertible<Val, const char*>::value) && (! std::is_convertible<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value)) && (! boost::multiprecision::detail::is_restricted_conversion<typename boost::multiprecision::detail::canonical<V, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::type, boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >::value)), void>::type*) [with V = solidity::util::PanicCode]’:
/build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:343:26:   required from here
/usr/include/boost/multiprecision/number.hpp:48:50: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
In file included from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from /build/solidity/src/solidity/libsolutil/Common.h:48,
                 from /build/solidity/src/solidity/libsolutil/CommonData.h:28,
                 from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTAnnotations.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/CompilerContext.cpp:24:
/usr/include/boost/multiprecision/number.hpp:46:35: note: candidate: ‘constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number(const boost::multiprecision::number<Backend, ExpressionTemplates>&) [with Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   46 |    BOOST_MP_FORCEINLINE constexpr number(const number& e) noexcept(noexcept(Backend(std::declval<Backend const&>()))) : m_backend(e.m_backend) {}
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:46:56: note:   no known conversion for argument 1 from ‘solidity::util::PanicCode’ to ‘const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >&’
   46 |    BOOST_MP_FORCEINLINE constexpr number(const number& e) noexcept(noexcept(Backend(std::declval<Backend const&>()))) : m_backend(e.m_backend) {}
      |                                          ~~~~~~~~~~~~~~^
/usr/include/boost/multiprecision/number.hpp:45:35: note: candidate: ‘constexpr boost::multiprecision::number<Backend, ExpressionTemplates>::number() [with Backend = boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>; boost::multiprecision::expression_template_option ExpressionTemplates = boost::multiprecision::et_off]’
   45 |    BOOST_MP_FORCEINLINE constexpr number() noexcept(noexcept(Backend())) {}
      |                                   ^~~~~~
/usr/include/boost/multiprecision/number.hpp:45:35: note:   candidate expects 0 arguments, 1 provided
[ 85%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/VariableUsage.cpp.o
[ 85%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/ABI.cpp.o
/build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.cpp: In lambda function:
/build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.cpp:4380:35: error: invalid initialization of reference of type ‘const u256&’ {aka ‘const boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256, 256, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void> >&’} from expression of type ‘solidity::util::PanicCode’
 4380 |   ("code", toCompactHexWithPrefix(_code))
      |                                   ^~~~~
In file included from /build/solidity/src/solidity/liblangutil/Exceptions.h:28,
                 from /build/solidity/src/solidity/libsolidity/ast/ASTEnums.h:25,
                 from /build/solidity/src/solidity/libsolidity/ast/Types.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.h:26,
                 from /build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.cpp:22:
/build/solidity/src/solidity/libsolutil/CommonData.h:407:55: note: in passing argument 1 of ‘std::string solidity::util::toCompactHexWithPrefix(const u256&)’
  407 | inline std::string toCompactHexWithPrefix(u256 const& _value)
      |                                           ~~~~~~~~~~~~^~~~~~
/build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.cpp: In member function ‘std::string solidity::frontend::YulUtilFunctions::panicFunction(solidity::util::PanicCode)’:
/build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.cpp:4382:3: error: no matching function for call to ‘solidity::frontend::MultiUseYulFunctionCollector::createFunction(std::string&, solidity::frontend::YulUtilFunctions::panicFunction(solidity::util::PanicCode)::<lambda()>)’
 4382 |  });
      |   ^
In file included from /build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.h:27,
                 from /build/solidity/src/solidity/libsolidity/codegen/YulUtilFunctions.cpp:22:
/build/solidity/src/solidity/libsolidity/codegen/MultiUseYulFunctionCollector.h:42:14: note: candidate: ‘std::string solidity::frontend::MultiUseYulFunctionCollector::createFunction(const string&, const std::function<std::__cxx11::basic_string<char>()>&)’
   42 |  std::string createFunction(std::string const& _name, std::function<std::string()> const& _creator);
      |              ^~~~~~~~~~~~~~
/build/solidity/src/solidity/libsolidity/codegen/MultiUseYulFunctionCollector.h:42:91: note:   no known conversion for argument 2 from ‘solidity::frontend::YulUtilFunctions::panicFunction(solidity::util::PanicCode)::<lambda()>’ to ‘const std::function<std::__cxx11::basic_string<char>()>&’
   42 |  std::string createFunction(std::string const& _name, std::function<std::string()> const& _creator);
      |                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/build/solidity/src/solidity/libsolidity/codegen/MultiUseYulFunctionCollector.h:44:14: note: candidate: ‘std::string solidity::frontend::MultiUseYulFunctionCollector::createFunction(const string&, const std::function<std::__cxx11::basic_string<char>(std::vector<std::__cxx11::basic_string<char> >&, std::vector<std::__cxx11::basic_string<char> >&)>&)’
   44 |  std::string createFunction(
      |              ^~~~~~~~~~~~~~
/build/solidity/src/solidity/libsolidity/codegen/MultiUseYulFunctionCollector.h:46:91: note:   no known conversion for argument 2 from ‘solidity::frontend::YulUtilFunctions::panicFunction(solidity::util::PanicCode)::<lambda()>’ to ‘const std::function<std::__cxx11::basic_string<char>(std::vector<std::__cxx11::basic_string<char> >&, std::vector<std::__cxx11::basic_string<char> >&)>&’
   46 |   std::function<std::string(std::vector<std::string>&, std::vector<std::string>&)> const& _creator
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
[ 86%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/CompilerStack.cpp.o
[ 86%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/FileReader.cpp.o
[ 87%] Building CXX object libsolidity/CMakeFiles/solidity.dir/interface/ImportRemapper.cpp.o
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/build.make:538: libsolidity/CMakeFiles/solidity.dir/codegen/CompilerContext.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/build.make:636: libsolidity/CMakeFiles/solidity.dir/codegen/YulUtilFunctions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:477: libsolidity/CMakeFiles/solidity.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by axic**
This should help with boost::multiprecision versions where explicit unsigned/enum conversion to bigint do not exists (such as boost 1.76)

Closes #11398

### CODE REVIEW

File: libsolutil/CommonData.h [hunk 1]
```diff
@@ -404,7 +404,8 @@ inline std::string toHex(u256 val, HexPrefix prefix = HexPrefix::DontAdd)
 	return (prefix == HexPrefix::Add) ? "0x" + str : str;
 }
 
-inline std::string toCompactHexWithPrefix(u256 const& _value)
+template <class T>
+inline std::string toCompactHexWithPrefix(T _value)
```
Comment (axic) [inline libsolutil/CommonData.h:408]: `toCompactBigEndian` is a similar template allowing for any unsigned integer and `bigint`-convertible type. Given the number of places this is used at (not extremely many), and that `toCompactBigEndian` is taking a copy anyway, I'm not convinced the const reference here is providing significant savings.

I guess we could `std::move(_value)` for `toCompactBigEndian`.

Comment (christianparpart) [reply libsolutil/CommonData.h:408]: @axic if it's only two different types that are allowed for the template type `T` and the body is basically a one-liner, wouldn't it make more sense to simply provide two overloads? It would reduce that question of what `T` can all be IMHO.

Comment (axic) [reply libsolutil/CommonData.h:408]: The typecheck is enforced in `toCompactBigEndian`. If you think it helps, that could be changed to having two overloads, but not sure that fits this PR well?

Comment (christianparpart) [reply libsolutil/CommonData.h:408]: I'm fine.

**Review by cameel — APPROVED** [review]
The fix looks correct.

I also think that two separate overloads would be better though.

**Comment by axic** [comment]
Merging this as a bugfix, we can do follow up improvement PRs.

**Comment by chriseth** [comment]
Why no `std::forward`?
