### PR TITLE
[BREAKING] Don't exclude public state variables when looking for conflicting declarations.

### LINKED ISSUE #4417: Internal compiler error on function name collision
## Solidity version:
0.4.24+commit.e67f0147.Linux.g++

## Source code:
```
pragma solidity ^0.4.24;

contract SomeContract {

  uint public balance = 0;


  function balance(uint number) public {
    
  }

  function doSomething() public {
    balance(3);
  }
}
```

## Platform:
Ubuntu 16.04.4 LTS

## How to reproduce the issue:
Run a bash script that compiles the contract like this:
```
#!/bin/sh

solc SomeContract.sol
```

## What was the result of the issue:
This output in the console:
```
Internal compiler error during compilation:
/build/solc-FodDYg/solc-0.4.24/libsolidity/analysis/TypeChecker.cpp(2260): Throw in function virtual bool dev::solidity::TypeChecker::visit(const dev::solidity::Identifier&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Requested type not present.
[dev::tag_comment*] = Requested type not present.
```

## What the expected behaviour is:
Correct compilation because of the different signatures the getter of the balance variable and the balance function have.

## Observations:
```
pragma solidity ^0.4.24;

contract SomeContract {

  mapping(uint => uint) public balance;

  function balance() public {
    
  }

  function doSomething() public {
    balance();
  }
}
```
- In this case, the same output is shown.

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #4417.

The issue suggests to allow name conflicts if function and getter end up having different signatures. I think state variables with the same name as a function are always bad and we should disallow them unconditionally.

Additionally the former behaviour was inconsistent - the following failed (``Identifier already declared.``):
```
contract C {
    function f() public pure {}
    uint256 public f = 0;
}
```
Whereas this was fine:
```
contract C {
    uint256 public f = 0;
    function f() public pure {}
}
```

### CODE REVIEW

File: libsolidity/analysis/DeclarationContainer.cpp [hunk 1]
```diff
@@ -49,16 +49,9 @@ Declaration const* DeclarationContainer::conflictingDeclaration(
 		dynamic_cast<MagicVariableDeclaration const*>(&_declaration)
 	)
 	{
-		// check that all other declarations with the same name are functions or a public state variable or events.
-		// And then check that the signatures are different.
```
Comment (ekpyron) [inline libsolidity/analysis/DeclarationContainer.cpp:53]: This was a pure lie it seems... (at least inside this function - one could mention that this will happen later on, though)

File: libsolidity/analysis/DeclarationContainer.cpp [hunk 2]
```diff
@@ -49,16 +49,9 @@ Declaration const* DeclarationContainer::conflictingDeclaration(
...
+		// check that all other declarations are of the same kind
 		for (Declaration const* declaration: declarations)
 		{
-			if (auto variableDeclaration = dynamic_cast<VariableDeclaration const*>(declaration))
-			{
-				if (variableDeclaration->isStateVariable() && !variableDeclaration->isConstant() && variableDeclaration->isPublic())
-					continue;
```
Comment (ekpyron) [inline libsolidity/analysis/DeclarationContainer.cpp:59]: Judging from the git history this exception was introduced to be able to compile an old version of ``std/StandardToken.sol``. However, this is removed now and the last version in the repository wouldn't even have needed this, so I think it's fine to remove it entirely.

**Comment by ekpyron** [comment]
We *did* have an example in the docs using this pattern (and I could imagine people using it in practice), so I'm unsure: do we want to allow name conflicts between public state variables and functions? If so, we should do so independently of the order of declaration and fix the underlying issue some other way. @chriseth @axic?

**Comment by leonardoalt** [comment]
I like the idea of disallowing state variables with the same name as a function.

**Comment by axic** [comment]
Technically there is no conflict if the function is internal, since it won't have an external signature.

If we want complex rules, we could allow that case only. However I would prefer to not have this ambiguity, but this is a breaking change and should be labeled like that.

**Comment by chriseth** [comment]
We specifically left these things out of scope of 0.5.0 to be properly discussed in the inheritance issue, but if this is a small thing to fix, we can include it and even change it again with 0.6.0 if we want.

Does this still work:
```
interface ERC20 { function x() external returns (uint); }
contract C is ERC20 { uint public x; }
```

**Comment by chriseth** [comment]
Also see https://github.com/ethereum/solidity/pull/4459

**Comment by ekpyron** [comment]
I added two additional test cases that clarify the behaviour of this PR wrt the case in the comment in the last commit.
I had not seen #4459 for some reason.

I think it may make sense to include the change in this PR, especially since otherwise the behaviour seems to depend on the order of declaration, which to me seems generally undesirable. I haven't checked how #4459 solves the underlying issue, though.

File: test/libsolidity/syntaxTests/inheritance/override/function_state_variable.sol [hunk 3]
```diff
@@ -0,0 +1,2 @@
+interface ERC20 { function x() external returns (uint); }
+contract C is ERC20 { uint public x; }
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/inheritance/override/function_state_variable.sol:2]: Ok, that looks good! So we might indeed disallow it.

File: libsolidity/analysis/DeclarationContainer.cpp [hunk 4]
```diff
@@ -49,16 +49,9 @@ Declaration const* DeclarationContainer::conflictingDeclaration(
 		dynamic_cast<MagicVariableDeclaration const*>(&_declaration)
 	)
 	{
-		// check that all other declarations with the same name are functions or a public state variable or events.
-		// And then check that the signatures are different.
+		// check that all other declarations are of the same kind
```
Comment (chriseth) [inline libsolidity/analysis/DeclarationContainer.cpp]: Please add a comment that the type checker ensures that the signatures are different.

**Comment by ekpyron** [comment]
@axic Moved the Changelog entry to "Breaking Changes" (not sure in which cases it actually worked and didn't crash before, but you're probably still right that that's more appropriate).

File: docs/solidity-by-example.rst [hunk 5]
```diff
@@ -231,18 +231,18 @@ activate themselves.
...
+        address public m_highestBidder;
+        uint public m_highestBid;
 
         // Allowed withdrawals of previous bids
-        mapping(address => uint) pendingReturns;
+        mapping(address => uint) m_pendingReturns;
 
         // Set to true at the end, disallows any change
-        bool ended;
+        bool m_ended;
```
Comment (axic) [inline docs/solidity-by-example.rst]: What is the style guide saying about this?

**Comment by axic** [comment]
I think this looks good apart from agreeing on the style changes.

**Comment by chriseth** [comment]
Can be merged in my opinion once the documentation style is fixed.

**Comment by ekpyron** [comment]
@axic I updated the example in the documentation and now only rename the variable ``auctionEnd`` to ``auctionEndTime`` which makes more sense and is consistent with the style guide.

**Review by axic — APPROVED** [review]
