### PR TITLE
fixed-sized arrays as return type for functions

### LINKED ISSUE #78: "Not yet implemented" error for returning fixed-size arrays
```
contract A { function f() constant returns (uint16[5]) { } }
contract B { function f() { A(1).f(); } }
```

### PR DESCRIPTION
**Pull request by LianaHus**
fixes https://github.com/ethereum/solidity/issues/78

### CODE REVIEW

File: libsolidity/CompilerUtils.cpp [hunk 1]
```diff
@@ -86,16 +86,27 @@ void CompilerUtils::loadFromMemoryDynamic(
...
-		m_context << u256(numBytes) << eth::Instruction::ADD;
+		solAssert(!arrayType->isDynamicallySized(), "");
+		solAssert(!_fromCalldata, "");
+		solAssert(_padToWordBoundaries, "");
+		if (_keepUpdatedMemoryOffset)
+			m_context << arrayType->memorySize() << eth::Instruction::ADD;
+	}
+	else
+	{
+		unsigned numBytes = loadFromMemoryHelper(_type, _fromCalldata, _padToWordBoundaries);
```
Comment (chriseth) [inline libsolidity/CompilerUtils.cpp]: Could you assert that it is a value type here?

File: libsolidity/Types.cpp [hunk 2]
```diff
@@ -902,6 +902,14 @@ TypePointer ArrayType::externalType() const
 		return std::make_shared<ArrayType>(DataLocation::Memory, baseExt, m_length);
 }
 
+u256 ArrayType::memorySize() const
+{
+	solAssert(!isDynamicallySized(), "");
+	solAssert(m_location == DataLocation::Memory, "");
+
+	return m_length * m_baseType->memoryHeadSize();
```
Comment (chriseth) [inline libsolidity/Types.cpp]: Please assert that the multiplication does not overflow.

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 3]
```diff
@@ -5283,6 +5283,25 @@ BOOST_AUTO_TEST_CASE(simple_throw)
...
+		}
+		contract B {
+			function f()
+			{
+				var a = new A();
+				uint16[5] memory res = a.f();
+			}
+		}
+	)";
+	compileAndRun(sourceCode, 0, "B");
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp:5350]: Please extend the test such that
- further memory is allocated and would overwrite `res` if done incorrectly
- some value from `res` is actually returned back to the caller - you could just let `B.f` also return `res` again.

File: libsolidity/Types.cpp [hunk 4]
```diff
@@ -853,6 +853,15 @@ TypePointer ArrayType::externalType() const
 		return std::make_shared<ArrayType>(DataLocation::Memory, baseExt, m_length);
 }
 
+u256 ArrayType::memorySize() const
+{
+	solAssert(!isDynamicallySized(), "");
+	solAssert(m_location == DataLocation::Memory, "");
+	u256 size =  m_length * m_baseType->memoryHeadSize();
```
Comment (chriseth) [inline libsolidity/Types.cpp:860]: If `m_length * m_baseType->memoryHeadSize()` does not fit into `u256`, it is wrapped. This is quite unlikely, but still, it might be possible to bypass some gas calculations.
Perhaps use

```
bigint size = bigint(m_length) * m_baseType->memoryHeadSize();
solAssert(size <= numeric_limits<u256>::max(), "Array size does not fit u256.");
return u256(size);
```

This might still overflow for the subsequent add where memorySize is used, though.
