### PR TITLE
Change translation of implicit throws

### LINKED ISSUE #1589: Distinguishing explicit and implicit throws
From what I can tell Solidity currently translates explicit, user-provided throw statements just like implicit ones (e.g., for division-by-zero or other runtime exceptions).

It would be nice if one were able to distinguish these to cases by looking at the resulting EVM byte code. For instance, a failing implicit throw usually constitutes an error in the contract. On the other hand, an implicit one is often used for parameter validation (i.e., a precondition) and usually the client contact (i.e., caller) is to blame (at least if the exception it is not properly dealt with).

Would it be possible to use different error tags for these two cases? Or is there some other way to tell them apart?

### PR DESCRIPTION
**Pull request by wuestholz**
Fixes #1589.

DO NOT MERGE, depensd on https://github.com/ethereum/EIPs/issues/141

@chriseth @pirapira  This adds a new invalid instruction that is used for encoding implicit throws that are emitted by the compiler. This makes it possible to distinguish such runtime errors from user-provided, explicit throws.

For some reason there seem to be three failing tests: `SolidityEndToEndTest/function_delete_stack`, `SolidityEndToEndTest/call_function_returning_function`, and `SolidityEndToEndTest/conditional_expression_functions`. The failures are due to a failing assertion in `CompilerUtils::moveToStackVariable`. However, it's not really clear to me why these changes should affect that assertion. It would be great if someone could have a look.

### CODE REVIEW

File: libsolidity/codegen/CompilerContext.cpp [hunk 1]
```diff
@@ -167,6 +167,18 @@ CompilerContext& CompilerContext::appendJump(eth::AssemblyItem::JumpType _jumpTy
...
 }
 
+CompilerContext& CompilerContext::appendInvalid()
+{
+	return *this << Instruction::INVALID;
+}
+
+CompilerContext& CompilerContext::appendConditionalInvalid()
+{
+	eth::AssemblyItem falseTag = appendConditionalJump();
```
Comment (chriseth) [inline libsolidity/codegen/CompilerContext.cpp]: I wounder whether it might be better to just have a single jump:
`ISZERO <continue> JUMPI INVALID continue:`

Your code does:
`<error> JUMPI <continue> JUMP error: INVALID continue:`

File: libsolidity/codegen/ContractCompiler.cpp [hunk 2]
```diff
@@ -910,7 +910,9 @@ eth::AssemblyPointer ContractCompiler::cloneRuntime()
 	a << Instruction::DELEGATECALL;
 	//Propagate error condition (if DELEGATECALL pushes 0 on stack).
 	a << Instruction::ISZERO;
-	a.appendJumpI(a.errorTag());
+	eth::AssemblyItem falseTag = a.appendJumpI();
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]: Why don't you use `appendConditionalInvalid()` here?

**Review by chriseth — CHANGES_REQUESTED** [review]

**Comment by chriseth** [comment]
Thanks! Please don't forget to change the documentation, too.

File: libsolidity/codegen/CompilerContext.cpp (hunk 1 above)
Comment (wuestholz) [reply libsolidity/codegen/CompilerContext.cpp]: I intentionally tried not to be too clever about encoding the jumps. I had considered the same optimization. I have pushed this now.

File: libsolidity/codegen/ContractCompiler.cpp (hunk 2 above)
Comment (wuestholz) [reply libsolidity/codegen/ContractCompiler.cpp]: It's not available for class `Assembly` and I didn't want to add it since it is only used here. However, I'd be happy to add it if you want.

**Comment by wuestholz** [comment]
@chriseth Thank you very much for the feedback. I pushed changes that should address it.

Did you have chance to look into why those three tests might be failing now? It it possible that my changes somehow uncovered a separate issue?

File: libsolidity/codegen/ContractCompiler.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/codegen/ContractCompiler.cpp]: Oh right, I'm sorry, I didn't see the full context. Is this case this is fine.

File: libsolidity/codegen/CompilerContext.cpp [hunk 3]
```diff
@@ -167,6 +167,18 @@ CompilerContext& CompilerContext::appendJump(eth::AssemblyItem::JumpType _jumpTy
...
+CompilerContext& CompilerContext::appendInvalid()
+{
+	return *this << Instruction::INVALID;
+}
+
+CompilerContext& CompilerContext::appendConditionalInvalid()
+{
+	*this << Instruction::ISZERO;
+	eth::AssemblyItem afterTag = appendConditionalJump();
+	return *this << Instruction::INVALID << afterTag;
```
Comment (chriseth) [inline libsolidity/codegen/CompilerContext.cpp]: The code generator is not too smart about the stack height with regards to control flow, so you have to manually adjust the stack height at the end of this function (it assumes that control flow continues after `invalid`). This is the reason for the test failure. You can try this snippet to check whether it worked:
```
		contract test {
			function x() returns (uint) { return 1; }
			function y() returns (uint) { return 2; }

			function f(bool cond) returns (uint) {
				var z = cond ? x : y;
				return z();
			}
		}
```

Comment (wuestholz) [reply libsolidity/codegen/CompilerContext.cpp]: Thanks! I tried the following:

```c++
	unsigned startStackHeight = stackHeight();
	*this << Instruction::ISZERO;
	eth::AssemblyItem afterTag = appendConditionalJump();
	*this << Instruction::INVALID << afterTag;
	setStackOffset(startStackHeight - 1);
	return *this;
```

However, this didn't seem to do the trick. Were you thinking of something else?

**Comment by chriseth** [comment]
Can you allow me access to your pull request branch (this is a new github feature, I think)? Then I will make the required adjustments.

**Comment by wuestholz** [comment]
@chriseth Thanks! That's fine with me. I believe I checked some box about allowing this when I created the PR. I have also added you as a collaborator just in case.

File: libevmasm/Instruction.h [hunk 4]
```diff
@@ -171,6 +171,8 @@ enum class Instruction: uint8_t
 	LOG3,				///< Makes a log entry; 3 topics.
 	LOG4,				///< Makes a log entry; 4 topics.
 
+	INVALID = 0xef,		///< invalid instruction for expressing runtime errors (e.g., division-by-zero)
```
Comment (axic) [inline libevmasm/Instruction.h]: Please update to `0xfe` as per the final EIP141.

**Comment by chriseth** [comment]
This is still not fixed, but I think we are getting closer.

**Comment by chriseth** [comment]
Ok, found the problem: Zero-initialized variables of internal function type have to be a tag. I found a solution above that is not the best yet, will submit a new version shortly.

**Comment by chriseth** [comment]
@axic / @pirapira please review.

**Comment by wuestholz** [comment]
@chriseth Great! Thanks for looking into this!

File: docs/control-structures.rst [hunk 5]
```diff
@@ -394,8 +394,13 @@ Currently, Solidity automatically generates a runtime exception in the following
 #. If you perform an external function call targeting a contract that contains no code.
 #. If your contract receives Ether via a public function without ``payable`` modifier (including the constructor and the fallback function).
 #. If your contract receives Ether via a public accessor function.
+#. If you call a zero-initialized variable of internal function type.
 
-Internally, Solidity performs an "invalid jump" when an exception is thrown and thus causes the EVM to revert all changes made to the state. The reason for this is that there is no safe way to continue execution, because an expected effect did not occur. Because we want to retain the atomicity of transactions, the safest thing to do is to revert all changes and make the whole transaction (or at least call) without effect.
+Internally, Solidity performs an "invalid jump" when a user-provided exception is thrown. In contrast, it performs an invalid operation
+(code ``0xfe``) if a runtime exception is encountered. In both cases, this causes
```
Comment (axic) [inline docs/control-structures.rst]: Maybe "performs an invalid operation (``0xfe`` instruction)" sounds a bit clearer?

File: libsolidity/codegen/ContractCompiler.cpp [hunk 6]
```diff
@@ -918,7 +918,9 @@ eth::AssemblyPointer ContractCompiler::cloneRuntime()
 	a << Instruction::DELEGATECALL;
 	//Propagate error condition (if DELEGATECALL pushes 0 on stack).
 	a << Instruction::ISZERO;
-	a.appendJumpI(a.errorTag());
+	a << Instruction::ISZERO;
+	eth::AssemblyItem afterTag = a.appendJumpI();
```
Comment (axic) [inline libsolidity/codegen/ContractCompiler.cpp]: Shouldn't this have a `.tag()`?

**Comment by axic** [comment]
It is missing an entry in the changelog.

File: libsolidity/codegen/ContractCompiler.cpp (hunk 6 above)
Comment (chriseth) [reply libsolidity/codegen/ContractCompiler.cpp]: Thanks!

**Comment by chriseth** [comment]
Updated.

File: libsolidity/codegen/ContractCompiler.cpp (hunk 6 above)
Comment (axic) [reply libsolidity/codegen/ContractCompiler.cpp]: I guess it didn't fail because we don't have a test for it?

**Comment by axic** [comment]
Is the idea for `catch` to insert `tags` for the jumps? If so, using `invalid` for non-user exceptions is the right way.

File: libsolidity/codegen/ContractCompiler.cpp (hunk 6 above)
Comment (chriseth) [reply libsolidity/codegen/ContractCompiler.cpp]: Yes, clone binaries are an undocumented and also mostly useless feature.

**Comment by chriseth** [comment]
@axic I don't think catch can really work in a consistent way (it has to roll back changes inside a single call), but if we do something like that, then `throw` will be changed from `jump(nonExistingTag)` to `jump(mload(mload(0x80)))` and catch will push an address onto the stack pointed to at address `0x80`.

File: libsolidity/codegen/ContractCompiler.cpp (hunk 6 above)
Comment (axic) [reply libsolidity/codegen/ContractCompiler.cpp]: Created an issue for that (#1618) so we can track.

**Review by axic — APPROVED** [review]

**Review by chriseth — APPROVED** [review]
