### PR TITLE
Fix bug in typechecking when comparing rational literals

### LINKED ISSUE #3796: Type checking for comparison operator with literal and int8 is not symmetric.
```
//pragma solidity 0.4.20;

contract test {
    function f() pure public {
        int8 x;
        if( x == 1) {} // OK
        if( 1 == x) {} // Compiler error
    }
}
```

### PR DESCRIPTION
**Pull request by randomnetcat**
Closes #3796.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1425,6 +1425,13 @@ void TypeChecker::endVisit(BinaryOperation const& _operation)
 	TypePointer const& leftType = type(_operation.leftExpression());
 	TypePointer const& rightType = type(_operation.rightExpression());
 	TypePointer commonType = leftType->binaryOperatorResult(_operation.getOperator(), rightType);
+	if (!commonType && leftType->category() == Type::Category::RationalNumber) {
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: If possible, I would prefer a solution inside `RationalNumberType::binaryOperatorResult`

**Comment by randomnetcat** [comment]
@chriseth Moved the logic into `RationalNumberType::binaryOperatorResult`.

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -830,7 +830,9 @@ TypePointer RationalNumberType::binaryOperatorResult(Token::Value _operator, Typ
 		auto mobile = mobileType();
 		if (!mobile)
 			return TypePointer();
-		return mobile->binaryOperatorResult(_operator, _other);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: This will fail for `x < 1` / `1 < x`. I think the proper fix could be to just replace the if body here by
```
		auto commonType = Type::commonType(shared_from_this(), _other);
		if (!commonType)
			return TypePointer();
		return commonType->binaryOperatorResult(_operator, _other);
```

Comment (chriseth) [reply libsolidity/ast/Types.cpp]: We use `Type::commonType` for many other implementations of `binaryOperatorResult`.

Comment (randomnetcat) [reply libsolidity/ast/Types.cpp]: Okay, I put that in. Tests passed on my end.

**Comment by randomnetcat** [comment]
@chriseth Took your suggestion. It made sense to me, and tests pass on my end.

**Comment by chriseth** [comment]
Please rebase, there is a conflict in the tests. Otherwise fine to merge!

**Comment by randomnetcat** [comment]
Rebased!

File: test/libsolidity/SolidityEndToEndTest.cpp [hunk 3]
```diff
@@ -11141,6 +11141,22 @@ BOOST_AUTO_TEST_CASE(swap_peephole_optimisation)
 	BOOST_CHECK(callContractFunction("div(uint256,uint256)", u256(0), u256(1)) == encodeArgs(u256(0)));
 }
 
+BOOST_AUTO_TEST_CASE(symmetric_literal_comparisons)
+{
+	char const* sourceCode = R"(
```
Comment (chriseth) [inline test/libsolidity/SolidityEndToEndTest.cpp]: Sorry, I only noticed this now, this should not be an EndToEndTest, since we check the syntax and not the semantics. Can you change this to a syntax test (in the new format)?

Comment (randomnetcat) [reply test/libsolidity/SolidityEndToEndTest.cpp]: Done

**Comment by randomnetcat** [comment]
@chriseth Can this be merged now?

File: test/libsolidity/syntaxTests/literal_comparisons.sol [hunk 4]
```diff
@@ -0,0 +1,10 @@
+contract test {
+    uint x = 2;
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/literal_comparisons.sol]: Sorry, but you need int8 here, this test did not fail before your change. Let me fix it, so that this can be finally merged.
