### PR TITLE
Fix shadowing struct types by struct member names

### LINKED ISSUE #9231: Struct member names can shadow type names within the struct
##  Description
The compiler allows struct members to have the same name as an existing struct, enum and contract type. This can cause some inconsistent behavior.

For example, this works perfectly fine (using enum as a member type):
```solidity
enum E {a, b, c}
struct T {E T;}
```

But this works too (using enum as a member name):
```solidity
enum E {a, b, c}
struct T {uint E;}
```

On the other hand, you can't do this (using both at the same time):
```solidity
enum E {a, b, c}
struct T {E T; uint E;}
```
```
Error: Name has to refer to a struct, enum or contract.
 --> test.sol:2:11:
  |
2 | struct T {E T; uint E;}
  |           ^
```
The error indicates that the compiler does not see `E` as an enum in this context.

I haven't found any buggy behavior related to this but having a member with the same name as a type might be confusing and might prevent you from using that type inside the struct in the future so I think it might be better not to allow it.

## Environment
- Compiler version: `develop` (>= 0.6.10)

### PR DESCRIPTION
**Pull request by a3d4**
Fixes #9231.

### CODE REVIEW

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 1]
```diff
@@ -174,6 +174,17 @@ void ReferencesResolver::endVisit(ModifierDefinition const&)
 void ReferencesResolver::endVisit(IdentifierPath const& _path)
 {
 	Declaration const* declaration = m_resolver.pathFromCurrentScope(_path.path());
```
Comment (hrkrshnn) [inline libsolidity/analysis/ReferencesResolver.cpp]: > I think we should first fix reference resolution inside a struct to not consider the members at all

Looking at the comment in the issue.

So shouldn't this be fixed inside `pathFromCurrentScope`?

File: libsolidity/analysis/NameAndTypeResolver.h [hunk 2]
```diff
@@ -87,6 +87,11 @@ class NameAndTypeResolver: private boost::noncopyable
 	/// Should only be called during the initial resolving phase.
 	std::vector<Declaration const*> nameFromCurrentScope(ASTString const& _name, bool _includeInvisibles = false) const;
 
+	/// Resolves a name in the "enclosing" scope, but also searches parent scopes.
```
Comment (bshastry) [inline libsolidity/analysis/NameAndTypeResolver.h]:
```suggestion
	/// Resolves a name in the enclosing or parent scopes.
```

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 3]
```diff
@@ -187,6 +187,19 @@ vector<Declaration const*> NameAndTypeResolver::nameFromCurrentScope(ASTString c
...
+{
+	DeclarationContainer const* enclosingContainer = m_currentScope->enclosingContainer();
+	if (!enclosingContainer)
+		return nullptr;
+
+	vector<Declaration const*> candidates = enclosingContainer->resolveName(_name, true);
+	if (candidates.size() == 1)
+		return candidates.front();
+	else
+		return nullptr;
```
Comment (bshastry) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: iiuc, there can be multiple `candidates.` Why is a `nullptr` returned when `candidates.size() > 1`

File: libsolidity/analysis/NameAndTypeResolver.h [hunk 4]
```diff
@@ -87,6 +87,11 @@ class NameAndTypeResolver: private boost::noncopyable
...
+	/// @returns a pointer to the declaration on success or nullptr on failure.
+	/// Should only be called during the initial resolving phase.
+	Declaration const* nameFromEnclosingScope(ASTString const& _name) const;
```
Comment (bshastry) [inline libsolidity/analysis/NameAndTypeResolver.h]: Since this method is actually returning a declaration, the name `nameFromEnclosingScope` is a bit misleading. How about `declarationFromEnclosingScope`?

File: test/libsolidity/syntaxTests/structs/member_type_eq_name.sol [hunk 5]
```diff
@@ -3,4 +3,4 @@ contract C {
   function f(function(S memory) external) public {}
 }
 // ----
-// TypeError 5172: (25-26): Name has to refer to a struct, enum or contract.
+// DeclarationError 7920: (25-26): Identifier not found or not unique.
```
Comment (bshastry) [inline test/libsolidity/syntaxTests/structs/member_type_eq_name.sol:6]: Isn't type error the correct error to output here?

File: test/libsolidity/syntaxTests/structs/member_type_eq_name_2.sol [hunk 6]
```diff
@@ -0,0 +1,6 @@
+contract C {
+    enum E {a, b, c}
+    struct S {E X; uint E;}
+    struct T {E T; uint E;}
+    struct U {E E;}
+}
```
Comment (bshastry) [inline test/libsolidity/syntaxTests/structs/member_type_eq_name_2.sol:6]: Should this test pass?

File: libsolidity/analysis/ReferencesResolver.cpp (hunk 1 above)
Comment (a3d4) [reply libsolidity/analysis/ReferencesResolver.cpp]: I am not sure, I would say that semantics is the same.

File: libsolidity/analysis/NameAndTypeResolver.h (hunk 2 above)
Comment (a3d4) [reply libsolidity/analysis/NameAndTypeResolver.h]: That sounds better for me too. However see other comments in the same header:
```
/// Resolves a name in the "current" scope, but also searches parent scopes.
/// Should only be called during the initial resolving phase.
std::vector<Declaration const*> nameFromCurrentScope(ASTString const& _name, bool _includeInvisibles = false) const;

/// Resolves a path starting from the "current" scope, but also searches parent scopes.
/// Should only be called during the initial resolving phase.
/// @note Returns a null pointer if any component in the path was not unique or not found.
Declaration const* pathFromCurrentScope(std::vector<ASTString> const& _path) const;
```

Should we change these comments altogether separately?

File: libsolidity/analysis/NameAndTypeResolver.cpp (hunk 3 above)
Comment (a3d4) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: Same as in `pathFromCurrentScope`, returning `nullptr` here indicates that identifier is not unique.

File: libsolidity/analysis/NameAndTypeResolver.h (hunk 4 above)
Comment (a3d4) [reply libsolidity/analysis/NameAndTypeResolver.h]: Completely agree, I was confused also. However that is how neighbor functions are called too: `nameFromCurrentScope`, `pathFromCurrentScope`. As with comments, we might want to change them synchronously.

File: test/libsolidity/syntaxTests/structs/member_type_eq_name.sol (hunk 5 above)
Comment (a3d4) [reply test/libsolidity/syntaxTests/structs/member_type_eq_name.sol:6]: Could be, but then it would be the only type error in `ReferencesResolver`.

File: test/libsolidity/syntaxTests/structs/member_type_eq_name_2.sol (hunk 6 above)
Comment (a3d4) [reply test/libsolidity/syntaxTests/structs/member_type_eq_name_2.sol:6]: According to my understanding, yes, because we allow struct members to have same names as types.

File: libsolidity/analysis/ReferencesResolver.cpp (hunk 1 above)
Comment (hrkrshnn) [reply libsolidity/analysis/ReferencesResolver.cpp]: Yeah. The only other use case seems to be for NatSpec, where `Struct` would not matter. So the semantics should be the same. But I think it's better to have the code for special case inside `pathFromCurrentScope`, in case `pathFromCurrentScope` needs to be used at a different place. What do you think?

Comment (a3d4) [reply libsolidity/analysis/ReferencesResolver.cpp]: I think it is a good idea, which also helps to reduce the amount of changes :).

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 7]
```diff
@@ -191,6 +191,21 @@ Declaration const* NameAndTypeResolver::pathFromCurrentScope(vector<ASTString> c
 {
 	solAssert(!_path.empty(), "");
 	vector<Declaration const*> candidates = m_currentScope->resolveName(_path.front(), true);
+
+	if (!candidates.empty() && candidates.front()->isStructMember())
+	{
+		// A special case like
+		// enum E {a}; struct S {E E;}
+		// We are within a struct scope and resolved name is a struct member name.
```
Comment (hrkrshnn) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: Maybe we can add an assert here about being inside struct scope?

Comment (a3d4) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: I did not find an easy way to check if we are within a struct scope (and that impacted my previous implementation).

I extended `DeclarationContainer` to provide that check, see https://github.com/ethereum/solidity/pull/10908/commits/085bede098e1c5123c778283ea1836343aba705f. Is it worth it?

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 8]
```diff
@@ -190,7 +190,23 @@ vector<Declaration const*> NameAndTypeResolver::nameFromCurrentScope(ASTString c
 Declaration const* NameAndTypeResolver::pathFromCurrentScope(vector<ASTString> const& _path) const
 {
 	solAssert(!_path.empty(), "");
-	vector<Declaration const*> candidates = m_currentScope->resolveName(_path.front(), true);
+	vector<Declaration const*> candidates;
+
+	bool isStructScope = dynamic_cast<StructDefinition const*>(m_currentScope->currentNode());
```
Comment (hrkrshnn) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: What would be the enclosing node here?

Comment (a3d4) [reply libsolidity/analysis/NameAndTypeResolver.cpp]: For the following contract
```
contract C {
    enum E {a}
    struct S {E X; uint E;}
}
```
if `isStructScope` is `true`, it would be `ContractDefinition`.

**Comment by chriseth** [comment]
This sounds like it is fixing a special case and a more general solution is possible. The issue at hand is that we do register a name that could shadow, but there is no code from which it could be accessed by that name. The same is true for a different but similar situation:
```
abstract contract C {
  function f(uint C) public pure;
}
```
as opposed to
```
contract C {
  function f(uint C) public pure {};
}
```
The second should create an error, the first does not have to. The same is true for event parameter names.

Are these two situations similar or not?

**Comment by a3d4** [comment]
@chriseth 

> The second should create an error, the first does not have to. 

Currently both samples produce the same warning:
> This declaration shadows an existing declaration.

```
Warning: This declaration shadows an existing declaration.
 --> d:/T/9231.sol:2:14:
  |
2 |   function f(uint C) public pure;
  |              ^^^^^^
Note: The shadowed declaration is here:
 --> d:/T/9231.sol:1:1:
  |
1 | abstract contract C {
  | ^ (Relevant source part starts here and spans across multiple lines).
```

```
Warning: This declaration shadows an existing declaration.
 --> d:/T/9231.sol:2:14:
  |
2 |   function f(uint C) public pure {}
  |              ^^^^^^
Note: The shadowed declaration is here:
 --> d:/T/9231.sol:1:1:
  |
1 | contract C {
  | ^ (Relevant source part starts here and spans across multiple lines).
```

> The same is true for event parameter names.

Do you mean something like this:
```
contract C {
  event e(uint C);
}
```
It compiles without the shadowing warning or error (which is fine I guess).

I'm having a closer look to see if we can have some unification.

**Comment by a3d4** [comment]
@chriseth
We can just handle parameters of abstract functions the same way as event parameters, see 4312277d9e9c622958765e4a283750ba408abf2b.

Or we can extend `Declaration` to indicate that certain names should not participate in the name lookup, see 31cc9959911a131e2f9fcc1d80d8161e1c1f167e.

**Comment by chriseth** [comment]
The solution looks good!

**Comment by leonardoalt** [comment]
The implemented or discussed solution?

**Comment by a3d4** [comment]
@chriseth

> All names are self-sufficient, but for some, there is no code that can refer to them, isn't it?

I would say that name is self-sufficient if it does not require any qualifier to identify to the corresponding entity :). 
But I agree, `isVisibleAsUnqualifiedName` sounds more precise.

**Comment by leonardoalt** [comment]
Is this ready for review again?

**Comment by a3d4** [comment]
@leonardoalt 

> Is this ready for review again?

Commits are not squashed and there is no changelog entry, but otherwise I believe it can be reviewed.

File: libsolidity/analysis/DeclarationContainer.cpp [hunk 9]
```diff
@@ -144,14 +140,28 @@ bool DeclarationContainer::registerDeclaration(
...
 	solAssert(!_name.empty(), "Attempt to resolve empty name.");
 	vector<Declaration const*> result;
+
+	auto filter = [&result, &_onlyVisibleAsUnqualifiedNames](vector<Declaration const*> _declarations) {
+		_onlyVisibleAsUnqualifiedNames ?
+			copy_if(_declarations.cbegin(), _declarations.cend(), back_inserter(result), [](auto& _declaration) {
+				return _declaration->isVisibleAsUnqualifiedName();
+			}) :
+			copy(_declarations.cbegin(), _declarations.cend(), back_inserter(result));
+	};
```
Comment (cameel) [inline libsolidity/analysis/DeclarationContainer.cpp]: Maybe this would be a bit nicer with ranges-v3.

File: libsolidity/analysis/DeclarationContainer.h [hunk 10]
```diff
@@ -40,11 +40,9 @@ class DeclarationContainer
...
 	using Homonyms = std::vector<std::pair<langutil::SourceLocation const*, std::vector<Declaration const*>>>;
 
-	explicit DeclarationContainer(
-		ASTNode const* _enclosingNode = nullptr,
-		DeclarationContainer* _enclosingContainer = nullptr
-	):
-		m_enclosingNode(_enclosingNode), m_enclosingContainer(_enclosingContainer)
+	DeclarationContainer() = default;
+	DeclarationContainer(ASTNode const* _enclosingNode, DeclarationContainer* _enclosingContainer, ASTNode const* _currentNode):
+		m_enclosingNode(_enclosingNode), m_enclosingContainer(_enclosingContainer), m_currentNode(_currentNode)
```
Comment (cameel) [inline libsolidity/analysis/DeclarationContainer.h]:
```suggestion
		m_enclosingNode(_enclosingNode),
		m_enclosingContainer(_enclosingContainer),
		m_currentNode(_currentNode)
```

File: libsolidity/analysis/DeclarationContainer.h [hunk 11]
```diff
@@ -58,9 +56,15 @@ class DeclarationContainer
...
-	std::vector<Declaration const*> resolveName(ASTString const& _name, bool _recursive = false, bool _alsoInvisible = false) const;
+	std::vector<Declaration const*> resolveName(
+		ASTString const& _name,
+		bool _recursive = false,
+		bool _alsoInvisible = false,
+		bool _onlyVisibleAsUnqualifiedNames = false
+	) const;
 	ASTNode const* enclosingNode() const { return m_enclosingNode; }
 	DeclarationContainer const* enclosingContainer() const { return m_enclosingContainer; }
+	ASTNode const* currentNode() const { return m_currentNode; }
```
Comment (cameel) [inline libsolidity/analysis/DeclarationContainer.h]: This seems unused.

File: libsolidity/ast/AST.h [hunk 12]
```diff
@@ -853,6 +859,7 @@ class FunctionDefinition: public CallableDeclaration, public StructurallyDocumen
 	Token kind() const { return m_kind; }
 	bool isPayable() const { return m_stateMutability == StateMutability::Payable; }
 	std::vector<ASTPointer<ModifierInvocation>> const& modifiers() const { return m_functionModifiers; }
+	bool hasBody() const { return m_body != nullptr; }
```
Comment (cameel) [inline libsolidity/ast/AST.h]: This seems unused.

File: libsolidity/ast/AST.cpp [hunk 13]
```diff
@@ -498,6 +498,18 @@ bool Declaration::isEventParameter() const
 	return dynamic_cast<EventDefinition const*>(scope());
 }
 
+bool Declaration::isVisibleAsUnqualifiedName() const
+{
+	if (!scope())
+		return true;
+	if (isStructMember() || isEnumValue() || isEventParameter())
```
Comment (cameel) [inline libsolidity/ast/AST.cpp]: After #10987 this should include custom error parameters as well.

We also need a test case covering events and errors.

File: libsolidity/ast/AST.h [hunk 14]
```diff
@@ -268,6 +268,12 @@ class Declaration: public ASTNode, public Scopable
 	/// @returns true if this is a declaration of a parameter of an event.
 	bool isEventParameter() const;
 
+	/// @returns true if the name can be used as is.
+	/// Usually the name alone can be used to refer to the corresponding entity.
+	/// But, for example, struct member names or enum member names require a prefix.
+	/// Another example is event parameter names, which do not participate in any proper scope.
+	bool isVisibleAsUnqualifiedName() const;
```
Comment (cameel) [inline libsolidity/ast/AST.h]: I think this should state more explicitly that `false` means that the name can **never** be used as is. Originally I wanted to comment that there must be something wrong here because this should depend on the scope where the name is used. Only after reading other comments I understood that this is meant only for cases where we know for certain. I.e. `true` really means that the name could be visible in some scope.

```suggestion
	/// @returns false if the declaration can never be referenced without being qualified with a scope.
	/// Usually the name alone can be used to refer to the corresponding entity.
	/// But, for example, struct member names or enum member names always require a prefix.
	/// Another example is event parameter names, which do not participate in any proper scope.
	bool isVisibleAsUnqualifiedName() const;
```

**Review by cameel — COMMENTED** [review]
The functionality looks finished to me, the PR just needs some final polish.

There are a some unused leftovers from previous iterations, commits are unsquashed and minor style tweaks are possible in a few places. It needs to be updated for custom errors and, as stated above, the changelog entry is missing. Also, it could use a few more test cases.

File: libsolidity/analysis/DeclarationContainer.cpp (hunk 9 above)
Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.cpp]: Done. Unfortunately ranges-v3 version is not as efficient as this (requires an extra copy) because we do not have `+=` overloaded for ranges and the range needs to be materialized.

File: libsolidity/analysis/DeclarationContainer.h (hunk 11 above)
Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.h]: Removed.

File: libsolidity/ast/AST.h (hunk 12 above)
Comment (cameel) [reply libsolidity/ast/AST.h]: Removed.

File: libsolidity/ast/AST.cpp (hunk 13 above)
Comment (cameel) [reply libsolidity/ast/AST.cpp]: Done. I have also added more tests.

**Comment by cameel** [comment]
Changelog, tweaks and extra tests added, commits squashed, PR rebased. This is now ready for the final review.

File: libsolidity/analysis/DeclarationContainer.cpp [hunk 15]
```diff
@@ -144,16 +143,35 @@ bool DeclarationContainer::registerDeclaration(
...
+) const
 {
 	solAssert(!_name.empty(), "Attempt to resolve empty name.");
 	vector<Declaration const*> result;
+
 	if (m_declarations.count(_name))
-		result = m_declarations.at(_name);
+	{
+		if (_onlyVisibleAsUnqualifiedNames)
+			result += ranges::to_vector(m_declarations.at(_name) | ranges::views::filter(&Declaration::isVisibleAsUnqualifiedName));
```
Comment (hrkrshnn) [inline libsolidity/analysis/DeclarationContainer.cpp]:
```suggestion
			result += m_declarations.at(_name) | ranges::views::filter(&Declaration::isVisibleAsUnqualifiedName) | ranges::to_vector;
```
?

File: libsolidity/analysis/DeclarationContainer.cpp [hunk 16]
```diff
@@ -144,16 +143,35 @@ bool DeclarationContainer::registerDeclaration(
...
+		else
+			result += m_declarations.at(_name);
+	}
+
 	if (_alsoInvisible && m_invisibleDeclarations.count(_name))
-		result += m_invisibleDeclarations.at(_name);
+	{
+		if (_onlyVisibleAsUnqualifiedNames)
+			result += ranges::to_vector(m_invisibleDeclarations.at(_name) | ranges::views::filter(&Declaration::isVisibleAsUnqualifiedName));
```
Comment (hrkrshnn) [inline libsolidity/analysis/DeclarationContainer.cpp]: Here as well.

File: test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol [hunk 17]
```diff
@@ -0,0 +1,12 @@
+contract C {
+    enum EnumType {A, B, C}
+
+    struct StructType {
+        uint x;
+    }
+
+    error E1(StructType StructType);
```
Comment (hrkrshnn) [inline test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol:8]: Can you perhaps add a semantic test where error is called using named arguments, i.e., `revert E1({StructType: StructType(5)})`?

File: Changelog.md [hunk 18]
```diff
@@ -10,6 +10,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * Name Resolver: Prevent member/parameter names from shadowing type names within struct/enum/error/event declarations.
```
Comment (bshastry) [inline Changelog.md]: Do we issue an error in case of shadowing? I'm trying to understand how we prevent shadowing, because users could still do it, right?

File: test/libsolidity/syntaxTests/enums/enum_member_shadowing.sol [hunk 19]
```diff
@@ -0,0 +1,12 @@
...
+        uint x;
+    }
+
+    enum E {E, S, C, a, f}
+
+    uint a;
+
+    function f() public pure {}
+}
+// ----
```
Comment (bshastry) [inline test/libsolidity/syntaxTests/enums/enum_member_shadowing.sol:12]: Shouldn't this issue a compiler error? Because enum member shadows type name?

File: test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol [hunk 20]
```diff
@@ -0,0 +1,12 @@
...
+    error E2(EnumType EnumType);
+    error E3(EnumType StrucType, StructType EnumType);
+}
+// ----
```
Comment (bshastry) [inline test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol:12]: Does this test pass as it is?

File: test/libsolidity/syntaxTests/scoping/name_shadowing_function_parameter_name_vs_contract.sol [hunk 21]
```diff
@@ -0,0 +1,20 @@
...
+    function f(uint I) external;         // OK
+}
+
+library L {
+    function f(uint L) public pure {}    // warning
+}
+
+abstract contract A {
+    function f(uint A) public pure {}    // warning
+    function g(uint A) public virtual;   // OK
```
Comment (bshastry) [inline test/libsolidity/syntaxTests/scoping/name_shadowing_function_parameter_name_vs_contract.sol:11]: Why is this "OK"? Shadowing still exists right?

File: Changelog.md (hunk 18 above)
Comment (cameel) [reply Changelog.md]: There's no error. That's the point of the PR. There are some examples in the original issue (#9231) that should make this clearer.

For example before this PR you would get an error here:
```solidity
enum E {a, b, c}
struct T {E T; uint E;}
```
```
Error: Name has to refer to a struct, enum or contract.
 --> test.sol:2:11:
  |
2 | struct T {E T; uint E;}
  |           ^
```

That's because the name checker thinks that `uint E` is shadowing the type `E` inside the body of the struct.

The PR changes that by making name checker aware that names defined in some kinds of scopes (struct declarations, enum declarations, function declarations without a body, event/error declarations) cannot shadow anything **inside that declaration**.

File: test/libsolidity/syntaxTests/enums/enum_member_shadowing.sol (hunk 19 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/enums/enum_member_shadowing.sol:12]: No, because shadowing is legal. It's only when you shadow type names used later within the same scope that it's an error:
```solidity
{
    Type1 Type2 = 1;
    Type2 x = 2;
}
```
You cannot do that in an enum. I added this test mostly for completeness.

File: test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol (hunk 20 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol:12]: It does. There's no ambiguity because you cannot define new types inside an error declaration. Allowing parameter names to shadow types would never lead to valid code so the PR makes name checker not consider them.

BTW, I just noticed a typo. `EnumType StrucType` should be `EnumType StructType`. But it should still pass with that if the PR is properly implemented.

File: test/libsolidity/syntaxTests/scoping/name_shadowing_function_parameter_name_vs_contract.sol (hunk 21 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/scoping/name_shadowing_function_parameter_name_vs_contract.sol:11]: See https://github.com/ethereum/solidity/pull/10908#issuecomment-781355831.

Having a parameter named like a type inside a function declaration that has no body cannot break anything so we do not consider that shadowing. It's clear what it's referring to. You don't want to warn about it and annoy the user. When there is a body, on the other hand, warning makes sense.

File: libsolidity/analysis/DeclarationContainer.h [hunk 22]
```diff
@@ -57,7 +56,12 @@ class DeclarationContainer
 	bool registerDeclaration(Declaration const& _declaration, ASTString const* _name, langutil::SourceLocation const* _location, bool _invisible, bool _update);
 	bool registerDeclaration(Declaration const& _declaration, bool _invisible, bool _update);
 
-	std::vector<Declaration const*> resolveName(ASTString const& _name, bool _recursive = false, bool _alsoInvisible = false) const;
+	std::vector<Declaration const*> resolveName(
+		ASTString const& _name,
+		bool _recursive = false,
+		bool _alsoInvisible = false,
+		bool _onlyVisibleAsUnqualifiedNames = false
+	) const;
```
Comment (hrkrshnn) [inline libsolidity/analysis/DeclarationContainer.h:72]: It would be nice to add a comment about the parameters. Also maybe something like `_onlyVisibleAsUnqualifiedNames` is applicable only to `UserDefinedTypeName` (is that true?)

File: libsolidity/analysis/DeclarationContainer.cpp (hunk 15 above)
Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.cpp]: Oh, just tried and looks like it works now. I'll change it.

I was changing it a lot and trying out various forms and I could not get it to work. But looks like it does work with the form I ended up using in the end.

File: libsolidity/analysis/DeclarationContainer.h (hunk 22 above)
Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.h:72]: Right. The function has no docstring. I'll add one.

> `_onlyVisibleAsUnqualifiedNames` is applicable only to `UserDefinedTypeName` (is that true?)

I think it's true unless we have built-in type names that are not keywords.
Well, I guess would not hurt to add a test that tries to shadow built-in names and to check that.

File: test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol (hunk 17 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol:8]: Test added. This works as expected.

File: libsolidity/analysis/DeclarationContainer.h (hunk 22 above)
Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.h:72]: Test added. All builtin types I could think of cause parser errors when used as parameter names.

File: test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol (hunk 20 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/errors/error_param_type_shadowed_by_param_name.sol:12]: Fixed.

File: Changelog.md (hunk 18 above)
Comment (a3d4) [reply Changelog.md]: @cameel 
> Prevent member/parameter names from shadowing type names within struct/enum/error/event declarations.

I think, strictly speaking, we do not _prevent shadowing_, we rather _prevent recognition of non-existing shadowing as shadowing_. Maybe

> Allow member/parameter names to be the same as type names within struct/enum/error/event declarations (avoid false name shadowing errors)

BTW, thanks a lot for taking care of the PR! (I still do hope to come back to the project for real eventually, even if right now it does not sound realistic.)

Comment (cameel) [reply Changelog.md]: Well, yeah, I get your point but I have a really hard time expressing this in a changelog entry without making it confusing to users or taking a whole paragraph :) This is the best I could come up with. If anyone has a better suggestion, I can replace it.

> BTW, thanks a lot for taking care of the PR! (I still do hope to come back to the project for real eventually, even if right now it does not sound realistic.)

Nice to heard that. I hope we'll get you back at some point :)

**Comment by cameel** [comment]
Just to summarize the current status: there were some review comments above but all have been addressed. The PR is finished and just waiting for an approve.

File: libsolidity/analysis/DeclarationContainer.h [hunk 23]
```diff
@@ -57,7 +56,21 @@ class DeclarationContainer
...
-	std::vector<Declaration const*> resolveName(ASTString const& _name, bool _recursive = false, bool _alsoInvisible = false) const;
+	/// Finds all declarations that in the current scope can be referred to using specified name.
+	/// @param _name the name to look for.
+	/// @param _recursive if true and there are no matching declarations in the current container,
+	///        recursively searches the enclosing containers as well.
+	/// @param _alsoInvisible if true, include invisible declaration in the results.
+	/// @param _onlyVisibleAsUnqualifiedNames if true, only include declarations which can be
+	///        referenced outside of the current scope without being qualified with the name of the
+	///        scope. I.e. when they shadow names in the enclosing scope(s). This option is **not**
+	///        passed to the enclosing scope when used together with @a _recursive.
```
Comment (hrkrshnn) [inline libsolidity/analysis/DeclarationContainer.h]: Do you think we should add an assert for `_recursive` and `_onlyVisibleAsUnqualifiedNames` both being true?

**Review by hrkrshnn — DISMISSED** [review]
Looks good. One minor comment, approving anyway.

File: libsolidity/analysis/DeclarationContainer.h (hunk 23 above)
Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.h]: I actually did that at first but the assertion fails :) We do call it with both being true and this is the expected behavior unfortunately.

Comment (hrkrshnn) [reply libsolidity/analysis/DeclarationContainer.h]: Is the comment here correct, then?

Comment (cameel) [reply libsolidity/analysis/DeclarationContainer.h]: Trying to answer your question pulled me down a rabbit hole today and I found a new problem with the PR. So it needs more work unfortunately :(

> Is the comment here correct, then?

Yes, it's correct in that respect because `resolveName()` does set `_onlyVisibleAsUnqualifiedNames` in the recursive call to `false`:
```c++
m_enclosingContainer->resolveName(_name, true, _alsoInvisible, false);
```
The only thing that the assert would change would be not having to document this case. But it turns out that this case does actually happen in practice.

But your comment made me think whether this is really the right behavior. And I think it's not so I changed it to propagate the value of the parameter. It's not a problem in practice though because I think it's not possible to trigger this case it with any currently allowed syntax. 

I tried to find a test case that would behave differently depending on whether we propagate `_onlyVisibleAsUnqualifiedNames` or not and I could not think of any. At first I thought this might be affected:
```solidity
contract C {
    enum E {a, b, c}
    struct S {function (E X) external f; uint E;}
}
```
Turns out it isn't. That's because apparently, unlike a function parameter list, the parameter list of a function type is not a scope. At least the `E` in `E X` is never checked for collision with `uint E`. Hypothetically though, if it was a scope, I think that `resolveName()` should not consider `uint E` from the outer scope a candidate - so `_onlyVisibleAsUnqualifiedNames` should be `true` when recursively visiting the outer scopes as well.

BTW, the comment wasn't really correct in another respect so I have rewritten it a bit.

**Comment by cameel** [comment]
I found a new case that is not covered by this PR. It's function parameters shadowing types of other parameters:

```solidity
contract C {
    enum EnumType1 {A, B, C}
    enum EnumType2 {A, B, C}

    function z(EnumType1 EnumType2) external returns (EnumType2 EnumType1) {}
}
```

This results in `Error: Name has to refer to a struct, enum or contract.`
This is the same problem this PR solves for structs but this time for function parameters. And unfortunately it does not nicely fit the `Declaration::isVisibleAsUnqualifiedName()` approach. That's because the function tells us if a declaration can never be referenced with name alone and this is not the case for functions that have a body.

To solve it I'd have to add a special case in `resolveName()` and that's what `isVisibleAsUnqualifiedName()` was supposed to let us avoid. So I'm not sure how to proceed here.

File: test/libsolidity/syntaxTests/scoping/name_shadowing_function_return_parameter_vs_struct_enum.sol [hunk 24]
```diff
@@ -0,0 +1,20 @@
...
+
+    function z(uint EnumType) external returns (EnumType e) {}
+}
+// ----
+// Warning 2519: (124-152): This declaration shadows an existing declaration.
+// Warning 2519: (192-209): This declaration shadows an existing declaration.
+// Warning 2519: (249-268): This declaration shadows an existing declaration.
+// Warning 2519: (270-296): This declaration shadows an existing declaration.
+// Warning 2519: (317-330): This declaration shadows an existing declaration.
+// TypeError 5172: (124-134): Name has to refer to a struct, enum or contract.
```
Comment (cameel) [inline test/libsolidity/syntaxTests/scoping/name_shadowing_function_return_parameter_vs_struct_enum.sol:20]: This `TypeError` is what I'm referring to in https://github.com/ethereum/solidity/pull/10908#issuecomment-838725246.

**Comment by cameel** [comment]
We discussed it today and the prevailing opinion was that for functions with a body we do want the shadowing to be disallowed. So the behavior that I caught in https://github.com/ethereum/solidity/pull/10908#issuecomment-838725246 is correct.

As such, this PR is ready for another review. I added new test cases and did some minor reformatting but the only significant change after the last approve from @hrkrshnn was the one mentioned in https://github.com/ethereum/solidity/pull/10908#discussion_r630292453.

**Comment by cameel** [comment]
Here's a snippet that summarizes the current state of the PR. Errors/warnings in each case before and after the PR:

```solidity
enum EnumType {A, B, C}

contract C {
    // struct, event, error
    //
    // BEFORE: Error: Name has to refer to a struct, enum or contract.
    //
    // AFTER: OK
    struct S {uint EnumType; EnumType x;}
    error Ev(uint EnumType, EnumType x);
    event Er(uint EnumType, EnumType x);

    // function with a body
    //
    // BEFORE: Warning: This declaration shadows an existing declaration.
    // BEFORE: Error: Name has to refer to a struct, enum or contract.
    //
    // AFTER: Warning: This declaration shadows an existing declaration.
    // AFTER: Error: Name has to refer to a struct, enum or contract.
    function f(uint EnumType, EnumType x) external {}

    // function without a body
    //
    // BEFORE: Warning: This declaration shadows an existing declaration.
    // BEFORE: Error: Name has to refer to a struct, enum or contract.
    //
    // AFTER: OK
    function g(uint EnumType, EnumType x) external virtual;

    // function type with named parameters
    //
    // BEFORE: Warning: Naming function type parameters is deprecated.
    // BEFORE: Warning: This declaration shadows an existing declaration.
    //
    // AFTER:  Warning: Naming function type parameters is deprecated.
    // AFTER:  Warning: This declaration shadows an existing declaration.
    function (uint EnumType, EnumType x) external h;
}

// contract
//
// BEFORE: Warning: This declaration shadows an existing declaration.
// BEFORE: Error: Name has to refer to a struct, enum or contract.
//
// AFTER:  Warning: This declaration shadows an existing declaration.
// AFTER:  Error: Name has to refer to a struct, enum or contract.
contract A {uint EnumType; EnumType x;}
```

**Comment by chriseth** [comment]
About the specific example of
```solidity
contract C {
    enum EnumType1 {A, B, C}
    enum EnumType2 {A, B, C}

    function z(EnumType1 EnumType2) external returns (EnumType2 EnumType1) {}
}
```
This should be an error as long as we have `{}` instead of `;`, because functions with empty body can have modifiers, while function without implementation cannot have modifiers. This is important because we said that shadowing is not a problem as long as there is no code the shadowing can cover. Modifier invocations are code that are inside the scope of the function, i.e. the parameters are visible in the modifier invocation.

**Comment by cameel** [comment]
> This should be an error as long as we have `{}` instead of `;`,

OK. That's exactly what happens:

``` solidity
contract C {
    enum EnumType1 {A, B, C}
    enum EnumType2 {A, B, C}

    // BEFORE: Warning: This declaration shadows an existing declaration.
    // BEFORE: Error: Name has to refer to a struct, enum or contract.
    //
    // AFTER:  Warning: This declaration shadows an existing declaration.
    // AFTER:  Error: Name has to refer to a struct, enum or contract. 
    function z1(EnumType1 EnumType2) external returns (EnumType2 EnumType1) {}

    // BEFORE: Warning: This declaration shadows an existing declaration.
    // BEFORE: Error: Name has to refer to a struct, enum or contract.
    //
    // AFTER:  OK 
    function z2(EnumType1 EnumType2) external virtual returns (EnumType2 EnumType1);
}
```

> Modifier invocations are code that are inside the scope of the function, i.e. the parameters are visible in the modifier invocation.

I just checked and looks like it's possible to shadow the type name inside modifier invocation. You do at least get a warning if the shadowing happens though. This case is unaffected by the PR (works the same before and after):

```solidity
enum EnumType {A, B, C}
struct StructType {uint x;}

contract C {
    modifier ms(StructType memory s) { _; }
    modifier mi(uint i) { _; }

    // Warning: This declaration shadows an existing declaration.
    function f(uint EnumType) mi(EnumType) external {}

    // OK
    function g(uint x) ms(StructType(x)) external {}

    // Warning: This declaration shadows an existing declaration.
    // Error: Type is not callable
    function h1(uint StructType) ms(StructType(StructType)) external {}

    // Warning: This declaration shadows an existing declaration.
    function h2(uint StructType) external {
        // Error: Type is not callable
        StructType(StructType);
    }
}
```

The last situation (functions `h1()` and `h2()`) is in line with what I would expect, i.e. you cannot use the struct type because it is shadowed, but the error message is wrong. The type is callable, it's just not the type that is being used.

**Comment by chriseth** [comment]
I assume "Type is not callable" refers to
```
ms(StructType(StructType))
   ^^^^^^^^^^
```
and I don't see why the error is wrong. `StructType` resolves to the name of the variable, and since the variable is not of function type, you cannot call it.

**Comment by cameel** [comment]
I said it's wrong because `StructType` is not a type if it resolves to the name of a variable. It should just say that it's not callable. Or was it meant to say that the type of `StructType` is not callable?

Still, it's mostly a cosmetic issue and not affected by the PR. Are all the other errors/warnings I listed working as they should?

**Comment by chriseth** [comment]
It could say "type of the expression is not callable" (if `StructType` were a variable of function type, it would work). I think everything is fine now.

**Review by chriseth — APPROVED** [review]
