### PR TITLE
[SMTChecker] Fix conversion from bytes to fixed bytes

### LINKED ISSUE #11389: [SMTChecker] SMT logic error during analysis in static solidity::smtutil::Expression solidity::smtutil::Expression::int2bv(solidity::smtutil::Expression, size_t)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function fromSlice(bytes calldata c) external returns (bytes8) {
        return bytes8(c[1:9]);
    }
}
```

produces:

```
SMT logic error during analysis:
/solidity/libsmtutil/SolverInterface.h(212): Throw in function static solidity::smtutil::Expression solidity::smtutil::Expression::int2bv(solidity::smtutil::Expression, size_t)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

## Environment

- Compiler version:  0.8.5-develop.2021.5.13+commit.98e2b4e5.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### LINKED ISSUE #11404: [SMTChecker] SMT logic error in solidity::smtutil::Expression solidity::smtutil::operator==(solidity::smtutil::Expression, solidity::smtutil::Expression)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function fromSlice(bytes calldata c) external returns (bytes32) {
        return bytes32(c[0:33]);
    }
}
```

produces:

```
SMT logic error during analysis:
/solidity/libsmtutil/SolverInterface.h(262): Throw in function solidity::smtutil::Expression solidity::smtutil::operator==(solidity::smtutil::Expression, solidity::smtutil::Expression)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Trying to create an 'equal' expression with different sorts
[solidity::util::tag_comment*] = Trying to create an 'equal' expression with different sorts
```

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer, now with a few more mutation operators

This is quite similar to #11389 but with a different failure symptom for the different size for some reason.

## Environment

- Compiler version:  0.8.5-develop.2021.5.17+commit.21af5408.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/11389
Fixes https://github.com/ethereum/solidity/issues/11404

Depends on https://github.com/ethereum/solidity/pull/11467

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -1022,6 +1022,17 @@ void SMTEncoder::visitTypeConversion(FunctionCall const& _funCall)
...
+		arrayType = &sliceType->arrayType();
+
+	if (arrayType && arrayType->isByteArray() && smt::isFixedBytes(*funCallType))
+	{
+		auto array = dynamic_pointer_cast<smt::SymbolicArrayVariable>(m_context.expression(*argument));
+		bytesToFixedBytesAssertions(*array, _funCall);
+		return;
+	}
+
 	// TODO Simplify this whole thing for 0.8.0 where weird casts are disallowed.
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp:1036]: :point_up:

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1036]: Yep
