### PR TITLE
[SMTChecker] Fix virtual modifier called statically

### LINKED ISSUE #10660: [SMTChecker] ICE in void solidity::frontend::SMTEncoder::visitFunctionOrModifier()
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract A {
    modifier m virtual {
      _;
    }
}
contract C is A {
    function f() public A.m returns (uint) {
    }
}
```

produces:

```
Internal compiler error during compilation:
/solidity/libsolidity/formal/SMTEncoder.cpp(212): Throw in function void solidity::frontend::SMTEncoder::visitFunctionOrModifier()
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.1-develop.2020.12.18+commit.72efdd3e.mod.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by blishko**
Fixes #10660.

This is a fix for a recent PR #10597.
Virtual modifiers require virtual resolution when they are called directly, using only the name: `m`.
However, when the name is qualified, using concrete contract type, the call is actually static: `A.m`.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -2688,11 +2690,14 @@ vector<VariableDeclaration const*> SMTEncoder::modifiersVariables(FunctionDefini
 
 		visited.insert(modifier);
 		solAssert(_contract, "No contract context provided for modifier analysis!");
-		auto const& actualModifier = modifier->resolveVirtual(*_contract);
-		if (actualModifier.isImplemented())
+		VirtualLookup lookup = *invok->name().annotation().requiredLookup;
+		solAssert(lookup == VirtualLookup::Virtual || lookup == VirtualLookup::Static, "");
+		if (lookup == VirtualLookup::Virtual)
+			modifier = &modifier->resolveVirtual(*_contract);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]: I think it's worth extracting the 4 lines above into a function, and reuse that also in the other modified code.

**Comment by leonardoalt** [comment]
Ah, I think we should also add a Changelog entry since the bug made the release.

**Comment by blishko** [comment]
> Ah, I think we should also add a Changelog entry since the bug made the release.

Actually, no, the PR that introduced this bug was merged after the release.

**Comment by leonardoalt** [comment]
Ok, then just the function extraction.

**Review by leonardoalt — APPROVED** [review]
