### PR TITLE
YulInterpreter: Call functions with the correct context

### LINKED ISSUE #7148: [yul] interpreter fails assertion because of incorrectly erased shadowed variable?
## Description

Found by ossfuzz: issue 16063

```
{function mr(){let r}{{mr()}function r(){}}}
```

fails 

https://github.com/ethereum/solidity/blob/00accd9daab8acf1e0bd2b0f32af1f2e4ed02d38/test/tools/yulInterpreter/Interpreter.cpp#L200

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): petersburg

## Steps to Reproduce

```
$ yulrun --input-file <code.yul>
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<langutil::InternalCompilerError>'
  what():  
Aborted (core dumped)
```

Could be a regression of #6446

### PR DESCRIPTION
**Pull request by Marenz**
fixes #7148

### CODE REVIEW

**Comment by Marenz** [comment]
still adding tests for this

File: test/tools/yulInterpreter/Interpreter.h [hunk 1]
```diff
@@ -96,6 +96,13 @@ struct InterpreterState
 	void dumpTraceAndState(std::ostream& _out) const;
 };
 
+/// Contains a function definition and the required context to call it
+struct FunctionContext
+{
+	std::map<YulString, FunctionContext> m_functions;
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.h]: You probably mean `FunctionDefinition const*` here, right?

Comment (Marenz) [reply test/tools/yulInterpreter/Interpreter.h]: Hmm no. If it would be `FunctionDefinition const*` then the called function would be missing the context again to call another function

**Comment by Marenz** [comment]
I found a few problems still with this, changing it to WIP

File: test/tools/yulInterpreter/Interpreter.h (hunk 1 above)
Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.h]: What looks suspicious here is that you store `FunctionContext` by value. This should produce an infinite data structure for the following code:
```
{
function f() {}
function g() {}
}
```

Since functions that are callable from the current context are always in the current scope or a parent scope, it should be enough to maintain a stack of scopes (we already have that) and just provide the list of visible functions as an initial segment of that stack, ending with the scope the function has been defined in.

**Comment by Marenz** [comment]
This is now ready.

File: test/tools/yulInterpreter/Interpreter.cpp [hunk 2]
```diff
@@ -246,9 +248,21 @@ void ExpressionEvaluator::operator()(FunctionCall const& _funCall)
 	for (size_t i = 0; i < fun.returnVariables.size(); ++i)
 		variables[fun.returnVariables.at(i).name] = 0;
 
+	std::map<YulString, FunctionDefinition const*> context;
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.cpp]:
```suggestion
	std::map<YulString, FunctionDefinition const*> visibleFunctions;
```

File: test/tools/yulInterpreter/Interpreter.cpp [hunk 3]
```diff
@@ -246,9 +248,21 @@ void ExpressionEvaluator::operator()(FunctionCall const& _funCall)
...
+
+	for (auto const& scope: m_scopes)
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.cpp]: Maybe extract this into its own function?

File: test/tools/yulInterpreter/Interpreter.h [hunk 4]
```diff
@@ -96,6 +96,12 @@ struct InterpreterState
 	void dumpTraceAndState(std::ostream& _out) const;
 };
 
+struct Scope
+{
+	std::map<YulString, FunctionDefinition const*> m_functions;
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.h]: No `m_` prefix for public struct members.

File: test/tools/yulInterpreter/Interpreter.h [hunk 5]
```diff
@@ -96,6 +96,12 @@ struct InterpreterState
 	void dumpTraceAndState(std::ostream& _out) const;
 };
 
+struct Scope
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.h]: It is a rather generic name, is it a big amount of work to move it inside the interpreter class?

File: test/tools/yulInterpreter/Interpreter.h (hunk 4 above)
Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.h]: Can you use `std::set<YulString>` here?

Comment (Marenz) [reply test/tools/yulInterpreter/Interpreter.h]: I need the definition to pass it to the `Interpreter` instance that we create

File: test/tools/yulInterpreter/Interpreter.h [hunk 6]
```diff
@@ -102,6 +102,12 @@ struct InterpreterState
 class Interpreter: public ASTWalker
 {
 public:
+	struct Scope
+	{
+		std::map<YulString, FunctionDefinition const*> visibleFunctions;
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.h]: Here, it should not be `visibleFunctions`, because also the functions in higher scopes are visible.

File: test/tools/yulInterpreter/Interpreter.h (hunk 4 above)
Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.h]: I'm just wondering because this is more or less duplicated in the `m_functions` member of the interpreter.

Comment (chriseth) [reply test/tools/yulInterpreter/Interpreter.h]: So maybe that member can be removed?

**Comment by Marenz** [comment]
Updatero

File: test/tools/yulInterpreter/Interpreter.h [hunk 7]
```diff
@@ -184,12 +192,14 @@ class ExpressionEvaluator: public ASTWalker
 	/// stores it in m_value.
 	void evaluateArgs(std::vector<Expression> const& _expr);
 
+	std::map<YulString, FunctionDefinition const*> visibleFunctionsFor(YulString const& _name);
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.h:190]: Please document and add newline below.

File: test/tools/yulInterpreter/Interpreter.h [hunk 8]
```diff
@@ -102,6 +102,12 @@ struct InterpreterState
 class Interpreter: public ASTWalker
 {
 public:
+	struct Scope
+	{
+		std::map<YulString, FunctionDefinition const*> functions;
```
Comment (chriseth) [inline test/tools/yulInterpreter/Interpreter.h]: It is probably possible to remove this member (and thus also replace the struct by the symbol set below) and use `m_functions` for the lookup inside `ExpressionEvaluator::visibleFunctionsFor`.

**Comment by Marenz** [comment]
Updated

**Review by chriseth — APPROVED** [review]
