### PR TITLE
[Sol->Yul] Implementing bytes copying from calldata to memory.

### LINKED ISSUE #8844: [Sol->Yul] Calldata to memory copying is not supported in the IR
```
contract C {
  function f(bytes calldata data) external returns (bytes32) {
    return keccak256(bytes(data[:32]));
  }
}
```

results in

```
Unimplemented feature:
/Users/alex/Projects/solidity/libsolidity/codegen/YulUtilFunctions.cpp(2135): Throw in function auto solidity::frontend::YulUtilFunctions::conversionFunctionSpecial(const solidity::frontend::Type &, const solidity::frontend::Type &)::(anonymous class)::operator()() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Type conversion bytes calldata -> bytes memory not yet implemented.
[solidity::util::tag_comment*] = Type conversion bytes calldata -> bytes memory not yet implemented.
bash-3.2$ less abislice.sol 
```

With #8799 :
```
contract C {
  function f(bytes calldata data) external returns (bytes memory) {
    return abi.encode(bytes(data[:32]));
  }
}
```

results in

```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/ir/IRVariable.cpp(92): Throw in function std::__1::string solidity::frontend::IRVariable::name() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

### PR DESCRIPTION
**Pull request by mijovic**
Fixes #8844

### CODE REVIEW

**Review by Marenz — DISMISSED** [review]
LGTM

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 1]
```diff
@@ -2412,6 +2412,29 @@ string YulUtilFunctions::conversionFunctionSpecial(Type const& _from, Type const
 			.render();
 		}
 
+		if (_from.category() == Type::Category::Array && _to.category() == Type::Category::Array)
+		{
+			auto const& fromArrayType = dynamic_cast<ArrayType const&>(_from);
+			auto const& toArrayType = dynamic_cast<ArrayType const&>(_to);
+
+			solAssert(!fromArrayType.baseType()->isDynamicallyEncoded(), "");
+			solAssert(fromArrayType.isByteArray() && toArrayType.isByteArray(), "");
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Shouldn't this be an unimplementedassert?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: (and all other assertions that follow, too?)

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 2]
```diff
@@ -2412,6 +2412,29 @@ string YulUtilFunctions::conversionFunctionSpecial(Type const& _from, Type const
...
+			solAssert(toArrayType.location() == DataLocation::Memory, "");
+			solAssert(fromArrayType.location() == DataLocation::CallData, "");
+			solAssert(toArrayType.isDynamicallySized(), "");
+
+			Whiskers templ(R"(
+				function <functionName>(offset, length) -> converted {
+					converted := <allocateMemoryArray>(length)
+					<copyToMemory>(offset, add(converted, 0x20), length)
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:2423]:
```
	/// @returns a function that copies raw bytes of dynamic length from calldata
	/// or memory to memory.
	/// Pads with zeros and might write more than exactly length.
	std::string copyToMemoryFunction(bool _fromCalldata);
```

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2423]: Ah, I see that it actually is fine - the array allocation function allocates enough.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 3]
```diff
@@ -2412,6 +2412,29 @@ string YulUtilFunctions::conversionFunctionSpecial(Type const& _from, Type const
...
+				}
+			)");
+			templ("functionName", functionName);
+			templ("allocateMemoryArray", allocateMemoryArrayFunction(toArrayType));
+			templ("copyToMemory", copyToMemoryFunction(fromArrayType.location() == DataLocation::CallData));
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp:2428]: it should be an assertion that from is calldata - otherwise there is nothing to convert.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2423]: Rounding up does not help, but I think we can assume that we can write past the end here because it is freshly allocated.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp:2428]: There is assertion just before constructing Whiskers, I think it should be fine.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 1 above)
Comment (mijovic) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Indeed, changed now

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 3 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:2428]: ok!

**Review by chriseth — APPROVED** [review]
