### PR TITLE
Fix ICE in IR when a library is bound to a literal

### LINKED ISSUE #11325: [Sol->Yul] ICE due to library function bound to a literal
```
library L{
  function f(uint) external {}
}

contract C {
  using L for *;
  function g() public {
    8.f();
  }
}
```

throws

https://github.com/ethereum/solidity/blob/5c02837485b8bae0a484ec1e1490851fae264417/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L1588-L1599

```
$ solc --experimental-via-ir test.sol
```

### PR DESCRIPTION
**Pull request by cameel**
Fixes #11325.

Removing the assertion checking supported types was enough to fix it.
- The list of types was incomplete - there is a way to bind a function to a literal.
- The assertion was meant to guard against silently skipping over types for which there is no handling implemented yet. The current code handles everything in a generic way though and likely will not have to be adjusted for newly added types so the risk of that happening is low.

### CODE REVIEW

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -1576,19 +1576,6 @@ void IRGeneratorForStatements::endVisit(MemberAccess const& _memberAccess)
...
-			Type::Category::Bool,
-			Type::Category::Integer,
-			Type::Category::Address,
-			Type::Category::Function,
-			Type::Category::Struct,
-			Type::Category::Enum,
-			Type::Category::Mapping,
-			Type::Category::Array,
-			Type::Category::FixedBytes,
-		}).count(objectCategory) > 0, "");
```
Comment (hrkrshnn) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1590]: Wouldn't it be better to add the type `Type::Category::RationalNumber` and `StringLiteral` to the list?

Can the others be also be "bound"?

Comment (cameel) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1590]: I'm a bit conflicted about it. I can restore it if you think it is useful after all.

I think the assert was overly cautious because this should really handle every type in the same way:
```c++
define(IRVariable(_memberAccess).part("self"), _memberAccess.expression());
```

Back when I added it, I knew much less about IR implementation and I was not sure if the implementation would handle  anything except the types I managed to cover with test cases.

> Can the others be also be "bound"?

I think they can't but I can't be 100% sure. I did extensive testing back when I implemented it and the literals still managed to slip through.

For example there might be a way to bind array slices. Are slices implicitly convertible to array types? I did quick testing and it looks like they can't and I did not find any test cases for this. But if they can, that would be another case where the assert was wrong.

**Review by chriseth — APPROVED** [review]
