### PR TITLE
Fixes #5052 (very large hex literals wrongly interpreted)

### LINKED ISSUE #5052: Hex literal erroneously handled as >32 FixedBytes type
Found by solfuzzer.

```
contract HexEncoding {
  function hexEncodeTest(address addr) public returns (bytes32 ret) {
    uint x = uint(addr) / 2**32;

    // Nibble interleave
    x = (x | ()) & 0x0000_fff0000ffff0ffffffff00000000ffffffff00000000ffffffff00000000ffffffff;
  }
}
```

The error:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/ast/Types.cpp(1413): Throw in function dev::solidity::FixedBytesType::FixedBytesType(unsigned int)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Invalid byte number for fixed bytes type: 36
[dev::tag_comment*] = Invalid byte number for fixed bytes type: 36
```

It seems to be introduced with #4684.

### PR DESCRIPTION
**Pull request by christianparpart**
Fixes #5052.

## BEAWARE !!!

This PR is rebased on top of #5125 to make use of the new `Literal::valueWithoutUnderscores()`.

### Description

This PR fixes the compiler error caused by too large hexadecimal literals (NB: regardless of whether or not underscores have been used as separators).

I'm not sure that code change is worth a changelog entry (?).

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -841,13 +841,14 @@ TypePointer RationalNumberType::forLiteral(Literal const& _literal)
...
 			size_t digitCount = count_if(
-				_literal.value().begin() + 2, // skip "0x"
-				_literal.value().end(),
+				valueString.begin() + 2, // skip "0x"
+				valueString.end(),
 				[](unsigned char _c) -> bool { return isxdigit(_c); }
 			);
 			// require even number of digits
-			if (!(digitCount & 1))
+			if (!(digitCount & 1) && (digitCount / 2) <= 32)
```
Comment (leonardoalt) [inline libsolidity/ast/Types.cpp]: Why not `digitCount <= 64`?

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -841,13 +841,14 @@ TypePointer RationalNumberType::forLiteral(Literal const& _literal)
 		TypePointer compatibleBytesType;
 		if (_literal.isHexNumber())
 		{
+			ASTString const valueString = _literal.valueWithoutUnderscores();
 			size_t digitCount = count_if(
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Why is this still needed?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (christianparpart) [reply libsolidity/ast/Types.cpp]: I wanted to preserve the "requirement" on when entering this condition is allowed (32 bytes), I feel like this is more intuitive to understand, more unlikely to be misunderstood.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (christianparpart) [reply libsolidity/ast/Types.cpp]: Well, we're catching two bugs here. First (a few lines below, the original report), where too large literals where wrongly getting the type FixedBytes-type with byte-count > 32), and secondly that the counting is wrong if we don't strip the underscores from the literal.

Comment (chriseth) [reply libsolidity/ast/Types.cpp]: But we DO strip the underscores, so no need to count in such a way, just `digitCount = valueString.length() - 2` should be enough, shouldn't it?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp]: Concerning "intuitive" - I think the first part of the check is easier to understand using `digitCount % 2 == 0`

File: test/libsolidity/syntaxTests/types/rational_number_huge.sol [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+        y = 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff00000000; // FixedBytes (32)
+        // one byte too long for storing in Fixedbytes (would require 33 bytes, should still work)
+        y = 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff000000001;
+
+        // fits exactly into FixedBytes (32), ensures underscored literals won't hurt
+        y = 0xffffffff00000000ffffffff00000000ffffffff00000000ffffffff_00000000;
+    }
+}
+// ----
+// TypeError: (309-376): Type int_const 1852...(71 digits omitted)...7281 is not implicitly convertible to expected type uint256.
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/types/rational_number_huge.sol]: Can you extract the failing case into its own file?

File: libsolidity/ast/Types.cpp (hunk 1 above)
Comment (christianparpart) [reply libsolidity/ast/Types.cpp]: haha. nice catch. I totally agree!

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (christianparpart) [reply libsolidity/ast/Types.cpp]: ah! okay, now I get you. you are right indeed.

File: test/libsolidity/syntaxTests/types/rational_number_huge_fail.sol [hunk 4]
```diff
@@ -0,0 +1,8 @@
+contract C {
+    function f(uint y) public pure {
+        // one byte too long for storing in Fixedbytes (would require 33 bytes, should still work)
```
Comment (leonardoalt) [inline test/libsolidity/syntaxTests/types/rational_number_huge_fail.sol]: What do you mean here with `should still work`?

**Comment by chriseth** [comment]
Removed the comment.

**Review by chriseth — APPROVED** [review]
