### PR TITLE
error out if no output artifacts are requested.

### LINKED ISSUE #4494: Solc should output something if no output is selected
From the zeppelin audit:

If no output format is specified (those listed under “Output Components” by solc --help), solc will not do any sort of output, but also won’t issue any warnings or notices. This behaviour is confusing, and makes it difficult for new users to understand why their invocation is failing.
Consider either adding a message when no output format is selected, or selecting one (e.g. binary) by default.

--

We should add a message like `Source files are valid, but no output requested.`

### PR DESCRIPTION
**Pull request by liangdzou**
### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] Used meaningful commit messages

### Description

Error out when there is no output requirement detected from the options.

Fixes #4494

### CODE REVIEW

**Comment by liangdzou** [comment]
@ekpyron Do we have option parsing test now? Where should I add the test case?

**Comment by liangdzou** [comment]
> @ekpyron Do we have option parsing test now? Where should I add the test case?

I found it in cmdlineTests.sh. Thx :-)

**Comment by chriseth** [comment]
In an earlier try to solve this issue, we concluded that deciding whether to output this just depending on the commandline options is too error-prone. Instead, we thought that it might be better to add a function that returns `std::cout` and sets an internal flag to `true`. If the flag is false at the end, we output the message.

**Comment by liangdzou** [comment]
@chriseth 
Then, if we check the result at the end, the file will be already compiled no matter we will print the warning or not. Is that ok?

File: solc/CommandLineInterface.cpp [hunk 1]
```diff
@@ -61,6 +61,9 @@
 #include <iostream>
 #include <fstream>
 
+bool g_HasOutputed = false;
+#define cout (g_HasOutputed = true, cout)
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Please use a proper function instead.

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -1231,6 +1234,25 @@ void CommandLineInterface::outputCompilationResults()
 		handleNatspec(true, contract);
 		handleNatspec(false, contract);
 	} // end of contracts iteration
+
+	if (!g_HasOutputed &&
+			!m_args.count(g_argAst) &&
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Why do we still need those?

Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: Some information is not printed on screen when -o is given.

**Comment by ekpyron** [comment]
This will now output ``Source files are valid, but no output requested.``, even if there is also a warning. Arguably, that could be fine (I'm undecided myself), but earlier we noted that we probable don't want that (see https://github.com/ethereum/solidity/pull/4525#issuecomment-412929008)...

**Comment by liangdzou** [comment]
> This will now output `Source files are valid, but no output requested.`, even if there is also a warning. Arguably, that could be fine (I'm undecided myself), but earlier we noted that we probable don't want that (see [#4525 (comment)](https://github.com/ethereum/solidity/pull/4525#issuecomment-412929008))...

yeah, but it is very error-prone if error out without compiling the file, e.g. print out gas estimation should not require an output.

File: solc/CommandLineInterface.cpp (hunk 1 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: will do soon.

**Comment by chriseth** [comment]
The purpose of this message is to tell the user that something happened if no other message is printed, so I think we should not output the message if there are warnings.

**Comment by liangdzou** [comment]
> The purpose of this message is to tell the user that something happened if no other message is printed, so I think we should not output the message if there are warnings.

does that mean we also need to record for cerr?

**Comment by chriseth** [comment]
Yes.

File: solc/CommandLineInterface.cpp [hunk 3]
```diff
@@ -61,12 +61,15 @@
...
 #include <fstream>
 
-bool g_HasOutputed = false;
-#define cout (g_HasOutputed = true, cout)
-
 using namespace std;
 namespace po = boost::program_options;
 
+bool g_hasOutputed = false;
+std::ostream& Out() {
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Should start with a lowercase letter.

**Comment by liangdzou** [comment]
Shall I ignore pre-released version warning since it will always print for pre-release version?
By the way, shall I do something for lllc?

**Comment by chriseth** [comment]
I think you don't have to handle the prerelease warning specially. lllc can be ignored.

File: solc/CommandLineInterface.cpp (hunk 3 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: lowercase conflict with local variables. I will try some other name with lower case.

**Comment by liangdzou** [comment]
Really, the warning message may not be able to work in pre-release version.
Actually, this can be done easily by record the bool before print and recover after print the string.

**Comment by liangdzou** [comment]
> I think you don't have to handle the prerelease warning specially. lllc can be ignored.

Also, this will make the test will hard to write for both released and pre-released version.

File: solc/CommandLineInterface.cpp [hunk 4]
```diff
@@ -812,7 +822,7 @@ bool CommandLineInterface::processInput()
 	m_compiler.reset(new CompilerStack(fileReader));
 
 	auto scannerFromSourceName = [&](string const& _sourceName) -> solidity::Scanner const& { return m_compiler->scanner(_sourceName); };
-	SourceReferenceFormatter formatter(cerr, scannerFromSourceName);
+	SourceReferenceFormatter formatter(serr(false), scannerFromSourceName);
```
Comment (ekpyron) [inline solc/CommandLineInterface.cpp:850]: Won't it slip by ``g_hasOutputed`` now, if something is printed using the ``formatter`` below?

Comment (liangdzou) [reply solc/CommandLineInterface.cpp:850]: Yeah, need to fix and add test case

Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: Yeah, need to fix and add test case

Comment (liangdzou) [reply solc/CommandLineInterface.cpp:850]: > Won't it slip by `g_hasOutputed` now, if something is printed using the `formatter` below?

Thanks :-)

**Comment by liangdzou** [comment]
> I think you don't have to handle the prerelease warning specially. lllc can be ignored.

this is not so easy since the content is not printed directly. It is actually accumulated first and then print.
I will not handle it specially then.

**Comment by liangdzou** [comment]
I will still choose to ignore the prerelease warning since we cannot test this feature in prerelease version otherwise. This is too terrible.

**Comment by liangdzou** [comment]
diff --git a/libsolidity/interface/CompilerStack.cpp b/libsolidity/interface/CompilerStack.cpp
index e800b27..89ba985 100644
--- a/libsolidity/interface/CompilerStack.cpp
+++ b/libsolidity/interface/CompilerStack.cpp
@@ -133,7 +133,7 @@ bool CompilerStack::parse()
        m_errorReporter.clear();
        ASTNode::resetID();
 
-       if (SemVerVersion{string(VersionString)}.isPrerelease())
+       if (false && SemVerVersion{string(VersionString)}.isPrerelease())
                m_errorReporter.warning("This is a pre-release compiler version, please do not use it in production.");
 
**some test after disable the prerelease warning**
➜  liang@matrix ~/projects/solidity/test/libsolidity/syntaxTests/viewPure git:(issue_4494_error_out_when_no_output_required) ✗ solc view_pure_abi_encode
"view_pure_abi_encode" is not found.
➜  liang@matrix ~/projects/solidity/test/cmdlineErrorReports git:(issue_4494_error_out_when_no_output_required) ✗ solc ~/no_output_requirement.sol --gas

======= /home/liang/no_output_requirement.sol:C =======
Gas estimation:
construction:
   81 + 26800 = 26881
external:
   f(): 133
➜  liang@matrix ~/projects/solidity/test/libsolidity/syntaxTests/viewPure git:(issue_4494_error_out_when_no_output_required) ✗ solc view_pure_abi_encode.sol 
view_pure_abi_encode.sol:1:1: Warning: Source file does not specify required compiler version!
contract C {
^ (Relevant source part starts here and spans across multiple lines).
➜  liang@matrix ~/projects/solidity/test/cmdlineErrorReports git:(issue_4494_error_out_when_no_output_required) ✗ solc too_long_line_left_short.sol
too_long_line_left_short.sol:1:1: Warning: Source file does not specify required compiler version!
contract C {
^ (Relevant source part starts here and spans across multiple lines).
too_long_line_left_short.sol:2:15: Error: Identifier not found or not unique.
   function f(announcementType Type, string Announcement, string  ...
              ^--------------^

**This shows warning, error, gas are all working. However, this cannot be added to trunk because pre-release will never print out anything.**

**Comment by liangdzou** [comment]
> I think you don't have to handle the prerelease warning specially. lllc can be ignored.

I agree with you now. It seems there is no easy way to deal with pre-release (@chriseth @ekpyron **If you have good suggestions, please let me know**).

One may be able to support it by regarding pre-release version can have one exception message. But, I do not like it since it will cause the implementation for pre-release and release version to be different and actually not a very small change.

File: libsolidity/interface/SourceReferenceFormatter.cpp [hunk 5]
```diff
@@ -31,8 +31,11 @@ namespace dev
 namespace solidity
 {
 
+bool g_hasOutputed = false;
```
Comment (chriseth) [inline libsolidity/interface/SourceReferenceFormatter.cpp]: I'm not a native speaker, but I think it should be just `g_hasOutput`.

File: solc/CommandLineInterface.cpp [hunk 6]
```diff
@@ -69,6 +69,16 @@ namespace dev
 namespace solidity
 {
 
+extern bool g_hasOutputed;
+std::ostream& sout(bool used = true) {
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: `{` on a line of its own.

File: solc/CommandLineInterface.cpp [hunk 7]
```diff
@@ -69,6 +69,16 @@ namespace dev
...
+	g_hasOutputed = g_hasOutputed || used;
+	return cout;
+}
+std::ostream& serr(bool used = true) {
+	g_hasOutputed = g_hasOutputed || used;
+	return cerr;
+}
+
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp:87]: As a safeguard, we could even add `#define cout ERROR` or something like that here.

File: libsolidity/interface/SourceReferenceFormatter.cpp (hunk 5 above)
Comment (liangdzou) [reply libsolidity/interface/SourceReferenceFormatter.cpp]: sure, thx, will change it soon

File: solc/CommandLineInterface.cpp (hunk 6 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: change it soon

File: solc/CommandLineInterface.cpp (hunk 4 above)
Comment (chriseth) [reply solc/CommandLineInterface.cpp:850]: I'm not sure if we should clutter the source reference formatter for this feature. Perhaps it would be better to just set the flag to true in this file here at the places where we use the formatter.

File: solc/CommandLineInterface.cpp [hunk 8]
```diff
@@ -1231,6 +1241,25 @@ void CommandLineInterface::outputCompilationResults()
 		handleNatspec(true, contract);
 		handleNatspec(false, contract);
 	} // end of contracts iteration
+
+	if (!g_hasOutputed &&
+			!m_args.count(g_argAst) &&
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Sorry, I think I asked this before, but why can't these be removed here?

File: solc/CommandLineInterface.cpp [hunk 9]
```diff
@@ -1231,6 +1241,25 @@ void CommandLineInterface::outputCompilationResults()
...
+			!m_args.count(g_argBinary) &&
+			!m_args.count(g_argBinaryRuntime) &&
+			!m_args.count(g_argAbi) &&
+			!m_args.count(g_argSignatureHashes) &&
+			!m_args.count(g_argNatspecUser) &&
+			!m_args.count(g_argNatspecDev) &&
+			!m_args.count(g_argMetadata))
+	{
+		serr() << "Source files are valid, but no output requested." << endl;
+		m_error = true;
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Why do you set m_error to true?

File: solc/CommandLineInterface.cpp (hunk 8 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: If the option -o is set, there may be no print on the screen but in the files, e.g. --ast.

File: solc/CommandLineInterface.cpp (hunk 7 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp:87]: sure, I will define it to empty to disable its usage.

File: solc/CommandLineInterface.cpp (hunk 9 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: Ok, this seems not a failure, I will remove this line to not return a failure for this situation?

File: solc/CommandLineInterface.cpp (hunk 4 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp:850]: > I'm not sure if we should clutter the source reference formatter for this feature. Perhaps it would be better to just set the flag to true in this file here at the places where we use the formatter.

it seems SourceReferenceFormatter has been used in multiple places. Is it ok to only consider the one used in ./solc/CommandLineInterface.cpp?

**Review by liangdzou — COMMENTED** [review]
I have modified according to your comments. There is one question may need discussion at the line 825 and 1245 of the file CommandLineInterface.cpp. You can open the file to review my answer about them. Thanks.

**Comment by chriseth** [comment]
Yes, only the SourceReferenceFormatter that is used in the CommandlineCompiler is relevant. That's why I suggested to not modify it.

File: solc/CommandLineInterface.cpp (hunk 8 above)
Comment (chriseth) [reply solc/CommandLineInterface.cpp]: Ok, but then the message should be different, shouldn't it? So if `-o` was given, we could report something like `Generated output files in <directory>.`.

Comment (chriseth) [reply solc/CommandLineInterface.cpp]: I mean the point of doing it like this (i.e. with the global variable) was that we can add another commandline option without checking this condition here.

**Comment by chriseth** [comment]
Since `CommandlineInterface` could be re-used multiple time in principle, it might make sense to set it to false at the beginning of `parseArguments`.

**Comment by liangdzou** [comment]
> Yes, only the SourceReferenceFormatter that is used in the CommandlineCompiler is relevant. That's why I suggested to not modify it.

done :-)

**Comment by liangdzou** [comment]
> Since `CommandlineInterface` could be re-used multiple time in principle, it might make sense to set it to false at the beginning of `parseArguments`.

done :-)

**Review by chriseth — CHANGES_REQUESTED** [review]
Please change the code such that the final check is something like:
```
if (!g_hasOutput)
{
  if (m_args.count(g_argOutputDir))
    // output something like "Artefacts can be found in <output dir>"
  else
    // output "source files valid but no output requested"
}
```

File: solc/CommandLineInterface.cpp (hunk 8 above)
Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: updated according to your comments :-)

**Comment by liangdzou** [comment]
updated according to the review comment.

File: solc/CommandLineInterface.cpp [hunk 10]
```diff
@@ -1232,6 +1260,14 @@ void CommandLineInterface::outputCompilationResults()
 		handleNatspec(true, contract);
 		handleNatspec(false, contract);
 	} // end of contracts iteration
+
+	if (!g_hasOutput)
+	{
+		if (m_args.count(g_argOutputDir))
+			sout() << "Altifact can be found in " << m_args.at(g_argOutputDir).as<string>() << "." << endl;
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Typo: altifact

Comment (liangdzou) [reply solc/CommandLineInterface.cpp]: fixed, Thanks :-)

**Comment by axic** [comment]
What is left here to do?

**Comment by liangdzou** [comment]
> What is left here to do?

I think @chriseth want this PR merged after the version 0.5.0

**Comment by chriseth** [comment]
Apart from that, someone needs to do some manual testing.

**Comment by liangdzou** [comment]
> Apart from that, someone needs to do some manual testing.

I have tried to modify the code to disable the pre-release message and test for warning, error, no output cases. But I think it is better for someone else to confirm it.

```
diff --git a/libsolidity/interface/CompilerStack.cpp b/libsolidity/interface/CompilerStack.cpp
index adf59a9..4c218f0 100644
--- a/libsolidity/interface/CompilerStack.cpp
+++ b/libsolidity/interface/CompilerStack.cpp
@@ -133,7 +133,7 @@ bool CompilerStack::parse()
        m_errorReporter.clear();
        ASTNode::resetID();
 
-       if (SemVerVersion{string(VersionString)}.isPrerelease())
+       if (false && SemVerVersion{string(VersionString)}.isPrerelease())
                m_errorReporter.warning("This is a pre-release compiler version, please do not use it in production.");
```

```
➜  liang@matrix ~/projects/zzz/yul solc t.sol 
t.sol:1:1: Warning: Source file does not specify required compiler version!
contract C {
^ (Relevant source part starts here and spans across multiple lines).
➜  liang@matrix ~/projects/zzz/yul solc e.sol 
e.sol:1:1: Error: Expected pragma, import directive or contract/interface/library definition.
ontract C {
^-----^
➜  liang@matrix ~/projects/zzz/yul solc v.sol 
Source files are valid, but no output requested.
```

**Review by chriseth — APPROVED** [review]
