### PR TITLE
[Yul] Mark recursive functions and functions containing loops to be non-movable.

### LINKED ISSUE #7847: [yul] loop-invariant-code-motion should check if loop may execute at least once before moving loop-invariant in for-body and for-post blocks
## Description

Summary: The yul optimiser converts a terminating program into a non terminating program.

Terminating program (because msize() evaluates to zero)

```
{
        for {} msize() {
          function foo_s_0() -> x_1 { for {} caller() {} {} }
          // x_3 is a movable loop invariant because `foo_s_0()` is movable
          let x_3 := foo_s_0()
          mstore(192, x_3)
        }
        {}
}
```

Non terminating program (post optimization)

```
{
    for { } iszero(iszero(caller())) { }
    { }
    for { } 1 { mstore(192, 0) }
    { if iszero(msize()) { break } }
}
```

The optimized program creates an infinite for loop due to a non-zero caller() value. On the other hand, the unoptimized program bails out early because `msize()` is zero at the point of evaluation.

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings): istanbul

## Steps to Reproduce

```
$ solc --strict-assembly --optimize <test.yul>
$ yulrun --input-file <test_opt.yul>
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/7847

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `d4c16496ff5ce08573d6d227ad4631ec74c07893`:
```
Coding style error:
 libyul/optimiser/Semantics.cpp:134: if (CycleDetector<YulString>([&](YulString const& _functionName, CycleDetector<YulString>& _cycleDetector, size_t) {

```
Please check that your changes are working as intended.

File: libyul/optimiser/Semantics.cpp [hunk 1]
```diff
@@ -108,11 +108,44 @@ void MSizeFinder::operator()(FunctionCall const& _functionCall)
 
 map<YulString, SideEffects> SideEffectsPropagator::sideEffects(
 	Dialect const& _dialect,
-	map<YulString, std::set<YulString>> const& _directCallGraph
+	CallGraph const& _directCallGraph
 )
 {
+	// Any loop currently makes a function non-movable, because
+	// it could be a non-terimnating loop.
```
Comment (leonardoalt) [inline libyul/optimiser/Semantics.cpp]:
```suggestion
	// it could be a non-terminating loop.
```

**Comment by leonardoalt** [comment]
Can you also add the original issue test?

**Review by leonardoalt — DISMISSED** [review]

**Review by leonardoalt — APPROVED** [review]
