### PR TITLE
Fix overload resolution when conflict is with members of address

### LINKED ISSUE #2655: A function is called balance() confuses compiler with balance property
Using 0.4.13+commit.0fb4cb1a

```
pragma solidity ^0.4.13;

contract A {
    function balance() returns (uint) {
        return 1;
    }
}
contract C {
    event Log(uint v);
    function B() {
        A a = new A();
        Log(a.balance);
    }
}
```
The following error is generated:

```
TypeError: Member "balance" not unique after argument-dependent lookup in contract A
        Log(a.balance);
            ^-------^
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #2655.

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -1712,12 +1712,34 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
...
-			(memberName == "value" ? " - did you forget the \"payable\" modifier?" : "")
-		);
+	{
+		// Remove builtins (i.e. not having a declaration) first
+		for (auto it = possibleMembers.begin(); it != possibleMembers.end();)
+			if (
+				(
+					// Overloaded functions without declaration (e.g. transfer(), send(), call(), etc.)
+					it->type->category() == Type::Category::Function &&
+					!dynamic_cast<FunctionType const&>(*it->type).hasDeclaration()
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: This  looks rather hacky. What about removing the members as part of the type instead of the overload resolution?
I would like `var  f = x.balance; f();` to work in the same way as `x.balance();`. If you need access to the account balance, you can use `address(x).balance`.

Comment (axic) [reply libsolidity/analysis/TypeChecker.cpp]: It is very hacky, should be removed entirely at the breaking release when a contract isn't an child of address.

Do you have a non-hacky solution for keeping the members in non-conflicting cases?

**Comment by chriseth** [comment]
You could try it in  `ContractType::nativeMembers` - although that might still not solve cases that use `using for`.

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -1661,6 +1662,37 @@ MemberList::MemberMap ContractType::nativeMembers(ContractDefinition const*) con
...
+		{
+			if (
+				member.name == it->name &&
+				(
+					// Members with different types are not allowed
+					member.type->category() != it->type->category() ||
+					// Members must overload functions without clash
+					(
+						member.type->category() == Type::Category::Function &&
+						dynamic_cast<FunctionType const&>(*member.type).hasEqualArgumentTypes(dynamic_cast<FunctionType const&>(*it->type))
```
Comment (axic) [inline libsolidity/ast/Types.cpp]: This is needed because simply comparing the type takes visibility specifiers into account, which is a can of worms.

**Comment by axic** [comment]
@chriseth can you review please?

File: test/libsolidity/SolidityNameAndTypeResolution.cpp [hunk 3]
```diff
@@ -6953,6 +6953,29 @@ BOOST_AUTO_TEST_CASE(warn_about_suicide)
...
+				return 1;
+			}
+			function transfer(uint amount) {
+				address(this).transfer(amount); // to avoid pureness warning
+			}
+		}
+		contract D {
+			function f() {
+				var x = (new C()).balance();
+				x;
```
Comment (chriseth) [inline test/libsolidity/SolidityNameAndTypeResolution.cpp:6971]: This produces "statement does not have an effect" warning. If you want to force "no warnings" I think you should use `CHECK_SUCCESS_NO_WARNINGS` or something like that.

File: Changelog.md [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 Features:
  * Parser: Better error message for unexpected trailing comma in parameter lists.
+ * Type Checker: Overload resolution should work with builtins of ``address``.
```
Comment (chriseth) [inline Changelog.md]: I think this is rather about overwriting instead of overloading. What about `Fix virtual function lookup when overwriting builtin members of ``address``.`?

File: libsolidity/ast/Types.cpp [hunk 5]
```diff
@@ -1619,7 +1619,8 @@ string ContractType::canonicalName() const
 MemberList::MemberMap ContractType::nativeMembers(ContractDefinition const*) const
 {
 	// All address members and all interface functions
-	MemberList::MemberMap members(IntegerType(160, IntegerType::Modifier::Address).nativeMembers(nullptr));
+	MemberList::MemberMap const& addressMembers = IntegerType(160, IntegerType::Modifier::Address).nativeMembers(nullptr);
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: This function returns by value, doesn't it?

File: test/libsolidity/SolidityNameAndTypeResolution.cpp (hunk 3 above)
Comment (axic) [reply test/libsolidity/SolidityNameAndTypeResolution.cpp:6971]: Ah, I thought `CHECK_SUCCESS_NO_WARNINGS` stands for success and not even warnings. Maybe it should read `CHECK_SUCCESS_IGNORE_WARNINGS `.

File: libsolidity/ast/Types.cpp [hunk 6]
```diff
@@ -1661,6 +1662,37 @@ MemberList::MemberMap ContractType::nativeMembers(ContractDefinition const*) con
 				&it.second->declaration()
 			));
 	}
+	// Add overloads from address only if there is no conflict
+	for (auto it = addressMembers.begin(); it != addressMembers.end(); ++it)
+	{
+		bool clash = false;
+		for (auto const member: members)
```
Comment (chriseth) [inline libsolidity/ast/Types.cpp]: Can you extract this into a function?

Comment (chriseth) [reply libsolidity/ast/Types.cpp]: Or perhaps everything startign from `add overloads from address....`?

File: test/libsolidity/SolidityNameAndTypeResolution.cpp (hunk 3 above)
Comment (chriseth) [reply test/libsolidity/SolidityNameAndTypeResolution.cpp:6971]: Sure, that's what it stands for, but I thought that because of the comments above (`to avoid pureness warning`) you were aiming for a test without warnings.

File: libsolidity/ast/Types.cpp (hunk 6 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: I was thinking about the same but not sure it helps much. It is quite specific.

File: test/libsolidity/SolidityNameAndTypeResolution.cpp (hunk 3 above)
Comment (axic) [reply test/libsolidity/SolidityNameAndTypeResolution.cpp:6971]: So it ignores warnings or doesn't?

Actually I don't mind the warnings myself in this code.

File: libsolidity/ast/Types.cpp (hunk 6 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp]: It is quite specific, but it will make the containing function shorter.

Basically my thinking is: If you need a comment to describe what a block inside a function does, you should probable move that into its own function. The purpose of the helper function is clear from its name, so you don't need the comment.

Comment (axic) [reply libsolidity/ast/Types.cpp]: Done.

**Review by chriseth — APPROVED** [review]
