### PR TITLE
Fix text formatting of CI matrix notifications

### LINKED ISSUE #13507: Gitter notifications for failing solc-bin nightly build
For some reason I get no notifications for failed nightly builds or sync runs in solc-bin. I have to manually check https://github.com/ethereum/solc-bin/actions from time to time. And even if it worked, the notification should be visible to the whole team.

Set up a notification for failed action runs that goes to the [#solidity-dev channel on Gitter](https://gitter.im/ethereum/solidity-dev).

You can reuse parts of the [`gitter_notify_unless_pr`](https://github.com/ethereum/solidity/blob/v0.8.17/.circleci/config.yml#L34-L72) command we use in our main CI config.

### PR DESCRIPTION
**Pull request by r0qs**
As the matrix API currently [does not support markdown](https://spec.matrix.org/v1.6/client-server-api/#mtext), the CI notification bot was posting unformatted text to the `solidity-dev` channel, as can be seen [here](https://matrix.to/#/!poXqlbVpQfXKWGseLY:gitter.im/$wa5nqCiWQXFCQboYHpQv_ivgqDwB7crJ55ne3z6Q6lg?via=gitter.im&via=matrix.org&via=matrix.dapp.org.uk).

This PR adds support to text formatting using the `org.matrix.custom.html` format. It also splits the notification logic from the CI config, allowing us to easily adapt the script to fix https://github.com/ethereum/solidity/issues/13507 as well.

### CODE REVIEW

File: scripts/ci/notification/matrix_notification.sh [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    echo "$(eval printf '%s' \""${formatted_msg}"\")"
+}
+
+sanitize_variable() {
+    sanitized_value="$(printf '%s' "$1" | sed "s;[^[:blank:][:alnum:]_:/?=&.()-];;g")"
+    echo "$sanitized_value"
+}
+
+# Set message environment variables based on CI backend
+if [ "$CIRCLECI" = true ] ; then
```
Comment (r0qs) [inline scripts/ci/notification/matrix_notification.sh]: The idea here is to add an `else` at this condition when fixing https://github.com/ethereum/solidity/issues/13507 and also move the `circleci_job_name` and `circleci_workflow_name` out of the `notify` function, since `solc-bin` uses github actions and not circleci for the nightly builds.

File: scripts/ci/notification/matrix_notification.sh [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+}
+
+notify() {
+    # Prevent eval over unexpected environment variable values
+    BRANCH="$(sanitize_variable "$BRANCH")"
+    TAG="$(sanitize_variable "$TAG")"
+    BUILD_URL="$(sanitize_variable "$BUILD_URL")"
+    BUILD_NUM="$(sanitize_variable "$BUILD_NUM")"
+
+    # FIXME: Checking $CIRCLE_PULL_REQUEST would be better than hard-coding branch names
```
Comment (r0qs) [inline scripts/ci/notification/matrix_notification.sh:19]: I kept this comment, since I still need to investigate if the statement still holds.

File: scripts/ci/notification/templates/build_fail.json
Comment (nikola-matic) [inline scripts/ci/notification/templates/build_fail.json:1]: Is there any way to run this locally and check whether it produces desired output?

File: scripts/ci/notification/matrix_notification.sh [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+    formatted_msg="$(printf '%s' "$message" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')"
+    # Evaluate environment variables
+    # NOTE: The variables must be sanitized before call eval to avoid execution
+    # of unexpected commands instead of valid input values.
+    # shellcheck disable=SC2005
+    echo "$(eval printf '%s' \""${formatted_msg}"\")"
+}
+
+sanitize_variable() {
+    sanitized_value="$(printf '%s' "$1" | sed "s;[^[:blank:][:alnum:]_:/?=&.()-];;g")"
```
Comment (nikola-matic) [inline scripts/ci/notification/matrix_notification.sh]: A comment would be nice here to show an example of a value pre and post being sanitized. Much easier for me than having to google the above sed command :)

File: scripts/ci/notification/templates/build_fail.json
Comment (r0qs) [reply scripts/ci/notification/templates/build_fail.json:1]: You can setup your own matrix channel, create a token for your matrix user, and run the curl command passing the room id, token and message. Or set the respective environment variables and call the `matrix_notification.sh` script, for example: 

```sh
MATRIX_SERVER="matrix.org" # for example
MATRIX_NOTIFY_ROOM_ID="room-id-here"
MATRIX_ACCESS_TOKEN="your-token-here"
BRANCH="develop"
TAG="something"
BUILD_NUM="otherthing"
BUILD_URL="anotherthing"
./matrix-notification.sh success
# ./matrix-notification.sh failure
# ./matrix-notification.sh release
```

Or even set the `MATRIX_*` environment variables in the circleci config of your fork and push to your develop branch there simulating an error.

File: scripts/ci/notification/matrix_notification.sh (hunk 3 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: haha yeah I will do that. Basically, I tried to skip some special parameters like `$` so it would not be possible to run it using `TAG="$(ls /tmp)"` for example. Which could allow remote execution in the ci environment due to the use of eval in the script. With this filter the `$` is removed from the input before evaluating it.

File: scripts/ci/notification/matrix_notification.sh (hunk 2 above)
Comment (NunoFilipeSantos) [reply scripts/ci/notification/matrix_notification.sh:19]: Any update?

File: scripts/ci/notification/matrix_notification.sh [hunk 4]
```diff
@@ -0,0 +1,107 @@
+#!/bin/bash
+
+set -e
+shopt -s inherit_errexit
+
+SCRIPT_DIR="$(dirname "$0")"
+
+fail() {
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]:
```suggestion
function fail {
```

File: scripts/ci/notification/matrix_notification.sh [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+    TAG="$(sanitize_variable "$TAG")"
+    BUILD_URL="$(sanitize_variable "$BUILD_URL")"
+    BUILD_NUM="$(sanitize_variable "$BUILD_NUM")"
+
+    # FIXME: Checking $CIRCLE_PULL_REQUEST would be better than hard-coding branch names
+    # but it's broken. CircleCI associates runs on develop/breaking with random old PRs.
+    [[ "$BRANCH" == "develop" || "$BRANCH" == "breaking" ]] || { echo "Running on a PR or a feature branch - notification skipped."; exit 0; }
+
+    [[ -z "$1" ]] && fail "Event type not provided."
+    local event="$1"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: I think it's a good practice to define locals for parameters as the first thing you do in a function. It makes it easy to see how many parameters there are what what they're called.

Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: Please validate it's one of: `failure`, `success`, `release`. Using other values should be an error.

File: scripts/ci/notification/matrix_notification.sh [hunk 6]
```diff
@@ -0,0 +1,107 @@
...
+
+    # The release notification only makes sense on tagged commits. If the commit is untagged, just bail out.
+    [[ "$event" == "release" ]] && { [[ $TAG != "" ]] || { echo "Not a tagged commit - notification skipped."; exit 0; } }
+
+    workflow_name="$(circleci_workflow_name)"
+    job="$(circleci_job_name)"
+    formatted_message="$(format_message "$event")"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: You're using global variables here. The effect will be seen outside of the function too.

File: scripts/ci/notification/matrix_notification.sh [hunk 7]
```diff
@@ -0,0 +1,107 @@
...
+        --header "Authorization: Bearer ${MATRIX_ACCESS_TOKEN}" \
+        --data "$formatted_message"
+}
+
+circleci_workflow_name() {
+    # Workflow name is not exposed as an env variable. Has to be queried from the API.
+    # The name is not critical so if anything fails, use the raw workflow ID as a fallback.
+    workflow_info=$(curl --silent "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}") || true
+    workflow_name=$(echo "$workflow_info" | grep -E '"\s*name"\s*:\s*".*"' | cut -d \" -f 4 || echo "$CIRCLE_WORKFLOW_ID")
+    printf '%s' "$(sanitize_variable "$workflow_name")"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: Isn't this equivalent?
```suggestion
    sanitize_variable "$workflow_name"
```

File: scripts/ci/notification/templates/build_fail.json [hunk 8]
```diff
@@ -0,0 +1,6 @@
+{
+  "msgtype": "m.text",
```
Comment (cameel) [inline scripts/ci/notification/templates/build_fail.json]:
```suggestion
    "msgtype": "m.text",
```

File: scripts/ci/notification/matrix_notification.sh [hunk 9]
```diff
@@ -0,0 +1,107 @@
...
+
+    [[ -z "$message" ]] && fail "Message for event [$event] not defined."
+
+    # Escape \ and "
+    formatted_msg="$(printf '%s' "$message" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')"
+    # Evaluate environment variables
+    # NOTE: The variables must be sanitized before call eval to avoid execution
+    # of unexpected commands instead of valid input values.
+    # shellcheck disable=SC2005
+    echo "$(eval printf '%s' \""${formatted_msg}"\")"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: I don't think `eval` is such a good idea for template substitutions. I guess it gets the job done, but you have to worry about all that sanitization and stuff. And sanitization with regexes is never foolproof. I would not trust it without good tests (and creating them just for this would be a huge overkill).

Why not try something safer?
- There's an utility called [`envsubst`](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html) that's bundled with gettext. I bet we can assume we have it installed in CI most of the time.
- Alternatively, you can cobble up poor man's templating with a Python one-liner:
    ```bash
    python \
        -c 'import sys; print(open(sys.argv[1]).read().format(workflow_name="x", ... <other parameters here> ...))' \ 
        build_success.json
    ```
    so that the template is basically processed as a Python string you call `.format()` on and can use all of its formatting syntax.
    
    You'd just have to escape the braces in the JSON files (use `{{` and `}}` instead) and remove `$`.

    Not great but IMO still beats `eval` with hand-rolled sanitization.

File: scripts/ci/notification/matrix_notification.sh [hunk 10]
```diff
@@ -0,0 +1,107 @@
...
+}
+
+circleci_job_name() {
+    [[ $CIRCLE_NODE_TOTAL == 1 ]] && job="${CIRCLE_JOB}"
+    [[ $CIRCLE_NODE_TOTAL != 1 ]] && job="${CIRCLE_JOB} (run $((CIRCLE_NODE_INDEX + 1))/${CIRCLE_NODE_TOTAL})"
+    printf '%s' "$(sanitize_variable "$job")"
+}
+
+# Currently matrix only supports html formatted body,
+# see: https://spec.matrix.org/v1.6/client-server-api/#mtext
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh:51]: We could work around this by installing some Python-based Markdown library and using it the render the templates.

Not worth it just for these short snippets IMO but something to consider if we ever need more complex templates.

File: scripts/ci/notification/matrix_notification.sh [hunk 11]
```diff
@@ -0,0 +1,107 @@
+#!/bin/bash
+
+set -e
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: Any reason not to use all the nice options?
```suggestion
set -euo pipefail
```

File: scripts/ci/notification/matrix_notification.sh [hunk 12]
```diff
@@ -0,0 +1,107 @@
...
+    [[ $CIRCLE_NODE_TOTAL != 1 ]] && job="${CIRCLE_JOB} (run $((CIRCLE_NODE_INDEX + 1))/${CIRCLE_NODE_TOTAL})"
+    printf '%s' "$(sanitize_variable "$job")"
+}
+
+# Currently matrix only supports html formatted body,
+# see: https://spec.matrix.org/v1.6/client-server-api/#mtext
+#
+# Eventually, the matrix api will have support for better format options and `formatted_body` may not be necessary anymore:
+# https://github.com/matrix-org/matrix-spec-proposals/pull/1767
+format_message() {
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]:
```suggestion
format_predefined_message() {
```

File: scripts/ci/notification/matrix_notification.sh [hunk 13]
```diff
@@ -0,0 +1,107 @@
...
+    echo "$sanitized_value"
+}
+
+# Set message environment variables based on CI backend
+if [[ "$CIRCLECI" = true ]] ; then
+    BRANCH="$CIRCLE_BRANCH"
+    TAG="$CIRCLE_TAG"
+    BUILD_URL="$CIRCLE_BUILD_URL"
+    BUILD_NUM="$CIRCLE_BUILD_NUM"
+fi
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: Not sure there's any point in doing this. You're still using other CircleCI variables like `$CIRCLE_NODE_INDEX`, comments and function names refer to CircleCI and overall we're pretty much assuming we're working with CircleCI. Might make more sense to just explicitly fail when `$CIRCLECI` is not `"true"` and keep the script simpler, with the assumption will actually make it work with whatever other CI we need when we need it.

Also, if you really want to keep it CI-independent, I think that passing these values to the function via arguments would be nicer.

File: scripts/ci/notification/matrix_notification.sh (hunk 11 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: Nope. I added it.

File: scripts/ci/notification/matrix_notification.sh (hunk 7 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: yes. Fixed

File: scripts/ci/notification/matrix_notification.sh (hunk 10 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh:51]: Yeah, I think it is not worth it either. And it seems that the API will change soon, at least the new format proposal was merged already. So I guess it is a matter of waiting clients implement it.

File: scripts/ci/notification/matrix_notification.sh (hunk 9 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: Right. Nice, I didn't know about `envsubst`. I replaced it and removed the `sanitization` stuff ;)

File: scripts/ci/notification/matrix_notification.sh (hunk 13 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: The idea was exactly to reuse this script to also fix https://github.com/ethereum/solidity/issues/13507 by only replacing the CI environment variables accordingly, since the notification mechanism will be the same. For instance, something like:

```sh
if [[ "$CIRCLECI" = true ]] ; then
    BRANCH="$CIRCLE_BRANCH"
    ...
else
    BRANCH="$GITHUB_HEAD_REF"
    ...
fi

File: scripts/ci/notification/matrix_notification.sh [hunk 14]
```diff
@@ -0,0 +1,87 @@
...
+    [[ "$event" == "release" ]] && template="${SCRIPT_DIR}/templates/build_release.json"
+
+    [[ -z "$template" ]] && fail "Message template for event [$event] not defined."
+
+    # Export variables that must be substituted
+    export WORKFLOW_NAME JOB BRANCH TAG BUILD_URL BUILD_NUM
+    formatted_message=$(envsubst < "$template")
+    unset WORKFLOW_NAME JOB BRANCH TAG BUILD_URL BUILD_NUM
+
+    echo "$formatted_message"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]: You can just print directly to stdout to keep it more concise. Also saves us some messing with locals:

```suggestion
    envsubst < "$template"
    unset WORKFLOW_NAME JOB BRANCH TAG BUILD_URL BUILD_NUM
```

File: scripts/ci/notification/matrix_notification.sh [hunk 15]
```diff
@@ -0,0 +1,87 @@
...
+    local workflow_info workflow_name
+    workflow_info=$(curl --silent "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}") || true
+    workflow_name=$(echo "$workflow_info" | grep -E '"\s*name"\s*:\s*".*"' | cut -d \" -f 4 || echo "$CIRCLE_WORKFLOW_ID")
+    echo "$workflow_name"
+}
+
+function circleci_job_name() {
+    local job
+    [[ $CIRCLE_NODE_TOTAL == 1 ]] && job="${CIRCLE_JOB}"
+    [[ $CIRCLE_NODE_TOTAL != 1 ]] && job="${CIRCLE_JOB} (run $((CIRCLE_NODE_INDEX + 1))/${CIRCLE_NODE_TOTAL})"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]:
```suggestion
    (( $CIRCLE_NODE_TOTAL == 1 )) && job="${CIRCLE_JOB}"
    (( $CIRCLE_NODE_TOTAL != 1 )) && job="${CIRCLE_JOB} (run $((CIRCLE_NODE_INDEX + 1))/${CIRCLE_NODE_TOTAL})"
```

File: scripts/ci/notification/matrix_notification.sh [hunk 16]
```diff
@@ -0,0 +1,87 @@
...
+    echo "$job"
```
Comment (cameel) [inline scripts/ci/notification/matrix_notification.sh]:
```suggestion
    [[ $CIRCLE_NODE_TOTAL == 1 ]] && echo "${CIRCLE_JOB}"
    [[ $CIRCLE_NODE_TOTAL != 1 ]] && echo "${CIRCLE_JOB} (run $((CIRCLE_NODE_INDEX + 1))/${CIRCLE_NODE_TOTAL})"
```

**Review by cameel — DISMISSED** [review]
I have some small suggestions but it already looks good.

File: scripts/ci/notification/matrix_notification.sh (hunk 13 above)
Comment (cameel) [reply scripts/ci/notification/matrix_notification.sh]: After your tweaks this now seems less to be dependent only on these variables (other than maybe the fact that it always runs CircleCI-specific workarounds).

I still think it would be better to do this only when we need this, but if you prefer it that way it's fine too.

File: scripts/ci/notification/matrix_notification.sh (hunk 16 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: I'm not sure about this change. Only echoing in the first condition will not return from the function even when `CIRCLE_NODE_TOTAL == 1`, thus the script will continue to the second condition, which will evaluate to `false` for this example, and the exit status of the function will then be 1 instead of 0. As we use `set -e`, this will terminate the script. We should keep it as it is or do:

```sh
(( CIRCLE_NODE_TOTAL == 1 )) && echo "${CIRCLE_JOB}" && return
(( CIRCLE_NODE_TOTAL != 1 )) && echo "${CIRCLE_JOB} (run $((CIRCLE_NODE_INDEX + 1))/${CIRCLE_NODE_TOTAL})"
```

The return will ensure that whatever is evaluated in the first condition is returned as exit status of the function.

Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: I added the return. Let me know if you prefer the other way or if I misunderstood something ;)

File: scripts/ci/notification/matrix_notification.sh (hunk 13 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: Yeah, but the fix of #13507 is trivial with the changes of this PR here, basically replacing the environment variables, or I'm missing something there haha

By CircleCI-specific workarounds you mean this comment https://github.com/ethereum/solidity/pull/14090#discussion_r1156943573, right? Actually, I still need to check what was this about, I don't really got what is the problem from the FIXME comment.

I mean, if CircleCI associates random PRs with what was supposed to be the `CIRCLE_PULL_REQUEST` it is a bug that we should report to upstream, no?

File: scripts/ci/notification/matrix_notification.sh (hunk 16 above)
Comment (cameel) [reply scripts/ci/notification/matrix_notification.sh]: Ah, right. I missed the fact that these conditions are not entirely equivalent to `if`/`else` and you can run into corner cases like this. `return` looks like a good way out.

File: scripts/ci/notification/matrix_notification.sh (hunk 13 above)
Comment (cameel) [reply scripts/ci/notification/matrix_notification.sh]: > Yeah, but the fix of https://github.com/ethereum/solidity/issues/13507 is trivial with the changes of this PR here

Ah, I missed that bit from your original comment. So it's not just future-proofing but you'll actually be using that extra code for portability. Fine then.

> By CircleCI-specific workarounds you mean this comment https://github.com/ethereum/solidity/pull/14090#discussion_r1156943573, right? Actually, I still need to check what was this about, I don't really got what is the problem from the FIXME comment.

See #12269. Originally I was checking if `$CIRCLE_PULL_REQUEST` is empty/unset to determine if the workflow is one running in a PR. It quickly turned out that this variable often points at a PR even in runs on `develop`.

I just checked the "Preparing environment variables" step in a few random workflows and I'm not seeing that any more. Must have been fixed by CircleCI.

> I mean, if CircleCI associates random PRs with what was supposed to be the CIRCLE_PULL_REQUEST it is a bug that we should report to upstream, no?

Yes, I did report a similar issue to their support back then: https://github.com/ethereum/solidity/pull/12202#issuecomment-952950518. I remember that I even got a reply later that this is super low priority for them and we have to live with it for the time being. And later again that they'll be fixing it after all.

**Review by cameel — APPROVED** [review]

File: scripts/ci/notification/matrix_notification.sh (hunk 13 above)
Comment (r0qs) [reply scripts/ci/notification/matrix_notification.sh]: Ah nice, thanks for the reference. I will remove the `FIXME` when changing this script to fix https://github.com/ethereum/solidity/issues/13507 then. ;)

**Comment by cameel** [comment]
@r0qs I just noticed this error in one of my CI runs (this one does not have an associated PR yet): https://app.circleci.com/pipelines/github/ethereum/solidity/29302/workflows/29eb5534-683c-454f-98cf-c0cc004beb25/jobs/1301024

```
scripts/ci/notification/matrix_notification.sh: line 75: CIRCLE_TAG: unbound variable
```

This is probably due to `set -u` and basically works as expected - this variable is not always present, so you should use something like `"${CIRCLE_TAG:-}"` to provide an explicit empty default value when accessing it.
