### PR TITLE
IR generation for shifts

### LINKED ISSUE #8717: [Sol-Yul] Support shifts
```
contract C {
  function f(uint a) public returns (uint ret) {
    ret = a >> 1;
  }
}
```

results in
```
Unimplemented feature:
/Users/alex/Projects/solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp(1573): Throw in function std::__1::string solidity::frontend::IRGeneratorForStatements::binaryOperation(langutil::Token, const solidity::frontend::Type &, const std::__1::string &, const std::__1::string &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

Also missing for `<<` and `>>>`.

### PR DESCRIPTION
**Pull request by axic**
TODO: need to consider sign of operands

Fixes #8717.

### CODE REVIEW

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -1566,12 +1567,23 @@ string IRGeneratorForStatements::binaryOperation(
 			case Token::BitAnd:
 				fun = "and";
 				break;
+			case Token::SHL:
+				fun = "shl";
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I think shifts should have their own function, you need to revert on negative amount, for example.

Comment (axic) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Yes, likely it will be too complex. Noted signs in the comment above.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `4ed734ffc0069ef2d3e527091469907cf48a9eec`:
```
Coding style error:
 libsolidity/codegen/YulUtilFunctions.cpp:331: let divisor := exp(2, bits)
 libsolidity/codegen/YulUtilFunctions.cpp:332: switch slt(value, 0)
 libsolidity/codegen/YulUtilFunctions.cpp:333: case 0 {
 libsolidity/codegen/YulUtilFunctions.cpp:335: }
 libsolidity/codegen/YulUtilFunctions.cpp:336: default {
 libsolidity/codegen/YulUtilFunctions.cpp:338: }
 libsolidity/codegen/ir/IRGeneratorForStatements.cpp:261: m_code << binaryOperation(

```
Please check that your changes are working as intended.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 2]
```diff
@@ -321,6 +318,81 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+			Whiskers(R"(
+			function <functionName>(bits, value) -> result {
+				<?hasShifts>
+					result := sar(bits, value)
+				<!hasShifts>
+					 let divisor := exp(2, bits)
+					 switch slt(value, 0)
+					 case 0 {
+						result := div(value, divisor)
+					 }
```
Comment (stackenbotten) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Coding style error

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 3]
```diff
@@ -321,6 +318,81 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+					 default {
```
Comment (stackenbotten) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Coding style error

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 4]
```diff
@@ -321,6 +318,81 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+						result := not(div(not(value), divisor))
+					 }
```
Comment (stackenbotten) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 5]
```diff
@@ -229,26 +229,42 @@ bool IRGeneratorForStatements::visit(Conditional const& _conditional)
...
-			leftIntermediate.name(),
-			value.name()
-		);
+		m_code << value.name() << " := ";
+		if (TokenTraits::isShiftOp(binaryOperator))
+			m_code << shiftOperation(binaryOperator, leftIntermediate, value);
+		else
+		{
+			solAssert(type(_assignment.leftHandSide()) == *rightIntermediateType, "");
+			 m_code << binaryOperation(
```
Comment (stackenbotten) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Coding style error

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 6]
```diff
@@ -229,32 +229,53 @@ bool IRGeneratorForStatements::visit(Conditional const& _conditional)
...
-		&type(_assignment.leftHandSide())
+
+	Token assignmentOperator = _assignment.assignmentOperator();
+	Token binaryOperator =
+		assignmentOperator == Token::Assign ?
+		assignmentOperator :
+		TokenTraits::AssignmentToBinaryOp(assignmentOperator);
+	Type const* rightIntermediateType =
+		TokenTraits::isShiftOp(binaryOperator) ?
+		type(_assignment.rightHandSide()).mobileType() :
```
Comment (leonardoalt) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:266]: Why is this the case only for `shift`?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 7]
```diff
@@ -1722,6 +1749,13 @@ std::ostream& IRGeneratorForStatements::define(IRVariable const& _var)
 	return m_code;
 }
 
+std::ostream& IRGeneratorForStatements::assign(IRVariable const& _var)
```
Comment (leonardoalt) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Can't this be reused by the function above?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 6 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:266]: Shifts are not symmetric with regards to the operands, so we do not want to convert the type of the right operand to the type of the left operand.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 7 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: `m_code << "let " << assign(_var)` - wouldn't that look weird?

Oh and I also think it's not possible because of the way `<<` works.

Comment (leonardoalt) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Hm ok

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 6 above)
Comment (leonardoalt) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:266]: Are shifts the only operators with that property?

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:266]: I think exp is also special, but in a different way. Please compare with the legacy code generator when reviewing :)

Comment (leonardoalt) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:266]: Ok!

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 8]
```diff
@@ -321,6 +318,81 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+					result := sar(bits, value)
+				<!hasShifts>
+					let divisor := exp(2, bits)
+					switch slt(value, 0)
+					case 0 {
+						result := div(value, divisor)
+					}
+					default {
+						result := not(div(not(value), divisor))
+					}
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp]: In old codegen, we did this jump-less...
```
 					let divisor := exp(2, bits)
 					let xor_mask := sub(0, slt(value, 0))
					value_to_shift := xor(div(xor(value, xor_mask), divisor), xor_mask)
```

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 9]
```diff
@@ -321,6 +318,81 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+
+
+string YulUtilFunctions::typedShiftLeftFunction(Type const& _type, bool _amountSigned)
+{
+	solAssert(_type.category() == Type::Category::FixedBytes || _type.category() == Type::Category::Integer, "");
+	string const functionName = "shift_left_" + _type.identifier() + (_amountSigned ? "_signedAmount" : "");
+	return m_functionCollector.createFunction(functionName, [&]() {
+		return
+			Whiskers(R"(
+			function <functionName>(value, bits) -> result {
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp:356]: A bit confusing that the order is reversed compared to the others and evm shifts here, isn't it?

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 8 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Yes, because the old optimizer was not able to cope with this.

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp]: I don't think the new one will be able to cope with this either.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 9 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:356]: Yes - the idea was that this is the higher-level function that is closer to the operator...

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:356]: Hm... ok, that's an argument I guess.

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 8 above)
Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Which situations did we want to optimize apart from constant values?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: If the new optimizer can determine that the shift amount is positive, this optimizes more nicely, I think.

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp]: Ah ok, maybe it does not matter...

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp]: It's always cheaper not to jump, isn't it?
And if ``slt(value, 0)`` is constant, then the inlined-version will optimize just as nicely...

So the non-constant path is faster due to not jumping and the constant path should be the same.

And this optimization is very hard for the optimizer in general - I don't think it'll be able to decide when it makes sense to remove jumps like this...

**Comment by chriseth** [comment]
Used xor version and removed pre-cleanup.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 10]
```diff
@@ -229,32 +229,53 @@ bool IRGeneratorForStatements::visit(Conditional const& _conditional)
 bool IRGeneratorForStatements::visit(Assignment const& _assignment)
 {
 	_assignment.rightHandSide().accept(*this);
-	Type const* intermediateType = type(_assignment.rightHandSide()).closestTemporaryType(
-		&type(_assignment.leftHandSide())
+
```
Comment (ekpyron) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: I think this function would be much cleaner, if it just treated shift-assigns entirely separately - I think that way we could get around the weird ``unique_ptr<IRVariable>`` construction and wouldn't need the additional ``ostream& assign(IRVariable const&)`` construction, which pretty much goes against the design of IRVariables and undermines their iḿplicit conversion properties.

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: I think most of us are still a bit puzzled about how to use the IRVariable mechanism outside of Solidity expressions. Why does `assign`  go against the design but `IRGeneratorForStatements::define` does not?

Comment (ekpyron) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: Well, ``ostream& assign(IRVariable)`` doesn't convert types. The idea would be to instead create a temporary IRVariable, define that with the function call and assign to that temporary.
That way one needs to think about what type the function call returns, which might be a different type than what is ultimately assigned to (compared to assigning directly).

Actually in the situation here, it might make sense to skip the whole IRVariable mechanism for compound assignments, though, since all types for which that can happen will only have one stack slot, so it may be easier to just work with single yul variables for this.

Comment (ekpyron) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: In a sense it would be better to have the util functions return temporary IRVariables to begin with - then we'd not need ``ostream& define(IRVariable)`` either - but only having ``define``, which by definition can be done only once and still needs you to give the variable an explicit type, pretty much achieves the same - that is *unless* we also add ``ostream& assign(IRVariable)``...

And rather than integrating IRVariables further into the util functions, I'd still keep the option open to remove them again, if we add native yul tuple assignments...

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: Having type information associated with the yul util functions might be a good idea, especially those that already take type parameters.

Also commented on the tuple issue.

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: I'm not sure this is much nicer like this.

**Comment by ekpyron** [comment]
If we go ahead with https://github.com/ethereum/solidity/pull/8845, then we need cleanup in these as well.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 10 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:257]: Ok, I think now it is nicely simplified.

**Comment by axic** [comment]
Can you rebase?  After constants were merged maybe new tests will be triggered.

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 11]
```diff
@@ -321,6 +318,84 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+{
+	solAssert(_type.category() == Type::Category::FixedBytes || _type.category() == Type::Category::Integer, "");
+	solAssert(_amountType.category() == Type::Category::Integer, "");
+	string const functionName = "shift_left_" + _type.identifier() + "_" + _amountType.identifier();
+	return m_functionCollector.createFunction(functionName, [&]() {
+		return
+			Whiskers(R"(
+			function <functionName>(value, bits) -> result {
+				<?amountSigned>
+					if slt(bits, 0) { invalid() }
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp:359]: This check should be on the cleaned amount, not the raw amount, shouldn't it?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 12]
```diff
@@ -321,6 +318,84 @@ string YulUtilFunctions::shiftRightFunctionDynamic()
...
+	IntegerType const* integerType = dynamic_cast<IntegerType const*>(&_type);
+	bool valueSigned = integerType && integerType->isSigned();
+
+	string const functionName = "shift_right_" + _type.identifier() + "_" + _amountType.identifier();
+	return m_functionCollector.createFunction(functionName, [&]() {
+		return
+			Whiskers(R"(
+			function <functionName>(value, bits) -> result {
+				<?amountSigned>
+					if slt(bits, 0) { invalid() }
```
Comment (ekpyron) [inline libsolidity/codegen/YulUtilFunctions.cpp:387]: Same as for the other one?

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: libsolidity/codegen/YulUtilFunctions.cpp (hunk 11 above)
Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:359]: E.g. if the amount type is ``int8``, then a dirty ``0x00...00FF`` could become negative only after cleaning, right?

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:359]: let me add a test.

Comment (ekpyron) [reply libsolidity/codegen/YulUtilFunctions.cpp:359]: Even if a simple test like that passes, I don't see a reason not to do ``bits := <cleanAmount>(bits)`` before this, so I'd still go for that.

Comment (chriseth) [reply libsolidity/codegen/YulUtilFunctions.cpp:359]: Yes, of course.

**Review by ekpyron — APPROVED** [review]
Looks good to me now!
