### PR TITLE
[SMTChecker] Fix analysis of overriding modifiers

### LINKED ISSUE #10602: [SMTChecker] Analyse overridden modifiers correctly
In the following example
```
pragma experimental SMTChecker;

abstract contract A {
    uint s;

    function f() public mod(s) {}
    modifier mod(uint x) virtual;
}

contract B is A {
    modifier mod(uint x) override {
        require(x == 42);
        _;
        assert(x == 42); // should hold
        assert(x == 0); // should fail
    }

    function set(uint x) public {
        s = x;
    }
}
```
SMTChecker currently fails to report the assertion violation.
The problem is that when analysing `B.f` it fails to resolve properly which version of the modifier will be used and analyses it with the modifier `A.mod` instead of `B.mod`.

### PR DESCRIPTION
**Pull request by blishko**
Fixes #10602.

This PR adds usage of `ModifierDefinition::resolveVirtual` to properly resolve which modifier definition should be analysed.
For that, it requires the context which contract is currently being analysed.

### CODE REVIEW

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -898,7 +898,7 @@ void CHC::defineInterfacesAndSummaries(SourceUnit const& _source)
 						createVariable(*var);
 					for (auto var: function->returnParameters())
 						createVariable(*var);
-					for (auto const* var: localVariablesIncludingModifiers(*function))
+					for (auto const* var: localVariablesIncludingModifiers(*function, base))
```
Comment (blishko) [inline libsolidity/formal/CHC.cpp]: I believe we want to use `base` here and not `contract`, as we want the variables for the function in the context of `base`.

File: libsolidity/formal/SMTEncoder.h [hunk 2]
```diff
@@ -74,8 +74,8 @@ class SMTEncoder: public ASTConstVisitor
 	static std::vector<VariableDeclaration const*> stateVariablesIncludingInheritedAndPrivate(ContractDefinition const& _contract);
 	static std::vector<VariableDeclaration const*> stateVariablesIncludingInheritedAndPrivate(FunctionDefinition const& _function);
 
-	static std::vector<VariableDeclaration const*> localVariablesIncludingModifiers(FunctionDefinition const& _function);
-	static std::vector<VariableDeclaration const*> modifiersVariables(FunctionDefinition const& _function);
+	static std::vector<VariableDeclaration const*> localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _currentContract);
+	static std::vector<VariableDeclaration const*> modifiersVariables(FunctionDefinition const& _function, ContractDefinition const* _currentContract);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.h]:
```suggestion
	static std::vector<VariableDeclaration const*> modifiersVariables(FunctionDefinition const& _function, ContractDefinition const* _contract);
```

File: libsolidity/formal/SMTEncoder.h [hunk 3]
```diff
@@ -74,8 +74,8 @@ class SMTEncoder: public ASTConstVisitor
 	static std::vector<VariableDeclaration const*> stateVariablesIncludingInheritedAndPrivate(ContractDefinition const& _contract);
 	static std::vector<VariableDeclaration const*> stateVariablesIncludingInheritedAndPrivate(FunctionDefinition const& _function);
 
-	static std::vector<VariableDeclaration const*> localVariablesIncludingModifiers(FunctionDefinition const& _function);
-	static std::vector<VariableDeclaration const*> modifiersVariables(FunctionDefinition const& _function);
+	static std::vector<VariableDeclaration const*> localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _currentContract);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.h]:
```suggestion
	static std::vector<VariableDeclaration const*> localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _contract);
```

File: libsolidity/formal/SMTEncoder.cpp [hunk 4]
```diff
@@ -201,7 +201,11 @@ void SMTEncoder::visitFunctionOrModifier()
 		if (dynamic_cast<ContractDefinition const*>(refDecl))
 			visitFunctionOrModifier();
 		else if (auto modifierDef = dynamic_cast<ModifierDefinition const*>(refDecl))
-			inlineModifierInvocation(modifierInvocation.get(), modifierDef);
+		{
+			solAssert(*modifierInvocation->name()->annotation().requiredLookup == VirtualLookup::Virtual, "");
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]: Why is this true?

File: libsolidity/formal/SMTEncoder.cpp [hunk 5]
```diff
@@ -2586,12 +2590,12 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
 	return stateVariablesIncludingInheritedAndPrivate(dynamic_cast<ContractDefinition const&>(*_function.scope()));
 }
 
-vector<VariableDeclaration const*> SMTEncoder::localVariablesIncludingModifiers(FunctionDefinition const& _function)
+vector<VariableDeclaration const*> SMTEncoder::localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _currentContract)
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]:
```suggestion
vector<VariableDeclaration const*> SMTEncoder::localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _contract)
```

File: libsolidity/formal/SMTEncoder.cpp [hunk 6]
```diff
@@ -2586,12 +2590,12 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
...
 {
-	return _function.localVariables() + modifiersVariables(_function);
+	return _function.localVariables() + modifiersVariables(_function, _currentContract);
 }
 
-vector<VariableDeclaration const*> SMTEncoder::modifiersVariables(FunctionDefinition const& _function)
+vector<VariableDeclaration const*> SMTEncoder::modifiersVariables(FunctionDefinition const& _function, ContractDefinition const* _currentContract)
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp]:
```suggestion
vector<VariableDeclaration const*> SMTEncoder::modifiersVariables(FunctionDefinition const& _function, ContractDefinition const* _contract)
```

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/CHC.cpp]: Not sure, I think it should be `contract` because we're looping over all base contracts of `contract` collecting all their functions as functions of `contract`. In that case, if `function` has virtual modifiers, they should be resolved in the context of `contract`.

File: libsolidity/formal/SMTEncoder.cpp (hunk 4 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp]: Not sure actually. But from the other places in the code, I see that this is usually checked before a call to `resolveVirtual`. Also in `ContractCompiler::appendModifierOrFunctionCode` from where I got this idea.

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp]: I think you are right, although, I could not find an example where it would break.

**Comment by leonardoalt** [comment]
Needs a changelog entry

File: libsolidity/formal/SMTEncoder.cpp [hunk 7]
```diff
@@ -2582,12 +2586,12 @@ vector<VariableDeclaration const*> SMTEncoder::stateVariablesIncludingInheritedA
 	return stateVariablesIncludingInheritedAndPrivate(dynamic_cast<ContractDefinition const&>(*_function.scope()));
 }
 
-vector<VariableDeclaration const*> SMTEncoder::localVariablesIncludingModifiers(FunctionDefinition const& _function)
+vector<VariableDeclaration const*> SMTEncoder::localVariablesIncludingModifiers(FunctionDefinition const& _function, ContractDefinition const* _contract)
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2645]: The way this function is now called is
"give me the local variables of _function when in the context of _contract", right?
The difference from before is that _function might not be in _contract, and might have invocations to virtual/overridden modifiers which might be in _contract.
Correct?

File: libsolidity/formal/SMTEncoder.cpp [hunk 8]
```diff
@@ -2608,10 +2612,12 @@ vector<VariableDeclaration const*> SMTEncoder::modifiersVariables(FunctionDefini
 			continue;
 
 		visited.insert(modifier);
-		if (modifier->isImplemented())
+		solAssert(_contract, "No contract context provided for modifier analysis!");
+		auto const& actualModifier = modifier->resolveVirtual(*_contract);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2672]: I'm wondering now if `SMTEncoder::inlineModifierInvocation` is buggy because of virtual modifiers

File: libsolidity/formal/SMTEncoder.cpp (hunk 7 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2645]: Yes, that's correct. The `_function` does not need to be in `_contract` directly, it can be that `_contract` just inherited it from one of its base contracts.
Exactly because `_contract` can have overriding modifiers used with `_function` and so the set of local variables can be different for different contracts in the inheritance hierarchy.

File: libsolidity/formal/SMTEncoder.cpp (hunk 8 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2672]: I don't see a problem right now, why do you think it could be buggy?

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+	modifier mod() virtual override (B,C){
+		x = 3;
+		_;
+	}
+}
+// ----
+// Warning 6328: (104-118): CHC: Assertion violation happens here.\nCounterexample:\nx = 0\n\n\n\nTransaction trace:\nconstructor()\nState: x = 0\nf()
+// Warning 6328: (137-151): CHC: Assertion violation happens here.\nCounterexample:\nx = 1\n\n\n\nTransaction trace:\nconstructor()\nState: x = 0\nf()
+// Warning 6328: (170-184): CHC: Assertion violation happens here.\nCounterexample:\nx = 2\n\n\n\nTransaction trace:\nconstructor()\nState: x = 0\nf()
+// Warning 6328: (203-217): CHC: Assertion violation happens here.\nCounterexample:\nx = 3\n\n\n\nTransaction trace:\nconstructor()\nState: x = 0\nf()
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol:42]: I had an idea here, that it would be good to have the contract in the counterexample transaction trace. Right now it is not clear which function is called (or rather on which contract) for each CEX.

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol [hunk 10]
```diff
@@ -0,0 +1,22 @@
+pragma experimental SMTChecker;
+
+abstract contract A {
+	bool s;
+
+	function f() public view mod {
+		assert(s); // holds for B
```
Comment (leonardoalt) [inline test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol:7]: Shouldn't this fail for A?

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol (hunk 9 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol:42]: Yea that's true, we should have the contract's name before both `constructor()` and function call.

File: libsolidity/formal/SMTEncoder.cpp (hunk 7 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:2645]: Ok. Then I'm convinced it should be `contract` and not `base` in CHC

File: libsolidity/formal/SMTEncoder.cpp [hunk 11]
```diff
@@ -203,7 +203,11 @@ void SMTEncoder::visitFunctionOrModifier()
 		if (dynamic_cast<ContractDefinition const*>(refDecl))
 			visitFunctionOrModifier();
 		else if (auto modifierDef = dynamic_cast<ModifierDefinition const*>(refDecl))
-			inlineModifierInvocation(modifierInvocation.get(), modifierDef);
+		{
+			solAssert(*modifierInvocation->name().annotation().requiredLookup == VirtualLookup::Virtual, "");
+			ModifierDefinition const& modifier = modifierDef->resolveVirtual(*m_currentContract);
+			inlineModifierInvocation(modifierInvocation.get(), &modifier);
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:214]: Ah you already took care of it here, nice.

File: libsolidity/formal/SMTEncoder.cpp [hunk 12]
```diff
@@ -203,7 +203,11 @@ void SMTEncoder::visitFunctionOrModifier()
 		if (dynamic_cast<ContractDefinition const*>(refDecl))
 			visitFunctionOrModifier();
 		else if (auto modifierDef = dynamic_cast<ModifierDefinition const*>(refDecl))
-			inlineModifierInvocation(modifierInvocation.get(), modifierDef);
+		{
+			solAssert(*modifierInvocation->name().annotation().requiredLookup == VirtualLookup::Virtual, "");
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:212]: I feel like I already asked this before, but why must it be `virtual`?

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol (hunk 9 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_4.sol:42]: Created an issue for that: #10646

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol (hunk 10 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol:7]: My understanding is that `f` cannot be called for `A`, since in `A` the modifier is abstract. So there cannot be an instance of `A`. I was thinking the analysis is doing the same reasoning. Do you think that's not the case?

File: libsolidity/formal/SMTEncoder.cpp (hunk 7 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2645]: OK, I think we converged on a decision and that's how it is done now in the code.

File: libsolidity/formal/SMTEncoder.cpp (hunk 12 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:212]: You did, here is my answer: https://github.com/ethereum/solidity/pull/10614#discussion_r544254357

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol (hunk 10 above)
Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol:7]: True, `mod` shouldn't be called for A. Hmm I'm wondering now what makes sense. Is the code now not analyzing A.f at all?

File: libsolidity/formal/SMTEncoder.cpp (hunk 4 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Ok. It seems to work for normal modifiers as well, so fine.

File: test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol (hunk 10 above)
Comment (blishko) [reply test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol:7]: It seems `A.f` is not analyzed, because there is no placeholder in the body of the modifier (no `_;`) (since the modifier has no body). And I think that is the correct way.

Comment (leonardoalt) [reply test/libsolidity/smtCheckerTests/modifiers/modifier_overriding_3.sol:7]: Ok that makes sense.

**Comment by leonardoalt** [comment]
Needs rebase

**Review by leonardoalt — APPROVED** [review]
