### PR TITLE
[libyul] use unique_ptr in AST over shared_ptr

### LINKED ISSUE #5653: shared_ptrs in Yul ast should all be unique_ptrs
This is to prevent two references to the same object from different places, which could result in unexpected behaviour if the object is modified.

### PR DESCRIPTION
**Pull request by christianparpart**
make use of unique_ptr instead of shared_ptr within the scope of libyul

Fixes #5653.

### CODE REVIEW

**Comment by ekpyron** [comment]
The only reason for these to be pointers and not value-members is because they are optional, right? Is it nicer to make them ``boost::optional`` instead of ``std::unique_ptr`` then? (And later with C++17, of course, ``std::optional`` ;-)?) I'm not sure what I prefer myself actually, but might be worth considering!

**Comment by chriseth** [comment]
Yes, some of them are optional, but in other cases, the main motivation was to not have a boost::variant as an in-place member (and also to keep the variant itself small).

**Comment by chriseth** [comment]
So to summarize: The fewer indirections the better, but we should check that `sizeof()` does not get too large.

**Comment by ekpyron** [comment]
We could even consider to use ``optional``, whenever the intention is in fact for the member to be optional and ``std::unique_ptr``, if the reason is merely a smaller size for the struct or to avoid problems due to recursions :-).

**Comment by chriseth** [comment]
It could be nice to have a checked unique_ptr, that asserts when `*` or `->` is invoked while it is null.

**Comment by ekpyron** [comment]
Actually, I'm not sure whether the size of these structs is in fact an issue - they will end up being non-copyable anyways, won't they? If they have to be copyable, we can't use ``unique_ptr`` anyways. So we probably only have to deal with recursions with variants (and I'm not sure we'll run into that problem)...
And yes: a "checked" unique_ptr might indeed be nice.

**Comment by chriseth** [comment]
Size is not only relevant when copying, it is also relevant when just iterating over it. Of course, only a profiler will tell, because also locality is important.

**Comment by chriseth** [comment]
I'm really not sure about this. I think we should only change it following a profiling run. The original issue was just to change from `shared_ptr` to `unique_ptr` to prevent modifications and nothing else.

File: libyul/optimiser/FullInliner.cpp [hunk 1]
```diff
@@ -235,7 +235,15 @@ Statement BodyCopier::operator()(VariableDeclaration const& _varDecl)
 Statement BodyCopier::operator()(FunctionDefinition const& _funDef)
 {
 	assertThrow(false, OptimizerException, "Function hoisting has to be done before function inlining.");
-	return _funDef;
```
Comment (chriseth) [inline libyul/optimiser/FullInliner.cpp:238]: The BodyCopier is not designed to copy functions (they also do not need to be copied, they can just be referenced). This line is just here to prevent the compiler warning. Something like `return {}` could work. If not, just take the simplest variant of statement.

File: libyul/optimiser/ASTCopier.h [hunk 2]
```diff
@@ -97,6 +97,19 @@ class ASTCopier: public ExpressionCopier, public StatementCopier
...
 	}
+
+	template <typename T>
+	std::unique_ptr<T> translate(std::unique_ptr<T> const& _v)
+	{
+		return _v ? std::make_unique<T>(translate(*_v)) : nullptr;
+	}
+
+	template <typename T>
+	boost::optional<T> translate(boost::optional<T> const& _v)
```
Comment (chriseth) [inline libyul/optimiser/ASTCopier.h]: This and the override for shared_ptr are not used and can be deleted.

File: libyul/optimiser/SSATransform.cpp [hunk 3]
```diff
@@ -87,14 +88,16 @@ void SSATransform::operator()(Block& _block)
 					visit(*varDecl.value);
 				if (varDecl.variables.size() != 1 || !m_variablesToReplace.count(varDecl.variables.front().name))
 					return {};
+				vector<Statement> v;
 				// Replace "let a := v" by "let a_1 := v  let a := v"
```
Comment (chriseth) [inline libyul/optimiser/SSATransform.cpp]: Unrelated but can be fixed with this pr: I think it should be 
```suggestion
				// Replace "let a := v" by "let a_1 := v  let a := a_1"
```

Comment (ekpyron) [reply libyul/optimiser/SSATransform.cpp]: Yep, that's right!

File: libyul/optimiser/ASTCopier.h (hunk 2 above)
Comment (christianparpart) [reply libyul/optimiser/ASTCopier.h]: @chriseth Actually, even the shared_ptr<> version can be removed (dead code). so only the unique_ptr<> version remains.

**Review by chriseth — APPROVED** [review]
