### PR TITLE
[SMTChecker] Fix ICE in touched vars

### LINKED ISSUE #6563: [SMTChecker] WalletLibrary ICE
WalletLibrary.sol from https://github.com/ConsenSys/mythril-classic/tree/develop/solidity_examples gives:
```
libsolidity/formal/SMTChecker.cpp:1586: void dev::solidity::SMTChecker::mergeVariables(const std::set<const dev::solidity::VariableDeclaration*>&, const dev::solidity::smt::Expression&, const VariableIndices&, const VariableIndices&): Assertion `trueIndex != falseIndex' failed.
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/6563 https://github.com/ethereum/solidity/issues/6009
Depends on https://github.com/ethereum/solidity/pull/6675
```
function f() {
    if (true)
        g();
}
function g() {
    uint x;
    x = 2;
}
```
The issue here was that `x` was considered as touched by `f`, which tried to merge the SSA versions of `x` after `if (true)`. Because this merging is already resolved inside `g` the assertion inside `mergeVariables` failed.
The fix is to only add a certain variable as touched by the queried node if the variable is declared in the same function (even if it actually is in the subtree like in the example above), since the SMTChecker keeps all the local variables of a certain function alive while visiting that function.

### CODE REVIEW

File: libsolidity/formal/VariableUsage.cpp [hunk 1]
```diff
@@ -30,8 +30,25 @@ void VariableUsage::endVisit(Identifier const& _identifier)
...
+		bool inOuterFunction = false;
+		if (isLocal)
+		{
+			solAssert(m_outerFunction, "");
+			auto const& localVars = m_outerFunction->localVariables();
+			inOuterFunction = find(localVars.begin(), localVars.end(), varDecl) != localVars.end();
+			auto const& retVars = m_outerFunction->returnParameters();
+			inOuterFunction |= find_if(retVars.begin(), retVars.end(), [&] (auto var) { return var.get() == varDecl; }) != retVars.end();
+			auto const& paramVars = m_outerFunction->parameters();
+			inOuterFunction |= find_if(paramVars.begin(), paramVars.end(), [&] (auto var) { return var.get() == varDecl; }) != paramVars.end();
```
Comment (leonardoalt) [inline libsolidity/formal/VariableUsage.cpp]: @chriseth any better way to do this check?

Comment (chriseth) [reply libsolidity/formal/VariableUsage.cpp]: You could use the `scope` function on VariableDeclaration. It might also return a `block` but perhaps a variant of that function could be introduced that goes all the way up to the function?

File: libsolidity/formal/VariableUsage.cpp [hunk 2]
```diff
@@ -30,8 +30,25 @@ void VariableUsage::endVisit(Identifier const& _identifier)
 	Declaration const* declaration = _identifier.annotation().referencedDeclaration;
 	solAssert(declaration, "");
 	if (VariableDeclaration const* varDecl = dynamic_cast<VariableDeclaration const*>(declaration))
-		if (_identifier.annotation().lValueRequested)
```
Comment (chriseth) [inline libsolidity/formal/VariableUsage.cpp]: Could keep that check (i.e. do it first) because the other checks might be expensive.

File: libsolidity/ast/AST.h [hunk 3]
```diff
@@ -161,6 +161,9 @@ class Scopable
 	/// @returns the source unit this scopable is present in.
 	SourceUnit const& sourceUnit() const;
 
+	/// @returns the function definition this scopable is present in or nullptr.
+	FunctionDefinition const* functionDefinition() const;
```
Comment (chriseth) [inline libsolidity/ast/AST.h]: Should perhaps also work with modifiers as scopes.

**Comment by chriseth** [comment]
The above comments of course leads to a follow-up question: What about local variables declared inside modifiers that are used by the current function or functions further up the call stack?

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `8be0e6a01cbe05f8888512a7f066e64d14eb9dc5`:
```
Coding style error:
 libsolidity/formal/VariableUsage.cpp:72: for(; it != m_callStack.rend() && !funDef; ++it)

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `b5e0a5f6912309735566d0d2869fec1d95fb842d`:
```
Coding style error:
 libsolidity/formal/VariableUsage.cpp:71: for(auto it = m_callStack.rbegin(); it != m_callStack.rend() && !funDef; ++it)

```
Please check that your changes are working as intended.

**Comment by leonardoalt** [comment]
Took a while to notice :p

**Comment by leonardoalt** [comment]
Do not merge yet, found a problem

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `97a7a370622b28c16a639033d1cc36c300ab9f5c`:
```
Error: Trailing whitespace found:
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:1:pragma experimental SMTChecker; 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:47: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:49: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:53: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:57: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:61: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:65: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:69: 
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:73: 

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `bfc6087cf92032fd18f45151d3b221760504eac9`:
```
Error: Trailing whitespace found:
 test/libsolidity/smtCheckerTests/complex/slither/external_function.sol:1:pragma experimental SMTChecker; 

```
Please check that your changes are working as intended.

**Comment by leonardoalt** [comment]
@chriseth ready for review now

File: libsolidity/formal/SMTChecker.cpp [hunk 4]
```diff
@@ -1946,8 +1952,10 @@ FunctionDefinition const* SMTChecker::inlinedFunctionCallToDefinition(FunctionCa
 
 set<VariableDeclaration const*> SMTChecker::touchedVariables(ASTNode const& _node)
 {
-	solAssert(!m_functionPath.empty(), "");
-	return m_variableUsage.touchedVariables(_node, m_functionPath);
+	solAssert(!m_callStack.empty(), "");
+	vector<CallableDeclaration const*> callStack;
+	for_each(m_callStack.begin(), m_callStack.end(), [&] (auto call) { callStack.push_back(call.first); });
```
Comment (chriseth) [inline libsolidity/formal/SMTChecker.cpp]: Wouldn't `for (auto call: m_callStack) callStack.push_back(call.first);` be shorter and easier to read?

**Review by chriseth — DISMISSED** [review]
Fine apart from the small style comment.

**Comment by leonardoalt** [comment]
Updated

**Review by chriseth — APPROVED** [review]
