### PR TITLE
TestFramework: Merge Options.h into Common.h

### LINKED ISSUE #7112: The function dev::test::Option::get() should be avoided
The function `dev::test::Option::get()` only works properly when run via soltest, it fails to work when used inside isoltest. Because of that, it should be avoided.

The SolidityExecutionFramework uses it to set the evm version, for example.

### PR DESCRIPTION
**Pull request by Marenz**
Merges the Option class into the CommonOption class.
Most stuff here is just renaming, the relevant files to look at are:

* isoltest.cpp
* boostTest.cpp
* Common.[h.cpp]

fixes #7112

### CODE REVIEW

File: test/tools/isoltest.cpp [hunk 1]
```diff
@@ -401,22 +401,25 @@ int main(int argc, char const *argv[])
...
-	solidity::test::IsolTestOptions options(&TestTool::editor);
+	solidity::test::IsolTestOptions* options = nullptr;
 
 	try
 	{
-		if (options.parse(argc, argv))
-			options.validate();
-		else
-			return 1;
+		options = new solidity::test::IsolTestOptions(&TestTool::editor);
```
Comment (ekpyron) [inline test/tools/isoltest.cpp]: Don't, just don't ;-)...

**Review by ekpyron — CHANGES_REQUESTED** [review]
Why do you merge the classes? Are all options in the old options class really shared? And it'd in any case be better to do it separately from the singleton change...

Also, generally, you're probably doing something wrong, whenever you write ``new``... even more so if you don't have a matching ``delete``...
One proper solution would e.g. be to give ``CommonOptions`` a virtual destructor and give it a protected ``static std::unique_ptr<CommonOptions> m_singleton;`` member and have e.g. ``IsoltestOptions`` create it as ``m_singleton = std::make_unique<IsoltestOptions>(...)``. And there's probably other options as well that don't leak memory...

**Comment by Marenz** [comment]
> Why do you merge classes?

Well, initially because @chriseth [said so](https://github.com/ethereum/solidity/issues/7112#issuecomment-518228025): 
> The (boost) options class should be merged into the common options class and the options should be explicitly created. 

And if you think about it, we want `isoltest` and `soltest` to be able to do the same thing and have the same options as much as possible..

The options found in the now removed file were also used for isoltest tests but couldn't actually be changed using the commandline..

Regarding leaking memory.. it is a singleton.. it's created once and kept till the end of life of the program... 

But I kinda expected that someone would yell at me for this :P anyway, I pushed [an alternative](https://github.com/ethereum/solidity/compare/035eeddcadb44da2daadee6f88890e8600b54388..2b10e4709cb2c0db75d38a97e04e1b6816993f7e) for you.

**Comment by ekpyron** [comment]
> Regarding leaking memory.. it is a singleton.. it's created once and kept till the end of life of the program...

You don't intentionally leak memory. Not once, not ever :-).


> But I kinda expected that someone would yell at me for this :P anyway, I pushed [an alternative](https://github.com/ethereum/solidity/compare/035eeddcadb44da2daadee6f88890e8600b54388..2b10e4709cb2c0db75d38a97e04e1b6816993f7e) for you.

I think your alternative is subject to type slicing, but I'd need to recheck...

File: test/tools/isoltest.cpp [hunk 2]
```diff
@@ -401,20 +401,25 @@ int main(int argc, char const *argv[])
...
+		solidity::test::IsolTestOptions options(&TestTool::editor);
+
+		try
+		{
+			if (!options.parse(argc, argv))
+				return -1;
+
 			options.validate();
-		else
+			solidity::test::CommonOptions::setSingleton(std::move(options));
```
Comment (ekpyron) [inline test/tools/isoltest.cpp:414]: I'm pretty sure this will slice ``options``. You can't just assign to a base class by value.

Comment (ekpyron) [reply test/tools/isoltest.cpp:414]: I.e. you can't use an ``optional``, but you need a ``unique_ptr``.

Comment (ekpyron) [reply test/tools/isoltest.cpp:414]: And a virtual destructor in ``CommonOptions``.

File: test/Common.h [hunk 3]
```diff
@@ -41,27 +40,34 @@ static constexpr auto evmoneDownloadLink = "https://github.com/ethereum/evmone/r
 
 struct ConfigException : public util::Exception {};
 
-struct CommonOptions: boost::noncopyable
+struct CommonOptions
```
Comment (chriseth) [inline test/Common.h]: Is this really the set of common options now?

File: test/tools/isoltest.cpp (hunk 2 above)
Comment (Marenz) [reply test/tools/isoltest.cpp:414]: You're right. A unique_ptr it is then

File: test/tools/isoltest.cpp [hunk 4]
```diff
@@ -401,20 +401,26 @@ int main(int argc, char const *argv[])
...
 
-	solidity::test::IsolTestOptions options(&TestTool::editor);
-
-	try
 	{
-		if (options.parse(argc, argv))
-			options.validate();
-		else
+		using IOptions = solidity::test::IsolTestOptions;
+		std::unique_ptr<IOptions> options(new IOptions(&TestTool::editor));
```
Comment (ekpyron) [inline test/tools/isoltest.cpp]:
```suggestion
		auto options = std::make_unique<solidity::test::IsolTestOptions>(&TestTool::editor);
```

Away with the ``new``s ;-D!!!

**Review by ekpyron — CHANGES_REQUESTED** [review]

**Comment by Marenz** [comment]
(pushed)

File: test/boostTest.cpp [hunk 5]
```diff
@@ -123,13 +123,27 @@ int registerTests(
 }
 }
 
+void initializeOptions()
+{
+	using COptions = solidity::test::CommonOptions;
```
Comment (chriseth) [inline test/boostTest.cpp]:
```suggestion
	using CommonOptions = solidity::test::CommonOptions;
```

File: test/boostTest.cpp [hunk 6]
```diff
@@ -123,13 +123,27 @@ int registerTests(
 }
 }
 
+void initializeOptions()
```
Comment (chriseth) [inline test/boostTest.cpp:125]: Is this inside the anonymous namespace?

File: test/libsolutil/UTF8.cpp [hunk 7]
```diff
@@ -150,7 +152,7 @@ hélló
 
 ₠ ₡ ₢ ₣ ₤ ₥
 
-⃐ ⃑ ⃒ ⃓ ⃔ ⃕ ⃖ ⃗ ⃘ ⃙ ⃚
```
Comment (chriseth) [inline test/libsolutil/UTF8.cpp]: please undo

File: test/libsolutil/UTF8.cpp [hunk 8]
```diff
@@ -104,7 +106,7 @@ hélló
 
 ʰ ʱ ʲ ʳ ʴ ʵ
 
-̀ ́ ̂ ̃ ̄ ̅
```
Comment (chriseth) [inline test/libsolutil/UTF8.cpp]: please undo

File: test/tools/isoltest.cpp [hunk 9]
```diff
@@ -401,20 +402,26 @@ int main(int argc, char const *argv[])
...
 	setupTerminal();
 
-	solidity::test::IsolTestOptions options(&TestTool::editor);
-
-	try
 	{
-		if (options.parse(argc, argv))
-			options.validate();
-		else
+		using IOptions = solidity::test::IsolTestOptions;
```
Comment (chriseth) [inline test/tools/isoltest.cpp]: It might be more useful to add `using namespace solidity::test` at the top of this file.

File: test/libsolutil/UTF8.cpp (hunk 8 above)
Comment (Marenz) [reply test/libsolutil/UTF8.cpp]: that must have been an accident... or maybe my editor.. will revert

File: test/libsolutil/UTF8.cpp (hunk 7 above)
Comment (Marenz) [reply test/libsolutil/UTF8.cpp]: that must have been an accident... or maybe my editor.. will revert

**Review by chriseth — CHANGES_REQUESTED** [review]
Looks good otherwise!

File: test/tools/isoltest.cpp (hunk 9 above)
Comment (Marenz) [reply test/tools/isoltest.cpp]: this one is actually only used once, so I just use it directly here

File: test/boostTest.cpp [hunk 10]
```diff
@@ -121,15 +121,27 @@ int registerTests(
...
 test_suite* init_unit_test_suite( int /*argc*/, char* /*argv*/[] )
 {
 	master_test_suite_t& master = framework::master_test_suite();
 	master.p_name.value = "SolidityTests";
-	solidity::test::Options::get().validate();
 
-	bool disableSemantics = !solidity::test::EVMHost::getVM(solidity::test::Options::get().evmonePath.string());
+	initializeOptions();
+
+	bool disableSemantics = !solidity::test::EVMHost::getVM(solidity::test::CommonOptions::get().evmonePath.string());
```
Comment (erak) [inline test/boostTest.cpp:144]: Probably nit-picking: but what about `skipSemanticTests` ?

**Review by erak — CHANGES_REQUESTED** [review]
Builds are failing.

File: test/boostTest.cpp (hunk 10 above)
Comment (Marenz) [reply test/boostTest.cpp:144]: Not sure.. I mean this is just renaming `Options` -> `CommonOptions`..
I can rename that in an extra commit if you want, sure.

**Comment by Marenz** [comment]
Fixed a wrong fix of mine. Everything should be fine now.

**Review by chriseth — APPROVED** [review]
