### PR TITLE
Fix interpreter exp bug.

### LINKED ISSUE #6667: [ossfuzz] Flaky nightly CI failure
## Description

The differential proto fuzzer is consistently failing in the nightly CI. This means that the nightly CI believes there is a difference in traces of unoptimized and optimized yul code.

The failure is seen for

```
{
mstore(1, exp(0xffffffffffffffffffffffffffffffff,exp(0xffffffffffffffffffffffffffffffff,add(1,1))))
}
```

OR

```
{
mstore(exp(0xffffffffffffffffffffffffffffffffffffff,not(1)), 1)
}
```

OR

```
{
mstore(exp(41,not(1)), 1)
}
```

but is not reproducible with clang-9 or clang-6. The CI uses clang-7.

## Environment

- Compiler version: latest develop

### PR DESCRIPTION
**Pull request by chriseth**
Might fix https://github.com/ethereum/solidity/issues/6667

### CODE REVIEW

File: test/tools/yulInterpreter/EVMInstructionInterpreter.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ u256 exp256(u256 _base, u256 _exponent)
 	u256 result = 1;
 	while (_exponent)
 	{
-		if (static_cast<limb_type>(_exponent) & 1)	// If exponent is odd.
+		if (_exponent & 1)
```
Comment (bshastry) [inline test/tools/yulInterpreter/EVMInstructionInterpreter.cpp]: I'm not sure I understand why the cast was necessary.

If I understand correctly `limb_type` is typedef to a machine word (32/64 bit), and the intention in the unpatched version was to downcast u256 to a native word and logical AND it with 1 so that we test for even/odd.

**Comment by bshastry** [comment]
A gas costs test is reporting failing, I'm not sure if it is significant.

**Comment by bshastry** [comment]
LGTM. Could you please add a yul interpreter test like so?

```
{
  mstore(0, exp(3,not(1)))
}
// ----
// Trace:
//   MSTORE_AT_SIZE(0, 32) [8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e39]
// Memory dump:
//      0: 8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e39
// Storage dump:
```

FWIW the buggy version has the following output

```
Trace:
MSTORE_AT_SIZE(0, 32) [0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab]
Memory dump:
     0: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
Storage dump:
```

**Comment by chriseth** [comment]
Thanks! Added the test.

**Review by bshastry — APPROVED** [review]
