### PR TITLE
SMTChecker: Fix SMT logic error when assigning to an array of addresses

### LINKED ISSUE #15308: SMT logic error: sorts are incompatible
## Description

The following code triggers the exception shown bellow in the latest solc version ```0.8.26```. I think the issue is due to the two arrays having a different (but compatible) base type. The problem seems to appear with version ```0.6.9``` (tested on remix).

## Steps to Reproduce

```testcase.sol```

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity =0.8.26;

contract A {}

contract B is A {}

contract C {
    A[10] a;
    B[10] b;

    function f() public {
        a = b;
    }
}
```

```
solc testcase.sol --model-checker-engine chc
```

```
SMT logic error:
./libsmtutil/Z3Interface.cpp(276): Throw in function z3::expr solidity::smtutil::Z3Interface::toZ3Expr(const solidity::smtutil::Expression&)
Dynamic exception type: boost::wrapexcept<solidity::smtutil::SMTLogicError>
std::exception::what: Sorts |contract A_array_tuple| and |contract B_array_tuple| are incompatible
[solidity::util::tag_comment*] = Sorts |contract A_array_tuple| and |contract B_array_tuple| are incompatible
```

## Environment

- Compiler version: ```0.8.26```

### PR DESCRIPTION
**Pull request by pgebal**
There was a SMT logic error when assigning a value of  `address payable[]` type to a variable of type `address[]`.

Closes https://github.com/ethereum/solidity/issues/15308
look at this comment: https://github.com/ethereum/solidity/issues/15308#issuecomment-2332905155

### CODE REVIEW

File: libsolidity/formal/SymbolicTypes.cpp [hunk 1]
```diff
@@ -118,6 +118,10 @@ SortPointer smtSort(frontend::Type const& _type)
 				// use a common sort for functions so pure and view modifier do not cause conflicting SMT types
 				// solc handles types mismtach
 				tupleName = "function";
+			else if (isAddress(*baseType))
+				// use a common sort for functions so pure and view modifier do not cause conflicting SMT types
+				// solc handles types mismtach
+				tupleName = "address";
```
Comment (blishko) [inline libsolidity/formal/SymbolicTypes.cpp]: The comment is incorrect, it should talk about addresses and the `payable` modifier.

File: test/libsolidity/smtCheckerTests/types/array_of_addresses.sol [hunk 2]
```diff
@@ -0,0 +1,14 @@
+// SPDX-License-Identifier: GPL-3.0
+
+pragma solidity >=0.0.0;
+contract C {
+	address[10] a;
+	address payable[10] b;
+
+	function f() public {
+		a = b;
```
Comment (blishko) [inline test/libsolidity/smtCheckerTests/types/array_of_addresses.sol:9]: Maybe you can also assert afterward that `a == b`?

**Review by blishko — CHANGES_REQUESTED** [review]

File: libsolidity/formal/SymbolicTypes.cpp (hunk 1 above)
Comment (pgebal) [reply libsolidity/formal/SymbolicTypes.cpp]: Right, I just copied it and forgot to read through it.

File: test/libsolidity/smtCheckerTests/types/array_of_addresses.sol (hunk 2 above)
Comment (pgebal) [reply test/libsolidity/smtCheckerTests/types/array_of_addresses.sol:9]: I can't do that because of:
`TypeError 2271: Built-in binary operator == cannot be applied to types address[10] storage ref and address payable[10] storage ref.`
I did `assert(a[0] == b[0])` isntead.

**Review by blishko — APPROVED** [review]
LGMT!
