### PR TITLE
Fix isDynamicallyEncoded() for structs containing internal types

### LINKED ISSUE #10516: ICE in `StructType::isDynamicallyEncoded()` when a function has a `memory` struct argument with an internal type inside
## Description

This contract:
```solidity
contract C {
    struct S {
    	function () e;
    }
    function f(S[2] memory s1) public {
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/ast/Types.cpp(2321): Throw in function virtual bool solidity::frontend::StructType::isDynamicallyEncoded() const
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

Looks like all other deaths in isDynamicallyEncoded were fixed, so this is a new variant (the structure looks different to me at a glance).

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.6-develop.2020.11.30+commit.7e7a42c6.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by cameel**
Fixes  #10516.

This PR changes the implementation of `isDynamicallyEncoded()` for structs to just use the member types directly instead of their `interfaceType()`. This does not seem to be causing any problems but I don't know why `interfaceType()` was used there in the first place.

### CODE REVIEW

**Comment by chriseth** [comment]
Why shouldn't `interfaceType` be called here? I actually think that `isDynamicallyEncoded` should not be called on non-external types in the first place. Can you check where it is called from?

**Comment by cameel** [comment]
> Why shouldn't `interfaceType` be called here?

It's not that it shouldn't but I think it does not have to. Couldn't we tell for every type (no matter whether it's a part of the ABI or not) if it's dynamically sized?

> I actually think that `isDynamicallyEncoded` should not be called on non-external types in the first place. Can you check where it is called from?

`TypeChecker::visit(VariableDeclaration)` uses `validForLocation()` on the parameter and for `ArrayType` this function calls `isDynamicallySized()`.

**Comment by chriseth** [comment]
`validForLocation` for structs and arrays should check that they don't contain internal types for calldata. The problem is that internal types are valid for calldata if it is an array or struct and a library is about to be called. I'll investigate a bit more.

**Comment by chriseth** [comment]
I have a different fix and will force-push here shortly.

**Comment by cameel** [comment]
ok. Your fix looks correct to me and passes my test cases.

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -583,13 +583,18 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
...
 			bool isLibraryStorageParameter = (_variable.isLibraryFunctionParameter() && referenceType->location() == DataLocation::Storage);
 			bool callDataCheckRequired = ((_variable.isConstructorParameter() || _variable.isPublicCallableParameter()) && !isLibraryStorageParameter);
 			if (callDataCheckRequired)
-				result = referenceType->validForLocation(DataLocation::CallData);
+			{
+				if (!referenceType->interfaceType(false))
+					solAssert(m_errorReporter.hasErrors(), "");
+				else
+					result = referenceType->validForLocation(DataLocation::CallData);
+			}
```
Comment (bshastry) [inline libsolidity/analysis/TypeChecker.cpp:597]: I don't know what the logic here is. My understanding is that we used to invoke `validForLocation(DataLocation::CallData` meaning that we always checked if it is okay to store the reference type in calldata, for constructor and public variables (I suppose function parameter counts as a public variable). If it couldn't be stored in calldata, we reported an error.

Now, we invoke `validForLocation` only if referenceType->interfaceType(false) is true which means only if the interface type of the variable (that is not in library) exists.

A few questions come up:

- Since we assume `interfaceType(false)`, is there a scenario where validForLocation(DataLocation::CallData) is called without a prior check for `interfaceType(true)`?
- When does a reference type not have an interface type? Presumably when the type is somehow not public exposed? What happens with
- 
```
pragma abicoder v2;

contract C {
    struct S { function() internal a; function() external b; }
    function f(S[2] memory) public {}
}
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -583,13 +583,18 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
 
 	if (auto referenceType = dynamic_cast<ReferenceType const*>(varType))
 	{
-		auto result = referenceType->validForLocation(referenceType->location());
+		BoolResult result = referenceType->validForLocation(referenceType->location());
 		if (result)
 		{
 			bool isLibraryStorageParameter = (_variable.isLibraryFunctionParameter() && referenceType->location() == DataLocation::Storage);
 			bool callDataCheckRequired = ((_variable.isConstructorParameter() || _variable.isPublicCallableParameter()) && !isLibraryStorageParameter);
 			if (callDataCheckRequired)
```
Comment (hrkrshnn) [inline libsolidity/analysis/TypeChecker.cpp:591]: Why do we need call data check for types, even though they don't live in calldata? Is the idea that the types for public function, must be abi encodable, and must have come from calldata?

**Review by hrkrshnn — COMMENTED** [review]
Looks good. I've one question.

File: libsolidity/analysis/TypeChecker.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:597]: The struct does not have an interface type because one of its members does not have an interface type (the internal function). The current logic works because there is another earlier check that looks for a non-interface type. That's why the assertion that checks that there has been a previous error is not failing.

File: libsolidity/analysis/TypeChecker.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/analysis/TypeChecker.cpp:591]: Yes, exactly.

**Review by hrkrshnn — APPROVED** [review]
