### PR TITLE
Internal reverts with reason in debug mode

### LINKED ISSUE #7260: Provide messages for internal reverts and option to remove.
## Description

`abi.decode()` reverts but does not return an error message on failure.

```
Error: VM Exception while processing transaction: revert
```

Adding a revert message like "abi.decode() input too short" would help with debugging.

related to #4224

## Environment

- Compiler version: 0.5.11

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/7260

Missing:
- [x] Check that the encoding actually works
- [x] Write revert messages to `codegen/ABIFunctions.cpp`
- [x] Write tests (missing for ABIFunctions)
- [x] Document new switch for the modes

### CODE REVIEW

File: libsolidity/codegen/CompilerContext.h [hunk 1]
```diff
@@ -219,6 +227,11 @@ class CompilerContext
 		OptimiserSettings const& _optimiserSettings = OptimiserSettings::none()
 	);
 
+	/// If m_revertStrings is Debug, @returns inline assembly code that
+	/// stores @param _message in memory position 0 and reverts.
+	/// Otherwise returns "revert(0, 0)".
+	std::string revertString(std::string const& _message = "") const;
```
Comment (chriseth) [inline libsolidity/codegen/CompilerContext.h]: `revertWithReasonIfDebug`? `revertWithReason`?

File: libsolidity/codegen/CompilerUtils.cpp [hunk 2]
```diff
@@ -277,7 +283,13 @@ void CompilerUtils::abiDecode(TypePointers const& _typeParameters, bool _fromMem
 	size_t encodedSize = 0;
 	for (auto const& t: _typeParameters)
 		encodedSize += t->decodingType()->calldataHeadSize();
-	m_context.appendInlineAssembly("{ if lt(len, " + to_string(encodedSize) + ") { revert(0, 0) } }", {"len"});
+
+	Whiskers templ(R"({
+		if lt(len, <encodedSize>) { <revertString> }
+	})");
+	templ("encodedSize", to_string(encodedSize));
+	templ("revertString", m_context.revertString("Calldata too large"));
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]:
```suggestion
	templ("revertString", m_context.revertString("Calldata too short"));
```

File: libsolidity/codegen/CompilerUtils.cpp [hunk 3]
```diff
@@ -319,19 +331,22 @@ void CompilerUtils::abiDecode(TypePointers const& _typeParameters, bool _fromMem
...
 						if or(
 							gt(array_length, 0x100000000),
 							gt(add(array_data_start, mul(array_length, <item_size>)), input_end)
-						) { revert(0, 0) }
+						) { <revertStringLength> }
 						mstore(dst, array_length)
 						dst := add(dst, 0x20)
 					})");
 					templ("item_size", to_string(arrayType.calldataStride()));
+					templ("revertStringPointer", m_context.revertString("Invalid data pointer"));
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]:
```suggestion
					templ("revertStringPointer", m_context.revertString("Invalid ABI data pointer"));
```

Comment (chriseth) [reply libsolidity/codegen/CompilerUtils.cpp]: Or more general: `ABI decoding error: ...`?

File: libsolidity/codegen/ContractCompiler.cpp [hunk 4]
```diff
@@ -129,7 +129,7 @@ void ContractCompiler::appendCallValueCheck()
 	// Throw if function is not payable but call contained ether.
 	m_context << Instruction::CALLVALUE;
 	// TODO: error message?
-	m_context.appendConditionalRevert();
+	m_context.appendConditionalRevert("Ether sent to non payable function");
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]:
```suggestion
	m_context.appendConditionalRevert("Ether sent to non-payable function");
```

File: libsolidity/codegen/ContractCompiler.cpp [hunk 5]
```diff
@@ -129,7 +129,7 @@ void ContractCompiler::appendCallValueCheck()
 	// Throw if function is not payable but call contained ether.
 	m_context << Instruction::CALLVALUE;
 	// TODO: error message?
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]:
```suggestion

```

File: libsolidity/codegen/ContractCompiler.cpp [hunk 6]
```diff
@@ -409,7 +409,7 @@ void ContractCompiler::appendFunctionSelector(ContractDefinition const& _contrac
 	m_context << notFoundOrReceiveEther;
 
 	if (!fallback && !etherReceiver)
-		m_context.appendRevert();
+		m_context.appendRevert("Contract cannot receive Ether");
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]:
```suggestion
		m_context.appendRevert("Ether sent to non-payable contract.");
```

File: libsolidity/codegen/ContractCompiler.cpp [hunk 7]
```diff
@@ -457,7 +457,7 @@ void ContractCompiler::appendFunctionSelector(ContractDefinition const& _contrac
 			// If the function is not a view function and is called without DELEGATECALL,
 			// we revert.
 			m_context << dupInstruction(2);
-			m_context.appendConditionalRevert();
+			m_context.appendConditionalRevert("Non view function called without DELEGATECALL");
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]:
```suggestion
			m_context.appendConditionalRevert("Non view function of library called without DELEGATECALL");
```

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 8]
```diff
@@ -655,7 +655,7 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 			}
 			else
 				// TODO: Can we bubble up here? There might be different reasons for failure, I think.
-				m_context.appendConditionalRevert(true);
+				m_context.appendConditionalRevert(true, "Uncaught exception in contract creation");
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: We might want to append the original reason here, or just bubble up the reason...

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 9]
```diff
@@ -713,7 +713,7 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 				// Check if zero (out of stack or not enough balance).
 				// TODO: bubble up here, but might also be different error.
 				m_context << Instruction::ISZERO;
-				m_context.appendConditionalRevert(true);
+				m_context.appendConditionalRevert(true, "Probably out of stack or not enough balance during transfer");
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: I would just copy the original message.

Comment (chriseth) [reply libsolidity/codegen/ExpressionCompiler.cpp]: Actually it already does because of the "true"

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 8 above)
Comment (chriseth) [reply libsolidity/codegen/ExpressionCompiler.cpp]: Sorry, forget that.

File: libsolidity/codegen/ExpressionCompiler.cpp (hunk 9 above)
Comment (chriseth) [reply libsolidity/codegen/ExpressionCompiler.cpp]: Sorry, forget about that.

Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: I would just say "uncaught exception" or something like that.

Comment (chriseth) [reply libsolidity/codegen/ExpressionCompiler.cpp]: Or "transfer failed"

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 10]
```diff
@@ -723,13 +723,13 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 		case FunctionType::Kind::Revert:
 		{
 			if (arguments.empty())
-				m_context.appendRevert();
+				m_context.appendRevert("Revert without reason");
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: This is not an internal revert, so we should not modify the message of the user.

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 11]
```diff
@@ -1046,7 +1046,7 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 				m_context.adjustStackOffset(arguments.at(1)->annotation().type->sizeOnStack());
 			}
 			else
-				m_context.appendRevert();
+				m_context.appendRevert("Revert without reason");
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]: Same here.

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 12]
```diff
@@ -2274,7 +2278,7 @@ void ExpressionCompiler::appendExternalFunctionCall(
 	{
 		// Propagate error condition (if CALL pushes 0 on stack).
 		m_context << Instruction::ISZERO;
-		m_context.appendConditionalRevert(true);
+		m_context.appendConditionalRevert(true, "Uncaught exception thrown");
```
Comment (chriseth) [inline libsolidity/codegen/ExpressionCompiler.cpp]:
```suggestion
		m_context.appendConditionalRevert(true, "Uncaught exception");
```

File: libsolidity/codegen/CompilerContext.h (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/codegen/CompilerContext.h]: I'd call it `revertReasonIfDebug` since this doesn't append to the context, only returns the code.

**Comment by leonardoalt** [comment]
Still adding tests but it can start to be reviewed.

**Comment by leonardoalt** [comment]
@chriseth @ekpyron I think you two touched ABI and code generation the most, right? Can we have a call to try to trigger the revert messages I haven't managed yet?

**Comment by leonardoalt** [comment]
@chriseth is it possible that the EVM version does not support return data but supports revert messages?

File: libsolidity/codegen/CompilerUtils.cpp [hunk 13]
```diff
@@ -130,9 +130,13 @@ void CompilerUtils::accessCalldataTail(Type const& _type)
 	// returns the absolute offset of the tail in "base_ref"
 	m_context.appendInlineAssembly(Whiskers(R"({
 		let rel_offset_of_tail := calldataload(ptr_to_tail)
-		if iszero(slt(rel_offset_of_tail, sub(sub(calldatasize(), base_ref), sub(<neededLength>, 1)))) { revert(0, 0) }
+		if iszero(slt(rel_offset_of_tail, sub(sub(calldatasize(), base_ref), sub(<neededLength>, 1)))) { <revertString> }
```
Comment (ekpyron) [inline libsolidity/codegen/CompilerUtils.cpp:133]: @leonardoalt Is this the one you're having trouble to trigger? It's a difficult one indeed and I still don't think it can be triggered without ABIEncoderV2 types.
You can check by commenting out the line - that makes ``SolidityEndToEndTest/calldata_array_dynamic_invalid_static_middle`` and ``semanticTests/abiEncoderV2/calldata_array_dynamic_static_short_decode`` fail (both ABIEncoderV2 cases) - so those test cases indeed do trigger this.

Comment (ekpyron) [reply libsolidity/codegen/CompilerUtils.cpp:133]: These are basically the nice cases that can only happen for three-dimensional arrays that I keep warning people not to forget about :-D.

Comment (ekpyron) [reply libsolidity/codegen/CompilerUtils.cpp:133]: We could actually look into whether we can actually drop the line at least for some types.

File: libsolidity/codegen/ContractCompiler.cpp [hunk 14]
```diff
@@ -441,7 +440,7 @@ void ContractCompiler::appendFunctionSelector(ContractDefinition const& _contrac
 		}
 		else
 			// TODO: error message here?
-			m_context.appendRevert();
+			m_context.appendRevert("Contract cannot receive Ether");
```
Comment (ekpyron) [inline libsolidity/codegen/ContractCompiler.cpp]: This is the other one? I don't think this is actually ``Contract cannot receive Ether``, but rather "Unknown signature and no fallback defined." - and only if you *do* have a receive function.
So I reckon it happens for one of or both of these (the first might be caught elsewhere in the dispatch, but at least the second with non-empty but short calldata works - that's the jump in L390):
```
contract C {
  receive() external {}
}
// ====
// (): 0x42 -> FAILURE
// (): hex"0x42" -> FAILURE
```

You do realize that an easy way to find out how to trigger lines like that is to just comment them out and run the test suite? Here this fails for the second to last call in ``semanticTests/receive/empty_calldata_calls_receive.sol``, so that triggers it... and if there's no test failing, then there's something fishy anyways...

Comment (leonardoalt) [reply libsolidity/codegen/ContractCompiler.cpp]: But look, if there is no fallback and no receive, it shouldn't go into the outer if at all.
If there is one of those, they add a `STOP`. So how does it reach that `REVERT`?!

Comment (leonardoalt) [reply libsolidity/codegen/ContractCompiler.cpp]: Yes, the C++ line is triggered, but I meant the `REVERT` instruction it adds is unreachable because of the previous `STOP`s. That's why no test fails I would say.

Comment (ekpyron) [reply libsolidity/codegen/ContractCompiler.cpp]: Look at the code with added comments about the possible code paths:
```
m_context << u256(4) << Instruction::CALLDATASIZE << Instruction::LT; // This can be true for 0, 1, 2 or 3 bytes of calldata, in which case we jump to "notFoundOrReceiveEther"
m_context.appendConditionalJumpTo(notFoundOrReceiveEther);

// so until we reach "notFoundOrReceiveEther" we're in the case "calldatasize >= 4"

// If there is no interface functions, we skip right over this whole thing.
// If there is some, we add entry points, but we still might fall out of this
// ``if``, if there is no match I think (haven't *really* checked that, though).
if (!interfaceFunctions.empty())
{
	CompilerUtils(m_context).loadFromMemory(0, IntegerType(CompilerUtils::dataStartOffset * 8), true);

	// stack now is: <can-call-non-view-functions>? <funhash>
	vector<FixedHash<4>> sortedIDs;
	for (auto const& it: interfaceFunctions)
	{
		callDataUnpackerEntryPoints.emplace(it.first, m_context.newTag());
		sortedIDs.emplace_back(it.first);
	}
	std::sort(sortedIDs.begin(), sortedIDs.end());
	appendInternalSelector(callDataUnpackerEntryPoints, sortedIDs, notFound, m_optimiserSettings.expectedExecutionsPerDeployment);
}

// So here we get out in one of two cases:
// - calldatasize >= 4 and no matching interface function (at least probably)
// - and definitely for calldatasize < 4 
m_context << notFoundOrReceiveEther;

// Now there is only *one* case in which the revert in question is hit,
// namely assume there *is* a receive function, but *no* fallback function.

if (!fallback && !etherReceiver) // This is "false" in that case, so onto the ``else``
	m_context.appendRevert();
else
{
	if (etherReceiver) // This is "true" in our case.
	{
		// This is the critical jump now: if we have ``calldatasize > 0``. But no reason that we shouldn't.
		m_context << Instruction::CALLDATASIZE;
		m_context.appendConditionalJumpTo(notFound); // So in that case we jump to ``notFound``

               // so we can ignore all this up to ``notFound`` (and jumping *over* the stop you mentioned)

		solAssert(!_contract.isLibrary(), "");
		solAssert(etherReceiver->isReceive(), "");
		solAssert(FunctionType(*etherReceiver).parameterTypes().empty(), "");
		solAssert(FunctionType(*etherReceiver).returnParameterTypes().empty(), "");
		etherReceiver->accept(*this);
		m_context << Instruction::STOP;
	}

        // So we end up here.
	m_context << notFound;
	if (fallback) // But we *don't* have a fallback
	{
		solAssert(!_contract.isLibrary(), "");
		if (!fallback->isPayable() && needToAddCallvalueCheck)
			appendCallValueCheck();

		solAssert(fallback->isFallback(), "");
		solAssert(FunctionType(*fallback).parameterTypes().empty(), "");
		solAssert(FunctionType(*fallback).returnParameterTypes().empty(), "");
		fallback->accept(*this);
		m_context << Instruction::STOP;
	}
	else
		// So finally we *do* arrive here...
		m_context.appendRevert();
}
```

Comment (ekpyron) [reply libsolidity/codegen/ContractCompiler.cpp]: Satisfied by that ;-)?

Comment (ekpyron) [reply libsolidity/codegen/ContractCompiler.cpp]: In short: You jump over the ``STOP`` added in the receive case, in case calldata is non-empty.

Comment (leonardoalt) [reply libsolidity/codegen/ContractCompiler.cpp]: Ah true, missed the jump. Ok, will try to trigger the failure somehow

Comment (ekpyron) [reply libsolidity/codegen/ContractCompiler.cpp]: As I said - this should definitely do:
```
contract C {
  receive() external {}
}
// ====
// (): hex"0x42" -> FAILURE, ...
```

File: libsolidity/codegen/CompilerUtils.cpp [hunk 15]
```diff
@@ -158,9 +161,13 @@ void CompilerUtils::accessCalldataTail(Type const& _type)
...
 				length := calldataload(base_ref)
 				base_ref := add(base_ref, 0x20)
-				if gt(length, 0xffffffffffffffff) { revert(0, 0) }
+				if gt(length, 0xffffffffffffffff) { <revertString> }
 				if sgt(base_ref, sub(calldatasize(), mul(length, <calldataStride>))) { revert(0, 0) }
-			})")("calldataStride", toCompactHexWithPrefix(calldataStride)).render(),
+			})")
+			("calldataStride", toCompactHexWithPrefix(calldataStride))
+			// TODO add test
+			("revertString", m_context.revertReasonIfDebug("Invalid calldata tail length"))
```
Comment (ekpyron) [inline libsolidity/codegen/CompilerUtils.cpp:168]: I would rather say ``Invalid calldata array length.``.
Does this work?
```
contract C {
  function f(uint256[][] calldata x) external {}
}
// ----
// f(uint256[][]): 0x20, 1, 0x20, 0x010000000000000000, 0
```

Comment (ekpyron) [reply libsolidity/codegen/CompilerUtils.cpp:168]: You might need to add ``x[0];`` to ``f``'s body.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 16]
```diff
@@ -319,19 +331,24 @@ void CompilerUtils::abiDecode(TypePointers const& _typeParameters, bool _fromMem
...
-						) { revert(0, 0) }
+						) { <revertStringLength> }
 						mstore(dst, array_length)
 						dst := add(dst, 0x20)
 					})");
 					templ("item_size", to_string(arrayType.calldataStride()));
+					// TODO add test
+					templ("revertStringPointer", m_context.revertReasonIfDebug("ABI memory decoding error: invalid data pointer"));
+					// TODO add test
+					templ("revertStringStart", m_context.revertReasonIfDebug("ABI memory decoding error: invalid data start"));
```
Comment (leonardoalt) [inline libsolidity/codegen/CompilerUtils.cpp]: The two above are never triggered by our current tests, need to find a way to trigger them.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 17]
```diff
@@ -359,24 +376,33 @@ void CompilerUtils::abiDecode(TypePointers const& _typeParameters, bool _fromMem
 					loadFromMemoryDynamic(*TypeProvider::uint256(), !_fromMemory);
 					m_context << Instruction::SWAP1;
 					// stack: input_end base_offset next_pointer data_offset
-					m_context.appendInlineAssembly("{ if gt(data_offset, 0x100000000) { revert(0, 0) } }", {"data_offset"});
+					m_context.appendInlineAssembly(Whiskers(R"({
+						if gt(data_offset, 0x100000000) { <revertString> }
+					})")
+					// TODO add test
+					("revertString", m_context.revertReasonIfDebug("ABI calldata decoding error: invalid data offset"))
```
Comment (leonardoalt) [inline libsolidity/codegen/CompilerUtils.cpp]: This is never triggered by the current tests, need to find a way to trigger.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 18]
```diff
@@ -792,8 +818,8 @@ void CompilerUtils::convertType(
 			solAssert(enumType.numberOfMembers() > 0, "empty enum should have caused a parser error.");
 			m_context << u256(enumType.numberOfMembers() - 1) << Instruction::DUP2 << Instruction::GT;
 			if (_asPartOfArgumentDecoding)
-				// TODO: error message?
-				m_context.appendConditionalRevert();
+				// TODO add test
+				m_context.appendConditionalRevert(false, "Enum out of range");
```
Comment (leonardoalt) [inline libsolidity/codegen/CompilerUtils.cpp:820]: This is never triggered by the current tests, need to find a way to trigger.

File: libsolidity/codegen/ContractCompiler.cpp [hunk 19]
```diff
@@ -954,7 +952,8 @@ void ContractCompiler::handleCatch(vector<ASTPointer<TryCatchClause>> const& _ca
 				revert(0, returndatasize())
 			})");
 		else
-			m_context.appendRevert();
+			// Since both returndata and revert are >=byzantium, this should be unreachable.
+			solAssert(false, "");
```
Comment (leonardoalt) [inline libsolidity/codegen/ContractCompiler.cpp:956]: Does this make sense?

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 20]
```diff
@@ -734,8 +733,8 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 			if (function.kind() == FunctionType::Kind::Transfer)
 			{
 				// Check if zero (out of stack or not enough balance).
-				// TODO: bubble up here, but might also be different error.
 				m_context << Instruction::ISZERO;
+				// Revert message bubbles up.
 				m_context.appendConditionalRevert(true);
```
Comment (leonardoalt) [inline libsolidity/codegen/ExpressionCompiler.cpp:738]: Because it bubbles up we don't add a message.

File: libsolidity/codegen/ExpressionCompiler.cpp [hunk 21]
```diff
@@ -677,7 +677,6 @@ bool ExpressionCompiler::visit(FunctionCall const& _functionCall)
 				m_context << errorCase;
 			}
 			else
-				// TODO: Can we bubble up here? There might be different reasons for failure, I think.
 				m_context.appendConditionalRevert(true);
```
Comment (leonardoalt) [inline libsolidity/codegen/ExpressionCompiler.cpp:680]: Because it bubbles up we don't add a message.

File: libsolidity/codegen/CompilerUtils.cpp [hunk 22]
```diff
@@ -319,19 +331,24 @@ void CompilerUtils::abiDecode(TypePointers const& _typeParameters, bool _fromMem
...
 							gt(array_length, 0x100000000),
 							gt(add(array_data_start, mul(array_length, <item_size>)), input_end)
-						) { revert(0, 0) }
+						) { <revertStringLength> }
 						mstore(dst, array_length)
 						dst := add(dst, 0x20)
 					})");
 					templ("item_size", to_string(arrayType.calldataStride()));
+					// TODO add test
+					templ("revertStringPointer", m_context.revertReasonIfDebug("ABI memory decoding error: invalid data pointer"));
```
Comment (leonardoalt) [inline libsolidity/codegen/CompilerUtils.cpp]: Never triggered by our current tests, need to find a way to trigger it.

**Comment by leonardoalt** [comment]
Missing docs and tests for `ABIFunctions`, but this could be reviewed especially regarding the new messages written in `ABIFunctions.cpp`.

I would leave messages and tests for `YulUtilFunctions.cpp` and `ir/*` for another PR otherwise this one is going to be really large.
This way this PR could be basics + ABIV1 + ABIV2.

**Comment by leonardoalt** [comment]
Created an issue for the Yul revert strings https://github.com/ethereum/solidity/issues/8252

**Comment by leonardoalt** [comment]
Decided in call: won't create tests for all cases that are unreachable in our current tests.

**Comment by leonardoalt** [comment]
Is this enough docs, or do we need more?

File: libsolidity/codegen/ContractCompiler.cpp [hunk 23]
```diff
@@ -954,7 +952,8 @@ void ContractCompiler::handleCatch(vector<ASTPointer<TryCatchClause>> const& _ca
 				revert(0, returndatasize())
```
Comment (leonardoalt) [inline libsolidity/codegen/ContractCompiler.cpp:952]: One idea here could be to check whether `returndatasize()` is 0, and if yes, add string `Uncaught exception` or something like that. Not sure if too pedantic though.

File: Changelog.md [hunk 24]
```diff
@@ -7,6 +7,7 @@ Language Features:
 Compiler Features:
  * Code Generator: Use ``calldatacopy`` instead of ``codecopy`` to zero out memory past input.
  * AST: Add a new node for doxygen-style, structured documentation that can be received by contract, function, event and modifier definitions.
+ * Debug: Inject strings for compiler-generated internal reverts when using the ``--revert-strings`` option or the ``settings.debug.revertStrings`` setting on ``debug`` mode.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Debug: Provide reason strings for compiler-generated internal reverts when using the ``--revert-strings debug`` / ``settings.debug.revertStrings = "debug"`` option.
```

File: libsolidity/codegen/ABIFunctions.cpp [hunk 25]
```diff
@@ -180,11 +180,12 @@ string ABIFunctions::tupleDecoder(TypePointers const& _types, bool _fromMemory)
 
 		Whiskers templ(R"(
 			function <functionName>(headStart, dataEnd) <arrow> <valueReturnParams> {
-				if slt(sub(dataEnd, headStart), <minimumSize>) { revert(0, 0) }
+				if slt(sub(dataEnd, headStart), <minimumSize>) { <revertString> }
 				<decodeElements>
 			}
 		)");
 		templ("functionName", functionName);
+		templ("revertString", revertReasonIfDebug("ABI decoding error: tuple data too short"));
```
Comment (chriseth) [inline libsolidity/codegen/ABIFunctions.cpp]: Should we shorten the strings so that they are at most 32 characters long? `ABI decoding: tuple data too short`?

File: libsolidity/codegen/ABIFunctions.cpp [hunk 26]
```diff
@@ -1159,7 +1166,12 @@ string ABIFunctions::abiDecodingFunctionArray(ArrayType const& _type, bool _from
 		}
 		else
 		{
-			templ("staticBoundsCheck", "if gt(add(src, mul(length, " + calldataStride + ")), end) { revert(0, 0) }");
+			templ("staticBoundsCheck", "if gt(add(src, mul(length, " +
```
Comment (chriseth) [inline libsolidity/codegen/ABIFunctions.cpp:1169]:
```suggestion
			templ("staticBoundsCheck",
    			"if gt(add(src, mul(length, " +
```

File: libsolidity/codegen/CompilerUtils.cpp [hunk 27]
```diff
@@ -359,24 +375,33 @@ void CompilerUtils::abiDecode(TypePointers const& _typeParameters, bool _fromMem
...
 					m_context << Instruction::DUP3 << Instruction::ADD;
 					// stack: input_end base_offset next_pointer array_head_ptr
-					m_context.appendInlineAssembly(
-						"{ if gt(add(array_head_ptr, 0x20), input_end) { revert(0, 0) } }",
-						{"input_end", "base_offset", "next_ptr", "array_head_ptr"}
-					);
+					m_context.appendInlineAssembly(Whiskers(R"({
+						if gt(add(array_head_ptr, 0x20), input_end) { <revertString> }
+					})")
+					("revertString", m_context.revertReasonIfDebug("ABI calldata decoding error: invalid head pointer"))
```
Comment (chriseth) [inline libsolidity/codegen/CompilerUtils.cpp]: why explicit "calldata"?

File: libsolidity/codegen/ContractCompiler.cpp [hunk 28]
```diff
@@ -457,7 +455,7 @@ void ContractCompiler::appendFunctionSelector(ContractDefinition const& _contrac
 			// If the function is not a view function and is called without DELEGATECALL,
 			// we revert.
 			m_context << dupInstruction(2);
-			m_context.appendConditionalRevert();
+			m_context.appendConditionalRevert(false, "Non view function of library called without DELEGATECALL");
```
Comment (chriseth) [inline libsolidity/codegen/ContractCompiler.cpp]:
```suggestion
			m_context.appendConditionalRevert(false, "Non-view function of library called without DELEGATECALL");
```

File: libsolidity/codegen/ContractCompiler.cpp (hunk 19 above)
Comment (chriseth) [reply libsolidity/codegen/ContractCompiler.cpp:956]: Can it be triggered?

File: libsolidity/codegen/YulUtilFunctions.cpp [hunk 29]
```diff
@@ -1905,3 +1905,42 @@ string YulUtilFunctions::readFromMemoryOrCalldata(Type const& _type, bool _fromC
 		.render();
 	});
 }
+
+string YulUtilFunctions::revertReasonIfDebug(RevertStrings revertStrings, string const& _message)
+{
+	if (revertStrings >= RevertStrings::Debug && !_message.empty())
+	{
+		Whiskers templ(R"({
+			let reasonLen := <length>
```
Comment (chriseth) [inline libsolidity/codegen/YulUtilFunctions.cpp]: Do you need a local variable for that?

File: test/libsolidity/StandardCompiler.cpp [hunk 30]
```diff
@@ -397,15 +398,15 @@ BOOST_AUTO_TEST_CASE(basic_compilation)
 		"{\"begin\":0,\"end\":14,\"name\":\"PUSH\",\"value\":\"40\"},"
 		"{\"begin\":0,\"end\":14,\"name\":\"MSTORE\"},"
 		"{\"begin\":0,\"end\":14,\"name\":\"CALLVALUE\"},"
-		"{\"begin\":8,\"end\":17,\"name\":\"DUP1\"},"
```
Comment (chriseth) [inline test/libsolidity/StandardCompiler.cpp:400]: Why did this change?

**Comment by chriseth** [comment]
Looks good!

File: test/libsolidity/StandardCompiler.cpp (hunk 30 above)
Comment (leonardoalt) [reply test/libsolidity/StandardCompiler.cpp:400]: Still trying to figure it out

File: libsolidity/codegen/CompilerUtils.cpp (hunk 27 above)
Comment (leonardoalt) [reply libsolidity/codegen/CompilerUtils.cpp]: Because it was easier to test, since some of the reverts would have the same message and it was hard to know which one was being tested.

File: libsolidity/codegen/ABIFunctions.cpp (hunk 25 above)
Comment (leonardoalt) [reply libsolidity/codegen/ABIFunctions.cpp]: All of them? Can do

Comment (chriseth) [reply libsolidity/codegen/ABIFunctions.cpp]: Just a suggestion.

File: libsolidity/codegen/ContractCompiler.cpp (hunk 19 above)
Comment (leonardoalt) [reply libsolidity/codegen/ContractCompiler.cpp:956]: Not by any of our tests, and I couldn't manually.

File: libsolidity/codegen/ABIFunctions.cpp (hunk 25 above)
Comment (leonardoalt) [reply libsolidity/codegen/ABIFunctions.cpp]: This specific one would have 34. We could have a rule that the message won't be longer than 32 which makes it easier, but the messages will be a lot less precise. I'm fine with either. What do you think?

Comment (chriseth) [reply libsolidity/codegen/ABIFunctions.cpp]: We should not lose precision, but the fact that this already is an error seems redundant.

Comment (leonardoalt) [reply libsolidity/codegen/ABIFunctions.cpp]: Fair enough

Comment (leonardoalt) [reply libsolidity/codegen/ABIFunctions.cpp]: Do you think it would make sense to also remove `tuple/array`, `calldata/memory` from the message?

Comment (chriseth) [reply libsolidity/codegen/ABIFunctions.cpp]: Don't strive too much to make it short, it was just about the "error" that seemed redundant.

File: test/libsolidity/StandardCompiler.cpp (hunk 30 above)
Comment (leonardoalt) [reply test/libsolidity/StandardCompiler.cpp:400]: @chriseth I still don't really know why this happened. Because in some places the code now uses `appendInlineAssembly` instead of just appending `revert(0, 0)`, `/* CODEGEN ... */` was added to some instructions. I suspect it's related to that. Any hints you can think of?

Comment (chriseth) [reply test/libsolidity/StandardCompiler.cpp:400]: ah yes! It might use the source locations of the inline assembly string.

**Comment by chriseth** [comment]
Looks good! Please squash and merge.

**Comment by leonardoalt** [comment]
Squashed

**Comment by leonardoalt** [comment]
@chriseth please approve

**Review by chriseth — APPROVED** [review]
