### PR TITLE
Fix ICE caused by an array of mappings

### LINKED ISSUE #7410: ICE on push to array with storage mapping
## Description

The following internal compiler error is thrown in the scenario below:
```
InternalCompilerError: Invalid non-value type for assignment.
            data.map.push(storageMapping);
            ^---------------------------^
```

## Steps to Reproduce

```
contract C {
    struct Data {
        mapping(uint=>uint)[] map;
    }
    
    Data data;
    mapping(uint=>uint) storageMapping;
    
    constructor() public {
        for (uint i = 0; i < 6; i++)
            data.map.push(storageMapping);
    }
}
```

### PR DESCRIPTION
**Pull request by a3d4**
Fixes #7410 by disallowing `.push(<arg>)` for storage arrays with mappings.

@chriseth @leonardoalt @hrkrshnn 

~~From the #7410 discussion, I somewhat concluded that the idea is to forbid arrays with (nested) mappings.~~

~~I added a simple check and updated several test cases (more needs to be updated). Is it the intended direction? The impact (in terms of the number of failing tests) is rather big.~~

Disallows `.push(<arg>)` ~~and `.pop()`~~ for storage arrays with nested mappings.

### CODE REVIEW

**Comment by chriseth** [comment]
I don't think we should disallow them - sorry :)

**Comment by a3d4** [comment]
> I don't think we should disallow them - sorry :)

Should we move #7410 back from the implementation backlog then? Or is there a consensus how to proceed?

**Comment by hrkrshnn** [comment]
One way to proceed is to disallow `push` and `pop` for arrays (state variables) containing mappings.

**Comment by cameel** [comment]
@hrkrshnn I just noticed that we already have an issue about that in the design backlog so it's probably the way to go: #8535.

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -2681,6 +2681,16 @@ bool TypeChecker::visit(MemberAccess const& _memberAccess)
 				_memberAccess.location(),
 				"Using \"." + memberName + "(...)\" is deprecated. Use \"{" + memberName + ": ...}\" instead."
 			);
+
+		if (
+			((funType->kind() == FunctionType::Kind::ArrayPush && arguments.value().numArguments() != 0) || funType->kind() == FunctionType::Kind::ArrayPop) &&
+			exprType->containsNestedMapping()
+		)
```
Comment (a3d4) [inline libsolidity/analysis/TypeChecker.cpp]:
```
if (
    auto arrayType = dynamic_cast<ArrayType const*>(exprType);
	arrayType &&
	arrayType->location() == DataLocation::Storage &&
	arrayType->containsNestedMapping() &&
	((memberName == "push" && arguments.value().numArguments() != 0) || memberName == "pop")
)
```
Would this be better?

**Comment by a3d4** [comment]
Several tests fail because of `.pop()`. Should I push to `breaking`?

**Comment by chriseth** [comment]
Disallowing `.push(<arg>)` is a bugfix to develop. Disallowing `.pop()` should be a feature for breaking (if we want it).

Just out of curiosity: `.push()` is fine, right?

**Comment by a3d4** [comment]
> `.push()` is fine, right?

In the sense that it does not crash the compiler, yes.

**Review by chriseth — APPROVED** [review]
