### PR TITLE
[SMTChecker] Fix CHC false positives when using branches inside modifiers

### LINKED ISSUE #10200: [SMTChecker] CHC reports false negatives in modifiers with branches
```
pragma experimental SMTChecker;
contract C {
    uint x;
    modifier m(uint z) {
        if (z == 10)
            x = 2;
        _; 
        if (z == 10)
            x = 4;
    }
    function f() m(10) internal {
        x = 3;
    }
    function g() public {
        x = 0;
        f();
        // reports false positive
        assert(x == 4);
        // reports fail correctly
        assert(x == 3);
    }
}
```

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/10200

The fix is to also add modifiers' parameters and local variables to FunctionBlock predicates as local variables of the function, since modifiers are inlined.
This is also necessary for early return, which is where the bug was found.

### CODE REVIEW

**Review by blishko — COMMENTED** [review]
This looks good to me!

File: libsolidity/formal/SMTEncoder.h [hunk 1]
```diff
@@ -71,6 +71,9 @@ class SMTEncoder: public ASTConstVisitor
 	static std::vector<VariableDeclaration const*> stateVariablesIncludingInheritedAndPrivate(ContractDefinition const& _contract);
 	static std::vector<VariableDeclaration const*> stateVariablesIncludingInheritedAndPrivate(FunctionDefinition const& _function);
 
+	static std::vector<VariableDeclaration const*> localVariablesIncludingModifiers(FunctionDefinition const& _function);
+	static std::vector<VariableDeclaration const*> modifiersVariables(FunctionDefinition const& _function);
```
Comment (mijovic) [inline libsolidity/formal/SMTEncoder.h:75]: Can this function be protected?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.h:75]: They can, I've just been adding the `static` ones as public just in case they're used from the outside somewhere, but can move into protected

Comment (mijovic) [reply libsolidity/formal/SMTEncoder.h:75]: > They can, I've just been adding the `static` ones as public just in case they're used from the outside somewhere, but can move into protected

If they will be used, let's leave them public than

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.h:75]: Currently they're only used by the SMTEncoder itself, I made it public "just in case"

**Review by mijovic — APPROVED** [review]
Looks good!
