### PR TITLE
[SMTChecker] Fix ICE when inlining functions from different source

### LINKED ISSUE #7162: [SMTChecker] ICE inline function that uses state variables from another source
From https://github.com/ethereum/solidity/issues/7011

To trigger this bug you need two files:

```
// one.sol
library L {
	uint constant one = 1;
	function f() internal pure returns (uint) {
		return one;
	}
}
```

```
pragma experimental SMTChecker;

import 'one.sol';

contract C {
	function g(uint x) public pure {
		uint y = L.f();
		assert(x > y);
	}
}
```

The cause of the bug is that state variables in imported code are not handled properly. If the library and the contract are in the same file it works fine.

### PR DESCRIPTION
**Pull request by leonardoalt**
and use state vars.

Fixes #7162

### CODE REVIEW

**Comment by leonardoalt** [comment]
Tests still need to be fixed.

**Comment by leonardoalt** [comment]
This is ready for review

File: libsolidity/ast/AST.cpp [hunk 1]
```diff
@@ -109,6 +109,16 @@ TypePointer ImportDirective::type() const
 	return TypeProvider::module(*annotation().sourceUnit);
 }
 
+vector<VariableDeclaration const*> ContractDefinition::stateVariablesWithInheritance() const
```
Comment (chriseth) [inline libsolidity/ast/AST.cpp]:
```suggestion
vector<VariableDeclaration const*> ContractDefinition::stateVariablesIncludingInherited() const
```
?

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -1158,6 +1161,12 @@ void SMTEncoder::initializeFunctionCallParameters(CallableDeclaration const& _fu
 			}
 }
 
+void SMTEncoder::initializeStateVariables(ContractDefinition const& _contract)
+{
+	for (auto var: _contract.stateVariablesWithInheritance())
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp]: Is it fine that this also returns constants?

File: libsolidity/formal/BMC.cpp [hunk 3]
```diff
@@ -120,8 +120,19 @@ bool BMC::visit(ContractDefinition const& _contract)
...
+{
+	SMTEncoder::endVisit(_contract);
+}
+
 bool BMC::visit(FunctionDefinition const& _function)
 {
+	auto contract = dynamic_cast<ContractDefinition const*>(_function.scope());
+	solAssert(contract, "");
+	solAssert(m_currentContract, "");
+	if (contract != m_currentContract)
```
Comment (chriseth) [inline libsolidity/formal/BMC.cpp]: Should be something like `cotract is not in inheritance hierarchy of m_currentContract`

File: Changelog.md [hunk 4]
```diff
@@ -23,6 +23,7 @@ Bugfixes:
  * SMTChecker: Fix pointer knowledge erasing in loops.
  * SMTChecker: Fix internal error when using compound bitwise assignment operators inside branches.
  * SMTChecker: Fix internal error when inlining a function that returns a tuple containing an unsupported type inside a branch.
+ * SMTChecker: Fix internal error when inlining functions from a different source that use state variables.
```
Comment (Marenz) [inline Changelog.md]:
```suggestion
 * SMTChecker: Fix internal error when inlining functions from a different source that uses state variables.
```

Comment (chriseth) [reply Changelog.md]: I think the funcitons use the state variables, not the source.

Comment (Marenz) [reply Changelog.md]: Ah. I got confused then.

File: libsolidity/formal/SMTEncoder.cpp (hunk 2 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: Yep that's intended.

File: libsolidity/formal/BMC.cpp (hunk 3 above)
Comment (leonardoalt) [reply libsolidity/formal/BMC.cpp]: I was wondering why the tests actually passed even though this was wrong.
The reason is that `initializeStateVariables` only calls `createVariable` which does nothing if it was already created, so that's why it was safe.
I'll still push the fix to this soon.

**Comment by leonardoalt** [comment]
Updated

File: Changelog.md [hunk 5]
```diff
@@ -27,6 +27,7 @@ Bugfixes:
...
```
Comment (erak) [inline Changelog.md]:
```suggestion
 * SMTChecker: Fix internal error when inlining functions from a different source that uses state variables.
```

Comment (leonardoalt) [reply Changelog.md]: I think this is the same that Marenz suggested here: https://github.com/ethereum/solidity/pull/7170#discussion_r311650429 ;)
The `functions` use the state variables, not the `source`

Comment (leonardoalt) [reply Changelog.md]: Maybe I should rephrase it, seems to be confusing

**Review by erak — DISMISSED** [review]

**Comment by leonardoalt** [comment]
@erak updated

**Review by erak — APPROVED** [review]
