### PR TITLE
Test low level calls with correct and incorrect encodings

### LINKED ISSUE #7173: [Abiv2 proto fuzzer] Test invalid encodings correctly fail
## Abstract

The current abiv2 proto fuzzer only tests that `decode(valid_encoding(value)) == value`. This issue tracks support for `decode(invalid_encoding(value)) != value)`

## Motivation

One way to construct invalid_encoding is to crop a valid encoding. Example

```
contract C {
  uint8[][2] y;

function f(uint8[][2] x) returns (uint) {
  if (x.length !=2 ) return 2;
  ...
}

function test() returns (bool) {
  y[0].length = 1;
  y[1].length = 2;
  y[0][0] = 3;
  y[1][0] = 4;
  y[1][1] = 5;
  bytes memory validEncoding = abi.encode(y);
  bytes memory cutOffEncoding = new bytes(validEncoding.length/2 + 4);
  cutOffEncoding[0] = <first_four_bytes_of_keccak_of_function_f>;
  for(uint i=0; i < cutOffEncoding.length; i++)
	cutOffEncoding[i + 4] = validEncoding[i];
  // Use a low-level call that tests decoding of invalid encoding for a call to function `f`
  (bool success,) = this.call(cutoffEncoding);
  return success;
}
```

In the proto fuzzer c++ harness, we expect success to be `false` and the execution to not revert (as before).

## Specification

This can be implemented as follows. We add a new field to the abi proto specification called `invalid_encoding_length`. The value of this field will be used to obtain invalid encoding length as follows

```
invalidLength = invalid_encoding_length % validEncodingLength
```

The solidity code that can be used to do this is as follows

```
	/// Accepts function selector, correct argument encoding, and length of invalid encoding and returns
	/// the correct and incorrect abi encoding for calling the function specified by the function selector.
	function createEncoding(bytes4 funcSelector, bytes memory argumentEncoding, uint invalidLengthFuzz)
		internal pure returns (bytes memory, bytes memory)
	{
		bytes memory validEncoding = new bytes(4 + argumentEncoding.length);
		// Ensure that invalidEncoding crops at least one and at most all bytes from correct encoding.
		uint invalidLength = invalidLengthFuzz % argumentEncoding.length;
		bytes memory invalidEncoding = new bytes(4 + invalidLength);
		for (uint i = 0; i < 4; i++)
			validEncoding[i] = invalidEncoding[i] = funcSelector[i];
		for (uint i = 0; i < argumentEncoding.length; i++)
			validEncoding[i+4] = argumentEncoding[i];
		for (uint i = 0; i < invalidLength; i++)
			invalidEncoding[i+4] = argumentEncoding[i];
		return (validEncoding, invalidEncoding);
	}

	/// Accepts function selector, correct argument encoding, and an invalid encoding length as input.
	/// Returns a non-zero value if either call with correct encoding fails or call with incorrect encoding
	/// succeeds. Returns zero if both calls meet expectation.
	function checkEncodedCall(bytes4 funcSelector, bytes memory argumentEncoding, uint invalidLengthFuzz) public returns (uint)
	{
		(bytes memory validEncoding, bytes memory invalidEncoding) = createEncoding(funcSelector, argumentEncoding, invalidLengthFuzz);
		(bool success, ) = address(this).call(validEncoding);
		// Return non-zero value if call fails for correct encoding
		if (success == false)
			return 400000;
		(success, ) = address(this).call(invalidEncoding);
		// Return non-zero value if call succeeds for incorrect encoding
		if (success == true)
			return 400001;
		return 0;
	}
```

### PR DESCRIPTION
**Pull request by bshastry**
fixes #7173

### CODE REVIEW

File: test/tools/ossfuzz/abiV2ProtoFuzzer.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ static size_t const expectedOutputLength = 32;
 /// Expected output value is decimal 1000 or hex 03E8
```
Comment (ekpyron) [inline test/tools/ossfuzz/abiV2ProtoFuzzer.cpp]: The change below suggests the comment needs to be updated.

File: test/tools/ossfuzz/protoToAbiV2.cpp [hunk 2]
```diff
@@ -708,6 +723,42 @@ void ProtoConverter::writeHelperFunctions()
...
 		return true;
 	}
+
+	/// Accepts function selector, correct argument encoding, and length of invalid encoding and returns
+	/// the correct and incorrect abi encoding for calling the function specified by the function selector.
+	function createEncoding(bytes4 funcSelector, bytes memory argumentEncoding, uint invalidLengthFuzz)
+		internal pure returns (bytes memory, bytes memory)
+	{
+		bytes memory validEncoding = new bytes(4 + argumentEncoding.length);
+		// Ensure that invalidEncoding crops at least one and at most all bytes from correct encoding.
```
Comment (ekpyron) [inline test/tools/ossfuzz/protoToAbiV2.cpp:733]: We can leave it like this for now and see what happens, but be aware:
It might be that ``abi.encode`` always adds padding to the argument encoding and that on the other hand decoding will not require that padding - as a consequence cropping one byte might not be enough to ensure failure (i.e. we might need to crop at least 31 bytes). (Consider a function taking a ``bytes`` argument of length 3 - I think ``abi.encode`` might pad the three bytes with zeros to 32 bytes, but even without those zeros the encoding is probably still considered valid and will decode just fine)

But yeah - I'm not entirely sure about this, so we'd need to verify this - and it might be just fine to keep it like this and revisit once we get a false positive due to this.

File: test/tools/ossfuzz/protoToAbiV2.cpp [hunk 3]
```diff
@@ -690,10 +690,25 @@ void ProtoConverter::visit(TestFunction const& _x)
...
 			return returnVal;
-		return (uint(1000) + this.coder_external(<parameter_names>));
+
+		returnVal = this.coder_external(<parameter_names>);
+		if (returnVal != 0)
+			return uint(200000) + returnVal;
+
+		bytes memory argumentEncoding = abi.encode(<parameter_names>);
+
+		returnVal = checkEncodedCall(this.coder_public.selector, argumentEncoding, <invalidLengthFuzz>);
```
Comment (ekpyron) [inline test/tools/ossfuzz/protoToAbiV2.cpp:700]: Ah yes, I hadn't thought about ``.selector`` - makes a lot of sense to use for this here.

**Review by ekpyron — COMMENTED** [review]
Looks good to me apart from the one comment that seems to need fixing!

File: test/tools/ossfuzz/abiV2ProtoFuzzer.cpp (hunk 1 above)
Comment (bshastry) [reply test/tools/ossfuzz/abiV2ProtoFuzzer.cpp]: Oh right! Thank you @ekpyron , pushed a fix for this.

File: test/tools/ossfuzz/protoToAbiV2.cpp (hunk 2 above)
Comment (bshastry) [reply test/tools/ossfuzz/protoToAbiV2.cpp:733]: That's interesting. I will make a note of this. Would you rather I copy-paste your warning as a comment in the code?

File: test/tools/ossfuzz/protoToAbiV2.cpp (hunk 3 above)
Comment (bshastry) [reply test/tools/ossfuzz/protoToAbiV2.cpp:700]: I wasn't very sure when I took this approach, but in the end it worked out I guess :-)

File: test/tools/ossfuzz/protoToAbiV2.cpp (hunk 2 above)
Comment (ekpyron) [reply test/tools/ossfuzz/protoToAbiV2.cpp:733]: As you like :-). We could also just check whether this is indeed a problem right away...

**Review by ekpyron — APPROVED** [review]
Approving this already despite the potential padding issue, which we might address now or later.

File: test/tools/ossfuzz/protoToAbiV2.cpp (hunk 2 above)
Comment (bshastry) [reply test/tools/ossfuzz/protoToAbiV2.cpp:733]: Actually, the proto fuzzer always initializes a `bytes` argument with a value that is exactly 32 bytes in size. Perhaps, this is a different issue that needs fixing? i.e., we should be intializing variables of type `bytes` with literals that are shorter than 32 bytes? Or perhaps even longer than 32 bytes?

The routine that provides the literal used to initialize a `bytes` or a `string` type variable is this

https://github.com/ethereum/solidity/blob/cd563e526a92721a1e9e1633f5e2c9e53e77b242/test/tools/ossfuzz/protoToAbiV2.h#L242-L245

The routine hashes a monotonically increasing counter using  `keccak256` and assigns  the resulting 32 byte hash value (in hex encoding minus the `0x` prefix) to a variable of `bytes` or `string` type. The initialized value is a string literal (that holds the hash value).

Comment (bshastry) [reply test/tools/ossfuzz/protoToAbiV2.cpp:733]: Moving this discussion to an independent issue #7180

Comment (ekpyron) [reply test/tools/ossfuzz/protoToAbiV2.cpp:733]: I think it definitely makes sense to test longer and shorter bytes and string arrays, yes.
