### PR TITLE
SMTChecker: Fix crash on external function call wrapped in 1-tuple

### LINKED ISSUE #15817: Enabling the trusted `ext-calls` option causes solc to generate an `Unreachable` Internal Compiler Error.
Hi! Compiling the following Solidity code with `solc a.sol --model-checker-engine all --model-checker-ext-calls trusted` results in an internal compiler error.

```solidity
contract C {
    function f() external {}
    function g() public {
        (this.f)();
    }
}
```

Output:

```
Internal compiler error:
/solidity/libsolidity/formal/SMTEncoder.cpp(2872): Throw in function solidity::smtutil::Expression solidity::frontend::SMTEncoder::contractAddressValue(const solidity::frontend::FunctionCall&)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Unreachable!
[solidity::util::tag_comment*] = Unreachable!
```

Solc version: `Version: 0.8.29-develop.2025.2.1+commit.170b86fa.Linux.g++`

### PR DESCRIPTION
**Pull request by blishko**
The function call needs to be unwrapped from within nested parentheses to get the proper call expression.

Fixes #15817.

### CODE REVIEW

File: libsolidity/formal/CHC.cpp [hunk 1]
```diff
@@ -927,17 +927,6 @@ void CHC::internalFunctionCall(FunctionCall const& _funCall)
 	Expression const* calledExpr = &_funCall.expression();
 	auto funType = dynamic_cast<FunctionType const*>(calledExpr->annotation().type);
 
-	auto contractAddressValue = [this](FunctionCall const& _f) {
```
Comment (clonker) [inline libsolidity/formal/CHC.cpp:930]: I guess this is simply unused?

**Review by clonker — APPROVED** [review]
At first, I was a bit worried about `innermostTuple` returning a pointer which could technically be null. But turns out the function never returns a null pointer and changing that is besides the point of the PR. LGTM.

**Comment by blishko** [comment]
> At first, I was a bit worried about `innermostTuple` returning a pointer which could technically be null. But turns out the function never returns a null pointer and changing that is besides the point of the PR. LGTM.

Exactly!
I was thinking of changing it to return a reference, but I will try to do that in a separate PR.

File: libsolidity/formal/CHC.cpp (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/CHC.cpp:930]: This lambda was exactly the same as `SMTEncoder::contractAddressValue`.
I did not dig in the history, but I assume it is a relict of some refactoring/generalization.
