### PR TITLE
solc crashes without 'export LC_ALL=C'

### LINKED ISSUE #674: solc crashes without 'export LC_ALL=C'
#### System information

Geth version: 1.5.0-unstable
OS & Version: Ubuntu 14.04.4
#### Expected behaviour

Solc must run normally.
#### Actual behaviour

It crashes and generates core file.
#### Steps to reproduce the behaviour

``` bash
ubuntu@xxx:~/$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
C
C.UTF-8
en_US.utf8
POSIX

ubuntu@xxx:~/$ solc SomeContract.sol
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)
```

Then i added 'export LC_ALL=C' and everything went normally.

### PR DESCRIPTION
**Pull request by cjgdev**
This pull request fixes #674. The issue is that it is possible for the POSIX system environment to be invalid when the program starts, causing a runtime exception to be thrown. The solution is to call setlocale to test that setting the user defined default succeeds, only if the call fails then adjust the environment setting to a reasonable default (else the only viable course of action for the program would be to exit).

### CODE REVIEW

File: lllc/main.cpp [hunk 1]
```diff
@@ -52,10 +53,20 @@ void version()
 	exit(0);
 }
 
+void setEnv() {
+	std::setlocale(LC_ALL, "C");
+#if !defined(WIN32) && !defined(MAC_OSX) && !defined(__FreeBSD__) && !defined(__OpenBSD__)
```
Comment (chriseth) [inline lllc/main.cpp]: To simplify things, I guess it is fine to just stay at the `C`-locale. I hope we do not use any locale-specific code in the compiler itself (i.e. the generated code should not depend on that). The only other locale-specific thing I can think of are low-level error messages, and I think it is not too bad if they are not localized.

**Comment by chriseth** [comment]
Wonderful, thanks!

File: lllc/main.cpp [hunk 2]
```diff
@@ -52,10 +53,20 @@ void version()
...
+	if (!std::setlocale(LC_ALL, "")) {
+		setenv("LC_ALL", "C", 1);
```
Comment (cjgdev) [inline lllc/main.cpp:74]: @chriseth Thank you for reviewing my pull request. These lines are important to ensure the program behaves in the least surprising way. Calling setlocale(LC_ALL, "C") is not all that is required to fix the problem where the user specified default locale is _invalid_. 

The call to setlocale with the empty string allows us to test whether the environment setting is valid (return non-NULL), and if not (return NULL) then we modify the process environment to a sensible default. In the latter case the call to setenv will prevent the runtime error exception.

File: lllc/main.cpp [hunk 3]
```diff
@@ -52,10 +53,20 @@ void version()
 	exit(0);
 }
 
+void setEnv() {
```
Comment (chriseth) [inline lllc/main.cpp]: Style: All `{` go to the next line (also for `if`).

**Comment by chriseth** [comment]
Ok, I think I understand this better now, thanks! The documentation for `setlocale` tells that "During program startup, the equivalent of `std::setlocale(LC_ALL, "C");` is executed before any user code is run." - so the first call seems redundant, doesn't it?

**Comment by chriseth** [comment]
Can you also explain the preprocessor macros? I guess they are more about the `setenv` call than the `setlocale` call, right? Do neither of the platforms that are specified have this problem?

File: lllc/main.cpp (hunk 3 above)
Comment (cjgdev) [reply lllc/main.cpp]: I shall update the pull request with the style changes.

**Comment by cjgdev** [comment]
Upon reviewing the documentation again I am also convinced that the first call to setlocale is redundant as you pointed out setlocale is called before any user code. I'll update the pull request after I've tested the modification.

The preprocessor macros prevent compilation on Windows, OSX and BSD as the change should not be required for those platforms. Any other (POSIX) compatible platform should require the code change. If the only platform that is supported is Linux this could be refactored.

**Comment by cjgdev** [comment]
@chriseth I have submitted the stylistic and functional changes you suggested ready for your review.

**Comment by bobsummerwill** [comment]
My recommendation on sticking with `__unix__` is just ease of maintenance.
The calls should be harmless on macOS, FreeBSD, etc.

We'll need this code for `soltest` too.   Sorry!

File: lllc/main.cpp [hunk 4]
```diff
@@ -52,10 +53,34 @@ void version()
 	exit(0);
 }
 
+/*
+The equivalent of setlocale(LC_ALL, “C”) is called before any user code is run.
```
Comment (chriseth) [inline lllc/main.cpp:57]: Please avoid non-ascii characters in source if possible.

**Comment by bobsummerwill** [comment]
I've just fixed those ... https://github.com/ethereum/solidity/pull/986

We had a weird bug related to non-ANSI characters in comments when I was working on FIFA.

We were using IncrediBuild (https://www.incredibuild.com/) which does a grid-engine thing to use spare desktop capacity to do massively parallel builds.    That does a transparent virtualization thing, where the submitting PC's environment is replicated elsewhere.    Very clever.   So you don't need Visual Studio installed, or same versions of anything.   It "just works".

Except for this scenario.    Building C++ on a machine with Japanese locale would fall over on non-ANSI characters only if it ran on that node.

It was a horror show to track down.

But yes - non-ANSI in source code is not good!

**Comment by blockchaindev** [comment]
I've just read the comments and I agree with everything said. I'll check my editor settings to disable automatic substitution of quote marks. Thanks for reviewing my submission and of course I'm happy to have had the merge accepted.
