### PR TITLE
SMTChecker: Fix internal compiler error on reporting proved targets

### LINKED ISSUE #15113: Internal compiler error when using --model-checker-show-proved-safe option in SMTChecker
Version affected: commit f9c8ab0
To replicate run `solc --model-checker-engine all --model-checker-targets all --model-checker-show-proved-safe A.sol`

A.sol:
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.0.0;
type I16 is int16;
using {
    bitor as |, bitand as &, bitxor as ^, bitnot as ~,
    add as +, sub as -, unsub as -, mul as *, div as /, mod as %,
    eq as ==, noteq as !=, lt as <, gt as >, leq as <=, geq as >=
} for I16 global;

function bitor(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) | I16.unwrap(y)); }
function bitand(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) & I16.unwrap(y)); }
function bitxor(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) ^ I16.unwrap(y)); }
function bitnot(I16 x) pure returns (I16) { return I16.wrap(~I16.unwrap(x)); }

function add(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) + I16.unwrap(y)); }
function sub(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) - I16.unwrap(y)); }
function unsub(I16 x) pure returns (I16) { return I16.wrap(-I16.unwrap(x)); }
function mul(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) * I16.unwrap(y)); }
function div(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) / I16.unwrap(y)); }
function mod(I16 x, I16 y) pure returns (I16) { return I16.wrap(I16.unwrap(x) % I16.unwrap(y)); }

function eq(I16 x, I16 y) pure returns (bool) { return I16.unwrap(x) == I16.unwrap(y); }
function noteq(I16 x, I16 y) pure returns (bool) { return I16.unwrap(x) != I16.unwrap(y); }
function lt(I16 x, I16 y) pure returns (bool) { return I16.unwrap(x) < I16.unwrap(y); }
function gt(I16 x, I16 y) pure returns (bool) { return I16.unwrap(x) > I16.unwrap(y); }
function leq(I16 x, I16 y) pure returns (bool) { return I16.unwrap(x) <= I16.unwrap(y); }
function geq(I16 x, I16 y) pure returns (bool) { return I16.unwrap(x) >= I16.unwrap(y); }

contract C {
    I16 constant MINUS_TWO = I16.wrap(-2);
    I16 constant ZERO = I16.wrap(0);
    I16 constant ONE = I16.wrap(1);
    I16 constant TWO = I16.wrap(2);
    I16 constant THREE = I16.wrap(3);
    I16 constant FOUR = I16.wrap(4);

    function testBitwise() public pure {
        assert(ONE | TWO == THREE);
        assert(ONE & THREE == ONE);
        assert(TWO ^ TWO == ZERO);
        assert(~ONE == MINUS_TWO);
    }

    function testArithmetic() public pure {
        assert(TWO + TWO == FOUR);
        assert(TWO - TWO == ZERO);
        assert(-TWO == MINUS_TWO);
        assert(TWO * TWO == FOUR);
        assert(TWO / TWO == ONE);
        assert(TWO % TWO == ZERO);
    }

    function testComparison() public pure {
        assert(TWO == TWO);
        assert(!(TWO != TWO));
        assert(!(TWO < TWO));
        assert(!(TWO > TWO));
        assert(TWO <= TWO);
        assert(TWO >= TWO);
    }
}
```

### LINKED ISSUE #15188: SMTChecker: Underflow and overflow targets not checked or reported on the same expression for BMC engine
## Description
When providing `underflow` and `overflow` verification targets only one of them is reported as proved safe for BMC engine.

## Environment

- Compiler version: commit 5da0f47439340097fe5b8a409caadc4fd3f00752

## Steps to Reproduce

```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.0.0;

contract C {
	function f(int x, int y) public pure returns (int) {
		require(x == 0);
		require(y == 0);
		return x + y;
	}
}

```

then run:
-  `solc --model-checker-engine bmc --model-checker-targets underflow,overflow test.sol`
-  `solc --model-checker-engine bmc --model-checker-targets underflow test.sol`
-  `solc --model-checker-engine bmc --model-checker-targets overflow test.sol`

All The above runs print on output that only 1 verification target was proved correct, although both underflow and overflow should be reported in the first run.

CHC engine is not affected.

### PR DESCRIPTION
**Pull request by pgebal**
Closes https://github.com/ethereum/solidity/issues/15188
Closes https://github.com/ethereum/solidity/issues/15113

We used `UniqueErrorLogger` for reporting proved targets, which requires pair `(error code, source location)` to be unique. I replaced that with a regular `ErrorLogger`.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.h [hunk 1]
```diff
@@ -57,6 +57,7 @@ class SMTEncoder: public ASTConstVisitor
 		ModelCheckerSettings _settings,
 		langutil::UniqueErrorReporter& _errorReporter,
 		langutil::UniqueErrorReporter& _unsupportedErrorReporter,
+		langutil::ErrorReporter& _provedSafeReporter,
```
Comment (blishko) [inline libsolidity/formal/SMTEncoder.h:60]: I don't see why we need to add this to `SMTEncoder`.
Should work fine without it, no?
`BMC` and `CHC` keep their own reference, right?

File: libsolidity/formal/BMC.cpp [hunk 2]
```diff
@@ -47,12 +47,13 @@ BMC::BMC(
 	smt::EncodingContext& _context,
 	UniqueErrorReporter& _errorReporter,
 	UniqueErrorReporter& _unsupportedErrorReporter,
+	ErrorReporter& _provedSafeReporter,
```
Comment (blishko) [inline libsolidity/formal/BMC.cpp:50]: Instead of adding a separate `ErrorReporter` for the safe targets, cannot we just turn `UniqueErrorReporter _errorReporter` into a regular `ErrorReport` and use only that?

**Comment by blishko** [comment]
What would happen if we remove `m_uniqueErrorReporter` from `ModelChecker` and just use the `ErrorReporter` passed from `CompilerStack` (so we do not have to add another `ErrorReporter`)? Where would we run into problem with duplicates?

**Comment by pgebal** [comment]
> What would happen if we remove `m_uniqueErrorReporter` from `ModelChecker` and just use the `ErrorReporter` passed from `CompilerStack` (so we do not have to add another `ErrorReporter`)? Where would we run into problem with duplicates?

I'll double check that, but I almost sure I've seen CHC reporting some failed targets twice.

File: libsolidity/formal/BMC.cpp (hunk 2 above)
Comment (pgebal) [reply libsolidity/formal/BMC.cpp:50]: Right. That's a mistake.

File: libsolidity/formal/SMTEncoder.h (hunk 1 above)
Comment (pgebal) [reply libsolidity/formal/SMTEncoder.h:60]: Right. That's a mistake.

**Comment by blishko** [comment]
> I'll double check that, but I almost sure I've seen CHC reporting some failed targets twice.

That's interesting. I would expect the same behaviour for safe and unsafe targets.

**Comment by cameel** [comment]
The unique reporter was added in #11850 (which was meant to address #11597). See the description:

> The SMTChecker generates a lot of redundant "unsupported" warnings, because it visits every contract separately in its own context, with 2 different engines. So for example if a contract that is inherited by 2 contracts has some assembly in it, we're going to see the message "inline assembly unsupported" possibly 6 times: each time a contract is visited, by each engine.

File: libsolidity/formal/BMC.cpp (hunk 2 above)
Comment (cameel) [reply libsolidity/formal/BMC.cpp:50]: The reason we have multiple reporters here is that we want to squash certain kinds of warnings into a single message by default, but also have an option to display them all, depending on the settings. See #14028 / #11597.

Not sure if that was the intention behind `_provedSafeReporter` as well. If not, those errors could just go to `_errorReporter` along with everything else.

Comment (blishko) [reply libsolidity/formal/BMC.cpp:50]: I understand the reason why we want to avoid duplicated "unsupported" warnings, so `_unsupportedErrorReporter` definitely should stay `UniqueErrorReporter`.
On the other hand, there can be multiple targets (underflow + overflow) for the same expression, and we do not want to lose reports on these, so `UniqueErrorReporter` should not be used for those. I would like to investigate if the error report for all the other things has to be unique or not.

**Comment by blishko** [comment]
@pgebal, I checked and you were right that in certain situations, we would emit a warning multiple times for the same source code location without `UniqueErrorReporter`. For example, assertion violation in a parent contract in the presence of inheritance.

There is a possibility to maybe be more efficient in these scenarios. For example, if the assertion can be violated in the context of one contract, we do not need to check it again in the context of another contract.
But then one must consider also the case where the assertion is safe in the context of one contract, but can be violated in the context of another contract.

Let's go with your fix now, and we can maybe revisit this later. Can you just remove the unnecessary field in `SMTEncoder`?
Or maybe you can do it the other way around? Only have it in `SMTEncoder` and not add again in `BMC` and `CHC`?

File: libsolidity/formal/SMTEncoder.h (hunk 1 above)
Comment (pgebal) [reply libsolidity/formal/SMTEncoder.h:60]: @blishko My previous comment is wrong. They do not keep their own reference. They use protected field from SMTEncoder.

**Comment by pgebal** [comment]
> @pgebal, I checked and you were right that in certain situations, we would emit a warning multiple times for the same source code location without `UniqueErrorReporter`. For example, assertion violation in a parent contract in the presence of inheritance.
> 
> There is a possibility to maybe be more efficient in these scenarios. For example, if the assertion can be violated in the context of one contract, we do not need to check it again in the context of another contract. But then one must consider also the case where the assertion is safe in the context of one contract, but can be violated in the context of another contract.
> 
> Let's go with your fix now, and we can maybe revisit this later. Can you just remove the unnecessary field in `SMTEncoder`? Or maybe you can do it the other way around? Only have it in `SMTEncoder` and not add again in `BMC` and `CHC`?

Actually, we have it only in the SMTEncoder. Sorry for misleading comment I posted earlier.
I think the PR is ready for a merge

**Review by blishko — APPROVED** [review]
LGTM!
