### PR TITLE
[Sol->Yul] Provide selector for some internal functions.

### LINKED ISSUE #10891: [soltoyul] ICE due to invalid use of selector function
## Description

```
contract B {
  function g() public {}
}
contract C is B {
  function h() public { g.selector; }
}
```

throws

https://github.com/ethereum/solidity/blob/8a4e6acdac8d11ee671f084d96d82de63f684812/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L1699

## Environment

- Compiler version:
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc --ir test.sol
```

### PR DESCRIPTION
**Pull request by chriseth**
Depends on https://github.com/ethereum/solidity/pull/11014
References #10905 
Closes https://github.com/ethereum/solidity/issues/10891

### CODE REVIEW

**Comment by bshastry** [comment]
Closes https://github.com/ethereum/solidity/issues/10891

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 1]
```diff
@@ -1689,7 +1689,12 @@ void IRGeneratorForStatements::endVisit(MemberAccess const& _memberAccess)
 				functionType.kind() == FunctionType::Kind::DelegateCall
 			)
 				define(IRVariable{_memberAccess}, IRVariable(_memberAccess.expression()).part("functionSelector"));
-			else if (functionType.kind() == FunctionType::Kind::Declaration)
+			else if (
+				functionType.kind() == FunctionType::Kind::Declaration ||
+				// In some situations, internal function types also provide the "selector" member.
+				// See Types.cpp for details.
+				functionType.kind() == FunctionType::Kind::Internal
```
Comment (bshastry) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1696]: Is this a blanket provision for all internal functions? Since the title of the PR is "...for some internal functions", I wonder how and where the "some" are filtered?

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1696]: They are filtered in the type checker. I can add some assertions to be sure it is not extended. On the other Hand, if there is no selector, then this will throw anyway.

Comment (bshastry) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1696]: Okay. I just took a look at these lines https://github.com/ethereum/solidity/blob/eacf7c1cf98ea85c7acb97edd29c0f062940b96a/libsolidity/ast/Types.cpp#L3151-L3163

So we permit selector for internal functions if function is part of external interface and invoked outside the scope of the contract it is defined in. Could we assert in this PR that the function type actually belongs to external interface of the contract or is that information already lost in IR? I suppose scope information is lost?

File: test/libsolidity/semanticTests/constants/function_unreferenced.sol [hunk 2]
```diff
@@ -0,0 +1,11 @@
+contract B {
+  function g() public {}
```
Comment (cameel) [inline test/libsolidity/semanticTests/constants/function_unreferenced.sol]:
```suggestion
    function g() public {}
```

File: test/libsolidity/semanticTests/constants/function_unreferenced.sol [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+}
+contract C is B {
+  bytes4 constant s2 = B.g.selector;
+  function f() external pure returns (bytes4) { return s2; }
+}
```
Comment (cameel) [inline test/libsolidity/semanticTests/constants/function_unreferenced.sol]: I'd add more cases from #10891, maybe combined into a single test:

```solidity
contract B {
    function ext() external {}
    function pub() public {}
}

contract C is B {
    function test() public {
        B.ext.selector;
        B.pub.selector;
        this.ext.selector;
        pub.selector;
    }
}

contract D {
    function test() public {
        B.ext.selector;
        B.pub.selector;
    }
}
```

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp:1696]: Added the assertion about the external interface.

File: test/libsolidity/semanticTests/constants/function_unreferenced.sol [hunk 4]
```diff
@@ -0,0 +1,11 @@
+contract B {
+    function g() public {}
+}
+contract C is B {
+    bytes4 constant s2 = B.g.selector;
```
Comment (ekpyron) [inline test/libsolidity/semanticTests/constants/function_unreferenced.sol:5]: Isn't this exactly the case that already worked before?

**Review by ekpyron — COMMENTED** [review]
I expected this to be more complicated, but looks to me like it should be fine. More tests won't hurt, though. Also should this get a changelog entry?

File: test/libsolidity/semanticTests/constants/function_unreferenced.sol (hunk 3 above)
Comment (chriseth) [reply test/libsolidity/semanticTests/constants/function_unreferenced.sol]: The problem is that those cannot be done as a semantic test.

**Comment by chriseth** [comment]
No changelog entry because it is sol->yul

File: test/libsolidity/semanticTests/constants/function_unreferenced.sol (hunk 3 above)
Comment (bshastry) [reply test/libsolidity/semanticTests/constants/function_unreferenced.sol]: Perhaps split into two tests

```
contract B {
    function ext() external {}
    function pub() public {}
}

contract C is B {
    function test() public returns (bytes4, bytes4, bytes4, bytes4) {
        return (B.ext.selector, B.pub.selector, this.ext.selector, pub.selector);
    }
}
// ====
// compileViaYul: true
// ----
// test() ->
```

and

```
contract B {
    function ext() external {}
    function pub() public {}
}

contract D {
    function test() public returns (bytes4, bytes4) {
        return (B.ext.selector, B.pub.selector);
    }
}
// ====
// compileViaYul: true
// ----
// test() -> 0xcf9f23b500000000000000000000000000000000000000000000000000000000, 0x7defb41000000000000000000000000000000000000000000000000000000000
```

Comment (chriseth) [reply test/libsolidity/semanticTests/constants/function_unreferenced.sol]: Does the tuple really trigger the same code path? I'll add a syntax test for the others just to be sure.

**Comment by chriseth** [comment]
Added tests.

File: test/libsolidity/syntaxTests/functionTypes/selectors.sol [hunk 5]
```diff
@@ -0,0 +1,26 @@
+contract B {
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: This file does not trigger an error when run through `solc --ir` (and I think this is also tested for all syntax tests)

Comment (bshastry) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: Do we run IR generator on all syntax tests? That's good to know.

File: test/libsolidity/semanticTests/constants/function_unreferenced.sol (hunk 3 above)
Comment (bshastry) [reply test/libsolidity/semanticTests/constants/function_unreferenced.sol]: > Does the tuple really trigger the same code path? I'll add a syntax test for the others just to be sure.

Yes, just verified that it does.

File: test/libsolidity/syntaxTests/functionTypes/selectors.sol (hunk 5 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: Acutally we do not. We compile to bytecode, but not via yul. I just tried it and it is kind of stuck in the optimizer :(

Comment (hrkrshnn) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: > Do we run IR generator on all syntax tests? That's good to know.

Not yet.

Comment (chriseth) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: Just ran the IR on all syntax tests and found one unimplemented feature: https://github.com/ethereum/solidity/issues/11024

Comment (ekpyron) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: We did that a few weeks ago already (it used to be more like 9 cases or so), so that issue may be a duplicate...

Comment (hrkrshnn) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: I couldn't find an equivalent issue. We probably missed that one. this was the CI job https://app.circleci.com/pipelines/github/ethereum/solidity/13394/workflows/42f7aa23-443b-4847-be5e-b37f8af856b3/jobs/621452/tests#failed-test-2

Comment (ekpyron) [reply test/libsolidity/syntaxTests/functionTypes/selectors.sol:1]: Weird... I do remember that we were wondering if it actually works and that I noted that it's a bit weird even in old codegen... but maybe we still didn't do anything about it or even file an issue :-).

**Review by bshastry — APPROVED** [review]
LGTM
