### PR TITLE
soltest: Improve handling invalid EVMVersion syntax in test files.

### LINKED ISSUE #7594: Test parser fails on wrong EVMVersion syntax
Input:

```
contract c {
  function f() public pure returns (uint) {
    return 7;
  }
}
// ====
// compileViaYul: also
// EVMVersion: byzantium
// ----
// f(uint256): 7 -> 7
```

It fails with an exception because of the syntax error in EVMVersion:

```
/Users/alex/Projects/solidity/test/boostTest.cpp:125: fatal error: in "semanticTests/wasm": unexpected exception thrown by { try { stringstream errorStream; auto testCase = _testCaseCreator(config); if (testCase->validateSettings(dev::test::Options::get().evmVersion())) switch (testCase->run(errorStream)) { case TestCase::TestResult::Success: break; case TestCase::TestResult::Failure: do { ::boost::unit_test::unit_test_log.set_checkpoint( ::boost::unit_test::const_string( "/Users/alex/Projects/solidity/test/boostTest.cpp", sizeof( "/Users/alex/Projects/solidity/test/boostTest.cpp" ) - 1 ), static_cast<std::size_t>(114) ); ::boost::test_tools::tt_detail:: report_assertion ( (false), (::boost::unit_test::lazy_ostream::instance() << "Test expectation mismatch.\n" + errorStream.str()), ::boost::unit_test::const_string( "/Users/alex/Projects/solidity/test/boostTest.cpp", sizeof( "/Users/alex/Projects/solidity/test/boostTest.cpp" ) - 1 ), static_cast<std::size_t>(114), ::boost::test_tools::tt_detail::CHECK, ::boost::test_tools::tt_detail::CHECK_MSG , 0 ); } while( ::boost::test_tools::tt_detail::dummy_cond() ); break; case TestCase::TestResult::FatalError: do { ::boost::unit_test::unit_test_log.set_checkpoint( ::boost::unit_test::const_string( "/Users/alex/Projects/solidity/test/boostTest.cpp", sizeof( "/Users/alex/Projects/solidity/test/boostTest.cpp" ) - 1 ), static_cast<std::size_t>(117) ); ::boost::test_tools::tt_detail:: report_assertion ( (false), (::boost::unit_test::lazy_ostream::instance() << "Fatal error during test.\n" + errorStream.str()), ::boost::unit_test::const_string( "/Users/alex/Projects/solidity/test/boostTest.cpp", sizeof( "/Users/alex/Projects/solidity/test/boostTest.cpp" ) - 1 ), static_cast<std::size_t>(117), ::boost::test_tools::tt_detail::CHECK, ::boost::test_tools::tt_detail::CHECK_MSG , 0 ); } while( ::boost::test_tools::tt_detail::dummy_cond() ); break; } } catch (boost::exception const& _e) { do { ::boost::unit_test::unit_test_log.set_checkpoint( ::boost::unit_test::const_string( "/Users/alex/Projects/solidity/test/boostTest.cpp", sizeof( "/Users/alex/Projects/solidity/test/boostTest.cpp" ) - 1 ), static_cast<std::size_t>(123) ); ::boost::test_tools::tt_detail:: report_assertion ( (false), (::boost::unit_test::lazy_ostream::instance() << "Exception during extracted test: " << boost::diagnostic_information(_e)), ::boost::unit_test::const_string( "/Users/alex/Projects/solidity/test/boostTest.cpp", sizeof( "/Users/alex/Projects/solidity/test/boostTest.cpp" ) - 1 ), static_cast<std::size_t>(123), ::boost::test_tools::tt_detail::CHECK, ::boost::test_tools::tt_detail::CHECK_MSG , 0 ); } while( ::boost::test_tools::tt_detail::dummy_cond() ); } }
```

### PR DESCRIPTION
**Pull request by christianparpart**
Fixes https://github.com/ethereum/solidity/issues/7594

Improves handling invalid `EVMVersion` values in .sol test file's metadata section. Before you saw a huge mess of c++ source code when test test failed because of that.

Now you see still an exception, but a much smaller and more descriptive one.

### CODE REVIEW

**Comment by christianparpart** [comment]
NB: In my force-push I *just* updated the commit log message.

File: test/TestCase.cpp [hunk 1]
```diff
@@ -201,6 +201,8 @@ bool EVMVersionRestrictedTestCase::validateSettings(langutil::EVMVersion _evmVer
 	else if (comparator == "!")
 		return !(_evmVersion == version);
 	else
-		throw runtime_error("Invalid EVM comparator: \"" + comparator + "\"");
-	return false; // not reached
+	{
+		BOOST_THROW_EXCEPTION(runtime_error{"Invalid EVM comparator: \"" + comparator + "\""});
+		return false; // not reached
```
Comment (erak) [inline test/TestCase.cpp]: Can we remove this comment? :-)

Comment (christianparpart) [reply test/TestCase.cpp]: Good question. Sure I can, wasn't part of my PR (I just indented). Hold tight.

**Review by erak — APPROVED** [review]
