### PR TITLE
Fix for Token::name and token::toString

### LINKED ISSUE #428: Token::name and Token::toString do not work for fixed
The functions Token::name and Token::toString do not work for the new complex tokens fixed and ufixed, e.g. they return "UFixed" for "ufixed8x8".

### PR DESCRIPTION
**Pull request by VoR0220**
Fixes #428 .

### CODE REVIEW

File: libsolidity/parsing/Token.cpp [hunk 1]
```diff
@@ -155,16 +155,15 @@ tuple<Token::Value, unsigned int, unsigned int> Token::fromIdentifierOrKeyword(s
 			) {
 				int n = parseSize(positionX + 1, _literal.end());
 				if (
-					0 < m && m < 256 &&
-					0 < n && n < 256 &&
+					m + n > 0 &&
```
Comment (chriseth) [inline libsolidity/parsing/Token.cpp:160]: Please do not undo this check.

Comment (VoR0220) [inline libsolidity/parsing/Token.cpp:160]: why not? We need to eventually change to it any way...is there a concern that something will break along the way?

**Comment by chriseth** [comment]
I don't think this PR fixes the issue. The problem was that for the following source file
`contract c fixed8x8` the error message is `Expected token LBrace got 'Fixed'`, but it should be `Expected token LBrace got 'Fixed8x8'`

File: libsolidity/parsing/Token.cpp (hunk 1 above)
Comment (chriseth) [inline libsolidity/parsing/Token.cpp:160]: parseSize can return -1 and we need to catch that.

**Comment by VoR0220** [comment]
@chriseth I got a FixedMxN for when I built mine.... This is the same kind of error that comes with a uint256, an error containing: `Error: Expected token LBrace got 'UIntM'`

**Comment by VoR0220** [comment]
granted we should have it set up so that they return the actual types, but I think that needs to be addressed in a separate issue.

File: libsolidity/parsing/Token.cpp (hunk 1 above)
Comment (VoR0220) [inline libsolidity/parsing/Token.cpp:160]: yes. Parse size can return -1 because that's the error statement. If you look in the function though, it is set to lexical cast to an unsigned int...and if there is a -1, there's no way they can make is equal to 0 on a modulo 8 condition...so I think we're fairly safe.

**Comment by VoR0220** [comment]
@chriseth now works exactly as it should :)

File: libsolidity/parsing/Token.cpp (hunk 1 above)
Comment (chriseth) [inline libsolidity/parsing/Token.cpp:160]: Yes, I am talking about the error condition that could arise when we encounter `fixed8x8888888888888888888888888888888888888888888888888888`. Please add the check for clarity even if it is also performed by `n % 8==0`.

Comment (VoR0220) [inline libsolidity/parsing/Token.cpp:160]: but without this change, we cannot make a fixed0x8 or a fixed8x0...and I've made a test in this latest iteration with your exact concern and it passes through it...

**Comment by chriseth** [comment]
Could you please rebase so jenkins hopefully runs the tests?

File: libsolidity/parsing/ParserBase.cpp [hunk 2]
```diff
@@ -44,14 +44,32 @@ int ParserBase::endPosition() const
...
-		);
+	Token::Value tok = m_scanner->currentToken();
+	if (tok != _value)
+	{
+		if (Token::isElementaryTypeName(tok)) //for the sake of accuracy in reporting
+		{
+			unsigned firstSize;
+			unsigned secondSize;
+			tie(firstSize, secondSize) = m_scanner->currentTokenInfo();
+			ElementaryTypeNameToken elemTypeName(tok, firstSize, secondSize);
```
Comment (chriseth) [inline libsolidity/parsing/ParserBase.cpp]: Can you create a helper function for that in the scanner? I guess this is used more than once. Could we also use it in the "else" case here?

File: libsolidity/parsing/Token.cpp (hunk 1 above)
Comment (chriseth) [inline libsolidity/parsing/Token.cpp:160]: Ok, all I want you to test is that it is not `-1`, because that is the error case.

File: libsolidity/parsing/ParserBase.cpp (hunk 2 above)
Comment (VoR0220) [inline libsolidity/parsing/ParserBase.cpp]: Can do on the helper function. Just wasn't certain whether I should go about it in the scanner or not. As for the else case...well, not really...because not all of them are elementary type name tokens....so I believe it wouldn't work in this instance if my memory serves me correctly.

File: libsolidity/parsing/Token.cpp [hunk 3]
```diff
@@ -113,7 +113,7 @@ int Token::parseSize(string::const_iterator _begin, string::const_iterator _end)
 {
 	try
 	{
-		unsigned int m = boost::lexical_cast<int>(boost::make_iterator_range(_begin, _end));
+		unsigned int m = boost::lexical_cast<unsigned int>(boost::make_iterator_range(_begin, _end));
```
Comment (chriseth) [inline libsolidity/parsing/Token.cpp]: I think lexical-casting it to `int` is better (we check that it does not contain `-` actually), because we also return int. Some compilers might complain about the conversion. You could just use `return boost::lexical_cast<int>(...)`.

File: libsolidity/parsing/Token.h [hunk 4]
```diff
@@ -334,8 +334,10 @@ class ElementaryTypeNameToken
 		std::string name = Token::toString(m_token);
 		if (tokenValue || (firstNumber() == 0 && secondNumber() == 0))
 			return name;
-		//need to set it up this way for fixed types construction in future
```
Comment (chriseth) [inline libsolidity/parsing/Token.h:337]: Please `solAssert(name.size()>=3,"")` here.

File: libsolidity/parsing/Token.cpp (hunk 1 above)
Comment (VoR0220) [inline libsolidity/parsing/Token.cpp:160]: ooooooooooo....okay....my misunderstanding.

File: libsolidity/parsing/Token.cpp [hunk 5]
```diff
@@ -132,6 +132,7 @@ tuple<Token::Value, unsigned int, unsigned int> Token::fromIdentifierOrKeyword(s
 		Token::Value keyword = keywordByName(baseType);
 		if (keyword == Token::Bytes)
 		{
+			solAssert(m != -1, "Invalid type M in fixed command. Should not reach here.");
```
Comment (chriseth) [inline libsolidity/parsing/Token.cpp]: I think `bytes888888888888888888888888888888888888` will trigger this assert, which should not happen (it is a valid identifier), so this assert should be removed (the actual check is performed one line below).

File: libsolidity/parsing/Token.cpp [hunk 6]
```diff
@@ -139,6 +140,7 @@ tuple<Token::Value, unsigned int, unsigned int> Token::fromIdentifierOrKeyword(s
 		{
 			if (0 < m && m <= 256 && m % 8 == 0 && positionX == _literal.end())
 			{
+				solAssert(m != -1, "Invalid type M in fixed command. Should not reach here.");
```
Comment (chriseth) [inline libsolidity/parsing/Token.cpp]: We already check for `0 < m` two lines above, so this is redundant.

File: libsolidity/parsing/Token.cpp [hunk 7]
```diff
@@ -160,6 +162,7 @@ tuple<Token::Value, unsigned int, unsigned int> Token::fromIdentifierOrKeyword(s
 					m % 8 == 0 &&
 					n % 8 == 0
 				) {
+					solAssert(n != -1, "Invalid type N in fixed command. Should not reach here.");
```
Comment (chriseth) [inline libsolidity/parsing/Token.cpp]: This should work, but I think it would be clearer to just put `0 <= m &&m <= 256 && 0 <= n && n <= 256` into the `if`.

Comment (VoR0220) [inline libsolidity/parsing/Token.cpp]: alright. I think I see what you're trying to say. I'll add it into the conditions.

**Comment by chriseth** [comment]
Thanks!
