### PR TITLE
[Sol->Yul] Implementing copying dynamically encoded structs from calldata to memory

### LINKED ISSUE #9160: UnimplementedFeatureError:  calldata structs
I notified @chriseth in the Gitter chat that I am getting a lot of `UnimplementedFeatureError` from the solc-js compiler 0.6.9, in places where I want to make use of `calldata structs`. It seems like the Error is thrown when I want to pass around such `calldata structs` between functions internally. The calldata structs are nested. 

## Environment

- Compiler version: 0.6.9

## Steps to Reproduce

In this issue I will include one such example of the `UnimplementedFeatureError:`  for a function that I was able to distill down a lot. In this case the error comes from a `calldata` array of the nested struct. 

I will include more examples, as soon as our repo is public again. The other examples I have are inside large functions that I won't distill down now.

Try to compile the following contract:

```solidity
// "SPDX-License-Identifier: UNLICENSED"
pragma solidity ^0.6.9;
pragma experimental ABIEncoderV2;

struct Condition {
    address inst;  // can be AddressZero for self-conditional Actions
    bytes data;  // can be bytes32(0) for self-conditional Actions
}

struct Task {
    Condition[] conditions;  // optional
    uint256 selfProviderGasPriceCeil;
}

struct TaskReceipt {
    uint256 id;
    Task[] tasks;
    uint256 expiryDate;
}

contract CalldataFeatureErrors {
    // taskReceipt.id => taskReceiptHash
    mapping(uint256 => bytes32) public taskReceiptHash;

    function cancelTask(TaskReceipt memory _TR) public {
        // Effects
        bytes32 hashedTaskReceipt = hashTaskReceipt(_TR);
        require(
            hashedTaskReceipt == taskReceiptHash[_TR.id],
            "GelatoCore.cancelTask: invalid taskReceiptHash"
        );
        delete taskReceiptHash[_TR.id];
    }

    function multiCancelTasks(TaskReceipt[] calldata _taskReceipts) external {
        for (uint i; i < _taskReceipts.length; i++) cancelTask(_taskReceipts[i]);
    }

    function hashTaskReceipt(TaskReceipt memory _TR) public pure returns(bytes32) {
        return keccak256(abi.encode(_TR));
    }
}
```

### PR DESCRIPTION
**Pull request by mijovic**
In this PR we can also activate it for old codegen which will fix #9160

TODO:
- [x] Add more tests as it wasn't implemented for old codegen, so no coverage at all

### CODE REVIEW

**Comment by mijovic** [comment]
Added few test with nested structs and structs including arrays. I think coverage should be good now.

File: libsolidity/codegen/ABIFunctions.h [hunk 1]
```diff
@@ -170,6 +170,11 @@ class ABIFunctions
 	/// signature: (dataOffset, length, dataEnd) -> decodedArray
 	std::string abiDecodingFunctionArrayAvailableLength(ArrayType const& _type, bool _fromMemory);
 
+	/// Internal decoding function that is also used by some copying routines.
+	/// @returns the name of a function that decodes struct
```
Comment (leonardoalt) [inline libsolidity/codegen/ABIFunctions.h]:
```suggestion
	/// @returns the name of a function that decodes structs.
```

File: test/libsolidity/semanticTests/structs/calldata/calldata_struct_with_nested_array_to_memory.sol [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+contract C {
+    struct S {
+        uint128 p1;
+        uint256[][2] a;
+        uint32 p2;
+    }
+    function f(uint32 p1, S calldata c) external returns(uint32, uint128, uint256, uint256, uint32) {
+        S memory s = c;
+        assert(s.a[0][0] == c.a[0][0]);
+        assert(s.a[1][1] == c.a[1][1]);
```
Comment (leonardoalt) [inline test/libsolidity/semanticTests/structs/calldata/calldata_struct_with_nested_array_to_memory.sol:12]: Can you also change something in `s` and assert that it's != from `c`?

**Comment by leonardoalt** [comment]
Are there any existing tests that could now work with `viaYul: also`?

**Comment by mijovic** [comment]
> Are there any existing tests that could now work with `viaYul: also`?

This is only implemented in sol->yul. I plan to activate it in old codegen via calling yul. So no test to activate unfortunately.

But, I can add more test anyway

**Comment by leonardoalt** [comment]
Ah ok, sounds good

File: test/libsolidity/semanticTests/structs/calldata/calldata_struct_with_nested_array_to_memory.sol (hunk 2 above)
Comment (mijovic) [reply test/libsolidity/semanticTests/structs/calldata/calldata_struct_with_nested_array_to_memory.sol:12]: I added some changes and assertions

**Comment by mijovic** [comment]
@leonardoalt Which tests would you suggest I should add?

File: test/libsolidity/semanticTests/structs/calldata/calldata_nested_structs.sol [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+    struct S2 {
+        S[2] array;
+    }
+
+    function f(S1 calldata c, uint32 p) external returns(uint32, uint128, uint256, uint256, uint32) {
+        S1 memory m = c;
+        assert(m.s.a[0][0] == c.s.a[0][0]);
+        assert(m.s.a[1][1] == c.s.a[1][1]);
+        return (p, m.s.p1, m.s.a[0][0], m.s.a[1][1], m.s.p2);
+    }
```
Comment (cameel) [inline test/libsolidity/semanticTests/structs/calldata/calldata_nested_structs.sol]: More test ideas:
- calldata struct being passed to an internal function that expects a memory struct
- An assignment between two tuples where one contains memory structs and the other calldata (or mixed) structs. E.g. `(m, m, m) = (c, c, c)`.
- Assignment from a nested calldata struct. E.g. `S memory m = c.s`.
- Assignment from the result of a function that returns a calldata struct.
- A call to a bound library function that has a memory struct as its first argument.
- A multiple assignment like `m = m = c`.
- I'm not sure if this involves a memory conversion (probably not) but I'll include it just in case: passing a calldata struct to an event being emitted. Both indexed and non-indexed.

**Review by cameel — COMMENTED** [review]
Everything seems fine here so I only have some test suggestions.

**Comment by mijovic** [comment]
@cameel @leonardoalt I added bunch of new tests. Do you think there should be even more?

**Comment by chriseth** [comment]
Shouldn't this activate more existing tests?

**Comment by cameel** [comment]
@mijovic I think it's well covered now. I have nothing to add and I can approve as soon as @leonardoalt's and @chriseth's questions are resolved.

**Comment by leonardoalt** [comment]
Looks good to me.

**Comment by mijovic** [comment]
> Shouldn't this activate more existing tests?

@chriseth There were no existing tests because in old codegen this wasn't implemented at all. Only statically encoded structs were supported.
My plan is to in follow-up PR to activate this in old codegen.

**Review by cameel — APPROVED** [review]

**Comment by chriseth** [comment]
Ah right, this only adds dynamic structs!
