### PR TITLE
[SMTChecker] Fix ICE in 1-tuple chain

### LINKED ISSUE #9296: [SMTChecker] ICE in solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C
{
    function i() public returns (uint d) {
	if (0==0)
            (d) = 13;
    }
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/formal/SMTEncoder.cpp(1712): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

And the parens on (d) are neccessary.

when compiled with solc

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.6.11-develop.2020.7.2+commit.3d96e2b1.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/9296

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -1878,6 +1873,19 @@ Expression const* SMTEncoder::leftmostBase(IndexAccess const& _indexAccess)
 	return base;
 }
 
+Expression const* SMTEncoder::innermostTuple(TupleExpression const& _tuple)
+{
+	TupleExpression const* tuple = &_tuple;
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp:1902]: This should also handle `isInlineArray` properly - either via assertion or via breaking the while loop.

**Review by chriseth — CHANGES_REQUESTED** [review]
Handle inline arrays properly.

File: libsolidity/formal/SMTEncoder.cpp (hunk 1 above)
Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1902]: Right!

**Comment by leonardoalt** [comment]
Updated

File: libsolidity/formal/SMTEncoder.cpp [hunk 2]
```diff
@@ -1901,6 +1896,20 @@ Expression const* SMTEncoder::leftmostBase(IndexAccess const& _indexAccess)
...
 }
 
+Expression const* SMTEncoder::innermostTuple(TupleExpression const& _tuple)
+{
+	solAssert(!_tuple.isInlineArray(), "");
+	TupleExpression const* tuple = &_tuple;
+	Expression const* expr = tuple;
+	while (tuple && tuple->components().size() == 1)
+	{
+		expr = tuple->components().front().get();
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp:1906]: What about `([x])`? You need the assertion in each loop iteration.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:1906]: Since the idea is to stop when the front component is not a Tuple anymore (not considering inline arrays), I think in that case it should just exit the while. Updated it in that way.

**Comment by chriseth** [comment]
Needs update in the changelog

**Comment by leonardoalt** [comment]
Updated

File: Changelog.md [hunk 3]
```diff
@@ -1,3 +1,9 @@
+### 0.7.0 (unreleased)
+
+Compiler Features:
+ * SMTChecker: Fix internal error when assigning to a 1-tuple.
```
Comment (chriseth) [inline Changelog.md]: needs update

**Comment by chriseth** [comment]
Needs rebase - looks good otherwise.

**Comment by leonardoalt** [comment]
Updated, should be good now

File: Changelog.md (hunk 3 above)
Comment (chriseth) [reply Changelog.md]: Isn't it a bugfix?

Comment (leonardoalt) [reply Changelog.md]: Ughhhh sorry I'm slow today

**Review by chriseth — APPROVED** [review]
