### PR TITLE
Bytecode difference caused by SSA transform

### LINKED ISSUE #14829: Shift in AST IDs affects inlining and expression splitting decisions in Yul Optimizer, causing bytecode differences
## Description

This is probably related to #14494, I am using solc 0.8.23 and still encounter the issue

## Steps to Reproduce

Here are two standard JSON input files:
[input1.json](https://github.com/ethereum/solidity/files/14132480/input1.json)
[input2.json](https://github.com/ethereum/solidity/files/14132482/input2.json)

The only difference between those is a small source file:
```
"contracts/DummyContract.sol": {
    "content": "contract DummyContract {}"
},
```

We are interested in the `UniversalRouter` bytecode. It was obtained by using the following command:
```
cat input1.json | '/path/to/0.8.23' --standard-json | jq '.contracts."contracts/UniversalRouter.sol".UniversalRouter.evm.bytecode.object' > bytecode1.txt 
```

Resulted bytecodes:
[bytecode1.txt](https://github.com/ethereum/solidity/files/14132486/bytecode1.txt)
[bytecode2.txt](https://github.com/ethereum/solidity/files/14132487/bytecode2.txt)

Bytecodes are expected to be equal, however they have a pretty big diff:

image

### PR DESCRIPTION
**Pull request by nikola-matic**
Fixes https://github.com/ethereum/solidity/issues/14829

### CODE REVIEW

**Comment by 0xalpharush** [comment]
Are there any tests for non-determinism like running in a loop and checking that each compilation of the same source unit results in the same bytecode?

**Comment by nikola-matic** [comment]
> Are there any tests for non-determinism like running in a loop and checking that each compilation of the same source unit results in the same bytecode?

What you're describing is fully deterministic already - i.e. the same sources will always compile to the same bytecode - the issue here is of a different sort; we use a ton of associative containers (e.g. a `std::set` which typically uses a red black tree underneath) to track values (e.g. generated IR variable names) during the optimization stages, and these can sometimes (extremely rarely) change if you insert an unrelated contract that is unused in the rest of the sources (in this case it's an empty dummy contract) which then causes the order of the elements in such containers to be different than without the said unrelated contract/sources. This is what creates the inconsistency in bytecode, and is what this PR fixes.

These inconsistencies don't actually change the behavior of contracts - the code will semantically remain the same, but the bytecode in such cases should none the less be identical, especially when it comes to source verification.

**Comment by cameel** [comment]
Given how easy it is to inadvertently run into this problem when using `YulString` with associative containers, I wonder if we can do something to prevent them in the future. Maybe we could e.g. create wrappers over `set<YulString>` and `map<YulString>` that remove any support for iterating them and add a "style" rule preventing the use of unwrapped containers?

File: libsolutil/CommonData.h [hunk 1]
```diff
@@ -450,6 +450,24 @@ bool contains_if(T const& _t, Predicate const& _p)
...
+/// whilst only taking into account unique elements of _source.
+template <class T>
+void concatenateVectorWithoutDuplicates(std::vector<T>& _destination, std::vector<T> const& _source)
+{
+	for (auto&& elem: _source)
+		if (!contains(_destination, elem))
+			_destination.emplace_back(std::move(elem));
+}
+
+/// Function that removes all elements present in vector @param _sub from vector @_super.
```
Comment (r0qs) [inline libsolutil/CommonData.h]:
```suggestion
/// Function that removes all elements present in vector @param _sub from vector @param _super.
```

File: libyul/optimiser/SSATransform.cpp [hunk 2]
```diff
@@ -245,16 +246,18 @@ void IntroduceControlFlowSSA::operator()(Block& _block)
 				for (auto const& var: varDecl.variables)
 					if (m_variablesToReplace.count(var.name))
 					{
-						variablesDeclaredHere.insert(var.name);
-						m_variablesInScope.insert(var.name);
+						if (!util::contains(variablesDeclaredHere, var.name))
+							variablesDeclaredHere.push_back(var.name);
+						if (!util::contains(m_variablesInScope, var.name))
+							m_variablesInScope.push_back(var.name);
```
Comment (r0qs) [inline libyul/optimiser/SSATransform.cpp]: Since you already add a `concatenateVectorWithoutDuplicates`, maybe it would be nice to also have a helper function that push elements if they don't exists in the vector? I.e. `pushVectorWithoutDuplicates` or something like that.

File: libyul/optimiser/SSATransform.cpp [hunk 3]
```diff
@@ -165,24 +165,24 @@ class IntroduceControlFlowSSA: public ASTModifier
 	NameDispenser& m_nameDispenser;
 	std::set<YulString> const& m_variablesToReplace;
 	/// Variables (that are to be replaced) currently in scope.
-	std::set<YulString> m_variablesInScope;
+	std::vector<YulString> m_variablesInScope;
 	/// Set of variables that do not have a specific value.
```
Comment (r0qs) [inline libyul/optimiser/SSATransform.cpp]:
```suggestion
	/// Variables that do not have a specific value.
```

File: libyul/optimiser/SSATransform.cpp (hunk 2 above)
Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: Not a bad idea honestly

File: libyul/optimiser/SSATransform.cpp [hunk 4]
```diff
@@ -245,16 +246,18 @@ void IntroduceControlFlowSSA::operator()(Block& _block)
 				for (auto const& var: varDecl.variables)
 					if (m_variablesToReplace.count(var.name))
 					{
-						variablesDeclaredHere.insert(var.name);
-						m_variablesInScope.insert(var.name);
+						if (!util::contains(variablesDeclaredHere, var.name))
+							variablesDeclaredHere.push_back(var.name);
```
Comment (r0qs) [inline libyul/optimiser/SSATransform.cpp]: Why not use the `emplaceBackUnique` here? As well in the other places that this pattern is used.
```suggestion
						util::emplaceBackUnique(variablesDeclaredHere, var.name);
```

File: libyul/optimiser/SSATransform.cpp [hunk 5]
```diff
@@ -165,24 +165,24 @@ class IntroduceControlFlowSSA: public ASTModifier
 	NameDispenser& m_nameDispenser;
 	std::set<YulString> const& m_variablesToReplace;
 	/// Variables (that are to be replaced) currently in scope.
-	std::set<YulString> m_variablesInScope;
-	/// Set of variables that do not have a specific value.
-	std::set<YulString> m_variablesToReassign;
+	std::vector<YulString> m_variablesInScope;
```
Comment (cameel) [inline libyul/optimiser/SSATransform.cpp]: Why does `m_variablesInScope` need to be a vector? I don't see it being iterated anywhere. We only use it for lookups.

File: libyul/optimiser/SSATransform.cpp [hunk 6]
```diff
@@ -207,20 +207,20 @@ void IntroduceControlFlowSSA::operator()(Switch& _switch)
...
 
 void IntroduceControlFlowSSA::operator()(Block& _block)
 {
-	std::set<YulString> variablesDeclaredHere;
-	std::set<YulString> assignedVariables;
+	std::vector<YulString> variablesDeclaredHere;
+	std::vector<YulString> assignedVariables;
 
 	util::iterateReplacing(
 		_block.statements,
```
Comment (cameel) [inline libyul/optimiser/SSATransform.cpp:226]: Since you're modifying the code around here anyway, could you fix the indent level for `toPrepend` declaration below? The way it is now it looks confusing, as if it was not meant to be a part of the block or something.

File: libyul/optimiser/SSATransform.cpp [hunk 7]
```diff
@@ -165,24 +165,24 @@ class IntroduceControlFlowSSA: public ASTModifier
 	NameDispenser& m_nameDispenser;
 	std::set<YulString> const& m_variablesToReplace;
 	/// Variables (that are to be replaced) currently in scope.
-	std::set<YulString> m_variablesInScope;
-	/// Set of variables that do not have a specific value.
-	std::set<YulString> m_variablesToReassign;
+	std::vector<YulString> m_variablesInScope;
+	/// Variables that do not have a specific value.
+	std::vector<YulString> m_variablesToReassign;
```
Comment (cameel) [inline libyul/optimiser/SSATransform.cpp]: Maybe a `set` with a custom comparator that compares based on `YulString::str()` would be a cleaner solution here? This would give us a deterministic iteration order while still being a set with logarithmic complexity and not requiring operation through special helpers (which someone could forget to user when modifying the code later, since normal non-unique insertion is still available).

File: libsolutil/CommonData.h [hunk 8]
```diff
@@ -450,6 +450,32 @@ bool contains_if(T const& _t, Predicate const& _p)
...
+		emplaceBackUnique(_destination, elem);
+}
+
+/// Function that removes all elements present in vector @param _sub from vector @param _super.
+template <class T>
+void removeVectorSubset(std::vector<T>& _super, std::vector<T> const& _sub)
+{
+	for (auto const& elem: _sub)
+		_super.erase(std::find(_super.begin(), _super.end(), elem));
+}
```
Comment (cameel) [inline libsolutil/CommonData.h]: I think naming could be clearer here (e.g. I'd use `tryEmplaceBack()` for the first function, analogous to `map::try_emplace()`; or `appendMissing()` for the second one because to me `concatenateVectorWithoutDuplicates()` suggests that it would be symmetrical and remove duplicates from both vectors, but apparently it isn't).

But before we get into that, maybe first say what you think about my suggestion above to use a custom comparator, since it would make these helpers unnecessary in the first place.

File: test/libyul/yulOptimizerTests/ssaTransform/function.yul
Comment (cameel) [inline test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: Do you have a repro of the issue that we could add as a test? I think we should have one like that.

File: libyul/optimiser/SSATransform.cpp (hunk 7 above)
Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: The issue here has nothing to do with the set comparator - `YulString `already overloads `operator<`, so it implicitly uses one anyway; the issue is that the actual names are generated differently in cases where unused contracts are introduced into the compilation pipeline, so the vector approach is used to preserve insertion order, which should be deterministic, rather than name based order. E.g. take a look at the test case change in this PR.

File: libsolutil/CommonData.h (hunk 8 above)
Comment (nikola-matic) [reply libsolutil/CommonData.h]: I picked shit names on purpose because I was 100% certain you'd swoop in with better ones :)

File: test/libyul/yulOptimizerTests/ssaTransform/function.yul
Comment (nikola-matic) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: Unfortunately no - at least nothing sensible. There's the repro from the issue, but it's not exactly feasible to fit it into our testing infrastructure, much like there were no tests added for a similar/same issue we had earlier - https://github.com/ethereum/solidity/pull/14311. The issue is that these things usually happen with larger compilation pipelines, i.e. with a ton of contracts.

File: libyul/optimiser/SSATransform.cpp (hunk 5 above)
Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: Iterating by itself is not a problem - `+=` and `-=` ops are also a part of the problem, so I changed all of them to be safe; I can revert it back to a set and see if it has any negative effect, although not sure how worth it that would be.

File: libyul/optimiser/SSATransform.cpp (hunk 6 above)
Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp:226]: Yes boss 🫡

File: libyul/optimiser/SSATransform.cpp (hunk 5 above)
Comment (cameel) [reply libyul/optimiser/SSATransform.cpp]: How is iterating not a problem? It's the main thing that produces non-determinism here, isn't it?

`+=` and `-=` on the other hand should never be a problem on their own. They may affect order of items in the the container but that's fine if we never depend on that order. And simple lookups don't.

> although not sure how worth it that would be.

I don't really like the idea of shooting in the dark here. I'd rather only change the bits that are known to produce this non-determinism.

Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: Ah you're right, I thought `m_variablesInScope` was assigned to another container that was iterated, but this isn't the case, so `m_variablesInScope` should be safe to revert back to `std::set`.

Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: Yup, you were right; `m_variablesInScope` can be a set - I've reverted it back, pushed the changes, and re-ran the repro to makes sure it's fine.

File: test/libyul/yulOptimizerTests/ssaTransform/function.yul
Comment (cameel) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: Here's a repro, based on the one from the issue:

```bash
cat <<-EOF > A.sol
contract DummyContract {}
EOF

cat <<-EOF > B.sol
contract C {
    bytes x;
    bytes y;
    constructor(bytes memory a_1, bytes memory a_2, bool c) {
        a_1 = "a";
        a_2 = "b";
        if (c)
        {
            a_1 = "c";
            a_2 = "d";
        }
        x = a_1;
        y = a_2;
    }
}

contract D is C {
    constructor(bytes memory a_1, bytes memory a_2, bool c) C(a_1, a_2, c) {}
}
EOF

diff --unified --color \
    <(solc       B.sol --via-ir --bin --ir-optimized --optimize --debug-info none --yul-optimizations "a:") \
    <(solc A.sol B.sol --via-ir --bin --ir-optimized --optimize --debug-info none --yul-optimizations "a:")
```

Does not work with the default sequence unfortunately. Not the full one at least - bytecode diverges after `a` but then `c` and `u` remove enough variables to make it match again. I think that the big repro just has enough of cases like this that some of them happen to have impact on decisions of other optimizer steps, like inliner or rematerializer, and snowball into something bigger over many repetitions.

The repro at least shows how the initial bytecode differences appear in SSA. They indeed come from the non-deterministic order of SSA variables inserted at the beginning of functions and at control joins by the loop in `IntroduceControlFlowSSA::operator()(Block&)`.

For SSA alone `C` could even be reduced to something smaller (see snippet below), but the one in the repro is closer to the one in the issue and I think that it's the control join case that triggers the snowballing differences, so I kept the `if`.

```solidity
contract C {
    constructor(bytes memory a_1, bytes memory a_2) {
        a_1 = "a";
        a_2 = "b";
    }
}
```

Comment (cameel) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: I wanted to understand why it's specifically the combination of constructors, inheritance, and memory parameters that's needed to get names to actually change in a way that triggers this bug. I could not do it for example just by using local variables because they seemed to have local numbering within fuctions (which was odd - I thought everything was supposed to be numbered globally based on AST IDs).

Turns out none of these things actually matter. I was fooled by `VarNameCleaner` and `NameSimplifier` :) Looks like everything does have a global numbering based on AST IDs after all, it's just that most of the time cleanup renumbers names in a way that makes it look like they were the same with and without AST ID shift. This is annoying when analyzing bugs like this, because there's no option to disable the cleaning. I had to comment it out to see what's really happening.

In the end that specific combination of features is not as crucial for reproducing these issues as I assumed it would be. It just happened to shift the IDs more, which made this easier to reproduce. But this can also be achieved by adding more stuff to the dummy file.

Here's a conceptually simpler repro:

```bash
cat <<-EOF > A.sol
contract DummyContract1 {}
contract DummyContract2 {}
contract DummyContract3 {}
contract DummyContract4 {}
contract DummyContract5 {}
EOF

cat <<-EOF > B.sol
contract C {
    function f(uint8 a_0, uint8 a_1, uint8 a_2) public {
        a_1 = 1;
        a_2 = 2;
    }
}
EOF

diff --unified --color \
    <(solc       B.sol --via-ir --bin --ir-optimized --optimize --debug-info none --yul-optimizations "a:") \
    <(solc A.sol B.sol --via-ir --bin --ir-optimized --optimize --debug-info none --yul-optimizations "a:")
```

With just one dummy contract all names have single-digit suffixes and the same length, which keeps them in the right relative order. With name cleanup commented-out it looks like this after SSA:
```diff
-            function fun_f(var_a_2, var_a, var_a_6)
+            function fun_f(var_a_4, var_a, var_a_8)
             {
-                let var_a_6_16 := var_a_6
+                let var_a_8_16 := var_a_8
                 let var_a_17 := var_a
                 ...
```

If we add more dummy contracts to get a bigger shift in AST IDs, things get more irregular and order changes:
```diff
-            function fun_f(var_a_2, var_a, var_a_6)
+            function fun_f(var_a, var_a_10, var_a_12)
             {
-                let var_a_6_16 := var_a_6
-                let var_a_17 := var_a
+                let var_a_10_16 := var_a_10
+                let var_a_12_17 := var_a_12
                 ...
```

Hopefully, understanding what happens to these names will come in handy the next time we run into an issue like this.

File: libyul/optimiser/SSATransform.cpp (hunk 7 above)
Comment (cameel) [reply libyul/optimiser/SSATransform.cpp]: Yes, you're right. I thought `YulString` did not have a deterministic sort order but it does so we can't do it the way I suggested above.

Still, having to remember to use these helpers to manipulate the vector like that just seems too error-prone to me. It would be fine it this was a separate data structure that hides the original `push_back()`&co but it's not.

How about a different approach - instead of keeping duplicates out on every insertion, how about we keep them in the vector but skip them later during iteration? We could have a nice and reusable `unique()` function that would give you a vector with only unique items (I actually wanted to suggest `ranges::unique()` originally, but I see it removes only adjacent duplicates).

File: libsolutil/CommonData.h [hunk 9]
```diff
@@ -450,6 +450,32 @@ bool contains_if(T const& _t, Predicate const& _p)
...
+template <class T>
+void appendMissing(std::vector<T>& _destination, std::vector<T> const& _source)
+{
+	for (auto&& elem: _source)
+		tryEmplaceBack(_destination, elem);
+}
+
+/// Function that removes all elements present in vector @param _sub from vector @param _super.
+template <class T>
+void removeVectorSubset(std::vector<T>& _super, std::vector<T> const& _sub)
```
Comment (cameel) [inline libsolutil/CommonData.h]: Why not make it a `-=` operator for `vector`? We already have `-=` for `set` and `+=` for `vector` here so it would fit the pattern.

File: libyul/optimiser/SSATransform.cpp (hunk 7 above)
Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: The reason I added the helper functions was to reduce code duplication, and then to eventually re-use them in other fixes of this type (retroactively, since we've already had at least one PR that used this same approach). I would prefer to merge this as is, and then we can decide on one of the Wednesday calls what would be the ideal way to address this in the future, and then we can re-factor in a separate PR.

File: libsolutil/CommonData.h (hunk 9 above)
Comment (nikola-matic) [reply libsolutil/CommonData.h]: Yeah, I thought about it, but considering that `+=` doesn't remove duplicates, and that conversely `-=` wouldn't do so either, it seemed a bit odd. I.e., with a `set`, all elements are guaranteed to be unique, whereas in a vector they're not.

File: Changelog.md [hunk 10]
```diff
@@ -8,6 +8,7 @@ Compiler Features:
 
 Bugfixes:
  * SMTChecker: Fix internal error when using bitwise operators with an array element as argument.
+ * Yul Optimizer: Fix ``SSATransform`` step that would sometimes cause non-deterministic output in cases where one or more unused contracts were added to the compilation pipeline.
```
Comment (cameel) [inline Changelog.md]:
```suggestion
 * Yul Optimizer: Fix the order of assignments generated by ``SSATransform`` being dependent on AST IDs, sometimes resulting in different (but equivalent) bytecode when unrelated files were added to the compilation pipeline.
 ```

File: libsolutil/CommonData.h (hunk 9 above)
Comment (cameel) [reply libsolutil/CommonData.h]: I don't think this has anything to do with whether `+=` removes duplicates. For that operator just appending items, without considering whether they're duplicates or not, seems like the intuitive default action.

In the same vein leaving the vector in a state where no copy of removed items remains seems like the intuitive default action for `-=`. It's what I'd normally expect and it does not need any extra settings so it's perfect for an operator.

Removing only some copies of specified items seems more like a special case and in that case I'd probably also want to specify which copies to preserve, so a function makes more sense for it.

File: libyul/optimiser/SSATransform.cpp (hunk 7 above)
Comment (cameel) [reply libyul/optimiser/SSATransform.cpp]: The problem I have with it is that "a vector for which you have to remember to keep items unique by hand" does not seems like a great data structure to have and I'd rather avoid generalizing that pattern without also making it safer. It's dangerous and if we're not careful we'll just turn one kind of easy to make, hard to find bug into another.

If you really want to keep this pattern then at least wrap it in some kind of custom container. I.e. define a `UniqueVector` class where these helpers are methods and it only provides access to the `const` version of the underlying vector. Should be quite short and without too much boilerplate if you simply put it in `CommonData.h` where the helpers currently are. This way we'll be able to keep it somewhat contained.

We might even, in the future, store an extra `set` inside to make lookups more efficient. The linear lookups in the current version bother me a bit, but I'm ignoring that because the set of variables in SSA will probably never be that big and managing the set by hand would make managing it even more error-prone. But if you promote it to more general pattern that we'll use elsewhere that becomes a consideration again.

Comment (nikola-matic) [reply libyul/optimiser/SSATransform.cpp]: Again, this is the same approach used in https://github.com/ethereum/solidity/pull/14311, which wasn't *ideal* then either; I'd rather not waste time implementing something without getting to a consensus as to what the best approach for this would be (or at least, and combination of best and feasible). @ekpyron?

Comment (cameel) [reply libyul/optimiser/SSATransform.cpp]: The important difference is that your PR generalizes that approach, which is not a good idea, because it will just make it easier for this unsafe pattern to spread.

I'm not demanding a perfect solution here, I'm just saying that there are ways to make it safer and some of them require very little extra effort. Even something as simple as this would do:

```c++
template <typename T>
class UniqueVector
{
public:
	std::vector<T> const& content() const { return m_content; }
	bool contains(T const& _value) const { return m_content.find(_value) != m_content.end(); }

	void append(T _value)
	{
		if (!contains(_value))
			m_content.emplace_back(std::move(_value));
	}

	void appendMissing(std::vector<T> const& _values)
	{
		for (auto const& value: _values)
			append(m_content, value);
	}

	void removeAll(std::vector<T> const& _values)
	{
		for (auto const& value: _values)
			m_content.erase(std::find(m_content.begin(), m_content.end(), _value));
	}

private:
	std::vector<T> m_content;
};
```

which is basically your solution but in a safety wrapper that won't let anyone forget to use the special helpers. Does not have to have a full set of methods and other bells and whistles - just slap a TODO on it and we'll add them when we need them.

File: libsolutil/CommonData.h [hunk 11]
```diff
@@ -343,6 +343,49 @@ void joinMap(std::map<K, V>& _a, std::map<K, V>&& _b, F _conflictSolver)
 	}
 }
 
+template<typename T>
+class UniqueVector
+{
+public:
+	std::vector<T>& contents() { return m_contents; }
```
Comment (cameel) [inline libsolutil/CommonData.h]: Wasn't the point of having to implement `swap()` and all the extra helpers that it allows us to keep acccess to the content const?

```suggestion
	std::vector<T> const& contents() const { return m_contents; }
```

File: test/libyul/yulOptimizerTests/ssaTransform/function.yul
Comment (cameel) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: So what about this one? Can you add the repro as a test?

Comment (nikola-matic) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: How would I add this? cmdlineTest?

Comment (cameel) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: Yeah. We already have one or two tests of this kind from previous issues so you can just reuse that pattern.

Comment (cameel) [reply test/libyul/yulOptimizerTests/ssaTransform/function.yul:1]: [`~name_dependent_cse_bug`](https://github.com/ethereum/solidity/tree/develop/test/cmdlineTests/~name_dependent_cse_bug) and [`~bytecode_equivalence_independent_of_import_discovery_order`](https://github.com/ethereum/solidity/tree/develop/test/cmdlineTests/~bytecode_equivalence_independent_of_import_discovery_order)

File: test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py [hunk 12]
```diff
@@ -0,0 +1,53 @@
...
+        raise RuntimeError(dedent("""\
+            `solc` compiler not found.
+            Please ensure you set the SOLC environment variable
+            with the correct path to the compiler's binary.
+        """))
+
+    # Repro for https://github.com/ethereum/solidity/issues/14829
+    save_bytecode(Path('A.bin'),
+                  solc_bin_report(solc_binary,
+                                  [Path('A.sol')],
```
Comment (r0qs) [inline test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: Souldn't this be `B` instead? And also `B.bin` above?
```suggestion
                                  [Path('B.sol')],
```

File: test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py [hunk 13]
```diff
@@ -0,0 +1,53 @@
...
+                                  via_ir=True,
+                                  optimize=True,
+                                  yul_optimizations='a:'),
+                  contract='B')
+    save_bytecode(Path('AB.bin'),
+                  solc_bin_report(solc_binary,
+                                  [Path('A.sol'),
+                                   Path('B.sol')],
+                                  via_ir=True, optimize=True,
```
Comment (r0qs) [inline test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: just to be a bit annoying ;P

```suggestion
                                  via_ir=True,
                                  optimize=True,
```

File: scripts/common/cmdline_helpers.py [hunk 14]
```diff
@@ -37,15 +37,21 @@ def f(*args, **kwargs):
     return tmp_dir_decorator
 
 
-def solc_bin_report(solc_binary: str, input_files: List[Path], via_ir: bool) -> FileReport:
+def solc_bin_report(solc_binary: str,
+                    input_files: List[Path],
+                    via_ir: bool,
+                    optimize: bool = False,
+                    yul_optimizations: Optional[str] = None) -> FileReport:
```
Comment (r0qs) [inline scripts/common/cmdline_helpers.py]: Just as a note, so we can remember to eventually refactor this. We could pass a dictionary here like  what was done in https://github.com/ethereum/solidity/blob/bbb7f58be026fdc51b0b4694a6f25c22a1425586/scripts/externalTests/test_helpers.py#L52 or event have a class for compiler settings so we could reuse in other scripts. I believe this will be desirable when we migrate the external tests to python.

File: test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py (hunk 12 above)
Comment (nikola-matic) [reply test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: Ha, yes, you're right; but unfortunately, doesn't seem to solve my problem :/

Comment (r0qs) [reply test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: Oh, but what is the problem then? If you want, we can discuss that in the Matrix dev channel, just ping me there.

Comment (cameel) [reply test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: I think that the problem was that this does not actually reproduce the problem on `develop`. And I just posted a solution to that on the channel:

> Either remove `add_preamble()` or reduce the number of dummy contracts. Removing two last ones does it for me.

This shorter repro requires a specific shift in AST IDs so even adding a pragma apparently breaks it. Maybe it would actually better to use the more complex one. It seemed more robust to me.

Comment (cameel) [reply test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: By the way, warnings can be suppressed by adding something like `a_1; a_2; a_3;` at the end of the function and making it `pure`. Which is not great, but still better than having the warnings :)

File: test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py (hunk 13 above)
Comment (cameel) [reply test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: To be even more annoying, please stick to our usual Python style:
```python
   save_bytecode(
       Path('AB.bin'),
       solc_bin_report(
           solc_binary,
           [Path('A.sol'), Path('B.sol')],
           via_ir=True,
           optimize=True,
           yul_optimizations='a:'
        ),
        contract='B'
    )
```

Which is pretty much the same as the one we use in C++ and is also PEP-8 compliant. If this is a result of some auto-formatter, you should be using using [black](https://black.readthedocs.io/en/stable/) - which will give you exactly that style.

**Comment by nikola-matic** [comment]
@cameel this should be ready now.

File: test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py [hunk 15]
```diff
@@ -0,0 +1,58 @@
...
+    save_bytecode(
+        Path('AB.bin'),
+        solc_bin_report(
+            solc_binary,
+            [Path('A.sol'),
+             Path('B.sol')],
+            via_ir=True,
+            optimize=True,
+            yul_optimizations='a:'),
+        contract='B')
```
Comment (cameel) [inline test/cmdlineTests/~bytecode_equivalence_with_unused_contracts/test.py]: That's still not quite the style I mentioned in https://github.com/ethereum/solidity/pull/14968#discussion_r1567333367:
```suggestion
    save_bytecode(
        Path('B.bin'),
        solc_bin_report(
            solc_binary,
            [Path('B.sol')],
            via_ir=True,
            optimize=True,
            yul_optimizations='a:',
        ),
        contract='B',
    )
    save_bytecode(
        Path('AB.bin'),
        solc_bin_report(
            solc_binary,
            [Path('A.sol'), Path('B.sol')],
            via_ir=True,
            optimize=True,
            yul_optimizations='a:',
        ),
        contract='B',
    )
```

But if we're at it, it would probably be even better off like this to underscore the fact that only the names really change:
```suggestion
    common_options = {
        'via_ir': True,
        'optimize': True,
        'yul_optimizations': 'a:',
    }
    save_bytecode(
        Path('B.bin'),
        solc_bin_report(solc_binary, [Path('B.sol')], **common_options),
        contract='B',
    )
    save_bytecode(
        Path('AB.bin'),
        solc_bin_report(solc_binary, [Path('A.sol'), Path('B.sol')], **common_options),
        contract='B',
    )
```

File: scripts/common/cmdline_helpers.py (hunk 14 above)
Comment (cameel) [inline scripts/common/cmdline_helpers.py]: And this one too. It's basically the same rule I mentioned in https://github.com/ethereum/solidity/pull/14968#discussion_r1567333367 so I expected it to be fixed as a part of that too:
```suggestion
def solc_bin_report(
    solc_binary: str,
    input_files: List[Path],
    via_ir: bool,
    optimize: bool = False,
    yul_optimizations: Optional[str] = None,
) -> FileReport:
```

**Review by cameel — DISMISSED** [review]
Looks good in terms of correctness, just needs two style tweaks.

**Review by cameel — APPROVED** [review]

File: libsolutil/CommonData.h [hunk 16]
```diff
@@ -343,6 +343,49 @@ void joinMap(std::map<K, V>& _a, std::map<K, V>&& _b, F _conflictSolver)
...
+
+private:
+	std::vector<T> m_contents;
+};
+
+template<typename T>
+void swap(UniqueVector<T>& _lhs, UniqueVector<T>& _rhs)
+{
+	std::swap(_lhs.contents(), _rhs.contents());
+}
```
Comment (ekpyron) [inline libsolutil/CommonData.h:387]: I was just looking at this to consider using it for https://github.com/ethereum/solidity/pull/15262 and noticed: this swap function won't work, will it? ``contents`` is a const reference, you can't swap these things...
what the ``std::swap`` below will do is to use the implicit move constructors of ``UniqueVector``...

Comment (nikola-matic) [reply libsolutil/CommonData.h:387]: Yeah, you're right, `contents()` should ideally just return a reference...

Comment (nikola-matic) [reply libsolutil/CommonData.h:387]: I would have honestly expected a compilation error here, this is really insidious.

Comment (ekpyron) [reply libsolutil/CommonData.h:387]: I mean, it's currently unused - and C++ only type-checks on instantiation :-). And I mean, it's not unused without reason: we don't need it, so we might as well remove the swap - ``std::swap`` will just work based on moving regardless
