### PR TITLE
Reports an error on unimplemented modifiers in a function definition.

### LINKED ISSUE #11468: ICE when invoking a modifier overriden by an unimplemented one
It is currently possible to override a modifier with one that has no implementation. Doing this with functions is forbidden. An attempt to invoke such a modifier results in an ICE:

```solidity
contract B {
    modifier m() virtual { _; }
}
abstract contract C is B {
    modifier m() virtual override;
}
contract D is C {
    function f() m public {}
}
```
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/AST.h(1054): Throw in function const solidity::frontend::Block& solidity::frontend::ModifierDefinition::body() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

I think this should be forbidden like it is for functions. Even then, however, it will still be possible to define an unimplemented modifier by sandwiching it between two implemented ones (see #11445) and then invoke it by qualifying it with the name of the contract where it has no implementation - this should probably be forbidden too.

## Environment
- Compiler version: 0.8.4
- Operating system: Arch Linux

### PR DESCRIPTION
**Pull request by christianparpart**
Partial fix for #11468

(some tests are still failing though. working on it).

I'll squash commits once :+1:'d

### CODE REVIEW

**Comment by chriseth** [comment]
So your fix is to require an overriding modifier to be implemented, right? Is this the same requirement for functions? If yes, can we somehow to do it in a uniform manner?

**Comment by cameel** [comment]
@chriseth For functions the rule seems to be that you cannot override an implemented function with an unimplemented one unless:
- The function you're overriding is unimplemented too.
- You use multiple inheritance with a linearized order that effectively puts the unimplemented function before the implemented one (this is basically #11468).

If you manage to override it, you can call such an unimplemented function it in two cases:
- There is no code actually generated for the call. E.g. because you do it in a function that is itself overriden.
- (after #11472) You make a call via `super` and the unimplemented function gets skipped.

@christianparpart Looks like this breaks quite a few tests. I think that we need to allow at least cases where the modifier is used in its own (abstract) contract but only implemented in one that inherits from it (`empty_modifier_body.sol`). Those are probably not the only ones though.

Also, you should add some new tests, including the one from the issue. I'd also add some where you explicitly reference the unimplemented modifier via its contract name (we do not have a test for that).

File: libsolidity/analysis/OverrideChecker.cpp [hunk 1]
```diff
@@ -573,7 +573,17 @@ void OverrideChecker::checkOverride(OverrideProxy const& _overriding, OverridePr
 			);
 	}
 
-	if (_super.isFunction())
+	if (_super.isModifier())
+	{
+		if (_overriding.unimplemented() && !_super.unimplemented())
```
Comment (chriseth) [inline libsolidity/analysis/OverrideChecker.cpp]: Can you extract the case for function and only create one error (inserting the "modifier" / "function" string based on `isModifier()`)?

File: libsolidity/analysis/OverrideChecker.cpp [hunk 2]
```diff
@@ -573,6 +573,16 @@ void OverrideChecker::checkOverride(OverrideProxy const& _overriding, OverridePr
 			);
 	}
 
+	if (_overriding.unimplemented() && !_super.unimplemented())
+		overrideError(
+			_overriding,
+			_super,
+			4593_error,
+			"Overriding an implemented " + _super.astNodeName() +
```
Comment (chriseth) [inline libsolidity/analysis/OverrideChecker.cpp:583]: Can this lead to `variable declaration` here?

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 3]
```diff
@@ -131,6 +131,16 @@ void PostTypeChecker::endVisit(ModifierInvocation const& _modifierInvocation)
 	callEndVisit(_modifierInvocation);
 }
 
+bool PostTypeChecker::visit(FunctionDefinition const& _functionDefinition)
```
Comment (chriseth) [inline libsolidity/analysis/PostTypeChecker.cpp]: Why are these needed?

File: test/libsolidity/syntaxTests/modifiers/modifier_abstract_override.sol [hunk 4]
```diff
@@ -0,0 +1,11 @@
+contract A {
+    modifier m() virtual { _; }
+}
+abstract contract B is A {
+    modifier m() virtual override;
+}
+contract C is B {
+    function f() m public {}
+}
```
Comment (cameel) [inline test/libsolidity/syntaxTests/modifiers/modifier_abstract_override.sol:9]: Failing test cases:
```solidity
contract A {
    modifier m() virtual { _; }
}
abstract contract B {
    modifier m() virtual;
}
contract C is A, B {
    modifier m() override(A, B) { _; }
    function f() B.m public {}
}
```

```solidity
abstract contract A {
    modifier m() virtual;
}
contract B is A {
    modifier m() virtual override { _; }
}
contract C is B {
    function f() A.m public {}
}
```
```
Internal compiler error during compilation:
/solidity/libsolidity/ast/AST.h(1070): Throw in function const solidity::frontend::Block& solidity::frontend::ModifierDefinition::body() const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what:
[solidity::util::tag_comment*] =
```

Comment (cameel) [inline test/libsolidity/syntaxTests/modifiers/modifier_abstract_override.sol:9]: I think we could use some positive test cases too (unless they already exist somewhere):

Overriding unimplemented with unimplemented:
```solidity
abstract contract A {
    modifier m() virtual;
}
abstract contract B is A {
    modifier m() virtual override;
}
abstract contract C is B {
    modifier m() virtual override;
    function f() m public {}
}
```
Leaving a modifier somewhere in the chain unimplemented through multiple inheritance:
```solidity
contract A {
    modifier m() virtual { _; }
}
abstract contract B {
    modifier m() virtual;
}
contract C is A, B {
    modifier m() override(A, B) { _; }
    function f() m public {}
}
```

Use of an unimplemented modifier in an abstract contract:
(**EDIT**: Replaced `A.m` with `m`. Also, this should not be an error after all)
```solidity
abstract contract A {
    modifier m() virtual;
    function f() m public {}
}
contract B is A {
    modifier m() virtual override { _; }
}
```

Use of an unimplemented modifier on a method that gets overridden:
(**EDIT**: Replaced `A.m` with `m`, changed `B` to abstract and removed `m` override from `B`)
```solidity
abstract contract A {
    modifier m() virtual;
    function f() m public virtual {}
}
abstract contract B is A {
    function f() public override {}
}
```

File: libsolidity/analysis/OverrideChecker.cpp (hunk 2 above)
Comment (cameel) [reply libsolidity/analysis/OverrideChecker.cpp:583]: I don't think so unless there's a way to create an unimplemented getter.

I'd add an assert just in case:
```c++
solAssert(!_overriding.isVariable() || !_overriding.unimplemented(), "");
```

File: Changelog.md [hunk 5]
```diff
@@ -29,6 +29,7 @@ Bugfixes:
  * Type Checker: Fix internal compiler error when attempting to use an invalid external function type on pre-byzantium EVMs.
  * Type Checker: Make errors about (nested) mapping type in event or error parameter into fatal type errors.
  * Type Checker: Fix internal compiler error when overriding receive ether function with one having different parameters during inheritance.
+ * Type Checker: Fix internal compiler error when overriding an implemented modifier with an unimplemented.
```
Comment (cameel) [inline Changelog.md]:
```suggestion
 * Type Checker: Fix internal compiler error when overriding an implemented modifier with an unimplemented one.
```

File: libsolidity/analysis/PostTypeChecker.cpp [hunk 6]
```diff
@@ -434,4 +444,5 @@ PostTypeChecker::PostTypeChecker(langutil::ErrorReporter& _errorReporter): m_err
 	m_checkers.push_back(make_shared<EventOutsideEmitErrorOutsideRevertChecker>(_errorReporter));
 	m_checkers.push_back(make_shared<NoVariablesInInterfaceChecker>(_errorReporter));
 	m_checkers.push_back(make_shared<ReservedErrorSelector>(_errorReporter));
+	//m_checkers.push_back(make_shared<ModifierImplementedChecker>(_errorReporter));
```
Comment (cameel) [inline libsolidity/analysis/PostTypeChecker.cpp]: Looks like a piece of commented-out debug code. Please remove.

File: libsolidity/analysis/PostTypeChecker.cpp (hunk 3 above)
Comment (christianparpart) [reply libsolidity/analysis/PostTypeChecker.cpp]: it's a left-over from an earlier attempt that i already deleted & squashed away. I'll drop this part, too.

File: libsolidity/analysis/TypeChecker.cpp [hunk 7]
```diff
@@ -613,6 +615,7 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
 
 void TypeChecker::visitManually(
 	ModifierInvocation const& _modifier,
+	ContractDefinition const* _contract,
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: Is this different from `m_currentContract`?

File: libsolidity/analysis/TypeChecker.cpp [hunk 8]
```diff
@@ -639,6 +643,17 @@ void TypeChecker::visitManually(
 						"Can only use modifiers defined in the current contract or in base contracts."
 					);
 			}
+
+			if (!modifierDecl->isImplemented() && !_contract->abstract())
+			{
+				m_errorReporter.typeError(
+					9113_error,
+					_modifier.location(),
+					"Cannot call unimplemented modifier."
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp]: I think this depends on whether the lookup is virtual or static.

File: libsolidity/analysis/TypeChecker.cpp [hunk 9]
```diff
@@ -629,16 +629,30 @@ void TypeChecker::visitManually(
 	if (auto modifierDecl = dynamic_cast<ModifierDefinition const*>(declaration))
 	{
 		parameters = &modifierDecl->parameters();
-		if (auto const* modifierContract = dynamic_cast<ContractDefinition const*>(modifierDecl->scope()))
-			if (m_currentContract)
+		solAssert(modifierDecl->annotation().contract, "");
+		auto const* modifierContract = dynamic_cast<ContractDefinition const*>(modifierDecl->scope());
+		solAssert(modifierContract, "");
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: This could be moved into the `if` below.

File: libsolidity/analysis/TypeChecker.cpp [hunk 10]
```diff
@@ -629,16 +629,30 @@ void TypeChecker::visitManually(
...
+			if (!contains(m_currentContract->annotation().linearizedBaseContracts, modifierContract))
+				m_errorReporter.typeError(
+				9428_error,
+					_modifier.location(),
+					"Can only use modifiers defined in the current contract or in base contracts."
+				);
+
+			if (m_currentContract->derivesFrom(*modifierDecl->annotation().contract) &&
+				!modifierDecl->isImplemented()
+			)
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
			if (
				m_currentContract->derivesFrom(*modifierDecl->annotation().contract) &&
				!modifierDecl->isImplemented()
			)
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 11]
```diff
@@ -629,16 +629,30 @@ void TypeChecker::visitManually(
...
+		auto const* modifierContract = dynamic_cast<ContractDefinition const*>(modifierDecl->scope());
+		solAssert(modifierContract, "");
+		if (m_currentContract)
+		{
+			if (!contains(m_currentContract->annotation().linearizedBaseContracts, modifierContract))
+				m_errorReporter.typeError(
+				9428_error,
+					_modifier.location(),
+					"Can only use modifiers defined in the current contract or in base contracts."
+				);
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]:
```suggestion
				m_errorReporter.typeError(
					9428_error,
					_modifier.location(),
					"Can only use modifiers defined in the current contract or in base contracts."
				);
```

File: libsolidity/analysis/TypeChecker.cpp [hunk 12]
```diff
@@ -629,16 +629,30 @@ void TypeChecker::visitManually(
...
+
+			if (m_currentContract->derivesFrom(*modifierDecl->annotation().contract) &&
```
Comment (cameel) [inline libsolidity/analysis/TypeChecker.cpp]: Isn't this really equivalent to `contains(m_currentContract->annotation().linearizedBaseContracts, modifierContract)` used above? I think this `if` could be just `else` for the `if` above, with the `!modifierDecl->isImplemented()` check inside.

File: test/libsolidity/syntaxTests/modifiers/modifier_call_unimplemented_1.sol [hunk 13]
```diff
@@ -0,0 +1,15 @@
+// SPDX-License-Identifier: UNLICENSED
+pragma solidity >= 0.5.0;
+
```
Comment (cameel) [inline test/libsolidity/syntaxTests/modifiers/modifier_call_unimplemented_1.sol]: We typically don't include these in tests. They get added automatically by the test suite.
And why specifically 0.5.0? The `B.m` call syntax for modifiers wasn't added until 0.7.x.

File: test/libsolidity/syntaxTests/modifiers/modifier_abstract_override.sol (hunk 4 above)
Comment (cameel) [reply test/libsolidity/syntaxTests/modifiers/modifier_abstract_override.sol:9]: What about these? Could you add them as tests?

All but the second one are currently errors (`Cannot call unimplemented modifier.`). I think they should all work without errors because equivalent examples for virtual functions do pass.

**Review by cameel — CHANGES_REQUESTED** [review]
Most of the comments below are cosmetic issues but there's also one that's a blocker in my opinion: I think that the cases I listed in https://github.com/ethereum/solidity/pull/11471#discussion_r647355644 are not handled correctly. They result in errors in cases that worked before and should still work because they work for functions.

File: test/libsolidity/syntaxTests/modifiers/modifier_call_unimplemented_2.sol [hunk 14]
```diff
@@ -0,0 +1,14 @@
+// SPDX-License-Identifier: UNLICENSED
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/modifiers/modifier_call_unimplemented_2.sol]: Why not GPL?

Comment (christianparpart) [reply test/libsolidity/syntaxTests/modifiers/modifier_call_unimplemented_2.sol]: This should have not been in there, I only added that so `./solc/solc` during debugging tests did not complain. will remove.

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
Needs test updates.

File: libsolidity/analysis/TypeChecker.cpp (hunk 7 above)
Comment (christianparpart) [reply libsolidity/analysis/TypeChecker.cpp]: I found m_currentContract just later. so I dropped that part again.

**Review by chriseth — DISMISSED** [review]

**Comment by cameel** [comment]
I have changed the first comment because now this no longer completely fixes #11468.

**Comment by chriseth** [comment]
I think @christianparpart wanted to create a new issue for the other part.

**Review by cameel — COMMENTED** [review]
I think it would be better to still include test cases from https://github.com/ethereum/solidity/pull/11471#discussion_r647355644 in this PR. If the PR changes the behavior for any of them, then it would be a non-backwards compatible change.

**Review by cameel — APPROVED** [review]
