### PR TITLE
ossfuzz regression ci

### LINKED ISSUE #6474: [ossfuzz] CI to run fuzzer regressions
## Abstract

Fuzzer regressions are regressions for fuzzer discovered bugs. We can use a new CI to check if a previously discovered bug is not reintroduced by a PR.

## Motivation

At a minimum
  - we store fuzzer binaries created by the build ossfuzz job as artifacts
  - clone the regressions from the solidity-fuzzing-corpus repo
  - run fuzzer binary against all test inputs in the repo

Latency: ~5 minutes

### PR DESCRIPTION
**Pull request by bshastry**
(closes #6474 )

### CODE REVIEW

**Comment by chriseth** [comment]
I'm wondering if this is really something we want to do as part of the CI. Shouldn't we have regular regression tests for bugs found by the fuzzer anyway?

**Comment by bshastry** [comment]
> I'm wondering if this is really something we want to do as part of the CI. Shouldn't we have regular regression tests for bugs found by the fuzzer anyway?

There are two types of regressions:
  - class 1: regression of bug found by fuzzer
  - class 2: regression of bug not found by fuzzer but in some program path already covered by the fuzzer

You are right that we should add tests for class 1 above, so they get caught during regular regression tests. This CI complements this setup with catching class 2 as well. 

Example use case is an optimizer PR that contains a new bug in a program path already covered by the fuzzer, or an optimizer bug fix PR that fixes the specific bug but perhaps not another one that may be triggered by some input in the fuzzing corpus.

I have been sort of doing this manually on select optimizer PRs until now, but it is something that could easily be automated.

Catching class 2 also requires us to maintain an up-to-date version of fuzzing corpus from time to time. We can do revision control of fuzzing corpus in the [solidity-fuzzing-corpus git repo](https://github.com/ethereum/solidity-fuzzing-corpus).

[Google actually recommends doing this](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#regression-testing) because it saves them resources if we catch such bugs in CI.

**Comment by bshastry** [comment]
Notes to continue work
  - The regression CI fails on known (unfixed) issues such as memory leaks. Need to suppress them for now so that we focus on high-priority issues e.g., optimizer bug.
  - Error reporting can be better to help devs get more actionable info. At the moment, raw logs are stored as artifacts for later inspection.

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `c37eeb24df7f802c7af679c4cd2642fd161d43b9`:
```
Error: Trailing whitespace found:
 scripts/regressions.py:27: help="""Directory where test results will be 

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `b34a1f376549758cd8a8652ae8005444cdf82dd3`:
```
Error: Trailing whitespace found:
 scripts/regressions.py:28: help="""Directory where test results will be 

```
Please check that your changes are working as intended.

**Comment by bshastry** [comment]
Update: Ported test runner to a python script that suppresses memory leaks for the moment. This PR can quickly report (assuming the fuzzer corpus repo is up-to-date) regressions introduced by changes to `solc` parsing and the yul optimizer subsystems.

File: scripts/download_ossfuzz_corpus.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/usr/bin/env sh
+set -e
+
+(
```
Comment (axic) [inline scripts/download_ossfuzz_corpus.sh]: Why is a subshell needed here?

Comment (chriseth) [reply scripts/download_ossfuzz_corpus.sh]: Because of the directory change. The other question would be: Why do we clone to the root directory? Perhaps we should at least check whether `$CI` is set? Or clone to `/tmp` instead?

Comment (bshastry) [reply scripts/download_ossfuzz_corpus.sh]: Thanks, removed subshell and moved corpus cloning to `/tmp`

**Comment by chriseth** [comment]
The tests take 7 minutes - shall we add them to the nightly run instead?

**Comment by bshastry** [comment]
@chriseth There is some room for optimization (making the tests complete faster) if you think it is something that is worthwhile. I can make use of python multithreading module to run as many tests as the number of cores we have in parallel.

Otherwise, running this CI on a nightly (once every night?) sounds good as well.

**Comment by bshastry** [comment]
Since we are moving to a nightly build that will probably report errors privately, here are some notes to aid debugging

- Each fuzzer has a corresponding log file that is stored as artifacts
- To investigate an ASan error, you'd need to go to the log file corresponding to the failing fuzzer
  - Then you grep for "ERROR: AddressSanitizer" to locate the test case that led to the failure. Note that there may be more than one unique error per fuzzer
  - Next, you locate the test case in the [solidity-fuzzing-corpus](https://github.com/ethereum/solidity-fuzzing-corpus) repo
  - `solc` errors can be reproduced on the command line. yul optimizer bugs need a more elaborate triage setup. You'd have to use a combination of `solc` and `yulrun` to pin-point the root-cause of failure.

**Review by chriseth — APPROVED** [review]
