### PR TITLE
[SMTChecker] Fix crash when analysing try-catch clauses with function call.

### LINKED ISSUE #11181: [SMTChecker] ICE in void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
## Description

This contract:
```solidity
pragma experimental SMTChecker;
contract C {
    function f() public returns (uint, uint) {
        try this.f() {
        } catch Error(string memory) {
			address a = g();
		}
	}
	function g() public pure returns (address) {
	}
}
```

produces:

```
Internal compiler error during compilation:
/solidity/libsolidity/formal/SMTEncoder.cpp(2353): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smtutil::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

when compiled with solc.

Looks like the fix for #10600 didn't handle all try/catch issues.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.8.4-develop.2021.3.26+commit.f24b2254.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 20.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by blishko**
Fixes #11181.

The referenced issue shows that SMTChecker crashes when BMC engine is analyzing try-catch clauses where a catch clause calls a function which returns value or contains local variables.

The reason was that `SMTEncoder::mergeVariables` assumes that the true branch is analyzed before the false branch. However, merging information from all the try-catch clauses is done differently and this assumption is not satisfied.

To fix the problem either `BMC::visit(TryStatement)` or `SMTEncoder::mergeVariables` needs to be changed.

This PR proposes the second way. Since the function is getting the information about the indices of **all** variables in the symbolic state for both the true and false branch, the `touched` variables are actually not needed. We can simply update only those variables present in both branches but with different indices. The rest of the variables do not need to be updated.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.h [hunk 1]
```diff
@@ -261,7 +261,7 @@ class SMTEncoder: public ASTConstVisitor
 	void expressionToTupleAssignment(std::vector<std::shared_ptr<VariableDeclaration>> const& _variables, Expression const& _rhs);
 
 	/// Maps a variable to an SSA index.
-	using VariableIndices = std::unordered_map<VariableDeclaration const*, int>;
+	using VariableIndices = std::unordered_map<VariableDeclaration const*, unsigned int>;
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.h]:
```suggestion
	using VariableIndices = std::unordered_map<VariableDeclaration const*, unsigned>;
```

File: libsolidity/formal/BMC.cpp [hunk 2]
```diff
@@ -258,8 +254,7 @@ bool BMC::visit(Conditional const& _op)
 bool BMC::visit(WhileStatement const& _node)
 {
 	auto indicesBeforeLoop = copyVariableIndices();
-	auto touchedVars = touchedVariables(_node);
-	m_context.resetVariables(touchedVars);
+	m_context.resetVariables(touchedVariables(_node));
```
Comment (leonardoalt) [inline libsolidity/formal/BMC.cpp:257]: Do we need `touchedVariables(_node)` here or is there another way, maybe using `visitBranch` on the loop body? I'm wondering if by getting rid of `touchedVariables` we could also get rid of `VariableUsage` entirely.

Comment (blishko) [reply libsolidity/formal/BMC.cpp:257]: I don't know. Do you remember why these variables need to be reset?

Comment (blishko) [reply libsolidity/formal/BMC.cpp:257]: I don't see a way around this at the moment. To me it makes sense that you reset the touched variables, to analyze the loop as if it could be any iteration.

File: libsolidity/formal/SMTEncoder.h (hunk 1 above)
Comment (blishko) [reply libsolidity/formal/SMTEncoder.h]: Fixed.

**Comment by blishko** [comment]
@leonardoalt , I have rebased this PR. Do you have any additional comments? Do you agree with this solution?

File: libsolidity/formal/SMTEncoder.cpp [hunk 3]
```diff
@@ -2346,38 +2344,20 @@ Type const* SMTEncoder::typeWithoutPointer(Type const* _type)
...
-		)
-			sortedVars.insert(var.first);
-	}
-
-	for (auto const* decl: sortedVars)
-	{
-		solAssert(_indicesEndTrue.count(decl) && _indicesEndFalse.count(decl), "");
-		auto trueIndex = static_cast<unsigned>(_indicesEndTrue.at(decl));
-		auto falseIndex = static_cast<unsigned>(_indicesEndFalse.at(decl));
-		solAssert(trueIndex != falseIndex, "");
```
Comment (leonardoalt) [inline libsolidity/formal/SMTEncoder.cpp:2375]: @blishko I guess in this solution we lose this check, that is, for every touched variable the indices must be different. I think it's not a problem, we can talk more tomorrow.

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:2375]: That is true.
I was considering also just doing small modification to the original code: basically the original assert at line 2372 is not true for the try-catch code. So it would be possible to just add the code to handle the situation where variable from one branch is not known in the other branch.

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp:2375]: I think it's ok to not have the check anymore. The new code is nicer and it's less code.

**Review by leonardoalt — APPROVED** [review]
