### PR TITLE
[SMTChecker] Fix ICE on array.pop nested inside 1-tuple

### LINKED ISSUE #11005: [SMTChecker] ICE because function call expr is not member access type
## Description

```
pragma experimental SMTChecker;
contract C{int[]data;function f()public{(data.pop)();}}
```

throws

https://github.com/ethereum/solidity/blob/2d48052ae50017bc41d8c85f1628b97352e73dcb/libsolidity/formal/SMTEncoder.cpp#L1615

### PR DESCRIPTION
**Pull request by blishko**
Fixes #11005.

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -444,6 +444,9 @@ void SMTEncoder::endVisit(Assignment const& _assignment)
 
 void SMTEncoder::endVisit(TupleExpression const& _tuple)
 {
+	if (_tuple.annotation().type->category() == Type::Category::Function)
+		return;
```
Comment (blishko) [inline libsolidity/formal/SMTEncoder.cpp:448]: This prevents SMTChecker from emitting warning "Internal error: Expression undefined for SMT solver".
This would happen if there is a function identifier nested in 1-tuple. Since we are not creating SMT representation for function identifiers (see `SMTEncoder::visit(MemberAccess const&)`), we should ignore these expressions here as well.

File: libsolidity/formal/CHC.cpp [hunk 2]
```diff
@@ -774,7 +774,7 @@ void CHC::makeArrayPopVerificationTarget(FunctionCall const& _arrayPop)
 	FunctionType const& funType = dynamic_cast<FunctionType const&>(*_arrayPop.expression().annotation().type);
 	solAssert(funType.kind() == FunctionType::Kind::ArrayPop, "");
 
-	auto memberAccess = dynamic_cast<MemberAccess const*>(&_arrayPop.expression());
+	auto memberAccess = dynamic_cast<MemberAccess const*>(cleanExpression(_arrayPop.expression()));
```
Comment (leonardoalt) [inline libsolidity/formal/CHC.cpp:777]: Nice

**Review by leonardoalt — APPROVED** [review]

File: libsolidity/formal/SMTEncoder.cpp [hunk 3]
```diff
@@ -1624,7 +1627,7 @@ void SMTEncoder::arrayPush(FunctionCall const& _funCall)
 
 void SMTEncoder::arrayPop(FunctionCall const& _funCall)
 {
-	auto memberAccess = dynamic_cast<MemberAccess const*>(&_funCall.expression());
+	auto memberAccess = dynamic_cast<MemberAccess const*>(cleanExpression(_funCall.expression()));
```
Comment (bshastry) [inline libsolidity/formal/SMTEncoder.cpp:1630]: Why is this change needed especially if we bail out early for tuple expressions now?

Comment (blishko) [reply libsolidity/formal/SMTEncoder.cpp:1630]: If I understand your question correctly, then my explanation would be the following.
The early bailout in tuple expressions is just for SMTChecker to *not* try to create an SMT representation for expressions corresponding to function identifiers inside 1-tuple, such as `(data.pop)` from example.
The change you refer to is needed to get to the `data.pop` from the FunctionCall expression `(data.pop)()`, and then to the array expression `data` and its SMT representation.
This would be the place where the code previously crashed, because `_funCall.expression()` would return the `Tuple` expression `(data.pop)` not a `MemberAccess` expression. We now use the `cleanExpression` method to strip away some syntactic structures (mainly these nested 1-tuples) to get to Expression that we expect.
