### PR TITLE
Better message for unexpected trailing commas in parameter lists

### LINKED ISSUE #2579: Improve error message for trailing commas in function signatures
Current message:
```
test.sol:4:31: Error: Expected type name
  function foo(uint a, uint b,) {}
                              ^
```
Improved message:
```
test.sol:4:31: Error: Unexpected trailing comma in function arguments
  function foo(uint a, uint b,) {}
                             ^
```

Also applies to return types:
```
test.sol:4:45: Error: Expected type name
  function foo(uint a, uint b) returns(uint,) {}
                                            ^
```

### PR DESCRIPTION
**Pull request by wadealexc**
Fixes #2579.

Improve error message for trailing commas in function signatures -

Trailing commas in function arguments, return parameters, event arguments, and modifier arguments now display the error message "Unexpected trailing comma in arguments"

### CODE REVIEW

File: libsolidity/parsing/Parser.cpp [hunk 1]
```diff
@@ -823,9 +823,15 @@ ASTPointer<ParameterList> Parser::parseParameterList(
 	VarDeclParserOptions options(_options);
 	options.allowEmptyName = true;
 	expectToken(Token::LParen);
+
 	if (!_allowEmpty || m_scanner->currentToken() != Token::RParen)
 	{
 		parameters.push_back(parseVariableDeclaration(options));
+		
+		if(m_scanner->currentToken() == Token::Comma && m_scanner->peekNextToken() == Token::RParen){
```
Comment (chriseth) [inline libsolidity/parsing/Parser.cpp]: It looks like this check only happens at the beginning of the parameter list, instead of the end.

Could you please add some tests to verify that?

Also, you accidentally added a binary file to this PR. Please remove it and rebase.

Comment (wadealexc) [reply libsolidity/parsing/Parser.cpp]: Yes, will do.

Comment (wadealexc) [reply libsolidity/parsing/Parser.cpp]: Right, fixed that. Will add boost tests and re-request

File: scripts/tests.sh [hunk 2]
```diff
@@ -55,7 +55,7 @@ fi
 # asynchronously. The shell will immediately return the return status of 0 for
 # true and continue as normal, either processing further commands in a script
 # or returning the cursor focus back to the user in a Linux terminal.
-../cpp-ethereum/build/eth/eth --test -d /tmp/test &
+$ETH_PATH --test -d /tmp/test &
```
Comment (axic) [inline scripts/tests.sh]: This seems to fix a change introduced by an earlier commit of yours. Can you please squash the two commits?

File: libsolidity/parsing/Parser.cpp [hunk 3]
```diff
@@ -823,13 +823,22 @@ ASTPointer<ParameterList> Parser::parseParameterList(
...
 	{
 		parameters.push_back(parseVariableDeclaration(options));
+
+		if(m_scanner->currentToken() == Token::Comma && m_scanner->peekNextToken() == Token::RParen){
+			fatalParserError("Unexpected trailing comma in arguments");
+		}
+
 		while (m_scanner->currentToken() != Token::RParen)
 		{
 			expectToken(Token::Comma);
```
Comment (axic) [inline libsolidity/parsing/Parser.cpp]: How about replacing those two checks with a single one before this `expectToken`? I think that should work.

**Comment by axic** [comment]
The tests look great and comprehensive!

File: libsolidity/parsing/Parser.cpp (hunk 3 above)
Comment (axic) [reply libsolidity/parsing/Parser.cpp]: Also please follow the coding style (space after if, before {, also no brackets needed if the body of a conditional is a single expression).

File: test/libsolidity/SolidityParser.cpp [hunk 4]
```diff
@@ -167,6 +167,90 @@ BOOST_AUTO_TEST_CASE(single_function_param)
...
 }
 
+BOOST_AUTO_TEST_CASE(single_function_param_trailing_comma)
+{
+	char const* text = R"(
+		contract test {
+			function(uint a,) {}
+		}
+	)";
+	CHECK_PARSE_ERROR(text, "Unexpected trailing comma in arguments");
```
Comment (axic) [inline test/libsolidity/SolidityParser.cpp]: I know this was the message suggested in the issue, but perhaps `Unexpected trailing comma in parameter list` is more universal given it is used on multiple places.

@chriseth @federicobond what do you think?

File: scripts/tests.sh (hunk 2 above)
Comment (wadealexc) [reply scripts/tests.sh]: Trying to squash all of my commits, accidentally created more. Could you point me in the right direction for cleaning this up? I haven't submitted a PR to a repository before so I'm new to squashing/merging/etc.

File: test/libsolidity/SolidityParser.cpp (hunk 4 above)
Comment (federicobond) [reply test/libsolidity/SolidityParser.cpp]: Sure, let's go ahead with parameter list.

**Comment by wadealexc** [comment]
Changed boost tests and error message to "Unexpected trailing comma in parameter list"

I've tried to squash my commits, but it keeps layering more on. I think as members of the repo you can squash when you merge. Otherwise, is there a different way for me to squash these?

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@wadeAlexC squashed and rebased in your branch, please do not update it, it should be ready to merge now.
