### PR TITLE
YulOpt: Extend StructuralSimplifier to work with all types

### LINKED ISSUE #6181: Strict assembly optimizer throws exception when _literal.kind != LiteralKind::Number for switch case statements containing string as well as integer literals
## Description

Here's the smallest example I could reduce this problem to

```
echo "{switch 0 case\"\"{} case 2{}}" | ./solc/solc --strict-assembly --optimize -
```

The exception thrown comes from here

https://github.com/ethereum/solidity/blob/eb5bde95b37b3d943644ce3c0ab20517fcafdc38/libyul/Utilities.cpp#L34

which is called from the structural simplifier phase of the optimizer here

https://github.com/ethereum/solidity/blob/eb5bde95b37b3d943644ce3c0ab20517fcafdc38/libyul/optimiser/StructuralSimplifier.cpp#L110-L121

Interestingly switch statement that contain a string literal in case statement do not pose a problem to the non-optimized code generation as shown by the CLI snippet below

```
$ $ echo "{switch 0 case\"\"{} case 2{}}" | ./solc/solc --strict-assembly -
                           
======= <stdin> (EVM) =======
    
Pretty printed source:
object "object" {
    code {                
        switch 0
        case "" {          
        }
        case 2 {
        }                  
    } 
}                         
      
     
Binary representation:
600060008114601357600281146017576018565b6018565b5b50
```

### Notes

- First case statement is actually an empty string literal `""`
- case statements with only string literal or only integer do not trigger the exception (see cli snippets below)
- at least two case statements needed to trigger issue

```
$ echo "{switch 0 case\"\"{}}" | ./solc/solc --strict-assembly --optimize -
======= <stdin> (EVM) =======

Pretty printed source:
object "object" {
    code {
    }
}


Binary representation:


Text representation:
No text representation found.
```

AND
```
$ echo "{switch 0 case 2{}}" | ./solc/solc --strict-assembly --optimize -

======= <stdin> (EVM) =======

Pretty printed source:
object "object" {
    code {
    }
}


Binary representation:


Text representation:
No text representation found.
```

## Environment

- Compiler version: develop `6c9961e04`
- Target EVM version (as per compiler settings): petersburg
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: n/a

### PR DESCRIPTION
**Pull request by Marenz**
fixes #6181

### CODE REVIEW

File: libyul/backends/evm/EVMCodeTransform.cpp [hunk 1]
```diff
@@ -396,20 +397,25 @@ void CodeTransform::operator()(Identifier const& _identifier)
...
-	{
-		if (_literal.value == "true"_yulstring)
-			m_assembly.appendConstant(u256(1));
-		else
-			m_assembly.appendConstant(u256(0));
-	}
-	else
+
+	u256 constant;
+	switch(_literal.kind)
```
Comment (ekpyron) [inline libyul/backends/evm/EVMCodeTransform.cpp]: This is exactly ``valueOfLiteral`` now, isn't it?

Comment (Marenz) [reply libyul/backends/evm/EVMCodeTransform.cpp]: The asserts types differ, but yes

Comment (ekpyron) [reply libyul/backends/evm/EVMCodeTransform.cpp]: I don't think the assert types matter too much here.

Comment (Marenz) [reply libyul/backends/evm/EVMCodeTransform.cpp]: I would prefer having it all in one function, too

Comment (chriseth) [reply libyul/backends/evm/EVMCodeTransform.cpp]: I think we should use the code, even if it might throw the wrong assertion exception types.

File: libyul/Utilities.h [hunk 2]
```diff
@@ -27,6 +27,9 @@ namespace yul
 {
 
 dev::u256 valueOfNumberLiteral(Literal const& _literal);
+dev::u256 valueOfStringLiteral(Literal const& _literal);
+dev::u256 valueOfBoolLiteral(Literal const& _literal);
+dev::u256 valueOfLiteral(Literal const& _literal);
```
Comment (chriseth) [inline libyul/Utilities.h:32]: Can you also use that in the yul interpreter?

File: libyul/Utilities.cpp [hunk 3]
```diff
@@ -32,11 +33,41 @@ using namespace yul;
...
 	assertThrow(_literal.kind == LiteralKind::Number, OptimizerException, "");
+
 	std::string const& literalString = _literal.value.str();
 	assertThrow(isValidDecimal(literalString) || isValidHex(literalString), OptimizerException, "");
 	return u256(literalString);
 }
 
+u256 yul::valueOfStringLiteral(Literal const& _literal)
+{
+	assertThrow(_literal.kind == LiteralKind::String, OptimizerException, "");
```
Comment (ekpyron) [inline libyul/Utilities.cpp]: Probably these assertions should be ``YulAssertion``s instead of ``OptimizerException``s anyways. (throughout the whole file)

**Comment by Marenz** [comment]
Updated

**Review by ekpyron — APPROVED** [review]
