### PR TITLE
Enforce data location.

### LINKED ISSUE #4382: Nested function parameter have wrong default data location
See https://github.com/ethereum/solidity/issues/4319#issuecomment-401149123
Solidity version: `0.4.24` / `develop`
Code:
```solidity
contract Test {
    struct Nested { uint y; }
    function h(function(Nested) external returns (uint)[]) external {}
}
```
Compiler output:
```
test.sol:3:25: Warning: Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.
    function h(function(Nested) external returns (uint)[]) external {}
                        ^----^
```
This is caused by `_variable.isExternalCallableParameter()` returning false and `_variable.isLocalVariable()` returning true (`_variable` = that problematic Nested). So ReferenceResolver treat that declaration as a local variable declaration.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #4382 
Fixes https://github.com/ethereum/solidity/issues/1815

### CODE REVIEW

File: libsolidity/analysis/NameAndTypeResolver.cpp [hunk 1]
```diff
@@ -297,7 +297,7 @@ bool NameAndTypeResolver::resolveNamesAndTypesInternal(ASTNode& _node, bool _res
 			if (!resolveNamesAndTypes(*node, false))
 			{
 				success = false;
-				break;
```
Comment (chriseth) [inline libsolidity/analysis/NameAndTypeResolver.cpp]: I'm not sure why this was here. I will run the whole test suite once the expectations are all updated, if it does not crash, I would propose to keep it like this.

**Comment by axic** [comment]
Needs rebasing.

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 2]
```diff
@@ -297,6 +303,9 @@ void ReferencesResolver::endVisit(VariableDeclaration const& _variable)
 	if (_variable.annotation().type)
 		return;
 
+	if (_variable.isConstant() && !_variable.isStateVariable())
+		m_errorReporter.declarationError(_variable.location(), "The \"constant\" keyword can only be used for state variables.");
```
Comment (axic) [inline libsolidity/analysis/ReferencesResolver.cpp:310]: Is this actually part of this PR?

Comment (chriseth) [reply libsolidity/analysis/ReferencesResolver.cpp:310]: Previously, the checks were much less restrictive, so the checks would pass here and then the type checker did the rest, but I actually think it is better to have strict tests here and then also move this check here, which I would say is the appropriate place.

File: libsolidity/analysis/TypeChecker.cpp [hunk 3]
```diff
@@ -708,8 +708,6 @@ bool TypeChecker::visit(VariableDeclaration const& _variable)
 		expectType(*_variable.value(), *varType);
 	if (_variable.isConstant())
 	{
-		if (!_variable.isStateVariable())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:719]: This is the place where the constant check was previously.

File: libsolidity/analysis/ReferencesResolver.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/analysis/ReferencesResolver.cpp:310]: Ok perhaps to summarize differently: Other ways to solve this would result in weird error messages.

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 4]
```diff
@@ -166,13 +172,13 @@ void ReferencesResolver::endVisit(FunctionTypeName const& _typeName)
...
 	default:
-		typeError(_typeName.location(), "Invalid visibility, can only be \"external\" or \"internal\".");
+		fatalTypeError(_typeName.location(), "Invalid visibility, can only be \"external\" or \"internal\".");
 		return;
 	}
 
 	if (_typeName.isPayable() && _typeName.visibility() != VariableDeclaration::Visibility::External)
 	{
-		typeError(_typeName.location(), "Only external function types can be payable.");
+		fatalTypeError(_typeName.location(), "Only external function types can be payable.");
```
Comment (chriseth) [inline libsolidity/analysis/ReferencesResolver.cpp:181]: These have to be fatal because otherwise the constructor of `FunctionType` will assert.

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 5]
```diff
@@ -306,127 +315,96 @@ void ReferencesResolver::endVisit(VariableDeclaration const& _variable)
...
-			else
+			switch (_location)
 			{
-				// force location of external function parameters (not return) to calldata
-				if (varLoc != Location::CallData && varLoc != Location::Default)
-					fatalTypeError(_variable.location(),
-						"Location has to be calldata for external functions "
-						"(remove the \"memory\" or \"storage\" keyword)."
-					);
+				case Location::Memory:
```
Comment (chriseth) [inline libsolidity/analysis/ReferencesResolver.cpp]: Could be pulled up onto the same line and unindented once.

File: libsolidity/analysis/ReferencesResolver.cpp [hunk 6]
```diff
@@ -454,3 +432,21 @@ void ReferencesResolver::fatalDeclarationError(SourceLocation const& _location,
 	m_errorOccurred = true;
 	m_errorReporter.fatalDeclarationError(_location, _description);
 }
+
+DataLocation ReferencesResolver::variableLocationToDataLocation(VariableDeclaration::Location _varLoc)
```
Comment (chriseth) [inline libsolidity/analysis/ReferencesResolver.cpp]: This is unused, should either be used above or removed.

File: libsolidity/ast/AST.cpp [hunk 7]
```diff
@@ -445,27 +450,109 @@ bool VariableDeclaration::isLocalOrReturn() const
...
+}
+
+set<VariableDeclaration::Location> VariableDeclaration::allowedDataLocations() const
+{
+	using Location = VariableDeclaration::Location;
+
+	if (!hasReferenceOrMappingType() || isStateVariable())
+		return set<Location>{ Location::Default };
+
+	if (isEventParameter())
```
Comment (chriseth) [inline libsolidity/ast/AST.cpp]: change to `else if`

File: libsolidity/ast/AST.cpp [hunk 8]
```diff
@@ -445,27 +450,109 @@ bool VariableDeclaration::isLocalOrReturn() const
...
+	else if (isCallableParameter())
+	{
+		set<Location> locations{ Location::Memory };
+		if (isInternalCallableParameter() || isLibraryFunctionParameter())
+			locations.insert(Location::Storage);
+		return locations;
+	}
+	else if (isLocalVariable())
+	{
+		// TODO where was this checked in the previous version?
```
Comment (chriseth) [inline libsolidity/ast/AST.cpp]: remove - it was in reference resolver visit.

File: test/libsolidity/ASTJSON/function_type_legacy.json [hunk 9]
```diff
@@ -100,7 +100,7 @@
 															{
 																"constant" : false,
 																"name" : "",
-																"scope" : 16,
```
Comment (chriseth) [inline test/libsolidity/ASTJSON/function_type_legacy.json:103]: Thanks for adding this to isoltest, @ekpyron ;)

File: test/libsolidity/syntaxTests/dataLocations/data_location_in_function_type.sol [hunk 10]
```diff
@@ -0,0 +1,11 @@
+library L {
+    struct Nested { uint y; }
+    // data location specifier in function signature should be optional even if there are multiple choices
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/dataLocations/data_location_in_function_type.sol]: Remove comment and also extract the working case.

File: test/libsolidity/syntaxTests/dataLocations/function_parameters_with_data_location_fine.sol [hunk 11]
```diff
@@ -0,0 +1,9 @@
+contract C {
+    // Warning for no data location provided can be silenced with storage or memory.
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/dataLocations/function_parameters_with_data_location_fine.sol]: remove

File: test/libsolidity/syntaxTests/dataLocations/function_return_parameters_with_data_location_fine.sol [hunk 12]
```diff
@@ -0,0 +1,7 @@
+contract C {
+    // Shows that the warning for no data location provided can be silenced with storage or memory.
```
Comment (chriseth) [inline test/libsolidity/syntaxTests/dataLocations/function_return_parameters_with_data_location_fine.sol]: remove

File: test/libsolidity/ASTJSON/function_type_legacy.json (hunk 9 above)
Comment (ekpyron) [reply test/libsolidity/ASTJSON/function_type_legacy.json:103]: Although it's still a bit hacky, e.g. it's adding the ``// ----`` delimiter above, although it's not needed for ASTJSON tests - but I'll fix all that in 0.5.1.

File: libsolidity/ast/AST.cpp [hunk 13]
```diff
@@ -418,21 +418,26 @@ bool VariableDeclaration::isLocalVariable() const
...
-		return false;
-	for (auto const& variable: callable->parameters())
-		if (variable.get() == this)
-			return true;
-	if (callable->returnParameterList())
-		for (auto const& variable: callable->returnParameterList()->parameters())
+	if (isReturnParameter())
+		return true;
+
+	std::vector<ASTPointer<VariableDeclaration>> const* parameters = nullptr;
```
Comment (ekpyron) [inline libsolidity/ast/AST.cpp]: No need for ``std::``.

File: libsolidity/ast/AST.cpp [hunk 14]
```diff
@@ -445,27 +450,105 @@ bool VariableDeclaration::isLocalOrReturn() const
 
 bool VariableDeclaration::isReturnParameter() const
 {
-	auto const* callable = dynamic_cast<CallableDeclaration const*>(scope());
-	if (!callable)
-		return false;
-	if (callable->returnParameterList())
-		for (auto const& variable: callable->returnParameterList()->parameters())
+	std::vector<ASTPointer<VariableDeclaration>> const* returnParameters = nullptr;
```
Comment (ekpyron) [inline libsolidity/ast/AST.cpp]: ``std::`` again

**Review by ekpyron — COMMENTED** [review]
Only had a very quick look so far, so for now only two very minor comments.

File: libsolidity/analysis/ReferencesResolver.cpp (hunk 2 above)
Comment (ekpyron) [reply libsolidity/analysis/ReferencesResolver.cpp:310]: Actually, to me it seems this check should even be moved up to the ``SyntaxChecker`` instead. Using the ``constant`` keyword in the wrong place feels like a syntax error to me.

File: test/libsolidity/syntaxTests/dataLocations/libraries/library_internal_function_return_parameters_no_data_location.sol [hunk 15]
```diff
@@ -0,0 +1,6 @@
+library L {
+    function g(uint[]) internal pure returns (uint[2]) {}
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/dataLocations/libraries/library_internal_function_return_parameters_no_data_location.sol]: Maybe better to remove the function argument here?

File: test/libsolidity/syntaxTests/dataLocations/libraries/library_private_function_parameters_no_data_location.sol [hunk 16]
```diff
@@ -0,0 +1,6 @@
+library L {
+    function h(uint[]) private pure returns (uint[]) {}
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/dataLocations/libraries/library_private_function_parameters_no_data_location.sol]: And remove the return value here?

File: test/libsolidity/syntaxTests/dataLocations/libraries/library_public_function_return_parameters_no_data_location.sol [hunk 17]
```diff
@@ -0,0 +1,6 @@
+library L {
+    function h(uint[]) public pure returns (uint[]) {}
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/dataLocations/libraries/library_public_function_return_parameters_no_data_location.sol]: Probably better to rename the test or split it into two (an return parameter and function parameter version; at the moment I don't see a function parameter version for this, but there is one for private functions).

File: test/libsolidity/syntaxTests/nameAndTypeResolution/224_string_bytes_conversion.sol [hunk 18]
```diff
@@ -1,17 +1,17 @@
...
     function m() internal { string(b); }
 }
 // ----
-// Warning: (47-99): Function state mutability can be restricted to pure
-// Warning: (104-163): Function state mutability can be restricted to pure
-// Warning: (168-210): Function state mutability can be restricted to view
-// Warning: (215-260): Function state mutability can be restricted to pure
-// Warning: (265-317): Function state mutability can be restricted to pure
-// Warning: (322-358): Function state mutability can be restricted to view
+// Warning: (47-108): Function state mutability can be restricted to pure
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/nameAndTypeResolution/224_string_bytes_conversion.sol]: Maybe we should get rid of these warnings altogether.

File: test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol [hunk 19]
```diff
@@ -2,4 +2,6 @@ contract Foo {
     function f(uint[] storage constant x, uint[] memory y) internal { }
 }
 // ----
-// TypeError: (30-55): Data location has to be "memory" (or unspecified) for constants.
+// DeclarationError: (30-55): The "constant" keyword can only be used for state variables.
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol:5]: This test looks a bit weird to me - what is it actually supposed to test?

File: test/libsolidity/syntaxTests/types/mapping/mapping_return_public_memory.sol [hunk 20]
```diff
@@ -0,0 +1,7 @@
+contract C {
+    function f() public pure returns (mapping(uint=>uint) memory m) {
+    }
+}
+// ----
+// TypeError: (51-79): Type is required to live outside storage.
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/types/mapping/mapping_return_public_memory.sol:6]: These expectations don't really match the intention of the test I guess - but it's probably good to keep the test - the expectations should properly align with/after #4798. [so nothing to be done here]

**Review by ekpyron — COMMENTED** [review]
This would probably have been easier to review, if it was split up into several commits/PRs, but I think it should be fine. I added some minor comments.

File: libsolidity/analysis/ReferencesResolver.cpp (hunk 2 above)
Comment (chriseth) [reply libsolidity/analysis/ReferencesResolver.cpp:310]: If you agree, I would still like to keep it here. While it can be checked earlier, I think it still "belongs" here, especially when we also add things like `mutable` and `immutable`.

File: test/libsolidity/syntaxTests/dataLocations/libraries/library_public_function_return_parameters_no_data_location.sol (hunk 17 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/dataLocations/libraries/library_public_function_return_parameters_no_data_location.sol]: I actually don't see much point in splitting, but it should probably be two different functions.

File: test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol (hunk 19 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol:5]: Will remove it.

Comment (chriseth) [reply test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol:5]: Hm, seems to be an old test. I think I will keep it for now.

Comment (chriseth) [reply test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol:5]: It is one of the few tests that combine 'constant' with params

File: test/libsolidity/syntaxTests/types/mapping/mapping_return_public_memory.sol (hunk 20 above)
Comment (chriseth) [reply test/libsolidity/syntaxTests/types/mapping/mapping_return_public_memory.sol:6]: Yes, should be in conflict with #4798 so good to keep.

**Comment by chriseth** [comment]
Updated.

File: libsolidity/analysis/ReferencesResolver.cpp (hunk 2 above)
Comment (ekpyron) [reply libsolidity/analysis/ReferencesResolver.cpp:310]: I'm fine with keeping it here.

**Comment by ekpyron** [comment]
Needs rebase.

File: test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol (hunk 19 above)
Comment (ekpyron) [reply test/libsolidity/syntaxTests/parsing/location_specifiers_for_params.sol:5]: We could rename it (not sure to what, though), but I'm fine with just keeping it as it is.

File: test/libsolidity/syntaxTests/dataLocations/data_location_in_function_type.sol [hunk 21]
```diff
@@ -0,0 +1,4 @@
+library L {
+    struct Nested { uint y; }
+    function c(function(Nested memory) external returns (uint)[] storage) external pure {}
```
Comment (ekpyron) [inline test/libsolidity/syntaxTests/dataLocations/data_location_in_function_type.sol:3]: If we feel paranoid, we could add tests for arguments of a function type, which in turn has arguments or return values of a function type that has arguments that require data locations, but judging from the code it should work fine.

**Review by ekpyron — DISMISSED** [review]
I haven't entirely convinced myself that the tests cover all possible cases, but in general I think this is fine now.

**Comment by chriseth** [comment]
Argh sorry, only rebased without re-adjusting the test expectations.

**Comment by chriseth** [comment]
I think I'll add some more tests with function parameters of mapping type and correct data location (but which is not storage).

**Comment by chriseth** [comment]
There should also be a test for a constant mapping.

**Comment by chriseth** [comment]
OK, hopefully final update. Will squash after review.

**Comment by ekpyron** [comment]
Emscripten build fails on travis.
Either we need ``#include <iterator>`` in ``StringUtils.h`` or the older emscripten is not fully C++11 compatible - ~~which~~ the latter would be another reason for #4486, it seems to work on circleci.

**Comment by chriseth** [comment]
Actually I think that is an argument against using the same version.

**Comment by ekpyron** [comment]
That depends on whether it's the lack of a header include or the lack of C++11 support... If it's the former, then yes, if it's the latter, then bumping the minimum required version makes more sense, I would say.

**Comment by chriseth** [comment]
Only read half-way into this, but the problem may be that `transformed` only gets us a single-pass iterator, while `std::next` requires a forward iterator.

**Comment by chriseth** [comment]
Not sure why it works in the other cases, but interestingly, since C++17, there is also an input iterator version of `std::next`...

**Comment by ekpyron** [comment]
That's probably right - and I guess newer compiler (resp. STL) versions are forward compatible with C++17, for which ``std::next`` only requires an input iterator. In that sense maybe it is an argument against #4486.

**Comment by chriseth** [comment]
Updated, let's see what travis will do with it.

**Comment by chriseth** [comment]
Build passed.

**Comment by ekpyron** [comment]
Why are the circleci linux tests passing and there is a test failure for one of the appveyor builds? Not related to this PR, but weird.

**Comment by ekpyron** [comment]
It's actually very weird - the respective test case ``syntaxTests/conversion/conversion_to_bytes.sol`` is not actually in this branch - not sure how it ended up in the appveyor test run, but in any case, the test *is* in develop and will fail after this PR, if the expectations are not updated, so this PR needs to be rebased again.

**Comment by chriseth** [comment]
Yeah, it sometimes happens that appveyor picks the wrong commit.

**Review by ekpyron — DISMISSED** [review]

**Comment by chriseth** [comment]
Another run...
