### PR TITLE
fixed ICError when creating EI for structs containing only mapping or arrays

### LINKED ISSUE #352: Crash when compiling structs with only subarrays.
Compiling the following:

```
contract BrokenArrays {
  struct Foo {
    //byte a;
    uint[15] subarray;
  }
  Foo public foo;
}
```

on the latest solc available from ethereum-dev crashes with the following.

```
Internal compiler error during compilation:
/build/cpp-ethereum-mgKuOj/cpp-ethereum-1.1.0-SNAPSHOT-154-20160113-8ce792f~trusty/solidity/libsolidity/codegen/ExpressionCompiler.cpp(139): Throw in function void dev::solidity::ExpressionCompiler::appendStateVariableAccessor(const dev::solidity::VariableDeclaration&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = 
```

Uncomment the `//byte a;` and it will compile.

### PR DESCRIPTION
**Pull request by LianaHus**
fixes https://github.com/ethereum/solidity/issues/352

### CODE REVIEW

File: libsolidity/analysis/TypeChecker.cpp [hunk 1]
```diff
@@ -292,17 +292,19 @@ void TypeChecker::checkContractExternalTypeClashes(ContractDefinition const& _co
...
+					);
 			}
 		for (VariableDeclaration const* v: contract->stateVariables())
 			if (v->isPartOfExternalInterface())
 			{
 				auto functionType = make_shared<FunctionType>(*v);
-				externalDeclarations[functionType->externalSignature()].push_back(
-					make_pair(v, functionType)
-				);
+				if (functionType->interfaceFunctionType())
```
Comment (chriseth) [inline libsolidity/analysis/TypeChecker.cpp:306]: Can you add a comment here and above stating that this can only happen if there was a type error before?

File: test/libsolidity/SolidityNameAndTypeResolution.cpp [hunk 2]
```diff
@@ -1003,6 +1003,18 @@ BOOST_AUTO_TEST_CASE(base_class_state_variable_accessor)
 	BOOST_CHECK(success(text));
 }
 
+BOOST_AUTO_TEST_CASE(struct_accessor_one_array_only)
+{
+	char const* sourceCode = R"(
+		contract test {
+
```
Comment (chriseth) [inline test/libsolidity/SolidityNameAndTypeResolution.cpp]: Surplus newline.
