### PR TITLE
[SMTChecker] Fix unary operator on lvalue tuple

### LINKED ISSUE #8817: [SMTChecker] ICE in SMTEncoder::mergeVariables because "trueIndex == falseIndex"
## Description

```
pragma experimental SMTChecker;
contract C {
  fixed x;
  address owner;
  modifier onlyOwner {
    if (msg.sender == owner) _;
  }
  function f() public onlyOwner { x--; }
}
```

throws

https://github.com/ethereum/solidity/blob/602b29cba782bae83769c1723e2b9cae2221d05d/libsolidity/formal/SMTEncoder.cpp#L1456

```
/Users/alex/Projects/solidity/libsolidity/formal/SMTEncoder.cpp(1481): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smt::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

## Environment

- Compiler version: latest develop

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/8817

### CODE REVIEW

File: libsolidity/formal/SMTEncoder.cpp [hunk 1]
```diff
@@ -463,21 +463,25 @@ void SMTEncoder::endVisit(UnaryOperation const& _op)
 
 	createExpr(_op);
 
+	auto const* subExpr = &_op.subExpression();
```
Comment (chriseth) [inline libsolidity/formal/SMTEncoder.cpp]: Why don't you turn this into a generic helper?

Comment (leonardoalt) [reply libsolidity/formal/SMTEncoder.cpp]: This uses the helper `innermostTuple`, but yea, I guess it could take a pointer instead of a ref which forces the type. This way a few ifs could be avoided.

**Comment by leonardoalt** [comment]
Updated

**Comment by chriseth** [comment]
Needs rebsae.

**Comment by chriseth** [comment]
Ah sorry, merged in the wrong order :(

**Review by mijovic — APPROVED** [review]
