### PR TITLE
[SMTChecker] Adapt division test for Z3 only

### LINKED ISSUE #7297: SMTChecker test failure: "SMTChecker/division": Multiple errors found
## Description

When I build `0.5.11` from https://github.com/ethereum/solidity/releases/download/v0.5.11/solidity_0.5.11.tar.gz, upon running the tests I get:

```
--- SKIPPING ALL SEMANTICS TESTS ---

Running 2879 test cases...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*******/build/source/test/libsolidity/AnalysisFramework.cpp(65): fatal error: in "SMTChecker/division": Multiple errors found: :9:17: Warning: Overflow (resulting value larger than 2**256 - 1) might happen here.
                                uint256 c = a * b;
                                            ^---^

:10:13: Warning: Division by zero happens here
                                require(c / a == b);
                                        ^---^
  for:
   = 0
  <result> = 0
  a = 0
  b = 0
  c = 0

Callstack:


********************************************

*** 1 failure is detected in the test module "SolidityTests"
```

## Environment

- Compiler version: the `0.5.11` release
- Target EVM version (as per compiler settings): -
- Framework/IDE (e.g. Truffle or Remix): -
- EVM execution environment / backend / blockchain client: -
- Operating system: linux

```
$ z3 --version
Z3 version 4.8.4 - 64 bit
```
## Steps to Reproduce

I am building `solc` with `nix` from [this version](https://github.com/livnev/nixpkgs/tree/solc-0.5.11) of `nixpkgs`. `0.5.10` builds and tests without problems. Could my `z3` version be responsible?

cc @leonardoalt

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes #7297 

Z3 4.8.5 times out in the overflow query which makes the test fail when not using CVC4 (which is able to solve it).
The test is adapted to allow for success (now that division by 0 does not happen anymore) or unknown solver result.

### CODE REVIEW

File: test/libsolidity/SMTChecker.cpp [hunk 1]
```diff
@@ -116,13 +116,15 @@ BOOST_AUTO_TEST_CASE(division)
 				if (a == 0) {
 					return 0;
 				}
+				// TODO remove when SMTChecker sees that this code is the `else` of the `return`.
+				require(a != 0);
```
Comment (erak) [inline test/libsolidity/SMTChecker.cpp:120]: Does the `require` prevent Z3 from trying to solve with `a == 0`?

**Review by erak — APPROVED** [review]

File: test/libsolidity/SMTChecker.cpp (hunk 1 above)
Comment (leonardoalt) [reply test/libsolidity/SMTChecker.cpp:120]: Yes. This should be the case because `a == 0` returns, but the SMTChecker does not see that `a != 0` should be true here (as an `else` of the `if` because of `return`), that's why I added it explicitly.
