### PR TITLE
Fixes doxygen style multiline comment parsing for files with CRLF

### LINKED ISSUE #7150: Natspec multiple "///" comments not interpreted
## Description

Check the documentation https://solidity.readthedocs.io/en/v0.5.10/natspec-format.html;
it shows to use multiple /// lines to document different values.
However only the last /// lines is incorporated in the compiled natspec data.
A workaround is using /** ... */ comments, then solc behaves as expected.

Please either change the documentation or the compiler; currently it is confusing.

## Environment
```xml
solc --version
solc, the solidity compiler commandline interface
Version: 0.5.10+commit.5a6ea5b1.Windows.msvc
```
Also noticed on Remix

## Steps to Reproduce
Use the following contract "comments.sol" as input:
```solidity
pragma solidity ^0.5.1;
contract Comments {    
    /// @author f1
    function f1() public {}

    /// @author f2
    /// @dev    dev2
    function f2() public {}

    /** @author f3
       @dev    dev3
    */   
    function f3() public {}
}
```
Then compile it using:
```xml
solc comments.sol --devdoc
```

Now you get the following output:
```json
======= comments.sol:Comments =======
Developer Documentation
{
  "methods" : 
  {
    "f1()" : 
    {
      "author" : "f1"
    },
    "f2()" : 
    {
      "details" : "dev2"
    },
    "f3()" : 
    {
      "author" : "f3\r",
      "details" : "dev3\r"
    }
  }
}
```

I would have expected the following output for function f2(). Notice the author line is missing above.
```json
    "f2()" : 
    {
      "author" : "f2\r",
      "details" : "dev2\r"
    }
```

### PR DESCRIPTION
**Pull request by christianparpart**
Fixes doxygen style multiline comment parsing for files with CRLF as line terminators.

Fixes #7150
Related: #4885

### Summary
So this PR is now treating CR, LF, and CRLF as newlines in Scanner.cpp. I added one test wrt multiline comments, and extended some others that only cared about CR and LF as line terminators.

### Old Behavior
Only CR and LF alone was treated as newline, hence, a CRLF have been two newlines.

### New Behavior
Along with CR and LF, also CRLF is treated as newline.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] Used meaningful commit messages
- [x] ~~README / documentation was extended, if necessary~~
- [x] Changelog entry (if change is visible to the user)

### CODE REVIEW

**Comment by chriseth** [comment]
Please add changelog.

**Comment by chriseth** [comment]
All places where `isLineTerminator` is called concern multi-line comments. This PR only changes one of these places. We should either change all of them or state that we only support `\n`-terminated files.

**Comment by christianparpart** [comment]
I'll look for the remaining places, too. I've been a little hasty it seems.

**Comment by ekpyron** [comment]
Maybe we should even try to fix all of those places **and still** state that we only support ``\n``-terminated files and CRLF might or might not work? Otherwise we should probably start specifically testing this...

**Comment by christianparpart** [comment]
> Maybe we should even try to fix all of those places **and still** state that we only support `\n`-terminated files and CRLF might or might not work? Otherwise we should probably start specifically testing this...

I have added *some* wrt doxygen style LF/CRLF handling, but also adapted *all* other occurrences of `isLineTerminator(m_char)` to properly detect LF/CRLF. I think I covered all places of LF handlings with this. If you find more @ekpyron, I'll adjust those, too.

File: liblangutil/Scanner.cpp [hunk 1]
```diff
@@ -343,13 +366,13 @@ Token Scanner::scanMultiLineDocComment()
 	bool endFound = false;
 	bool charsAdded = false;
 
-	while (isWhiteSpace(m_char) && !isLineTerminator(m_char))
+	while (isWhiteSpace(m_char) && !isLineTerminator())
```
Comment (erak) [inline liblangutil/Scanner.cpp]: Shall we do the same with `isWhiteSpace()` then?

File: liblangutil/Scanner.h [hunk 2]
```diff
@@ -219,6 +219,12 @@ class Scanner
 	Token skipSingleLineComment();
 	Token skipMultiLineComment();
 
+	/// Tests if current source position is LF or CRLF.
+	bool isLineTerminator() const;
+
+	/// Tries consuming CR, LF or CRLF line terminators and returns success or failure.
```
Comment (erak) [inline liblangutil/Scanner.h]:
```suggestion
	/// Tries to consume CR, LF or CRLF line terminators and returns success or failure.
```

File: Changelog.md [hunk 3]
```diff
@@ -21,6 +21,7 @@ Compiler Features:
 
 Bugfixes:
  * ABI decoder: Ensure that decoded arrays always point to distinct memory locations.
+ * Scanner: Fix parsing doxygen style multiline comments with triple slashes when file is encoded with CRLF instead of LF.
```
Comment (erak) [inline Changelog.md]:
```suggestion
 * Scanner: Fix doxygen-style parsing of multi-line comments with triple slashes when file is encoded with CRLF instead of LF.
```

File: liblangutil/Scanner.cpp (hunk 1 above)
Comment (erak) [reply liblangutil/Scanner.cpp]: Probably in another PR ;)

**Review by erak — COMMENTED** [review]
LGTM besides some minor comments.

File: liblangutil/Scanner.cpp (hunk 1 above)
Comment (christianparpart) [reply liblangutil/Scanner.cpp]: Right @erak. I'd prefer to stick with what this PR was about. OTOH, I also prefer free-functions, except that for isLineTerminator it needed more than just a byte, due to multi-byte line termination sequences. :)

File: Changelog.md [hunk 4]
```diff
@@ -22,6 +22,7 @@ Compiler Features:
 
 Bugfixes:
  * ABI decoder: Ensure that decoded arrays always point to distinct memory locations.
+ * Scanner: Fix doxygen-style parsing of multi-line comments with triple slashes when file is encoded with CRLF instead of LF.
```
Comment (ekpyron) [inline Changelog.md]:
```suggestion
 * Scanner: Fix parsing of doxygen-style multi-line comments with triple slashes when file is encoded with CRLF instead of LF.
```

As counterproposal to the last suggestion - not sure in what way the parsing is "doxygen-style" ;-).

File: liblangutil/Scanner.cpp [hunk 5]
```diff
@@ -280,6 +280,30 @@ Token Scanner::skipSingleLineComment()
...
+	if (m_char == '\n')
+	{
+		advance();
+		return true;
+	}
+
+	if (m_char == '\r')
+	{
+		advance();
+		if (!m_source->isPastEndOfInput(1) && m_source->get(0) == '\n')
```
Comment (ekpyron) [inline liblangutil/Scanner.cpp]: Hm... what happens if there is no ``\n`` after the ``\r``? How do we want do deal with that? Is it OK to just treat a single ``\r`` as a regular line break (that's what's happening now, right?)?

File: test/libsolidity/SolidityScanner.cpp [hunk 6]
```diff
@@ -622,9 +638,9 @@ BOOST_AUTO_TEST_CASE(irregular_line_breaks_in_single_line_doc_comment)
 
 BOOST_AUTO_TEST_CASE(regular_line_breaks_in_strings)
 {
-	for (auto const& nl: {"\n", "\r"})
+	for (auto const& nl: {"\r"s, "\n"s, "\r\n"s})
```
Comment (ekpyron) [inline test/libsolidity/SolidityScanner.cpp:641]: Ok, this suggests that we did and still do consider stray ``\r`` valid line breaks...

**Review by ekpyron — COMMENTED** [review]
Looks pretty good to me - not entirely sure about stray single ``\r``, but it's probably fine.

File: Changelog.md (hunk 4 above)
Comment (erak) [reply Changelog.md]: Ah, wait. "Doxygen-style" is even incorrent, isn't it? Shouldn't it say Natspec?

Comment (ekpyron) [reply Changelog.md]: Yeah, ``multi-line natspec comments`` is probably even better.

File: test/libsolidity/SolidityScanner.cpp (hunk 6 above)
Comment (erak) [reply test/libsolidity/SolidityScanner.cpp:641]: Still a bit undecided on allowing CR only as a valid line break. I'd try to follow what modern programming languages do, but they behave differently (starting point of my research was this Rust issue: https://github.com/rust-lang/rust/issues/7946). 

Maybe let's keep it for now and discuss again?

**Comment by erak** [comment]
Besides the Changelog suggestion, this looks good. Please also rebase.

File: test/libsolidity/SolidityScanner.cpp (hunk 6 above)
Comment (ekpyron) [reply test/libsolidity/SolidityScanner.cpp:641]: The safest thing might be to actually throw on single ``\r``, but yeah - we can discuss this separately.

Comment (erak) [reply test/libsolidity/SolidityScanner.cpp:641]: I found out that some languages treat stray`\r` as whitespace, which seem to simplify parsing on their side. Adopting this behaviour would also affect this PR positively ;)

File: liblangutil/Scanner.cpp (hunk 1 above)
Comment (chriseth) [inline liblangutil/Scanner.cpp]: This loop will terminate if there is a single `\r` not followed by `\n`. Is that on purpose?

Comment (chriseth) [reply liblangutil/Scanner.cpp]: Sorry: It will consume the `\r` that is not followed by `\n`.

File: liblangutil/Scanner.h [hunk 7]
```diff
@@ -219,6 +219,12 @@ class Scanner
 	Token skipSingleLineComment();
 	Token skipMultiLineComment();
 
+	/// Tests if current source position is LF or CRLF.
+	bool isLineTerminator() const;
```
Comment (chriseth) [inline liblangutil/Scanner.h]: I would propose to rename this to `atEndOfLine` and return true if `m_char` is either `\r` or `\n`, regardless of what follows.

Comment (erak) [reply liblangutil/Scanner.h]: Ok, then we can also remove https://github.com/ethereum/solidity/pull/7174/files#diff-0daa5e48651cfd58baca84f28cbd853bR299, can't we?

File: liblangutil/Scanner.cpp (hunk 5 above)
Comment (christianparpart) [reply liblangutil/Scanner.cpp]: we compared to VSCode as source of inspiration. How it is treated:
* `\n` is newline
* `\r` is newline
* `\r\n` is newline,
that is, if there's no following `\n` to the `\r` then it's still treated as newline.

Comment (chriseth) [reply liblangutil/Scanner.cpp]: Sounds good!

File: liblangutil/Scanner.h (hunk 7 above)
Comment (christianparpart) [reply liblangutil/Scanner.h]: @erak, no, because that function is actually meant to consume (if available) a newline, i.e. either CR, or LF, or CRLF.

The other function just tests if any line terminator is present, so with CR being present, it already knows it's going to be a newline, regardless of what follows. I guess this is what Chris. meant. :)

File: liblangutil/Scanner.cpp [hunk 8]
```diff
@@ -280,6 +280,36 @@ Token Scanner::skipSingleLineComment()
 	return Token::Whitespace;
 }
 
+bool Scanner::atEndOfLine() const
```
Comment (chriseth) [inline liblangutil/Scanner.cpp:283]: I have the impression that the implementation of this function can be simplified a little :)

File: liblangutil/Scanner.cpp [hunk 9]
```diff
@@ -280,6 +280,36 @@ Token Scanner::skipSingleLineComment()
...
+{
+	if (m_char == '\n')
+	{
+		advance();
+		return true;
+	}
+
+	if (m_char == '\r')
+	{
+		advance();
```
Comment (chriseth) [inline liblangutil/Scanner.cpp]:
```
{
  if (advance() && m_char == '\n')
    advance();
  return true;
}
```

File: test/libsolidity/SolidityScanner.cpp [hunk 10]
```diff
@@ -605,6 +605,22 @@ BOOST_AUTO_TEST_CASE(regular_line_breaks_in_single_line_doc_comment)
...
 
+BOOST_AUTO_TEST_CASE(regular_line_breaks_in_multiline_doc_comment)
+{
+	// Test CR, LF, CRLF as line valid terminators for code comments.
+	// Any accepted non-LF is being canonicalized to LF.
+	for (auto const& nl : {"\r"s, "\n"s, "\r\n"s})
+	{
+		Scanner scanner{CharStream{"/// Hello" + nl + "/// World" + nl + "ident", ""}};
+		auto const& lit = scanner.currentCommentLiteral();
+		BOOST_CHECK_EQUAL(lit, "Hello\n World");
```
Comment (chriseth) [inline test/libsolidity/SolidityScanner.cpp:616]: Did the old version also insert a space after the newline?

File: liblangutil/Scanner.cpp [hunk 11]
```diff
@@ -280,6 +280,36 @@ Token Scanner::skipSingleLineComment()
...
 
+bool Scanner::atEndOfLine() const
+{
+	if (m_char == '\n')
+		return true;
+
+	if (m_char == '\r')
+		return true;
+	return false;
+	//return m_char == '\n' || (m_char == '\r' && !m_source->isPastEndOfInput(2) && m_source->get(1) == '\n');
```
Comment (erak) [inline liblangutil/Scanner.cpp]: Left-over comment?

File: liblangutil/Scanner.cpp (hunk 8 above)
Comment (erak) [reply liblangutil/Scanner.cpp:283]: Me too ;)

File: test/libsolidity/SolidityScanner.cpp (hunk 10 above)
Comment (christianparpart) [reply test/libsolidity/SolidityScanner.cpp:616]: It looks like so, there was just no test for it before it seems.

**Review by erak — APPROVED** [review]
