### PR TITLE
[Sol2Yul] IR bug on Modifier with argument being a function return variable

### LINKED ISSUE #10947: IR bug syntaxTests/modifiers/function_modifier_invocation_parameters.sol
```
contract B {
    function f(uint8 a) mod1(a, true) mod2(r) pure public returns (bytes7 r) { }
    modifier mod1(uint a, bool b) { if (b) _; }
    modifier mod2(bytes7 a) { while (a == "1234567") _; }
}
```

```
: Internal compiler error during compilation:
: /solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp(2353): Throw in function void solidity::frontend::IRGeneratorForStatements::handleVariableReference(const solidity::frontend::VariableDeclaration&, const solidity::frontend::Expression&)
: Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
: std::exception::what: Invalid variable kind.
: [solidity::util::tag_comment*] = Invalid variable kind.
  
```

### PR DESCRIPTION
**Pull request by hrkrshnn**
Closes https://github.com/ethereum/solidity/issues/10947

### CODE REVIEW

File: libsolidity/codegen/ir/IRGenerator.cpp [hunk 1]
```diff
@@ -323,7 +323,7 @@ string IRGenerator::generateModifier(
 		t("functionName", functionName);
 		vector<string> retParamsIn;
 		for (auto const& varDecl: _function.returnParameters())
-			retParamsIn += IRVariable(*varDecl).stackSlots();
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGenerator.cpp:326]: Can you explain the problem here?

File: test/libsolidity/semanticTests/modifiers/function_return_parameter_complex.sol [hunk 2]
```diff
@@ -0,0 +1,26 @@
+// Test to see if the function return parameter, when forwarded to the modifier actually has value
+// zero.
+contract A {
+    modifier alwaysZeros(uint256 a, uint256 b) {
+        _;
+        require(a == 0, "a is not zero");
+        require(b == 0, "b is not zero");
```
Comment (bshastry) [inline test/libsolidity/semanticTests/modifiers/function_return_parameter_complex.sol:10]: Are the require statements executed? Doesn't control flow terminate with `_;`?

**Comment by bshastry** [comment]
Not sure if changelog entries are warranted for Sol->Yul issues yet, I guess not.

File: libsolidity/codegen/ir/IRGenerator.cpp (hunk 1 above)
Comment (hrkrshnn) [reply libsolidity/codegen/ir/IRGenerator.cpp:326]: I think the problem is that in line 366 of the same file, would end up calling `IRGeneratorForStatements::handleVariableReference`. And because the return variable was not in `m_context.m_localVariable`, it would throw.

Here is a stack trace:
```
#0  solidity::frontend::IRGeneratorForStatements::handleVariableReference (this=0x7fffffffc550, _variable=..., _referencingExpression=...)
    at /home/hari/s/r2/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:2353
#1  0x00000000008aa7df in solidity::frontend::IRGeneratorForStatements::endVisit (this=0x7fffffffc550, _identifier=...)
    at /home/hari/s/r2/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:2278
#2  0x000000000070e58a in solidity::frontend::Identifier::accept (this=0x1300ef0, _visitor=...) at /home/hari/s/r2/libsolidity/ast/AST_accept.h:938
#3  0x00000000008849a3 in solidity::frontend::IRGeneratorForStatements::evaluateExpression (this=0x7fffffffc550, _expression=..., _targetType=...)
    at /home/hari/s/r2/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:294
#4  0x0000000000868e2d in operator() (__closure=0x1370c40) at /home/hari/s/r2/libsolidity/codegen/ir/IRGenerator.cpp:369
#5  0x0000000000876729 in std::__invoke_impl<std::__cxx11::basic_string<char>, solidity::frontend::IRGenerator::generateModifier(const solidity::frontend::ModifierInvocation&, const solidity::frontend::FunctionDefinition&, const string&)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#6  0x0000000000875a15 in std::__invoke_r<std::__cxx11::basic_string<char>, solidity::frontend::IRGenerator::generateModifier(const solidity::frontend::ModifierInvocation&, const solidity::frontend::FunctionDefinition&, const string&)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/10/bits/invoke.h:115
#7  0x0000000000874dbc in std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >(), solidity::frontend::IRGenerator::generateModifier(const solidity::frontend::ModifierInvocation&, const solidity::frontend::FunctionDefinition&, const string&)::<lambda()> >::_M_invoke(const std::_Any_data &) (
    __functor=...) at /usr/include/c++/10/bits/std_function.h:292
#8  0x00000000007f1fce in std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const (this=0x7fffffffcc10)
    at /usr/include/c++/10/bits/std_function.h:622
#9  0x00000000007f1b1a in solidity::frontend::MultiUseYulFunctionCollector::createFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()> const&) (this=0x7fffffffd988, _name="modifier_mod2_6", _creator=...)
    at /home/hari/s/r2/libsolidity/codegen/MultiUseYulFunctionCollector.cpp:50
#10 0x00000000008696cf in solidity::frontend::IRGenerator::generateModifier (this=0x7fffffffd860, _modifierInvocation=..., _function=..., _nextFunction="fun_f_11_inner")
    at /home/hari/s/r2/libsolidity/codegen/ir/IRGenerator.cpp:386
```

File: test/libsolidity/semanticTests/modifiers/function_return_parameter_complex.sol (hunk 2 above)
Comment (hrkrshnn) [reply test/libsolidity/semanticTests/modifiers/function_return_parameter_complex.sol:10]: No. You can sort of imagine the modifiers as  replacing `_;` by `f_return_parameters := f_body_only(f_arguments)`. The rest of the statements would continue running. Even when the function has an early `return ;`. See `transitionNext` modifier in https://docs.soliditylang.org/en/v0.8.1/common-patterns.html?highlight=state%20machine#state-machine

File: libsolidity/codegen/ir/IRGenerator.cpp (hunk 1 above)
Comment (chriseth) [reply libsolidity/codegen/ir/IRGenerator.cpp:326]: It's not a problem that it is added multiple times?

Comment (chriseth) [reply libsolidity/codegen/ir/IRGenerator.cpp:326]: Ah ok, now I see. This might be fine :)

**Comment by chriseth** [comment]
Can you add another test where you access the same return variable in multiple modifier invocations (maybe even invocations of the same modifier)?

File: test/libsolidity/semanticTests/modifiers/function_return_parameter_complex.sol [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+        r3 = 64;
+    }
+
+    function shouldFail(uint i1) public alwaysZeros(i1, r + 20) returns (uint r) {
+        r = 0;
+    }
+
+    // The value of x would be 1 before calling this. It gets incremented four times in total during
+    // the modifier calls
+    function g() alwaysZeros(r, r) alwaysZeros(r, r) alwaysZeros(r + r, r - r) alwaysZeros(r * r, r & r) public returns (uint r) {
```
Comment (hrkrshnn) [inline test/libsolidity/semanticTests/modifiers/function_return_parameter_complex.sol:25]: Added a test where return variable is accessed multiple times.

**Review by chriseth — APPROVED** [review]

**Review by chriseth — APPROVED** [review]
