### PR TITLE
Fix wrong assert in overflow check

### LINKED ISSUE #7549: ICE on array index with ABIEncoderV2
## Description

Initally reported by @CHM1993.

The contract below :

```
pragma experimental ABIEncoderV2;
contract C {
    struct S { uint a; T[222222222222222222222222222] sub; }
    struct T { uint[] x; }
    function f() public returns (uint, S memory) {
    }
}
```
reports an internal compiler error:

```
Internal compiler error during compilation:
/build/solc/parts/solidity/src/libsolidity/ast/Types.cpp(1852): Throw in function virtual dev::u256 dev::solidity::ArrayType::memoryDataSize() const
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Array size does not fit u256.
[dev::tag_comment*] = Array size does not fit u256.
```

## Environment

- Compiler version: 0.5.11+
- Target EVM version (as per compiler settings): 0.5.11+commit.22be8592.Linux.g++
- Framework/IDE (e.g. Truffle or Remix): Remix (i found it from command line, while fuzzing the solc compiler)
- EVM execution environment / backend / blockchain client:
- Operating system: Ubuntu 18.04

## Steps to Reproduce

Run `./build/test/tools/solfuzzer`

### PR DESCRIPTION
**Pull request by Marenz**
fixes #7549

### CODE REVIEW

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -1849,7 +1849,7 @@ u256 ArrayType::memoryDataSize() const
 	solAssert(m_location == DataLocation::Memory, "");
 	solAssert(!isByteArray(), "");
 	bigint size = bigint(m_length) * m_baseType->memoryHeadSize();
-	solAssert(size <= numeric_limits<unsigned>::max(), "Array size does not fit u256.");
+	solAssert(size <= numeric_limits<u256>::max(), "Array size does not fit u256.");
```
Comment (bshastry) [inline libsolidity/ast/Types.cpp:1852]: This fixes #7549

File: libsolidity/analysis/TypeChecker.cpp [hunk 2]
```diff
@@ -2376,15 +2381,24 @@ bool TypeChecker::visit(Identifier const& _identifier)
...
 
+	if (!m_insideModifierInvocation)
+		if (ModifierType const* type = dynamic_cast<decltype(type)>(_identifier.annotation().type))
+		{
+			m_errorReporter.typeError(
+				_identifier.location(),
+				"Modifier can only be referenced in function signatures."
+			);
+		}
+
```
Comment (bshastry) [inline libsolidity/analysis/TypeChecker.cpp]: Fixes #7550

File: libsolidity/analysis/TypeChecker.h [hunk 3]
```diff
@@ -166,6 +166,9 @@ class TypeChecker: private ASTConstVisitor
 	/// Flag indicating whether we are currently inside a StructDefinition.
 	bool m_insideStruct = false;
 
+	/// Flag indicating whether we are currently inside the invocation of a modifier
+	bool m_insideModifierInvocation = false;
```
Comment (bshastry) [inline libsolidity/analysis/TypeChecker.h]: Should this be `m_insideFunctionSignature` instead because if I understood correctly what we care about is whether we are evaluating the function signature or not?

**Review by bshastry — COMMENTED** [review]
PR can be split into two (one each for #7549 and #7550 ). Minor comment on class member name.

File: libsolidity/analysis/TypeChecker.h (hunk 3 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.h]: Hmm I suppose, though I do explicitly set it only for the processing of the identifier part of the modifier and not the signature..

File: libsolidity/analysis/TypeChecker.cpp (hunk 2 above)
Comment (Marenz) [reply libsolidity/analysis/TypeChecker.cpp]: Ah, I forgot to reset my branch after doing my other PR

**Comment by Marenz** [comment]
Update: Removed wrong commits

**Review by bshastry — DISMISSED** [review]
Looks good to me. Could add a failing test case like so

```
contract C {
  // UINT256_MAX + 1
bool[115792089237316195423570985008687907853269984665640564039457584007913129639936] x;
}
```

that triggers the assertion now.

**Comment by Marenz** [comment]
Ah, I completely forgot to add the test that failed before, too

**Comment by Marenz** [comment]
@bshastry I don't think I can add such a test because the idea is that the assert should never fail ;)
If I can add such a test then my fix didn't work. 
What your test would do is trigger a compilation error at an earlier stage in the compiler and we already have tests like that :)

**Comment by Marenz** [comment]
I did however add the test that originally caused the ICE

**Comment by bshastry** [comment]
@Marenz ah okay, I misunderstood the underlying issue. The problem was in the assertion condition and not array size checking (which is presumably done elsewhere and is correct).

**Review by bshastry — DISMISSED** [review]
LGTM if test passes

**Comment by chriseth** [comment]
Please add a changelog entry.

**Comment by Marenz** [comment]
Added changelog

File: Changelog.md [hunk 4]
```diff
@@ -5,6 +5,8 @@ Language Features:
 
 Compiler Features:
  * Code Generator: Use SELFBALANCE for ``address(this).balance`` if using Istanbul EVM
+ * Code Generator: Fixed a faulty assert that would wrongly trigger for array
```
Comment (chriseth) [inline Changelog.md]: Should be under "bugfixes".

Comment (Marenz) [reply Changelog.md]: Wops. fixed.

File: Changelog.md [hunk 5]
```diff
@@ -5,10 +5,12 @@ Language Features:
 
 Compiler Features:
  * Code Generator: Use SELFBALANCE for ``address(this).balance`` if using Istanbul EVM
+   sizes exceeding unsigned integer
```
Comment (erak) [inline Changelog.md]: This also need to go into the bugfixes section ;)

**Review by erak — CHANGES_REQUESTED** [review]
Please see my tiny comment.

File: Changelog.md (hunk 5 above)
Comment (Marenz) [reply Changelog.md]: oh damn

**Review by chriseth — APPROVED** [review]
