### PR TITLE
Handle file prefix

### LINKED ISSUE #4884: Prefix file:// in standard json input not working
If files are given as urls in the standard json input, the prefix `file://` is not taken into account. Removing `file://` works fine.

Command line:
`solc --allow-paths /home/leonardo/somepath --standard-json < file.json`

File.json:
```
{
  "language": "Solidity",
  "sources":
  {
    "B.sol":
    {
      "urls": [ "file:///home/leonardo/somepath/B.sol" ]
    }
  },
  "settings":
  {
    "outputSelection": {
      "*": {
        "*": [ "evm.bytecode.linkReferences", "metadata" ]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by ssi91**
Attempting to fix https://github.com/ethereum/solidity/issues/4884
The solution is straight (may be even too straight).
Btw, it looks like the bug is deeper, because another cases of `"urls"` (`bzzr://` and `ipfs://` is mentioned [in the doc](https://solidity.readthedocs.io/en/v0.5.0/using-the-compiler.html#input-description)  ) are not handling there.

### CODE REVIEW

File: solc/CommandLineInterface.cpp [hunk 1]
```diff
@@ -944,7 +944,7 @@ bool CommandLineInterface::processInput()
 					"ReadFile callback used as callback kind " +
 					_kind
 				));
-			auto path = boost::filesystem::path(_path);
+			auto path = boost::filesystem::path(trimProtocol(_path));
```
Comment (chriseth) [inline solc/CommandLineInterface.cpp]: Can you do that here without defining a new function for it?

Comment (ssi91) [reply solc/CommandLineInterface.cpp]: @chriseth  sure. Done :)

File: solc/CommandLineInterface.cpp [hunk 2]
```diff
@@ -944,7 +944,10 @@ bool CommandLineInterface::processInput()
 					"ReadFile callback used as callback kind " +
 					_kind
 				));
-			auto path = boost::filesystem::path(_path);
+			string validPath = _path;
+			if (validPath.find("file://") == 0)
+				validPath.erase(0, 7);
+			auto path = boost::filesystem::path(validPath);
```
Comment (hrkrshnn) [inline solc/CommandLineInterface.cpp:959]: LGTM. But, commits needs to get squashed.

**Review by hrkrshnn — CHANGES_REQUESTED** [review]

File: Changelog.md [hunk 3]
```diff
@@ -8,6 +8,7 @@ Compiler Features:
 
 Bugfixes:
  * Type Checker: Disallow ``virtual`` and ``override`` for constructors.
+ * Standard Json Input: Error when in the `"urls"` field path has prefix `file://`
```
Comment (leonardoalt) [inline Changelog.md]:
```suggestion
 * Standard Json Input: Fix error when using prefix ``file://`` in the field ``urls``.
```

**Review by leonardoalt — CHANGES_REQUESTED** [review]
Could you also add some command line tests that use the standard JSON interface? You can find similar ones in `test/cmdlineTests/standard*`. To update the test expectations you can run our test ~~tool `isoltest`~~ script `./test/cmdlineTests.sh` which will do that automatically for you.
Please don't hesitate and ask questions if you run into problems when running the script :)

**Comment by chriseth** [comment]
you run the tests using `./test/cmdlineTests.sh` and not using `isoltest`

**Comment by leonardoalt** [comment]
Ah true, my bad! Fixed my comment

**Comment by leonardoalt** [comment]
Also please rebase

File: Changelog.md [hunk 4]
```diff
@@ -8,6 +8,7 @@ Compiler Features:
 
 Bugfixes:
  * Type Checker: Disallow ``virtual`` and ``override`` for constructors.
+ * Standard Json Input: Fix error when using prefix ``file://`` in the field ``urls``.
```
Comment (axic) [inline Changelog.md:18]: I wouldn't say this is a bugfix, nor it is a bugfix for "standard json". It is a feature for the CLI.

Comment (ssi91) [reply Changelog.md:18]: According to the https://github.com/ethereum/solidity/issues/4884 it's a bug. And I agree with it because if it don't work as documented it looks like a bug, IMHO

Comment (leonardoalt) [reply Changelog.md:18]: Well, it's either a bugfix in the code or in the documentation, since those were inconsistent. But I'm fine with either

**Review by chriseth — APPROVED** [review]
