### PR TITLE
[Sol->Yul] Enabling storage pointers to local vars in inline assembly.

### LINKED ISSUE #9618: [Sol->Yul] Map key access exception
## Description

```
contract C {
  uint[] x;
  fallback() external {
    uint[] storage y = x;
    assembly {
      pop(y.offset)
    }
  }
}
```

throws

https://github.com/ethereum/solidity/blob/5d670aaa1895945fe7b5bd1367eb257019d97c96/libsolidity/codegen/ir/IRGenerationContext.h#L103

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc --ir <test.sol>
```

### PR DESCRIPTION
**Pull request by mijovic**
Fixes #9618

### CODE REVIEW

**Comment by chriseth** [comment]
Does assignment to `.slot` in inline assembly work?

File: libsolidity/codegen/ir/IRGenerationContext.cpp [hunk 1]
```diff
@@ -170,6 +170,42 @@ void IRGenerationContext::internalFunctionAccessed(Expression const& _expression
 	}
 }
 
+pair<u256, unsigned> IRGenerationContext::storageLocationOfStateVariable(VariableDeclaration const& _varDecl) const
+{
+	solAssert(isStateVariable(_varDecl), "");
+	return m_stateVariables.at(&_varDecl);
+}
+
+pair<string, string> IRGenerationContext::storageLocationOfLocalVariable(VariableDeclaration const& _varDecl) const
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGenerationContext.cpp]: Wouldn't it be better to inline this function?

**Comment by chriseth** [comment]
Why is this only needed for inline assembly?

File: libsolidity/codegen/ir/IRGenerationContext.cpp [hunk 2]
```diff
@@ -170,6 +170,42 @@ void IRGenerationContext::internalFunctionAccessed(Expression const& _expression
...
+}
+
+pair<string, string> IRGenerationContext::storageLocationOfVariable(VariableDeclaration const& _varDecl) const
+{
+	if (isLocalVariable(_varDecl))
+	{
+		solAssert(
+			_varDecl.type()->dataStoredIn(DataLocation::Storage),
+			"Local variables with storage data location are only supported for slot/offset."
+		);
```
Comment (bshastry) [inline libsolidity/codegen/ir/IRGenerationContext.cpp]: Redundant assert since the called function contains this assertion

File: libsolidity/codegen/ir/IRGenerationContext.cpp [hunk 3]
```diff
@@ -170,6 +170,42 @@ void IRGenerationContext::internalFunctionAccessed(Expression const& _expression
...
+		return storageLocationOfLocalVariable(_varDecl);
+	}
+	else
+	{
+		solAssert(isStateVariable(_varDecl), "");
```
Comment (bshastry) [inline libsolidity/codegen/ir/IRGenerationContext.cpp]: Redundant assert

File: libsolidity/codegen/ir/IRGenerationContext.h [hunk 4]
```diff
@@ -98,10 +98,10 @@ class IRGenerationContext
...
 	void addStateVariable(VariableDeclaration const& _varDecl, u256 _storageOffset, unsigned _byteOffset);
 	bool isStateVariable(VariableDeclaration const& _varDecl) const { return m_stateVariables.count(&_varDecl); }
-	std::pair<u256, unsigned> storageLocationOfVariable(VariableDeclaration const& _varDecl) const
-	{
-		return m_stateVariables.at(&_varDecl);
-	}
+	std::pair<u256, unsigned> storageLocationOfStateVariable(VariableDeclaration const& _varDecl) const;
+
+	std::pair<std::string, std::string> storageLocationOfLocalVariable(VariableDeclaration const& _varDecl) const;
+	std::pair<std::string, std::string> storageLocationOfVariable(VariableDeclaration const& _varDecl) const;
```
Comment (bshastry) [inline libsolidity/codegen/ir/IRGenerationContext.h]: I'm not sure I understand the different signatures here i.e., `u256, unsigned` vs `string, string`

Comment (mijovic) [reply libsolidity/codegen/ir/IRGenerationContext.h]: StateVariables have numeric literals for `slot/offset` and LocalVariables have parts for `slot/offset` which are `IRVariables`.

There is an option to return string in both cases and have only one function. Does it sound better than?

File: libsolidity/codegen/ir/IRGenerationContext.cpp [hunk 5]
```diff
@@ -170,6 +170,42 @@ void IRGenerationContext::internalFunctionAccessed(Expression const& _expression
...
 
+pair<u256, unsigned> IRGenerationContext::storageLocationOfStateVariable(VariableDeclaration const& _varDecl) const
+{
+	solAssert(isStateVariable(_varDecl), "");
+	return m_stateVariables.at(&_varDecl);
+}
+
+pair<string, string> IRGenerationContext::storageLocationOfLocalVariable(VariableDeclaration const& _varDecl) const
+{
+	solAssert(isLocalVariable(_varDecl), "");
```
Comment (bshastry) [inline libsolidity/codegen/ir/IRGenerationContext.cpp]: This is also redundant if the function is only called from https://github.com/ethereum/solidity/pull/9652/files#diff-f841efc1479453da2e05b159a7f1da6bR199

File: libsolidity/codegen/ir/IRGenerationContext.cpp (hunk 1 above)
Comment (bshastry) [reply libsolidity/codegen/ir/IRGenerationContext.cpp]: :+1: for inlining

File: libsolidity/codegen/ir/IRGenerationContext.h (hunk 4 above)
Comment (bshastry) [reply libsolidity/codegen/ir/IRGenerationContext.h]: To me, inlining `storageLocationOfLocalVariable` into `storageLocationOfVariable` and having the latter return `string, string` and `storageLocationOfStateVariable` return `u256, unsigned` seems reasonable

**Comment by mijovic** [comment]
> Does assignment to `.slot` in inline assembly work?

It doesn't work, fails with somewhere in ASTCopier. I think it is something unrelated to this PR. We can open another issue for this.

**Comment by mijovic** [comment]
> Why is this only needed for inline assembly?

I am not sure if we can access `slot/offset` in any other way?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 6]
```diff
@@ -75,18 +75,14 @@ struct CopyTranslate: public yul::ASTCopier
...
-					_identifier.location,
-					yul::LiteralKind::Number,
-					yul::YulString{value},
-					{}
-				};
+				auto [slot, offset] = m_context.storageLocationOfVariable(*varDecl);
+
+				string const value = reference.isSlot ? slot : offset;
+
+				if (varDecl->isStateVariable() || (!reference.isSlot && varDecl->type()->stackItems().size() == 1))
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: What about checking if it starts with `[0-9]` (works for both decimals and hex)?

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 7]
```diff
@@ -75,18 +75,14 @@ struct CopyTranslate: public yul::ASTCopier
...
+					return yul::Literal{_identifier.location,yul::LiteralKind::Number,yul::YulString{value},{}};
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]:
```suggestion
					return yul::Literal{_identifier.location, yul::LiteralKind::Number, yul::YulString{value},{}};
```

**Review by chriseth — CHANGES_REQUESTED** [review]
The general parts of the ir generator should use IRVariable and`handleVariableReference` in conjunction with IRLvalue. Defining a `storageLocationOfVariable` function might suggest that this can also be used in the parts of the ir generator unrelated to inline assembly.

Wouldn't it be better to use the current code in inline assembly to handle the case of a state variable and just `IRVariable(_name).part("slot").name()` / `IRVariable(_name).part("offset").name()` for the local variable case?

**Comment by mijovic** [comment]
> The general parts of the ir generator should use IRVariable and`handleVariableReference` in conjunction with IRLvalue. Defining a `storageLocationOfVariable` function might suggest that this can also be used in the parts of the ir generator unrelated to inline assembly.
> 
> Wouldn't it be better to use the current code in inline assembly to handle the case of a state variable and just `IRVariable(_name).part("slot").name()` / `IRVariable(_name).part("offset").name()` for the local variable case?



> The general parts of the ir generator should use IRVariable and`handleVariableReference` in conjunction with IRLvalue. Defining a `storageLocationOfVariable` function might suggest that this can also be used in the parts of the ir generator unrelated to inline assembly.
> 
> Wouldn't it be better to use the current code in inline assembly to handle the case of a state variable and just `IRVariable(_name).part("slot").name()` / `IRVariable(_name).part("offset").name()` for the local variable case?

I changed PR to do like that, should look much better now.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 8]
```diff
@@ -75,18 +75,25 @@ struct CopyTranslate: public yul::ASTCopier
...
+						reference.isSlot ?
+							m_context.storageLocationOfStateVariable(*varDecl).first.str() :
+							to_string(m_context.storageLocationOfStateVariable(*varDecl).second);
+				else
+				{
+					solAssert(varDecl->isLocalVariable(), "");
+					if (reference.isSlot)
+						value = IRVariable{*varDecl}.part("slot").name();
+					else
+						value = varDecl->type()->stackItems().size() == 1 ? "0" : IRVariable{*varDecl}.part("offset").name();
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I think it is safer to check for `varDecl->type()->valueType()`.

Comment (mijovic) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I think there are cases when we have reference type when stack size is 1. For example struct types. Maybe I can create another helper function in `Type` that is more specific?

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I meant that only value types have an offset part. Non-value types always have an implicit zero offset.

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Another way to do it would be to check if `offset` exists.

Comment (chriseth) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: But better to add assertions both ways :)

Comment (mijovic) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I didn't know that all ref types have always only slot part. Will update now.

Comment (mijovic) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: I added some assertions in every part, for both slot and offset...
Hope it is not overkill now :)

Comment (mijovic) [reply libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: Actually, `.part` asserts if there is no particular stack slot.
So, I think your original suggestion is enough.

File: libsolidity/codegen/ir/IRGeneratorForStatements.cpp [hunk 9]
```diff
@@ -75,18 +75,25 @@ struct CopyTranslate: public yul::ASTCopier
...
+						reference.isSlot ?
+							m_context.storageLocationOfStateVariable(*varDecl).first.str() :
+							to_string(m_context.storageLocationOfStateVariable(*varDecl).second);
+				else
+				{
+					solAssert(varDecl->isLocalVariable(), "");
+					if (reference.isSlot)
+						value = IRVariable{*varDecl}.part("slot").name();
+					else
+						value = varDecl->type()->isValueType() ? IRVariable{*varDecl}.part("offset").name() : "0";
```
Comment (chriseth) [inline libsolidity/codegen/ir/IRGeneratorForStatements.cpp]: There is no assertion that we do not have an offset part for non-value types, is there? Can you please add one?

**Review by chriseth — APPROVED** [review]
