### PR TITLE
Fix dependency tracking for abstract contracts

### LINKED ISSUE #7627: `Compiled contract not found` error when not requesting output for inherited contract in Standard JSON
## Description

We have a [repository](https://github.com/poanetwork/posdao-contracts/tree/solc-bug) containing smart contracts and unit tests for them. When we compile the contracts with `truffle` and `solc` v0.5.11 or v0.5.12 (see [truffle's config](https://github.com/poanetwork/posdao-contracts/blob/solc-bug/truffle-config.js#L119-L128)), the `build` directory is created in repo's root directory as expected. After that, when we start unit tests,  we see the following error:

image

However, if we remove the `build` directory (`rm -rf build`) and then restart the tests with `npm run test`, they start successfully.

But if we do the same for `solc` v0.5.10 (or v0.5.9), that works fine and the contracts are compiled successfully during the tests even when the `build` directory is not removed.

## Environment

- Compiler version: 0.5.11 or 0.5.12
- Target EVM version (as per compiler settings): constantinople
- Framework/IDE (e.g. Truffle or Remix): truffle 5.0.43
- EVM execution environment / backend / blockchain client: ganache-cli 6.6.0
- Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

To see the error, perform the next steps:

```bash
$ git clone -b solc-bug https://github.com/poanetwork/posdao-contracts
$ cd posdao-contracts
$ npm i
$ npm run compile
$ npm run test
```

To successfully start the same tests with `solc 0.5.10`, perform the next steps:

```bash
$ git clone -b solc-bug https://github.com/poanetwork/posdao-contracts
$ cd posdao-contracts
$ git checkout 3581cf3730f53848572104d95c465bb237d3936e
$ npm i
$ npm run compile
$ npm run test
```

### PR DESCRIPTION
**Pull request by Marenz**
fixes #7627

### CODE REVIEW

File: libsolidity/interface/CompilerStack.h [hunk 1]
```diff
@@ -454,6 +454,7 @@ class CompilerStack: boost::noncopyable
 	langutil::EVMVersion m_evmVersion;
 	smtutil::SMTSolverChoice m_enabledSMTSolvers;
 	std::map<std::string, std::set<std::string>> m_requestedContractNames;
+	std::map<ContractDefinition const*, std::string const> m_otherYulSources;
```
Comment (ekpyron) [inline libsolidity/interface/CompilerStack.h]: I did say "member" first, but tried to correct myself to "or passed down" :-).
I think it would be better to only keep it during ``generateIR``, just like the second argument for ``compileContract``.
Otherwise, we'd probably need to clear this in ``reset()`` and think about whether it's valid to keep it otherwise - I think passing it down as an argument is less of a headache (that's fine for ``compileContract``, so it should be fine here, without having to worry about further stuff).

**Review by ekpyron — CHANGES_REQUESTED** [review]

File: test/libsolidity/StandardCompiler.cpp [hunk 2]
```diff
@@ -1505,6 +1505,47 @@ BOOST_AUTO_TEST_CASE(stopAfter_ast_output)
 	BOOST_CHECK(result["sources"]["a.sol"]["ast"].isObject());
 }
 
+BOOST_AUTO_TEST_CASE(dependency_tracking_of_abstract_contract)
```
Comment (ekpyron) [inline test/libsolidity/StandardCompiler.cpp:1508]: Can't this be a commandline test, i.e. see ``test/cmdlineTests/standard_yul_multiple_files`` for example.
But I may be missing a reason for not doing that...

Comment (ekpyron) [reply test/libsolidity/StandardCompiler.cpp:1508]: Well, hm - the IR output may be a bit fragile... I'm not sure...

**Review by ekpyron — DISMISSED** [review]
If the test was intentionally not extracted as command line test, then this is fine - and maybe it is indeed better not to have the full IR output in a test expectation there.

File: Changelog.md [hunk 3]
```diff
@@ -11,6 +11,7 @@ Compiler Features:
 
 
 Bugfixes:
+ * Code generator: Fix missing dependency tracking for abstract contracts.
```
Comment (chriseth) [inline Changelog.md]: Is this a IR-only change?

File: libsolidity/interface/CompilerStack.cpp [hunk 4]
```diff
@@ -526,7 +528,7 @@ bool CompilerStack::compile(State _stopAfter)
 						if (m_generateEvmBytecode)
 							compileContract(*contract, otherCompilers);
 						if (m_generateIR || m_generateEwasm)
-							generateIR(*contract);
+							generateIR(*contract, otherYulSources);
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp]: Can you avoid passing by non-const reference?

Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp]: No, in this case the non-constness is the whole reason for the parameter. The functions receiving it modify it and the caller uses the result.

**Comment by chriseth** [comment]
Is the problem that we do not recurse into `_contract.annotation().contractDependencies`? Would computing the transitive closure on that graph as a first step help?

File: Changelog.md (hunk 3 above)
Comment (Marenz) [reply Changelog.md]: Nope, it's also for normal output.

**Comment by Marenz** [comment]
> Is the problem that we do not recurse into _contract.annotation().contractDependencies? Would computing the transitive closure on that graph as a first step help?

In way yes that's the problem. The function `compileContract` and `generateIR` didn't check the dependencies for abstract contracts and instead returned early. I don't know if what you described would help.. It seems to me my fix is a simple solution to the problem..

File: libsolidity/interface/CompilerStack.cpp (hunk 4 above)
Comment (chriseth) [reply libsolidity/interface/CompilerStack.cpp]: Isn't the information already available in `m_contracts`? Also I think that `IRGenerator::generate` only picks the sources from `_otherYulSources` that it really needs, so passing all of the sources from `m_contracts` to ``IRGenerator::generate` should work, shouldn't it?

**Comment by Marenz** [comment]
ah, you mean recursing.. yeah that would help I think

**Comment by ekpyron** [comment]
> Is the problem that we do not recurse into `_contract.annotation().contractDependencies`? Would computing the transitive closure on that graph as a first step help?

Yeah, I also thought about it - making ``contractDependencies`` recursive (or computing the transitive closure from it) would also solve this issue and we would get rid of passing these maps around as function arguments.
DFS on it should do it...

File: Changelog.md (hunk 3 above)
Comment (ekpyron) [reply Changelog.md]: It's both IR and old codegen, same issue.

**Comment by Marenz** [comment]
I would merge this in any case, we can still make it better.. I can create an extra issue for that...

File: libsolidity/interface/CompilerStack.cpp [hunk 5]
```diff
@@ -1212,30 +1218,31 @@ void CompilerStack::compileContract(
...
 	string dependenciesSource;
 	for (auto const* dependency: _contract.annotation().contractDependencies)
 	{
-		generateIR(*dependency);
-		otherYulSources.emplace(dependency, m_contracts.at(dependency->fullyQualifiedName()).yulIR);
+		generateIR(*dependency, _otherYulSources);
+		_otherYulSources.emplace(dependency, m_contracts.at(dependency->fullyQualifiedName()).yulIR);
 	}
 
+	if (!_contract.canBeDeployed())
```
Comment (chriseth) [inline libsolidity/interface/CompilerStack.cpp:1243]: If you want to merge this quickly, can you create a PR that only has this change here? I would really try to avoid adding the other complication.

Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp:1243]: Well, doing this alone doesn't really fixes anything..

Comment (Marenz) [reply libsolidity/interface/CompilerStack.cpp:1243]: However, I pushed a version here now that only fixes the non-yul parts.

File: libsolidity/interface/CompilerStack.cpp [hunk 6]
```diff
@@ -1218,21 +1223,20 @@ void CompilerStack::generateIR(ContractDefinition const& _contract)
...
 	for (auto const* dependency: _contract.annotation().contractDependencies)
-	{
 		generateIR(*dependency);
-		otherYulSources.emplace(dependency, m_contracts.at(dependency->fullyQualifiedName()).yulIR);
-	}
+
+	if (!_contract.canBeDeployed())
+		return;
+
+	map<ContractDefinition const*, string const> otherYulSources;
```
Comment (ekpyron) [inline libsolidity/interface/CompilerStack.cpp]: If one really wants to be nit-pickey about this, then this should actually be a
```suggestion
	map<ContractDefinition const*, string_view const> otherYulSources;
```
:-)...
Not much point in copying them around twice...

Comment (ekpyron) [reply libsolidity/interface/CompilerStack.cpp]: (i.e. and also passed as such to ``IRGenerator``, changing the argument type for ``run`` and ``generate`` there)

**Comment by chriseth** [comment]
Looks good, but please add a test that shows that only the IRs of contracts that are really needed are included. Maybe something like
```
contract A {}
contract B {}
contract C {
  constructor() { new B(); }
}
contract D {}
```

and check that the runtime code of `C` does not contain any other contracts and that only `B` is included in the creation code.

File: test/libsolidity/StandardCompiler.cpp [hunk 7]
```diff
@@ -1505,6 +1505,96 @@ BOOST_AUTO_TEST_CASE(stopAfter_ast_output)
...
+	BOOST_REQUIRE(result["contracts"]["A.sol"].isObject());
+	BOOST_REQUIRE(result["contracts"]["A.sol"].size() == 1);
+	BOOST_REQUIRE(result["contracts"]["A.sol"]["C"].isObject());
+	BOOST_REQUIRE(result["contracts"]["A.sol"]["C"]["ir"].isString());
+
+	const string& irCode = result["contracts"]["A.sol"]["C"]["ir"].asString();
+
+	// Make sure C and B contracts are deployed
+	BOOST_REQUIRE(irCode.find("object \"C") == string::npos);
+	BOOST_REQUIRE(irCode.find("object \"B") == string::npos);
```
Comment (ekpyron) [inline test/libsolidity/StandardCompiler.cpp]:
```suggestion
	BOOST_REQUIRE(irCode.find("object \"C") != string::npos);
	BOOST_REQUIRE(irCode.find("object \"B") != string::npos);
```
? Or did I misunderstand something here?

Comment (chriseth) [reply test/libsolidity/StandardCompiler.cpp]: I think the objects are called `A.sol:C` and so on.

Comment (ekpyron) [reply test/libsolidity/StandardCompiler.cpp]: Ah right, I wasn't really looking at the stuff above this...

Comment (Marenz) [reply test/libsolidity/StandardCompiler.cpp]: @ekpyron you are completely right. And I remember typing `!=` and have no idea why it ended up like this. Good eye.

File: Changelog.md [hunk 8]
```diff
@@ -1,6 +1,9 @@
 ### 0.7.5 (unreleased)
 
 
+Bugfixes:
+ * Code generator: Fix missing dependency tracking for abstract contracts.
```
Comment (chriseth) [inline Changelog.md]:
```suggestion
 * Code generator: Fix missing creation dependency tracking for abstract contracts.
```

**Comment by chriseth** [comment]
Apart from the changelog wording it looks good!

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Does it fully fix the cited issue?

**Comment by Marenz** [comment]
> Does it fully fix the cited issue?

Yes, that and more.
