### PR TITLE
More clear error messages with converting (hex) string literals

### LINKED ISSUE #9866: String literals should use hex representation if not ASCII in error messages
```
Error: Explicit type conversion not allowed from "literal_string "4V"" to "bytes2".
  --> unsigned.sol:10:13:
   |
10 |      return bytes2(hex"123456");
   |             ^^^^^^^^^^^^^^^^^^^
```

The `hex"123456"` is displayed as "4V" which corresponds to `0x34 0x56`. The first character is not displayed as it is a control character.

`StringLiteralType::toString` should be changed to display hex string if there are non-ASCII characters in the literal. Perhaps we could also consider changing the "invalid UTF-8 literal" there to also just display as hex string, given the conversion error is displayed elsewhere.

### PR DESCRIPTION
**Pull request by axic**
Fixes #9866.
Depends on #9868.
Depends on #9870.

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `f88e8a1855e071c50f6074f20f93aa1c49d1f35b`:
```
Coding style error:
 libsolidity/ast/Types.cpp:1381: auto isPrintableASCII = [](const string& s)

```
Please check that your changes are working as intended.

File: libsolidity/ast/Types.cpp [hunk 1]
```diff
@@ -1378,12 +1378,24 @@ bool StringLiteralType::operator==(Type const& _other) const
 
 std::string StringLiteralType::toString(bool) const
 {
-	size_t invalidSequence;
+	auto isPrintableASCII = [](const string& s)
```
Comment (stackenbotten) [inline libsolidity/ast/Types.cpp:1381]: Coding style error

File: libsolidity/ast/Types.cpp [hunk 2]
```diff
@@ -1378,12 +1378,25 @@ bool StringLiteralType::operator==(Type const& _other) const
...
+	};
+
+	string ret = isPrintableASCII(m_value) ?
+		("literal_string \"" + m_value + "\"") :
+		("literal_string hex\"" + util::toHex(util::asBytes(m_value)) + "\"");
 
+	size_t invalidSequence;
 	if (!util::validateUTF8(m_value, invalidSequence))
-		return "literal_string (contains invalid UTF-8 sequence at position " + util::toString(invalidSequence) + ")";
+		ret += " (contains invalid UTF-8 sequence at position " + util::toString(invalidSequence) + ")";
```
Comment (axic) [inline libsolidity/ast/Types.cpp]: Still not happy having this, but this is the only error message indication we have.

File: libsolidity/ast/Types.cpp [hunk 3]
```diff
@@ -1378,12 +1378,25 @@ bool StringLiteralType::operator==(Type const& _other) const
 
 std::string StringLiteralType::toString(bool) const
 {
-	size_t invalidSequence;
+	auto isPrintableASCII = [](const string& s)
```
Comment (stackenbotten) [inline libsolidity/ast/Types.cpp]: Coding style error

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `f506700299887796e3eb8630d6965501a1b9bfb2`:
```
Coding style error:
 libsolidity/ast/Types.cpp:1381: auto isPrintableASCII = [](const string& s)

```
Please check that your changes are working as intended.

**Comment by mijovic** [comment]
> There was an error when running `chk_coding_style` for commit `f506700299887796e3eb8630d6965501a1b9bfb2`:
> ```
> Coding style error:
>  libsolidity/ast/Types.cpp:1381: auto isPrintableASCII = [](const string& s)
> 
> ```
> Please check that your changes are working as intended.

Should be:
auto isPrintableASCII = [](string const& s)

**Comment by axic** [comment]
Thanks @mijovic, the bot was super helpful telling what it wants.

**Comment by mijovic** [comment]
> Thanks @mijovic, the bot was super helpful telling what it wants.

It is better that just script fails than bot commenting. I hate him/her :)

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: Tried changing this and unfortunately there are 3 different places in the typechecker this would need to be added 😢

File: libsolidity/ast/Types.cpp [hunk 4]
```diff
@@ -1378,12 +1378,25 @@ bool StringLiteralType::operator==(Type const& _other) const
...
 std::string StringLiteralType::toString(bool) const
 {
-	size_t invalidSequence;
+	auto isPrintableASCII = [](string const& s)
+	{
+		for (auto c: s)
+		{
+			if (static_cast<unsigned>(c) <= 0x1f || static_cast<unsigned>(c) >= 0x7f)
+				return false;
+		}
```
Comment (mijovic) [inline libsolidity/ast/Types.cpp:1399]:
```suggestion
			if (static_cast<unsigned>(c) <= 0x1f || static_cast<unsigned>(c) >= 0x7f)
				return false;
```

**Review by mijovic — COMMENTED** [review]
Tests are failing

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (mijovic) [reply libsolidity/ast/Types.cpp]: I did review before reading this. You can ignore it for now

**Comment by axic** [comment]
> Tests are failing

I actually have another PR as a prerequisite which will allow me to remove the UTF-8 mess, and that will require a lot of test updates.

File: test/libsolidity/syntaxTests/string/invalid_utf8_sequence.sol [hunk 5]
```diff
@@ -2,5 +2,5 @@ contract C {
     string s = unicode"�";
 }
 // ----
-// SyntaxError 8452: (28-38): Invalid UTF-8 sequence found
-// TypeError 7407: (28-38): Type literal_string (contains invalid UTF-8 sequence at position 0) is not implicitly convertible to expected type string storage ref.
+// SyntaxError 8452: (28-38): Invalid UTF-8 sequence found at position 0
```
Comment (axic) [inline test/libsolidity/syntaxTests/string/invalid_utf8_sequence.sol]: This extra check is there for even no-op expressions like `unicode"À"` so I guess we have to keep it.

File: libsolidity/ast/Types.cpp (hunk 2 above)
Comment (axic) [reply libsolidity/ast/Types.cpp]: Got rid of this.

File: test/libsolidity/ASTJSON/unicode_legacy.json [hunk 6]
```diff
@@ -131,7 +131,7 @@
                         "isPure": true,
                         "lValueRequested": false,
                         "token": "unicodeString",
-                        "type": "literal_string \"Hello \ud83d\ude03\"",
+                        "type": "literal_string hex\"48656c6c6f20f09f9883\"",
```
Comment (axic) [inline test/libsolidity/ASTJSON/unicode_legacy.json:134]: I was wondering to actually return `literal_string unicode""`, `literal_string hex""`, or `literal_string ""` where appropriate, but not sure it is worth the effort.

File: libsolidity/ast/Types.cpp (hunk 4 above)
Comment (mijovic) [reply libsolidity/ast/Types.cpp:1399]: if you can apply this one, I think parenthesis are really not needed

Comment (axic) [reply libsolidity/ast/Types.cpp:1399]: I don't care, I think a while ago we preferred to always have braces around for loops if they had branching within, but obviously this case has no such risk.

**Review by mijovic — APPROVED** [review]

File: libsolidity/ast/Types.cpp (hunk 4 above)
Comment (chriseth) [reply libsolidity/ast/Types.cpp:1399]: No, we never had braces unless the compiler warned about it.

**Comment by axic** [comment]
@chriseth I was wondering if you had any changelog suggestions for the second two commits.

File: test/libsolidity/ASTJSON/unicode_legacy.json (hunk 6 above)
Comment (axic) [reply test/libsolidity/ASTJSON/unicode_legacy.json:134]: @chriseth and this ^^

Comment (chriseth) [reply test/libsolidity/ASTJSON/unicode_legacy.json:134]: not worth the effort
